Insert into COMUNI (CODICECOMUNE,COMUNE,SIGLAPROVINCIA,PROVINCIA,REGIONE,CAP,CF,CODICEISTAT,CODICEISTATREGIONE,CODICESTATOESTERO) values ('M392','LATERINA PERGINE VALDARNO','AR','AREZZO','TOSCANA','52020','M392','051042','09',null);

Insert into COMUNI (CODICECOMUNE,COMUNE,SIGLAPROVINCIA,PROVINCIA,REGIONE,CAP,CF,CODICEISTAT,CODICEISTATREGIONE,CODICESTATOESTERO) values ('M391','RIO','LI','LIVORNO','TOSCANA','57039','M391','049021','09',null);

DELETE FROM CLPERMMENU where FKIDMENU = 1017;
DELETE FROM CLMENU_JAVA where ID=1017;

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_PROTOINF', 'BASEPATH_FILES_PROTO', 'Indicare il percorso base visibile dalla macchina di protocollo relativamente ai files inviati dal backoffice.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_PROTOINF', 'BASEPATH_FILES_LOCAL', 'Indicare il percorso base visibile dalla macchina di backoffice relativamente ai files inviati dal backoffice');

Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('COMPORTAMENTI_ISTANZE','GENERA_PRATICA_SUAP','Gestisce l''attivazione dell''integrazione SUAP/Edilizia mediante canale di protocollazione. Valori attesi ''S'' funzionalità attiva, ''N o null'' funzionalità non attiva');
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('COMPORTAMENTI_ISTANZE','GENERA_PRATICA_SUAP_URL','Url del servizio genera pratica SUAP');
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('COMPORTAMENTI_ISTANZE','GENERA_PRATICA_SUAP_VALIDA','Valori attesi S o N (NULL) indica se validare o meno lo schema prima di creare il file xml che rappresenta la pratica');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('STC', 'USA_NUMISTANZA_AS_NODI', 'Rappresenta la lista degli idnodi ( separata da virgola ) per i quali attivare il comportamento di usare il numero istanza del sistema mittente (vedi parametro USA_NUMISTANZA_ALTRO_SISTEMA). I valori vanno specificati separati da virgola es: 410,420,430.');


Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('PROTOCOLLO_PROTOINF','CODAMM_DESTINATARIO','In questo campo va necessariamente indicato il codice dell''amministrazione del backoffice alla quale saranno inviati i dati come destinatario fisso dei protocolli in partenza. In particolare saranno inviati i dati relativi a: DENOMINAZIONE, PEC, INDIRIZZO, UFFICIO (Codice UO). Da notare che solo la denominazione è obbligatoria.');
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('PROTOCOLLO_PROTOINF','IGNORA_CLASSIFICA','Se valorizzato a 1 ignorerà qualsiasi valore proveniente dalla classifica, il tutto in quanto tale voce non è obbligatoria nel sistema di protocollo mentre lo è in VBG.');
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('PROTOCOLLO_PROTOINF','NETWORK_DOMAIN','Indicare la credenziale di dominio per l''accesso in modalità share di rete utile per il passaggio dei file nel percorso indicato nel parametro BASEPATH_FILES_LOCAL');
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('PROTOCOLLO_PROTOINF','NETWORK_PASSWORD','Indicare la credenziale di password per l''accesso in modalità share di rete utile per il passaggio dei file nel percorso indicato nel parametro BASEPATH_FILES_LOCAL');
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('PROTOCOLLO_PROTOINF','NETWORK_USERNAME','Indicare la credenziale di username per l''accesso in modalità share di rete utile per il passaggio dei file nel percorso indicato nel parametro BASEPATH_FILES_LOCAL');
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('PROTOCOLLO_PROTOINF','PROPRIETARIO','Indicare il codice del proprietario del protocollo esposto su PROTOINF, il valore è da recuperare dalla tabella PI_PERSONA campo PI_PE_PERSONA');
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('PROTOCOLLO_PROTOINF','PROTOCOLLATORE','Indicare il codice del protocollatore esposto su PROTOINF, il valore è da recuperare nella tabella PI_PERSONA campo PI_PE_DIPENDENTE.');

Insert into CLMENU_JAVA (ID,DESCRIZIONE,PAGINA,MENULINK,SOFTWARE,JSP,LAYOUTTESTI,VERTICALIZZAZIONE,SOFTWAREESCLUSI,LINK_STANDARD,TIPO_FUNZIONALITA,MENULINK_V2) values ('1037','Archiviazione documentale','archiviazioni/list.htm?software=SOFTWARE','782','*','JAVA',null,null,'PR,FI,AB','archiviazioni/list.htm','E','707');

Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('SIT_LDP','GESTISCI_MOD_DEL_AREE','Parametro che indica se mostrare le funzionalita'' di gestione/cancellazione aree. Valori possibili S/N defatult N');

INSERT INTO VERTICALIZZAZIONIBASE (MODULO, DESCRIZIONE) VALUES ('PROTOCOLLO_CIVILIA', 'Protocollo con servizi di tipo RESTsviluppato da Dedagroup, il web service necessita di autenticazione di tipo OAUTH');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_CIVILIA', 'URL_OAUTH', 'Endpoint relativo all''autenticazione oauth 2.0 da utilizzare per ottenere il token da usare poi per le chiamate al web service rest.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_CIVILIA', 'URL_WS', 'Endpoint del web service rest');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_CIVILIA', 'CLIENT_ID', 'Parametro client_id da passare all''endpoint oauth 2.0');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_CIVILIA', 'SECRET', 'Parametro secret da passare all''endpoint oauth 2.0');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_CIVILIA', 'CODICEAOO', 'Indicare in questo parametro il valore relativo al codice AOO del protocollo, che sarà poi inserito nel parametro IdCodiceAOO della richieta json.');

insert into MAPOGGETTI (NOMETABELLA,NOMECAMPO) values('ARCHIVIAZIONI_OGGETTI','CODICEOGGETTO');
insert into MAPOGGETTI (NOMETABELLA,NOMECAMPO) values('FO_ARJ_DOMANDE','CODICEOGGETTO_RICEVUTA');
insert into MAPOGGETTI (NOMETABELLA,NOMECAMPO) values('ISTANZERICHIEDENTI','CODICEOGGETTO_PROCURA');
insert into MAPOGGETTI (NOMETABELLA,NOMECAMPO) values('RESPONSABILI','FK_OGGETTO_IMMAGINE');

insert into MAPOGGETTI (NOMETABELLA,NOMECAMPO) values('MOVIMENTIMAILALLEGATI','CODICEOGGETTO');


INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_IRIDE', 'PROTO_OGGETTO_PEC', 'Parametro Si o No (valore 1 o altro), se valorizzato a 1 nell''oggetto della pec, inviata tramite la chiamata a ws PostaWeb, saranno visualizzati, in fondo all''oggetto stesso i dati di protocollo sotto forma di: Pr. Num. [NUMERO_PROTOCOLLO], Pr. Data [DATA_PROTOCOLLO]');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_IRIDE', 'PEC_INTEROP', 'Parametro Si o No (valore 1 o altro), se valorizzato a 1, l''invio della pec tramite ws PosteWeb, sarà interoperabile, sarà quindi inserito l''elemento <InvioInteroperabile> valorizzato a S, questo consente l''invio della segnatura xml.');


UPDATE VERTICALIZZAZIONIPARAMETRIBASE SET DESCRIZIONE = 'etichetta del numero protocollo (OBSOLETO)' WHERE modulo='APPLICA_LAYER_PROT_PDF' and PARAMETRO='ETICHETTA_NUM_PROT';
UPDATE VERTICALIZZAZIONIPARAMETRIBASE SET DESCRIZIONE = 'etichetta della data protocollo (OBSOLETO)' WHERE modulo='APPLICA_LAYER_PROT_PDF' and PARAMETRO='ETICHETTA_DATA_PROT';
UPDATE VERTICALIZZAZIONIPARAMETRIBASE SET DESCRIZIONE = 'nome del layer, verrà visualizzato nel pdf e dovrà essere unico (OBSOLETO)' WHERE modulo='APPLICA_LAYER_PROT_PDF' and PARAMETRO='NOME_LAYER';
UPDATE VERTICALIZZAZIONIPARAMETRIBASE SET DESCRIZIONE = 'Tipo di font da impostare al layer. Possibili font GILL_SANS_MT, TIMES_ROMAN, HELVETICA (NON GESTITO)' WHERE modulo='APPLICA_LAYER_PROT_PDF' and PARAMETRO='FONT_TYPE';
UPDATE VERTICALIZZAZIONIPARAMETRIBASE SET DESCRIZIONE = 'Dimensione font da impostare al layer (NON GESTITO)' WHERE modulo='APPLICA_LAYER_PROT_PDF' and PARAMETRO='FONT_SIZE';


INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('APPLICA_LAYER_PROT_PDF', 'DIM_RETTANGOLO_X', 'Dimensione x del rettangolo che racchiude l''annotazione');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('APPLICA_LAYER_PROT_PDF', 'DIM_RETTANGOLO_Y', 'Dimensione y del rettangolo che racchiude l''annotazione');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('APPLICA_LAYER_PROT_PDF', 'NUM_PAGINA_ANNOTATION', 'Indica il numero della pagina su cui applicare l''annotazione. Valori che può assumere: NUMERO INTERO ( Es. 1,2,3. Se numero intero è maggiore del numero pagine documento verrà apposta sull''ultima pagina), vuoto o numero non intero : Pagina 1, valore 0: Tutte le pagine, valore -1 : Ultima pagina.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('APPLICA_LAYER_PROT_PDF', 'COLORE_FONT_ANNOTATION', 'Colore del font dell''annotazione secondo il formato RGB Es. 136,136,136. Se non corretto o vuoto prende quello di default.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('APPLICA_LAYER_PROT_PDF', 'COLORE_BACKGROUND_ANNOTATION', 'Colore del backgroud dell''annotazione secondo il formato RGB Es. 136,136,136. Se non corretto o vuoto prende quello di default.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('APPLICA_LAYER_PROT_PDF', 'LOCK_ANNOTATION', 'Valori ammessi - 1: Annotazione non modificabile/eliminabile, 0: Annotazione modificabile/eliminabile. Default non modificabile ');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('APPLICA_LAYER_PROT_PDF', 'COD_MAIL_TIPO', 'Codice mail ttipo da cui prendere l''oggetto per creare la stringa stampata nell''annotazione');

INSERT INTO VERTICALIZZAZIONIBASE (MODULO, DESCRIZIONE, FLAG_GESTCOMUNE) VALUES  ('PROTOCOLLO_JIRIDE', 'Abilita il protocollo J-IRIDE realizzato da Maggioli, tale protocollo è utilizzabile anche dalla regola PROTOCOLLO_IRIDE, tuttavia è consigliato utilizzare questo che è specifico proprio per il protocollo J-IRIDE (che è diverso e ragiona diversamente rispetto a IRIDE)', '1');
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('PROTOCOLLO_JIRIDE','URLFASC','Percorso completo del WS di fascicolazione DocWsFascicoli');
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('PROTOCOLLO_JIRIDE','PEC_INTEROP','Parametro Si o No (valore 1 o altro), se valorizzato a 1, l''invio della pec tramite ws PosteWeb, sarà interoperabile, sarà quindi inserito l''elemento <InvioInteroperabile> valorizzato a S, questo consente l''invio della segnatura xml.');
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('PROTOCOLLO_JIRIDE','NUMEROPRATICA','Numero pratica da passare al WS J-Iride a Ravenna "9999999"');
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('PROTOCOLLO_JIRIDE','AGGIORNAANAGRAFICHE','Parametro che in J-Iride specifica se aggiornare le anagrafiche. Possibili valori S o N.');
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('PROTOCOLLO_JIRIDE','URL','Percorso completo del WS di Protocollazione WsProtocolloDM');
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('PROTOCOLLO_JIRIDE','CODICEAMMINISTRAZIONE','Indica il codice di amministrazione da passare al web service di J-Iride, deve essere fornito dall''amministratore del protocollo. Questo dato indica su quale amministrazione protocollare, infatti J-Iride può avere un''installazione MultiDB, in questo caso va valorizzato questo dato che, tra le altre cose può indicare se si sta utilizzando un ambiente di Test o di Produzione.');
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('PROTOCOLLO_JIRIDE','DISABILITA_CREACOPIE','Consente di disabilitare la funzionalità di creazione delle copie su J-Iride (se = 1). Inserito in quanto l''invio della notifica tramite il movimento dell''istanza creava automaticamente anche la copia sul sistema di protocollazione J-Iride, e questo può creare alcuni disagi per i clienti che gestiscono manualmente le pratiche o che abbiano già creato il protocollo su J-Iride, come nel caso della Bassa Romagna. NB. L''utilizzo di questo parametro può portare a qualche problema durante la funzionalità di leggi protocollo, infatti se valorizzato a 1, i dati inviati tramite notifica STC sulla nuova istanza su nuovo software non saranno compresi di IDPROTOCOLLO, questo significa che, in presenza di più copie (su J-IRIDE) con stessa numerazione ma con ID diverso, nel momento della lettura di un protocollo senza ID può essere riportato quello con ID sbagliato, in teoria comunque i dati dei protocolli con diversi ID ma con stessa numerazione dovrebbero essere gli stessi.');
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('PROTOCOLLO_JIRIDE','MEZZO_DEFAULT','Indica il mezzo di default da passare al web service di J-Iride, non è un dato obbligatorio quindi può essere omesso. Questo dato, se valorizzato, viene proposto di default nella maschera di protocollazione nel dropdown riguardante i mezzi e se lo stesso valore è presente nella tabella PROTOCOLLO_MEZZI, viene inviato al web service anche quando la protocollazione è automatica, quindi proveniente da un frontoffice o dal backoffice se impostata la configurazione di protocollazione automatica. NB. se la tabella PROTOCOLLO_MEZZI è vuota il drop down mezzi, nella maschera di protocollazione, non viene visualizzato, ignorando quindi il valore di questo parametro.');
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('PROTOCOLLO_JIRIDE','MOSTRA_METTI_ALLA_FIRMA','Attivando il pulsante c''è la possibilità di comunicare al software INTRANOS (Comune di Ravenna) che un documento deve essere firmato. Ogni successivo cambiamento di stato compiuto in INTRANOS + J-IRIDE viene comunicato al Backoffice tramite WebService (Es: "Il documento è stato firmato", "Il documento è stato protocollato", "Il documento è stato inviato"). I cambiamenti di stato vengono scritti nel backoffice nella sezione eventi del movimento e, nel caso di protocollazione, viene riportato in automatico il numero di protocollo nel movimento. Accetta valori S o N');
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('PROTOCOLLO_JIRIDE','AOO','Valorizzare questo parametro solamente nel caso in il parametro VERSIONE sia valorizzato a J-IRIDE, in caso contrario sarà comunque ignorato, serve solamente per l''invio delle PEC in quanto il metodo utilizzato da J-IRIDE inviaMail (a differenza di J-IRIDE che utilizza inviaMailInterop) lo richiede in modo necessario.');
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('PROTOCOLLO_JIRIDE','FORMATO_DATA_FASC','Serve per indicare in quale formato deve essere inviata la data di fascicolazione al web service. Maggioli ha creato un altro web service compatibile con J-Iride (ProtocolloSoap e DocWsFascicoli), solo che la data deve avere formato yyyy-MM-dd altrimenti non viene riconosciuta. Quindi, solo nel momento in cui vengono usati questi web service, il formato data deve essere impostato a yyyy-MM-dd, in generale, comunque, il componente PROTOCOLLO_IRIDE andrà ad impostare la data in base a quanto scritto in questo parametro, quindi, se viene impostato dd-MM-yyyy il sistema invierà ad esempio 23-10-2014, che nel caso specifico di questo web service, restituirà errore, evitare quindi di inserire ulteriori formati. Nel caso del vecchio J-Iride, non va impostato.');
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('PROTOCOLLO_JIRIDE','WARNING_DA_ELIMINARE','Inserire in questo parametro la stringa che viene restituita dal web service nn fase di protocollazione avvenuta correttamente. J-Iride restituisce un messaggio anche in caso di protocollazione avvenuta correttamente, il messaggio viene successivamente inserito nei warning quindi va eliminata la stringa restituita in caso di protocollazione OK.');
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('PROTOCOLLO_JIRIDE','USA_NUM_ANNO_LEGGI','Questo parametro serve per indicare al plugin del protocollo per capire se la lettura del protocollo deve essere fatta invocando il metodo LeggiProtocollo oppure LeggiDocumento, nel primo caso la chiamata viene fatta passando il numero e l''anno del protocollo, nel secondo l''id del documento, di default, se valorizzato il campo FKIDPROTOCOLLO delle ISTANZE o MOVIMENTO viene invocato il metodo LeggiDocumento, valorizzando questo parametro a 1 il sistema forza la chiamata sempre utilizzando il metodo LeggiProtocollo, questo perchè il nuovo ws retrocompatibile J-IRIDE di Maggioli ha un bug su leggi documento che non ritorna gli allegati.');
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('PROTOCOLLO_JIRIDE','URL_PEC','Indicare in questo parametro l''endpoint da utilizzare per usare il servizio di invio posta elettronica certificata di J-Iride, sarà proprio questo servizio che si occuperà di inviare la PEC');
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('PROTOCOLLO_JIRIDE','MEZZO_PEC','Indicare il mezzo da utilizzare se si vuole inviare la PEC richiamando il web service PosteWeb di J-Iride. Se il protocollo è in partenza e sono presenti dei destinatari esterni (che non abbiano scrivanie su J-Iride) è necessario indicare il mezzo per cui, al destinatario, venga inviata anche una PEC tramite il servizio PostePec di J-Iride indicato nel parametro URL_PEC, se sarà utilizzato quindi il mezzo indicato in questo parametro il sistema si occuperà di chiamare quindi il servizio di invio pec di J-iride');
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('PROTOCOLLO_JIRIDE','MITTENTE_PEC','Inserire in questo parametro il valore relativo al mittente che invia la mail pec in fase di protocollazione in partenza, questo parametro è legato all''altro parametro URL_PEC in quanto, se non presente quest''ultimo, MITTENTE_PEC non viene utilizzato');
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('PROTOCOLLO_JIRIDE','UO_SMISTAMENTO','Indicare il codice UO (ufficio) che indica il mittente interno per le pratiche in arrivo, nel protocollo sta ad indicare lo smistamento, in pratica quale ufficio ha lavorato il documento (in arrivo).');
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('PROTOCOLLO_JIRIDE','WARNING_PEC','Se valorizzato a 1 consente di visualizzare sempre un warning relativo all''invio PEC di una protocollazione in partenza, sia che vada a buon fine che vada in errore.');
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('PROTOCOLLO_JIRIDE','PROTO_OGGETTO_PEC','Parametro Si o No (valore 1 o altro), se valorizzato a 1 nell''oggetto della pec, inviata tramite la chiamata a ws PostaWeb, saranno visualizzati, in fondo all''oggetto stesso i dati di protocollo sotto forma di: Pr. Num. [NUMERO_PROTOCOLLO], Pr. Data [DATA_PROTOCOLLO]');
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('PROTOCOLLO_JIRIDE','AGGIORNACLASSIFICA','Parametro che in J-Iride specifica se aggiornare la classifica del documento se diversa da quella del fascicolo');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_PAL', 'GESTISCI_ASSEGNATARI', 'Indicare il valore 1 se l''utilizzo degli assegnatari risulta essere obbligatorio (confrontarsi con PAL per questo), il parametro è stato inserito per garantire una retro compatibilità con le versioni precedenti che non prevedevano l''assegnazione.');


Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('FVG_SUAP_IN_RETE','URL_WSDL_INSIEL',
'Url del wsdl esposto da INSIEL per recuperare informazioni sui procedimenti e moduli');

Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('FVG_SUAP_IN_RETE','WS_INSIEL_USER',
'Username WS esposto da INSIEL per recuperare informazioni sui procedimenti e moduli');

Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('FVG_SUAP_IN_RETE','WS_INSIEL_PASSWORD',
'password WS esposto da INSIEL per recuperare informazioni sui procedimenti e moduli');

Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('FVG_SUAP_IN_RETE','COD_PROC_GENERICO','Codice del procedimento generico che viene associato ai procedimenti presenti nella pratica suap in rete che non comportano la creazione della pratica in VBG ');
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('FVG_SUAP_IN_RETE','SPACCHETTA_PRATICA_CO','Parametro per impostare il comportamento di spacchettamento pratica. Se attivo verrano create N pratiche quanti sono i procedimenti collegati al commercio. Può assumere i valori 1 : ATTIVO o 0(NULL) : NON ATTIVO');
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('FVG_SUAP_IN_RETE','SERCH_PATTER_CO_PROC','Indica la stringa utilizzata per capire se un procedimento è del commercio o no.');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_ATTIVO', 'MOSTRA_METTI_ALLA_FIRMA', 'Valorizzare a S se si desidera gestire la funzionalità della messa alla firma. Sarà visualizzato il pulsante METTI ALLA FIRMA nella maschera dei movimenti ma solo se non presenti i riferimenti di protocollo. Questa gestione è utilizzata soprattutto nei sistemi Maggioli (IRIDE, JIRIDE).');

INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,PROVINCIA,REGIONE,CAP,CF,CODICEISTAT,CODICEISTATREGIONE) VALUES('M300',  'DUE CARRARE','PD','PADOVA','VENETO','35020','M300','028106','05');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_CIVILIA', 'URL_SERVICE_OAUTH', 'Endpoint del servizio rest adibito a contattare il servizio OAUTH2, si è reso necessario lo sviluppo di un servizio rest adibito solamente a staccare il token, in quanto le classi da utilizzare hanno bisogno di una versione del framework superiore a quella di sigepro.net che non può essere aggiornato per via dell''utilizzo di classi che si interfacciano con SqlServer2003 (ancora utilizzato).');


INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_CIVILIA', 'URL_WSRESOURCE', 'Indicare la url che identifica la risorsa che contiene il token richiesto, in genere è sufficiente indicare la parte iniziale del ws indicato nel parametro URL_WS, in pratica invece di http://api.civilianextdev.it/Protocollo/Protocollo/Protocolla');

