<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema xmlns:sem="http://www.suap.regione.toscana.it/sem/types/attori"
	xmlns:wsi="http://ws-i.org/profiles/basic/1.1/xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema"
	attributeFormDefault="unqualified" elementFormDefault="qualified"
	targetNamespace="http://www.suap.regione.toscana.it/sem/types/attori"
	version="1.0">

 	<xs:simpleType name="attoreReteSuap">
 		<xs:annotation>
			<xs:documentation>
				Elenco degli attori della rete SUAP che possono essere coinvolti in un procedimento:
					* 'FACCT': Front End di Accettazione 
					* 'COMACCT': Front End di Accettazione ComUnica 
					* 'SUAP' : Sportello Unico per le Attivita' Produttive 
					* 'ASL'  : Azienda Sanitaria Locale
					* 'GC'   : Genio Civile
					* 'VVFF' : Vigili del Fuoco
					* 'REG'  : Regione
					* 'PROV' : Provincia
					* 'ED'   : Ufficio Edilizia
					* 'COMM' : Ufficio Commercio
					* 'AMB'  : Ufficio Ambiente
					* 'VVUU' : Polizia Municipale
					* 'SBBAA': Soprintendenza BB.AA. 
					* 'ANAS' : A.N.A.S. 
					* 'ARPAT': A.R.P.A.T. 
					* 'ENPA' : Ente Parco
					* 'CPORTO': Capitaneria di Porto
					* 'QUEST': Questura
					* 'MISE' : Ministero per lo sviluppo economico
					* 'MINT' : Ministero degli interni
					* 'PREF' : Prefettura
					* 'AIT'	 : Autorita' Idrica Toscana
					* 'EGF'  : Ente Gestore Fognature
					* 'CIRC' : Circondario
					* 'INAIL': INAIL (ex Ispesl)
					* 'ADM'  : Agenzia delle Dogane e dei Monopoli
					* 'ATO'  : Rifiuti
					* 'APORTO': Autorita' Portuale
					* 'URB'  : Urbanistica
					* 'DEM'  : Demanio
					* 'PAMM' : Polizia Amministrativa
					* 'SOC'  : Sociale
					* 'AMBRT': Settore Ambiente Regionale
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="FACCT|COMACCT|SUAP|ASL|GC|VVFF|REG|PROV|ED|COMM|AMB|VVUU|SBBAA|ANAS|ARPAT|ENPA|CPORTO|QUEST|MISE|MINT|PREF|AIT|EGF|CIRC|INAIL|ADM|ATO|APORTO|URB|DEM|PAMM|SOC|AMBRT"/>
		</xs:restriction>
	</xs:simpleType>

</xs:schema>
