SET IMPLICIT_TRANSACTIONS ON
GO
ALTER TABLE INVENTARIOPROCEDIMENTISOFTWARE ADD CODICEAMMINISTRAZIONE NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE INVENTARIOPROCEDIMENTISOFTWARE ADD CONSTRAINT FK_INVPROCSOFT_AMM FOREIGN KEY (IDCOMUNE, CODICEAMMINISTRAZIONE) REFERENCES AMMINISTRAZIONI(IDCOMUNE, CODICEAMMINISTRAZIONE)
GO
COMMIT
GO
ALTER TABLE INVENTARIOPROCEDIMENTISOFTWARE ADD ID NUMERIC(6,0)
GO
COMMIT
GO
