SET IMPLICIT_TRANSACTIONS ON
GO
ALTER TABLE INVENTARIOPROCEDIMENTISOFTWARE DROP PRIMARY KEY
GO
COMMIT
GO
ALTER TABLE INVENTARIOPROCEDIMENTISOFTWARE MODIFY COLUMN ID NUMERIC(6,0) NOT NULL
GO
COMMIT
GO
ALTER TABLE INVENTARIOPROCEDIMENTISOFTWARE ADD CONSTRAINT INVENTARIOPROCEDIMENTISOFTW_PK PRIMARY KEY (IDCOMUNE, ID)
GO
COMMIT
GO