ALTER TABLE domandestc MODIFY richiedente VARCHAR(150);

alter table MERCATI_CONFIGURAZIONE add SEGNA_PRESENZA_SPUNT_NO_POST numeric(1,0);


ALTER TABLE GRUPPI_ISTRUTTORI_RESP DROP FOREIGN KEY FK_GRP_ISTRUTTOR_ISTRUTT;

ALTER TABLE GRUPPI_ISTRUTTORI_RESP ADD CONSTRAINT FK_GRP_ISTRUTTOR_ISTRUTT FOREIGN KEY (IDCOMUNE, FK_GRP_ISTRUTTORI) REFERENCES GRUPPI_ISTRUTTORI (IDCOMUNE, ID);


ALTER TABLE GRUPPI_ISTRUTTORI_RESP DROP FOREIGN KEY FK_GRP_ISTRUTTOR_RESP; 

ALTER TABLE GRUPPI_ISTRUTTORI_RESP ADD CONSTRAINT FK_GRP_ISTRUTTOR_RESP FOREIGN KEY (IDCOMUNE, FK_RESPOSABILE) REFERENCES RESPONSABILI (IDCOMUNE, CODICERESPONSABILE);

ALTER TABLE MOVIMENTI ADD ID_ATT_DEST VARCHAR(250);
ALTER TABLE MOVIMENTI ADD STATO_ATT_DEST VARCHAR(250);

ALTER TABLE AMMINISTRAZIONI MODIFY AMMINISTRAZIONE VARCHAR(255);

CREATE TABLE ALLEGATI_DOC_SOGG_FIRMATARI (
  IDCOMUNE                  VARCHAR(6) NOT NULL,
  ID                      NUMERIC (10,0)     NOT NULL,
  FK_TIPO_SOGGETTO        NUMERIC (10,0)     NOT NULL,
  FK_ALLEGATI_ID          NUMERIC (10,0)     NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

ALTER TABLE ALLEGATI_DOC_SOGG_FIRMATARI
  ADD CONSTRAINT ALLEGATI_DOC_SOGG_FIRM_PK PRIMARY KEY (
    IDCOMUNE,
    ID
  );

ALTER TABLE ALLEGATI_DOC_SOGG_FIRMATARI
  ADD CONSTRAINT FK_SOGG_FIRM_ALLEGATI FOREIGN KEY (
    IDCOMUNE,
    FK_ALLEGATI_ID
  ) REFERENCES ALLEGATI (
    IDCOMUNE,
    ID
  );

ALTER TABLE ALLEGATI_DOC_SOGG_FIRMATARI
  ADD CONSTRAINT FK_ALL_SOGG_FIRM_TIPO_SOGG FOREIGN KEY (
    IDCOMUNE,
    FK_TIPO_SOGGETTO
  ) REFERENCES TIPISOGGETTO (
    IDCOMUNE,
    CODICETIPOSOGGETTO
  );

  
ALTER TABLE TIPOLOGIAREGISTRI add CODICECOMUNE VARCHAR(5);
ALTER TABLE TIPOLOGIAREGISTRI ADD  CONSTRAINT FK_TIPOLOGIAREGISTRI_COMUNI FOREIGN KEY (CODICECOMUNE) REFERENCES COMUNI(CODICECOMUNE);

ALTER TABLE GRADUATORIET_COM ADD FLG_TRASFORMA_PDF NUMERIC(1,0);