idcomunealias=L219TS
installationId=TZT

ws.oggetti.mtom=true
ws.eventi.mtom=true

#BACKEND
ws.backend.url=REDACTED

#attivazione scheduler di quartz, i trigger di attivazione dei job devono essere configurati nella tabella PAY_CONNECTOR_WS_ENDPOINT
scheduler.enabled=false

