# Comment out the Log4J listener in web.xml to activate Log4J.
log4j.rootLogger=ERROR, logfile

log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d %p [%c] %nBACKEND - <%m>%n

log4j.appender.logfile=org.apache.log4j.RollingFileAppender
log4j.appender.logfile.File=${catalina.home}/logs/nodo-pagamenti.log
log4j.appender.logfile.MaxFileSize=10240KB
log4j.appender.logfile.MaxBackupIndex=30
log4j.appender.logfile.layout=org.apache.log4j.PatternLayout
log4j.appender.logfile.layout.ConversionPattern=%d %p [%c] - %m%n

#log4j.logger.generic-exception=ERROR, mail
#attivazione log-info per attività del nodo pagamenti
log4j.logger.it.gruppoinit.pal.gp.pay=INFO

log4j.logger.org.springframework=WARN
#log4j.logger.org.apache=WARN
log4j.logger.org.springframework.orm.hibernate3=WARN
log4j.logger.org.hibernate=WARN
log4j.logger.org.quartz=WARN

log4j.logger.org.apache.cxf=WARN
#log delle chiamate soap(INFO=on,WARN=off)
log4j.logger.org.apache.cxf.services=INFO
## impostare a DEBUG per visualizzare le query ed i parametri di binding(impostare type a TRACE per visualizzare anche i parametri di ritorno)
log4j.logger.org.hibernate.SQL=WARN
log4j.logger.org.hibernate.type=WARN
# BasicExtractor ESTRAE I VALORI TORNATI DALLE QUERY
log4j.logger.org.hibernate.type.descriptor.sql.BasicExtractor=WARN
# BasicBinder I VALORI IMPOSTATI COME FILTRI DELLE QUERY
log4j.logger.org.hibernate.type.descriptor.sql.BasicBinder=WARN
log4j.logger.org.hibernate.cache=WARN
log4j.logger.org.hibernate.jdbc=WARN
log4j.logger.org.hibernate.resource.transaction=WARN
log4j.logger.org.hibernate.engine.transaction=WARN
#log4j.logger.org.hibernate.type.AnyType=WARN
#log4j.logger.org.hibernate.type.BigDecimalType=WARN
#log4j.logger.org.hibernate.type.BigIntegerType=WARN
#log4j.logger.org.hibernate.type.BooleanType=WARN
#log4j.logger.org.hibernate.type.ByteType=WARN
#log4j.logger.org.hibernate.type.CalendarDateType=WARN
#log4j.logger.org.hibernate.type.CalendarType=WARN
#log4j.logger.org.hibernate.type.CharacterType=WARN
#log4j.logger.org.hibernate.type.DateType=WARN
#log4j.logger.org.hibernate.type.DbTimestampType=WARN
#log4j.logger.org.hibernate.type.DoubleType=WARN
#log4j.logger.org.hibernate.type.FloatType=WARN
#log4j.logger.org.hibernate.type.IdentifierBagType=WARN
#log4j.logger.org.hibernate.type.IntegerType=WARN
#log4j.logger.org.hibernate.type.LongType=WARN
#log4j.logger.org.hibernate.type.NullableType=WARN
#log4j.logger.org.hibernate.type.NumericBooleanType=WARN
#log4j.logger.org.hibernate.type.ShortType=WARN
#log4j.logger.org.hibernate.type.StringClobType=WARN
#log4j.logger.org.hibernate.type.StringType=WARN
#log4j.logger.org.hibernate.type.TextType=WARN
#log4j.logger.org.hibernate.type.TimestampType=WARN
#log4j.logger.org.hibernate.type.TimeType=WARN

log4j.logger.it.gruppoinit.pal.gp.core.domain.util.EntityUtils=OFF
#log4j.logger.it.gruppoinit.pal.gp.core.utils.FileSystemHelper=DEBUG
#log4j.logger.it.gruppoinit.pal.gp.pay.connector.mip.genova=DEBUG
#log4j.logger.it.gruppoinit.pal.gp=WARN
#log4j.logger.it.gruppoinit.pal.gp.core.service=WARN
#log4j.logger.it.gruppoinit.pal.gp.core.service.impl=WARN
#log4j.logger.it.gruppoinit.pal.gp.core.event.LogHibernateDeleteEvents=WARN
#log4j.logger.it.gruppoinit.pal.gp.core.dao.helper.DataSourceContainer=DEBUG


## c3p0 logger
#log4j.logger.com.mchange=WARN
