# INSERIRE USERNAME / PASSWORD PER AUTENTICAZIONE BASIC
# MEDIANTE INTERCEPTOR ==> it.gruppoinit.pal.gp.pay.ws.interceptors.BasicAuthAuthorizationInterceptor
# MEDIANTE INTERCEPTOR ==> it.gruppoinit.pal.gp.pay.ws.interceptors.InterceptorInHeaderAuth
# ES: user1=passw1
test.retelit.mip.genova=TEstMIPRetelit87\#\#
