alter table ISTANZEPROCURE add(CONTROLLOOK NUMBER(1, 0));
alter table ISTANZEPROCURE add(NECESSARIO NUMBER(1, 0));
alter table ISTANZEPROCURE add(PRESENTE NUMBER(1, 0));
alter table ISTANZEPROCURE add(NOTE VARCHAR2(1200));

CREATE TABLE LDP_DECODIFICHE (
  Idcomune VARCHAR2(6), 
  Software VARCHAR2(2), 
  Id NUMBER(10,0), 
  Contesto VARCHAR2(16), 
  Codice VARCHAR2(32), 
  Descrizione VARCHAR2(64)
);

CREATE UNIQUE INDEX IDX_LDP_DECODIFICHE_001
  ON LDP_DECODIFICHE (
    idcomune,
    software,
    Contesto,
    Codice
  );

ALTER TABLE LDP_DECODIFICHE
  ADD CONSTRAINT LDP_DECODIFICHE_PK PRIMARY KEY (
    idcomune,
    id
  );

ALTER TABLE alberoproc ADD LDP_TIP_OCCUPAZIONE NUMBER(10,0);
ALTER TABLE alberoproc ADD LDP_TIP_PERIODO NUMBER(10,0);
ALTER TABLE alberoproc ADD LDP_TIP_GEOMETRIA NUMBER(10,0);

ALTER TABLE alberoproc
  ADD CONSTRAINT fk_alberoproc_ldp_decod1 FOREIGN KEY (
    idcomune,
    LDP_TIP_OCCUPAZIONE
  ) REFERENCES LDP_DECODIFICHE (
    idcomune,
    id
  );
  
ALTER TABLE alberoproc
  ADD CONSTRAINT fk_alberoproc_ldp_decod2 FOREIGN KEY (
    idcomune,
    LDP_TIP_PERIODO
  ) REFERENCES LDP_DECODIFICHE (
    idcomune,
    id
  );  

ALTER TABLE alberoproc
  ADD CONSTRAINT fk_alberoproc_ldp_decod3 FOREIGN KEY (
    idcomune,
    LDP_TIP_GEOMETRIA
  ) REFERENCES LDP_DECODIFICHE (
    idcomune,
    id
  );

ALTER TABLE PROTOCOLLO_UFFICIREGISTRI DROP CONSTRAINT PROTOCOLLO_UFFICIREGISTRI_PK;

ALTER TABLE PROTOCOLLO_UFFICIREGISTRI ADD CONSTRAINT PROTOCOLLO_UFFICIREGISTRI_PK PRIMARY KEY (IDCOMUNE, CODICEREGISTRO) ENABLE;

ALTER TABLE NEWS ADD (FLAG_IN_PRIMO_PIANO NUMBER(1,0));

ALTER TABLE GRUPPI_ISTRUTTORI MODIFY (ID NUMBER(10,0));

ALTER TABLE GRUPPI_ISTRUTTORI_RESP MODIFY (FK_GRP_ISTRUTTORI NUMBER(10,0));
