CREATE TABLE STAR_CONFIGONERI
(
  ID NUMBER(10,0) NOT NULL
, IDCOMUNE VARCHAR2(6) NOT NULL
, FLG_ONLINE_ENTITERZI NUMBER(1,0) DEFAULT 1 , INFO_PAGAMENTI_FO CLOB , CODICE_COMUNE VARCHAR2(6) , CONSTRAINT STAR_CONFIGONERI_PK PRIMARY KEY
  (
    ID
  , IDCOMUNE
  )
  ENABLE
);

COMMENT ON COLUMN STAR_CONFIGONERI.FLG_ONLINE_ENTITERZI IS 'SE IMPOSTATO A 0 DISATTIVA IL PAGAMENTO ONLINE DEGLIL ONERI DESTINATI AD ENTI TERZI PER IL SINGOLO COMUNE';



