ALTER TABLE MOVIMENTIALLEGATI MODIFY ID_BASE VARCHAR2(600 CHAR);

ALTER TABLE MERCATI_FORMULE_CALCOLO ADD CONTESTO VARCHAR2(20 char);

UPDATE MERCATI_FORMULE_CALCOLO SET CONTESTO = 'PRESENZA' WHERE CONTESTO IS NULL;

ALTER TABLE MERCATI_FORMULE_CALCOLO MODIFY CONTESTO VARCHAR2(20 char) NOT NULL;



ALTER TABLE BOLL_GEST_DETT_AUTORIZZ ADD FK_BOLLGEST_ID NUMBER(4,0);
ALTER TABLE BOLL_GEST_DETT_RATE ADD FK_BOLLGEST_ID NUMBER(4,0);
ALTER TABLE BOLL_GEST_ISTANZEONERI ADD FK_BOLLGEST_ID NUMBER(4,0);
ALTER TABLE BOLL_GEST_MERCATI_DETT ADD FK_BOLLGEST_ID NUMBER(4,0);
ALTER TABLE BOLL_GEST_ONERI_SEQUENCE ADD FK_BOLLGEST_ID NUMBER(4,0);

ALTER TABLE BOLL_GEST_DETT_AUTORIZZ ADD CONSTRAINT FK_DETAUT_BLLGSTTEST FOREIGN KEY (IDCOMUNE, FK_BOLLGEST_ID) REFERENCES BOLL_GEST_TESTATA(IDCOMUNE, ID);
ALTER TABLE BOLL_GEST_DETT_RATE ADD CONSTRAINT FK_DETRAT_BLLGSTTEST FOREIGN KEY (IDCOMUNE, FK_BOLLGEST_ID) REFERENCES BOLL_GEST_TESTATA(IDCOMUNE, ID);
ALTER TABLE BOLL_GEST_ISTANZEONERI ADD CONSTRAINT FK_ISTONE_BLLGSTTEST FOREIGN KEY (IDCOMUNE, FK_BOLLGEST_ID) REFERENCES BOLL_GEST_TESTATA(IDCOMUNE, ID);
ALTER TABLE BOLL_GEST_MERCATI_DETT ADD CONSTRAINT FK_MERDET_BLLGSTTEST FOREIGN KEY (IDCOMUNE, FK_BOLLGEST_ID) REFERENCES BOLL_GEST_TESTATA(IDCOMUNE, ID);
ALTER TABLE BOLL_GEST_ONERI_SEQUENCE ADD CONSTRAINT FK_ONESEQ_BLLGSTTEST FOREIGN KEY (IDCOMUNE, FK_BOLLGEST_ID) REFERENCES BOLL_GEST_TESTATA(IDCOMUNE, ID);

CREATE INDEX IDX_DETAUT_BLLGSTTEST_001 ON BOLL_GEST_DETT_AUTORIZZ(IDCOMUNE,FK_BOLLGEST_ID);
CREATE INDEX IDX_DETRAT_BLLGSTTEST_001 ON BOLL_GEST_DETT_RATE(IDCOMUNE,FK_BOLLGEST_ID);
CREATE INDEX IDX_ISTONE_BLLGSTTEST_001 ON BOLL_GEST_ISTANZEONERI(IDCOMUNE,FK_BOLLGEST_ID);
CREATE INDEX IDX_MERDET_BLLGSTTEST_001 ON BOLL_GEST_MERCATI_DETT(IDCOMUNE,FK_BOLLGEST_ID);
CREATE INDEX IDX_ONESEQ_BLLGSTTEST_001 ON BOLL_GEST_ONERI_SEQUENCE(IDCOMUNE,FK_BOLLGEST_ID);

MERGE INTO BOLL_GEST_DETT_AUTORIZZ USING (SELECT IDCOMUNE, ID, FK_BOLLGEST_ID, RNUM FROM (SELECT BOLL_GEST_DETT_AUTORIZZ.IDCOMUNE, BOLL_GEST_DETT_AUTORIZZ.ID, BOLL_GEST_TESTATA.ID AS FK_BOLLGEST_ID, ROW_NUMBER() OVER(PARTITION BY BOLL_GEST_DETT_AUTORIZZ.IDCOMUNE, BOLL_GEST_DETT_AUTORIZZ.ID ORDER BY BOLL_GEST_DETT_AUTORIZZ.IDCOMUNE ASC, BOLL_GEST_DETT_AUTORIZZ.ID ASC) AS RNUM FROM BOLL_GEST_TESTATA INNER JOIN BOLL_GEST_DETTAGLIO ON BOLL_GEST_TESTATA.IDCOMUNE = BOLL_GEST_DETTAGLIO.IDCOMUNE AND BOLL_GEST_TESTATA.ID = BOLL_GEST_DETTAGLIO.FK_BOLLGEST_ID INNER JOIN BOLL_GEST_DETT_AUTORIZZ ON BOLL_GEST_DETTAGLIO.IDCOMUNE = BOLL_GEST_DETT_AUTORIZZ.IDCOMUNE AND BOLL_GEST_DETTAGLIO.ID = BOLL_GEST_DETT_AUTORIZZ.FK_BOLLGESTDET_ID AND BOLL_GEST_DETT_AUTORIZZ.FK_BOLLGEST_ID IS NULL) WHERE RNUM = 1) TESTATA ON (BOLL_GEST_DETT_AUTORIZZ.IDCOMUNE = TESTATA.IDCOMUNE AND BOLL_GEST_DETT_AUTORIZZ.ID = TESTATA.ID) WHEN MATCHED THEN UPDATE SET BOLL_GEST_DETT_AUTORIZZ.FK_BOLLGEST_ID = TESTATA.FK_BOLLGEST_ID;
MERGE INTO BOLL_GEST_DETT_RATE USING (SELECT IDCOMUNE, ID, FK_BOLLGEST_ID, RNUM FROM (SELECT BOLL_GEST_DETT_RATE.IDCOMUNE, BOLL_GEST_DETT_RATE.ID, BOLL_GEST_TESTATA.ID AS FK_BOLLGEST_ID, ROW_NUMBER() OVER(PARTITION BY BOLL_GEST_DETT_RATE.IDCOMUNE, BOLL_GEST_DETT_RATE.ID ORDER BY BOLL_GEST_DETT_RATE.IDCOMUNE ASC, BOLL_GEST_DETT_RATE.ID ASC) AS RNUM FROM BOLL_GEST_TESTATA INNER JOIN BOLL_GEST_DETTAGLIO ON BOLL_GEST_TESTATA.IDCOMUNE = BOLL_GEST_DETTAGLIO.IDCOMUNE AND BOLL_GEST_TESTATA.ID = BOLL_GEST_DETTAGLIO.FK_BOLLGEST_ID INNER JOIN BOLL_GEST_DETT_RATE ON BOLL_GEST_DETTAGLIO.IDCOMUNE = BOLL_GEST_DETT_RATE.IDCOMUNE AND BOLL_GEST_DETTAGLIO.ID = BOLL_GEST_DETT_RATE.FK_BOLLGESTDET_ID AND BOLL_GEST_DETT_RATE.FK_BOLLGEST_ID IS NULL) WHERE RNUM = 1) TESTATA ON (BOLL_GEST_DETT_RATE.IDCOMUNE = TESTATA.IDCOMUNE AND BOLL_GEST_DETT_RATE.ID = TESTATA.ID) WHEN MATCHED THEN UPDATE SET BOLL_GEST_DETT_RATE.FK_BOLLGEST_ID = TESTATA.FK_BOLLGEST_ID;
MERGE INTO BOLL_GEST_ISTANZEONERI USING (SELECT IDCOMUNE, ID, FK_BOLLGEST_ID, RNUM FROM (SELECT BOLL_GEST_ISTANZEONERI.IDCOMUNE, BOLL_GEST_ISTANZEONERI.ID, BOLL_GEST_TESTATA.ID AS FK_BOLLGEST_ID, ROW_NUMBER() OVER(PARTITION BY BOLL_GEST_ISTANZEONERI.IDCOMUNE, BOLL_GEST_ISTANZEONERI.ID ORDER BY BOLL_GEST_ISTANZEONERI.IDCOMUNE ASC, BOLL_GEST_ISTANZEONERI.ID ASC) AS RNUM FROM BOLL_GEST_TESTATA INNER JOIN BOLL_GEST_DETTAGLIO ON BOLL_GEST_TESTATA.IDCOMUNE = BOLL_GEST_DETTAGLIO.IDCOMUNE AND BOLL_GEST_TESTATA.ID = BOLL_GEST_DETTAGLIO.FK_BOLLGEST_ID INNER JOIN BOLL_GEST_ISTANZEONERI ON BOLL_GEST_DETTAGLIO.IDCOMUNE = BOLL_GEST_ISTANZEONERI.IDCOMUNE AND BOLL_GEST_DETTAGLIO.ID = BOLL_GEST_ISTANZEONERI.FK_BOLLGESTDET_ID AND BOLL_GEST_ISTANZEONERI.FK_BOLLGEST_ID IS NULL) WHERE RNUM = 1) TESTATA ON (BOLL_GEST_ISTANZEONERI.IDCOMUNE = TESTATA.IDCOMUNE AND BOLL_GEST_ISTANZEONERI.ID = TESTATA.ID) WHEN MATCHED THEN UPDATE SET BOLL_GEST_ISTANZEONERI.FK_BOLLGEST_ID = TESTATA.FK_BOLLGEST_ID;
MERGE INTO BOLL_GEST_MERCATI_DETT USING (SELECT IDCOMUNE, ID, FK_BOLLGEST_ID, RNUM FROM (SELECT BOLL_GEST_MERCATI_DETT.IDCOMUNE, BOLL_GEST_MERCATI_DETT.ID, BOLL_GEST_TESTATA.ID AS FK_BOLLGEST_ID, ROW_NUMBER() OVER(PARTITION BY BOLL_GEST_MERCATI_DETT.IDCOMUNE, BOLL_GEST_MERCATI_DETT.ID ORDER BY BOLL_GEST_MERCATI_DETT.IDCOMUNE ASC, BOLL_GEST_MERCATI_DETT.ID ASC) AS RNUM FROM BOLL_GEST_TESTATA INNER JOIN BOLL_GEST_DETTAGLIO ON BOLL_GEST_TESTATA.IDCOMUNE = BOLL_GEST_DETTAGLIO.IDCOMUNE AND BOLL_GEST_TESTATA.ID = BOLL_GEST_DETTAGLIO.FK_BOLLGEST_ID INNER JOIN BOLL_GEST_DETT_AUTORIZZ ON BOLL_GEST_DETTAGLIO.IDCOMUNE = BOLL_GEST_DETT_AUTORIZZ.IDCOMUNE AND BOLL_GEST_DETTAGLIO.ID = BOLL_GEST_DETT_AUTORIZZ.FK_BOLLGESTDET_ID INNER JOIN BOLL_GEST_MERCATI_DETT ON BOLL_GEST_DETT_AUTORIZZ.IDCOMUNE = BOLL_GEST_MERCATI_DETT.IDCOMUNE AND BOLL_GEST_DETT_AUTORIZZ.ID = BOLL_GEST_MERCATI_DETT.FK_ID_GEST_AUTORIZZAZIONI AND BOLL_GEST_MERCATI_DETT.FK_BOLLGEST_ID IS NULL) WHERE RNUM = 1) TESTATA ON (BOLL_GEST_MERCATI_DETT.IDCOMUNE = TESTATA.IDCOMUNE AND BOLL_GEST_MERCATI_DETT.ID = TESTATA.ID) WHEN MATCHED THEN UPDATE SET BOLL_GEST_MERCATI_DETT.FK_BOLLGEST_ID = TESTATA.FK_BOLLGEST_ID;
MERGE INTO BOLL_GEST_ONERI_SEQUENCE USING (SELECT IDCOMUNE, ID_BOLLEGEST_DETT, ID_BOLLEGEST_ONERI, FK_BOLLGEST_ID, RNUM FROM (SELECT BOLL_GEST_ONERI_SEQUENCE.IDCOMUNE, BOLL_GEST_ONERI_SEQUENCE.ID_BOLLEGEST_DETT, BOLL_GEST_ONERI_SEQUENCE.ID_BOLLEGEST_ONERI, BOLL_GEST_TESTATA.ID AS FK_BOLLGEST_ID, ROW_NUMBER() OVER(PARTITION BY BOLL_GEST_ONERI_SEQUENCE.IDCOMUNE, BOLL_GEST_ONERI_SEQUENCE.ID_BOLLEGEST_DETT, BOLL_GEST_ONERI_SEQUENCE.ID_BOLLEGEST_ONERI ORDER BY BOLL_GEST_ONERI_SEQUENCE.IDCOMUNE ASC, BOLL_GEST_ONERI_SEQUENCE.ID_BOLLEGEST_DETT ASC, BOLL_GEST_ONERI_SEQUENCE.ID_BOLLEGEST_ONERI ASC) AS RNUM FROM BOLL_GEST_TESTATA INNER JOIN BOLL_GEST_DETTAGLIO ON BOLL_GEST_TESTATA.IDCOMUNE = BOLL_GEST_DETTAGLIO.IDCOMUNE AND BOLL_GEST_TESTATA.ID = BOLL_GEST_DETTAGLIO.FK_BOLLGEST_ID INNER JOIN BOLL_GEST_ONERI_SEQUENCE ON BOLL_GEST_DETTAGLIO.IDCOMUNE = BOLL_GEST_ONERI_SEQUENCE.IDCOMUNE AND BOLL_GEST_DETTAGLIO.ID = BOLL_GEST_ONERI_SEQUENCE.ID_BOLLEGEST_DETT AND BOLL_GEST_ONERI_SEQUENCE.FK_BOLLGEST_ID IS NULL) WHERE RNUM = 1) TESTATA ON (BOLL_GEST_ONERI_SEQUENCE.IDCOMUNE = TESTATA.IDCOMUNE AND BOLL_GEST_ONERI_SEQUENCE.ID_BOLLEGEST_DETT = TESTATA.ID_BOLLEGEST_DETT AND BOLL_GEST_ONERI_SEQUENCE.ID_BOLLEGEST_ONERI = TESTATA.ID_BOLLEGEST_ONERI) WHEN MATCHED THEN UPDATE SET BOLL_GEST_ONERI_SEQUENCE.FK_BOLLGEST_ID = TESTATA.FK_BOLLGEST_ID;


ALTER TABLE BOLL_GEST_DETT_AUTORIZZ MODIFY FK_BOLLGEST_ID NUMBER(4,0) NOT NULL;
ALTER TABLE BOLL_GEST_DETT_RATE MODIFY FK_BOLLGEST_ID NUMBER(4,0) NOT NULL;
ALTER TABLE BOLL_GEST_ISTANZEONERI MODIFY FK_BOLLGEST_ID NUMBER(4,0) NOT NULL;
ALTER TABLE BOLL_GEST_MERCATI_DETT MODIFY FK_BOLLGEST_ID NUMBER(4,0) NOT NULL;
ALTER TABLE BOLL_GEST_ONERI_SEQUENCE MODIFY FK_BOLLGEST_ID NUMBER(4,0) NOT NULL;


CREATE TABLE MESSAGGI_RABBIT(
IDCOMUNE VARCHAR2(6 CHAR) NOT NULL,
GUID VARCHAR2(40 CHAR) NOT NULL,
TOPIC VARCHAR2(50 CHAR) NOT NULL,
MESSAGGIO CLOB NOT NULL,
DATA_TRASMISSIONE DATE
);

ALTER TABLE MESSAGGI_RABBIT ADD CONSTRAINT PK_MESSAGGIRABBIT PRIMARY KEY (IDCOMUNE,GUID);

create TABLE TIPIMOVIMENTO_RABBIT (
IDCOMUNE VARCHAR2(6 char) NOT NULL,
fk_tipimovimento VARCHAR2(8 char) not null,
fk_mailtipo NUMBER(4,0) not null,
topic VARCHAR(50 char)
);

ALTER TABLE TIPIMOVIMENTO_RABBIT ADD CONSTRAINT PK_TIPIMOVRABBIT  PRIMARY KEY (IDCOMUNE,fk_tipimovimento,fk_mailtipo);
ALTER TABLE TIPIMOVIMENTO_RABBIT ADD CONSTRAINT FK_TIPIMOV_TIPIMOVRABBIT FOREIGN KEY (IDCOMUNE,fk_tipimovimento) REFERENCES tipimovimento (IDCOMUNE,TIPOMOVIMENTO);
ALTER TABLE TIPIMOVIMENTO_RABBIT ADD CONSTRAINT FK_MAILTIPO_TIPIMOVRABBIT FOREIGN KEY (IDCOMUNE,fk_mailtipo) REFERENCES mailtipo(IDCOMUNE,CODICEMAIL);

CREATE TABLE BOLL_CFG_TIPO_METADATI(IDCOMUNE VARCHAR2(6 CHAR) NOT NULL, ID DECIMAL(10,0) NOT NULL, CODICECOMUNE VARCHAR2(5 CHAR) NULL, FK_BOLLCFGTIPO_ID DECIMAL(4,0) NOT NULL, CHIAVE VARCHAR2(60 CHAR) NOT NULL, VALORE VARCHAR2(500 CHAR) NOT NULL);
ALTER TABLE BOLL_CFG_TIPO_METADATI ADD CONSTRAINT PK_BOLLCFGTIPOMETADATI PRIMARY KEY(IDCOMUNE,ID);
ALTER TABLE BOLL_CFG_TIPO_METADATI ADD CONSTRAINT FK_BOLLCFGTIPOMETADATI_001 FOREIGN KEY(IDCOMUNE,FK_BOLLCFGTIPO_ID) REFERENCES BOLL_CFG_TIPO(IDCOMUNE,ID);
ALTER TABLE BOLL_CFG_TIPO_METADATI ADD CONSTRAINT FK_BOLLCFGTIPOMETADATI_002 FOREIGN KEY(CODICECOMUNE) REFERENCES COMUNI(CODICECOMUNE);
CREATE INDEX IDX_BOLLCFGTIPOMETADATI_001 ON BOLL_CFG_TIPO_METADATI(IDCOMUNE,FK_BOLLCFGTIPO_ID);
CREATE INDEX IDX_BOLLCFGTIPOMETADATI_002 ON BOLL_CFG_TIPO_METADATI(CODICECOMUNE);
CREATE TABLE MASSIVE_TPROT_METADATI(IDCOMUNE VARCHAR2(6 CHAR) NOT NULL, ID DECIMAL(10,0) NOT NULL, FK_MASSIVETPROT_ID DECIMAL(6,0) NOT NULL, FKID_TESTATA DECIMAL(6,0) NOT NULL, CODICECOMUNE VARCHAR2(5 CHAR) NULL, CHIAVE VARCHAR2(60 CHAR) NOT NULL, VALORE VARCHAR2(500 CHAR) NULL);
ALTER TABLE MASSIVE_TPROT_METADATI ADD CONSTRAINT PK_MASSIVETPROTMETADATI PRIMARY KEY(IDCOMUNE,ID,CHIAVE);
ALTER TABLE MASSIVE_TPROT_METADATI ADD CONSTRAINT FK_MASSIVETPROTMETADATI_001 FOREIGN KEY(IDCOMUNE,FK_MASSIVETPROT_ID) REFERENCES MASSIVE_T_PROTOCOLLO(IDCOMUNE,ID);
ALTER TABLE MASSIVE_TPROT_METADATI ADD CONSTRAINT FK_MASSIVETPROTMETADATI_002 FOREIGN KEY(IDCOMUNE,FKID_TESTATA) REFERENCES MASSIVE_TESTATA(IDCOMUNE,ID);
ALTER TABLE MASSIVE_TPROT_METADATI ADD CONSTRAINT FK_MASSIVETPROTMETADATI_003 FOREIGN KEY(CODICECOMUNE) REFERENCES COMUNI(CODICECOMUNE);
CREATE INDEX IDX_MASSIVETPROTMETADATI_001 ON MASSIVE_TPROT_METADATI(IDCOMUNE,FK_MASSIVETPROT_ID);
CREATE INDEX IDX_MASSIVETPROTMETADATI_002 ON MASSIVE_TPROT_METADATI(IDCOMUNE,FKID_TESTATA);


ALTER TABLE tipisoggetto ADD descrizione_estesa VARCHAR2(400 char);
ALTER TABLE alberoproc_tipisoggetto ADD override_descrizione VARCHAR(400 char);
ALTER TABLE alberoproc_tipisoggetto ADD obbligatorio number(1,0);
ALTER TABLE alberoproc_tipisoggetto ADD occorrenze_max number(2,0);

MERGE INTO alberoproc_tipisoggetto t1
USING (
	SELECT idcomune
		,FK_CODICETIPOSOGGETTO
		, FO_OBBLIGATORIO
		,rnum
	FROM (
		SELECT alberoproc_tipisoggetto.idcomune
			,alberoproc_tipisoggetto.FK_CODICETIPOSOGGETTO
			, FO_OBBLIGATORIO
			,ROW_NUMBER() OVER (
				PARTITION BY alberoproc_tipisoggetto.idcomune
				,alberoproc_tipisoggetto.FK_CODICETIPOSOGGETTO ORDER BY alberoproc_tipisoggetto.idcomune ASC
					,alberoproc_tipisoggetto.FK_CODICETIPOSOGGETTO ASC
				) AS rnum
		FROM alberoproc_tipisoggetto
		INNER JOIN tipisoggetto ON alberoproc_tipisoggetto.idcomune = tipisoggetto.idcomune
			AND alberoproc_tipisoggetto.FK_CODICETIPOSOGGETTO = tipisoggetto.CODICETIPOSOGGETTO
		)
	WHERE rnum = 1
	) t2
	ON (
			t1.idcomune = t2.idcomune
			AND t1.FK_CODICETIPOSOGGETTO = t2.FK_CODICETIPOSOGGETTO
			)
WHEN MATCHED
	THEN
		UPDATE
		SET t1.obbligatorio = coalesce(FO_OBBLIGATORIO,0);


ALTER TABLE alberoproc_tipisoggetto MODIFY obbligatorio number(1,0) DEFAULT 0 NOT NULL ;

ALTER TABLE PROTOCOLLO MODIFY ORDINE NUMBER(3,0);



ALTER TABLE tipimovimento_app_io_servizi ADD TEMPLATE_OGGETTO VARCHAR2(120 CHAR);
ALTER TABLE tipimovimento_app_io_servizi ADD TEMPLATE_MESSAGGIO CLOB;



CREATE TABLE TIPIMOV_APPIOSERVIZI_INT (
  IDCOMUNE VARCHAR2(6 CHAR) NOT NULL,
  TIPOMOVIMENTO VARCHAR2(8 CHAR) NOT NULL,
  FK_ALBEROPROC_SCID NUMBER(10,0) NOT NULL,
  IDENTIFICATIVO_SERVIZIO VARCHAR2(50 CHAR) NOT NULL,
  TEMPLATE_OGGETTO VARCHAR2(120 CHAR),
  TEMPLATE_MESSAGGIO CLOB
) ;


ALTER TABLE TIPIMOV_APPIOSERVIZI_INT ADD CONSTRAINT PK_APPIOSERVINT PRIMARY KEY (IDCOMUNE,TIPOMOVIMENTO,FK_ALBEROPROC_SCID,IDENTIFICATIVO_SERVIZIO); 
ALTER TABLE TIPIMOV_APPIOSERVIZI_INT ADD CONSTRAINT FK_TIPIMOVIOSERVINT_SERV FOREIGN KEY (IDCOMUNE, IDENTIFICATIVO_SERVIZIO) REFERENCES APP_IO_SERVIZI (IDCOMUNE, IDENTIFICATIVO_SERVIZIO);
ALTER TABLE TIPIMOV_APPIOSERVIZI_INT ADD CONSTRAINT FK_TIPIMOVIOSERVINT_TMOV FOREIGN KEY (IDCOMUNE, TIPOMOVIMENTO) REFERENCES TIPIMOVIMENTO (IDCOMUNE, TIPOMOVIMENTO);
ALTER TABLE TIPIMOV_APPIOSERVIZI_INT ADD CONSTRAINT FK_TIPIMOVIOSERVINT_AP FOREIGN KEY (IDCOMUNE, FK_ALBEROPROC_SCID) REFERENCES ALBEROPROC(IDCOMUNE, SC_ID);



CREATE TABLE TIPIMOV_APPIOSERVIZI_ENDO (
  IDCOMUNE VARCHAR2(6 CHAR) NOT NULL,
  TIPOMOVIMENTO VARCHAR2(8 CHAR) NOT NULL,
  CODICEINVENTARIO NUMBER(10,0) NOT NULL,
  IDENTIFICATIVO_SERVIZIO VARCHAR2(50 CHAR) NOT NULL,
  TEMPLATE_OGGETTO VARCHAR2(120 CHAR),
  TEMPLATE_MESSAGGIO CLOB
) ;


ALTER TABLE TIPIMOV_APPIOSERVIZI_ENDO ADD CONSTRAINT PK_APPIOSERVENDO PRIMARY KEY (IDCOMUNE,TIPOMOVIMENTO,CODICEINVENTARIO,IDENTIFICATIVO_SERVIZIO); 
ALTER TABLE TIPIMOV_APPIOSERVIZI_ENDO ADD CONSTRAINT FK_TIPIMOVIOSERVENDO_SERV FOREIGN KEY (IDCOMUNE, IDENTIFICATIVO_SERVIZIO) REFERENCES APP_IO_SERVIZI (IDCOMUNE, IDENTIFICATIVO_SERVIZIO);
ALTER TABLE TIPIMOV_APPIOSERVIZI_ENDO ADD CONSTRAINT FK_TIPIMOVIOSERVENDO_TMOV FOREIGN KEY (IDCOMUNE, TIPOMOVIMENTO) REFERENCES TIPIMOVIMENTO (IDCOMUNE, TIPOMOVIMENTO);
ALTER TABLE TIPIMOV_APPIOSERVIZI_ENDO ADD CONSTRAINT FK_TIPIMOVIOSERVENDO_ENDO FOREIGN KEY (IDCOMUNE, CODICEINVENTARIO) REFERENCES INVENTARIOPROCEDIMENTI(IDCOMUNE, CODICEINVENTARIO);


