<?xml version="1.0" ?><wsdl:definitions targetNamespace="http://sigepro.init.it/rte/definitions" xmlns:sch0="http://sigepro.init.it/rte" xmlns:sch1="http://sigepro.init.it/rte/types" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://sigepro.init.it/rte/definitions" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
<schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://sigepro.init.it/rte/elements" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:sch0="http://sigepro.init.it/rte" xmlns:sch1="http://sigepro.init.it/rte/types" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://sigepro.init.it/rte" xmlns:types="http://sigepro.init.it/rte/types" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
			<import namespace="http://sigepro.init.it/rte" schemaLocation="stc.xsd"></import>
		</schema>
  </wsdl:types>
  <wsdl:message name="InserimentoPraticaResponse">
    <wsdl:part element="sch0:InserimentoPraticaResponse" name="InserimentoPraticaResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="AllegatoBinarioResponse">
    <wsdl:part element="sch0:AllegatoBinarioResponse" name="AllegatoBinarioResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="RichiestaPraticheListaRequest">
    <wsdl:part element="sch0:RichiestaPraticheListaRequest" name="RichiestaPraticheListaRequest">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="DirezioneSportelloResponse">
    <wsdl:part element="sch0:DirezioneSportelloResponse" name="DirezioneSportelloResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="RichiestaPraticaCollegataDaAttivitaDestinataria">
    <wsdl:part element="sch0:RichiestaPraticaCollegataDaAttivitaDestinatariaRequest" name="RichiestaPraticaCollegataDaAttivitaDestinatariaRequest">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="CheckTokenRequest">
    <wsdl:part element="sch0:CheckTokenRequest" name="CheckTokenRequest">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="LoginResponse">
    <wsdl:part element="sch0:LoginResponse" name="LoginResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="NotificaAttivitaRequest">
    <wsdl:part element="sch0:NotificaAttivitaRequest" name="NotificaAttivitaRequest">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="RichiestaPraticheListaResponse">
    <wsdl:part element="sch0:RichiestaPraticheListaResponse" name="RichiestaPraticheListaResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="InserimentoPraticaRequest">
    <wsdl:part element="sch0:InserimentoPraticaRequest" name="InserimentoPraticaRequest">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="RichiestaPraticaCollegataRequest">
    <wsdl:part element="sch0:RichiestaPraticaCollegataRequest" name="RichiestaPraticaCollegataRequest">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="RichiestaPraticaCollegataResponse">
    <wsdl:part element="sch0:RichiestaPraticaCollegataResponse" name="RichiestaPraticaCollegataResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="RichiestaPraticaCollegataDaAttivitaMittente">
    <wsdl:part element="sch0:RichiestaPraticaCollegataDaAttivitaMittenteRequest" name="RichiestaPraticaCollegataDaAttivitaMittenteRequest">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="AggiungiDocumentiRequest">
    <wsdl:part element="sch0:AggiungiDocumentiRequest" name="AggiungiDocumentiRequest">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="CheckTokenResponse">
    <wsdl:part element="sch0:CheckTokenResponse" name="CheckTokenResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="LoginRequest">
    <wsdl:part element="sch0:LoginRequest" name="LoginRequest">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="RichiestaPraticaCollegataDaAttivitaDestinatariaResponse">
    <wsdl:part element="sch0:RichiestaPraticaCollegataResponse" name="RichiestaPraticaCollegataResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="CancellaAttivitaResponse">
  </wsdl:message>
  <wsdl:message name="DirezioneSportelloRequest">
    <wsdl:part element="sch0:DirezioneSportelloRequest" name="DirezioneSportelloRequest">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="RichiestaPraticaRequest">
    <wsdl:part element="sch0:RichiestaPraticaRequest" name="RichiestaPraticaRequest">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="AggiungiDocumentiResponse">
    <wsdl:part element="sch0:AggiungiDocumentiResponse" name="AggiungiDocumentiResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="CancellaAttivita">
    <wsdl:part element="sch0:CancellaAttivitaRequest" name="CancellaAttivitaRequest">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="NotificaAttivitaResponse">
    <wsdl:part element="sch0:NotificaAttivitaResponse" name="NotificaAttivitaResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="RichiestaPraticaCollegataDaAttivitaMittenteResponse">
    <wsdl:part element="sch0:RichiestaPraticaCollegataResponse" name="RichiestaPraticaCollegataResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="AllegatoBinarioRequest">
    <wsdl:part element="sch0:AllegatoBinarioRequest" name="AllegatoBinarioRequest">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="RichiestaPraticaResponse">
    <wsdl:part element="sch0:RichiestaPraticaResponse" name="RichiestaPraticaResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="Stc">
    <wsdl:operation name="CheckToken">
      <wsdl:input message="tns:CheckTokenRequest" name="CheckTokenRequest">
    </wsdl:input>
      <wsdl:output message="tns:CheckTokenResponse" name="CheckTokenResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="Login">
      <wsdl:input message="tns:LoginRequest" name="LoginRequest">
    </wsdl:input>
      <wsdl:output message="tns:LoginResponse" name="LoginResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="DirezioneSportello">
      <wsdl:input message="tns:DirezioneSportelloRequest" name="DirezioneSportelloRequest">
    </wsdl:input>
      <wsdl:output message="tns:DirezioneSportelloResponse" name="DirezioneSportelloResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="RichiestaPraticheLista">
      <wsdl:input message="tns:RichiestaPraticheListaRequest" name="RichiestaPraticheListaRequest">
    </wsdl:input>
      <wsdl:output message="tns:RichiestaPraticheListaResponse" name="RichiestaPraticheListaResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="NotificaAttivita">
      <wsdl:input message="tns:NotificaAttivitaRequest" name="NotificaAttivitaRequest">
    </wsdl:input>
      <wsdl:output message="tns:NotificaAttivitaResponse" name="NotificaAttivitaResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="RichiestaPraticaCollegata">
      <wsdl:input message="tns:RichiestaPraticaCollegataRequest" name="RichiestaPraticaCollegataRequest">
    </wsdl:input>
      <wsdl:output message="tns:RichiestaPraticaCollegataResponse" name="RichiestaPraticaCollegataResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="AllegatoBinario">
      <wsdl:input message="tns:AllegatoBinarioRequest" name="AllegatoBinarioRequest">
    </wsdl:input>
      <wsdl:output message="tns:AllegatoBinarioResponse" name="AllegatoBinarioResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="InserimentoPratica">
      <wsdl:input message="tns:InserimentoPraticaRequest" name="InserimentoPraticaRequest">
    </wsdl:input>
      <wsdl:output message="tns:InserimentoPraticaResponse" name="InserimentoPraticaResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="RichiestaPratica">
      <wsdl:input message="tns:RichiestaPraticaRequest" name="RichiestaPraticaRequest">
    </wsdl:input>
      <wsdl:output message="tns:RichiestaPraticaResponse" name="RichiestaPraticaResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="AggiungiDocumenti">
      <wsdl:input message="tns:AggiungiDocumentiRequest" name="AggiungiDocumentiRequest">
    </wsdl:input>
      <wsdl:output message="tns:AggiungiDocumentiResponse" name="AggiungiDocumentiResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="CancellaAttivita">
      <wsdl:input message="tns:CancellaAttivita" name="CancellaAttivita">
    </wsdl:input>
      <wsdl:output message="tns:CancellaAttivitaResponse" name="CancellaAttivitaResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="RichiestaPraticaCollegataDaAttivitaMittente">
      <wsdl:input message="tns:RichiestaPraticaCollegataDaAttivitaMittente" name="RichiestaPraticaCollegataDaAttivitaMittente">
    </wsdl:input>
      <wsdl:output message="tns:RichiestaPraticaCollegataDaAttivitaMittenteResponse" name="RichiestaPraticaCollegataDaAttivitaMittenteResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="RichiestaPraticaCollegataDaAttivitaDestinataria">
      <wsdl:input message="tns:RichiestaPraticaCollegataDaAttivitaDestinataria" name="RichiestaPraticaCollegataDaAttivitaDestinataria">
    </wsdl:input>
      <wsdl:output message="tns:RichiestaPraticaCollegataDaAttivitaDestinatariaResponse" name="RichiestaPraticaCollegataDaAttivitaDestinatariaResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="StcSoap11" type="tns:Stc">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"></soap:binding>
    <wsdl:operation name="CheckToken">
      <soap:operation soapAction=""></soap:operation>
      <wsdl:input name="CheckTokenRequest">
        <soap:body use="literal"></soap:body>
      </wsdl:input>
      <wsdl:output name="CheckTokenResponse">
        <soap:body use="literal"></soap:body>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="Login">
      <soap:operation soapAction=""></soap:operation>
      <wsdl:input name="LoginRequest">
        <soap:body use="literal"></soap:body>
      </wsdl:input>
      <wsdl:output name="LoginResponse">
        <soap:body use="literal"></soap:body>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="DirezioneSportello">
      <soap:operation soapAction=""></soap:operation>
      <wsdl:input name="DirezioneSportelloRequest">
        <soap:body use="literal"></soap:body>
      </wsdl:input>
      <wsdl:output name="DirezioneSportelloResponse">
        <soap:body use="literal"></soap:body>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="RichiestaPraticheLista">
      <soap:operation soapAction=""></soap:operation>
      <wsdl:input name="RichiestaPraticheListaRequest">
        <soap:body use="literal"></soap:body>
      </wsdl:input>
      <wsdl:output name="RichiestaPraticheListaResponse">
        <soap:body use="literal"></soap:body>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="NotificaAttivita">
      <soap:operation soapAction=""></soap:operation>
      <wsdl:input name="NotificaAttivitaRequest">
        <soap:body use="literal"></soap:body>
      </wsdl:input>
      <wsdl:output name="NotificaAttivitaResponse">
        <soap:body use="literal"></soap:body>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="RichiestaPraticaCollegata">
      <soap:operation soapAction=""></soap:operation>
      <wsdl:input name="RichiestaPraticaCollegataRequest">
        <soap:body use="literal"></soap:body>
      </wsdl:input>
      <wsdl:output name="RichiestaPraticaCollegataResponse">
        <soap:body use="literal"></soap:body>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="AllegatoBinario">
      <soap:operation soapAction=""></soap:operation>
      <wsdl:input name="AllegatoBinarioRequest">
        <soap:body use="literal"></soap:body>
      </wsdl:input>
      <wsdl:output name="AllegatoBinarioResponse">
        <soap:body use="literal"></soap:body>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="InserimentoPratica">
      <soap:operation soapAction=""></soap:operation>
      <wsdl:input name="InserimentoPraticaRequest">
        <soap:body use="literal"></soap:body>
      </wsdl:input>
      <wsdl:output name="InserimentoPraticaResponse">
        <soap:body use="literal"></soap:body>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="RichiestaPratica">
      <soap:operation soapAction=""></soap:operation>
      <wsdl:input name="RichiestaPraticaRequest">
        <soap:body use="literal"></soap:body>
      </wsdl:input>
      <wsdl:output name="RichiestaPraticaResponse">
        <soap:body use="literal"></soap:body>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="AggiungiDocumenti">
      <soap:operation soapAction=""></soap:operation>
      <wsdl:input name="AggiungiDocumentiRequest">
        <soap:body use="literal"></soap:body>
      </wsdl:input>
      <wsdl:output name="AggiungiDocumentiResponse">
        <soap:body use="literal"></soap:body>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="CancellaAttivita">
      <soap:operation soapAction="" style="document"></soap:operation>
      <wsdl:input name="CancellaAttivita">
        <soap:body use="literal"></soap:body>
      </wsdl:input>
      <wsdl:output name="CancellaAttivitaResponse">
        <soap:body use="literal"></soap:body>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="RichiestaPraticaCollegataDaAttivitaDestinataria">
      <soap:operation soapAction="" style="document"></soap:operation>
      <wsdl:input name="RichiestaPraticaCollegataDaAttivitaDestinataria">
        <soap:body use="literal"></soap:body>
      </wsdl:input>
      <wsdl:output name="RichiestaPraticaCollegataDaAttivitaDestinatariaResponse">
        <soap:body use="literal"></soap:body>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="RichiestaPraticaCollegataDaAttivitaMittente">
      <soap:operation soapAction="" style="document"></soap:operation>
      <wsdl:input name="RichiestaPraticaCollegataDaAttivitaMittente">
        <soap:body use="literal"></soap:body>
      </wsdl:input>
      <wsdl:output name="RichiestaPraticaCollegataDaAttivitaMittenteResponse">
        <soap:body use="literal"></soap:body>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="StcService">
    <wsdl:port binding="tns:StcSoap11" name="StcSoap11">
      <soap:address location="https://devel3.vbg.community/ibcstcnew/services/stc"></soap:address>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>