INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M385','CASALI DEL MANCO','CS','CALABRIA','078156','18','COSENZA');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M403','CORIGLIANO-ROSSANO','CS','CALABRIA','078157','18','COSENZA');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M410','RIVA DEL PO','FE','EMILIA-ROMAGNA','038029','08','FERRARA');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M381','TERRE DEL RENO','FE','EMILIA-ROMAGNA','038028','08','FERRARA');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M409','TRESIGNANA','FE','EMILIA-ROMAGNA','038030','08','FERRARA');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M386','ALTA VAL TIDONE','PC','EMILIA-ROMAGNA','033049','08','PIACENZA');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M367','POLESINE ZIBELLO','PR','EMILIA-ROMAGNA','034050','08','PARMA');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M411','SORBOLO MEZZANI','PR','EMILIA-ROMAGNA','034051','08','PARMA');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M364','VENTASSO','RE','EMILIA-ROMAGNA','035046','08','REGGIO EMILIA');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M368','MONTESCUDO-MONTE COLOMBO','RN','EMILIA-ROMAGNA','099029','08','RIMINI');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M324','POGGIO TORRIANA','RN','EMILIA-ROMAGNA','099028','08','RIMINI');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M346','VALVASONE ARZENE','PN','FRIULI-VENEZIA GIULIA','093053','06','PORDENONE');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M311','CAMPOLONGO TAPOGLIANO','UD','FRIULI-VENEZIA GIULIA','030138','06','UDINE');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M400','FIUMICELLO VILLA VICENTINA','UD','FRIULI-VENEZIA GIULIA','030190','06','UDINE');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M399','TREPPO LIGOSULLO','UD','FRIULI-VENEZIA GIULIA','030191','06','UDINE');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M387','MONTALTO CARPASIO','IM','LIGURIA','008068','07','IMPERIA');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M383','ALTA VALLE INTELVI','CO','LOMBARDIA','013253','03','COMO');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M394','CENTRO VALLE INTELVI','CO','LOMBARDIA','013254','03','COMO');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M315','GRAVEDONA ED UNITI','CO','LOMBARDIA','013249','03','COMO');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('I162','SAN SIRO','CO','LOMBARDIA','013248','03','COMO');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M412','SOLBIATE CON CAGNO','CO','LOMBARDIA','013255','03','COMO');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M418','PIADENA DRIZZONA','CR','LOMBARDIA','019116','03','CREMONA');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M348','LA VALLETTA BRIANZA','LC','LOMBARDIA','097092','03','LECCO');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M395','VALVARRONE','LC','LOMBARDIA','097093','03','LECCO');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M393','CASTELGERUNDO','LO','LOMBARDIA','098062','03','LODI');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M396','BORGO MANTOVANO','MN','LOMBARDIA','020072','03','MANTOVA');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M340','BORGOCARBONARA','MN','LOMBARDIA','020071','03','MANTOVA');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('H883','SAN GIORGIO BIGARELLO','MN','LOMBARDIA','020057','03','MANTOVA');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('I632','SERMIDE E FELONICA','MN','LOMBARDIA','020061','03','MANTOVA');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M419','COLLI VERDI','PV','LOMBARDIA','018193','03','PAVIA');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M372','CORTEOLONA E GENZONE','PV','LOMBARDIA','018192','03','PAVIA');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M382','VALFORNACE','MC','MARCHE','043058','11','MACERATA');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M380','COLLI AL METAURO','PU','MARCHE','041069','11','PESARO E URBINO');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M413','SASSOCORVARO AUDITORE','PU','MARCHE','041071','11','PESARO E URBINO');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M379','TERRE ROVERESCHE','PU','MARCHE','041070','11','PESARO E URBINO');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M397','ALLUVIONI PIOVERA','AL','PIEMONTE','006192','01','ALESSANDRIA');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M388','CASSANO SPINOLA','AL','PIEMONTE','006191','01','ALESSANDRIA');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M373','CAMPIGLIA CERVO','BI','PIEMONTE','096086','01','BIELLA');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M371','LESSONA','BI','PIEMONTE','096085','01','BIELLA');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M414','QUAREGNA CERRETO','BI','PIEMONTE','096087','01','BIELLA');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M417','VALDILANA','BI','PIEMONTE','096088','01','BIELLA');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M416','GATTICO-VERUNO','NO','PIEMONTE','003166','01','NOVARA');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M405','VAL DI CHY','TO','PIEMONTE','001317','01','TORINO');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M415','VALCHIUSA','TO','PIEMONTE','001318','01','TORINO');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M370','BORGOMEZZAVALLE','VB','PIEMONTE','103078','01','VERBANO-CUSIO-OSSOLA');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M404','VALLE CANNOBINA','VB','PIEMONTE','103079','01','VERBANO-CUSIO-OSSOLA');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M389','ALTO SERMENZA','VC','PIEMONTE','002170','01','VERCELLI');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M398','CELLIO CON BREIA','VC','PIEMONTE','002171','01','VERCELLI');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('I601','SÈN JAN DI FASSA','GR','TOSCANA','053028','09','GROSSETO');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M349','ALTAVALLE','TN','PROV. AUT. TRENTO','022235','04','TRENTO');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M350','ALTOPIANO DELLA VIGOLANA','TN','PROV. AUT. TRENTO','022236','04','TRENTO');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M351','AMBLAR-DON','TN','PROV. AUT. TRENTO','022237','04','TRENTO');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M352','BORGO CHIESE','TN','PROV. AUT. TRENTO','022238','04','TRENTO');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M353','BORGO LARES','TN','PROV. AUT. TRENTO','022239','04','TRENTO');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M354','CASTEL IVANO','TN','PROV. AUT. TRENTO','022240','04','TRENTO');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M355','CEMBRA LISIGNAGO','TN','PROV. AUT. TRENTO','022241','04','TRENTO');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M314','COMANO TERME','TN','PROV. AUT. TRENTO','022228','04','TRENTO');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M356','CONTÀ','TN','PROV. AUT. TRENTO','022242','04','TRENTO');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M366','DIMARO FOLGARIDA','TN','PROV. AUT. TRENTO','022233','04','TRENTO');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M313','LEDRO','TN','PROV. AUT. TRENTO','022229','04','TRENTO');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M357','MADRUZZO','TN','PROV. AUT. TRENTO','022243','04','TRENTO');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M365','PIEVE DI BONO-PREZZO','TN','PROV. AUT. TRENTO','022234','04','TRENTO');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M358','PORTE DI RENDENA','TN','PROV. AUT. TRENTO','022244','04','TRENTO');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M344','PREDAIA','TN','PROV. AUT. TRENTO','022230','04','TRENTO');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M359','PRIMIERO SAN MARTINO DI CASTROZZA','TN','PROV. AUT. TRENTO','022245','04','TRENTO');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M390','SAN GIOVANNI DI FASSA','TN','PROV. AUT. TRENTO','022250','04','TRENTO');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M360','SELLA GIUDICARIE','TN','PROV. AUT. TRENTO','022246','04','TRENTO');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M407','TERRE D’ADIGE','TN','PROV. AUT. TRENTO','022251','04','TRENTO');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M361','TRE VILLE','TN','PROV. AUT. TRENTO','022247','04','TRENTO');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M343','VALDAONE','TN','PROV. AUT. TRENTO','022232','04','TRENTO');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M362','VALLELAGHI','TN','PROV. AUT. TRENTO','022248','04','TRENTO');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M375','ALPAGO','BL','VENETO','025072','05','BELLUNO');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M342','LONGARONE','BL','VENETO','025071','05','BELLUNO');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M374','VAL DI ZOLDO','BL','VENETO','025073','05','BELLUNO');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M402','BORGO VENETO','PD','VENETO','028107','05','PADOVA');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M401','BARBARANO MOSSANO','VI','VENETO','024124','05','VICENZA');
INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,REGIONE,CODICEISTAT,CODICEISTATREGIONE,PROVINCIA) VALUES('M384','VAL LIONA','VI','VENETO','024123','05','VICENZA');

update comuni set cf=codicecomune where cf is null and codicecomune='H883';
update comuni set cf=codicecomune where cf is null and codicecomune='I162';
update comuni set cf=codicecomune where cf is null and codicecomune='I601';
update comuni set cf=codicecomune where cf is null and codicecomune='I632';
update comuni set cf=codicecomune where cf is null and codicecomune='M311';
update comuni set cf=codicecomune where cf is null and codicecomune='M313';
update comuni set cf=codicecomune where cf is null and codicecomune='M314';
update comuni set cf=codicecomune where cf is null and codicecomune='M315';
update comuni set cf=codicecomune where cf is null and codicecomune='M324';
update comuni set cf=codicecomune where cf is null and codicecomune='M340';
update comuni set cf=codicecomune where cf is null and codicecomune='M342';
update comuni set cf=codicecomune where cf is null and codicecomune='M343';
update comuni set cf=codicecomune where cf is null and codicecomune='M344';
update comuni set cf=codicecomune where cf is null and codicecomune='M346';
update comuni set cf=codicecomune where cf is null and codicecomune='M348';
update comuni set cf=codicecomune where cf is null and codicecomune='M349';
update comuni set cf=codicecomune where cf is null and codicecomune='M350';
update comuni set cf=codicecomune where cf is null and codicecomune='M351';
update comuni set cf=codicecomune where cf is null and codicecomune='M352';
update comuni set cf=codicecomune where cf is null and codicecomune='M353';
update comuni set cf=codicecomune where cf is null and codicecomune='M354';
update comuni set cf=codicecomune where cf is null and codicecomune='M355';
update comuni set cf=codicecomune where cf is null and codicecomune='M356';
update comuni set cf=codicecomune where cf is null and codicecomune='M357';
update comuni set cf=codicecomune where cf is null and codicecomune='M358';
update comuni set cf=codicecomune where cf is null and codicecomune='M359';
update comuni set cf=codicecomune where cf is null and codicecomune='M360';
update comuni set cf=codicecomune where cf is null and codicecomune='M361';
update comuni set cf=codicecomune where cf is null and codicecomune='M362';
update comuni set cf=codicecomune where cf is null and codicecomune='M364';
update comuni set cf=codicecomune where cf is null and codicecomune='M365';
update comuni set cf=codicecomune where cf is null and codicecomune='M366';
update comuni set cf=codicecomune where cf is null and codicecomune='M367';
update comuni set cf=codicecomune where cf is null and codicecomune='M368';
update comuni set cf=codicecomune where cf is null and codicecomune='M370';
update comuni set cf=codicecomune where cf is null and codicecomune='M371';
update comuni set cf=codicecomune where cf is null and codicecomune='M372';
update comuni set cf=codicecomune where cf is null and codicecomune='M373';
update comuni set cf=codicecomune where cf is null and codicecomune='M374';
update comuni set cf=codicecomune where cf is null and codicecomune='M375';
update comuni set cf=codicecomune where cf is null and codicecomune='M379';
update comuni set cf=codicecomune where cf is null and codicecomune='M380';
update comuni set cf=codicecomune where cf is null and codicecomune='M381';
update comuni set cf=codicecomune where cf is null and codicecomune='M382';
update comuni set cf=codicecomune where cf is null and codicecomune='M383';
update comuni set cf=codicecomune where cf is null and codicecomune='M384';
update comuni set cf=codicecomune where cf is null and codicecomune='M385';
update comuni set cf=codicecomune where cf is null and codicecomune='M386';
update comuni set cf=codicecomune where cf is null and codicecomune='M387';
update comuni set cf=codicecomune where cf is null and codicecomune='M388';
update comuni set cf=codicecomune where cf is null and codicecomune='M389';
update comuni set cf=codicecomune where cf is null and codicecomune='M390';
update comuni set cf=codicecomune where cf is null and codicecomune='M393';
update comuni set cf=codicecomune where cf is null and codicecomune='M394';
update comuni set cf=codicecomune where cf is null and codicecomune='M395';
update comuni set cf=codicecomune where cf is null and codicecomune='M396';
update comuni set cf=codicecomune where cf is null and codicecomune='M397';
update comuni set cf=codicecomune where cf is null and codicecomune='M398';
update comuni set cf=codicecomune where cf is null and codicecomune='M399';
update comuni set cf=codicecomune where cf is null and codicecomune='M400';
update comuni set cf=codicecomune where cf is null and codicecomune='M401';
update comuni set cf=codicecomune where cf is null and codicecomune='M402';
update comuni set cf=codicecomune where cf is null and codicecomune='M403';
update comuni set cf=codicecomune where cf is null and codicecomune='M404';
update comuni set cf=codicecomune where cf is null and codicecomune='M405';
update comuni set cf=codicecomune where cf is null and codicecomune='M407';
update comuni set cf=codicecomune where cf is null and codicecomune='M409';
update comuni set cf=codicecomune where cf is null and codicecomune='M410';
update comuni set cf=codicecomune where cf is null and codicecomune='M411';
update comuni set cf=codicecomune where cf is null and codicecomune='M412';
update comuni set cf=codicecomune where cf is null and codicecomune='M413';
update comuni set cf=codicecomune where cf is null and codicecomune='M414';
update comuni set cf=codicecomune where cf is null and codicecomune='M415';
update comuni set cf=codicecomune where cf is null and codicecomune='M416';
update comuni set cf=codicecomune where cf is null and codicecomune='M417';
update comuni set cf=codicecomune where cf is null and codicecomune='M418';
update comuni set cf=codicecomune where cf is null and codicecomune='M419';



Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('FIRMA_REMOTA_ARUBA','TYPE_SEND_OTP','Modalità con cui viene inviato l''otp. Possibili valori: SMS - tramite messaggio, CALL - tramite chiamata. Se attivo IS_GENERA_OTP, se NULL verrà impostato il valore di default CALL');

INSERT INTO verticalizzazioniparametribase (
    modulo,
    parametro,
    descrizione
) VALUES (
    'COMPORTAMENTI_MERCATI',
    'URL_APP_SPUNTA_DIGITALE',
    'L''url dell''APP di spunta digitale.'
);


INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_APSYSTEMS', 'FORMATO_ORA', 'Indica il formato dell''ora presente nel sistema di protocollo. Serve per la lettura di un protocollo e viene agganciato al parametro FORMATO_DATA.');

Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('SIT_CORE','CODICEENTE','Codice Catastale del comune che effettua la chiamata al servizio SIT al Comune di Modena, è strettamente legato al parametro URL_WS_CATASTO perchè tale ws necessita di questo tipo di dato.');

Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('SIT_CORE','URL_WS_CATASTO','Url del web service rest che restituisce i dati relativi al catasto, in particolare il subalterno, viene utilizzato, al momento, solo dal Comune di Modena perchè le viste relative al SIT_CORE non restituitscono questo tipo di dato.');

INSERT INTO verticalizzazioniparametribase (
    modulo,
    parametro,
    descrizione
) VALUES (
    'COMPORTAMENTI_MERCATI',
    'SC_CODICE_IST_NUOV_SPUNTISTA',
    'Indica il codice della voce dell''albero che verrà utilizzata per inserire l''istanza in fase di ''inserimento nuovo spuntista'' '
);



UPDATE AUTORIZZAZIONI SET DATA_RILASCIO = AUTORIZDATA WHERE DATA_RILASCIO IS NULL;
UPDATE AUTORIZZAZIONI_SUBENTRI SET DATA_RILASCIO = AUTORIZDATA WHERE DATA_RILASCIO IS NULL;
INSERT INTO verticalizzazioniparametribase (
    modulo,
    parametro,
    descrizione
) VALUES (
    'COMPORTAMENTI_MERCATI',
    'CODICE_ISTAT_BATTITORI',
    'Indica il codice dettaglio informazione che identifica la tipologia BATTITORI'
);

INSERT INTO verticalizzazioniparametribase (
    modulo,
    parametro,
    descrizione
) VALUES (
    'COMPORTAMENTI_MERCATI',
    'REST_CERCA_COMUNE_LIST_ESCUSI',
    'Nel servizio rest la lista dei codici comuni da escludere, separata da "," es: L219,E256'
);

INSERT INTO verticalizzazioniparametribase (
    modulo,
    parametro,
    descrizione
) VALUES (
    'COMPORTAMENTI_MERCATI',
    'REST_VERIFICA_CF_PIVA',
    'Nel servizio rest ALL''INSERIMENTO DELLO SPUNTISTA VIENE FATTA LA VERIFICA CHE IL CAMPO CF IMPRESA SIA DI 11 CARATTERI SE NUMERICO E 16 SE ALFANUMERICO'
);

INSERT INTO verticalizzazioniparametribase (
    modulo,
    parametro,
    descrizione
) VALUES (
    'PARAMETRI_SISTEMA',
    'NASCONDI_SCRIPT_LOCATION',
    'Serve nascondere lo script di reindirizzamento nel decorator "top.location.href=location.href;".'
);
