ALTER TABLE ALBEROPROC_ENDO ADD (NOTE VARCHAR2(2000) );
ALTER TABLE INVENTARIOPROCEDIMENTI ADD FLAG_RICHIEDEENDO NUMBER(1,0) DEFAULT 0;
ALTER TABLE ALBEROPROC_ENDO ADD (FLAG_RICHIEDEENDO NUMBER(1) default 0);

CREATE TABLE SDEPROXY_STC
  (
    ALIAS            VARCHAR2(20) NOT NULL,
    SOFTWARE         VARCHAR2(2) NOT NULL,
    URL_STC          VARCHAR2(255 CHAR),
    IDNODO_MITT      VARCHAR2(10 CHAR),
    IDENTE_MITT      VARCHAR2(20 CHAR) ,
    IDSPORTELLO_MITT VARCHAR2(10 CHAR),
    USERNAME         VARCHAR2(30 CHAR),
    PASSWORD         VARCHAR2(30 CHAR),
    IDNODO_DEST      VARCHAR2(10 CHAR),
    IDENTE_DEST      VARCHAR2(20 CHAR) ,
    IDSPORTELLO_DEST VARCHAR2(10 CHAR)
  );
ALTER TABLE SDEPROXY_STC ADD CONSTRAINT PK_SDEPROXYSTC PRIMARY KEY (ALIAS, SOFTWARE);

ALTER TABLE RESPONSABILI ADD CIRCOSCRIZIONE VARCHAR2(50);

ALTER TABLE SDEPROXY ADD WS_SERVIZI VARCHAR2(255);
ALTER TABLE SDEPROXY ADD ALIAS_WS_SERVIZI VARCHAR2(20);

CREATE TABLE MASTERKEY(
TABLENAME  NOT NULL VARCHAR2(40), 
COLUMNNAME NOT NULL VARCHAR2(40)
) ;
Alter table masterkey add constraint MASTERKEY_PK primary key(TABLENAME, COLUMNNAME);

ALTER TABLE dyn2_modellid ADD flg_spezza_tabella number(1,0);