INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_FOLIUM', 'URL_WSMAIL', 'Indicare la url del web service di ProtocollazioneMail che ha la facoltà di generare protocolli e inviare PEC. Questo ws va usato se, presente ovviamente, e se il cliente desidera che, venga inviata anche una PEC contestualmente ad una protocollazione in partenza, non può essere usato il ws indicato nel parametro URL in quanto invia solamente il documento principale.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_PAL', 'INVIOPEC', 'Valorizzare a 1 se si desidera utilizzare la funzionalità di invio pec per i protocolli in partenza, qualsiasi altro valore se non si vuole utilizzarla. NB. tale funzionalità è stata introdotta in un secondo momento dal fornitore di protocollo PAL Informatica, quindi verificare, sempre con il fornitore, se tale funzionalità è abilitata o meno, al caso non valorizzare a 1 questo parametro.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_SIDUMBRIA', 'VERSIONE', 'Questo parametro indica la versione del ws che è stato installato, al momento SID presenta due versioni, la 2.0 e la 4.0, nella seconda viene gestita anche la UORDestinatario, ossia l''ufficio destinatario di un protocollo in arrivo. Indicare quindi il valore "4.0" se la versione è la medesima altrimenti "2.0", se la versione non sarà specificata verrà presa in considerazione la prima, ossia la "2.0". Se verrà inserito un valore diverso da quelli specificati verrà sollevato un errore.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE   (modulo, parametro, descrizione ) VALUES ('COMPORTAMENTI_ISTANZE','SEGNA_DOCUMENTO_FIRMATO','Attiva la funzionalità che permettere di segnare come firmato un documento messo alla firma. 0: Non attivo, 1: Attivo' );
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE   (modulo, parametro, descrizione ) VALUES ('ARCHIVIAZIONE_DOC_LEGALDOC','PREFIX_NAME_PACHETTO','Indica il prefisso che verrà utilizzato per nominare il pacchetto contenete i file inviati');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_SIDUMBRIA', 'USA_FTP', 'Valori 1 o altro. Se valorizzato a 1 tutto il sistema di invio files allegati al protocollo avverrà tramite FTP, dovranno quindi essere valorizzati anche i parametri FTP_URL, FTP_USERNAME e FTP_PASSWORD. Con qualsiasi valore diverso da 1 invece, il sistema si comporterà esattamente come prima, i file quindi saranno inviati come byte array direttamente nella request.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_SIDUMBRIA', 'FTP_URL', 'Valorizzare questo parametro con l''indirizzo ftp nel quale inserire i files allegati, sarà preso in considerazione solamente se il parametro USA_FTP è valorizzato a 1');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_SIDUMBRIA', 'FTP_USERNAME', 'Inserire la credenziale di username del server ftp dove saranno inseriti gli allegati, preso in considerazione solamente se il parametro USA_FTP è valorizzato a 1');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_SIDUMBRIA', 'FTP_PASSWORD', 'Inserire la credenziale password del server ftp dove saranno inseriti gli allegati, preso in considerazione solamente se il parametro USA_FTP è valorizzato a 1');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_DOCAREA', 'GESTISCI_FASCICOLAZIONE', 'Valorizzare a 1 se si intende gestire la fascicolazione del componente Standard Docarea. La logica sarà la seguente: il numero e l''anno del fascicolo andranno indicati nella voce Classifica nel seguente formato [CLASSIFICA]/[PROGRESSIVO_FASCICOLO]/[ANNO], se non presenti le ultime due voci (progressivo fascicolo e anno fascicolo), non saranno valorizzati i dati di fascicolo, altrimenti saranno inseriti nell''apposita gestione presente all''interno della segnatura di protocollazione.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_DOCAREA', 'ANNO_FASCICOLO_DEFAULT', 'Indicare l''anno del fascicolo di default che si vuole venga visualizzato per le protocollazioni in partenza, sarà inserito nella voce di classifica con il seguente formato (esempio): 08-04/[PROGRESSIVO_FASCICOLO]/2017, l''ultimo parametro (2017 nell''esempio) sta ad indicare il valore espresso in questo parametro. NB. Se non presente non verrà inserito nessun valore, ma sarà presente solamente la classifica.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_DOCAREA', 'NUMERO_FASCICOLO_DEFAULT', 'Indicare il progressivo del fascicolo di default che si vuole venga visualizzato o utilizzato per le protocollazioni automatiche (ad esempio integrazioni o invio automatico di ricevute) per le protocollazioni in partenza, sarà inserito nella voce di classifica con il seguente formato (esempio): 08-04/[PROGRESSIVO_FASCICOLO]/[ANNO_FASCICOLO], [PROGRESSIVO_FASCICOLO] sta ad indicare il valore espresso in questo parametro. NB. Se non presente non verrà inserito nessun valore, ma sarà presente solamente la classifica. E'' necessario valorizzare anche il parametro ANNO_FASCICOLO_DEFAULT');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_DOCAREA', 'SEPARATORE_FASCICOLO', 'Indicare il separatore che deve essere utilizzato nel campo CLASSIFICA dell''interfaccia di protocollazione che indica la separazione tra il valore di classifica, progressivo fascicolo e anno fascicolo. Di default sarà utilizzato il carattere ''/'', ma se la stessa classifica è separata dal medesimo carattere (ad esempio 08/04) è necessario utilizzare un carattere diverso (ad esempio il punto, il pipe o la virgola). Da utilizzare solo se il valore del parametro GESTISCI_FASCICOLAZIONE è impostato a 1');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE  (modulo, parametro, descrizione ) VALUES ('ARCHIVIAZIONE_DOC_LEGALDOC','ALGORITMO_ARCHIVIAZIONE','specifica l''algoritmo usato per l''archiviazione. ARCHIVIAZIONE_MULTI_ISTANZE: un pacchetto N istanze, ARCHIVIAZIONE_PER_OGGETTO: un pacchetto un oggetto');
INSERT INTO VERTICALIZZAZIONIBASE (MODULO, DESCRIZIONE) VALUES ('PROTOCOLLO_PROTOINF', 'Se attivato gestisce il protocollo PROTOINF, sviluppato dalla ditta IFM Srl.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_PROTOINF', 'URL', 'Indicare in questo parametro l''endpoint a cui fa riferimento il web service di protocollazione.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_PROTOINF', 'CODICE_ENTE', 'In questo parametro va indicato il codice ente definito nel sistema di protocollo, che fa parte delle credenziali per accedere sia all''applicativo che al web service stesso.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_PROTOINF', 'USERNAME', 'In questo parametro va indicato lo username facente parte delle credenziali fornite dagli amministratori di protocollo, che poi sarà l''utente che eseguirà le operazioni di protocollazione invocandone i metodi dei web services.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_PROTOINF', 'PASSWORD', 'In questo parametro va indicata la password facente parte delle credenziali fornite dagli amministratori di protocollo e riferita al parametro USERNAME.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE  (modulo, parametro, descrizione ) VALUES ('STC','LISTA_NODI_MITT_DOWNLOAD_ALLS','Rappresenta la lista degli idnodi ( separata da virgola ) per i quali attivare il comportamento di scaricare subito gli allegati passati come riferimento. E'' il caso ad es. di VIRTUAL-DESK dove devono essere recuperati gli allegati prima della protocollazione. Il parametro non deve essere usato insieme a LISTA_NODI_MITT_GET_ALLEGATI. I valori vanno specificati separati da virgola 410,420,430');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_PROTOINF', 'CODICEAMMINISTRAZIONE', 'Indircare il codice dell''amministrazione relativo al protocollo, questo dato va recuperato dalla tabella di configurazione di ProtoInf2 (PI_DECODI)');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_PROTOINF', 'CODICEAOO', 'questo dato va recuperato dalla tabella di configurazione di ProtoInf2 (PI_DECODI)');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_PROTOINF', 'PATHBASE', 'Percorso base di dove dovranno essere inseriti in upload i files allegati, il percorso dovrà essere raggiungibile dal backoffice. Successivamente il componente si occuperà di creare una sotto-struttura ad albero utile a distinguere i files stessi, il percorso generato prenderà in consederazione il codice dell''oggetto e sarà "paddato" con 10 zeri, il file successivametne avrà come prefisso il codice dell''oggetto stesso. Ad esempio, codice oggetto 24258, 0000\02\42\58\24258-[nome_file]');
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('SIEDER','URL_MODIFICA_STATO_PRATICA','In questo parametro deve essere indicata l''url per i servizi rest esposti dal nodo sieder per la modifica dello stato attuale della pratica in SIEDER');
INSERT INTO VERTICALIZZAZIONIBASE (MODULO, DESCRIZIONE) VALUES ('APPLICA_LAYER_PROT_PDF', 'Se attivata permette di applicare un layer contenente numero e data protocollo ad un pdf associato al movimento');


INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('APPLICA_LAYER_PROT_PDF', 'POSIZIONE_X', 'punto dell''ascisse dove posizionare il testo');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('APPLICA_LAYER_PROT_PDF', 'POSIZIONE_Y', 'punto dell''ordinata dove posizionare il testo');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('APPLICA_LAYER_PROT_PDF', 'ETICHETTA_NUM_PROT', 'etichetta del numero protocollo');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('APPLICA_LAYER_PROT_PDF', 'ETICHETTA_DATA_PROT', 'etichetta della data protocollo');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('APPLICA_LAYER_PROT_PDF', 'NOME_LAYER', 'nome del layer, verrà visualizzato nel pdf e dovrà essere unico');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('APPLICA_LAYER_PROT_PDF', 'FONT_TYPE', 'Tipo di font da impostare al layer. Possibili font GILL_SANS_MT, TIMES_ROMAN, HELVETICA');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('APPLICA_LAYER_PROT_PDF', 'FONT_SIZE', 'Dimesione font da impostare al layer');

Insert into VERTICALIZZAZIONIBASE (MODULO,DESCRIZIONE,FLAG_GESTCOMUNE) values ('WSANAGRAFE_ADRIER','Se attivato permette di recuperare un''anagrafe persona giuridica dai servizi web di ADRIER, la funzionalità viene attivata nelle anagrafiche richiedenti e tecnici sia in inserimento che per controlli successivi e durante la presentazione della dom,anda on-line. Questo modulo va abilitato contestualmente ad un altro modulo WSANAGRAFE_XXX (modulo "principale") dove XXX è CESENA,PIACENZA,... a condizione che il modulo "principale" sia sviluppato tenendo conto della compatibilità con l''integrazione ADRIER. Le indicazioni se un modulo "principale" è compatibile con ADRIER saranno scritte nella descrizione del modulo "principale".','0');
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('WSANAGRAFE_ADRIER','CERCA_SOLO_CF','Se impostato a 1 allora ricerca le anagrafiche ADRIER solamente per codice fiscale impresa'); 
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('WSANAGRAFE_ADRIER','PASSWORD','Password dell''utente abilitato alla ricerca'); 
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('WSANAGRAFE_ADRIER','PROXY_ADDRESS','Url nel formato http[s]://INDIRIZZO:PORTA da utilizzare per effettuare le chiamate al web service di ADRIER'); 
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('WSANAGRAFE_ADRIER','SWITCHCONTROL','Parametro che stabilisce se effettuare la ricerca sul servizio nazionale o meno ( "diretto": accesso diretto alò servizio nazionale, "no" non passa mai dal servizio nazionale, ""/" ":passa dal servizio locale ed eventualmente da quello nazionale'); 
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('WSANAGRAFE_ADRIER','URL','Url del web service (wsdl) da invocare per ricavare i dati anagrafici.Es. ER: https://adritest.lepida.it/AdriGate/services/RicercaImprese?wsdl Nel browser del server application aggiungendo alla URL ''?wsdl'' si può verificare se il server raggiunge il servizio.'); 
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('WSANAGRAFE_ADRIER','USER','E '' l''utente per accedere ai servizi ADRIER, deve essere fornito dal cliente.'); 
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('WSANAGRAFE_ADRIER','XSD','Percorso degli xsd utili per la validazione dei risultati restituiti dai ws di ADRIER');
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('AREA_RISERVATA','URL_AUTHENTICATION_OVERRIDE','Url per personalizzare l''autenticazione sovrascrivendo la configurazione in FO_ARCONFIGURAZIONE.NOME_PARAMETRO_LOGIN_URL.');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_DOCAREA', 'UTENTE_CREAZIONE_PEC', 'UUtilizzare questo parametro solo per la funzionalità di invio PEC utilizzato dal ws di ADS. E'' il parametro che andrà a finire nell''elemento utente_creazione del ws di invio PEC');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) VALUES ('COMPORTAMENTI_ISTANZE','VIS_ICONA_A_IN_LISTAISTANZE','Gestisce la logica di visualizzazione dell'' icona ''A'' sulla lista delle istanze. Può assumere i seguenti valori. NULL : Icona sempre presente se l''istanza ha almeno un autorizzazione/concessione; SOLO_ATTIVE : Icona presente se l''istanza ha almeno un autorizzazione/concessione attiva');

INSERT INTO verticalizzazionibase (modulo, descrizione, flag_gestcomune) VALUES ('FVG_SOL', 'Integrazione tra l''area riservata ed i servizi online del Friuli Venezia Giulia', 0);
INSERT INTO verticalizzazioniparametribase (modulo, parametro, descrizione) VALUES ('FVG_SOL', 'WEB_SERVICE_URL', 'Url del web service utilizzato per lo scambio dati con l''area riservata (in collaudo è http://FegService-collaudo.regione.fvg.it/FormService/api/ws/formsService?wsdl)');
INSERT INTO verticalizzazioniparametribase (modulo, parametro, descrizione) VALUES ('FVG_SOL', 'WEB_SERVICE_USERNAME', 'Username con cui invocare il servizio web di integrazione (in collaudo è admin)');
INSERT INTO verticalizzazioniparametribase (modulo, parametro, descrizione) VALUES ('FVG_SOL', 'WEB_SERVICE_PASSWORD', 'Password con cui invocare il servizio web di integrazione (in collaudo è we5Tg8Np0)');


update responsabili set password='db5034c3eee19e122f13e566fe43a223' where password='202cb962ac59075b964b07152d234b70';
update responsabili set password='db5034c3eee19e122f13e566fe43a223' where password='e10adc3949ba59abbe56e057f20f883e';
update responsabili set password='db5034c3eee19e122f13e566fe43a223' where password='81dc9bdb52d04dc20036dbd8313ed055';
update responsabili set password='db5034c3eee19e122f13e566fe43a223' where password='827ccb0eea8a706c4c34a16891f84e7b';

INSERT INTO VERTICALIZZAZIONIBASE (MODULO, DESCRIZIONE) VALUES ('SORTEGGI', 'Consente la gestione della funzionalità sorteggi');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('SORTEGGI', 'LR_152013_ER', 'Se VALORE = 1 consente di accedere alle funzionalità di Sorteggio L.R. 15/2013 Emilia Romagna');

Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('FVG_SUAP_IN_RETE','ELABORA_DOCUMENTI_XML','Parametro per la configurare dell''analisi dei file xml della domanda. Se rispettano la struttura xsd di fvgDataSet.xsd (presente nel backoffice) verranno trasformati in un oggetto SchedaType inserito durante l''inserimento della pratica. Può assumere i valori S: analisi attiva, N: analisi non attiva');

Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('FVG_SOL','USA_BACKOFFICE_COME_CONSOLE','Se attivo trasforma il backoffice in una console di configurazione. Valori 1:Attivo, 0 o null : Non attivo');
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('FVG_SOL','TEMPIFICAZIONE_ENDO_DEFAULT','Codice della tempificazione di default da inserire in un endoprocedimento se il parametro USA_BACKOFFICE_COME_CONSOLE = 1');
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('FVG_SOL','AMMINISTRAZIONE_ENDO_DEFAULT','Codice dell''amministrazione di default da inserire in un endoprocedimento se il parametro USA_BACKOFFICE_COME_CONSOLE = 1');
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('FVG_SOL','CODICENATURA_ENDO_DEFAULT','Codice della natura di default da inserire in un endoprocedimento se il parametro USA_BACKOFFICE_COME_CONSOLE = 1');
