ALTER TABLE FO_ARCONFIGURAZIONE ADD CODOGGETTO_RIEP_SCHEDE NUMBER(10,0);
ALTER TABLE FO_ARCONFIGURAZIONE ADD CONSTRAINT FK_FOARCONF_OGG_RIEP_SCHEDE FOREIGN KEY (IDCOMUNE, CODOGGETTO_RIEP_SCHEDE) REFERENCES OGGETTI (IDCOMUNE, CODICEOGGETTO);

ALTER TABLE FO_DOMANDE ADD PROVENIENZA VARCHAR2(64 CHAR);