INSERT INTO VERTICALIZZAZIONIBASE (MODULO, DESCRIZIONE) VALUES ('WSDURC','Modulo per attivare le funzionalità di verifica dei documenti DURC esistenti e la richiesta di nuovi.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO, DESCRIZIONE) VALUES ('WSDURC','SERVIZIO_ATTIVO','E'' il nome del servizio che fornisce le informazioni del DURC (WSDURC_INFODURC, ...)');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO, DESCRIZIONE) VALUES ('WSDURC','TIPODOC_ANAGRAFE','E'' la tipologia di documento che al quale associare il DURC o le richieste di verifica; viene anche utilizzata per determinare la data di scadenza qualora non presente nelle informazioni restituite.');
INSERT INTO VERTICALIZZAZIONIBASE (MODULO, DESCRIZIONE) VALUES ('WSDURC_INFODURC','Servizio di cooperazione applicativa per gestire le funzionalità di verifica e la richiesta dei documenti DURC implementato da NUOVAINFORMATICA per l''Osservatorio Cantieri Cassa Edile');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO, DESCRIZIONE) VALUES ('WSDURC_INFODURC','INSTITUTECODE','Codice della Cassa Edile che fornisce il servizio (Es PR00); è comunicato dalla Cassa Edile.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO, DESCRIZIONE) VALUES ('WSDURC_INFODURC','SOFTWARECODEID','Identificativo del software richiedente; il codice è rilasciato dal gestore tecnico del servizio Osservatorio (Nuova Informatica)');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO, DESCRIZIONE) VALUES ('WSDURC_INFODURC','USERID','Codice Utente autorizzato ad utilizzare i servizi ISG dell''Osservatorio Cantieri');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO, DESCRIZIONE) VALUES ('WSDURC_INFODURC','USERPASSWORD','Password dell'' utente autorizzato ad utilizzare i servizi ISG dell''Osservatorio Cantieri');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO, DESCRIZIONE) VALUES ('WSDURC_INFODURC','URLWS_SERVIZIODURC','Indirizzo del wsdl dei servizi INFODURC ES:(STAGE: http://osservatorio.cassaedileweb.it/ServizioDURCTest/WSDurcServiceCE.asmx?WSDL, PRODUZIONE: https://osservatorio.cassaedileweb.it/ServizioDURC/WSDurcServiceCE.asmx?WSDL). Per la produzione è necessario installare nella jvm i certificati rilasciati da NUOVAINFORMATICA');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_DOCER', 'URL_REG_PARTICOLARE', 'Il sistema standard docer ha un web service apposito creato per gestire solo il sistema di registrazione particolare, dentro questo parametro va indicato, appunto, l''end point del servizio che gestisce la registrazione particolare');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_HALLEY', 'RADICE_ALBERO_EDILIZIA', 'Questa funzionalità si attiva solamente se il parametro GENERA_SUAP_XML è valorizzato a 1, va indicata la radice dell''albero dell''edilizia (ad esempio 04, 07 o 0401....) serve per specificare se la pratica è relativa all''edilizia in fase di creazione SUAP o SUEXML. Il sistema infatti, in fase di protocollazione istanza, andrà a verificare se l''intervento specificato ha la stessa radice indicata in questo parametro, in caso positivo si andrà a creare il file SUEXML, altrimenti SUAPXML, in sostanza è la discriminante tra la creazione per il SUAP e il SUE');

INSERT INTO MAPOGGETTI (NOMETABELLA,NOMECAMPO) VALUES ('OGGETTI_DOCER','CODICEOGGETTO');

INSERT INTO METADATI_DIZ_BASE(ID,LABEL,DESCRIZIONE) VALUES ('INITMD_NUMERO_ISTANZA','Numero istanza','Viene riportato il numero della pratica');
INSERT INTO METADATI_DIZ_BASE(ID,LABEL,DESCRIZIONE) VALUES ('INITMD_RICHIEDENTE_CF','Codice fiscale richiedente','Il codice fiscale del richiedente');
INSERT INTO METADATI_DIZ_BASE(ID,LABEL,DESCRIZIONE) VALUES ('INITMD_AZIENDA_CF_PIVA','Codice fiscale o Partita iva dell''azienda','CF o Piva dell''azienda della pratica(se presente)');
INSERT INTO METADATI_DIZ_BASE(ID,LABEL,DESCRIZIONE) VALUES ('INITMD_RICHIEDENTE_DESCRIZIONE','Nome e cognome del richiedente','Nome cognome del richiedente');
INSERT INTO METADATI_DIZ_BASE(ID,LABEL,DESCRIZIONE) VALUES ('INITMD_AZIENDA_RAGIONESOCIALE','Ragione sociale dell''azienda','Ragione sociale della azienda della pratica (se presente)');
INSERT INTO METADATI_DIZ_BASE(ID,LABEL,DESCRIZIONE) VALUES ('INITMD_TIPO_INTERVENTO','Descrizione dell''intervento','La descrizione dell''intervento');
INSERT INTO METADATI_DIZ_BASE(ID,LABEL,DESCRIZIONE) VALUES ('INITMD_DOMICILIO_ELETTRONICO','Il domicilio elettronico della pratica','il domicilio elettronico');
INSERT INTO METADATI_DIZ_BASE(ID,LABEL,DESCRIZIONE) VALUES ('INITMD_CODICEPRATICATELEMATICA','Il codice pratica telematica','Il codicepratica telematica della pratica');
INSERT INTO METADATI_DIZ_BASE(ID,LABEL,DESCRIZIONE) VALUES ('INITMD_DATAPRATICA','Data inserimento pratica','la data di inserimento pratica');
INSERT INTO METADATI_DIZ_BASE(ID,LABEL,DESCRIZIONE) VALUES ('INITMD_SPORTELLO','Modulo software specifico','Il modulo software specifico (Sportello unico, Commercio, ecc...)');
INSERT INTO METADATI_DIZ_BASE(ID,LABEL,DESCRIZIONE) VALUES ('INITMD_RESP_PROCEDIMENTO','Responsabile del procedimento','La descrizione del responsabile del procedimento');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('CART', 'GENERA_ALLEGATI_NOTIFICA', 'Valori ammessi sono S o N. Se il valore è S allora sarà attivata la funzione ''Genera allegati per notifica CART'' nella pagina del movimento.');

INSERT INTO verticalizzazionibase (modulo,descrizione,flag_gestcomune) VALUES ('CID_BARI', 'Verticalizzazione per gestione CID/PIN del comune di Bari', 0);
INSERT INTO verticalizzazioniparametribase (modulo,parametro,descrizione) VALUES ('CID_BARI', 'URL_SERVIZIO', 'Url del servizio da invocare per ottenere i dati relativi a PIN/CID');
INSERT INTO verticalizzazioniparametribase (modulo,parametro,descrizione) VALUES ('CID_BARI', 'IDENTIFICATIVO_UTENTE', 'Identificativo utente da utilizzare per invocare il servizio');
INSERT INTO verticalizzazioniparametribase (modulo,parametro,descrizione) VALUES ('CID_BARI', 'PASSWORD', 'Passphrase da utilizzare per generare la password di chiamata al servizio');

INSERT INTO SOFTWARE (CODICE, DESCRIZIONE, MODULOOPZIONALE, DESCRIZIONELUNGA, ACCESSORAPIDO, ORDINE) VALUES ('A2', 'A.S.L.',1, 'A.S.L. - U.F. Igiene e Sanità Pubblica', 0,59);
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_DOCER', 'URL_PEC', 'Il sistema standard docer ha un web service apposito creato per gestire solo l''invio delle PEC gestito nelle protocollazioni in partenza, dentro questo parametro va indicato, appunto, l''end point del servizio.');
INSERT INTO SOFTWARE(CODICE, DESCRIZIONE, MODULOOPZIONALE, DESCRIZIONELUNGA, ACCESSORAPIDO, ORDINE) VALUES ('IN', 'Infrastrutture', 1, 'Infrastrutture', 0,60);

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_DOCER', 'TIPO_INVIO_PEC', 'Parametro che indica come gestire l''invio della PEC per le protocollazioni in PARTENZA, se non valorizzato o valorizzato a 0 non avverrà nessun invio della PEC e non si presenterà nessun pulsante che possa inviarla durante la protocollazione in partenza, se valorizzato a 1 l''invio della PEC sarà automatico ogni volta che verrà richiesto un protocollo con flusso in PARTENZA, se valorizzato a 2 l''invio della PEC sarà manuale, ossia l''invio sarà subordinato solamente al clic del pulsante INVIA MAIL che viene visualizzato subito dopo che vengono restituiti i dati di protocollo.');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_DOCER', 'TYPE_ID_ANAG_CUSTOM', 'Indica con quale type id devono essere gestite le anagrafiche del web service. Le anagrafiche DocEr hanno un campo denominato type id, che sarebbe una sorta di categoria, questo dato deve essere specificato sia in fase di ricerca che in fase di creazione o aggiornamento anagrafica. Alcuni type id sono fissi, come AOO, ENTE, FASCICOLO E TITOLARIO, esiste poi l''ANAGRAFICA CUSTOM dove indicare il tipo di anagrafica da gestire, ad esempio può essere inserito il valore RICHIEDENTI, AZIENDE....Questo valore deve riportare un tipo di anagrafica custom gestita solo da VBG, ad esempio ANAGRAFICA_VBG, e deve essere prima inserita manualmente dal cliente nel sistema docer e poi riportata in questo valore, in pratica quando si vanno a fare ricerche o inserimenti di anagrafiche, questo type_id deve essere presente nel sistema docer.');

insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) values ('ARCHIVIAZIONE_DOC_LEGALDOC', 'DOC_PRINCIPALE_SEARCH_STRING', 'Lista di stringhe (separate da ;) da ricercare nel nome del file per individuare il documento principale');

INSERT INTO  VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_DOCER', 'ANAG_CUSTOM_CODICE', 'Indicare in questo parametro il nome del campo codice obbligatorio ai fini della gestione delle Anagrafiche Custom su docer, questo campo è obbligatorio su docer se si vuole gestire le anagrafiche custom e deve essere creato lato server, ossia dal cliente.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_DOCER', 'ANAG_CUSTOM_DESCRIZIONE', 'Indicare in questo parametro il nome del campo descrizione obbligatorio ai fini della gestione delle Anagrafiche Custom su docer, questo campo è obbligatorio su docer se si vuole gestire le anagrafiche custom e deve essere creato lato server, ossia dal cliente.');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_IRIDE', 'FORMATO_DATA_FASC', 'Serve per indicare in quale formato deve essere inviata la data di fascicolazione al web service. Maggioli ha creato un altro web service compatibile con Iride (ProtocolloSoap e DocWsFascicoli), solo che la data deve avere formato yyyy-MM-dd altrimenti non viene riconosciuta. Quindi, solo nel momento in cui vengono usati questi web service, il formato data deve essere impostato a yyyy-MM-dd, in generale, comunque, il componente PROTOCOLLO_IRIDE andrà ad impostare la data in base a quanto scritto in questo parametro, quindi, se viene impostato dd-MM-yyyy il sistema invierà ad esempio 23-10-2014, che nel caso specifico di questo web service, restituirà errore, evitare quindi di inserire ulteriori formati. Nel caso del vecchio Iride, non va impostato.');
insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('TARES_BARI', 'URL_SERVIZIO_AGEV_TASI','Url del servizio di agevolazioni TASI');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('ARCHIVIAZIONE_DOC_LEGALDOC', 'CARATTERI_NON_AMMESSI', 'Lista di caratteri non ammessi nel nome dei file da archiviare');

UPDATE SOFTWARE SET DESCRIZIONE='Tributi CAF', descrizionelunga='TRIBUTI - Agevolazioni tramite CAF' where codice='TA';

UPDATE CLMENU_JAVA SET link_standard ='dyn2modellit/list.htm?software=TT' WHERE ID = 447;

INSERT INTO CLMENU_JAVA (ID, DESCRIZIONE, MENULINK, SOFTWARE, JSP, LAYOUTTESTI, LINK_STANDARD, TIPO_FUNZIONALITA) VALUES ('1020', 'Regole', '0AZ32', '*', 'ASP', '0', 'dyn2regole/list.htm?software=SOFTWARE', 'S');
INSERT INTO CLMENU_JAVA (ID, DESCRIZIONE, MENULINK, SOFTWARE, JSP, LAYOUTTESTI, LINK_STANDARD, TIPO_FUNZIONALITA) VALUES ('1021', 'Regole', '00B02', 'TT', 'ASP', '0', 'dyn2regole/list.htm?software=TT', 'S');

insert into software (codice, descrizione, moduloopzionale,descrizionelunga,accessorapido,ordine)
values ('T1', 'Tributi Online', 1,'Modulo per l''accesso all''area riservata degli operatori dell''ente identificati come anagrafiche',0,99);

update verticalizzazionibase set descrizione = 'Se attivato, consente di eseguire la protocollazione con il sistema di INSIEL MERCATO (INSIEL MERCATO è il fornitore del software), deve essere anche inserita la stringa PROTOCOLLO_INSIELMERCATO nel parametro TIPOPROTOCOLLO della verticalizzazione PROTOCOLLO_ATTIVO. L''integrazione con questo protocollo, al momento, è presente al Comune di Fondi. Questo protocollo è simile al protocollo Insiel in quanto un tempo erano la stessa azienda prima della scissione dove sono nate le due aziende, una pubblica (Insiel Mercato) e una privata (Insiel).
Da novembre 2014 è possibile utilizzare la versione 14.01 del web service che noi abbiamo chiamato 2, che gestisce anche l''invio delle pec per le protocollazioni in partenza. Quest''ultimo è possibile utilizzarlo dal client della versione precedente ma non viceversa chiaramente, quindi 
è stato deciso di creare un nuovo client PROTOCOLLO_INSIELMERCATO2 che andrà ad aggiungersi al client PROTOCOLLO_INSIELMERCATO.
In sostanza per utilizzare la versione precedente sulla verticalizzazione PROTOCOLLO_ATTIVO nel parametro TIPOPROTOCOLLO va inserito PROTOCOLLO_INSIELMERCATO, altrimenti se si desidera usare la nuova versione va inserito, nello stesso parametro, il valore PROTOCOLLO_INSIELMERCATO2. 
Visto che i PARAMETRI non hanno differenze saranno comunque usati, per entrambe le versioni, quelli valorizzati sulla verticalizzazione PROTOCOLLO_INSIELMERCATO, anche quelli con TIPOPROTOCOLLO valorizzato a PROTOCOLLO_ INSIELMERCATO2.' where modulo = 'PROTOCOLLO_INSIELMERCATO';

INSERT INTO SOFTWARE(CODICE, DESCRIZIONE, MODULOOPZIONALE, DESCRIZIONELUNGA, ACCESSORAPIDO, ORDINE) VALUES ('MA', 'Mestieri e Artisti di strada', '1', 'Mestieri e Attività Artistiche di strada', '0', '61');

INSERT INTO FO_ARJ_STEPS_PARAMS_BASE (ID,CHIAVE,DESCRIZIONE,FK_FO_ARJ_STEP_BASE) VALUES (1,'NASCONDI_LISTA_STEPS','Nasconde la lista degli step visualizzata sulla pagina. Inserire il valore 1.','BENVENUTO');
insert into FO_ARJ_STEPS_PARAMS_BASE (id,CHIAVE,DESCRIZIONE,FK_FO_ARJ_STEP_BASE) values (2,'ETICHETTA_CHECKBOX','Sovrascrive il testo del checkbox.','INFORMATIVA');
INSERT INTO FO_ARJ_STEPS_PARAMS_BASE (ID,CHIAVE,DESCRIZIONE,FK_FO_ARJ_STEP_BASE) VALUES (3,'VIA_E_CIVICO_OBBLIGATORI','Rende obbligatori i campi nome via e civico. Inserire il valore 1.','LOCALIZZAZIONE');
insert into FO_ARJ_STEPS_PARAMS_BASE (id,CHIAVE,DESCRIZIONE,FK_FO_ARJ_STEP_BASE) values (4,'RIEPILOGO_NON_FIRMATO','Disabilita il controllo della firma digitale sul file di riepilogo. Inserire il valore 1.','RIEPILOGO');

INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE AOSTA','AO00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE ALESSANDRIA','AL00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE ASTI','AT00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE BIELLA','BI00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE CUNEO','CN00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE NOVARA','NO00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE TORINO','TO00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE VERBANIA','VB00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE VERCELLI','VC00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE GENOVA','GE00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE IMPERIA','IM00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE LA SPEZIA','SP00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE SAVONA','SV00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE BERGAMO','BG00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('EDILCASSA ARTIGIANA DI BERGAMO','BG01');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE BRESCIA','BS00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE COMO','CO00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE CREMONA','CR00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE MILANO','MI00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE MANTOVA','MN00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE PIACENZA','PC00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE PAVIA','PV00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE SONDRIO','SO00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE VARESE','VA00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE BOLZANO','BZ00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE TRENTO','TN00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE BELLUNO','BL00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE PADOVA','PD00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE ROVIGO','RO00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE TREVISO','TV00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE VENEZIA','VE00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('C.E.A.V. CASSA EDILE ARTIGIANA VENETA','VE11');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('C.E.V.A. CASSA EDILE VENETA ARTIGIANA','VE21');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE VICENZA','VI00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE VERONA','VR00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE GORIZIA','GO00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE PORDENONE','PN00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE TRIESTE','TS00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE UDINE','UD00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE BOLOGNA','BO00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('C.E.D.A. CASSA EDILE DIPENDENTI ARTIGIANI','BO01');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('C.A.L.E.C. CASSA ASSIST.LAVOR.EDILI DELLE COOPERATIVE','BO03');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('C.E.D.A. I.I.E.R. C. ED. DELL''ART.INTERPROV. IN EM.ROM.','BO11');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE FERRARA','FE00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('C.E.D.A.F. CASSA EDILE DIP. ARTIG. FERRARESI','FE01');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('C.E.L.C.O.F. CASSA EDILE LAV. COOP. FERRARESI','FE03');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE FORLI’','FO00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE DELLE COOPERATIVE','FO03');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE MODENA','MO00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE ED AFFINI DELLA PROVINCIA DI MODENA','MO03');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE PARMA','PR00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE RAVENNA','RA00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE REGGIO EMILIA','RE00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CEMA CASSA EDILE DI MUTUALITA'' ED ASSISTENZA','RE03');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE RIMINI','RN00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE AREZZO','AR00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('F.A.L.E.A. FONDO ASSIST. LAVOR. EDILI ARTIGIANI','AR01');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE FIRENZE','FI00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('C.E.R.T. CASSA EDILE REG. TOSCANA','FI02');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE GROSSETO','GR00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE LIVORNO','LI00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE LUCCA','LU00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE MASSA CARRARA','MS00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE PISA','PI00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE PRATO','PO00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE PISTOIA','PT00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE SIENA','SI00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE ANCONA','AN00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('C.E.D.A.M. CASSA EDILE DELLE MARCHE','AN02');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE ASCOLI PICENO','AP00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE MACERATA','MC00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE PESARO','PS00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE PERUGIA','PG00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE TERNI','TR00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE FROSINONE','FR00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE LATINA','LT00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE RIETI','RI00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE ROMA','RM00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('EDILCASSA DEL LAZIO','RM02');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE VITERBO','VT00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE L’AQUILA','AQ00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('EDILCASSA ABRUZZO - CASSA EDILE REGIONALE','AQ02');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE CHIETI','CH00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE PESCARA','PE00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE TERAMO','TE00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE CAMPOBASSO','CB00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('EDILCASSA REGIONALE MOLISE','CB02');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE AVELLINO','AV00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE BENEVENTO','BN00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE CASERTA','CE00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE NAPOLI','NA00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE SALERNO','SA00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE MATERA','MT00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE POTENZA','PZ00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('EDILCASSA REGIONALE DI BASILICATA','PZ02');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE BARI','BA00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('EDILCASSA DI PUGLIA','BA02');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE BRINDISI','BR00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE FOGGIA','FG00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE LECCE','LE00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE TARANTO','TA00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE CATANZARO','CZ00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE COSENZA','CS00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('REGGIO CALABRIA','RC00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('EDILCASSA REGIONALE CALABRESE','RC02');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE AGRIGENTO','AG00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE CALTANISSETTA','CL00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE CATANIA','CT00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE ENNA','EN00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE MESSINA','ME00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE PALERMO','PA00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE RAGUSA','RG00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE SIRACUSA','SR00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE TRAPANI','TP00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('EDILCASSA SICILIA','PA03');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE CAGLIARI','CA00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('E.R.S. EDILCASSA REGIONALE SARDEGNA','CA02');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE NUORO','NU00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE ORISTANO','OR00');
INSERT INTO ELENCOCASSAEDILEBASE (DESCRIZIONE,CODICE) VALUES ('CASSA EDILE DELLE PROV. DI SASSARI E OLBIA - TEMPIO','SS00');
