package it.gruppoinit.regulus.gestoreincassi;

import java.util.HashMap;
import java.util.Map;

/**
 * Classe utilizzata per memorizzaare tutti possibili ESITI gestiti dal Sistema di pagamento Regulus.
 * 
 * @author francescop
 * 
 */
public class RegulusEsitoConstants {

    public static final Integer I_NO_ERROR = 0;
    public static final Integer W_FATTURA_PAGATA = 4097;
    public static final Integer W_FATTURA_INPAGAMENTO = 4098;
    public static final Integer W_FATTURA_PAGABILE = 4099;
    public static final Integer W_NESSUN_ELEMENTO_TROVATO = 4100;
    public static final Integer W_INFORMAZIONI_INCOMPLETE = 4105;
    public static final Integer E_FATTURA_PAGATA = 769;
    public static final Integer E_RATA_PAGATA = 770;
    public static final Integer E_PAGAMENTO_REGISTRATO = 771;
    public static final Integer E_MULTA_NON_PAGABILE = 772;
    public static final Integer E_FATTURA_NON_TROVATA = 773;
    public static final Integer E_DOCUMENTO_NON_TROVATO = 774;
    public static final Integer E_FUNZIONE_NON_DISPONIBILE = 775;
    public static final Integer E_CAMPO_OBBLIGATORIO_MANCANTE = 776;
    public static final Integer E_TRIBUTO_NON_GESTITO = 777;
    public static final Integer E_RATA_PRENOTATA_DA_ALTRI = 778;
    public static final Integer E_MULTA_PAGATA = 784;
    public static final Integer E_MULTA_INPAGAMENTO = 785;
    public static final Integer E_MULTA_PREN_NON_PAGABILE = 786;
    public static final Integer E_MULTA_PRENOTATA_DA_ALTRI = 787;
    public static final Integer E_MULTA_NON_TROVATA = 800;
    public static final Integer E_IDENTIFICATIVO_NON_VALIDO = 1025;
    public static final Integer E_TARGA_NON_VALIDA = 1026;
    public static final Integer E_GENERIC_EXCEPTION = 1280;
    public static final Integer E_NAMING_EXCEPTION = 1281;
    public static final Integer E_SQL_EXCEPTION = 1282;
    public static final Integer E_CLASS_NOT_FOUND = 1283;
    public static final Integer E_ILLEGAL_ACCESS = 1284;
    public static final Integer E_INSTANTIATION_EXCEPTION = 1285;
    public static final Integer E_FILE_NOT_FOUND = 1286;
    public static final Integer E_IO_EXCEPTION = 1287;
    public static final Integer E_PARSE_EXCEPTION = 1288;
    public static final Integer E_SAX_PARSE_EXCEPTION = 1289;
    public static final Integer E_NULL_OBJECT = 1290;
    public static final Integer E_PARSE_CONFIGURATION_EXCEPTION = 1291;
    public static final Integer E_LINKAGE_ERROR = 1292;
    public static final Integer E_INITIALIZER_EXCEPTION = 1293;
    public static final Integer E_SAX_NOT_SUPPORTED_EXCEPTION = 1294;
    public static final Integer E_SAX_NOT_RECOGNIZED_EXCEPTION = 1295;
    public static final Integer E_DB_CLOSED_EXCEPTION = 1312;
    public static final Integer E_DB_RECORD_NOT_FOUND = 1313;
    public static final Integer E_DB_SEARCH_CONDITION_NOT_FOUND = 1314;
    public static final Integer E_DB_SEARCH_CONDITION_NOT_UNIQUE = 1315;
    public static final Integer E_DB_DATA_MISMATCH = 1316;
    public static final Integer E_SQL_QUERY_ERROR = 1317;
    public static final Integer E_SQL_UPDATE_ERROR = 1318;
    public static final Integer E_SQL_INSERT_ERROR = 1319;
    public static final Integer E_SQL_DELETE_ERROR = 1320;
    public static final Integer LEVEL_INFO = 0;
    public static final Integer LEVEL_WARNING = 1;
    public static final Integer LEVEL_ERROR = 2;
    public static final Integer LEVEL_FATAL = 3;
    public static Map<Integer, Integer> map = new HashMap<Integer, Integer>();
    public static Map<Integer, String> mapDesc = new HashMap<Integer, String>();
    static {
	map.put(I_NO_ERROR, LEVEL_INFO);
	map.put(W_FATTURA_PAGATA, LEVEL_WARNING);
	map.put(W_FATTURA_INPAGAMENTO, LEVEL_WARNING);
	map.put(W_FATTURA_PAGABILE, LEVEL_WARNING);
	map.put(W_NESSUN_ELEMENTO_TROVATO, LEVEL_WARNING);
	map.put(W_INFORMAZIONI_INCOMPLETE, LEVEL_WARNING);
	map.put(E_FATTURA_PAGATA, LEVEL_ERROR);
	map.put(E_RATA_PAGATA, LEVEL_ERROR);
	map.put(E_PAGAMENTO_REGISTRATO, LEVEL_ERROR);
	map.put(E_MULTA_NON_PAGABILE, LEVEL_ERROR);
	map.put(E_FATTURA_NON_TROVATA, LEVEL_ERROR);
	map.put(E_DOCUMENTO_NON_TROVATO, LEVEL_ERROR);
	map.put(E_FUNZIONE_NON_DISPONIBILE, LEVEL_ERROR);
	map.put(E_CAMPO_OBBLIGATORIO_MANCANTE, LEVEL_ERROR);
	map.put(E_TRIBUTO_NON_GESTITO, LEVEL_ERROR);
	map.put(E_RATA_PRENOTATA_DA_ALTRI, LEVEL_ERROR);
	map.put(E_MULTA_PAGATA, LEVEL_ERROR);
	map.put(E_MULTA_INPAGAMENTO, LEVEL_ERROR);
	map.put(E_MULTA_PREN_NON_PAGABILE, LEVEL_ERROR);
	map.put(E_MULTA_PRENOTATA_DA_ALTRI, LEVEL_ERROR);
	map.put(E_IDENTIFICATIVO_NON_VALIDO, LEVEL_ERROR);
	map.put(E_TARGA_NON_VALIDA, LEVEL_ERROR);
	map.put(E_DB_SEARCH_CONDITION_NOT_FOUND, LEVEL_ERROR);
	map.put(E_DB_SEARCH_CONDITION_NOT_UNIQUE, LEVEL_ERROR);
	map.put(E_GENERIC_EXCEPTION, LEVEL_FATAL);
	map.put(E_FILE_NOT_FOUND, LEVEL_FATAL);
	map.put(E_IO_EXCEPTION, LEVEL_FATAL);
	map.put(E_PARSE_EXCEPTION, LEVEL_FATAL);
	map.put(E_SAX_PARSE_EXCEPTION, LEVEL_FATAL);
	map.put(E_PARSE_CONFIGURATION_EXCEPTION, LEVEL_FATAL);
	map.put(E_LINKAGE_ERROR, LEVEL_FATAL);
	map.put(E_INITIALIZER_EXCEPTION, LEVEL_FATAL);
	map.put(E_SAX_NOT_SUPPORTED_EXCEPTION, LEVEL_FATAL);
	map.put(E_SAX_NOT_RECOGNIZED_EXCEPTION, LEVEL_FATAL);
	map.put(E_DB_CLOSED_EXCEPTION, LEVEL_FATAL);
	map.put(E_DB_RECORD_NOT_FOUND, LEVEL_FATAL);
	map.put(E_DB_DATA_MISMATCH, LEVEL_ERROR);
	map.put(E_SQL_QUERY_ERROR, LEVEL_FATAL);
	map.put(E_SQL_UPDATE_ERROR, LEVEL_FATAL);
	map.put(E_SQL_INSERT_ERROR, LEVEL_FATAL);
	map.put(E_SQL_DELETE_ERROR, LEVEL_FATAL);
	map.put(E_NAMING_EXCEPTION, LEVEL_FATAL);
	map.put(E_SQL_EXCEPTION, LEVEL_FATAL);
	map.put(E_CLASS_NOT_FOUND, LEVEL_FATAL);
	map.put(E_ILLEGAL_ACCESS, LEVEL_FATAL);
	map.put(E_NULL_OBJECT, LEVEL_FATAL);
	map.put(E_INSTANTIATION_EXCEPTION, LEVEL_FATAL);
	mapDesc.put(I_NO_ERROR, "");
	mapDesc.put(W_FATTURA_PAGATA, "La fattura ricercata e' gia' pagata");
	mapDesc.put(W_FATTURA_INPAGAMENTO, "La fattura ricercata e' gia' in pagamento");
	mapDesc.put(W_FATTURA_PAGABILE, "La fattura ricercata e' gia' pagabile");
	mapDesc.put(W_NESSUN_ELEMENTO_TROVATO, "Non ci sono elementi che rispettano i parametri di ricerca indicati");
	mapDesc.put(W_INFORMAZIONI_INCOMPLETE, "Alcune delle informazioni richieste non sono recuperabili");
	mapDesc.put(E_FATTURA_PAGATA, "La fattura ricercata e' gia' pagata");
	mapDesc.put(E_RATA_PAGATA, "La rata e' gia' pagata");
	mapDesc.put(E_PAGAMENTO_REGISTRATO, "L'Id Ordine Pagamento e' gia' registrato");
	mapDesc.put(E_MULTA_NON_PAGABILE, "La multa ricercata non e' pagabile");
	mapDesc.put(E_FATTURA_NON_TROVATA, "La fattura ricercata non e' stata trovata");
	mapDesc.put(E_DOCUMENTO_NON_TROVATO, "Il documento cercato non e' stato trovato");
	mapDesc.put(E_FUNZIONE_NON_DISPONIBILE, "La funzionalità richiesta non e' disponibile");
	mapDesc.put(E_CAMPO_OBBLIGATORIO_MANCANTE, "Non e' stato fornito un valore obbligatorio");
	mapDesc.put(E_TRIBUTO_NON_GESTITO, "Il tributo richiesto non e in carico a GestoreIncassi");
	mapDesc.put(E_RATA_PRENOTATA_DA_ALTRI, "La rata non può essere sprenotata in quanto prenotata da altri");
	mapDesc.put(E_MULTA_PAGATA, "La multa non può essere prenotata in quanto già pagata");
	mapDesc.put(E_MULTA_INPAGAMENTO, "La multa non può essere prenotata in quanto già prenotata da un altra richiesta");
	mapDesc.put(E_MULTA_PREN_NON_PAGABILE, "La multa non può essere prenotata in quanto non pagabile");
	mapDesc.put(E_MULTA_PRENOTATA_DA_ALTRI, "La multa non può essere sprenotata in quanto prenotata da altri");
	mapDesc.put(E_IDENTIFICATIVO_NON_VALIDO, "L'identificativo fornito non è corretto");
	mapDesc.put(E_TARGA_NON_VALIDA, "La targa indicata non corrisponde a quella associata al verbale in esame");
	mapDesc.put(E_DB_SEARCH_CONDITION_NOT_FOUND, "Condizione di ricerca su DB non valorizzata");
	mapDesc.put(E_DB_SEARCH_CONDITION_NOT_UNIQUE, "Condizione di ricerca su DB non univoca");
	mapDesc.put(E_GENERIC_EXCEPTION, "Generic Exception");
	mapDesc.put(E_FILE_NOT_FOUND, "File Not Found Exception");
	mapDesc.put(E_IO_EXCEPTION, "IO Exception");
	mapDesc.put(E_PARSE_EXCEPTION, "Parse Exception");
	mapDesc.put(E_SAX_PARSE_EXCEPTION, "SAX Parse Exception");
	mapDesc.put(E_PARSE_CONFIGURATION_EXCEPTION, "DB connection closed Exception");
	mapDesc.put(E_LINKAGE_ERROR, "Linkage Error");
	mapDesc.put(E_INITIALIZER_EXCEPTION, "Initializer Exception");
	mapDesc.put(E_SAX_NOT_SUPPORTED_EXCEPTION, "SAX not supported Exception");
	mapDesc.put(E_SAX_NOT_RECOGNIZED_EXCEPTION, "SAX not recognized Exception");
	mapDesc.put(E_DB_CLOSED_EXCEPTION, "Parse Configuration Exception");
	mapDesc.put(E_DB_RECORD_NOT_FOUND, "DB record not found");
	mapDesc.put(E_DB_DATA_MISMATCH, "Application and DB data mismatch");
	mapDesc.put(E_SQL_QUERY_ERROR, "DB query error");
	mapDesc.put(E_SQL_UPDATE_ERROR, "DB update error");
	mapDesc.put(E_SQL_INSERT_ERROR, "DB insert error");
	mapDesc.put(E_SQL_DELETE_ERROR, "DB delete error");
	mapDesc.put(E_NAMING_EXCEPTION, "Naming Exception");
	mapDesc.put(E_SQL_EXCEPTION, "SQL Exception");
	mapDesc.put(E_CLASS_NOT_FOUND, "Class Not Found Exception");
	mapDesc.put(E_ILLEGAL_ACCESS, "Illegal Access Exception");
	mapDesc.put(E_NULL_OBJECT, "Null Object Exception");
	mapDesc.put(E_INSTANTIATION_EXCEPTION, "Instantiation Exception");
    }
}
