CREATE TABLE MASSIVE_TESTATA(
 IDCOMUNE VARCHAR2(6 CHAR)  NOT NULL, 
 ID NUMBER(6,0) NOT NULL,
 DESCRIZIONE VARCHAR2(2000 CHAR) NOT NULL,
 DATA_COMUNICAZIONE DATE NOT NULL,
 CODICERESPONSABILE NUMBER(8,0) NOT NULL,
 FKID_MAILTIPO NUMBER(4),
 ESCLUDI_NO_MAIL NUMBER(1,0) NOT NULL,
 DATA_ELIMINAZIONE DATE 
);

ALTER TABLE MASSIVE_TESTATA ADD CONSTRAINT PK_MASSIVETESTATA PRIMARY KEY(IDCOMUNE,ID);
ALTER TABLE MASSIVE_TESTATA ADD CONSTRAINT FK_MASSIVETESTATA_RESP FOREIGN KEY(IDCOMUNE,CODICERESPONSABILE) REFERENCES RESPONSABILI(IDCOMUNE,CODICERESPONSABILE);
ALTER TABLE MASSIVE_TESTATA ADD CONSTRAINT FK_MASSIVETESTATA_MAILTIPO FOREIGN KEY(IDCOMUNE,FKID_MAILTIPO) REFERENCES MAILTIPO(IDCOMUNE,CODICEMAIL);


CREATE TABLE MASSIVE_T_FIRMATARI(
  IDCOMUNE VARCHAR2(6 CHAR)  NOT NULL, 
  ID NUMBER(6,0) NOT NULL,
  FKID_TESTATA NUMBER(6,0) NOT NULL,
  CODICERESPONSABILE NUMBER(8,0) NOT NULL
);

ALTER TABLE MASSIVE_T_FIRMATARI ADD CONSTRAINT PK_MASSIVETFIRMATARI PRIMARY KEY(IDCOMUNE,ID);
ALTER TABLE MASSIVE_T_FIRMATARI ADD CONSTRAINT FK_MASSIVETFIRMATARI_TESTATA FOREIGN KEY(IDCOMUNE,FKID_TESTATA) REFERENCES MASSIVE_TESTATA(IDCOMUNE,ID);
ALTER TABLE MASSIVE_T_FIRMATARI ADD CONSTRAINT FK_MASSIVETFIRMATARI_RESP FOREIGN KEY(IDCOMUNE,CODICERESPONSABILE) REFERENCES RESPONSABILI(IDCOMUNE,CODICERESPONSABILE);
                
                
CREATE TABLE MASSIVE_T_ALLEGATI(
  IDCOMUNE VARCHAR2(6 CHAR)  NOT NULL,
  ID NUMBER(6,0) NOT NULL,
  FKID_TESTATA NUMBER(6,0) NOT NULL,
  CODICEOGGETTO NUMBER(10,0) NOT NULL
);

ALTER TABLE MASSIVE_T_ALLEGATI ADD CONSTRAINT PK_MASSIVETALLEGATI PRIMARY KEY(IDCOMUNE,ID);
ALTER TABLE MASSIVE_T_ALLEGATI ADD CONSTRAINT FK_MASSIVETALLEGATI_TESTATA FOREIGN KEY(IDCOMUNE,FKID_TESTATA) REFERENCES MASSIVE_TESTATA(IDCOMUNE,ID);
ALTER TABLE MASSIVE_T_ALLEGATI ADD CONSTRAINT FK_MASSIVETALLEGATI_OGG FOREIGN KEY(IDCOMUNE,CODICEOGGETTO) REFERENCES OGGETTI(IDCOMUNE,CODICEOGGETTO);


CREATE TABLE MASSIVE_T_LETTERE(
 IDCOMUNE VARCHAR2(6 CHAR)  NOT NULL,
 ID NUMBER(6,0) NOT NULL,
 FKID_TESTATA NUMBER(6,0) NOT NULL,
 FKID_LETTERA_TIPO NUMBER(10,0) NOT NULL,
 TRASFORMA_IN_PDF NUMBER(1,0) NOT NULL
);

ALTER TABLE MASSIVE_T_LETTERE ADD CONSTRAINT PK_MASSIVETLETTERE PRIMARY KEY(IDCOMUNE,ID);
ALTER TABLE MASSIVE_T_LETTERE ADD CONSTRAINT FK_MASSIVETLETTERE_TESTATA FOREIGN KEY(IDCOMUNE,FKID_TESTATA) REFERENCES MASSIVE_TESTATA(IDCOMUNE,ID);
ALTER TABLE MASSIVE_T_LETTERE ADD CONSTRAINT FK_MASSIVETLETTERE_LETTIPO FOREIGN KEY(IDCOMUNE,FKID_LETTERA_TIPO) REFERENCES LETTERETIPO(IDCOMUNE,CODICELETTERA);


CREATE TABLE MASSIVE_DETTAGLIO(
 IDCOMUNE VARCHAR2(6 CHAR)  NOT NULL,
 ID NUMBER(6,0) NOT NULL,
 FKID_TESTATA NUMBER(6,0) NOT NULL,
 CODICEANAGRAFE NUMBER(6,0) NOT NULL,
 ULTIMO_STATO_COMPLETATO VARCHAR2(100 CHAR),
 ULTIMO_STATO_DATA DATE,
 MAIL_DESTINATARIO VARCHAR2(100 CHAR),
 ERRORE VARCHAR2(2000 CHAR)
);

ALTER TABLE MASSIVE_DETTAGLIO ADD CONSTRAINT PK_MASSIVEDETTAGLIO PRIMARY KEY(IDCOMUNE,ID);
ALTER TABLE MASSIVE_DETTAGLIO ADD CONSTRAINT FK_MASSIVEDETTAGLIO_TESTATA FOREIGN KEY(IDCOMUNE,FKID_TESTATA) REFERENCES MASSIVE_TESTATA(IDCOMUNE,ID);
ALTER TABLE MASSIVE_DETTAGLIO ADD CONSTRAINT FK_MASSIVEDETTAGLIO_ANAGRAFE FOREIGN KEY(IDCOMUNE,CODICEANAGRAFE) REFERENCES ANAGRAFE(IDCOMUNE,CODICEANAGRAFE);


CREATE TABLE MASSIVE_D_ALLEGATI(
 IDCOMUNE VARCHAR2(6 CHAR)  NOT NULL,
 ID NUMBER(6,0) NOT NULL,
 FKID_DETTAGLIO NUMBER(6,0) NOT NULL,
 CHIAVE VARCHAR2(50 CHAR) NOT NULL, 
 CODICEOGGETTO NUMBER(10,0) NOT NULL
);

ALTER TABLE MASSIVE_D_ALLEGATI ADD CONSTRAINT PK_MASSIVEDALLEGATI PRIMARY KEY(IDCOMUNE,ID);
ALTER TABLE MASSIVE_D_ALLEGATI ADD CONSTRAINT FK_MASSIVEDALLEGATI_DETTAGLIO FOREIGN KEY(IDCOMUNE,FKID_DETTAGLIO) REFERENCES MASSIVE_DETTAGLIO(IDCOMUNE,ID);
ALTER TABLE MASSIVE_D_ALLEGATI ADD CONSTRAINT FK_MASSIVEDALLEGATI_OGG FOREIGN KEY(IDCOMUNE,CODICEOGGETTO) REFERENCES OGGETTI(IDCOMUNE,CODICEOGGETTO);


CREATE TABLE BOLL_MASSIVE_T(
 IDCOMUNE VARCHAR2(6 CHAR)  NOT NULL,
 ID NUMBER(6,0) NOT NULL,
 FKID_TESTATA NUMBER(6,0) NOT NULL,
 FKID_BOLLETTAZIONE NUMBER(4,0) NOT NULL
);

ALTER TABLE BOLL_MASSIVE_T ADD CONSTRAINT PK_BOLLMASSIVET PRIMARY KEY(IDCOMUNE,ID);
ALTER TABLE BOLL_MASSIVE_T ADD CONSTRAINT FK_BOLLMASSIVET_TESTATA FOREIGN KEY(IDCOMUNE,FKID_TESTATA) REFERENCES MASSIVE_TESTATA(IDCOMUNE,ID);
ALTER TABLE BOLL_MASSIVE_T ADD CONSTRAINT FK_BOLLMASSIVET_BOLL FOREIGN KEY(IDCOMUNE,FKID_BOLLETTAZIONE) REFERENCES BOLL_GEST_TESTATA(IDCOMUNE,ID);


CREATE TABLE BOLL_MASSIVE_D(
  IDCOMUNE VARCHAR2(6 CHAR)  NOT NULL,
  ID NUMBER(6,0) NOT NULL,
  FKID_MASSIVE_D NUMBER(6,0) NOT NULL,
  FKID_BOLL_GEST_DETTAGLIO NUMBER(10,0) NOT NULL,
  CODICEMOVIMENTO NUMBER(8,0)
);

ALTER TABLE BOLL_MASSIVE_D ADD CONSTRAINT PK_BOLLMASSIVED PRIMARY KEY(IDCOMUNE,ID);
ALTER TABLE BOLL_MASSIVE_D ADD CONSTRAINT FK_BOLLMASSIVED_MASSIVED FOREIGN KEY(IDCOMUNE,FKID_MASSIVE_D) REFERENCES MASSIVE_DETTAGLIO(IDCOMUNE,ID);
ALTER TABLE BOLL_MASSIVE_D ADD CONSTRAINT FK_BOLLMASSIVED_BOLLGESTDETT FOREIGN KEY(IDCOMUNE,FKID_BOLL_GEST_DETTAGLIO) REFERENCES BOLL_GEST_DETTAGLIO(IDCOMUNE,ID);
ALTER TABLE BOLL_MASSIVE_D ADD CONSTRAINT FK_BOLLMASSIVED_MOV FOREIGN KEY(IDCOMUNE,CODICEMOVIMENTO) REFERENCES MOVIMENTI(IDCOMUNE,CODICEMOVIMENTO);


CREATE TABLE MASSIVE_PARAMETRI(
 IDCOMUNE VARCHAR2(6 CHAR)  NOT NULL,
 ID NUMBER(6,0) NOT NULL,
 FKID_TESTATA NUMBER(6,0)  NOT NULL,
 CHIAVE VARCHAR2(50 CHAR) NOT NULL,
 VALORE VARCHAR2(4000 CHAR) NOT NULL
);

ALTER TABLE MASSIVE_PARAMETRI ADD CONSTRAINT PK_MASSIVEPARAMETRI PRIMARY KEY(IDCOMUNE,ID);
ALTER TABLE MASSIVE_PARAMETRI ADD CONSTRAINT FK_MASSIVEPARAMETRI_TESTATA FOREIGN KEY(IDCOMUNE,FKID_TESTATA) REFERENCES MASSIVE_TESTATA(IDCOMUNE,ID);

ALTER TABLE MASSIVE_TESTATA ADD SENDERACCOUNT NUMBER(5,0);
ALTER TABLE MASSIVE_TESTATA ADD CONSTRAINT FK_MASSIVETESTATA_MAILCONFIG FOREIGN KEY(IDCOMUNE,SENDERACCOUNT) REFERENCES MAIL_CONFIG(IDCOMUNE,ID);

ALTER TABLE MASSIVE_DETTAGLIO ADD NUMEROPROTOCOLLO VARCHAR2(30 CHAR);
ALTER TABLE MASSIVE_DETTAGLIO ADD DATAPROTOCOLLO DATE;
ALTER TABLE MASSIVE_DETTAGLIO ADD FKIDPROTOCOLLO VARCHAR2(400 CHAR);

ALTER TABLE documenti_da_firmare MODIFY CODICEISTANZA NUMBER(6,0) NULL;
ALTER TABLE documenti_da_firmare MODIFY CODICEMOVALLEGATI NUMBER(8,0) NULL;

CREATE TABLE MESSAGGI_MAIL(
  IDCOMUNE  VARCHAR2(6 CHAR) NOT NULL
, ID NUMBER(10,0) NOT NULL
, MITTENTE  VARCHAR2(200) NOT NULL
, DESTINATARIO   VARCHAR2(600)
, DESTINATARIOCC VARCHAR2(600)
, DESTINATARIOBCC   VARCHAR2(600)
, OGGETTO  VARCHAR2(1500)
, DATAINVIO  DATE
, MESSAGE_ID  VARCHAR2(400)
, ID_PADRE NUMBER(10,0)
, CORPO CLOB
, ACCOUNT_ID NUMBER(5,0) NOT NULL
);
ALTER TABLE MESSAGGI_MAIL ADD CONSTRAINT PK_MESSAGGI_MAIL PRIMARY KEY(IDCOMUNE,ID); 
ALTER TABLE MESSAGGI_MAIL ADD CONSTRAINT FK_MESSAGGIMAIL_PADRE FOREIGN KEY (IDCOMUNE,ID_PADRE) REFERENCES MESSAGGI_MAIL(IDCOMUNE,ID); 
ALTER TABLE MESSAGGI_MAIL ADD CONSTRAINT FK_MESSAGGIMAIL_MAILCONFIG FOREIGN KEY (IDCOMUNE,ACCOUNT_ID) REFERENCES MAIL_CONFIG(IDCOMUNE,ID);

CREATE TABLE MESSAGGI_MAIL_ALLEGATI(
  IDCOMUNE  VARCHAR2(6 CHAR)NOT NULL
, ID NUMBER(10,0)  NOT NULL
, FKID_MESSAGGIMAIL  NUMBER(10,0)NOT NULL
, CODICEOGGETTO  NUMBER(10,0) NOT NULL
);
ALTER TABLE MESSAGGI_MAIL_ALLEGATI ADD CONSTRAINT PK_MESSAGGI_MAIL_ALLEGATI PRIMARY KEY(IDCOMUNE,ID); 
ALTER TABLE MESSAGGI_MAIL_ALLEGATI ADD CONSTRAINT FK_MESSAGGIMAILALL_MSGMAIL FOREIGN KEY(IDCOMUNE,FKID_MESSAGGIMAIL) REFERENCES MESSAGGI_MAIL(IDCOMUNE,ID); 
ALTER TABLE MESSAGGI_MAIL_ALLEGATI ADD CONSTRAINT FK_MESSAGGIMAILALL_OGGETTI FOREIGN KEY(IDCOMUNE,CODICEOGGETTO) REFERENCES OGGETTI(IDCOMUNE,CODICEOGGETTO); 
CREATE INDEX IDX_MESSAGGI_MAIL_ALLEGATI_001 ON MESSAGGI_MAIL_ALLEGATI(IDCOMUNE,FKID_MESSAGGIMAIL);

CREATE TABLE  MASSIVE_DETT_MESSAGGIMAIL(
  IDCOMUNE VARCHAR2(6 CHAR)  NOT NULL
, ID  NUMBER(10,0) NOT NULL
, FKID_MASSIVE_D  NUMBER(6,0) NOT NULL
, FKID_MESSAGGIMAIL  NUMBER(10,0) NOT NULL
);
ALTER TABLE MASSIVE_DETT_MESSAGGIMAIL ADD CONSTRAINT PK_MASSIVEDETTMAIL PRIMARY KEY(IDCOMUNE,ID); 
ALTER TABLE MASSIVE_DETT_MESSAGGIMAIL ADD CONSTRAINT FK_MASSIVEDETTMAIL_MASSIVEDETT FOREIGN KEY(IDCOMUNE,FKID_MASSIVE_D) REFERENCES MASSIVE_DETTAGLIO(IDCOMUNE,ID);
ALTER TABLE MASSIVE_DETT_MESSAGGIMAIL ADD CONSTRAINT FK_MASSIVEDETTMAIL_MESSMAIL FOREIGN KEY(IDCOMUNE,FKID_MESSAGGIMAIL) REFERENCES MESSAGGI_MAIL(IDCOMUNE,ID);
CREATE INDEX IDX_MASSIVEDETTMESGMAIL_001 ON MASSIVE_DETT_MESSAGGIMAIL(IDCOMUNE,FKID_MASSIVE_D);
CREATE INDEX IDX_MASSIVEDETTMESGMAIL_002 ON MASSIVE_DETT_MESSAGGIMAIL(IDCOMUNE,FKID_MESSAGGIMAIL);

CREATE TABLE MASSIVE_DETT_DOCDAFIRMARE(
IDCOMUNE VARCHAR2(6 char) NOT NULL
,ID NUMBER(10,0) NOT NULL
,FKID_MASSIVE_D  NUMBER(6,0) NOT NULL
,FK_DOCDAFIRMARE_ID  NUMBER(6,0) NOT NULL );

ALTER TABLE MASSIVE_DETT_DOCDAFIRMARE ADD CONSTRAINT PK_MASSIVEDDOCDAFIRMARE primary key(IDCOMUNE,ID);
ALTER TABLE MASSIVE_DETT_DOCDAFIRMARE ADD CONSTRAINT FK_MASSDDOCDAF_MASSIVED foreign key(IDCOMUNE,FKID_MASSIVE_D) REFERENCES MASSIVE_DETTAGLIO(IDCOMUNE,ID);
ALTER TABLE MASSIVE_DETT_DOCDAFIRMARE ADD CONSTRAINT FK_MASSDDOCDAF_docdafirm foreign key(IDCOMUNE,FK_DOCDAFIRMARE_ID) REFERENCES DOCUMENTI_DA_FIRMARE(IDCOMUNE,ID);
CREATE INDEX IDX_MASSIVED_DOCDAFIRM_001 on MASSIVE_DETT_DOCDAFIRMARE(IDCOMUNE, FKID_MASSIVE_D);

CREATE INDEX IDX_MASSIVED_DOCDAFIRM_002 on MASSIVE_DETT_DOCDAFIRMARE(IDCOMUNE, FK_DOCDAFIRMARE_ID);

ALTER TABLE MASSIVE_TESTATA ADD PROT_CODICEAMMINISTRAZIONE NUMBER(10)   ;
ALTER TABLE MASSIVE_TESTATA ADD PROT_CLASSIFICA      VARCHAR2(50) ;
ALTER TABLE MASSIVE_TESTATA ADD PROT_TIPODOCUMENTO   VARCHAR2(50) ;
ALTER TABLE MASSIVE_TESTATA ADD PROT_FKID_MAILTIPO   NUMBER(4)    ;
ALTER TABLE MASSIVE_TESTATA ADD CONSTRAINT FK_MASSIVET_AMMINISTRAZIONI FOREIGN KEY(IDCOMUNE,PROT_CODICEAMMINISTRAZIONE) REFERENCES AMMINISTRAZIONI(IDCOMUNE,CODICEAMMINISTRAZIONE);
ALTER TABLE MASSIVE_TESTATA ADD CONSTRAINT FK_MASSIVET_MAILTIPO FOREIGN KEY(IDCOMUNE,PROT_FKID_MAILTIPO) REFERENCES MAILTIPO(IDCOMUNE,CODICEMAIL);

alter table MASSIVE_TESTATA drop column ESCLUDI_NO_MAIL;

alter table massive_D_Allegati drop column chiave;


create table tipimov_tipisoggetto (
 IDCOMUNE varchar2(6) not null,
 ID number(10) not null,
 FK_IDTIPOMOVIMENTO varchar2(8) not null,
 FK_IDTIPOSOGGETTO number(10) not null,
 CONSTRAINT tipimov_tipisogg_pk PRIMARY KEY (IDCOMUNE, ID)
);

ALTER TABLE tipimov_tipisoggetto
  ADD CONSTRAINT fk_tt_tipisogg FOREIGN KEY (
    IDCOMUNE,
                FK_IDTIPOSOGGETTO
  ) REFERENCES tipisoggetto (
    idcomune,
    codicetiposoggetto 
  );
  
  
ALTER TABLE tipimov_tipisoggetto
  ADD CONSTRAINT fk_tt_tipimov FOREIGN KEY (
    IDCOMUNE,
                FK_IDTIPOMOVIMENTO
  ) REFERENCES tipimovimento (
    idcomune,
    tipomovimento 
  );

CREATE TABLE MASSIVE_T_PROTOCOLLO(
IDCOMUNE VARCHAR2(6 CHAR) NOT NULL,
ID NUMBER(6,0) NOT NULL,
FKID_TESTATA NUMBER(6,0) NOT NULL,
CODICECOMUNE VARCHAR2(5),
CODICEAMMINISTRAZIONE NUMBER(10,0),
CLASSIFICA VARCHAR2(50),
TIPODOCUMENTO VARCHAR2(50)
);

ALTER TABLE MASSIVE_T_PROTOCOLLO ADD CONSTRAINT PK_MASSIVE_T_PROTOCOLLO PRIMARY KEY (IDCOMUNE, ID);

ALTER TABLE MASSIVE_T_PROTOCOLLO ADD CONSTRAINT FK_MASSIVETPROT_MASST FOREIGN KEY (IDCOMUNE, FKID_TESTATA) REFERENCES MASSIVE_TESTATA (IDCOMUNE,ID);

ALTER TABLE MASSIVE_T_PROTOCOLLO ADD CONSTRAINT FK_MASSIVETPROT_COMUNI FOREIGN KEY ( CODICECOMUNE) REFERENCES COMUNI (CODICECOMUNE);

ALTER TABLE MASSIVE_T_PROTOCOLLO ADD CONSTRAINT FK_MASSIVETPROT_AMM FOREIGN KEY (IDCOMUNE, CODICEAMMINISTRAZIONE) REFERENCES AMMINISTRAZIONI (IDCOMUNE,CODICEAMMINISTRAZIONE);

CREATE INDEX IDX_MASSIVE_T_PROTOCOLLO_01 ON MASSIVE_T_PROTOCOLLO(IDCOMUNE,FKID_TESTATA);


ALTER TABLE LOCK_TABLE MODIFY LOCK_NAME VARCHAR2(255) ;

ALTER TABLE MASSIVE_TESTATA ADD DATA_CANCELLAZIONE DATE;
ALTER TABLE MASSIVE_TESTATA ADD RESP_CANCELLAZIONE NUMBER(8,0);
ALTER TABLE MASSIVE_TESTATA ADD CONSTRAINT FK_MASSIVE_T_RESP_CANC FOREIGN KEY (IDCOMUNE,  RESP_CANCELLAZIONE) REFERENCES RESPONSABILI(IDCOMUNE,CODICERESPONSABILE);

ALTER TABLE BOLL_MASSIVE_D MODIFY CODICEMOVIMENTO NUMBER(8,0) NULL;

ALTER TABLE PEOPLEPROCSPORTELLI ADD CONSTRAINT FK_PEOPLEPROCSPORTELLI_SOFT FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE (CODICE);

ALTER TABLE PEOPLEPROCSPORTELLI ADD CONSTRAINT UC_PEOPLEPROCSPORTELLI UNIQUE(IDCOMUNE, CODICECOMUNE, PEOPLE_PROC);

ALTER TABLE tipisoggetto ADD FLAG_LIVELLI_VISURA_PRATICA NUMBER(4, 0);

ALTER TABLE PEOPLEPROCSPORTELLI ADD CONSTRAINT FK_PEOPLEPROCSPORTELLI_COMUNI FOREIGN KEY(CODICECOMUNE) REFERENCES COMUNI (CODICECOMUNE);

