SET IMPLICIT_TRANSACTIONS ON
GO
ALTER TABLE ISTANZESTRADARIO ADD ID_PUNTO_SIT VARCHAR(50)
GO
COMMIT
GO
ALTER TABLE COMUNIASSOCIATI ADD CODICE_ENTE_PAYER VARCHAR(5)
GO
COMMIT
GO
CREATE TABLE MERCATI_D2C_ASSEGNAZ 
(
  IDCOMUNE VARCHAR(6) NOT NULL,
  ID NUMERIC(10,0) NOT NULL,
  FKCODICEMERCATO NUMERIC(4, 0) NOT NULL, 
  FK_D2C_ID NUMERIC(10, 0) NOT NULL, 
  CONSTRAINT MERCATI_D2C_ASSEGNAZ_PK PRIMARY KEY 
  (
    IDCOMUNE, 
    ID 
  ) 
)
GO
COMMIT
GO
ALTER TABLE MERCATI_D2C_ASSEGNAZ ADD CONSTRAINT FK_MERC_D2C_ASS_MERCATI FOREIGN KEY(IDCOMUNE , FKCODICEMERCATO) REFERENCES MERCATI (IDCOMUNE, CODICEMERCATO )
GO
COMMIT
GO
ALTER TABLE MERCATI_D2C_ASSEGNAZ ADD CONSTRAINT FK_MERC_D2C_ASS_DYN2_CAMPI FOREIGN KEY (IDCOMUNE , FK_D2C_ID) REFERENCES DYN2_CAMPI (IDCOMUNE , ID)
GO
COMMIT
GO
ALTER TABLE MERCATI  ADD FK_D2CID_PREF_USO NUMERIC(10, 0)
GO
COMMIT
GO
ALTER TABLE MERCATI ADD CONSTRAINT FK_MERCATI_DYN2_CAMPI FOREIGN KEY (IDCOMUNE , FK_D2CID_PREF_USO) REFERENCES DYN2_CAMPI (IDCOMUNE , ID)
GO
COMMIT
GO
ALTER TABLE MERCATI_D  ADD PESO NUMERIC(4, 0)
GO
COMMIT
GO
CREATE TABLE MERCATI_D_CRITASS 
(
  IDCOMUNE VARCHAR(6) NOT NULL,
  ID NUMERIC(10,0) NOT NULL,
  FK_IDPOSTEGGIO NUMERIC(6, 0) NOT NULL, 
  FK_D2C_ID NUMERIC(10, 0) NOT NULL,
  VALORE VARCHAR (100) NOT NULL,
  VALOREDECODIFICATO VARCHAR(100),
  FLAG_CONSENTITO NUMERIC(1, 0), 
  CONSTRAINT MERCATI_D_CRITASS_PK PRIMARY KEY 
  (
    IDCOMUNE, 
    ID 
  )
)
GO
COMMIT
GO
ALTER TABLE MERCATI_D_CRITASS ADD CONSTRAINT FK_MERC_D_CRITASS_DYN2_CAMPI FOREIGN KEY (IDCOMUNE , FK_D2C_ID) REFERENCES DYN2_CAMPI(IDCOMUNE , ID)
GO
COMMIT
GO
ALTER TABLE MERCATI_D_CRITASS ADD CONSTRAINT FK_MERC_D_CRITASS_MERCATID FOREIGN KEY (IDCOMUNE , FK_IDPOSTEGGIO) REFERENCES MERCATI_D(IDCOMUNE , IDPOSTEGGIO)
GO
COMMIT
GO
CREATE TABLE COMUNIASSOCIAZIONI (CODICEASSOCIAZIONE VARCHAR(5) NOT NULL, ASSOCIAZIONE VARCHAR(128) NOT NULL)
GO
COMMIT
GO
ALTER TABLE COMUNIASSOCIAZIONI ADD CONSTRAINT PK_COMASSOCIAZIONI PRIMARY KEY (CODICEASSOCIAZIONE)
GO
COMMIT
GO
CREATE VIEW VW_ENTILOCALI AS SELECT CODICECOMUNE, COMUNE FROM COMUNI UNION SELECT CODICEASSOCIAZIONE AS CODICECOMUNE, ASSOCIAZIONE AS COMUNE FROM COMUNIASSOCIAZIONI
GO
COMMIT
GO
ALTER TABLE AUTORIZZAZIONI DROP CONSTRAINT FK_AUTCOMUNI
GO
COMMIT
GO
ALTER TABLE AUTORIZZAZIONI_SUBENTRI DROP CONSTRAINT FK_AUTSUB_COMUNI
GO
COMMIT
GO
ALTER TABLE MERCATIPRESENZE_STORICO MODIFY FKIDMERCATIUSO NUMERIC(4,0) NULL
GO
COMMIT
GO
CREATE TABLE FO_ARJ_STEPS_BASE (
  NOME_STEP VARCHAR(50) NOT NULL,  
  LINK_FUNZIONE VARCHAR(125) NOT NULL,
  TITOLO VARCHAR(150) NOT NULL,
  DESCRIZIONE VARCHAR(4000),
  FLAG_OBBLIGATORIO NUMERIC(1,0),
  DIPENDE_DA_STEP VARCHAR(50),  
  INCOMPATIBILE_CON_STEP VARCHAR(50),
  ORDINE_DEFAULT NUMERIC(2,0),
PRIMARY KEY (NOME_STEP)
)
GO
COMMIT
GO
ALTER TABLE FO_ARJ_STEPS ADD FK_NOME_STEP_BASE VARCHAR(50)
GO
COMMIT
GO
ALTER TABLE FO_ARJ_STEPS ADD CONSTRAINT FK_FASNOMESTEP_FASBNOMESTEP FOREIGN KEY (FK_NOME_STEP_BASE) REFERENCES FO_ARJ_STEPS_BASE(NOME_STEP)
GO
COMMIT
GO
CREATE TABLE FO_ARJ_STEPS_PARAMS_BASE(
  CHIAVE  VARCHAR(200),
  DESCRIZIONE VARCHAR(500),
  PRIMARY KEY(CHIAVE)
)
GO
COMMIT
GO
ALTER TABLE FO_ARJ_STEPS_PARAMS ADD CONSTRAINT FK_FASPCHIAVE_FASPB_CHIAVE FOREIGN KEY(CHIAVE) REFERENCES FO_ARJ_STEPS_PARAMS_BASE (CHIAVE)
GO
COMMIT
GO
ALTER TABLE FO_ARCONFIGURAZIONE ADD FK_FOARJSTEPSTEST_ID NUMERIC(6,0)
GO
COMMIT
GO
ALTER TABLE FO_ARCONFIGURAZIONE ADD CONSTRAINT FK_FOAC_FOARJST_ID FOREIGN KEY (IDCOMUNE,FK_FOARJSTEPSTEST_ID) REFERENCES FO_ARJ_STEPS_TESTATA(IDCOMUNE,ID)
GO
COMMIT
GO
CREATE TABLE I_ATTIVITA_TIPOLOGIE(
IDCOMUNE VARCHAR(6) NOT NULL
,ID NUMERIC(4,0) NOT NULL
,DESCRIZIONE VARCHAR(100)
,SOFTWARE VARCHAR(2)
, PRIMARY KEY (IDCOMUNE, ID)
)
GO
COMMIT
GO
ALTER TABLE I_ATTIVITA ADD FK_IATIPOLOGIE_ID NUMERIC(4,0)
GO
COMMIT
GO
ALTER TABLE I_ATTIVITA ADD CONSTRAINT FK_IATT_IATIPOLOGIEID FOREIGN KEY (IDCOMUNE,FK_IATIPOLOGIE_ID ) REFERENCES I_ATTIVITA_TIPOLOGIE (IDCOMUNE,ID)
GO
COMMIT
GO
ALTER TABLE I_ATTIVITA_TIPOLOGIE ADD CONSTRAINT FK_IAT_TIPOLOGIE_SOFTWARE FOREIGN KEY (SOFTWARE) REFERENCES SOFTWARE (CODICE)
GO
COMMIT
GO
ALTER TABLE I_ATTIVITA_SNAPSHOT ADD FK_IATIPOLOGIE_ID NUMERIC(4,0)
GO
COMMIT
GO
ALTER TABLE I_ATTIVITA_SNAPSHOT ADD CONSTRAINT FK_IATTSNAP_IATIPOLOGIEID FOREIGN KEY (IDCOMUNE,FK_IATIPOLOGIE_ID ) REFERENCES I_ATTIVITA_TIPOLOGIE (IDCOMUNE,ID)
GO
COMMIT
GO
ALTER TABLE ISTANZE ALTER COLUMN LAVORI VARCHAR(2000)
GO
COMMIT
GO
CREATE TABLE FO_ARJ_DOMANDE_ONERI(
IDCOMUNE VARCHAR(6) NOT NULL
, ID NUMERIC(8,0) NOT NULL
, FK_ID_DOMANDA NUMERIC(6,0) NOT NULL
, FK_CAUSALEONERI NUMERIC(10,0) NOT NULL
, FK_CODICEINVENTARIO NUMERIC(10,0)
, IMPORTO NUMERIC(6,2)
, ID_NUM_OPERAZ_ONLINE VARCHAR(20)
, IDORDINE_SISTEMA_PAGAMENTI VARCHAR(125) 
, FLAG_STATO NUMERIC(1,0) 
, FLAG_ONLINE NUMERIC(1,0) 
, CODICEOGGETTO_XML NUMERIC(10,0) 
, CODICEOGGETTO_PDF NUMERIC(10,0)
, NOTE VARCHAR(500)
)
GO
COMMIT
GO
ALTER TABLE FO_ARJ_DOMANDE_ONERI ADD CONSTRAINT PK_FO_ARJ_DOMANDE_ONERI PRIMARY KEY(IDCOMUNE, ID)
GO
COMMIT
GO
ALTER TABLE FO_ARJ_DOMANDE_ONERI ADD CONSTRAINT FK_FADO_FADID FOREIGN KEY (IDCOMUNE, FK_ID_DOMANDA) REFERENCES FO_ARJ_DOMANDE(IDCOMUNE, ID)
GO
COMMIT
GO
ALTER TABLE FO_ARJ_DOMANDE_ONERI ADD CONSTRAINT FK_FADO_TCASUONERICOID FOREIGN KEY (IDCOMUNE, FK_CAUSALEONERI) REFERENCES TIPICAUSALIONERI(IDCOMUNE, CO_ID)
GO
COMMIT
GO
ALTER TABLE FO_ARJ_DOMANDE_ONERI ADD CONSTRAINT FK_FADO_INVPROCCODINV FOREIGN KEY (IDCOMUNE, FK_CODICEINVENTARIO) REFERENCES INVENTARIOPROCEDIMENTI(IDCOMUNE, CODICEINVENTARIO)
GO
COMMIT
GO
ALTER TABLE FO_ARJ_DOMANDE_ONERI ADD CONSTRAINT FK_FADOCOXML_OGGETTICO FOREIGN KEY (IDCOMUNE, CODICEOGGETTO_XML) REFERENCES OGGETTI(IDCOMUNE, CODICEOGGETTO)
GO
COMMIT
GO
ALTER TABLE FO_ARJ_DOMANDE_ONERI ADD CONSTRAINT FK_FADOCOPDF_OGGETTICO FOREIGN KEY (IDCOMUNE, CODICEOGGETTO_PDF) REFERENCES OGGETTI(IDCOMUNE, CODICEOGGETTO)
GO
COMMIT
GO
ALTER TABLE ALBEROPROC ADD FK_FOARJSTEPSTESTATAID NUMERIC(6,0)
GO
COMMIT
GO
ALTER TABLE ALBEROPROC ADD CONSTRAINT FK_ALBEROPROC_FOARJSTEPSTESTA FOREIGN KEY ( IDCOMUNE, FK_FOARJSTEPSTESTATAID ) REFERENCES FO_ARJ_STEPS_TESTATA ( IDCOMUNE, ID ) 
GO
COMMIT
GO
ALTER TABLE FO_ARJ_DOMANDE ADD FK_ALBEROPROCSCID NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE FO_ARJ_DOMANDE ADD CONSTRAINT FK_FOARJDOMANDE_ALBEROPROC FOREIGN KEY ( IDCOMUNE, FK_ALBEROPROCSCID ) REFERENCES ALBEROPROC ( IDCOMUNE, SC_ID ) 
GO
COMMIT
GO
CREATE TABLE NLA_SERVIZI
  (
    ID          NUMERIC(6,0) NOT NULL ,
    IDCOMUNE    VARCHAR(6) NOT NULL ,
    IDNODO      NUMERIC(6,0) NOT NULL ,
    IDENTE      VARCHAR(10) NOT NULL ,
    IDSPORTELLO VARCHAR(10) NOT NULL ,
    PEC         VARCHAR(320) ,
    DESCRIZIONE VARCHAR(4000) NOT NULL
  ) 
GO
COMMIT
GO
ALTER TABLE NLA_SERVIZI ADD CONSTRAINT NLA_SERVIZI_PK PRIMARY KEY(IDCOMUNE, ID)
GO
COMMIT
GO
CREATE TABLE FO_ARJ_SERVIZI
  (
    ID                NUMERIC(6,0) NOT NULL ,
    IDCOMUNE          VARCHAR(6,0) NOT NULL ,
    URL_SERVIZIO      VARCHAR(4000) NOT NULL ,
    ANONIMO           NUMERIC(1,0) ,
    FK_ALBEROPROCSCID NUMERIC(10,0) NOT NULL ,
    FK_NLASERVIZIID   NUMERIC(6,0) NOT NULL
  ) 
GO
COMMIT
GO
ALTER TABLE FO_ARJ_SERVIZI ADD CONSTRAINT FO_ARJ_SERVIZI_PK PRIMARY KEY (IDCOMUNE, ID)
GO
COMMIT
GO
ALTER TABLE FO_ARJ_SERVIZI ADD CONSTRAINT FK_FOARJSERVIZI_ALBEROPROC FOREIGN KEY ( IDCOMUNE, FK_ALBEROPROCSCID ) REFERENCES ALBEROPROC ( IDCOMUNE, SC_ID )
GO
COMMIT
GO
ALTER TABLE FO_ARJ_SERVIZI ADD CONSTRAINT FK_FOARJSERVIZI_NLASERVIZI FOREIGN KEY ( IDCOMUNE, FK_NLASERVIZIID ) REFERENCES NLA_SERVIZI ( IDCOMUNE, ID )
GO
COMMIT
GO
ALTER TABLE ALBEROPROC DROP CONSTRAINT FK_ALBERO_PROC_PROT_TIPI_DOC
GO
COMMIT
GO
ALTER TABLE ISTANZEONERI ALTER COLUMN DOCRIFERIMENTO VARCHAR(200)
GO
COMMIT
GO
ALTER TABLE TMP_ISTANZEONERI ALTER COLUMN RIFERIMENTO VARCHAR(200)
GO
COMMIT
GO
ALTER TABLE CC_CLASSISUPERFICI ADD ALIQUOTA_CALCOLO_CC NUMERIC(5,2)
GO
COMMIT
GO
ALTER TABLE DOCUMENTIISTANZA ADD ID_BASE VARCHAR(50)
GO
COMMIT
GO
ALTER TABLE MOVIMENTIALLEGATI ADD ID_BASE VARCHAR(50)
GO
COMMIT
GO
ALTER TABLE ISTANZEALLEGATI ADD ID_BASE VARCHAR(50)
GO
COMMIT
GO