CREATE TABLE AMMINISTRAZIONI_COLLEGATE(
IDCOMUNE VARCHAR2(6 CHAR) NOT NULL
, CODICEAMMINISTRAZIONE NUMBER(10,0) NOT NULL
, CODICESOTTOAMMINISTRAZIONE NUMBER(10,0) NOT NULL
, CODICECOMUNE VARCHAR2 (5 CHAR) NOT NULL
) ;

ALTER TABLE AMMINISTRAZIONI_COLLEGATE ADD CONSTRAINT PK_AMMCOLLEGATE PRIMARY KEY(IDCOMUNE,CODICEAMMINISTRAZIONE,CODICECOMUNE);

ALTER TABLE AMMINISTRAZIONI_COLLEGATE ADD CONSTRAINT FK_AMMCOLLEGATE_AMMI FOREIGN KEY(IDCOMUNE,CODICEAMMINISTRAZIONE) REFERENCES  AMMINISTRAZIONI (IDCOMUNE,CODICEAMMINISTRAZIONE);

ALTER TABLE AMMINISTRAZIONI_COLLEGATE ADD CONSTRAINT FK_AMMCOLLEGATE_SOTTOAMM FOREIGN KEY(IDCOMUNE,CODICESOTTOAMMINISTRAZIONE) REFERENCES  AMMINISTRAZIONI (IDCOMUNE,CODICEAMMINISTRAZIONE);

ALTER TABLE AMMINISTRAZIONI_COLLEGATE ADD CONSTRAINT FK_AMMCOLLEGATE_COMUNI FOREIGN KEY(CODICECOMUNE) REFERENCES  COMUNI (CODICECOMUNE);

CREATE TABLE CONFIGURAZIONE_CALCOLI
(
IDCOMUNE VARCHAR2(6 CHAR) NOT NULL,
ID NUMBER(10,0) NOT NULL,
DESCRIZIONE VARCHAR2(200 CHAR) NOT NULL,
JSON_MATRICE NUMBER(10,0) NOT NULL,
JSON_CONFIGURAZIONE NUMBER(10,0) NOT NULL 
);

ALTER TABLE CONFIGURAZIONE_CALCOLI ADD CONSTRAINT PK_CONFIGCALCOLI PRIMARY KEY(IDCOMUNE,ID);

ALTER TABLE CONFIGURAZIONE_CALCOLI ADD CONSTRAINT FK_OGGETTI_MATRICE FOREIGN KEY(IDCOMUNE,JSON_MATRICE) REFERENCES OGGETTI (IDCOMUNE,CODICEOGGETTO);
ALTER TABLE CONFIGURAZIONE_CALCOLI ADD CONSTRAINT FK_OGGETTI_CONFIGURAZIONE FOREIGN KEY(IDCOMUNE,JSON_CONFIGURAZIONE) REFERENCES OGGETTI (IDCOMUNE,CODICEOGGETTO);
