ALTER TABLE ISTANZEEVENTI MODIFY IDEVENTO NUMERIC(10);
ALTER TABLE ISTANZEEVENTI ADD SOFTWARE VARCHAR(2);
ALTER TABLE ISTANZEEVENTI ADD CONSTRAINT FK_IEVENTI_SOFTWARE FOREIGN KEY (SOFTWARE) REFERENCES SOFTWARE(CODICE);
CREATE INDEX IDX_ISTEVENTI_001 ON ISTANZEEVENTI (IDCOMUNE, SOFTWARE, FLAG_LETTO);
CREATE INDEX IDX_ISTEVENTI_002 ON ISTANZEEVENTI (IDCOMUNE, FKIDCATEGORIAEVENTO, SOFTWARE, FLAG_LETTO);
CREATE INDEX IDX_ISTEVENTI_003 ON ISTANZEEVENTI (IDCOMUNE, CODICEISTANZA,FLAG_LETTO);
CREATE INDEX IDX_ISTEVENTI_004 ON ISTANZEEVENTI (IDCOMUNE, CODICEMOVIMENTO, FLAG_LETTO);

ALTER TABLE ALBEROPROC_ENDO ADD FLAG_PUBBLICA NUMERIC(1, 0);

CREATE OR REPLACE ALGORITHM=TEMPTABLE VIEW VW_ISTANZECONCESSIONILISTA as
SELECT 99999999 AS PROGRESSIVO, AUTORIZZAZIONI.AUTORIZRESPONSABILE AS CONC_AUTORIZRESPONSABILE, AUTORIZZAZIONI.IDCOMUNE, AUTORIZZAZIONI.FK_CAUSALE_ACQUISIZIONE AS ICONC_CODICECAUSALE, IFNULL(AUTORIZZAZIONI.DATA_CESSAZIONE,STR_TO_DATE('31/12/9999','%d/%m/%Y')) AS DATA_STORICO, ISTANZE.SOFTWARE, ISTANZE.CODICEISTANZA AS IST_CODICEISTANZA, ISTANZE.NUMEROISTANZA AS IST_NUMEROISTANZA, ISTANZE.CODICERICHIEDENTE AS IST_CODICERICHIEDENTE, ISTANZE.CODICETITOLARELEGALE AS IST_CODICETITOLARELEGALE, AUTORIZZAZIONI.ID AS CONC_ID, AUTORIZZAZIONI.AUTORIZNUMERO AS CONC_NUMERO, AUTORIZZAZIONI.AUTORIZDATA AS CONC_DATARILASCIO, AUTORIZZAZIONI.AUTORIZDATA AS DATARILASCIO, AUTORIZZAZIONI.DATASCADENZA AS CONC_DATASCADENZA, AUTORIZZAZIONI_CONCESSIONI.FK_TIPOCONCESSIONE AS CONC_CODICETIPO, CONCESSIONITIPI.DESCRIZIONE AS CONC_TIPO, AUTORIZZAZIONI_CONCESSIONI.STAGIONALEA AS CONC_STAGIONALEA, AUTORIZZAZIONI_CONCESSIONI.STAGIONALEDA AS CONC_STAGIONALEDA, AUTORIZZAZIONI.FLAG_ATTIVA AS CONC_ATTIVA, AUTORIZZAZIONI.FK_CODICEANAGRAFE AS CONC_CODICETITOLARE, CONCAT_WS('',TITOLARE.NOMINATIVO,' ',TITOLARE.NOME) AS CONC_TITOLARE, TITOLARE.CODICEFISCALE AS CONC_TIT_CF, TITOLARE.PARTITAIVA AS CONC_TIT_PIVA, TITOLARE.TIPOANAGRAFE AS CONC_TIT_TIPOANAGRAFE, AUT_COLLEGATA.AUTORIZNUMERO AS AUT_NUMERO, AUT_COLLEGATA.AUTORIZDATA AS AUT_DATA, AUT_COLLEGATA.AUTORIZDATA, AUT_COLLEGATA.FKIDREGISTRO AS AUT_CODREGISTRO, TIPOLOGIAREGISTRI.TR_DESCRIZIONE AS AUT_REGISTRO, CONCAT_WS('',IST_RICHIEDENTE.NOMINATIVO,' ',IST_RICHIEDENTE.NOME) AS IST_NOMINATIVO, IST_RICHIEDENTE.TIPOANAGRAFE AS IST_RIC_TIPOANAGRAFE, CONCAT_WS('',IST_AZIENDA.NOMINATIVO,' ',IST_AZIENDA.NOME) AS IST_NOMINATIVOAZIENDA, IST_AZIENDA.TIPOANAGRAFE AS IST_AZI_TIPOANAGRAFE, IST_AZIENDA.CODICEFISCALE AS IST_AZI_CODICEFISCALE, IST_AZIENDA.PARTITAIVA AS IST_AZI_PARTITAIVA, IST_RICHIEDENTE.CODICEFISCALE AS IST_CODICEFISCALE, IST_RICHIEDENTE.PARTITAIVA AS IST_PARTITAIVA, CAUS_ATTUALE.DESCRIZIONE AS ICONC_CAUSALE, AUTORIZZAZIONI.FK_CAUSALE_CESSAZIONE AS ICONC_CODICECAUSALESTORICO, CAUS_STORICO.DESCRIZIONE AS ICONC_CAUSALESTORICO, AUTORIZZAZIONI_CONCESSIONI.FK_CODICEMERCATO AS CONC_IDMERCATO, MERCATI.DESCRIZIONE AS CONC_MERCATO, MERCATI.ATTIVO AS MERC_ATTIVO, AUTORIZZAZIONI_CONCESSIONI.FK_IDPOSTEGGIO AS CONC_IDPOSTEGGIO, MERCATI_D.CODICEPOSTEGGIO AS CONC_POSTEGGIO, MERCATI_D.LARGHEZZA AS CONC_POS_LARGHEZZA, MERCATI_D.LUNGHEZZA AS CONC_POS_LUNGHEZZA, MERCATI_D.SUPERFICIE AS CONC_POS_SUPERFICIE, MERCATI_D.FKCODICETIPOSPAZIO AS POST_IDTIPOSPAZIO, POSTEGGITIPOSPAZIO.TIPOSPAZIO AS POST_TIPOSPAZIO, AUTORIZZAZIONI_CONCESSIONI.FK_IDMERCATIUSO AS CONC_IDMERCATIUSO, MERCATI_USO.DESCRIZIONE AS CONC_DESCRIZIONEUSO, MERCATI_USO.PESO AS PESO_MERCATO, MERCATI_USO.FKCODICEUSO AS MERC_IDUSO, MERCATI_D.FKCODICESTRADARIO AS CONC_POS_CODICESTRADARIO, MERCATI_D.NOTE AS CONC_POS_NOTE FROM ((AUTORIZZAZIONI LEFT OUTER JOIN TIPOLOGIAREGISTRI ON AUTORIZZAZIONI.IDCOMUNE = TIPOLOGIAREGISTRI.IDCOMUNE AND AUTORIZZAZIONI.FKIDREGISTRO = TIPOLOGIAREGISTRI.TR_ID) LEFT OUTER JOIN CONCESSIONICAUSALI CAUS_STORICO ON AUTORIZZAZIONI.IDCOMUNE = CAUS_STORICO.IDCOMUNE AND AUTORIZZAZIONI.FK_CAUSALE_CESSAZIONE = CAUS_STORICO.CODICECAUSALE), (AUTORIZZAZIONI_CONCESSIONI LEFT OUTER JOIN AUTORIZZAZIONI AUT_COLLEGATA ON AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE = AUT_COLLEGATA.IDCOMUNE AND AUTORIZZAZIONI_CONCESSIONI.FK_IDAUT_COLLEGATA = AUT_COLLEGATA.ID), CONCESSIONITIPI, ANAGRAFE TITOLARE, CONCESSIONICAUSALI CAUS_ATTUALE, ISTANZE LEFT OUTER JOIN ANAGRAFE IST_AZIENDA ON ISTANZE.IDCOMUNE = IST_AZIENDA.IDCOMUNE AND ISTANZE.CODICETITOLARELEGALE = IST_AZIENDA.CODICEANAGRAFE, ANAGRAFE IST_RICHIEDENTE, MERCATI, (MERCATI_D LEFT OUTER JOIN POSTEGGITIPOSPAZIO ON  MERCATI_D.IDCOMUNE = POSTEGGITIPOSPAZIO.IDCOMUNE AND MERCATI_D.FKCODICETIPOSPAZIO = POSTEGGITIPOSPAZIO.CODICE), MERCATI_USO WHERE AUTORIZZAZIONI.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND AUTORIZZAZIONI.ID = AUTORIZZAZIONI_CONCESSIONI.FK_IDAUT_ATTUALE AND CONCESSIONITIPI.TIPOCONCESSIONE = AUTORIZZAZIONI_CONCESSIONI.FK_TIPOCONCESSIONE AND TITOLARE.IDCOMUNE = AUTORIZZAZIONI.IDCOMUNE AND TITOLARE.CODICEANAGRAFE = AUTORIZZAZIONI.FK_CODICEANAGRAFE AND CAUS_ATTUALE.IDCOMUNE = AUTORIZZAZIONI.IDCOMUNE AND CAUS_ATTUALE.CODICECAUSALE = AUTORIZZAZIONI.FK_CAUSALE_ACQUISIZIONE AND ISTANZE.IDCOMUNE = AUTORIZZAZIONI.IDCOMUNE AND ISTANZE.CODICEISTANZA = AUTORIZZAZIONI.FKIDISTANZA AND IST_RICHIEDENTE.IDCOMUNE = ISTANZE.IDCOMUNE AND IST_RICHIEDENTE.CODICEANAGRAFE = ISTANZE.CODICERICHIEDENTE AND MERCATI.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND MERCATI.CODICEMERCATO = AUTORIZZAZIONI_CONCESSIONI.FK_CODICEMERCATO AND MERCATI_D.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND MERCATI_D.IDPOSTEGGIO = AUTORIZZAZIONI_CONCESSIONI.FK_IDPOSTEGGIO AND MERCATI_USO.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND MERCATI_USO.ID = AUTORIZZAZIONI_CONCESSIONI.FK_IDMERCATIUSO
UNION
SELECT AUTORIZZAZIONI_SUBENTRI.ID AS PROGRESSIVO, AUTORIZZAZIONI_SUBENTRI.AUTORIZRESPONSABILE AS CONC_AUTORIZRESPONSABILE, AUTORIZZAZIONI_SUBENTRI.IDCOMUNE, AUTORIZZAZIONI_SUBENTRI.FK_CAUSALE_ACQUISIZIONE AS ICONC_CODICECAUSALE, AUTORIZZAZIONI_SUBENTRI.DATA_CESSAZIONE AS DATA_STORICO, ISTANZE.SOFTWARE, ISTANZE.CODICEISTANZA AS IST_CODICEISTANZA, ISTANZE.NUMEROISTANZA AS IST_NUMEROISTANZA, ISTANZE.CODICERICHIEDENTE AS IST_CODICERICHIEDENTE, ISTANZE.CODICETITOLARELEGALE AS IST_CODICETITOLARELEGALE, AUTORIZZAZIONI_SUBENTRI.FK_IDAUT_ATTUALE AS CONC_ID, AUTORIZZAZIONI_SUBENTRI.AUTORIZNUMERO AS CONC_NUMERO, AUTORIZZAZIONI_SUBENTRI.AUTORIZDATA AS CONC_DATARILASCIO, AUTORIZZAZIONI_SUBENTRI.AUTORIZDATA AS DATARILASCIO, AUTORIZZAZIONI_SUBENTRI.DATASCADENZA AS CONC_DATASCADENZA, AUTORIZZAZIONI_CONCESSIONI.FK_TIPOCONCESSIONE AS CONC_CODICETIPO, CONCESSIONITIPI.DESCRIZIONE AS CONC_TIPO, AUTORIZZAZIONI_CONCESSIONI.STAGIONALEA AS CONC_STAGIONALEA, AUTORIZZAZIONI_CONCESSIONI.STAGIONALEDA AS CONC_STAGIONALEDA, 0 AS CONC_ATTIVA,AUTORIZZAZIONI_SUBENTRI.FK_CODICEANAGRAFE AS CONC_CODICETITOLARE, CONCAT_WS('',TITOLARE.NOMINATIVO,' ',TITOLARE.NOME) AS CONC_TITOLARE, TITOLARE.CODICEFISCALE AS CONC_TIT_CF, TITOLARE.PARTITAIVA AS CONC_TIT_PIVA, TITOLARE.TIPOANAGRAFE AS CONC_TIT_TIPOANAGRAFE, AUT_COLLEGATA.AUTORIZNUMERO AS AUT_NUMERO, AUT_COLLEGATA.AUTORIZDATA AS AUT_DATA, AUT_COLLEGATA.AUTORIZDATA,AUT_COLLEGATA.FKIDREGISTRO AS AUT_CODREGISTRO, TIPOLOGIAREGISTRI.TR_DESCRIZIONE AS AUT_REGISTRO, CONCAT_WS('',IST_RICHIEDENTE.NOMINATIVO,' ',IST_RICHIEDENTE.NOME) AS IST_NOMINATIVO, IST_RICHIEDENTE.TIPOANAGRAFE AS IST_RIC_TIPOANAGRAFE, CONCAT_WS('',IST_AZIENDA.NOMINATIVO,' ',IST_AZIENDA.NOME ) AS IST_NOMINATIVOAZIENDA, IST_AZIENDA.TIPOANAGRAFE AS IST_AZI_TIPOANAGRAFE, IST_AZIENDA.CODICEFISCALE AS IST_AZI_CODICEFISCALE, IST_AZIENDA.PARTITAIVA AS IST_AZI_PARTITAIVA, IST_RICHIEDENTE.CODICEFISCALE AS IST_CODICEFISCALE,IST_RICHIEDENTE.PARTITAIVA AS IST_PARTITAIVA, CAUS_ATTUALE.DESCRIZIONE AS ICONC_CAUSALE, AUTORIZZAZIONI_SUBENTRI.FK_CAUSALE_CESSAZIONE AS ICONC_CODICECAUSALESTORICO, CAUS_STORICO.DESCRIZIONE AS ICONC_CAUSALESTORICO, AUTORIZZAZIONI_CONCESSIONI.FK_CODICEMERCATO AS CONC_IDMERCATO, MERCATI.DESCRIZIONE AS CONC_MERCATO,MERCATI.ATTIVO AS MERC_ATTIVO, AUTORIZZAZIONI_CONCESSIONI.FK_IDPOSTEGGIO AS CONC_IDPOSTEGGIO, MERCATI_D.CODICEPOSTEGGIO AS CONC_POSTEGGIO, MERCATI_D.LARGHEZZA AS CONC_POS_LARGHEZZA,MERCATI_D.LUNGHEZZA AS CONC_POS_LUNGHEZZA,MERCATI_D.SUPERFICIE AS CONC_POS_SUPERFICIE, MERCATI_D.FKCODICETIPOSPAZIO AS POST_IDTIPOSPAZIO,POSTEGGITIPOSPAZIO.TIPOSPAZIO AS POST_TIPOSPAZIO, AUTORIZZAZIONI_CONCESSIONI.FK_IDMERCATIUSO AS CONC_IDMERCATIUSO, MERCATI_USO.DESCRIZIONE AS CONC_DESCRIZIONEUSO,MERCATI_USO.PESO AS PESO_MERCATO, MERCATI_USO.FKCODICEUSO AS MERC_IDUSO, MERCATI_D.FKCODICESTRADARIO AS CONC_POS_CODICESTRADARIO, MERCATI_D.NOTE AS CONC_POS_NOTE FROM (( AUTORIZZAZIONI_SUBENTRI LEFT OUTER JOIN TIPOLOGIAREGISTRI ON AUTORIZZAZIONI_SUBENTRI.IDCOMUNE = TIPOLOGIAREGISTRI.IDCOMUNE AND AUTORIZZAZIONI_SUBENTRI.FKIDREGISTRO = TIPOLOGIAREGISTRI.TR_ID )        LEFT OUTER JOIN CONCESSIONICAUSALI CAUS_STORICO ON  AUTORIZZAZIONI_SUBENTRI.IDCOMUNE = CAUS_STORICO.IDCOMUNE AND AUTORIZZAZIONI_SUBENTRI.FK_CAUSALE_CESSAZIONE = CAUS_STORICO.CODICECAUSALE ), ( AUTORIZZAZIONI_CONCESSIONI LEFT OUTER JOIN AUTORIZZAZIONI AUT_COLLEGATA ON  AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE = AUT_COLLEGATA.IDCOMUNE AND AUTORIZZAZIONI_CONCESSIONI.FK_IDAUT_COLLEGATA = AUT_COLLEGATA.ID ), CONCESSIONITIPI, ANAGRAFE TITOLARE, CONCESSIONICAUSALI CAUS_ATTUALE, ( ISTANZE LEFT OUTER JOIN ANAGRAFE IST_AZIENDA ON ISTANZE.IDCOMUNE = IST_AZIENDA.IDCOMUNE AND ISTANZE.CODICETITOLARELEGALE = IST_AZIENDA.CODICEANAGRAFE ), ANAGRAFE IST_RICHIEDENTE,MERCATI, ( MERCATI_D LEFT OUTER JOIN POSTEGGITIPOSPAZIO ON MERCATI_D.IDCOMUNE = POSTEGGITIPOSPAZIO.IDCOMUNE AND MERCATI_D.FKCODICETIPOSPAZIO = POSTEGGITIPOSPAZIO.CODICE ), MERCATI_USO WHERE AUTORIZZAZIONI_SUBENTRI.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND AUTORIZZAZIONI_SUBENTRI.FK_IDAUT_ATTUALE = AUTORIZZAZIONI_CONCESSIONI.FK_IDAUT_ATTUALE AND CONCESSIONITIPI.TIPOCONCESSIONE = AUTORIZZAZIONI_CONCESSIONI.FK_TIPOCONCESSIONE AND TITOLARE.IDCOMUNE = AUTORIZZAZIONI_SUBENTRI.IDCOMUNE AND TITOLARE.CODICEANAGRAFE = AUTORIZZAZIONI_SUBENTRI.FK_CODICEANAGRAFE AND CAUS_ATTUALE.IDCOMUNE = AUTORIZZAZIONI_SUBENTRI.IDCOMUNE AND CAUS_ATTUALE.CODICECAUSALE = AUTORIZZAZIONI_SUBENTRI.FK_CAUSALE_ACQUISIZIONE AND ISTANZE.IDCOMUNE = AUTORIZZAZIONI_SUBENTRI.IDCOMUNE AND ISTANZE.CODICEISTANZA = AUTORIZZAZIONI_SUBENTRI.FKIDISTANZA AND IST_RICHIEDENTE.IDCOMUNE = ISTANZE.IDCOMUNE AND IST_RICHIEDENTE.CODICEANAGRAFE = ISTANZE.CODICERICHIEDENTE AND MERCATI.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND MERCATI.CODICEMERCATO = AUTORIZZAZIONI_CONCESSIONI.FK_CODICEMERCATO AND MERCATI_D.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND MERCATI_D.IDPOSTEGGIO = AUTORIZZAZIONI_CONCESSIONI.FK_IDPOSTEGGIO AND MERCATI_USO.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND MERCATI_USO.ID = AUTORIZZAZIONI_CONCESSIONI.FK_IDMERCATIUSO;

ALTER TABLE TIPISOGGETTOPEOPLE MODIFY TIPORAPPRPEOPLE VARCHAR(100);

ALTER TABLE NORMEGENERALI MODIFY INDIRIZZOWEB VARCHAR(512);


CREATE TABLE LINK_PREFERITI_UTENTE 
(
  IDCOMUNE VARCHAR(6) NOT NULL,
  ID NUMERIC(6,0),
  CODICERESPONSABILE NUMERIC(4, 0) NOT NULL, 
  DESCRIZIONE VARCHAR(150) NOT NULL, 
  URL VARCHAR(255) NOT NULL, 
  TARGET VARCHAR(10), 
  ORDINE NUMERIC(2, 0), 
  CONSTRAINT LINK_PREFERITI_UTENTE_PK PRIMARY KEY 
  (
    IDCOMUNE, 
    ID 
  )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE LINK_PREFERITI_UTENTE ADD CONSTRAINT FK_LINK_PREF_UTENTE_RESP FOREIGN KEY (IDCOMUNE , CODICERESPONSABILE) REFERENCES RESPONSABILI (IDCOMUNE , CODICERESPONSABILE );

CREATE TABLE DOCUMENTI_CONTABILITA 
(
  IDCOMUNE VARCHAR(6) NOT NULL,
  ID NUMERIC(6,0),
  CODICERESPONSABILE NUMERIC(4, 0) NOT NULL,
  CODICESOFTWARE VARCHAR(2),
  CODICEOGGETTO NUMERIC(10,0),
  NOMEDOCUMENTO VARCHAR(50) NOT NULL, 
  DOCUMENTO VARCHAR(4000),
  DATA DATE NOT NULL,
  DATAINSERIMENTO DATE NOT NULL,
  MESE VARCHAR(2), 
  ANNO VARCHAR(4),
  CONSTRAINT DOCUMENTI_CONTABILITA_PK PRIMARY KEY 
  (
    IDCOMUNE, 
    ID 
  )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE DOCUMENTI_CONTABILITA ADD CONSTRAINT FK_DOC_CONTAB_RESP FOREIGN KEY (IDCOMUNE , CODICERESPONSABILE) REFERENCES RESPONSABILI (IDCOMUNE , CODICERESPONSABILE );
ALTER TABLE DOCUMENTI_CONTABILITA ADD CONSTRAINT FK_DOC_CONTAB_OGGETTI FOREIGN KEY (IDCOMUNE , CODICEOGGETTO) REFERENCES OGGETTI (IDCOMUNE , CODICEOGGETTO);
CREATE TABLE PROTOCOLLO_SMISTAMENTI 
(
  IDCOMUNE VARCHAR(6) NOT NULL 
, CODICE VARCHAR(30) NOT NULL 
, DESCRIZIONE VARCHAR(300) NOT NULL 
, CONSTRAINT PROTOCOLLO_SMISTAMENTI_PK PRIMARY KEY 
  (
    IDCOMUNE 
  , CODICE 
  )
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
