<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://gruppoinit.it/sigepro/schemas/messages/iride" xmlns:tns="http://gruppoinit.it/sigepro/schemas/messages/iride"
	elementFormDefault="qualified">
	<element name="IrideMessaggioRequest">
		<complexType>
			<all>
				<element name="token" type="string" />
				<element name="software" type="string" />
				<element name="docid" type="long" />
				<element name="operazione" type="string" />
				<element name="esito" type="string" />
				<element name="messaggio" type="string" />
			</all>
		</complexType>
	</element>
	<element name="IrideMessaggioResponse">
		<complexType>
			<sequence>
				<element name="docid" type="long" />
				<element name="esito" type="string" />
				<element name="messaggio" type="string" />
			</sequence>
		</complexType>
	</element>
</schema>