<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://gruppoinit.it/cart/dizionario"
		elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" 
		xmlns:xmime="http://www.w3.org/2005/05/xmlmime">	
	<element name="UploadDizionarioRequest">
		<complexType>
			<sequence>
				<element name="dataPubblicazione" type="dateTime" minOccurs="1" maxOccurs="1"/>		
				<element name="fileName" type="string" minOccurs="1" maxOccurs="1"/>
				<element name="binaryData" type="base64Binary" xmime:expectedContentTypes="application/octet-stream" />
			</sequence>
		</complexType>
	</element>
	<element name="UploadDizionarioResponse">
		<complexType>
			<sequence>
				<element name="code" type="integer" />
				<element name="message" type="string" />
			</sequence>
		</complexType>
	</element>
</schema>