<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<Configurations>Debug;Release;ReleaseFramework</Configurations>
		<Platforms>AnyCPU</Platforms>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\VBG.Pagamenti.Legacy\VBG.Pagamenti.Legacy.csproj" />
		<ProjectReference Include="..\Init.Sigepro.FrontEnd.AppLogic\Init.Sigepro.FrontEnd.AppLogic.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Properties\" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="log4net" Version="3.3.2" />
	  <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.10" />
	  <PackageReference Include="Microsoft.VisualStudio.Threading" Version="18.7.23" />
	  <PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="18.7.23">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	</ItemGroup>

</Project>
