ALTER TABLE PROTOCOLLO_REGISTRI ADD CODICECOMUNE VARCHAR2(5 CHAR);
ALTER TABLE PROTOCOLLO_REGISTRI ADD FOREIGN KEY FK_PROTREGISTRI_COMUNI FOREIGN KEY (CODICECOMUNE) REFERENCES COMUNI(CODICECOMUNE);
ALTER TABLE PROTOCOLLO_REGISTRI ADD ID NUMBER(6,0) NULL;