ALTER TABLE PROTOCOLLO_REGISTRI DROP PRIMARY KEY;
ALTER TABLE PROTOCOLLO_REGISTRI MODIFY ID NUMBER(6,0) NOT NULL;

ALTER TABLE PROTOCOLLO_REGISTRI ADD CONSTRAINT PROTOCOLLO_REGISTRI_PK PRIMARY KEY (IDCOMUNE, ID);