<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="urn:it.regulus.gestoreincassi" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="urn:it.regulus.gestoreincassi" elementFormDefault="qualified">
	<xs:include schemaLocation="TipiDati.xsd"/>
	<xs:element name="DATIFORNITI">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="CODENTE" type="xs:string"/>
				<xs:element name="TIPOCODENTE" type="TipoCodiceEnte"/>
				<xs:element name="CODTRIBUTO" type="xs:string"/>
				<xs:element name="NUMDOC" type="xs:string"/>
				<xs:element name="ANNODOC" type="TipoAnno"/>
				<xs:element name="CODFISC" type="CodiceFiscale"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>
