<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:include schemaLocation="TipiDati.xsd"/>
	<xs:complexType name="TipoUtente">
		<xs:annotation>
			<xs:documentation>Informazioni utilizzate per individuare un soggetto coinvolto nella sanzione amministrativa</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="CODICEFISCALE" type="CodiceFiscale" minOccurs="0"/>
			<xs:element name="COGNOME" type="xs:string" minOccurs="0"/>
			<xs:element name="NOME" type="xs:string" minOccurs="0"/>
			<xs:element name="RAGIONESOCIALE" type="xs:string" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>
