
ALTER TABLE MERCATIPRESENZE_D ADD FK_CODGERENTE_CONC NUMERIC(6,0); 
ALTER TABLE MERCATIPRESENZE_D ADD CONSTRAINT FK_MPD_ANAG_GER_CONC FOREIGN KEY (IDCOMUNE,FK_CODGERENTE_CONC) REFERENCES ANAGRAFE(IDCOMUNE,CODICEANAGRAFE);


ALTER TABLE MERCATIPRESENZE_D ADD FK_CODGERENTE_SPUNT NUMERIC(6,0); 
ALTER TABLE MERCATIPRESENZE_D ADD CONSTRAINT FK_MPD_ANAG_GER_SPUNT FOREIGN KEY (IDCOMUNE,FK_CODGERENTE_SPUNT) REFERENCES ANAGRAFE(IDCOMUNE,CODICEANAGRAFE);



ALTER TABLE TIPOLOGIAREGISTRI ADD NUMERO_PROROGHE NUMERIC(4,0);
ALTER TABLE TIPOLOGIAREGISTRI ADD NUMERO_RINNOVI NUMERIC(4,0);
ALTER TABLE TIPOLOGIAREGISTRI ADD NUMERO_PREAVVISI NUMERIC(4,0);
ALTER TABLE TIPOLOGIAREGISTRI ADD DURATA_AUTORIZZAZIONE VARCHAR(25);

ALTER TABLE AUTORIZZAZIONI ADD NUM_PROROGHE_RIMASTE NUMERIC(4,0);
ALTER TABLE AUTORIZZAZIONI ADD NUM_PREAVVISI_RIMASTI NUMERIC(4,0);
ALTER TABLE AUTORIZZAZIONI ADD NUM_RINNOVI_RIMASTI NUMERIC(4,0);

ALTER TABLE TIPIMOVIMENTO ADD FLAG_AUTORIZ_PROROGA NUMERIC(1,0);
ALTER TABLE TIPIMOVIMENTO ADD FLAG_AUTORIZ_PREAVV NUMERIC(1,0);
ALTER TABLE TIPIMOVIMENTO ADD FLAG_AUTORIZ_RINNOVO NUMERIC(1,0);
ALTER TABLE TIPIMOVIMENTO ADD FLAG_AUTORIZ_MODIFICA NUMERIC(1,0);

alter table AUTORIZZAZIONI modify AUTORIG_NUMERO VARCHAR(60);