ALTER TABLE ALBEROPROCPEOPLEOPER MODIFY SETTORE VARCHAR(30);
ALTER TABLE ALBEROPROCPEOPLEOPER MODIFY OPERAZIONE VARCHAR(30);

ALTER TABLE ISTANZEPROCURE MODIFY STC_ID_ALLEGATO VARCHAR(500);
ALTER TABLE ISTANZEPROCURE MODIFY STC_ID_DOCUMENTO VARCHAR(500);

ALTER TABLE DOCUMENTIISTANZA MODIFY STC_IDALLEGATO VARCHAR(500);
ALTER TABLE DOCUMENTIISTANZA MODIFY STC_IDDOCUMENTO VARCHAR(500);

ALTER TABLE ISTANZEALLEGATI MODIFY STC_IDDOCUMENTO VARCHAR(500);
ALTER TABLE ISTANZEALLEGATI MODIFY STC_IDALLEGATO VARCHAR(500);


ALTER TABLE MOVIMENTIALLEGATI MODIFY STC_IDDOCUMENTO VARCHAR(500);
ALTER TABLE MOVIMENTIALLEGATI MODIFY STC_IDALLEGATO VARCHAR(500);

