ALTER TABLE MOVIMENTI ADD FLG_MOD_MANUALE_DATA NUMBER(1,0);

COMMENT ON COLUMN MOVIMENTI.FLG_MOD_MANUALE_DATA IS 'SE 1 ALLORA SIGNIFICA CHE LA DATA DI SCADENZA DEL MOVIMENTO E'' STATO MODIFICATA MANUALMENTE DALL'' OPERATORE E NON DEVE ESSERE RICALCOLATA DALL''ELABORAZIONE';

CREATE TABLE DEHORS_CFG  (
  IDCOMUNE VARCHAR2(6) NOT NULL, 
  ID NUMBER(4,0) NOT NULL,
  CODICEREGISTRO NUMBER (4,0) NOT NULL,
  FK_CONCESSIONECAUSALE NUMBER (4,0) NOT NULL,
  SOFTWARE VARCHAR2(2) NOT NULL
);

CREATE UNIQUE INDEX DEHORS_CFG_PK ON DEHORS_CFG (IDCOMUNE, ID) ; 
ALTER TABLE DEHORS_CFG ADD CONSTRAINT DEHORS_CFG_PK PRIMARY KEY (IDCOMUNE, ID);
ALTER TABLE DEHORS_CFG ADD CONSTRAINT DEHORS_CFG_TIPO_REG FOREIGN KEY (IDCOMUNE, CODICEREGISTRO) REFERENCES TIPOLOGIAREGISTRI (IDCOMUNE, TR_ID);
ALTER TABLE DEHORS_CFG ADD CONSTRAINT DEHORS_CFG_CONC_CAUSALI FOREIGN KEY (IDCOMUNE, FK_CONCESSIONECAUSALE) REFERENCES CONCESSIONICAUSALI (IDCOMUNE, CODICECAUSALE);

CREATE TABLE DEHORS_MQ_ISTANZE (
  IDCOMUNE VARCHAR2(6) NOT NULL, 
  ID NUMBER(10,0) NOT NULL,
  CODICEISTANZA NUMBER (6,0) NOT NULL,
  FK_ID_AUTORIZZAZIONE NUMBER(6,0),
  FK_AREE  NUMBER(8,0),
  CESSATA NUMBER(1,0) DEFAULT (0) NOT NULL,
  MQASSEGNATI DECIMAL(10,2),
  MQRICHIESTI DECIMAL(10,2) NOT NULL
);

CREATE UNIQUE INDEX DEHORS_MQ_ISTANZE_PK ON DEHORS_MQ_ISTANZE (IDCOMUNE, ID) ; 
ALTER TABLE DEHORS_MQ_ISTANZE ADD CONSTRAINT DEHORS_MQ_ISTANZE_PK PRIMARY KEY (IDCOMUNE, ID);

ALTER TABLE DEHORS_MQ_ISTANZE ADD CONSTRAINT FK_DEHORS_MQ_IST_IST FOREIGN KEY (IDCOMUNE, CODICEISTANZA) REFERENCES ISTANZE (IDCOMUNE, CODICEISTANZA);
ALTER TABLE DEHORS_MQ_ISTANZE ADD CONSTRAINT FK_DEHORS_MQ_IST_AUT FOREIGN KEY (IDCOMUNE, FK_ID_AUTORIZZAZIONE) REFERENCES AUTORIZZAZIONI (IDCOMUNE, ID);
ALTER TABLE DEHORS_MQ_ISTANZE ADD CONSTRAINT FK_DEHORS_MQ_IST_AREE FOREIGN KEY (IDCOMUNE, FK_AREE) REFERENCES AREE (IDCOMUNE, CODICEAREA);

CREATE TABLE DEHORS_LOG (
  IDCOMUNE VARCHAR2(6) NOT NULL, 
  ID NUMBER(10,0) NOT NULL,
  CODICEISTANZA NUMBER (6,0) NOT NULL,
  CODICERESPONSABILE NUMBER(8,0) NOT NULL,
  FK_ID_AUTORIZZAZIONE NUMBER(6,0) NOT NULL,
  DATA_ORA_MODIFICA DATE NOT NULL,
  MQ_INIZIALI NUMBER (10,2)  NOT NULL,
  MQ_VARIATI NUMBER (10,2)  NOT NULL,
  MESSAGGIO_LOG VARCHAR2(500 )
);

CREATE UNIQUE INDEX DEHORS_LOG_PK ON DEHORS_LOG (IDCOMUNE, ID) ; 
ALTER TABLE DEHORS_LOG ADD CONSTRAINT DEHORS_LOG_PK PRIMARY KEY (IDCOMUNE, ID);
ALTER TABLE DEHORS_LOG ADD CONSTRAINT FK_DEHORS_LOG_IST FOREIGN KEY (IDCOMUNE, CODICEISTANZA) REFERENCES ISTANZE (IDCOMUNE, CODICEISTANZA);
ALTER TABLE DEHORS_LOG ADD CONSTRAINT DEHORS_LOG_RESP FOREIGN KEY (IDCOMUNE, CODICERESPONSABILE) REFERENCES RESPONSABILI (IDCOMUNE, CODICERESPONSABILE);
ALTER TABLE DEHORS_LOG ADD CONSTRAINT DEHORS_LOG_AUT FOREIGN KEY (IDCOMUNE, FK_ID_AUTORIZZAZIONE) REFERENCES AUTORIZZAZIONI (IDCOMUNE, ID);

CREATE TABLE DEHORS_AREE  (
  IDCOMUNE VARCHAR2(6) NOT NULL, 
  ID NUMBER(10,0) NOT NULL,
  FK_CODICEAREA NUMBER (8,0) NOT NULL,
  MQDISPONIBILI NUMBER(10,2) NOT NULL
);

CREATE UNIQUE INDEX DEHORS_AREE_PK ON DEHORS_AREE (IDCOMUNE, ID) ; 
ALTER TABLE DEHORS_AREE ADD CONSTRAINT DEHORS_AREE_PK PRIMARY KEY (IDCOMUNE, ID);
ALTER TABLE DEHORS_AREE ADD CONSTRAINT FK_DEHORS_AREE FOREIGN KEY (IDCOMUNE, FK_CODICEAREA) REFERENCES AREE (IDCOMUNE, CODICEAREA);

CREATE INDEX IDX_DOCUMENTIISTANZA_002 ON DOCUMENTIISTANZA (IDCOMUNE,CODICEISTANZA);
CREATE INDEX IDX_DOCUMENTIISTANZA_003 ON DOCUMENTIISTANZA (IDCOMUNE,CODICEISTANZA, FLG_DA_MODELLO_DINAMICO);

ALTER TABLE TMP_ESPORTAZIONI DROP PRIMARY KEY;
CREATE UNIQUE INDEX TMP_ESPORTAZIONI_PK ON TMP_ESPORTAZIONI (IDCOMUNE, ID) ; 
ALTER TABLE TMP_ESPORTAZIONI ADD CONSTRAINT TMP_ESPORTAZIONI_PK PRIMARY KEY (IDCOMUNE, ID);

ALTER TABLE ALBEROPROC MODIFY SC_CODICE VARCHAR2(30);

ALTER TABLE TIPIMOVIMENTO ADD (FK_MAILTIPO_OGGPROT NUMERIC(4,0) );

ALTER TABLE TIPIMOVIMENTO ADD CONSTRAINT FK_TIPOMOV_MAILTIPO_PROTOGG FOREIGN KEY (IDCOMUNE, FK_MAILTIPO_OGGPROT) REFERENCES MAILTIPO(IDCOMUNE, CODICEMAIL);

ALTER TABLE ANAGRAFE MODIFY NOMINATIVO VARCHAR2(220);
ALTER TABLE ANAGRAFESTORICO MODIFY NOMINATIVO VARCHAR2(220);

ALTER TABLE ALBEROPROC_TIPISOGGETTO MODIFY ID NUMBER(10,0);

ALTER TABLE ALBEROPROC ADD (FLAG_OGGETTO_PRATICA_DEFAULT NUMBER(1, 0));