INSERT INTO  COMUNI (CODICECOMUNE, COMUNE, SIGLAPROVINCIA, PROVINCIA, REGIONE, CAP, CF, CODICEISTAT, CODICEISTATREGIONE) VALUES ('M376', 'ABETONE CUTIGLIANO', 'PT', 'PISTOIA', 'TOSCANA', '00000', 'M376', '047023', '09');



INSERT INTO  COMUNI (CODICECOMUNE, COMUNE, SIGLAPROVINCIA, PROVINCIA, REGIONE, CAP, CF, CODICEISTAT, CODICEISTATREGIONE) VALUES ('M377', 'SAN MARCELLO PITEGLIO', 'PT', 'PISTOIA', 'TOSCANA', '00000', 'M377', '047024', '09');

