SET IMPLICIT_TRANSACTIONS ON
GO
ALTER TABLE TIPISOGGETTOPEOPLE ADD CONSTRAINT FK_TIPI_SOGG_PEOLE_TIPI_SOGG FOREIGN KEY (IDCOMUNE, CODICETIPOSOGGETTO) REFERENCES TIPISOGGETTO (IDCOMUNE, CODICETIPOSOGGETTO)
GO
COMMIT
GO
ALTER TABLE CONFIGURAZIONEUTENTE ADD CONSTRAINT CONFUTENTE_RESPONSABILI_FK1 FOREIGN KEY (IDCOMUNE,CODICERESPONSABILE) REFERENCES RESPONSABILI(IDCOMUNE, CODICERESPONSABILE)
GO
COMMIT
GO
CREATE INDEX IDX_ANAGRAFESTORICO_001 ON ANAGRAFESTORICO (IDCOMUNE,CODICEANAGRAFE,DATAINIZIOVALIDITA)
GO
COMMIT
GO
CREATE INDEX  IDX_ANAGRAFESTORICO_002 ON ANAGRAFESTORICO (IDCOMUNE,CODICEANAGRAFE,DATAFINEVALIDITA)
GO
COMMIT
GO
CREATE VIEW VW_ANAGRAFESTORICO_UTILIZZO AS SELECT IDCOMUNE, FK_RICHIEDENTESTORICO_ID AS IDSTORICO, 'ISTANZE.FK_RICHIEDENTESTORICO_ID' AS UTILIZZO FROM ISTANZE WHERE FK_RICHIEDENTESTORICO_ID IS NOT NULL UNION SELECT IDCOMUNE, FK_TITOLARELEGALESTORICO_ID AS IDSTORICO, 'ISTANZE.FK_TITOLARELEGALESTORICO_ID' AS UTILIZZO FROM ISTANZE WHERE FK_TITOLARELEGALESTORICO_ID IS NOT NULL UNION SELECT IDCOMUNE, FK_PROFESSIONISTASTORICO_ID AS IDSTORICO, 'ISTANZE.FK_PROFESSIONISTASTORICO_ID' AS UTILIZZO FROM ISTANZE WHERE FK_PROFESSIONISTASTORICO_ID IS NOT NULL UNION SELECT IDCOMUNE, FK_RICHIEDENTESTORICO_ID AS IDSTORICO, 'ISTANZERICHIEDENTI.FK_RICHIEDENTESTORICO_ID' AS UTILIZZO FROM ISTANZERICHIEDENTI WHERE FK_RICHIEDENTESTORICO_ID IS NOT NULL UNION SELECT IDCOMUNE, FK_ANAGRAFECOLLSTORICO_ID AS IDSTORICO, 'ISTANZERICHIEDENTI.FK_ANAGRAFECOLLSTORICO_ID' AS UTILIZZO FROM ISTANZERICHIEDENTI WHERE FK_ANAGRAFECOLLSTORICO_ID IS NOT NULL UNION SELECT IDCOMUNE, FK_PROCURATORESTORICO_ID AS IDSTORICO, 'ISTANZERICHIEDENTI.FK_PROCURATORESTORICO_ID' AS UTILIZZO  FROM ISTANZERICHIEDENTI WHERE FK_PROCURATORESTORICO_ID IS NOT NULL
GO
COMMIT
GO
ALTER TABLE TIPISOGGETTOPEOPLE ALTER COLUMN CODICETIPOSOGGETTO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE FO_ARCONFIGURAZIONE ADD NOME_CONFIGURAZIONE_CONTENUTI VARCHAR(50) 
GO
COMMIT
GO
ALTER TABLE ALBEROPROC_DYN2MODELLIT ADD ORDINE NUMERIC(3,0)
GO
COMMIT
GO
ALTER TABLE TIPIPROCEDURE_DYN2MODELLIT ADD ORDINE NUMERIC(3,0)
GO
COMMIT
GO
ALTER TABLE INVENTARIOPROCDYN2MODELLIT ADD ORDINE NUMERIC(3,0)
GO
COMMIT
GO
ALTER TABLE RESPONSABILI ADD SCAD_DATAINIZIO DATETIME
GO
COMMIT
GO
ALTER TABLE RESPONSABILI ADD SCAD_SOFTWARE VARCHAR(2)
GO
COMMIT
GO
ALTER TABLE RESPONSABILI ADD SCAD_OPERATORE NUMERIC(4,0)
GO
COMMIT
GO
ALTER TABLE RESPONSABILI ADD SCAD_COMPORTAMENTO NUMERIC(1,0)
GO
COMMIT
GO
ALTER TABLE RESPONSABILI ADD CONSTRAINT FK_RESPONSABILI_SCADOPE FOREIGN KEY (IDCOMUNE,SCAD_OPERATORE) REFERENCES RESPONSABILI (IDCOMUNE, CODICERESPONSABILE)
GO
COMMIT
GO
ALTER TABLE RESPONSABILI ALTER COLUMN SCADENZARIOPREC NUMERIC(5,0)
GO
COMMIT
GO
ALTER TABLE TIPIPROCEDURE ADD CODICEOGGETTO_CERTINVIO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE TIPIPROCEDURE ADD CONSTRAINT FK_TIPIPROCEDURE_OGGETTI FOREIGN KEY (IDCOMUNE,CODICEOGGETTO_CERTINVIO) REFERENCES OGGETTI (IDCOMUNE,CODICEOGGETTO)
GO
COMMIT
GO
delete from INTERESSI_LEGALI
GO
COMMIT
GO
Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (1,CONVERT(DATETIME,'21/04/1942',103),CONVERT(DATETIME,'15/12/1990',103),5,null)
GO
COMMIT
GO
Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (2,CONVERT(DATETIME,'16/12/1990',103),CONVERT(DATETIME,'31/12/1996',103),10,'Legge 26 novembre 1990, n. 353')
GO
COMMIT
GO 
Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (3,CONVERT(DATETIME,'01/01/1997',103),CONVERT(DATETIME,'31/12/1998',103),5,'Legge 23 dicembre 1996, n. 662')
GO
COMMIT
GO 
Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (4,CONVERT(DATETIME,'01/01/1999',103),CONVERT(DATETIME,'31/12/2000',103),2.5,'D.M. 10 dicembre 1998')
GO
COMMIT
GO
Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (5,CONVERT(DATETIME,'01/01/2001',103),CONVERT(DATETIME,'31/12/2001',103),3.5,'D.M. 11 dicembre 2000')
GO
COMMIT
GO
Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (6,CONVERT(DATETIME,'01/01/2002',103),CONVERT(DATETIME,'31/12/2003',103),3,'D.M. 11 dicembre 2001')
GO
COMMIT
GO
Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (7,CONVERT(DATETIME,'01/01/2004',103),CONVERT(DATETIME,'31/12/2007',103),2.5,'D.M. 1 dicembre 2003')
GO
COMMIT
GO
Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (8,CONVERT(DATETIME,'01/01/2008',103),CONVERT(DATETIME,'31/12/2009',103),3,'D.M. 12 dicembre 2007')
GO
COMMIT
GO
Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (9,CONVERT(DATETIME,'01/01/2010',103),CONVERT(DATETIME,'31/12/2010',103),1,'D.M. 4 dicembre 2009')
GO
COMMIT
GO
Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (10,CONVERT(DATETIME,'01/01/2011',103),CONVERT(DATETIME,'31/12/2011',103),1.5,'D.M. 07 Dicembre 2010')
GO
COMMIT
GO
Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (11,CONVERT(DATETIME,'01/01/2012',103),null,2.5,'DM 12 dicembre 2011')
GO
COMMIT
GO
ALTER TABLE MOVIMENTIMAIL  ALTER COLUMN  DESTINATARIO VARCHAR(600)
GO
COMMIT
GO
ALTER TABLE MOVIMENTIMAIL  ALTER COLUMN  DESTINATARIOCC  VARCHAR(600)
GO
COMMIT
GO
ALTER TABLE MOVIMENTIMAIL  ALTER COLUMN  DESTINATARIOBCC  VARCHAR(600)
GO
COMMIT
GO
ALTER TABLE ANAGRAFE ADD FO_UTENTETESTER NUMERIC(1)
GO
COMMIT
GO
ALTER TABLE ANAGRAFESTORICO ADD FO_UTENTETESTER NUMERIC(1)
GO
COMMIT
GO