package it.gruppoinit.pal.gp.core.jmesa;

public enum LinkTargetEnum {
    BATCH_SCADENZARIO_ISTANZE, BATCH_SCADENZARIO_MOVIMENTI, DETTAGLIO_ISTANZA, CREATE_AUTORIZZAZIONE, ISTANZE_STC_SCADENZARIO, //
    DETTAGLIO_MOVIMENTO, DETTAGLIO_AUTORIZZAZIONE, DETTAGLIO_CONCESSIONI, //
    DETTAGLIO_ANAGRAFE, ELIMINA_FO_RICHIESTE, // 
    ISTANZE_EVENTI_HELPER_ISTANZE, ISTANZE_EVENTI_HELPER_MOVIMENTI, //
    INVENTARIOPROCEDIMENTISOFTWARE, INVENTARIOPROCEDIMENTI, DOCUMENTI_DA_FIRMARE_ISTANZE, DOCUMENTI_DA_FIRMARE_MOVIMENTI, // 
    DETTAGLIO_ISTANZA_VWCONCESSIONI, DETTAGLIO_ANAGRAFE_VWCONCESSIONI//
}
