ALTER TABLE MAIL_CONFIG ADD ID NUMERIC(5,0);
ALTER TABLE MAIL_CONFIG ADD DESCRIZIONE VARCHAR (500);
ALTER TABLE MAIL_CONFIG ADD FLAG_DISABILITATO  NUMERIC(1,0) DEFAULT 0;
ALTER TABLE MAIL_CONFIG ADD FLAG_PRINCIPALE  NUMERIC(1,0) DEFAULT 0;
ALTER TABLE MAIL_CONFIG ADD CODICECOMUNE VARCHAR(5);

ALTER TABLE MAIL_CONFIG DROP PRIMARY KEY;

ALTER TABLE MOVIMENTIMAIL ADD ACCOUNT_ID NUMERIC(5,0);
ALTER TABLE PEC_INBOX ADD  ACCOUNT_ID NUMERIC (5,0);

ALTER TABLE ALBEROPROC ADD FLG_ACCESSO_ATTI NUMERIC(1,0);

CREATE TABLE ISTANZE_ACCESSO_ATTI_T(
IDCOMUNE  VARCHAR(6) NOT NULL,
ID NUMERIC(9,0) NOT NULL,      
CODICEISTANZA NUMERIC(6,0) NOT NULL,
DATAINIZIO DATETIME,
DATAFINE DATETIME,
CODICEOPERATORE NUMERIC(8,0) NOT NULL,    
FLG_PUBBLICA NUMERIC(1,0)
)ENGINE=INNODB DEFAULT CHARSET=utf8;

ALTER TABLE ISTANZE_ACCESSO_ATTI_T ADD CONSTRAINT PK_ISTANZE_ACCESSO_AGLI_ATTI_T PRIMARY KEY(IDCOMUNE,ID);
ALTER TABLE ISTANZE_ACCESSO_ATTI_T ADD CONSTRAINT FK_IST_ATTI_T_IST FOREIGN KEY(IDCOMUNE,CODICEISTANZA) REFERENCES ISTANZE(IDCOMUNE,CODICEISTANZA);
ALTER TABLE ISTANZE_ACCESSO_ATTI_T ADD CONSTRAINT FK_IST_ATTI_T_RESP FOREIGN KEY(IDCOMUNE,CODICEOPERATORE) REFERENCES RESPONSABILI(IDCOMUNE,CODICERESPONSABILE);


CREATE TABLE ISTANZE_ACCESSO_ATTI_D(
IDCOMUNE  VARCHAR(6) NOT NULL,
ID NUMERIC(9,0) NOT NULL,
FK_IDACCESSO_ATTI NUMERIC(9,0) NOT NULL,
CODICEISTANZA NUMERIC(6,0) NOT NULL,
FLG_VISUALIZZA_DOC NUMERIC(1,0)
)ENGINE=INNODB DEFAULT CHARSET=utf8;

ALTER TABLE ISTANZE_ACCESSO_ATTI_D ADD CONSTRAINT PK_ISTANZE_ACCESSO_AGLI_ATTI_D PRIMARY KEY(IDCOMUNE,ID);
ALTER TABLE ISTANZE_ACCESSO_ATTI_D ADD CONSTRAINT FK_IST_ATTI_D_IST FOREIGN KEY (IDCOMUNE, CODICEISTANZA) REFERENCES ISTANZE(IDCOMUNE,CODICEISTANZA);
ALTER TABLE ISTANZE_ACCESSO_ATTI_D ADD CONSTRAINT FK_IST_ATTI_D_T FOREIGN KEY (IDCOMUNE,FK_IDACCESSO_ATTI) REFERENCES ISTANZE_ACCESSO_ATTI_T(IDCOMUNE, ID);


CREATE TABLE ISTANZE_ACCESSO_ATTI_ANAGRAFE (
IDCOMUNE VARCHAR(6) NOT NULL,
FK_IDACCESSO_ATTI NUMERIC(9,0) NOT NULL,
CODICEANAGRAFE NUMERIC(6,0) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8;

ALTER TABLE ISTANZE_ACCESSO_ATTI_ANAGRAFE ADD CONSTRAINT ISTAN_ACCESSO_ATTI_ANAGR_PK PRIMARY KEY(IDCOMUNE, FK_IDACCESSO_ATTI, CODICEANAGRAFE);
ALTER TABLE ISTANZE_ACCESSO_ATTI_ANAGRAFE ADD CONSTRAINT FK_IST_ACC_ATT_ANG_ACC_T FOREIGN KEY(IDCOMUNE,FK_IDACCESSO_ATTI) REFERENCES ISTANZE_ACCESSO_ATTI_T(IDCOMUNE,ID);
ALTER TABLE ISTANZE_ACCESSO_ATTI_ANAGRAFE ADD CONSTRAINT FK_IST_ACC_ATT_ANAG_ACC_ANAG FOREIGN KEY(IDCOMUNE, CODICEANAGRAFE) REFERENCES ANAGRAFE(IDCOMUNE, CODICEANAGRAFE);

CREATE TABLE ISTANZE_ACCESSO_ATTI_LOG (
IDCOMUNE VARCHAR(6) NOT NULL,
UUID VARCHAR(50) NOT NULL,
FK_IDACCESSO_ATTI NUMERIC(9,0) NOT NULL,
DATAORA DATETIME NULL,
CODICEANAGRAFE NUMERIC(6,0) NOT NULL,
CODICEISTANZA NUMERIC(6,0) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8;

UPDATE ISTANZE_ACCESSO_ATTI_LOG SET UUID = UUID();
ALTER TABLE ISTANZE_ACCESSO_ATTI_LOG ADD CONSTRAINT ISTANZE_ACCESSO_ATTI_LOG_PK PRIMARY KEY(IDCOMUNE, UUID);

ALTER TABLE ISTANZE_ACCESSO_ATTI_LOG ADD CONSTRAINT FK_ATTI_LOG_CODICEANAGRAFE FOREIGN KEY(IDCOMUNE, CODICEANAGRAFE) REFERENCES ANAGRAFE(IDCOMUNE, CODICEANAGRAFE);
ALTER TABLE ISTANZE_ACCESSO_ATTI_LOG ADD CONSTRAINT FK_ATTI_LOG_CODICEISTANZA FOREIGN KEY(IDCOMUNE, CODICEISTANZA) REFERENCES ISTANZE(IDCOMUNE, CODICEISTANZA);
ALTER TABLE ISTANZE_ACCESSO_ATTI_LOG ADD CONSTRAINT FK_ATTI_LOG_ACCATTIT FOREIGN KEY(IDCOMUNE, FK_IDACCESSO_ATTI) REFERENCES ISTANZE_ACCESSO_ATTI_T(IDCOMUNE,ID);

ALTER TABLE ANAGRAFE ADD DATA_INIZIO_ATTIVITA DATETIME;
ALTER TABLE ANAGRAFESTORICO ADD DATA_INIZIO_ATTIVITA DATETIME;

ALTER TABLE ISTANZE_ACCESSO_ATTI_T ADD DESCRIZIONE_FASCICOLO VARCHAR(500);