ALTER TABLE MAIL_CONFIG MODIFY ID NUMERIC(5,0) NOT NULL;
ALTER TABLE MAIL_CONFIG ADD CONSTRAINT MAIL_CONFIG_PK PRIMARY KEY (IDCOMUNE,ID);

ALTER TABLE MAIL_CONFIG  ADD (DATA_INSERIMENTO DATE);
ALTER TABLE MAIL_CONFIG  ADD (DATA_ULTIMA_MODIFICA DATE);
ALTER TABLE MAIL_CONFIG  ADD (DESCRIZIONE_ULTIMA_MODIFICA VARCHAR(500));

ALTER TABLE MOVIMENTIMAIL ADD CONSTRAINT FK_MOVMAIL_MAIL_CFG FOREIGN KEY(IDCOMUNE,ACCOUNT_ID) REFERENCES MAIL_CONFIG(IDCOMUNE,ID);
ALTER TABLE PEC_INBOX ADD CONSTRAINT FK_PEC_INBOX_CFG FOREIGN KEY(IDCOMUNE,ACCOUNT_ID) REFERENCES MAIL_CONFIG (IDCOMUNE,ID);