ALTER TABLE INVENTARIOPROCEDIMENTIONERI ADD DYN2CAMPI_ONERI_FRONT NUMBER(10,0);
ALTER TABLE INVENTARIOPROCEDIMENTIONERI ADD FK_DYN2CAMPI_IDCOMUNE VARCHAR2(6 CHAR);

ALTER TABLE INVENTARIOPROCEDIMENTIONERI ADD CONSTRAINT FK_INVPROCON_DYN2C FOREIGN KEY (FK_DYN2CAMPI_IDCOMUNE,DYN2CAMPI_ONERI_FRONT) REFERENCES DYN2_CAMPI(IDCOMUNE,ID);
