//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2009.09.10 at 03:15:58 PM CEST
//
package it.gruppoinit.regulus.schema.getbilldetails.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element name=&quot;TITOLO&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
 *         &lt;element name=&quot;RISPOSTA&quot;&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *                 &lt;attribute name=&quot;IdentificativoRisposta&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; /&gt;
 *                 &lt;attribute name=&quot;DataRisposta&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name=&quot;ESITO&quot;&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base=&quot;&lt;http://www.w3.org/2001/XMLSchema&gt;string&quot;&gt;
 *                 &lt;attribute name=&quot;RC&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; /&gt;
 *                 &lt;attribute name=&quot;RCADD&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; /&gt;
 *                 &lt;attribute name=&quot;TIPOM&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; /&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element ref=&quot;{urn:it.regulus.gestoreincassi}DATIOUTPUT&quot;/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name=&quot;VersioneMessaggio&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; /&gt;
 *       &lt;attribute name=&quot;NomeFunzione&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; /&gt;
 *       &lt;attribute name=&quot;CodiceFunzione&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "titolo", "risposta", "esito", "datioutput" })
@XmlRootElement(name = "MSG")
public class MSG {

    @XmlElement(name = "TITOLO", required = true)
    protected String titolo;
    @XmlElement(name = "RISPOSTA", required = true)
    protected MSG.RISPOSTA risposta;
    @XmlElement(name = "ESITO", required = true)
    protected MSG.ESITO esito;
    @XmlElement(name = "DATIOUTPUT", required = true)
    protected DATIOUTPUT datioutput;
    @XmlAttribute(name = "VersioneMessaggio", required = true)
    protected String versioneMessaggio;
    @XmlAttribute(name = "NomeFunzione", required = true)
    protected String nomeFunzione;
    @XmlAttribute(name = "CodiceFunzione", required = true)
    protected String codiceFunzione;

    /**
     * Gets the value of the titolo property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTITOLO() {

	return titolo;
    }

    /**
     * Sets the value of the titolo property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTITOLO(String value) {

	this.titolo = value;
    }

    /**
     * Gets the value of the risposta property.
     * 
     * @return possible object is {@link MSG.RISPOSTA }
     * 
     */
    public MSG.RISPOSTA getRISPOSTA() {

	return risposta;
    }

    /**
     * Sets the value of the risposta property.
     * 
     * @param value
     *            allowed object is {@link MSG.RISPOSTA }
     * 
     */
    public void setRISPOSTA(MSG.RISPOSTA value) {

	this.risposta = value;
    }

    /**
     * Gets the value of the esito property.
     * 
     * @return possible object is {@link MSG.ESITO }
     * 
     */
    public MSG.ESITO getESITO() {

	return esito;
    }

    /**
     * Sets the value of the esito property.
     * 
     * @param value
     *            allowed object is {@link MSG.ESITO }
     * 
     */
    public void setESITO(MSG.ESITO value) {

	this.esito = value;
    }

    /**
     * Gets the value of the datioutput property.
     * 
     * @return possible object is {@link DATIOUTPUT }
     * 
     */
    public DATIOUTPUT getDATIOUTPUT() {

	return datioutput;
    }

    /**
     * Sets the value of the datioutput property.
     * 
     * @param value
     *            allowed object is {@link DATIOUTPUT }
     * 
     */
    public void setDATIOUTPUT(DATIOUTPUT value) {

	this.datioutput = value;
    }

    /**
     * Gets the value of the versioneMessaggio property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getVersioneMessaggio() {

	return versioneMessaggio;
    }

    /**
     * Sets the value of the versioneMessaggio property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setVersioneMessaggio(String value) {

	this.versioneMessaggio = value;
    }

    /**
     * Gets the value of the nomeFunzione property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getNomeFunzione() {

	return nomeFunzione;
    }

    /**
     * Sets the value of the nomeFunzione property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setNomeFunzione(String value) {

	this.nomeFunzione = value;
    }

    /**
     * Gets the value of the codiceFunzione property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCodiceFunzione() {

	return codiceFunzione;
    }

    /**
     * Sets the value of the codiceFunzione property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCodiceFunzione(String value) {

	this.codiceFunzione = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;simpleContent&gt;
     *     &lt;extension base=&quot;&lt;http://www.w3.org/2001/XMLSchema&gt;string&quot;&gt;
     *       &lt;attribute name=&quot;RC&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; /&gt;
     *       &lt;attribute name=&quot;RCADD&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; /&gt;
     *       &lt;attribute name=&quot;TIPOM&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; /&gt;
     *     &lt;/extension&gt;
     *   &lt;/simpleContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "value" })
    public static class ESITO {

	@XmlValue
	protected String value;
	@XmlAttribute(name = "RC", required = true)
	protected String rc;
	@XmlAttribute(name = "RCADD", required = true)
	protected String rcadd;
	@XmlAttribute(name = "TIPOM", required = true)
	protected String tipom;

	/**
	 * Gets the value of the value property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getValue() {

	    return value;
	}

	/**
	 * Sets the value of the value property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setValue(String value) {

	    this.value = value;
	}

	/**
	 * Gets the value of the rc property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRC() {

	    return rc;
	}

	/**
	 * Sets the value of the rc property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRC(String value) {

	    this.rc = value;
	}

	/**
	 * Gets the value of the rcadd property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRCADD() {

	    return rcadd;
	}

	/**
	 * Sets the value of the rcadd property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRCADD(String value) {

	    this.rcadd = value;
	}

	/**
	 * Gets the value of the tipom property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTIPOM() {

	    return tipom;
	}

	/**
	 * Sets the value of the tipom property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTIPOM(String value) {

	    this.tipom = value;
	}
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
     *       &lt;attribute name=&quot;IdentificativoRisposta&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; /&gt;
     *       &lt;attribute name=&quot;DataRisposta&quot; use=&quot;required&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class RISPOSTA {

	@XmlAttribute(name = "IdentificativoRisposta", required = true)
	protected String identificativoRisposta;
	@XmlAttribute(name = "DataRisposta", required = true)
	protected String dataRisposta;

	/**
	 * Gets the value of the identificativoRisposta property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getIdentificativoRisposta() {

	    return identificativoRisposta;
	}

	/**
	 * Sets the value of the identificativoRisposta property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setIdentificativoRisposta(String value) {

	    this.identificativoRisposta = value;
	}

	/**
	 * Gets the value of the dataRisposta property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDataRisposta() {

	    return dataRisposta;
	}

	/**
	 * Sets the value of the dataRisposta property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDataRisposta(String value) {

	    this.dataRisposta = value;
	}
    }
}
