ALTER TABLE INVENTARIOPROCEDIMENTI ADD FLAGTIPITITOLO NUMBER(1,0);
ALTER TABLE CLPERMMENU MODIFY ID NUMBER(10,0);

CREATE TABLE FVG_TIPIVARIAZIONI (CODICE VARCHAR2(15) NOT NULL, DESCRIZIONE VARCHAR2(2000) NOT NULL, PRIMARY KEY (CODICE));
ALTER TABLE ALBEROPROC ADD (FVG_TIPOVARIAZIONE VARCHAR2(15));
ALTER TABLE ALBEROPROC ADD CONSTRAINT FK_ALBERO_FVGTIPIVARIAZIONI FOREIGN KEY(FVG_TIPOVARIAZIONE) REFERENCES FVG_TIPIVARIAZIONI(CODICE) ENABLE;

CREATE TABLE TIPIMODELLI  (
  IDCOMUNE VARCHAR2(6) NOT NULL, 
  ID NUMBER(10,0) NOT NULL,
  DESCRIZIONE VARCHAR2(200) NOT NULL
);

ALTER TABLE TIPIMODELLI ADD CONSTRAINT TIPIMODELLI_PK PRIMARY KEY (IDCOMUNE, ID);

alter table MODELLI add FLAG_PUBBLICA NUMBER(1,0) default 0;
alter table MODELLI add FK_TIPIMODULO NUMBER(10,0);
ALTER TABLE MODELLI ADD CONSTRAINT  FK_TIPIMODULO_MODELLI FOREIGN KEY (IDCOMUNE, FK_TIPIMODULO) REFERENCES TIPIMODELLI (IDCOMUNE, ID);

alter table ALBEROPROC add PAROLE_CHIAVE varchar2(1000);
alter table INVENTARIOPROCEDIMENTI add PAROLE_CHIAVE varchar2(1000);

CREATE TABLE JOB_REPOSITORY_PARAM  (
  ID NUMBER(10,0) NOT NULL,
  ETICHETTA VARCHAR2(200) NOT NULL,
  DESCRIZIONE VARCHAR2(2000) NOT NULL,
  VALORE VARCHAR2(100) NOT NULL,
  FK_JOB_REPOSITORY NUMBER(6,0) NOT NULL
);

CREATE UNIQUE INDEX JOB_REPOSITORY_PARAM_PK ON JOB_REPOSITORY_PARAM (ID) ; 
ALTER TABLE JOB_REPOSITORY_PARAM ADD CONSTRAINT JOB_REPOSITORY_PARAM_PK PRIMARY KEY (ID);

ALTER TABLE JOB_REPOSITORY_PARAM
ADD CONSTRAINT FK_JOB_REP_JOB_REP_PAR
FOREIGN KEY (FK_JOB_REPOSITORY) 
REFERENCES JOB_REPOSITORY(ID);

CREATE UNIQUE INDEX JOB_REPOSITORY_PARAM_PK ON JOB_REPOSITORY_PARAM (ID) ; 
ALTER TABLE JOB_REPOSITORY_PARAM ADD CONSTRAINT JOB_REPOSITORY_PARAM_PK PRIMARY KEY (ID);

ALTER TABLE JOB_REPOSITORY_PARAM
ADD CONSTRAINT FK_JOB_REP_JOB_REP_PAR
FOREIGN KEY (FK_JOB_REPOSITORY) 
REFERENCES JOB_REPOSITORY(ID);
