//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Init.SIGePro.Manager.WsMailService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://gruppoinit.it/MailService/", ConfigurationName="WsMailService.MailServicePortType")]
    internal interface MailServicePortType {
        
        // CODEGEN: Generating message contract since the operation sendMail is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://gruppoinit.it/MailService/sendMail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Init.SIGePro.Manager.WsMailService.sendMailResponse sendMail(Init.SIGePro.Manager.WsMailService.sendMailRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gruppoinit.it/mailService/schemas/messages")]
    public partial class MessageRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        private string softwareField;
        
        private string codicemovimentoField;
        
        private MailMessageType mailMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string software {
            get {
                return this.softwareField;
            }
            set {
                this.softwareField = value;
                this.RaisePropertyChanged("software");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string codicemovimento {
            get {
                return this.codicemovimentoField;
            }
            set {
                this.codicemovimentoField = value;
                this.RaisePropertyChanged("codicemovimento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public MailMessageType mailMessage {
            get {
                return this.mailMessageField;
            }
            set {
                this.mailMessageField = value;
                this.RaisePropertyChanged("mailMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gruppoinit.it/mailService/schemas/messages")]
    public partial class MailMessageType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool inviaComeHtmlField;
        
        private bool inviaComeHtmlFieldSpecified;
        
        private string mittenteField;
        
        private string corpoMailField;
        
        private string oggettoField;
        
        private string destinatariField;
        
        private string destinatariInCopiaField;
        
        private string destinatariInCopiaNascostaField;
        
        private string messageIDField;
        
        private AttachmentType[] attachmentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool inviaComeHtml {
            get {
                return this.inviaComeHtmlField;
            }
            set {
                this.inviaComeHtmlField = value;
                this.RaisePropertyChanged("inviaComeHtml");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool inviaComeHtmlSpecified {
            get {
                return this.inviaComeHtmlFieldSpecified;
            }
            set {
                this.inviaComeHtmlFieldSpecified = value;
                this.RaisePropertyChanged("inviaComeHtmlSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string mittente {
            get {
                return this.mittenteField;
            }
            set {
                this.mittenteField = value;
                this.RaisePropertyChanged("mittente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string corpoMail {
            get {
                return this.corpoMailField;
            }
            set {
                this.corpoMailField = value;
                this.RaisePropertyChanged("corpoMail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string oggetto {
            get {
                return this.oggettoField;
            }
            set {
                this.oggettoField = value;
                this.RaisePropertyChanged("oggetto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string destinatari {
            get {
                return this.destinatariField;
            }
            set {
                this.destinatariField = value;
                this.RaisePropertyChanged("destinatari");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string destinatariInCopia {
            get {
                return this.destinatariInCopiaField;
            }
            set {
                this.destinatariInCopiaField = value;
                this.RaisePropertyChanged("destinatariInCopia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string destinatariInCopiaNascosta {
            get {
                return this.destinatariInCopiaNascostaField;
            }
            set {
                this.destinatariInCopiaNascostaField = value;
                this.RaisePropertyChanged("destinatariInCopiaNascosta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string messageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
                this.RaisePropertyChanged("messageID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=8)]
        [System.Xml.Serialization.XmlArrayItemAttribute("attachment", IsNullable=false)]
        public AttachmentType[] attachments {
            get {
                return this.attachmentsField;
            }
            set {
                this.attachmentsField = value;
                this.RaisePropertyChanged("attachments");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gruppoinit.it/mailService/schemas/messages")]
    public partial class AttachmentType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string descrizioneField;
        
        private string mimeTypeField;
        
        private string fileNameField;
        
        private byte[] binaryDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string descrizione {
            get {
                return this.descrizioneField;
            }
            set {
                this.descrizioneField = value;
                this.RaisePropertyChanged("descrizione");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string mimeType {
            get {
                return this.mimeTypeField;
            }
            set {
                this.mimeTypeField = value;
                this.RaisePropertyChanged("mimeType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("fileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=4)]
        public byte[] binaryData {
            get {
                return this.binaryDataField;
            }
            set {
                this.binaryDataField = value;
                this.RaisePropertyChanged("binaryData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gruppoinit.it/mailService/schemas/messages")]
    public partial class MessageResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string esitoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string esito {
            get {
                return this.esitoField;
            }
            set {
                this.esitoField = value;
                this.RaisePropertyChanged("esito");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class sendMailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gruppoinit.it/mailService/schemas/messages", Order=0)]
        public Init.SIGePro.Manager.WsMailService.MessageRequest MessageRequest;
        
        public sendMailRequest() {
        }
        
        public sendMailRequest(Init.SIGePro.Manager.WsMailService.MessageRequest MessageRequest) {
            this.MessageRequest = MessageRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class sendMailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gruppoinit.it/mailService/schemas/messages", Order=0)]
        public Init.SIGePro.Manager.WsMailService.MessageResponse MessageResponse;
        
        public sendMailResponse() {
        }
        
        public sendMailResponse(Init.SIGePro.Manager.WsMailService.MessageResponse MessageResponse) {
            this.MessageResponse = MessageResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface MailServicePortTypeChannel : Init.SIGePro.Manager.WsMailService.MailServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class MailServicePortTypeClient : System.ServiceModel.ClientBase<Init.SIGePro.Manager.WsMailService.MailServicePortType>, Init.SIGePro.Manager.WsMailService.MailServicePortType {
        
        public MailServicePortTypeClient() {
        }
        
        public MailServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MailServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MailServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MailServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Init.SIGePro.Manager.WsMailService.sendMailResponse Init.SIGePro.Manager.WsMailService.MailServicePortType.sendMail(Init.SIGePro.Manager.WsMailService.sendMailRequest request) {
            return base.Channel.sendMail(request);
        }
        
        public Init.SIGePro.Manager.WsMailService.MessageResponse sendMail(Init.SIGePro.Manager.WsMailService.MessageRequest MessageRequest) {
            Init.SIGePro.Manager.WsMailService.sendMailRequest inValue = new Init.SIGePro.Manager.WsMailService.sendMailRequest();
            inValue.MessageRequest = MessageRequest;
            Init.SIGePro.Manager.WsMailService.sendMailResponse retVal = ((Init.SIGePro.Manager.WsMailService.MailServicePortType)(this)).sendMail(inValue);
            return retVal.MessageResponse;
        }
    }
}
