ALTER TABLE AUTORIZZAZIONI_SUBENTRI ADD (FK_MERCATO NUMBER(4,0));
ALTER TABLE AUTORIZZAZIONI_SUBENTRI ADD (FK_USO NUMBER(4,0));
ALTER TABLE AUTORIZZAZIONI_SUBENTRI ADD (FK_MERCATOD NUMBER(6,0));
ALTER TABLE AUTORIZZAZIONI_SUBENTRI ADD (FK_CONCESSIONITIPI VARCHAR2(2 BYTE));
ALTER TABLE AUTORIZZAZIONI_SUBENTRI ADD (STAGIONALE_DA DATE);
ALTER TABLE AUTORIZZAZIONI_SUBENTRI ADD (STAGIONALE_A DATE);

ALTER TABLE AUTORIZZAZIONI_SUBENTRI ADD CONSTRAINT FK_AUT_SUB_MERCATO FOREIGN KEY(IDCOMUNE,FK_MERCATO) REFERENCES MERCATI(IDCOMUNE,CODICEMERCATO);
ALTER TABLE AUTORIZZAZIONI_SUBENTRI ADD CONSTRAINT FK_AUT_SUB_MERC_USO FOREIGN KEY(IDCOMUNE,FK_USO) REFERENCES MERCATI_USO(IDCOMUNE,ID);
ALTER TABLE AUTORIZZAZIONI_SUBENTRI ADD CONSTRAINT FK_AUT_SUB_MERCATOD FOREIGN KEY(IDCOMUNE,FK_MERCATOD) REFERENCES MERCATI_D(IDCOMUNE,IDPOSTEGGIO);
ALTER TABLE AUTORIZZAZIONI_SUBENTRI ADD CONSTRAINT FK_AUT_SUB_CONCTIPI FOREIGN KEY(FK_CONCESSIONITIPI) REFERENCES CONCESSIONITIPI(TIPOCONCESSIONE);

ALTER TABLE I_ATTIVITA ADD (DATA_INIZIO DATE);
ALTER TABLE I_ATTIVITA ADD (DATA_FINE DATE);

ALTER TABLE fo_domande ADD CODICEISTANZA_ORIGINE NUMBER(6,0);

CREATE TABLE PROTOCOLLO_CLASSIFICHE 
(
  IDCOMUNE VARCHAR2(6) NOT NULL 
, CODICE VARCHAR2(50) NOT NULL 
, DESCRIZIONE VARCHAR2(100) NOT NULL 
, CODICECOMUNE VARCHAR2(5) 
, SOFTWARE VARCHAR2(2) 
, ID NUMBER(10) NOT NULL
) ;

ALTER TABLE PROTOCOLLO_CLASSIFICHE ADD CONSTRAINT PROTOCOLLO_CLASSIFICHE_PK PRIMARY KEY(  IDCOMUNE   , ID ) ;

ALTER TABLE PROTOCOLLO_CLASSIFICHE ADD CONSTRAINT PROT_CLASSIFICHE_COMUNI FOREIGN KEY(  CODICECOMUNE ) REFERENCES COMUNI(  CODICECOMUNE) ENABLE;

ALTER TABLE PROTOCOLLO_CLASSIFICHE ADD CONSTRAINT PROT_CLASSIFICHE_SOFTWARE FOREIGN KEY (   SOFTWARE) REFERENCES SOFTWARE (   CODICE ) ENABLE;

ALTER TABLE PROTOCOLLO_CLASSIFICHE MODIFY (DESCRIZIONE VARCHAR2(500 BYTE) );

CREATE TABLE ISTANZE_INOLTRATE_TRIB
  (
    IDCOMUNE      VARCHAR2(6),
    CODICEISTANZA NUMBER(6,0)
  );
ALTER TABLE ISTANZE_INOLTRATE_TRIB ADD CONSTRAINT PK_ISTANZE_INOLTRATE_TRIB PRIMARY KEY (idcomune,codiceistanza);

CREATE TABLE PEOPLEPROCSPORTELLI (
ID NUMBER(10) NOT NULL, 
IDCOMUNE VARCHAR2(6 BYTE) NOT NULL, 
CODICECOMUNE VARCHAR2(5 BYTE), 
PEOPLE_PROC VARCHAR2(20 BYTE), 
SOFTWARE VARCHAR2(2 BYTE)
);
   
ALTER TABLE PEOPLEPROCSPORTELLI ADD CONSTRAINT PEOPLEPROCSPORTELLI_PK PRIMARY KEY (IDCOMUNE, ID);


DELETE FROM INTERESSI_LEGALI;

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (1,TO_DATE('21-04-1942','dd-MM-yyyy'),TO_DATE('15-12-1990','dd-MM-yyyy'),5,null);

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (2,TO_DATE('16-12-1990','dd-MM-yyyy'),TO_DATE('31-12-1996','dd-MM-yyyy'),10,'Legge 26 novembre 1990, n. 353'); 

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (3,TO_DATE('01-01-1997','dd-MM-yyyy'),TO_DATE('31-12-1998','dd-MM-yyyy'),5,'Legge 23 dicembre 1996, n. 662'); 

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (4,TO_DATE('01-01-1999','dd-MM-yyyy'),TO_DATE('31-12-2000','dd-MM-yyyy'),2.5,'D.M. 10 dicembre 1998');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (5,TO_DATE('01-01-2001','dd-MM-yyyy'),TO_DATE('31-12-2001','dd-MM-yyyy'),3.5,'D.M. 11 dicembre 2000');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (6,TO_DATE('01-01-2002','dd-MM-yyyy'),TO_DATE('31-12-2003','dd-MM-yyyy'),3,'D.M. 11 dicembre 2001');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (7,TO_DATE('01-01-2004','dd-MM-yyyy'),TO_DATE('31-12-2007','dd-MM-yyyy'),2.5,'D.M. 1 dicembre 2003');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (8,TO_DATE('01-01-2008','dd-MM-yyyy'),TO_DATE('31-12-2009','dd-MM-yyyy'),3,'D.M. 12 dicembre 2007');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (9,TO_DATE('01-01-2010','dd-MM-yyyy'),TO_DATE('31-12-2010','dd-MM-yyyy'),1,'D.M. 4 dicembre 2009');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (10,TO_DATE('01-01-2011','dd-MM-yyyy'),TO_DATE('31-12-2011','dd-MM-yyyy'),1.5,'D.M. 07 Dicembre 2010');

insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (11,TO_DATE('01-01-2012','dd-MM-yyyy'),TO_DATE('31-12-2013','dd-MM-yyyy'),2.5,'DM 12 dicembre 2011');
Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (12,to_date('01-01-2014','dd-MM-yyyy'),TO_DATE('31-12-2014','dd-MM-yyyy'),1,'Dm Economia 13.12.2013');
Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (13,to_date('01-01-2015','dd-MM-yyyy'),TO_DATE('31-12-2015','dd-MM-yyyy'),0.5,'Dm Economia 11.12.2014');
Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (14,to_date('01-01-2016','dd-MM-yyyy'),to_date('31-12-2016','dd-MM-yyyy'),0.2,'Dm Economia 11.12.2015');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (15,to_date('01-01-2017','dd-MM-yyyy'),null,0.1,'Dm economia e finanze 07/12/2016,G.U.14/12/2016');

ALTER TABLE SORTEGGIDETTAGLIO ADD FLAG_INTERVENTO_OBBLIGATORIO NUMBER(1,0);