<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>true</ImplicitUsings>
		<RootNamespace>AspnetCoreServices</RootNamespace>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<DockerfileContext>..\..</DockerfileContext>
		<DockerfileTag>vbg.aspnet-core-services</DockerfileTag>
		<Configurations>Debug;Release;ReleaseFramework</Configurations>
		<DockerImageLabels>BUILD_DATE=$([System.DateTime]::Now.ToString("yyyy.MM.dd"))</DockerImageLabels>
		<DockerfileBuildArguments>--build-arg PAT=$(PAT)</DockerfileBuildArguments>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<Platforms>AnyCPU</Platforms>
	</PropertyGroup>

	<ItemGroup>
		<Using Include="CoreWCF" />
		<Using Include="CoreWCF.Configuration" />
		<Using Include="CoreWCF.Channels" />
		<Using Include="CoreWCF.Description" />
		<Using Include="System.Runtime.Serialization " />
		<Using Include="Microsoft.Extensions.DependencyInjection.Extensions" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="CoreWCF.Primitives" Version="1.*" />
		<PackageReference Include="CoreWCF.Http" Version="1.*" />
		<PackageReference Include="Gelf4Net.UdpAppender" Version="1.0.3.1" />
		<PackageReference Include="log4net" Version="3.3.2" />
		<PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="10.0.*" />
		<PackageReference Include="Microsoft.Extensions.Logging.Log4Net.AspNetCore" Version="10.0.0" />
		<PackageReference Include="Microsoft.Extensions.ServiceDiscovery" Version="10.8.0" />
		<PackageReference Include="Microsoft.Extensions.ServiceDiscovery.Dns" Version="10.8.0" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
		<PackageReference Include="System.Text.Encodings.Web" Version="10.0.*" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\SIGePro.Exceptions\SIGePro.Exceptions.csproj" />
	  <ProjectReference Include="..\SIGePro.Manager.Authentication\SIGePro.Manager.Authentication.csproj" />
	  <ProjectReference Include="..\SIGePro.Manager.Configuration\SIGePro.Manager.Configuration.csproj" />
	  <ProjectReference Include="..\SIGePro.Manager.DTO\SIGePro.Manager.DTO.csproj" />
	  <ProjectReference Include="..\SIGePro.Manager.Utils\SIGePro.Manager.Utils.csproj" />
	  <ProjectReference Include="..\SIGePro.Manager.Verticalizzazioni\SIGePro.Manager.Verticalizzazioni.csproj" />
	  <ProjectReference Include="..\SIGePro.Manager\SIGePro.Manager.csproj" />
	</ItemGroup>
</Project>