ALTER TABLE amministrazioni MODIFY STC_IDSPORTELLO VARCHAR(30);
ALTER TABLE domandestc MODIFY ID_SPORTELLOMITT VARCHAR(30);

alter table tipicausalioneri add  column mappaturanodopag varchar(50);
alter table tipicausalioneri add  column codicetassonomia varchar(12);

ALTER TABLE TIPOLOGIAREGISTRI ADD COLUMN NUMERAZIONE_CUSTOM VARCHAR(50) NULL;

ALTER TABLE TIPOLOGIAREGISTRI MODIFY TR_FLAGDATAAUTO DECIMAL(1,0) DEFAULT 0;

update TIPOLOGIAREGISTRI set TR_FLAGDATAAUTO = 0 where TR_FLAGDATAAUTO  is null;

ALTER TABLE TIPOLOGIAREGISTRI MODIFY TR_FLAGDATAAUTO DECIMAL(1,0) DEFAULT 0 not null;

alter table pay_registrazioni_contabili add column codicetassonomia varchar(12);

CREATE TABLE boll_gest_oneri_sequence(
idcomune VARCHAR(6) NOT NULL
,fk_codiceistanzeoneri NUMERIC(10,0) NOT NULL
,id_bollegest_dett NUMERIC(10,0) NOT NULL
,id_bollegest_oneri NUMERIC(10,0) NOT NULL
, guid VARCHAR(60) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE INDEX idx_boll_oneri_sequence_001 ON boll_gest_oneri_sequence (idcomune,fk_codiceistanzeoneri);
CREATE INDEX idx_boll_oneri_sequence_002 ON boll_gest_oneri_sequence (guid);
ALTER TABLE boll_gest_oneri_sequence ADD CONSTRAINT fk_bollgestoneriseq_istoneri FOREIGN KEY (idcomune,fk_codiceistanzeoneri) REFERENCES istanzeoneri(idcomune,id);


ALTER TABLE AUTORIZZAZIONI ADD COLUMN FKIDPROTOCOLLO VARCHAR(400);
ALTER TABLE AUTORIZZAZIONI ADD COLUMN MODIFICABLOCCATA DECIMAL(1,0); 
UPDATE AUTORIZZAZIONI SET MODIFICABLOCCATA = 0 WHERE MODIFICABLOCCATA IS NULL;
ALTER TABLE AUTORIZZAZIONI MODIFY COLUMN MODIFICABLOCCATA DECIMAL(1,0) NOT NULL DEFAULT 0;
ALTER TABLE DOCUMENTI_AUTORIZZAZIONE ADD COLUMN PRINCIPALE DECIMAL(1,0) DEFAULT 0;
UPDATE DOCUMENTI_AUTORIZZAZIONE SET PRINCIPALE = 0 WHERE PRINCIPALE IS NULL;
ALTER TABLE DOCUMENTI_AUTORIZZAZIONE MODIFY COLUMN PRINCIPALE DECIMAL(1,0) NOT NULL DEFAULT 0;
ALTER TABLE DOCUMENTI_AUTORIZZAZIONE ADD COLUMN RIFERIMENTO_ESTERNO VARCHAR(50);
CREATE TABLE AUTORIZZAZIONI_METADATI(IDCOMUNE VARCHAR(6) NOT NULL, FKIDAUTORIZZAZIONE DECIMAL(6,0) NOT NULL, CHIAVE VARCHAR(100) NOT NULL, VALORE VARCHAR(4000) NOT NULL) ENGINE=INNODB DEFAULT CHARSET=utf8;
ALTER TABLE AUTORIZZAZIONI_METADATI ADD CONSTRAINT PK_AUTORIZZAZIONIMETADATI PRIMARY KEY(IDCOMUNE,FKIDAUTORIZZAZIONE,CHIAVE);
ALTER TABLE AUTORIZZAZIONI_METADATI ADD CONSTRAINT FK_AUTORIZZAZIONI FOREIGN KEY(IDCOMUNE,FKIDAUTORIZZAZIONE) REFERENCES AUTORIZZAZIONI(IDCOMUNE,ID);

