
ALTER TABLE ANAGRAFE ADD FLAG_IDENTIFICATO NUMERIC(1,0);

ALTER TABLE ANAGRAFE ADD OPER_IDENTIFICAZIONE NUMERIC(8,0);

ALTER TABLE ANAGRAFE ADD CONSTRAINT FK_ANAGRAFE_RESPIDENT FOREIGN KEY (IDCOMUNE, OPER_IDENTIFICAZIONE) REFERENCES RESPONSABILI (IDCOMUNE, CODICERESPONSABILE);

ALTER TABLE ANAGRAFE ADD DATA_IDENTIFICAZIONE DATETIME;


ALTER TABLE ANAGRAFESTORICO ADD FLAG_IDENTIFICATO NUMERIC(1,0);

ALTER TABLE ANAGRAFESTORICO ADD OPER_IDENTIFICAZIONE NUMERIC(8,0);

ALTER TABLE ANAGRAFESTORICO ADD CONSTRAINT FK_ANAGRAFEST_RESPIDENT FOREIGN KEY (IDCOMUNE, OPER_IDENTIFICAZIONE) REFERENCES RESPONSABILI (IDCOMUNE, CODICERESPONSABILE);

ALTER TABLE ANAGRAFESTORICO ADD DATA_IDENTIFICAZIONE DATETIME;

DELETE FROM INTERESSI_LEGALI;

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (1,STR_TO_DATE('21-04-1942','%d-%m-%Y'),STR_TO_DATE('15-12-1990','%d-%m-%Y'),5,null);

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (2,STR_TO_DATE('16-12-1990','%d-%m-%Y'),STR_TO_DATE('31-12-1996','%d-%m-%Y'),10,'Legge 26 novembre 1990, n. 353'); 

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (3,STR_TO_DATE('01-01-1997','%d-%m-%Y'),STR_TO_DATE('31-12-1998','%d-%m-%Y'),5,'Legge 23 dicembre 1996, n. 662'); 

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (4,STR_TO_DATE('01-01-1999','%d-%m-%Y'),STR_TO_DATE('31-12-2000','%d-%m-%Y'),2.5,'D.M. 10 dicembre 1998');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (5,STR_TO_DATE('01-01-2001','%d-%m-%Y'),STR_TO_DATE('31-12-2001','%d-%m-%Y'),3.5,'D.M. 11 dicembre 2000');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (6,STR_TO_DATE('01-01-2002','%d-%m-%Y'),STR_TO_DATE('31-12-2003','%d-%m-%Y'),3,'D.M. 11 dicembre 2001');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (7,STR_TO_DATE('01-01-2004','%d-%m-%Y'),STR_TO_DATE('31-12-2007','%d-%m-%Y'),2.5,'D.M. 1 dicembre 2003');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (8,STR_TO_DATE('01-01-2008','%d-%m-%Y'),STR_TO_DATE('31-12-2009','%d-%m-%Y'),3,'D.M. 12 dicembre 2007');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (9,STR_TO_DATE('01-01-2010','%d-%m-%Y'),STR_TO_DATE('31-12-2010','%d-%m-%Y'),1,'D.M. 4 dicembre 2009');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (10,STR_TO_DATE('01-01-2011','%d-%m-%Y'),STR_TO_DATE('31-12-2011','%d-%m-%Y'),1.5,'D.M. 07 Dicembre 2010');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (11,STR_TO_DATE('01-01-2012','%d-%m-%Y'),STR_TO_DATE('31-12-2013','%d-%m-%Y'),2.5,'DM 12 dicembre 2011');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (12,STR_TO_DATE('01-01-2014','%d-%m-%Y'),STR_TO_DATE('31-12-2014','%d-%m-%Y'),1,'Dm Economia 13.12.2013');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (13,STR_TO_DATE('01-01-2015','%d-%m-%Y'),STR_TO_DATE('31-12-2015','%d-%m-%Y'),0.5,'Dm Economia 11.12.2014');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (14,STR_TO_DATE('01-01-2016','%d-%m-%Y'),null,0.2,'Dm Economia 11.12.2015');


CREATE TABLE ALBEROPROC_DOC_SOGG_FIRMATARI(
  ID NUMERIC(10,0) NOT NULL,
  IDCOMUNE VARCHAR(6) NOT NULL,
  FK_TIPO_SOGGETTO NUMERIC(10,0) NOT NULL,
  FK_ALBEROPROC_DOCUMENTI NUMERIC(10,0) NOT NULL
)  ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE UNIQUE INDEX ALBEROPROC_DOC_SOGG_FIRM_PK ON ALBEROPROC_DOC_SOGG_FIRMATARI (IDCOMUNE,ID);
ALTER TABLE ALBEROPROC_DOC_SOGG_FIRMATARI ADD CONSTRAINT ALBEROPROC_DOC_SOGG_FIRM_PK PRIMARY KEY (IDCOMUNE,ID);

ALTER TABLE ALBEROPROC_DOC_SOGG_FIRMATARI 
ADD CONSTRAINT FK_SOGG_FIRM_TIPO_SOGGETTO
FOREIGN KEY (IDCOMUNE, FK_TIPO_SOGGETTO) 
REFERENCES TIPISOGGETTO (IDCOMUNE, CODICETIPOSOGGETTO);

ALTER TABLE ALBEROPROC_DOC_SOGG_FIRMATARI 
ADD CONSTRAINT FK_SOGG_FIRM_ALBEROPROC_DOC
FOREIGN KEY (IDCOMUNE, FK_ALBEROPROC_DOCUMENTI) 
REFERENCES ALBEROPROC_DOCUMENTI (IDCOMUNE, SM_ID);

CREATE TABLE INVENTARIOPROC_SOGG_FIRMATARI(
  ID NUMERIC(10,0) NOT NULL,
  IDCOMUNE VARCHAR(6) NOT NULL,
  FK_TIPO_SOGGETTO NUMERIC(10,0) NOT NULL,
  FK_DOCUMENTI NUMERIC(8,0) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE UNIQUE INDEX INVENTARIOPROC_SOGG_FIRM_PK ON INVENTARIOPROC_SOGG_FIRMATARI (IDCOMUNE,ID);
ALTER TABLE INVENTARIOPROC_SOGG_FIRMATARI ADD CONSTRAINT INVENTARIOPROC_SOGG_FIRM_PK PRIMARY KEY (IDCOMUNE,ID);

ALTER TABLE INVENTARIOPROC_SOGG_FIRMATARI 
ADD CONSTRAINT FK_INVENT_SOGG_FIRM_TIPO_SOGG
FOREIGN KEY (IDCOMUNE, FK_TIPO_SOGGETTO) 
REFERENCES TIPISOGGETTO (IDCOMUNE, CODICETIPOSOGGETTO);

ALTER TABLE INVENTARIOPROC_SOGG_FIRMATARI 
ADD CONSTRAINT FK_SOGG_FIRM_INVET_PROC_DOC
FOREIGN KEY (IDCOMUNE, FK_DOCUMENTI) 
REFERENCES DOCUMENTI (IDCOMUNE, ID);

ALTER TABLE TIPIMOVIMENTO_COMUNICAZIONI ADD DESTINATARI_MAIL VARCHAR(50) ;


ALTER TABLE TIPIMOVIMENTO_COMUNICAZIONI ADD FLAG_INSERIMENTO_MOV NUMERIC(1,0) ;
ALTER TABLE TIPIMOVIMENTO_COMUNICAZIONI MODIFY FUNZIONE VARCHAR(100) ;