<?xml version="1.0" ?><wsdl:definitions targetNamespace="http://sigepro.init.it/rte/definitions" xmlns:sch0="http://sigepro.init.it/rte" xmlns:sch1="http://sigepro.init.it/rte/types" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://sigepro.init.it/rte/definitions" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
<schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://sigepro.init.it/rte/elements" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:sch0="http://sigepro.init.it/rte" xmlns:sch1="http://sigepro.init.it/rte/types" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://sigepro.init.it/rte" xmlns:types="http://sigepro.init.it/rte/types" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
			<import namespace="http://sigepro.init.it/rte" schemaLocation="./nla.xsd"></import>
		</schema>
  </wsdl:types>
  <wsdl:message name="RichiestaPraticheListaNLAResponse">
    <wsdl:part element="sch0:RichiestaPraticheListaNLAResponse" name="RichiestaPraticheListaNLAResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="InserimentoAttivitaNLAResponse">
    <wsdl:part element="sch0:InserimentoAttivitaNLAResponse" name="InserimentoAttivitaNLAResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="InserimentoPraticaNLAResponse">
    <wsdl:part element="sch0:InserimentoPraticaNLAResponse" name="InserimentoPraticaNLAResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="InserimentoAttivitaNLARequest">
    <wsdl:part element="sch0:InserimentoAttivitaNLARequest" name="InserimentoAttivitaNLARequest">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="TestNLAResponse">
    <wsdl:part element="sch0:TestNLAResponse" name="TestNLAResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="AggiungiDocumentiNLARequest">
    <wsdl:part element="sch0:AggiungiDocumentiNLARequest" name="AggiungiDocumentiNLARequest">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="AggiungiDocumentiNLAResponse">
    <wsdl:part element="sch0:AggiungiDocumentiNLAResponse" name="AggiungiDocumentiNLAResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="TestNLARequest">
    <wsdl:part element="sch0:TestNLARequest" name="TestNLARequest">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="InserimentoPraticaNLARequest">
    <wsdl:part element="sch0:InserimentoPraticaNLARequest" name="InserimentoPraticaNLARequest">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="AllegatoBinarioNLARequest">
    <wsdl:part element="sch0:AllegatoBinarioNLARequest" name="AllegatoBinarioNLARequest">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="AllegatoBinarioNLAResponse">
    <wsdl:part element="sch0:AllegatoBinarioNLAResponse" name="AllegatoBinarioNLAResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="RichiestaPraticaNLARequest">
    <wsdl:part element="sch0:RichiestaPraticaNLARequest" name="RichiestaPraticaNLARequest">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="RichiestaPraticheListaNLARequest">
    <wsdl:part element="sch0:RichiestaPraticheListaNLARequest" name="RichiestaPraticheListaNLARequest">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="RichiestaPraticaNLAResponse">
    <wsdl:part element="sch0:RichiestaPraticaNLAResponse" name="RichiestaPraticaNLAResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="Nla">
    <wsdl:operation name="RichiestaPraticheListaNLA">
      <wsdl:input message="tns:RichiestaPraticheListaNLARequest" name="RichiestaPraticheListaNLARequest">
    </wsdl:input>
      <wsdl:output message="tns:RichiestaPraticheListaNLAResponse" name="RichiestaPraticheListaNLAResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="InserimentoPraticaNLA">
      <wsdl:input message="tns:InserimentoPraticaNLARequest" name="InserimentoPraticaNLARequest">
    </wsdl:input>
      <wsdl:output message="tns:InserimentoPraticaNLAResponse" name="InserimentoPraticaNLAResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="RichiestaPraticaNLA">
      <wsdl:input message="tns:RichiestaPraticaNLARequest" name="RichiestaPraticaNLARequest">
    </wsdl:input>
      <wsdl:output message="tns:RichiestaPraticaNLAResponse" name="RichiestaPraticaNLAResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="TestNLA">
      <wsdl:input message="tns:TestNLARequest" name="TestNLARequest">
    </wsdl:input>
      <wsdl:output message="tns:TestNLAResponse" name="TestNLAResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="InserimentoAttivitaNLA">
      <wsdl:input message="tns:InserimentoAttivitaNLARequest" name="InserimentoAttivitaNLARequest">
    </wsdl:input>
      <wsdl:output message="tns:InserimentoAttivitaNLAResponse" name="InserimentoAttivitaNLAResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="AllegatoBinarioNLA">
      <wsdl:input message="tns:AllegatoBinarioNLARequest" name="AllegatoBinarioNLARequest">
    </wsdl:input>
      <wsdl:output message="tns:AllegatoBinarioNLAResponse" name="AllegatoBinarioNLAResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="AggiungiDocumentiNLA">
      <wsdl:input message="tns:AggiungiDocumentiNLARequest" name="AggiungiDocumentiNLARequest">
    </wsdl:input>
      <wsdl:output message="tns:AggiungiDocumentiNLAResponse" name="AggiungiDocumentiNLAResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="NlaSoap11" type="tns:Nla">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"></soap:binding>
    <wsdl:operation name="RichiestaPraticheListaNLA">
      <soap:operation soapAction=""></soap:operation>
      <wsdl:input name="RichiestaPraticheListaNLARequest">
        <soap:body use="literal"></soap:body>
      </wsdl:input>
      <wsdl:output name="RichiestaPraticheListaNLAResponse">
        <soap:body use="literal"></soap:body>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="InserimentoPraticaNLA">
      <soap:operation soapAction=""></soap:operation>
      <wsdl:input name="InserimentoPraticaNLARequest">
        <soap:body use="literal"></soap:body>
      </wsdl:input>
      <wsdl:output name="InserimentoPraticaNLAResponse">
        <soap:body use="literal"></soap:body>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="RichiestaPraticaNLA">
      <soap:operation soapAction=""></soap:operation>
      <wsdl:input name="RichiestaPraticaNLARequest">
        <soap:body use="literal"></soap:body>
      </wsdl:input>
      <wsdl:output name="RichiestaPraticaNLAResponse">
        <soap:body use="literal"></soap:body>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="TestNLA">
      <soap:operation soapAction=""></soap:operation>
      <wsdl:input name="TestNLARequest">
        <soap:body use="literal"></soap:body>
      </wsdl:input>
      <wsdl:output name="TestNLAResponse">
        <soap:body use="literal"></soap:body>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="InserimentoAttivitaNLA">
      <soap:operation soapAction=""></soap:operation>
      <wsdl:input name="InserimentoAttivitaNLARequest">
        <soap:body use="literal"></soap:body>
      </wsdl:input>
      <wsdl:output name="InserimentoAttivitaNLAResponse">
        <soap:body use="literal"></soap:body>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="AllegatoBinarioNLA">
      <soap:operation soapAction=""></soap:operation>
      <wsdl:input name="AllegatoBinarioNLARequest">
        <soap:body use="literal"></soap:body>
      </wsdl:input>
      <wsdl:output name="AllegatoBinarioNLAResponse">
        <soap:body use="literal"></soap:body>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="AggiungiDocumentiNLA">
      <soap:operation soapAction=""></soap:operation>
      <wsdl:input name="AggiungiDocumentiNLARequest">
        <soap:body use="literal"></soap:body>
      </wsdl:input>
      <wsdl:output name="AggiungiDocumentiNLAResponse">
        <soap:body use="literal"></soap:body>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="NlaService">
    <wsdl:port binding="tns:NlaSoap11" name="NlaSoap11">
      <soap:address location="http://devel9:8080/ibcstc/services/nla"></soap:address>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>