ALTER TABLE PROTOCOLLO_REGISTRI DROP CONSTRAINT FK_PROTREG_TIPOLOGIAREG;
ALTER TABLE PROTOCOLLO_REGISTRI DROP PRIMARY KEY DROP INDEX;
ALTER TABLE PROTOCOLLO_REGISTRI MODIFY ID NUMBER(10,0) NOT NULL;
ALTER TABLE PROTOCOLLO_REGISTRI ADD CONSTRAINT PROTOCOLLO_REGISTRI_PK PRIMARY KEY (IDCOMUNE, ID);