ALTER TABLE dyn2_modellid MODIFY posorizzontale numeric(2);

ALTER TABLE PDF_MAPPATURE DROP PRIMARY KEY;
ALTER TABLE PDF_MAPPATURE MODIFY LABEL VARCHAR(255);
alter table PDF_MAPPATURE ADD CONSTRAINT PK_PDF_MAPPATURE PRIMARY KEY (LABEL);

CREATE TABLE TIPI_LOCALIZZAZIONI 
(
  IDCOMUNE VARCHAR(6) NOT NULL 
, ID NUMERIC(10, 0) NOT NULL 
, DESCRIZIONE VARCHAR(50) NOT NULL 
, CONSTRAINT TIPI_LOCALIZZAZIONI_PK PRIMARY KEY 
  (
    IDCOMUNE 
  , ID 
  )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


ALTER TABLE istanzestradario ADD tipolocalizzazione_id numeric(10,0);
ALTER TABLE ISTANZESTRADARIO ADD CONSTRAINT FK_ISTANZESTRADARIO_TIPILOC FOREIGN KEY (IDCOMUNE, TIPOLOCALIZZAZIONE_ID) REFERENCES TIPI_LOCALIZZAZIONI( IDCOMUNE, ID );

ALTER TABLE istanzestradario ADD uuid VARCHAR(50);
UPDATE istanzestradario SET uuid = UUID();

ALTER TABLE ISTANZESTRADARIO ADD LATITUDINE VARCHAR(50);
ALTER TABLE ISTANZESTRADARIO ADD LONGITUDINE VARCHAR(50);

ALTER TABLE MERCATI ADD TIPOCONTEGGIO_PRESENZE NUMERIC (2,0);

CREATE OR REPLACE ALGORITHM=TEMPTABLE View VW_MERCATIPRESENZETOTALI AS SELECT 'STORICO' AS ORIGINE, MERCATIPRESENZE_STORICO.IDCOMUNE, MERCATIPRESENZE_STORICO.ANNO, MERCATIPRESENZE_STORICO.CODICEANAGRAFE, MERCATIPRESENZE_STORICO.FK_AUTORIZZAZIONI_ID, MERCATIPRESENZE_STORICO.FKCODICEMERCATO, MERCATIPRESENZE_STORICO.FKIDMERCATIUSO, MERCATIPRESENZE_STORICO.FK_IDPOSTEGGIO AS FKIDPOSTEGGIO,  MERCATIPRESENZE_STORICO.NUMEROPRESENZE, TRIM( concat_ws('',ANAGRAFE.NOMINATIVO , ' ' , ANAGRAFE.NOME) ) AS ANAGRAFE, ANAGRAFE.CODICEFISCALE, ANAGRAFE.PARTITAIVA, COMUNI.COMUNE AS COMUNERESIDENZA, CITTADINANZA.CITTADINANZA, STR_TO_DATE(ANAGRAFE.DATAREGDITTE, '%d/%m/%Y' ) AS DATAREGDITTE FROM MERCATIPRESENZE_STORICO inner join ANAGRAFE on ANAGRAFE.IDCOMUNE = MERCATIPRESENZE_STORICO.IDCOMUNE AND ANAGRAFE.CODICEANAGRAFE = MERCATIPRESENZE_STORICO.CODICEANAGRAFE left outer join COMUNI on COMUNI.CODICECOMUNE = ANAGRAFE.COMUNERESIDENZA left outer join CITTADINANZA on CITTADINANZA.CODICE = ANAGRAFE.CODICECITTADINANZA UNION ALL  SELECT 'CALENDARIO' AS ORIGINE, MERCATIPRESENZE_T.IDCOMUNE, MERCATIPRESENZE_T.ANNO, MERCATIPRESENZE_D.CODICEANAGRAFE, MERCATIPRESENZE_D.FK_AUTORIZZAZIONI_ID, MERCATIPRESENZE_T.FKCODICEMERCATO, MERCATIPRESENZE_T.FKIDMERCATIUSO, MERCATIPRESENZE_D.FKIDPOSTEGGIO, MERCATIPRESENZE_D.NUMEROPRESENZE, TRIM( concat_ws('',ANAGRAFE.NOMINATIVO , ' ' , ANAGRAFE.NOME )) AS ANAGRAFE, ANAGRAFE.CODICEFISCALE, ANAGRAFE.PARTITAIVA, COMUNI.COMUNE AS COMUNERESIDENZA, CITTADINANZA.CITTADINANZA, STR_TO_DATE(ANAGRAFE.DATAREGDITTE, '%d/%m/%Y' ) AS DATAREGDITTE FROM MERCATIPRESENZE_T inner join MERCATIPRESENZE_D on MERCATIPRESENZE_D.IDCOMUNE = MERCATIPRESENZE_T.IDCOMUNE AND MERCATIPRESENZE_D.FKIDTESTATA = MERCATIPRESENZE_T.ID inner join ANAGRAFE on ANAGRAFE.IDCOMUNE = MERCATIPRESENZE_D.IDCOMUNE AND ANAGRAFE.CODICEANAGRAFE = MERCATIPRESENZE_D.CODICEANAGRAFE left outer join COMUNI on COMUNI.CODICECOMUNE = ANAGRAFE.COMUNERESIDENZA left outer join CITTADINANZA on CITTADINANZA.CODICE = ANAGRAFE.CODICECITTADINANZA;

ALTER TABLE PEC_INBOX ADD IN_LOGINNAME VARCHAR(320);

CREATE TABLE MERCATI_ELABPRESENZE(
IDCOMUNE  VARCHAR(6) NOT NULL,
ID        NUMERIC(4,0) NOT NULL,
FK_CODICEMERCATO NUMERIC(4,0) NOT NULL,
ANNO NUMERIC(4,0) NOT NULL,
DATA_ELABORAZIONE DATETIME
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE MERCATI_ELABPRESENZE ADD CONSTRAINT PK_MERCATIELABPRE PRIMARY KEY (IDCOMUNE, ID);
ALTER TABLE MERCATI_ELABPRESENZE ADD CONSTRAINT FK_MERELABP_MERCATI FOREIGN KEY (IDCOMUNE, FK_CODICEMERCATO) REFERENCES MERCATI(IDCOMUNE, CODICEMERCATO);
ALTER TABLE MERCATIPRESENZE_D MODIFY PROPRIETARIO NUMERIC(4,0);

ALTER TABLE ISTANZEALLEGATI ADD NECESSARIO NUMERIC(1,0);
ALTER TABLE DOCUMENTIISTANZA ADD CONTROLLOOK NUMERIC(1, 0);
ALTER TABLE MOVIMENTIALLEGATI ADD CONTROLLOOK NUMERIC(1, 0);

ALTER TABLE CONTENTTYPES MODIFY CT_MIMETYPE VARCHAR(100);

ALTER TABLE DYN2_MODELLID MODIFY POSORIZZONTALE NUMERIC(2,0);
ALTER TABLE TIPIMOV_STC_MAPPING ADD FLAG_NOTIFICAINTERAPRATICA NUMERIC(1,0);