<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup Label="Globals">
		<Configurations>Debug;Release;ReleaseFramework</Configurations>
		<Platforms>AnyCPU</Platforms>
	</PropertyGroup>

	<PropertyGroup>
		<TargetFrameworks>net10.0;net48</TargetFrameworks>
		<RootNamespace>Init.Sigepro.FrontEnd.Infrastructure</RootNamespace>
		<LangVersion>preview</LangVersion>
		<ImplicitUsings>disable</ImplicitUsings>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	</PropertyGroup>

	<ItemGroup>
		<Folder Include="Properties\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="log4net" Version="3.3.2" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.10" />
		<PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="18.7.23">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="ReflectionMagic" Version="5.0.1" />
		<PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.11" />
		<PackageReference Include="System.ServiceModel.Http" Version="10.0.652802" />
	</ItemGroup>


	<ItemGroup Condition=" '$(TargetFramework)' == 'net48' ">
		<Reference Include="System.ServiceModel" />
		<Reference Include="System.Web" />
		<PackageReference Include="Ninject" Version="3.3.6" />
		<PackageReference Include="Ninject.Web.Common" Version="3.3.2" />
	</ItemGroup>


	<ItemGroup>
	  <ProjectReference Include="..\..\VBG.Shared.Infrastructure\VBG.Shared.Infrastructure.csproj" />
	</ItemGroup>

</Project>