INSERT INTO verticalizzazioniparametribase(modulo, parametro, descrizione) VALUES('PROTOCOLLO_SIPRWEB', 'USA_WS_CLASSIFICHE','Indica se per il recupero delle classifiche, sull''albero degli interventi, debba essere usato il metodo messo a disposizione del web service (valore = 1) oppure no (valore 0, vuoto o non presente). E'' stato deciso di inserire questo parametro in quanto recuperare le classifiche da web service potrebbe essere macchinoso rendendo la pagina del dettaglio degli interventi molto lenta se i dati dovessero essere molti. Oltre tutto i dati potrebbero creare una lunga lista difficilmente leggibile dagli utenti. In ultimo, se dovesso essere modificati i codici, questi non sarebbero più direttamente visibili sul campo Classifica nel dettaglio degli interventi in quanto non più presenti nella lista.');

INSERT INTO verticalizzazioniparametribase(modulo, parametro, descrizione) VALUES('PROTOCOLLO_SIPRWEB', 'USA_WS_TIPIDOC','Indica se per il recupero delle tipologie di documento, sull''albero degli interventi, debba essere usato il metodo messo a disposizione del web service (valore = 1) oppure no (valore 0, vuoto o non presente). E'' stato deciso di inserire questo parametro in quanto recuperare le tipologie di documento da web service potrebbe essere macchinoso rendendo la pagina del dettaglio degli interventi molto lenta se i dati dovessero essere molti. Oltre tutto i dati potrebbero creare una lunga lista difficilmente leggibile dagli utenti. In ultimo, se dovesso essere modificati i codici'); 

INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,PROVINCIA,REGIONE,CAP,CF,CODICEISTAT,CODICEISTATREGIONE,CODICESTATOESTERO) VALUES ('M326','SCARPERIA E SAN PIERO','FI','FIRENZE','TOSCANA','50038','M326','048053','09',null);

INSERT INTO verticalizzazioniparametribase(modulo, parametro, descrizione) VALUES('PROTOCOLLO_IRIDE', 'SWAP_EMAIL', 'Valido solo per Iride2, è un tag che indica che tipo di comportamento deve assumere il recapito EMAIL, se il tag NON è presente oppure è presente con un qualsiasi valore diverso da S, il ws si comporta come ha sempre fatto (inserisce anagrafica se non esiste o va in aggiornamento sul tipo recapito indicato), se il tag è presente con il valore S esegue le seguenti operazioni: a) se il recapito per quel tipo e quel valore (considerando la valutazione case insensitive) esiste non si esegue nulla b) se il recapito per quel tipo esiste ma con valore diverso occorre: se non esiste un TipoRecapito X col valore attuale del recapito se ne inserisce uno nuovo dove X e’ il primo disponibile e successivamente si aggiorna il recapito con il VALORERECAPITO, se invece esiste lo stesso recapito sarà classificato come primo della lista.');

INSERT INTO SOFTWARE (CODICE, DESCRIZIONE, MODULOOPZIONALE, DESCRIZIONELUNGA, ACCESSORAPIDO, ORDINE) VALUES ('SG', 'Supporto Giuridico e Suap', '1', 'Supporto Giuridico e Suap', '0', '53');

INSERT INTO verticalizzazioniparametribase(modulo, parametro, descrizione) VALUES('PROTOCOLLO_DOCAREA', 'USA_DENOMINAZIONE_PG', 'Questo parametro indica se il componente che crea la segnatura da inviare come request al web service DOCAREA deve inserire la ragione sociale della persona giuridica sull''elemento <DENOMINAZIONE> presente dentro al nodo <MITTENTE> o <DESTINATARIO> (valore = a 1), o sull''elemento <COGNOME> (non presente, non valorizzato o valore diverso da 1); questo parametro si è reso necessario per il protocollo DocArea in quanto il web service installato da Maggioli (ad esempio Comune di Lucca) ha un limite, sull''elemento <COGNOME> che è quello che viene valorizzato di default con la Ragione Sociale della persona giuridica, di 40 caratteri, e può succedere di avere delle ragioni sociali più lunghe, quindi valorizzando a 1 questo parametro, la ragione sociale stessa verrebbe dirottata sull''elemento <DENOMINAZIONE>, che non ha limiti. Il web service DocArea di altre aziende (ad esempio Ads) non avendo limiti di lunghezza, non permette questo tipo di sistema, richiedendo che la ragione sociale passi necessariamente sull''elemento <COGNOME>, in questo caso questo parametro non va valorizzato (o comunque non va valorizzato a 1)'); 

INSERT INTO verticalizzazioniparametribase(modulo, parametro, descrizione) VALUES('PROTOCOLLO_DOCAREA', 'MULTI_MITT_DEST', 'Questo parametro indica se il componente che crea la segnatura da inviare come request al web service DOCAREA debba inviare tutte le anagrafiche che arrivano dal backoffice (valore uguale a 1), oppure solo la prima (non presente, valore vuoto o qualsiasi altro valore diverso da 1); in teoria, da specifiche DOCAREA non sarebbe possibile inviare più anagrafiche come MITTENTI / DESTINATARI, usare quindi questo parametro solamente in casi particolari dove il web service fornito dal fornitore di protocollo non tenga conto di questa regola'); 

INSERT INTO LAYOUTPAGINEBASE (LP_OGGETTO, DESCRIZIONE) VALUES ('fldCodicePraticaTelematica', 'Mostra o nasconde nella scheda istanza il campo CODICE_PRATICA_TELEMATICA');
INSERT INTO LAYOUTPAGINEBASE (LP_OGGETTO, DESCRIZIONE) VALUES ('fldIstanzeTecnico', 'Mostra o nasconde nella scheda dell''istanza il campo relativo al tecnico/intermediario');
INSERT INTO LAYOUTPAGINEBASE (LP_OGGETTO, DESCRIZIONE) VALUES ('sezIstanzeLocalizzazione', 'Mostra o nasconde nella scheda dell''istanza la sezione relativa alla localizzazione');
INSERT INTO LAYOUTPAGINEBASE (LP_OGGETTO, DESCRIZIONE) VALUES ('fldIstanzeNomeAttivita', 'mostra o nasconde il campo NOMEATTIVITA della scheda dell''istanza');

INSERT INTO COMUNI(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,PROVINCIA,REGIONE,CAP,CF,CODICEISTAT,CODICEISTATREGIONE) VALUES ('B737','CARBONARA DI BARI','BA','BARI','PUGLIA',NULL,'B737',NULL,16);

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('SIT_ATTIVO', 'URL_WSSIT', 'URL completo del componente WS Sit per l''integrazione tra il backoffice e i sistemi SIT esposti, se presente andrà a sovrascrivere quello di default che punta al componente doNet. Es. http://<ip-servert>:<port>/webapp/services/name_services?wsdl (http://devel9:8080/wssit/services/sit?wsdl)');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_SIGEDO', 'OPERATORE_RICERCHE_CLASSIFICHE', 'Parametro operatore usato nei metadati per eseguire la ricerca delle classifiche, invocando i servizi presenti sull''endpoint del parametro URL_QUERYSERVICE. Valore fisso da passare che però non ha niente a che fare ne con lo username del web service ne con gli operatori di protocollo.');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_SIGEDO', 'USA_WS_CLASSIFICHE', 'Indica se per il recupero delle classifiche, sull''albero degli interventi, debba essere usato il metodo messo a disposizione del web service (valore = 1) oppure no (valore 0, vuoto o non presente). E'' stato deciso di inserire questo parametro in quanto recuperare le classifiche da web service potrebbe essere macchinoso rendendo la pagina del dettaglio degli interventi molto lenta se i dati dovessero essere molti. Oltre tutto i dati potrebbero creare una lunga lista difficilmente leggibile dagli utenti. In ultimo, se dovesso essere modificati i codici, questi non sarebbero più direttamente visibili sul campo Classifica nel dettaglio degli interventi  quanto non più presenti nella lista.');

INSERT INTO MAPOGGETTI (NOMETABELLA, NOMECAMPO) VALUES ('DOCUMENTI_DA_FIRMARE','CODICEOGGETTO');


INSERT INTO  COMUNI (CODICECOMUNE,COMUNE,SIGLAPROVINCIA,PROVINCIA,REGIONE,CAP,CF,CODICEISTAT,CODICEISTATREGIONE,CODICESTATOESTERO) VALUES ('M324','POGGIO TORRIANA','RN','RIMINI','EMILIA ROMAGNA','47824','M324','099028','08',NULL);
INSERT INTO  COMUNI (CODICECOMUNE,COMUNE,SIGLAPROVINCIA,PROVINCIA,REGIONE,CAP,CF,CODICEISTAT,CODICEISTATREGIONE,CODICESTATOESTERO) VALUES ('M320','VALSAMOGGIA','BO','BOLOGNA','EMILIA ROMAGNA','40053','M320','037061','08',NULL);

INSERT INTO  COMUNI (CODICECOMUNE,COMUNE,SIGLAPROVINCIA,PROVINCIA,REGIONE,CAP,CF,CODICEISTAT,CODICEISTATREGIONE,CODICESTATOESTERO) VALUES ('M323','FISCAGLIA','FE','FERRARA','EMILIA ROMAGNA','44020','M323','038027','08',NULL);

INSERT INTO  comuni (CODICECOMUNE,COMUNE,SIGLAPROVINCIA,PROVINCIA,REGIONE,CAP,CF,CODICEISTAT,CODICEISTATREGIONE,CODICESTATOESTERO) VALUES ('M325','SISSA TRECASALI','PR','PARMA','EMILIA ROMAGNA','43018','M325','034049','08',NULL);

INSERT INTO  comuni (CODICECOMUNE,COMUNE,SIGLAPROVINCIA,PROVINCIA,REGIONE,CAP,CF,CODICEISTAT,CODICEISTATREGIONE,CODICESTATOESTERO) VALUES ('M317','RIVIGNANO TEOR','UD','UDINE','FRIULI VENEZIA GIULIA','33050','M317','030188','06',NULL);

INSERT INTO  comuni (CODICECOMUNE,COMUNE,SIGLAPROVINCIA,PROVINCIA,REGIONE,CAP,CF,CODICEISTAT,CODICEISTATREGIONE,CODICESTATOESTERO) VALUES ('M333','SANT''OMOBONO TERME','BG','BERGAMO','LOMBARDIA','24038','M333','016252','03',NULL);

INSERT INTO  comuni (CODICECOMUNE,COMUNE,SIGLAPROVINCIA,PROVINCIA,REGIONE,CAP,CF,CODICEISTAT,CODICEISTATREGIONE,CODICESTATOESTERO) VALUES ('M334','VAL BREMBILLA','BG','BERGAMO','LOMBARDIA','24012','M334','016253','03',NULL);

INSERT INTO  comuni (CODICECOMUNE,COMUNE,SIGLAPROVINCIA,PROVINCIA,REGIONE,CAP,CF,CODICEISTAT,CODICEISTATREGIONE,CODICESTATOESTERO) VALUES ('M335','BELLAGIO','CO','COMO','LOMBARDIA','22021','M335','013250','03',NULL);

INSERT INTO  comuni (CODICECOMUNE,COMUNE,SIGLAPROVINCIA,PROVINCIA,REGIONE,CAP,CF,CODICEISTAT,CODICEISTATREGIONE,CODICESTATOESTERO) VALUES ('M336','COLVERDE','CO','COMO','LOMBARDIA','22020','M336','013251','03',NULL);

INSERT INTO  comuni (CODICECOMUNE,COMUNE,SIGLAPROVINCIA,PROVINCIA,REGIONE,CAP,CF,CODICEISTAT,CODICEISTATREGIONE,CODICESTATOESTERO) VALUES ('M341','TREMEZZINA','CO','COMO','LOMBARDIA','22016','M341','013252','03',NULL);

INSERT INTO  comuni (CODICECOMUNE,COMUNE,SIGLAPROVINCIA,PROVINCIA,REGIONE,CAP,CF,CODICEISTAT,CODICEISTATREGIONE,CODICESTATOESTERO) VALUES ('M337','VERDERIO','LC','LECCO','LOMBARDIA','23878','M337','097091','03',NULL);

INSERT INTO  comuni (CODICECOMUNE,COMUNE,SIGLAPROVINCIA,PROVINCIA,REGIONE,CAP,CF,CODICEISTAT,CODICEISTATREGIONE,CODICESTATOESTERO) VALUES ('M340','BORGO VIRGILIO','MN','MANTOVA','LOMBARDIA','46030','M340','020071','03',NULL);

INSERT INTO  comuni (CODICECOMUNE,COMUNE,SIGLAPROVINCIA,PROVINCIA,REGIONE,CAP,CF,CODICEISTAT,CODICEISTATREGIONE,CODICESTATOESTERO) VALUES ('M338','CORNALE E BASTIDA','PV','PAVIA','LOMBARDIA','27050','M338','018191','03',NULL);


INSERT INTO  comuni (CODICECOMUNE,COMUNE,SIGLAPROVINCIA,PROVINCIA,REGIONE,CAP,CF,CODICEISTAT,CODICEISTATREGIONE,CODICESTATOESTERO) VALUES ('M339','MACCAGNO CON PINO E VEDDASCA','VA','VARESE','LOMBARDIA','21010','M339','012142','03',NULL);

INSERT INTO  comuni (CODICECOMUNE,COMUNE,SIGLAPROVINCIA,PROVINCIA,REGIONE,CAP,CF,CODICEISTAT,CODICEISTATREGIONE,CODICESTATOESTERO) VALUES ('M318','TRECASTELLI','AN','ANCONA','MARCHE','60012','M318','042050','11',NULL);


INSERT INTO  comuni (CODICECOMUNE,COMUNE,SIGLAPROVINCIA,PROVINCIA,REGIONE,CAP,CF,CODICEISTAT,CODICEISTATREGIONE,CODICESTATOESTERO) VALUES ('M331','VALLEFOGLIA','PU','PESARO E URBINO','MARCHE','61022','M331','041068','11',NULL);


INSERT INTO  comuni (CODICECOMUNE,COMUNE,SIGLAPROVINCIA,PROVINCIA,REGIONE,CAP,CF,CODICEISTAT,CODICEISTATREGIONE,CODICESTATOESTERO) VALUES ('M322','CASTELFRANCO PIANDISCO''','AR','AREZZO','TOSCANA','52020','M322','051040','09',NULL);

INSERT INTO  comuni (CODICECOMUNE,COMUNE,SIGLAPROVINCIA,PROVINCIA,REGIONE,CAP,CF,CODICEISTAT,CODICEISTATREGIONE,CODICESTATOESTERO) VALUES ('M329','PRATOVECCHIO STIA','AR','AREZZO','TOSCANA','52017','M329','051041','09',NULL);

INSERT INTO  comuni (CODICECOMUNE,COMUNE,SIGLAPROVINCIA,PROVINCIA,REGIONE,CAP,CF,CODICEISTAT,CODICEISTATREGIONE,CODICESTATOESTERO) VALUES ('M321','FIGLINE E INCISA VALDARNO','FI','FIRENZE','TOSCANA','50064','M321','048052','09',NULL);

INSERT INTO  comuni (CODICECOMUNE,COMUNE,SIGLAPROVINCIA,PROVINCIA,REGIONE,CAP,CF,CODICEISTAT,CODICEISTATREGIONE,CODICESTATOESTERO) VALUES ('M319','FABBRICHE DI VERGEMOLI','LU','LUCCA','TOSCANA','55020','M319','046036','09',NULL);

INSERT INTO  comuni (CODICECOMUNE,COMUNE,SIGLAPROVINCIA,PROVINCIA,REGIONE,CAP,CF,CODICEISTAT,CODICEISTATREGIONE,CODICESTATOESTERO) VALUES ('M327','CASCIANA TERME LARI','PT','PISTOIA','TOSCANA','56035','M327','050040','09',NULL);


INSERT INTO  comuni (CODICECOMUNE,COMUNE,SIGLAPROVINCIA,PROVINCIA,REGIONE,CAP,CF,CODICEISTAT,CODICEISTATREGIONE,CODICESTATOESTERO) VALUES ('M328','CRESPINA LORENZANA','PI','PISA','TOSCANA','56040','M328','050041','09',NULL);

INSERT INTO  comuni (CODICECOMUNE,COMUNE,SIGLAPROVINCIA,PROVINCIA,REGIONE,CAP,CF,CODICEISTAT,CODICEISTATREGIONE,CODICESTATOESTERO) VALUES ('M330','MONTORO','AV','AVELLINO','CAMPANIA','83025','M330','064121','15',NULL);

INSERT INTO  comuni (CODICECOMUNE,COMUNE,SIGLAPROVINCIA,PROVINCIA,REGIONE,CAP,CF,CODICEISTAT,CODICEISTATREGIONE,CODICESTATOESTERO) VALUES ('M332','QUERO VAS','BL','BELLUNO','VENETO','32030','M332','025070','05',NULL);

DELETE FROM MASTERKEY;
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('NATURAENDO','BINARIODIPENDENZE');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('TIPIMOV_STC_MAPPING','ID');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('MAPPATURE','ID');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('TIPIMOV_STC_ALBEROPROC','ID');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('TIPIMOV_STC_ALTRIDATI','ID');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('TIPIMOV_STC_MODELLI','ID');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('ALBEROPROC_ONERI','AO_ID');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('TIPICAUSALIONERI','CO_ID');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('TIPIENDO','CODICE');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('TIPIFAMIGLIEENDO','CODICE');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('AMMINISTRAZIONI','CODICEAMMINISTRAZIONE');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('INVENTARIOPROCEDIMENTI','CODICEINVENTARIO');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('LETTERETIPO','CODICELETTERA');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('NATURAENDO','CODICENATURA');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('NORMATIVE','CODICENORMATIVA');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('TIPIPROCEDURE','CODICEPROCEDURA');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('TEMPIFICAZIONI','CODICETEMPIFICAZIONE');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('TIPICONTROMOVIMENTO','CONTATORE');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('ALBEROPROC_DOCUMENTICAT','ID');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('INVENTARIOPROCEDIMENTIINCOMP','ID');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('INVENTARIOPROC_LEGGI','ID');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('INVENTARIOPROCEDIMENTIPEOPLE','ID');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('ALLEGATI','ID');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('TESTIESTESI','ID');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('DOCUMENTI','ID');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('INVENTARIOPROCEDIMENTIONERI','ID');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('DYN2_CAMPI','ID');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('DYN2_MODELLID','ID');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('DYN2_MODELLIDTESTI','ID');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('DYN2_MODELLIT','ID');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('INVENTARIOPROC_TIPITITOLO','ID');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('ALBEROPROCPEOPLEOPER','ID');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('ALBEROPROCPEOPLEHREF','ID');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('ALBEROPROC_ARENDO','ID');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('LEGGI','LE_ID');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('LEGGITIPI','LT_ID');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('TIPIMODALITAPAGAMENTO','MP_ID');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('RAGGRUPPAMENTOCAUSALIONERI','RCO_ID');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('ALBEROPROC','SC_ID');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('ALBEROPROC_LEGGI','SL_ID');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('ALBEROPROC_DOCUMENTI','SM_ID');
