CREATE TABLE SDEPROXY (
	IDENTE VARCHAR(15) NOT NULL,
	ALIAS_ENTE    VARCHAR(20),
	DESCRIZIONE VARCHAR(255),
	CODICECATASTALECOMUNE VARCHAR(5),
	WS_STRADARIO VARCHAR(255),
	WS_ANAGRAFE_RESIDENTI VARCHAR(255),
	WS_STATOPRATICA VARCHAR(255),
	USERNAME_WS  VARCHAR(15),
	PASSWORD_WS  VARCHAR(15)
) ENGINE=INNODB DEFAULT CHARSET=utf8;
ALTER TABLE SDEPROXY ADD CONSTRAINT PK_SDEPROXY PRIMARY KEY (IDENTE);
ALTER TABLE SDEPROXY ADD CONSTRAINT FK_SDEPROXY_COMUNI FOREIGN KEY (CODICECATASTALECOMUNE) REFERENCES COMUNI (
CODICECOMUNE
) ;
CREATE TABLE SDECOMUNIASSOCIATI(
IDENTE VARCHAR(6) NOT NULL,
CODICECATASTALECOMUNE VARCHAR(5) NOT NULL
)ENGINE=INNODB DEFAULT CHARSET=utf8;

ALTER TABLE SDECOMUNIASSOCIATI ADD CONSTRAINT PK_SDECOMUNIASSOCIATI PRIMARY KEY (IDENTE, CODICECATASTALECOMUNE);
ALTER TABLE SDECOMUNIASSOCIATI ADD CONSTRAINT FK_SDECOMUNIASSOCIATI_PROXY FOREIGN KEY (IDENTE) REFERENCES SDEPROXY (IDENTE);
ALTER TABLE SDECOMUNIASSOCIATI ADD CONSTRAINT FK_SDECOMUNIASSOCIATI_COMUNI FOREIGN KEY (CODICECATASTALECOMUNE) REFERENCES COMUNI (CODICECOMUNE);

ALTER TABLE FO_DOMANDE ADD idente VARCHAR(15);

ALTER TABLE STP_ENDO_TIPO2 ADD FLAG_REGIONALE NUMERIC(1,0) DEFAULT 0; 

ALTER TABLE STP_ENDO_TIPO1 ADD FLAG_REGIONALE NUMERIC(1,0) DEFAULT 0; 

ALTER TABLE ALBEROPROC_ENDO ADD FLAG_REGIONALE NUMERIC(1,0) DEFAULT 0; 


CREATE TABLE PRODOTTO(
  CODICE VARCHAR(20) NOT NULL,
  PRODOTTO VARCHAR(100)
)ENGINE=INNODB DEFAULT CHARSET=utf8;

ALTER TABLE PRODOTTO ADD CONSTRAINT PK_PRODOTTO PRIMARY KEY(CODICE);
ALTER TABLE PRODOTTO ADD IDENTIFICATIVO_MITTENTE VARCHAR(10);
ALTER TABLE PRODOTTO ADD FLAG_MOD_MITTENTE NUMERIC(1,0);