INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO ,DESCRIZIONE ) VALUES ('SIT_NAUTILUS' ,'URLCARTSTRADARIO' ,'E'' l''url da utilizzare per richiamare l''applicativo cartografico a partire da codice viario e civico'  );

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO ,DESCRIZIONE ) VALUES ('SIT_NAUTILUS' ,'URLCARTMAPPALE' ,'E'' l''url da utilizzare per richiamare l''applicativo cartografico a partire da sezione, foglio e particella'  );

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO ,DESCRIZIONE ) VALUES ('SIT_NAUTILUS' ,'URLRUESTRADARIO' ,'E'' l''url da utilizzare per richiamare l''applicativo RUE a partire da codice viario e civico'  );

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO ,DESCRIZIONE ) VALUES ('SIT_NAUTILUS' ,'URLRUEMAPPALE' ,'E'' l''url da utilizzare per richiamare l''applicativo RUE a partire da sezione,foglio e particella'  );

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO ,DESCRIZIONE ) VALUES ('SIT_NAUTILUS' ,'URLPOCMAPPALE' ,'E'' l''url da utilizzare per richiamare l''applicativo POC a partire da sezione,foglio e particella'  );

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO ,DESCRIZIONE ) VALUES ('SIT_NAUTILUS' ,'URLPOCSTRADARIO' ,'E'' l''url da utilizzare per richiamare l''applicativo POC a partire da codice viario e civico'  );

UPDATE CLMENU_JAVA SET DESCRIZIONE = 'Domande da Frontend con errori', PAGINA = 'domandestc/list.htm?software=SOFTWARE', JSP = 'JAVA' WHERE id=974;