//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2009.09.10 at 03:15:17 PM CEST
//
package it.gruppoinit.regulus.schema.billpaymentnotify.request;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;

/**
 * <p>
 * Java class for TipoSistemaPagamento.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="TipoSistemaPagamento">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="BPASS"/>
 *     &lt;enumeration value="BPASW"/>
 *     &lt;enumeration value="BPPR"/>
 *     &lt;enumeration value="STFI"/>
 *     &lt;enumeration value="RID"/>
 *     &lt;enumeration value="POSTA"/>
 *     &lt;enumeration value="POST1"/>
 *     &lt;enumeration value="POST2"/>
 *     &lt;enumeration value="POST3"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum TipoSistemaPagamento {
    BPASS("BPASS"), BPASW("BPASW"), BPPR("BPPR"), STFI("STFI"), RID("RID"), POSTA("POSTA"), @XmlEnumValue("POST1")
    POST_1("POST1"), @XmlEnumValue("POST2")
    POST_2("POST2"), @XmlEnumValue("POST3")
    POST_3("POST3");

    private final String value;

    TipoSistemaPagamento(String v) {

	value = v;
    }

    public String value() {

	return value;
    }

    public static TipoSistemaPagamento fromValue(String v) {

	for (TipoSistemaPagamento c : TipoSistemaPagamento.values()) {
	    if (c.value.equals(v)) {
		return c;
	    }
	}
	throw new IllegalArgumentException(v);
    }
}
