CREATE INDEX IDX_PECINBOX_ISTANZE ON PEC_INBOX(IDCOMUNE,CODICEISTANZA);
CREATE INDEX IDX_PECINBOX_MOVIMENTI ON PEC_INBOX(IDCOMUNE,CODICEMOVIMENTO);
CREATE TABLE VISTA_ALBEROPROC AS SELECT * FROM VW_ALBEROPROC;
CREATE INDEX IDX_VISTA_ALBEROPROC_001 ON VISTA_ALBEROPROC (IDCOMUNE, SC_ID) ;
ALTER TABLE ALBEROPROC ADD DESCRIZIONE_COMPLETA VARCHAR2(4000);

UPDATE ALBEROPROC SET ALBEROPROC.DESCRIZIONE_COMPLETA = (SELECT VISTA_ALBEROPROC.sc_descrizione
                                  FROM VISTA_ALBEROPROC 
                                  WHERE ALBEROPROC.idcomune = VISTA_ALBEROPROC.idcomune and
                                  ALBEROPROC.sc_id = VISTA_ALBEROPROC.sc_id )
WHERE ALBEROPROC.descrizione_completa is null
AND EXISTS (SELECT 1
            FROM VISTA_ALBEROPROC 
            WHERE  ALBEROPROC.idcomune = VISTA_ALBEROPROC.idcomune and
                                  ALBEROPROC.sc_id = VISTA_ALBEROPROC.sc_id);

DROP TABLE vista_alberoproc;

create index IDX_DOCUMENTIDAFIRMARE_FK_001 on DOCUMENTI_DA_FIRMARE(IDCOMUNE,CODICEISTANZA);
create index IDX_DOCUMENTIDAFIRMARE_FK_002 on DOCUMENTI_DA_FIRMARE(IDCOMUNE,CODICEMOVALLEGATI);
create index IDX_DOCUMENTIDAFIRMARE_FK_003 on DOCUMENTI_DA_FIRMARE(IDCOMUNE,CODICERICHIEDENTE);
create index IDX_DOCUMENTIDAFIRMARE_FK_004 on DOCUMENTI_DA_FIRMARE(IDCOMUNE,CODICEFIRMATARIO);

ALTER TABLE NEWS ADD DATA_SCADENZA DATE;

UPDATE NEWS SET DATA_SCADENZA=TO_DATE('31/12/2999','dd/MM/yyyy');

ALTER TABLE ANAGRAFE MODIFY INAIL_MATRICOLA VARCHAR2(50);
ALTER TABLE ANAGRAFESTORICO MODIFY INAIL_MATRICOLA VARCHAR2(50);

ALTER TABLE ANAGRAFE MODIFY INPS_MATRICOLA VARCHAR2(50);
ALTER TABLE ANAGRAFESTORICO MODIFY INPS_MATRICOLA VARCHAR2(50);

ALTER TABLE ANAGRAFE MODIFY CASSAEDILE_MATRICOLA VARCHAR2(50);
ALTER TABLE ANAGRAFESTORICO MODIFY CASSAEDILE_MATRICOLA VARCHAR2(50);

CREATE TABLE NEWS_BACKV2_20180531 AS SELECT * FROM NEWS;
ALTER TABLE NEWS ADD NEWS_CLOB CLOB;
UPDATE NEWS SET NEWS_CLOB=NEWS;
ALTER TABLE NEWS DROP COLUMN NEWS;
ALTER TABLE NEWS ADD NEWS CLOB;
UPDATE NEWS SET NEWS=NEWS_CLOB;
ALTER TABLE NEWS DROP COLUMN NEWS_CLOB;

CREATE TABLE INFOSUAP_BACKV2_20180531 AS SELECT * FROM INFOSUAP;
ALTER TABLE INFOSUAP ADD DESCRIZIONE_CLOB CLOB;
UPDATE INFOSUAP SET DESCRIZIONE_CLOB=DESCRIZIONE;
ALTER TABLE INFOSUAP DROP COLUMN DESCRIZIONE;
ALTER TABLE INFOSUAP ADD DESCRIZIONE CLOB;
UPDATE INFOSUAP SET DESCRIZIONE=DESCRIZIONE_CLOB;
ALTER TABLE INFOSUAP DROP COLUMN DESCRIZIONE_CLOB;



DELETE FROM INTERESSI_LEGALI;

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (1,TO_DATE('21-04-1942','dd-MM-yyyy'),TO_DATE('15-12-1990','dd-MM-yyyy'),5,null);

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (2,TO_DATE('16-12-1990','dd-MM-yyyy'),TO_DATE('31-12-1996','dd-MM-yyyy'),10,'Legge 26 novembre 1990, n. 353'); 

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (3,TO_DATE('01-01-1997','dd-MM-yyyy'),TO_DATE('31-12-1998','dd-MM-yyyy'),5,'Legge 23 dicembre 1996, n. 662'); 

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (4,TO_DATE('01-01-1999','dd-MM-yyyy'),TO_DATE('31-12-2000','dd-MM-yyyy'),2.5,'D.M. 10 dicembre 1998');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (5,TO_DATE('01-01-2001','dd-MM-yyyy'),TO_DATE('31-12-2001','dd-MM-yyyy'),3.5,'D.M. 11 dicembre 2000');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (6,TO_DATE('01-01-2002','dd-MM-yyyy'),TO_DATE('31-12-2003','dd-MM-yyyy'),3,'D.M. 11 dicembre 2001');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (7,TO_DATE('01-01-2004','dd-MM-yyyy'),TO_DATE('31-12-2007','dd-MM-yyyy'),2.5,'D.M. 1 dicembre 2003');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (8,TO_DATE('01-01-2008','dd-MM-yyyy'),TO_DATE('31-12-2009','dd-MM-yyyy'),3,'D.M. 12 dicembre 2007');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (9,TO_DATE('01-01-2010','dd-MM-yyyy'),TO_DATE('31-12-2010','dd-MM-yyyy'),1,'D.M. 4 dicembre 2009');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (10,TO_DATE('01-01-2011','dd-MM-yyyy'),TO_DATE('31-12-2011','dd-MM-yyyy'),1.5,'D.M. 07 Dicembre 2010');

insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (11,TO_DATE('01-01-2012','dd-MM-yyyy'),TO_DATE('31-12-2013','dd-MM-yyyy'),2.5,'DM 12 dicembre 2011');
Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (12,to_date('01-01-2014','dd-MM-yyyy'),TO_DATE('31-12-2014','dd-MM-yyyy'),1,'Dm Economia 13.12.2013');
Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (13,to_date('01-01-2015','dd-MM-yyyy'),TO_DATE('31-12-2015','dd-MM-yyyy'),0.5,'Dm Economia 11.12.2014');
Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (14,to_date('01-01-2016','dd-MM-yyyy'),to_date('31-12-2016','dd-MM-yyyy'),0.2,'Dm Economia 11.12.2015');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (15,to_date('01-01-2017','dd-MM-yyyy'),to_date('31-12-2017','dd-MM-yyyy'),0.1,'Dm economia e finanze 07/12/2016,G.U.14/12/2016');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (16,to_date('01-01-2018','dd-MM-yyyy'),null,0.3,'Dm economia e finanze 13/12/2017,G.U.15/12/2017');

ALTER TABLE ISTANZE ADD OPERATORE_IN_CARICO NUMBER(8,0);
ALTER TABLE ISTANZE ADD CONSTRAINT FK_ISTANZE_OPPRESAINCAR FOREIGN KEY(IDCOMUNE,OPERATORE_IN_CARICO) REFERENCES RESPONSABILI(IDCOMUNE, CODICERESPONSABILE); 
CREATE INDEX IDX_ISTANZE_RESP004 ON ISTANZE (IDCOMUNE,OPERATORE_IN_CARICO);

CREATE TABLE RT_ANAGRAFETRIB_CO (CODICE_ENDO_REGIONALE VARCHAR2(20 CHAR) NOT NULL, CODICE_TIPOLOGIA_ENDO NUMBER(4,0) NOT NULL, ATRIB_TIPOLOGIAINTERVENTO VARCHAR2(5 CHAR) NOT NULL);
ALTER TABLE RT_ANAGRAFETRIB_CO ADD CONSTRAINT RT_ANAGRAFETRIBCO_PK PRIMARY KEY (CODICE_ENDO_REGIONALE,CODICE_TIPOLOGIA_ENDO);

