//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 

namespace Init.SIGePro.Protocollo.EGrammata2.Anagrafiche.Response
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class RisultatoRicercaAnagrafica
    {

        private Stato statoField;

        private Anagrafica[] anagraficaField;

        /// <remarks/>
        public Stato Stato
        {
            get
            {
                return this.statoField;
            }
            set
            {
                this.statoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Anagrafica")]
        public Anagrafica[] Anagrafica
        {
            get
            {
                return this.anagraficaField;
            }
            set
            {
                this.anagraficaField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Stato
    {

        private string codiceField;

        private string messaggioField;

        /// <remarks/>
        public string Codice
        {
            get
            {
                return this.codiceField;
            }
            set
            {
                this.codiceField = value;
            }
        }

        /// <remarks/>
        public string Messaggio
        {
            get
            {
                return this.messaggioField;
            }
            set
            {
                this.messaggioField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Anagrafica
    {

        private string nominativoField;

        private string itemField;

        private ItemChoiceType itemElementNameField;

        private string descrizioneResidenzaField;

        private string dataFineValiditaField;

        private string codiceField;

        private string matricolaField;

        private AnagraficaTipo tipoField;

        public Anagrafica()
        {
            this.matricolaField = "";
            this.tipoField = AnagraficaTipo.P;
        }

        /// <remarks/>
        public string Nominativo
        {
            get
            {
                return this.nominativoField;
            }
            set
            {
                this.nominativoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CodiceFiscale", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("PartitaIva", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName
        {
            get
            {
                return this.itemElementNameField;
            }
            set
            {
                this.itemElementNameField = value;
            }
        }

        /// <remarks/>
        public string DescrizioneResidenza
        {
            get
            {
                return this.descrizioneResidenzaField;
            }
            set
            {
                this.descrizioneResidenzaField = value;
            }
        }

        /// <remarks/>
        public string DataFineValidita
        {
            get
            {
                return this.dataFineValiditaField;
            }
            set
            {
                this.dataFineValiditaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "NMTOKEN")]
        public string codice
        {
            get
            {
                return this.codiceField;
            }
            set
            {
                this.codiceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string matricola
        {
            get
            {
                return this.matricolaField;
            }
            set
            {
                this.matricolaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AnagraficaTipo tipo
        {
            get
            {
                return this.tipoField;
            }
            set
            {
                this.tipoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "", IncludeInSchema = false)]
    public enum ItemChoiceType
    {

        /// <remarks/>
        CodiceFiscale,

        /// <remarks/>
        PartitaIva,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
    public enum AnagraficaTipo
    {

        /// <remarks/>
        P,

        /// <remarks/>
        D,
    }

}