//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Init.SIGePro.Protocollo.ProtocolloProtInfService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://servizi.protinf.ifm.it", ConfigurationName="ProtocolloProtInfService.ProtocolloWebService")]
    public interface ProtocolloWebService {
        
        // CODEGEN: Generating message contract since element name protocolloXML from namespace http://servizi.protinf.ifm.it is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Init.SIGePro.Protocollo.ProtocolloProtInfService.protocollaResponse protocolla(Init.SIGePro.Protocollo.ProtocolloProtInfService.protocollaRequest request);
        
        // CODEGEN: Generating message contract since element name ente from namespace http://servizi.protinf.ifm.it is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Init.SIGePro.Protocollo.ProtocolloProtInfService.elencoRuoliResponse elencoRuoli(Init.SIGePro.Protocollo.ProtocolloProtInfService.elencoRuoliRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class protocollaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="protocolla", Namespace="http://servizi.protinf.ifm.it", Order=0)]
        public Init.SIGePro.Protocollo.ProtocolloProtInfService.protocollaRequestBody Body;
        
        public protocollaRequest() {
        }
        
        public protocollaRequest(Init.SIGePro.Protocollo.ProtocolloProtInfService.protocollaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://servizi.protinf.ifm.it")]
    public partial class protocollaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string protocolloXML;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mittenteXML;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string destinatarioXML;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string assegnatarioXML;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string allegatiXML;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string dirftp;
        
        public protocollaRequestBody() {
        }
        
        public protocollaRequestBody(string protocolloXML, string mittenteXML, string destinatarioXML, string assegnatarioXML, string allegatiXML, string dirftp) {
            this.protocolloXML = protocolloXML;
            this.mittenteXML = mittenteXML;
            this.destinatarioXML = destinatarioXML;
            this.assegnatarioXML = assegnatarioXML;
            this.allegatiXML = allegatiXML;
            this.dirftp = dirftp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class protocollaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="protocollaResponse", Namespace="http://servizi.protinf.ifm.it", Order=0)]
        public Init.SIGePro.Protocollo.ProtocolloProtInfService.protocollaResponseBody Body;
        
        public protocollaResponse() {
        }
        
        public protocollaResponse(Init.SIGePro.Protocollo.ProtocolloProtInfService.protocollaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://servizi.protinf.ifm.it")]
    public partial class protocollaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string protocollaReturn;
        
        public protocollaResponseBody() {
        }
        
        public protocollaResponseBody(string protocollaReturn) {
            this.protocollaReturn = protocollaReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class elencoRuoliRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="elencoRuoli", Namespace="http://servizi.protinf.ifm.it", Order=0)]
        public Init.SIGePro.Protocollo.ProtocolloProtInfService.elencoRuoliRequestBody Body;
        
        public elencoRuoliRequest() {
        }
        
        public elencoRuoliRequest(Init.SIGePro.Protocollo.ProtocolloProtInfService.elencoRuoliRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://servizi.protinf.ifm.it")]
    public partial class elencoRuoliRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string utente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        public elencoRuoliRequestBody() {
        }
        
        public elencoRuoliRequestBody(string ente, string utente, string password) {
            this.ente = ente;
            this.utente = utente;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class elencoRuoliResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="elencoRuoliResponse", Namespace="http://servizi.protinf.ifm.it", Order=0)]
        public Init.SIGePro.Protocollo.ProtocolloProtInfService.elencoRuoliResponseBody Body;
        
        public elencoRuoliResponse() {
        }
        
        public elencoRuoliResponse(Init.SIGePro.Protocollo.ProtocolloProtInfService.elencoRuoliResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://servizi.protinf.ifm.it")]
    public partial class elencoRuoliResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string elencoRuoliReturn;
        
        public elencoRuoliResponseBody() {
        }
        
        public elencoRuoliResponseBody(string elencoRuoliReturn) {
            this.elencoRuoliReturn = elencoRuoliReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProtocolloWebServiceChannel : Init.SIGePro.Protocollo.ProtocolloProtInfService.ProtocolloWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProtocolloWebServiceClient : System.ServiceModel.ClientBase<Init.SIGePro.Protocollo.ProtocolloProtInfService.ProtocolloWebService>, Init.SIGePro.Protocollo.ProtocolloProtInfService.ProtocolloWebService {
        
        public ProtocolloWebServiceClient() {
        }
        
        public ProtocolloWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProtocolloWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProtocolloWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProtocolloWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Init.SIGePro.Protocollo.ProtocolloProtInfService.protocollaResponse Init.SIGePro.Protocollo.ProtocolloProtInfService.ProtocolloWebService.protocolla(Init.SIGePro.Protocollo.ProtocolloProtInfService.protocollaRequest request) {
            return base.Channel.protocolla(request);
        }
        
        public string protocolla(string protocolloXML, string mittenteXML, string destinatarioXML, string assegnatarioXML, string allegatiXML, string dirftp) {
            Init.SIGePro.Protocollo.ProtocolloProtInfService.protocollaRequest inValue = new Init.SIGePro.Protocollo.ProtocolloProtInfService.protocollaRequest();
            inValue.Body = new Init.SIGePro.Protocollo.ProtocolloProtInfService.protocollaRequestBody();
            inValue.Body.protocolloXML = protocolloXML;
            inValue.Body.mittenteXML = mittenteXML;
            inValue.Body.destinatarioXML = destinatarioXML;
            inValue.Body.assegnatarioXML = assegnatarioXML;
            inValue.Body.allegatiXML = allegatiXML;
            inValue.Body.dirftp = dirftp;
            Init.SIGePro.Protocollo.ProtocolloProtInfService.protocollaResponse retVal = ((Init.SIGePro.Protocollo.ProtocolloProtInfService.ProtocolloWebService)(this)).protocolla(inValue);
            return retVal.Body.protocollaReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Init.SIGePro.Protocollo.ProtocolloProtInfService.elencoRuoliResponse Init.SIGePro.Protocollo.ProtocolloProtInfService.ProtocolloWebService.elencoRuoli(Init.SIGePro.Protocollo.ProtocolloProtInfService.elencoRuoliRequest request) {
            return base.Channel.elencoRuoli(request);
        }
        
        public string elencoRuoli(string ente, string utente, string password) {
            Init.SIGePro.Protocollo.ProtocolloProtInfService.elencoRuoliRequest inValue = new Init.SIGePro.Protocollo.ProtocolloProtInfService.elencoRuoliRequest();
            inValue.Body = new Init.SIGePro.Protocollo.ProtocolloProtInfService.elencoRuoliRequestBody();
            inValue.Body.ente = ente;
            inValue.Body.utente = utente;
            inValue.Body.password = password;
            Init.SIGePro.Protocollo.ProtocolloProtInfService.elencoRuoliResponse retVal = ((Init.SIGePro.Protocollo.ProtocolloProtInfService.ProtocolloWebService)(this)).elencoRuoli(inValue);
            return retVal.Body.elencoRuoliReturn;
        }
    }
}
