ALTER TABLE BOLL_GEST_DETT_AUTORIZZ ADD FK_BOLLGEST_ID DECIMAL(4,0);
ALTER TABLE BOLL_GEST_DETT_RATE ADD FK_BOLLGEST_ID DECIMAL(4,0);
ALTER TABLE BOLL_GEST_ISTANZEONERI ADD FK_BOLLGEST_ID DECIMAL(4,0);
ALTER TABLE BOLL_GEST_MERCATI_DETT ADD FK_BOLLGEST_ID DECIMAL(4,0);
ALTER TABLE BOLL_GEST_ONERI_SEQUENCE ADD FK_BOLLGEST_ID DECIMAL(4,0);

ALTER TABLE BOLL_GEST_DETT_AUTORIZZ ADD CONSTRAINT FK_DETAUT_BLLGSTTEST FOREIGN KEY (IDCOMUNE, FK_BOLLGEST_ID) REFERENCES BOLL_GEST_TESTATA(IDCOMUNE, ID);
ALTER TABLE BOLL_GEST_DETT_RATE ADD CONSTRAINT FK_DETRAT_BLLGSTTEST FOREIGN KEY (IDCOMUNE, FK_BOLLGEST_ID) REFERENCES BOLL_GEST_TESTATA(IDCOMUNE, ID);
ALTER TABLE BOLL_GEST_ISTANZEONERI ADD CONSTRAINT FK_ISTONE_BLLGSTTEST FOREIGN KEY (IDCOMUNE, FK_BOLLGEST_ID) REFERENCES BOLL_GEST_TESTATA(IDCOMUNE, ID);
ALTER TABLE BOLL_GEST_MERCATI_DETT ADD CONSTRAINT FK_MERDET_BLLGSTTEST FOREIGN KEY (IDCOMUNE, FK_BOLLGEST_ID) REFERENCES BOLL_GEST_TESTATA(IDCOMUNE, ID);
ALTER TABLE BOLL_GEST_ONERI_SEQUENCE ADD CONSTRAINT FK_ONESEQ_BLLGSTTEST FOREIGN KEY (IDCOMUNE, FK_BOLLGEST_ID) REFERENCES BOLL_GEST_TESTATA(IDCOMUNE, ID);

CREATE INDEX IDX_DETAUT_BLLGSTTEST_001 ON BOLL_GEST_DETT_AUTORIZZ(IDCOMUNE,FK_BOLLGEST_ID);
CREATE INDEX IDX_DETRAT_BLLGSTTEST_001 ON BOLL_GEST_DETT_RATE(IDCOMUNE,FK_BOLLGEST_ID);
CREATE INDEX IDX_ISTONE_BLLGSTTEST_001 ON BOLL_GEST_ISTANZEONERI(IDCOMUNE,FK_BOLLGEST_ID);
CREATE INDEX IDX_MERDET_BLLGSTTEST_001 ON BOLL_GEST_MERCATI_DETT(IDCOMUNE,FK_BOLLGEST_ID);
CREATE INDEX IDX_ONESEQ_BLLGSTTEST_001 ON BOLL_GEST_ONERI_SEQUENCE(IDCOMUNE,FK_BOLLGEST_ID);

UPDATE BOLL_GEST_DETT_AUTORIZZ INNER JOIN BOLL_GEST_DETTAGLIO ON BOLL_GEST_DETT_AUTORIZZ.IDCOMUNE = BOLL_GEST_DETTAGLIO.IDCOMUNE AND BOLL_GEST_DETT_AUTORIZZ.FK_BOLLGESTDET_ID = BOLL_GEST_DETTAGLIO.ID SET BOLL_GEST_DETT_AUTORIZZ.FK_BOLLGEST_ID = BOLL_GEST_DETTAGLIO.FK_BOLLGEST_ID WHERE BOLL_GEST_DETT_AUTORIZZ.FK_BOLLGEST_ID IS NULL;
UPDATE BOLL_GEST_DETT_RATE INNER JOIN BOLL_GEST_DETTAGLIO ON BOLL_GEST_DETT_RATE.IDCOMUNE = BOLL_GEST_DETTAGLIO.IDCOMUNE AND BOLL_GEST_DETT_RATE.FK_BOLLGESTDET_ID = BOLL_GEST_DETTAGLIO.ID SET BOLL_GEST_DETT_RATE.FK_BOLLGEST_ID = BOLL_GEST_DETTAGLIO.FK_BOLLGEST_ID WHERE BOLL_GEST_DETT_RATE.FK_BOLLGEST_ID IS NULL;
UPDATE BOLL_GEST_ISTANZEONERI INNER JOIN BOLL_GEST_DETTAGLIO ON BOLL_GEST_ISTANZEONERI.IDCOMUNE = BOLL_GEST_DETTAGLIO.IDCOMUNE AND BOLL_GEST_ISTANZEONERI.FK_BOLLGESTDET_ID = BOLL_GEST_DETTAGLIO.ID SET BOLL_GEST_ISTANZEONERI.FK_BOLLGEST_ID = BOLL_GEST_DETTAGLIO.FK_BOLLGEST_ID WHERE BOLL_GEST_ISTANZEONERI.FK_BOLLGEST_ID IS NULL;
UPDATE BOLL_GEST_MERCATI_DETT INNER JOIN BOLL_GEST_DETT_AUTORIZZ ON BOLL_GEST_MERCATI_DETT.IDCOMUNE = BOLL_GEST_DETT_AUTORIZZ.IDCOMUNE AND BOLL_GEST_MERCATI_DETT.FK_ID_GEST_AUTORIZZAZIONI = BOLL_GEST_DETT_AUTORIZZ.ID INNER JOIN BOLL_GEST_DETTAGLIO ON BOLL_GEST_DETT_AUTORIZZ.IDCOMUNE = BOLL_GEST_DETTAGLIO.IDCOMUNE AND BOLL_GEST_DETT_AUTORIZZ.FK_BOLLGESTDET_ID = BOLL_GEST_DETTAGLIO.ID SET BOLL_GEST_MERCATI_DETT.FK_BOLLGEST_ID = BOLL_GEST_DETTAGLIO.FK_BOLLGEST_ID WHERE BOLL_GEST_MERCATI_DETT.FK_BOLLGEST_ID IS NULL;
UPDATE BOLL_GEST_ONERI_SEQUENCE INNER JOIN BOLL_GEST_DETTAGLIO ON BOLL_GEST_ONERI_SEQUENCE.IDCOMUNE = BOLL_GEST_DETTAGLIO.IDCOMUNE AND BOLL_GEST_ONERI_SEQUENCE.ID_BOLLEGEST_DETT = BOLL_GEST_DETTAGLIO.ID  SET BOLL_GEST_ONERI_SEQUENCE.FK_BOLLGEST_ID = BOLL_GEST_DETTAGLIO.FK_BOLLGEST_ID WHERE BOLL_GEST_ONERI_SEQUENCE.FK_BOLLGEST_ID IS NULL;

ALTER TABLE BOLL_GEST_DETT_AUTORIZZ MODIFY FK_BOLLGEST_ID DECIMAL(4,0) NOT NULL;
ALTER TABLE BOLL_GEST_DETT_RATE MODIFY FK_BOLLGEST_ID DECIMAL(4,0) NOT NULL;
ALTER TABLE BOLL_GEST_ISTANZEONERI MODIFY FK_BOLLGEST_ID DECIMAL(4,0) NOT NULL;
ALTER TABLE BOLL_GEST_MERCATI_DETT MODIFY FK_BOLLGEST_ID DECIMAL(4,0) NOT NULL;
ALTER TABLE BOLL_GEST_ONERI_SEQUENCE MODIFY FK_BOLLGEST_ID DECIMAL(4,0) NOT NULL;