//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sigepro.net.Utilita.SchedeDinamiche
{


    public partial class Index
    {

        /// <summary>
        /// txtEsportaAlias control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Utils.Web.UI.LabeledTextBox txtEsportaAlias;

        /// <summary>
        /// txtEsportaIdScheda control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Utils.Web.UI.LabeledIntTextBox txtEsportaIdScheda;

        /// <summary>
        /// btnVaiAEsporta control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnVaiAEsporta;

        /// <summary>
        /// txtEsportaIstanzaAlias control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Utils.Web.UI.LabeledTextBox txtEsportaIstanzaAlias;

        /// <summary>
        /// txtEsportaCodiceIstanza control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Utils.Web.UI.LabeledIntTextBox txtEsportaCodiceIstanza;

        /// <summary>
        /// btnEsportaIstanza control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnEsportaIstanza;

        /// <summary>
        /// txtImportAlias control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Utils.Web.UI.LabeledTextBox txtImportAlias;

        /// <summary>
        /// txtImportSoftware control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Utils.Web.UI.LabeledTextBox txtImportSoftware;

        /// <summary>
        /// btnVaiAImporta control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnVaiAImporta;

        /// <summary>
        /// txtEliminaAlias control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Utils.Web.UI.LabeledTextBox txtEliminaAlias;

        /// <summary>
        /// txtEliminaIdScheda control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Utils.Web.UI.LabeledIntTextBox txtEliminaIdScheda;

        /// <summary>
        /// btnVaiAElimina control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnVaiAElimina;

        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new SigeproNetMaster Master
        {
            get
            {
                return ((SigeproNetMaster)(base.Master));
            }
        }
    }
}
