package it.gruppoinit.pal.gp.core.service.helper;

public enum NodoNLAEnum {
    NLA_IDNODO, NLA_IDNODO_AREARISERVATA, NLA_IDNODO_CART_COMINTERNE, NLA_IDNODO_AR_CONSOLE, //
    NLA_IDNODO_PEOPLE, NLA_IDNODO_PROTOCOLLOSIGEPRO, NLA_IDNODO_AIDA, NLA_IDNODO_PEC_MUTA, //
    NLA_IDNODO_SIEDER, NLA_IDNODO_SCONOSCIUTO, NLA_IDNODO_RFC239, //
    NLA_IDNODO_ENTE_NON_LOCALE
}
