alter table ISTANZEPROCURE add CONTROLLOOK NUMERIC(1, 0);

alter table ISTANZEPROCURE add NECESSARIO NUMERIC(1, 0);
alter table ISTANZEPROCURE add PRESENTE NUMERIC(1, 0);
alter table ISTANZEPROCURE add NOTE VARCHAR(1200);

CREATE TABLE LDP_DECODIFICHE (
  Idcomune VARCHAR(6), 
  Software VARCHAR(2), 
  Id NUMERIC(10,0), 
  Contesto VARCHAR(16), 
  Codice VARCHAR(32), 
  Descrizione VARCHAR(64)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



CREATE UNIQUE INDEX IDX_LDP_DECODIFICHE_001
  ON LDP_DECODIFICHE (
    idcomune,
    software,
    Contesto,
    Codice
  );

ALTER TABLE LDP_DECODIFICHE
  ADD CONSTRAINT LDP_DECODIFICHE_PK PRIMARY KEY (
    idcomune,
    id
  );

ALTER TABLE alberoproc ADD LDP_TIP_OCCUPAZIONE numeric(10,0);
ALTER TABLE alberoproc ADD LDP_TIP_PERIODO numeric (10,0);
ALTER TABLE alberoproc ADD LDP_TIP_GEOMETRIA numeric (10,0);

ALTER TABLE alberoproc
  ADD CONSTRAINT fk_alberoproc_ldp_decod1 FOREIGN KEY (
    idcomune,
    LDP_TIP_OCCUPAZIONE
  ) REFERENCES LDP_DECODIFICHE (
    idcomune,
    id
  );
  
ALTER TABLE alberoproc
  ADD CONSTRAINT fk_alberoproc_ldp_decod2 FOREIGN KEY (
    idcomune,
    LDP_TIP_PERIODO
  ) REFERENCES LDP_DECODIFICHE (
    idcomune,
    id
  );  

ALTER TABLE alberoproc
  ADD CONSTRAINT fk_alberoproc_ldp_decod3 FOREIGN KEY (
    idcomune,
    LDP_TIP_GEOMETRIA
  ) REFERENCES LDP_DECODIFICHE (
    idcomune,
    id
  );

  
 ALTER TABLE PROTOCOLLO_UFFICIREGISTRI DROP PRIMARY KEY;

ALTER TABLE PROTOCOLLO_UFFICIREGISTRI ADD CONSTRAINT PROTOCOLLO_UFFICIREGISTRI_PK PRIMARY KEY (IDCOMUNE, CODICEREGISTRO);

ALTER TABLE NEWS ADD FLAG_IN_PRIMO_PIANO NUMERIC(1,0);

ALTER TABLE GRUPPI_ISTRUTTORI MODIFY ID NUMERIC(10,0);

ALTER TABLE GRUPPI_ISTRUTTORI_RESP MODIFY FK_GRP_ISTRUTTORI NUMERIC(10,0);
