 drop index IDX_ISTANZE_002  ;
    
CREATE UNIQUE INDEX IDX_ISTANZE_002 ON ISTANZE (IDCOMUNE,SOFTWARE,LOWER(NUMEROISTANZA));    
ALTER TABLE ISTANZEDYN2DATI MODIFY INDICE NUMBER(4,0);
ALTER TABLE ISTANZEDYN2DATI MODIFY INDICE_MOLTEPLICITA NUMBER(4,0);
ALTER TABLE I_ATTIVITADYN2DATI MODIFY INDICE NUMBER(4,0);
ALTER TABLE I_ATTIVITADYN2DATI MODIFY INDICE_MOLTEPLICITA NUMBER(4,0);
ALTER TABLE I_ATTIVITADYN2DATI_SNAPSHOT MODIFY INDICE NUMBER(4,0);
ALTER TABLE I_ATTIVITADYN2DATI_SNAPSHOT MODIFY INDICE_MOLTEPLICITA NUMBER(4,0);

ALTER TABLE ISTANZE ADD NATURA VARCHAR2(20);
ALTER TABLE NATURAENDO ADD NATURABASE VARCHAR2(20);
CREATE TABLE NATURE_PROCEDURE
(
IDCOMUNE VARCHAR2(6) NOT NULL,
ID NUMBER(4,0),
SOFTWARE VARCHAR2(2) NOT NULL,
CODICEPROCEDURA NUMBER(10,0) NOT NULL,
CODICENATURABASE VARCHAR2(20) NOT NULL
);

ALTER TABLE NATURE_PROCEDURE ADD CONSTRAINT PK_NATURE_PROCEDURE PRIMARY KEY(IDCOMUNE,ID);
ALTER TABLE NATURE_PROCEDURE ADD CONSTRAINT FK_NATUREPROCEDURE_SOFTWARE FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);
ALTER TABLE NATURE_PROCEDURE ADD CONSTRAINT FK_NATUREPROCEDURE_PROCEDURE FOREIGN KEY(IDCOMUNE, CODICEPROCEDURA) REFERENCES TIPIPROCEDURE(IDCOMUNE, CODICEPROCEDURA);

CREATE INDEX IDX_OGGETTI_METADATI_003 ON OGGETTI_METADATI (IDCOMUNE ASC, CODICEOGGETTO ASC);

ALTER TABLE ALBEROPROC ADD CONSTRAINT FK_SOFTWARE_79 FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);
ALTER TABLE ALBEROPROC_DOCUMENTICAT ADD CONSTRAINT FK_SOFTWARE_80 FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);
ALTER TABLE ALBEROPROC_LIMITI ADD CONSTRAINT FK_SOFTWARE_81 FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);
ALTER TABLE ATTIVITA ADD CONSTRAINT FK_SOFTWARE_86 FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);
ALTER TABLE BATCH_SCADENZARIO ADD CONSTRAINT FK_SOFTWARE_142 FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);
ALTER TABLE BATCH_SCAD_ISTANZE ADD CONSTRAINT FK_SOFTWARE_143 FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);
ALTER TABLE CANONI_CONFIGURAZIONE ADD CONSTRAINT FK_SOFTWARE_146 FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);
ALTER TABLE CANONI_RIDUZIONIOMI ADD CONSTRAINT FK_SOFTWARE_147 FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);
ALTER TABLE CANONI_TIPISUPERFICI ADD CONSTRAINT FK_SOFTWARE_148 FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);
ALTER TABLE CATEGORIAAFFISSIONI ADD CONSTRAINT FK_SOFTWARE_149 FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);
ALTER TABLE CLMENU_V1 ADD CONSTRAINT FK_SOFTWARE_93 FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);
ALTER TABLE COMUNIASSOCIATISOFTWARE ADD CONSTRAINT FK_SOFTWARE_95 FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);
ALTER TABLE CONFIGURAZIONE ADD CONSTRAINT FK_SOFTWARE_87 FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);
ALTER TABLE DEHORS_CFG ADD CONSTRAINT FK_SOFTWARE_169 FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);
ALTER TABLE DOCUMENTI_CONTABILITA ADD CONSTRAINT FK_SOFTWARE_156 FOREIGN KEY(CODICESOFTWARE) REFERENCES SOFTWARE(CODICE);
ALTER TABLE DOM_DOMANDE ADD CONSTRAINT FK_SOFTWARE_107 FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);
ALTER TABLE DYN2_REGOLE ADD CONSTRAINT FK_SOFTWARE_151 FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);
ALTER TABLE FO_ARCONFIGURAZIONE ADD CONSTRAINT FK_SOFTWARE_114 FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);
ALTER TABLE FO_CONFIGURAZIONE ADD CONSTRAINT FK_SOFTWARE_115 FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);
ALTER TABLE GRADUATORIECRITERI ADD CONSTRAINT FK_SOFTWARE_118 FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);
ALTER TABLE HELP ADD CONSTRAINT FK_SOFTWARE_119 FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);
ALTER TABLE HELPBASE ADD CONSTRAINT FK_SOFTWARE_120 FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);
ALTER TABLE INSEDIAMENTI ADD CONSTRAINT FK_SOFTWARE_8 FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);
ALTER TABLE INVENTARIOPROCEDIMENTI ADD CONSTRAINT FK_SOFTWARE_78 FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);
ALTER TABLE INVENTARIOPROCEDIMENTIONERI ADD CONSTRAINT FK_SOFTWARE_10 FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);
ALTER TABLE INVENTARIOPROCEDIMENTISOFTWARE ADD CONSTRAINT FK_SOFTWARE_11 FOREIGN KEY(MODULOSOFTWARE) REFERENCES SOFTWARE(CODICE);
ALTER TABLE ISTANZEDELETE ADD CONSTRAINT FK_SOFTWARE_167 FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);
ALTER TABLE ISTANZEDOSSIER ADD CONSTRAINT FK_SOFTWARE_168 FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);
ALTER TABLE ISTANZEPEOPLET ADD CONSTRAINT FK_SOFTWARE_4 FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);
ALTER TABLE JOB_REPOSITORY ADD CONSTRAINT FK_SOFTWARE_162 FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);
ALTER TABLE LAYOUTPAGINE ADD CONSTRAINT FK_SOFTWARE_58 FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);
ALTER TABLE LAYOUTTESTI ADD CONSTRAINT FK_SOFTWARE_59 FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);
ALTER TABLE LAYOUTTESTIBASE ADD CONSTRAINT FK_SOFTWARE_60 FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);
ALTER TABLE LDP_DECODIFICHE ADD CONSTRAINT FK_SOFTWARE_174 FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);
ALTER TABLE LETTERETIPO ADD CONSTRAINT FK_SOFTWARE_61 FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);
ALTER TABLE MAIL_CONFIG ADD CONSTRAINT FK_SOFTWARE_62 FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);
ALTER TABLE MAIL_CONFIGSW ADD CONSTRAINT FK_SOFTWARE_63 FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);
ALTER TABLE MAPPATUREPEOPLER ADD CONSTRAINT FK_SOFTWARE_65 FOREIGN KEY(CODICESOFTWARE) REFERENCES SOFTWARE(CODICE);
ALTER TABLE MAPPATUREPEOPLET ADD CONSTRAINT FK_SOFTWARE_66 FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);
ALTER TABLE MERCATI ADD CONSTRAINT FK_SOFTWARE_67 FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);
ALTER TABLE MERCATI_IDENTAUT ADD CONSTRAINT FK_SOFTWARE_122 FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);
ALTER TABLE MERCATIPRESENZE_T ADD CONSTRAINT FK_SOFTWARE_123 FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);
ALTER TABLE NATURAAFFISSIONI ADD CONSTRAINT FK_SOFTWARE_43 FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);
ALTER TABLE ONERIDOSSIER ADD CONSTRAINT FK_SOFTWARE_157 FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);
ALTER TABLE ONERITIPIRATEIZZAZIONE ADD CONSTRAINT FK_SOFTWARE_53 FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);
ALTER TABLE ORARIAPERTURA ADD CONSTRAINT FK_SOFTWARE_98 FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);
ALTER TABLE PROTOCOLLO_CONFIGURAZIONE ADD CONSTRAINT FK_SOFTWARE_104 FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);
ALTER TABLE RESOURCES_EXT ADD CONSTRAINT FK_SOFTWARE_27 FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);
ALTER TABLE RESPONSABILI ADD CONSTRAINT FK_SOFTWARE_29 FOREIGN KEY(SCAD_SOFTWARE) REFERENCES SOFTWARE(CODICE);
ALTER TABLE RICERCHE ADD CONSTRAINT FK_SOFTWARE_31 FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);
ALTER TABLE SETTORI ADD CONSTRAINT FK_SOFTWARE_32 FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);
ALTER TABLE SETTORIAVVISI ADD CONSTRAINT FK_SOFTWARE_33 FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);
ALTER TABLE STATIISTANZA ADD CONSTRAINT FK_SOFTWARE_72 FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);
ALTER TABLE TIPIARCHIVIOISTANZE ADD CONSTRAINT FK_SOFTWARE_75 FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);
ALTER TABLE TIPIMOVIMENTO ADD CONSTRAINT FK_SOFTWARE_16 FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);
ALTER TABLE TIPIPROCEDURE ADD CONSTRAINT FK_SOFTWARE_18 FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);
ALTER TABLE TIPISOGGETTOPEOPLE ADD CONSTRAINT FK_SOFTWARE_35 FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);
ALTER TABLE TIPOLOGIAISTANZA ADD CONSTRAINT FK_SOFTWARE_36 FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);
ALTER TABLE TIPOLOGIAREGISTRI ADD CONSTRAINT FK_SOFTWARE_37 FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);
