<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Connected Services - Old\**" />
    <EmbeddedResource Remove="Connected Services - Old\**" />
    <None Remove="Connected Services - Old\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="RestSharp" Version="114.0.0" />
    <PackageReference Include="SSH.NET" Version="2026.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Init.Utils\Init.Utils.csproj" />
    <ProjectReference Include="..\SIGePro.Data\SIGePro.Data.csproj" />
    <ProjectReference Include="..\VBG.Backend.Protocollo.AppLogic.Shared\VBG.Backend.Protocollo.AppLogic.Shared.csproj" />
    <ProjectReference Include="..\VBG.Backend.Protocollo.Verticalizzazioni.Core\VBG.Backend.Protocollo.Verticalizzazioni.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="ApSystems\LeggiProtocollo\DsGetProtocollo.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>DsGetProtocollo.xsd</DependentUpon>
    </Compile>
    <Compile Update="ApSystems\Protocollazione\Comuni\DsGetComune.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>DsGetComune.xsd</DependentUpon>
    </Compile>
    <Compile Update="ApSystems\Protocollazione\Corrispondenti\Get\DsGetCorrispondente.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>DsGetCorrispondente.xsd</DependentUpon>
    </Compile>
    <Compile Update="ApSystems\Protocollazione\Corrispondenti\Insert\DsInsertCorrispondente.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>DsInsertCorrispondente.xsd</DependentUpon>
    </Compile>
    <Compile Update="ApSystems\Protocollazione\DatiProtocollo\DsDatiProtocollo.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>DsDatiProtocollo.xsd</DependentUpon>
    </Compile>
    <Compile Update="ApSystems\Protocollazione\InserimentoBozza\DsInsertBozza.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>DsInsertBozza.xsd</DependentUpon>
    </Compile>
    <Compile Update="ApSystems\Protocollazione\InsertProtocollo\DsInsertProtocollo.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>DsInsertProtocollo.xsd</DependentUpon>
    </Compile>
    <Compile Update="ApSystems\Protocollazione\InvioBozza\DsInvioBozza.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>DsInvioBozza.xsd</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="ApSystems\LeggiProtocollo\DsGetProtocollo.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>DsGetProtocollo.Designer.cs</LastGenOutput>
    </None>
    <None Update="ApSystems\Protocollazione\Comuni\DsGetComune.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>DsGetComune.Designer.cs</LastGenOutput>
    </None>
    <None Update="ApSystems\Protocollazione\Corrispondenti\Get\DsGetCorrispondente.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>DsGetCorrispondente.Designer.cs</LastGenOutput>
    </None>
    <None Update="ApSystems\Protocollazione\Corrispondenti\Insert\DsInsertCorrispondente.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>DsInsertCorrispondente.Designer.cs</LastGenOutput>
    </None>
    <None Update="ApSystems\Protocollazione\DatiProtocollo\DsDatiProtocollo.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>DsDatiProtocollo.Designer.cs</LastGenOutput>
    </None>
    <None Update="ApSystems\Protocollazione\InserimentoBozza\DsInsertBozza.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>DsInsertBozza.Designer.cs</LastGenOutput>
    </None>
    <None Update="ApSystems\Protocollazione\InsertProtocollo\DsInsertProtocollo.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>DsInsertProtocollo.Designer.cs</LastGenOutput>
    </None>
    <None Update="ApSystems\Protocollazione\InvioBozza\DsInvioBozza.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>DsInvioBozza.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.ServiceModel.Http" Version="10.0.652802" />
  </ItemGroup>
</Project>