ALTER TABLE PAY_REGISTRAZIONI_CONTABILI MODIFY COLUMN IMPORTO DECIMAL(12,2) NULL;
UPDATE ISTANZE SET DATAVALIDITA = STR_TO_DATE(DATE_FORMAT(DATAVALIDITA,'%d/%m/%Y'),'%d/%m/%Y') WHERE DATAVALIDITA IS NOT NULL;
UPDATE I_ATTIVITA_SNAPSHOT SET DATA = STR_TO_DATE(DATE_FORMAT(DATA,'%d/%m/%Y'),'%d/%m/%Y') WHERE DATA IS NOT NULL;

alter Table PAY_POSIZIONI_DEBITORIE drop index PAY_POSDEB_UIDX;
CREATE INDEX PAY_POSDEB_UIDX ON PAY_POSIZIONI_DEBITORIE (IDCOMUNE, IUV);