CREATE INDEX IDX_LAYOUTTESTI_001 ON LAYOUTTESTI (IDCOMUNE, CODICETESTO);
CREATE INDEX IDX_LAYOUTTESTIBASE_001 ON LAYOUTTESTIBASE (CODICETESTO);

CREATE TABLE MASTERKEY (TableName Varchar2(40 char) Not Null, ColumnName Varchar2(40 char) Not Null);
Alter TABLE MASTERKEY ADD CONSTRAINT MASTERKEY_PK PRIMARY KEY (TableName ,COLUMNNAME);

Alter table LETTERETIPO modify (CODICELETTERA number(10));
Alter table TIPIDOCUMENTO modify (CODLETTERATIPO number(10));
Alter table TIPIMOVIMENTO modify (FK_LETTERETIPO number(10));
Alter table TIPIMOVIMENTODOCTIPO modify (CODICELETTERA number(10));
Alter table TIPIPROCEDURE modify (CODLETTAUORIZZATIVA number(10));
Alter table TIPICAUSALIONERI modify (CO_ID number(10));
Alter table INVENTARIOPROCEDIMENTIONERI modify (FK_COID number(10));
Alter table ISTANZELAVORI_D modify (FK_COID number(10));
Alter table LAVORITIPI_CAUSALIONERI modify (FK_COID number(10));
Alter table ISTANZEONERI modify (FKIDTIPOCAUSALE number(10));
Alter table O_CONFIGURAZIONETIPIONERE modify (FK_CO_ID number(10));
Alter table ALBEROPROC_ONERI modify (AO_FK_COID number(10));
Alter table TIPISOGGETTO modify (CODICETIPOSOGGETTO number(10,0));
Alter table ISTANZE modify (FKCODICESOGGETTO number(10,0));
Alter table ISTANZERICHIEDENTI modify (CODICETIPOSOGGETTO number(10,0));
Alter table TIPIMOVIMENTOONERI modify (FK_COID number(10));

ALTER TABLE ISTANZEONERI ADD CONSTRAINT FK_ISTANZEONERI_TIPICAUSALI FOREIGN KEY (IDCOMUNE, FKIDTIPOCAUSALE) REFERENCES TIPICAUSALIONERI (IDCOMUNE, CO_ID);
ALTER TABLE O_CONFIGURAZIONETIPIONERE ADD CONSTRAINT FK_O_CONFTIPIONERE_TIPICAUSALI FOREIGN KEY (IDCOMUNE, FK_CO_ID )REFERENCES TIPICAUSALIONERI(  IDCOMUNE , CO_ID );
ALTER TABLE ALBEROPROC_ONERI ADD CONSTRAINT FK_ALBEROPROCONERI_TIPICAUSALI FOREIGN KEY (IDCOMUNE, AO_FK_COID )REFERENCES TIPICAUSALIONERI(  IDCOMUNE , CO_ID );
ALTER TABLE TIPIMOVIMENTOONERI ADD CONSTRAINT FK_TIPIMOVONERI_TIPICAUSALI FOREIGN KEY (IDCOMUNE, FK_COID )REFERENCES TIPICAUSALIONERI(  IDCOMUNE , CO_ID );

CREATE TABLE SEGNAPOSTO
  (
    ID          NUMBER(4,0) NOT NULL ENABLE,
    TAG         VARCHAR2(64 BYTE) NOT NULL ENABLE,
    DESCRIZIONE VARCHAR2(64 BYTE) NOT NULL ENABLE,
    HELP        VARCHAR2(4000 BYTE)
  );
  
ALTER TABLE SEGNAPOSTO ADD CONSTRAINT SEGNAPOSTO_PK PRIMARY KEY (ID) ENABLE;
COMMENT ON COLUMN SEGNAPOSTO.ID IS 'PK';
COMMENT ON COLUMN SEGNAPOSTO.TAG IS 'TAG CHE VIENE INSERITO NEL DOCUMENTO. ESCLUSI ''[-'' INIZIALE E ''-]'' FINALE';
COMMENT ON COLUMN SEGNAPOSTO.DESCRIZIONE IS 'ETICHETTA DESCRITTIVA DEL SEGNAPOSTO';
COMMENT ON COLUMN SEGNAPOSTO.HELP IS 'HELP PER L''UTILIZZO DEL TAG';
COMMENT ON TABLE SEGNAPOSTO IS 'TABELLA CHE MEMORIZZA TUTTI I SEGNAPOSTO SUPPORTATI PER LE SOSTITUZIONI NEI DOCUMENTI TIPO.';
CREATE UNIQUE INDEX SEGNAPOSTO_IDX_001 ON SEGNAPOSTO  (TAG);

ALTER TABLE DYN2_CAMPI_SCRIPT MODIFY (FK_D2C_ID NUMBER (10));
ALTER TABLE DYN2_MODELLI_SCRIPT MODIFY (FK_D2MT_ID NUMBER (10));    

CREATE VIEW VW_MERCATIPRESENZETOTALI AS SELECT 'STORICO' AS ORIGINE, IDCOMUNE, ANNO, CODICEANAGRAFE, FK_AUTORIZZAZIONI_ID, FKCODICEMERCATO, FKIDMERCATIUSO, FK_IDPOSTEGGIO AS FKIDPOSTEGGIO, NUMEROPRESENZE FROM MERCATIPRESENZE_STORICO UNION SELECT 'CALENDARIO' AS ORIGINE, MERCATIPRESENZE_T.IDCOMUNE, MERCATIPRESENZE_T.ANNO, MERCATIPRESENZE_D.CODICEANAGRAFE, MERCATIPRESENZE_D.FK_AUTORIZZAZIONI_ID, MERCATIPRESENZE_T.FKCODICEMERCATO, MERCATIPRESENZE_T.FKIDMERCATIUSO, MERCATIPRESENZE_D.FKIDPOSTEGGIO, 1 AS NUMEROPRESENZE FROM MERCATIPRESENZE_D, MERCATIPRESENZE_T WHERE MERCATIPRESENZE_D.IDCOMUNE = MERCATIPRESENZE_T.IDCOMUNE AND MERCATIPRESENZE_D.FKIDTESTATA = MERCATIPRESENZE_T.ID AND MERCATIPRESENZE_D.CODICEANAGRAFE IS NOT NULL WITH READ ONLY;
ALTER TABLE BATCH_SCAD_ISTANZE DROP CONSTRAINT FK_BATCHSCADISTANZE_ISTANZE;
ALTER TABLE MESSAGGICFGBASE MODIFY (CORPO NULL);
ALTER TABLE MESSAGGICFG MODIFY (CORPO NULL);
Alter Table Inventarioprocdyn2modellit ADD CONSTRAINT FK_INV_DYN2MODT_DYN2MODELLIT FOREIGN KEY (IDCOMUNE, FK_D2MT_ID) REFERENCES DYN2_MODELLIT (IDCOMUNE, ID);

ALTER TABLE DYN2_CAMPIPROPRIETA ADD CONSTRAINT FK_DYN2_CAMPIPROP_DYN2CAMPI FOREIGN KEY (IDCOMUNE, FK_D2C_ID) REFERENCES DYN2_CAMPI (IDCOMUNE, ID);
ALTER TABLE DYN2_CAMPI_SCRIPT ADD CONSTRAINT FK_DYN2CAMPISCRIPT_DYN2CAMPI FOREIGN KEY (IDCOMUNE, FK_D2C_ID) REFERENCES DYN2_CAMPI (IDCOMUNE, ID);
ALTER TABLE DYN2_MODELLI_SCRIPT ADD CONSTRAINT FK_DYN2MOSCRIPT_DYN2MODELLIT FOREIGN KEY (IDCOMUNE, FK_D2MT_ID) REFERENCES DYN2_MODELLIT (IDCOMUNE, ID);
ALTER TABLE TIPISOGGETTO ADD ORDINE NUMBER(2,0);
ALTER TABLE FORMEGIURIDICHE MODIFY (FORMAGIURIDICA VARCHAR2(60));

CREATE OR REPLACE FORCE VIEW VW_SCADENZARIO (IDCOMUNE, CODICESCADENZA, SOFTWARE, CODICEISTANZA, NUMEROPROTOCOLLO, DATAPROTOCOLLO, 
NUMEROISTANZA, CODSTATOISTANZA, DESCRSTATOISTANZA, CODMOVIMENTO, DESCRMOVIMENTO, DATAMOVIMENTO, CODMOVIMENTODAFARE, 
DESCRMOVIMENTODAFARE, DATASCADENZASTR, CODICEINVENTARIO, CODICEAMMINISTRAZIONE, RESPONSABILE, PROCEDIMENTO, PROCEDURA, 
MODULOSOFTWARE, AMM_AMMINISTRAZIONE, AMM_PARTITAIVA, AMM_PASSWORD, RIC_NOMINATIVO, RIC_CODICEFISCALE, RIC_PARTITAIVA, 
RIC_INDIRIZZO, RIC_CAP, RIC_LOCALITA, RIC_CITTA, RIC_PROVINCIA, RIC_PASSWORD, TEC_NOMINATIVO, TEC_CODICEFISCALE, 
TEC_PARTITAIVA, TEC_PASSWORD, AZ_NOMINATIVO, AZ_CODICEFISCALE, AZ_PARTITAIVA, AZ_PASSWORD, FK_FO_SOGGETTIESTERNI)
                                                            AS
  SELECT VW_BATCH_SCADENZARIO.IDCOMUNE                      AS IDCOMUNE,
    VW_BATCH_SCADENZARIO.ID                                 AS CODICESCADENZA,
    VW_BATCH_SCADENZARIO.SOFTWARE                           AS software,
    VW_BATCH_SCADENZARIO.CODICEISTANZA                      AS codiceistanza,
    ISTANZE.NUMEROPROTOCOLLO                                AS numeroprotocollo,
    ISTANZE.DATAPROTOCOLLO                                  AS dataprotocollo,
    ISTANZE.NUMEROISTANZA                                   AS NUMEROISTANZA,
    ISTANZE.CHIUSURA                                        AS CODSTATOISTANZA,
    STATIISTANZA.STATO                                      AS DESCRSTATOISTANZA,
    VW_BATCH_SCADENZARIO.CODICEMOVIMENTO                    AS CODMOVIMENTO,
    VW_BATCH_SCADENZARIO.DESCRMOVIMENTO                     AS DESCRMOVIMENTO,
    TO_CHAR(MOVIMENTI.DATA,'DD/MM/YYYY')                    AS DATAMOVIMENTO,
    VW_BATCH_SCADENZARIO.TIPOMOVIMENTODAFARE                AS CODMOVIMENTODAFARE,
    VW_BATCH_SCADENZARIO.DESCRMOVIMENTODAFARE               AS DESCRMOVIMENTODAFARE,
    TO_CHAR(VW_BATCH_SCADENZARIO.DATASCADENZA,'DD/MM/YYYY') AS DATASCADENZASTR,
    VW_BATCH_SCADENZARIO.codiceinventario                   AS codiceinventario,
    VW_BATCH_SCADENZARIO.CODICEAMMINISTRAZIONE              AS CODICEAMMINISTRAZIONE,
    RESPONSABILI.RESPONSABILE                               AS RESPONSABILE,
    INVENTARIOPROCEDIMENTI.PROCEDIMENTO                     AS PROCEDIMENTO,
    TIPIPROCEDURE.PROCEDURA                                 AS PROCEDURA,
    SOFTWARE.DESCRIZIONE                                    AS MODULOSOFTWARE,
    amministrazioni.AMMINISTRAZIONE                         AS AMM_amministrazione,
    AMMINISTRAZIONI.PARTITAIVA                              AS AMM_PARTITAIVA,
    AMMINISTRAZIONI.PASSWORD                                AS AMM_PASSWORD,
    ANAGRAFE.NOMINATIVO
    || ' '
    || ANAGRAFE.NOME               AS RIC_NOMINATIVO,
    NVL(ANAGRAFE.CODICEFISCALE,'') AS RIC_CODICEFISCALE,
    NVL(ANAGRAFE.PARTITAIVA,'')    AS RIC_PARTITAIVA,
    ANAGRAFE.INDIRIZZO             AS RIC_INDIRIZZO,
    ANAGRAFE.CAP                   AS RIC_CAP,
    ANAGRAFE.CITTA                 AS RIC_LOCALITA,
    COMUNERESIDENZA.COMUNE         AS RIC_CITTA,
    COMUNERESIDENZA.PROVINCIA      AS RIC_PROVINCIA,
    ANAGRAFE.PASSWORD              AS RIC_PASSWORD,
    TECNICO.NOMINATIVO
    || ' '
    || TECNICO.NOME               AS TEC_NOMINATIVO,
    NVL(TECNICO.CODICEFISCALE,'') AS TEC_CODICEFISCALE,
    NVL(TECNICO.PARTITAIVA,'')    AS TEC_PARTITAIVA,
    TECNICO.PASSWORD              AS TEC_PASSWORD,
    AZIENDA.NOMINATIVO
    || ' '
    || AZIENDA.NOME               AS AZ_NOMINATIVO,
    NVL(AZIENDA.CODICEFISCALE,'') AS AZ_CODICEFISCALE,
    NVL(AZIENDA.PARTITAIVA,'')    AS AZ_PARTITAIVA,
    AZIENDA.PASSWORD              AS AZ_PASSWORD,
    TIPIMOVIMENTO.FK_FO_SOGGETTIESTERNI
  FROM VW_BATCH_SCADENZARIO,
    ISTANZE,
    RESPONSABILI,
    INVENTARIOPROCEDIMENTI,
    MOVIMENTI,
    TIPIPROCEDURE,
    SOFTWARE,
    ANAGRAFE,
    COMUNI COMUNERESIDENZA,
    ANAGRAFE TECNICO,
    ANAGRAFE AZIENDA,
    STATIISTANZA,
    AMMINISTRAZIONI,
    TIPIMOVIMENTO
  WHERE ISTANZE.IDCOMUNE                        =VW_BATCH_SCADENZARIO.IDCOMUNE
  AND ISTANZE.CODICEISTANZA                     =VW_BATCH_SCADENZARIO.CODICEISTANZA
  AND RESPONSABILI.IDCOMUNE                     =ISTANZE.IDCOMUNE
  AND RESPONSABILI.CODICERESPONSABILE           =ISTANZE.CODICERESPONSABILE
  AND INVENTARIOPROCEDIMENTI.IDCOMUNE(+)        =VW_BATCH_SCADENZARIO.IDCOMUNE
  AND INVENTARIOPROCEDIMENTI.CODICEINVENTARIO(+)=VW_BATCH_SCADENZARIO.CODICEINVENTARIO
  AND MOVIMENTI.IDCOMUNE                        =VW_BATCH_SCADENZARIO.IDCOMUNE
  AND MOVIMENTI.CODICEMOVIMENTO                 =VW_BATCH_SCADENZARIO.CODICEMOVIMENTO
  AND TIPIMOVIMENTO.IDCOMUNE                    =VW_BATCH_SCADENZARIO.IDCOMUNE
  AND TIPIMOVIMENTO.TIPOMOVIMENTO               =VW_BATCH_SCADENZARIO.TIPOMOVIMENTODAFARE
  AND TIPIPROCEDURE.IDCOMUNE                    =ISTANZE.IDCOMUNE
  AND TIPIPROCEDURE.CODICEPROCEDURA             =ISTANZE.CODICEPROCEDURA
  AND SOFTWARE.CODICE                           =VW_BATCH_SCADENZARIO.SOFTWARE
  AND ANAGRAFE.IDCOMUNE                         = ISTANZE.IDCOMUNE
  AND ANAGRAFE.CODICEANAGRAFE                   = ISTANZE.CODICERICHIEDENTE
  AND COMUNERESIDENZA.CODICECOMUNE(+)           = ANAGRAFE.COMUNERESIDENZA
  AND TECNICO.IDCOMUNE(+)                       = ISTANZE.IDCOMUNE
  AND TECNICO.CODICEANAGRAFE(+)                 = ISTANZE.CODICEPROFESSIONISTA
  AND AZIENDA.IDCOMUNE(+)                       = ISTANZE.IDCOMUNE
  AND AZIENDA.CODICEANAGRAFE(+)                 = ISTANZE.CODICETITOLARELEGALE
  AND STATIISTANZA.IDCOMUNE                     = ISTANZE.IDCOMUNE
  AND STATIISTANZA.SOFTWARE                     = ISTANZE.SOFTWARE
  AND STATIISTANZA.CODICESTATO                  = ISTANZE.CHIUSURA
  AND AMMINISTRAZIONI.IDCOMUNE(+)               = VW_BATCH_SCADENZARIO.IDCOMUNE
  AND AMMINISTRAZIONI.CODICEAMMINISTRAZIONE(+)  = VW_BATCH_SCADENZARIO.CODICEAMMINISTRAZIONE;
ALTER TABLE F_DOMANDE ADD (DM_NUM_PROT NUMBER(7) );
ALTER TABLE F_DOMANDE ADD (DM_DATA_PROT VARCHAR2(8) );
ALTER TABLE ALBEROPROC MODIFY (SC_PROTTIPODOCUMENTO VARCHAR2(50 CHAR) );  
ALTER TABLE CLMENU_JAVA ADD (TIPO_FUNZIONALITA VARCHAR2(1 CHAR));
COMMENT ON COLUMN CLMENU_JAVA.TIPO_FUNZIONALITA IS 'Specifica se la funzionalità che attiva il menù è di tipo Enterprise o Standard (valori ammessi E=Enterprise, S=Standard)';

ALTER TABLE FO_DOMANDE ADD IDENTIFICATIVODOMANDA VARCHAR2(50 CHAR);
select 'ATTENZIONE: Se si dovessero verificare errori durante la attivazione della chiave FK_DOMANDE_ANAGRAFE utilizzare il seguente script per bonificare i records ATTENZIONEATTENZIONE: lo script non elimina gli oggetti referenziati in fo_domande_oggetti,  eseguire questo passaggio a parte o lasciare gli oggetti nel db (potrebbero essere in uso in qualche istanza). Controllare il file WARNING1.TXT' from NONESISTE;
ALTER TABLE FO_DOMANDE ADD CONSTRAINT FK_DOMANDE_ANAGRAFE FOREIGN KEY (IDCOMUNE, CODICEANAGRAFE) REFERENCES ANAGRAFE (IDCOMUNE, CODICEANAGRAFE);
SELECT 'ATTENZIONE Se si dovessero verificare errori durante la attivazione della chiave FK_DOMANDE_OGGETTI_DOMPADRE utilizzare il seguente script per bonificare i records ATTENZIONE lo script non elimina gli oggetti referenziati in fo_domande_oggetti,  eseguire questo passaggio a parte o lasciare gli oggetti nel db (potrebbero essere in uso in qualche istanza). Controllare il file WARNING2.TXT'  from NONESISTE;
ALTER TABLE FO_DOMANDE_OGGETTI ADD CONSTRAINT FK_DOMANDE_OGGETTI_DOMPADRE FOREIGN KEY (IDCOMUNE, IDDOMANDA) REFERENCES FO_DOMANDE (IDCOMUNE, ID);
ALTER TABLE FO_SOTTOSCRIZIONI ADD CONSTRAINT FO_SOTTOSCRIZIONI_DOMPADRE FOREIGN KEY (IDCOMUNE, CODICEDOMANDA) REFERENCES FO_DOMANDE (IDCOMUNE, ID);
ALTER TABLE FO_MESSAGGI ADD CONSTRAINT FO_MESSAGGI_DOMPADRE FOREIGN KEY (IDCOMUNE, CODICEDOMANDA) REFERENCES FO_DOMANDE (IDCOMUNE, ID);

ALTER TABLE MOVIMENTIMAIL ADD MESSAGE_ID VARCHAR2(400 CHAR);
ALTER TABLE MOVIMENTIMAIL ADD ID_PADRE NUMBER(8,0);
ALTER TABLE MOVIMENTIMAIL ADD CONSTRAINT FK_IDPADRE_ID FOREIGN KEY(IDCOMUNE,ID_PADRE) REFERENCES MOVIMENTIMAIL(IDCOMUNE,ID);
ALTER TABLE MOVIMENTIMAIL MODIFY MITTENTE VARCHAR2(200 CHAR);
ALTER TABLE ISTANZESTRADARIO ADD CONSTRAINT FK_ISTANZESTRADARIO_COLORE FOREIGN KEY (IDCOMUNE, COLORE) REFERENCES STRADARIOCOLORE (IDCOMUNE, CODICECOLORE);
ALTER TABLE ISTANZESTRADARIO ADD PIANO VARCHAR2(50 CHAR);
ALTER TABLE ISTANZESTRADARIO ADD QUARTIERE VARCHAR2(50 CHAR);
ALTER TABLE RAGGRUPPAMENTOCAUSALIONERI MODIFY (RCO_ID NUMBER(10));
ALTER TABLE TIPICAUSALIONERI MODIFY (FK_RCO_ID NUMBER(10));
ALTER TABLE FO_DOMANDE ADD CONSTRAINT FK_FO_DOMANDE_SOFTWARE FOREIGN KEY (SOFTWARE) REFERENCES SOFTWARE (CODICE);
ALTER TABLE FO_MESSAGGI ADD CONSTRAINT FK_FO_MESSAGGI_SOFTWARE FOREIGN KEY (SOFTWARE) REFERENCES SOFTWARE (CODICE);
alter table ISTANZEPROCEDIMENTI add TIPO_ATTO varchar2(100 char);
alter table ISTANZEPROCEDIMENTI add RILASCIATO_DA varchar2(100 char);
CREATE INDEX IDX_ISTANZECOLLEGATE_002 ON ISTANZECOLLEGATE (IDCOMUNE,CODICEISTANZA);
CREATE INDEX IDX_ISTANZECOLLEGATE_003 ON ISTANZECOLLEGATE (IDCOMUNE,CODICEISTANZACOLLEGATA) ;
CREATE OR REPLACE FORCE VIEW VW_FULL_ISTANZECOLLEGATE (IDCOMUNE, PROGRESSIVO, CODICEISTANZA, ORDINE) AS   SELECT IDCOMUNE, PROGRESSIVO, CODICEISTANZA, ORDINE FROM ISTANZECOLLEGATE GROUP BY IDCOMUNE, PROGRESSIVO, CODICEISTANZA, ORDINE UNION SELECT IDCOMUNE, PROGRESSIVO, CODICEISTANZACOLLEGATA, ORDINE FROM ISTANZECOLLEGATE GROUP BY IDCOMUNE, PROGRESSIVO, CODICEISTANZACOLLEGATA, ORDINE;

ALTER TABLE ALLEGATI ADD FLAG_INSERIMENTO_AUT NUMBER(1,0);
COMMENT ON COLUMN ALLEGATI.FLAG_INSERIMENTO_AUT IS 'Se 1 allora l''allegato non è stato inserito tramite interfaccia grafica ma in automatico tramite altre procedure';
ALTER TABLE ALBEROPROC_DOCUMENTI ADD FLAG_INSERIMENTO_AUT NUMBER(1,0);
COMMENT ON COLUMN ALBEROPROC_DOCUMENTI.FLAG_INSERIMENTO_AUT IS 'Se 1 allora il documento non è stato inserito tramite interfaccia grafica ma in automatico tramite altre procedure ';
CREATE INDEX IDX_DOMANDESTC_001 ON DOMANDESTC (IDCOMUNE,CODICESOFTWARE,NUMEROISTANZA);
alter table NATURAENDO modify (BINARIODIPENDENZE number(10));

ALTER TABLE DYN2_MODELLIT DROP CONSTRAINT DYN2_MODELLIT_UK1;
DROP INDEX DYN2_MODELLIT_UK1;
CREATE INDEX DYN2_MODELLIT_UK1 ON DYN2_MODELLIT (IDCOMUNE, SOFTWARE, CODICE_SCHEDA);

CREATE TABLE tipiprocedure_dyn2modellit (idcomune VARCHAR2(6) NOT NULL,fk_codiceprocedura NUMBER(10,0) NOT NULL,fk_d2mt_id NUMBER(10,0) NOT NULL,flag_pubblica NUMBER(1,0)  NULL,flag_tipofirma NUMBER(1,0)  NULL,flag_facoltativa NUMBER(1,0) NULL);
ALTER TABLE tipiprocedure_dyn2modellit ADD CONSTRAINT tipiprocedure_dyn2modellit_pk PRIMARY KEY (idcomune,fk_codiceprocedura,fk_d2mt_id);
ALTER TABLE tipiprocedure_dyn2modellit ADD CONSTRAINT fk_tpd2mt_tproc FOREIGN KEY (idcomune,fk_codiceprocedura) REFERENCES tipiprocedure (idcomune,codiceprocedura);
ALTER TABLE tipiprocedure_dyn2modellit ADD CONSTRAINT fk_tpd2mt_d2mt FOREIGN KEY (idcomune,fk_d2mt_id) REFERENCES dyn2_modellit (idcomune,id);

COMMENT ON COLUMN tipiprocedure_dyn2modellit.fk_codiceprocedura IS 'tipiprocedure.codiceprocedura';
COMMENT ON COLUMN tipiprocedure_dyn2modellit.fk_d2mt_id IS 'DYN2_MODELLIT.ID';
COMMENT ON COLUMN tipiprocedure_dyn2modellit.flag_pubblica IS '0 = Non pubblicare, 1 = Pubblica nell''area riservata';
COMMENT ON COLUMN tipiprocedure_dyn2modellit.flag_tipofirma IS '0 = Non necessita di firma, 1 = Firma l''intero documento, 2 = Firma ogni singolo blocco';

CREATE OR REPLACE VIEW VW_ISTANZECONCESSIONILISTA AS SELECT 99999999 AS PROGRESSIVO, AUTORIZZAZIONI.AUTORIZRESPONSABILE AS CONC_AUTORIZRESPONSABILE, AUTORIZZAZIONI.IDCOMUNE, AUTORIZZAZIONI.FK_CAUSALE_ACQUISIZIONE AS ICONC_CODICECAUSALE, NVL(AUTORIZZAZIONI.DATA_CESSAZIONE,TO_DATE('31/12/9999','DD/MM/YYYY')) AS DATA_STORICO, ISTANZE.SOFTWARE, ISTANZE.CODICEISTANZA AS IST_CODICEISTANZA, ISTANZE.NUMEROISTANZA AS IST_NUMEROISTANZA, ISTANZE.CODICERICHIEDENTE AS IST_CODICERICHIEDENTE, AUTORIZZAZIONI.ID AS CONC_ID, AUTORIZZAZIONI.AUTORIZNUMERO AS CONC_NUMERO, AUTORIZZAZIONI.AUTORIZDATA AS CONC_DATARILASCIO, AUTORIZZAZIONI.AUTORIZDATA AS DATARILASCIO, AUTORIZZAZIONI.DATASCADENZA AS CONC_DATASCADENZA, AUTORIZZAZIONI_CONCESSIONI.FK_TIPOCONCESSIONE AS CONC_CODICETIPO, CONCESSIONITIPI.DESCRIZIONE AS CONC_TIPO, AUTORIZZAZIONI_CONCESSIONI.STAGIONALEA AS CONC_STAGIONALEA, AUTORIZZAZIONI_CONCESSIONI.STAGIONALEDA AS CONC_STAGIONALEDA, AUTORIZZAZIONI.FLAG_ATTIVA AS CONC_ATTIVA, AUTORIZZAZIONI.FK_CODICEANAGRAFE AS CONC_CODICETITOLARE, TITOLARE.NOMINATIVO || ' ' || TITOLARE.NOME AS CONC_TITOLARE, TITOLARE.CODICEFISCALE AS CONC_TIT_CF, TITOLARE.PARTITAIVA AS CONC_TIT_PIVA, TITOLARE.TIPOANAGRAFE AS CONC_TIT_TIPOANAGRAFE, AUT_COLLEGATA.AUTORIZNUMERO AS AUT_NUMERO, AUT_COLLEGATA.AUTORIZDATA AS AUT_DATA, AUT_COLLEGATA.AUTORIZDATA, AUT_COLLEGATA.FKIDREGISTRO AS AUT_CODREGISTRO, TIPOLOGIAREGISTRI.TR_DESCRIZIONE AS AUT_REGISTRO, IST_RICHIEDENTE.NOMINATIVO || ' ' || IST_RICHIEDENTE.NOME AS IST_NOMINATIVO, IST_RICHIEDENTE.TIPOANAGRAFE AS IST_RIC_TIPOANAGRAFE, IST_AZIENDA.NOMINATIVO || ' ' || IST_AZIENDA.NOME AS IST_NOMINATIVOAZIENDA, IST_AZIENDA.TIPOANAGRAFE AS IST_AZI_TIPOANAGRAFE, IST_RICHIEDENTE.CODICEFISCALE AS IST_CODICEFISCALE, IST_RICHIEDENTE.PARTITAIVA AS IST_PARTITAIVA, CAUS_ATTUALE.DESCRIZIONE AS ICONC_CAUSALE, AUTORIZZAZIONI.FK_CAUSALE_CESSAZIONE AS ICONC_CODICECAUSALESTORICO, CAUS_STORICO.DESCRIZIONE AS ICONC_CAUSALESTORICO, AUTORIZZAZIONI_CONCESSIONI.FK_CODICEMERCATO AS CONC_IDMERCATO, MERCATI.DESCRIZIONE AS CONC_MERCATO, MERCATI.ATTIVO AS MERC_ATTIVO, AUTORIZZAZIONI_CONCESSIONI.FK_IDPOSTEGGIO AS CONC_IDPOSTEGGIO, MERCATI_D.CODICEPOSTEGGIO AS CONC_POSTEGGIO, MERCATI_D.LARGHEZZA AS CONC_POS_LARGHEZZA, MERCATI_D.LUNGHEZZA AS CONC_POS_LUNGHEZZA, MERCATI_D.SUPERFICIE AS CONC_POS_SUPERFICIE, MERCATI_D.FKCODICETIPOSPAZIO AS POST_IDTIPOSPAZIO, POSTEGGITIPOSPAZIO.TIPOSPAZIO AS POST_TIPOSPAZIO, AUTORIZZAZIONI_CONCESSIONI.FK_IDMERCATIUSO AS CONC_IDMERCATIUSO, MERCATI_USO.DESCRIZIONE AS CONC_DESCRIZIONEUSO, MERCATI_USO.PESO AS PESO_MERCATO, MERCATI_USO.FKCODICEUSO AS MERC_IDUSO, MERCATI_D.FKCODICESTRADARIO AS CONC_POS_CODICESTRADARIO FROM AUTORIZZAZIONI, AUTORIZZAZIONI_CONCESSIONI, AUTORIZZAZIONI AUT_COLLEGATA, CONCESSIONITIPI, TIPOLOGIAREGISTRI, ANAGRAFE TITOLARE, CONCESSIONICAUSALI CAUS_ATTUALE, CONCESSIONICAUSALI CAUS_STORICO, ISTANZE, ANAGRAFE IST_RICHIEDENTE, MERCATI, MERCATI_D, POSTEGGITIPOSPAZIO, MERCATI_USO, ANAGRAFE IST_AZIENDA WHERE AUTORIZZAZIONI.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND AUTORIZZAZIONI.ID = AUTORIZZAZIONI_CONCESSIONI.FK_IDAUT_ATTUALE AND AUT_COLLEGATA.IDCOMUNE(+) = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND AUT_COLLEGATA.ID(+) = AUTORIZZAZIONI_CONCESSIONI.FK_IDAUT_COLLEGATA AND CONCESSIONITIPI.TIPOCONCESSIONE = AUTORIZZAZIONI_CONCESSIONI.FK_TIPOCONCESSIONE AND TIPOLOGIAREGISTRI.IDCOMUNE(+) = AUTORIZZAZIONI.IDCOMUNE AND TIPOLOGIAREGISTRI.TR_ID(+) = AUTORIZZAZIONI.FKIDREGISTRO AND TITOLARE.IDCOMUNE = AUTORIZZAZIONI.IDCOMUNE AND TITOLARE.CODICEANAGRAFE = AUTORIZZAZIONI.FK_CODICEANAGRAFE AND CAUS_ATTUALE.IDCOMUNE = AUTORIZZAZIONI.IDCOMUNE AND CAUS_ATTUALE.CODICECAUSALE = AUTORIZZAZIONI.FK_CAUSALE_ACQUISIZIONE AND CAUS_STORICO.IDCOMUNE(+) = AUTORIZZAZIONI.IDCOMUNE AND CAUS_STORICO.CODICECAUSALE(+) = AUTORIZZAZIONI.FK_CAUSALE_CESSAZIONE AND ISTANZE.IDCOMUNE = AUTORIZZAZIONI.IDCOMUNE AND ISTANZE.CODICEISTANZA = AUTORIZZAZIONI.FKIDISTANZA AND IST_RICHIEDENTE.IDCOMUNE = ISTANZE.IDCOMUNE AND IST_RICHIEDENTE.CODICEANAGRAFE = ISTANZE.CODICERICHIEDENTE AND MERCATI.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND MERCATI.CODICEMERCATO = AUTORIZZAZIONI_CONCESSIONI.FK_CODICEMERCATO AND MERCATI_D.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND MERCATI_D.IDPOSTEGGIO = AUTORIZZAZIONI_CONCESSIONI.FK_IDPOSTEGGIO AND POSTEGGITIPOSPAZIO.IDCOMUNE(+) = MERCATI_D.IDCOMUNE AND POSTEGGITIPOSPAZIO.CODICE(+) = MERCATI_D.FKCODICETIPOSPAZIO AND MERCATI_USO.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND MERCATI_USO.ID = AUTORIZZAZIONI_CONCESSIONI.FK_IDMERCATIUSO AND IST_AZIENDA.IDCOMUNE(+) = ISTANZE.IDCOMUNE AND IST_AZIENDA.CODICEANAGRAFE(+) = ISTANZE.CODICETITOLARELEGALE UNION SELECT AUTORIZZAZIONI_SUBENTRI.ID AS PROGRESSIVO, AUTORIZZAZIONI_SUBENTRI.AUTORIZRESPONSABILE AS CONC_AUTORIZRESPONSABILE, AUTORIZZAZIONI_SUBENTRI.IDCOMUNE, AUTORIZZAZIONI_SUBENTRI.FK_CAUSALE_ACQUISIZIONE AS ICONC_CODICECAUSALE, AUTORIZZAZIONI_SUBENTRI.DATA_CESSAZIONE AS DATA_STORICO, ISTANZE.SOFTWARE, ISTANZE.CODICEISTANZA AS IST_CODICEISTANZA, ISTANZE.NUMEROISTANZA AS IST_NUMEROISTANZA, ISTANZE.CODICERICHIEDENTE AS IST_CODICERICHIEDENTE, AUTORIZZAZIONI_SUBENTRI.FK_IDAUT_ATTUALE AS CONC_ID, AUTORIZZAZIONI_SUBENTRI.AUTORIZNUMERO AS CONC_NUMERO, AUTORIZZAZIONI_SUBENTRI.AUTORIZDATA AS CONC_DATARILASCIO, AUTORIZZAZIONI_SUBENTRI.AUTORIZDATA AS DATARILASCIO, AUTORIZZAZIONI_SUBENTRI.DATASCADENZA AS CONC_DATASCADENZA, AUTORIZZAZIONI_CONCESSIONI.FK_TIPOCONCESSIONE AS CONC_CODICETIPO, CONCESSIONITIPI.DESCRIZIONE AS CONC_TIPO, AUTORIZZAZIONI_CONCESSIONI.STAGIONALEA AS CONC_STAGIONALEA, AUTORIZZAZIONI_CONCESSIONI.STAGIONALEDA AS CONC_STAGIONALEDA, 0 AS CONC_ATTIVA,AUTORIZZAZIONI_SUBENTRI.FK_CODICEANAGRAFE AS CONC_CODICETITOLARE,TITOLARE.NOMINATIVO || ' ' || TITOLARE.NOME AS CONC_TITOLARE, TITOLARE.CODICEFISCALE AS CONC_TIT_CF,TITOLARE.PARTITAIVA AS CONC_TIT_PIVA, TITOLARE.TIPOANAGRAFE AS CONC_TIT_TIPOANAGRAFE, AUT_COLLEGATA.AUTORIZNUMERO AS AUT_NUMERO, AUT_COLLEGATA.AUTORIZDATA AS AUT_DATA, AUT_COLLEGATA.AUTORIZDATA,AUT_COLLEGATA.FKIDREGISTRO AS AUT_CODREGISTRO, TIPOLOGIAREGISTRI.TR_DESCRIZIONE AS AUT_REGISTRO,IST_RICHIEDENTE.NOMINATIVO || ' ' || IST_RICHIEDENTE.NOME AS IST_NOMINATIVO, IST_RICHIEDENTE.TIPOANAGRAFE AS IST_RIC_TIPOANAGRAFE, IST_AZIENDA.NOMINATIVO || ' ' || IST_AZIENDA.NOME AS IST_NOMINATIVOAZIENDA, IST_AZIENDA.TIPOANAGRAFE AS IST_AZI_TIPOANAGRAFE, IST_RICHIEDENTE.CODICEFISCALE AS IST_CODICEFISCALE,IST_RICHIEDENTE.PARTITAIVA AS IST_PARTITAIVA, CAUS_ATTUALE.DESCRIZIONE AS ICONC_CAUSALE, AUTORIZZAZIONI_SUBENTRI.FK_CAUSALE_CESSAZIONE AS ICONC_CODICECAUSALESTORICO, CAUS_STORICO.DESCRIZIONE AS ICONC_CAUSALESTORICO, AUTORIZZAZIONI_CONCESSIONI.FK_CODICEMERCATO AS CONC_IDMERCATO, MERCATI.DESCRIZIONE AS CONC_MERCATO,MERCATI.ATTIVO AS MERC_ATTIVO,AUTORIZZAZIONI_CONCESSIONI.FK_IDPOSTEGGIO AS CONC_IDPOSTEGGIO, MERCATI_D.CODICEPOSTEGGIO AS CONC_POSTEGGIO, MERCATI_D.LARGHEZZA AS CONC_POS_LARGHEZZA,MERCATI_D.LUNGHEZZA AS CONC_POS_LUNGHEZZA,MERCATI_D.SUPERFICIE AS CONC_POS_SUPERFICIE, MERCATI_D.FKCODICETIPOSPAZIO AS POST_IDTIPOSPAZIO,POSTEGGITIPOSPAZIO.TIPOSPAZIO AS POST_TIPOSPAZIO,AUTORIZZAZIONI_CONCESSIONI.FK_IDMERCATIUSO AS CONC_IDMERCATIUSO, MERCATI_USO.DESCRIZIONE AS CONC_DESCRIZIONEUSO,MERCATI_USO.PESO AS PESO_MERCATO, MERCATI_USO.FKCODICEUSO AS MERC_IDUSO, MERCATI_D.FKCODICESTRADARIO AS CONC_POS_CODICESTRADARIO FROM AUTORIZZAZIONI_SUBENTRI,AUTORIZZAZIONI_CONCESSIONI, AUTORIZZAZIONI AUT_COLLEGATA, CONCESSIONITIPI, TIPOLOGIAREGISTRI,ANAGRAFE TITOLARE,CONCESSIONICAUSALI CAUS_ATTUALE, CONCESSIONICAUSALI CAUS_STORICO, ISTANZE, ANAGRAFE IST_RICHIEDENTE,MERCATI,MERCATI_D,POSTEGGITIPOSPAZIO, MERCATI_USO,ANAGRAFE IST_AZIENDA WHERE AUTORIZZAZIONI_SUBENTRI.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND AUTORIZZAZIONI_SUBENTRI.FK_IDAUT_ATTUALE = AUTORIZZAZIONI_CONCESSIONI.FK_IDAUT_ATTUALE AND AUT_COLLEGATA.IDCOMUNE(+) = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND AUT_COLLEGATA.ID(+) = AUTORIZZAZIONI_CONCESSIONI.FK_IDAUT_COLLEGATA AND CONCESSIONITIPI.TIPOCONCESSIONE = AUTORIZZAZIONI_CONCESSIONI.FK_TIPOCONCESSIONE AND TIPOLOGIAREGISTRI.IDCOMUNE(+) = AUTORIZZAZIONI_SUBENTRI.IDCOMUNE AND TIPOLOGIAREGISTRI.TR_ID(+) = AUTORIZZAZIONI_SUBENTRI.FKIDREGISTRO AND TITOLARE.IDCOMUNE = AUTORIZZAZIONI_SUBENTRI.IDCOMUNE AND TITOLARE.CODICEANAGRAFE = AUTORIZZAZIONI_SUBENTRI.FK_CODICEANAGRAFE AND CAUS_ATTUALE.IDCOMUNE = AUTORIZZAZIONI_SUBENTRI.IDCOMUNE AND CAUS_ATTUALE.CODICECAUSALE = AUTORIZZAZIONI_SUBENTRI.FK_CAUSALE_ACQUISIZIONE AND CAUS_STORICO.IDCOMUNE(+) = AUTORIZZAZIONI_SUBENTRI.IDCOMUNE AND CAUS_STORICO.CODICECAUSALE(+) = AUTORIZZAZIONI_SUBENTRI.FK_CAUSALE_CESSAZIONE AND ISTANZE.IDCOMUNE = AUTORIZZAZIONI_SUBENTRI.IDCOMUNE AND ISTANZE.CODICEISTANZA = AUTORIZZAZIONI_SUBENTRI.FKIDISTANZA AND IST_RICHIEDENTE.IDCOMUNE = ISTANZE.IDCOMUNE AND IST_RICHIEDENTE.CODICEANAGRAFE = ISTANZE.CODICERICHIEDENTE AND MERCATI.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND MERCATI.CODICEMERCATO = AUTORIZZAZIONI_CONCESSIONI.FK_CODICEMERCATO AND MERCATI_D.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND MERCATI_D.IDPOSTEGGIO = AUTORIZZAZIONI_CONCESSIONI.FK_IDPOSTEGGIO AND POSTEGGITIPOSPAZIO.IDCOMUNE(+) = MERCATI_D.IDCOMUNE AND POSTEGGITIPOSPAZIO.CODICE(+) = MERCATI_D.FKCODICETIPOSPAZIO AND MERCATI_USO.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND MERCATI_USO.ID = AUTORIZZAZIONI_CONCESSIONI.FK_IDMERCATIUSO AND IST_AZIENDA.IDCOMUNE(+) = ISTANZE.IDCOMUNE AND IST_AZIENDA.CODICEANAGRAFE(+) = ISTANZE.CODICETITOLARELEGALE;
CREATE OR REPLACE VIEW VW_CONCESSIONILISTA AS SELECT IDCOMUNE, SOFTWARE, PROGRESSIVO, CONC_ID, CONC_NUMERO, CONC_DATARILASCIO, CONC_DATASCADENZA, CONC_CODICETIPO, CONC_TIPO, CONC_STAGIONALEA, CONC_STAGIONALEDA, CONC_ATTIVA, CONC_CODICETITOLARE, CONC_TITOLARE, CONC_TIT_CF, CONC_TIT_PIVA, CONC_TIT_TIPOANAGRAFE, AUT_NUMERO, AUT_DATA, AUT_CODREGISTRO, AUT_REGISTRO, IST_CODICEISTANZA, IST_NUMEROISTANZA, IST_CODICERICHIEDENTE, IST_NOMINATIVO, IST_CODICEFISCALE, IST_PARTITAIVA, IST_RIC_TIPOANAGRAFE, ICONC_CODICECAUSALE, ICONC_CAUSALE, ICONC_CODICECAUSALESTORICO, ICONC_CAUSALESTORICO, CONC_IDMERCATO, CONC_MERCATO, MERC_ATTIVO, CONC_IDPOSTEGGIO, CONC_POSTEGGIO, CONC_POS_LARGHEZZA, CONC_POS_LUNGHEZZA, CONC_POS_SUPERFICIE, POST_IDTIPOSPAZIO, POST_TIPOSPAZIO, CONC_IDMERCATIUSO, CONC_DESCRIZIONEUSO, PESO_MERCATO, MERC_IDUSO, CONC_POS_CODICESTRADARIO FROM VW_ISTANZECONCESSIONILISTA;

ALTER TABLE CC_CAUSALIRIDUZIONIR DROP CONSTRAINT  FK_CCCAUSRIDUR_CCCAUSRIDUT;
ALTER TABLE CC_CAUSALIRIDUZIONIR ADD CONSTRAINT FK_CCCAUSRIDUR_CCCAUSRIDUT FOREIGN KEY (IDCOMUNE, FK_CCCRT_ID) REFERENCES CC_CAUSALIRIDUZIONIT (IDCOMUNE, ID);

alter table MAIL_CONFIG add (IN_LOGINNAME varchar2(320 char));
alter table MAIL_CONFIG add (IN_LOGINPASS varchar2(30 char));
alter table MAIL_CONFIG add (IN_USEAUTHENTICATION number(1,0));
alter table MAIL_CONFIG add (IN_MAILSERVER varchar2(50 char));
alter table MAIL_CONFIG add (IN_PORT number(5,0));
alter table MAIL_CONFIG add (IN_USESSL number(1,0));
comment on column MAIL_CONFIG.SSL_ACCEPTINVALIDCERTIFICATES is 'Dismesso';

ALTER TABLE BATCH_SCADENZARIO DROP CONSTRAINT FK_BATCHSCA_AMMINISTRAZ;
ALTER TABLE BATCH_SCADENZARIO DROP CONSTRAINT FK_BATCHSCA_INVENTARIO;
ALTER TABLE BATCH_SCADENZARIO DROP CONSTRAINT FK_BATCHSCA_ISTANZE;
ALTER TABLE BATCH_SCADENZARIO DROP CONSTRAINT FK_BATCHSCA_MOVIMENTI;
ALTER TABLE BATCH_SCADENZARIO DROP CONSTRAINT FK_BATCHSCA_TIPIMOV;

CREATE INDEX IDX_DOMANDESTC_002 ON DOMANDESTC (IDCOMUNE,CODICESOFTWARE,FLAG_IMPORT);
ALTER TABLE SORTEGGIDETTAGLIO ADD CONSTRAINT SORTEGGIDETTAGLIO_UK01 UNIQUE (IDCOMUNE,SD_FK_STID,CODICEISTANZA);

ALTER TABLE ANAGRAFE MODIFY INDIRIZZO VARCHAR2(100);
ALTER TABLE ANAGRAFESTORICO MODIFY INDIRIZZO VARCHAR2(100);
ALTER TABLE TIPIMOV_STC_ALBEROPROC MODIFY FK_SCID NUMBER(10, 0);
ALTER TABLE INVENTARIOPROCEDIMENTIPEOPLE MODIFY COD_PROC_PEOPLE VARCHAR2(50 CHAR);
CREATE INDEX IDX_DOMANDESTC_003 ON DOMANDESTC (IDCOMUNE, ID_DOMANDAMITT);

ALTER TABLE DOCUMENTIISTANZA ADD FLG_DA_MODELLO_DINAMICO NUMBER(1,0);
COMMENT ON COLUMN DOCUMENTIISTANZA.FLG_DA_MODELLO_DINAMICO IS 'Se 1 allora il documento è stato inserito da un modello dinamico';

ALTER TABLE ISTANZECOLLEGATE DROP CONSTRAINT FK_ISTANZE_COLL_ISTANZACOLL;
ALTER TABLE ISTANZECOLLEGATE DROP CONSTRAINT FK_ISTANZE_COLL_ISTANZE;
DROP INDEX IDX_ISTANZECOLLEGATE_001;
DROP INDEX IDX_ISTANZECOLLEGATE_002;
DROP INDEX IDX_ISTANZECOLLEGATE_003;
CREATE TABLE ISTANZECOLLEGATE_BAK AS SELECT * FROM ISTANZECOLLEGATE;



DROP TABLE ISTANZECOLLEGATE;
CREATE TABLE ISTANZECOLLEGATE (IDCOMUNE VARCHAR2(6) NOT NULL, PROGRESSIVO NUMBER(8,0) NOT NULL, CODICEISTANZA NUMBER(6,0) NOT NULL, ORDINE NUMBER(3,0) NOT NULL, ID NUMBER(8,0) NOT NULL, CODICEISTANZACOLLEGATA NUMBER(6,0));
INSERT INTO ISTANZECOLLEGATE (IDCOMUNE,ID,PROGRESSIVO,CODICEISTANZA, ORDINE, CODICEISTANZACOLLEGATA)( SELECT IDCOMUNE, ID,PROGRESSIVO,CODICEISTANZA,ORDINE,CODICEISTANZACOLLEGATA FROM ISTANZECOLLEGATE_BAK );
ALTER TABLE ISTANZECOLLEGATE ADD CONSTRAINT ISTANZECOLLEGATE_PK PRIMARY KEY (IDCOMUNE,ID);
ALTER TABLE ISTANZECOLLEGATE ADD (CONSTRAINT FK_ISTANZE_COLL_ISTANZE FOREIGN KEY(IDCOMUNE,CODICEISTANZA) REFERENCES ISTANZE(IDCOMUNE,CODICEISTANZA));
ALTER TABLE ISTANZECOLLEGATE ADD (CONSTRAINT FK_ISTANZE_COLL_ISTANZACOLL FOREIGN KEY(IDCOMUNE,CODICEISTANZACOLLEGATA) REFERENCES ISTANZE(IDCOMUNE,CODICEISTANZA));
CREATE INDEX IDX_ISTANZECOLLEGATE_001 ON ISTANZECOLLEGATE(IDCOMUNE,PROGRESSIVO,CODICEISTANZA,ORDINE);
CREATE INDEX IDX_ISTANZECOLLEGATE_002 ON ISTANZECOLLEGATE(IDCOMUNE,CODICEISTANZA);
CREATE INDEX IDX_ISTANZECOLLEGATE_003 ON ISTANZECOLLEGATE(IDCOMUNE,CODICEISTANZACOLLEGATA);
ALTER TABLE ANAGRAFE MODIFY PARTITAIVA VARCHAR2(16 CHAR);
ALTER TABLE ANAGRAFESTORICO MODIFY PARTITAIVA VARCHAR2(16 CHAR);

ALTER TABLE ALBEROPROC_DYN2MODELLIT ADD FLAG_FACOLTATIVA NUMBER(1, 0);

ALTER TABLE INVENTARIOPROCDYN2MODELLIT ADD FLAG_FACOLTATIVA NUMBER(1, 0);
