CREATE INDEX IDX_PECINBOX_ISTANZE ON PEC_INBOX(IDCOMUNE,CODICEISTANZA);
CREATE INDEX IDX_PECINBOX_MOVIMENTI ON PEC_INBOX(IDCOMUNE,CODICEMOVIMENTO);

CREATE TABLE VISTA_ALBEROPROC AS SELECT * FROM VW_ALBEROPROC;
CREATE INDEX IDX_VISTA_ALBEROPROC_001 ON VISTA_ALBEROPROC (IDCOMUNE, SC_ID) ;
ALTER TABLE ALBEROPROC ADD DESCRIZIONE_COMPLETA VARCHAR(4000);

UPDATE ALBEROPROC A 
    JOIN VISTA_ALBEROPROC B ON A.IDCOMUNE = B.IDCOMUNE AND A.SC_ID = B.SC_ID
    SET A.DESCRIZIONE_COMPLETA = B.SC_DESCRIZIONE
WHERE A.DESCRIZIONE_COMPLETA IS NULL;

DROP TABLE vista_alberoproc;

create index IDX_DOCUMENTIDAFIRMARE_FK_001 on DOCUMENTI_DA_FIRMARE(IDCOMUNE,CODICEISTANZA);
create index IDX_DOCUMENTIDAFIRMARE_FK_002 on DOCUMENTI_DA_FIRMARE(IDCOMUNE,CODICEMOVALLEGATI);
create index IDX_DOCUMENTIDAFIRMARE_FK_003 on DOCUMENTI_DA_FIRMARE(IDCOMUNE,CODICERICHIEDENTE);
create index IDX_DOCUMENTIDAFIRMARE_FK_004 on DOCUMENTI_DA_FIRMARE(IDCOMUNE,CODICEFIRMATARIO);


ALTER TABLE NEWS ADD DATA_SCADENZA DATETIME;

UPDATE NEWS SET DATA_SCADENZA=STR_TO_DATE('31/12/2999', '%d/%m/%Y');

ALTER TABLE ANAGRAFE MODIFY INAIL_MATRICOLA VARCHAR(50);
ALTER TABLE ANAGRAFESTORICO MODIFY INAIL_MATRICOLA VARCHAR(50);

ALTER TABLE ANAGRAFE MODIFY INPS_MATRICOLA VARCHAR(50);
ALTER TABLE ANAGRAFESTORICO MODIFY INPS_MATRICOLA VARCHAR(50);

ALTER TABLE ANAGRAFE MODIFY CASSAEDILE_MATRICOLA VARCHAR(50);
ALTER TABLE ANAGRAFESTORICO MODIFY CASSAEDILE_MATRICOLA VARCHAR(50);


CREATE TABLE NEWS_BACKV2_20180531 AS SELECT * FROM NEWS;
ALTER TABLE NEWS ADD NEWS_CLOB LONGTEXT;
UPDATE NEWS SET NEWS_CLOB=NEWS;
ALTER TABLE NEWS DROP COLUMN NEWS;
ALTER TABLE NEWS ADD NEWS LONGTEXT;
UPDATE NEWS SET NEWS=NEWS_CLOB;
ALTER TABLE NEWS DROP COLUMN NEWS_CLOB;


CREATE TABLE INFOSUAP_BACKV2_20180531 AS SELECT * FROM INFOSUAP;
ALTER TABLE INFOSUAP ADD DESCRIZIONE_CLOB LONGTEXT;
UPDATE INFOSUAP SET DESCRIZIONE_CLOB=DESCRIZIONE;
ALTER TABLE INFOSUAP DROP COLUMN DESCRIZIONE;
ALTER TABLE INFOSUAP ADD DESCRIZIONE LONGTEXT;
UPDATE INFOSUAP SET DESCRIZIONE=DESCRIZIONE_CLOB;
ALTER TABLE INFOSUAP DROP COLUMN DESCRIZIONE_CLOB;

DELETE FROM INTERESSI_LEGALI;

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (1,STR_TO_DATE('21-04-1942','%d-%m-%Y'),STR_TO_DATE('15-12-1990','%d-%m-%Y'),5,null);

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (2,STR_TO_DATE('16-12-1990','%d-%m-%Y'),STR_TO_DATE('31-12-1996','%d-%m-%Y'),10,'Legge 26 novembre 1990, n. 353'); 

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (3,STR_TO_DATE('01-01-1997','%d-%m-%Y'),STR_TO_DATE('31-12-1998','%d-%m-%Y'),5,'Legge 23 dicembre 1996, n. 662'); 

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (4,STR_TO_DATE('01-01-1999','%d-%m-%Y'),STR_TO_DATE('31-12-2000','%d-%m-%Y'),2.5,'D.M. 10 dicembre 1998');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (5,STR_TO_DATE('01-01-2001','%d-%m-%Y'),STR_TO_DATE('31-12-2001','%d-%m-%Y'),3.5,'D.M. 11 dicembre 2000');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (6,STR_TO_DATE('01-01-2002','%d-%m-%Y'),STR_TO_DATE('31-12-2003','%d-%m-%Y'),3,'D.M. 11 dicembre 2001');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (7,STR_TO_DATE('01-01-2004','%d-%m-%Y'),STR_TO_DATE('31-12-2007','%d-%m-%Y'),2.5,'D.M. 1 dicembre 2003');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (8,STR_TO_DATE('01-01-2008','%d-%m-%Y'),STR_TO_DATE('31-12-2009','%d-%m-%Y'),3,'D.M. 12 dicembre 2007');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (9,STR_TO_DATE('01-01-2010','%d-%m-%Y'),STR_TO_DATE('31-12-2010','%d-%m-%Y'),1,'D.M. 4 dicembre 2009');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (10,STR_TO_DATE('01-01-2011','%d-%m-%Y'),STR_TO_DATE('31-12-2011','%d-%m-%Y'),1.5,'D.M. 07 Dicembre 2010');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (11,STR_TO_DATE('01-01-2012','%d-%m-%Y'),STR_TO_DATE('31-12-2013','%d-%m-%Y'),2.5,'DM 12 dicembre 2011');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (12,STR_TO_DATE('01-01-2014','%d-%m-%Y'),STR_TO_DATE('31-12-2014','%d-%m-%Y'),1,'Dm Economia 13.12.2013');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (13,STR_TO_DATE('01-01-2015','%d-%m-%Y'),STR_TO_DATE('31-12-2015','%d-%m-%Y'),0.5,'Dm Economia 11.12.2014');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (14,STR_TO_DATE('01-01-2016','%d-%m-%Y'),STR_TO_DATE('31-12-2016','%d-%m-%Y') ,0.2,'Dm Economia 11.12.2015');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (15,STR_TO_DATE('01-01-2017', '%d-%m-%Y'),STR_TO_DATE('31-12-2017', '%d-%m-%Y'),0.1,'Dm economia e finanze 07/12/2016,G.U.14/12/2016');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (16,STR_TO_DATE('01-01-2018', '%d-%m-%Y'),NULL,0.3,'Dm economia e finanze 13/12/2017,G.U.15/12/2017');

ALTER TABLE ISTANZE ADD OPERATORE_IN_CARICO NUMERIC(8,0);

ALTER TABLE ISTANZE ADD CONSTRAINT FK_ISTANZE_OPPRESAINCAR FOREIGN KEY(IDCOMUNE,OPERATORE_IN_CARICO) REFERENCES RESPONSABILI(IDCOMUNE, CODICERESPONSABILE); 
CREATE INDEX IDX_ISTANZE_RESP004 ON ISTANZE (IDCOMUNE,OPERATORE_IN_CARICO);

CREATE TABLE RT_ANAGRAFETRIB_CO (CODICE_ENDO_REGIONALE VARCHAR(20) NOT NULL, CODICE_TIPOLOGIA_ENDO DECIMAL(4,0) NOT NULL, ATRIB_TIPOLOGIAINTERVENTO VARCHAR(5) NOT NULL)  ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE RT_ANAGRAFETRIB_CO ADD CONSTRAINT RT_ANAGRAFETRIBCO_PK PRIMARY KEY (CODICE_ENDO_REGIONALE,CODICE_TIPOLOGIA_ENDO);

