
ALTER TABLE CLMENU_JAVA ADD MENULINK_V2 VARCHAR2(6);

CREATE INDEX IDX_MOVIMENTI_006 ON MOVIMENTI(IDCOMUNE, STATO_ATT_DEST, ID_ATT_DEST);

create table CATEGORIE_EVENTI_MAIL(
IDCOMUNE VARCHAR2(6) NOT NULL
,ID NUMBER(4,0) NOT NULL
,DESCRIZIONE VARCHAR2(200)
,FKIDCATEGORIAEVENTO VARCHAR2(16)
,TRIGGER_TYPE VARCHAR2(20)
,TRIGGER_TEXT VARCHAR2(50)
,CODICEMAILTIPO NUMBER(4,0)
,DESTINATARIMAIL VARCHAR2(500)
,DESTINATARIAGGIUNTIVI VARCHAR2(50)
,FLAG_ATTIVA NUMBER(1,0)
);

ALTER TABLE CATEGORIE_EVENTI_MAIL ADD CONSTRAINT PK_CATEGORIEEVENTI_MAIL PRIMARY KEY(IDCOMUNE, ID);

ALTER TABLE CATEGORIE_EVENTI_MAIL ADD CONSTRAINT FK_CATEVENTIMAIL_CATEVBASE FOREIGN KEY(FKIDCATEGORIAEVENTO) REFERENCES CATEGORIEEVENTIBASE(ID);

CREATE INDEX IDX_CATEGORIEEVENTI_MAIL_001 ON CATEGORIE_EVENTI_MAIL (IDCOMUNE, FKIDCATEGORIAEVENTO);


ALTER TABLE TIPIMOV_STC_ALTRIDATI ADD flag_help number(1,0) default 0;
ALTER TABLE TIPIMOV_STC_ALTRIDATI MODIFY HELP_TEXT VARCHAR2(4000) ;

ALTER TABLE TIPIMOVIMENTO ADD (FLAG_PUBBL_SCHEDE NUMBER(1,0));