<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<RootNamespace>Init.SIGePro.Manager.Authentication</RootNamespace>
		<Configurations>Debug;Release;ReleaseFramework</Configurations>
		<Platforms>AnyCPU</Platforms>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<LangVersion>9.0</LangVersion>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Init.Utils\Init.Utils.csproj" />
		<ProjectReference Include="..\PersonalLib2\PersonalLib2.csproj" />
		<ProjectReference Include="..\VBG.Shared.Infrastructure\VBG.Shared.Infrastructure.csproj" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="System.ServiceModel.Http" Version="10.0.652802" />
	</ItemGroup>


	<!--<ItemGroup Condition=" '$(TargetFramework)' == 'net48' ">
		<Reference Include="System.Web" />
		<Reference Include="System.ServiceModel" />
		<PackageReference Include="Ninject.Web.Common" Version="3.3.2" />
	</ItemGroup>-->

</Project>
