//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Init.Sigepro.FrontEnd.Reserved.InserimentoIstanza {
    
    
    public partial class GestioneLocalizzazioni {
        
        /// <summary>
        /// multiView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.MultiView multiView;
        
        /// <summary>
        /// listaView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.View listaView;
        
        /// <summary>
        /// dgStradario control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView dgStradario;
        
        /// <summary>
        /// cmdAddNew control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button cmdAddNew;
        
        /// <summary>
        /// dettaglioView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.View dettaglioView;
        
        /// <summary>
        /// dgIndirizzi control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView dgIndirizzi;
        
        /// <summary>
        /// ddlComuneLocalizzazione control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.DropDownList ddlComuneLocalizzazione;
        
        /// <summary>
        /// HiddenIdLocalizzazione control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField HiddenIdLocalizzazione;
        
        /// <summary>
        /// HiddenCodiceCivico control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField HiddenCodiceCivico;
        
        /// <summary>
        /// HiddenCodiceViario control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField HiddenCodiceViario;
        
        /// <summary>
        /// acIndirizzo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.Autocomplete acIndirizzo;
        
        /// <summary>
        /// txtCivico control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.TextBox txtCivico;
        
        /// <summary>
        /// txtEsponente control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.TextBox txtEsponente;
        
        /// <summary>
        /// ddlColore control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.DropDownList ddlColore;
        
        /// <summary>
        /// txtScala control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.TextBox txtScala;
        
        /// <summary>
        /// txtPiano control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.TextBox txtPiano;
        
        /// <summary>
        /// txtInterno control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.TextBox txtInterno;
        
        /// <summary>
        /// txtEsponenteInterno control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.TextBox txtEsponenteInterno;
        
        /// <summary>
        /// txtFabbricato control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.TextBox txtFabbricato;
        
        /// <summary>
        /// txtKm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.TextBox txtKm;
        
        /// <summary>
        /// txtNote control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.TextBox txtNote;
        
        /// <summary>
        /// ltrTitoloBloccoCoordinate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltrTitoloBloccoCoordinate;
        
        /// <summary>
        /// txtLongitudine control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.TextBox txtLongitudine;
        
        /// <summary>
        /// txtLatitudine control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.TextBox txtLatitudine;
        
        /// <summary>
        /// ddlTipoCatasto control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.DropDownList ddlTipoCatasto;
        
        /// <summary>
        /// txtSezione control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField txtSezione;
        
        /// <summary>
        /// txtFoglio control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.TextBox txtFoglio;
        
        /// <summary>
        /// txtParticella control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.TextBox txtParticella;
        
        /// <summary>
        /// txtSub control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.TextBox txtSub;
        
        /// <summary>
        /// txtAccessoTipo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField txtAccessoTipo;
        
        /// <summary>
        /// txtAccessoNumero control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField txtAccessoNumero;
        
        /// <summary>
        /// txtAccessoDescrizione control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField txtAccessoDescrizione;
        
        /// <summary>
        /// cmdConfirm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button cmdConfirm;
        
        /// <summary>
        /// cmdCancel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton cmdCancel;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new Init.Sigepro.FrontEnd.Reserved.InserimentoIstanza.InserimentoIstanzaMaster Master {
            get {
                return ((Init.Sigepro.FrontEnd.Reserved.InserimentoIstanza.InserimentoIstanzaMaster)(base.Master));
            }
        }
    }
}
