ALTER TABLE MERCATIPRESENZE_D ADD FK_CODGERENTE_CONC NUMBER(6,0); 
ALTER TABLE MERCATIPRESENZE_D ADD CONSTRAINT FK_MPD_ANAG_GER_CONC FOREIGN KEY (IDCOMUNE,FK_CODGERENTE_CONC) REFERENCES ANAGRAFE(IDCOMUNE,CODICEANAGRAFE);


ALTER TABLE MERCATIPRESENZE_D ADD FK_CODGERENTE_SPUNT NUMBER(6,0); 
ALTER TABLE MERCATIPRESENZE_D ADD CONSTRAINT FK_MPD_ANAG_GER_SPUNT FOREIGN KEY (IDCOMUNE,FK_CODGERENTE_SPUNT) REFERENCES ANAGRAFE(IDCOMUNE,CODICEANAGRAFE);

ALTER TABLE TIPOLOGIAREGISTRI ADD NUMERO_PROROGHE NUMBER(4,0);
ALTER TABLE TIPOLOGIAREGISTRI ADD NUMERO_RINNOVI NUMBER(4,0);
ALTER TABLE TIPOLOGIAREGISTRI ADD NUMERO_PREAVVISI NUMBER(4,0);
ALTER TABLE TIPOLOGIAREGISTRI ADD DURATA_AUTORIZZAZIONE VARCHAR2(25);

ALTER TABLE AUTORIZZAZIONI ADD NUM_PROROGHE_RIMASTE NUMBER(4,0);
ALTER TABLE AUTORIZZAZIONI ADD NUM_PREAVVISI_RIMASTI NUMBER(4,0);
ALTER TABLE AUTORIZZAZIONI ADD NUM_RINNOVI_RIMASTI NUMBER(4,0);

ALTER TABLE TIPIMOVIMENTO ADD FLAG_AUTORIZ_PROROGA NUMBER(1,0);
ALTER TABLE TIPIMOVIMENTO ADD FLAG_AUTORIZ_PREAVV NUMBER(1,0);
ALTER TABLE TIPIMOVIMENTO ADD FLAG_AUTORIZ_RINNOVO NUMBER(1,0);
ALTER TABLE TIPIMOVIMENTO ADD FLAG_AUTORIZ_MODIFICA NUMBER(1,0);

alter table AUTORIZZAZIONI modify AUTORIG_NUMERO varchar2(60);