ALTER TABLE PROTOCOLLO_MEZZI MODIFY (ID NUMBER(10) NOT NULL);
ALTER TABLE PROTOCOLLO_MEZZI DROP PRIMARY KEY DROP INDEX;
ALTER TABLE PROTOCOLLO_MEZZI ADD CONSTRAINT PROTOCOLLO_MEZZI_PK PRIMARY KEY (IDCOMUNE , ID);

ALTER TABLE PROTOCOLLO_MODALITAINVIO MODIFY (ID NUMBER(10) NOT NULL);
ALTER TABLE PROTOCOLLO_MODALITAINVIO DROP PRIMARY KEY DROP INDEX;
ALTER TABLE PROTOCOLLO_MODALITAINVIO ADD CONSTRAINT PK_PROTOCOLLO_MODALITAINVIO PRIMARY KEY (IDCOMUNE, ID);

ALTER TABLE PROTOCOLLO_SEQUENZE MODIFY (ID NUMBER(10) NOT NULL);
ALTER TABLE PROTOCOLLO_SEQUENZE DROP PRIMARY KEY DROP INDEX;
ALTER TABLE PROTOCOLLO_SEQUENZE ADD CONSTRAINT PROTOCOLLO_SEQUENZE_PK PRIMARY KEY (IDCOMUNE, ID);

ALTER TABLE PROTOCOLLO_SMISTAMENTI MODIFY (ID NUMBER(10) NOT NULL);
ALTER TABLE PROTOCOLLO_SMISTAMENTI DROP PRIMARY KEY DROP INDEX;
ALTER TABLE PROTOCOLLO_SMISTAMENTI ADD CONSTRAINT PROTOCOLLO_SMISTAMENTI_PK PRIMARY KEY (IDCOMUNE, ID);

ALTER TABLE TIPIMOV_STC_MAPPING DROP CONSTRAINT FK_TIPIMOV_STC_MAP_TIPI_DOC;
ALTER TABLE PROTOCOLLO_TIPIDOCUMENTO MODIFY (ID NUMBER(10) NOT NULL);
ALTER TABLE PROTOCOLLO_TIPIDOCUMENTO DROP PRIMARY KEY DROP INDEX;
ALTER TABLE PROTOCOLLO_TIPIDOCUMENTO ADD CONSTRAINT PROTOCOLLO_TIPIDOCUMENTO_PK PRIMARY KEY (IDCOMUNE, ID);

ALTER TABLE PROTOCOLLO_UFFICIREGISTRI MODIFY (ID NUMBER(10) NOT NULL);
ALTER TABLE PROTOCOLLO_UFFICIREGISTRI DROP PRIMARY KEY DROP INDEX;
ALTER TABLE PROTOCOLLO_UFFICIREGISTRI ADD CONSTRAINT PROTOCOLLO_UFFICIREGISTRI_PK PRIMARY KEY (CODICEREGISTRO, ID);
