ALTER TABLE VERTICALIZZAZIONIBASE ADD FLAG_GESTCOMUNE NUMBER(1, 0);
ALTER TABLE VERTICALIZZAZIONI ADD CODICECOMUNE VARCHAR2(5 CHAR);

ALTER TABLE VERTICALIZZAZIONI ADD CONSTRAINT FK_VERT_COMUNI FOREIGN KEY(CODICECOMUNE) REFERENCES COMUNI (CODICECOMUNE); 
ALTER TABLE VERTICALIZZAZIONIPARAMETRI ADD CODICECOMUNE VARCHAR2(5 CHAR);

ALTER TABLE VERTICALIZZAZIONIPARAMETRI ADD CONSTRAINT FK_VERT_PARAM_COMUNI FOREIGN KEY(CODICECOMUNE) REFERENCES COMUNI (CODICECOMUNE);


ALTER TABLE VERTICALIZZAZIONI ADD ID NUMBER(6,0);
ALTER TABLE VERTICALIZZAZIONIPARAMETRI ADD ID NUMBER(6,0);