ALTER TABLE PROTOCOLLO_MEZZI ADD (ID NUMBER(10) );
ALTER TABLE PROTOCOLLO_MODALITAINVIO ADD (ID NUMBER(10) );
ALTER TABLE PROTOCOLLO_SEQUENZE ADD (ID NUMBER(10) );
ALTER TABLE PROTOCOLLO_SMISTAMENTI ADD (ID NUMBER(10) );
ALTER TABLE PROTOCOLLO_TIPIDOCUMENTO ADD (ID NUMBER(10) );
ALTER TABLE PROTOCOLLO_UFFICIREGISTRI ADD (ID NUMBER(10) );