ALTER TABLE PAY_REGISTRAZIONI_CAUSALI MODIFY (DESCRIZIONE VARCHAR2(200 CHAR) );
ALTER TABLE PAY_REGISTRAZIONI_CAUSALI MODIFY (CODICE_VERSAMENTO VARCHAR2(200 CHAR) );
ALTER TABLE CONTI MODIFY CODICESOTTOCONTO VARCHAR2(30 CHAR);

CREATE TABLE DYN2_METADATI_CONTESTI(
IDCOMUNE VARCHAR2(6 CHAR) NOT NULL, 
ID NUMBER(6,0) NOT NULL,
CONTESTO  VARCHAR2(255 CHAR) NOT NULL, 
DESCRIZIONE VARCHAR2(4000 CHAR));

ALTER TABLE DYN2_METADATI_CONTESTI ADD CONSTRAINT PK_DYN2_METADATI_CONTESTI PRIMARY KEY(IDCOMUNE,ID);
CREATE INDEX IDX_DYN2METADATICONTESTI ON DYN2_METADATI_CONTESTI(IDCOMUNE,CONTESTO); 

CREATE TABLE DYN2_METADATI(
IDCOMUNE VARCHAR2(6 CHAR) NOT NULL, 
ID NUMBER(6,0) NOT NULL,
FK_CONTESTO_ID  NUMBER(6,0), 
FK_CAMPODINAMICO_ID NUMBER(10,0),
CONTESTO_CAMPO VARCHAR2(255 CHAR));

ALTER TABLE DYN2_METADATI ADD CONSTRAINT PK_DYN2_METADATI PRIMARY KEY(IDCOMUNE,ID);
ALTER TABLE DYN2_METADATI ADD CONSTRAINT FK_DYN2_METADATI_CONTESTO FOREIGN KEY(IDCOMUNE,FK_CONTESTO_ID) REFERENCES DYN2_METADATI_CONTESTI(IDCOMUNE,ID);
ALTER TABLE DYN2_METADATI ADD CONSTRAINT FK_DYN2_CAMPI FOREIGN KEY(IDCOMUNE,FK_CAMPODINAMICO_ID) REFERENCES DYN2_CAMPI(IDCOMUNE,ID);

ALTER TABLE dyn2_metadati_contesti ADD CONSTRAINT uc_dyn2metadaticontesti UNIQUE(idcomune,contesto);

ALTER TABLE dyn2_metadati ADD CONSTRAINT uc_dyn2metadati UNIQUE(idcomune, fk_contesto_id, contesto_campo);
