CREATE INDEX IDX_LAYOUTTESTI_001 ON LAYOUTTESTI (IDCOMUNE, CODICETESTO);
CREATE INDEX IDX_LAYOUTTESTIBASE_001 ON LAYOUTTESTIBASE (CODICETESTO);

CREATE TABLE MASTERKEY (TABLENAME VARCHAR(40) NOT NULL, COLUMNNAME VARCHAR(40) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE MASTERKEY ADD CONSTRAINT MASTERKEY_PK PRIMARY KEY (TABLENAME ,COLUMNNAME);

Alter table LETTERETIPO modify CODICELETTERA numeric(10);
Alter table TIPIDOCUMENTO modify CODLETTERATIPO numeric(10);
Alter table TIPIMOVIMENTO modify FK_LETTERETIPO numeric(10);
Alter table TIPIMOVIMENTODOCTIPO modify CODICELETTERA numeric(10);
Alter table TIPIPROCEDURE modify CODLETTAUORIZZATIVA numeric(10);
Alter table TIPICAUSALIONERI modify CO_ID numeric(10);
Alter table INVENTARIOPROCEDIMENTIONERI modify FK_COID numeric(10);
Alter table ISTANZELAVORI_D modify FK_COID numeric(10);
Alter table LAVORITIPI_CAUSALIONERI modify FK_COID numeric(10);
Alter table ISTANZEONERI modify FKIDTIPOCAUSALE numeric(10);
Alter table O_CONFIGURAZIONETIPIONERE modify FK_CO_ID numeric(10);
Alter table ALBEROPROC_ONERI modify AO_FK_COID numeric(10);
Alter table TIPISOGGETTO modify CODICETIPOSOGGETTO numeric(10,0);
Alter table ISTANZE modify FKCODICESOGGETTO numeric(10,0);
Alter table ISTANZERICHIEDENTI modify CODICETIPOSOGGETTO numeric(10,0);
Alter table TIPIMOVIMENTOONERI modify FK_COID numeric(10);

ALTER TABLE ISTANZEONERI ADD CONSTRAINT FK_ISTANZEONERI_TIPICAUSALI FOREIGN KEY (IDCOMUNE, FKIDTIPOCAUSALE) REFERENCES TIPICAUSALIONERI (IDCOMUNE, CO_ID);
ALTER TABLE O_CONFIGURAZIONETIPIONERE ADD CONSTRAINT FK_O_CONFTIPIONERE_TIPICAUSALI FOREIGN KEY (IDCOMUNE, FK_CO_ID )REFERENCES TIPICAUSALIONERI(  IDCOMUNE , CO_ID );
ALTER TABLE ALBEROPROC_ONERI ADD CONSTRAINT FK_ALBEROPROCONERI_TIPICAUSALI FOREIGN KEY (IDCOMUNE, AO_FK_COID )REFERENCES TIPICAUSALIONERI(  IDCOMUNE , CO_ID );
ALTER TABLE TIPIMOVIMENTOONERI ADD CONSTRAINT FK_TIPIMOVONERI_TIPICAUSALI FOREIGN KEY (IDCOMUNE, FK_COID )REFERENCES TIPICAUSALIONERI(  IDCOMUNE , CO_ID );
CREATE TABLE SEGNAPOSTO
  (
    ID          NUMERIC(4,0) NOT NULL,
    TAG         VARCHAR(64) NOT NULL,
    DESCRIZIONE VARCHAR(64) NOT NULL,
    HELP        VARCHAR(4000)
  )  ENGINE=INNODB DEFAULT CHARSET=UTF8;
ALTER TABLE SEGNAPOSTO ADD CONSTRAINT SEGNAPOSTO_PK PRIMARY KEY (ID);
CREATE UNIQUE INDEX SEGNAPOSTO_IDX_001 ON SEGNAPOSTO(TAG);

ALTER TABLE DYN2_CAMPI_SCRIPT MODIFY COLUMN FK_D2C_ID NUMERIC(10);
ALTER TABLE DYN2_MODELLI_SCRIPT MODIFY COLUMN FK_D2MT_ID NUMERIC(10);        
CREATE OR REPLACE ALGORITHM=TEMPTABLE View VW_MERCATIPRESENZETOTALI as SELECT 'STORICO' AS ORIGINE, IDCOMUNE, ANNO, CODICEANAGRAFE, FK_AUTORIZZAZIONI_ID, FKCODICEMERCATO, FKIDMERCATIUSO, FK_IDPOSTEGGIO AS FKIDPOSTEGGIO, NUMEROPRESENZE FROM MERCATIPRESENZE_STORICO UNION SELECT 'CALENDARIO' AS ORIGINE, MERCATIPRESENZE_T.IDCOMUNE, MERCATIPRESENZE_T.ANNO, MERCATIPRESENZE_D.CODICEANAGRAFE, MERCATIPRESENZE_D.FK_AUTORIZZAZIONI_ID, MERCATIPRESENZE_T.FKCODICEMERCATO, MERCATIPRESENZE_T.FKIDMERCATIUSO, MERCATIPRESENZE_D.FKIDPOSTEGGIO, 1 as NUMEROPRESENZE FROM MERCATIPRESENZE_D, MERCATIPRESENZE_T WHERE MERCATIPRESENZE_D.IDCOMUNE = MERCATIPRESENZE_T.IDCOMUNE AND MERCATIPRESENZE_D.FKIDTESTATA = MERCATIPRESENZE_T.ID AND MERCATIPRESENZE_D.CODICEANAGRAFE IS NOT NULL;
ALTER TABLE BATCH_SCAD_ISTANZE drop FOREIGN KEY FK_BATCHSCADISTANZE_ISTANZE;
ALTER TABLE MESSAGGICFGBASE MODIFY CORPO varchar(4000) NULL;
ALTER TABLE MESSAGGICFG MODIFY CORPO  varchar(4000) NULL;
ALTER TABLE INVENTARIOPROCDYN2MODELLIT ADD FOREIGN KEY FK_INV_DYN2MODT_DYN2MODELLIT (IDCOMUNE, FK_D2MT_ID) REFERENCES DYN2_MODELLIT (IDCOMUNE, ID);

ALTER TABLE DYN2_CAMPIPROPRIETA ADD FOREIGN KEY FK_DYN2_CAMPIPROP_DYN2CAMPI (IDCOMUNE, FK_D2C_ID) REFERENCES DYN2_CAMPI (IDCOMUNE, ID);
ALTER TABLE DYN2_CAMPI_SCRIPT ADD FOREIGN KEY FK_DYN2CAMPISCRIPT_DYN2CAMPI (IDCOMUNE, FK_D2C_ID) REFERENCES DYN2_CAMPI (IDCOMUNE, ID);
ALTER TABLE DYN2_MODELLI_SCRIPT ADD FOREIGN KEY FK_DYN2MOSCRIPT_DYN2MODELLIT (IDCOMUNE, FK_D2MT_ID) REFERENCES DYN2_MODELLIT (IDCOMUNE, ID);
ALTER TABLE TIPISOGGETTO ADD ORDINE NUMERIC(2,0);
ALTER TABLE FORMEGIURIDICHE MODIFY FORMAGIURIDICA VARCHAR(60);
ALTER TABLE F_DOMANDE ADD DM_NUM_PROT NUMERIC(7,0) ;
ALTER TABLE F_DOMANDE ADD DM_DATA_PROT VARCHAR(8) ;
ALTER TABLE ALBEROPROC MODIFY SC_PROTTIPODOCUMENTO VARCHAR(50);
ALTER TABLE CLMENU_JAVA ADD TIPO_FUNZIONALITA VARCHAR(1);

ALTER TABLE FO_DOMANDE ADD IDENTIFICATIVODOMANDA VARCHAR(50);
SELECT 'ATTENZIONE: Se si dovessero verificare errori durante la attivazione della chiave FK_DOMANDE_ANAGRAFE utilizzare il seguente script per bonificare i records ATTENZIONEATTENZIONE: lo script non elimina gli oggetti referenziati in fo_domande_oggetti,  eseguire questo passaggio a parte o lasciare gli oggetti nel db (potrebbero essere in uso in qualche istanza). Controllare il file WARNING1.TXT' from NONESISTE;
ALTER TABLE FO_DOMANDE ADD CONSTRAINT FK_DOMANDE_ANAGRAFE FOREIGN KEY (IDCOMUNE, CODICEANAGRAFE) REFERENCES ANAGRAFE (IDCOMUNE, CODICEANAGRAFE);
SELECT 'ATTENZIONE Se si dovessero verificare errori durante la attivazione della chiave FK_DOMANDE_OGGETTI_DOMPADRE utilizzare il seguente script per bonificare i records ATTENZIONE lo script non elimina gli oggetti referenziati in fo_domande_oggetti,  eseguire questo passaggio a parte o lasciare gli oggetti nel db (potrebbero essere in uso in qualche istanza). Controllare il file WARNING2.TXT'  from NONESISTE;

ALTER TABLE FO_DOMANDE_OGGETTI ADD CONSTRAINT FK_DOMANDE_OGGETTI_DOMPADRE FOREIGN KEY (IDCOMUNE, IDDOMANDA) REFERENCES FO_DOMANDE (IDCOMUNE, ID);
ALTER TABLE FO_SOTTOSCRIZIONI ADD CONSTRAINT FO_SOTTOSCRIZIONI_DOMPADRE FOREIGN KEY (IDCOMUNE, CODICEDOMANDA) REFERENCES FO_DOMANDE (IDCOMUNE, ID);
ALTER TABLE FO_MESSAGGI ADD CONSTRAINT FO_MESSAGGI_DOMPADRE FOREIGN KEY (IDCOMUNE, CODICEDOMANDA) REFERENCES FO_DOMANDE (IDCOMUNE, ID);

ALTER TABLE MOVIMENTIMAIL ADD MESSAGE_ID VARCHAR(400);
ALTER TABLE MOVIMENTIMAIL ADD ID_PADRE NUMERIC(8,0);
ALTER TABLE MOVIMENTIMAIL ADD CONSTRAINT FK_IDPADRE_ID FOREIGN KEY(IDCOMUNE,ID_PADRE) REFERENCES MOVIMENTIMAIL(IDCOMUNE,ID);
ALTER TABLE MOVIMENTIMAIL MODIFY MITTENTE VARCHAR(200);
ALTER TABLE ISTANZESTRADARIO ADD CONSTRAINT FK_ISTANZESTRADARIO_COLORE FOREIGN KEY (IDCOMUNE, COLORE) REFERENCES STRADARIOCOLORE (IDCOMUNE, CODICECOLORE);
ALTER TABLE ISTANZESTRADARIO ADD PIANO VARCHAR(50);
ALTER TABLE ISTANZESTRADARIO ADD QUARTIERE VARCHAR(50);
ALTER TABLE RAGGRUPPAMENTOCAUSALIONERI MODIFY RCO_ID NUMERIC(10,0);
ALTER TABLE TIPICAUSALIONERI MODIFY FK_RCO_ID NUMERIC(10,0);
ALTER TABLE FO_DOMANDE ADD CONSTRAINT FK_FO_DOMANDE_SOFTWARE FOREIGN KEY (SOFTWARE) REFERENCES SOFTWARE (CODICE);
ALTER TABLE FO_MESSAGGI ADD CONSTRAINT FK_FO_MESSAGGI_SOFTWARE FOREIGN KEY (SOFTWARE) REFERENCES SOFTWARE (CODICE);
alter table ISTANZEPROCEDIMENTI add TIPO_ATTO varchar(100);
alter table ISTANZEPROCEDIMENTI add RILASCIATO_DA varchar(100);
CREATE INDEX IDX_ISTANZECOLLEGATE_002 ON ISTANZECOLLEGATE (IDCOMUNE,CODICEISTANZA);
CREATE INDEX IDX_ISTANZECOLLEGATE_003 ON ISTANZECOLLEGATE (IDCOMUNE,CODICEISTANZACOLLEGATA) ;
CREATE OR REPLACE ALGORITHM=TEMPTABLE VIEW VW_FULL_ISTANZECOLLEGATE (IDCOMUNE, PROGRESSIVO, CODICEISTANZA, ORDINE) AS SELECT IDCOMUNE, PROGRESSIVO, CODICEISTANZA, ORDINE FROM ISTANZECOLLEGATE GROUP BY IDCOMUNE, PROGRESSIVO, CODICEISTANZA, ORDINE UNION SELECT IDCOMUNE, PROGRESSIVO, CODICEISTANZACOLLEGATA, ORDINE FROM ISTANZECOLLEGATE GROUP BY IDCOMUNE, PROGRESSIVO, CODICEISTANZACOLLEGATA, ORDINE;

ALTER TABLE ALLEGATI ADD FLAG_INSERIMENTO_AUT NUMERIC(1,0);
ALTER TABLE ALBEROPROC_DOCUMENTI ADD FLAG_INSERIMENTO_AUT NUMERIC(1,0);

CREATE INDEX IDX_DOMANDESTC_001 ON DOMANDESTC (IDCOMUNE,CODICESOFTWARE,NUMEROISTANZA);
alter table NATURAENDO modify BINARIODIPENDENZE numeric(10);

DROP INDEX DYN2_MODELLIT_UK1 on DYN2_MODELLIT;
CREATE INDEX DYN2_MODELLIT_UK1 ON DYN2_MODELLIT (IDCOMUNE, SOFTWARE, CODICE_SCHEDA);

CREATE TABLE TIPIPROCEDURE_DYN2MODELLIT (IDCOMUNE VARCHAR(6) NOT NULL,FK_CODICEPROCEDURA NUMERIC(10,0) NOT NULL,FK_D2MT_ID NUMERIC(10,0) NOT NULL,FLAG_PUBBLICA NUMERIC(1,0) NULL,FLAG_TIPOFIRMA NUMERIC(1,0) NULL,FLAG_FACOLTATIVA NUMERIC(1,0) NULL) ENGINE=INNODB DEFAULT CHARSET=UTF8;
ALTER TABLE TIPIPROCEDURE_DYN2MODELLIT ADD CONSTRAINT TIPIPROCEDURE_DYN2MODELLIT_PK PRIMARY KEY ( IDCOMUNE, FK_CODICEPROCEDURA, FK_D2MT_ID );
ALTER TABLE TIPIPROCEDURE_DYN2MODELLIT ADD CONSTRAINT FK_TPD2MT_TPROC FOREIGN KEY ( IDCOMUNE, FK_CODICEPROCEDURA ) REFERENCES TIPIPROCEDURE ( IDCOMUNE, CODICEPROCEDURA );
ALTER TABLE TIPIPROCEDURE_DYN2MODELLIT ADD CONSTRAINT FK_TPD2MT_D2MT FOREIGN KEY ( IDCOMUNE, FK_D2MT_ID ) REFERENCES DYN2_MODELLIT ( IDCOMUNE, ID );

CREATE OR REPLACE ALGORITHM=TEMPTABLE VIEW VW_ISTANZECONCESSIONILISTA as SELECT 99999999 as PROGRESSIVO,AUTORIZZAZIONI.AUTORIZRESPONSABILE as CONC_AUTORIZRESPONSABILE,AUTORIZZAZIONI.IDCOMUNE,AUTORIZZAZIONI.FK_CAUSALE_ACQUISIZIONE as ICONC_CODICECAUSALE,ifnull(AUTORIZZAZIONI.DATA_CESSAZIONE,STR_TO_DATE('31/12/9999','%d/%m/%Y')) as DATA_STORICO,ISTANZE.SOFTWARE,ISTANZE.CODICEISTANZA as IST_CODICEISTANZA,ISTANZE.NUMEROISTANZA as IST_NUMEROISTANZA,ISTANZE.CODICERICHIEDENTE as IST_CODICERICHIEDENTE,AUTORIZZAZIONI.ID as CONC_ID,AUTORIZZAZIONI.AUTORIZNUMERO as CONC_NUMERO,AUTORIZZAZIONI.AUTORIZDATA as CONC_DATARILASCIO,AUTORIZZAZIONI.AUTORIZDATA as DATARILASCIO,AUTORIZZAZIONI.DATASCADENZA as CONC_DATASCADENZA,AUTORIZZAZIONI_CONCESSIONI.FK_TIPOCONCESSIONE as CONC_CODICETIPO,CONCESSIONITIPI.DESCRIZIONE as CONC_TIPO,AUTORIZZAZIONI_CONCESSIONI.STAGIONALEA as CONC_STAGIONALEA,AUTORIZZAZIONI_CONCESSIONI.STAGIONALEDA as CONC_STAGIONALEDA,AUTORIZZAZIONI.FLAG_ATTIVA as CONC_ATTIVA,AUTORIZZAZIONI.FK_CODICEANAGRAFE as CONC_CODICETITOLARE,CONCAT_WS('',TITOLARE.NOMINATIVO,' ',TITOLARE.NOME) as CONC_TITOLARE,TITOLARE.CODICEFISCALE as CONC_TIT_CF,TITOLARE.PARTITAIVA as CONC_TIT_PIVA,TITOLARE.TIPOANAGRAFE as CONC_TIT_TIPOANAGRAFE,AUT_COLLEGATA.AUTORIZNUMERO as AUT_NUMERO,AUT_COLLEGATA.AUTORIZDATA as AUT_DATA,AUT_COLLEGATA.AUTORIZDATA,AUT_COLLEGATA.FKIDREGISTRO as AUT_CODREGISTRO,TIPOLOGIAREGISTRI.TR_DESCRIZIONE as AUT_REGISTRO,CONCAT_WS('',IST_RICHIEDENTE.NOMINATIVO,' ',IST_RICHIEDENTE.NOME) as IST_NOMINATIVO,IST_RICHIEDENTE.TIPOANAGRAFE as IST_RIC_TIPOANAGRAFE,CONCAT_WS('',IST_AZIENDA.NOMINATIVO,' ',IST_AZIENDA.NOME) as IST_NOMINATIVOAZIENDA,IST_AZIENDA.TIPOANAGRAFE as IST_AZI_TIPOANAGRAFE,IST_RICHIEDENTE.CODICEFISCALE as IST_CODICEFISCALE,IST_RICHIEDENTE.PARTITAIVA as IST_PARTITAIVA,CAUS_ATTUALE.DESCRIZIONE as ICONC_CAUSALE,AUTORIZZAZIONI.FK_CAUSALE_CESSAZIONE as ICONC_CODICECAUSALESTORICO,CAUS_STORICO.DESCRIZIONE as ICONC_CAUSALESTORICO,AUTORIZZAZIONI_CONCESSIONI.FK_CODICEMERCATO as CONC_IDMERCATO,MERCATI.DESCRIZIONE as CONC_MERCATO,MERCATI.ATTIVO as MERC_ATTIVO,AUTORIZZAZIONI_CONCESSIONI.FK_IDPOSTEGGIO as CONC_IDPOSTEGGIO,MERCATI_D.CODICEPOSTEGGIO as CONC_POSTEGGIO,MERCATI_D.LARGHEZZA as CONC_POS_LARGHEZZA,MERCATI_D.LUNGHEZZA as CONC_POS_LUNGHEZZA,MERCATI_D.SUPERFICIE as CONC_POS_SUPERFICIE,MERCATI_D.FKCODICETIPOSPAZIO as POST_IDTIPOSPAZIO,POSTEGGITIPOSPAZIO.TIPOSPAZIO as POST_TIPOSPAZIO,AUTORIZZAZIONI_CONCESSIONI.FK_IDMERCATIUSO as CONC_IDMERCATIUSO,MERCATI_USO.DESCRIZIONE as CONC_DESCRIZIONEUSO,MERCATI_USO.PESO as PESO_MERCATO,MERCATI_USO.FKCODICEUSO as MERC_IDUSO,MERCATI_D.FKCODICESTRADARIO as CONC_POS_CODICESTRADARIO FROM AUTORIZZAZIONI_CONCESSIONI LEFT OUTER JOIN AUTORIZZAZIONI AUT_COLLEGATA ON AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE=AUT_COLLEGATA.IDCOMUNE  AND AUTORIZZAZIONI_CONCESSIONI.FK_IDAUT_COLLEGATA=AUT_COLLEGATA.ID,AUTORIZZAZIONI LEFT OUTER JOIN TIPOLOGIAREGISTRI ON AUTORIZZAZIONI.IDCOMUNE=TIPOLOGIAREGISTRI.IDCOMUNE  AND AUTORIZZAZIONI.FKIDREGISTRO=TIPOLOGIAREGISTRI.TR_ID  LEFT OUTER JOIN CONCESSIONICAUSALI CAUS_STORICO ON AUTORIZZAZIONI.IDCOMUNE=CAUS_STORICO.IDCOMUNE  AND AUTORIZZAZIONI.FK_CAUSALE_CESSAZIONE=CAUS_STORICO.CODICECAUSALE,MERCATI_D LEFT OUTER JOIN POSTEGGITIPOSPAZIO ON MERCATI_D.IDCOMUNE=POSTEGGITIPOSPAZIO.IDCOMUNE  AND MERCATI_D.FKCODICETIPOSPAZIO=POSTEGGITIPOSPAZIO.CODICE,ISTANZE LEFT OUTER JOIN ANAGRAFE IST_AZIENDA ON ISTANZE.IDCOMUNE=IST_AZIENDA.IDCOMUNE  AND ISTANZE.CODICETITOLARELEGALE=IST_AZIENDA.CODICEANAGRAFE,CONCESSIONITIPI,ANAGRAFE TITOLARE,CONCESSIONICAUSALI CAUS_ATTUALE,ANAGRAFE IST_RICHIEDENTE,MERCATI,MERCATI_USO WHERE AUTORIZZAZIONI.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND AUTORIZZAZIONI.ID = AUTORIZZAZIONI_CONCESSIONI.FK_IDAUT_ATTUALE AND CONCESSIONITIPI.TIPOCONCESSIONE = AUTORIZZAZIONI_CONCESSIONI.FK_TIPOCONCESSIONE AND TITOLARE.IDCOMUNE = AUTORIZZAZIONI.IDCOMUNE AND TITOLARE.CODICEANAGRAFE = AUTORIZZAZIONI.FK_CODICEANAGRAFE AND CAUS_ATTUALE.IDCOMUNE = AUTORIZZAZIONI.IDCOMUNE AND CAUS_ATTUALE.CODICECAUSALE = AUTORIZZAZIONI.FK_CAUSALE_ACQUISIZIONE AND ISTANZE.IDCOMUNE = AUTORIZZAZIONI.IDCOMUNE AND ISTANZE.CODICEISTANZA = AUTORIZZAZIONI.FKIDISTANZA AND IST_RICHIEDENTE.IDCOMUNE = ISTANZE.IDCOMUNE AND IST_RICHIEDENTE.CODICEANAGRAFE = ISTANZE.CODICERICHIEDENTE AND MERCATI.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND MERCATI.CODICEMERCATO = AUTORIZZAZIONI_CONCESSIONI.FK_CODICEMERCATO AND MERCATI_D.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND MERCATI_D.IDPOSTEGGIO = AUTORIZZAZIONI_CONCESSIONI.FK_IDPOSTEGGIO AND MERCATI_USO.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND MERCATI_USO.ID = AUTORIZZAZIONI_CONCESSIONI.FK_IDMERCATIUSO UNION SELECT AUTORIZZAZIONI_SUBENTRI.ID as PROGRESSIVO,AUTORIZZAZIONI_SUBENTRI.AUTORIZRESPONSABILE as CONC_AUTORIZRESPONSABILE,AUTORIZZAZIONI_SUBENTRI.IDCOMUNE,AUTORIZZAZIONI_SUBENTRI.FK_CAUSALE_ACQUISIZIONE as ICONC_CODICECAUSALE,AUTORIZZAZIONI_SUBENTRI.DATA_CESSAZIONE as DATA_STORICO,ISTANZE.SOFTWARE,ISTANZE.CODICEISTANZA as IST_CODICEISTANZA,ISTANZE.NUMEROISTANZA as IST_NUMEROISTANZA,ISTANZE.CODICERICHIEDENTE as IST_CODICERICHIEDENTE,AUTORIZZAZIONI_SUBENTRI.FK_IDAUT_ATTUALE as CONC_ID,AUTORIZZAZIONI_SUBENTRI.AUTORIZNUMERO as CONC_NUMERO,AUTORIZZAZIONI_SUBENTRI.AUTORIZDATA as CONC_DATARILASCIO,AUTORIZZAZIONI_SUBENTRI.AUTORIZDATA as DATARILASCIO,AUTORIZZAZIONI_SUBENTRI.DATASCADENZA as CONC_DATASCADENZA,AUTORIZZAZIONI_CONCESSIONI.FK_TIPOCONCESSIONE as CONC_CODICETIPO,CONCESSIONITIPI.DESCRIZIONE as CONC_TIPO,AUTORIZZAZIONI_CONCESSIONI.STAGIONALEA as CONC_STAGIONALEA,AUTORIZZAZIONI_CONCESSIONI.STAGIONALEDA as CONC_STAGIONALEDA,0 as CONC_ATTIVA,AUTORIZZAZIONI_SUBENTRI.FK_CODICEANAGRAFE as CONC_CODICETITOLARE,CONCAT_WS('',TITOLARE.NOMINATIVO,' ',TITOLARE.NOME) as CONC_TITOLARE,TITOLARE.CODICEFISCALE as CONC_TIT_CF,TITOLARE.PARTITAIVA as CONC_TIT_PIVA,TITOLARE.TIPOANAGRAFE as CONC_TIT_TIPOANAGRAFE,AUT_COLLEGATA.AUTORIZNUMERO as AUT_NUMERO,AUT_COLLEGATA.AUTORIZDATA as AUT_DATA,AUT_COLLEGATA.AUTORIZDATA,AUT_COLLEGATA.FKIDREGISTRO as AUT_CODREGISTRO,TIPOLOGIAREGISTRI.TR_DESCRIZIONE as AUT_REGISTRO,CONCAT_WS('',IST_RICHIEDENTE.NOMINATIVO,' ',IST_RICHIEDENTE.NOME) as IST_NOMINATIVO,IST_RICHIEDENTE.TIPOANAGRAFE as IST_RIC_TIPOANAGRAFE,CONCAT_WS('',IST_AZIENDA.NOMINATIVO,' ',IST_AZIENDA.NOME) as IST_NOMINATIVOAZIENDA,IST_AZIENDA.TIPOANAGRAFE as IST_AZI_TIPOANAGRAFE,IST_RICHIEDENTE.CODICEFISCALE as IST_CODICEFISCALE,IST_RICHIEDENTE.PARTITAIVA as IST_PARTITAIVA,CAUS_ATTUALE.DESCRIZIONE as ICONC_CAUSALE,AUTORIZZAZIONI_SUBENTRI.FK_CAUSALE_CESSAZIONE as ICONC_CODICECAUSALESTORICO,CAUS_STORICO.DESCRIZIONE as ICONC_CAUSALESTORICO,AUTORIZZAZIONI_CONCESSIONI.FK_CODICEMERCATO as CONC_IDMERCATO,MERCATI.DESCRIZIONE as CONC_MERCATO,MERCATI.ATTIVO as MERC_ATTIVO,AUTORIZZAZIONI_CONCESSIONI.FK_IDPOSTEGGIO as CONC_IDPOSTEGGIO,MERCATI_D.CODICEPOSTEGGIO as CONC_POSTEGGIO,MERCATI_D.LARGHEZZA as CONC_POS_LARGHEZZA,MERCATI_D.LUNGHEZZA as CONC_POS_LUNGHEZZA,MERCATI_D.SUPERFICIE as CONC_POS_SUPERFICIE,MERCATI_D.FKCODICETIPOSPAZIO as POST_IDTIPOSPAZIO,POSTEGGITIPOSPAZIO.TIPOSPAZIO as POST_TIPOSPAZIO,AUTORIZZAZIONI_CONCESSIONI.FK_IDMERCATIUSO as CONC_IDMERCATIUSO,MERCATI_USO.DESCRIZIONE as CONC_DESCRIZIONEUSO,MERCATI_USO.PESO as PESO_MERCATO,MERCATI_USO.FKCODICEUSO as MERC_IDUSO,MERCATI_D.FKCODICESTRADARIO as CONC_POS_CODICESTRADARIO FROM AUTORIZZAZIONI_CONCESSIONI LEFT OUTER JOIN AUTORIZZAZIONI AUT_COLLEGATA ON AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE=AUT_COLLEGATA.IDCOMUNE  AND AUTORIZZAZIONI_CONCESSIONI.FK_IDAUT_COLLEGATA=AUT_COLLEGATA.ID,AUTORIZZAZIONI_SUBENTRI LEFT OUTER JOIN TIPOLOGIAREGISTRI ON AUTORIZZAZIONI_SUBENTRI.IDCOMUNE=TIPOLOGIAREGISTRI.IDCOMUNE  AND AUTORIZZAZIONI_SUBENTRI.FKIDREGISTRO=TIPOLOGIAREGISTRI.TR_ID  LEFT OUTER JOIN CONCESSIONICAUSALI CAUS_STORICO ON AUTORIZZAZIONI_SUBENTRI.IDCOMUNE=CAUS_STORICO.IDCOMUNE  AND AUTORIZZAZIONI_SUBENTRI.FK_CAUSALE_CESSAZIONE=CAUS_STORICO.CODICECAUSALE,MERCATI_D LEFT OUTER JOIN POSTEGGITIPOSPAZIO ON MERCATI_D.IDCOMUNE=POSTEGGITIPOSPAZIO.IDCOMUNE  AND MERCATI_D.FKCODICETIPOSPAZIO=POSTEGGITIPOSPAZIO.CODICE,ISTANZE LEFT OUTER JOIN ANAGRAFE IST_AZIENDA ON ISTANZE.IDCOMUNE=IST_AZIENDA.IDCOMUNE  AND ISTANZE.CODICETITOLARELEGALE=IST_AZIENDA.CODICEANAGRAFE,CONCESSIONITIPI,ANAGRAFE TITOLARE,CONCESSIONICAUSALI CAUS_ATTUALE,ANAGRAFE IST_RICHIEDENTE,MERCATI,MERCATI_USO WHERE AUTORIZZAZIONI_SUBENTRI.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND AUTORIZZAZIONI_SUBENTRI.FK_IDAUT_ATTUALE = AUTORIZZAZIONI_CONCESSIONI.FK_IDAUT_ATTUALE AND CONCESSIONITIPI.TIPOCONCESSIONE = AUTORIZZAZIONI_CONCESSIONI.FK_TIPOCONCESSIONE AND TITOLARE.IDCOMUNE = AUTORIZZAZIONI_SUBENTRI.IDCOMUNE AND TITOLARE.CODICEANAGRAFE = AUTORIZZAZIONI_SUBENTRI.FK_CODICEANAGRAFE AND CAUS_ATTUALE.IDCOMUNE = AUTORIZZAZIONI_SUBENTRI.IDCOMUNE AND CAUS_ATTUALE.CODICECAUSALE = AUTORIZZAZIONI_SUBENTRI.FK_CAUSALE_ACQUISIZIONE AND ISTANZE.IDCOMUNE = AUTORIZZAZIONI_SUBENTRI.IDCOMUNE AND ISTANZE.CODICEISTANZA = AUTORIZZAZIONI_SUBENTRI.FKIDISTANZA AND IST_RICHIEDENTE.IDCOMUNE = ISTANZE.IDCOMUNE AND IST_RICHIEDENTE.CODICEANAGRAFE = ISTANZE.CODICERICHIEDENTE AND MERCATI.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND MERCATI.CODICEMERCATO = AUTORIZZAZIONI_CONCESSIONI.FK_CODICEMERCATO AND MERCATI_D.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND MERCATI_D.IDPOSTEGGIO = AUTORIZZAZIONI_CONCESSIONI.FK_IDPOSTEGGIO AND MERCATI_USO.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND MERCATI_USO.ID = AUTORIZZAZIONI_CONCESSIONI.FK_IDMERCATIUSO;
CREATE OR REPLACE ALGORITHM=TEMPTABLE VIEW VW_CONCESSIONILISTA AS SELECT IDCOMUNE, SOFTWARE, PROGRESSIVO, CONC_ID, CONC_NUMERO, CONC_DATARILASCIO, CONC_DATASCADENZA, CONC_CODICETIPO, CONC_TIPO, CONC_STAGIONALEA, CONC_STAGIONALEDA, CONC_ATTIVA, CONC_CODICETITOLARE, CONC_TITOLARE, CONC_TIT_CF, CONC_TIT_PIVA, CONC_TIT_TIPOANAGRAFE, AUT_NUMERO, AUT_DATA, AUT_CODREGISTRO, AUT_REGISTRO, IST_CODICEISTANZA, IST_NUMEROISTANZA, IST_CODICERICHIEDENTE, IST_NOMINATIVO, IST_CODICEFISCALE, IST_PARTITAIVA, IST_RIC_TIPOANAGRAFE, ICONC_CODICECAUSALE, ICONC_CAUSALE, ICONC_CODICECAUSALESTORICO, ICONC_CAUSALESTORICO, CONC_IDMERCATO, CONC_MERCATO, MERC_ATTIVO, CONC_IDPOSTEGGIO, CONC_POSTEGGIO, CONC_POS_LARGHEZZA, CONC_POS_LUNGHEZZA, CONC_POS_SUPERFICIE, POST_IDTIPOSPAZIO, POST_TIPOSPAZIO, CONC_IDMERCATIUSO, CONC_DESCRIZIONEUSO, PESO_MERCATO, MERC_IDUSO, CONC_POS_CODICESTRADARIO FROM VW_ISTANZECONCESSIONILISTA;

ALTER TABLE CC_CAUSALIRIDUZIONIR DROP FOREIGN KEY FK_CCCAUSRIDUR_CCCAUSRIDUT;
ALTER TABLE CC_CAUSALIRIDUZIONIR ADD CONSTRAINT FK_CCCAUSRIDUR_CCCAUSRIDUT FOREIGN KEY (IDCOMUNE, FK_CCCRT_ID) REFERENCES CC_CAUSALIRIDUZIONIT (IDCOMUNE, ID);

alter table MAIL_CONFIG add IN_LOGINNAME varchar(320 );
alter table MAIL_CONFIG add IN_LOGINPASS varchar(30 );
alter table MAIL_CONFIG add IN_USEAUTHENTICATION numeric(1,0);
alter table MAIL_CONFIG add IN_MAILSERVER varchar(50 );
alter table MAIL_CONFIG add IN_PORT numeric(5,0);
alter table MAIL_CONFIG add IN_USESSL numeric(1,0);

ALTER TABLE BATCH_SCADENZARIO DROP FOREIGN KEY  FK_BATCHSCA_AMMINISTRAZ;
ALTER TABLE BATCH_SCADENZARIO DROP FOREIGN KEY  FK_BATCHSCA_INVENTARIO;
ALTER TABLE BATCH_SCADENZARIO DROP FOREIGN KEY  FK_BATCHSCA_ISTANZE;
ALTER TABLE BATCH_SCADENZARIO DROP FOREIGN KEY  FK_BATCHSCA_MOVIMENTI;
ALTER TABLE BATCH_SCADENZARIO DROP FOREIGN KEY  FK_BATCHSCA_TIPIMOV;

CREATE INDEX IDX_DOMANDESTC_002 ON DOMANDESTC (IDCOMUNE,CODICESOFTWARE,FLAG_IMPORT);
CREATE UNIQUE INDEX SORTEGGIDETTAGLIO_UK01 ON SORTEGGIDETTAGLIO (IDCOMUNE,SD_FK_STID,CODICEISTANZA);

ALTER TABLE ANAGRAFE MODIFY INDIRIZZO VARCHAR(100);
ALTER TABLE ANAGRAFESTORICO MODIFY INDIRIZZO VARCHAR(100);
ALTER TABLE TIPIMOV_STC_ALBEROPROC MODIFY FK_SCID NUMERIC(10,0);
ALTER TABLE INVENTARIOPROCEDIMENTIPEOPLE MODIFY COD_PROC_PEOPLE VARCHAR(50);
CREATE INDEX IDX_DOMANDESTC_003 ON DOMANDESTC (IDCOMUNE, ID_DOMANDAMITT);

ALTER TABLE DOCUMENTIISTANZA ADD FLG_DA_MODELLO_DINAMICO NUMERIC(1,0);

ALTER TABLE ISTANZECOLLEGATE DROP FOREIGN KEY FK_ISTANZE_COLL_ISTANZACOLL;
ALTER TABLE ISTANZECOLLEGATE DROP FOREIGN KEY FK_ISTANZE_COLL_ISTANZE;
DROP INDEX IDX_ISTANZECOLLEGATE_001 ON ISTANZECOLLEGATE;
DROP INDEX IDX_ISTANZECOLLEGATE_002 ON ISTANZECOLLEGATE;
DROP INDEX IDX_ISTANZECOLLEGATE_003 ON ISTANZECOLLEGATE;
CREATE TABLE ISTANZECOLLEGATE_BAK AS SELECT * FROM ISTANZECOLLEGATE;
DROP TABLE ISTANZECOLLEGATE;
CREATE TABLE ISTANZECOLLEGATE (IDCOMUNE VARCHAR(6) NOT NULL, PROGRESSIVO NUMERIC(8,0) NOT NULL, CODICEISTANZA NUMERIC(6,0) NOT NULL, ORDINE NUMERIC(3,0) NOT NULL, ID NUMERIC(8,0) NOT NULL, CODICEISTANZACOLLEGATA NUMERIC(6,0)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO ISTANZECOLLEGATE (IDCOMUNE,ID,PROGRESSIVO,CODICEISTANZA, ORDINE, CODICEISTANZACOLLEGATA)( SELECT IDCOMUNE, ID,PROGRESSIVO,CODICEISTANZA,ORDINE,CODICEISTANZACOLLEGATA FROM ISTANZECOLLEGATE_BAK );
ALTER TABLE ISTANZECOLLEGATE ADD( CONSTRAINT ISTANZECOLLEGATE_PK PRIMARY KEY (IDCOMUNE,ID));
ALTER TABLE ISTANZECOLLEGATE ADD (CONSTRAINT FK_ISTANZE_COLL_ISTANZE FOREIGN KEY(IDCOMUNE,CODICEISTANZA) REFERENCES ISTANZE(IDCOMUNE,CODICEISTANZA));
ALTER TABLE ISTANZECOLLEGATE ADD (CONSTRAINT FK_ISTANZE_COLL_ISTANZACOLL FOREIGN KEY(IDCOMUNE,CODICEISTANZACOLLEGATA) REFERENCES ISTANZE(IDCOMUNE,CODICEISTANZA));
CREATE INDEX IDX_ISTANZECOLLEGATE_001 ON ISTANZECOLLEGATE(IDCOMUNE,PROGRESSIVO,CODICEISTANZA,ORDINE);
CREATE INDEX IDX_ISTANZECOLLEGATE_002 ON ISTANZECOLLEGATE(IDCOMUNE,CODICEISTANZA);
CREATE INDEX IDX_ISTANZECOLLEGATE_003 ON ISTANZECOLLEGATE(IDCOMUNE,CODICEISTANZACOLLEGATA);
ALTER TABLE ANAGRAFE MODIFY PARTITAIVA VARCHAR(16);
ALTER TABLE ANAGRAFESTORICO MODIFY PARTITAIVA VARCHAR(16);

ALTER TABLE ALBEROPROC_DYN2MODELLIT ADD FLAG_FACOLTATIVA NUMERIC(1, 0);
ALTER TABLE INVENTARIOPROCDYN2MODELLIT ADD FLAG_FACOLTATIVA NUMERIC(1, 0);
