<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="urn:it.regulus.gestoreincassi" xmlns="urn:it.regulus.gestoreincassi" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:include schemaLocation="TipiDati.xsd"/>
	<xs:element name="DATIFORNITI">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="CODFISC" type="CodiceFiscale"/>
				<xs:element name="CODENTE" type="xs:string" minOccurs="0"/>
				<xs:element name="TIPOCODENTE" type="TipoCodiceEnte" minOccurs="0"/>
				<xs:element name="CODTRIBUTO" type="xs:string" minOccurs="0"/>
				<xs:element name="DATAINIZIO" type="xs:date" minOccurs="0"/>
				<xs:element name="DATAFINE" type="xs:date" minOccurs="0"/>
				<xs:element name="ANNODOC" type="TipoAnno" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>
