<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:complexType name="TipoDettaglioErrore">
		<xs:annotation>
			<xs:documentation>Tipologia contenente il dettaglio dell'eventuale errore occorso</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="CODICE">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="DESCRIZIONE" type="xs:string"/>
			<xs:element name="SORGENTE" type="xs:string"/>
			<xs:element name="CODICEAGG" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>
