ALTER TABLE ANAGRAFE ADD FLAG_IDENTIFICATO NUMBER(1,0);

ALTER TABLE ANAGRAFE ADD OPER_IDENTIFICAZIONE NUMBER(8,0);

ALTER TABLE ANAGRAFE ADD CONSTRAINT FK_ANAGRAFE_RESPIDENT FOREIGN KEY (IDCOMUNE, OPER_IDENTIFICAZIONE) REFERENCES RESPONSABILI (IDCOMUNE, CODICERESPONSABILE);

ALTER TABLE ANAGRAFE ADD DATA_IDENTIFICAZIONE DATE;


ALTER TABLE ANAGRAFESTORICO ADD FLAG_IDENTIFICATO NUMBER(1,0);

ALTER TABLE ANAGRAFESTORICO ADD OPER_IDENTIFICAZIONE NUMBER(8,0);

ALTER TABLE ANAGRAFESTORICO ADD CONSTRAINT FK_ANAGRAFEST_RESPIDENT FOREIGN KEY (IDCOMUNE, OPER_IDENTIFICAZIONE) REFERENCES RESPONSABILI (IDCOMUNE, CODICERESPONSABILE);

ALTER TABLE ANAGRAFESTORICO ADD DATA_IDENTIFICAZIONE DATE;

DELETE FROM INTERESSI_LEGALI;

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (1,TO_DATE('21-04-1942','dd-MM-yyyy'),TO_DATE('15-12-1990','dd-MM-yyyy'),5,null);

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (2,TO_DATE('16-12-1990','dd-MM-yyyy'),TO_DATE('31-12-1996','dd-MM-yyyy'),10,'Legge 26 novembre 1990, n. 353'); 

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (3,TO_DATE('01-01-1997','dd-MM-yyyy'),TO_DATE('31-12-1998','dd-MM-yyyy'),5,'Legge 23 dicembre 1996, n. 662'); 

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (4,TO_DATE('01-01-1999','dd-MM-yyyy'),TO_DATE('31-12-2000','dd-MM-yyyy'),2.5,'D.M. 10 dicembre 1998');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (5,TO_DATE('01-01-2001','dd-MM-yyyy'),TO_DATE('31-12-2001','dd-MM-yyyy'),3.5,'D.M. 11 dicembre 2000');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (6,TO_DATE('01-01-2002','dd-MM-yyyy'),TO_DATE('31-12-2003','dd-MM-yyyy'),3,'D.M. 11 dicembre 2001');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (7,TO_DATE('01-01-2004','dd-MM-yyyy'),TO_DATE('31-12-2007','dd-MM-yyyy'),2.5,'D.M. 1 dicembre 2003');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (8,TO_DATE('01-01-2008','dd-MM-yyyy'),TO_DATE('31-12-2009','dd-MM-yyyy'),3,'D.M. 12 dicembre 2007');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (9,TO_DATE('01-01-2010','dd-MM-yyyy'),TO_DATE('31-12-2010','dd-MM-yyyy'),1,'D.M. 4 dicembre 2009');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (10,TO_DATE('01-01-2011','dd-MM-yyyy'),TO_DATE('31-12-2011','dd-MM-yyyy'),1.5,'D.M. 07 Dicembre 2010');

insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (11,TO_DATE('01-01-2012','dd-MM-yyyy'),TO_DATE('31-12-2013','dd-MM-yyyy'),2.5,'DM 12 dicembre 2011');
Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (12,to_date('01-01-2014','dd-MM-yyyy'),TO_DATE('31-12-2014','dd-MM-yyyy'),1,'Dm Economia 13.12.2013');
Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (13,to_date('01-01-2015','dd-MM-yyyy'),TO_DATE('31-12-2015','dd-MM-yyyy'),0.5,'Dm Economia 11.12.2014');
Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (14,to_date('01-01-2016','dd-MM-yyyy'),null,0.2,'Dm Economia 11.12.2015');

CREATE TABLE ALBEROPROC_DOC_SOGG_FIRMATARI(
  ID NUMBER(10,0) NOT NULL,
  IDCOMUNE VARCHAR2(6) NOT NULL,
  FK_TIPO_SOGGETTO NUMBER(10,0) NOT NULL,
  FK_ALBEROPROC_DOCUMENTI NUMBER(10,0) NOT NULL
);


CREATE UNIQUE INDEX ALBEROPROC_DOC_SOGG_FIRM_PK ON ALBEROPROC_DOC_SOGG_FIRMATARI (IDCOMUNE,ID);
ALTER TABLE ALBEROPROC_DOC_SOGG_FIRMATARI ADD CONSTRAINT ALBEROPROC_DOC_SOGG_FIRM_PK PRIMARY KEY (IDCOMUNE,ID);

ALTER TABLE ALBEROPROC_DOC_SOGG_FIRMATARI 
ADD CONSTRAINT FK_SOGG_FIRM_TIPO_SOGGETTO
FOREIGN KEY (IDCOMUNE, FK_TIPO_SOGGETTO) 
REFERENCES TIPISOGGETTO (IDCOMUNE, CODICETIPOSOGGETTO);

ALTER TABLE ALBEROPROC_DOC_SOGG_FIRMATARI 
ADD CONSTRAINT FK_SOGG_FIRM_ALBEROPROC_DOC
FOREIGN KEY (IDCOMUNE, FK_ALBEROPROC_DOCUMENTI) 
REFERENCES ALBEROPROC_DOCUMENTI (IDCOMUNE, SM_ID);


CREATE TABLE INVENTARIOPROC_SOGG_FIRMATARI(
  ID NUMBER(10,0) NOT NULL,
  IDCOMUNE VARCHAR2(6 BYTE) NOT NULL,
  FK_TIPO_SOGGETTO NUMBER(10,0) NOT NULL,
  FK_DOCUMENTI NUMBER(8,0) NOT NULL
);


CREATE UNIQUE INDEX INVENTARIOPROC_SOGG_FIRM_PK ON INVENTARIOPROC_SOGG_FIRMATARI (IDCOMUNE,ID);
ALTER TABLE INVENTARIOPROC_SOGG_FIRMATARI ADD CONSTRAINT INVENTARIOPROC_SOGG_FIRM_PK PRIMARY KEY (IDCOMUNE,ID);

ALTER TABLE INVENTARIOPROC_SOGG_FIRMATARI 
ADD CONSTRAINT FK_INVENT_SOGG_FIRM_TIPO_SOGG
FOREIGN KEY (IDCOMUNE, FK_TIPO_SOGGETTO) 
REFERENCES TIPISOGGETTO (IDCOMUNE, CODICETIPOSOGGETTO);

ALTER TABLE INVENTARIOPROC_SOGG_FIRMATARI 
ADD CONSTRAINT FK_SOGG_FIRM_INVET_PROC_DOC
FOREIGN KEY (IDCOMUNE, FK_DOCUMENTI) 
REFERENCES DOCUMENTI (IDCOMUNE, ID);

ALTER TABLE TIPIMOVIMENTO_COMUNICAZIONI ADD (DESTINATARI_MAIL VARCHAR2(50) );


ALTER TABLE TIPIMOVIMENTO_COMUNICAZIONI ADD (FLAG_INSERIMENTO_MOV NUMBER(1,0) );

ALTER TABLE TIPIMOVIMENTO_COMUNICAZIONI MODIFY (FUNZIONE VARCHAR2(100) );