ALTER TABLE METADATI_DIZ_BASE ADD CONTESTO VARCHAR2(1);

create table CFG_METADATI_CMIS (
IDCOMUNE varchar2(6) not null,
FK_METADATO_BASE varchar2(30) not null,
MAPPING_CMIS varchar2(100) not null
);

alter table CFG_METADATI_CMIS add constraint PK_CFG_METADATI_CMIS primary key (IDCOMUNE,FK_METADATO_BASE);
alter table CFG_METADATI_CMIS add constraint FK_CFGMETACMIS_DIZBASE FOREIGN key (FK_METADATO_BASE) REFERENCES METADATI_DIZ_BASE (ID);

ALTER TABLE CFG_METADATI_CMIS ADD TIPO_DATO_CMIS varchar2 (20);
COMMENT ON COLUMN CFG_METADATI_CMIS.TIPO_DATO_CMIS IS 'Sul sistema ECM un dato potrebbe essere di un tipo particolare es: date, ad oggi sono previsti solamente i valori STRING e DATE';

ALTER TABLE ANAGRAFESTORICO ADD(FK_CODICERESPONSABILE NUMBER(8,0));

ALTER TABLE ANAGRAFESTORICO ADD CONSTRAINT  FK_ANAGRAFE_STORICO_RESPONS FOREIGN KEY (IDCOMUNE,FK_CODICERESPONSABILE) REFERENCES RESPONSABILI(IDCOMUNE,CODICERESPONSABILE);

ALTER TABLE ALBEROPROC ADD(INIZIO_VALIDITA DATE);
ALTER TABLE ALBEROPROC ADD(FINE_VALIDITA DATE);

ALTER TABLE STRADARIO ADD(COMUNE_LOCALIZZAZIONE VARCHAR2(5));
ALTER TABLE STRADARIO ADD CONSTRAINT FK_STRADARIO_COMUNE_LOCALIZZ FOREIGN KEY (COMUNE_LOCALIZZAZIONE) REFERENCES COMUNI(CODICECOMUNE);

CREATE TABLE CONF_APPLICATIVE(
	IDCOMUNE VARCHAR2(6) NOT NULL,
	CHIAVE   VARCHAR2(50) NOT NULL,
	VALORE   VARCHAR2(200)
);

ALTER TABLE CONF_APPLICATIVE ADD CONSTRAINT PK_CONF_APPLICATIVE PRIMARY KEY (IDCOMUNE, CHIAVE);