ALTER TABLE ALBEROPROC ADD FLAG_PROG_ATT_OSSERV NUMERIC(1,0);
ALTER TABLE I_ATTIVITA ADD CODICE_OSSERVATORIO NUMERIC(10,0);
ALTER TABLE I_ATTIVITA_SNAPSHOT ADD CODICE_OSSERVATORIO NUMERIC(10,0);

ALTER TABLE PENTAHOCFG add USERID VARCHAR(50);
ALTER TABLE PENTAHOCFG add PASSWORD VARCHAR(50);
