CREATE TABLE ALBEROPROC_TIPISOGGETTO(
IDCOMUNE VARCHAR2(6) NOT NULL,
ID NUMBER(6,0) NOT NULL,
FK_SCID NUMBER(10,0) NOT NULL,
FK_CODICETIPOSOGGETTO NUMBER(10,0) NOT NULL
);

ALTER TABLE ALBEROPROC_TIPISOGGETTO ADD CONSTRAINT PK_ALBEROPROC_TIPISOGGETTO PRIMARY KEY(IDCOMUNE, ID);
ALTER TABLE ALBEROPROC_TIPISOGGETTO ADD CONSTRAINT FK_APTS_TIPISOGGETTO FOREIGN KEY(IDCOMUNE, FK_CODICETIPOSOGGETTO) REFERENCES TIPISOGGETTO(IDCOMUNE, CODICETIPOSOGGETTO);
ALTER TABLE ALBEROPROC_TIPISOGGETTO ADD CONSTRAINT FK_APTS_ALBEROPROC FOREIGN KEY(IDCOMUNE, FK_SCID) REFERENCES ALBEROPROC(IDCOMUNE, SC_ID);

CREATE OR REPLACE VIEW VW_ENTILOCALI AS SELECT CODICECOMUNE, COMUNE FROM COMUNI WHERE CODICESTATOESTERO IS NULL UNION SELECT CODICEASSOCIAZIONE AS CODICECOMUNE, ASSOCIAZIONE AS COMUNE FROM COMUNIASSOCIAZIONI;
ALTER TABLE FO_ARJ_DOMANDE ADD FLAG_INVALIDATA NUMBER(1,0); 
ALTER TABLE FO_ARJ_DOMANDE ADD DATA_INVALIDATA DATE; 

CREATE TABLE FO_ARJ_DOMANDE_STEPS_ESEGUITI(
ID NUMBER(6) NOT NULL,
IDCOMUNE VARCHAR2(6) NOT NULL,
FK_FO_ARJ_DOMANDE NUMBER(6,0) NOT NULL,
FK_FO_ARJ_STEPS_BASE VARCHAR2(50) NOT NULL
);

ALTER TABLE FO_ARJ_DOMANDE_STEPS_ESEGUITI ADD CONSTRAINT FOARJDOMANDESTEPSESEGUITI_PK PRIMARY KEY
(
  IDCOMUNE, ID
);

ALTER TABLE FO_ARJ_DOMANDE_STEPS_ESEGUITI ADD CONSTRAINT STEPSESEGUITI_FOARJDOMANDE FOREIGN KEY ( IDCOMUNE, FK_FO_ARJ_DOMANDE) REFERENCES FO_ARJ_DOMANDE ( IDCOMUNE, ID );

ALTER TABLE FO_ARJ_DOMANDE_STEPS_ESEGUITI ADD CONSTRAINT STEPSESEGUITI_FOARJSTEPSBA FOREIGN KEY ( FK_FO_ARJ_STEPS_BASE) REFERENCES FO_ARJ_STEPS_BASE ( NOME_STEP );

CREATE TABLE PAYER_ATTIVAZIONI 
(
CODICECOMUNE VARCHAR2(5) NOT NULL, 
ALIAS VARCHAR2(20) NOT NULL ,
IDCOMUNE VARCHAR2(6) NOT NULL,
CONSTRAINT PAYER_ATTIVAZIONI_PK PRIMARY KEY (CODICECOMUNE)
); 
CREATE TABLE PAYER_LOG
(
IDCOMUNE VARCHAR2(6) NOT NULL,
CODICE NUMBER(10,0) NOT NULL,
CODICEOGGETTO NUMBER(10,0) NOT NULL,
PROGRESSIVO NUMBER(8,0) NOT NULL,
NUM_DOCUMENTO VARCHAR2(23),
NUM_RATA NUMBER (2,0),
IMPORTO  NUMBER (8,2),
ISTANZA NUMBER(6,0),
CAUSALE_ONERE NUMBER (10,0),
FK_ONERI NUMBER(10,0),
ERRORE CLOB,
CODICE_ERRORE VARCHAR2(4), 
FLAG_ERRORE NUMBER(1,0) NOT NULL,
DATA_PAGAMENTO DATE,
DATA_REGISTRAZIONE DATE
);

ALTER TABLE PAYER_LOG ADD CONSTRAINT PK_APAYER_LOG PRIMARY KEY(IDCOMUNE, CODICE); 

ALTER TABLE PAYER_LOG ADD CONSTRAINT FK_PAYERLOG_OGGETTI FOREIGN KEY(IDCOMUNE, CODICEOGGETTO) REFERENCES OGGETTI(IDCOMUNE, CODICEOGGETTO);

alter table FO_ARJ_DOMANDE add FLAG_FLUSSO_DA_INTERVENTO NUMBER(1,0);

alter table FO_ARJ_DOMANDE add FK_FO_ARJ_SERVIZI NUMBER(6,0);

alter table FO_ARJ_DOMANDE add constraint FK_FOARJDOMANDE_FOARJSERVIZI foreign key (IDCOMUNE, FK_FO_ARJ_SERVIZI) references FO_ARJ_SERVIZI (IDCOMUNE, ID);

alter table FO_ARJ_SERVIZI modify URL_SERVIZIO VARCHAR2(200);
alter table FO_ARJ_SERVIZI add constraint UIDX_FOARJSERVIZI_001 unique (IDCOMUNE, URL_SERVIZIO);

COMMENT on column FO_ARJ_DOMANDE.CODICEISTANZA is 'DISMESSO';
COMMENT on column FO_ARJ_DOMANDE.STEP is 'DISMESSO';
alter table FO_ARJ_DOMANDE add CODICEOGGETTO_RICEVUTA number(10,0);
alter table FO_ARJ_DOMANDE add constraint FK_FOARJDOMANDE_OGGRICE_OGG foreign key (IDCOMUNE, CODICEOGGETTO_RICEVUTA) references OGGETTI (IDCOMUNE, CODICEOGGETTO);


CREATE TABLE GRADUATORIET_COM
(
IDCOMUNE VARCHAR2(6) NOT NULL,
ID NUMBER(10,0) NOT NULL,
FK_GT_ID NUMBER(6,0) NOT NULL, 
DATA DATE NOT NULL,
DESCRIZIONE VARCHAR2(500) NOT NULL,
TIPOMOVIMENTO VARCHAR2 (8) NOT NULL,
FLG_PROTOCOLLA  NUMBER (1,0) NOT NULL,
CODICELETTERA NUMBER(10,0), CODICEMAIL NUMBER (4,0),
DESTINATARI VARCHAR2(1) NOT NULL,
POSIZIONE_DA NUMBER (4,0), 
POSIZIONE_AL NUMBER(4,0), 
DYN2FILTRI VARCHAR2(2000),
AMMINISTRAZIONE_PROT NUMBER(10, 0)
);

ALTER TABLE GRADUATORIET_COM ADD CONSTRAINT PK_GRADUATORIET_COM PRIMARY KEY(IDCOMUNE, ID); 
ALTER TABLE GRADUATORIET_COM ADD CONSTRAINT FK_GRADUAT_COM_GRADUA_T FOREIGN KEY(IDCOMUNE, FK_GT_ID) REFERENCES GRADUATORIET(IDCOMUNE, ID);
ALTER TABLE GRADUATORIET_COM ADD CONSTRAINT FK_GRADUAT_COM_TIPOMOV FOREIGN KEY(IDCOMUNE, TIPOMOVIMENTO) REFERENCES TIPIMOVIMENTO(IDCOMUNE, TIPOMOVIMENTO); 
ALTER TABLE GRADUATORIET_COM ADD CONSTRAINT FK_GRADUAT_COM_LETT_TIPO FOREIGN KEY(IDCOMUNE, CODICELETTERA) REFERENCES LETTERETIPO(IDCOMUNE, CODICELETTERA);
ALTER TABLE GRADUATORIET_COM ADD CONSTRAINT FK_GRADUAT_COM_MAILTIPO FOREIGN KEY(IDCOMUNE, CODICEMAIL) REFERENCES MAILTIPO(IDCOMUNE, CODICEMAIL);
ALTER TABLE GRADUATORIET_COM ADD CONSTRAINT FK_GRADUAT_AMM_PROT FOREIGN KEY(IDCOMUNE, AMMINISTRAZIONE_PROT) REFERENCES AMMINISTRAZIONI(IDCOMUNE, CODICEAMMINISTRAZIONE);

CREATE TABLE GRADUATORIED_COM
(
IDCOMUNE VARCHAR2(6) NOT NULL,
ID NUMBER(10,0) NOT NULL,
FK_IDTESTATA NUMBER(10,0) NOT NULL,
FK_GD_ID NUMBER(9,0) NOT NULL,
CODICEMOVIMENTO NUMBER (8,0),
FLG_PROTOCOLLATO  NUMBER (1,0) NOT NULL,
CODICEOGGETTO NUMBER(10,0), 
FK_IDMAIL NUMBER (8,0)
);

ALTER TABLE GRADUATORIED_COM ADD CONSTRAINT PK_GRADUATORIED_COM PRIMARY KEY(IDCOMUNE, ID); 
ALTER TABLE GRADUATORIED_COM ADD CONSTRAINT FK_GRAD_D_COM_GRAD_T_COM FOREIGN KEY(IDCOMUNE, FK_IDTESTATA) REFERENCES GRADUATORIET_COM(IDCOMUNE, ID); 
ALTER TABLE GRADUATORIED_COM ADD CONSTRAINT FK_GRAD_D_COM_GRADUA_D FOREIGN KEY(IDCOMUNE, FK_GD_ID) REFERENCES GRADUATORIED(IDCOMUNE, ID);
ALTER TABLE GRADUATORIED_COM ADD CONSTRAINT FK_GRAD_D_COM_MOVIM FOREIGN KEY(IDCOMUNE, CODICEMOVIMENTO) REFERENCES MOVIMENTI(IDCOMUNE, CODICEMOVIMENTO); 
ALTER TABLE GRADUATORIED_COM ADD CONSTRAINT FK_GRAD_D_COM_OGGETTI FOREIGN KEY(IDCOMUNE, CODICEOGGETTO) REFERENCES OGGETTI(IDCOMUNE, CODICEOGGETTO); 
ALTER TABLE GRADUATORIED_COM ADD CONSTRAINT FK_GRAD_D_COM_MOV_MAIL FOREIGN KEY(IDCOMUNE, FK_IDMAIL) REFERENCES MOVIMENTIMAIL(IDCOMUNE, ID); 


ALTER TABLE INVENTARIOPROC_TIPITITOLO ADD FLG_MOSTRA_DATA NUMBER(1,0);
ALTER TABLE INVENTARIOPROC_TIPITITOLO ADD FLG_MOSTRA_NUMERO NUMBER(1,0); 
ALTER TABLE INVENTARIOPROC_TIPITITOLO ADD FLG_MOSTRA_RILASCIATO_DA NUMBER(1,0); 
ALTER TABLE INVENTARIOPROC_TIPITITOLO ADD FLG_RICHIEDE_ALLEGATO NUMBER(1,0); 
ALTER TABLE INVENTARIOPROC_TIPITITOLO ADD FLG_VERIFICA_FIRMA_ALLEGATO NUMBER(1,0);

ALTER TABLE FO_ARJ_STEPS_PARAMS_BASE ADD FK_FO_ARJ_STEP_BASE VARCHAR2(50);

ALTER TABLE FO_ARJ_STEPS_PARAMS_BASE ADD CONSTRAINT FK_FOARJSTEPPARMBASE_STEPBASE FOREIGN KEY (FK_FO_ARJ_STEP_BASE) REFERENCES FO_ARJ_STEPS_BASE (NOME_STEP);

ALTER TABLE TIPIPROCEDURE ADD CODOGGETTO_RICEVUTACART NUMBER(10,0);
ALTER TABLE TIPIPROCEDURE ADD CONSTRAINT FK_TPROC_CODRICCART FOREIGN KEY(IDCOMUNE, CODOGGETTO_RICEVUTACART) REFERENCES OGGETTI(IDCOMUNE,CODICEOGGETTO);

ALTER TABLE ANAGRAFEDOCUMENTI ADD FLAG_XMLVISURAPARIX NUMBER(1,0);

ALTER TABLE PEC_INBOX ADD (FLAG_PROCESSATA NUMBER(1, 0) DEFAULT 0 );
ALTER TABLE PEC_INBOX ADD (CODICEISTANZA NUMBER(6, 0) );
ALTER TABLE PEC_INBOX ADD (CODICEMOVIMENTO NUMBER(8, 0) );
ALTER TABLE PEC_INBOX ADD (CODICEOPERATORE NUMBER(4, 0) );
ALTER TABLE PEC_INBOX ADD (IDPROTOCOLLO VARCHAR2(15) );
ALTER TABLE PEC_INBOX ADD (NUMEROPROTOCOLLO VARCHAR2(30) );
ALTER TABLE PEC_INBOX ADD (DATAPROTOCOLLO DATE );
ALTER TABLE PEC_INBOX ADD (CODICEOGGETTOPROTOCOLLO NUMBER(10, 0));


ALTER TABLE PEC_INBOX ADD CONSTRAINT PEC_INBOX_FK_ISTANZE FOREIGN KEY(IDCOMUNE, CODICEISTANZA) REFERENCES ISTANZE(IDCOMUNE, CODICEISTANZA);
ALTER TABLE PEC_INBOX ADD CONSTRAINT PEC_INBOX_MOVIMENTI_FK1 FOREIGN KEY(IDCOMUNE, CODICEMOVIMENTO) REFERENCES MOVIMENTI(IDCOMUNE, CODICEMOVIMENTO);
ALTER TABLE PEC_INBOX ADD CONSTRAINT PEC_INBOX_RESPONSABILI_FK1 FOREIGN KEY (IDCOMUNE, CODICEOPERATORE) REFERENCES RESPONSABILI(IDCOMUNE, CODICERESPONSABILE);

ALTER TABLE PEC_INBOX ADD CONSTRAINT CHK_FLG_PROCESSATA CHECK (FLAG_PROCESSATA IN (0, 1));
ALTER TABLE PEC_INBOX ADD CONSTRAINT PEC_INBOX_FK_OGGETTI FOREIGN KEY (IDCOMUNE, CODICEOGGETTOPROTOCOLLO) REFERENCES OGGETTI (IDCOMUNE, CODICEOGGETTO);

CREATE TABLE PEC_INBOX_ALLEGATI 
(
  IDCOMUNE VARCHAR2(6) NOT NULL 
, ID NUMBER(8, 0) NOT NULL 
, FKIDPEC VARCHAR2(128) NOT NULL 
, CODICEOGGETTO NUMBER(10, 0) NOT NULL 
, FLAG_CORPO NUMBER(1, 0) DEFAULT 0
, CONSTRAINT PEC_INBOX_ALLEGATI_PK PRIMARY KEY 
  (
    IDCOMUNE 
  , ID 
  )
);

ALTER TABLE PEC_INBOX_ALLEGATI ADD CONSTRAINT PECALLEGATI_FK_OGGETTI FOREIGN KEY (IDCOMUNE, CODICEOGGETTO) REFERENCES OGGETTI (IDCOMUNE, CODICEOGGETTO);
ALTER TABLE PEC_INBOX_ALLEGATI ADD CONSTRAINT PECALLEGATI_FK_PEC FOREIGN KEY (IDCOMUNE, FKIDPEC) REFERENCES PEC_INBOX(IDCOMUNE, ID);
COMMENT ON COLUMN PEC_INBOX_ALLEGATI.FLAG_CORPO IS 'SE VALE 1 DISTINGUE IL CORPO DEL MESSAGGIO DAI VERI ALLEGATI';
ALTER TABLE DOMANDESTC MODIFY ID_DOMANDAMITT VARCHAR2(150 CHAR);

ALTER TABLE PEC_INBOX ADD (FLAG_CANCELLATA NUMBER(1, 0) DEFAULT 0 );

ALTER TABLE PEC_INBOX ADD CONSTRAINT CHK_FLG_CANCELLATA CHECK (FLAG_CANCELLATA IN (0, 1)) ENABLE;

ALTER TABLE PROTOCOLLO_TIPIDOCUMENTO  MODIFY CODICE VARCHAR2(50 BYTE);


DROP TABLE FO_ARJ_STEPS_PARAMS;

DROP TABLE FO_ARJ_STEPS_PARAMS_BASE;

CREATE TABLE FO_ARJ_STEPS_PARAMS_BASE(
ID NUMBER(6,0) NOT NULL,
CHIAVE VARCHAR2(200 CHAR) NOT NULL,
DESCRIZIONE VARCHAR2(500 CHAR) NOT NULL,
FK_FO_ARJ_STEP_BASE VARCHAR2(50 BYTE) NOT NULL,
  CONSTRAINT FO_ARJ_STEPS_PARAMS_BASE_PK PRIMARY KEY (ID) ENABLE,
  CONSTRAINT FK_FOARJSTEPPARMBASE_STEPBASE FOREIGN KEY (FK_FO_ARJ_STEP_BASE) REFERENCES FO_ARJ_STEPS_BASE (NOME_STEP) ENABLE
);

CREATE TABLE FO_ARJ_STEPS_PARAMS(
IDCOMUNE VARCHAR2(6 CHAR) NOT NULL,
ID NUMBER(6,0) NOT NULL,
FK_PARAMS_BASE NUMBER(6,0) NOT NULL,
VALORE VARCHAR2(400 CHAR),
FK_FO_ARJ_STEPS NUMBER(6,0) NOT NULL,
 CONSTRAINT FO_ARJ_STEPS_PARAMS_PK PRIMARY KEY (IDCOMUNE, ID) ENABLE,
 CONSTRAINT FK_FOARJSTEPSPARAMS_FOARJSTEPS FOREIGN KEY (IDCOMUNE, FK_FO_ARJ_STEPS) REFERENCES FO_ARJ_STEPS (IDCOMUNE, ID) ENABLE,
 CONSTRAINT FK_FOARJSTEPSPARAMS_BASE FOREIGN KEY (FK_PARAMS_BASE) REFERENCES FO_ARJ_STEPS_PARAMS_BASE (ID) ENABLE
);

CREATE OR REPLACE VIEW VW_STATISTICHEISTANZE
                                                               AS
  SELECT DISTINCT ISTANZE.IDCOMUNE                             AS f_idcomune,
    ISTANZE.SOFTWARE                                           AS f_software,
    ISTANZE.DATA                                               AS f_data,
    NVL(ISTANZE.codiceResponsabile,  -1)                       AS f_responsabile,
    NVL(ISTANZE.codiceprofessionista,-1)                       AS f_professionista,
    NVL(ISTANZE.CODICEINTERVENTOPROC,ISTANZE.CODICEINTERVENTO) AS f_codiceintervento,
    NVL(ISTANZE.METRIQUADRATI,0)                               AS f_metriquadrati,
    NVL(ISTANZE.CODICEPROCEDURA,-1)                            AS f_procedura,
    NVL(ISTANZEATTIVITA.CodiceAttivita,' ')                    AS f_dettaglioinformazioni,
    NVL(SETTORI.CodiceSettore,      -1)                              AS f_tipoinformazioni,
    NVL(ISTANZEAREE.CODICEAREA,     -1)                              AS f_zonizzazione,
    NVL(AUTORIZZAZIONI.FKIDREGISTRO,-1)                              AS f_registro,
    NVL(ISTANZE.CHIUSURA,' ')                                        AS f_stato,
    ISTANZE.CODICEISTANZA,
    ISTANZE.CODICERESPONSABILE,
    ISTANZE.CODICERICHIEDENTE,
    ISTANZE.CODICEPROFESSIONISTA,
    ISTANZE.DATA,
    ISTANZE.NUMEROPROTOCOLLO,
    ISTANZE.DATAPROTOCOLLO,
    ISTANZE.CODICEINTERVENTO,
    ISTANZE.LAVORI,
    ISTANZE.CODICEPROCEDURA,
    ISTANZE.CODICEAREA,
    ISTANZE.CODICELOTTO,
    ISTANZE.PASSWORD,
    ISTANZE.ATTIVA,
    ISTANZE.FOGLIO,
    ISTANZE.PARTICELLA,
    ISTANZE.SUB,
    ISTANZE.CODICESETTORE,
    ISTANZE.VARIANTEPR,
    ISTANZE.CODICEIMPIANTO,
    ISTANZE.CODICEATTIVITA,
    ISTANZE.FLAGVIA,
    ISTANZE.CHIUSURA,
    ISTANZE.PROGREGAUT,
    ISTANZE.LAVORIESTESA,
    ISTANZE.CODICEARCHIVIO,
    ISTANZE.CODICESTRADARIO,
    ISTANZE.CIVICO,
    ISTANZE.AUTORIZNUMERO,
    ISTANZE.AUTORIZDATA,
    ISTANZE.AUTORIZDATAREGISTR,
    ISTANZE.AUTORIZRESPONSABILE,
    ISTANZE.TIPOMOVAVVIO,
    ISTANZE.TIPOARCHIVIO,
    ISTANZE.CODICECOMUNE,
    ISTANZE.SOFTWARE,
    ISTANZE.IDMODELLO,
    ISTANZE.CODICEINTERVENTOPROC,
    ISTANZE.NUMEROISTANZA,
    ISTANZE.IDCOMUNE,
    ISTANZE.SETITOLARELEGALE,
    ISTANZE.FKIDTIPOLOGIAISTANZA,
    ISTANZE.CODICETITOLARELEGALE,
    ISTANZE.FKTOID,
    ISTANZE.METRIQUADRATI,
    ISTANZE.GIORNOCHIUSURA,
    ISTANZE.CODISTANZACOLLEGATA,
    ISTANZE.AZIONE,
    ISTANZE.FKIDREGISTRO,
    ISTANZE.NOMEATTIVITA,
    ISTANZE.FKIDFORMATO,
    ISTANZE.POSIZIONEARCHIVIO,
    ISTANZE.BASE,
    ISTANZE.ALTEZZA,
    ISTANZE.FACCE,
    ISTANZE.FKIDPROTOCOLLO,
    ISTANZE.FKCODICESOGGETTO,
    ISTANZE.CODICEISTRUTTORE,
    ISTANZE.CODICERESPONSABILEPROC,
    ISTANZE.CODICEAREA2,
    ISTANZE.FK_IDI_ATTIVITA,
    ISTANZE.DATAVALIDITA,
    ISTANZE.I_ATTIVITAORDINE,
    ISTANZE.CREATO_DA_STC,
    ISTANZE.DESCRSOGGETTO,
    ISTANZE.DOMICILIO_ELETTRONICO
  FROM ISTANZE,
    ISTANZEATTIVITA,
    ATTIVITA,
    SETTORI,
    AUTORIZZAZIONI,
    ISTANZEAREE
  WHERE ISTANZEATTIVITA.IDCOMUNE(+)   =ISTANZE.IDCOMUNE
  AND ISTANZEATTIVITA.CODICEISTANZA(+)=ISTANZE.CODICEISTANZA
  AND ATTIVITA.IDCOMUNE(+)            =ISTANZEATTIVITA.IDCOMUNE
  AND ATTIVITA.CODICEISTAT(+)         =ISTANZEATTIVITA.CODICEATTIVITA
  AND SETTORI.IDCOMUNE(+)             =ATTIVITA.IDCOMUNE
  AND SETTORI.CODICESETTORE(+)        =ATTIVITA.CODICESETTORE
  AND ISTANZEAREE.IDCOMUNE(+)         = ISTANZE.IDCOMUNE
  AND ISTANZEAREE.CODICEISTANZA(+)    = ISTANZE.CODICEISTANZA
  AND AUTORIZZAZIONI.IDCOMUNE(+)      = ISTANZE.IDCOMUNE
  AND AUTORIZZAZIONI.FKIDISTANZA(+)   = ISTANZE.CODICEISTANZA;

CREATE TABLE NLA_SERVIZI_ALTRI_DATI(
IDCOMUNE VARCHAR2(6) NOT NULL,
ID NUMBER(4,0) NOT NULL,
NOMEPARAMETRO VARCHAR2(50) NOT NULL,
VALORE VARCHAR2(200),
FK_NLASERVIZIID NUMBER(6,0) NOT NULL
);

ALTER TABLE NLA_SERVIZI_ALTRI_DATI ADD CONSTRAINT PK_NLA_SERVIZI_ALTRI_DATI PRIMARY KEY(IDCOMUNE, ID);
ALTER TABLE NLA_SERVIZI_ALTRI_DATI ADD CONSTRAINT FK_NSADATI_NLA_SERVIZI FOREIGN KEY(IDCOMUNE, FK_NLASERVIZIID) REFERENCES NLA_SERVIZI(IDCOMUNE, ID);
COMMENT ON TABLE NLA_SERVIZI_ALTRI_DATI IS 'La tabella contiene una lista di altri dati da popolare nella relativa sezione in DettaglioPraticaType';

CREATE TABLE DOCUMENTI_DA_FIRMARE (
    IDCOMUNE VARCHAR2(6 BYTE) NOT NULL,
    ID NUMBER(6,0) NOT NULL,
    CODICERICHIEDENTE NUMBER(4,0) NOT NULL,
    CODICEFIRMATARIO NUMBER(4,0) NOT NULL,
    DATA_RICHIESTA DATE,
    FLAG_DA_FIRMARE VARCHAR2(20 BYTE),
    DATA_FIRMA DATE,
    CODICEISTANZA NUMBER(6,0) NOT NULL,
    CODICEMOVALLEGATI NUMBER(8,0) NOT NULL,
    CODICEOGGETTO NUMBER(10,0) NOT NULL,
    ANNOTAZIONI_RICHIEDENTE VARCHAR2(4000 BYTE),
    ANNOTAZIONI_FIRMATARIO VARCHAR2(4000 BYTE),
    FLAG_LETTO NUMBER(1,0)
);

ALTER TABLE DOCUMENTI_DA_FIRMARE ADD CONSTRAINT DOCUMENTI_DA_FIRMARE_PK PRIMARY KEY (IDCOMUNE, ID);
ALTER TABLE DOCUMENTI_DA_FIRMARE ADD CONSTRAINT DOCUMENTI_DA_FIRMARE_RESP_FK2 FOREIGN KEY (IDCOMUNE, CODICEFIRMATARIO) REFERENCES RESPONSABILI (IDCOMUNE, CODICERESPONSABILE);
ALTER TABLE DOCUMENTI_DA_FIRMARE ADD CONSTRAINT DOCUMENTI_DA_FIRMARE_RESP_FK1 FOREIGN KEY (IDCOMUNE, CODICERICHIEDENTE) REFERENCES RESPONSABILI (IDCOMUNE, CODICERESPONSABILE);
ALTER TABLE DOCUMENTI_DA_FIRMARE ADD CONSTRAINT DOCUMENTI_DA_FIRMARE_ISTA_FK1 FOREIGN KEY (IDCOMUNE, CODICEISTANZA) REFERENCES ISTANZE (IDCOMUNE, CODICEISTANZA);
ALTER TABLE DOCUMENTI_DA_FIRMARE ADD CONSTRAINT DOCUMENTI_DA_FIRMARE_MOVI_FK1 FOREIGN KEY (IDCOMUNE, CODICEMOVALLEGATI) REFERENCES MOVIMENTIALLEGATI (IDCOMUNE, ID);
ALTER TABLE DOCUMENTI_DA_FIRMARE ADD CONSTRAINT DOCUMENTI_DA_FIRMARE_OGGE_FK1 FOREIGN KEY (IDCOMUNE, CODICEOGGETTO) REFERENCES OGGETTI (IDCOMUNE, CODICEOGGETTO);

ALTER TABLE I_ATTIVITADYN2DATI_SNAPSHOT ADD (AUTOINS NUMBER(1,0));
ALTER TABLE I_ATTIVITADYN2DATI ADD (AUTOINS NUMBER(1,0));
