

CREATE TABLE MERCATI_D_AVVISI  (
 IDCOMUNE VARCHAR2(6) NOT NULL, 
  ID NUMBER(10,0) NOT NULL,
  FK_ANGRAFE NUMBER (6,0) NOT NULL,
  FK_MERCATI_D NUMBER (6,0) NOT NULL,
  FK_CAUSALI_ONERI NUMBER (10,0) ,
  FLAG_VERIFICATO NUMBER (1,0)  NOT NULL
);

CREATE UNIQUE INDEX MERCATI_D_AVVISI_PK ON MERCATI_D_AVVISI (IDCOMUNE, ID) ; 
ALTER TABLE MERCATI_D_AVVISI ADD CONSTRAINT MERCATI_D_AVVISI_PK PRIMARY KEY (IDCOMUNE, ID);

ALTER TABLE MERCATI_D_AVVISI 
ADD CONSTRAINT FK_MERC_D_AVV_ANAGR FOREIGN KEY (IDCOMUNE, FK_ANGRAFE)
REFERENCES ANAGRAFE (IDCOMUNE, CODICEANAGRAFE);


ALTER TABLE MERCATI_D_AVVISI 
ADD CONSTRAINT  FK_MERC_D_AVV_POSTEGGIO FOREIGN KEY (IDCOMUNE, FK_MERCATI_D)
REFERENCES MERCATI_D (IDCOMUNE, IDPOSTEGGIO);

ALTER TABLE MERCATI_D_AVVISI 
ADD CONSTRAINT FK_MERC_D_AVV_CAUS_ONERI FOREIGN KEY (IDCOMUNE, FK_CAUSALI_ONERI)
REFERENCES TIPICAUSALIONERI (IDCOMUNE, CO_ID);

alter table MERCATI add FLAG_GESTISCI_POSIZIONI number(1,0) default 0;

alter table MERCATI_D add POSIZIONE number(4,0);
