
create table MERCATI_RESPONSABILI(
    IDCOMUNE VARCHAR2(6) NOT NULL,
    ID NUMBER(4,0),
    FK_CODICEMERCATO NUMBER(4,0),
    FK_CODICERESPONSABILE NUMBER(8,0)
);

ALTER TABLE MERCATI_RESPONSABILI ADD CONSTRAINT PK_MERCATIRESPONSABILI PRIMARY KEY(IDCOMUNE, ID);
ALTER TABLE MERCATI_RESPONSABILI ADD CONSTRAINT FK_MERCATIRESPONSABILI_MERCATI FOREIGN KEY(IDCOMUNE, FK_CODICEMERCATO) REFERENCES MERCATI (IDCOMUNE, CODICEMERCATO) ;

ALTER TABLE MERCATI_RESPONSABILI ADD CONSTRAINT FK_MERCATIRESPONSABILI_RESP FOREIGN KEY (IDCOMUNE,FK_CODICERESPONSABILE) REFERENCES RESPONSABILI (IDCOMUNE,CODICERESPONSABILE);

CREATE INDEX IDX_MERCRESPONSABILI_001 ON MERCATI_RESPONSABILI (IDCOMUNE,FK_CODICEMERCATO);
CREATE INDEX IDX_MERCRESPONSABILI_002 ON MERCATI_RESPONSABILI (IDCOMUNE,FK_CODICERESPONSABILE);

ALTER TABLE ANAGRAFE MODIFY REGDITTE VARCHAR2(25);
ALTER TABLE ANAGRAFE MODIFY REGTRIB VARCHAR2(25);

ALTER TABLE ANAGRAFESTORICO MODIFY REGDITTE VARCHAR2(25);
ALTER TABLE ANAGRAFESTORICO MODIFY REGTRIB VARCHAR2(25);

alter table tipicausalioneri modify CODICECAUSALEPEOPLE varchar2(50);



create index IDX_AUTORIZZAZIONI_ANAGRAFE ON AUTORIZZAZIONI(IDCOMUNE,fk_codiceanagrafe);

create table AMMINISTRAZIONI_ANAGRAFE(
    IDCOMUNE VARCHAR2(6) NOT NULL,
    ID NUMBER(6,0),
    FK_AMMINISTRAZIONE NUMBER(10,0) NOT NULL,
    FK_ANAGRAFE NUMBER(6,0) NOT NULL,
    INOLTRA_COMUNICAZIONE NUMBER(1,0)
);

ALTER TABLE AMMINISTRAZIONI_ANAGRAFE ADD CONSTRAINT PK_AMMINISTRAZIONI_ANAGRAFE PRIMARY KEY(IDCOMUNE, ID);
ALTER TABLE AMMINISTRAZIONI_ANAGRAFE ADD CONSTRAINT FK_AMMIN_ANAGR_AMM FOREIGN KEY(IDCOMUNE, FK_AMMINISTRAZIONE) REFERENCES AMMINISTRAZIONI (IDCOMUNE, CODICEAMMINISTRAZIONE);
ALTER TABLE AMMINISTRAZIONI_ANAGRAFE ADD CONSTRAINT FK_AMMIN_ANAGR_ANAGR FOREIGN KEY (IDCOMUNE,FK_ANAGRAFE) REFERENCES ANAGRAFE (IDCOMUNE,CODICEANAGRAFE);

CREATE INDEX IDX_AMMINISTR_ANAGR_001 ON AMMINISTRAZIONI_ANAGRAFE (IDCOMUNE,FK_AMMINISTRAZIONE);
CREATE INDEX IDX_AMMINISTR_ANAGR_002 ON AMMINISTRAZIONI_ANAGRAFE (IDCOMUNE,FK_ANAGRAFE);

CREATE TABLE MERCATIPRESENZE_T_PRENOT(
IDCOMUNE VARCHAR2(6),
ID NUMBER(6,0),
FKIDMERCATIPRESENZET NUMBER(6,0) NOT NULL,
DATA_INSERIMENTO DATE,
FKIDPOSTEGGIO  NUMBER(6,0),
CODICEANAGRAFE NUMBER(6,0),
NOTE VARCHAR2(4000)
);

ALTER TABLE MERCATIPRESENZE_T_PRENOT ADD CONSTRAINT PK_MERCATIPRESENZE_T_PRENOT PRIMARY KEY(IDCOMUNE,ID);
ALTER TABLE MERCATIPRESENZE_T_PRENOT ADD CONSTRAINT FK_MERCPREST_PRENOT_PREST FOREIGN KEY(IDCOMUNE, FKIDMERCATIPRESENZET) REFERENCES MERCATIPRESENZE_T(IDCOMUNE,ID);
ALTER TABLE MERCATIPRESENZE_T_PRENOT ADD CONSTRAINT FK_MERCPREST_PRENOT_ANAGR FOREIGN KEY(IDCOMUNE,CODICEANAGRAFE ) REFERENCES ANAGRAFE(IDCOMUNE,CODICEANAGRAFE);
ALTER TABLE MERCATIPRESENZE_T_PRENOT ADD CONSTRAINT FK_MERCPREST_PRENOT_MERCD FOREIGN KEY(IDCOMUNE,FKIDPOSTEGGIO ) REFERENCES MERCATI_D(IDCOMUNE,IDPOSTEGGIO);

CREATE INDEX IDX_MERCPRES_T_PRENOT_001 ON MERCATIPRESENZE_T_PRENOT (IDCOMUNE, FKIDMERCATIPRESENZET);
CREATE INDEX IDX_MERCPRES_T_PRENOT_002 ON MERCATIPRESENZE_T_PRENOT (IDCOMUNE,CODICEANAGRAFE);
CREATE INDEX IDX_MERCPRES_T_PRENOT_003 ON MERCATIPRESENZE_T_PRENOT (IDCOMUNE,FKIDPOSTEGGIO );


CREATE TABLE AUTORIZZAZIONI_ATTIVITA(
IDCOMUNE VARCHAR2(6),
ID NUMBER(10,0),
FK_IDAUTORIZZAZIONE NUMBER(6,0),
FK_CODICEISTAT VARCHAR2(15),
NOTE VARCHAR2(3000)

);

ALTER TABLE AUTORIZZAZIONI_ATTIVITA ADD CONSTRAINT PK_AUTORIZZAZIONI_ATTIVITA PRIMARY KEY(IDCOMUNE,ID);
ALTER TABLE AUTORIZZAZIONI_ATTIVITA ADD CONSTRAINT FK_AUTATTI_AUTORIZZAZIONI FOREIGN KEY(IDCOMUNE,FK_IDAUTORIZZAZIONE) REFERENCES AUTORIZZAZIONI(IDCOMUNE,ID);
ALTER TABLE AUTORIZZAZIONI_ATTIVITA ADD CONSTRAINT FK_AUTATTI_ATTIVITA FOREIGN KEY(IDCOMUNE,FK_CODICEISTAT) REFERENCES ATTIVITA(IDCOMUNE,CODICEISTAT);

CREATE INDEX IDX_AUTATTI_AUTORIZZAZIONI ON AUTORIZZAZIONI_ATTIVITA(IDCOMUNE,FK_IDAUTORIZZAZIONE) ;
CREATE INDEX IDX_AUTATTI_ATTIVITA ON AUTORIZZAZIONI_ATTIVITA(IDCOMUNE,FK_CODICEISTAT);
ALTER TABLE MERCATIPRESENZE_D ADD IMPORTO NUMBER(10,2);
ALTER TABLE MERCATIPRESENZE_D ADD FLAG_PAGATO NUMBER(1,0) DEFAULT 0;
ALTER TABLE MERCATIPRESENZE_D ADD RIF_PAGAMENTO VARCHAR2(50);
ALTER TABLE MERCATIPRESENZE_D ADD FK_MODPAGAM_ID NUMBER(10);
ALTER TABLE MERCATIPRESENZE_D ADD CONSTRAINT FK_MERCPRESD_MODPAG FOREIGN KEY(IDCOMUNE,FK_MODPAGAM_ID) REFERENCES TIPIMODALITAPAGAMENTO(IDCOMUNE,MP_ID);

CREATE INDEX IDX_mercatipresenzet_MERCATI ON mercatipresenze_t(IDCOMUNE,FKCODICEMERCATO);
CREATE INDEX IDX_mercatipresenzet_MERCUSO ON mercatipresenze_t(IDCOMUNE,fkidmercatiuso);

CREATE INDEX IDX_MERCPREST_001 ON MERCATIPRESENZE_T (IDCOMUNE,FKCODICEMERCATO,FKIDMERCATIUSO);
CREATE INDEX IDX_MERCPRESD_001 ON MERCATIPRESENZE_D (IDCOMUNE,FKIDTESTATA);

CREATE TABLE MERCATI_SPUNTE(
    IDCOMUNE VARCHAR2(6),
    ID NUMBER(4,0),
    CODICEMERCATO NUMBER(4,0),
    DESCRIZIONE VARCHAR2(50),
    FLAG_SEGNA_PRES NUMBER(1,0),
    ORDINE NUMBER(2,0)

);

ALTER TABLE MERCATI_SPUNTE ADD CONSTRAINT PK_MERCATI_SPUNTE PRIMARY KEY (IDCOMUNE, ID);
ALTER TABLE MERCATI_SPUNTE ADD CONSTRAINT FK_MERCATISPUNTE_MERC FOREIGN KEY(IDCOMUNE,CODICEMERCATO)REFERENCES MERCATI(IDCOMUNE,CODICEMERCATO);
CREATE INDEX IDX_MERCSPUNTE_001 ON MERCATI_SPUNTE(IDCOMUNE, CODICEMERCATO);


ALTER TABLE MERCATIPRESENZE_T ADD FK_MERCATISPUNTE_ID NUMBER(4,0);

ALTER TABLE MERCATIPRESENZE_D ADD FK_MERCATISPUNTE_ID NUMBER(4,0);

ALTER TABLE MERCATIPRESENZE_T ADD CONSTRAINT FK_MERCPREST_MERCSPUNTE FOREIGN KEY(IDCOMUNE,FK_MERCATISPUNTE_ID) REFERENCES MERCATI_SPUNTE(IDCOMUNE,ID);
ALTER TABLE MERCATIPRESENZE_D ADD CONSTRAINT FK_MERCPRESD_MERCSPUNTE FOREIGN KEY(IDCOMUNE,FK_MERCATISPUNTE_ID) REFERENCES MERCATI_SPUNTE(IDCOMUNE,ID);

CREATE INDEX IDX_MERCPREST_MERCSPU ON  MERCATIPRESENZE_T(IDCOMUNE,FK_MERCATISPUNTE_ID);
CREATE INDEX IDX_MERCPRESD_MERCSPU ON  MERCATIPRESENZE_D(IDCOMUNE,FK_MERCATISPUNTE_ID);

alter table responsabili add flag_dis_modanagrafe number(1,0) default 0;
comment on column responsabili.flag_dis_modanagrafe is 'Il flag toglie la possibilità di salvare le informazioni delle anagrafiche. Il comportamento vale solo per la modifica non per l''inserimento';

CREATE TABLE MESSAGGI_239_PROCESSATI(
          IDMESSAGGIO VARCHAR2(255),
          IDPRATICA VARCHAR2(255),
          TIPOMESSAGGIO VARCHAR2(100),
          DATA_INSERIMENTO DATE DEFAULT SYSDATE
);

ALTER TABLE MESSAGGI_239_PROCESSATI ADD CONSTRAINT PK_MESSAGGI_239_PROCESSATI PRIMARY KEY(IDMESSAGGIO);

CREATE TABLE ISTANZE_ET_ELABORATE (
  idcomune VARCHAR2(6) NOT NULL,
  codiceistanza NUMBER(6) NOT NULL,
  codiceamministrazione NUMBER(10) NOT NULL,
  flg_elaborata NUMBER(1) NOT null
);

ALTER TABLE ISTANZE_ET_ELABORATE
  ADD CONSTRAINT ISTANZE_ET_ELABORATE_pk PRIMARY KEY (
    idcomune,
    codiceistanza,
    codiceamministrazione
  );

ALTER TABLE ISTANZE_ET_ELABORATE
  ADD CONSTRAINT fk_ist_elab_istanze FOREIGN KEY (
    idcomune,
    codiceistanza
  ) REFERENCES istanze (
    idcomune,
    codiceistanza
  );

ALTER TABLE ISTANZE_ET_ELABORATE
  ADD CONSTRAINT fk_ist_elab_ammin FOREIGN KEY (
    idcomune,
    codiceamministrazione
  ) REFERENCES amministrazioni (
    idcomune,
    codiceamministrazione
  );

  
ALTER TABLE ALBEROPROC MODIFY FLAGESCLUDISORTEGGIO DEFAULT 0;