CREATE TABLE PROTOCOLLO_TIPIDOC_METADATI 
(
  IDCOMUNE VARCHAR2(6) NOT NULL 
, FKTIPODOCUMENTO NUMBER(10) NOT NULL 
, CODICE_METADATO VARCHAR2(50) NOT NULL 
, DESCRIZIONE_METADATO VARCHAR2(500) NOT NULL 
, CONSTRAINT PROTOCOLLO_TIPIDOC_METADAT_PK PRIMARY KEY 
  (
    IDCOMUNE 
  , FKTIPODOCUMENTO
  , CODICE_METADATO
  )
  ENABLE 
);

ALTER TABLE PROTOCOLLO_TIPIDOC_METADATI
ADD CONSTRAINT PROTOCOLLO_TIPIDOC_METADA_FK1 FOREIGN KEY
(
  IDCOMUNE 
, FKTIPODOCUMENTO 
)
REFERENCES PROTOCOLLO_TIPIDOCUMENTO
(
  IDCOMUNE 
, ID 
)
ENABLE;

ALTER TABLE ALBEROPROC MODIFY SC_CODICE VARCHAR2(34);