<?xml version="1.0" encoding="UTF-8"?>
<project name="star-core" default="sync-oscat-core">
	
	<property name="oscat.workspace" value="../../oscat_workspace"></property>
	<property name="oscat.core" value="star-core"></property>

	<target name="sync-oscat-core">
		<sync overwrite="false" todir="${oscat.workspace}/${oscat.core}" verbose="true" >
			<fileset dir="../${oscat.core}">
				<include name="src/**"/>
			</fileset>
		</sync>
	</target>
	
</project>