CREATE TABLE ALBEROPROC_COMUNI_ESCLUSI ( idcomune VARCHAR2(6 char) NOT NULL, fk_scid NUMBER(10,0) NOT NULL, codicecomune VARCHAR2(5 char) NOT NULL ); 
ALTER TABLE ALBEROPROC_COMUNI_ESCLUSI ADD PRIMARY KEY (idcomune, fk_scid, codicecomune); 
ALTER TABLE ALBEROPROC_COMUNI_ESCLUSI ADD CONSTRAINT FK_COMUNI_ESCLUSI_ALBERO FOREIGN KEY (idcomune, fk_scid) REFERENCES alberoproc (idcomune, sc_id); 
ALTER TABLE ALBEROPROC_COMUNI_ESCLUSI ADD CONSTRAINT FK_COMUNI_ESCLUSI_COMUNI FOREIGN KEY (codicecomune) REFERENCES comuni (codicecomune);
