# FILE PER PERSONALIZZARE COMPORTAMENTI DELLA COMPOMENTE RABBIT

# il parametro serve per indicare l'alias da non processare durante la richiesta degli alias attivi
# a ibcsecurity
servizio.rest.messaggi-rabbit.alias-da-escludere=
