UPDATE CONFIGURAZIONE SET MAIL_AMMENDO=NULL WHERE MAIL_AMMENDO=0;
UPDATE CONFIGURAZIONE SET MAIL_MOVIRIC=NULL WHERE MAIL_MOVIRIC=0;
UPDATE CONFIGURAZIONE SET MAIL_MOVIAMM=NULL WHERE MAIL_MOVIAMM=0;
UPDATE CONFIGURAZIONE SET MAIL_MOVINEG=NULL WHERE MAIL_MOVINEG=0;