<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup Label="Globals">
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<Configurations>Debug;Release</Configurations>
	</PropertyGroup>

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>
	
	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Markdig" Version="1.3.2" />
		<PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="18.7.23">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>

		<PackageReference Include="VBG.BlazorComponentsLibrary" Version="10.0.4" />
		<PackageReference Include="VBG.DatiDinamici.Agid" Version="10.1.10" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Frontoffice\Init.Sigepro.FrontEnd.AppLogic.ConnectedServices\Init.Sigepro.FrontEnd.AppLogic.ConnectedServices.csproj" />
		<ProjectReference Include="..\Frontoffice\Init.Sigepro.FrontEnd.AppLogic\Init.Sigepro.FrontEnd.AppLogic.csproj" />
		<ProjectReference Include="..\Frontoffice\Init.Sigepro.FrontEnd.Infrastructure\Init.Sigepro.FrontEnd.Infrastructure.csproj" />
	</ItemGroup>
	
</Project>
