<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	  <TargetFrameworks>net10.0;net48</TargetFrameworks>
	  <RootNamespace>Init.SIGePro.Manager.Authentication</RootNamespace>
	  <Configurations>Debug;Release</Configurations>
	  <Platforms>AnyCPU</Platforms>
	  <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SIGePro.Manager.Authentication\SIGePro.Manager.Authentication.csproj" />
    <ProjectReference Include="..\SIGePro.Manager.Configuration\SIGePro.Manager.Configuration.csproj" />
    <ProjectReference Include="..\SIGePro.Manager.IOC\SIGePro.Manager.IOC.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.ServiceModel.Http" Version="10.0.652802" />
  </ItemGroup>
</Project>