CREATE TABLE MOVIMENTI_IO_COMUNICAZIONI (IDCOMUNE VARCHAR2(6 CHAR) NOT NULL, CODICECOMUNE VARCHAR2(5 CHAR) NOT NULL, SOFTWARE VARCHAR2(2 CHAR) NOT NULL, CODICEMOVIMENTO NUMBER(8,0) NOT NULL, CODICEANAGRAFE NUMBER(6,0) NOT NULL, MESSAGE_ID VARCHAR2(36 CHAR) NOT NULL, FISCAL_CODE VARCHAR2(16 CHAR) NOT NULL, DATAINVIO DATE NOT NULL, SENDER_ALLOWED NUMBER(1,0) NOT NULL, CREATED_AT TIMESTAMP, NOTIFICATION_STATUS VARCHAR2(50 CHAR), NOTIFICATION_WEBHOOK VARCHAR2(50 CHAR), NOTIFICATION_EMAIL VARCHAR2(50 CHAR), ERRORE VARCHAR2(4000 CHAR), FLAG_COMPLETATO NUMBER(1,0) NOT NULL);
ALTER TABLE MOVIMENTI_IO_COMUNICAZIONI ADD CONSTRAINT PK_MOVIMENTI_IO_COMUNICAZIONI PRIMARY KEY(IDCOMUNE,CODICECOMUNE,SOFTWARE,CODICEMOVIMENTO,CODICEANAGRAFE);
ALTER TABLE MOVIMENTI_IO_COMUNICAZIONI ADD CONSTRAINT FK_MOVIMENTIIOCOM_MOVIMENTI FOREIGN KEY(IDCOMUNE,CODICEMOVIMENTO) REFERENCES MOVIMENTI (IDCOMUNE, CODICEMOVIMENTO);
ALTER TABLE MOVIMENTI_IO_COMUNICAZIONI ADD CONSTRAINT FK_MOVIMENTIIOCOM_ANAGRAFE FOREIGN KEY(IDCOMUNE,CODICEANAGRAFE) REFERENCES ANAGRAFE (IDCOMUNE, CODICEANAGRAFE);
ALTER TABLE MOVIMENTI_IO_COMUNICAZIONI ADD CONSTRAINT FK_MOVIMENTIIOCOM_COMUNI FOREIGN KEY(CODICECOMUNE) REFERENCES COMUNI (CODICECOMUNE);
ALTER TABLE MOVIMENTI_IO_COMUNICAZIONI ADD CONSTRAINT FK_MOVIMENTIIOCOM_SOFTWARE FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE (CODICE);
CREATE UNIQUE INDEX IDX_MOVIMENTIIOCOM_001 ON MOVIMENTI_IO_COMUNICAZIONI (MESSAGE_ID ASC);
CREATE INDEX IDX_MOVIMENTIIOCOM_002 ON MOVIMENTI_IO_COMUNICAZIONI(IDCOMUNE, CODICEMOVIMENTO);
CREATE INDEX IDX_MOVIMENTIIOCOM_003 ON MOVIMENTI_IO_COMUNICAZIONI(IDCOMUNE, CODICEANAGRAFE);
CREATE INDEX IDX_MOVIMENTIIOCOM_004 ON MOVIMENTI_IO_COMUNICAZIONI(CODICECOMUNE);
CREATE INDEX IDX_MOVIMENTIIOCOM_005 ON MOVIMENTI_IO_COMUNICAZIONI(SOFTWARE);
CREATE INDEX IDX_MOVIMENTIIOCOM_006 ON MOVIMENTI_IO_COMUNICAZIONI (FLAG_COMPLETATO ASC);
CREATE INDEX IDX_MOVIMENTI_IOAPP ON MOVIMENTI (PUBBLICA DESC, DATAPROTOCOLLO DESC);

CREATE TABLE CONFIGURAZIONE_APP_IO (
    IDCOMUNE VARCHAR2(6 CHAR) NOT NULL,
    CODICECOMUNE VARCHAR2(5 CHAR) NOT NULL,
    SOFTWARE VARCHAR2(2 CHAR) NOT NULL,
    URL_PORTALE_SERVIZI VARCHAR2(200 CHAR) NOT NULL
);
ALTER TABLE CONFIGURAZIONE_APP_IO ADD CONSTRAINT PK_CONFIGURAZIONE_APP_IO PRIMARY KEY(IDCOMUNE,CODICECOMUNE,SOFTWARE);
ALTER TABLE CONFIGURAZIONE_APP_IO ADD CONSTRAINT FK_CONFIGURAZIONEAPPIO_COMUNI FOREIGN KEY(CODICECOMUNE) REFERENCES COMUNI (CODICECOMUNE);
ALTER TABLE CONFIGURAZIONE_APP_IO ADD CONSTRAINT FK_CONFIGURAZIONEAPPIO_SOFT FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE (CODICE);
CREATE INDEX IDX_CONFIGURAZIONEAPPIO_001 ON CONFIGURAZIONE_APP_IO(CODICECOMUNE);
CREATE INDEX IDX_CONFIGURAZIONEAPPIO_002 ON CONFIGURAZIONE_APP_IO(SOFTWARE);

DROP INDEX PAY_POSDEB_UIDX;
CREATE UNIQUE INDEX PAY_POSDEB_UIDX ON PAY_POSIZIONI_DEBITORIE(IDCOMUNE,IUV);

ALTER TABLE CONCESSIONICAUSALI ADD FLAG_CAUSALI_AFFITTO NUMBER(1,0) DEFAULT 0;
ALTER TABLE AUTORIZZAZIONI ADD DATA_FINE_AFFITTO DATE;
ALTER TABLE AUTORIZZAZIONI_SUBENTRI ADD DATA_FINE_AFFITTO DATE;

ALTER TABLE PAY_CONNECTOR_WS_ENDPOINT MODIFY PASSWORD VARCHAR2(70);
ALTER TABLE DECODIFICHE MODIFY TABELLA VARCHAR2(100);


ALTER TABLE DECODIFICHE ADD ID NUMBER(10,0);

UPDATE DECODIFICHE SET id=rownum WHERE ID IS NULL;
