ALTER TABLE INVENTARIOPROCEDIMENTIONERI ADD DYN2CAMPI_ONERI_FRONT NUMERIC(10,0);
ALTER TABLE INVENTARIOPROCEDIMENTIONERI ADD FK_DYN2CAMPI_IDCOMUNE VARCHAR(6);

ALTER TABLE INVENTARIOPROCEDIMENTIONERI ADD CONSTRAINT FK_INVPROCON_DYN2C FOREIGN KEY (FK_DYN2CAMPI_IDCOMUNE,DYN2CAMPI_ONERI_FRONT) REFERENCES DYN2_CAMPI(IDCOMUNE,ID);

