CREATE TABLE PAY_POS_DEB_MASSIVE(
IDCOMUNE VARCHAR(6) NOT NULL,
ID NUMERIC(9,0) NOT NULL,
FK_POSIZIONE_DEBITORIA NUMERIC(9,0) NOT NULL,
ID_OPERAZIONE VARCHAR(100) NOT NULL,
FLAG_PROCESSATA VARCHAR(1) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8;

ALTER TABLE PAY_POS_DEB_MASSIVE ADD CONSTRAINT PK_PAY_POS_DEB_MASSIVE PRIMARY KEY (IDCOMUNE,ID);

ALTER TABLE PAY_POS_DEB_MASSIVE ADD CONSTRAINT FK_PAYPOSDEBMASS_PAYPOS FOREIGN KEY (IDCOMUNE,FK_POSIZIONE_DEBITORIA) REFERENCES PAY_POSIZIONI_DEBITORIE(IDCOMUNE,ID);

ALTER TABLE boll_cfg_tipo ADD FLAG_CARICAM_MASSIVO NUMERIC(1,0) NOT NULL DEFAULT 0;