#PARAMETRI DI DEPLOY
#
##------------LISTA DEGLI IDCOMUNE CHE INDIVIDUANO UNA INSTALLAZIONE MASTER----------------------##
# Nella proprietà [installazione.master.idcomune.codici] vengono definiti i vari identificativi 
# (IDCOMUNE) della base dati che individuano una installazione MASTER. Gli identificativi sono separati da virgola 
##-----------------------------------------------------------------------------------------------##
installazione.master.idcomune.codici=

# WEB SERVICE SIGEPROSECURITY
ws.token.pwd=REDACTED
ws.token.url=REDACTED
ws.token.user=REDACTED

# PARAMETRI DELLO SCHEDULER
# abilita o disabilita lo scheduler
scheduler.autoStartup=false
# rappresenta l'alias dove sono memorizzati i job dello scheduler
scheduler.idcomunealias=E256
