# GENERALE 
## IL PARAMETRO NON FA ESEGUIRE LE SCHEDULAZIONI DI SISTEMA (DEVE ESSERE COMUNQUE ABILITATO SU DEPLOY.PROPERTIES SCHEDULER ENABLED)
scheduler.abilita.attivita.sistema=true
# SEZIONE PARAMETRI CLASSI JOB SISTEMA
scheduler.ScadenzeAutorizzazioniConcessioniJob.cron=0 5 20 ? * * *

## esegui accetta true o false se non specificato allora true
scheduler.ScadenzeAutorizzazioniConcessioniJob.esegui=true

## LISTA_ALIAS_DA_ELABORARE ACCETTA UNA LISTA DI ALIAS SEPARATI DA VIRGOLA (,) 
# scheduler.ScadenzeAutorizzazioniConcessioniJob.param.LISTA_ALIAS_DA_ELABORARE=E256
