SET IMPLICIT_TRANSACTIONS ON
GO
ALTER TABLE ANAGRAFE ADD CONSTRAINT FK_ANAGRAFE_COMUNI_CITTAD FOREIGN KEY(CODICECITTADINANZA) REFERENCES CITTADINANZA(CODICE)
GO
COMMIT
GO
ALTER TABLE ANAGRAFESTORICO ADD CONSTRAINT FK_ANAGRASTOR_COMUNI_CITTAD FOREIGN KEY(CODICECITTADINANZA) REFERENCES CITTADINANZA(CODICE)
GO
COMMIT
GO