ALTER TABLE MERCATIPRESENZE_T ADD FLAG_CHIUSURA_APPELLO NUMBER(1,0);
ALTER TABLE MERCATIPRESENZE_T ADD DATA_CHIUSURA_APPELLO DATE;
ALTER TABLE MERCATIPRESENZE_T ADD RESP_CHIUSURA_APPELLO NUMBER(8,0);
ALTER TABLE MERCATIPRESENZE_T ADD CONSTRAINT FK_MERCPREST_RESPAPPELLO FOREIGN KEY(IDCOMUNE, RESP_CHIUSURA_APPELLO) REFERENCES RESPONSABILI(IDCOMUNE,CODICERESPONSABILE);
CREATE INDEX IDX_MERCPREST_RESPAPPELLO ON MERCATIPRESENZE_T(IDCOMUNE,RESP_CHIUSURA_APPELLO);

ALTER TABLE MERCATI_SPUNTE ADD FLAG_FILTRO_CATMERC NUMBER(1,0);

alter table autorizzazioni add note_sistema varchar2(4000);
alter table autorizzazioni add note varchar2(4000);

ALTER TABLE mercatipresenze_d add fk_codiceistat varchar2(15);
alter table mercatipresenze_d add constraint fk_mercpresenzed_istat foreign key (idcomune,fk_codiceistat) references attivita(idcomune,codiceistat);


alter table autorizzazioni add autorig_numero varchar2(40);
alter table autorizzazioni add autorig_data date;
alter table autorizzazioni add autorig_codcomune VARCHAR2(5);



alter table mercatipresenze_d add flag_rinuncia_presenza number(1,0);

CREATE TABLE POSTEGGI_SETTORI(
IDCOMUNE                VARCHAR2(6)  NOT NULL,
ID                      NUMBER(4,0) NOT NULL,
CODICESETTORE           VARCHAR2(10) NOT NULL, 
SETTORE                 VARCHAR2(50)
);

ALTER TABLE POSTEGGI_SETTORI ADD CONSTRAINT PK_POSTEGGI_SETTORI PRIMARY KEY(IDCOMUNE,ID);

ALTER TABLE MERCATI_D ADD FK_POSTEGGISETTORI_ID NUMBER(4,0);
ALTER TABLE MERCATI_D ADD CONSTRAINT FK_MERCATID_POSTSETT_ID FOREIGN KEY (IDCOMUNE,FK_POSTEGGISETTORI_ID) REFERENCES POSTEGGI_SETTORI(IDCOMUNE,ID);

alter table mercati_d add identificativo_percorso number(4,0);

CREATE OR REPLACE VIEW VW_COMUNIASSOCIATIINFO AS SELECT COMUNIASSOCIATI.*, COMUNI.CODICEISTAT FROM COMUNIASSOCIATI INNER JOIN COMUNI ON COMUNIASSOCIATI.CODICECOMUNE = COMUNI.CODICECOMUNE;


create table AUTORIZZAZIONI_SUBENTRI_CONC(
IDCOMUNE          VARCHAR2(6)  NOT NULL ,
ID                  NUMBER(6,0) NOT NULL,
FK_AUTSUB_ID        NUMBER(6,0) NOT NULL,
FK_CODICEMERCATO            NUMBER(4,0),   
FK_IDMERCATIUSO             NUMBER(4,0),  
FK_IDPOSTEGGIO              NUMBER(6,0),   
FK_TIPOCONCESSIONE          VARCHAR2(2), 
STAGIONALEDA                VARCHAR2(4),
STAGIONALEA                 VARCHAR2(4),
DATASCADENZA                DATE,
FK_IDAUT_ATTUALE            NUMBER(6,0),
FK_IDAUT_COLLEGATA          NUMBER(6,0)   
);

alter table AUTORIZZAZIONI_SUBENTRI_CONC ADD CONSTRAINT PK_AUTO_SUBENTRI_CONC PRIMARY KEY(IDCOMUNE,ID);

alter table AUTORIZZAZIONI_SUBENTRI_CONC ADD CONSTRAINT FK_AUTSUBCONC_MERCATI FOREIGN KEY(IDCOMUNE,FK_CODICEMERCATO) REFERENCES MERCATI(IDCOMUNE,CODICEMERCATO);
CREATE INDEX IDX_AUTSUBCONC_001 ON AUTORIZZAZIONI_SUBENTRI_CONC (IDCOMUNE,FK_CODICEMERCATO);

alter table AUTORIZZAZIONI_SUBENTRI_CONC ADD CONSTRAINT FK_AUTSUBCONC_MERCUSO FOREIGN KEY(IDCOMUNE,FK_IDMERCATIUSO) REFERENCES MERCATI_USO(IDCOMUNE,ID);
CREATE INDEX IDX_AUTSUBCONC_002 ON AUTORIZZAZIONI_SUBENTRI_CONC(IDCOMUNE,FK_IDMERCATIUSO);


alter table AUTORIZZAZIONI_SUBENTRI_CONC ADD CONSTRAINT FK_AUTSUBCONC_POSTEGGI FOREIGN KEY(IDCOMUNE,FK_IDPOSTEGGIO) REFERENCES MERCATI_D(IDCOMUNE,IDPOSTEGGIO);
CREATE INDEX IDX_AUTSUBCONC_003 ON AUTORIZZAZIONI_SUBENTRI_CONC(IDCOMUNE,FK_IDPOSTEGGIO);


alter table AUTORIZZAZIONI_SUBENTRI_CONC ADD CONSTRAINT FK_AUTSUBCONC_AUT FOREIGN KEY(IDCOMUNE,FK_IDAUT_ATTUALE) REFERENCES AUTORIZZAZIONI(IDCOMUNE,ID);
CREATE INDEX IDX_AUTSUBCONC_004 ON AUTORIZZAZIONI_SUBENTRI_CONC(IDCOMUNE,FK_IDAUT_ATTUALE);


alter table AUTORIZZAZIONI_SUBENTRI_CONC ADD CONSTRAINT FK_AUTSUBCONC_AUTCOL FOREIGN KEY(IDCOMUNE,FK_IDAUT_COLLEGATA) REFERENCES AUTORIZZAZIONI(IDCOMUNE,ID);
CREATE INDEX IDX_AUTSUBCONC_005 ON AUTORIZZAZIONI_SUBENTRI_CONC(IDCOMUNE,FK_IDAUT_COLLEGATA);

alter table AUTORIZZAZIONI_SUBENTRI_CONC ADD CONSTRAINT FK_AUTSUBCONC_CONCTIPI FOREIGN KEY(FK_TIPOCONCESSIONE) REFERENCES CONCESSIONITIPI(TIPOCONCESSIONE);

alter table AUTORIZZAZIONI_SUBENTRI_CONC ADD CONSTRAINT FK_AUTSUBCONC_AUTSUB FOREIGN KEY(IDCOMUNE,FK_AUTSUB_ID) REFERENCES AUTORIZZAZIONI_SUBENTRI(IDCOMUNE,ID);
CREATE INDEX IDX_AUTSUBCONC_006 ON AUTORIZZAZIONI_SUBENTRI_CONC(IDCOMUNE,FK_AUTSUB_ID);




create table AUTORIZZAZIONI_SOGGETTI (
IDCOMUNE VARCHAR2(6) NOT NULL,
ID NUMBER(6,0) NOT NULL,
FK_AUTORIZZAZIONI_ID NUMBER(6,0) NOT NULL, 
FK_CODICEANAGRAFE NUMBER(6,0) NOT NULL );

ALTER TABLE AUTORIZZAZIONI_SOGGETTI ADD CONSTRAINT PK_AUTORIZZAZIONI_SOGGETTI PRIMARY KEY(IDCOMUNE,ID); 
ALTER TABLE AUTORIZZAZIONI_SOGGETTI ADD CONSTRAINT FK_AUTSOGGETTI_ANAGRAFE FOREIGN KEY(IDCOMUNE,FK_CODICEANAGRAFE) REFERENCES ANAGRAFE (IDCOMUNE,CODICEANAGRAFE); 
CREATE INDEX IDX_AUTSOGG_001 ON AUTORIZZAZIONI_SOGGETTI(IDCOMUNE,FK_CODICEANAGRAFE);

ALTER TABLE AUTORIZZAZIONI_SOGGETTI ADD CONSTRAINT FK_AUTSOGGETTI_AUTORIZZAZIONI FOREIGN KEY(IDCOMUNE,FK_AUTORIZZAZIONI_ID) REFERENCES AUTORIZZAZIONI (IDCOMUNE,ID); 
CREATE INDEX IDX_AUTSOGG_002 ON AUTORIZZAZIONI_SOGGETTI(IDCOMUNE,FK_AUTORIZZAZIONI_ID);


CREATE TABLE AUTORIZZAZIONI_CSI (
IDCOMUNE VARCHAR2(6) NOT NULL,
ID NUMBER(10,0) NOT NULL,
FK_AUTORIZZAZIONI_ID NUMBER(6,0),
FK_CODICEGERENTE  NUMBER(6,0),
STATO_AUTORIZZAZIONE VARCHAR2(50),
STATO_WARNING VARCHAR2(50),
VALIDA_SPUNTA NUMBER(1,0),
CAUSALE_SOSPENSIONE VARCHAR2(30),
DATA_SOSP_DA DATE,
DATA_SOSP_A DATE,
DATA_INIZIO_GERENZA DATE,
DATA_FINE_GERENZA DATE
);

ALTER TABLE AUTORIZZAZIONI_CSI ADD CONSTRAINT PK_AUTORIZZAZIONI_CSI PRIMARY KEY(IDCOMUNE,ID);

ALTER TABLE AUTORIZZAZIONI_CSI ADD CONSTRAINT FK_AUTORIZ_CSI_AUTORIZ FOREIGN KEY(IDCOMUNE,FK_AUTORIZZAZIONI_ID) REFERENCES AUTORIZZAZIONI(IDCOMUNE,ID);
CREATE INDEX IDX_AUTORIZZAZIONI_CSI_001 ON AUTORIZZAZIONI_CSI (IDCOMUNE,FK_AUTORIZZAZIONI_ID);

ALTER TABLE AUTORIZZAZIONI_CSI ADD CONSTRAINT FK_AUTORIZ_CSI_ANAG FOREIGN KEY(IDCOMUNE,FK_CODICEGERENTE) REFERENCES ANAGRAFE(IDCOMUNE,CODICEANAGRAFE);
CREATE INDEX IDX_AUTORIZZAZIONI_CSI_002 ON AUTORIZZAZIONI_CSI (IDCOMUNE,FK_CODICEGERENTE);

ALTER TABLE AUTORIZZAZIONI_CSI ADD AUT_PRECEDENTE_NUMERO VARCHAR2(50);
ALTER TABLE AUTORIZZAZIONI_CSI ADD AUT_PRECEDENTE_DATA DATE;
ALTER TABLE AUTORIZZAZIONI_CSI ADD AUT_PRECEDENTE_COMUNE VARCHAR2(5);

CREATE INDEX IDX_AUTORIZZAZIONI_CSI_003 ON AUTORIZZAZIONI_CSI(IDCOMUNE, AUT_PRECEDENTE_NUMERO);




ALTER TABLE  AUTORIZZAZIONI_SUBENTRI DROP COLUMN STAGIONALE_DA;
ALTER TABLE  AUTORIZZAZIONI_SUBENTRI DROP COLUMN STAGIONALE_A;

ALTER TABLE  AUTORIZZAZIONI_SUBENTRI add STAGIONALE_DA VARCHAR2(4);
ALTER TABLE  AUTORIZZAZIONI_SUBENTRI add STAGIONALE_A VARCHAR2(4);

UPDATE AUTORIZZAZIONI_SUBENTRI SET AUTORIZZAZIONI_SUBENTRI.STAGIONALE_DA = (SELECT AUTORIZZAZIONI_CONCESSIONI.STAGIONALEDA
                                  FROM AUTORIZZAZIONI_CONCESSIONI 
                                  WHERE AUTORIZZAZIONI_SUBENTRI.idcomune = AUTORIZZAZIONI_CONCESSIONI.idcomune and
                                  AUTORIZZAZIONI_SUBENTRI.FK_IDAUT_ATTUALE = AUTORIZZAZIONI_CONCESSIONI.FK_IDAUT_ATTUALE )
WHERE AUTORIZZAZIONI_SUBENTRI.STAGIONALE_DA is null
AND EXISTS (SELECT 1
            FROM AUTORIZZAZIONI_CONCESSIONI 
            WHERE  AUTORIZZAZIONI_SUBENTRI.idcomune = AUTORIZZAZIONI_CONCESSIONI.idcomune and
                                  AUTORIZZAZIONI_SUBENTRI.FK_IDAUT_ATTUALE = AUTORIZZAZIONI_CONCESSIONI.FK_IDAUT_ATTUALE);
                                  
  UPDATE AUTORIZZAZIONI_SUBENTRI SET AUTORIZZAZIONI_SUBENTRI.STAGIONALE_A = (SELECT AUTORIZZAZIONI_CONCESSIONI.STAGIONALEA
  FROM AUTORIZZAZIONI_CONCESSIONI 
  WHERE AUTORIZZAZIONI_SUBENTRI.idcomune = AUTORIZZAZIONI_CONCESSIONI.idcomune and
                                  AUTORIZZAZIONI_SUBENTRI.FK_IDAUT_ATTUALE = AUTORIZZAZIONI_CONCESSIONI.FK_IDAUT_ATTUALE )
WHERE AUTORIZZAZIONI_SUBENTRI.STAGIONALE_A is null
AND EXISTS (SELECT 1
            FROM AUTORIZZAZIONI_CONCESSIONI 
            WHERE  AUTORIZZAZIONI_SUBENTRI.idcomune = AUTORIZZAZIONI_CONCESSIONI.idcomune and
                                  AUTORIZZAZIONI_SUBENTRI.FK_IDAUT_ATTUALE = AUTORIZZAZIONI_CONCESSIONI.FK_IDAUT_ATTUALE);


ALTER TABLE AUTORIZZAZIONI_SUBENTRI_CONC DROP COLUMN FK_IDAUT_COLLEGATA CASCADE CONSTRAINTS;
ALTER TABLE AUTORIZZAZIONI_SUBENTRI_CONC ADD FK_IDAUTSUB_AUTCOLL NUMBER(6,0);

ALTER TABLE AUTORIZZAZIONI_SUBENTRI_CONC ADD CONSTRAINT FK_IDAUTSUB_AUTSUBCOLL_CONC FOREIGN KEY (IDCOMUNE, FK_IDAUTSUB_AUTCOLL)
            REFERENCES AUTORIZZAZIONI_SUBENTRI (IDCOMUNE, ID) ;

CREATE INDEX IDX_AUT_SUB_CONC_001 ON AUTORIZZAZIONI_SUBENTRI_CONC (IDCOMUNE, FK_IDAUTSUB_AUTCOLL);

CREATE OR REPLACE VIEW VW_ISTANZECONCESSIONILISTA AS SELECT 99999999 AS PROGRESSIVO, AUTORIZZAZIONI.AUTORIZRESPONSABILE AS CONC_AUTORIZRESPONSABILE, AUTORIZZAZIONI.IDCOMUNE, AUTORIZZAZIONI.FK_CAUSALE_ACQUISIZIONE AS ICONC_CODICECAUSALE, NVL(AUTORIZZAZIONI.DATA_CESSAZIONE,TO_DATE('31/12/9999','DD/MM/YYYY')) AS DATA_STORICO, ISTANZE.SOFTWARE, ISTANZE.CODICEISTANZA AS IST_CODICEISTANZA, ISTANZE.NUMEROISTANZA AS IST_NUMEROISTANZA, ISTANZE.CODICERICHIEDENTE AS IST_CODICERICHIEDENTE, AUTORIZZAZIONI.ID AS CONC_ID, AUTORIZZAZIONI.AUTORIZNUMERO AS CONC_NUMERO, AUTORIZZAZIONI.AUTORIZDATA AS CONC_DATARILASCIO, AUTORIZZAZIONI.AUTORIZDATA AS DATARILASCIO, AUTORIZZAZIONI.DATASCADENZA AS CONC_DATASCADENZA, AUTORIZZAZIONI_CONCESSIONI.FK_TIPOCONCESSIONE AS CONC_CODICETIPO, CONCESSIONITIPI.DESCRIZIONE AS CONC_TIPO, AUTORIZZAZIONI_CONCESSIONI.STAGIONALEA AS CONC_STAGIONALEA, AUTORIZZAZIONI_CONCESSIONI.STAGIONALEDA AS CONC_STAGIONALEDA, AUTORIZZAZIONI.FLAG_ATTIVA AS CONC_ATTIVA, AUTORIZZAZIONI.FK_CODICEANAGRAFE AS CONC_CODICETITOLARE, AUTORIZZAZIONI.FKIDREGISTRO AS CONC_FKIDREGISTRO, CONC_REGISTRO.TR_DESCRIZIONE AS CONC_REGISTRO, TITOLARE.NOMINATIVO || ' ' || TITOLARE.NOME AS CONC_TITOLARE, TITOLARE.CODICEFISCALE AS CONC_TIT_CF, TITOLARE.PARTITAIVA AS CONC_TIT_PIVA, TITOLARE.TIPOANAGRAFE AS CONC_TIT_TIPOANAGRAFE, AUT_COLLEGATA.AUTORIZNUMERO AS AUT_NUMERO, AUT_COLLEGATA.AUTORIZDATA AS AUT_DATA, AUT_COLLEGATA.AUTORIZDATA, AUT_COLLEGATA.FKIDREGISTRO AS AUT_CODREGISTRO, TIPOLOGIAREGISTRI.TR_DESCRIZIONE AS AUT_REGISTRO, IST_RICHIEDENTE.NOMINATIVO || ' ' || IST_RICHIEDENTE.NOME AS IST_NOMINATIVO, IST_RICHIEDENTE.TIPOANAGRAFE AS IST_RIC_TIPOANAGRAFE, IST_AZIENDA.NOMINATIVO || ' ' || IST_AZIENDA.NOME AS IST_NOMINATIVOAZIENDA, IST_AZIENDA.TIPOANAGRAFE AS IST_AZI_TIPOANAGRAFE, IST_RICHIEDENTE.CODICEFISCALE AS IST_CODICEFISCALE, IST_RICHIEDENTE.PARTITAIVA AS IST_PARTITAIVA, CAUS_ATTUALE.DESCRIZIONE AS ICONC_CAUSALE, AUTORIZZAZIONI.FK_CAUSALE_CESSAZIONE AS ICONC_CODICECAUSALESTORICO, CAUS_STORICO.DESCRIZIONE AS ICONC_CAUSALESTORICO, AUTORIZZAZIONI_CONCESSIONI.FK_CODICEMERCATO AS CONC_IDMERCATO, MERCATI.DESCRIZIONE AS CONC_MERCATO, MERCATI.ATTIVO AS MERC_ATTIVO, AUTORIZZAZIONI_CONCESSIONI.FK_IDPOSTEGGIO AS CONC_IDPOSTEGGIO, MERCATI_D.CODICEPOSTEGGIO AS CONC_POSTEGGIO, MERCATI_D.LARGHEZZA AS CONC_POS_LARGHEZZA, MERCATI_D.LUNGHEZZA AS CONC_POS_LUNGHEZZA, MERCATI_D.SUPERFICIE AS CONC_POS_SUPERFICIE, MERCATI_D.FKCODICETIPOSPAZIO AS POST_IDTIPOSPAZIO, POSTEGGITIPOSPAZIO.TIPOSPAZIO AS POST_TIPOSPAZIO, AUTORIZZAZIONI_CONCESSIONI.FK_IDMERCATIUSO AS CONC_IDMERCATIUSO, MERCATI_USO.DESCRIZIONE AS CONC_DESCRIZIONEUSO, MERCATI_USO.PESO AS PESO_MERCATO, MERCATI_USO.FKCODICEUSO AS MERC_IDUSO, MERCATI_D.FKCODICESTRADARIO AS CONC_POS_CODICESTRADARIO, MERCATI_D.NOTE AS CONC_POS_NOTE, VW_ENTILOCALI.COMUNE AS CONC_ENTERILASCIO FROM AUTORIZZAZIONI INNER JOIN TIPOLOGIAREGISTRI CONC_REGISTRO ON AUTORIZZAZIONI.IDCOMUNE = CONC_REGISTRO.IDCOMUNE AND AUTORIZZAZIONI.FKIDREGISTRO = CONC_REGISTRO.TR_ID INNER JOIN AUTORIZZAZIONI_CONCESSIONI ON AUTORIZZAZIONI.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND AUTORIZZAZIONI.ID = AUTORIZZAZIONI_CONCESSIONI.FK_IDAUT_ATTUALE LEFT  JOIN AUTORIZZAZIONI AUT_COLLEGATA ON AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE = AUT_COLLEGATA.IDCOMUNE AND AUTORIZZAZIONI_CONCESSIONI.FK_IDAUT_COLLEGATA = AUT_COLLEGATA.ID LEFT  JOIN TIPOLOGIAREGISTRI ON AUT_COLLEGATA.IDCOMUNE = TIPOLOGIAREGISTRI.IDCOMUNE AND AUT_COLLEGATA.FKIDREGISTRO = TIPOLOGIAREGISTRI.TR_ID INNER JOIN CONCESSIONITIPI ON AUTORIZZAZIONI_CONCESSIONI.FK_TIPOCONCESSIONE = CONCESSIONITIPI.TIPOCONCESSIONE INNER JOIN ANAGRAFE TITOLARE ON AUTORIZZAZIONI.IDCOMUNE = TITOLARE.IDCOMUNE AND AUTORIZZAZIONI.FK_CODICEANAGRAFE = TITOLARE.CODICEANAGRAFE INNER JOIN CONCESSIONICAUSALI CAUS_ATTUALE ON AUTORIZZAZIONI.IDCOMUNE = CAUS_ATTUALE.IDCOMUNE AND AUTORIZZAZIONI.FK_CAUSALE_ACQUISIZIONE = CAUS_ATTUALE.CODICECAUSALE LEFT  JOIN CONCESSIONICAUSALI CAUS_STORICO ON AUTORIZZAZIONI.IDCOMUNE = CAUS_STORICO.IDCOMUNE AND AUTORIZZAZIONI.FK_CAUSALE_CESSAZIONE = CAUS_STORICO.CODICECAUSALE INNER JOIN ISTANZE ON AUTORIZZAZIONI.IDCOMUNE = ISTANZE.IDCOMUNE AND AUTORIZZAZIONI.FKIDISTANZA = ISTANZE.CODICEISTANZA INNER JOIN ANAGRAFE IST_RICHIEDENTE ON ISTANZE.IDCOMUNE = IST_RICHIEDENTE.IDCOMUNE AND ISTANZE.CODICERICHIEDENTE = IST_RICHIEDENTE.CODICEANAGRAFE INNER JOIN MERCATI ON AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE = MERCATI.IDCOMUNE AND AUTORIZZAZIONI_CONCESSIONI.FK_CODICEMERCATO = MERCATI.CODICEMERCATO INNER JOIN MERCATI_D ON AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE = MERCATI_D.IDCOMUNE AND AUTORIZZAZIONI_CONCESSIONI.FK_IDPOSTEGGIO = MERCATI_D.IDPOSTEGGIO LEFT  JOIN POSTEGGITIPOSPAZIO ON MERCATI_D.IDCOMUNE = POSTEGGITIPOSPAZIO.IDCOMUNE AND MERCATI_D.FKCODICETIPOSPAZIO = POSTEGGITIPOSPAZIO.CODICE INNER JOIN MERCATI_USO ON AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE = MERCATI_USO.IDCOMUNE AND AUTORIZZAZIONI_CONCESSIONI.FK_IDMERCATIUSO = MERCATI_USO.ID LEFT  JOIN ANAGRAFE IST_AZIENDA ON ISTANZE.IDCOMUNE = IST_AZIENDA.IDCOMUNE AND ISTANZE.CODICETITOLARELEGALE = IST_AZIENDA.CODICEANAGRAFE INNER JOIN VW_ENTILOCALI ON AUTORIZZAZIONI.AUTORIZCOMUNE = VW_ENTILOCALI.CODICECOMUNE UNION SELECT AUTORIZZAZIONI_SUBENTRI.ID AS PROGRESSIVO, AUTORIZZAZIONI_SUBENTRI.AUTORIZRESPONSABILE AS CONC_AUTORIZRESPONSABILE, AUTORIZZAZIONI_SUBENTRI.IDCOMUNE, AUTORIZZAZIONI_SUBENTRI.FK_CAUSALE_ACQUISIZIONE AS ICONC_CODICECAUSALE, AUTORIZZAZIONI_SUBENTRI.DATA_CESSAZIONE AS DATA_STORICO, ISTANZE.SOFTWARE, ISTANZE.CODICEISTANZA AS IST_CODICEISTANZA, ISTANZE.NUMEROISTANZA AS IST_NUMEROISTANZA, ISTANZE.CODICERICHIEDENTE AS IST_CODICERICHIEDENTE, AUTORIZZAZIONI_SUBENTRI.FK_IDAUT_ATTUALE AS CONC_ID, AUTORIZZAZIONI_SUBENTRI.AUTORIZNUMERO AS CONC_NUMERO, AUTORIZZAZIONI_SUBENTRI.AUTORIZDATA AS CONC_DATARILASCIO, AUTORIZZAZIONI_SUBENTRI.AUTORIZDATA AS DATARILASCIO, AUTORIZZAZIONI_SUBENTRI.DATASCADENZA AS CONC_DATASCADENZA, AUTORIZZAZIONI_SUBENTRI_CONC.FK_TIPOCONCESSIONE AS CONC_CODICETIPO, CONCESSIONITIPI.DESCRIZIONE AS CONC_TIPO, AUTORIZZAZIONI_SUBENTRI_CONC.STAGIONALEA AS CONC_STAGIONALEA, AUTORIZZAZIONI_SUBENTRI_CONC.STAGIONALEDA AS CONC_STAGIONALEDA, 0 AS CONC_ATTIVA, AUTORIZZAZIONI_SUBENTRI.FK_CODICEANAGRAFE AS CONC_CODICETITOLARE, AUTORIZZAZIONI_SUBENTRI.FKIDREGISTRO AS CONC_FKIDREGISTRO, CONC_REGISTRO.TR_DESCRIZIONE AS CONC_REGISTRO, TITOLARE.NOMINATIVO || ' ' || TITOLARE.NOME AS CONC_TITOLARE, TITOLARE.CODICEFISCALE AS CONC_TIT_CF, TITOLARE.PARTITAIVA AS CONC_TIT_PIVA, TITOLARE.TIPOANAGRAFE AS CONC_TIT_TIPOANAGRAFE, AUT_COLLEGATA.AUTORIZNUMERO AS AUT_NUMERO, AUT_COLLEGATA.AUTORIZDATA AS AUT_DATA, AUT_COLLEGATA.AUTORIZDATA, AUT_COLLEGATA.FKIDREGISTRO AS AUT_CODREGISTRO, TIPOLOGIAREGISTRI.TR_DESCRIZIONE AS AUT_REGISTRO, IST_RICHIEDENTE.NOMINATIVO || ' ' || IST_RICHIEDENTE.NOME AS IST_NOMINATIVO, IST_RICHIEDENTE.TIPOANAGRAFE AS IST_RIC_TIPOANAGRAFE, IST_AZIENDA.NOMINATIVO || ' ' || IST_AZIENDA.NOME AS IST_NOMINATIVOAZIENDA, IST_AZIENDA.TIPOANAGRAFE AS IST_AZI_TIPOANAGRAFE, IST_RICHIEDENTE.CODICEFISCALE AS IST_CODICEFISCALE, IST_RICHIEDENTE.PARTITAIVA AS IST_PARTITAIVA, CAUS_ATTUALE.DESCRIZIONE AS ICONC_CAUSALE, AUTORIZZAZIONI_SUBENTRI.FK_CAUSALE_CESSAZIONE AS ICONC_CODICECAUSALESTORICO, CAUS_STORICO.DESCRIZIONE AS ICONC_CAUSALESTORICO, AUTORIZZAZIONI_SUBENTRI_CONC.FK_CODICEMERCATO AS CONC_IDMERCATO, MERCATI.DESCRIZIONE AS CONC_MERCATO, MERCATI.ATTIVO AS MERC_ATTIVO, AUTORIZZAZIONI_SUBENTRI_CONC.FK_IDPOSTEGGIO AS CONC_IDPOSTEGGIO, MERCATI_D.CODICEPOSTEGGIO AS CONC_POSTEGGIO, MERCATI_D.LARGHEZZA AS CONC_POS_LARGHEZZA, MERCATI_D.LUNGHEZZA AS CONC_POS_LUNGHEZZA, MERCATI_D.SUPERFICIE AS CONC_POS_SUPERFICIE, MERCATI_D.FKCODICETIPOSPAZIO AS POST_IDTIPOSPAZIO, POSTEGGITIPOSPAZIO.TIPOSPAZIO AS POST_TIPOSPAZIO, AUTORIZZAZIONI_SUBENTRI_CONC.FK_IDMERCATIUSO AS CONC_IDMERCATIUSO, MERCATI_USO.DESCRIZIONE AS CONC_DESCRIZIONEUSO, MERCATI_USO.PESO AS PESO_MERCATO, MERCATI_USO.FKCODICEUSO AS MERC_IDUSO, MERCATI_D.FKCODICESTRADARIO AS CONC_POS_CODICESTRADARIO, MERCATI_D.NOTE AS CONC_POS_NOTE, VW_ENTILOCALI.COMUNE AS CONC_ENTERILASCIO FROM AUTORIZZAZIONI_SUBENTRI INNER JOIN TIPOLOGIAREGISTRI CONC_REGISTRO ON AUTORIZZAZIONI_SUBENTRI.IDCOMUNE = CONC_REGISTRO.IDCOMUNE AND AUTORIZZAZIONI_SUBENTRI.FKIDREGISTRO = CONC_REGISTRO.TR_ID INNER JOIN AUTORIZZAZIONI_SUBENTRI_CONC ON AUTORIZZAZIONI_SUBENTRI.IDCOMUNE = AUTORIZZAZIONI_SUBENTRI_CONC.IDCOMUNE AND AUTORIZZAZIONI_SUBENTRI.ID = AUTORIZZAZIONI_SUBENTRI_CONC.FK_AUTSUB_ID LEFT  JOIN AUTORIZZAZIONI_SUBENTRI AUT_COLLEGATA ON AUTORIZZAZIONI_SUBENTRI_CONC.IDCOMUNE = AUT_COLLEGATA.IDCOMUNE AND AUTORIZZAZIONI_SUBENTRI_CONC.FK_IDAUTSUB_AUTCOLL = AUT_COLLEGATA.ID LEFT  JOIN TIPOLOGIAREGISTRI ON AUT_COLLEGATA.IDCOMUNE = TIPOLOGIAREGISTRI.IDCOMUNE AND AUT_COLLEGATA.FKIDREGISTRO = TIPOLOGIAREGISTRI.TR_ID INNER JOIN CONCESSIONITIPI ON AUTORIZZAZIONI_SUBENTRI_CONC.FK_TIPOCONCESSIONE = CONCESSIONITIPI.TIPOCONCESSIONE INNER JOIN ANAGRAFE TITOLARE ON AUTORIZZAZIONI_SUBENTRI.IDCOMUNE = TITOLARE.IDCOMUNE AND AUTORIZZAZIONI_SUBENTRI.FK_CODICEANAGRAFE = TITOLARE.CODICEANAGRAFE INNER JOIN CONCESSIONICAUSALI CAUS_ATTUALE ON AUTORIZZAZIONI_SUBENTRI.IDCOMUNE = CAUS_ATTUALE.IDCOMUNE AND AUTORIZZAZIONI_SUBENTRI.FK_CAUSALE_ACQUISIZIONE = CAUS_ATTUALE.CODICECAUSALE LEFT  JOIN CONCESSIONICAUSALI CAUS_STORICO ON AUTORIZZAZIONI_SUBENTRI.IDCOMUNE = CAUS_STORICO.IDCOMUNE AND AUTORIZZAZIONI_SUBENTRI.FK_CAUSALE_CESSAZIONE = CAUS_STORICO.CODICECAUSALE INNER JOIN ISTANZE ON AUTORIZZAZIONI_SUBENTRI.IDCOMUNE = ISTANZE.IDCOMUNE AND AUTORIZZAZIONI_SUBENTRI.FKIDISTANZA = ISTANZE.CODICEISTANZA INNER JOIN ANAGRAFE IST_RICHIEDENTE ON ISTANZE.IDCOMUNE = IST_RICHIEDENTE.IDCOMUNE AND ISTANZE.CODICERICHIEDENTE = IST_RICHIEDENTE.CODICEANAGRAFE INNER JOIN MERCATI ON AUTORIZZAZIONI_SUBENTRI_CONC.IDCOMUNE = MERCATI.IDCOMUNE AND AUTORIZZAZIONI_SUBENTRI_CONC.FK_CODICEMERCATO = MERCATI.CODICEMERCATO INNER JOIN MERCATI_D ON AUTORIZZAZIONI_SUBENTRI_CONC.IDCOMUNE = MERCATI_D.IDCOMUNE AND AUTORIZZAZIONI_SUBENTRI_CONC.FK_IDPOSTEGGIO = MERCATI_D.IDPOSTEGGIO LEFT  JOIN POSTEGGITIPOSPAZIO ON MERCATI_D.IDCOMUNE = POSTEGGITIPOSPAZIO.IDCOMUNE AND MERCATI_D.FKCODICETIPOSPAZIO = POSTEGGITIPOSPAZIO.CODICE INNER JOIN MERCATI_USO ON AUTORIZZAZIONI_SUBENTRI_CONC.IDCOMUNE = MERCATI_USO.IDCOMUNE AND AUTORIZZAZIONI_SUBENTRI_CONC.FK_IDMERCATIUSO = MERCATI_USO.ID LEFT  JOIN ANAGRAFE IST_AZIENDA ON ISTANZE.IDCOMUNE = IST_AZIENDA.IDCOMUNE AND ISTANZE.CODICETITOLARELEGALE = IST_AZIENDA.CODICEANAGRAFE INNER JOIN VW_ENTILOCALI ON AUTORIZZAZIONI_SUBENTRI.AUTORIZCOMUNE = VW_ENTILOCALI.CODICECOMUNE;


alter table AUTORIZZAZIONI_CSI ADD TIPOLOGIA_BATTITORI VARCHAR2(1) DEFAULT 'N';

ALTER TABLE MERCATIPRESENZE_D ADD FK_CODICECOLLABORATORE NUMBER(6,0);

ALTER TABLE MERCATIPRESENZE_D ADD CONSTRAINT FK_MERCPRESD_ANAGCOLLAB FOREIGN KEY (IDCOMUNE,FK_CODICECOLLABORATORE) REFERENCES ANAGRAFE (IDCOMUNE,CODICEANAGRAFE);
CREATE INDEX IDX_MERCATIPRESENZED_ANACOLL ON MERCATIPRESENZE_D (IDCOMUNE,FK_CODICECOLLABORATORE);


ALTER TABLE AUTORIZZAZIONI ADD DATA_RILASCIO DATE;
ALTER TABLE AUTORIZZAZIONI_SUBENTRI ADD DATA_RILASCIO DATE;

CREATE OR REPLACE VIEW vw_istanzeconcessionilista AS SELECT 99999999 AS progressivo, autorizzazioni.autorizresponsabile AS conc_autorizresponsabile, autorizzazioni.idcomune, autorizzazioni.fk_causale_acquisizione AS iconc_codicecausale, nvl(autorizzazioni.data_cessazione,TO_DATE('31/12/9999','DD/MM/YYYY') ) AS data_storico, istanze.software, istanze.codiceistanza AS ist_codiceistanza, istanze.numeroistanza AS ist_numeroistanza, istanze.codicerichiedente AS ist_codicerichiedente, autorizzazioni.id AS conc_id, autorizzazioni.autoriznumero AS conc_numero, autorizzazioni.autorizdata AS conc_datavalidita, autorizzazioni.autorizdata AS datavalidita, autorizzazioni.data_rilascio AS conc_datarilascio, autorizzazioni.data_rilascio AS datarilascio, autorizzazioni.datascadenza AS conc_datascadenza, autorizzazioni_concessioni.fk_tipoconcessione AS conc_codicetipo, concessionitipi.descrizione AS conc_tipo, autorizzazioni_concessioni.stagionalea AS conc_stagionalea, autorizzazioni_concessioni.stagionaleda AS conc_stagionaleda, autorizzazioni.flag_attiva AS conc_attiva, autorizzazioni.fk_codiceanagrafe AS conc_codicetitolare, autorizzazioni.fkidregistro AS conc_fkidregistro, conc_registro.tr_descrizione AS conc_registro, titolare.nominativo || ' ' || titolare.nome AS conc_titolare, titolare.codicefiscale AS conc_tit_cf, titolare.partitaiva AS conc_tit_piva, titolare.tipoanagrafe AS conc_tit_tipoanagrafe, aut_collegata.autoriznumero AS aut_numero, aut_collegata.autorizdata AS aut_data, aut_collegata.autorizdata, aut_collegata.fkidregistro AS aut_codregistro, tipologiaregistri.tr_descrizione AS aut_registro, ist_richiedente.nominativo || ' ' || ist_richiedente.nome AS ist_nominativo, ist_richiedente.tipoanagrafe AS ist_ric_tipoanagrafe, ist_azienda.nominativo || ' ' || ist_azienda.nome AS ist_nominativoazienda, ist_azienda.tipoanagrafe AS ist_azi_tipoanagrafe, ist_richiedente.codicefiscale AS ist_codicefiscale, ist_richiedente.partitaiva AS ist_partitaiva, caus_attuale.descrizione AS iconc_causale, autorizzazioni.fk_causale_cessazione AS iconc_codicecausalestorico, caus_storico.descrizione AS iconc_causalestorico, autorizzazioni_concessioni.fk_codicemercato AS conc_idmercato, mercati.descrizione AS conc_mercato, mercati.attivo AS merc_attivo, autorizzazioni_concessioni.fk_idposteggio AS conc_idposteggio, mercati_d.codiceposteggio AS conc_posteggio, mercati_d.larghezza AS conc_pos_larghezza, mercati_d.lunghezza AS conc_pos_lunghezza, mercati_d.superficie AS conc_pos_superficie, mercati_d.fkcodicetipospazio AS post_idtipospazio, posteggitipospazio.tipospazio AS post_tipospazio, autorizzazioni_concessioni.fk_idmercatiuso AS conc_idmercatiuso, mercati_uso.descrizione AS conc_descrizioneuso, mercati_uso.peso AS peso_mercato, mercati_uso.fkcodiceuso AS merc_iduso, mercati_d.fkcodicestradario AS conc_pos_codicestradario, mercati_d.note AS conc_pos_note, vw_entilocali.comune AS conc_enterilascio FROM autorizzazioni INNER JOIN tipologiaregistri conc_registro ON autorizzazioni.idcomune = conc_registro.idcomune AND autorizzazioni.fkidregistro = conc_registro.tr_id INNER JOIN autorizzazioni_concessioni ON autorizzazioni.idcomune = autorizzazioni_concessioni.idcomune AND autorizzazioni.id = autorizzazioni_concessioni.fk_idaut_attuale LEFT JOIN autorizzazioni aut_collegata ON autorizzazioni_concessioni.idcomune = aut_collegata.idcomune AND autorizzazioni_concessioni.fk_idaut_collegata = aut_collegata.id LEFT JOIN tipologiaregistri ON aut_collegata.idcomune = tipologiaregistri.idcomune AND aut_collegata.fkidregistro = tipologiaregistri.tr_id INNER JOIN concessionitipi ON autorizzazioni_concessioni.fk_tipoconcessione = concessionitipi.tipoconcessione INNER JOIN anagrafe titolare ON autorizzazioni.idcomune = titolare.idcomune AND autorizzazioni.fk_codiceanagrafe = titolare.codiceanagrafe INNER JOIN concessionicausali caus_attuale ON autorizzazioni.idcomune = caus_attuale.idcomune AND autorizzazioni.fk_causale_acquisizione = caus_attuale.codicecausale LEFT JOIN concessionicausali caus_storico ON autorizzazioni.idcomune = caus_storico.idcomune AND autorizzazioni.fk_causale_cessazione = caus_storico.codicecausale INNER JOIN istanze ON autorizzazioni.idcomune = istanze.idcomune AND autorizzazioni.fkidistanza = istanze.codiceistanza INNER JOIN anagrafe ist_richiedente ON istanze.idcomune = ist_richiedente.idcomune AND istanze.codicerichiedente = ist_richiedente.codiceanagrafe INNER JOIN mercati ON autorizzazioni_concessioni.idcomune = mercati.idcomune AND autorizzazioni_concessioni.fk_codicemercato = mercati.codicemercato INNER JOIN mercati_d ON autorizzazioni_concessioni.idcomune = mercati_d.idcomune AND autorizzazioni_concessioni.fk_idposteggio = mercati_d.idposteggio LEFT JOIN posteggitipospazio ON mercati_d.idcomune = posteggitipospazio.idcomune AND mercati_d.fkcodicetipospazio = posteggitipospazio.codice INNER JOIN mercati_uso ON autorizzazioni_concessioni.idcomune = mercati_uso.idcomune AND autorizzazioni_concessioni.fk_idmercatiuso = mercati_uso.id LEFT JOIN anagrafe ist_azienda ON istanze.idcomune = ist_azienda.idcomune AND istanze.codicetitolarelegale = ist_azienda.codiceanagrafe INNER JOIN vw_entilocali ON autorizzazioni.autorizcomune = vw_entilocali.codicecomune UNION SELECT autorizzazioni_subentri.id AS progressivo, autorizzazioni_subentri.autorizresponsabile AS conc_autorizresponsabile, autorizzazioni_subentri.idcomune, autorizzazioni_subentri.fk_causale_acquisizione AS iconc_codicecausale, autorizzazioni_subentri.data_cessazione AS data_storico, istanze.software, istanze.codiceistanza AS ist_codiceistanza, istanze.numeroistanza AS ist_numeroistanza, istanze.codicerichiedente AS ist_codicerichiedente, autorizzazioni_subentri.fk_idaut_attuale AS conc_id, autorizzazioni_subentri.autoriznumero AS conc_numero, autorizzazioni_subentri.autorizdata AS conc_datavalidita, autorizzazioni_subentri.autorizdata AS datavalidita, autorizzazioni_subentri.data_rilascio AS conc_datarilascio, autorizzazioni_subentri.data_rilascio AS datarilascio, autorizzazioni_subentri.datascadenza AS conc_datascadenza, autorizzazioni_subentri_conc.fk_tipoconcessione AS conc_codicetipo, concessionitipi.descrizione AS conc_tipo, autorizzazioni_subentri_conc.stagionalea AS conc_stagionalea, autorizzazioni_subentri_conc.stagionaleda AS conc_stagionaleda, 0 AS conc_attiva, autorizzazioni_subentri.fk_codiceanagrafe AS conc_codicetitolare, autorizzazioni_subentri.fkidregistro AS conc_fkidregistro, conc_registro.tr_descrizione AS conc_registro, titolare.nominativo || ' ' || titolare.nome AS conc_titolare, titolare.codicefiscale AS conc_tit_cf, titolare.partitaiva AS conc_tit_piva, titolare.tipoanagrafe AS conc_tit_tipoanagrafe, aut_collegata.autoriznumero AS aut_numero, aut_collegata.autorizdata AS aut_data, aut_collegata.autorizdata, aut_collegata.fkidregistro AS aut_codregistro, tipologiaregistri.tr_descrizione AS aut_registro, ist_richiedente.nominativo || ' ' || ist_richiedente.nome AS ist_nominativo, ist_richiedente.tipoanagrafe AS ist_ric_tipoanagrafe, ist_azienda.nominativo || ' ' || ist_azienda.nome AS ist_nominativoazienda, ist_azienda.tipoanagrafe AS ist_azi_tipoanagrafe, ist_richiedente.codicefiscale AS ist_codicefiscale, ist_richiedente.partitaiva AS ist_partitaiva, caus_attuale.descrizione AS iconc_causale, autorizzazioni_subentri.fk_causale_cessazione AS iconc_codicecausalestorico, caus_storico.descrizione AS iconc_causalestorico, autorizzazioni_subentri_conc.fk_codicemercato AS conc_idmercato, mercati.descrizione AS conc_mercato, mercati.attivo AS merc_attivo, autorizzazioni_subentri_conc.fk_idposteggio AS conc_idposteggio, mercati_d.codiceposteggio AS conc_posteggio, mercati_d.larghezza AS conc_pos_larghezza, mercati_d.lunghezza AS conc_pos_lunghezza, mercati_d.superficie AS conc_pos_superficie, mercati_d.fkcodicetipospazio AS post_idtipospazio, posteggitipospazio.tipospazio AS post_tipospazio, autorizzazioni_subentri_conc.fk_idmercatiuso AS conc_idmercatiuso, mercati_uso.descrizione AS conc_descrizioneuso, mercati_uso.peso AS peso_mercato, mercati_uso.fkcodiceuso AS merc_iduso, mercati_d.fkcodicestradario AS conc_pos_codicestradario, mercati_d.note AS conc_pos_note, vw_entilocali.comune AS conc_enterilascio FROM autorizzazioni_subentri INNER JOIN tipologiaregistri conc_registro ON autorizzazioni_subentri.idcomune = conc_registro.idcomune AND autorizzazioni_subentri.fkidregistro = conc_registro.tr_id INNER JOIN autorizzazioni_subentri_conc ON autorizzazioni_subentri.idcomune = autorizzazioni_subentri_conc.idcomune AND autorizzazioni_subentri.id = autorizzazioni_subentri_conc.fk_autsub_id LEFT JOIN autorizzazioni_subentri aut_collegata ON autorizzazioni_subentri_conc.idcomune = aut_collegata.idcomune AND autorizzazioni_subentri_conc.fk_idautsub_autcoll = aut_collegata.id LEFT JOIN tipologiaregistri ON aut_collegata.idcomune = tipologiaregistri.idcomune AND aut_collegata.fkidregistro = tipologiaregistri.tr_id INNER JOIN concessionitipi ON autorizzazioni_subentri_conc.fk_tipoconcessione = concessionitipi.tipoconcessione INNER JOIN anagrafe titolare ON autorizzazioni_subentri.idcomune = titolare.idcomune AND autorizzazioni_subentri.fk_codiceanagrafe = titolare.codiceanagrafe INNER JOIN concessionicausali caus_attuale ON autorizzazioni_subentri.idcomune = caus_attuale.idcomune AND autorizzazioni_subentri.fk_causale_acquisizione = caus_attuale.codicecausale LEFT JOIN concessionicausali caus_storico ON autorizzazioni_subentri.idcomune = caus_storico.idcomune AND autorizzazioni_subentri.fk_causale_cessazione = caus_storico.codicecausale INNER JOIN istanze ON autorizzazioni_subentri.idcomune = istanze.idcomune AND autorizzazioni_subentri.fkidistanza = istanze.codiceistanza INNER JOIN anagrafe ist_richiedente ON istanze.idcomune = ist_richiedente.idcomune AND istanze.codicerichiedente = ist_richiedente.codiceanagrafe INNER JOIN mercati ON autorizzazioni_subentri_conc.idcomune = mercati.idcomune AND autorizzazioni_subentri_conc.fk_codicemercato = mercati.codicemercato INNER JOIN mercati_d ON autorizzazioni_subentri_conc.idcomune = mercati_d.idcomune AND autorizzazioni_subentri_conc.fk_idposteggio = mercati_d.idposteggio LEFT JOIN posteggitipospazio ON mercati_d.idcomune = posteggitipospazio.idcomune AND mercati_d.fkcodicetipospazio = posteggitipospazio.codice INNER JOIN mercati_uso ON autorizzazioni_subentri_conc.idcomune = mercati_uso.idcomune AND autorizzazioni_subentri_conc.fk_idmercatiuso = mercati_uso.id LEFT JOIN anagrafe ist_azienda ON istanze.idcomune = ist_azienda.idcomune AND istanze.codicetitolarelegale = ist_azienda.codiceanagrafe INNER JOIN vw_entilocali ON autorizzazioni_subentri.autorizcomune = vw_entilocali.codicecomune;

CREATE OR REPLACE VIEW vw_concessionilista AS SELECT idcomune, software, progressivo, conc_id, conc_numero, conc_datavalidita, conc_datarilascio, conc_datascadenza, conc_codicetipo, conc_tipo, conc_stagionalea, conc_stagionaleda, conc_attiva, conc_codicetitolare, conc_titolare, conc_tit_cf, conc_tit_piva, conc_tit_tipoanagrafe, conc_fkidregistro, conc_registro, aut_numero, aut_data, aut_codregistro, aut_registro, ist_codiceistanza, ist_numeroistanza, ist_codicerichiedente, ist_nominativo, ist_codicefiscale, ist_partitaiva, ist_ric_tipoanagrafe, iconc_codicecausale, iconc_causale, iconc_codicecausalestorico, iconc_causalestorico, conc_idmercato, conc_mercato, merc_attivo, conc_idposteggio, conc_posteggio, conc_pos_larghezza, conc_pos_lunghezza, conc_pos_superficie, post_idtipospazio, post_tipospazio, conc_idmercatiuso, conc_descrizioneuso, peso_mercato, merc_iduso, conc_pos_codicestradario, data_storico, conc_enterilascio FROM vw_istanzeconcessionilista;


create table BATTITORI_CSI(
IDCOMUNE VARCHAR2(6) NOT NULL,
ID NUMBER(10,0) NOT NULL,
FK_IDAUTORIZZAZIONE NUMBER(6,0) NOT NULL,
FK_GS_ID NUMBER(2,0),
SIAP_DENOMINAZIONE VARCHAR2(100)
);

ALTER TABLE BATTITORI_CSI ADD CONSTRAINT PK_BATTITORI_CSI PRIMARY KEY (IDCOMUNE,ID);
ALTER TABLE BATTITORI_CSI ADD CONSTRAINT FK_BATTCSI_AUTORIZZAZIONI FOREIGN KEY (IDCOMUNE,FK_IDAUTORIZZAZIONE) REFERENCES AUTORIZZAZIONI(IDCOMUNE,ID);
ALTER TABLE BATTITORI_CSI ADD CONSTRAINT FK_BATTCSI_GIORNISETTIMANA FOREIGN KEY (FK_GS_ID) REFERENCES GIORNISETTIMANA(GS_ID);

ALTER TABLE MERCATI ADD CIRCOSCRIZIONE VARCHAR2(50);
alter table istanzestradario modify esponente varchar2(25);

ALTER TABLE RESPONSABILI ADD CIRCOSCRIZIONE VARCHAR2(50);


CREATE TABLE AUTORIZ_SUB_BK20190703 AS SELECT * FROM Autorizzazioni_Subentri;