//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VbgFileConverter
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://gruppoinit.it/fileconverter/definitions", ConfigurationName="VbgFileConverter.fileconverter")]
    public interface fileconverter
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<VbgFileConverter.MergeDataAndConvertResponse1> MergeDataAndConvertAsync(VbgFileConverter.MergeDataAndConvertRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<VbgFileConverter.MergeDataResponse1> MergeDataAsync(VbgFileConverter.MergeDataRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<VbgFileConverter.ConvertResponse1> ConvertAsync(VbgFileConverter.ConvertRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<VbgFileConverter.ConvertBinaryResponse1> ConvertBinaryAsync(VbgFileConverter.ConvertBinaryRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<VbgFileConverter.MergeAndConvertResponse1> MergeAndConvertAsync(VbgFileConverter.MergeAndConvertRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gruppoinit.it/fileconverter")]
    public partial class MergeDataAndConvertRequest
    {
        
        private string tokenField;
        
        private byte[] rtfBinaryDataField;
        
        private byte[] xmlBinaryDataField;
        
        private string conversionTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] rtfBinaryData
        {
            get
            {
                return this.rtfBinaryDataField;
            }
            set
            {
                this.rtfBinaryDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=2)]
        public byte[] xmlBinaryData
        {
            get
            {
                return this.xmlBinaryDataField;
            }
            set
            {
                this.xmlBinaryDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string conversionType
        {
            get
            {
                return this.conversionTypeField;
            }
            set
            {
                this.conversionTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gruppoinit.it/fileconverter")]
    public partial class MergeDataAndConvertResponse
    {
        
        private string mimeTypeField;
        
        private byte[] binaryDataField;
        
        private string fileNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string mimeType
        {
            get
            {
                return this.mimeTypeField;
            }
            set
            {
                this.mimeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] binaryData
        {
            get
            {
                return this.binaryDataField;
            }
            set
            {
                this.binaryDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string fileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MergeDataAndConvertRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gruppoinit.it/fileconverter", Order=0)]
        public VbgFileConverter.MergeDataAndConvertRequest MergeDataAndConvertRequest;
        
        public MergeDataAndConvertRequest1()
        {
        }
        
        public MergeDataAndConvertRequest1(VbgFileConverter.MergeDataAndConvertRequest MergeDataAndConvertRequest)
        {
            this.MergeDataAndConvertRequest = MergeDataAndConvertRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MergeDataAndConvertResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gruppoinit.it/fileconverter", Order=0)]
        public VbgFileConverter.MergeDataAndConvertResponse MergeDataAndConvertResponse;
        
        public MergeDataAndConvertResponse1()
        {
        }
        
        public MergeDataAndConvertResponse1(VbgFileConverter.MergeDataAndConvertResponse MergeDataAndConvertResponse)
        {
            this.MergeDataAndConvertResponse = MergeDataAndConvertResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gruppoinit.it/fileconverter")]
    public partial class MergeDataRequest
    {
        
        private string tokenField;
        
        private byte[] rtfBinaryDataField;
        
        private byte[] xmlBinaryDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] rtfBinaryData
        {
            get
            {
                return this.rtfBinaryDataField;
            }
            set
            {
                this.rtfBinaryDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=2)]
        public byte[] xmlBinaryData
        {
            get
            {
                return this.xmlBinaryDataField;
            }
            set
            {
                this.xmlBinaryDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gruppoinit.it/fileconverter")]
    public partial class MergeDataResponse
    {
        
        private string mimeTypeField;
        
        private byte[] binaryDataField;
        
        private string fileNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string mimeType
        {
            get
            {
                return this.mimeTypeField;
            }
            set
            {
                this.mimeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] binaryData
        {
            get
            {
                return this.binaryDataField;
            }
            set
            {
                this.binaryDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string fileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MergeDataRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gruppoinit.it/fileconverter", Order=0)]
        public VbgFileConverter.MergeDataRequest MergeDataRequest;
        
        public MergeDataRequest1()
        {
        }
        
        public MergeDataRequest1(VbgFileConverter.MergeDataRequest MergeDataRequest)
        {
            this.MergeDataRequest = MergeDataRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MergeDataResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gruppoinit.it/fileconverter", Order=0)]
        public VbgFileConverter.MergeDataResponse MergeDataResponse;
        
        public MergeDataResponse1()
        {
        }
        
        public MergeDataResponse1(VbgFileConverter.MergeDataResponse MergeDataResponse)
        {
            this.MergeDataResponse = MergeDataResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gruppoinit.it/fileconverter")]
    public partial class ConvertRequest
    {
        
        private string tokenField;
        
        private string contentField;
        
        private string contentTypeField;
        
        private string conversionTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string content
        {
            get
            {
                return this.contentField;
            }
            set
            {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string contentType
        {
            get
            {
                return this.contentTypeField;
            }
            set
            {
                this.contentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string conversionType
        {
            get
            {
                return this.conversionTypeField;
            }
            set
            {
                this.conversionTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gruppoinit.it/fileconverter")]
    public partial class ConvertResponse
    {
        
        private string mimeTypeField;
        
        private byte[] binaryDataField;
        
        private string fileNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string mimeType
        {
            get
            {
                return this.mimeTypeField;
            }
            set
            {
                this.mimeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] binaryData
        {
            get
            {
                return this.binaryDataField;
            }
            set
            {
                this.binaryDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string fileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gruppoinit.it/fileconverter", Order=0)]
        public VbgFileConverter.ConvertRequest ConvertRequest;
        
        public ConvertRequest1()
        {
        }
        
        public ConvertRequest1(VbgFileConverter.ConvertRequest ConvertRequest)
        {
            this.ConvertRequest = ConvertRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gruppoinit.it/fileconverter", Order=0)]
        public VbgFileConverter.ConvertResponse ConvertResponse;
        
        public ConvertResponse1()
        {
        }
        
        public ConvertResponse1(VbgFileConverter.ConvertResponse ConvertResponse)
        {
            this.ConvertResponse = ConvertResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gruppoinit.it/fileconverter")]
    public partial class ConvertBinaryRequest
    {
        
        private string tokenField;
        
        private byte[] binaryDataField;
        
        private string contentTypeField;
        
        private string conversionTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] binaryData
        {
            get
            {
                return this.binaryDataField;
            }
            set
            {
                this.binaryDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string contentType
        {
            get
            {
                return this.contentTypeField;
            }
            set
            {
                this.contentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string conversionType
        {
            get
            {
                return this.conversionTypeField;
            }
            set
            {
                this.conversionTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gruppoinit.it/fileconverter")]
    public partial class ConvertBinaryResponse
    {
        
        private string mimeTypeField;
        
        private byte[] binaryDataField;
        
        private string fileNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string mimeType
        {
            get
            {
                return this.mimeTypeField;
            }
            set
            {
                this.mimeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] binaryData
        {
            get
            {
                return this.binaryDataField;
            }
            set
            {
                this.binaryDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string fileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertBinaryRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gruppoinit.it/fileconverter", Order=0)]
        public VbgFileConverter.ConvertBinaryRequest ConvertBinaryRequest;
        
        public ConvertBinaryRequest1()
        {
        }
        
        public ConvertBinaryRequest1(VbgFileConverter.ConvertBinaryRequest ConvertBinaryRequest)
        {
            this.ConvertBinaryRequest = ConvertBinaryRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertBinaryResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gruppoinit.it/fileconverter", Order=0)]
        public VbgFileConverter.ConvertBinaryResponse ConvertBinaryResponse;
        
        public ConvertBinaryResponse1()
        {
        }
        
        public ConvertBinaryResponse1(VbgFileConverter.ConvertBinaryResponse ConvertBinaryResponse)
        {
            this.ConvertBinaryResponse = ConvertBinaryResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gruppoinit.it/fileconverter")]
    public partial class MergeAndConvertRequest
    {
        
        private string tokenField;
        
        private byte[] dataField;
        
        private string dataTypeField;
        
        private byte[] modelField;
        
        private string modelTypeField;
        
        private string conversionTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string dataType
        {
            get
            {
                return this.dataTypeField;
            }
            set
            {
                this.dataTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=3)]
        public byte[] model
        {
            get
            {
                return this.modelField;
            }
            set
            {
                this.modelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string modelType
        {
            get
            {
                return this.modelTypeField;
            }
            set
            {
                this.modelTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string conversionType
        {
            get
            {
                return this.conversionTypeField;
            }
            set
            {
                this.conversionTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gruppoinit.it/fileconverter")]
    public partial class MergeAndConvertResponse
    {
        
        private string mimeTypeField;
        
        private byte[] binaryDataField;
        
        private string fileNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string mimeType
        {
            get
            {
                return this.mimeTypeField;
            }
            set
            {
                this.mimeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] binaryData
        {
            get
            {
                return this.binaryDataField;
            }
            set
            {
                this.binaryDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string fileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MergeAndConvertRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gruppoinit.it/fileconverter", Order=0)]
        public VbgFileConverter.MergeAndConvertRequest MergeAndConvertRequest;
        
        public MergeAndConvertRequest1()
        {
        }
        
        public MergeAndConvertRequest1(VbgFileConverter.MergeAndConvertRequest MergeAndConvertRequest)
        {
            this.MergeAndConvertRequest = MergeAndConvertRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MergeAndConvertResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gruppoinit.it/fileconverter", Order=0)]
        public VbgFileConverter.MergeAndConvertResponse MergeAndConvertResponse;
        
        public MergeAndConvertResponse1()
        {
        }
        
        public MergeAndConvertResponse1(VbgFileConverter.MergeAndConvertResponse MergeAndConvertResponse)
        {
            this.MergeAndConvertResponse = MergeAndConvertResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface fileconverterChannel : VbgFileConverter.fileconverter, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class fileconverterClient : System.ServiceModel.ClientBase<VbgFileConverter.fileconverter>, VbgFileConverter.fileconverter
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public fileconverterClient() : 
                base(fileconverterClient.GetDefaultBinding(), fileconverterClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.fileconverterSoap11.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public fileconverterClient(EndpointConfiguration endpointConfiguration) : 
                base(fileconverterClient.GetBindingForEndpoint(endpointConfiguration), fileconverterClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public fileconverterClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(fileconverterClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public fileconverterClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(fileconverterClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public fileconverterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VbgFileConverter.MergeDataAndConvertResponse1> VbgFileConverter.fileconverter.MergeDataAndConvertAsync(VbgFileConverter.MergeDataAndConvertRequest1 request)
        {
            return base.Channel.MergeDataAndConvertAsync(request);
        }
        
        public System.Threading.Tasks.Task<VbgFileConverter.MergeDataAndConvertResponse1> MergeDataAndConvertAsync(VbgFileConverter.MergeDataAndConvertRequest MergeDataAndConvertRequest)
        {
            VbgFileConverter.MergeDataAndConvertRequest1 inValue = new VbgFileConverter.MergeDataAndConvertRequest1();
            inValue.MergeDataAndConvertRequest = MergeDataAndConvertRequest;
            return ((VbgFileConverter.fileconverter)(this)).MergeDataAndConvertAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VbgFileConverter.MergeDataResponse1> VbgFileConverter.fileconverter.MergeDataAsync(VbgFileConverter.MergeDataRequest1 request)
        {
            return base.Channel.MergeDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<VbgFileConverter.MergeDataResponse1> MergeDataAsync(VbgFileConverter.MergeDataRequest MergeDataRequest)
        {
            VbgFileConverter.MergeDataRequest1 inValue = new VbgFileConverter.MergeDataRequest1();
            inValue.MergeDataRequest = MergeDataRequest;
            return ((VbgFileConverter.fileconverter)(this)).MergeDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VbgFileConverter.ConvertResponse1> VbgFileConverter.fileconverter.ConvertAsync(VbgFileConverter.ConvertRequest1 request)
        {
            return base.Channel.ConvertAsync(request);
        }
        
        public System.Threading.Tasks.Task<VbgFileConverter.ConvertResponse1> ConvertAsync(VbgFileConverter.ConvertRequest ConvertRequest)
        {
            VbgFileConverter.ConvertRequest1 inValue = new VbgFileConverter.ConvertRequest1();
            inValue.ConvertRequest = ConvertRequest;
            return ((VbgFileConverter.fileconverter)(this)).ConvertAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VbgFileConverter.ConvertBinaryResponse1> VbgFileConverter.fileconverter.ConvertBinaryAsync(VbgFileConverter.ConvertBinaryRequest1 request)
        {
            return base.Channel.ConvertBinaryAsync(request);
        }
        
        public System.Threading.Tasks.Task<VbgFileConverter.ConvertBinaryResponse1> ConvertBinaryAsync(VbgFileConverter.ConvertBinaryRequest ConvertBinaryRequest)
        {
            VbgFileConverter.ConvertBinaryRequest1 inValue = new VbgFileConverter.ConvertBinaryRequest1();
            inValue.ConvertBinaryRequest = ConvertBinaryRequest;
            return ((VbgFileConverter.fileconverter)(this)).ConvertBinaryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VbgFileConverter.MergeAndConvertResponse1> VbgFileConverter.fileconverter.MergeAndConvertAsync(VbgFileConverter.MergeAndConvertRequest1 request)
        {
            return base.Channel.MergeAndConvertAsync(request);
        }
        
        public System.Threading.Tasks.Task<VbgFileConverter.MergeAndConvertResponse1> MergeAndConvertAsync(VbgFileConverter.MergeAndConvertRequest MergeAndConvertRequest)
        {
            VbgFileConverter.MergeAndConvertRequest1 inValue = new VbgFileConverter.MergeAndConvertRequest1();
            inValue.MergeAndConvertRequest = MergeAndConvertRequest;
            return ((VbgFileConverter.fileconverter)(this)).MergeAndConvertAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.fileconverterSoap11))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.fileconverterSoap11))
            {
                return new System.ServiceModel.EndpointAddress("http://vbg.fileconverter:9080/fileconverter/ws");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return fileconverterClient.GetBindingForEndpoint(EndpointConfiguration.fileconverterSoap11);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return fileconverterClient.GetEndpointAddress(EndpointConfiguration.fileconverterSoap11);
        }
        
        public enum EndpointConfiguration
        {
            
            fileconverterSoap11,
        }
    }
}
