CREATE TABLE ISTANZE_METADATI(
    IDCOMUNE VARCHAR(6) NOT NULL,
    CODICEISTANZA NUMERIC(6,0) NOT NULL,
    CHIAVE VARCHAR(60) NOT NULL,
    VALORE VARCHAR(500) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

ALTER TABLE ISTANZE_METADATI ADD CONSTRAINT PK_ISTANZE_METADATI PRIMARY KEY(IDCOMUNE,CODICEISTANZA,CHIAVE);
ALTER TABLE ISTANZE_METADATI ADD CONSTRAINT FK_ISTANZEMD_ISTANZE FOREIGN KEY(IDCOMUNE,CODICEISTANZA) REFERENCES ISTANZE(IDCOMUNE,CODICEISTANZA);
