ALTER TABLE movimenti_atti MODIFY ID_DOCUMENTO NUMERIC(10,0) NOT NULL;
ALTER TABLE movimenti_atti MODIFY NUMERO NUMERIC(10,0) NOT NULL;

CREATE INDEX IDX_DOCUMENTICONDIVISI_001 ON DOCUMENTI_CONDIVISI (IDCOMUNE,CODICEMOVIMENTO);
CREATE INDEX IDX_DOCUMENTICONDIVISI_002 ON DOCUMENTI_CONDIVISI (IDCOMUNE,CODICEISTANZA);

CREATE INDEX IDX_DOCUMENTICONDIVISILOGS_001 ON DOCUMENTI_CONDIVISI_LOGS(IDCOMUNE, FK_IDDOCCONDIVISO);