ALTER TABLE INVENTARIOPROCEDIMENTIPEOPLE DROP FOREIGN KEY FK_INV_PROC_PEOP_INV_PROC;
ALTER TABLE INVENTARIOPROCEDIMENTIPEOPLE DROP PRIMARY KEY;
ALTER TABLE INVENTARIOPROCEDIMENTIPEOPLE ADD CONSTRAINT INVENTARIOPROCEDIMENTIPEOPL_PK PRIMARY KEY(IDCOMUNE,ID);
ALTER TABLE INVENTARIOPROCEDIMENTIPEOPLE ADD CONSTRAINT FK_INV_PROC_PEOP_INV_PROC FOREIGN KEY (IDCOMUNE,CODICEINVENTARIO) REFERENCES INVENTARIOPROCEDIMENTI(IDCOMUNE,CODICEINVENTARIO);
ALTER TABLE AUTORIZZAZIONI_CONCESSIONI ADD CONSTRAINT FK_AUTCONC_MERCATI_D FOREIGN KEY(IDCOMUNE,FK_IDPOSTEGGIO) REFERENCES MERCATI_D(IDCOMUNE,IDPOSTEGGIO);
ALTER TABLE MERCATI_D ADD CONSTRAINT FK_MERCATID_STRADARIO FOREIGN KEY(IDCOMUNE,FKCODICESTRADARIO) REFERENCES STRADARIO(IDCOMUNE,CODICESTRADARIO);
ALTER TABLE MERCATI_D ADD CONSTRAINT FK_MERCATID_MERCATI FOREIGN KEY(IDCOMUNE,FKCODICEMERCATO) REFERENCES MERCATI(IDCOMUNE,CODICEMERCATO);
ALTER TABLE MERCATI_DATTIVITAISTAT ADD CONSTRAINT FK_MERC_DATTIVIT_MERCATID FOREIGN KEY (IDCOMUNE, FKIDPOSTEGGIO) REFERENCES MERCATI_D (IDCOMUNE, IDPOSTEGGIO);
ALTER TABLE CONFIGURAZIONE MODIFY COLUMN ORARIO VARCHAR(1000);
ALTER TABLE OGGETTI MODIFY COLUMN NOMEFILE VARCHAR(216);

ALTER TABLE FO_VISURA_CAMPI DROP FOREIGN KEY FO_VISURA_CAMPI__FK1;
ALTER TABLE FO_VISURA_CAMPI DROP FOREIGN KEY FO_VISURA_CAMPI__FK2;

ALTER TABLE FO_VISURA_CAMPI ADD CONSTRAINT FK_FO_VIS_CAMPI_CONTESTI_BASE FOREIGN KEY (FKIDCONTESTO) REFERENCES FO_VISURA_CONTESTI_BASE (ID);
ALTER TABLE FO_VISURA_CAMPI ADD CONSTRAINT FK_FO_VIS_CAMPI_CAMPI_BASE FOREIGN KEY (FKIDCAMPO) REFERENCES FO_VISURA_CAMPI_BASE (ID);
ALTER TABLE FO_VISURA_CAMPI ADD CONSTRAINT FK_FO_VIS_CAMPI_SOFTWARE FOREIGN KEY (SOFTWARE) REFERENCES SOFTWARE (CODICE);
ALTER TABLE MAIL_CONFIG MODIFY COLUMN LOGINNAME VARCHAR(320);
CREATE OR REPLACE ALGORITHM=MERGE View VW_I_ATTIVITALISTA as SELECT I_ATTIVITA.CODICEISTANZAULTIMA as I_CODICEISTANZAULTIMA, I_ATTIVITA.ID as I_IDATTIVITA, I_ATTIVITA.IDCOMUNE, I_ATTIVITA.ATTIVA, I_ATTIVITA.OPERANTE, ISTANZE.SOFTWARE, I_ATTIVITA.DENOMINAZIONE, ISTANZE.NUMEROISTANZA, ISTANZE.CODICERICHIEDENTE, CONCAT_WS('', T_RICHIEDENTE.NOMINATIVO,' ', T_RICHIEDENTE.NOME) as RICHIEDENTE, TRIM( CONCAT_WS('', T_RICHIEDENTE.CODICEFISCALE,' ', T_RICHIEDENTE.PARTITAIVA))  as CF_PIVA_RICHIEDENTE, ISTANZE.FKCODICESOGGETTO, TIPISOGGETTO.TIPOSOGGETTO, ISTANZE.CODICECOMUNE, ISTANZE.CODICETITOLARELEGALE, TRIM( CONCAT_WS('', T_AZIENDARICHIEDENTE.NOMINATIVO,' ', T_AZIENDARICHIEDENTE.NOME))  as AZIENDARICHIEDENTE, TRIM( CONCAT_WS('', T_AZIENDARICHIEDENTE.CODICEFISCALE,' ', T_AZIENDARICHIEDENTE.PARTITAIVA))  as CF_PIVA_AZIENDARICHIEDENTE, ISTANZESTRADARIO.CODICESTRADARIO, CONCAT_WS('', STRADARIO.PREFISSO,' ', STRADARIO.DESCRIZIONE,',', ifnull(ISTANZESTRADARIO.CIVICO,''), ifnull(ISTANZESTRADARIO.COLORE, '')) as LOCALIZZAZIONE, ISTANZESTRADARIO.CIVICO FROM ISTANZE LEFT OUTER JOIN ANAGRAFE T_AZIENDARICHIEDENTE ON ISTANZE.IDCOMUNE=T_AZIENDARICHIEDENTE.IDCOMUNE  AND ISTANZE.CODICETITOLARELEGALE=T_AZIENDARICHIEDENTE.CODICEANAGRAFE  LEFT OUTER JOIN TIPISOGGETTO ON ISTANZE.IDCOMUNE=TIPISOGGETTO.IDCOMUNE  AND ISTANZE.FKCODICESOGGETTO=TIPISOGGETTO.CODICETIPOSOGGETTO LEFT OUTER JOIN ISTANZESTRADARIO ON ISTANZESTRADARIO.IDCOMUNE = ISTANZE.IDCOMUNE AND ISTANZESTRADARIO.CODICEISTANZA = ISTANZE.CODICEISTANZA AND ISTANZESTRADARIO.PRIMARIO = 1 LEFT OUTER JOIN STRADARIO ON STRADARIO.IDCOMUNE = ISTANZESTRADARIO.IDCOMUNE AND STRADARIO.CODICESTRADARIO = ISTANZESTRADARIO.CODICESTRADARIO, I_ATTIVITA, ANAGRAFE T_RICHIEDENTE WHERE ISTANZE.IDCOMUNE = I_ATTIVITA.IDCOMUNE AND ISTANZE.CODICEISTANZA = I_ATTIVITA.CODICEISTANZAULTIMA AND T_RICHIEDENTE.IDCOMUNE = ISTANZE.IDCOMUNE AND T_RICHIEDENTE.CODICEANAGRAFE = ISTANZE.CODICERICHIEDENTE;
ALTER TABLE DYN2_CAMPIPROPRIETA MODIFY COLUMN VALORE VARCHAR(2000);
ALTER TABLE STP_ENDO_TIPO2 ADD CODICE_ENDO_REGIONALE VARCHAR(20); 
ALTER TABLE STP_ENDO_TIPO2 ADD CODICE_TIPOLOGIA_ENDO NUMERIC(4,0);
CREATE OR REPLACE ALGORITHM=MERGE VIEW VW_SCADENZARIO AS
  SELECT VW_BATCH_SCADENZARIO.IDCOMUNE                      AS IDCOMUNE,
    VW_BATCH_SCADENZARIO.ID                                 AS CODICESCADENZA,
    VW_BATCH_SCADENZARIO.SOFTWARE                           AS software,
    VW_BATCH_SCADENZARIO.CODICEISTANZA                      AS codiceistanza,
    ISTANZE.NUMEROPROTOCOLLO                                AS numeroprotocollo,
    ISTANZE.DATAPROTOCOLLO                                  AS dataprotocollo,
    ISTANZE.NUMEROISTANZA                                   AS NUMEROISTANZA,
    ISTANZE.CHIUSURA                                        AS CODSTATOISTANZA,
    STATIISTANZA.STATO                                      AS DESCRSTATOISTANZA,
    VW_BATCH_SCADENZARIO.CODICEMOVIMENTO                    AS CODMOVIMENTO,
    VW_BATCH_SCADENZARIO.DESCRMOVIMENTO                     AS DESCRMOVIMENTO,
    DATE_FORMAT(MOVIMENTI.DATA,_utf8'%d/%m/%Y')                    AS DATAMOVIMENTO,
    VW_BATCH_SCADENZARIO.TIPOMOVIMENTODAFARE                AS CODMOVIMENTODAFARE,
    VW_BATCH_SCADENZARIO.DESCRMOVIMENTODAFARE               AS DESCRMOVIMENTODAFARE,
    DATE_FORMAT(VW_BATCH_SCADENZARIO.DATASCADENZA,_utf8'%d/%m/%Y') AS DATASCADENZASTR,
    VW_BATCH_SCADENZARIO.codiceinventario                   AS codiceinventario,
    VW_BATCH_SCADENZARIO.CODICEAMMINISTRAZIONE              AS CODICEAMMINISTRAZIONE,
    RESPONSABILI.RESPONSABILE                               AS RESPONSABILE,
    INVENTARIOPROCEDIMENTI.PROCEDIMENTO                     AS PROCEDIMENTO,
    TIPIPROCEDURE.PROCEDURA                                 AS PROCEDURA,
    SOFTWARE.DESCRIZIONE                                    AS MODULOSOFTWARE,
    AMMINISTRAZIONI.AMMINISTRAZIONE                         AS AMM_amministrazione,
    AMMINISTRAZIONI.PARTITAIVA                              AS AMM_PARTITAIVA,
    AMMINISTRAZIONI.PASSWORD                                AS AMM_PASSWORD,
    CONCAT_WS(' ',ANAGRAFE.NOMINATIVO, ANAGRAFE.NOME)AS RIC_NOMINATIVO,
    IFNULL(ANAGRAFE.CODICEFISCALE,'') AS RIC_CODICEFISCALE,
    IFNULL(ANAGRAFE.PARTITAIVA,'')    AS RIC_PARTITAIVA,
    ANAGRAFE.INDIRIZZO             AS RIC_INDIRIZZO,
    ANAGRAFE.CAP                   AS RIC_CAP,
    ANAGRAFE.CITTA                 AS RIC_LOCALITA,
    COMUNERESIDENZA.COMUNE         AS RIC_CITTA,
    COMUNERESIDENZA.PROVINCIA      AS RIC_PROVINCIA,
    ANAGRAFE.PASSWORD              AS RIC_PASSWORD,
    CONCAT_WS(' ',TECNICO.NOMINATIVO, TECNICO.NOME) AS TEC_NOMINATIVO,
    IFNULL(TECNICO.CODICEFISCALE,'') AS TEC_CODICEFISCALE,
    IFNULL(TECNICO.PARTITAIVA,'')    AS TEC_PARTITAIVA,
    TECNICO.PASSWORD              AS TEC_PASSWORD,
    CONCAT_WS(' ', AZIENDA.NOMINATIVO, AZIENDA.NOME) AS AZ_NOMINATIVO,
    IFNULL(AZIENDA.CODICEFISCALE,'') AS AZ_CODICEFISCALE,
    IFNULL(AZIENDA.PARTITAIVA,'')    AS AZ_PARTITAIVA,
    AZIENDA.PASSWORD              AS AZ_PASSWORD,
    TIPIMOVIMENTO.FK_FO_SOGGETTIESTERNI
  FROM VW_BATCH_SCADENZARIO
  JOIN ISTANZE ON ISTANZE.IDCOMUNE = VW_BATCH_SCADENZARIO.IDCOMUNE
  AND ISTANZE.CODICEISTANZA = VW_BATCH_SCADENZARIO.CODICEISTANZA
  JOIN RESPONSABILI ON RESPONSABILI.IDCOMUNE = ISTANZE.IDCOMUNE
  AND RESPONSABILI.CODICERESPONSABILE = ISTANZE.CODICERESPONSABILE
  JOIN MOVIMENTI ON MOVIMENTI.IDCOMUNE = VW_BATCH_SCADENZARIO.IDCOMUNE
  AND MOVIMENTI.CODICEMOVIMENTO = VW_BATCH_SCADENZARIO.CODICEMOVIMENTO
  JOIN TIPIMOVIMENTO ON TIPIMOVIMENTO.IDCOMUNE = VW_BATCH_SCADENZARIO.IDCOMUNE
  AND TIPIMOVIMENTO.TIPOMOVIMENTO  = VW_BATCH_SCADENZARIO.TIPOMOVIMENTODAFARE
  JOIN TIPIPROCEDURE ON TIPIPROCEDURE.IDCOMUNE = ISTANZE.IDCOMUNE
  AND TIPIPROCEDURE.CODICEPROCEDURA = ISTANZE.CODICEPROCEDURA
  JOIN SOFTWARE ON SOFTWARE.CODICE = VW_BATCH_SCADENZARIO.SOFTWARE
  JOIN ANAGRAFE ON ANAGRAFE.IDCOMUNE = ISTANZE.IDCOMUNE
  AND ANAGRAFE.CODICEANAGRAFE = ISTANZE.CODICERICHIEDENTE
  JOIN STATIISTANZA ON STATIISTANZA.IDCOMUNE = ISTANZE.IDCOMUNE
  AND STATIISTANZA.SOFTWARE = ISTANZE.SOFTWARE
  AND STATIISTANZA.CODICESTATO = ISTANZE.CHIUSURA
  LEFT OUTER JOIN AMMINISTRAZIONI ON AMMINISTRAZIONI.IDCOMUNE = VW_BATCH_SCADENZARIO.IDCOMUNE
  AND AMMINISTRAZIONI.CODICEAMMINISTRAZIONE = VW_BATCH_SCADENZARIO.CODICEAMMINISTRAZIONE
  LEFT OUTER JOIN INVENTARIOPROCEDIMENTI ON INVENTARIOPROCEDIMENTI.IDCOMUNE = VW_BATCH_SCADENZARIO.IDCOMUNE
  AND INVENTARIOPROCEDIMENTI.CODICEINVENTARIO = VW_BATCH_SCADENZARIO.CODICEINVENTARIO
  LEFT OUTER JOIN COMUNI COMUNERESIDENZA ON COMUNERESIDENZA.CODICECOMUNE = ANAGRAFE.COMUNERESIDENZA
  LEFT OUTER JOIN ANAGRAFE TECNICO ON TECNICO.IDCOMUNE = ISTANZE.IDCOMUNE
  AND TECNICO.CODICEANAGRAFE = ISTANZE.CODICEPROFESSIONISTA
  LEFT OUTER JOIN ANAGRAFE AZIENDA ON AZIENDA.IDCOMUNE = ISTANZE.IDCOMUNE
  AND AZIENDA.CODICEANAGRAFE = ISTANZE.CODICETITOLARELEGALE;

ALTER TABLE TIPIMOV_STC_MAPPING ADD FLAG_CREAINVIA_ALLEGATI NUMERIC(1,0);
ALTER TABLE TIPIMOV_STC_MAPPING ADD FLAG_ALLEGA_DOCUMENTI_ISTANZA NUMERIC(1,0);
ALTER TABLE TIPIMOV_STC_MAPPING ADD FLAG_PROTOCOLLA NUMERIC(1,0);
ALTER TABLE TIPIMOV_STC_MAPPING ADD PROTOCOLLO_FLUSSO VARCHAR(1);
ALTER TABLE TIPIMOV_STC_MAPPING ADD PROTOCOLLO_TIPODOCUMENTO VARCHAR(10);
ALTER TABLE TIPIMOV_STC_MAPPING ADD PROTOCOLLO_OGGETTO NUMERIC(4,0);
ALTER TABLE TIPIMOV_STC_MAPPING ADD PROTOCOLLO_MITTENTE NUMERIC(10,0);
ALTER TABLE TIPIMOV_STC_MAPPING ADD FLAG_NOTIFICA_AUTOMATICA NUMERIC(1,0);


ALTER TABLE TIPIMOV_STC_MAPPING ADD CONSTRAINT FK_TIPIMOV_STC_MAP_TIPI_DOC FOREIGN KEY (IDCOMUNE,PROTOCOLLO_TIPODOCUMENTO) REFERENCES PROTOCOLLO_TIPIDOCUMENTO(IDCOMUNE,CODICE);
ALTER TABLE TIPIMOV_STC_MAPPING ADD CONSTRAINT FK_TIPIMOV_STC_MAP_PROT_FL FOREIGN KEY (PROTOCOLLO_FLUSSO ) REFERENCES PROTOCOLLO_FLUSSO(CODICE );
ALTER TABLE TIPIMOV_STC_MAPPING ADD CONSTRAINT FK_TIPIMOV_STC_MAP_AMMIN FOREIGN KEY (IDCOMUNE,PROTOCOLLO_MITTENTE) REFERENCES AMMINISTRAZIONI(IDCOMUNE,CODICEAMMINISTRAZIONE);
ALTER TABLE TIPIMOV_STC_MAPPING ADD CONSTRAINT FK_TIPIMOV_STC_MAP_MAIL_TIPO FOREIGN KEY (IDCOMUNE,PROTOCOLLO_OGGETTO) REFERENCES MAILTIPO(IDCOMUNE,CODICEMAIL);  

CREATE TABLE ALBEROPROC_ARENDO 
(
  IDCOMUNE VARCHAR(6) NOT NULL 
, ID NUMERIC(10, 0) NOT NULL 
, FK_SCID NUMERIC(10, 0) NOT NULL 
, FK_FAMIGLIAENDO NUMERIC(10, 0) NOT NULL 
, FK_CATEGORIAENDO NUMERIC(10, 0) 
, CONSTRAINT ALBEROPROC_ARENDO_PK PRIMARY KEY 
  (
    IDCOMUNE 
  , ID 
  )
);

ALTER TABLE ALBEROPROC_ARENDO ADD CONSTRAINT ALBEROPROC_ARENDO_ALBEROP_FK1 FOREIGN KEY
( IDCOMUNE , FK_SCID ) REFERENCES ALBEROPROC ( IDCOMUNE , SC_ID );

ALTER TABLE ALBEROPROC_ARENDO ADD CONSTRAINT ALBEROPROC_ARENDO_TIPIFAM_FK1 FOREIGN KEY
( IDCOMUNE , FK_FAMIGLIAENDO ) REFERENCES TIPIFAMIGLIEENDO ( IDCOMUNE , CODICE );

ALTER TABLE ALBEROPROC_ARENDO ADD CONSTRAINT ALBEROPROC_ARENDO_TIPIEND_FK1 FOREIGN KEY
( IDCOMUNE , FK_CATEGORIAENDO ) REFERENCES TIPIENDO ( IDCOMUNE , CODICE );

CREATE INDEX IDX_MOVIMENTI_006 ON MOVIMENTI (IDCOMUNE, TIPOMOVIMENTO);

CREATE INDEX IDX_COMUNI_PROVINCE002 ON COMUNI (SIGLAPROVINCIA, PROVINCIA);
ALTER TABLE MOVIMENTIALLEGATI MODIFY COLUMN DESCRIZIONE VARCHAR(4000);
ALTER TABLE ISTANZEALLEGATI MODIFY COLUMN ALLEGATOEXTRA VARCHAR(4000);

ALTER TABLE CLMENU_JAVA ADD LINK_STANDARD VARCHAR(150);

ALTER TABLE CONFIGURAZIONE ADD CONSTRAINT FK_MAIL_AMMENDO_MAILTIPO FOREIGN KEY (IDCOMUNE,MAIL_AMMENDO) REFERENCES MAILTIPO(IDCOMUNE,CODICEMAIL);
ALTER TABLE CONFIGURAZIONE ADD CONSTRAINT FK_MAIL_MOVRIC_MAILTIPO FOREIGN KEY (IDCOMUNE,MAIL_MOVIRIC) REFERENCES MAILTIPO(IDCOMUNE,CODICEMAIL);
ALTER TABLE CONFIGURAZIONE ADD CONSTRAINT FK_MAIL_MOVAMM_MAILTIPO FOREIGN KEY (IDCOMUNE,MAIL_MOVIAMM) REFERENCES MAILTIPO(IDCOMUNE,CODICEMAIL);
ALTER TABLE CONFIGURAZIONE ADD CONSTRAINT FK_MAIL_MOVNEG_MAILTIPO FOREIGN KEY (IDCOMUNE,MAIL_MOVINEG) REFERENCES MAILTIPO(IDCOMUNE,CODICEMAIL);

CREATE INDEX IDX_ANAGRAFE_006 ON ANAGRAFE (IDCOMUNE, NOMINATIVO, NOME);
ALTER TABLE MOVIMENTI ADD CODICEAMMINISTRAZIONE_STC NUMERIC(10,0); 
ALTER TABLE MOVIMENTI ADD CONSTRAINT FK_MOVIMENTI_AMM_STC FOREIGN KEY (IDCOMUNE, CODICEAMMINISTRAZIONE_STC) REFERENCES AMMINISTRAZIONI (IDCOMUNE, CODICEAMMINISTRAZIONE);

CREATE UNIQUE INDEX IDX_ALBEROPROC_ARENDO_001 ON ALBEROPROC_ARENDO(IDCOMUNE, FK_SCID, FK_FAMIGLIAENDO, FK_CATEGORIAENDO);
CREATE OR REPLACE ALGORITHM=MERGE VIEW VW_ISTANZE_OPE_RUOLI AS SELECT RR.IDCOMUNE, RR.IDRUOLO, RR.CODICERESPONSABILE, IR.CODICEISTANZA FROM RESPONSABILIRUOLI RR INNER JOIN  ISTANZERUOLI IR ON RR.IDCOMUNE=IR.IDCOMUNE AND RR.IDRUOLO = IR.IDRUOLO;
