package it.gruppoinit.pal.gp.core.report.helper;

public enum TypeReport {
    OPERATORI, AMMINISTRAZIONI, TEMPIFICAZIONI, FORME_GIURIDICHE, RICHIEDENTI, AMMINISTRAZIONE, RICEVUTA_ISTANZA, ITER_ISTANZA, REPORT_ISTANZA, STATISTICHE_ISTANZA_OPERATORE, STATISTICHE_ISTANZA_PROCEDURA,
    STATISTICHE_ISTANZA_STATO,STATISTICHE_ISTANZA_PROCEDIMENTO
}
