CREATE TABLE MASSIVE_TESTATA(
   IDCOMUNE VARCHAR(6)  NOT NULL, 
   ID DECIMAL(6,0) NOT NULL,
   DESCRIZIONE VARCHAR(2000) NOT NULL,
   DATA_COMUNICAZIONE DATETIME NOT NULL,
   CODICERESPONSABILE DECIMAL(8,0) NOT NULL,
   FKID_MAILTIPO DECIMAL(4,0),
   ESCLUDI_NO_MAIL DECIMAL(1,0) NOT NULL,
   DATA_ELIMINAZIONE DATETIME )ENGINE=INNODB DEFAULT CHARSET=UTF8;

ALTER TABLE MASSIVE_TESTATA ADD CONSTRAINT PK_MASSIVETESTATA PRIMARY KEY(IDCOMUNE,ID); 
ALTER TABLE MASSIVE_TESTATA ADD CONSTRAINT FK_MASSIVETESTATA_RESP FOREIGN KEY(IDCOMUNE,CODICERESPONSABILE) REFERENCES RESPONSABILI(IDCOMUNE,CODICERESPONSABILE);
ALTER TABLE MASSIVE_TESTATA ADD CONSTRAINT FK_MASSIVETESTATA_MAILTIPO FOREIGN KEY(IDCOMUNE,FKID_MAILTIPO) REFERENCES MAILTIPO(IDCOMUNE,CODICEMAIL);


CREATE TABLE MASSIVE_T_FIRMATARI(
   IDCOMUNE VARCHAR(6)  NOT NULL, 
   ID DECIMAL(6,0) NOT NULL,
   FKID_TESTATA DECIMAL(6,0) NOT NULL,
   CODICERESPONSABILE DECIMAL(8,0) NOT NULL )ENGINE=INNODB DEFAULT CHARSET=UTF8;

ALTER TABLE MASSIVE_T_FIRMATARI ADD CONSTRAINT PK_MASSIVETFIRMATARI PRIMARY KEY(IDCOMUNE,ID); 
ALTER TABLE MASSIVE_T_FIRMATARI ADD CONSTRAINT FK_MASSIVETFIRMATARI_TESTATA FOREIGN KEY(IDCOMUNE,FKID_TESTATA) REFERENCES MASSIVE_TESTATA(IDCOMUNE,ID);
ALTER TABLE MASSIVE_T_FIRMATARI ADD CONSTRAINT FK_MASSIVETFIRMATARI_RESP FOREIGN KEY(IDCOMUNE,CODICERESPONSABILE) REFERENCES RESPONSABILI(IDCOMUNE,CODICERESPONSABILE);
   
   
CREATE TABLE MASSIVE_T_ALLEGATI(
   IDCOMUNE VARCHAR(6)  NOT NULL,
   ID DECIMAL(6,0) NOT NULL,
   FKID_TESTATA DECIMAL(6,0) NOT NULL,
   CODICEOGGETTO DECIMAL(10,0) NOT NULL )ENGINE=INNODB DEFAULT CHARSET=UTF8;

ALTER TABLE MASSIVE_T_ALLEGATI ADD CONSTRAINT PK_MASSIVETALLEGATI PRIMARY KEY(IDCOMUNE,ID);
ALTER TABLE MASSIVE_T_ALLEGATI ADD CONSTRAINT FK_MASSIVETALLEGATI_TESTATA FOREIGN KEY(IDCOMUNE,FKID_TESTATA) REFERENCES MASSIVE_TESTATA(IDCOMUNE,ID);
ALTER TABLE MASSIVE_T_ALLEGATI ADD CONSTRAINT FK_MASSIVETALLEGATI_OGG FOREIGN KEY(IDCOMUNE,CODICEOGGETTO) REFERENCES OGGETTI(IDCOMUNE,CODICEOGGETTO);


CREATE TABLE MASSIVE_T_LETTERE(
   IDCOMUNE VARCHAR(6)  NOT NULL,
   ID DECIMAL(6,0) NOT NULL,
   FKID_TESTATA DECIMAL(6,0) NOT NULL,
   FKID_LETTERA_TIPO DECIMAL(10,0) NOT NULL,
   TRASFORMA_IN_PDF DECIMAL(1,0) NOT NULL )ENGINE=INNODB DEFAULT CHARSET=UTF8;

ALTER TABLE MASSIVE_T_LETTERE ADD CONSTRAINT PK_MASSIVETLETTERE PRIMARY KEY(IDCOMUNE,ID);
ALTER TABLE MASSIVE_T_LETTERE ADD CONSTRAINT FK_MASSIVETLETTERE_TESTATA FOREIGN KEY(IDCOMUNE,FKID_TESTATA) REFERENCES MASSIVE_TESTATA(IDCOMUNE,ID); 
ALTER TABLE MASSIVE_T_LETTERE ADD CONSTRAINT FK_MASSIVETLETTERE_LETTIPO FOREIGN KEY(IDCOMUNE,FKID_LETTERA_TIPO) REFERENCES LETTERETIPO(IDCOMUNE,CODICELETTERA);


CREATE TABLE MASSIVE_DETTAGLIO(
   IDCOMUNE VARCHAR(6)  NOT NULL,
   ID DECIMAL(6,0) NOT NULL,
   FKID_TESTATA DECIMAL(6,0) NOT NULL,
   CODICEANAGRAFE DECIMAL(6,0) NOT NULL,
   ULTIMO_STATO_COMPLETATO VARCHAR(100 ),
   ULTIMO_STATO_DATA DATETIME,
   MAIL_DESTINATARIO VARCHAR(100 ),
   ERRORE VARCHAR(2000 )
)ENGINE=INNODB DEFAULT CHARSET=UTF8;

ALTER TABLE MASSIVE_DETTAGLIO ADD CONSTRAINT PK_MASSIVEDETTAGLIO PRIMARY KEY(IDCOMUNE,ID); 
ALTER TABLE MASSIVE_DETTAGLIO ADD CONSTRAINT FK_MASSIVEDETTAGLIO_TESTATA FOREIGN KEY(IDCOMUNE,FKID_TESTATA) REFERENCES MASSIVE_TESTATA(IDCOMUNE,ID);
ALTER TABLE MASSIVE_DETTAGLIO ADD CONSTRAINT FK_MASSIVEDETTAGLIO_ANAGRAFE FOREIGN KEY(IDCOMUNE,CODICEANAGRAFE) REFERENCES ANAGRAFE(IDCOMUNE,CODICEANAGRAFE);


CREATE TABLE MASSIVE_D_ALLEGATI(
   IDCOMUNE VARCHAR(6)  NOT NULL,
   ID DECIMAL(6,0) NOT NULL,
   FKID_DETTAGLIO DECIMAL(6,0) NOT NULL,
   CHIAVE VARCHAR(50) NOT NULL, 
   CODICEOGGETTO DECIMAL(10,0) NOT NULL )ENGINE=INNODB DEFAULT CHARSET=UTF8;

ALTER TABLE MASSIVE_D_ALLEGATI ADD CONSTRAINT PK_MASSIVEDALLEGATI PRIMARY KEY(IDCOMUNE,ID); 
ALTER TABLE MASSIVE_D_ALLEGATI ADD CONSTRAINT FK_MASSIVEDALLEGATI_DETTAGLIO FOREIGN KEY(IDCOMUNE,FKID_DETTAGLIO) REFERENCES MASSIVE_DETTAGLIO(IDCOMUNE,ID);
ALTER TABLE MASSIVE_D_ALLEGATI ADD CONSTRAINT FK_MASSIVEDALLEGATI_OGG FOREIGN KEY(IDCOMUNE,CODICEOGGETTO) REFERENCES OGGETTI(IDCOMUNE,CODICEOGGETTO);


CREATE TABLE BOLL_MASSIVE_T(
   IDCOMUNE VARCHAR(6)  NOT NULL,
   ID DECIMAL(6,0) NOT NULL,
   FKID_TESTATA DECIMAL(6,0) NOT NULL,
   FKID_BOLLETTAZIONE DECIMAL(4,0) NOT NULL )ENGINE=INNODB DEFAULT CHARSET=UTF8;

ALTER TABLE BOLL_MASSIVE_T ADD CONSTRAINT PK_BOLLMASSIVET PRIMARY KEY(IDCOMUNE,ID); 
ALTER TABLE BOLL_MASSIVE_T ADD CONSTRAINT FK_BOLLMASSIVET_TESTATA FOREIGN KEY(IDCOMUNE,FKID_TESTATA) REFERENCES MASSIVE_TESTATA(IDCOMUNE,ID); 
ALTER TABLE BOLL_MASSIVE_T ADD CONSTRAINT FK_BOLLMASSIVET_BOLL FOREIGN KEY(IDCOMUNE,FKID_BOLLETTAZIONE) REFERENCES BOLL_GEST_TESTATA(IDCOMUNE,ID);


CREATE TABLE BOLL_MASSIVE_D(
   IDCOMUNE VARCHAR(6)  NOT NULL,
   ID DECIMAL(6,0)  NOT NULL,
   FKID_MASSIVE_D DECIMAL(6,0) NOT NULL,
   FKID_BOLL_GEST_DETTAGLIO DECIMAL(10,0) NOT NULL,
   CODICEMOVIMENTO DECIMAL(8,0) )ENGINE=INNODB DEFAULT CHARSET=UTF8;

ALTER TABLE BOLL_MASSIVE_D ADD CONSTRAINT PK_BOLLMASSIVED PRIMARY KEY(IDCOMUNE,ID); 
ALTER TABLE BOLL_MASSIVE_D ADD CONSTRAINT FK_BOLLMASSIVED_MASSIVED FOREIGN KEY(IDCOMUNE,FKID_MASSIVE_D) REFERENCES MASSIVE_DETTAGLIO(IDCOMUNE,ID); 
ALTER TABLE BOLL_MASSIVE_D ADD CONSTRAINT FK_BOLLMASSIVED_BOLLGESTDETT FOREIGN KEY(IDCOMUNE,FKID_BOLL_GEST_DETTAGLIO) REFERENCES BOLL_GEST_DETTAGLIO(IDCOMUNE,ID); 
ALTER TABLE BOLL_MASSIVE_D ADD CONSTRAINT FK_BOLLMASSIVED_MOV FOREIGN KEY(IDCOMUNE,CODICEMOVIMENTO) REFERENCES MOVIMENTI(IDCOMUNE,CODICEMOVIMENTO);


CREATE TABLE MASSIVE_PARAMETRI(
   IDCOMUNE VARCHAR(6)  NOT NULL,
   ID DECIMAL(6,0)  NOT NULL,
   FKID_TESTATA DECIMAL(6)  NOT NULL,
   CHIAVE VARCHAR(50) NOT NULL,
   VALORE VARCHAR(4000) NOT NULL )ENGINE=INNODB DEFAULT CHARSET=UTF8;

ALTER TABLE MASSIVE_PARAMETRI ADD CONSTRAINT PK_MASSIVEPARAMETRI PRIMARY KEY(IDCOMUNE,ID);
ALTER TABLE MASSIVE_PARAMETRI ADD CONSTRAINT FK_MASSIVEPARAMETRI_TESTATA FOREIGN KEY(IDCOMUNE,FKID_TESTATA) REFERENCES MASSIVE_TESTATA(IDCOMUNE,ID);

ALTER TABLE MASSIVE_TESTATA ADD COLUMN SENDERACCOUNT NUMERIC(5,0);
ALTER TABLE MASSIVE_TESTATA ADD CONSTRAINT FK_MASSIVETESTATA_MAILCONFIG FOREIGN KEY(IDCOMUNE,SENDERACCOUNT) REFERENCES MAIL_CONFIG(IDCOMUNE,ID);

ALTER TABLE MASSIVE_DETTAGLIO ADD COLUMN NUMEROPROTOCOLLO VARCHAR(30);
ALTER TABLE MASSIVE_DETTAGLIO ADD COLUMN DATAPROTOCOLLO DATETIME;
ALTER TABLE MASSIVE_DETTAGLIO ADD COLUMN FKIDPROTOCOLLO VARCHAR(400);


ALTER TABLE documenti_da_firmare MODIFY CODICEISTANZA NUMERIC(6,0) NULL;
ALTER TABLE documenti_da_firmare MODIFY CODICEMOVALLEGATI NUMERIC(8,0) NULL;


CREATE TABLE MESSAGGI_MAIL(
  IDCOMUNE  VARCHAR(6) NOT NULL
, ID NUMERIC(10,0) NOT NULL
, MITTENTE  VARCHAR(200) NOT NULL
, DESTINATARIO   VARCHAR(600)
, DESTINATARIOCC VARCHAR(600)
, DESTINATARIOBCC   VARCHAR(600)
, OGGETTO  VARCHAR(1500)
, DATAINVIO  DATETIME
, MESSAGE_ID  VARCHAR(400)
, ID_PADRE NUMERIC(10,0)
, CORPO LONGTEXT
, ACCOUNT_ID NUMERIC(5,0) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE MESSAGGI_MAIL ADD CONSTRAINT PK_MESSAGGI_MAIL PRIMARY KEY(IDCOMUNE,ID); 
ALTER TABLE MESSAGGI_MAIL ADD CONSTRAINT FK_MESSAGGIMAIL_PADRE FOREIGN KEY (IDCOMUNE,ID_PADRE) REFERENCES MESSAGGI_MAIL(IDCOMUNE,ID);
ALTER TABLE MESSAGGI_MAIL ADD CONSTRAINT FK_MESSAGGIMAIL_MAILCONFIG FOREIGN KEY (IDCOMUNE,ACCOUNT_ID) REFERENCES MAIL_CONFIG(IDCOMUNE,ID);

CREATE TABLE MESSAGGI_MAIL_ALLEGATI(
  IDCOMUNE  VARCHAR(6)NOT NULL
, ID NUMERIC(10,0)  NOT NULL
, FKID_MESSAGGIMAIL  NUMERIC(10,0)NOT NULL
, CODICEOGGETTO  NUMERIC(10,0) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE MESSAGGI_MAIL_ALLEGATI ADD CONSTRAINT PK_MESSAGGI_MAIL_ALLEGATI PRIMARY KEY(IDCOMUNE,ID); 
ALTER TABLE MESSAGGI_MAIL_ALLEGATI ADD CONSTRAINT FK_MESSAGGIMAILALL_MSGMAIL FOREIGN KEY(IDCOMUNE,FKID_MESSAGGIMAIL) REFERENCES MESSAGGI_MAIL(IDCOMUNE,ID); 
ALTER TABLE MESSAGGI_MAIL_ALLEGATI ADD CONSTRAINT FK_MESSAGGIMAILALL_OGGETTI FOREIGN KEY(IDCOMUNE,CODICEOGGETTO) REFERENCES OGGETTI(IDCOMUNE,CODICEOGGETTO); 
CREATE INDEX IDX_MESSAGGI_MAIL_ALLEGATI_001 ON MESSAGGI_MAIL_ALLEGATI(IDCOMUNE,FKID_MESSAGGIMAIL);

CREATE TABLE  MASSIVE_DETT_MESSAGGIMAIL(
  IDCOMUNE VARCHAR(6)  NOT NULL
, ID  NUMERIC(10,0) NOT NULL
, FKID_MASSIVE_D  NUMERIC(6,0) NOT NULL
, FKID_MESSAGGIMAIL  NUMERIC(10,0) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE MASSIVE_DETT_MESSAGGIMAIL ADD CONSTRAINT PK_MASSIVEDETTMAIL PRIMARY KEY(IDCOMUNE,ID); 
ALTER TABLE MASSIVE_DETT_MESSAGGIMAIL ADD CONSTRAINT FK_MASSIVEDETTMAIL_MASSIVEDETT FOREIGN KEY(IDCOMUNE,FKID_MASSIVE_D) REFERENCES MASSIVE_DETTAGLIO(IDCOMUNE,ID); 
ALTER TABLE MASSIVE_DETT_MESSAGGIMAIL ADD CONSTRAINT FK_MASSIVEDETTMAIL_MESSMAIL FOREIGN KEY(IDCOMUNE,FKID_MESSAGGIMAIL) REFERENCES MESSAGGI_MAIL(IDCOMUNE,ID); 
CREATE INDEX IDX_MASSIVEDETTMESGMAIL_001 ON MASSIVE_DETT_MESSAGGIMAIL(IDCOMUNE,FKID_MASSIVE_D);
CREATE INDEX IDX_MASSIVEDETTMESGMAIL_002 ON MASSIVE_DETT_MESSAGGIMAIL(IDCOMUNE,FKID_MESSAGGIMAIL);

CREATE TABLE MASSIVE_DETT_DOCDAFIRMARE(
IDCOMUNE varchar(6) NOT NULL
,ID NUMERIC(10,0) NOT NULL
,FKID_MASSIVE_D  NUMERIC(6,0) NOT NULL
,FK_DOCDAFIRMARE_ID  NUMERIC(6,0) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE MASSIVE_DETT_DOCDAFIRMARE ADD CONSTRAINT PK_MASSIVEDDOCDAFIRMARE PRIMARY KEY(IDCOMUNE,ID);
ALTER TABLE MASSIVE_DETT_DOCDAFIRMARE ADD CONSTRAINT FK_MASSDDOCDAF_MASSIVED FOREIGN KEY(IDCOMUNE,FKID_MASSIVE_D) REFERENCES MASSIVE_DETTAGLIO(IDCOMUNE,ID);
ALTER TABLE MASSIVE_DETT_DOCDAFIRMARE ADD CONSTRAINT FK_MASSDDOCDAF_DOCDAFIRM FOREIGN KEY(IDCOMUNE,FK_DOCDAFIRMARE_ID) REFERENCES DOCUMENTI_DA_FIRMARE(IDCOMUNE,ID);
CREATE INDEX IDX_MASSIVED_DOCDAFIRM_001 ON MASSIVE_DETT_DOCDAFIRMARE(IDCOMUNE, FKID_MASSIVE_D);

CREATE INDEX IDX_MASSIVED_DOCDAFIRM_002 on MASSIVE_DETT_DOCDAFIRMARE(IDCOMUNE, FK_DOCDAFIRMARE_ID);


ALTER TABLE MASSIVE_TESTATA ADD PROT_CODICEAMMINISTRAZIONE NUMERIC(10,0)   ;
ALTER TABLE MASSIVE_TESTATA ADD PROT_CLASSIFICA      VARCHAR(50) ;
ALTER TABLE MASSIVE_TESTATA ADD PROT_TIPODOCUMENTO   VARCHAR(50) ;
ALTER TABLE MASSIVE_TESTATA ADD PROT_FKID_MAILTIPO   NUMERIC(4,0)    ;
ALTER TABLE MASSIVE_TESTATA ADD CONSTRAINT FK_MASSIVET_AMMINISTRAZIONI FOREIGN KEY(IDCOMUNE,PROT_CODICEAMMINISTRAZIONE) REFERENCES AMMINISTRAZIONI(IDCOMUNE,CODICEAMMINISTRAZIONE);
ALTER TABLE MASSIVE_TESTATA ADD CONSTRAINT FK_MASSIVET_MAILTIPO FOREIGN KEY(IDCOMUNE,PROT_FKID_MAILTIPO) REFERENCES MAILTIPO(IDCOMUNE,CODICEMAIL);

alter table MASSIVE_TESTATA drop column ESCLUDI_NO_MAIL;

alter table massive_D_Allegati drop column chiave;


create table tipimov_tipisoggetto (
   IDCOMUNE varchar(6) not null,
   ID numeric(10,0) not null,
   FK_IDTIPOMOVIMENTO varchar(8) not null,
   FK_IDTIPOSOGGETTO numeric(10,0) not null,
   CONSTRAINT tipimov_tipisogg_pk PRIMARY KEY (IDCOMUNE, ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE tipimov_tipisoggetto
  ADD CONSTRAINT fk_tt_tipisogg FOREIGN KEY (
    IDCOMUNE,FK_IDTIPOSOGGETTO
  ) REFERENCES tipisoggetto (
    idcomune,
    codicetiposoggetto 
  );
    
ALTER TABLE tipimov_tipisoggetto
  ADD CONSTRAINT fk_tt_tipimov FOREIGN KEY (
    IDCOMUNE, FK_IDTIPOMOVIMENTO
  ) REFERENCES tipimovimento (
    idcomune,
    tipomovimento 
  );
CREATE TABLE MASSIVE_T_PROTOCOLLO(
IDCOMUNE VARCHAR(6) NOT NULL,
ID NUMERIC(6,0) NOT NULL,
FKID_TESTATA NUMERIC(6,0) NOT NULL,
CODICECOMUNE VARCHAR(5),
CODICEAMMINISTRAZIONE NUMERIC(10,0),
CLASSIFICA VARCHAR(50),
TIPODOCUMENTO VARCHAR(50)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE MASSIVE_T_PROTOCOLLO ADD CONSTRAINT PK_MASSIVE_T_PROTOCOLLO PRIMARY KEY (IDCOMUNE, ID);

ALTER TABLE MASSIVE_T_PROTOCOLLO ADD CONSTRAINT FK_MASSIVETPROT_MASST FOREIGN KEY (IDCOMUNE, FKID_TESTATA) REFERENCES MASSIVE_TESTATA (IDCOMUNE,ID);

ALTER TABLE MASSIVE_T_PROTOCOLLO ADD CONSTRAINT FK_MASSIVETPROT_COMUNI FOREIGN KEY ( CODICECOMUNE) REFERENCES COMUNI (CODICECOMUNE);

ALTER TABLE MASSIVE_T_PROTOCOLLO ADD CONSTRAINT FK_MASSIVETPROT_AMM FOREIGN KEY (IDCOMUNE, CODICEAMMINISTRAZIONE) REFERENCES AMMINISTRAZIONI (IDCOMUNE,CODICEAMMINISTRAZIONE);

CREATE INDEX IDX_MASSIVE_T_PROTOCOLLO_01 ON MASSIVE_T_PROTOCOLLO(IDCOMUNE,FKID_TESTATA);

ALTER TABLE LOCK_TABLE MODIFY LOCK_NAME VARCHAR(255) ;

ALTER TABLE MASSIVE_TESTATA ADD DATA_CANCELLAZIONE DATETIME;
ALTER TABLE MASSIVE_TESTATA ADD RESP_CANCELLAZIONE NUMERIC(8,0);
ALTER TABLE MASSIVE_TESTATA ADD CONSTRAINT FK_MASSIVE_T_RESP_CANC FOREIGN KEY (IDCOMUNE,  RESP_CANCELLAZIONE) REFERENCES RESPONSABILI(IDCOMUNE,CODICERESPONSABILE);

ALTER TABLE BOLL_MASSIVE_D MODIFY CODICEMOVIMENTO NUMERIC(8,0) NULL;


ALTER TABLE PEOPLEPROCSPORTELLI ADD CONSTRAINT FK_PEOPLEPROCSPORTELLI_SOFT FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE (CODICE);

ALTER TABLE PEOPLEPROCSPORTELLI ADD CONSTRAINT UC_PEOPLEPROCSPORTELLI UNIQUE(IDCOMUNE, CODICECOMUNE, PEOPLE_PROC);


ALTER TABLE tipisoggetto ADD FLAG_LIVELLI_VISURA_PRATICA NUMERIC(4, 0);


ALTER TABLE PEOPLEPROCSPORTELLI ADD CONSTRAINT FK_PEOPLEPROCSPORTELLI_COMUNI FOREIGN KEY(CODICECOMUNE) REFERENCES COMUNI (CODICECOMUNE);
