<Project Sdk="Microsoft.NET.Sdk">


	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<AssemblyName>SIGeProSIT</AssemblyName>
		<PackageId>SIGePro.SIT</PackageId>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="RestSharp" Version="[106.12.0]" />
		<PackageReference Include="System.ServiceModel.Http" Version="[4.10.3]" />
		<PackageReference Include="System.Text.Json" Version="10.0.*" />
	</ItemGroup>


	<ItemGroup>
		<ProjectReference Include="..\SIGePro.Manager.DTO\SIGePro.Manager.DTO.csproj" />
		<ProjectReference Include="..\SIGePro.Exceptions\SIGePro.Exceptions.csproj" />
		<ProjectReference Include="..\SIGePro.Manager\SIGePro.Manager.csproj" />
	</ItemGroup>

</Project>