UPDATE RESPONSABILI_TM_SCA SET FLAG_ESCLUDE = 0 WHERE FLAG_ESCLUDE IS NULL;
UPDATE RESPONSABILI_TM_AVV SET FLAG_ESCLUDE = 0 WHERE FLAG_ESCLUDE IS NULL;

UPDATE RESPONSABILI SET DISABILITATO = 0 WHERE DISABILITATO IS NULL;

INSERT INTO CONFIGURAZIONEUTENTE (CODICERESPONSABILE, NOMEPARAMETRO, VALORE, IDCOMUNE) (SELECT CODICERESPONSABILE, 'COLONNA TERMINE PROCEDIMENTO' AS NOMEPARAMETRO, 1 AS VALORE, IDCOMUNE FROM RESPONSABILI WHERE  DISABILITATO = 0 );

INSERT INTO CONFIGURAZIONEUTENTE (CODICERESPONSABILE, NOMEPARAMETRO, VALORE, IDCOMUNE) (SELECT CODICERESPONSABILE, 'COLONNA OPERATORE' AS NOMEPARAMETRO, 1 AS VALORE, IDCOMUNE FROM RESPONSABILI WHERE  DISABILITATO = 0 );

INSERT INTO CONFIGURAZIONEUTENTE (CODICERESPONSABILE, NOMEPARAMETRO, VALORE, IDCOMUNE) (SELECT CODICERESPONSABILE, 'COLONNA AMMINISTRAZIONE' AS NOMEPARAMETRO, 1 AS VALORE, IDCOMUNE FROM RESPONSABILI WHERE  DISABILITATO = 0 );

INSERT INTO CONFIGURAZIONEUTENTE (CODICERESPONSABILE, NOMEPARAMETRO, VALORE, IDCOMUNE) (SELECT CODICERESPONSABILE, 'COLONNA MOVIMENTO FATTO' AS NOMEPARAMETRO, 1 AS VALORE, IDCOMUNE FROM RESPONSABILI WHERE  DISABILITATO = 0 );

INSERT INTO CONFIGURAZIONEUTENTE (CODICERESPONSABILE, NOMEPARAMETRO, VALORE, IDCOMUNE) (SELECT CODICERESPONSABILE, 'COLONNA RICHIEDENTE' AS NOMEPARAMETRO, 1 AS VALORE, IDCOMUNE FROM RESPONSABILI WHERE  DISABILITATO = 0 );

INSERT INTO CONFIGURAZIONEUTENTE (CODICERESPONSABILE, NOMEPARAMETRO, VALORE, IDCOMUNE) (SELECT CODICERESPONSABILE, 'COLONNA DATA PRESENTAZIONE PRATICA' AS NOMEPARAMETRO, 1 AS VALORE, IDCOMUNE FROM RESPONSABILI WHERE  DISABILITATO = 0 );
