create index pay_stato_pagamenti_001 on pay_stato_pagamenti (idcomune, fk_posizione_debitoria);

create index mercatipresenzed_002 on mercatipresenze_d (idcomune, fk_pay_pos_deb);


CREATE TABLE BLACKLIST_MOTIVI (
IDCOMUNE  VARCHAR2(6) NOT NULL,
ID NUMBER(10,0) NOT NULL,
MOTIVO CLOB,
DATA_INIZIO_BL DATE,
DATA_FINE_BL DATE
);
ALTER TABLE BLACKLIST_MOTIVI ADD CONSTRAINT PK_BLACKLIST_MOTIVI PRIMARY KEY(IDCOMUNE,ID);

create table BLACKLIST_SRC_P_DEB_SP(
IDCOMUNE  VARCHAR2(6) NOT NULL,
ID NUMBER(10,0) NOT NULL,    
FK_ID_PAYPOS_DEB NUMBER(9,0) NOT NULL,
FK_ID_BLACKLIST_MOT NUMBER(10,0),
DATA_INSERIMENTO DATE
);

ALTER TABLE BLACKLIST_SRC_P_DEB_SP ADD CONSTRAINT PK_BLACKLISTSRCPOSDEB PRIMARY KEY(IDCOMUNE,ID); ALTER TABLE BLACKLIST_SRC_P_DEB_SP ADD CONSTRAINT FK_BLSRCPOSDEB_POSDEB FOREIGN KEY(IDCOMUNE,FK_ID_PAYPOS_DEB) REFERENCES PAY_POSIZIONI_DEBITORIE(IDCOMUNE,ID);
ALTER TABLE BLACKLIST_SRC_P_DEB_SP ADD CONSTRAINT FK_BLSRCPOSDEB_BLMOT FOREIGN KEY(IDCOMUNE,FK_ID_BLACKLIST_MOT) REFERENCES BLACKLIST_MOTIVI(IDCOMUNE,ID); CREATE INDEX IDX_BLSRCPOSDEB_001 ON BLACKLIST_SRC_P_DEB_SP (IDCOMUNE,FK_ID_PAYPOS_DEB); CREATE INDEX IDX_BLSRCPOSDEB_002 ON BLACKLIST_SRC_P_DEB_SP (IDCOMUNE,FK_ID_BLACKLIST_MOT);

create table BLACKLIST_AUTORIZZAZIONI(
IDCOMUNE  VARCHAR2(6) NOT NULL,
ID NUMBER(10,0) NOT NULL,    
FK_ID_BLACKLIST_MOT NUMBER(10,0),
FK_CODICEANAGRAFE NUMBER(6,0),
FK_ID_AUTORIZZAZIONE NUMBER(6,0),
FLAG_PRINCIPALE NUMBER(1,0)
);

ALTER TABLE BLACKLIST_AUTORIZZAZIONI ADD CONSTRAINT PK_BLACKLISTAUTORIZ PRIMARY KEY(IDCOMUNE,ID); ALTER TABLE BLACKLIST_AUTORIZZAZIONI ADD CONSTRAINT FK_BL_AUTORIZ_ANAG FOREIGN KEY(IDCOMUNE,FK_CODICEANAGRAFE) REFERENCES ANAGRAFE(IDCOMUNE,CODICEANAGRAFE);
ALTER TABLE BLACKLIST_AUTORIZZAZIONI ADD CONSTRAINT FK_BL_AUTORIZ_AUTS FOREIGN KEY(IDCOMUNE,FK_ID_AUTORIZZAZIONE) REFERENCES AUTORIZZAZIONI(IDCOMUNE,ID); ALTER TABLE BLACKLIST_AUTORIZZAZIONI ADD CONSTRAINT FK_BL_AUTORIZ_BLMOT FOREIGN KEY(IDCOMUNE,FK_ID_BLACKLIST_MOT) REFERENCES BLACKLIST_MOTIVI(IDCOMUNE,ID);

CREATE INDEX IDX_BL_AUTORIZ_001 ON BLACKLIST_AUTORIZZAZIONI (IDCOMUNE,FK_CODICEANAGRAFE); CREATE INDEX IDX_BL_AUTORIZ_002 ON BLACKLIST_AUTORIZZAZIONI (IDCOMUNE,FK_ID_AUTORIZZAZIONE); CREATE INDEX IDX_BL_AUTORIZ_003 ON BLACKLIST_AUTORIZZAZIONI (IDCOMUNE,FK_ID_BLACKLIST_MOT);

