ALTER TABLE PAY_REGISTRAZIONI_CAUSALI MODIFY DESCRIZIONE VARCHAR(200);
ALTER TABLE PAY_REGISTRAZIONI_CAUSALI MODIFY CODICE_VERSAMENTO VARCHAR(200);
ALTER TABLE CONTI MODIFY COLUMN CODICESOTTOCONTO VARCHAR(30);

CREATE TABLE DYN2_METADATI_CONTESTI(
IDCOMUNE VARCHAR(6) NOT NULL, 
ID NUMERIC(6,0) NOT NULL,
CONTESTO  VARCHAR(255) NOT NULL, 
DESCRIZIONE VARCHAR(4000)) ENGINE=INNODB DEFAULT CHARSET=UTF8;

ALTER TABLE DYN2_METADATI_CONTESTI ADD CONSTRAINT PK_DYN2_METADATI_CONTESTI PRIMARY KEY(IDCOMUNE,ID);
CREATE INDEX IDX_DYN2METADATICONTESTI ON DYN2_METADATI_CONTESTI(IDCOMUNE,CONTESTO); 

CREATE TABLE DYN2_METADATI(
IDCOMUNE VARCHAR(6) NOT NULL, 
ID NUMERIC(6,0) NOT NULL,
FK_CONTESTO_ID  NUMERIC(6,0), 
FK_CAMPODINAMICO_ID NUMERIC(10,0),
CONTESTO_CAMPO VARCHAR(255)) ENGINE=INNODB DEFAULT CHARSET=UTF8;

ALTER TABLE DYN2_METADATI ADD CONSTRAINT PK_DYN2_METADATI PRIMARY KEY(IDCOMUNE,ID);
ALTER TABLE DYN2_METADATI ADD CONSTRAINT FK_DYN2_METADATI_CONTESTO FOREIGN KEY(IDCOMUNE,FK_CONTESTO_ID) REFERENCES DYN2_METADATI_CONTESTI(IDCOMUNE,ID);
ALTER TABLE DYN2_METADATI ADD CONSTRAINT FK_DYN2_CAMPI FOREIGN KEY(IDCOMUNE,FK_CAMPODINAMICO_ID) REFERENCES DYN2_CAMPI(IDCOMUNE,ID);

ALTER TABLE dyn2_metadati_contesti ADD CONSTRAINT uc_dyn2metadaticontesti UNIQUE(idcomune,contesto);

ALTER TABLE dyn2_metadati ADD CONSTRAINT uc_dyn2metadati UNIQUE(idcomune, fk_contesto_id, contesto_campo);