CREATE TABLE AMMINISTRAZIONI_COLLEGATE(
IDCOMUNE VARCHAR(6) NOT NULL
, CODICEAMMINISTRAZIONE NUMERIC(10,0) NOT NULL
, CODICESOTTOAMMINISTRAZIONE NUMERIC(10,0) NOT NULL
, CODICECOMUNE VARCHAR (5) NOT NULL
) 
ENGINE=INNODB DEFAULT CHARSET=utf8;
ALTER TABLE AMMINISTRAZIONI_COLLEGATE ADD CONSTRAINT PK_AMMCOLLEGATE PRIMARY KEY(IDCOMUNE,CODICEAMMINISTRAZIONE,CODICECOMUNE);

ALTER TABLE AMMINISTRAZIONI_COLLEGATE ADD CONSTRAINT FK_AMMCOLLEGATE_AMMI FOREIGN KEY(IDCOMUNE,CODICEAMMINISTRAZIONE) REFERENCES  AMMINISTRAZIONI (IDCOMUNE,CODICEAMMINISTRAZIONE);

ALTER TABLE AMMINISTRAZIONI_COLLEGATE ADD CONSTRAINT FK_AMMCOLLEGATE_SOTTOAMM FOREIGN KEY(IDCOMUNE,CODICESOTTOAMMINISTRAZIONE) REFERENCES  AMMINISTRAZIONI (IDCOMUNE,CODICEAMMINISTRAZIONE);

ALTER TABLE AMMINISTRAZIONI_COLLEGATE ADD CONSTRAINT FK_AMMCOLLEGATE_COMUNI FOREIGN KEY(CODICECOMUNE) REFERENCES  COMUNI (CODICECOMUNE);

CREATE TABLE CONFIGURAZIONE_CALCOLI
(
IDCOMUNE VARCHAR(6) NOT NULL,
ID NUMERIC(10,0) NOT NULL,
DESCRIZIONE VARCHAR(200) NOT NULL,
JSON_MATRICE NUMERIC(10,0) NOT NULL,
JSON_CONFIGURAZIONE NUMERIC(10,0) NOT NULL 
)
ENGINE=INNODB DEFAULT CHARSET=utf8;

ALTER TABLE CONFIGURAZIONE_CALCOLI ADD CONSTRAINT PK_CONFIGCALCOLI PRIMARY KEY(IDCOMUNE,ID);

ALTER TABLE CONFIGURAZIONE_CALCOLI ADD CONSTRAINT FK_OGGETTI_MATRICE FOREIGN KEY(IDCOMUNE,JSON_MATRICE) REFERENCES OGGETTI (IDCOMUNE,CODICEOGGETTO);
ALTER TABLE CONFIGURAZIONE_CALCOLI ADD CONSTRAINT FK_OGGETTI_CONFIGURAZIONE FOREIGN KEY(IDCOMUNE,JSON_CONFIGURAZIONE) REFERENCES OGGETTI (IDCOMUNE,CODICEOGGETTO);

