ALTER TABLE INVENTARIOPROCEDIMENTISOFTWARE MODIFY ID NUMBER(10,0);


CREATE TABLE MOVIMENTIMAIL_BACKV2_20 AS SELECT * FROM MOVIMENTIMAIL;
ALTER TABLE MOVIMENTIMAIL ADD CORPO_CLOB CLOB;
UPDATE MOVIMENTIMAIL SET CORPO_CLOB=CORPO;
ALTER TABLE MOVIMENTIMAIL DROP COLUMN CORPO;
ALTER TABLE MOVIMENTIMAIL ADD CORPO CLOB;
UPDATE MOVIMENTIMAIL SET CORPO=CORPO_CLOB;
ALTER TABLE MOVIMENTIMAIL DROP COLUMN CORPO_CLOB;


CREATE TABLE MAILTIPO_BACK_v_2_20 AS SELECT * FROM MAILTIPO;
ALTER TABLE MAILTIPO ADD CORPO_CLOB CLOB;
UPDATE MAILTIPO SET CORPO_CLOB=CORPO;
ALTER TABLE MAILTIPO DROP COLUMN CORPO;
ALTER TABLE MAILTIPO ADD CORPO CLOB;
UPDATE MAILTIPO SET CORPO=CORPO_CLOB;
ALTER TABLE MAILTIPO DROP COLUMN CORPO_CLOB;

ALTER TABLE ANAGRAFE MODIFY CAP VARCHAR2(15);
ALTER TABLE ANAGRAFE MODIFY CAPLR VARCHAR2(15);
ALTER TABLE ANAGRAFE MODIFY CAPCORRISPONDENZA VARCHAR2(15);

ALTER TABLE ANAGRAFESTORICO MODIFY CAP VARCHAR2(15);
ALTER TABLE ANAGRAFESTORICO MODIFY CAPLR VARCHAR2(15);
ALTER TABLE ANAGRAFESTORICO MODIFY CAPCORRISPONDENZA VARCHAR2(15);


CREATE INDEX IDX_MOVMAIL_MOVIMENTI ON MOVIMENTIMAIL (IDCOMUNE, CODICEMOVIMENTO);

CREATE TABLE ELENCOINAILBASE(
  CODICE VARCHAR2(6) NOT NULL,
  DESCRIZIONE VARCHAR2(50)
);
ALTER TABLE ELENCOINAILBASE ADD CONSTRAINT PK_ELENCOINAILBASE PRIMARY KEY (CODICE);

CREATE TABLE ELENCOINPSBASE(
  CODICE VARCHAR2(6) NOT NULL,
  DESCRIZIONE VARCHAR2(50)
);
ALTER TABLE ELENCOINPSBASE ADD CONSTRAINT PK_ELENCOINPSBASE PRIMARY KEY (CODICE);

ALTER TABLE ANAGRAFE ADD INAIL_MATRICOLA VARCHAR2(16);
ALTER TABLE ANAGRAFE ADD INAIL_CODICESEDE VARCHAR2(6);
ALTER TABLE ANAGRAFE ADD INPS_MATRICOLA VARCHAR2(16);
ALTER TABLE ANAGRAFE ADD INPS_CODICESEDE VARCHAR2(6);

ALTER TABLE ANAGRAFESTORICO ADD INAIL_MATRICOLA VARCHAR2(16);
ALTER TABLE ANAGRAFESTORICO ADD INAIL_CODICESEDE VARCHAR2(6);
ALTER TABLE ANAGRAFESTORICO ADD INPS_MATRICOLA VARCHAR2(16);
ALTER TABLE ANAGRAFESTORICO ADD INPS_CODICESEDE VARCHAR2(6);

ALTER TABLE ANAGRAFE ADD CONSTRAINT FK_ANAG_ELENCOINAIL FOREIGN KEY (INAIL_CODICESEDE) REFERENCES ELENCOINAILBASE(CODICE);
ALTER TABLE ANAGRAFE ADD CONSTRAINT FK_ANAG_ELENCOINPS FOREIGN KEY (INPS_CODICESEDE) REFERENCES ELENCOINPSBASE(CODICE);
ALTER TABLE ANAGRAFESTORICO ADD CONSTRAINT FK_ANAGSTO_ELENCOINAIL FOREIGN KEY (INAIL_CODICESEDE) REFERENCES ELENCOINAILBASE(CODICE);
ALTER TABLE ANAGRAFESTORICO ADD CONSTRAINT FK_ANAGSTO_ELENCOINPS FOREIGN KEY (INPS_CODICESEDE) REFERENCES ELENCOINPSBASE(CODICE);

COMMENT ON COLUMN ANAGRAFE.INAIL_MATRICOLA IS 'Codice ditta INAIL';
COMMENT ON COLUMN ANAGRAFE.INAIL_CODICESEDE IS 'Contiene il codice della sede provinciale, come da codifica ufficiale disponibile sul portale dell''istituto. chiave esterna verso ELENCOINAILBASE';

COMMENT ON COLUMN ANAGRAFE.INPS_MATRICOLA IS 'Codice ditta INPS';
COMMENT ON COLUMN ANAGRAFE.INPS_CODICESEDE IS 'Contiene il codice della SAP di iscrizione corrispondente al numero di matricola indicato. FK verso ELENCOINPSBASE';


CREATE TABLE ANAGRAFEDOCUMENTI_DURC(
IDCOMUNE VARCHAR2(6) NOT NULL,
ID NUMBER(10,0) NOT NULL,
FK_ANAGRAFEDOC_ID  NUMBER(10,0) NOT NULL,
REQUESTID VARCHAR2(50),
RESULTCODE VARCHAR2(5),
RESULTDESCRIPTION VARCHAR2(300),
CIP VARCHAR2(20),
PROTOCOL VARCHAR2(10),
ISSUEDATE DATE,
EXPIRATIONDATE DATE,
CODICEOGGETTO NUMBER(10,0)
);

COMMENT ON COLUMN ANAGRAFEDOCUMENTI_DURC.IDCOMUNE IS 'Chiave primaria';
COMMENT ON COLUMN ANAGRAFEDOCUMENTI_DURC.ID IS 'Chiave primaria';
COMMENT ON COLUMN ANAGRAFEDOCUMENTI_DURC.FK_ANAGRAFEDOC_ID IS 'FK verso ANAGRAFEDOCUMENTI.ID';
COMMENT ON COLUMN ANAGRAFEDOCUMENTI_DURC.REQUESTID IS 'utilizzato dal sistema per il terzo livello di cooperazione applicativa ( anche se ad oggi la cooperazione verrà estesa ai primi due livelli )';
COMMENT ON COLUMN ANAGRAFEDOCUMENTI_DURC.RESULTCODE IS 'Codice di errore o di warning generato durante l’elaborazione della richiesta. ';
COMMENT ON COLUMN ANAGRAFEDOCUMENTI_DURC.RESULTDESCRIPTION IS 'Descrizione dell’errore o del warning ';
COMMENT ON COLUMN ANAGRAFEDOCUMENTI_DURC.CIP IS 'Codice Identificativo Pratica (CIP) del DURC esistente e valido';
COMMENT ON COLUMN ANAGRAFEDOCUMENTI_DURC.PROTOCOL IS 'Protocollo del DURC esistente e valido';
COMMENT ON COLUMN ANAGRAFEDOCUMENTI_DURC.ISSUEDATE IS 'Data di emissione del DURC esistente e valido.';
COMMENT ON COLUMN ANAGRAFEDOCUMENTI_DURC.EXPIRATIONDATE IS 'Opzionale – Data di scadenza del DURC esistente e valido. NOTA: la validità dei DURC per lavori privati in edilizia è fissata a 90 giorni dalla data di emissione';
COMMENT ON COLUMN ANAGRAFEDOCUMENTI_DURC.CODICEOGGETTO IS 'Il file XML inviato in risposta dal servizio di Infodurc';


ALTER TABLE ANAGRAFEDOCUMENTI_DURC ADD CONSTRAINT PK_ANAGRAFEDOCUMENTIDURC PRIMARY KEY(IDCOMUNE, ID);
ALTER TABLE ANAGRAFEDOCUMENTI_DURC ADD CONSTRAINT FK_ANAGRDOCUDURC_ANAGDOC FOREIGN KEY(IDCOMUNE, FK_ANAGRAFEDOC_ID) REFERENCES ANAGRAFEDOCUMENTI (IDCOMUNE, ID);
ALTER TABLE ANAGRAFEDOCUMENTI_DURC ADD CONSTRAINT FK_ANAGRDOCUDURC_OGGETTI FOREIGN KEY(IDCOMUNE, CODICEOGGETTO) REFERENCES OGGETTI (IDCOMUNE, CODICEOGGETTO);

ALTER TABLE PEC_INBOX ADD (FK_RESP_EVIDENZA NUMBER(4, 0));

ALTER TABLE PEC_INBOX ADD CONSTRAINT PEC_INBOX_RESP_EVIDENZA FOREIGN KEY (IDCOMUNE,FK_RESP_EVIDENZA) REFERENCES RESPONSABILI (IDCOMUNE,CODICERESPONSABILE);


ALTER TABLE INVENTARIOPROC_TIPITITOLO ADD FLG_NON_PUBBLICARE NUMBER(1,0) DEFAULT 0;
alter table INVENTARIOPROC_TIPITITOLO add FLG_ALL_OBBLIGATORIO NUMBER(1,0) DEFAULT 0;

ALTER TABLE PEC_INBOX ADD PEC_TOCC VARCHAR2(4000);

COMMENT ON COLUMN PEC_INBOX.PEC_TOCC IS 'IL CAMPO CONTIENE TUTTI I DESTINATARI IN CC SEPARATI DA '';''';


ALTER TABLE FAQ ADD ORDINE NUMBER(3,0);
ALTER TABLE NORMATIVE ADD ORDINE NUMBER(3,0);
ALTER TABLE NEWS ADD SOMMARIO VARCHAR2(400);

CREATE TABLE ALBEROPROC_FO_TOP(
IDCOMUNE VARCHAR2(6) NOT NULL,
ID NUMBER(6,0) NOT NULL, 
SOFTWARE VARCHAR2 (2) NOT NULL, 
DESCRIZIONE VARCHAR2(256) NOT NULL,
FK_SCID NUMBER(10,0) NOT NULL,
ORDINE NUMBER(3,0) NOT NULL
);

ALTER TABLE ALBEROPROC_FO_TOP ADD CONSTRAINT PK_ALBPROCFOTOP PRIMARY KEY (IDCOMUNE,ID);
ALTER TABLE ALBEROPROC_FO_TOP ADD CONSTRAINT FK_ALBPROCFOTOP_ALBEROPROC FOREIGN KEY (IDCOMUNE,FK_SCID) REFERENCES ALBEROPROC(IDCOMUNE, SC_ID);
ALTER TABLE ALBEROPROC_FO_TOP ADD CONSTRAINT FK_ALBPROCFOTOP_SOFTWARE FOREIGN KEY (SOFTWARE) REFERENCES SOFTWARE(CODICE);

CREATE TABLE INVENTARIOPROC_FO_TOP(
IDCOMUNE VARCHAR2(6) NOT NULL,
ID NUMBER(6,0) NOT NULL,
SOFTWARE VARCHAR2 (2) NOT NULL,
DESCRIZIONE VARCHAR2(256) NOT NULL,
FK_CODICEINVENTARIO NUMBER(10,0) NOT NULL,
ORDINE NUMBER(3,0) NOT NULL );

ALTER TABLE INVENTARIOPROC_FO_TOP ADD CONSTRAINT PK_INVENTARIOPROCFOTOP PRIMARY KEY (IDCOMUNE,ID);
ALTER TABLE INVENTARIOPROC_FO_TOP ADD CONSTRAINT FK_INVPROCFOTOP_INVPROC FOREIGN KEY (IDCOMUNE, FK_CODICEINVENTARIO) REFERENCES INVENTARIOPROCEDIMENTI(IDCOMUNE, CODICEINVENTARIO);
ALTER TABLE INVENTARIOPROC_FO_TOP ADD CONSTRAINT FK_INVPROCFOTOP_SOFTWARE FOREIGN KEY (SOFTWARE) REFERENCES SOFTWARE(CODICE);

ALTER TABLE NORMEGENERALI MODIFY ORDINE NUMBER(3);

ALTER TABLE RESPONSABILI MODIFY CODICERESPONSABILE NUMBER(8,0);
ALTER TABLE CONFIGURAZIONEUTENTE MODIFY CODICERESPONSABILE NUMBER(8,0);
ALTER TABLE RESPONSABILIRUOLI MODIFY CODICERESPONSABILE NUMBER(8,0);
ALTER TABLE PROTOCOLLO_RESPONSABILIFLUSSI MODIFY CODICERESPONSABILE NUMBER(8,0);
ALTER TABLE REGISTRAZIONI MODIFY CODICEOPERATORE NUMBER(8,0);
ALTER TABLE REGISTRAZIONI MODIFY CODICEUTENTESISTEMA NUMBER(8,0);
ALTER TABLE ALBO_PUBBLICAZIONI MODIFY CODICERESPONSABILE NUMBER(8,0);
ALTER TABLE CONFIGURAZIONE MODIFY CODICERESPONSABILE NUMBER(8,0);
ALTER TABLE PERMISTANZE MODIFY CODICERESPONSABILE NUMBER(8,0);
ALTER TABLE ALBEROPROC MODIFY CODICERESPISTRUTTORIA NUMBER(8,0);
ALTER TABLE AMMINISTRAZIONIRESPONSABILI MODIFY CODICERESPONSABILE NUMBER(8,0);
ALTER TABLE ALBEROPROC MODIFY CODICERESPONSABILE NUMBER(8,0);
ALTER TABLE MOVIMENTI MODIFY CODICERESPONSABILE NUMBER(8,0);
ALTER TABLE CLPERMMENU MODIFY CODICERESPONSABILE NUMBER(8,0);
ALTER TABLE RESPONSABILICOMUNI MODIFY CODICERESPONSABILE NUMBER(8,0);
ALTER TABLE ISTANZE MODIFY CODICEISTRUTTORE NUMBER(8,0);
ALTER TABLE ISTANZE MODIFY CODICERESPONSABILEPROC NUMBER(8,0);
ALTER TABLE ISTANZE MODIFY CODICERESPONSABILE NUMBER(8,0);
ALTER TABLE ISTANZEONERI MODIFY CODICEUTENTE NUMBER(8,0);
ALTER TABLE RESPONSABILISOFTWARE MODIFY CODICERESPONSABILE NUMBER(8,0);
ALTER TABLE RESPONSABILI MODIFY SCAD_OPERATORE NUMBER(8,0);
ALTER TABLE ALBEROPROC MODIFY CODICEOPERATORE_STC NUMBER(8,0);
ALTER TABLE LINK_PREFERITI_UTENTE MODIFY CODICERESPONSABILE NUMBER(8,0);
ALTER TABLE DOCUMENTI_CONTABILITA MODIFY CODICERESPONSABILE NUMBER(8,0);
ALTER TABLE PEC_INBOX MODIFY CODICEOPERATORE NUMBER(8,0);
ALTER TABLE DOCUMENTI_DA_FIRMARE MODIFY CODICERICHIEDENTE NUMBER(8,0);
ALTER TABLE DOCUMENTI_DA_FIRMARE MODIFY CODICEFIRMATARIO NUMBER(8,0);
ALTER TABLE PEC_INBOX MODIFY FK_RESP_EVIDENZA NUMBER(8,0);

alter table anagrafedocumenti modify codiceanagrafe number(6,0) null;
alter table anagrafedocumenti modify idtipodocumento number(4,0) null;

CREATE INDEX IDX_OGGETTI_METADATI_001 ON OGGETTI_METADATI(IDCOMUNE, CHIAVE, VALORE);

create table ARCHIVIAZIONI (
IDCOMUNE varchar2(6) not null,
ID number(10,0) not null,
ID_JOB varchar2(100) not null,
DATA date
);
alter table ARCHIVIAZIONI add constraint PK_ARCHIVIAZIONI primary key(IDCOMUNE, ID);
create table ARCHIVIAZIONI_ISTANZE (
IDCOMUNE varchar2(6) not null,
ID number(10,0) not null,
CODICEISTANZA number(6,0) not null,
FK_ARCHIVIAZIONI_ID number(10,0) not null,
PARZIALE number(1,0) default 0
);
alter table ARCHIVIAZIONI_ISTANZE add constraint PK_ARCHIVIAZIONI_ISTANZE primary key(IDCOMUNE, ID);
alter table ARCHIVIAZIONI_ISTANZE add constraint FK_ARCH_ISTANZE_ARCH foreign key(IDCOMUNE, FK_ARCHIVIAZIONI_ID) references ARCHIVIAZIONI (IDCOMUNE, ID);
alter table ARCHIVIAZIONI_ISTANZE add constraint FK_ARCH_ISTANZE_ISTANZE foreign key(IDCOMUNE, CODICEISTANZA) references ISTANZE (IDCOMUNE, CODICEISTANZA);

create table ARCHIVIAZIONI_OGGETTI (
IDCOMUNE varchar2(6) not null,
ID number(10,0) not null,
FK_ARCHIVIAZIONI_ISTANZE_ID number(10,0) not null,
FK_ARCHIVIAZIONI_ID number(10,0) not null,
CODICEOGGETTO number(10,0) not null
);
alter table ARCHIVIAZIONI_OGGETTI add constraint PK_ARCHIVIAZIONI_OGGETTI primary key(IDCOMUNE, ID);
alter table ARCHIVIAZIONI_OGGETTI add constraint FK_ARCH_OGGETTI_ARCH_ISTANZE foreign key(IDCOMUNE, FK_ARCHIVIAZIONI_ISTANZE_ID) references ARCHIVIAZIONI_ISTANZE (IDCOMUNE, ID);
alter table ARCHIVIAZIONI_OGGETTI add constraint FK_ARCH_OGGETTI_ARCH_ID foreign key(IDCOMUNE, FK_ARCHIVIAZIONI_ID) references ARCHIVIAZIONI (IDCOMUNE, ID);
alter table ARCHIVIAZIONI_OGGETTI add constraint FK_ARCH_OGGETTI_OGGETTI foreign key(IDCOMUNE, CODICEOGGETTO) references OGGETTI (IDCOMUNE, CODICEOGGETTO);

ALTER TABLE INVENTARIOPROCDYN2MODELLIT ADD FK_TIPILOCALIZZAZIONE_ID NUMBER(10,0);
ALTER TABLE INVENTARIOPROCDYN2MODELLIT ADD CONSTRAINT FK_TIPI_LOCALIZZAZIONE FOREIGN KEY (IDCOMUNE,FK_TIPILOCALIZZAZIONE_ID) REFERENCES TIPI_LOCALIZZAZIONI (IDCOMUNE,ID);
create INDEX IDX_IATTIVITA_002 ON I_ATTIVITA(IDCOMUNE, DENOMINAZIONE);

CREATE TABLE JOB_REPOSITORY(
ID NUMBER(6,0) NOT NULL,
IDCOMUNEALIAS VARCHAR2(20 CHAR),
JOB_NAME VARCHAR2(255 CHAR),
DESCRIPTION VARCHAR2(255 CHAR),
ACTIVE NUMBER(1,0),
TRIGGER_TYPE VARCHAR2(255 CHAR),
START_DELAY NUMBER(10,0),
REPEAT_INTERVAL NUMBER(10,0),
CRON_EXPRESSION VARCHAR2(255 CHAR),
JOB_CLASS_NAME VARCHAR2(255 CHAR)
);

ALTER TABLE JOB_REPOSITORY ADD CONSTRAINT PK_JOBREPOSITORY PRIMARY KEY (ID);
CREATE INDEX IDX_MOVIMENTIMAIL_MSGID ON MOVIMENTIMAIL (IDCOMUNE, MESSAGE_ID);
CREATE INDEX IDX_MOVIMENTIMAIL_IDPADRE ON MOVIMENTIMAIL (IDCOMUNE, ID_PADRE);
