ALTER TABLE responsabili ADD flag_dis_modanagrafe number(1,0) DEFAULT '0';
ALTER TABLE responsabili ADD CIRCOSCRIZIONE VARCHAR2(50) ;

 ALTER TABLE anagrafe ADD DATA_INIZIO_ATTIVITA date ;
ALTER TABLE anagrafestorico ADD DATA_INIZIO_ATTIVITA date ;

ALTER TABLE configurazione ADD RESPONSABILE_TRATTAMENTO VARCHAR2(4000) ;
ALTER TABLE configurazione ADD DATA_PROTECTION_OFFICER VARCHAR2(4000) ;
ALTER TABLE configurazione ADD PROGRESSIVO_REGISTRI_AUT VARCHAR2(35) ;

ALTER TABLE responsabili ADD flag_dis_modanagrafe number(1,0) DEFAULT '0';
ALTER TABLE responsabili ADD CIRCOSCRIZIONE VARCHAR2(50) ;

ALTER TABLE configurazione ADD RESPONSABILE_TRATTAMENTO VARCHAR2(4000) ;
ALTER TABLE configurazione ADD DATA_PROTECTION_OFFICER VARCHAR2(4000) ;
ALTER TABLE configurazione ADD PROGRESSIVO_REGISTRI_AUT VARCHAR2(35) ;

CREATE TABLE logsuap (
  ID number(9,0) NOT NULL,
  DATA VARCHAR2(8) ,
  ORA VARCHAR2(5) ,
  IP VARCHAR2(15) ,
  OPERATORE VARCHAR2(80) ,
  CODICERICHIESTA VARCHAR2(20) ,
  CODICEERRORE VARCHAR2(20) ,
  IDCOMUNE VARCHAR2(6) NOT NULL,
  MESSAGGIO VARCHAR2(4000) ,
  PRIMARY KEY (IDCOMUNE,ID),
  KEY IDX_LOGSUAP_001 (IDCOMUNE,CODICERICHIESTA),
  KEY IDX_LOGSUAP_002 (IDCOMUNE,DATA),
  KEY IDX_LOGSUAP_003 (IDCOMUNE,IP),
  KEY IDX_LOGSUAP_004 (IDCOMUNE,OPERATORE),
  KEY IDX_LOGSUAP_005 (IDCOMUNE,CODICEERRORE)
);

ALTER TABLE SDEPROXY ADD WS_SERVIZI_CONSOLE VARCHAR2(255);


