<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
		<RootNamespace>Init.SIGePro.Protocollo.Test</RootNamespace>
		<AssemblyName>SIGePro.Protocollo.Test</AssemblyName>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<OutputType>Exe</OutputType>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\SIGePro.Manager.Authentication\SIGePro.Manager.Authentication.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="xunit.v3" Version="3.2.2" />
	</ItemGroup>

</Project>