CREATE TABLE RUBRICA(
 IDCOMUNE VARCHAR(6) NOT NULL,
 ID DECIMAL(10) NOT NULL,
 DESCRIZIONE VARCHAR(200),
 MAIL VARCHAR(100),
 CHIAVE VARCHAR(100)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

ALTER TABLE RUBRICA  ADD CONSTRAINT RUBRICA_PK PRIMARY KEY (IDCOMUNE,ID);

create index IDX_RUBRICA_001 ON RUBRICA(IDCOMUNE, DESCRIZIONE);