ALTER TABLE TIPICAUSALIONERIDETTAGLIO ADD FLAG_ATTIVO NUMBER(1,0) DEFAULT 0 NOT NULL;
ALTER TABLE pay_profili_enti_creditori ADD CF_ENTE_QRCODE_PAGOPA VARCHAR2(20 CHAR); 
COMMENT on column pay_profili_enti_creditori.CF_ENTE_QRCODE_PAGOPA is 'Il codice fiscale/partitaiva dell''ente che serve per generare la sezione Identificativo Ente/codice fiscale dell''Ente Creditore dell''algoritmo di generazione qrcode';
update pay_profili_enti_creditori set CF_ENTE_QRCODE_PAGOPA=CF_CODICE_PROFILO_PSP where CF_ENTE_QRCODE_PAGOPA is null;
CREATE INDEX IDX_BOLLGESTISTANZEONERI_001 ON boll_gest_istanzeoneri(IDCOMUNE,fk_bollgestdet_id);
ALTER TABLE PAY_POSIZIONI_DEBITORIE ADD FK_RICEVUTA_XML NUMBER(10,0);
ALTER TABLE PAY_POSIZIONI_DEBITORIE ADD CONSTRAINT PAY_POSDEB_FK_RICEVUTAXML FOREIGN KEY(IDCOMUNE,FK_RICEVUTA_XML) REFERENCES PAY_DOCUMENTI(IDCOMUNE,ID);
alter table DETT_POSIZIONE_DEBITORIA add CF_ENTE_CREDITORE varchar2(20 char);
alter table MERCATI add  CODICECOMUNE varchar2(5 CHAR);
alter table MERCATI add constraint FK_MERCATI_COMUNI foreign key(CODICECOMUNE) references COMUNI(CODICECOMUNE);

update VERTICALIZZAZIONIBASE  set FLAG_GESTCOMUNE = 1 where MODULO = 'NODO_PAGAMENTI';
ALTER TABLE PAY_POSIZIONI_DEBITORIE MODIFY RIFERIMENTO_CLIENT VARCHAR2(50 CHAR);
CREATE TABLE DETT_POSIZIONE_DA_ALLINEARE( IDCOMUNE VARCHAR2(6 CHAR) NOT NULL ,FK_DETTPOSIZIONEDEBITORIAID NUMBER(10,0) NOT NULL );

ALTER TABLE DETT_POSIZIONE_DA_ALLINEARE ADD CONSTRAINT PK_DETT_POSIZIONE_DA_ALLINEARE PRIMARY KEY(IDCOMUNE,FK_DETTPOSIZIONEDEBITORIAID);
ALTER TABLE DETT_POSIZIONE_DA_ALLINEARE ADD CONSTRAINT FK_DETTPOSDAALLI_DETTPOSDEB FOREIGN KEY(IDCOMUNE,FK_DETTPOSIZIONEDEBITORIAID) REFERENCES DETT_POSIZIONE_DEBITORIA(IDCOMUNE,ID);

ALTER TABLE ALBEROPROCPEOPLEOPER MODIFY SETTORE VARCHAR2(50 CHAR);
ALTER TABLE ALBEROPROCPEOPLEOPER MODIFY OPERAZIONE VARCHAR2(50 CHAR);
