ALTER TABLE STATIISTANZA ADD COLORE VARCHAR2(10);

COMMENT ON COLUMN STATIISTANZA.COLORE IS 'Questa impostazione serve per impostare in visualizzazione di una pratica in quello stato con la colorazione indicata';

ALTER TABLE STATIISTANZA ADD FLAG_WARNING  NUMBER(1,0);

COMMENT ON COLUMN STATIISTANZA.FLAG_WARNING IS 'serve per far comparire nella maschera di ricerca istanze una sezione specifica (domande da verificare) che mette in evidenza le istanze che si trovano in quello / quegli stati configurati';


ALTER TABLE STATIISTANZA ADD TESTO_WARNING  VARCHAR2(500);

COMMENT ON COLUMN STATIISTANZA.TESTO_WARNING IS 'Quando la pratica passa in questo stato viene inserito un evento con questo testo';

CREATE TABLE GRUPPI_ENDOPROCEDIMENTI_T(
IDCOMUNE VARCHAR2(6) NOT NULL
,ID NUMBER(4,0) NOT NULL
,SOFTWARE VARCHAR2(2) NOT NULL
,DESCRIZIONE VARCHAR2(100)
,NUM_ENDO_WARNING NUMBER(2,0)
,TIPOMOVIMENTO VARCHAR2(8)
);

ALTER TABLE GRUPPI_ENDOPROCEDIMENTI_T ADD CONSTRAINT PK_GRUPPIENDOPROCEDIMENTIT PRIMARY KEY (IDCOMUNE,ID); 
ALTER TABLE GRUPPI_ENDOPROCEDIMENTI_T ADD CONSTRAINT FK_GRUPPIENDO_TIPIMOV FOREIGN KEY (IDCOMUNE,TIPOMOVIMENTO) REFERENCES TIPIMOVIMENTO(IDCOMUNE,TIPOMOVIMENTO);
CREATE INDEX GRUPPI_ENDOPROCEDIMENTI_T_001 ON GRUPPI_ENDOPROCEDIMENTI_T(IDCOMUNE,TIPOMOVIMENTO);
ALTER TABLE GRUPPI_ENDOPROCEDIMENTI_T ADD CONSTRAINT FK_GRUPPIENDO_SOFTWARE FOREIGN KEY (SOFTWARE) REFERENCES SOFTWARE(CODICE);

CREATE TABLE GRUPPI_ENDOPROCEDIMENTI_D(
IDCOMUNE VARCHAR2(6) NOT NULL
,ID NUMBER(10,0) NOT NULL
,FK_GET_ID NUMBER(4,0) NOT NULL
,CODICEINVENTARIO NUMBER(10,0) NOT NULL
);

ALTER TABLE GRUPPI_ENDOPROCEDIMENTI_D ADD CONSTRAINT PK_GRUPPIENDOPROCEDIMENTID PRIMARY KEY (IDCOMUNE,ID); 
ALTER TABLE GRUPPI_ENDOPROCEDIMENTI_D ADD CONSTRAINT FK_GRUPPIENDOD_GRUPPIT FOREIGN KEY (IDCOMUNE,FK_GET_ID) REFERENCES GRUPPI_ENDOPROCEDIMENTI_T(IDCOMUNE,ID);
ALTER TABLE GRUPPI_ENDOPROCEDIMENTI_D ADD CONSTRAINT FK_GRUPPIENDOD_INVPROC FOREIGN KEY (IDCOMUNE,CODICEINVENTARIO) REFERENCES INVENTARIOPROCEDIMENTI(IDCOMUNE,CODICEINVENTARIO);
CREATE INDEX GRUPPI_ENDOPROCEDIMENTI_D_001 ON GRUPPI_ENDOPROCEDIMENTI_D(IDCOMUNE,CODICEINVENTARIO);

ALTER TABLE ALBEROPROC ADD CODICEAMMINISTRAZIONE NUMBER(10,0);
ALTER TABLE ALBEROPROC ADD CONSTRAINT FK_ALBEROPROC_AMM FOREIGN KEY(IDCOMUNE,CODICEAMMINISTRAZIONE) REFERENCES AMMINISTRAZIONI (IDCOMUNE,CODICEAMMINISTRAZIONE); 
CREATE INDEX IDX_ALBEROPROC_AMMINISTR_001 ON  ALBEROPROC(IDCOMUNE,CODICEAMMINISTRAZIONE);
ALTER TABLE ISTANZE ADD CODICEAMMINISTRAZIONE NUMBER(10,0); 
ALTER TABLE ISTANZE ADD CONSTRAINT FK_ISTANZE_AMM FOREIGN KEY(IDCOMUNE,CODICEAMMINISTRAZIONE) REFERENCES AMMINISTRAZIONI (IDCOMUNE,CODICEAMMINISTRAZIONE); 
CREATE INDEX IDX_ISTANZE_AMMINISTR_001 ON  ISTANZE(IDCOMUNE,CODICEAMMINISTRAZIONE);

ALTER TABLE PROTOCOLLO_CLASSIFICHE ADD (ORDINAMENTO NUMBER(10) );

CREATE TABLE ALBEROPROC_GRUPPI_SMIST(
IDCOMUNE VARCHAR2(6) NOT NULL
,ID NUMBER(10,0) NOT NULL
,SOFTWARE VARCHAR2(2)
,FK_SCID NUMBER(10,0)
,FK_GET_ID_PRIMO NUMBER(4,0)
,FK_GET_ID_SECONDO NUMBER(4,0)
,FK_GET_ID_TERZO NUMBER(4,0)
,FK_TIPIPROCEDURE_SCIA NUMBER(10,0)
,FK_TIPIPROCEDURE_ORDINARIO NUMBER(10,0)
);

ALTER TABLE ALBEROPROC_GRUPPI_SMIST ADD CONSTRAINT PK_ALBEROPROCGRUPPISMIST PRIMARY KEY (IDCOMUNE, ID);
ALTER TABLE ALBEROPROC_GRUPPI_SMIST ADD CONSTRAINT FK_ALBPROCGRUPSMIST_SOFT FOREIGN KEY (SOFTWARE) REFERENCES SOFTWARE(CODICE);
CREATE INDEX IDX_ALBPROCGRUPSMIST_001 ON ALBEROPROC_GRUPPI_SMIST(SOFTWARE);

ALTER TABLE ALBEROPROC_GRUPPI_SMIST ADD CONSTRAINT FK_ALBPROCGRUPSMIST_GET_01 FOREIGN KEY (IDCOMUNE, FK_GET_ID_PRIMO) REFERENCES GRUPPI_ENDOPROCEDIMENTI_T(IDCOMUNE,ID);
CREATE INDEX IDX_ALBPROCGRPSMI_GET_001 ON ALBEROPROC_GRUPPI_SMIST(IDCOMUNE, FK_GET_ID_PRIMO);

ALTER TABLE ALBEROPROC_GRUPPI_SMIST ADD CONSTRAINT FK_ALBPROCGRUPSMIST_GET_02 FOREIGN KEY (IDCOMUNE, FK_GET_ID_SECONDO) REFERENCES GRUPPI_ENDOPROCEDIMENTI_T(IDCOMUNE,ID);
CREATE INDEX IDX_ALBPROCGRPSMI_GET_002 ON ALBEROPROC_GRUPPI_SMIST(IDCOMUNE, FK_GET_ID_SECONDO);

ALTER TABLE ALBEROPROC_GRUPPI_SMIST ADD CONSTRAINT FK_ALBPROCGRUPSMIST_GET_03 FOREIGN KEY (IDCOMUNE, FK_GET_ID_TERZO) REFERENCES GRUPPI_ENDOPROCEDIMENTI_T(IDCOMUNE,ID);
CREATE INDEX IDX_ALBPROCGRPSMI_GET_003 ON ALBEROPROC_GRUPPI_SMIST(IDCOMUNE, FK_GET_ID_TERZO);

ALTER TABLE ALBEROPROC_GRUPPI_SMIST ADD CONSTRAINT FK_ALBPROCGRPSM_TIPIPROC_01 FOREIGN KEY (IDCOMUNE, FK_TIPIPROCEDURE_SCIA) REFERENCES TIPIPROCEDURE(IDCOMUNE,CODICEPROCEDURA);
CREATE INDEX IDX_ALBPROCGRPSM_TIPIPROC_01 ON ALBEROPROC_GRUPPI_SMIST(IDCOMUNE, FK_TIPIPROCEDURE_SCIA);

ALTER TABLE ALBEROPROC_GRUPPI_SMIST ADD CONSTRAINT FK_ALBPROCGRPSM_TIPIPROC_02 FOREIGN KEY (IDCOMUNE, FK_TIPIPROCEDURE_ORDINARIO) REFERENCES TIPIPROCEDURE(IDCOMUNE,CODICEPROCEDURA);
CREATE INDEX IDX_ALBPROCGRPSM_TIPIPROC_02 ON ALBEROPROC_GRUPPI_SMIST(IDCOMUNE, FK_TIPIPROCEDURE_ORDINARIO);

