create index IDX_FODOMANDE_OGG_001 ON FO_DOMANDE(IDCOMUNE, CODICEOGGETTO);
create index IDX_FODOMANDE_OGG_002 ON FO_DOMANDE(IDCOMUNE, CODICEOGGETTO_CART);
create index IDX_FODOMANDEOGG_OGG_001 ON FO_DOMANDE_OGGETTI(IDCOMUNE, CODICEOGGETTO);

ALTER TABLE COMUNIASSOCIATISOFTWARE  MODIFY SI_INTESTAZIONE1 VARCHAR(500);
ALTER TABLE COMUNIASSOCIATISOFTWARE  MODIFY SI_INTESTAZIONE2 VARCHAR(500);
ALTER TABLE COMUNIASSOCIATISOFTWARE  MODIFY SI_INTESTAZIONE3 VARCHAR(500);
ALTER TABLE COMUNIASSOCIATISOFTWARE  MODIFY SI_PDP1 VARCHAR(500);
ALTER TABLE COMUNIASSOCIATISOFTWARE  MODIFY SI_PDP2 VARCHAR(500);
ALTER TABLE COMUNIASSOCIATI  MODIFY SI_INTESTAZIONE1 VARCHAR(500);
ALTER TABLE COMUNIASSOCIATI  MODIFY SI_INTESTAZIONE2 VARCHAR(500);
ALTER TABLE COMUNIASSOCIATI  MODIFY SI_INTESTAZIONE3 VARCHAR(500);
ALTER TABLE COMUNIASSOCIATI  MODIFY SI_PDP1 VARCHAR(500);
ALTER TABLE COMUNIASSOCIATI  MODIFY SI_PDP2 VARCHAR(500);


ALTER TABLE ALBEROPROC_DOCUMENTI ADD FO_DIMENSIONE_MASSIMA NUMERIC(10,0);
ALTER TABLE ALBEROPROC_DOCUMENTI ADD FO_ESTENSIONI_AMMESSE  VARCHAR(256);

ALTER TABLE ALLEGATI ADD FO_DIMENSIONE_MASSIMA NUMERIC(10,0);
ALTER TABLE ALLEGATI ADD FO_ESTENSIONI_AMMESSE VARCHAR(256);

ALTER TABLE FO_ARCONFIGURAZIONE ADD DIMENSIONE_MASSIMA NUMERIC(10,0);
ALTER TABLE FO_ARCONFIGURAZIONE ADD ESTENSIONI_AMMESSE VARCHAR(256);


CREATE TABLE FO_FORMATI_DOCUMENTI (
    IDCOMUNE VARCHAR(6),
    ID NUMERIC(10,0),
    SOFTWARE VARCHAR(2),
    FORMATO VARCHAR(50) NOT NULL,
    DIMENSIONE_MAX_PAGINA NUMERIC(6,0) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE FO_FORMATI_DOCUMENTI ADD CONSTRAINT PK_FO_FORMATI_DOCUMENTI PRIMARY KEY (IDCOMUNE, ID);
ALTER TABLE FO_FORMATI_DOCUMENTI ADD CONSTRAINT FK_FO_FORM_DOC_SW FOREIGN KEY (SOFTWARE) REFERENCES SOFTWARE(CODICE);

ALTER TABLE inventarioprocdyn2modellit ADD FLAG_FVG_MOSTRA_NEL_BACK NUMERIC(1,0);

alter table layouttestibase modify testo varchar(1000);
alter table layouttesti modify nuovotesto varchar(1000);
