<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>netstandard2.0</TargetFramework>
	  <RootNamespace>Init.SIGePro.Manager.Authentication</RootNamespace>
	  <Configurations>Debug;Release</Configurations>
	  <Platforms>AnyCPU</Platforms>
	  <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SIGePro.Manager.VerticalizzazioniBase\SIGePro.Manager.VerticalizzazioniBase.csproj" />
  </ItemGroup>

</Project>
