debug=false

spring.config.validate-on-startup=true

spring.mvc.log-request-details=true

spring.application.name=security

server.port=${SECURITY_SERVER_PORT}
server.servlet.context-path=/ibcsecurity

spring.mvc.servlet.path=/


spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size: 10MB

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=${SECURITY_HIBERNATE_DIALECT}

spring.datasource.url=REDACTED
spring.datasource.username=REDACTED
spring.datasource.password=REDACTED
spring.datasource.driver-class-name=${SECURITY_JDBC_DRIVER}
spring.jpa.show-sql=false

spring.webservices.servlet.load-on-startup=5

security.delete-token-enabled=${SECURITY_DELETE_TOKEN_ENABLED}
security.delete-token-cron=${SECURITY_DELETE_TOKEN_CRON}
security.delete-token-save-file=${SECURITY_DELETE_TOKEN_SAVE_FILE}
security.logs-file-dir=${SECURITY_DELETE_TOKEN_LOGS_DIR}

management.endpoint.health.show-details=always
#management.endpoints.web.base-path=/ibcsecurity/actuator

management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
management.health.rabbit.enabled=false
