#JDBC DRIVERS
oracle=oracle.jdbc.OracleDriver
mysql=com.mysql.cj.jdbc.Driver
postgresql=org.postgresql.Driver
sqlserver=net.sourceforge.jtds.jdbc.Driver
#sqlserver=com.microsoft.jdbc.sqlserver.SQLServerDriver
#per i driver jdbc-2.0: sqljdbc4.jar(per JRE6) o sqljdbc.jar(per JRE5)
#sqlserver=com.microsoft.sqlserver.jdbc.SQLServerDriver			
