CREATE TABLE ALBEROPROC_METADATI(IDCOMUNE VARCHAR2(6 CHAR),FK_SCID NUMBER(10,0),CHIAVE VARCHAR2(100 CHAR),VALORE VARCHAR2(4000 CHAR));
ALTER TABLE ALBEROPROC_METADATI ADD PRIMARY KEY(IDCOMUNE,FK_SCID,CHIAVE);

ALTER TABLE ALBEROPROC_METADATI ADD CONSTRAINT ALBEROPROC_METADATI_FK1 FOREIGN KEY (IDCOMUNE,FK_SCID) REFERENCES ALBEROPROC(IDCOMUNE,SC_ID) ENABLE;

ALTER TABLE ISTANZEONERI ADD FK_POSDEBDETTAGLIO_ID NUMBER(10,0); 
ALTER TABLE ISTANZEONERI ADD CONSTRAINT FK_ISTONERI_DETTPOSDEB FOREIGN KEY(IDCOMUNE,FK_POSDEBDETTAGLIO_ID) REFERENCES DETT_POSIZIONE_DEBITORIA(IDCOMUNE,ID);
CREATE INDEX IDX_ISTONERI_DETTPOSDEB  ON ISTANZEONERI (IDCOMUNE,FK_POSDEBDETTAGLIO_ID); 
COMMENT ON COLUMN ISTANZEONERI.FK_POSDEBDETTAGLIO_ID IS 'Chiave esterna verso la tabella DETT_POSIZIONE_DEBITORIA che contiene le informazioni delle posizioni debitorie inserite in un sistema di pagamento';

alter table BOLL_CFG_TIPO add FLAG_IGNORA_SUBENTRI number(1,0);
comment on column BOLL_CFG_TIPO.FLAG_IGNORA_SUBENTRI is 'SE SPUNTATO L''INTERA BOLLETTAZIONE VERRA''  ADDEBITATA AL PRIMO CONCESSIONARIO DEL PERIODO, ALTRIMENTI VERRANNO RIPARTITE TRA GLI ALTRI CONCESSIONARI DERIVANTI DA SUBENTRI/VENDITE';


alter table mercati_d add data_creazione date;
update mercati_d set data_creazione=to_date('1900-01-01','yyyy-MM-dd') where  data_creazione IS NULL;

alter table mercati_uso add data_creazione date;
update mercati_uso set  data_creazione=to_date('1900-01-01','yyyy-MM-dd') where  data_creazione IS NULL;


ALTER TABLE BOLL_CFG_TIPO ADD FLAG_RICHIESTA_FATTURA NUMBER(1,0);
COMMENT ON COLUMN BOLL_CFG_TIPO.FLAG_RICHIESTA_FATTURA IS 'Se spuntato allora all''invio al nodo dei pagamenti sarà invocato il metodo di richiesta fattura';
UPDATE BOLL_CFG_TIPO SET FLAG_RICHIESTA_FATTURA=0 WHERE FLAG_RICHIESTA_FATTURA IS NULL;


ALTER TABLE PAY_CONNECTOR_CONFIG ADD FK_WS_FATTURA NUMBER(9,0) NULL;
ALTER TABLE PAY_CONNECTOR_CONFIG ADD FK_WS_RICEVUTA NUMBER(9,0) NULL;
ALTER TABLE PAY_CONNECTOR_CONFIG ADD FK_WS_IUV NUMBER(9,0) NULL;
ALTER TABLE PAY_CONNECTOR_CONFIG ADD CONSTRAINT PAYCONN_FK_RICEVUTA FOREIGN KEY (CODICE, FK_WS_RICEVUTA) REFERENCES PAY_CONNECTOR_WS_ENDPOINT(CODICE_CONNETTORE, ID);
ALTER TABLE PAY_CONNECTOR_CONFIG ADD CONSTRAINT PAYCONN_FK_FATTURA FOREIGN KEY (CODICE, FK_WS_FATTURA) REFERENCES PAY_CONNECTOR_WS_ENDPOINT(CODICE_CONNETTORE, ID);
ALTER TABLE PAY_CONNECTOR_CONFIG ADD CONSTRAINT PAYCONN_FK_IUV FOREIGN KEY (CODICE, FK_WS_IUV) REFERENCES PAY_CONNECTOR_WS_ENDPOINT(CODICE_CONNETTORE, ID);


ALTER TABLE PAY_POSIZIONI_DEBITORIE DROP CONSTRAINT PAY_POSDEB_FK_OGGAVV;
ALTER TABLE PAY_POSIZIONI_DEBITORIE DROP CONSTRAINT PAY_POSDEB_FK_OGGFAT;
ALTER TABLE PAY_POSIZIONI_DEBITORIE DROP CONSTRAINT PAY_POSDEB_FK_OGGRT;


ALTER TABLE PAY_POSIZIONI_DEBITORIE MODIFY FK_OGGETTO_RICEVUTA NUMBER(10,0);
ALTER TABLE PAY_POSIZIONI_DEBITORIE MODIFY FK_OGGETTO_AVVISO NUMBER(10,0);
ALTER TABLE PAY_POSIZIONI_DEBITORIE MODIFY FK_OGGETTO_FATTURA NUMBER(10,0);



CREATE TABLE PAY_DOCUMENTI( 
 IDCOMUNE VARCHAR2(6 CHAR) NOT NULL,
 ID NUMBER(10,0) NOT NULL,
 NOME_DOCUMENTO VARCHAR2(256 CHAR) NOT NULL,
 NOME_FILESYSTEM VARCHAR2(256 CHAR),
 PERCORSO VARCHAR2(256 CHAR),
 DATI_FILE BLOB,
 DIMENSIONE NUMBER(9,0),
 PRIMARY KEY (IDCOMUNE, ID)
);

ALTER TABLE PAY_POSIZIONI_DEBITORIE ADD CONSTRAINT PAY_POSDEB_FK_DOCFATT FOREIGN KEY (IDCOMUNE, FK_OGGETTO_FATTURA) REFERENCES PAY_DOCUMENTI(IDCOMUNE, ID);
ALTER TABLE PAY_POSIZIONI_DEBITORIE ADD CONSTRAINT PAY_POSDEB_FK_DOCRICEV FOREIGN KEY (IDCOMUNE, FK_OGGETTO_RICEVUTA) REFERENCES PAY_DOCUMENTI(IDCOMUNE, ID);
ALTER TABLE PAY_POSIZIONI_DEBITORIE ADD CONSTRAINT PAY_POSDEB_FK_DOCAVVISO FOREIGN KEY (IDCOMUNE, FK_OGGETTO_AVVISO) REFERENCES PAY_DOCUMENTI(IDCOMUNE, ID);



create TABLE BOLL_GEST_DETT_AUTORIZZ(
IDCOMUNE VARCHAR2(6 CHAR) NOT NULL,
ID NUMBER(10,0) NOT NULL,
FK_AUTORIZZAZIONE_ID NUMBER(6,0),
FK_BOLLGESTDET_ID NUMBER(10,0)
);

ALTER TABLE BOLL_GEST_DETT_AUTORIZZ ADD CONSTRAINT PK_BOLL_GEST_DETT_AUTORIZZ PRIMARY KEY(IDCOMUNE, ID); 
ALTER TABLE BOLL_GEST_DETT_AUTORIZZ ADD CONSTRAINT FK_BGESTDETTAUT_AUTORIZZAZIONI FOREIGN KEY(IDCOMUNE, FK_AUTORIZZAZIONE_ID) REFERENCES AUTORIZZAZIONI(IDCOMUNE,ID); 
ALTER TABLE BOLL_GEST_DETT_AUTORIZZ ADD CONSTRAINT FK_BGESTDETTAUT_BOLL_GESTD FOREIGN KEY(IDCOMUNE, FK_BOLLGESTDET_ID) REFERENCES BOLL_GEST_DETTAGLIO(IDCOMUNE,ID);


CREATE TABLE BOLL_GEST_MERCATI_DETT(
IDCOMUNE VARCHAR2(6 CHAR) NOT NULL,
ID NUMBER(10,0) NOT NULL,
FK_ID_GEST_AUTORIZZAZIONI NUMBER(10,0) NOT NULL, 
FK_IDPOSTEGGIO NUMBER(6,0) NOT NULL, 
FK_MERCATO_USO NUMBER(4,0) NOT NULL,
FK_MERCATIPRESENZET_ID NUMBER(6,0) NOT NULL,
IMPORTO_TOTALE NUMBER(11,2) NOT NULL
) ;

ALTER TABLE BOLL_GEST_MERCATI_DETT ADD CONSTRAINT PK_BOLL_GEST_MERCATI_DETT PRIMARY KEY(IDCOMUNE, ID); 
ALTER TABLE BOLL_GEST_MERCATI_DETT ADD CONSTRAINT FK_BGESTMERCDETT_MERCATI_D FOREIGN KEY(IDCOMUNE, FK_IDPOSTEGGIO) REFERENCES MERCATI_D(IDCOMUNE,IDPOSTEGGIO); 
ALTER TABLE BOLL_GEST_MERCATI_DETT ADD CONSTRAINT FK_BGESTMERCDETT_MERC_USO FOREIGN KEY(IDCOMUNE, FK_MERCATO_USO) REFERENCES MERCATI_USO(IDCOMUNE,ID); 
ALTER TABLE BOLL_GEST_MERCATI_DETT ADD CONSTRAINT FK_BGESTMERCDETT_BGESTDETTAUT FOREIGN KEY(IDCOMUNE, FK_ID_GEST_AUTORIZZAZIONI) REFERENCES BOLL_GEST_DETT_AUTORIZZ(IDCOMUNE,ID);
ALTER TABLE BOLL_GEST_MERCATI_DETT ADD CONSTRAINT FK_BGESTMERCDETT_MERCATIPREST FOREIGN KEY (IDCOMUNE, FK_MERCATIPRESENZET_ID) REFERENCES MERCATIPRESENZE_T(IDCOMUNE, ID);


CREATE TABLE PAY_CONNECTOR_CONFIG_PARAMS(  
  CONFIG_PARAM VARCHAR2(30 CHAR) NOT NULL,
  DESCRIZIONE VARCHAR2(200 CHAR) NOT NULL,
  CODICE_CONNETTORE VARCHAR2(20 CHAR),
  PRIMARY KEY (CONFIG_PARAM)
)  ;
ALTER TABLE PAY_CONNECTOR_CONFIG_PARAMS ADD CONSTRAINT PAYCONNCFG_FK_CONN FOREIGN KEY (CODICE_CONNETTORE) REFERENCES PAY_CONNECTOR_CONFIG(CODICE);


CREATE TABLE PAY_CONNECTOR_CONFIG_VALUES(  
  IDCOMUNE VARCHAR2(6 CHAR) NOT NULL,
  ID DECIMAL(4,0) NOT NULL,
  CONFIG_PARAM VARCHAR2(30 CHAR) NOT NULL,
  CODICE_CONNETTORE VARCHAR2(20 CHAR),
  VALORE VARCHAR2(500 CHAR),
  PRIMARY KEY (IDCOMUNE, ID),
  CONSTRAINT PAYCONNVAL_FK_CONN FOREIGN KEY (CODICE_CONNETTORE) REFERENCES PAY_CONNECTOR_CONFIG(CODICE),
  CONSTRAINT PAYCONNVAL_FK_CONNPARAM FOREIGN KEY (CONFIG_PARAM) REFERENCES PAY_CONNECTOR_CONFIG_PARAMS(CONFIG_PARAM)
)  ;



ALTER TABLE BOLL_CFG_TIPO ADD TITOLARITA_PAGAMENTI VARCHAR2(25 CHAR);
COMMENT ON COLUMN BOLL_CFG_TIPO.TITOLARITA_PAGAMENTI  IS 'indica se il pagamento: - deve essere assoggettato interamente al primo concessionario - ognuno paga in base alle presenze / assenze ingiustificate fatte - al concessionario attuale';

ALTER TABLE BOLL_GEST_TESTATA ADD TITOLARITA_PAGAMENTI VARCHAR2(25 CHAR);
COMMENT ON COLUMN BOLL_GEST_TESTATA.TITOLARITA_PAGAMENTI  IS 'indica se il pagamento:  - deve essere assoggettato interamente al primo concessionario  - ognuno paga in base alle presenze / assenze ingiustificate fatte  - al concessionario attuale';


ALTER TABLE BOLL_GEST_DETTAGLIO ADD IMPORTO_SENZA_IVA  NUMBER(11,2) ;
ALTER TABLE BOLL_GEST_DETTAGLIO ADD IVA NUMBER(2,0) NULL;
ALTER TABLE BOLL_GEST_DETTAGLIO ADD IMPORTO_TOTALE  NUMBER(11,2) ;

UPDATE BOLL_GEST_DETTAGLIO SET IMPORTO_TOTALE=IMPORTO WHERE IMPORTO_TOTALE IS NULL;
ALTER TABLE BOLL_GEST_DETTAGLIO DROP COLUMN IMPORTO;

ALTER TABLE BOLL_GEST_DETTAGLIO MODIFY IMPORTO_TOTALE  NUMBER(11,2) NOT NULL;
UPDATE BOLL_GEST_DETTAGLIO SET IVA=0 WHERE IVA IS NULL;

UPDATE BOLL_GEST_DETTAGLIO SET IMPORTO_SENZA_IVA=IMPORTO_TOTALE WHERE IMPORTO_SENZA_IVA IS NULL;

ALTER TABLE BOLL_GEST_DETTAGLIO MODIFY IMPORTO_SENZA_IVA  NUMBER(11,2) NOT NULL ;

 
ALTER TABLE PAY_POSIZIONI_DEBITORIE ADD DATA_CREAZIONE_FATTURA DATE NULL;
ALTER TABLE PAY_POSIZIONI_DEBITORIE ADD DATA_INVIO_AVVISO DATE NULL;


ALTER TABLE STP_TIPOLOGIE_ENDO2 MODIFY DESCRIZIONE VARCHAR2(250 CHAR);

ALTER TABLE INVENTARIOPROCEDIMENTI MODIFY CODICEANCITEL VARCHAR2(250 CHAR);
ALTER TABLE STP_ENDO_TIPO1 MODIFY CODICE_ENDO_REGIONALE VARCHAR2(250 CHAR);
ALTER TABLE STP_ENDO_TIPO2 MODIFY CODICE_ENDO_REGIONALE VARCHAR2(250 CHAR);

ALTER TABLE BOLL_GEST_DETTAGLIO ADD (FLAG_CONGUAGLIO NUMBER(1,0) DEFAULT 0 NOT NULL );


ALTER TABLE DECODIFICHE MODIFY RAGGRUPPAMENTO VARCHAR2(200 CHAR);


ALTER TABLE PAY_PROFILI_ENTI_CREDITORI MODIFY APPLICATION_CODE NUMBER(4,0) ;



ALTER TABLE DETT_POSIZIONE_DEBITORIA ADD IUV VARCHAR2(100 CHAR) ; 
ALTER TABLE DETT_POSIZIONE_DEBITORIA ADD CODICE_AVVISO VARCHAR2(50 CHAR) ; 
ALTER TABLE DETT_POSIZIONE_DEBITORIA ADD QRCODE VARCHAR2(100 CHAR) ;
ALTER TABLE DETT_POSIZIONE_DEBITORIA ADD IMPORTO_IVATO NUMBER(10,2);


alter table DETT_POSIZIONE_DEBITORIA ADD DATA_REGISTRAZIONE DATE;
ALTER TABLE DETT_POSIZIONE_DEBITORIA ADD DESCRIZIONE_CAUSALE VARCHAR2(250 CHAR);


ALTER TABLE DETT_POSIZIONE_DEBITORIA ADD CODICEANAGRAFE NUMBER(6,0);
ALTER TABLE DETT_POSIZIONE_DEBITORIA ADD CONSTRAINT FK_DETTPOSDEB_ANAGRAFE FOREIGN KEY(IDCOMUNE,CODICEANAGRAFE) REFERENCES ANAGRAFE(IDCOMUNE, CODICEANAGRAFE);


CREATE TABLE MOVIMENTI_ZIP_LOGICO_TESTATA(IDCOMUNE VARCHAR2(6 CHAR) NOT NULL, CODICEMOVIMENTO NUMBER(8,0) NOT NULL, GUID VARCHAR2(60 CHAR) NOT NULL, GUID_COLLEGATO VARCHAR2(60 CHAR));

ALTER TABLE MOVIMENTI_ZIP_LOGICO_TESTATA ADD CONSTRAINT MOVIMENTI_ZIP_LOGICO_TESTA_PK PRIMARY KEY (IDCOMUNE, CODICEMOVIMENTO);

ALTER TABLE MOVIMENTI_ZIP_LOGICO_TESTATA ADD CONSTRAINT MOVIMENTI_ZIP_LOGICO_TEST_FK1 FOREIGN KEY(IDCOMUNE, CODICEMOVIMENTO)REFERENCES MOVIMENTI(IDCOMUNE, CODICEMOVIMENTO);

ALTER TABLE PAY_DETTAGLIO_IMPORTI ADD  NUMERO_SOTTOACCERTAMENTO VARCHAR2(35 CHAR) NULL;


ALTER TABLE MERCATIPRESENZE_D DROP CONSTRAINT FK_PAYPOSDEB_SPUNT;
ALTER TABLE MERCATIPRESENZE_D MODIFY FK_PAY_POS_DEB NUMBER(10,0);

ALTER TABLE BLACKLIST_SRC_P_DEB_SP DROP CONSTRAINT FK_BLSRCPOSDEB_POSDEB;
ALTER TABLE BLACKLIST_SRC_P_DEB_SP MODIFY FK_ID_PAYPOS_DEB NUMBER(10,0);

ALTER TABLE BOLL_CFG_TIPO ADD cod_lett_accompagnamento  NUMBER(10, 0);

ALTER TABLE BOLL_CFG_TIPO ADD constraint fk_bollcfgtipo_letttipo foreign key (idcomune,cod_lett_accompagnamento) references letteretipo(idcomune,codicelettera) ;



ALTER TABLE BOLL_GEST_TESTATA ADD (DATA_SCADENZA DATE );
ALTER TABLE DETT_POSIZIONE_DEBITORIA ADD (DATA_SCADENZA DATE );

    
ALTER TABLE LIVELLO_SERVIZIO ADD CONSTRAINT UC_LIVELLOSERVIZIO UNIQUE (IDCOMUNE,SEGNAPOSTO);

ALTER TABLE PAY_CONNECTOR_WS_ENDPOINT ADD FLAG_SPEGNI_SCHEDULER NUMBER(1,0) NULL;

ALTER TABLE CONTI ADD NUMERO_SOTTO_ACCERTAMENTO VARCHAR2(35 CHAR) NULL;