ALTER TABLE MERCATIPRESENZE_D ADD CONSTRAINT FK_PAYPOSDEB_SPUNT FOREIGN KEY (IDCOMUNE,FK_PAY_POS_DEB) REFERENCES DETT_POSIZIONE_DEBITORIA(IDCOMUNE, ID);

ALTER TABLE BLACKLIST_SRC_P_DEB_SP ADD CONSTRAINT FK_BLSRCPOSDEB_POSDEB FOREIGN KEY (IDCOMUNE,FK_ID_PAYPOS_DEB) REFERENCES DETT_POSIZIONE_DEBITORIA(IDCOMUNE, ID);
