<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:tns="http://easybridge.eu/bridge/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:s="http://www.w3.org/2001/XMLSchema" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" targetNamespace="http://easybridge.eu/bridge/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
    <s:schema elementFormDefault="qualified" targetNamespace="http://easybridge.eu/bridge/">
      <s:element name="pdpGeneraIUV">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="identificativoDominio" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="identificativoBU" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="param" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="pdpGeneraIUVResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="pdpGeneraIUVResult" type="tns:Output" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:complexType name="Output">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="1" name="param" type="s:string" />
        </s:sequence>
      </s:complexType>
      <s:element name="pdpCaricaPagamento">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="identificativoDominio" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="identificativoBU" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="param" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="pdpCaricaPagamentoResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="pdpCaricaPagamentoResult" type="tns:Output" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="pdpGeneraRPT">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="identificativoDominio" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="identificativoBU" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="param" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="pdpGeneraRPTResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="pdpGeneraRPTResult" type="tns:Output" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="pdpInviaRPT">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="identificativoDominio" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="identificativoBU" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="param" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="pdpInviaRPTResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="pdpInviaRPTResult" type="tns:Output" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="pdpChiediStatoRPT">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="identificativoDominio" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="identificativoBU" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="param" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="pdpChiediStatoRPTResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="pdpChiediStatoRPTResult" type="tns:Output" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="pdpRecuperaRPT">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="identificativoDominio" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="identificativoBU" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="param" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="pdpRecuperaRPTResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="pdpRecuperaRPTResult" type="tns:Output" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="pdpRecuperaRT">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="identificativoDominio" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="identificativoBU" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="param" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="pdpRecuperaRTResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="pdpRecuperaRTResult" type="tns:Output" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="pdpRichiediStornoRT">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="identificativoDominio" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="identificativoBU" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="param" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="pdpRichiediStornoRTResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="pdpRichiediStornoRTResult" type="tns:Output" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="pdpChiediSceltaWISP">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="identificativoDominio" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="identificativoBU" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="param" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="pdpChiediSceltaWISPResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="pdpChiediSceltaWISPResult" type="tns:Output" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="pdpPredisponiCodiciGraficiIUV">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="identificativoDominio" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="identificativoBU" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="param" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="pdpPredisponiCodiciGraficiIUVResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="pdpPredisponiCodiciGraficiIUVResult" type="tns:Output" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="pdpInviaCarrelloRPT">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="identificativoDominio" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="identificativoBU" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="param" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="pdpInviaCarrelloRPTResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="pdpInviaCarrelloRPTResult" type="tns:Output" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="pdpVerificaMarcaDaBolloDigitale">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="identificativoDominio" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="identificativoBU" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="param" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="pdpVerificaMarcaDaBolloDigitaleResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="pdpVerificaMarcaDaBolloDigitaleResult" type="tns:Output" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="pdpCancellaPagamento">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="identificativoDominio" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="identificativoBU" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="param" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="pdpCancellaPagamentoResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="pdpCancellaPagamentoResult" type="tns:Output" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="pdpAttivaPagamento">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="identificativoDominio" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="identificativoBU" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="param" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="pdpAttivaPagamentoResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="pdpAttivaPagamentoResult" type="tns:Output" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="pdpRecuperaDebit">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="identificativoDominio" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="identificativoBU" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="param" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="pdpRecuperaDebitResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="pdpRecuperaDebitResult" type="tns:Output" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="pdpGenAnalogRT">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="identificativoDominio" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="identificativoBU" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="param" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="pdpGenAnalogRTResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="pdpGenAnalogRTResult" type="tns:Output" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="pdpPaymentNotice">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="identificativoDominio" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="identificativoBU" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="param" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="pdpPaymentNoticeResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="pdpPaymentNoticeResult" type="tns:Output" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="pdpExportAny">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="identificativoDominio" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="identificativoBU" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="param" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="pdpExportAnyResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="pdpExportAnyResult" type="tns:Output" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="pdpExportFile">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="identificativoDominio" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="identificativoBU" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="param" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="pdpExportFileResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="pdpExportFileResult" type="tns:Output" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="intExecuteDistant">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="identificativoDominio" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="identificativoBU" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="param" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="intExecuteDistantResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="intExecuteDistantResult" type="tns:Output" />
          </s:sequence>
        </s:complexType>
      </s:element>
    </s:schema>
  </wsdl:types>
  <wsdl:message name="pdpGeneraIUVSoapIn">
    <wsdl:part name="parameters" element="tns:pdpGeneraIUV" />
  </wsdl:message>
  <wsdl:message name="pdpGeneraIUVSoapOut">
    <wsdl:part name="parameters" element="tns:pdpGeneraIUVResponse" />
  </wsdl:message>
  <wsdl:message name="pdpCaricaPagamentoSoapIn">
    <wsdl:part name="parameters" element="tns:pdpCaricaPagamento" />
  </wsdl:message>
  <wsdl:message name="pdpCaricaPagamentoSoapOut">
    <wsdl:part name="parameters" element="tns:pdpCaricaPagamentoResponse" />
  </wsdl:message>
  <wsdl:message name="pdpGeneraRPTSoapIn">
    <wsdl:part name="parameters" element="tns:pdpGeneraRPT" />
  </wsdl:message>
  <wsdl:message name="pdpGeneraRPTSoapOut">
    <wsdl:part name="parameters" element="tns:pdpGeneraRPTResponse" />
  </wsdl:message>
  <wsdl:message name="pdpInviaRPTSoapIn">
    <wsdl:part name="parameters" element="tns:pdpInviaRPT" />
  </wsdl:message>
  <wsdl:message name="pdpInviaRPTSoapOut">
    <wsdl:part name="parameters" element="tns:pdpInviaRPTResponse" />
  </wsdl:message>
  <wsdl:message name="pdpChiediStatoRPTSoapIn">
    <wsdl:part name="parameters" element="tns:pdpChiediStatoRPT" />
  </wsdl:message>
  <wsdl:message name="pdpChiediStatoRPTSoapOut">
    <wsdl:part name="parameters" element="tns:pdpChiediStatoRPTResponse" />
  </wsdl:message>
  <wsdl:message name="pdpRecuperaRPTSoapIn">
    <wsdl:part name="parameters" element="tns:pdpRecuperaRPT" />
  </wsdl:message>
  <wsdl:message name="pdpRecuperaRPTSoapOut">
    <wsdl:part name="parameters" element="tns:pdpRecuperaRPTResponse" />
  </wsdl:message>
  <wsdl:message name="pdpRecuperaRTSoapIn">
    <wsdl:part name="parameters" element="tns:pdpRecuperaRT" />
  </wsdl:message>
  <wsdl:message name="pdpRecuperaRTSoapOut">
    <wsdl:part name="parameters" element="tns:pdpRecuperaRTResponse" />
  </wsdl:message>
  <wsdl:message name="pdpRichiediStornoRTSoapIn">
    <wsdl:part name="parameters" element="tns:pdpRichiediStornoRT" />
  </wsdl:message>
  <wsdl:message name="pdpRichiediStornoRTSoapOut">
    <wsdl:part name="parameters" element="tns:pdpRichiediStornoRTResponse" />
  </wsdl:message>
  <wsdl:message name="pdpChiediSceltaWISPSoapIn">
    <wsdl:part name="parameters" element="tns:pdpChiediSceltaWISP" />
  </wsdl:message>
  <wsdl:message name="pdpChiediSceltaWISPSoapOut">
    <wsdl:part name="parameters" element="tns:pdpChiediSceltaWISPResponse" />
  </wsdl:message>
  <wsdl:message name="pdpPredisponiCodiciGraficiIUVSoapIn">
    <wsdl:part name="parameters" element="tns:pdpPredisponiCodiciGraficiIUV" />
  </wsdl:message>
  <wsdl:message name="pdpPredisponiCodiciGraficiIUVSoapOut">
    <wsdl:part name="parameters" element="tns:pdpPredisponiCodiciGraficiIUVResponse" />
  </wsdl:message>
  <wsdl:message name="pdpInviaCarrelloRPTSoapIn">
    <wsdl:part name="parameters" element="tns:pdpInviaCarrelloRPT" />
  </wsdl:message>
  <wsdl:message name="pdpInviaCarrelloRPTSoapOut">
    <wsdl:part name="parameters" element="tns:pdpInviaCarrelloRPTResponse" />
  </wsdl:message>
  <wsdl:message name="pdpVerificaMarcaDaBolloDigitaleSoapIn">
    <wsdl:part name="parameters" element="tns:pdpVerificaMarcaDaBolloDigitale" />
  </wsdl:message>
  <wsdl:message name="pdpVerificaMarcaDaBolloDigitaleSoapOut">
    <wsdl:part name="parameters" element="tns:pdpVerificaMarcaDaBolloDigitaleResponse" />
  </wsdl:message>
  <wsdl:message name="pdpCancellaPagamentoSoapIn">
    <wsdl:part name="parameters" element="tns:pdpCancellaPagamento" />
  </wsdl:message>
  <wsdl:message name="pdpCancellaPagamentoSoapOut">
    <wsdl:part name="parameters" element="tns:pdpCancellaPagamentoResponse" />
  </wsdl:message>
  <wsdl:message name="pdpAttivaPagamentoSoapIn">
    <wsdl:part name="parameters" element="tns:pdpAttivaPagamento" />
  </wsdl:message>
  <wsdl:message name="pdpAttivaPagamentoSoapOut">
    <wsdl:part name="parameters" element="tns:pdpAttivaPagamentoResponse" />
  </wsdl:message>
  <wsdl:message name="pdpRecuperaDebitSoapIn">
    <wsdl:part name="parameters" element="tns:pdpRecuperaDebit" />
  </wsdl:message>
  <wsdl:message name="pdpRecuperaDebitSoapOut">
    <wsdl:part name="parameters" element="tns:pdpRecuperaDebitResponse" />
  </wsdl:message>
  <wsdl:message name="pdpGenAnalogRTSoapIn">
    <wsdl:part name="parameters" element="tns:pdpGenAnalogRT" />
  </wsdl:message>
  <wsdl:message name="pdpGenAnalogRTSoapOut">
    <wsdl:part name="parameters" element="tns:pdpGenAnalogRTResponse" />
  </wsdl:message>
  <wsdl:message name="pdpPaymentNoticeSoapIn">
    <wsdl:part name="parameters" element="tns:pdpPaymentNotice" />
  </wsdl:message>
  <wsdl:message name="pdpPaymentNoticeSoapOut">
    <wsdl:part name="parameters" element="tns:pdpPaymentNoticeResponse" />
  </wsdl:message>
  <wsdl:message name="pdpExportAnySoapIn">
    <wsdl:part name="parameters" element="tns:pdpExportAny" />
  </wsdl:message>
  <wsdl:message name="pdpExportAnySoapOut">
    <wsdl:part name="parameters" element="tns:pdpExportAnyResponse" />
  </wsdl:message>
  <wsdl:message name="pdpExportFileSoapIn">
    <wsdl:part name="parameters" element="tns:pdpExportFile" />
  </wsdl:message>
  <wsdl:message name="pdpExportFileSoapOut">
    <wsdl:part name="parameters" element="tns:pdpExportFileResponse" />
  </wsdl:message>
  <wsdl:message name="intExecuteDistantSoapIn">
    <wsdl:part name="parameters" element="tns:intExecuteDistant" />
  </wsdl:message>
  <wsdl:message name="intExecuteDistantSoapOut">
    <wsdl:part name="parameters" element="tns:intExecuteDistantResponse" />
  </wsdl:message>
  <wsdl:portType name="WEBS_EasyBridgeInterfaceSoap">
    <wsdl:operation name="pdpGeneraIUV">
      <wsdl:input message="tns:pdpGeneraIUVSoapIn" />
      <wsdl:output message="tns:pdpGeneraIUVSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="pdpCaricaPagamento">
      <wsdl:input message="tns:pdpCaricaPagamentoSoapIn" />
      <wsdl:output message="tns:pdpCaricaPagamentoSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="pdpGeneraRPT">
      <wsdl:input message="tns:pdpGeneraRPTSoapIn" />
      <wsdl:output message="tns:pdpGeneraRPTSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="pdpInviaRPT">
      <wsdl:input message="tns:pdpInviaRPTSoapIn" />
      <wsdl:output message="tns:pdpInviaRPTSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="pdpChiediStatoRPT">
      <wsdl:input message="tns:pdpChiediStatoRPTSoapIn" />
      <wsdl:output message="tns:pdpChiediStatoRPTSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="pdpRecuperaRPT">
      <wsdl:input message="tns:pdpRecuperaRPTSoapIn" />
      <wsdl:output message="tns:pdpRecuperaRPTSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="pdpRecuperaRT">
      <wsdl:input message="tns:pdpRecuperaRTSoapIn" />
      <wsdl:output message="tns:pdpRecuperaRTSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="pdpRichiediStornoRT">
      <wsdl:input message="tns:pdpRichiediStornoRTSoapIn" />
      <wsdl:output message="tns:pdpRichiediStornoRTSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="pdpChiediSceltaWISP">
      <wsdl:input message="tns:pdpChiediSceltaWISPSoapIn" />
      <wsdl:output message="tns:pdpChiediSceltaWISPSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="pdpPredisponiCodiciGraficiIUV">
      <wsdl:input message="tns:pdpPredisponiCodiciGraficiIUVSoapIn" />
      <wsdl:output message="tns:pdpPredisponiCodiciGraficiIUVSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="pdpInviaCarrelloRPT">
      <wsdl:input message="tns:pdpInviaCarrelloRPTSoapIn" />
      <wsdl:output message="tns:pdpInviaCarrelloRPTSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="pdpVerificaMarcaDaBolloDigitale">
      <wsdl:input message="tns:pdpVerificaMarcaDaBolloDigitaleSoapIn" />
      <wsdl:output message="tns:pdpVerificaMarcaDaBolloDigitaleSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="pdpCancellaPagamento">
      <wsdl:input message="tns:pdpCancellaPagamentoSoapIn" />
      <wsdl:output message="tns:pdpCancellaPagamentoSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="pdpAttivaPagamento">
      <wsdl:input message="tns:pdpAttivaPagamentoSoapIn" />
      <wsdl:output message="tns:pdpAttivaPagamentoSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="pdpRecuperaDebit">
      <wsdl:input message="tns:pdpRecuperaDebitSoapIn" />
      <wsdl:output message="tns:pdpRecuperaDebitSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="pdpGenAnalogRT">
      <wsdl:input message="tns:pdpGenAnalogRTSoapIn" />
      <wsdl:output message="tns:pdpGenAnalogRTSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="pdpPaymentNotice">
      <wsdl:input message="tns:pdpPaymentNoticeSoapIn" />
      <wsdl:output message="tns:pdpPaymentNoticeSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="pdpExportAny">
      <wsdl:input message="tns:pdpExportAnySoapIn" />
      <wsdl:output message="tns:pdpExportAnySoapOut" />
    </wsdl:operation>
    <wsdl:operation name="pdpExportFile">
      <wsdl:input message="tns:pdpExportFileSoapIn" />
      <wsdl:output message="tns:pdpExportFileSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="intExecuteDistant">
      <wsdl:input message="tns:intExecuteDistantSoapIn" />
      <wsdl:output message="tns:intExecuteDistantSoapOut" />
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="WEBS_EasyBridgeInterfaceSoap" type="tns:WEBS_EasyBridgeInterfaceSoap">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="pdpGeneraIUV">
      <soap:operation soapAction="http://easybridge.eu/bridge/pdpGeneraIUV" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="pdpCaricaPagamento">
      <soap:operation soapAction="http://easybridge.eu/bridge/pdpCaricaPagamento" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="pdpGeneraRPT">
      <soap:operation soapAction="http://easybridge.eu/bridge/pdpGeneraRPT" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="pdpInviaRPT">
      <soap:operation soapAction="http://easybridge.eu/bridge/pdpInviaRPT" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="pdpChiediStatoRPT">
      <soap:operation soapAction="http://easybridge.eu/bridge/pdpChiediStatoRPT" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="pdpRecuperaRPT">
      <soap:operation soapAction="http://easybridge.eu/bridge/pdpRecuperaRPT" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="pdpRecuperaRT">
      <soap:operation soapAction="http://easybridge.eu/bridge/pdpRecuperaRT" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="pdpRichiediStornoRT">
      <soap:operation soapAction="http://easybridge.eu/bridge/pdpRichiediStornoRT" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="pdpChiediSceltaWISP">
      <soap:operation soapAction="http://easybridge.eu/bridge/pdpChiediSceltaWISP" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="pdpPredisponiCodiciGraficiIUV">
      <soap:operation soapAction="http://easybridge.eu/bridge/pdpPredisponiCodiciGraficiIUV" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="pdpInviaCarrelloRPT">
      <soap:operation soapAction="http://easybridge.eu/bridge/pdpInviaCarrelloRPT" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="pdpVerificaMarcaDaBolloDigitale">
      <soap:operation soapAction="http://easybridge.eu/bridge/pdpVerificaMarcaDaBolloDigitale" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="pdpCancellaPagamento">
      <soap:operation soapAction="http://easybridge.eu/bridge/pdpCancellaPagamento" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="pdpAttivaPagamento">
      <soap:operation soapAction="http://easybridge.eu/bridge/pdpAttivaPagamento" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="pdpRecuperaDebit">
      <soap:operation soapAction="http://easybridge.eu/bridge/pdpRecuperaDebit" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="pdpGenAnalogRT">
      <soap:operation soapAction="http://easybridge.eu/bridge/pdpGenAnalogRT" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="pdpPaymentNotice">
      <soap:operation soapAction="http://easybridge.eu/bridge/pdpPaymentNotice" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="pdpExportAny">
      <soap:operation soapAction="http://easybridge.eu/bridge/pdpExportAny" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="pdpExportFile">
      <soap:operation soapAction="http://easybridge.eu/bridge/pdpExportFile" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="intExecuteDistant">
      <soap:operation soapAction="http://easybridge.eu/bridge/intExecuteDistant" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:binding name="WEBS_EasyBridgeInterfaceSoap12" type="tns:WEBS_EasyBridgeInterfaceSoap">
    <soap12:binding transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="pdpGeneraIUV">
      <soap12:operation soapAction="http://easybridge.eu/bridge/pdpGeneraIUV" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="pdpCaricaPagamento">
      <soap12:operation soapAction="http://easybridge.eu/bridge/pdpCaricaPagamento" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="pdpGeneraRPT">
      <soap12:operation soapAction="http://easybridge.eu/bridge/pdpGeneraRPT" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="pdpInviaRPT">
      <soap12:operation soapAction="http://easybridge.eu/bridge/pdpInviaRPT" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="pdpChiediStatoRPT">
      <soap12:operation soapAction="http://easybridge.eu/bridge/pdpChiediStatoRPT" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="pdpRecuperaRPT">
      <soap12:operation soapAction="http://easybridge.eu/bridge/pdpRecuperaRPT" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="pdpRecuperaRT">
      <soap12:operation soapAction="http://easybridge.eu/bridge/pdpRecuperaRT" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="pdpRichiediStornoRT">
      <soap12:operation soapAction="http://easybridge.eu/bridge/pdpRichiediStornoRT" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="pdpChiediSceltaWISP">
      <soap12:operation soapAction="http://easybridge.eu/bridge/pdpChiediSceltaWISP" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="pdpPredisponiCodiciGraficiIUV">
      <soap12:operation soapAction="http://easybridge.eu/bridge/pdpPredisponiCodiciGraficiIUV" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="pdpInviaCarrelloRPT">
      <soap12:operation soapAction="http://easybridge.eu/bridge/pdpInviaCarrelloRPT" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="pdpVerificaMarcaDaBolloDigitale">
      <soap12:operation soapAction="http://easybridge.eu/bridge/pdpVerificaMarcaDaBolloDigitale" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="pdpCancellaPagamento">
      <soap12:operation soapAction="http://easybridge.eu/bridge/pdpCancellaPagamento" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="pdpAttivaPagamento">
      <soap12:operation soapAction="http://easybridge.eu/bridge/pdpAttivaPagamento" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="pdpRecuperaDebit">
      <soap12:operation soapAction="http://easybridge.eu/bridge/pdpRecuperaDebit" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="pdpGenAnalogRT">
      <soap12:operation soapAction="http://easybridge.eu/bridge/pdpGenAnalogRT" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="pdpPaymentNotice">
      <soap12:operation soapAction="http://easybridge.eu/bridge/pdpPaymentNotice" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="pdpExportAny">
      <soap12:operation soapAction="http://easybridge.eu/bridge/pdpExportAny" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="pdpExportFile">
      <soap12:operation soapAction="http://easybridge.eu/bridge/pdpExportFile" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="intExecuteDistant">
      <soap12:operation soapAction="http://easybridge.eu/bridge/intExecuteDistant" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="WEBS_EasyBridgeInterface">
    <wsdl:port name="WEBS_EasyBridgeInterfaceSoap" binding="tns:WEBS_EasyBridgeInterfaceSoap">
      <soap:address location="http://88.80.149.16/bridge/WEBS_EasyBridgeInterface.asmx" />
    </wsdl:port>
    <wsdl:port name="WEBS_EasyBridgeInterfaceSoap12" binding="tns:WEBS_EasyBridgeInterfaceSoap12">
      <soap12:address location="http://88.80.149.16/bridge/WEBS_EasyBridgeInterface.asmx" />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>