<wsdl:definitions targetNamespace="http://www.cart.rete.toscana.it/servizi/iris_1_1/proxy" xmlns="http://www.cart.rete.toscana.it/servizi/iris_1_1/proxy" xmlns:h="http://www.cart.rete.toscana.it/servizi/iris_1_1/IdpHeader" xmlns:i="http://www.cart.rete.toscana.it/servizi/iris_1_1/IdpInclude" xmlns:idpAP="http://www.cart.rete.toscana.it/servizi/iris_1_1/IdpAllineamentoPendenze" xmlns:idpAPE="http://www.cart.rete.toscana.it/servizi/iris_1_1/IdpEsito" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<wsdl:types>
		<xsd:schema targetNamespace="http://www.cart.rete.toscana.it/servizi/iris_1_1/proxy">
			<xsd:import namespace="http://www.cart.rete.toscana.it/servizi/iris_1_1/IdpEsito" schemaLocation="Schemi/IdP.Esito.xsd"/>
			<xsd:element name="IdpAllineamentoPendenzeEnte.Esito">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element ref="idpAPE:IdpEsito"/>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="AllineamentoPendenzeEnte.EsitoMessage">
		<wsdl:part element="IdpAllineamentoPendenzeEnte.Esito" name="AllineamentoPendenzeEnte.Esito"/>
	</wsdl:message>
	<wsdl:portType name="ComunicazionePosizioniDebitorieEsito">
		<wsdl:operation name="IdpAllineamentoPendenzeEnte.Esito">
			<wsdl:input message="AllineamentoPendenzeEnte.EsitoMessage" name="AllineamentoPendenzeEnte.EsitoMessage"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="ComunicazionePosizioniDebitorieEsitoBinding" type="ComunicazionePosizioniDebitorieEsito">
		<soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IdpAllineamentoPendenzeEnte.Esito">
			<soap:operation soapAction="IdpAllineamentoPendenzeEnte.Esito" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="ComunicazionePosizioniDebitorieEsitoService">
		<wsdl:port binding="ComunicazionePosizioniDebitorieEsitoBinding" name="ComunicazionePosizioniDebitorieEsitoPort">
			<soap:address location="http://pdd/portadelegata"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>