<wsdl:definitions 
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
    xmlns:idpIPP="http://www.cart.rete.toscana.it/servizi/iris_1_1/IdpInformativaPagamento" 
    xmlns:idpE="http://www.cart.rete.toscana.it/servizi/iris_1_1/IdpEsito" 
    xmlns="http://www.cart.rete.toscana.it/servizi/iris_1_1/proxy" 
    xmlns:h="http://www.cart.rete.toscana.it/servizi/iris_1_1/IdpHeader" 
    xmlns:i="http://www.cart.rete.toscana.it/servizi/iris_1_1/IdpInclude" 
    xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" 
    targetNamespace="http://www.cart.rete.toscana.it/servizi/iris_1_1/proxy">
	
	<wsdl:types>
		<xsd:schema targetNamespace="http://www.cart.rete.toscana.it/servizi/iris_1_1/proxy">
			<xsd:import namespace="http://www.cart.rete.toscana.it/servizi/iris_1_1/IdpInformativaPagamento" schemaLocation="./Schemi/IdP.InformativaPagamento.xsd"/>
			<xsd:import namespace="http://www.cart.rete.toscana.it/servizi/iris_1_1/IdpEsito" schemaLocation="./Schemi/IdP.Esito.xsd"/>
            
            <xsd:element name="IdpInformativaPagamento">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element ref="idpIPP:IdpInformativaPagamento"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            
            <xsd:element name="IdpInformativaPagamentoResponse">
            	<xsd:complexType>
            		<xsd:sequence>

            			<xsd:element name="infoMessaggio"
            				type="idpE:InfoMessaggio">
            			</xsd:element>
            		</xsd:sequence>
            	</xsd:complexType>
            </xsd:element>
		</xsd:schema>
    </wsdl:types>
    
    <wsdl:message name="IdpInformativaPagamentoMessage">
        <wsdl:part name="IdpInformativaPagamento" element="IdpInformativaPagamento"/>
    </wsdl:message>

    <wsdl:message name="IdpInformativaPagamentoResponse">
    	<wsdl:part name="IdpinformativaPagamentoResponse" element="IdpInformativaPagamentoResponse"></wsdl:part>
    </wsdl:message>
    <wsdl:portType name="InvioNotificaPagamento">
        <wsdl:operation name="IdpInformativaPagamento">
            <wsdl:input  name="IdpInformativaPagamentoMessage"  message="IdpInformativaPagamentoMessage"/>
            <wsdl:output name="IdpInformativaPagamentoResponse" message="IdpInformativaPagamentoResponse"></wsdl:output>
        </wsdl:operation>
    </wsdl:portType>
    
    <wsdl:binding name="InvioNotificaPagamentoBinding" type="InvioNotificaPagamento">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="IdpInformativaPagamento">
            <soap:operation soapAction="IdpInformativaPagamento"/>
            <wsdl:input name="IdpInformativaPagamentoMessage">
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
    
    <wsdl:service name="InvioNotificaPagamentoService">
        <wsdl:port binding="InvioNotificaPagamentoBinding" name="InvioNotificaPagamento">
            <soap:address location="http://host/invionotificapagamento" />
        </wsdl:port>
    </wsdl:service>
 
</wsdl:definitions>