
ALTER TABLE INVENTARIOPROCEDIMENTIONERI 
ADD (FK_COIDCOMUNE VARCHAR2(6) );

ALTER TABLE INVENTARIOPROCEDIMENTIONERI 
ADD (FLAG_DISATTIVO number(1,0) );

ALTER TABLE INVENTARIOPROCEDIMENTIONERI 
DROP CONSTRAINT FK_INVENT_PROCONER_TIPI_CAUS;

ALTER TABLE INVENTARIOPROCEDIMENTIONERI
ADD CONSTRAINT FK_INVENT_PROCONER_TIPI_CAUS FOREIGN KEY
(
  FK_COIDCOMUNE 
, FK_COID 
)
REFERENCES TIPICAUSALIONERI
(
  IDCOMUNE 
, CO_ID 
)
ENABLE;


ALTER TABLE INVENTARIOPROCEDIMENTIONERI 
DROP CONSTRAINT FK_INV_PROC_ONERI_INV_PROC;

ALTER TABLE INVENTARIOPROCEDIMENTIONERI 
ADD (FK_INVPROC_IDCOMUNE VARCHAR2(6) );

ALTER TABLE INVENTARIOPROCEDIMENTIONERI
ADD CONSTRAINT FK_INV_PROC_ONERI_INV_PROC FOREIGN KEY
(
  FK_INVPROC_IDCOMUNE 
, CODICEINVENTARIO 
)
REFERENCES INVENTARIOPROCEDIMENTI
(
  IDCOMUNE 
, CODICEINVENTARIO 
)
ENABLE;

ALTER TABLE INVENTARIOPROCEDIMENTIONERI ADD (CODICECOMUNE VARCHAR2(6) );

ALTER TABLE INVENTARIOPROCEDIMENTIONERI
ADD CONSTRAINT FK_INVPROCONERI_COMUNI FOREIGN KEY
(
  CODICECOMUNE 
)
REFERENCES COMUNI
(
  CODICECOMUNE 
)
ENABLE;

ALTER TABLE INVENTARIOPROCEDIMENTIONERI DROP COLUMN FLAG_PAGATO;

