DELETE FROM INTERESSI_LEGALI;

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (1,STR_TO_DATE('21-04-1942','%d-%m-%Y'),STR_TO_DATE('15-12-1990','%d-%m-%Y'),5,null);

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (2,STR_TO_DATE('16-12-1990','%d-%m-%Y'),STR_TO_DATE('31-12-1996','%d-%m-%Y'),10,'Legge 26 novembre 1990, n. 353'); 

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (3,STR_TO_DATE('01-01-1997','%d-%m-%Y'),STR_TO_DATE('31-12-1998','%d-%m-%Y'),5,'Legge 23 dicembre 1996, n. 662'); 

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (4,STR_TO_DATE('01-01-1999','%d-%m-%Y'),STR_TO_DATE('31-12-2000','%d-%m-%Y'),2.5,'D.M. 10 dicembre 1998');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (5,STR_TO_DATE('01-01-2001','%d-%m-%Y'),STR_TO_DATE('31-12-2001','%d-%m-%Y'),3.5,'D.M. 11 dicembre 2000');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (6,STR_TO_DATE('01-01-2002','%d-%m-%Y'),STR_TO_DATE('31-12-2003','%d-%m-%Y'),3,'D.M. 11 dicembre 2001');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (7,STR_TO_DATE('01-01-2004','%d-%m-%Y'),STR_TO_DATE('31-12-2007','%d-%m-%Y'),2.5,'D.M. 1 dicembre 2003');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (8,STR_TO_DATE('01-01-2008','%d-%m-%Y'),STR_TO_DATE('31-12-2009','%d-%m-%Y'),3,'D.M. 12 dicembre 2007');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (9,STR_TO_DATE('01-01-2010','%d-%m-%Y'),STR_TO_DATE('31-12-2010','%d-%m-%Y'),1,'D.M. 4 dicembre 2009');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (10,STR_TO_DATE('01-01-2011','%d-%m-%Y'),STR_TO_DATE('31-12-2011','%d-%m-%Y'),1.5,'D.M. 07 Dicembre 2010');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (11,STR_TO_DATE('01-01-2012','%d-%m-%Y'),STR_TO_DATE('31-12-2013','%d-%m-%Y'),2.5,'DM 12 dicembre 2011');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (12,STR_TO_DATE('01-01-2014','%d-%m-%Y'),STR_TO_DATE('31-12-2014','%d-%m-%Y'),1,'Dm Economia 13.12.2013');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (13,STR_TO_DATE('01-01-2015','%d-%m-%Y'),STR_TO_DATE('31-12-2015','%d-%m-%Y'),0.5,'Dm Economia 11.12.2014');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (14,STR_TO_DATE('01-01-2016','%d-%m-%Y'),STR_TO_DATE('31-12-2016','%d-%m-%Y') ,0.2,'Dm Economia 11.12.2015');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (15,STR_TO_DATE('01-01-2017', '%d-%m-%Y'),STR_TO_DATE('31-12-2017', '%d-%m-%Y'),0.1,'Dm economia e finanze 07/12/2016,G.U.14/12/2016');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (16,STR_TO_DATE('01-01-2018', '%d-%m-%Y'),STR_TO_DATE('31-12-2018', '%d-%m-%Y'),0.3,'Dm economia e finanze 13/12/2017,G.U.15/12/2017');


Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (17,STR_TO_DATE('01-01-2019', '%d-%m-%Y'),NULL,0.8,'Dm economia 12/12/2018,G.U. 302 31/12/2018');


ALTER TABLE INVENTARIOPROCEDIMENTIONERI ADD DYN2CAMPI_ONERI_FRONT NUMERIC(10,0);
ALTER TABLE ALBEROPROC_ONERI ADD DYN2CAMPI_ONERI_FRONT NUMERIC(10,0);

ALTER TABLE INVENTARIOPROCEDIMENTIONERI ADD CONSTRAINT FK_INV_PROC_ONERI_DYN2C FOREIGN KEY (IDCOMUNE,DYN2CAMPI_ONERI_FRONT) REFERENCES DYN2_CAMPI(IDCOMUNE,ID);

ALTER TABLE ALBEROPROC_ONERI ADD CONSTRAINT FK_ALB_PROC_ONERI_DYN2C FOREIGN KEY (IDCOMUNE,DYN2CAMPI_ONERI_FRONT) REFERENCES DYN2_CAMPI(IDCOMUNE,ID);






CREATE TABLE EQUITALIA_TRACCIATI_CFG(
  IDCOMUNE VARCHAR(6) NOT NULL,
  ID NUMERIC(10,0) NOT NULL,
  SOFTWARE VARCHAR (2) NOT NULL,
  CODICE_ENTE_CREDITORE VARCHAR(10),
  TIPO_UFFICIO VARCHAR(5),
  CODICE_UFFICIO VARCHAR(10),
  TIPO_MINUTA VARCHAR(1),
  TIPO_CARTELLAZIONE VARCHAR(5),
  SPECIE_DEL_RUOLO VARCHAR(5),
  TIPO_ISCRIZIONE VARCHAR(5),
  TIPO_COMPENSO VARCHAR(5),
  RILASCIO VARCHAR(5),
  TESTO_MODALITA_OPPOSIZIONE VARCHAR(5),
  TESTO_COMUNICAZIONE_CONTRIB VARCHAR(5),
  INVIO_TESTO_SING_CONTRIB VARCHAR(5),
  TIPOLOGIA_ENTE VARCHAR(5),
  INVIO_VOLANTINO VARCHAR(5),
  MODALITA_STAMPA_VOLANTINO VARCHAR(5),
  COMUNICAZIONE_CONTRIB VARCHAR(5),
  FLAG_PROVENIENZA VARCHAR(5),
  CODICE_MOV_ANNO_DEBITO VARCHAR(8) NOT NULL,
  CODICE_MOV_DATA_ATTO VARCHAR(8) NOT NULL,
  CODICE_MOV_DATA_NOTIFICA_ATTO VARCHAR(8) NOT NULL 
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE EQUITALIA_TRACCIATI_CFG ADD CONSTRAINT PK_EQUITALIA_TRACCIATI_CFG PRIMARY KEY (IDCOMUNE, ID);

ALTER TABLE EQUITALIA_TRACCIATI_CFG ADD CODIFICA_TIPOLOGIA_ATTO VARCHAR(5); 
ALTER TABLE EQUITALIA_TRACCIATI_CFG ADD CODICE_TIPO_ATTO VARCHAR(5); 
ALTER TABLE EQUITALIA_TRACCIATI_CFG ADD DYN_2_CAMPI_TESTO_VERBALE VARCHAR(50);
ALTER TABLE EQUITALIA_TRACCIATI_CFG ADD MAP_EQ_IN_SAN_AMM_COM_ONER NUMERIC(10,0); 
ALTER TABLE EQUITALIA_TRACCIATI_CFG ADD MAP_EQ_IN_SP_SAN_AMM_COM_ONER NUMERIC (10,0);


CREATE TABLE EQUITALIATRACCIATO(
  IDCOMUNE VARCHAR(6) NOT NULL,
  ID NUMERIC(10,0) NOT NULL,
  SOFTWARE VARCHAR (2) NOT NULL,
  DATA_CREAZIONE DATETIME NOT NULL,
  PROGRESSIVO_ANNO NUMERIC (5,0) NOT NULL ,
  ANNO VARCHAR (4) NOT NULL,
  CODICEOGGETTO NUMERIC(10,0),
  CODICERESPONSABILE NUMERIC (8,0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE EQUITALIATRACCIATO ADD CONSTRAINT PK_EQUITALIATRACCIATO PRIMARY KEY (IDCOMUNE, ID);

ALTER TABLE EQUITALIATRACCIATO ADD CONSTRAINT FK_EQUIT_TRACC_OGGETTI FOREIGN KEY (IDCOMUNE,CODICEOGGETTO) REFERENCES OGGETTI(IDCOMUNE,CODICEOGGETTO);
ALTER TABLE EQUITALIATRACCIATO ADD CONSTRAINT FK_EQUIT_TRACC_RESP FOREIGN KEY (IDCOMUNE,CODICERESPONSABILE) REFERENCES RESPONSABILI(IDCOMUNE,CODICERESPONSABILE);


CREATE TABLE EQUITALIATRACCIATO_D(
  IDCOMUNE VARCHAR(6) NOT NULL,
  ID NUMERIC(10,0) NOT NULL,
  FK_TRACCIATO_EQ NUMERIC(10,0) NOT NULL,
  FK_ISTANZA NUMERIC (6,0) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE EQUITALIATRACCIATO_D ADD CONSTRAINT PK_EQUITALIATRACCIATO_D PRIMARY KEY (IDCOMUNE, ID);

ALTER TABLE EQUITALIATRACCIATO_D ADD CONSTRAINT FK_EQUIT_TRACC_D FOREIGN KEY (IDCOMUNE,FK_TRACCIATO_EQ) REFERENCES EQUITALIATRACCIATO(IDCOMUNE,ID);

ALTER TABLE EQUITALIATRACCIATO_D ADD CONSTRAINT FK_EQUIT_TRACC_IST FOREIGN KEY (IDCOMUNE,FK_ISTANZA) REFERENCES ISTANZE(IDCOMUNE,CODICEISTANZA);


ALTER TABLE EQUITALIA_TRACCIATI_CFG ADD CODICE_MOV_ISTANZA_A_RUOLO VARCHAR(8);

ALTER TABLE EQUITALIA_TRACCIATI_CFG MODIFY MAP_EQ_IN_SAN_AMM_COM_ONER VARCHAR(50);
ALTER TABLE EQUITALIA_TRACCIATI_CFG MODIFY MAP_EQ_IN_SP_SAN_AMM_COM_ONER VARCHAR(50);

ALTER TABLE EQUITALIA_TRACCIATI_CFG ADD DYN_2_CAMPI_DATA_VERBALE  VARCHAR(50);
ALTER TABLE EQUITALIA_TRACCIATI_CFG ADD DYN_2_CAMPI_NUMERO_VERBALE  VARCHAR(50);

ALTER TABLE MAIL_CONFIG  MODIFY LOGINPASS VARCHAR(300);
ALTER TABLE MAIL_CONFIG  MODIFY IN_LOGINPASS VARCHAR(300);


ALTER TABLE EQUITALIA_TRACCIATI_CFG ADD CODICE_REG_AUT_ORDINANZA VARCHAR(50);
ALTER TABLE EQUITALIA_TRACCIATI_CFG ADD DYN2_CAMPI_FILTRO_AMBITO  VARCHAR(50);

CREATE TABLE DECODIFICHE(
IDCOMUNE VARCHAR(6) NOT NULL
, TABELLA VARCHAR(64) NOT NULL
, CHIAVE VARCHAR(20) NOT NULL
, VALORE VARCHAR(2000) NOT NULL
, FLG_DISABILITATO DECIMAL(1,0) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE INDEX IDX_DECODIFICHE_001 ON DECODIFICHE (IDCOMUNE, TABELLA, CHIAVE);


ALTER TABLE TIPICONTESTOESPORTAZIONE  MODIFY DESCRIZIONE VARCHAR(100);

create table FO_CONSENSI_INFORMATIVI(
IDCOMUNE VARCHAR(6),
ID NUMERIC(10,0),
IDENTIFICATIVO_UTENTE VARCHAR(50),
FLAG_CONSENSO NUMERIC(1,0) DEFAULT 0,
DATA_AVVENUTO_CONSENSO DATETIME,
CONTESTO VARCHAR(50),
TESTO_CONSENSO MEDIUMTEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE FO_CONSENSI_INFORMATIVI ADD CONSTRAINT PK_FO_CONSENSI_INFORMATIVI PRIMARY KEY (IDCOMUNE, ID);
CREATE INDEX IDX_FO_CONSINFO_IDUTE ON FO_CONSENSI_INFORMATIVI (IDCOMUNE, IDENTIFICATIVO_UTENTE);


ALTER TABLE DECODIFICHE ADD RAGGRUPPAMENTO VARCHAR(20);


ALTER TABLE dyn2_campi MODIFY etichetta VARCHAR(2000);

ALTER TABLE ISTANZEPROCEDIMENTI MODIFY TIPO_ATTO VARCHAR(1000);

ALTER TABLE CONFIGURAZIONE ADD PROGRESSIVO_REGISTRI_AUT VARCHAR(35);
ALTER TABLE TIPOLOGIAREGISTRI ADD FLAG_USA_PROGR_CONF NUMERIC(1,0) DEFAULT 0;

