CREATE TABLE PAY_POS_DEB_MASSIVE(
IDCOMUNE VARCHAR2(6) NOT NULL,
ID NUMBER(9,0) NOT NULL,
FK_POSIZIONE_DEBITORIA NUMBER(9,0) NOT NULL,
ID_OPERAZIONE VARCHAR2(100) NOT NULL,
FLAG_PROCESSATA VARCHAR2(1) NOT NULL
);

ALTER TABLE PAY_POS_DEB_MASSIVE ADD CONSTRAINT PK_PAY_POS_DEB_MASSIVE PRIMARY KEY (IDCOMUNE,ID);

ALTER TABLE PAY_POS_DEB_MASSIVE ADD CONSTRAINT FK_PAYPOSDEBMASS_PAYPOS FOREIGN KEY (IDCOMUNE,FK_POSIZIONE_DEBITORIA) REFERENCES PAY_POSIZIONI_DEBITORIE(IDCOMUNE,ID);

ALTER TABLE boll_cfg_tipo ADD FLAG_CARICAM_MASSIVO NUMBER(1,0) DEFAULT 0 NOT NULL;
