ALTER TABLE PAY_REGISTRAZIONI_CONTABILI MODIFY IMPORTO NUMBER(12,2) NULL;

UPDATE ISTANZE SET DATAVALIDITA = TO_DATE(TO_CHAR(DATAVALIDITA,'DD/MM/YYYY'),'DD/MM/YYYY') WHERE DATAVALIDITA IS NOT NULL;
UPDATE I_ATTIVITA_SNAPSHOT SET DATA = TO_DATE(TO_CHAR(DATA,'DD/MM/YYYY'),'DD/MM/YYYY') WHERE DATA IS NOT NULL;

DROP INDEX PAY_POSDEB_UIDX;
CREATE INDEX PAY_POSDEB_UIDX ON PAY_POSIZIONI_DEBITORIE (IDCOMUNE, IUV);