<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://tempuri.org/" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://tempuri.org/" xmlns:intf="http://tempuri.org/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->
 <wsdl:types>
  <schema elementFormDefault="qualified" targetNamespace="http://tempuri.org/" xmlns="http://www.w3.org/2001/XMLSchema">
   <element name="InserisciProposta">
    <complexType>
     <sequence>
      <element name="PropostaIn" type="impl:PropostaIn"/>
      <element name="CodiceAmministrazione" type="xsd:string"/>
      <element name="CodiceAOO" type="xsd:string"/>
     </sequence>
    </complexType>
   </element>
   <complexType name="AllegatoIn">
    <sequence>
     <element maxOccurs="1" minOccurs="0" name="TipoFile" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="ContentType" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="Image" nillable="true" type="xsd:base64Binary"/>
     <element maxOccurs="1" minOccurs="0" name="Commento" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="IdAllegatoPrincipale" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="Schema" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="NomeAllegato" nillable="true" type="xsd:string"/>
     <element name="hash" nillable="true" type="xsd:string"/>
     <element name="tipoAllegato" nillable="true" type="xsd:string"/>
     <element name="uri" nillable="true" type="xsd:string"/>
    </sequence>
   </complexType>
   <complexType name="ArrayOfAllegatoIn">
    <sequence>
     <element maxOccurs="unbounded" minOccurs="0" name="item" type="impl:AllegatoIn"/>
    </sequence>
   </complexType>
   <complexType name="PropostaIn">
    <sequence>
     <element maxOccurs="1" minOccurs="0" name="Oggetto" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="Organo" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="Trattamento" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="Proponente" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="Relatore" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="Data" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="Classifica" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="ImmediatamenteEsecutiva" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="ACapigruppo" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="APrefetto" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="ACoReCo" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="DaPubblicare" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="Utente" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="Ruolo" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="Allegati" nillable="true" type="impl:ArrayOfAllegatoIn"/>
    </sequence>
   </complexType>
   <element name="InserisciPropostaResponse">
    <complexType>
     <sequence>
      <element name="AttoInseritoOut" type="impl:AttoInseritoOut"/>
     </sequence>
    </complexType>
   </element>
   <complexType name="AttoInseritoOut">
    <sequence>
     <element name="IdDocumento" type="xsd:int"/>
     <element maxOccurs="1" minOccurs="0" name="TipoDocumento" nillable="true" type="xsd:string"/>
     <element name="Numero" type="xsd:int"/>
     <element name="Anno" type="xsd:int"/>
     <element maxOccurs="1" minOccurs="0" name="Annullato" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="Messaggio" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="Errore" nillable="true" type="xsd:string"/>
    </sequence>
   </complexType>
   <element name="InserisciDetermina">
    <complexType>
     <sequence>
      <element name="DeterminaIn" type="impl:DeterminaIn"/>
      <element name="CodiceAmministrazione" type="xsd:string"/>
      <element name="CodiceAOO" type="xsd:string"/>
     </sequence>
    </complexType>
   </element>
   <complexType name="DeterminaIn">
    <sequence>
     <element maxOccurs="1" minOccurs="0" name="Oggetto" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="Trattamento" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="Proponente" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="Dirigente" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="DataDocumento" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="Classifica" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="DaPubblicare" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="Utente" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="Ruolo" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="Allegati" nillable="true" type="impl:ArrayOfAllegatoIn"/>
    </sequence>
   </complexType>
   <element name="InserisciDeterminaResponse">
    <complexType>
     <sequence>
      <element name="AttoInseritoOut" type="impl:AttoInseritoOut"/>
     </sequence>
    </complexType>
   </element>
   <element name="AggiungiAllegati">
    <complexType>
     <sequence>
      <element name="NuoviAllegati" type="impl:NuoviAllegati"/>
      <element name="CodiceAmministrazione" type="xsd:string"/>
      <element name="CodiceAOO" type="xsd:string"/>
     </sequence>
    </complexType>
   </element>
   <complexType name="NuoviAllegati">
    <sequence>
     <element maxOccurs="1" minOccurs="0" name="idDoc" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="annoProt" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="numProt" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="utente" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="ruolo" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="Allegati" nillable="true" type="impl:ArrayOfAllegatoIn"/>
    </sequence>
   </complexType>
   <element name="AggiungiAllegatiResponse">
    <complexType>
     <sequence>
      <element name="AggiungiAllegatiResult" type="impl:AllegatiInseritiOut"/>
     </sequence>
    </complexType>
   </element>
   <complexType name="AllegatoInseritoOut">
    <sequence>
     <element name="Serial" type="xsd:long"/>
     <element name="IDBase" type="xsd:int"/>
     <element name="Versione" type="xsd:short"/>
    </sequence>
   </complexType>
   <complexType name="ArrayOfAllegatoInseritoOut">
    <sequence>
     <element maxOccurs="unbounded" minOccurs="0" name="item" type="impl:AllegatoInseritoOut"/>
    </sequence>
   </complexType>
   <complexType name="AllegatiInseritiOut">
    <sequence>
     <element name="IdDocumento" type="xsd:int"/>
     <element maxOccurs="1" minOccurs="0" name="Allegati" nillable="true" type="impl:ArrayOfAllegatoInseritoOut"/>
     <element maxOccurs="1" minOccurs="0" name="Messaggio" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="Errore" nillable="true" type="xsd:string"/>
    </sequence>
   </complexType>
   <element name="LeggiAtto">
    <complexType>
     <sequence>
      <element name="IdDocumento" type="xsd:string"/>
      <element name="Tipo" type="xsd:string"/>
      <element name="Organo" type="xsd:string"/>
      <element name="Anno" type="xsd:string"/>
      <element name="Numero" type="xsd:string"/>
      <element name="Utente" type="xsd:string"/>
      <element name="Ruolo" type="xsd:string"/>
      <element name="CodiceAmministrazione" type="xsd:string"/>
      <element name="CodiceAOO" type="xsd:string"/>
     </sequence>
    </complexType>
   </element>
   <element name="LeggiAttoResponse">
    <complexType>
     <sequence>
      <element name="AttoOut" type="impl:AttoOut"/>
     </sequence>
    </complexType>
   </element>
   <complexType name="PropostaOut">
    <sequence>
     <element maxOccurs="1" minOccurs="0" name="Organo" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="Organo_Descrizione" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="Trattamento" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="Trattamento_Descrizione" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="Proponente" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="Proponente_Descrizione" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="Relatore" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="Relatore_Descrizione" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="ImmediatamenteEsecutiva" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="ACapigruppo" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="APrefetto" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="ACoReCo" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="DaPubblicare" nillable="true" type="xsd:string"/>
     <element name="Anno" type="xsd:short"/>
     <element name="Numero" type="xsd:int"/>
     <element name="IdentificativoDelibera" type="xsd:int"/>
    </sequence>
   </complexType>
   <complexType name="DeliberaOut">
    <sequence>
     <element maxOccurs="1" minOccurs="0" name="Organo" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="Organo_Descrizione" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="Trattamento" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="Trattamento_Descrizione" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="Proponente" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="Proponente_Descrizione" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="ImmediatamenteEsecutiva" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="ACapigruppo" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="APrefetto" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="ACoReCo" type="xsd:string"/>
     <element name="Anno" type="xsd:int"/>
     <element name="Numero" type="xsd:int"/>
     <element name="Data" nillable="true" type="xsd:dateTime"/>
     <element name="DataEsecutivita" nillable="true" type="xsd:dateTime"/>
     <element name="DataPubblicazione" nillable="true" type="xsd:dateTime"/>
     <element name="GiorniPubblicazione" type="xsd:int"/>
     <element name="GiorniEsecutivita" type="xsd:int"/>
     <element name="DataEvidenza" nillable="true" type="xsd:dateTime"/>
     <element name="DataTrascrizione" nillable="true" type="xsd:dateTime"/>
     <element name="DataRipubblicazione" nillable="true" type="xsd:dateTime"/>
     <element name="GiorniRipubblicazione" type="xsd:int"/>
     <element name="IdentificativoProposta" type="xsd:int"/>
     <element name="DataFinePubblicazione" nillable="true" type="xsd:dateTime"/>
    </sequence>
   </complexType>
   <complexType name="DeterminaOut">
    <sequence>
     <element maxOccurs="1" minOccurs="0" name="Trattamento" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="Trattamento_Descrizione" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="Proponente" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="Proponente_Descrizione" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="Dirigente" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="Dirigente_Descrizione" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="DaPubblicare" nillable="true" type="xsd:string"/>
     <element name="Data" nillable="true" type="xsd:dateTime"/>
     <element name="Anno" type="xsd:int"/>
     <element name="Numero" type="xsd:int"/>
     <element maxOccurs="1" minOccurs="0" name="NumeroRegistro" nillable="true" type="xsd:string"/>
     <element name="DataEsecutivita" nillable="true" type="xsd:dateTime"/>
     <element name="DataPubblicazione" nillable="true" type="xsd:dateTime"/>
     <element name="GiorniPubblicazione" type="xsd:int"/>
     <element name="DataFinePubblicazione" nillable="true" type="xsd:dateTime"/>
    </sequence>
   </complexType>
   <complexType name="AllegatoOut">
    <sequence>
     <element name="Serial" type="xsd:int"/>
     <element maxOccurs="1" minOccurs="0" name="TipoFile" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="ContentType" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="Image" nillable="true" type="xsd:base64Binary"/>
     <element maxOccurs="1" minOccurs="0" name="Commento" nillable="true" type="xsd:string"/>
     <element name="IDBase" type="xsd:int"/>
     <element name="Versione" type="xsd:short"/>
     <element maxOccurs="1" minOccurs="0" name="TipoAllegato" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="Schema" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="SottoEstensione" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="Firmato" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="NomeAllegato" nillable="true" type="xsd:string"/>
    </sequence>
   </complexType>
   <complexType name="ArrayOfAllegatoOut">
    <sequence>
     <element maxOccurs="unbounded" minOccurs="0" name="item" type="impl:AllegatoOut"/>
    </sequence>
   </complexType>
   <complexType name="ImpegnoOut">
    <sequence>
     <element name="AnnoImpegno" type="xsd:int"/>
     <element maxOccurs="1" minOccurs="0" name="NumeroImpegno" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="CapitoloImpegno" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="ArticoloImpegno" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="CodSiopeImpegno" nillable="true" type="xsd:string"/>
     <element name="ImportoImpegno" type="xsd:double"/>
     <element name="SoggettoImpegno" type="xsd:double"/>
    </sequence>
   </complexType>
   <complexType name="ArrayOfImpegnoOut">
    <sequence>
     <element maxOccurs="unbounded" minOccurs="0" name="item" type="impl:ImpegnoOut"/>
    </sequence>
   </complexType>
   <complexType name="AccertamentoOut">
    <sequence>
     <element name="AnnoAccertamento" type="xsd:int"/>
     <element maxOccurs="1" minOccurs="0" name="NumeroAccertamento" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="CapitoloAccertamento" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="ArticoloAccertamento" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="CodSiopeAccertamento" nillable="true" type="xsd:string"/>
     <element name="ImportoAccertamento" type="xsd:double"/>
     <element name="SoggettoAccertamento" type="xsd:double"/>
    </sequence>
   </complexType>
   <complexType name="ArrayOfAccertamentoOut">
    <sequence>
     <element maxOccurs="unbounded" minOccurs="0" name="item" type="impl:AccertamentoOut"/>
    </sequence>
   </complexType>
   <complexType name="CentriDiCostoOut">
    <sequence>
     <element maxOccurs="1" minOccurs="0" name="Tipo" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="Voce" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="CdC_provento" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="Propon_ammor" nillable="true" type="xsd:string"/>
     <element name="Importo" type="xsd:double"/>
    </sequence>
   </complexType>
   <complexType name="ArrayOfCentriDiCostoOut">
    <sequence>
     <element maxOccurs="unbounded" minOccurs="0" name="item" type="impl:CentriDiCostoOut"/>
    </sequence>
   </complexType>
   <complexType name="RegistroAssegnatoOut">
    <sequence>
     <element maxOccurs="1" minOccurs="0" name="TipoRegistro" nillable="true" type="xsd:string"/>
     <element name="AnnoRegistro" type="xsd:int"/>
     <element name="NumeroRegistro" type="xsd:int"/>
     <element maxOccurs="1" minOccurs="0" name="DataRegistro" nillable="true" type="xsd:string"/>
    </sequence>
   </complexType>
   <complexType name="ArrayOfRegistroAssegnatoOut">
    <sequence>
     <element maxOccurs="unbounded" minOccurs="0" name="item" type="impl:RegistroAssegnatoOut"/>
    </sequence>
   </complexType>
   <complexType name="CampoUtente">
    <sequence>
     <element name="nomeCampo" nillable="true" type="xsd:string"/>
     <element name="tipoCampo" nillable="true" type="xsd:string"/>
     <element name="valoreCampo" nillable="true" type="xsd:string"/>
    </sequence>
   </complexType>
   <complexType name="ArrayOfCampoUtente">
    <sequence>
     <element maxOccurs="unbounded" minOccurs="0" name="item" type="impl:CampoUtente"/>
    </sequence>
   </complexType>
   <complexType name="RecordUtente">
    <sequence>
     <element name="campi" nillable="true" type="impl:ArrayOfCampoUtente"/>
     <element name="progressivo" nillable="true" type="xsd:int"/>
    </sequence>
   </complexType>
   <complexType name="ArrayOfRecordUtente">
    <sequence>
     <element maxOccurs="unbounded" minOccurs="0" name="item" type="impl:RecordUtente"/>
    </sequence>
   </complexType>
   <complexType name="TabellaUtente">
    <sequence>
     <element name="nomeTabella" nillable="true" type="xsd:string"/>
     <element name="righe" nillable="true" type="impl:ArrayOfRecordUtente"/>
    </sequence>
   </complexType>
   <complexType name="ArrayOfTabellaUtente">
    <sequence>
     <element maxOccurs="unbounded" minOccurs="0" name="item" type="impl:TabellaUtente"/>
    </sequence>
   </complexType>
   <complexType name="AttoOut">
    <sequence>
     <element name="IdDocumento" type="xsd:int"/>
     <element maxOccurs="1" minOccurs="0" name="TipoDocumento" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="TipoDocumento_Descrizione" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="Oggetto" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="Classifica" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="Classifica_Descrizione" nillable="true" type="xsd:string"/>
     <element name="DataDocumento" nillable="true" type="xsd:dateTime"/>
     <element maxOccurs="1" minOccurs="0" name="NumeroProtocollo" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="Conservabile" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="Proposta" nillable="true" type="impl:PropostaOut"/>
     <element maxOccurs="1" minOccurs="0" name="Delibera" nillable="true" type="impl:DeliberaOut"/>
     <element maxOccurs="1" minOccurs="0" name="Determina" nillable="true" type="impl:DeterminaOut"/>
     <element maxOccurs="1" minOccurs="0" name="Allegati" nillable="true" type="impl:ArrayOfAllegatoOut"/>
     <element maxOccurs="1" minOccurs="0" name="Impegni" nillable="true" type="impl:ArrayOfImpegnoOut"/>
     <element maxOccurs="1" minOccurs="0" name="Accertamenti" nillable="true" type="impl:ArrayOfAccertamentoOut"/>
     <element maxOccurs="1" minOccurs="0" name="CentriDiCosto" nillable="true" type="impl:ArrayOfCentriDiCostoOut"/>
     <element maxOccurs="1" minOccurs="0" name="Registri" nillable="true" type="impl:ArrayOfRegistroAssegnatoOut"/>
     <element maxOccurs="1" minOccurs="0" name="Messaggio" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="Errore" nillable="true" type="xsd:string"/>
     <element name="datiUtente" nillable="true" type="impl:ArrayOfTabellaUtente"/>
    </sequence>
   </complexType>
   <element name="NumeraDetermina">
    <complexType>
     <sequence>
      <element name="IdDocumento" type="xsd:string"/>
      <element name="Utente" type="xsd:string"/>
      <element name="Ruolo" type="xsd:string"/>
      <element name="CodiceAmministrazione" type="xsd:string"/>
      <element name="CodiceAOO" type="xsd:string"/>
     </sequence>
    </complexType>
   </element>
   <element name="NumeraDeterminaResponse">
    <complexType>
     <sequence>
      <element name="NumerazioneDeterminaOut" type="impl:NumerazioneDeterminaOut"/>
     </sequence>
    </complexType>
   </element>
   <complexType name="NumerazioneDeterminaOut">
    <sequence>
     <element name="IdDocumento" type="xsd:int"/>
     <element maxOccurs="1" minOccurs="0" name="Trattamento" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="Trattamento_Descrizione" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="Dirigente" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="Dirigente_Descrizione" nillable="true" type="xsd:string"/>
     <element name="Data" nillable="true" type="xsd:dateTime"/>
     <element name="Anno" type="xsd:int"/>
     <element name="Numero" type="xsd:int"/>
     <element maxOccurs="1" minOccurs="0" name="Messaggio" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="Errore" nillable="true" type="xsd:string"/>
    </sequence>
   </complexType>
   <element name="AssegnaImpegni">
    <complexType>
     <sequence>
      <element name="ImpegniAccertamentiIn" type="impl:ImpegniAccertamentiIn"/>
      <element name="CodiceAmministrazione" type="xsd:string"/>
      <element name="CodiceAOO" type="xsd:string"/>
     </sequence>
    </complexType>
   </element>
   <complexType name="ImpegnoAccertamentoIn">
    <sequence>
     <element maxOccurs="1" minOccurs="0" name="Anno" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="Numero" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="Capitolo" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="Articolo" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="CodSiope" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="Importo" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="Soggetto" nillable="true" type="xsd:string"/>
    </sequence>
   </complexType>
   <complexType name="ArrayOfImpegnoAccertamentoIn">
    <sequence>
     <element maxOccurs="unbounded" minOccurs="0" name="item" type="impl:ImpegnoAccertamentoIn"/>
    </sequence>
   </complexType>
   <complexType name="ImpegniAccertamentiIn">
    <sequence>
     <element name="IdDocumento" type="xsd:int"/>
     <element maxOccurs="1" minOccurs="0" name="Utente" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="Ruolo" nillable="true" type="xsd:string"/>
     <element maxOccurs="1" minOccurs="0" name="ImpegniAccertamenti" nillable="true" type="impl:ArrayOfImpegnoAccertamentoIn"/>
    </sequence>
   </complexType>
   <element name="AssegnaImpegniResponse">
    <complexType>
     <sequence>
      <element name="AssegnaImpegniResult" type="xsd:string"/>
     </sequence>
    </complexType>
   </element>
   <element name="AssegnaAccertamenti">
    <complexType>
     <sequence>
      <element name="ImpegniAccertamentiIn" type="impl:ImpegniAccertamentiIn"/>
      <element name="CodiceAmministrazione" type="xsd:string"/>
      <element name="CodiceAOO" type="xsd:string"/>
     </sequence>
    </complexType>
   </element>
   <element name="AssegnaAccertamentiResponse">
    <complexType>
     <sequence>
      <element name="AssegnaAccertamentiResult" type="xsd:string"/>
     </sequence>
    </complexType>
   </element>
   <element name="AggiungiAllegatiString">
    <complexType>
     <sequence>
      <element name="NuoviAllegatiStr" type="xsd:string"/>
      <element name="CodiceAmministrazione" type="xsd:string"/>
      <element name="CodiceAOO" type="xsd:string"/>
     </sequence>
    </complexType>
   </element>
   <element name="AggiungiAllegatiStringResponse">
    <complexType>
     <sequence>
      <element name="AggiungiAllegatiStringResult" type="xsd:string"/>
     </sequence>
    </complexType>
   </element>
   <element name="InserisciDeterminaString">
    <complexType>
     <sequence>
      <element name="DeterminaInStr" type="xsd:string"/>
      <element name="CodiceAmministrazione" type="xsd:string"/>
      <element name="CodiceAOO" type="xsd:string"/>
     </sequence>
    </complexType>
   </element>
   <element name="InserisciDeterminaStringResponse">
    <complexType>
     <sequence>
      <element name="InserisciDeterminaStringResult" type="xsd:string"/>
     </sequence>
    </complexType>
   </element>
   <element name="InserisciPropostaString">
    <complexType>
     <sequence>
      <element name="PropostaInStr" type="xsd:string"/>
      <element name="CodiceAmministrazione" type="xsd:string"/>
      <element name="CodiceAOO" type="xsd:string"/>
     </sequence>
    </complexType>
   </element>
   <element name="InserisciPropostaStringResponse">
    <complexType>
     <sequence>
      <element name="InserisciPropostaStringResult" type="xsd:string"/>
     </sequence>
    </complexType>
   </element>
   <element name="LeggiAttoString">
    <complexType>
     <sequence>
      <element name="IdDocumento" type="xsd:string"/>
      <element name="Tipo" type="xsd:string"/>
      <element name="Organo" type="xsd:string"/>
      <element name="Anno" type="xsd:string"/>
      <element name="Numero" type="xsd:string"/>
      <element name="Utente" type="xsd:string"/>
      <element name="Ruolo" type="xsd:string"/>
      <element name="CodiceAmministrazione" type="xsd:string"/>
      <element name="CodiceAOO" type="xsd:string"/>
     </sequence>
    </complexType>
   </element>
   <element name="LeggiAttoStringResponse">
    <complexType>
     <sequence>
      <element name="LeggiAttoStringResult" type="xsd:string"/>
     </sequence>
    </complexType>
   </element>
   <element name="NumeraDeterminaString">
    <complexType>
     <sequence>
      <element name="IdDocumento" type="xsd:string"/>
      <element name="Utente" type="xsd:string"/>
      <element name="Ruolo" type="xsd:string"/>
      <element name="CodiceAmministrazione" type="xsd:string"/>
      <element name="CodiceAOO" type="xsd:string"/>
      <element name="CodiceSettore" type="xsd:string"/>
     </sequence>
    </complexType>
   </element>
   <element name="NumeraDeterminaStringResponse">
    <complexType>
     <sequence>
      <element name="NumeraDeterminaStringResult" type="xsd:string"/>
     </sequence>
    </complexType>
   </element>
   <element name="LeggiAttoPlus">
    <complexType>
     <sequence>
      <element name="FiltroAtto" type="xsd:string"/>
      <element name="CodiceAmministrazione" type="xsd:string"/>
      <element name="CodiceAOO" type="xsd:string"/>
     </sequence>
    </complexType>
   </element>
   <element name="LeggiAttoPlusResponse">
    <complexType>
     <sequence>
      <element name="LeggiAttoPlusResult" type="xsd:string"/>
     </sequence>
    </complexType>
   </element>
  </schema>
 </wsdl:types>

   <wsdl:message name="InserisciDeterminaRequest">

      <wsdl:part element="impl:InserisciDetermina" name="parameters"/>

   </wsdl:message>

   <wsdl:message name="LeggiAttoResponse">

      <wsdl:part element="impl:LeggiAttoResponse" name="parameters"/>

   </wsdl:message>

   <wsdl:message name="AssegnaImpegniRequest">

      <wsdl:part element="impl:AssegnaImpegni" name="parameters"/>

   </wsdl:message>

   <wsdl:message name="AggiungiAllegatiStringRequest">

      <wsdl:part element="impl:AggiungiAllegatiString" name="parameters"/>

   </wsdl:message>

   <wsdl:message name="AggiungiAllegatiStringResponse">

      <wsdl:part element="impl:AggiungiAllegatiStringResponse" name="parameters"/>

   </wsdl:message>

   <wsdl:message name="NumeraDeterminaResponse">

      <wsdl:part element="impl:NumeraDeterminaResponse" name="parameters"/>

   </wsdl:message>

   <wsdl:message name="InserisciDeterminaStringResponse">

      <wsdl:part element="impl:InserisciDeterminaStringResponse" name="parameters"/>

   </wsdl:message>

   <wsdl:message name="InserisciPropostaStringResponse">

      <wsdl:part element="impl:InserisciPropostaStringResponse" name="parameters"/>

   </wsdl:message>

   <wsdl:message name="AggiungiAllegatiRequest">

      <wsdl:part element="impl:AggiungiAllegati" name="parameters"/>

   </wsdl:message>

   <wsdl:message name="LeggiAttoPlusRequest">

      <wsdl:part element="impl:LeggiAttoPlus" name="parameters"/>

   </wsdl:message>

   <wsdl:message name="LeggiAttoRequest">

      <wsdl:part element="impl:LeggiAtto" name="parameters"/>

   </wsdl:message>

   <wsdl:message name="InserisciPropostaResponse">

      <wsdl:part element="impl:InserisciPropostaResponse" name="parameters"/>

   </wsdl:message>

   <wsdl:message name="AssegnaAccertamentiRequest">

      <wsdl:part element="impl:AssegnaAccertamenti" name="parameters"/>

   </wsdl:message>

   <wsdl:message name="LeggiAttoStringResponse">

      <wsdl:part element="impl:LeggiAttoStringResponse" name="parameters"/>

   </wsdl:message>

   <wsdl:message name="InserisciDeterminaStringRequest">

      <wsdl:part element="impl:InserisciDeterminaString" name="parameters"/>

   </wsdl:message>

   <wsdl:message name="NumeraDeterminaStringResponse">

      <wsdl:part element="impl:NumeraDeterminaStringResponse" name="parameters"/>

   </wsdl:message>

   <wsdl:message name="NumeraDeterminaRequest">

      <wsdl:part element="impl:NumeraDetermina" name="parameters"/>

   </wsdl:message>

   <wsdl:message name="InserisciPropostaRequest">

      <wsdl:part element="impl:InserisciProposta" name="parameters"/>

   </wsdl:message>

   <wsdl:message name="LeggiAttoStringRequest">

      <wsdl:part element="impl:LeggiAttoString" name="parameters"/>

   </wsdl:message>

   <wsdl:message name="InserisciPropostaStringRequest">

      <wsdl:part element="impl:InserisciPropostaString" name="parameters"/>

   </wsdl:message>

   <wsdl:message name="InserisciDeterminaResponse">

      <wsdl:part element="impl:InserisciDeterminaResponse" name="parameters"/>

   </wsdl:message>

   <wsdl:message name="NumeraDeterminaStringRequest">

      <wsdl:part element="impl:NumeraDeterminaString" name="parameters"/>

   </wsdl:message>

   <wsdl:message name="AssegnaAccertamentiResponse">

      <wsdl:part element="impl:AssegnaAccertamentiResponse" name="parameters"/>

   </wsdl:message>

   <wsdl:message name="LeggiAttoPlusResponse">

      <wsdl:part element="impl:LeggiAttoPlusResponse" name="parameters"/>

   </wsdl:message>

   <wsdl:message name="AggiungiAllegatiResponse">

      <wsdl:part element="impl:AggiungiAllegatiResponse" name="parameters"/>

   </wsdl:message>

   <wsdl:message name="AssegnaImpegniResponse">

      <wsdl:part element="impl:AssegnaImpegniResponse" name="parameters"/>

   </wsdl:message>

   <wsdl:portType name="WSattiSoap">

      <wsdl:operation name="InserisciProposta">

         <wsdl:input message="impl:InserisciPropostaRequest" name="InserisciPropostaRequest"/>

         <wsdl:output message="impl:InserisciPropostaResponse" name="InserisciPropostaResponse"/>

      </wsdl:operation>

      <wsdl:operation name="InserisciDetermina">

         <wsdl:input message="impl:InserisciDeterminaRequest" name="InserisciDeterminaRequest"/>

         <wsdl:output message="impl:InserisciDeterminaResponse" name="InserisciDeterminaResponse"/>

      </wsdl:operation>

      <wsdl:operation name="AggiungiAllegati">

         <wsdl:input message="impl:AggiungiAllegatiRequest" name="AggiungiAllegatiRequest"/>

         <wsdl:output message="impl:AggiungiAllegatiResponse" name="AggiungiAllegatiResponse"/>

      </wsdl:operation>

      <wsdl:operation name="LeggiAtto">

         <wsdl:input message="impl:LeggiAttoRequest" name="LeggiAttoRequest"/>

         <wsdl:output message="impl:LeggiAttoResponse" name="LeggiAttoResponse"/>

      </wsdl:operation>

      <wsdl:operation name="NumeraDetermina">

         <wsdl:input message="impl:NumeraDeterminaRequest" name="NumeraDeterminaRequest"/>

         <wsdl:output message="impl:NumeraDeterminaResponse" name="NumeraDeterminaResponse"/>

      </wsdl:operation>

      <wsdl:operation name="AssegnaImpegni">

         <wsdl:input message="impl:AssegnaImpegniRequest" name="AssegnaImpegniRequest"/>

         <wsdl:output message="impl:AssegnaImpegniResponse" name="AssegnaImpegniResponse"/>

      </wsdl:operation>

      <wsdl:operation name="AssegnaAccertamenti">

         <wsdl:input message="impl:AssegnaAccertamentiRequest" name="AssegnaAccertamentiRequest"/>

         <wsdl:output message="impl:AssegnaAccertamentiResponse" name="AssegnaAccertamentiResponse"/>

      </wsdl:operation>

      <wsdl:operation name="AggiungiAllegatiString">

         <wsdl:input message="impl:AggiungiAllegatiStringRequest" name="AggiungiAllegatiStringRequest"/>

         <wsdl:output message="impl:AggiungiAllegatiStringResponse" name="AggiungiAllegatiStringResponse"/>

      </wsdl:operation>

      <wsdl:operation name="InserisciDeterminaString">

         <wsdl:input message="impl:InserisciDeterminaStringRequest" name="InserisciDeterminaStringRequest"/>

         <wsdl:output message="impl:InserisciDeterminaStringResponse" name="InserisciDeterminaStringResponse"/>

      </wsdl:operation>

      <wsdl:operation name="InserisciPropostaString">

         <wsdl:input message="impl:InserisciPropostaStringRequest" name="InserisciPropostaStringRequest"/>

         <wsdl:output message="impl:InserisciPropostaStringResponse" name="InserisciPropostaStringResponse"/>

      </wsdl:operation>

      <wsdl:operation name="LeggiAttoString">

         <wsdl:input message="impl:LeggiAttoStringRequest" name="LeggiAttoStringRequest"/>

         <wsdl:output message="impl:LeggiAttoStringResponse" name="LeggiAttoStringResponse"/>

      </wsdl:operation>

      <wsdl:operation name="NumeraDeterminaString">

         <wsdl:input message="impl:NumeraDeterminaStringRequest" name="NumeraDeterminaStringRequest"/>

         <wsdl:output message="impl:NumeraDeterminaStringResponse" name="NumeraDeterminaStringResponse"/>

      </wsdl:operation>

      <wsdl:operation name="LeggiAttoPlus">

         <wsdl:input message="impl:LeggiAttoPlusRequest" name="LeggiAttoPlusRequest"/>

         <wsdl:output message="impl:LeggiAttoPlusResponse" name="LeggiAttoPlusResponse"/>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="WSattiSoapSoapBinding" type="impl:WSattiSoap">

      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="InserisciProposta">

         <wsdlsoap:operation soapAction="http://tempuri.org/InserisciProposta"/>

         <wsdl:input name="InserisciPropostaRequest">

            <wsdlsoap:body use="literal"/>

         </wsdl:input>

         <wsdl:output name="InserisciPropostaResponse">

            <wsdlsoap:body use="literal"/>

         </wsdl:output>

      </wsdl:operation>

      <wsdl:operation name="InserisciDetermina">

         <wsdlsoap:operation soapAction="http://tempuri.org/InserisciDetermina"/>

         <wsdl:input name="InserisciDeterminaRequest">

            <wsdlsoap:body use="literal"/>

         </wsdl:input>

         <wsdl:output name="InserisciDeterminaResponse">

            <wsdlsoap:body use="literal"/>

         </wsdl:output>

      </wsdl:operation>

      <wsdl:operation name="AggiungiAllegati">

         <wsdlsoap:operation soapAction="http://tempuri.org/AggiungiAllegati"/>

         <wsdl:input name="AggiungiAllegatiRequest">

            <wsdlsoap:body use="literal"/>

         </wsdl:input>

         <wsdl:output name="AggiungiAllegatiResponse">

            <wsdlsoap:body use="literal"/>

         </wsdl:output>

      </wsdl:operation>

      <wsdl:operation name="LeggiAtto">

         <wsdlsoap:operation soapAction="http://tempuri.org/LeggiAtto"/>

         <wsdl:input name="LeggiAttoRequest">

            <wsdlsoap:body use="literal"/>

         </wsdl:input>

         <wsdl:output name="LeggiAttoResponse">

            <wsdlsoap:body use="literal"/>

         </wsdl:output>

      </wsdl:operation>

      <wsdl:operation name="NumeraDetermina">

         <wsdlsoap:operation soapAction="http://tempuri.org/NumeraDetermina"/>

         <wsdl:input name="NumeraDeterminaRequest">

            <wsdlsoap:body use="literal"/>

         </wsdl:input>

         <wsdl:output name="NumeraDeterminaResponse">

            <wsdlsoap:body use="literal"/>

         </wsdl:output>

      </wsdl:operation>

      <wsdl:operation name="AssegnaImpegni">

         <wsdlsoap:operation soapAction="http://tempuri.org/AssegnaImpegni"/>

         <wsdl:input name="AssegnaImpegniRequest">

            <wsdlsoap:body use="literal"/>

         </wsdl:input>

         <wsdl:output name="AssegnaImpegniResponse">

            <wsdlsoap:body use="literal"/>

         </wsdl:output>

      </wsdl:operation>

      <wsdl:operation name="AssegnaAccertamenti">

         <wsdlsoap:operation soapAction="http://tempuri.org/AssegnaAccertamenti"/>

         <wsdl:input name="AssegnaAccertamentiRequest">

            <wsdlsoap:body use="literal"/>

         </wsdl:input>

         <wsdl:output name="AssegnaAccertamentiResponse">

            <wsdlsoap:body use="literal"/>

         </wsdl:output>

      </wsdl:operation>

      <wsdl:operation name="AggiungiAllegatiString">

         <wsdlsoap:operation soapAction="http://tempuri.org/AggiungiAllegatiString"/>

         <wsdl:input name="AggiungiAllegatiStringRequest">

            <wsdlsoap:body use="literal"/>

         </wsdl:input>

         <wsdl:output name="AggiungiAllegatiStringResponse">

            <wsdlsoap:body use="literal"/>

         </wsdl:output>

      </wsdl:operation>

      <wsdl:operation name="InserisciDeterminaString">

         <wsdlsoap:operation soapAction="http://tempuri.org/InserisciDeterminaString"/>

         <wsdl:input name="InserisciDeterminaStringRequest">

            <wsdlsoap:body use="literal"/>

         </wsdl:input>

         <wsdl:output name="InserisciDeterminaStringResponse">

            <wsdlsoap:body use="literal"/>

         </wsdl:output>

      </wsdl:operation>

      <wsdl:operation name="InserisciPropostaString">

         <wsdlsoap:operation soapAction="http://tempuri.org/InserisciPropostaString"/>

         <wsdl:input name="InserisciPropostaStringRequest">

            <wsdlsoap:body use="literal"/>

         </wsdl:input>

         <wsdl:output name="InserisciPropostaStringResponse">

            <wsdlsoap:body use="literal"/>

         </wsdl:output>

      </wsdl:operation>

      <wsdl:operation name="LeggiAttoString">

         <wsdlsoap:operation soapAction="http://tempuri.org/LeggiAttoString"/>

         <wsdl:input name="LeggiAttoStringRequest">

            <wsdlsoap:body use="literal"/>

         </wsdl:input>

         <wsdl:output name="LeggiAttoStringResponse">

            <wsdlsoap:body use="literal"/>

         </wsdl:output>

      </wsdl:operation>

      <wsdl:operation name="NumeraDeterminaString">

         <wsdlsoap:operation soapAction="http://tempuri.org/NumeraDeterminaString"/>

         <wsdl:input name="NumeraDeterminaStringRequest">

            <wsdlsoap:body use="literal"/>

         </wsdl:input>

         <wsdl:output name="NumeraDeterminaStringResponse">

            <wsdlsoap:body use="literal"/>

         </wsdl:output>

      </wsdl:operation>

      <wsdl:operation name="LeggiAttoPlus">

         <wsdlsoap:operation soapAction="http://tempuri.org/LeggiAttoPlus"/>

         <wsdl:input name="LeggiAttoPlusRequest">

            <wsdlsoap:body use="literal"/>

         </wsdl:input>

         <wsdl:output name="LeggiAttoPlusResponse">

            <wsdlsoap:body use="literal"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="WSatti">

      <wsdl:port binding="impl:WSattiSoapSoapBinding" name="WSattiSoap">

         <wsdlsoap:address location="http://iridetest2k3:50080/client/services/WSattiSoap"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
