ALTER TABLE CONFIGURAZIONE_CALCOLI ADD VERSIONE NUMBER(2,0) NULL;
UPDATE CONFIGURAZIONE_CALCOLI SET VERSIONE = 1 WHERE VERSIONE IS NULL;
ALTER TABLE CONFIGURAZIONE_CALCOLI MODIFY VERSIONE NUMBER(2,0) NOT NULL;

ALTER TABLE tipimovimento_rabbit DROP CONSTRAINT FK_MAILTIPO_TIPIMOVRABBIT;
ALTER TABLE tipimovimento_rabbit DROP CONSTRAINT FK_TIPIMOV_TIPIMOVRABBIT;
alter table tipimovimento_rabbit drop primary key;

alter table tipimovimento_rabbit add constraint pk_tipimov_rabbit PRIMARY KEY(idcomune,fk_tipimovimento,topic);
alter table tipimovimento_rabbit add constraint FK_MAILTIPO_TIPIMOVRABBIT FOREIGN KEY (IDCOMUNE, fk_mailtipo) REFERENCES mailtipo (IDCOMUNE, CODICEMAIL);
alter table tipimovimento_rabbit add constraint FK_TIPIMOV_TIPIMOVRABBIT FOREIGN KEY (IDCOMUNE, fk_tipimovimento) REFERENCES tipimovimento (IDCOMUNE, TIPOMOVIMENTO);

ALTER TABLE tipisoggetto ADD flag_riceve_notifiche NUMBER(1,0);
UPDATE tipisoggetto SET flag_riceve_notifiche = 0 WHERE flag_riceve_notifiche IS NULL;
ALTER TABLE tipisoggetto MODIFY flag_riceve_notifiche NUMBER(1,0) DEFAULT 0 NOT NULL;


ALTER TABLE APP_IO_CODA MODIFY STATO_MESSAGGIO VARCHAR2(500); 

alter table tipimovimento_rabbit modify fk_mailtipo NUMBER(4,0) null;

alter table statiistanza add flag_filtrabile_front number(1,0);

CREATE TABLE MOVIMENTI_METADATI(IDCOMUNE VARCHAR2(6 CHAR) NOT NULL, CODICEMOVIMENTO DECIMAL(8,0) NOT NULL, CHIAVE VARCHAR2(60 CHAR) NOT NULL, VALORE VARCHAR2(500 CHAR) NOT NULL );
ALTER TABLE MOVIMENTI_METADATI ADD CONSTRAINT PK_MOVIMENTI_METADATI PRIMARY KEY(IDCOMUNE,CODICEMOVIMENTO,CHIAVE);
ALTER TABLE MOVIMENTI_METADATI ADD CONSTRAINT FK_MOVIMENTIMETADATI_001 FOREIGN KEY(IDCOMUNE,CODICEMOVIMENTO) REFERENCES MOVIMENTI(IDCOMUNE,CODICEMOVIMENTO);
CREATE INDEX IDX_MOVIMENTIMETADATI_001 ON MOVIMENTI_METADATI(IDCOMUNE,CODICEMOVIMENTO);
CREATE TABLE SCADENZE_ELIMINATE(IDCOMUNE VARCHAR2(6 CHAR) NOT NULL, UUID VARCHAR2(60 CHAR) NOT NULL);
ALTER TABLE SCADENZE_ELIMINATE ADD CONSTRAINT PK_SCADENZEELIMINATE PRIMARY KEY(IDCOMUNE,UUID);

CREATE TABLE MESSAGGI_RABBIT_MOVIMENTI(IDCOMUNE VARCHAR2(6 CHAR) NOT NULL, FK_MSGRABBIT_GUID VARCHAR2(40 CHAR) NOT NULL, UUID_MOVIMENTO VARCHAR2(60 CHAR) NOT NULL);
ALTER TABLE MESSAGGI_RABBIT_MOVIMENTI ADD CONSTRAINT PK_MSG_RABBIT_MOVIMENTI PRIMARY KEY (IDCOMUNE,FK_MSGRABBIT_GUID, UUID_MOVIMENTO);
ALTER TABLE MESSAGGI_RABBIT_MOVIMENTI ADD CONSTRAINT FK_MSGRABBITMOV_MSGRABBIT FOREIGN KEY (IDCOMUNE,FK_MSGRABBIT_GUID) REFERENCES MESSAGGI_RABBIT(IDCOMUNE,GUID);

CREATE TABLE MESSAGGI_RABBIT_ISTANZE (IDCOMUNE VARCHAR2(6 CHAR) NOT NULL, FK_MSGRABBIT_GUID VARCHAR2(40 CHAR) NOT NULL, UUID_ISTANZA VARCHAR2(60 CHAR) NOT NULL);
ALTER TABLE MESSAGGI_RABBIT_ISTANZE ADD CONSTRAINT PK_MSGRABBIT_ISTANZE  PRIMARY KEY (IDCOMUNE,FK_MSGRABBIT_GUID, UUID_ISTANZA);
ALTER TABLE MESSAGGI_RABBIT_ISTANZE ADD CONSTRAINT FK_MSGRABBIT_MSG_RABBIT FOREIGN KEY (IDCOMUNE,FK_MSGRABBIT_GUID) REFERENCES MESSAGGI_RABBIT (IDCOMUNE,GUID);



CREATE TABLE MESSAGGI_RABBIT_PAGAMENTI (
  IDCOMUNE VARCHAR2(6 CHAR) NOT NULL,
  FK_MSGRABBIT_GUID VARCHAR2(40 CHAR) NOT NULL,
  UUID_POSIZIONE_DEB VARCHAR2(60 CHAR) NOT NULL
) ;


ALTER TABLE MESSAGGI_RABBIT_PAGAMENTI ADD CONSTRAINT PK_MESSAGGI_RABBIT_PAGAMENTI PRIMARY KEY (IDCOMUNE,FK_MSGRABBIT_GUID,UUID_POSIZIONE_DEB);
ALTER TABLE MESSAGGI_RABBIT_PAGAMENTI ADD CONSTRAINT FK_MSGRABBITPAG_MSGRABBIT FOREIGN KEY (IDCOMUNE, FK_MSGRABBIT_GUID) REFERENCES MESSAGGI_RABBIT (IDCOMUNE, GUID);
 

