ALTER TABLE INVENTARIOPROC_ENDO ADD FK_CID_IDCOMUNE VARCHAR(6) NOT NULL;

ALTER TABLE INVENTARIOPROC_ENDO ADD CONSTRAINT FK_INVPROCENDO_INVPROC_D FOREIGN KEY (FK_CID_IDCOMUNE, CODICEINVENTARIO_D) REFERENCES INVENTARIOPROCEDIMENTI (IDCOMUNE, CODICEINVENTARIO); 

ALTER TABLE ALBEROPROC_ARENDO ADD FK_AP_IDCOMUNE VARCHAR(6);
ALTER TABLE ALBEROPROC_ARENDO DROP FOREIGN KEY ALBEROPROC_ARENDO_ALBEROP_FK1;
UPDATE ALBEROPROC_ARENDO SET FK_AP_IDCOMUNE=IDCOMUNE WHERE FK_AP_IDCOMUNE IS NULL;
ALTER TABLE ALBEROPROC_ARENDO ADD CONSTRAINT ALBEROPROC_ARENDO_ALBEROP_FK1 FOREIGN KEY (FK_AP_IDCOMUNE, FK_SCID) REFERENCES ALBEROPROC(IDCOMUNE,SC_ID);

ALTER TABLE ALLEGATI DROP FOREIGN KEY  FK_ALLEGATI_INVT_PROC;
ALTER TABLE ALLEGATI ADD FK_CI_IDCOMUNE VARCHAR(6);
UPDATE ALLEGATI SET FK_CI_IDCOMUNE=IDCOMUNE WHERE FK_CI_IDCOMUNE IS NULL;
DROP INDEX FK_ALLEGATI_INVT_PROC ON allegati;
ALTER TABLE ALLEGATI ADD CONSTRAINT FK_ALLEGATI_INVT_PROC FOREIGN KEY (FK_CI_IDCOMUNE, CODICEINVENTARIO) REFERENCES INVENTARIOPROCEDIMENTI (IDCOMUNE, CODICEINVENTARIO);