UPDATE verticalizzazioniparametribase SET descrizione = 'Questo parametro va utilizzato solamente nel caso in cui nel parametro OPERATORE sia specificato un valore segnalibro, ossia un valore che inizia e termina con il carattere -$-, solo in questo caso questo parametro sarà preso in considerazione e il suo valore sarà cercato tra i codici operatori di SIGEPRO (quindi va passato necessariamente un valore numerico) che, una volta trovato, andrà a valorizzare il dato da passare al web service tramite le regole descritte appunto nel parametro OPERATORE che indicano come individuarne il campo esatto tramite il segnalibro' WHERE modulo = 'PROTOCOLLO_ATTIVO' AND parametro = 'CODOPERATOREFO';
INSERT INTO verticalizzazionibase(modulo, descrizione) VALUES('WS_LOGIN','Se attivata permette di sovrascrivere la User Id con la quale eseguire la login durante le chiamate via web service');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) VALUES('WS_LOGIN','USERID_OPERATORE','User Id dell''operatore');

DELETE FROM MASTERKEY WHERE TABLENAME='TIPISOGGETTO' AND COLUMNNAME='CODICETIPOSOGGETTO';

INSERT INTO VERTICALIZZAZIONIBASE (MODULO, DESCRIZIONE) VALUES ('PAYER_ADAPTER', 'Contiene i parametri usati dal componente PAYER_ADAPTER per l''integrazione di Back Office con PayER (Sistema dei pagamenti Regione Emilia Romagna)');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PAYER_ADAPTER', 'CODICE_UTENTE', 'Indica il valore che viene inviato da PayER nel tag Request_ResponseBase.codiceUtente. Serve per recuperare il modulo software per filtrare gli oneri (nel caso non venga specificato anche il parametro di verticalizzazione PAYER_ADAPTER.CODICE_UFFICIO)');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PAYER_ADAPTER', 'CODICE_UFFICIO', 'Indica il valore che viene inviato da PayER nel tag Request_ResponseBase.codiceUfficio. Serve per recuperare il modulo software per filtrare gli oneri (se questo valore non è specificato (oppure è uguale a TT) allora il software viene recuperato da PAYER_ADAPTER.CODICE_UTENTE e se questo è nullo o uguale a TT allora le scadenze vengono estratte per tutti i moduli)');	
	
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PAYER_ADAPTER', 'NUM_CCACCREDITOPAGAMENTO', 'Contiene il valore che viene inviato dal PAYER_ADAPTER alla richiesta di RecuperaDatiBollettinoRequest. Rappresenta il valore del Conto Corrente di accreditamento che verrà presentato al cittadino. Il valore viene inserito in RecuperaDatiBollettinoResponse.numeroCCAccreditoPagamento. Se configurato un valore per software allora il software sarà recuperato secondo la logica di quanto scritto in PAYER_ADAPTER.CODICE_UFFICIO altrimenti sarà preso il valore del software TT. In caso di mancata valorizzazione di questo parametro PAYER_ADAPTER lancera'' un errore alla richiesta da parte di PayER');

UPDATE CITTADINANZA SET FLG_PAESE_COMUNITARIO = 1 WHERE CODICE = 8440;

INSERT INTO COMUNIASSOCIAZIONI(CODICEASSOCIAZIONE,ASSOCIAZIONE) VALUES ('AL081','UNIONE DEI COMUNI PIAN DEL BRUSCOLO');
INSERT INTO COMUNIASSOCIAZIONI(CODICEASSOCIAZIONE,ASSOCIAZIONE) VALUES ('AE730','UNIONE DEI COMUNI BASSA ROMAGNA');
INSERT INTO COMUNIASSOCIAZIONI(CODICEASSOCIAZIONE,ASSOCIAZIONE) VALUES ('AF715','UNIONE DELLA VAL CONCA');
INSERT INTO COMUNIASSOCIAZIONI(CODICEASSOCIAZIONE,ASSOCIAZIONE) VALUES ('AF401','UNIONE DEI COMUNI DI OSTRA E RIPE');


INSERT INTO FO_ARJ_STEPS_BASE (NOME_STEP, LINK_FUNZIONE, TITOLO, DESCRIZIONE,FLAG_OBBLIGATORIO, DIPENDE_DA_STEP, INCOMPATIBILE_CON_STEP, ORDINE_DEFAULT) VALUES ('BENVENUTO','../nuovaistanza/benvenuto.htm','Benvenuto','Le pagine che seguono rappresentano il percorso guidato per la presentazione on line di una istanza.<br />Il percorso per inviare la pratica on line è composto da una serie di step (schede).<br />In fondo a destra si trova la numerazione delle pagine e in nero viene evidenziato lo step che si sta compilando.',0,NULL,NULL, 1);

INSERT INTO FO_ARJ_STEPS_BASE (NOME_STEP, LINK_FUNZIONE, TITOLO, DESCRIZIONE,FLAG_OBBLIGATORIO, DIPENDE_DA_STEP, INCOMPATIBILE_CON_STEP, ORDINE_DEFAULT) VALUES ('INFORMATIVA_PRIVACY','../nuovaistanza/informativa.htm','Informativa privacy','INFORMATIVA AI SENSI DELL''ART. 13 DEL DECRETO LEGISLATIVO N. 196/2003, "CODICE IN MATERIA DI PROTEZIONE DEI DATI PERSONALI"
 
Si informa, ai sensi dell''art. 13 del D. Lgs. n. 196 del 30 giugno 2003 ("Codice in materia di protezione dei dati personali"), che il Comune di Ponteratto, in qualità di "Titolare" del trattamento, è tenuto a fornirle informazioni in merito all''utilizzo dei suoi dati personali.
Per trattamento si intende qualunque operazione o complesso di operazioni concernenti "la raccolta, la registrazione, l''organizzazione, la conservazione, la consultazione, l''elaborazione, la modificazione, la selezione, l''estrazione, il raffronto, l''utilizzo,l''interconnessione, il blocco, la comunicazione, la diffusione, la cancellazione e la distruzione di dati, anche se non registrati in una banca dati".
La raccolta dei suoi dati personali viene effettuata registrando i dati da lei stesso forniti, in qualità di interessato, al momento della iscrizione al sistema di autenticazione federato.
 
I dati personali sono trattati per le finalità previste dal procedimento. Per garantire l''efficienza del servizio la informiamo inoltre che i dati potrebbero essere utilizzati per effettuare prove tecniche e di verifica.
In relazione alle finalità descritte, il trattamento dei dati personali avviene mediante strumenti manuali, informatici e telematici con logiche strettamente correlate alle finalità sopra evidenziate e, comunque, in modo da garantire la sicurezza e la riservatezza dei dati stessi. Adempiute le finalità prefissate, i dati verranno cancellati o trasformati in forma anonima.
 
Ai sensi dell''art. 13, 1° comma lett. b) e c), si evidenzia che il trattamento dei dati da parte del Comune è essenziale per l''adempimento degli obblighi di legge e che, pertanto, il mancato conferimento di tali dati impedisce l''utilizzo del servizio offerto on line.
I suoi dati personali potranno essere conosciuti esclusivamente dagli operatori dell''ufficio del SUAP del Comune di Ponteratto e da tutti gli operatori degli altri uffici comunali interessati dal procedimento, individuati quali Incaricati del trattamento.
Si precisa inoltre che i dati verranno comunicati a terzi esclusivamente in adempimento di specifici obblighi di legge, ovvero qualora tale comunicazione risulti necessaria o funzionale alla gestione del servizio, previa designazione in qualità di Responsabili del trattamento e garantendo il medesimo livello di protezione.
 
Si informa, infine, che l''art. 7 del Decreto Legislativo n. 196/2003, riportato di seguito integralmente, attribuisce all''interessato specifici diritti a garanzia della corretta acquisizione e del corretto utilizzo dei dati trattati ed in particolare:
L''interessato ha diritto di ottenere la conferma dell''esistenza o meno di dati personali che lo riguardano, anche se non ancora registrati, e la loro comunicazione in forma intelligibile.L''interessato ha diritto di ottenere l''indicazione: 
dell''origine dei dati personali; 
delle finalità e modalità del trattamento; 
della logica applicata in caso di trattamento effettuato con l''ausilio di strumenti elettronici; 
degli estremi identificativi del titolare, dei responsabili e del rappresentante designato ai sensi dell''articolo 5, comma 2; 
dei soggetti o delle categorie di soggetti ai quali i dati personali possono essere comunicati o che possono venirne a conoscenza in qualità di rappresentante designato nel territorio dello Stato, di responsabili o incaricati. 
L''interessato ha diritto di ottenere:l''aggiornamento, la rettificazione ovvero, quando vi ha interesse, l''integrazione dei dati; 
la cancellazione, la trasformazione in forma anonima o il blocco dei dati trattati in violazione di legge, compresi quelli di cui non è necessaria la conservazione in relazione agli scopi per i quali i dati sono stati raccolti o successivamente trattati; ',0,NULL,NULL,2);

INSERT INTO FO_ARJ_STEPS_BASE (NOME_STEP, LINK_FUNZIONE, TITOLO, DESCRIZIONE,FLAG_OBBLIGATORIO, DIPENDE_DA_STEP, INCOMPATIBILE_CON_STEP, ORDINE_DEFAULT) VALUES ('INSERIMENTO_ANAGRAFICHE','../anagrafe/richiedente.htm','Inserimento anagrafiche','In questa scheda vanno inseriti tutti i soggetti, persone fisiche e giuridiche, coinvolti nella pratica che si sta presentando. I soggetti possono essere l''interessato, l''azienda coinvolta, l''intermediario ...',0,NULL,NULL,3);

INSERT INTO FO_ARJ_STEPS_BASE (NOME_STEP, LINK_FUNZIONE, TITOLO, DESCRIZIONE,FLAG_OBBLIGATORIO, DIPENDE_DA_STEP, INCOMPATIBILE_CON_STEP, ORDINE_DEFAULT) VALUES ('LOCALIZZAZIONE','../nuovaistanza/localizzazione.htm','Localizzazione','È possibile in questa sezione inserire nel campo "Indirizzo" la localizzazione dell''intervento. <br />Selezionare un indirizzo compreso nello stradario comunale dopo aver digitato nel campo "Denominazione" almeno due lettere della localizzazione, quindi completare l''indirizzo indicando il civico ed eventuali note.<br />Se l''intervento ricade in una zona ancora non censita digitare "NON DEFINITO" nel campo "Denominazione" e nel campo "Note" immettere una localizzazione di massima (frazione, zona, etc.)',0,NULL,NULL,4);
				
INSERT INTO FO_ARJ_STEPS_BASE (NOME_STEP, LINK_FUNZIONE, TITOLO, DESCRIZIONE,FLAG_OBBLIGATORIO, DIPENDE_DA_STEP, INCOMPATIBILE_CON_STEP, ORDINE_DEFAULT) VALUES ('INTERVENTO','../nuovaistanza/intervento.htm','Intervento','In questa sezione è possibile individuare l''attività della propria azienda secondo la classificazione adottata dallo sportello unico del comune',0,NULL,NULL,5);
					
INSERT INTO FO_ARJ_STEPS_BASE (NOME_STEP, LINK_FUNZIONE, TITOLO, DESCRIZIONE,FLAG_OBBLIGATORIO, DIPENDE_DA_STEP, INCOMPATIBILE_CON_STEP, ORDINE_DEFAULT) VALUES ('PROCEDIMENTI','../nuovaistanza/procedimenti.htm','Procedimenti','In questa sezione è possibile attivare gli endoprocedimenti utili al completamento dell''istanza.<br />Gli endo-procedimenti già selezionati sono proposti dal sistema in base alla compilazione degli step precedenti.',0,NULL,NULL,6);
			
INSERT INTO FO_ARJ_STEPS_BASE (NOME_STEP, LINK_FUNZIONE, TITOLO, DESCRIZIONE,FLAG_OBBLIGATORIO, DIPENDE_DA_STEP, INCOMPATIBILE_CON_STEP, ORDINE_DEFAULT) VALUES ('SCHEDE','../nuovaistanzaschede/list.htm','Schede','...',0,NULL,NULL,7);

INSERT INTO FO_ARJ_STEPS_BASE (NOME_STEP, LINK_FUNZIONE, TITOLO, DESCRIZIONE,FLAG_OBBLIGATORIO, DIPENDE_DA_STEP, INCOMPATIBILE_CON_STEP, ORDINE_DEFAULT) VALUES ('ALLEGATI','../nuovaistanza/allegati.htm','Allegati','Gli allegati che riportano il simbolo (<b>*</b>) sono obbligatori. Sarà cura del richiedente o della persona incaricata allegare i documenti proposti nell''elenco. <br />Il bottone "Sfoglia" permette di cercare il documento da caricare , una volta selezionato cliccare sulla voce "Carica". <br />',0,NULL,NULL,8);

UPDATE FO_ARJ_STEPS SET FK_NOME_STEP_BASE='BENVENUTO' WHERE NOME='../nuovaistanza/benvenuto.htm';
UPDATE FO_ARJ_STEPS SET FK_NOME_STEP_BASE='INFORMATIVA_PRIVACY' WHERE NOME='../nuovaistanza/informativa.htm';
UPDATE FO_ARJ_STEPS SET FK_NOME_STEP_BASE='INSERIMENTO_ANAGRAFICHE' WHERE NOME='../anagrafe/richiedente.htm';
UPDATE FO_ARJ_STEPS SET FK_NOME_STEP_BASE='LOCALIZZAZIONE' WHERE NOME='../nuovaistanza/localizzazione.htm';
UPDATE FO_ARJ_STEPS SET FK_NOME_STEP_BASE='INTERVENTO' WHERE NOME='../nuovaistanza/intervento.htm';
UPDATE FO_ARJ_STEPS SET FK_NOME_STEP_BASE='PROCEDIMENTI' WHERE NOME='../nuovaistanza/procedimenti.htm';
UPDATE FO_ARJ_STEPS SET FK_NOME_STEP_BASE='ALLEGATI' WHERE NOME='../nuovaistanza/allegati.htm';
UPDATE FO_ARJ_STEPS SET FK_NOME_STEP_BASE='SCHEDE' WHERE NOME='../nuovaistanzaschede/list.htm';

DELETE FROM FO_ARJ_STEPS WHERE NOME='../schede/list.htm';

INSERT INTO FO_ARJ_STEPS_BASE(NOME_STEP,LINK_FUNZIONE, TITOLO,DESCRIZIONE,FLAG_OBBLIGATORIO,DIPENDE_DA_STEP,INCOMPATIBILE_CON_STEP, ORDINE_DEFAULT) VALUES
    (
    'INSERIMENTO_ANAGRAFE_DEFAULT'
    ,'../nuovaistanzaanagrafesingola/soggetti.htm'
    ,'Inserimento anagrafiche'	
    ,'In questa scheda vanno inseriti tutti i soggetti, persone fisiche e giuridiche, coinvolti nella pratica che si sta presentando. I soggetti possono essere l''interessato, l''azienda coinvolta, l''intermediario ...'    
    ,1
    ,null
    ,'INSERIMENTO_ANAGRAFICHE'
    ,3
  );

UPDATE FO_ARJ_STEPS SET FK_NOME_STEP_BASE='INSERIMENTO_ANAGRAFE_DEFAULT' WHERE NOME='../nuovaistanzaanagrafesingola/soggetti.htm';

UPDATE FO_ARJ_STEPS_BASE SET incompatibile_con_step='INSERIMENTO_ANAGRAFE_DEFAULT' WHERE nome_step='INSERIMENTO_ANAGRAFICHE';

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) VALUES('AREA_RISERVATA','AREA_RISERVATA_JAVA_ATTIVA','Indica se e'' attivo l''applicativo area riservata java. Valori ammessi S (Si) N (No)');

INSERT INTO CLMENU_JAVA (ID,DESCRIZIONE,PAGINA,MENULINK, SOFTWARE, JSP, LAYOUTTESTI, VERTICALIZZAZIONE,SOFTWAREESCLUSI, LINK_STANDARD,TIPO_FUNZIONALITA ) VALUES (1006, 'Tipologie attività', 'iattivitatipologie/list.htm?software=SOFTWARE', '0AZM', '*','JAVA', 0, NULL, 'PR,FI,AB','iattivitatipologie/list.htm?software=SOFTWARE', 'E');

INSERT into CATEGORIEEVENTIBASE (ID, DESCRIZIONE) VALUES('AR-NUOVO-ENTE','Ente non trovato nella lista degli enti locali');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_SIGEDO','TIPO_DOCUMENTO_PRINCIPALE','Specificare il valore del tipo documento dell''allegato principale, questo dato può essere omesso IN quanto non obbligatorio');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_SIGEDO','APPLICATIVO_PROTOCOLLO','Indica il nome dell''applicativo del protocollo, questa voce sarà inserita dentro il file segnatura.xml dentro l''attributo -nome- di <ApplicativoProtocollo/>. NB. Se lasciato vuoto o non attivato prenderà il valore inserito dentro il parametro CODICEENTE');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_SIGEDO','CODICEENTE','E'' il codice dell''ente per il quale protocollare, questo parametro va usato nell''autenticazione al web service insieme al parametro USERNAME_WS e PASSWORD_WS');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_SIGEDO','CODICE_AOO','E'' il codice dell''Area Organizzativa Omogenea, definisce l''ambito per cui protocollare, in particolare, deve essere fornito dai responsabili di protocollo.');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_SIGEDO','INVIA_SEGNATURA','Se valorizzato a 1 consente, in fase di protocollazione istanza o movimento da backoffice, di allegare il file di profilazione (segnatura.xml) che sarebbe il file che viene inviato al web service per eseguire la protocollazione. Questa funzionalità viene usata nel momento in cui il cliente decide che nessun file allegato deve essere inviato al web service, che però ne richiede necessariamente almeno uno.; se valorizzato a 0 o non valorizzato non esegue nessuna funzionalità.');                                                                                                                                                                                                                                                                                                             
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_SIGEDO','USERNAME_WS','E'' lo username che serve per autenticarsi al web service di protocollazione, va usato insieme al parametro CODICEENTE e PASSWORD_WS.');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_SIGEDO','PASSWORD_WS','E'' la password che serve per autenticarsi al web service di protocollazione, va usato insieme al parametro CODICEENTE e USERNAME_WS.');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_SIGEDO','TIPO_DOCUMENTO_ALLEGATO','Specificare il valore del tipo documento degli allegati secondari, ossia quei documenti allegati al protocollo escluso quello principale, questo parametro non è obbligatorio.');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_SIGEDO','UO','Indica l''ufficio di smistamento del protocollo, questa voce sarà inserita dentro il file segnatura.xml dentro il nodo <ApplicativoProtocollo> valorizzando un nuovo parametro con nome -UO-. ');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_SIGEDO','URL_PROTO','E'' l''endpoint utilizzato per invocare il web service di protocollazione.');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_SIGEDO','URL_QUERYSERVICE','E'' l''endpoint utilizzato per invocare il web service di ricerche, tramite questo servizio è possibile cercare i protocolli, gli allegati, i mittenti e destinatari, da usare in fase di LeggiProtocollo, questo servizio ha la particolarità che restituisce diversi dati in base ai metadati passati e determinati dai parametri AREA e MODELLO, ad esempio se AREA viene lasciato vuoto e MODELLO valorizzato con @PROTO cerca un protocollo altrimenti con diversi valori potrebbe cercare allegati oppure mittenti e destinatari.');                                                                                                                                                                                                                                                                   
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_SIGEDO','AREA_LEGGIPROTO','Parametro area usato per la ricerca di un protocollo invocando i servizi presenti sull''endpoint del parametro URL_QUERYSERVICE. E'' una sezione del documentale dedicata ad un particolare compito applicativo con dei modelli atti a tale scopo; ad esempio l’area SEGRETERIA contiene i modelli del protocollo');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_SIGEDO','MODELLO_LEGGIPROTO','Parametro modello usato per la ricerca di un protocollo invocando i servizi presenti sull''endpoint del parametro URL_QUERYSERVICE. Rappresenta la tipologia di modello di riferimento (in relazione all’area scelta); ciascuna tipologia è dotata di una collezione di attributi specifici e/o metadati da valorizzare, ad esempio anno e numero per la ricerca di un protocollo');                                                                                                                                                                                                                                                                                                                                                                                                                       
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_SIGEDO','STATO','Parametro stato usato per invocare i servizi presenti sull''endpoint del parametro URL_QUERYSERVICE, questo parametro è fisso per tutte le ricerche e indica se cercare un protocollo in stato BO (Bozza) oppure CO (Completo)');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_SIGEDO','AREA_ALLEGATI','Parametro area usato per la ricerca degli allegati secondari di uno specifico protocollo, cercato in precedenza, invocando i servizi presenti sull''endpoint del parametro URL_QUERYSERVICE. E'' una sezione del documentale dedicata ad un particolare compito applicativo con dei modelli atti a tale scopo; ad esempio l’area SEGRETERIA contiene i modelli del protocollo');                                                                                                                                                                                                                                                                                                                                                                                                                                
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_SIGEDO','MODELLO_ALLEGATI','Parametro modello usato per la ricerca degli allegati di uno specifico protocollo, cercato in precedenza, invocando i servizi presenti sull''endpoint del parametro URL_QUERYSERVICE. Rappresenta la tipologia di modello di riferimento (in relazione all’area scelta); ciascuna tipologia è dotata di una collezione di attributi specifici e/o metadati da valorizzare, ad esempio anno e numero per la ricerca di un protocollo');                                                                                                                                                                                                                                                                                                                                                                       
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_SIGEDO','AREA_SOGGETTI','Parametro area usato per la ricerca soggetti (mittenti/destinatari) di uno specifico protocollo, cercato in precedenza, invocando i servizi presenti sull''endpoint del parametro URL_QUERYSERVICE. E'' una sezione del documentale dedicata ad un particolare compito applicativo con dei modelli atti a tale scopo; ad esempio l’area SEGRETERIA contiene i modelli del protocollo');                                                                                                                                                                                                                                                                                                                                                                                                                         
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_SIGEDO','MODELLO_SOGGETTI','Parametro modello usato per la ricerca soggetti (mittenti/destinatari) di uno specifico protocollo, cercato in precedenza, invocando i servizi presenti sull''endpoint del parametro URL_QUERYSERVICE. Rappresenta la tipologia di modello di riferimento (in relazione all’area scelta); ciascuna tipologia è dotata di una collezione di attributi specifici e/o metadati da valorizzare, ad esempio anno e numero per la ricerca di un protocollo');                                                                                                                                                                                                                                                                                                                                                      
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_SIGEDO','OPERATORE_RICERCHE','Parametro operatore usato nei metadati per eseguire tutti i tipi di ricerche, invocando i servizi presenti sull''endpoint del parametro URL_QUERYSERVICE. Valore fisso da passare che però non ha niente a che fare ne con lo username del web service ne con gli operatori di protocollo.');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_SIGEDO','USERNAME_QUERYSERVICE','Username usato per l''autenticazione del web service di ricerche QUERYSERVICE.');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_SIGEDO','PASSWORD_QUERYSERVICE','Password usata per l''autenticazione del web service di ricerche QUERYSERVICE.');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       

INSERT INTO VERTICALIZZAZIONIBASE(MODULO, DESCRIZIONE) VALUES ('PROTOCOLLO_DELTA', 'Se attivato consente di eseguire la protocollazione con il protocollo proprietario di Delta Informatica, con questo tipo di protocollo abbiamo la possibilità di eseguire delle prove in ambiente di test fornito proprio dalla Società Delta Informatica, in particolare l''applicativo si trova all''indirizzo: http://crm.deltainf.it/protocollo/, NB.: la protocollazione può avvenire solo tramite un unico operatore in quanto il web service richiede, oltre che il paramtro username, anche la password che verrà inserita tra i parametri, quindi non è possibile usare i segnalibri nel parametro Operatore della verticalizzazione PROTOCOLLO_ATTIVO');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_DELTA', 'URL', 'Specificare in questo parametro l''end point del web service di protocollazione');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_DELTA', 'PASSWORD', 'Indica la password dell''utente che protocolla, questo dato può essere usato solamente nel caso in cui l''utente protocollatore sia solamente uno, quindi non è possibile usare i segnalibri nel parametro OPERATORE della verticalizzazione PROTOCOLLO_ATTIVO così come spiegato anche sulla descrizione della verticalizzazione PROTOCOLLO_DELTA');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_DELTA', 'REGISTRO', 'Indica il registro (o AOO è la stessa cosa) da usare durante la fase di protocollazione, è un dato alfanumerico di tre caratteri, ad esempio in ambiente di test il valore è 011');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES('PROTOCOLLO_DELTA', 'CODICE_CC','Indica il codice per conoscenza da utilizzare in fase di protocollazione. Sulla maschera di protocollazione è presente un campo a tendina denominato -Trasmesso per- legato all''anagrafica (Mittente / Destinatario), questo campo viene popolato dai valori presenti nella tabella PROTOCOLLO_MODALITAINVIO, indicando il codice in questo campo, quando l''operatore selezionerà nella tendina -Trasmesso per- il valore con lo stesso codice, l''anagrafica selezionata sarà considerata per conoscenza.');

UPDATE FO_ARJ_STEPS_BASE SET LINK_FUNZIONE='../nuovaistanzaanagrafe/richiedente.htm' WHERE NOME_STEP='INSERIMENTO_ANAGRAFICHE';

INSERT INTO MAPOGGETTI (NOMETABELLA, NOMECAMPO) VALUES ('FO_ARJ_DOMANDE','CODICEOGGETTO_RIEPILOGO');
INSERT INTO MAPOGGETTI (NOMETABELLA, NOMECAMPO) VALUES ('FO_ARJ_DOMANDE_ONERI','CODICEOGGETTO_XML');
INSERT INTO MAPOGGETTI (NOMETABELLA, NOMECAMPO) VALUES ('FO_ARJ_DOMANDE_ONERI','CODICEOGGETTO_PDF');
INSERT INTO FO_ARJ_STEPS_BASE (NOME_STEP, LINK_FUNZIONE, TITOLO, DESCRIZIONE, FLAG_OBBLIGATORIO, DIPENDE_DA_STEP,INCOMPATIBILE_CON_STEP, ORDINE_DEFAULT) VALUES ('ONERI','../nuovaistanzaoneri/oneri.htm','Riepilogo diritti/oneri','Questa scheda riepiloga quanti diritti di istruttoria/oneri/bolli devono essere corrisposti con riferimento all''intervento e agli endoprocedimenti attivati. Per i pagamenti per i quali si possiede già la ricevuta si ricorda che questa deve essere firmata digitalmente. I pagamenti possono essere effettuati mediante bollettino utilizzando le seguenti coordinate: <b>c/c postale n. XXXX intestato a Comune di XXXXX- Direzione XXXXXX.</b>',0,'INTERVENTO', NULL, 9);

UPDATE VERTICALIZZAZIONIBASE SET DESCRIZIONE = 'Se attivato consente di eseguire la protocollazione con il protocollo proprietario di Delta Informatica, con questo tipo di protocollo abbiamo la possibilità di eseguire delle prove in ambiente di test fornito proprio dalla Società Delta Informatica, in particolare l''applicativo si trova all''indirizzo: http://crm.deltainf.it/protocollo/, NB.: tutte le chiamate al web service hanno come argomenti fissi username e password, che coincidono con un utente già registrato nel sistema, indicare questi valori nei parametri USERNAME e PASSWORD della verticalizzazione PROTOCOLLO_DELTA.' WHERE MODULO = 'PROTOCOLLO_DELTA';
UPDATE VERTICALIZZAZIONIPARAMETRIBASE SET DESCRIZIONE = 'Indica la password dell''utente che protocolla, e fa parte dell''autenticazione dell''operatore già registrato nell''applicativo di protocollo; ogni chiamata al web service necessita come argomento il valore di questo parametro.' WHERE MODULO = 'PROTOCOLLO_DELTA' AND PARAMETRO = 'PASSWORD'; 
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES('PROTOCOLLO_DELTA', 'USERNAME', 'Indica lo username dell''utente che protocolla, e fa parte dell''autenticazione dell''operatore già registrato nell''applicativo di protocollo; ogni chiamata al web service necessita come argomento il valore di questo parametro.') ; 

INSERT INTO VERTICALIZZAZIONIBASE (MODULO, DESCRIZIONE) VALUES ('SISTEMAPAGAMENTI_ATTIVO_FO','Indica se nel frontoffice è attivato un sistema di pagamento per permettere all''utente collegato di poter effettuare pagamenti telematici. (es: PAGAMENTI_MIP_RPCSUAP)');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES('SISTEMAPAGAMENTI_ATTIVO_FO','TIPOSISTEMA','Indicare quale sistema di pagamento è attivo (es: PAGAMENTI_MIP_RPCSUAP)');


INSERT INTO VERTICALIZZAZIONIBASE (MODULO, DESCRIZIONE) VALUES ('PAGAMENTI_MIP_RPCSUAP','Il sistema di pagamento di frontend "modulo incassi e pagamento" del progetto RPC_SUAP');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES('PAGAMENTI_MIP_RPCSUAP','URLSERVERPAGAMENTO','indica l''URL del Server di Pagamento'); 
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES('PAGAMENTI_MIP_RPCSUAP','INDIRIZZOPROXY','Indica l''indirizzo del proxy (eventuale) usato dai componenti di comunicazione col sistema di pagamento'); 
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES('PAGAMENTI_MIP_RPCSUAP','PORTAPROXY','Indica la porta del proxy (eventuale) usato dai componenti di comunicazione col sistema di pagamento'); 
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES('PAGAMENTI_MIP_RPCSUAP','WINDOW_MINUTES','Finestra temporale per la validazione del messaggio'); 
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES('PAGAMENTI_MIP_RPCSUAP','IDSERVIZIO','Identificativo del servizio chiamante.'); 
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES('PAGAMENTI_MIP_RPCSUAP','IDENTIFICATIVO_COMPONENTE','L''identificativo del componente nelle chiamate verso il sistema di pagamenti'); 
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES('PAGAMENTI_MIP_RPCSUAP','PORTALEID','Identifica il sito dei servizi nei confronti del sistema dei pagamenti'); 
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES('PAGAMENTI_MIP_RPCSUAP','PASSWORD_CHIAMATE','La chiave segreta per la generazione delle chiamate al PayServerClient'); 
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES('PAGAMENTI_MIP_RPCSUAP','EMAIL_PORTALE','Email che il sistema di pagamenti usa in caso di problemi (pe. il mancato invio della notifica)');

insert into CLMENU_JAVA (ID,DESCRIZIONE,PAGINA,MENULINK,SOFTWARE,JSP,LAYOUTTESTI,VERTICALIZZAZIONE,SOFTWAREESCLUSI,LINK_STANDARD,TIPO_FUNZIONALITA) values (1007, 'NLA per servizi FO', 'nlaservizi/list.htm?software=CS','00BS','CS','JAVA',0,null,null,'nlaservizi/list.htm?software=CS','E');

INSERT INTO SOFTWARE (ACCESSORAPIDO,CODICE,DESCRIZIONE,DESCRIZIONELUNGA,MODULOOPZIONALE,ORDINE) VALUES (0,'CS','Centro Servizi','Modulo per la configurazione dei servizi extra SUAPE',1,52);

UPDATE FO_ARJ_STEPS SET NOME = NULL;
UPDATE FO_ARJ_STEPS_BASE SET LINK_FUNZIONE = '../nuovaistanzabenvenuto/view.htm' WHERE NOME_STEP = 'BENVENUTO';
UPDATE FO_ARJ_STEPS_BASE SET LINK_FUNZIONE = '../nuovaistanzainformativa/view.htm' WHERE NOME_STEP = 'INFORMATIVA_PRIVACY';
UPDATE FO_ARJ_STEPS_BASE SET LINK_FUNZIONE = '../nuovaistanzalocalizzazione/view.htm' WHERE NOME_STEP = 'LOCALIZZAZIONE';
UPDATE FO_ARJ_STEPS_BASE SET LINK_FUNZIONE = '../nuovaistanzaintervento/view.htm' WHERE NOME_STEP = 'INTERVENTO';
UPDATE FO_ARJ_STEPS_BASE SET LINK_FUNZIONE = '../nuovaistanzaallegati/view.htm' WHERE NOME_STEP = 'ALLEGATI';
UPDATE FO_ARJ_STEPS_BASE SET LINK_FUNZIONE = '../nuovaistanzaschede/view.htm' WHERE NOME_STEP = 'SCHEDE';
UPDATE FO_ARJ_STEPS_BASE SET LINK_FUNZIONE = '../nuovaistanzaprocedimenti/view.htm' WHERE NOME_STEP = 'PROCEDIMENTI';
UPDATE FO_ARJ_STEPS_BASE SET LINK_FUNZIONE = '../nuovaistanzaoneri/view.htm' WHERE NOME_STEP = 'ONERI';
UPDATE FO_ARJ_STEPS_BASE SET LINK_FUNZIONE = '../nuovaistanzaanagrafesingola/view.htm' WHERE NOME_STEP = 'INSERIMENTO_ANAGRAFE_DEFAULT';

UPDATE DOCUMENTIISTANZA SET FLG_DA_MODELLO_DINAMICO=0 WHERE FLG_DA_MODELLO_DINAMICO IS NULL;

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('WSANAGRAFE_PARIX','PROXY_ADDRESS', 'Url nel formato http[s]://INDIRIZZO:PORTA da utilizzare per effettuare le chiamate al web service di parix');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_DOCAREA', 'INVIA_NOMEFILE_ATTACH', 'Indica se il nome file degli allegati deve essere inviato come id sull''attachment della richiesta soap, questa esigenza è venuta a crearsi con il protocollo SAGA al Comune di Lucca in quanto il web service non riusciva a leggere il nome del file in quanto non veniva inviato come id dell''attachment, in altri ambiti DOCAREA invece sembra funzionare correttamente, se valorizzato a 1 allora il sistema invia il nome file come id, (vedi anche il parametro NOMEFILE_ORIGINE della verticalizzazione PROTOCOLLO_ATTIVO) qualsiasi altro valore non invia il nome file sull''id dell''attachment');