package it.gruppoinit.sde;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2015-03-23T17:16:26.739+01:00
 * Generated source version: 2.5.1
 * 
 */
@WebServiceClient(name = "SdeWS", 
                  wsdlLocation = "SdeWS.wsdl",
                  targetNamespace = "http://gruppoinit.it/sde") 
public class SdeWS_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://gruppoinit.it/sde", "SdeWS");
    public final static QName SdeWSSOAP = new QName("http://gruppoinit.it/sde", "SdeWSSOAP");
    static {
        URL url = null;
        try {
            url = new URL("SdeWS.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SdeWS_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "SdeWS.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SdeWS_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SdeWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SdeWS_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns SdeWS
     */
    @WebEndpoint(name = "SdeWSSOAP")
    public SdeWS getSdeWSSOAP() {
        return super.getPort(SdeWSSOAP, SdeWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SdeWS
     */
    @WebEndpoint(name = "SdeWSSOAP")
    public SdeWS getSdeWSSOAP(WebServiceFeature... features) {
        return super.getPort(SdeWSSOAP, SdeWS.class, features);
    }

}
