INSERT INTO VERTICALIZZAZIONIBASE (MODULO, DESCRIZIONE) VALUES ('PROTOCOLLO_JIRIDEDOCIN', 'Abilita il protocollo J-IRIDE realizzato da Maggioli con la particolare gestione dei documenti interni DOCIN (inizialmente richiesto da C.M. di Firenze), questo protocollo non gestisce nell''immediato la protocollazione ma si occupa, per i protocolli in partenza e interni, di creare solo un documento che andrà ad associarsi al campo FKIDPROTOCOLLO, la creazione del protocollo è asincrona e sottoposta ad una notifica inviata dai sistemi di Maggioli verso un ws di VBG lato Java. Per questo motivo, a parte i protocolli in arrivo che hanno la classica gestione presente anche nella regola PROTOCOLLO_JIRIDE, non saranno subito staccati i protocolli.');
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('PROTOCOLLO_JIRIDEDOCIN','TIPORECAPITO_EMAIL','Indica la tipologia di recapito relativa alla Mail / Pec. Questo tipo di dato deve essere fornito dal gestore di protocollo perchè indica, appunto la tipologia che deve assumere il recapito, va indicato solo se, in accordo con l''ente, è stata aggiunta una tipologia nuova ( di default è impostata a EMAIL).');
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('PROTOCOLLO_JIRIDEDOCIN','DISABILITA_CARICO_P','Se valorizzato a 1 consente di non impostare il carico per le protocollazioni in partenza, come accade di default, quindi, se non valorizzato o valorizzato diverso da 1 la procedura sarà la medesima di default, quindi verrà impostato il carico con il dato del mittente.');
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('PROTOCOLLO_JIRIDEDOCIN','URLFASC','Percorso completo del WS di fascicolazione DocWsFascicoli');
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('PROTOCOLLO_JIRIDEDOCIN','PEC_INTEROP','Parametro Si o No (valore 1 o altro), se valorizzato a 1, l''invio della pec tramite ws PosteWeb, sarà interoperabile, sarà quindi inserito l''elemento <InvioInteroperabile> valorizzato a S, questo consente l''invio della segnatura xml.');
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('PROTOCOLLO_JIRIDEDOCIN','NUMEROPRATICA','Numero pratica da passare al WS J-Iride a Ravenna "9999999"');
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('PROTOCOLLO_JIRIDEDOCIN','AGGIORNAANAGRAFICHE','Parametro che in J-Iride specifica se aggiornare le anagrafiche. Possibili valori S o N.');
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('PROTOCOLLO_JIRIDEDOCIN','URL','Percorso completo del WS di Protocollazione WsProtocolloDM');
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('PROTOCOLLO_JIRIDEDOCIN','CODICEAMMINISTRAZIONE','Indica il codice di amministrazione da passare al web service di J-Iride, deve essere fornito dall''amministratore del protocollo. Questo dato indica su quale amministrazione protocollare, infatti J-Iride può avere un''installazione MultiDB, in questo caso va valorizzato questo dato che, tra le altre cose può indicare se si sta utilizzando un ambiente di Test o di Produzione.');
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('PROTOCOLLO_JIRIDEDOCIN','DISABILITA_CREACOPIE','Consente di disabilitare la funzionalità di creazione delle copie su J-Iride (se = 1). Inserito in quanto l''invio della notifica tramite il movimento dell''istanza creava automaticamente anche la copia sul sistema di protocollazione J-Iride, e questo può creare alcuni disagi per i clienti che gestiscono manualmente le pratiche o che abbiano già creato il protocollo su J-Iride, come nel caso della Bassa Romagna. NB. L''utilizzo di questo parametro può portare a qualche problema durante la funzionalità di leggi protocollo, infatti se valorizzato a 1, i dati inviati tramite notifica STC sulla nuova istanza su nuovo software non saranno compresi di IDPROTOCOLLO, questo significa che, in presenza di più copie (su J-IRIDE) con stessa numerazione ma con ID diverso, nel momento della lettura di un protocollo senza ID può essere riportato quello con ID sbagliato, in teoria comunque i dati dei protocolli con diversi ID ma con stessa numerazione dovrebbero essere gli stessi.');
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('PROTOCOLLO_JIRIDEDOCIN','MEZZO_DEFAULT','Indica il mezzo di default da passare al web service di J-Iride, non è un dato obbligatorio quindi può essere omesso. Questo dato, se valorizzato, viene proposto di default nella maschera di protocollazione nel dropdown riguardante i mezzi e se lo stesso valore è presente nella tabella PROTOCOLLO_MEZZI, viene inviato al web service anche quando la protocollazione è automatica, quindi proveniente da un frontoffice o dal backoffice se impostata la configurazione di protocollazione automatica. NB. se la tabella PROTOCOLLO_MEZZI è vuota il drop down mezzi, nella maschera di protocollazione, non viene visualizzato, ignorando quindi il valore di questo parametro.');
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('PROTOCOLLO_JIRIDEDOCIN','MOSTRA_METTI_ALLA_FIRMA','Attivando il pulsante c''è la possibilità di comunicare al software INTRANOS (Comune di Ravenna) che un documento deve essere firmato. Ogni successivo cambiamento di stato compiuto in INTRANOS + J-IRIDE viene comunicato al Backoffice tramite WebService (Es: "Il documento è stato firmato", "Il documento è stato protocollato", "Il documento è stato inviato"). I cambiamenti di stato vengono scritti nel backoffice nella sezione eventi del movimento e, nel caso di protocollazione, viene riportato in automatico il numero di protocollo nel movimento. Accetta valori S o N');
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('PROTOCOLLO_JIRIDEDOCIN','AOO','Valorizzare questo parametro solamente nel caso in il parametro VERSIONE sia valorizzato a J-IRIDE, in caso contrario sarà comunque ignorato, serve solamente per l''invio delle PEC in quanto il metodo utilizzato da J-IRIDE inviaMail (a differenza di J-IRIDE che utilizza inviaMailInterop) lo richiede in modo necessario.');
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('PROTOCOLLO_JIRIDEDOCIN','FORMATO_DATA_FASC','Serve per indicare in quale formato deve essere inviata la data di fascicolazione al web service. Maggioli ha creato un altro web service compatibile con J-Iride (ProtocolloSoap e DocWsFascicoli), solo che la data deve avere formato yyyy-MM-dd altrimenti non viene riconosciuta. Quindi, solo nel momento in cui vengono usati questi web service, il formato data deve essere impostato a yyyy-MM-dd, in generale, comunque, il componente PROTOCOLLO_IRIDE andrà ad impostare la data in base a quanto scritto in questo parametro, quindi, se viene impostato dd-MM-yyyy il sistema invierà ad esempio 23-10-2014, che nel caso specifico di questo web service, restituirà errore, evitare quindi di inserire ulteriori formati. Nel caso del vecchio J-Iride, non va impostato.');
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('PROTOCOLLO_JIRIDEDOCIN','WARNING_DA_ELIMINARE','Inserire in questo parametro la stringa che viene restituita dal web service nn fase di protocollazione avvenuta correttamente. J-Iride restituisce un messaggio anche in caso di protocollazione avvenuta correttamente, il messaggio viene successivamente inserito nei warning quindi va eliminata la stringa restituita in caso di protocollazione OK.');
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('PROTOCOLLO_JIRIDEDOCIN','USA_NUM_ANNO_LEGGI','Questo parametro serve per indicare al plugin del protocollo per capire se la lettura del protocollo deve essere fatta invocando il metodo LeggiProtocollo oppure LeggiDocumento, nel primo caso la chiamata viene fatta passando il numero e l''anno del protocollo, nel secondo l''id del documento, di default, se valorizzato il campo FKIDPROTOCOLLO delle ISTANZE o MOVIMENTO viene invocato il metodo LeggiDocumento, valorizzando questo parametro a 1 il sistema forza la chiamata sempre utilizzando il metodo LeggiProtocollo, questo perchè il nuovo ws retrocompatibile J-IRIDE di Maggioli ha un bug su leggi documento che non ritorna gli allegati.');
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('PROTOCOLLO_JIRIDEDOCIN','URL_PEC','Indicare in questo parametro l''endpoint da utilizzare per usare il servizio di invio posta elettronica certificata di J-Iride, sarà proprio questo servizio che si occuperà di inviare la PEC');
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('PROTOCOLLO_JIRIDEDOCIN','MEZZO_PEC','Indicare il mezzo da utilizzare se si vuole inviare la PEC richiamando il web service PosteWeb di J-Iride. Se il protocollo è in partenza e sono presenti dei destinatari esterni (che non abbiano scrivanie su J-Iride) è necessario indicare il mezzo per cui, al destinatario, venga inviata anche una PEC tramite il servizio PostePec di J-Iride indicato nel parametro URL_PEC, se sarà utilizzato quindi il mezzo indicato in questo parametro il sistema si occuperà di chiamare quindi il servizio di invio pec di J-iride');
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('PROTOCOLLO_JIRIDEDOCIN','MITTENTE_PEC','Inserire in questo parametro il valore relativo al mittente che invia la mail pec in fase di protocollazione in partenza, questo parametro è legato all''altro parametro URL_PEC in quanto, se non presente quest''ultimo, MITTENTE_PEC non viene utilizzato');
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('PROTOCOLLO_JIRIDEDOCIN','UO_SMISTAMENTO','Indicare il codice UO (ufficio) che indica il mittente interno per le pratiche in arrivo, nel protocollo sta ad indicare lo smistamento, in pratica quale ufficio ha lavorato il documento (in arrivo).');
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('PROTOCOLLO_JIRIDEDOCIN','WARNING_PEC','Se valorizzato a 1 consente di visualizzare sempre un warning relativo all''invio PEC di una protocollazione in partenza, sia che vada a buon fine che vada in errore.');
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('PROTOCOLLO_JIRIDEDOCIN','PROTO_OGGETTO_PEC','Parametro Si o No (valore 1 o altro), se valorizzato a 1 nell''oggetto della pec, inviata tramite la chiamata a ws PostaWeb, saranno visualizzati, in fondo all''oggetto stesso i dati di protocollo sotto forma di: Pr. Num. [NUMERO_PROTOCOLLO], Pr. Data [DATA_PROTOCOLLO]');
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('PROTOCOLLO_JIRIDEDOCIN','AGGIORNACLASSIFICA','Parametro che in J-Iride specifica se aggiornare la classifica del documento se diversa da quella del fascicolo');
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('PROTOCOLLO_JIRIDEDOCIN','VISUALIZZA_RICEVUTE_PEC','Impostare a 1 se si vuole visualizzare l''esito delle ricevute inviate via PEC dal sistema di protocollo, tra l''elenco degli allegati in fase di lettura di un protocollo.');
Insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) values ('PROTOCOLLO_JIRIDEDOCIN','TIPODOCUMENTO_DOCIN','Inserire in questo parametro il codice del tipo documento corrispondente al DOCIN (in linea di massima il codice dovrebbe essere proprio DOCIN ma va verificato), se lasciato vuoto o valorizzato in modo errato non saranno eseguiti inserimenti nel documentale di documenti di tipo DOCIN.');

UPDATE VERTICALIZZAZIONIPARAMETRIBASE
SET DESCRIZIONE = 'Indica con quale dato deve essere valorizzato il mittente/destinatario per le protocollazioni automatiche, se una protocollazione è in arrivo allora il soggetto interessato sarà il mittente, se la protocollazione automatica sarà in partenza allora il soggetto sarà il destinatario.
Può assumere i seguenti valori
- 0 ( o non valorizzato ): Il sistema indicherà come mittente/destinatario il richiedente e l''azienda.
- 1: Verrà proposto solo il richiedente.
- 2: Il mittente/destinatario sarà solo l''azienda, qualora l''azienda non fosse presente sarà solamente il richiedente
- 3: I mittenti/destinatari saranno l''azienda e il professionista, se l''azienda non fosse presente verrà preso il richiedente
- 4: Il mittente/destinatario sarà solo il tecnico, se non presente il richiedente
- 5: Stesso comportamento del punto 2 con la differenza che se la qualifica del richiedente è una ditta individuale verrà passato il richiedente a prescindere. Questo parametro va utilizzato insieme al parametro MAPPATURA_DITTA_INDIVIDUALE'
WHERE MODULO = 'PROTOCOLLO_ATTIVO' AND PARAMETRO = 'TIPO_MITTDEST_AUTO';

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES ('PROTOCOLLO_ATTIVO','MAPPATURA_DITTA_INDIVIDUALE','Indicare la mappatura utilizzata per qualificare una tipologia di soggetto come ditta individuale; viene utilizzata quando il parametro TIPO_MITTDEST_AUTO è impostato a 5');

