//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.27 at 05:06:07 PM CEST 
//


package it.gruppoinit.pal.gp.core.domain.cart.mapping;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ValueBuilder complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ValueBuilder">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element name="vbg-value" type="{http://gruppoinit.it/sigepro/schemas/cartmapping}VbgValue"/>
 *       &lt;/sequence>
 *       &lt;attribute name="indexed-property" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="value-elaboration" type="{http://gruppoinit.it/sigepro/schemas/cartmapping}ElaborationType" default="GET_FIRST" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ValueBuilder", namespace = "http://gruppoinit.it/sigepro/schemas/cartmapping", propOrder = {
    "vbgValues"
})
public class ValueBuilder {

    @XmlElement(name = "vbg-value", namespace = "http://gruppoinit.it/sigepro/schemas/cartmapping", required = true)
    protected List<VbgValue> vbgValues;
    @XmlAttribute(name = "indexed-property")
    protected String indexedProperty;
    @XmlAttribute(name = "value-elaboration")
    protected ElaborationType valueElaboration;

    /**
     * Gets the value of the vbgValues property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the vbgValues property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVbgValues().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VbgValue }
     * 
     * 
     */
    public List<VbgValue> getVbgValues() {
        if (vbgValues == null) {
            vbgValues = new ArrayList<VbgValue>();
        }
        return this.vbgValues;
    }

    /**
     * Gets the value of the indexedProperty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndexedProperty() {
        return indexedProperty;
    }

    /**
     * Sets the value of the indexedProperty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndexedProperty(String value) {
        this.indexedProperty = value;
    }

    /**
     * Gets the value of the valueElaboration property.
     * 
     * @return
     *     possible object is
     *     {@link ElaborationType }
     *     
     */
    public ElaborationType getValueElaboration() {
        if (valueElaboration == null) {
            return ElaborationType.GET_FIRST;
        } else {
            return valueElaboration;
        }
    }

    /**
     * Sets the value of the valueElaboration property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElaborationType }
     *     
     */
    public void setValueElaboration(ElaborationType value) {
        this.valueElaboration = value;
    }

}
