ALTER TABLE VERTICALIZZAZIONIPARAMETRI MODIFY VALORE VARCHAR2(4000 CHAR);
ALTER TABLE domandestc_allegati MODIFY id number(10,0);
ALTER TABLE MERCATI ADD ACTIVE_WALLET_MARKET NUMBER(1,0) DEFAULT 0 NOT NULL;
CREATE TABLE RICALCOLO_AREE (
  IDCOMUNE VARCHAR2(6 CHAR) NOT NULL,
  ID VARCHAR2(50 CHAR) NOT NULL,
  DESCRIZIONE VARCHAR2(1000 CHAR) NULL,
  STATO VARCHAR2(20 CHAR) NOT NULL,
  DATAFINE DATE NOT NULL,
  DAFARE NUMBER(6,0) NOT NULL,
  FATTI NUMBER(6,0) NOT NULL,
  TOTALI NUMBER(6,0) NOT NULL
);

ALTER TABLE RICALCOLO_AREE ADD CONSTRAINT PK_RICALCOLOAREE PRIMARY KEY(IDCOMUNE,ID);

ALTER TABLE MOVIMENTIMAIL ADD BOZZA NUMBER(1,0) DEFAULT 0 NOT NULL;


CREATE TABLE RICALCOLO_AREE_ISTANZE (
  IDCOMUNE VARCHAR2(6 CHAR) NOT NULL,
  RICALCOLO_ID VARCHAR2(50 CHAR) NOT NULL,
  ISTANZE_UUID VARCHAR2(60 CHAR) NOT NULL,
  ID_RICALCOLO_AREE VARCHAR2(50 CHAR) NOT NULL
);

ALTER TABLE RICALCOLO_AREE_ISTANZE ADD CONSTRAINT PK_RICALCOLOAREEIST PRIMARY KEY(IDCOMUNE,RICALCOLO_ID,ISTANZE_UUID);
CREATE INDEX IDX_RIC_AREE_ISTANZE_001 ON RICALCOLO_AREE_ISTANZE(IDCOMUNE,ID_RICALCOLO_AREE);
ALTER TABLE RICALCOLO_AREE_ISTANZE ADD CONSTRAINT FK_RICALCOLO_AREE_IST FOREIGN KEY(IDCOMUNE,ID_RICALCOLO_AREE) REFERENCES RICALCOLO_AREE (IDCOMUNE,ID);

ALTER TABLE MERCATI ADD ASSENZE_PERCENTUALE NUMBER(10,0);
ALTER TABLE MERCATI ADD ASSENZE_TIPO_CALCOLO VARCHAR2(500 CHAR);
ALTER TABLE MERCATIPRESENZE_T ADD FLG_GG_NULLA NUMBER(1,0) DEFAULT 0;
ALTER TABLE MERCATIPRESENZE_T ADD ANNOTAZIONI_GG_NULLA VARCHAR2(4000 CHAR);


CREATE TABLE MERCATI_AUD_PRESENZE (
  IDCOMUNE            VARCHAR2(6 CHAR) NOT NULL,
  ID                  NUMBER(10) NOT NULL,
  CODICEOPERATORE     NUMBER(8),
  FK_ID_AUT_SORGENTE  NUMBER(6) NOT NULL,
  FK_ID_AUT_DEST      NUMBER(6) NOT NULL,
  DATA_OPERAZIONE     DATE NOT NULL,
  NOTE                VARCHAR2(4000 CHAR),
  TOT_PRESENZE        NUMBER(6) NOT NULL,
  CONSTRAINT PK_MERCATI_AUD_PRESENZE PRIMARY KEY (IDCOMUNE, ID),
  CONSTRAINT FK_AUD_PRESENZE_RESP FOREIGN KEY (IDCOMUNE, CODICEOPERATORE)
    REFERENCES RESPONSABILI (IDCOMUNE, CODICERESPONSABILE),
  CONSTRAINT FK_AUD_PRESENZE_SORG FOREIGN KEY (IDCOMUNE, FK_ID_AUT_SORGENTE)
    REFERENCES AUTORIZZAZIONI (IDCOMUNE, ID),
  CONSTRAINT FK_AUD_PRESENZE_DEST FOREIGN KEY (IDCOMUNE, FK_ID_AUT_DEST)
    REFERENCES AUTORIZZAZIONI (IDCOMUNE, ID)
);
CREATE INDEX IDX_AUD_PRESENZE_RESP ON MERCATI_AUD_PRESENZE (IDCOMUNE, CODICEOPERATORE);
CREATE INDEX IDX_AUD_PRESENZE_SORG ON MERCATI_AUD_PRESENZE (IDCOMUNE, FK_ID_AUT_SORGENTE);
CREATE INDEX IDX_AUD_PRESENZE_DEST ON MERCATI_AUD_PRESENZE (IDCOMUNE, FK_ID_AUT_DEST);

CREATE INDEX IDX_MERCAUDPRES_001 ON MERCATI_AUD_PRESENZE (IDCOMUNE, CODICEOPERATORE);
CREATE INDEX IDX_MERCAUDPRES_002 ON MERCATI_AUD_PRESENZE (IDCOMUNE, FK_ID_AUT_SORGENTE);
CREATE INDEX IDX_MERCAUDPRES_003 ON MERCATI_AUD_PRESENZE (IDCOMUNE, FK_ID_AUT_DEST);

ALTER TABLE MERCATIPRESENZE_STORICO ADD DATA DATE;
UPDATE MERCATIPRESENZE_STORICO SET DATA = TO_DATE('01/01/' || TO_CHAR(ANNO), 'DD/MM/YYYY') WHERE DATA IS NULL;
ALTER TABLE MERCATIPRESENZE_STORICO MODIFY DATA NOT NULL;


ALTER TABLE MERCATIPRESENZE_STORICO DROP CONSTRAINT IDX_MERCPRESSTORICO_001;
ALTER TABLE MERCATIPRESENZE_STORICO ADD CONSTRAINT IDX_MERCPRESSTORICO_003 UNIQUE (IDCOMUNE, FKCODICEMERCATO, FKIDMERCATIUSO, CODICEANAGRAFE, FK_AUTORIZZAZIONI_ID, DATA);