
ALTER TABLE INVENTARIOPROCEDIMENTIONERI 
ADD FK_COIDCOMUNE VARCHAR(6) ;

ALTER TABLE INVENTARIOPROCEDIMENTIONERI 
ADD FLAG_DISATTIVO NUMERIC(1,0);

ALTER TABLE INVENTARIOPROCEDIMENTIONERI 
DROP FOREIGN KEY FK_INVENT_PROCONER_TIPI_CAUS;

ALTER TABLE INVENTARIOPROCEDIMENTIONERI
ADD CONSTRAINT FK_INVENT_PROCONER_TIPI_CAUS FOREIGN KEY
(
  FK_COIDCOMUNE 
, FK_COID 
)
REFERENCES TIPICAUSALIONERI
(
  IDCOMUNE 
, CO_ID 
)
;


ALTER TABLE INVENTARIOPROCEDIMENTIONERI 
DROP FOREIGN KEY FK_INV_PROC_ONERI_INV_PROC;

ALTER TABLE INVENTARIOPROCEDIMENTIONERI 
ADD FK_INVPROC_IDCOMUNE VARCHAR(6) ;

ALTER TABLE INVENTARIOPROCEDIMENTIONERI
ADD CONSTRAINT FK_INV_PROC_ONERI_INV_PROC FOREIGN KEY
(
  FK_INVPROC_IDCOMUNE 
, CODICEINVENTARIO 
)
REFERENCES INVENTARIOPROCEDIMENTI
(
  IDCOMUNE 
, CODICEINVENTARIO 
)
;

ALTER TABLE INVENTARIOPROCEDIMENTIONERI ADD CODICECOMUNE VARCHAR(6) ;

ALTER TABLE INVENTARIOPROCEDIMENTIONERI
ADD CONSTRAINT FK_INVPROCONERI_COMUNI FOREIGN KEY
(
  CODICECOMUNE 
)
REFERENCES COMUNI
(
  CODICECOMUNE 
)
;

ALTER TABLE INVENTARIOPROCEDIMENTIONERI DROP COLUMN FLAG_PAGATO;