log4j.rootLogger=WARN, R

################################################
#CONSOLE
################################################
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
#%r [%t] %-5p %c - %m%n
log4j.appender.stdout.layout.ConversionPattern= %d [%t] %-5p - %c{1} - %M - %m%n
#log4j.appender.stdout.threshold=INFO

################################################
#ROLLING FILE APPENDER
################################################
log4j.appender.R=org.apache.log4j.RollingFileAppender
log4j.appender.R.File=${catalina.home}/logs/sigeprorenderer.log
log4j.appender.R.MaxFileSize=1000KB
log4j.appender.R.MaxBackupIndex=10
log4j.appender.R.layout=org.apache.log4j.PatternLayout
log4j.appender.R.layout.ConversionPattern= %d [%t] %-5p %20c{1} %30M - %n%m%n

################################################
# raised levels, to avoid framework dumping
################################################
#raise level
log4j.logger.org.apache=ERROR

