ALTER TABLE STATIISTANZA MODIFY STATO VARCHAR(100);

ALTER TABLE istanzestradario ADD accesso_tipo VARCHAR(20);
ALTER TABLE istanzestradario ADD accesso_numero VARCHAR(20);
ALTER TABLE istanzestradario ADD accesso_descrizione VARCHAR(100);


CREATE OR REPLACE VIEW ldp_pratiche_indirizzi AS
    SELECT
        istanze.idcomune AS installazione,
        istanze.software AS modulo,
        istanze.codiceistanza AS idpratica,
        istanzestradario.id AS idindirizzo,
        stradario.codviario AS codviario,
        stradario.prefisso AS toponimo,
        stradario.descrizione AS descvia,
        istanzestradario.codicecivico AS codicecivico,
        istanzestradario.civico AS civico,
        istanzestradario.colore AS colore,
        istanzestradario.frazione AS frazione,
        istanzestradario.circoscrizione AS circoscrizione,
        istanzestradario.cap AS cap,
        istanzestradario.km AS km,
        istanzestradario.esponente AS esponente,
        istanzestradario.scala AS scala,
        istanzestradario.interno AS interno,
        istanzestradario.esponenteinterno AS esponenteinterno,
        istanzestradario.fabbricato AS fabbricato,
        istanzestradario.piano AS piano,
        istanzestradario.quartiere AS quartiere,
        istanzestradario.id_punto_sit AS id_punto_sit,
        istanzestradario.uuid AS uuid,
        istanzestradario.latitudine AS latitudine,
        istanzestradario.longitudine AS longitudine,
        istanzestradario.accesso_tipo AS accesso_tipo,
        istanzestradario.accesso_numero AS accesso_numero,
        istanzestradario.accesso_descrizione AS accesso_descrizione
    FROM
        istanze
        JOIN istanzestradario ON istanzestradario.idcomune = istanze.idcomune
                                 AND istanzestradario.codiceistanza = istanze.codiceistanza
        INNER JOIN stradario ON stradario.idcomune = istanzestradario.idcomune
                                AND stradario.codicestradario = istanzestradario.codicestradario;

CREATE TABLE DOCUMENTI_AUTORIZZAZIONE (
    IDCOMUNE VARCHAR(6) NOT NULL,
    CODICEOGGETTO NUMERIC(10,0) NOT NULL,
    ID_AUTORIZZAZIONE NUMERIC(6,0) NOT NULL,
    FK_DOCUMENTIISTANZA NUMERIC(8,0),
    FK_MOVIMENTIALLEGATI NUMERIC(8,0),
    FK_ISTANZEALLEGATI NUMERIC(8,0),
    FK_ANAGRAFEDOCUMENTI NUMERIC(10,0),
    FK_ISTANZEPROCURE NUMERIC(10,0)
)ENGINE=INNODB DEFAULT CHARSET=utf8;

ALTER TABLE DOCUMENTI_AUTORIZZAZIONE ADD CONSTRAINT DOCUMENTI_AUTORIZZAZIONE_PK PRIMARY KEY (IDCOMUNE, CODICEOGGETTO, ID_AUTORIZZAZIONE);
ALTER TABLE DOCUMENTI_AUTORIZZAZIONE ADD CONSTRAINT FK_DOC_AUT_OGGETTI FOREIGN KEY (IDCOMUNE, CODICEOGGETTO) REFERENCES OGGETTI(IDCOMUNE, CODICEOGGETTO);
ALTER TABLE DOCUMENTI_AUTORIZZAZIONE ADD CONSTRAINT FK_DOC_AUT_AUT FOREIGN KEY (IDCOMUNE, ID_AUTORIZZAZIONE) REFERENCES AUTORIZZAZIONI(IDCOMUNE, ID);
ALTER TABLE DOCUMENTI_AUTORIZZAZIONE ADD CONSTRAINT FK_DOC_AUT_DOC_IST FOREIGN KEY (IDCOMUNE,FK_DOCUMENTIISTANZA) REFERENCES DOCUMENTIISTANZA(IDCOMUNE,ID);
ALTER TABLE DOCUMENTI_AUTORIZZAZIONE ADD CONSTRAINT FK_DOC_AUT_MOV_ALL FOREIGN KEY (IDCOMUNE,FK_MOVIMENTIALLEGATI) REFERENCES MOVIMENTIALLEGATI(IDCOMUNE,ID);
ALTER TABLE DOCUMENTI_AUTORIZZAZIONE ADD CONSTRAINT FK_DOC_AUT_IST_ALL FOREIGN KEY (IDCOMUNE,FK_ISTANZEALLEGATI) REFERENCES ISTANZEALLEGATI(IDCOMUNE,ID);
ALTER TABLE DOCUMENTI_AUTORIZZAZIONE ADD CONSTRAINT FK_DOC_AUT_DOC_ANAG FOREIGN KEY (IDCOMUNE,FK_ANAGRAFEDOCUMENTI) REFERENCES ANAGRAFEDOCUMENTI(IDCOMUNE,ID);
ALTER TABLE DOCUMENTI_AUTORIZZAZIONE ADD CONSTRAINT FK_DOC_AUT_IST_PROC FOREIGN KEY (IDCOMUNE,FK_ISTANZEPROCURE) REFERENCES ISTANZEPROCURE(IDCOMUNE,ID);




CREATE TABLE SPUNTISTI_MERCATI (
  IDCOMUNE VARCHAR(6) NOT NULL,
  ID NUMERIC(10,0) NOT NULL,
  FK_MERCATO NUMERIC(4,0) NOT NULL,
  FK_MERCATO_USO NUMERIC(4,0),
  FK_AUTORIZZAZIONE  NUMERIC(6,0) NOT NULL,
  FK_ISTANZA  NUMERIC(6,0),
  DATA_REGISTRAZIONE DATETIME NOT NULL,
   DATA_DISATTIVAZIONE  DATETIME,
  FLG_ATTIVO NUMERIC(1) NOT NULL
)ENGINE=INNODB DEFAULT CHARSET=utf8;

ALTER TABLE SPUNTISTI_MERCATI
  ADD CONSTRAINT SPUNTISTI_MERCATI_PK PRIMARY KEY (
    IDCOMUNE,
    ID
  );

ALTER TABLE SPUNTISTI_MERCATI
  ADD CONSTRAINT FK_SPUN_MERC_MERCATI FOREIGN KEY (
    IDCOMUNE,
    FK_MERCATO
  ) REFERENCES MERCATI (
    IDCOMUNE,
    CODICEMERCATO
  );

ALTER TABLE SPUNTISTI_MERCATI
  ADD CONSTRAINT FK_SPUN_MERC_MERCATI_U FOREIGN KEY (
    IDCOMUNE,
    FK_MERCATO_USO
  ) REFERENCES MERCATI_USO (
    IDCOMUNE,
    ID
  );
  
  ALTER TABLE SPUNTISTI_MERCATI
  ADD CONSTRAINT FK_SPUN_MERC_AUT FOREIGN KEY (
    IDCOMUNE,
    FK_AUTORIZZAZIONE
  ) REFERENCES AUTORIZZAZIONI (
    IDCOMUNE,
    ID
  );
  
  
ALTER TABLE SPUNTISTI_MERCATI
  ADD CONSTRAINT FK_SPUN_MERC_IST FOREIGN KEY (
    IDCOMUNE,
    FK_ISTANZA
) REFERENCES ISTANZE (
    IDCOMUNE,
    CODICEISTANZA
  );

ALTER TABLE ALBEROPROC ADD FLAG_GESTIONE_SPUNTISTI NUMERIC(1,0) default 0;

ALTER TABLE MERCATI_CONFIGURAZIONE ADD FK_D2CID_MERCATO_SPUNTA NUMERIC(10,0);
ALTER TABLE MERCATI_CONFIGURAZIONE ADD FK_D2CID_USO_SPUNTA NUMERIC(10,0);
ALTER TABLE MERCATI_CONFIGURAZIONE ADD FLAG_ATTIVA_GRAD_SPUNTISTI NUMERIC(1,0);
ALTER TABLE MERCATI_CONFIGURAZIONE ADD GG_ASSENZA NUMERIC(5,0);


ALTER TABLE MERCATI_CONFIGURAZIONE ADD CONSTRAINT FK_M_CFG_MERC_SPUNT FOREIGN KEY (IDCOMUNE,FK_D2CID_MERCATO_SPUNTA) REFERENCES DYN2_CAMPI (IDCOMUNE,ID);
ALTER TABLE MERCATI_CONFIGURAZIONE ADD CONSTRAINT FK_M_CFG_USO_SPUNT FOREIGN KEY (IDCOMUNE,FK_D2CID_USO_SPUNTA) REFERENCES DYN2_CAMPI (IDCOMUNE,ID);
