#PARAMETRI DI CONFIGURAZIONE

#dimensione massima in Mbyte del singolo file caricato
maxUploadSize=20

#moltiplicatore del valore maxUploadSize per stabilire la dimensione massima dell'insieme 
#dei file caricati durante la sessione di firma
uploadSizeFactor=5


#### nel caso che sia necessario settare https al posto di http
#### caso di regione umbria che hanno pubblicatore che fa le redirect su http
baseurl.override.scheme.https=
