ALTER TABLE RUOLI ADD COD_DOCER VARCHAR2(50);
ALTER TABLE RESPONSABILI ADD COD_UTE_DOCER VARCHAR2(30);
ALTER TABLE RESPONSABILI ADD PASSWORD_UTE_DOCER VARCHAR2(30);

CREATE TABLE OGGETTI_DOCER (
IDCOMUNE VARCHAR2(6) NOT NULL,
ID NUMBER(10,0) NOT NULL,
CODICEOGGETTO NUMBER(10) NOT NULL,
DOC_ID VARCHAR2(50),
UDOC_ID VARCHAR2(50)
);

ALTER TABLE OGGETTI_DOCER ADD CONSTRAINT PK_OGGETTIDOCER PRIMARY KEY(IDCOMUNE, ID);
ALTER TABLE OGGETTI_DOCER ADD CONSTRAINT FK_OGGETTIDOCER_OGGETTI FOREIGN KEY (IDCOMUNE, CODICEOGGETTO) REFERENCES OGGETTI (IDCOMUNE, CODICEOGGETTO);

CREATE TABLE METADATI_DIZ_BASE(
ID VARCHAR2(30) NOT NULL,
LABEL VARCHAR2(100) NOT NULL,
DESCRIZIONE VARCHAR2(500) 
);

ALTER TABLE METADATI_DIZ_BASE ADD CONSTRAINT PK_METADATIDIZBASE PRIMARY KEY(ID);

CREATE TABLE PROT_TIPIDOCUMENTO_METADATI(
IDCOMUNE VARCHAR2(6) NOT NULL,
FKIDPROTTPDOC NUMBER(10) NOT NULL,
FKIDMETADATIDIZBASE VARCHAR2(30) NOT NULL 
);

ALTER TABLE PROT_TIPIDOCUMENTO_METADATI ADD CONSTRAINT PK_TIPIDOCUMENTO_METADATI PRIMARY KEY (IDCOMUNE,FKIDPROTTPDOC,FKIDMETADATIDIZBASE);
ALTER TABLE PROT_TIPIDOCUMENTO_METADATI ADD CONSTRAINT FK_TIPIDOCUMENTOMD_TIPIDOC FOREIGN KEY (IDCOMUNE,FKIDPROTTPDOC) REFERENCES PROTOCOLLO_TIPIDOCUMENTO(IDCOMUNE,ID);
ALTER TABLE PROT_TIPIDOCUMENTO_METADATI ADD CONSTRAINT FK_TIPIDOCUMENTOMD_MDDZBASE FOREIGN KEY (FKIDMETADATIDIZBASE) REFERENCES METADATI_DIZ_BASE(ID);


ALTER TABLE DOCUMENTIISTANZA ADD ID_DOCER VARCHAR2(50);

ALTER TABLE TIPOLOGIAREGISTRI ADD COD_REGISTRO_DOCER VARCHAR2(50);
ALTER TABLE PROTOCOLLO_TIPIDOCUMENTO MODIFY CODICE VARCHAR2(30);

ALTER TABLE ARCHIVIAZIONI ADD SOFTWARE VARCHAR2(2 CHAR);
ALTER TABLE ARCHIVIAZIONI ADD CONSTRAINT FK_ARCHIVIAZIONI_SOFTWARE FOREIGN KEY (SOFTWARE) REFERENCES SOFTWARE (CODICE);
ALTER TABLE JOB_REPOSITORY ADD SOFTWARE VARCHAR2(2 CHAR);

CREATE TABLE DYN2_REGOLE 
(
  IDCOMUNE VARCHAR2(6) NOT NULL 
, ID NUMBER(10,0) NOT NULL 
, DESCRIZIONE VARCHAR2(200) NOT NULL 
, SOFTWARE VARCHAR2(2)
, CONSTRAINT DYN2_REGOLE_PK PRIMARY KEY 
  (
    IDCOMUNE 
  , ID 
  )
  ENABLE 
);

COMMENT ON TABLE DYN2_REGOLE IS 'TABELLA CHE MEMORIZZA LE REGOLE DA APPLICARE ALLE SCHEDE DINAMICHE. UNA REGOLA PUO'' ESSERE UTILIZZATA PER ATTIVARE UN CAMPO IN BASE AL VERIFICARSI DI UNA CONDIZIONE. IN FUTURO POTREBBERO ESSERE UTILIZZATE ANCHE PER RENDERE OBBLIGATORI I CAMPI IN MODO DINAMICO OPPURE EFFETTUARE DELLE VALIDAZIONI.';
COMMENT ON COLUMN DYN2_REGOLE.DESCRIZIONE IS 'BREVE DESCRIZIONE DELLA REGOLA VISUALIZZATA NELLE MASCHERE DI AMMINISTRAZIONE';

CREATE TABLE DYN2_ESPRESSIONI 
(
  IDCOMUNE VARCHAR2(6) NOT NULL 
, ID NUMBER(10,0) NOT NULL 
, FK_REGOLA NUMBER(10,0) NOT NULL 
, PROGRESSIVO NUMBER(3, 0) NOT NULL 
, OPERATORE_LOGICO VARCHAR2(5) 
, PARENTESI_APERTA VARCHAR2(1) 
, FK_CAMPO NUMBER(10,0)
, ATTRIBUTO_STC VARCHAR2(200) 
, ID_SEMANTICO_CART VARCHAR2(50) 
, OPERATORE_CONFRONTO VARCHAR2(20) DEFAULT 'EQ' NOT NULL 
, VALORE_CONFRONTO VARCHAR2(400)
, PARENTESI_CHIUSA VARCHAR2(1)
, CONSTRAINT DYN2_ESPRESSIONI_PK PRIMARY KEY 
  (
    IDCOMUNE 
  , ID 
  )
  ENABLE 
);

ALTER TABLE DYN2_ESPRESSIONI
ADD CONSTRAINT DYN2EXP_UK_PROGRESSIVO UNIQUE 
(
  IDCOMUNE 
, FK_REGOLA 
, PROGRESSIVO 
)
ENABLE;

ALTER TABLE DYN2_ESPRESSIONI ADD CONSTRAINT DYN2EXP_FK_REGOLE FOREIGN KEY (IDCOMUNE,FK_REGOLA) REFERENCES DYN2_REGOLE (IDCOMUNE,ID) ON DELETE CASCADE ENABLE;

ALTER TABLE DYN2_ESPRESSIONI ADD CONSTRAINT DYN2EXP_FK_CAMPO FOREIGN KEY (IDCOMUNE,FK_CAMPO) REFERENCES DYN2_CAMPI(IDCOMUNE,ID) ENABLE;
ALTER TABLE DYN2_ESPRESSIONI ADD CONSTRAINT DYN2EXP_CHK_OPCONFRONTO CHECK (OPERATORE_CONFRONTO IN ('EQ','NOT_EQ','GT','GT_EQ','LT','LT_EQ','IS_NULL','NOT_IS_NULL','IN','NOT_IN','MATCHES','NOT_MATCHES')) ENABLE;
ALTER TABLE DYN2_ESPRESSIONI ADD CONSTRAINT DYN2EXP_CHK_OPLOGICO CHECK (OPERATORE_LOGICO IN ('AND', 'OR')) ENABLE;

ALTER TABLE DYN2_ESPRESSIONI ADD CONSTRAINT DYN2EXP_CHK_PARAPERTA CHECK (PARENTESI_APERTA IN ('(')) ENABLE;

ALTER TABLE DYN2_ESPRESSIONI
ADD CONSTRAINT DYN2EXP_CHK_PARCHIUSA CHECK 
(PARENTESI_CHIUSA IN (')'))
ENABLE;

COMMENT ON TABLE DYN2_ESPRESSIONI IS 'OGNI REGOLA DEFINITA IN DYN2_REGOLE SARA'' COSTITUITA DA UNA O PIU'' ESPRESSIONI DEFINITE IN QUESTA TABELLA, ORDINATE PER PROGRESSIVO E COMBINATE FRA LORO CON OPERATORI LOGICI AND/OR';

COMMENT ON COLUMN DYN2_ESPRESSIONI.FK_REGOLA IS 'FK ALLA REGOLA A CUI APPARTIENE L''ESPRESSIONE';

COMMENT ON COLUMN DYN2_ESPRESSIONI.PROGRESSIVO IS 'LE ESPRESSIONI BOOLEANE CHE FANNO PARTE DI UNA REGOLA SONO VALUTATE IN ''ORDINE DI PROGRESSIVO CRESCENTE.';

COMMENT ON COLUMN DYN2_ESPRESSIONI.OPERATORE_LOGICO IS 'OPERATORE LOGICO AND/OR CON CUI QUESTA ESPRESSIONE SI LEGA ALLA PRECEDENTE';

COMMENT ON COLUMN DYN2_ESPRESSIONI.PARENTESI_APERTA IS 'IL VALORE ''('' APRE UNA PARENTESI NELL''ESPRESSIONE';

COMMENT ON COLUMN DYN2_ESPRESSIONI.FK_CAMPO IS 'FK AL CAMPO DINAMICO DI CUI VIENE VERIFICATO IL VALORE';

COMMENT ON COLUMN DYN2_ESPRESSIONI.ATTRIBUTO_STC IS 'ATTRIBUTO STATICO DELL''ISTANZA/DOMANDA DI CUI DEVE ESSERE VERIFICATO IL VALORE. L''ATTRIBUTO DEVE ESSERE SPECIFICATO CON NOTAZIONE XPATH FACENDO RIFERIMENTO ALLO SCHEMA XSD DI STC CONSIDERANDO COME ROOT L''ELEMENTO DettaglioPraticaType';

COMMENT ON COLUMN DYN2_ESPRESSIONI.ID_SEMANTICO_CART IS 'ATTRIBUTO DELLA DOMANDA CART DI CUI DEVE ESSERE VERIFICATO IL VALORE. DEVE ESSERE SPECIFICATO L''ID SEMANTICO DEL CAMPO DA VERIFICARE';

COMMENT ON COLUMN DYN2_ESPRESSIONI.OPERATORE_CONFRONTO IS 'OPERATORE DI CONFRONTO. VALORI POSSIBILI: ''EQ'',''NOT_EQ'',''GT'',''GT_EQ'',''LT'',''LT_EQ'',''IS_NULL'',''NOT_IS_NULL'',''IN'',''NOT_IN'',''MATCHES'',''NOT_MATCHES''';

COMMENT ON COLUMN DYN2_ESPRESSIONI.VALORE_CONFRONTO IS 'VALORE DA CONFRONTARE CON IL VALORE DEL CAMPO DINAMICO O DELL''ATTRIBUTO ISTANZA.
SE OPERATORE_CONFRONTO VALE ''NULL'' QUESTO CAMPO VIENE IGNORATO.
SE OPERATORE_CONFRONTO VALE ''IN'' SI POSSONO SPECIFICARE PIU'' DI UN VALORE SEPARANDOLI CON ''|''.
SE OPERATORE_CONFRONTO VALE ''MATCHES'' INSERIRE UNA REGEX CON SINTASSI JAVA ';

COMMENT ON COLUMN DYN2_ESPRESSIONI.PARENTESI_CHIUSA IS 'SPECIFICARE '')'' PER METTERE UNA PARENTESI CHIUSA DOPO QUESTA ESPRESSIONE';

ALTER TABLE DYN2_MODELLID ADD (FK_REGOLA_ATTIVO NUMBER(10,0) );

ALTER TABLE DYN2_MODELLID ADD (FLG_OBBLIGATORIO NUMBER(1, 0) DEFAULT 0 );

COMMENT ON COLUMN DYN2_MODELLID.FK_REGOLA_ATTIVO IS 'FK ALLA REGOLA PER L''ATTIVAZIONE DEL CAMPO O DEL TESTO.';
COMMENT ON COLUMN DYN2_MODELLID.FLG_OBBLIGATORIO IS 'FLAG 1/0 PER RENDERE OBBLIGATORIO IL CAMPO IN QUESTA SCHEDA. NON SI APPLICA AI TESTI.';

ALTER TABLE DYN2_MODELLID ADD CONSTRAINT FK_DYN2MODED_DYN2REG_ATT FOREIGN KEY ( IDCOMUNE, FK_REGOLA_ATTIVO) REFERENCES DYN2_REGOLE (IDCOMUNE, ID) ENABLE;

ALTER TABLE DYN2_MODELLID ADD CONSTRAINT DYN2MODED_CHK_FLGOBB CHECK (FLG_OBBLIGATORIO IN (0, 1)) ENABLE;

ALTER TABLE I_ATTIVITA MODIFY DENOMINAZIONE VARCHAR2(700 BYTE);
ALTER TABLE I_ATTIVITA_SNAPSHOT MODIFY DENOMINAZIONE VARCHAR2(700 BYTE);

CREATE TABLE ELENCOCASSAEDILEBASE(
  CODICE VARCHAR2(4) NOT NULL,
  DESCRIZIONE VARCHAR2(100)
);
ALTER TABLE ELENCOCASSAEDILEBASE ADD CONSTRAINT PK_ELENCOCASSAEDILEBASE PRIMARY KEY (CODICE);

ALTER TABLE ANAGRAFE ADD CASSAEDILE_MATRICOLA VARCHAR2(10);

ALTER TABLE ANAGRAFE ADD CASSAEDILE_CODICESEDE VARCHAR2(4);

ALTER TABLE ANAGRAFESTORICO ADD CASSAEDILE_MATRICOLA VARCHAR2(10);

ALTER TABLE ANAGRAFESTORICO ADD CASSAEDILE_CODICESEDE  VARCHAR2(4);


ALTER TABLE ANAGRAFE ADD CONSTRAINT FK_ANAG_ELENCOCASSAEDILE FOREIGN KEY (CASSAEDILE_CODICESEDE) REFERENCES ELENCOCASSAEDILEBASE (CODICE);

ALTER TABLE ANAGRAFESTORICO ADD CONSTRAINT FK_ANAGSTO_ELENCOCASSAEDILE FOREIGN KEY (CASSAEDILE_CODICESEDE) REFERENCES ELENCOCASSAEDILEBASE (CODICE);
