ALTER TABLE ALBEROPROC_ENDO ADD NOTE VARCHAR(2000) ;

ALTER TABLE INVENTARIOPROCEDIMENTI ADD FLAG_RICHIEDEENDO NUMERIC(1,0) DEFAULT 0;
ALTER TABLE ALBEROPROC_ENDO  ADD FLAG_RICHIEDEENDO NUMERIC(1) default 0;

CREATE TABLE SDEPROXY_STC
  (
    ALIAS            VARCHAR(20) NOT NULL,
    SOFTWARE         VARCHAR(2) NOT NULL,
    URL_STC          VARCHAR(255),
    IDNODO_MITT      VARCHAR(10),
    IDENTE_MITT      VARCHAR(20) ,
    IDSPORTELLO_MITT VARCHAR(10),
    USERNAME         VARCHAR(30),
    PASSWORD         VARCHAR(30),
    IDNODO_DEST      VARCHAR(10),
    IDENTE_DEST      VARCHAR(20) ,
    IDSPORTELLO_DEST VARCHAR(10)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE SDEPROXY_STC ADD CONSTRAINT PK_SDEPROXYSTC PRIMARY KEY (ALIAS, SOFTWARE);
ALTER TABLE RESPONSABILI ADD CIRCOSCRIZIONE VARCHAR(50);

ALTER TABLE SDEPROXY ADD WS_SERVIZI VARCHAR(255);
ALTER TABLE SDEPROXY ADD ALIAS_WS_SERVIZI VARCHAR(20);


CREATE TABLE MASTERKEY(
TABLENAME  NOT NULL VARCHAR(40), 
COLUMNNAME NOT NULL VARCHAR(40)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
Alter table masterkey add constraint MASTERKEY_PK primary key(TABLENAME, COLUMNNAME);

ALTER TABLE dyn2_modellid ADD flg_spezza_tabella numeric(1,0);