SET IMPLICIT_TRANSACTIONS ON
GO
ALTER TABLE AREE ALTER COLUMN CODICEAREA NUMERIC(8,0)
GO
COMMIT
GO
ALTER TABLE AREEDETTAGLI ALTER COLUMN CODICEAREA NUMERIC(8,0)
GO
COMMIT
GO
ALTER TABLE AREE2 ALTER COLUMN CODICEAREA NUMERIC(8,0)
GO
COMMIT
GO
ALTER TABLE CC_COEFFCONTRIBUTO ALTER COLUMN FK_AREE_CODICEAREA NUMERIC(8,0)
GO
COMMIT
GO
ALTER TABLE CC_ICALCOLO_DCONTRIBUTO ALTER COLUMN FK_AREE_CODICEAREA NUMERIC(8,0)
GO
COMMIT
GO
ALTER TABLE ISTANZE ALTER COLUMN CODICEAREA NUMERIC(8,0)
GO
COMMIT
GO
ALTER TABLE ISTANZE ALTER COLUMN CODICEAREA2 NUMERIC(8,0)
GO
COMMIT
GO
ALTER TABLE ISTANZEAREE ALTER COLUMN CODICEAREA  NUMERIC(8,0)
GO
COMMIT
GO
ALTER TABLE O_ICALCOLOCONTRIBT ALTER COLUMN FK_AREE_CODICEAREA_ZTO NUMERIC(8,0)
GO
COMMIT
GO
ALTER TABLE O_ICALCOLOCONTRIBT ALTER COLUMN FK_AREE_CODICEAREA_PRG NUMERIC(8,0)
GO
COMMIT
GO
CREATE INDEX IDX_AUTCONC_001 ON AUTORIZZAZIONI_CONCESSIONI(IDCOMUNE,FK_CODICEMERCATO,FK_IDPOSTEGGIO)
GO
COMMIT
GO
CREATE INDEX IDX_AUTCONC_002 ON AUTORIZZAZIONI_CONCESSIONI(IDCOMUNE,FK_CODICEMERCATO,FK_IDMERCATIUSO,FK_IDPOSTEGGIO)
GO
COMMIT
GO
CREATE INDEX IDX_AUTCONC_003 ON AUTORIZZAZIONI_CONCESSIONI(IDCOMUNE,FK_IDPOSTEGGIO)
GO
COMMIT
GO
ALTER TABLE TIPIMOV_STC_ALTRIDATI ALTER COLUMN NOME_CAMPO VARCHAR(100)
GO
COMMIT
GO
ALTER TABLE INVENTARIOPROCEDIMENTIPEOPLE ADD ID NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE TIPIMOV_STC_MAPPING ADD NONINVIAREPROCEDIMENTI NUMERIC(1,0)
GO
COMMIT
GO
ALTER TABLE AMMINISTRAZIONI ALTER COLUMN EMAIL VARCHAR(320)
GO
COMMIT
GO
ALTER TABLE AMMINISTRAZIONI ALTER COLUMN PEC VARCHAR(320)
GO
COMMIT
GO
ALTER TABLE ANAGRAFE ALTER COLUMN EMAIL VARCHAR(320)
GO
COMMIT
GO
ALTER TABLE ANAGRAFE ALTER COLUMN PEC VARCHAR(320)
GO
COMMIT
GO
ALTER TABLE ANAGRAFESTORICO ALTER COLUMN EMAIL VARCHAR(320)
GO
COMMIT
GO
ALTER TABLE ANAGRAFESTORICO ALTER COLUMN PEC VARCHAR(320)
GO
COMMIT
GO
ALTER TABLE CDSINVITATI ALTER COLUMN CODICEINVITATO NUMERIC(6, 0) NULL
GO
COMMIT
GO
ALTER TABLE ISTANZEEVENTI ALTER COLUMN DESCRIZIONE VARCHAR(4000);
GO
COMMIT
GO
CREATE TABLE FO_VISURA_CONTESTI_BASE 
(
  ID VARCHAR(50) NOT NULL 
, CONTESTO VARCHAR(150) NOT NULL 
, CONSTRAINT FO_VISURA_CONTESTI_BASE_PK PRIMARY KEY 
  (
    ID 
  )
)
GO
COMMIT
GO
CREATE TABLE FO_VISURA_CAMPI_BASE 
(
  ID VARCHAR(50) NOT NULL 
, CAMPO VARCHAR(150) NOT NULL 
, CONSTRAINT FO_VISURA_CAMPI_BASE_PK PRIMARY KEY 
  (
    ID 
  )
)
GO
COMMIT
GO
CREATE TABLE FO_VISURA_CONTESTI_CAMPI_BASE 
(
  FKIDCONTESTO VARCHAR(50) NOT NULL 
, FKIDCAMPO VARCHAR(50) NOT NULL 
, CONSTRAINT FO_VISURA_CONTESTI_CAMPI__PK PRIMARY KEY 
  (
    FKIDCONTESTO 
  , FKIDCAMPO 
  )
)
GO
COMMIT
GO
create TABLE FO_VISURA_CAMPI 
(
  IDCOMUNE varchar(6) not null,
  SOFTWARE varchar(2) not null,
  FKIDCONTESTO VARCHAR(50) NOT NULL 
, FKIDCAMPO VARCHAR(50) NOT NULL 
, POSIZIONE numeric(3) 
, CONSTRAINT FO_VISURA_CAMPI_PK PRIMARY KEY 
  (
    IDCOMUNE,
    SOFTWARE,
    FKIDCONTESTO,
    FKIDCAMPO 
  )
)
GO
COMMIT
GO
ALTER TABLE FO_VISURA_CONTESTI_CAMPI_BASE
ADD CONSTRAINT FO_VISURA_CONTESTI_CAMPI__FK1 FOREIGN KEY
(
  FKIDCAMPO 
)
REFERENCES FO_VISURA_CAMPI_BASE
(
  ID 
)
GO
COMMIT
GO
ALTER TABLE FO_VISURA_CONTESTI_CAMPI_BASE
ADD CONSTRAINT FO_VISURA_CONTESTI_CAMPI__FK2 FOREIGN KEY
(
  FKIDCONTESTO 
)
REFERENCES FO_VISURA_CONTESTI_BASE
(
  ID 
)
GO
COMMIT
GO
ALTER TABLE FO_VISURA_CAMPI
ADD CONSTRAINT FO_VISURA_CAMPI__FK1 FOREIGN KEY
(
  FKIDCAMPO 
)
REFERENCES FO_VISURA_CAMPI_BASE
(
  ID 
)
GO
COMMIT
GO
ALTER TABLE FO_VISURA_CAMPI
ADD CONSTRAINT FO_VISURA_CAMPI__FK2 FOREIGN KEY
(
  FKIDCONTESTO 
)
REFERENCES FO_VISURA_CONTESTI_BASE
(
  ID 
)
GO
COMMIT
GO
ALTER TABLE STILI ADD CONSTRAINT STILI_PK PRIMARY KEY (ST_ID)
GO
COMMIT
GO
ALTER TABLE INVENTARIOPROCEDIMENTIPEOPLE ALTER COLUMN COD_PROC_PEOPLE VARCHAR(50)
GO
COMMIT
GO