ALTER TABLE PROTOCOLLO_MEZZI ADD (ID NUMERIC(10) );
ALTER TABLE PROTOCOLLO_MODALITAINVIO ADD (ID NUMERIC(10) );
ALTER TABLE PROTOCOLLO_SEQUENZE ADD (ID NUMERIC(10) );
ALTER TABLE PROTOCOLLO_SMISTAMENTI ADD (ID NUMERIC(10) );
ALTER TABLE PROTOCOLLO_TIPIDOCUMENTO ADD (ID NUMERIC(10) );
ALTER TABLE PROTOCOLLO_UFFICIREGISTRI ADD (ID NUMERIC(10) );