//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Init.Sigepro.FrontEnd.Reserved.GestioneMovimenti {
    
    
    public partial class EffettuaMovimento {
        
        /// <summary>
        /// ltrDescrizioneStep control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltrDescrizioneStep;
        
        /// <summary>
        /// lblMovimento control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.LabeledLabel lblMovimento;
        
        /// <summary>
        /// lblDataMovimento control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.LabeledLabel lblDataMovimento;
        
        /// <summary>
        /// lblProtocolloMovimento control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.LabeledLabel lblProtocolloMovimento;
        
        /// <summary>
        /// lblDataProtocollo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.LabeledLabel lblDataProtocollo;
        
        /// <summary>
        /// lblProcedimento control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.LabeledLabel lblProcedimento;
        
        /// <summary>
        /// lblAmministrazione control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.LabeledLabel lblAmministrazione;
        
        /// <summary>
        /// LabeledLabel1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.LabeledLabel LabeledLabel1;
        
        /// <summary>
        /// LabeledLabel2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.LabeledLabel LabeledLabel2;
        
        /// <summary>
        /// LabeledLabel3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.LabeledLabel LabeledLabel3;
        
        /// <summary>
        /// LabeledLabel4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.LabeledLabel LabeledLabel4;
        
        /// <summary>
        /// rptSchedeMovimento control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater rptSchedeMovimento;
        
        /// <summary>
        /// dgAllegatiMovimento control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView dgAllegatiMovimento;
        
        /// <summary>
        /// cmdProcedi control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button cmdProcedi;
    }
}
