CREATE TABLE MOVIMENTI_ATTI  (
  IDCOMUNE VARCHAR2(6) NOT NULL, 
  ID NUMBER(10,0) NOT NULL,
  DATA_RICHIESTA_ATTO DATE NOT NULL,
  DATA_RICEZIONE_ATTO DATE,
  ID_DOCUMENTO NUMBER (6,0) NOT NULL ,
  NUMERO NUMBER (6,0) NOT NULL,
  ANNO NUMBER (4,0) NOT NULL,
  TIPO_DOCUMENTO VARCHAR2(4) NOT NULL,
  STATO NUMBER (1,0) NOT NULL,
  FK_MOVIMENTO NUMBER (8,0) NOT NULL
);

CREATE UNIQUE INDEX MOVIMENTI_ATTI_PK ON MOVIMENTI_ATTI (IDCOMUNE, ID) ; 
ALTER TABLE MOVIMENTI_ATTI ADD CONSTRAINT MOVIMENTI_ATTI_PK PRIMARY KEY (IDCOMUNE, ID);
ALTER TABLE MOVIMENTI_ATTI ADD CONSTRAINT FK_MOV_ATTI FOREIGN KEY (IDCOMUNE, FK_MOVIMENTO) REFERENCES MOVIMENTI (IDCOMUNE, CODICEMOVIMENTO);

ALTER TABLE TMP_ISTANZEONERI MODIFY ENDO VARCHAR2(500 CHAR);

CREATE OR REPLACE VIEW VW_LISTAPRATICHE AS 
SELECT 
  ISTANZE.CODICECOMUNE,
  ISTANZE.IDCOMUNE, 
  ISTANZE.SOFTWARE AS SOFTWARE,
  SOFTWARE.DESCRIZIONELUNGA AS DESCSOFTWARE,
  ISTANZE.CODICEISTANZA AS IDPRATICA,
  ISTANZE.NUMEROISTANZA AS NUMEROPRATICA, 
  TO_CHAR(ISTANZE.DATA,'DD/MM/YYYY') AS DATAPRESENTAZIONE, 
  TO_CHAR(ISTANZE.DATA,'YYYY') AS ANNOPRESENTAZIONE, 
  TO_CHAR(ISTANZE.DATA,'MM') AS MESEPRESENTAZIONE, 
  ISTANZE.NUMEROPROTOCOLLO, 
  TO_CHAR(ISTANZE.DATAPROTOCOLLO,'DD/MM/YYYY') AS DATAPROTOCOLLO, 
  ISTANZE.CODICEINTERVENTOPROC AS CODICEINTERVENTO, 
  VW_ALBEROPROC.SC_DESCRIZIONE AS DESCRIZIONEINTERVENTO, 
  TIPIPROCEDURE.CODICEPROCEDURA, 
  TIPIPROCEDURE.PROCEDURA, 
  ISTANZE.LAVORI AS OGGETTO, 
  UPPER(ISTANZE.LAVORI) AS OGGETTOU, 
  ISTANZE.CHIUSURA AS CODSTATOPRATICA, 
  STATO AS STATOPRATICA, 
  RESPONSABILI.RESPONSABILE, 
  RESPONSABILI.TELEFONOLAVORO AS RESPONSABILE_TELEFONO, 
  NVL(STRADARIO.CODVIARIO,STRADARIO.CODICESTRADARIO) AS PR_CODVIARIO, 
  STRADARIO.PREFISSO || ' ' || STRADARIO.DESCRIZIONE AS PR_INDIRIZZO, 
  ISTANZESTRADARIO.CODICECIVICO AS PR_CODCIVICO, 
  ISTANZESTRADARIO.CIVICO AS PR_CIVICO, 
  ISTANZE.CODICEAREA AS CODICEZONIZZAZIONE, 
  AREE.DENOMINAZIONE AS ZONIZZAZIONE, 
  ANAGRAFE.CODICEANAGRAFE AS CODICERICHIEDENTE, 
  NVL(UPPER(ANAGRAFE.CODICEFISCALE), '') AS CODICEFISCALE, 
  NVL(ANAGRAFE.PARTITAIVA, '') AS PARTITAIVA,
  ANAGRAFE.NOMINATIVO || ' ' || ANAGRAFE.NOME AS NOMINATIVO,
  ANAGRAFE.INDIRIZZO,
  ANAGRAFE.CAP,
  ANAGRAFE.CITTA AS LOCALITA,
  COMUNERESIDENZA.COMUNE AS CITTA,
  COMUNERESIDENZA.PROVINCIA,
  TIPISOGGETTO.TIPOSOGGETTO AS TIPORAPPORTO,
 CATASTO.DESCRIZIONE AS TIPOCATASTO,
  ISTANZEMAPPALI.FOGLIO,
  ISTANZEMAPPALI.PARTICELLA,
  ISTANZEMAPPALI.SUB,
  TECNICO.CODICEANAGRAFE AS TEC_CODICE,
  TECNICO.NOMINATIVO || ' ' || TECNICO.NOME AS TEC_NOMINATIVO,
  NVL(UPPER(TECNICO.CODICEFISCALE), '') AS TEC_CODICEFISCALE,
  NVL(TECNICO.PARTITAIVA, '') AS TEC_PARTITAIVA,
  AZIENDA.CODICEANAGRAFE AS AZ_CODICE,
  AZIENDA.NOMINATIVO || ' ' || AZIENDA.NOME AS AZ_NOMINATIVO,
  NVL(UPPER(AZIENDA.CODICEFISCALE), '') AS AZ_CODICEFISCALE,
  NVL(AZIENDA.PARTITAIVA, '') AS AZ_PARTITAIVA,
  ISTRUTTORI.RESPONSABILE AS ISTRUTTORE,
  ISTRUTTORI.TELEFONOLAVORO AS ISTRUTTORE_TELEFONO,
  OPERATORI.RESPONSABILE AS OPERATORE,
  OPERATORI.TELEFONOLAVORO AS OPERATORE_TELEFONO,
  ISTANZE.DOMICILIO_ELETTRONICO AS DOMICILIO_ELETTRONICO,
  DOMANDESTC.ID_SPORTELLOMITT,
  DOMANDESTC.ID_DOMANDAMITT
FROM 
  ISTANZE 
                INNER JOIN SOFTWARE ON SOFTWARE.CODICE = ISTANZE.SOFTWARE
                INNER JOIN ANAGRAFE ON ANAGRAFE.IDCOMUNE = ISTANZE.IDCOMUNE AND ANAGRAFE.CODICEANAGRAFE = ISTANZE.CODICERICHIEDENTE
                INNER JOIN STATIISTANZA ON STATIISTANZA.IDCOMUNE = ISTANZE.IDCOMUNE AND STATIISTANZA.SOFTWARE = ISTANZE.SOFTWARE AND STATIISTANZA.CODICESTATO = ISTANZE.CHIUSURA
                INNER JOIN VW_ALBEROPROC ON VW_ALBEROPROC.IDCOMUNE = ISTANZE.IDCOMUNE AND VW_ALBEROPROC.SC_ID = ISTANZE.CODICEINTERVENTOPROC
                LEFT JOIN ANAGRAFE TECNICO ON TECNICO.IDCOMUNE = ISTANZE.IDCOMUNE AND TECNICO.CODICEANAGRAFE = ISTANZE.CODICEPROFESSIONISTA
                LEFT JOIN ANAGRAFE AZIENDA ON ISTANZE.IDCOMUNE = AZIENDA.IDCOMUNE AND ISTANZE.CODICETITOLARELEGALE = AZIENDA.CODICEANAGRAFE
                LEFT JOIN ISTANZESTRADARIO ON ISTANZE.IDCOMUNE = ISTANZESTRADARIO.IDCOMUNE AND ISTANZE.CODICEISTANZA = ISTANZESTRADARIO.CODICEISTANZA AND 1 = ISTANZESTRADARIO.PRIMARIO
                LEFT JOIN STRADARIO ON STRADARIO.IDCOMUNE = ISTANZESTRADARIO.IDCOMUNE AND STRADARIO.CODICESTRADARIO = ISTANZESTRADARIO.CODICESTRADARIO
                LEFT JOIN ISTANZEMAPPALI ON ISTANZE.IDCOMUNE = ISTANZEMAPPALI.IDCOMUNE AND ISTANZE.CODICEISTANZA = ISTANZEMAPPALI.FKCODICEISTANZA AND 1 = ISTANZEMAPPALI.PRIMARIO
                LEFT JOIN RESPONSABILI ON ISTANZE.IDCOMUNE = RESPONSABILI.IDCOMUNE AND ISTANZE.CODICERESPONSABILEPROC = RESPONSABILI.CODICERESPONSABILE
                LEFT JOIN COMUNI COMUNERESIDENZA ON ANAGRAFE.COMUNERESIDENZA = COMUNERESIDENZA.CODICECOMUNE
                LEFT JOIN TIPISOGGETTO ON ISTANZE.IDCOMUNE = TIPISOGGETTO.IDCOMUNE AND ISTANZE.FKCODICESOGGETTO = TIPISOGGETTO.CODICETIPOSOGGETTO
                LEFT JOIN AREE ON ISTANZE.IDCOMUNE = AREE.IDCOMUNE AND ISTANZE.CODICEAREA = AREE.CODICEAREA
                LEFT JOIN CATASTO ON ISTANZEMAPPALI.CODICECATASTO = CATASTO.CODICE
                LEFT JOIN TIPIPROCEDURE ON ISTANZE.IDCOMUNE = TIPIPROCEDURE.IDCOMUNE AND ISTANZE.CODICEPROCEDURA = TIPIPROCEDURE.CODICEPROCEDURA
                LEFT JOIN RESPONSABILI ISTRUTTORI ON ISTANZE.IDCOMUNE = ISTRUTTORI.IDCOMUNE AND ISTANZE.CODICEISTRUTTORE = ISTRUTTORI.CODICERESPONSABILE
                LEFT JOIN RESPONSABILI OPERATORI ON OPERATORI.IDCOMUNE = ISTANZE.IDCOMUNE AND OPERATORI.CODICERESPONSABILE = ISTANZE.CODICERESPONSABILE
                LEFT JOIN DOMANDESTC ON ISTANZE.IDCOMUNE = DOMANDESTC.IDCOMUNE AND ISTANZE.CODICEISTANZA = DOMANDESTC.CODICEISTANZA;
                
ALTER TABLE TIPIMOVIMENTO ADD (FLAG_RIPORTA_PROT_ISTANZA NUMBER(1,0) );
                
                
CREATE TABLE ALBEROPROC_TIPISOG_BACK  (
  IDCOMUNE VARCHAR2(6) NOT NULL, 
  ID NUMBER(10,0) NOT NULL,
  FK_SCID NUMBER (10,0) NOT NULL,
  FK_TIPISOGGETTO NUMBER (10,0) NOT NULL
);

CREATE UNIQUE INDEX ALBEROPROC_TIPISOG_BACK_PK ON ALBEROPROC_TIPISOG_BACK (IDCOMUNE, ID) ; 
ALTER TABLE ALBEROPROC_TIPISOG_BACK ADD CONSTRAINT ALBEROPROC_TIPISOG_BACK_PK PRIMARY KEY (IDCOMUNE, ID);

ALTER TABLE ALBEROPROC_TIPISOG_BACK 
ADD CONSTRAINT FK_ALB_PROC_BACK_ALBERO_PROC FOREIGN KEY (IDCOMUNE, FK_SCID)
REFERENCES ALBEROPROC (IDCOMUNE, SC_ID);


ALTER TABLE ALBEROPROC_TIPISOG_BACK 
ADD CONSTRAINT FK_ALB_PROC_BACK_TIPI_SOGG FOREIGN KEY (IDCOMUNE, FK_TIPISOGGETTO)
REFERENCES TIPISOGGETTO (IDCOMUNE, CODICETIPOSOGGETTO);

ALTER TABLE TIPIMOV_STC_MAPPING ADD (CODICE_MOV_RECUPERO_ALLEGATO VARCHAR2(8) );

COMMENT ON COLUMN TIPIMOV_STC_MAPPING.CODICE_MOV_RECUPERO_ALLEGATO  IS 'Rappresenta il codice del movimento da cui recuperare i documenti in caso di notifica automatica';

ALTER TABLE CLMENU_JAVA DROP COLUMN LAYOUTTESTI;
ALTER TABLE CLMENU_JAVA ADD LAYOUTTESTI VARCHAR(200);

CREATE TABLE TIPIMOVIMENTO_COMUNICAZIONI  (
  IDCOMUNE VARCHAR2(6) NOT NULL, 
  ID NUMBER(10,0) NOT NULL,
  FK_TIPOMOV VARCHAR2(8) NOT NULL,
  FK_MAILTIPO NUMBER(4,0) NOT NULL,
  FUNZIONE VARCHAR2(10)  NOT NULL
);

CREATE UNIQUE INDEX TIPIMOVIMENTO_COMUNICAZIONI_PK ON TIPIMOVIMENTO_COMUNICAZIONI (IDCOMUNE, ID) ; 
ALTER TABLE TIPIMOVIMENTO_COMUNICAZIONI ADD CONSTRAINT TIPIMOVIMENTO_COMUNICAZIONI_PK PRIMARY KEY (IDCOMUNE, ID);

ALTER TABLE TIPIMOVIMENTO_COMUNICAZIONI 
ADD CONSTRAINT FK_TIPIMOV_COM_TIPIMOV FOREIGN KEY (IDCOMUNE, FK_TIPOMOV)
REFERENCES TIPIMOVIMENTO (IDCOMUNE, TIPOMOVIMENTO);


ALTER TABLE TIPIMOVIMENTO_COMUNICAZIONI 
ADD CONSTRAINT FK_TIPIMOV_COM_MAILTIPO FOREIGN KEY (IDCOMUNE, FK_MAILTIPO)
REFERENCES MAILTIPO (IDCOMUNE, CODICEMAIL);

ALTER TABLE RESPONSABILI ADD FLAG_EDITLABEL NUMBER(1,0) DEFAULT 0;

alter table INVENTARIOPROCEDIMENTI add FLAG_PUBBLICA number(1,0);
alter table TIPIENDO add FLAG_PUBBLICA number(1,0);
alter table TIPIFAMIGLIEENDO add FLAG_PUBBLICA number(1,0);

alter table TIPISOGGETTO add FLAG_MOSTRA_DETT_ISTANZA number(1,0) default 0;


INSERT INTO verticalizzazioniparametribase(modulo, parametro, descrizione) VALUES (
  'SIT_LDP',
  'URL_PRESENTAZIONE_DOMANDA',
  'Url per l''inserimento dei dati nel SIT LDP (es. http://siena.ldpgis.it/presentazione_pratiche_edilizie_online/index.php?identificativo_temporaneo={idDomanda}' || chr(38) || 'token_auth={token} )'
);
