<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Globals">

    <Configurations>Debug;Release</Configurations>
    <TargetFrameworks>net48</TargetFrameworks>
    <PackageId>PersonalLib2</PackageId>
    <LangVersion>preview</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Platforms>AnyCPU</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="log4net" Version="3.3.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.*" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.*" />
    <PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="17.14.15">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="MySqlConnector" Version="[2.2.7]" />
    <PackageReference Include="System.Text.Json" Version="10.0.*" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net48' ">
    <Reference Include="System.Data.OracleClient" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net10.0' ">
		<PackageReference Include="Oracle.ManagedDataAccess.Core" Version="[23.7.0]" />
  </ItemGroup>

</Project>