CREATE OR REPLACE VIEW VW_ISTANZECONCESSIONILISTA AS 
SELECT 99999999 AS PROGRESSIVO, AUTORIZZAZIONI.AUTORIZRESPONSABILE AS CONC_AUTORIZRESPONSABILE, AUTORIZZAZIONI.IDCOMUNE, AUTORIZZAZIONI.FK_CAUSALE_ACQUISIZIONE AS ICONC_CODICECAUSALE, NVL(AUTORIZZAZIONI.DATA_CESSAZIONE,TO_DATE('31/12/9999','DD/MM/YYYY')) AS DATA_STORICO, ISTANZE.SOFTWARE, ISTANZE.CODICEISTANZA AS IST_CODICEISTANZA, ISTANZE.NUMEROISTANZA AS IST_NUMEROISTANZA, ISTANZE.CODICERICHIEDENTE AS IST_CODICERICHIEDENTE, AUTORIZZAZIONI.ID AS CONC_ID, AUTORIZZAZIONI.AUTORIZNUMERO AS CONC_NUMERO, AUTORIZZAZIONI.AUTORIZDATA AS CONC_DATARILASCIO, AUTORIZZAZIONI.AUTORIZDATA AS DATARILASCIO, AUTORIZZAZIONI.DATASCADENZA AS CONC_DATASCADENZA, AUTORIZZAZIONI_CONCESSIONI.FK_TIPOCONCESSIONE AS CONC_CODICETIPO, CONCESSIONITIPI.DESCRIZIONE AS CONC_TIPO, AUTORIZZAZIONI_CONCESSIONI.STAGIONALEA AS CONC_STAGIONALEA, AUTORIZZAZIONI_CONCESSIONI.STAGIONALEDA AS CONC_STAGIONALEDA, AUTORIZZAZIONI.FLAG_ATTIVA AS CONC_ATTIVA, AUTORIZZAZIONI.FK_CODICEANAGRAFE AS CONC_CODICETITOLARE, AUTORIZZAZIONI.FKIDREGISTRO AS CONC_FKIDREGISTRO, CONC_REGISTRO.TR_DESCRIZIONE AS CONC_REGISTRO, TITOLARE.NOMINATIVO || ' ' || TITOLARE.NOME AS CONC_TITOLARE, TITOLARE.CODICEFISCALE AS CONC_TIT_CF, TITOLARE.PARTITAIVA AS CONC_TIT_PIVA, TITOLARE.TIPOANAGRAFE AS CONC_TIT_TIPOANAGRAFE, AUT_COLLEGATA.AUTORIZNUMERO AS AUT_NUMERO, AUT_COLLEGATA.AUTORIZDATA AS AUT_DATA, AUT_COLLEGATA.AUTORIZDATA, AUT_COLLEGATA.FKIDREGISTRO AS AUT_CODREGISTRO, TIPOLOGIAREGISTRI.TR_DESCRIZIONE AS AUT_REGISTRO, IST_RICHIEDENTE.NOMINATIVO || ' ' || IST_RICHIEDENTE.NOME AS IST_NOMINATIVO, IST_RICHIEDENTE.TIPOANAGRAFE AS IST_RIC_TIPOANAGRAFE, IST_AZIENDA.NOMINATIVO || ' ' || IST_AZIENDA.NOME AS IST_NOMINATIVOAZIENDA, IST_AZIENDA.TIPOANAGRAFE AS IST_AZI_TIPOANAGRAFE, IST_RICHIEDENTE.CODICEFISCALE AS IST_CODICEFISCALE, IST_RICHIEDENTE.PARTITAIVA AS IST_PARTITAIVA, CAUS_ATTUALE.DESCRIZIONE AS ICONC_CAUSALE, AUTORIZZAZIONI.FK_CAUSALE_CESSAZIONE AS ICONC_CODICECAUSALESTORICO, CAUS_STORICO.DESCRIZIONE AS ICONC_CAUSALESTORICO, AUTORIZZAZIONI_CONCESSIONI.FK_CODICEMERCATO AS CONC_IDMERCATO, MERCATI.DESCRIZIONE AS CONC_MERCATO, MERCATI.ATTIVO AS MERC_ATTIVO, AUTORIZZAZIONI_CONCESSIONI.FK_IDPOSTEGGIO AS CONC_IDPOSTEGGIO, MERCATI_D.CODICEPOSTEGGIO AS CONC_POSTEGGIO, MERCATI_D.LARGHEZZA AS CONC_POS_LARGHEZZA, MERCATI_D.LUNGHEZZA AS CONC_POS_LUNGHEZZA, MERCATI_D.SUPERFICIE AS CONC_POS_SUPERFICIE, MERCATI_D.FKCODICETIPOSPAZIO AS POST_IDTIPOSPAZIO, POSTEGGITIPOSPAZIO.TIPOSPAZIO AS POST_TIPOSPAZIO, AUTORIZZAZIONI_CONCESSIONI.FK_IDMERCATIUSO AS CONC_IDMERCATIUSO, MERCATI_USO.DESCRIZIONE AS CONC_DESCRIZIONEUSO, MERCATI_USO.PESO AS PESO_MERCATO, MERCATI_USO.FKCODICEUSO AS MERC_IDUSO, MERCATI_D.FKCODICESTRADARIO AS CONC_POS_CODICESTRADARIO, MERCATI_D.NOTE AS CONC_POS_NOTE FROM AUTORIZZAZIONI, AUTORIZZAZIONI_CONCESSIONI, AUTORIZZAZIONI AUT_COLLEGATA, CONCESSIONITIPI, TIPOLOGIAREGISTRI, TIPOLOGIAREGISTRI CONC_REGISTRO, ANAGRAFE TITOLARE, CONCESSIONICAUSALI CAUS_ATTUALE, CONCESSIONICAUSALI CAUS_STORICO, ISTANZE, ANAGRAFE IST_RICHIEDENTE, MERCATI, MERCATI_D, POSTEGGITIPOSPAZIO, MERCATI_USO, ANAGRAFE IST_AZIENDA WHERE CONC_REGISTRO.IDCOMUNE = AUTORIZZAZIONI.IDCOMUNE AND CONC_REGISTRO.TR_ID = AUTORIZZAZIONI.FKIDREGISTRO AND AUTORIZZAZIONI.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND AUTORIZZAZIONI.ID = AUTORIZZAZIONI_CONCESSIONI.FK_IDAUT_ATTUALE AND AUT_COLLEGATA.IDCOMUNE(+) = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND AUT_COLLEGATA.ID(+) = AUTORIZZAZIONI_CONCESSIONI.FK_IDAUT_COLLEGATA AND CONCESSIONITIPI.TIPOCONCESSIONE = AUTORIZZAZIONI_CONCESSIONI.FK_TIPOCONCESSIONE AND TIPOLOGIAREGISTRI.IDCOMUNE(+) = AUT_COLLEGATA.IDCOMUNE AND TIPOLOGIAREGISTRI.TR_ID(+) = AUT_COLLEGATA.FKIDREGISTRO AND TITOLARE.IDCOMUNE = AUTORIZZAZIONI.IDCOMUNE AND TITOLARE.CODICEANAGRAFE = AUTORIZZAZIONI.FK_CODICEANAGRAFE AND CAUS_ATTUALE.IDCOMUNE = AUTORIZZAZIONI.IDCOMUNE AND CAUS_ATTUALE.CODICECAUSALE = AUTORIZZAZIONI.FK_CAUSALE_ACQUISIZIONE AND CAUS_STORICO.IDCOMUNE(+) = AUTORIZZAZIONI.IDCOMUNE AND CAUS_STORICO.CODICECAUSALE(+) = AUTORIZZAZIONI.FK_CAUSALE_CESSAZIONE AND ISTANZE.IDCOMUNE = AUTORIZZAZIONI.IDCOMUNE AND ISTANZE.CODICEISTANZA = AUTORIZZAZIONI.FKIDISTANZA AND IST_RICHIEDENTE.IDCOMUNE = ISTANZE.IDCOMUNE AND IST_RICHIEDENTE.CODICEANAGRAFE = ISTANZE.CODICERICHIEDENTE AND MERCATI.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND MERCATI.CODICEMERCATO = AUTORIZZAZIONI_CONCESSIONI.FK_CODICEMERCATO AND MERCATI_D.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND MERCATI_D.IDPOSTEGGIO = AUTORIZZAZIONI_CONCESSIONI.FK_IDPOSTEGGIO AND POSTEGGITIPOSPAZIO.IDCOMUNE(+) = MERCATI_D.IDCOMUNE AND POSTEGGITIPOSPAZIO.CODICE(+) = MERCATI_D.FKCODICETIPOSPAZIO AND MERCATI_USO.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND MERCATI_USO.ID = AUTORIZZAZIONI_CONCESSIONI.FK_IDMERCATIUSO AND IST_AZIENDA.IDCOMUNE(+) = ISTANZE.IDCOMUNE AND IST_AZIENDA.CODICEANAGRAFE(+) = ISTANZE.CODICETITOLARELEGALE
UNION
SELECT AUTORIZZAZIONI_SUBENTRI.ID AS PROGRESSIVO, AUTORIZZAZIONI_SUBENTRI.AUTORIZRESPONSABILE AS CONC_AUTORIZRESPONSABILE, AUTORIZZAZIONI_SUBENTRI.IDCOMUNE, AUTORIZZAZIONI_SUBENTRI.FK_CAUSALE_ACQUISIZIONE AS ICONC_CODICECAUSALE, AUTORIZZAZIONI_SUBENTRI.DATA_CESSAZIONE AS DATA_STORICO, ISTANZE.SOFTWARE, ISTANZE.CODICEISTANZA AS IST_CODICEISTANZA, ISTANZE.NUMEROISTANZA AS IST_NUMEROISTANZA, ISTANZE.CODICERICHIEDENTE AS IST_CODICERICHIEDENTE, AUTORIZZAZIONI_SUBENTRI.FK_IDAUT_ATTUALE AS CONC_ID, AUTORIZZAZIONI_SUBENTRI.AUTORIZNUMERO AS CONC_NUMERO, AUTORIZZAZIONI_SUBENTRI.AUTORIZDATA AS CONC_DATARILASCIO, AUTORIZZAZIONI_SUBENTRI.AUTORIZDATA AS DATARILASCIO, AUTORIZZAZIONI_SUBENTRI.DATASCADENZA AS CONC_DATASCADENZA, AUTORIZZAZIONI_CONCESSIONI.FK_TIPOCONCESSIONE AS CONC_CODICETIPO, CONCESSIONITIPI.DESCRIZIONE AS CONC_TIPO, AUTORIZZAZIONI_CONCESSIONI.STAGIONALEA AS CONC_STAGIONALEA, AUTORIZZAZIONI_CONCESSIONI.STAGIONALEDA AS CONC_STAGIONALEDA, 0 AS CONC_ATTIVA, AUTORIZZAZIONI_SUBENTRI.FK_CODICEANAGRAFE AS CONC_CODICETITOLARE, AUTORIZZAZIONI_SUBENTRI.FKIDREGISTRO AS CONC_FKIDREGISTRO, CONC_REGISTRO.TR_DESCRIZIONE AS CONC_REGISTRO, TITOLARE.NOMINATIVO || ' ' || TITOLARE.NOME AS CONC_TITOLARE, TITOLARE.CODICEFISCALE AS CONC_TIT_CF, TITOLARE.PARTITAIVA AS CONC_TIT_PIVA, TITOLARE.TIPOANAGRAFE AS CONC_TIT_TIPOANAGRAFE, AUT_COLLEGATA.AUTORIZNUMERO AS AUT_NUMERO, AUT_COLLEGATA.AUTORIZDATA AS AUT_DATA, AUT_COLLEGATA.AUTORIZDATA, AUT_COLLEGATA.FKIDREGISTRO AS AUT_CODREGISTRO, TIPOLOGIAREGISTRI.TR_DESCRIZIONE AS AUT_REGISTRO, IST_RICHIEDENTE.NOMINATIVO || ' ' || IST_RICHIEDENTE.NOME AS IST_NOMINATIVO, IST_RICHIEDENTE.TIPOANAGRAFE AS IST_RIC_TIPOANAGRAFE, IST_AZIENDA.NOMINATIVO || ' ' || IST_AZIENDA.NOME AS IST_NOMINATIVOAZIENDA, IST_AZIENDA.TIPOANAGRAFE AS IST_AZI_TIPOANAGRAFE, IST_RICHIEDENTE.CODICEFISCALE AS IST_CODICEFISCALE, IST_RICHIEDENTE.PARTITAIVA AS IST_PARTITAIVA, CAUS_ATTUALE.DESCRIZIONE AS ICONC_CAUSALE, AUTORIZZAZIONI_SUBENTRI.FK_CAUSALE_CESSAZIONE AS ICONC_CODICECAUSALESTORICO, CAUS_STORICO.DESCRIZIONE AS ICONC_CAUSALESTORICO, AUTORIZZAZIONI_CONCESSIONI.FK_CODICEMERCATO AS CONC_IDMERCATO, MERCATI.DESCRIZIONE AS CONC_MERCATO, MERCATI.ATTIVO AS MERC_ATTIVO, AUTORIZZAZIONI_CONCESSIONI.FK_IDPOSTEGGIO AS CONC_IDPOSTEGGIO, MERCATI_D.CODICEPOSTEGGIO AS CONC_POSTEGGIO, MERCATI_D.LARGHEZZA AS CONC_POS_LARGHEZZA, MERCATI_D.LUNGHEZZA AS CONC_POS_LUNGHEZZA, MERCATI_D.SUPERFICIE AS CONC_POS_SUPERFICIE, MERCATI_D.FKCODICETIPOSPAZIO AS POST_IDTIPOSPAZIO, POSTEGGITIPOSPAZIO.TIPOSPAZIO AS POST_TIPOSPAZIO, AUTORIZZAZIONI_CONCESSIONI.FK_IDMERCATIUSO AS CONC_IDMERCATIUSO, MERCATI_USO.DESCRIZIONE AS CONC_DESCRIZIONEUSO, MERCATI_USO.PESO AS PESO_MERCATO, MERCATI_USO.FKCODICEUSO AS MERC_IDUSO, MERCATI_D.FKCODICESTRADARIO AS CONC_POS_CODICESTRADARIO, MERCATI_D.NOTE AS CONC_POS_NOTE FROM AUTORIZZAZIONI_SUBENTRI, AUTORIZZAZIONI_CONCESSIONI, AUTORIZZAZIONI AUT_COLLEGATA, CONCESSIONITIPI, TIPOLOGIAREGISTRI, TIPOLOGIAREGISTRI CONC_REGISTRO, ANAGRAFE TITOLARE, CONCESSIONICAUSALI CAUS_ATTUALE, CONCESSIONICAUSALI CAUS_STORICO, ISTANZE, ANAGRAFE IST_RICHIEDENTE, MERCATI, MERCATI_D, POSTEGGITIPOSPAZIO, MERCATI_USO, ANAGRAFE IST_AZIENDA WHERE CONC_REGISTRO.IDCOMUNE = AUTORIZZAZIONI_SUBENTRI.IDCOMUNE AND CONC_REGISTRO.TR_ID = AUTORIZZAZIONI_SUBENTRI.FKIDREGISTRO AND AUTORIZZAZIONI_SUBENTRI.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND AUTORIZZAZIONI_SUBENTRI.FK_IDAUT_ATTUALE = AUTORIZZAZIONI_CONCESSIONI.FK_IDAUT_ATTUALE AND AUT_COLLEGATA.IDCOMUNE(+) = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND AUT_COLLEGATA.ID(+) = AUTORIZZAZIONI_CONCESSIONI.FK_IDAUT_COLLEGATA AND CONCESSIONITIPI.TIPOCONCESSIONE = AUTORIZZAZIONI_CONCESSIONI.FK_TIPOCONCESSIONE AND TIPOLOGIAREGISTRI.IDCOMUNE(+) = AUT_COLLEGATA.IDCOMUNE AND TIPOLOGIAREGISTRI.TR_ID(+) = AUT_COLLEGATA.FKIDREGISTRO AND TITOLARE.IDCOMUNE = AUTORIZZAZIONI_SUBENTRI.IDCOMUNE AND TITOLARE.CODICEANAGRAFE = AUTORIZZAZIONI_SUBENTRI.FK_CODICEANAGRAFE AND CAUS_ATTUALE.IDCOMUNE = AUTORIZZAZIONI_SUBENTRI.IDCOMUNE AND CAUS_ATTUALE.CODICECAUSALE = AUTORIZZAZIONI_SUBENTRI.FK_CAUSALE_ACQUISIZIONE AND CAUS_STORICO.IDCOMUNE(+) = AUTORIZZAZIONI_SUBENTRI.IDCOMUNE AND CAUS_STORICO.CODICECAUSALE(+) = AUTORIZZAZIONI_SUBENTRI.FK_CAUSALE_CESSAZIONE AND ISTANZE.IDCOMUNE = AUTORIZZAZIONI_SUBENTRI.IDCOMUNE AND ISTANZE.CODICEISTANZA = AUTORIZZAZIONI_SUBENTRI.FKIDISTANZA AND IST_RICHIEDENTE.IDCOMUNE = ISTANZE.IDCOMUNE AND IST_RICHIEDENTE.CODICEANAGRAFE = ISTANZE.CODICERICHIEDENTE AND MERCATI.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND MERCATI.CODICEMERCATO = AUTORIZZAZIONI_CONCESSIONI.FK_CODICEMERCATO AND MERCATI_D.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND MERCATI_D.IDPOSTEGGIO = AUTORIZZAZIONI_CONCESSIONI.FK_IDPOSTEGGIO AND POSTEGGITIPOSPAZIO.IDCOMUNE(+) = MERCATI_D.IDCOMUNE AND POSTEGGITIPOSPAZIO.CODICE(+) = MERCATI_D.FKCODICETIPOSPAZIO AND MERCATI_USO.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND MERCATI_USO.ID = AUTORIZZAZIONI_CONCESSIONI.FK_IDMERCATIUSO AND IST_AZIENDA.IDCOMUNE(+) = ISTANZE.IDCOMUNE AND IST_AZIENDA.CODICEANAGRAFE(+) = ISTANZE.CODICETITOLARELEGALE;

CREATE OR REPLACE VIEW VW_CONCESSIONILISTA AS 
SELECT IDCOMUNE, SOFTWARE, PROGRESSIVO, CONC_ID, CONC_NUMERO, CONC_DATARILASCIO, CONC_DATASCADENZA, CONC_CODICETIPO, CONC_TIPO, CONC_STAGIONALEA, CONC_STAGIONALEDA, CONC_ATTIVA, CONC_CODICETITOLARE, CONC_TITOLARE, CONC_TIT_CF, CONC_TIT_PIVA, CONC_TIT_TIPOANAGRAFE, CONC_FKIDREGISTRO, CONC_REGISTRO, AUT_NUMERO, AUT_DATA, AUT_CODREGISTRO, AUT_REGISTRO, IST_CODICEISTANZA, IST_NUMEROISTANZA, IST_CODICERICHIEDENTE, IST_NOMINATIVO, IST_CODICEFISCALE, IST_PARTITAIVA, IST_RIC_TIPOANAGRAFE, ICONC_CODICECAUSALE, ICONC_CAUSALE, ICONC_CODICECAUSALESTORICO, ICONC_CAUSALESTORICO, CONC_IDMERCATO, CONC_MERCATO, MERC_ATTIVO, CONC_IDPOSTEGGIO, CONC_POSTEGGIO, CONC_POS_LARGHEZZA, CONC_POS_LUNGHEZZA, CONC_POS_SUPERFICIE, POST_IDTIPOSPAZIO, POST_TIPOSPAZIO, CONC_IDMERCATIUSO, CONC_DESCRIZIONEUSO, PESO_MERCATO, MERC_IDUSO, CONC_POS_CODICESTRADARIO, DATA_STORICO FROM VW_ISTANZECONCESSIONILISTA;

ALTER TABLE ISTANZESTRADARIO ADD ID_PUNTO_SIT VARCHAR2(50); 
COMMENT ON COLUMN ISTANZESTRADARIO.ID_PUNTO_SIT IS 'Contiene i riferimenti al sistema di geolocalizzazione';

ALTER TABLE COMUNIASSOCIATI ADD CODICE_ENTE_PAYER VARCHAR2(5); 
COMMENT ON COLUMN COMUNIASSOCIATI.CODICE_ENTE_PAYER IS 'Indica il valore che viene inviato da PayER nel tag Request_ResponseBase.codiceEnte. Serve al componente PAYER_ADAPTER per ricavare il codice comune e l''idcomune per selezionare i dati delle richieste.';

CREATE TABLE MERCATI_D2C_ASSEGNAZ 
(
  IDCOMUNE VARCHAR2(6) NOT NULL,
  ID NUMBER(10,0) NOT NULL,
  FKCODICEMERCATO NUMBER(4, 0) NOT NULL, 
  FK_D2C_ID NUMBER(10, 0) NOT NULL, 
  CONSTRAINT MERCATI_D2C_ASSEGNAZ_PK PRIMARY KEY 
  (
    IDCOMUNE, 
    ID 
  )
  ENABLE 
);

ALTER TABLE MERCATI_D2C_ASSEGNAZ ADD CONSTRAINT FK_MERC_D2C_ASS_MERCATI FOREIGN KEY(IDCOMUNE , FKCODICEMERCATO) REFERENCES MERCATI (IDCOMUNE, CODICEMERCATO );
ALTER TABLE MERCATI_D2C_ASSEGNAZ ADD CONSTRAINT FK_MERC_D2C_ASS_DYN2_CAMPI FOREIGN KEY (IDCOMUNE , FK_D2C_ID) REFERENCES DYN2_CAMPI (IDCOMUNE , ID);

ALTER TABLE MERCATI  ADD (FK_D2CID_PREF_USO NUMBER(10, 0) );
ALTER TABLE MERCATI ADD CONSTRAINT FK_MERCATI_DYN2_CAMPI FOREIGN KEY (IDCOMUNE , FK_D2CID_PREF_USO) REFERENCES DYN2_CAMPI (IDCOMUNE , ID);

ALTER TABLE MERCATI_D  ADD (PESO NUMBER(4, 0) );
CREATE TABLE MERCATI_D_CRITASS 
(
  IDCOMUNE VARCHAR2(6) NOT NULL,
  ID NUMBER(10,0) NOT NULL,
  FK_IDPOSTEGGIO NUMBER(6, 0) NOT NULL, 
  FK_D2C_ID NUMBER(10, 0) NOT NULL,
  VALORE VARCHAR2 (100) NOT NULL,
  VALOREDECODIFICATO VARCHAR2(100),
  FLAG_CONSENTITO NUMBER(1, 0), 
  CONSTRAINT MERCATI_D_CRITASS_PK PRIMARY KEY 
  (
    IDCOMUNE, 
    ID 
  )
  ENABLE 
);
ALTER TABLE MERCATI_D_CRITASS ADD CONSTRAINT FK_MERC_D_CRITASS_DYN2_CAMPI FOREIGN KEY (IDCOMUNE , FK_D2C_ID) REFERENCES DYN2_CAMPI(IDCOMUNE , ID);
ALTER TABLE MERCATI_D_CRITASS ADD CONSTRAINT FK_MERC_D_CRITASS_MERCATID FOREIGN KEY (IDCOMUNE , FK_IDPOSTEGGIO) REFERENCES MERCATI_D(IDCOMUNE , IDPOSTEGGIO);

CREATE TABLE COMUNIASSOCIAZIONI (CODICEASSOCIAZIONE VARCHAR2(5) NOT NULL, ASSOCIAZIONE VARCHAR2(128) NOT NULL);
ALTER TABLE COMUNIASSOCIAZIONI ADD (CONSTRAINT PK_COMASSOCIAZIONI PRIMARY KEY(CODICEASSOCIAZIONE));
CREATE OR REPLACE VIEW VW_ENTILOCALI AS SELECT CODICECOMUNE, COMUNE FROM COMUNI UNION SELECT CODICEASSOCIAZIONE AS CODICECOMUNE, ASSOCIAZIONE AS COMUNE FROM COMUNIASSOCIAZIONI;

ALTER TABLE AUTORIZZAZIONI DROP CONSTRAINT FK_AUTCOMUNI;
ALTER TABLE AUTORIZZAZIONI_SUBENTRI DROP CONSTRAINT FK_AUTSUB_COMUNI;

ALTER TABLE MERCATIPRESENZE_STORICO MODIFY(FKIDMERCATIUSO NULL);


CREATE TABLE FO_ARJ_STEPS_BASE (
  NOME_STEP VARCHAR2(50) NOT NULL,  
  LINK_FUNZIONE VARCHAR2(125) NOT NULL,
  TITOLO VARCHAR2(150) NOT NULL,
  DESCRIZIONE VARCHAR2(4000),
  FLAG_OBBLIGATORIO NUMBER(1,0),
  DIPENDE_DA_STEP VARCHAR2(50),  
  INCOMPATIBILE_CON_STEP VARCHAR2(50),
  ORDINE_DEFAULT NUMBER(2,0), 
PRIMARY KEY (NOME_STEP)
);

COMMENT ON TABLE FO_ARJ_STEPS_BASE IS 'Tabella di base che censisce le varie tipologie di step che l''area riservata puo'' gestire';
COMMENT ON column FO_ARJ_STEPS_BASE.NOME_STEP IS 'Identificativo parlante dello step Es. ANAGRAFICHE';
COMMENT ON column FO_ARJ_STEPS_BASE.LINK_FUNZIONE IS 'Specifica l''url alla funzionalita'' dell''applicativo areariservata';
COMMENT ON column FO_ARJ_STEPS_BASE.TITOLO IS 'Rappresenta il titolo predefinito della funzionalita''. Puo'' essere sovrascritto in FO_ARJ_STEPS.TITOLO';
COMMENT ON column FO_ARJ_STEPS_BASE.DESCRIZIONE IS 'Rappresenta la descrizione predefinita della funzionalita''. Puo'' essere sovrascritta in FO_ARJ_STEPS.DESCRIZIONE';
COMMENT ON column FO_ARJ_STEPS_BASE.FLAG_OBBLIGATORIO IS 'Indica se lo step e'' obbligatorio e deve comunque essere sempre presente';
COMMENT ON column FO_ARJ_STEPS_BASE.DIPENDE_DA_STEP IS 'Indica se lo step puo'' essere istanziato indipendentemente da altri o deve necessariamente essere inserito dopo un''altro step';

ALTER TABLE FO_ARJ_STEPS ADD FK_NOME_STEP_BASE VARCHAR2(50);
ALTER TABLE FO_ARJ_STEPS ADD CONSTRAINT FK_FASNOMESTEP_FASBNOMESTEP FOREIGN KEY (FK_NOME_STEP_BASE) REFERENCES FO_ARJ_STEPS_BASE(NOME_STEP);

CREATE TABLE FO_ARJ_STEPS_PARAMS_BASE(
  CHIAVE  VARCHAR2(200 CHAR),
  DESCRIZIONE VARCHAR2(500 CHAR),
  PRIMARY KEY(CHIAVE)
);

ALTER TABLE FO_ARJ_STEPS_PARAMS ADD CONSTRAINT FK_FASPCHIAVE_FASPB_CHIAVE FOREIGN KEY(CHIAVE) REFERENCES FO_ARJ_STEPS_PARAMS_BASE (CHIAVE);

ALTER TABLE FO_ARCONFIGURAZIONE ADD FK_FOARJSTEPSTEST_ID NUMBER(6,0);

ALTER TABLE FO_ARCONFIGURAZIONE ADD CONSTRAINT FK_FOAC_FOARJST_ID FOREIGN KEY (IDCOMUNE,FK_FOARJSTEPSTEST_ID) REFERENCES FO_ARJ_STEPS_TESTATA(IDCOMUNE,ID);


CREATE TABLE I_ATTIVITA_TIPOLOGIE(
IDCOMUNE VARCHAR2(6) NOT NULL
,ID NUMBER(4,0) NOT NULL
,DESCRIZIONE VARCHAR2(100)
,SOFTWARE VARCHAR2(2)
, PRIMARY KEY (IDCOMUNE, ID)
);

COMMENT ON TABLE I_ATTIVITA_TIPOLOGIE IS 'TABELLA CHE CENSISCE E TIPOLOGIE DELL''ATTIVITA';
ALTER TABLE I_ATTIVITA ADD FK_IATIPOLOGIE_ID NUMBER(4,0);
COMMENT ON COLUMN I_ATTIVITA.FK_IATIPOLOGIE_ID IS 'IDENTIFICA LA TIPOLOGIA DELL''ATTIVITA''. CHIAVE ESTERNA VERSO LA TABELLA I_ATTIVITA_TIPOLOGIE ';
ALTER TABLE I_ATTIVITA ADD CONSTRAINT FK_IATT_IATIPOLOGIEID FOREIGN KEY (IDCOMUNE,FK_IATIPOLOGIE_ID ) REFERENCES I_ATTIVITA_TIPOLOGIE (IDCOMUNE,ID);
ALTER TABLE I_ATTIVITA_TIPOLOGIE ADD CONSTRAINT FK_IAT_TIPOLOGIE_SOFTWARE FOREIGN KEY (SOFTWARE) REFERENCES SOFTWARE (CODICE);

ALTER TABLE I_ATTIVITA_SNAPSHOT ADD FK_IATIPOLOGIE_ID NUMBER(4,0);
COMMENT ON COLUMN I_ATTIVITA_SNAPSHOT.FK_IATIPOLOGIE_ID IS 'IDENTIFICA LA TIPOLOGIA DELL''ATTIVITA''. CHIAVE ESTERNA VERSO LA TABELLA I_ATTIVITA_TIPOLOGIE ';
ALTER TABLE I_ATTIVITA_SNAPSHOT ADD CONSTRAINT FK_IATTSNAP_IATIPOLOGIEID FOREIGN KEY (IDCOMUNE,FK_IATIPOLOGIE_ID ) REFERENCES I_ATTIVITA_TIPOLOGIE (IDCOMUNE,ID);

ALTER TABLE ISTANZE MODIFY LAVORI VARCHAR2(2000 CHAR);	

CREATE TABLE FO_ARJ_DOMANDE_ONERI(
IDCOMUNE VARCHAR2(6) NOT NULL
, ID NUMBER(8,0) NOT NULL
, FK_ID_DOMANDA NUMBER(6,0) NOT NULL
, FK_CAUSALEONERI NUMBER(10,0) NOT NULL
, FK_CODICEINVENTARIO NUMBER(10,0)
, IMPORTO NUMBER(6,2)
, ID_NUM_OPERAZ_ONLINE VARCHAR2(20)
, IDORDINE_SISTEMA_PAGAMENTI VARCHAR2(125) 
, FLAG_STATO NUMBER(1,0) 
, FLAG_ONLINE NUMBER(1,0) 
, CODICEOGGETTO_XML NUMBER(10,0) 
, CODICEOGGETTO_PDF NUMBER(10,0)
, NOTE VARCHAR2(500)
);

ALTER TABLE FO_ARJ_DOMANDE_ONERI ADD CONSTRAINT PK_FO_ARJ_DOMANDE_ONERI PRIMARY KEY(IDCOMUNE, ID); 
ALTER TABLE FO_ARJ_DOMANDE_ONERI ADD CONSTRAINT FK_FADO_FADID FOREIGN KEY (IDCOMUNE, FK_ID_DOMANDA) REFERENCES FO_ARJ_DOMANDE(IDCOMUNE, ID); 
ALTER TABLE FO_ARJ_DOMANDE_ONERI ADD CONSTRAINT FK_FADO_TCASUONERICOID FOREIGN KEY (IDCOMUNE, FK_CAUSALEONERI) REFERENCES TIPICAUSALIONERI(IDCOMUNE, CO_ID); 
ALTER TABLE FO_ARJ_DOMANDE_ONERI ADD CONSTRAINT FK_FADO_INVPROCCODINV FOREIGN KEY (IDCOMUNE, FK_CODICEINVENTARIO) REFERENCES INVENTARIOPROCEDIMENTI(IDCOMUNE, CODICEINVENTARIO); 
ALTER TABLE FO_ARJ_DOMANDE_ONERI ADD CONSTRAINT FK_FADOCOXML_OGGETTICO FOREIGN KEY (IDCOMUNE, CODICEOGGETTO_XML) REFERENCES OGGETTI(IDCOMUNE, CODICEOGGETTO); 
ALTER TABLE FO_ARJ_DOMANDE_ONERI ADD CONSTRAINT FK_FADOCOPDF_OGGETTICO FOREIGN KEY (IDCOMUNE, CODICEOGGETTO_PDF) REFERENCES OGGETTI(IDCOMUNE, CODICEOGGETTO);

ALTER TABLE ALBEROPROC ADD FK_FOARJSTEPSTESTATAID NUMBER (6,0);
ALTER TABLE ALBEROPROC ADD CONSTRAINT FK_ALBEROPROC_FOARJSTEPSTESTA FOREIGN KEY ( IDCOMUNE, FK_FOARJSTEPSTESTATAID ) REFERENCES FO_ARJ_STEPS_TESTATA ( IDCOMUNE, ID ) ;

ALTER TABLE FO_ARJ_DOMANDE ADD FK_ALBEROPROCSCID NUMBER (10,0);
ALTER TABLE FO_ARJ_DOMANDE ADD CONSTRAINT FK_FOARJDOMANDE_ALBEROPROC FOREIGN KEY ( IDCOMUNE, FK_ALBEROPROCSCID ) REFERENCES ALBEROPROC ( IDCOMUNE, SC_ID ) ;

CREATE TABLE NLA_SERVIZI
  (
    ID          NUMBER (6,0) NOT NULL ,
    IDCOMUNE    VARCHAR2 (6) NOT NULL ,
    IDNODO      NUMBER (6,0) NOT NULL ,
    IDENTE      VARCHAR2 (10 CHAR) NOT NULL ,
    IDSPORTELLO VARCHAR2 (10 CHAR) NOT NULL ,
    PEC         VARCHAR2 (320 CHAR) ,
    DESCRIZIONE VARCHAR2 (4000 CHAR) NOT NULL
  ) ;

ALTER TABLE NLA_SERVIZI ADD CONSTRAINT NLA_SERVIZI_PK PRIMARY KEY(IDCOMUNE, ID);

CREATE TABLE FO_ARJ_SERVIZI
  (
    ID                NUMBER (6,0) NOT NULL ,
    IDCOMUNE          VARCHAR2 (6) NOT NULL ,
    URL_SERVIZIO      VARCHAR2 (4000 CHAR) NOT NULL ,
    ANONIMO           NUMBER (1,0) ,
    FK_ALBEROPROCSCID NUMBER (10,0) NOT NULL ,
    FK_NLASERVIZIID   NUMBER (6,0) NOT NULL
  ) ;
  
ALTER TABLE FO_ARJ_SERVIZI ADD CONSTRAINT FO_ARJ_SERVIZI_PK PRIMARY KEY (IDCOMUNE, ID);

ALTER TABLE FO_ARJ_SERVIZI ADD CONSTRAINT FK_FOARJSERVIZI_ALBEROPROC FOREIGN KEY ( IDCOMUNE, FK_ALBEROPROCSCID ) REFERENCES ALBEROPROC ( IDCOMUNE, SC_ID );
ALTER TABLE FO_ARJ_SERVIZI ADD CONSTRAINT FK_FOARJSERVIZI_NLASERVIZI FOREIGN KEY ( IDCOMUNE, FK_NLASERVIZIID ) REFERENCES NLA_SERVIZI ( IDCOMUNE, ID );

ALTER TABLE ALBEROPROC DROP CONSTRAINT FK_ALBERO_PROC_PROT_TIPI_DOC;

ALTER TABLE ISTANZEONERI MODIFY DOCRIFERIMENTO VARCHAR2(200 CHAR);
ALTER TABLE TMP_ISTANZEONERI MODIFY RIFERIMENTO VARCHAR2(200 CHAR);

ALTER TABLE CC_CLASSISUPERFICI ADD ALIQUOTA_CALCOLO_CC NUMBER(5,2);

ALTER TABLE DOCUMENTIISTANZA ADD ID_BASE VARCHAR2(50 CHAR);
ALTER TABLE MOVIMENTIALLEGATI ADD ID_BASE VARCHAR2(50 CHAR);
ALTER TABLE ISTANZEALLEGATI ADD ID_BASE VARCHAR2(50 CHAR);