#SE IMPOSTATO LA BASE URL SOVRASCRIVE QUELLA DI SIGEPROSECURITY
#SE NON NECESSARIO NON COMMENTARE MA LASCIARE VUOTO IL VALORE
base.url.ws=

# PARAMETRI PER COMUNICAZIONE CON SIGEPROSECURITY (registrare l'utente MAILSERVICE in sigeprosecurity)
ws.token.url=REDACTED
#ws.token.alias= al momento non utilizzato
ws.token.user=REDACTED
ws.token.pwd=REDACTED
