# -------------------------------------------------------------------
#
#  L O G G I N G
#
# -------------------------------------------------------------------

log4j.rootLogger=WARN, R

################################################
#CONSOLE
################################################
# A1 is set to be a ConsoleAppender.
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d{dd/MMM/yyyy HH:mm:ss} [%-5p] - %C{1} (%M) %m %n
log4j.appender.stdout.threshold=WARN

################################################
#ROLLING FILE APPENDER
################################################
log4j.appender.R=org.apache.log4j.RollingFileAppender
log4j.appender.R.File=${catalina.home}/logs/mailservice.log
#log4j.appender.R.File=C:/applicationServer/Apache/tomcat_6.0.32/logs/MailService.log
log4j.appender.R.MaxFileSize=2048KB
log4j.appender.R.MaxBackupIndex=5
log4j.appender.R.layout=org.apache.log4j.PatternLayout
log4j.appender.R.layout.ConversionPattern=%d{dd/MMM/yyyy HH:mm:ss} [%-5p] - %C{1} (%M) %m %n
log4j.appender.R.threshold=WARN
