
UPDATE mercatipresenze_d SET FLAG_ASSENZA_GIUST=0 WHERE FLAG_ASSENZA_GIUST IS NULL; 
ALTER TABLE mercatipresenze_d MODIFY COLUMN FLAG_ASSENZA_GIUST NUMERIC(1,0) NOT NULL DEFAULT 0 ;
CREATE INDEX IDX_DETTPOSDEB_IDPOSDEB ON DETT_POSIZIONE_DEBITORIA (IDCOMUNE,ID_POSIZIONE_DEBITORIA);

ALTER TABLE BLACKLIST_AUTORIZZAZIONI ADD (FK_IDMERCATIUSO DECIMAL(4,0));
ALTER TABLE BLACKLIST_AUTORIZZAZIONI ADD CONSTRAINT FK_BL_AUTORIZ_USO FOREIGN KEY(IDCOMUNE,FK_IDMERCATIUSO) REFERENCES MERCATI_USO(IDCOMUNE,ID);
CREATE INDEX IDX_BL_AUTORIZ_004 ON BLACKLIST_AUTORIZZAZIONI (IDCOMUNE, FK_IDMERCATIUSO);


UPDATE pay_richieste SET n_chiamate=0 WHERE n_chiamate IS NULL; 
ALTER TABLE pay_richieste MODIFY COLUMN n_chiamate DECIMAL(9,0) NOT NULL DEFAULT 0; 

CREATE INDEX idx_pay_richieste_01 ON pay_richieste(idcomune,fk_posizione_debitoria,tipo_richiesta);
CREATE INDEX idx_pay_richieste_02 ON pay_richieste(idcomune,fk_profilo_ente,tipo_richiesta);
CREATE INDEX idx_pay_richieste_03 ON pay_richieste(idcomune,fk_evento);
CREATE INDEX idx_pay_richieste_04 ON pay_richieste(idcomune,fk_evento_out);
CREATE INDEX idx_pay_richieste_05 ON pay_richieste(idcomune,data_richiesta);

CREATE INDEX IDX_DETTPOSDEB_01 ON DETT_POSIZIONE_DEBITORIA(IDCOMUNE,STATO);
CREATE INDEX IDX_BLACKLIST_MOT_01 ON BLACKLIST_MOTIVI(IDCOMUNE,DATA_FINE_BL);


CREATE TABLE ALBEROPROC_MOVIMENTI(
IDCOMUNE VARCHAR(6) NOT NULL,
ID NUMERIC(6,0) NOT NULL,
FK_SCID NUMERIC(10,0) NOT NULL,
FK_TIPOMOVIMENTO VARCHAR(8),
FK_CODICEAMMINISTRAZIONE NUMERIC(10,0) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE ALBEROPROC_MOVIMENTI ADD CONSTRAINT PK_ALBEROPROCMOVIMENTI PRIMARY KEY(IDCOMUNE, ID);

ALTER TABLE  ALBEROPROC_MOVIMENTI ADD CONSTRAINT FK_ALBEROPROCMOV_TIPIMOV FOREIGN KEY(IDCOMUNE,FK_TIPOMOVIMENTO) REFERENCES TIPIMOVIMENTO (IDCOMUNE,TIPOMOVIMENTO);

ALTER TABLE  ALBEROPROC_MOVIMENTI ADD CONSTRAINT FK_ALBEROPROCMOV_ALBEROPROC FOREIGN KEY(IDCOMUNE,FK_SCID) REFERENCES ALBEROPROC (IDCOMUNE,SC_ID);

ALTER TABLE  ALBEROPROC_MOVIMENTI ADD CONSTRAINT FK_ALBEROPROCMOV_AMMINIST FOREIGN KEY(IDCOMUNE,FK_CODICEAMMINISTRAZIONE) REFERENCES AMMINISTRAZIONI (IDCOMUNE,CODICEAMMINISTRAZIONE);

CREATE INDEX IDX_ALBRPROCMOV_01 ON ALBEROPROC_MOVIMENTI(IDCOMUNE, FK_SCID);

CREATE INDEX IDX_MERCAPRESSTORICO_01 ON mercatipresenze_storico(IDCOMUNE,FK_AUTORIZZAZIONI_ID,FKCODICEMERCATO,FKIDMERCATIUSO);

ALTER TABLE pay_documenti MODIFY dati_file LONGBLOB;