CREATE TABLE GRUPPI_ISTRUTTORI(
  ID NUMERIC(6,0) NOT NULL,
  IDCOMUNE VARCHAR(6) NOT NULL,
  DESCRIZIONE VARCHAR(100) NOT NULL,
  SOFTWARE VARCHAR(2) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


ALTER TABLE GRUPPI_ISTRUTTORI ADD CONSTRAINT GRUPPI_ISTRUTTORI_PK PRIMARY KEY (IDCOMUNE,ID);

ALTER TABLE GRUPPI_ISTRUTTORI ADD CONSTRAINT FK_GRUPPI_ISTRUTTORI_SWT FOREIGN KEY (SOFTWARE) REFERENCES SOFTWARE (CODICE);


CREATE TABLE GRUPPI_ISTRUTTORI_RESP(
  ID NUMERIC(10,0) NOT NULL,
  IDCOMUNE VARCHAR(6) NOT NULL,
  FK_GRP_ISTRUTTORI NUMERIC(6,0) NOT NULL,
  FK_RESPOSABILE NUMERIC(8,0) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE GRUPPI_ISTRUTTORI_RESP ADD CONSTRAINT GRUPPI_ISTRUTTORI_RESP_PK PRIMARY KEY (IDCOMUNE,ID);

ALTER TABLE GRUPPI_ISTRUTTORI_RESP  ADD CONSTRAINT FK_GRP_ISTRUTTOR_ISTRUTT FOREIGN KEY (IDCOMUNE, FK_GRP_ISTRUTTORI) REFERENCES RESPONSABILI (IDCOMUNE, CODICERESPONSABILE);
ALTER TABLE GRUPPI_ISTRUTTORI_RESP ADD CONSTRAINT FK_GRP_ISTRUTTOR_RESP FOREIGN KEY (IDCOMUNE, FK_RESPOSABILE) REFERENCES GRUPPI_ISTRUTTORI (IDCOMUNE, ID);

CREATE TABLE RESPONSABILI_ASSENZE(
  ID NUMERIC(10,0) NOT NULL,
  IDCOMUNE VARCHAR(6) NOT NULL,
  DAL DATE NOT NULL,
  AL DATE,
  NOTE VARCHAR(500),
  FK_RESPOSABILE NUMERIC(8,0) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE RESPONSABILI_ASSENZE ADD CONSTRAINT RESPONSABILI_ASSENZE_PK PRIMARY KEY (IDCOMUNE,ID);

ALTER TABLE RESPONSABILI_ASSENZE 
ADD CONSTRAINT FK_RESP_ASSENZE
FOREIGN KEY (IDCOMUNE, FK_RESPOSABILE) 
REFERENCES RESPONSABILI (IDCOMUNE, CODICERESPONSABILE);


ALTER TABLE ALBEROPROC 
ADD GRP_FLAG_ASSEGNAZIONE_AUT NUMERIC(1,0);

ALTER TABLE ALBEROPROC 
ADD GRP_FLAG_ACCETTAZIONE NUMERIC(1,0);

ALTER TABLE ALBEROPROC 
ADD FK_GRP_ISTRUTTORI NUMERIC(10,0);


ALTER TABLE ALBEROPROC 
ADD CONSTRAINT FK_ALB_PROC_GRP_ISTR
FOREIGN KEY (IDCOMUNE, FK_GRP_ISTRUTTORI) 
REFERENCES GRUPPI_ISTRUTTORI (IDCOMUNE,ID);


ALTER TABLE ISTANZE 
ADD GRP_FLAG_ASSEGNAZIONE_AUT NUMERIC(1,0);

ALTER TABLE ISTANZE 
ADD GRP_FLAG_ACCETTAZIONE NUMERIC(1,0);

ALTER TABLE ISTANZE 
ADD GRP_DATA_ACCETTAZIONE DATE;

ALTER TABLE ISTANZE 
ADD FK_ISTRUTTORE_TEMP NUMERIC(8,0);

ALTER TABLE ISTANZE 
ADD FK_GRP_ISTRUTTORI NUMERIC(10,0);

ALTER TABLE ISTANZE
ADD CONSTRAINT FK_ISTANZE_ISTRUT_TMP
FOREIGN KEY (IDCOMUNE, FK_ISTRUTTORE_TEMP) 
REFERENCES RESPONSABILI (IDCOMUNE, CODICERESPONSABILE);

ALTER TABLE ISTANZE 
ADD CONSTRAINT FK_ISTANZE_GRP_ISTR
FOREIGN KEY (IDCOMUNE, FK_GRP_ISTRUTTORI) 
REFERENCES GRUPPI_ISTRUTTORI (IDCOMUNE,ID);

ALTER TABLE TIPIMOVIMENTO ADD FLAG_SOST_DOCUMENTALE NUMERIC(1,0);


CREATE TABLE OGGETTI_STORICO(
  ID NUMERIC(10,0) NOT NULL,
  IDCOMUNE VARCHAR(6) NOT NULL,
  CODICEOGGETTO NUMERIC(10,0) NOT NULL,
  CODICEOGGETTO_SOSTIT NUMERIC(10,0) NOT NULL,
  DATA_SOSTITUZIONE DATE NOT NULL,
  NOTE VARCHAR(500)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE OGGETTI_STORICO ADD CONSTRAINT OGGETTI_STORICO_PK PRIMARY KEY (IDCOMUNE,ID);

ALTER TABLE OGGETTI_STORICO 
ADD CONSTRAINT FK_OGGETTO_NUOVO
FOREIGN KEY (IDCOMUNE, CODICEOGGETTO) 
REFERENCES OGGETTI (IDCOMUNE, CODICEOGGETTO);

ALTER TABLE OGGETTI_STORICO 
ADD CONSTRAINT FK_OGGETTO_VECCHIO
FOREIGN KEY (IDCOMUNE, CODICEOGGETTO_SOSTIT) 
REFERENCES OGGETTI (IDCOMUNE, CODICEOGGETTO);


ALTER TABLE STATIISTANZA ADD FLAG_BLOCCA_INTEGR_ONLINE NUMERIC(1,0);


ALTER TABLE ISTANZEONERI ADD FLAG_NONDOVUTO NUMERIC(1,0);


ALTER TABLE ISTANZE MODIFY CODICEPRATICATEL VARCHAR(80);

ALTER TABLE tipimovimento ADD FLAG_INTEGR_CHECK_FIRMA NUMERIC(1);


