## SECURITY
ws.token.url=REDACTED
ws.token.user=REDACTED
ws.token.pwd=REDACTED

# URL DELLA EVENTUALE CONSOLE REMOTA
console.offline.ws.url=REDACTED

## STC
stc.url=REDACTED
stc.userid=....
stc.password=REDACTED
stc.mtom=true
stc.timeout=480000



stc.idNodoMittente=1234
stc.idEnteMittente=...
stc.idSportelloMittente=...
stc.idNodoDestinatario=400
stc.idSportelloDestinatario=CE

ws.oggetti.mtom=true
ws.eventi.mtom=true



#BACKEND
ws.backend.url=REDACTED

#SCHEDULAZIONI
scheduler.enabled=false
downloadpratiche.cron.trigger.interval=0 0/20 * * * ?
#downloadpratiche.cron.trigger.interval=0 0/2 * 1/1 * ? *

lista.alias.da.processare=
