ALTER TABLE MASSIVE_DETT_DESTINATARI MODIFY CODICEAMMINISTRAZIONE NUMBER(10,0);

CREATE TABLE canoni_tipologiesuperficie (
  IDCOMUNE VARCHAR2(6) NOT NULL,
  ID NUMBER(4,0) NOT NULL,
  TIPOSUPERFICIE VARCHAR2(200) NOT NULL,
  SOFTWARE VARCHAR2(2) NOT NULL
);
ALTER TABLE canoni_tipologiesuperficie ADD CONSTRAINT pk_ccanonitipologiesuperficie PRIMARY KEY(idcomune,id); ALTER TABLE canoni_tipologiesuperficie ADD CONSTRAINT fk_cantipsup_software FOREIGN KEY(software)REFERENCES software(codice);


CREATE TABLE rer_centricommerciali (
  IDCOMUNE VARCHAR2(6) NOT NULL,
  ID VARCHAR2(4) NOT NULL,
  DENOMINAZIONE_CENTRO VARCHAR2(100) NOT NULL,
  ANNO_APERTURA NUMBER(4,0)  NULL
 );
  
ALTER TABLE rer_centricommerciali ADD CONSTRAINT pk_rer_centricommerciali PRIMARY KEY(idcomune,id);

ALTER TABLE inventarioprocedimentipeople MODIFY COD_PROC_PEOPLE VARCHAR2(80);


CREATE TABLE BORSELLINO(IDCOMUNE VARCHAR2(6 CHAR) NOT NULL, ID NUMBER(10,0) NOT NULL, DATACREAZIONE DATE NOT NULL, DESCRIZIONE VARCHAR2(200 CHAR) NOT NULL, FKID_ANAGRAFE NUMBER(6,0) NOT NULL, STATO VARCHAR2(50 CHAR) NOT NULL);
ALTER TABLE BORSELLINO ADD CONSTRAINT PK_BORSELLINO PRIMARY KEY(IDCOMUNE,ID);
ALTER TABLE BORSELLINO ADD CONSTRAINT FK_BORS_ANAGRAFE FOREIGN KEY(IDCOMUNE,FKID_ANAGRAFE) REFERENCES ANAGRAFE(IDCOMUNE,CODICEANAGRAFE);
CREATE INDEX IDX_BORS_ANAGRAFE ON BORSELLINO (IDCOMUNE,FKID_ANAGRAFE);
CREATE TABLE BORSELLINO_AUTORIZZAZIONI(IDCOMUNE VARCHAR2(6 CHAR) NOT NULL, FKID_BORSELLINO NUMBER(10,0) NOT NULL,FKID_AUTORIZZAZIONI NUMBER(6,0) NOT NULL );
ALTER TABLE BORSELLINO_AUTORIZZAZIONI ADD CONSTRAINT PK_BORSELLINOAUTORIZZAZIONI PRIMARY KEY(IDCOMUNE,FKID_BORSELLINO,FKID_AUTORIZZAZIONI);
ALTER TABLE BORSELLINO_AUTORIZZAZIONI ADD CONSTRAINT FK_BORSAUT_BORSELLINO FOREIGN KEY(IDCOMUNE,FKID_BORSELLINO) REFERENCES BORSELLINO(IDCOMUNE,ID);
ALTER TABLE BORSELLINO_AUTORIZZAZIONI ADD CONSTRAINT FK_BORSAUT_AUTORIZZAZIONI FOREIGN KEY(IDCOMUNE,FKID_AUTORIZZAZIONI) REFERENCES AUTORIZZAZIONI(IDCOMUNE,ID);
CREATE INDEX IDX_BORSAUT_BORSELLINO ON BORSELLINO_AUTORIZZAZIONI (IDCOMUNE,FKID_BORSELLINO);
CREATE INDEX IDX_BORSAUT_AUTORIZZAZIONI ON BORSELLINO_AUTORIZZAZIONI (IDCOMUNE,FKID_AUTORIZZAZIONI);
CREATE TABLE BORSELLINO_MOVIMENTI(IDCOMUNE VARCHAR2(6 CHAR) NOT NULL, ID NUMBER(10,0) NOT NULL, FKID_BORSELLINO NUMBER(10,0) NOT NULL, TIPO VARCHAR2(50 CHAR) NOT NULL, DATA DATE NOT NULL, IMPORTO NUMBER(10,2) NOT NULL, FKID_DETTPOSIZIONEDEBITORIA NUMBER(10,0), FKID_MERCATID NUMBER(6,0), FKID_MERCATIPRESENZET NUMBER(6,0), FKID_AUTORIZZAZIONI NUMBER(6,0));
ALTER TABLE BORSELLINO_MOVIMENTI ADD CONSTRAINT PK_BORSELLINOMOVIMENTI PRIMARY KEY(IDCOMUNE,ID);
ALTER TABLE BORSELLINO_MOVIMENTI ADD CONSTRAINT FK_BORSMOV_BORSELLINO FOREIGN KEY(IDCOMUNE,FKID_BORSELLINO) REFERENCES BORSELLINO(IDCOMUNE,ID);
ALTER TABLE BORSELLINO_MOVIMENTI ADD CONSTRAINT FK_BORSMOV_DETTPOSDEB FOREIGN KEY(IDCOMUNE,FKID_DETTPOSIZIONEDEBITORIA) REFERENCES DETT_POSIZIONE_DEBITORIA(IDCOMUNE,ID);
ALTER TABLE BORSELLINO_MOVIMENTI ADD CONSTRAINT FK_BORSMOV_MERCATID FOREIGN KEY(IDCOMUNE,FKID_MERCATID) REFERENCES MERCATI_D(IDCOMUNE,IDPOSTEGGIO);
ALTER TABLE BORSELLINO_MOVIMENTI ADD CONSTRAINT FK_BORSMOV_MERCATIPRESENZET FOREIGN KEY(IDCOMUNE,FKID_MERCATIPRESENZET) REFERENCES MERCATIPRESENZE_T(IDCOMUNE,ID);
ALTER TABLE BORSELLINO_MOVIMENTI ADD CONSTRAINT FK_BORSMOV_AUTORIZZAZIONI FOREIGN KEY(IDCOMUNE,FKID_AUTORIZZAZIONI) REFERENCES AUTORIZZAZIONI(IDCOMUNE,ID);
CREATE INDEX IDX_BORSMOV_BORSELLINO ON BORSELLINO_MOVIMENTI (IDCOMUNE,FKID_BORSELLINO);
CREATE INDEX IDX_BORSMOV_DETTPOSDEB ON BORSELLINO_MOVIMENTI (IDCOMUNE,FKID_DETTPOSIZIONEDEBITORIA);
CREATE TABLE BORSELLINO_MOVIMENTI_IMPORTI(IDCOMUNE VARCHAR2(6 CHAR) NOT NULL, ID NUMBER(10,0) NOT NULL, FKID_BORSELLINOMOVIMENTI NUMBER(10,0) NOT NULL, FKID_CONTI NUMBER(6,0) NOT NULL, IMPORTO NUMBER(10,2) NOT NULL);
ALTER TABLE BORSELLINO_MOVIMENTI_IMPORTI ADD CONSTRAINT PK_BORSELLINOMOVIMENTIIMPORTI PRIMARY KEY(IDCOMUNE,ID);
ALTER TABLE BORSELLINO_MOVIMENTI_IMPORTI ADD CONSTRAINT FK_BORSMOVIMP_BORSMOV FOREIGN KEY(IDCOMUNE,FKID_BORSELLINOMOVIMENTI) REFERENCES BORSELLINO_MOVIMENTI(IDCOMUNE,ID);
ALTER TABLE BORSELLINO_MOVIMENTI_IMPORTI ADD CONSTRAINT FK_BORSMOVIMP_CONTI FOREIGN KEY(IDCOMUNE,FKID_CONTI) REFERENCES CONTI(IDCOMUNE,ID);
CREATE INDEX IDX_BORSMOVIMP_BORSMOV ON BORSELLINO_MOVIMENTI_IMPORTI (IDCOMUNE,FKID_BORSELLINOMOVIMENTI);
CREATE INDEX IDX_BORSMOVIMP_CONTI ON BORSELLINO_MOVIMENTI_IMPORTI (IDCOMUNE,FKID_CONTI);
CREATE INDEX IDX_BORSMOV_MERCATID ON BORSELLINO_MOVIMENTI (IDCOMUNE,FKID_MERCATID);
CREATE INDEX IDX_BORSMOV_MERCATIPRESENZET ON BORSELLINO_MOVIMENTI (IDCOMUNE,FKID_MERCATIPRESENZET);
CREATE INDEX IDX_BORSMOV_AUTORIZZAZIONI ON BORSELLINO_MOVIMENTI (IDCOMUNE,FKID_AUTORIZZAZIONI);

ALTER TABLE BORSELLINO_MOVIMENTI ADD FKID_MOVIMENTOSTORNO NUMBER(10,0);
ALTER TABLE BORSELLINO_MOVIMENTI ADD CONSTRAINT FK_BORSMOV_STORNO FOREIGN KEY(IDCOMUNE,FKID_MOVIMENTOSTORNO) REFERENCES BORSELLINO_MOVIMENTI(IDCOMUNE,ID);
CREATE INDEX IDX_BORSMOV_STORNO ON BORSELLINO_MOVIMENTI(IDCOMUNE,FKID_MOVIMENTOSTORNO);

ALTER TABLE BORSELLINO ADD UUID VARCHAR2(60) ;
UPDATE BORSELLINO SET UUID = SYS_GUID() WHERE UUID IS NULL;
ALTER TABLE BORSELLINO MODIFY UUID VARCHAR2(60) NOT NULL;

CREATE TABLE BORSELLINO_CONFIGURAZIONE(IDCOMUNE VARCHAR2(6 CHAR) NOT NULL, ID NUMBER(10,0) NOT NULL, TIPO_INSTALLAZIONE VARCHAR2(50 CHAR) NOT NULL, MSG_NODOPAG_NONDISP VARCHAR2(500 CHAR) NULL, GESTIONE_FO NUMBER(1,0) NOT NULL);
ALTER TABLE BORSELLINO_CONFIGURAZIONE ADD CONSTRAINT PK_BORSELLINO_CONFIGURAZIONE PRIMARY KEY(IDCOMUNE,ID);
CREATE TABLE BORSELLINO_CONFIG_COMUNE(IDCOMUNE VARCHAR2(6 CHAR) NOT NULL, ID NUMBER(10,0) NOT NULL, CODICECOMUNE VARCHAR2(5 CHAR) NOT NULL, MSG_NODOPAG_NONDISP VARCHAR2(500 CHAR) NULL);
ALTER TABLE BORSELLINO_CONFIG_COMUNE ADD CONSTRAINT PK_BORSCFGCOM PRIMARY KEY(IDCOMUNE,ID);
ALTER TABLE BORSELLINO_CONFIG_COMUNE ADD CONSTRAINT FK_BORSCFGCOM_COMUNI FOREIGN KEY(CODICECOMUNE) REFERENCES COMUNI(CODICECOMUNE);
CREATE INDEX IDX_BORSCFGCOM_COMUNI ON BORSELLINO_CONFIG_COMUNE (CODICECOMUNE);
CREATE TABLE BORSELLINO_INFORMATIVE(IDCOMUNE VARCHAR2(6 CHAR) NOT NULL, ID NUMBER(10,0) NOT NULL, CODICECOMUNE VARCHAR2(5 CHAR) NOT NULL, INFORMATIVA VARCHAR2(500 CHAR) NOT NULL, DATA_FINE_VALIDITA DATE NULL );
ALTER TABLE BORSELLINO_INFORMATIVE ADD CONSTRAINT PK_BORSELLINO_INFORMATIVE PRIMARY KEY(IDCOMUNE,ID);
ALTER TABLE BORSELLINO_INFORMATIVE ADD CONSTRAINT FK_BORSINFO_COMUNI FOREIGN KEY(CODICECOMUNE) REFERENCES COMUNI(CODICECOMUNE);
CREATE INDEX IDX_BORSINFO_COMUNI ON BORSELLINO_INFORMATIVE (CODICECOMUNE);
CREATE TABLE BORSELLINO_ACCETTAZIONI(IDCOMUNE VARCHAR2(6 CHAR) NOT NULL, ID NUMBER(10,0) NOT NULL, FK_IDINFORMATIVA NUMBER(10,0) NOT NULL, FKID_BORSELLINO NUMBER(10,0) NOT NULL, DATA_ACCETTAZIONE DATE NOT NULL );
ALTER TABLE BORSELLINO_ACCETTAZIONI ADD CONSTRAINT PK_BORSELLINO_ACCETTAZIONI PRIMARY KEY(IDCOMUNE,ID);
ALTER TABLE BORSELLINO_ACCETTAZIONI ADD CONSTRAINT FK_BORSACC_INFORMATIVA FOREIGN KEY(IDCOMUNE,FK_IDINFORMATIVA) REFERENCES BORSELLINO_INFORMATIVE(IDCOMUNE,ID);
ALTER TABLE BORSELLINO_ACCETTAZIONI ADD CONSTRAINT FK_BORSACC_BORSELLINO FOREIGN KEY(IDCOMUNE,FKID_BORSELLINO) REFERENCES BORSELLINO(IDCOMUNE,ID);
CREATE INDEX IDX_BORSACC_INFORMATIVA ON BORSELLINO_ACCETTAZIONI (IDCOMUNE,FK_IDINFORMATIVA);
CREATE INDEX IDX_BORSACC_BORSELLINO ON BORSELLINO_ACCETTAZIONI (IDCOMUNE,FKID_BORSELLINO);
CREATE TABLE BORSELLINO_RICARICHE(IDCOMUNE VARCHAR2(6 CHAR) NOT NULL, ID NUMBER(10,0) NOT NULL, CODICECOMUNE VARCHAR2(5 CHAR) NOT NULL, IMPORTO NUMBER(10,2) NOT NULL);
ALTER TABLE BORSELLINO_RICARICHE ADD CONSTRAINT PK_BORSELLINO_RICARICHE PRIMARY KEY(IDCOMUNE,ID);
ALTER TABLE BORSELLINO_RICARICHE ADD CONSTRAINT FK_BORSRIC_COMUNI FOREIGN KEY(CODICECOMUNE) REFERENCES COMUNI(CODICECOMUNE);
CREATE INDEX IDX_BORSRIC_COMUNI ON BORSELLINO_RICARICHE (CODICECOMUNE);

ALTER TABLE BORSELLINO_RICARICHE ADD TIPO VARCHAR2(20 CHAR) NOT NULL;
ALTER TABLE BORSELLINO_MOVIMENTI_IMPORTI MODIFY FKID_CONTI NUMBER(6,0) NULL;
ALTER TABLE BORSELLINO_CONFIG_COMUNE ADD CONSTRAINT IDX_BORSCFGCOM_UNIQUE UNIQUE(IDCOMUNE,CODICECOMUNE);

ALTER TABLE dett_posizione_debitoria ADD CODICECOMUNE VARCHAR2(5);

ALTER TABLE dett_posizione_debitoria ADD SOFTWARE VARCHAR2(2);

ALTER TABLE dett_posizione_debitoria ADD CONSTRAINT FK_DETTPOSDEB_COMUNI FOREIGN KEY ( CODICECOMUNE) REFERENCES COMUNI(CODICECOMUNE);

ALTER TABLE dett_posizione_debitoria ADD CONSTRAINT FK_DETTPOSDEB_SOFTWARE FOREIGN KEY ( SOFTWARE ) REFERENCES SOFTWARE(CODICE);

CREATE TABLE MERCATIPRESENZE_T_MASSIVE (IDCOMUNE VARCHAR2(6 CHAR) NOT NULL,ID NUMBER(10,0) NOT NULL,FKID_MASSIVE_TESTATA NUMBER(6,0) NOT NULL,FKID_MERCATIPRESENZE_T NUMBER(6,0) NOT NULL );
ALTER TABLE MERCATIPRESENZE_T_MASSIVE ADD CONSTRAINT PK_MERCATIPRESENZE_T_MASSIVE PRIMARY KEY(IDCOMUNE,ID);
ALTER TABLE MERCATIPRESENZE_T_MASSIVE ADD CONSTRAINT FK_MASSIVE_TESTATA FOREIGN KEY(IDCOMUNE,FKID_MASSIVE_TESTATA) REFERENCES MASSIVE_TESTATA(IDCOMUNE,ID);
ALTER TABLE MERCATIPRESENZE_T_MASSIVE ADD CONSTRAINT FK_MERCATIPRESENZE_T FOREIGN KEY(IDCOMUNE,FKID_MERCATIPRESENZE_T) REFERENCES MERCATIPRESENZE_T(IDCOMUNE,ID);
CREATE INDEX IDX_MERCATIPRES_T_MASSIVE_001 ON MERCATIPRESENZE_T_MASSIVE (IDCOMUNE,FKID_MASSIVE_TESTATA);
CREATE INDEX IDX_MERCATIPRES_T_MASSIVE_002 ON MERCATIPRESENZE_T_MASSIVE (IDCOMUNE,FKID_MERCATIPRESENZE_T);
CREATE TABLE MERCATIPRESENZE_D_MASSIVE (IDCOMUNE VARCHAR2(6 CHAR) NOT NULL,ID NUMBER(10,0) NOT NULL,FKID_MASSIVE_DETTAGLIO NUMBER(6,0) NOT NULL,FKID_MERCATIPRESENZE_D NUMBER(10,0) NOT NULL );
ALTER TABLE MERCATIPRESENZE_D_MASSIVE ADD CONSTRAINT PK_MERCATIPRESENZE_D_MASSIVE PRIMARY KEY(IDCOMUNE,ID);
ALTER TABLE MERCATIPRESENZE_D_MASSIVE ADD CONSTRAINT FK_MASSIVE_DETTAGLIO FOREIGN KEY(IDCOMUNE,FKID_MASSIVE_DETTAGLIO) REFERENCES MASSIVE_DETTAGLIO(IDCOMUNE,ID);
ALTER TABLE MERCATIPRESENZE_D_MASSIVE ADD CONSTRAINT FK_MERCATIPRESENZE_D FOREIGN KEY(IDCOMUNE,FKID_MERCATIPRESENZE_D) REFERENCES MERCATIPRESENZE_D(IDCOMUNE,ID);
CREATE INDEX IDX_MERCATIPRES_D_MASSIVE_001 ON MERCATIPRESENZE_D_MASSIVE (IDCOMUNE,FKID_MASSIVE_DETTAGLIO);
CREATE INDEX IDX_MERCATIPRES_D_MASSIVE_002 ON MERCATIPRESENZE_D_MASSIVE (IDCOMUNE,FKID_MERCATIPRESENZE_D);
ALTER TABLE borsellino_ricariche MODIFY IMPORTO NUMBER(10,0);

MERGE INTO dett_posizione_debitoria t1
USING 
(     SELECT
			idcomune,
			id,
			codicecomune,
			software,
			rnum
	   FROM
			(
				SELECT
					dett_posizione_debitoria.idcomune,
					dett_posizione_debitoria.id,
					mercati.codicecomune,
					mercati.software,
					ROW_NUMBER() OVER(
						PARTITION BY dett_posizione_debitoria.idcomune,
						dett_posizione_debitoria.id
						ORDER BY
							dett_posizione_debitoria.idcomune ASC,
							dett_posizione_debitoria.id ASC
					) AS rnum                                
				FROM
				dett_posizione_debitoria
				 INNER JOIN
				mercatipresenze_d
				 ON dett_posizione_debitoria.idcomune = mercatipresenze_d.idcomune AND
				 dett_posizione_debitoria.id = mercatipresenze_d.FK_PAY_POS_DEB 
				 INNER JOIN mercatipresenze_t ON 
				 mercatipresenze_t.idcomune=mercatipresenze_d.idcomune AND
				 mercatipresenze_t.id=mercatipresenze_d.fkidtestata 
				 INNER JOIN mercati ON 
				 mercati.idcomune=mercatipresenze_t.idcomune AND
				 mercati.codicemercato=mercatipresenze_t.FKCODICEMERCATO
			WHERE 
				dett_posizione_debitoria.CODICECOMUNE IS NULL		 
				
		) where rnum=1
) t2
	
ON (
        t1.idcomune = t2.idcomune
        AND t1.id = t2.id   
)
WHEN MATCHED THEN 
UPDATE SET t1.codicecomune = t2.codicecomune, T1.SOFTWARE=T2.SOFTWARE;	
	
	
MERGE INTO dett_posizione_debitoria t1
USING 
(     SELECT
			idcomune,
			id,
			codicecomune,
			software,
            rnum
	   FROM
			(
				SELECT
					dett_posizione_debitoria.idcomune,
					dett_posizione_debitoria.id,
					istanze.codicecomune,
					istanze.software,
					ROW_NUMBER() OVER(
						PARTITION BY dett_posizione_debitoria.idcomune,
						dett_posizione_debitoria.id
						ORDER BY
							dett_posizione_debitoria.idcomune ASC,
							dett_posizione_debitoria.id ASC
					) AS rnum                                
				FROM
				dett_posizione_debitoria
                INNER JOIN
                istoneri_dett_posizioni
                 ON dett_posizione_debitoria.idcomune = istoneri_dett_posizioni.idcomune AND
                 dett_posizione_debitoria.id = istoneri_dett_posizioni.fk_dettposdebitoria_id 
                 INNER JOIN istanzeoneri ON 
                 istanzeoneri.idcomune=istoneri_dett_posizioni.idcomune AND
                 istanzeoneri.id=istoneri_dett_posizioni.fk_istanzeoneri_id 
                 INNER JOIN istanze ON 
                 istanze.idcomune=istanzeoneri.idcomune AND
                 istanze.codiceistanza=istanzeoneri.codiceistanza
                WHERE dett_posizione_debitoria.codicecomune IS NULL
		) where rnum=1
) t2
	
ON (
        t1.idcomune = t2.idcomune
        AND t1.id = t2.id   
)
WHEN MATCHED THEN 
UPDATE SET t1.codicecomune = t2.codicecomune, T1.SOFTWARE=T2.SOFTWARE;
	
MERGE INTO dett_posizione_debitoria t1
USING 
(     SELECT
			idcomune,
			id,
			codicecomune,
			software,
            rnum
	   FROM
			(
				SELECT
					dett_posizione_debitoria.idcomune,
					dett_posizione_debitoria.id,
					istanze.codicecomune,
					istanze.software,
					ROW_NUMBER() OVER(
						PARTITION BY dett_posizione_debitoria.idcomune,
						dett_posizione_debitoria.id
						ORDER BY
							dett_posizione_debitoria.idcomune ASC,
							dett_posizione_debitoria.id ASC
					) AS rnum                                
				FROM
				dett_posizione_debitoria
                 INNER JOIN istanzeoneri ON 
                 istanzeoneri.idcomune=dett_posizione_debitoria.idcomune AND
                 istanzeoneri.FK_POSDEBDETTAGLIO_ID=dett_posizione_debitoria.id 
                 INNER JOIN istanze ON 
                 istanze.idcomune=istanzeoneri.idcomune AND
                 istanze.codiceistanza=istanzeoneri.codiceistanza
                 WHERE dett_posizione_debitoria.codicecomune IS NULL
		) where rnum=1
) t2
	
ON (
        t1.idcomune = t2.idcomune
        AND t1.id = t2.id   
)
WHEN MATCHED THEN 
UPDATE SET t1.codicecomune = t2.codicecomune, T1.SOFTWARE=T2.SOFTWARE;


MERGE INTO dett_posizione_debitoria t1
USING 
(     SELECT
                        idcomune,
                        id,
                        codicecomune,
                        software,
						rnum
                    FROM
                        (
                            SELECT
                                dett_posizione_debitoria.idcomune,
                                dett_posizione_debitoria.id,
                                istanze.codicecomune,
                                istanze.software                                
                                ,ROW_NUMBER() OVER(
                                    PARTITION BY dett_posizione_debitoria.idcomune,
                                    dett_posizione_debitoria.id
                                    ORDER BY
                                        dett_posizione_debitoria.idcomune ASC,
                                        dett_posizione_debitoria.id ASC
                                ) AS rnum                                
                            FROM
                                dett_posizione_debitoria
                                INNER JOIN boll_gest_dettaglio ON 
                                    boll_gest_dettaglio.idcomune = dett_posizione_debitoria.idcomune
                                    AND boll_gest_dettaglio.fk_posdebdettaglio_id = dett_posizione_debitoria.id
                                INNER JOIN boll_gest_istanzeoneri ON 
                                    boll_gest_istanzeoneri.idcomune = boll_gest_dettaglio.idcomune
                                    AND boll_gest_istanzeoneri.fk_bollgestdet_id = boll_gest_dettaglio.id
                                INNER JOIN istanzeoneri ON 
                                    istanzeoneri.idcomune = boll_gest_istanzeoneri.idcomune
                                    AND istanzeoneri.id = boll_gest_istanzeoneri.fk_codiceistanzeoneri
                                INNER JOIN istanze ON 
                                    istanze.idcomune = istanzeoneri.idcomune
                                    AND istanze.codiceistanza = istanzeoneri.codiceistanza
                             WHERE dett_posizione_debitoria.codicecomune IS NULL
                        )
                     WHERE  rnum = 1
                ) t2
ON (
        t1.idcomune = t2.idcomune
        AND t1.id = t2.id   
)
WHEN MATCHED THEN 
UPDATE SET t1.codicecomune = t2.codicecomune,
    T1.SOFTWARE=T2.SOFTWARE;
	
MERGE INTO dett_posizione_debitoria t1
USING 
(     SELECT
			idcomune,
			id,
			codicecomune,
			software,
            rnum
	   FROM
			(
				SELECT
					dett_posizione_debitoria.idcomune,
					dett_posizione_debitoria.id,
					istanze.codicecomune,
					istanze.software,
					ROW_NUMBER() OVER(
						PARTITION BY dett_posizione_debitoria.idcomune,
						dett_posizione_debitoria.id
						ORDER BY
							dett_posizione_debitoria.idcomune ASC,
							dett_posizione_debitoria.id ASC
					) AS rnum                                
				FROM
				dett_posizione_debitoria
                INNER JOIN boll_gest_dett_rate ON
                boll_gest_dett_rate.IDCOMUNE=dett_posizione_debitoria.idcomune AND
                boll_gest_dett_rate.FK_POSDEBDETTAGLIO_ID=dett_posizione_debitoria.ID
                INNER JOIN boll_gest_istanzeoneri ON 
                boll_gest_istanzeoneri.IDCOMUNE=boll_gest_dett_rate.IDCOMUNE AND
                boll_gest_istanzeoneri.FK_BOLLGESTDET_ID=boll_gest_dett_rate.FK_BOLLGESTDET_ID
                 INNER JOIN istanzeoneri ON 
                 istanzeoneri.idcomune=boll_gest_istanzeoneri.idcomune AND
                 istanzeoneri.ID=boll_gest_istanzeoneri.FK_CODICEISTANZEONERI 
                 INNER JOIN istanze ON 
                 istanze.idcomune=istanzeoneri.idcomune AND
                 istanze.codiceistanza=istanzeoneri.codiceistanza
                 WHERE dett_posizione_debitoria.codicecomune IS NULL
		) where rnum=1
) t2
	
ON (
        t1.idcomune = t2.idcomune
        AND t1.id = t2.id   
)
WHEN MATCHED THEN 
UPDATE SET t1.codicecomune = t2.codicecomune, T1.SOFTWARE=T2.SOFTWARE;

MERGE INTO dett_posizione_debitoria t1
USING 
(     SELECT
			idcomune,
			id,
			codicecomune,
			software,
            rnum
	   FROM
			(
				SELECT
					dett_posizione_debitoria.idcomune,
					dett_posizione_debitoria.id,
					mercati.codicecomune,
					mercati.software,
					ROW_NUMBER() OVER(
						PARTITION BY dett_posizione_debitoria.idcomune,
						dett_posizione_debitoria.id
						ORDER BY
							dett_posizione_debitoria.idcomune ASC,
							dett_posizione_debitoria.id ASC
					) AS rnum                                
				FROM
				dett_posizione_debitoria
                    INNER JOIN boll_gest_dettaglio ON
                    boll_gest_dettaglio.IDCOMUNE=dett_posizione_debitoria.idcomune AND
                    boll_gest_dettaglio.FK_POSDEBDETTAGLIO_ID=dett_posizione_debitoria.ID
                    INNER JOIN boll_gest_dett_autorizz ON 
                    boll_gest_dett_autorizz.IDCOMUNE=boll_gest_dettaglio.IDCOMUNE AND
                    boll_gest_dett_autorizz.FK_BOLLGESTDET_ID=boll_gest_dettaglio.id
                     INNER JOIN boll_gest_mercati_dett ON 
                     boll_gest_mercati_dett.idcomune=boll_gest_dett_autorizz.idcomune AND
                     boll_gest_mercati_dett.FK_ID_GEST_AUTORIZZAZIONI=boll_gest_dett_autorizz.id 
                     INNER JOIN mercati_d ON 
                     mercati_d.idcomune=boll_gest_mercati_dett.idcomune AND
                     mercati_d.idposteggio=boll_gest_mercati_dett.FK_IDPOSTEGGIO
                     INNER JOIN mercati ON 
                     mercati.idcomune=mercati_d.idcomune AND
                     mercati.codicemercato=mercati_d.FKCODICEMERCATO
					 WHERE dett_posizione_debitoria.codicecomune IS NULL
		) where rnum=1
) t2
	
ON (
        t1.idcomune = t2.idcomune
        AND t1.id = t2.id   
)
WHEN MATCHED THEN 
UPDATE SET t1.codicecomune = t2.codicecomune, T1.SOFTWARE=T2.SOFTWARE;
	
MERGE INTO dett_posizione_debitoria t1
USING 
(     SELECT
			idcomune,
			id,
			codicecomune,
			software,
            rnum
	   FROM
			(
				SELECT
					dett_posizione_debitoria.idcomune,
					dett_posizione_debitoria.id,
					mercati.codicecomune,
					mercati.software,
					ROW_NUMBER() OVER(
						PARTITION BY dett_posizione_debitoria.idcomune,
						dett_posizione_debitoria.id
						ORDER BY
							dett_posizione_debitoria.idcomune ASC,
							dett_posizione_debitoria.id ASC
					) AS rnum                                
				FROM
				dett_posizione_debitoria
                    INNER JOIN boll_gest_dett_rate ON
                    boll_gest_dett_rate.IDCOMUNE=dett_posizione_debitoria.idcomune AND
                    boll_gest_dett_rate.FK_POSDEBDETTAGLIO_ID=dett_posizione_debitoria.ID
                    INNER JOIN boll_gest_dett_autorizz ON 
                    boll_gest_dett_autorizz.IDCOMUNE=boll_gest_dett_rate.IDCOMUNE AND
                    boll_gest_dett_autorizz.FK_BOLLGESTDET_ID=boll_gest_dett_rate.FK_BOLLGESTDET_ID
                    INNER JOIN boll_gest_mercati_dett ON 
                    boll_gest_mercati_dett.idcomune=boll_gest_dett_autorizz.idcomune AND
                    boll_gest_mercati_dett.FK_ID_GEST_AUTORIZZAZIONI=boll_gest_dett_autorizz.id 
                    INNER JOIN mercati_d ON 
                    mercati_d.idcomune=boll_gest_mercati_dett.idcomune AND
                    mercati_d.idposteggio=boll_gest_mercati_dett.FK_IDPOSTEGGIO
                    INNER JOIN mercati ON 
                    mercati.idcomune=mercati_d.idcomune AND
                    mercati.codicemercato=mercati_d.FKCODICEMERCATO
                 WHERE dett_posizione_debitoria.codicecomune IS NULL
		) where rnum=1
) t2
	
ON (
        t1.idcomune = t2.idcomune
        AND t1.id = t2.id   
)
WHEN MATCHED THEN 
UPDATE SET t1.codicecomune = t2.codicecomune, T1.SOFTWARE=T2.SOFTWARE;

CREATE INDEX BORSELLINO_MOVIMENTI_001 ON BORSELLINO_MOVIMENTI(IDCOMUNE,TIPO);

ALTER TABLE ANAGRAFESTORICO ADD FLAG_MAIL_VERIFICATA NUMBER(1,0) DEFAULT 0 NOT NULL;

ALTER TABLE ANAGRAFE ADD FLAG_MAIL_VERIFICATA NUMBER(1,0) DEFAULT 0 NOT NULL;

CREATE TABLE ANAGRAFE_VERIFICHE_MAIL(
IDCOMUNE VARCHAR2(6 CHAR) NOT NULL
,ID NUMBER(10,0) NOT NULL
,FK_CODICEANAGRAFE NUMBER(6,0) NOT NULL
,CODICE_VERIFICA VARCHAR2(20 CHAR) NOT NULL
,NUOVA_EMAIL VARCHAR2(320 CHAR) NOT NULL
,DATA_SCADENZA DATE NOT NULL
,DATA_VERIFICA DATE ); 
ALTER TABLE ANAGRAFE_VERIFICHE_MAIL ADD CONSTRAINT PK_ANAGRAFE_VERIFICHE_MAIL PRIMARY KEY(IDCOMUNE,ID); 
ALTER TABLE ANAGRAFE_VERIFICHE_MAIL ADD CONSTRAINT FK_ANAGRAFEVERMAIL_ANAG FOREIGN KEY(IDCOMUNE,FK_CODICEANAGRAFE) REFERENCES ANAGRAFE (IDCOMUNE, CODICEANAGRAFE);

CREATE INDEX IDX_ANAG_VERIFICHE_MAIL_001 ON ANAGRAFE_VERIFICHE_MAIL(IDCOMUNE, FK_CODICEANAGRAFE, CODICE_VERIFICA);

alter table boll_cfg_tipo_rate drop CONSTRAINT FK_BLCFGRATE_RANGERATE;
alter table boll_cfg_tipo_rate modify FK_RANGERATE number (6,0);
alter table boll_cfg_tipo_rate add constraint fk_blcfgrate_rangerate foreign key(idcomune,fk_rangerate) references range_rateizzazioni(idcomune,id);

CREATE TABLE ANAGRAFE_INDIRIZZI(IDCOMUNE VARCHAR2(6 CHAR) NOT NULL,  ID NUMBER(10,0) NOT NULL,  CODICEANAGRAFE NUMBER(6,0) NOT NULL,  IDENTIFICATIVO_SEDE VARCHAR2(20 CHAR), PARTITAIVA VARCHAR2(11 CHAR), CODICEFISCALE VARCHAR2(16 CHAR), CITTA VARCHAR2(50 CHAR), INDIRIZZO VARCHAR2(100 CHAR));
ALTER TABLE ANAGRAFE_INDIRIZZI ADD CONSTRAINT PK_ANAGRAFE_INDIRIZZI PRIMARY KEY(IDCOMUNE,ID);
ALTER TABLE ANAGRAFE_INDIRIZZI ADD CONSTRAINT FK_ANAGRAFE_INDIRIZZI_001 FOREIGN KEY(IDCOMUNE,CODICEANAGRAFE) REFERENCES ANAGRAFE(IDCOMUNE,CODICEANAGRAFE);
CREATE INDEX IDX_ANAGRAFE_INDIRIZZI_001 ON ANAGRAFE_INDIRIZZI (IDCOMUNE,CODICEANAGRAFE);

CREATE TABLE APP_IO_SERVIZI (IDCOMUNE VARCHAR2(6 CHAR) NOT NULL,IDENTIFICATIVO_SERVIZIO VARCHAR2(50 CHAR) NOT NULL,DESCRIZIONE VARCHAR2(1000 CHAR));
ALTER TABLE APP_IO_SERVIZI ADD CONSTRAINT PK_APP_IO_SERVIZI PRIMARY KEY(IDCOMUNE,IDENTIFICATIVO_SERVIZIO);
CREATE TABLE APP_IO_PARAM (IDCOMUNE VARCHAR2(6 CHAR) NOT NULL,IDENTIFICATIVO_SERVIZIO VARCHAR2(50 CHAR) NOT NULL,PARAMETRO VARCHAR2(50 CHAR) NOT NULL,DESCRIZIONE VARCHAR2(1000 CHAR));
ALTER TABLE APP_IO_PARAM ADD CONSTRAINT PK_APP_IO_PARAM PRIMARY KEY(IDCOMUNE,IDENTIFICATIVO_SERVIZIO,PARAMETRO);
ALTER TABLE APP_IO_PARAM ADD CONSTRAINT FK_APP_IO_PARAM FOREIGN KEY(IDCOMUNE,IDENTIFICATIVO_SERVIZIO) REFERENCES APP_IO_SERVIZI(IDCOMUNE,IDENTIFICATIVO_SERVIZIO);
CREATE TABLE APP_IO_SERVIZI_CONFIG (IDCOMUNE VARCHAR2(6 CHAR) NOT NULL,CODICECOMUNE VARCHAR2(5 CHAR) NOT NULL,SOFTWARE VARCHAR2(2 CHAR) NOT NULL,IDENTIFICATIVO_SERVIZIO VARCHAR2(50 CHAR) NOT NULL,AMBITO VARCHAR2(50 CHAR),MAX_MESSAGGI_GIORNO NUMBER(10,0),TEMPLATE_OGGETTO VARCHAR2(120 CHAR),TEMPLATE_MESSAGGIO CLOB, ATTIVO NUMBER(1,0));
ALTER TABLE APP_IO_SERVIZI_CONFIG ADD CONSTRAINT PK_APP_IO_SERVIZI_CONFIG PRIMARY KEY(IDCOMUNE,CODICECOMUNE,SOFTWARE,IDENTIFICATIVO_SERVIZIO);
ALTER TABLE APP_IO_SERVIZI_CONFIG ADD CONSTRAINT FK_SERVIZI_CONFIG FOREIGN KEY(IDCOMUNE,IDENTIFICATIVO_SERVIZIO) REFERENCES APP_IO_SERVIZI(IDCOMUNE,IDENTIFICATIVO_SERVIZIO);
CREATE TABLE APP_IO_SERVIZI_CONFIG_PARAM (IDCOMUNE VARCHAR2(6 CHAR) NOT NULL,CODICECOMUNE VARCHAR2(5 CHAR) NOT NULL,SOFTWARE VARCHAR2(2 CHAR) NOT NULL,IDENTIFICATIVO_SERVIZIO VARCHAR2(50 CHAR) NOT NULL,PARAMETRO VARCHAR2(50 CHAR) NOT NULL,DESCRIZIONE VARCHAR2(1000 CHAR));
ALTER TABLE APP_IO_SERVIZI_CONFIG_PARAM ADD CONSTRAINT PK_APP_IO_SERVIZI_CONFIG_PARAM PRIMARY KEY(IDCOMUNE,CODICECOMUNE,SOFTWARE,IDENTIFICATIVO_SERVIZIO,PARAMETRO);
ALTER TABLE APP_IO_SERVIZI_CONFIG_PARAM ADD CONSTRAINT FK_SERVIZI_CONFIG_PARAM FOREIGN KEY(IDCOMUNE,IDENTIFICATIVO_SERVIZIO) REFERENCES APP_IO_SERVIZI(IDCOMUNE,IDENTIFICATIVO_SERVIZIO);
CREATE TABLE TIPIMOVIMENTO_APP_IO_SERVIZI (IDCOMUNE VARCHAR2(6 CHAR) NOT NULL,TIPOMOVIMENTO VARCHAR2(8 CHAR) NOT NULL,IDENTIFICATIVO_SERVIZIO VARCHAR2(50 CHAR) NOT NULL);
ALTER TABLE TIPIMOVIMENTO_APP_IO_SERVIZI ADD CONSTRAINT PK_TIPIMOVIMENTO_SERVIZI PRIMARY KEY(IDCOMUNE,TIPOMOVIMENTO,IDENTIFICATIVO_SERVIZIO);
ALTER TABLE TIPIMOVIMENTO_APP_IO_SERVIZI ADD CONSTRAINT FK_TIPIMOVIMENTO_APP_IO FOREIGN KEY(IDCOMUNE,IDENTIFICATIVO_SERVIZIO) REFERENCES APP_IO_SERVIZI(IDCOMUNE,IDENTIFICATIVO_SERVIZIO);
ALTER TABLE TIPIMOVIMENTO_APP_IO_SERVIZI ADD CONSTRAINT FK_TIPIMOVIMENTO_APP_IO2 FOREIGN KEY(IDCOMUNE,TIPOMOVIMENTO) REFERENCES TIPIMOVIMENTO(IDCOMUNE,TIPOMOVIMENTO);
CREATE TABLE APP_IO_CODA (IDCOMUNE VARCHAR2(6 CHAR) NOT NULL,GUID VARCHAR2(40 CHAR) NOT NULL,IDENTIFICATIVO_SERVIZIO VARCHAR2(50 CHAR),CODICEFISCALE VARCHAR2(32 CHAR),OGGETTO VARCHAR2(120 char),MESSAGGIO CLOB,STATO VARCHAR2(50 CHAR),STATO_DATA DATE,STATO_MESSAGGIO VARCHAR2(200 CHAR),DATA_PREVISTA_ELABORAZIONE DATE,ORDINE NUMBER(10,0));
ALTER TABLE APP_IO_CODA ADD CONSTRAINT PK_APP_IO_CODA PRIMARY KEY(IDCOMUNE,GUID);
ALTER TABLE APP_IO_CODA ADD CONSTRAINT FK_APP_IO_CODA FOREIGN KEY(IDCOMUNE,IDENTIFICATIVO_SERVIZIO) REFERENCES APP_IO_SERVIZI(IDCOMUNE,IDENTIFICATIVO_SERVIZIO);
CREATE TABLE APP_IO_CODA_STATI (IDCOMUNE VARCHAR2(6 CHAR) NOT NULL,FK_GUIDCODA VARCHAR2(40 CHAR) NOT NULL,STATO VARCHAR2(50 CHAR),DATA DATE,STATO_APP_IO VARCHAR2(50 CHAR), MESSAGGIO CLOB);
ALTER TABLE APP_IO_CODA_STATI ADD CONSTRAINT PK_APP_IO_CODA_STATI PRIMARY KEY(IDCOMUNE,FK_GUIDCODA,STATO,DATA);
ALTER TABLE APP_IO_CODA_STATI ADD CONSTRAINT FK_APP_IO_CODA_STATI FOREIGN KEY(IDCOMUNE,FK_GUIDCODA) REFERENCES APP_IO_CODA(IDCOMUNE,GUID);
CREATE TABLE APP_IO_CODA_MOVIMENTI (IDCOMUNE VARCHAR2(6 CHAR) NOT NULL,CODICEMOVIMENTO NUMBER(8,0) NOT NULL,FK_GUIDCODA VARCHAR2(40 CHAR));
ALTER TABLE APP_IO_CODA_MOVIMENTI ADD CONSTRAINT PK_APP_IO_CODA_MOVIMENTI PRIMARY KEY(IDCOMUNE,CODICEMOVIMENTO,FK_GUIDCODA);
ALTER TABLE APP_IO_CODA_MOVIMENTI ADD CONSTRAINT FK_APP_IO_CODA_MOVIMENTI FOREIGN KEY(IDCOMUNE,FK_GUIDCODA) REFERENCES APP_IO_CODA(IDCOMUNE,GUID);
ALTER TABLE APP_IO_CODA_MOVIMENTI ADD CONSTRAINT FK_APP_IO_CODA_MOVIMENTI2 FOREIGN KEY(IDCOMUNE,CODICEMOVIMENTO) REFERENCES MOVIMENTI(IDCOMUNE,CODICEMOVIMENTO);
