package it.gruppoinit.pal.gp.core.domain;

import it.gruppoinit.pal.gp.core.constants.WebConstants;
import it.gruppoinit.pal.gp.core.dao.helper.PkIdGenerator;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.apache.commons.lang.StringUtils;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotEmpty;

/**
 * Anagrafestorico generated by hbm2java
 */
@Entity
@Table(name = "ANAGRAFESTORICO")
public class Anagrafestorico implements java.io.Serializable {

    /**
     * @author gianpaolot
     */
    private static final long serialVersionUID = 7266347911973575191L;
    private PkId id;
    private Comuni comuneNascita;
    private Titoli titolo;
    private Comuni comunecorrispondenza;
    private Formegiuridiche formagiuridica;
    private Comuni comuneregtrib;
    private Comuni comuneResidenza;
    private Cittadinanza cittadinanza;
    private Comuni comunecomregditte;
    private Anagrafe anagrafe;
    private Responsabili responsabili;
    private String nominativo;
    private String referente;
    private Integer tipologia;
    private String indirizzo;
    private String citta;
    private String cap;
    private String provincia;
    private String telefono;
    private String telefonocellulare;
    private String fax;
    private String partitaiva;
    private String legalerappresentante;
    private String codicefiscale;
    private String note;
    private String email;
    private String pec;
    private String regditte;
    private String regtrib;
    private Date datanascita;
    private Date dataregditte;
    private Date dataregtrib;
    private Boolean invioemail;
    private String sesso;
    private String nome;
    private String tipoanagrafe;
    private String indirizzolr;
    private String cittalr;
    private String caplr;
    private String provincialr;
    private String telefonolr;
    private String telefonocellularelr;
    private Date datanominativo;
    private Boolean invioemailtec;
    private String password;
    private String indirizzocorrispondenza;
    private String cittacorrispondenza;
    private String capcorrispondenza;
    private String provinciacorrispondenza;
    private String provinciarea;
    private String numiscrrea;
    private Date dataiscrrea;
    private String codicefiscalelr;
    private Boolean flagNoprofit;
    private Integer flagDisabilitato;
    private Date dataDisabilitato;
    private Date dataInizioAttivita;
    private Short codiceelencopro;
    private String numeroelencopro;
    private String provinciaelencopro;
    private Date datainiziovalidita;
    private Date datafinevalidita;
    private Boolean foUtentetester;
    private String inailMatricola;
    private Elencoinailbase sedeInail;
    private String inpsMatricola;
    private Elencoinpsbase sedeInps;
    private String cassaedileMatricola;
    private Elencocassaedilebase sedeCassaedile;
    private Boolean flagIdentificato;
    private Responsabili operatoreIdentificazione;
    private Date dataIdentificazione;
    private Set<Istanze> richiedenteistanzestoricos = new HashSet<Istanze>(0);
    private Set<Istanze> titolarelegaleistanzestoricos = new HashSet<Istanze>(0);
    private Set<Istanze> professionistastoricoistanzestoricos = new HashSet<Istanze>(0);
    private Set<Istanzerichiedenti> istanzerichiedenteAnagrafestoricos = new HashSet<Istanzerichiedenti>(0);
    private Set<Istanzerichiedenti> istanzerichiedentiProfessionistastoricos = new HashSet<Istanzerichiedenti>(0);
    private Set<Istanzerichiedenti> istanzerichiedentiTitolarelegalestoricos = new HashSet<Istanzerichiedenti>(0);
    // Campi Transiet per la visulaizzazione di informazioni sulla tabella
    private String corrispondenza;
    private String richiedente;
    private String descrizioneRichiedente;
    private String descrizioneResidenza;
    private boolean isFirst;
    private boolean isLast;
    private boolean flagMailVerificata;

    public Anagrafestorico() {

	this.id = new PkId();
	this.comunecomregditte = new Comuni();
	this.comunecorrispondenza = new Comuni();
	this.comuneNascita = new Comuni();
	this.comuneregtrib = new Comuni();
	this.comuneResidenza = new Comuni();
	this.cittadinanza = new Cittadinanza();
	this.anagrafe = new Anagrafe();
	this.titolo = new Titoli();
	this.formagiuridica = new Formegiuridiche();
	this.isFirst = false;
	this.isLast = false;
    }

    @EmbeddedId
    @GenericGenerator(name = "pkGenerator", strategy = "it.gruppoinit.pal.gp.core.dao.helper.PkIdGenerator", parameters = {
	    @Parameter(name = PkIdGenerator.CONFIG_PREFER_SEGMENT_PER_ENTITY, value = "true"),
	    @Parameter(name = PkIdGenerator.TABLE_PARAM, value = "SEQUENCETABLE"),
	    @Parameter(name = PkIdGenerator.VALUE_COLUMN_PARAM, value = "CURRVAL"),
	    @Parameter(name = PkIdGenerator.SEGMENT_COLUMN_PARAM, value = "SEQUENCENAME"),
	    @Parameter(name = PkIdGenerator.SEGMENT_VALUE_PARAM, value = "ANAGRAFESTORICO.ID") })
    @GeneratedValue(generator = "pkGenerator")
    @AttributeOverrides({ @AttributeOverride(name = "idcomune", column = @Column(name = "IDCOMUNE", nullable = false, length = 6)),
	    @AttributeOverride(name = "codice", column = @Column(name = "ID", nullable = false, precision = 6, scale = 0)) })
    public PkId getId() {

	return this.id;
    }

    public void setId(PkId id) {

	this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CODCOMNASCITA", referencedColumnName = "CODICECOMUNE")
    public Comuni getComuneNascita() {

	return comuneNascita;
    }

    public void setComuneNascita(Comuni comuneNascita) {

	this.comuneNascita = comuneNascita;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumns({ @JoinColumn(name = "IDCOMUNE", referencedColumnName = "IDCOMUNE", nullable = false, insertable = false, updatable = false),
	    @JoinColumn(name = "TITOLO", referencedColumnName = "CODICETITOLO", nullable = false, insertable = false, updatable = false) })
    public Titoli getTitolo() {

	return this.titolo;
    }

    public void setTitolo(Titoli titolo) {

	this.titolo = titolo;
    }

    // FIXME WORKAROUND PER AGGIORNAMENTO CHIAVI ESTERNE COMPOSITE///
    private Integer titoloId;

    @Column(name = "TITOLO")
    @SuppressWarnings("unused")
    private Integer getTitoloId() {

	if (null != this.getTitolo()) {
	    if (null != this.getTitolo().getId()) {
		this.titoloId = getTitolo().getId().getCodice();
		return this.titoloId;
	    }
	}
	return null;
    }

    @SuppressWarnings("unused")
    private void setTitoloId(Integer titoloId) {

	if (null != this.getTitolo()) {
	    if (null != this.getTitolo().getId()) {
		this.titoloId = getTitolo().getId().getCodice();
	    }
	}
    }

    // END FIX/////////////////////////////////////////////////////
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "COMUNECORRISPONDENZA", referencedColumnName = "CODICECOMUNE")
    public Comuni getComunecorrispondenza() {

	return comunecorrispondenza;
    }

    public void setComunecorrispondenza(Comuni comunecorrispondenza) {

	this.comunecorrispondenza = comunecorrispondenza;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumns({ @JoinColumn(name = "IDCOMUNE", referencedColumnName = "IDCOMUNE", nullable = false, insertable = false, updatable = false),
	    @JoinColumn(name = "FORMAGIURIDICA", referencedColumnName = "CODICEFORMAGIURIDICA", nullable = false, insertable = false, updatable = false) })
    public Formegiuridiche getFormagiuridica() {

	return formagiuridica;
    }

    public void setFormagiuridica(Formegiuridiche formagiuridica) {

	this.formagiuridica = formagiuridica;
    }

    // FIXME WORKAROUND PER AGGIORNAMENTO CHIAVI ESTERNE COMPOSITE///
    private Integer formagiuridicaId;

    @Column(name = "FORMAGIURIDICA")
    @SuppressWarnings("unused")
    private Integer getFormagiuridicaId() {

	if (null != this.getFormagiuridica()) {
	    if (null != this.getFormagiuridica().getId()) {
		this.formagiuridicaId = getFormagiuridica().getId().getCodice();
		return this.formagiuridicaId;
	    }
	}
	return null;
    }

    @SuppressWarnings("unused")
    private void setFormagiuridicaId(Integer formagiuridicaId) {

	if (null != this.getFormagiuridica()) {
	    if (null != this.getFormagiuridica().getId()) {
		this.formagiuridicaId = getFormagiuridica().getId().getCodice();
	    }
	}
    }

    // END FIX/////////////////////////////////////////////////////
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CODCOMREGTRIB", referencedColumnName = "CODICECOMUNE")
    public Comuni getComuneregtrib() {

	return comuneregtrib;
    }

    public void setComuneregtrib(Comuni comuneregtrib) {

	this.comuneregtrib = comuneregtrib;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "COMUNERESIDENZA", referencedColumnName = "CODICECOMUNE")
    public Comuni getComuneResidenza() {

	return comuneResidenza;
    }

    public void setComuneResidenza(Comuni comuneResidenza) {

	this.comuneResidenza = comuneResidenza;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CODICECITTADINANZA", referencedColumnName = "CODICE")
    public Cittadinanza getCittadinanza() {

	return this.cittadinanza;
    }

    public void setCittadinanza(Cittadinanza cittadinanza) {

	this.cittadinanza = cittadinanza;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CODCOMREGDITTE", referencedColumnName = "CODICECOMUNE")
    public Comuni getComunecomregditte() {

	return comunecomregditte;
    }

    public void setComunecomregditte(Comuni comunecomregditte) {

	this.comunecomregditte = comunecomregditte;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumns({ @JoinColumn(name = "IDCOMUNE", referencedColumnName = "IDCOMUNE", nullable = false, insertable = false, updatable = false),
	    @JoinColumn(name = "CODICEANAGRAFE", referencedColumnName = "CODICEANAGRAFE", nullable = false, insertable = false, updatable = false) })
    public Anagrafe getAnagrafe() {

	return this.anagrafe;
    }

    public void setAnagrafe(Anagrafe anagrafe) {

	this.anagrafe = anagrafe;
    }

    // FIXME WORKAROUND PER AGGIORNAMENTO CHIAVI ESTERNE COMPOSITE///
    private Integer anagrafeId;

    @Column(name = "CODICEANAGRAFE")
    @SuppressWarnings("unused")
    private Integer getAnagrafeId() {

	if (null != this.getAnagrafe()) {
	    if (null != this.getAnagrafe().getId()) {
		this.anagrafeId = getAnagrafe().getId().getCodice();
		return this.anagrafeId;
	    }
	}
	return null;
    }

    @SuppressWarnings("unused")
    private void setAnagrafeId(Integer anagrafeId) {

	if (null != this.getAnagrafe()) {
	    if (null != this.getAnagrafe().getId()) {
		this.anagrafeId = getAnagrafe().getId().getCodice();
	    }
	}
    }

    // END FIX/////////////////////////////////////////////////////
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumns({ @JoinColumn(name = "IDCOMUNE", referencedColumnName = "IDCOMUNE", nullable = false, insertable = false, updatable = false),
	    @JoinColumn(name = "FK_CODICERESPONSABILE", referencedColumnName = "CODICERESPONSABILE", nullable = false, insertable = false, updatable = false) })
    public Responsabili getResponsabili() {

	return responsabili;
    }

    public void setResponsabili(Responsabili responsabili) {

	this.responsabili = responsabili;
    }

    //FIXME WORKAROUND PER AGGIORNAMENTO CHIAVI ESTERNE COMPOSITE///
    private Integer responsabiliId;

    @Column(name = "FK_CODICERESPONSABILE")
    @SuppressWarnings("unused")
    private Integer getResponsabiliId() {

	if (null != this.getResponsabili()) {
	    if (null != this.getResponsabili().getId()) {
		this.responsabiliId = getResponsabili().getId().getCodice();
		return this.responsabiliId;
	    }
	}
	return null;
    }

    @SuppressWarnings("unused")
    private void setResponsabiliId(Integer responsabiliId) {

	if (null != this.getResponsabili()) {
	    if (null != this.getResponsabili().getId()) {
		this.responsabiliId = getResponsabili().getId().getCodice();
	    }
	}
    }

    //END FIX/////////////////////////////////////////////////////
    @Column(name = "NOMINATIVO", length = 220)
    public String getNominativo() {

	return this.nominativo;
    }

    public void setNominativo(String nominativo) {

	this.nominativo = nominativo;
    }

    @Column(name = "REFERENTE", length = 80)
    public String getReferente() {

	return this.referente;
    }

    public void setReferente(String referente) {

	this.referente = referente;
    }

    @Column(name = "TIPOLOGIA", precision = 4, scale = 0)
    public Integer getTipologia() {

	return this.tipologia;
    }

    public void setTipologia(Integer tipologia) {

	this.tipologia = tipologia;
    }

    @Column(name = "INDIRIZZO", length = 100)
    public String getIndirizzo() {

	return this.indirizzo;
    }

    public void setIndirizzo(String indirizzo) {

	this.indirizzo = indirizzo;
    }

    @Column(name = "CITTA", length = 50)
    public String getCitta() {

	return this.citta;
    }

    public void setCitta(String citta) {

	this.citta = citta;
    }

    @Column(name = "CAP", length = 15)
    public String getCap() {

	return this.cap;
    }

    public void setCap(String cap) {

	this.cap = cap;
    }

    @Column(name = "PROVINCIA", length = 2)
    public String getProvincia() {

	return this.provincia;
    }

    public void setProvincia(String provincia) {

	this.provincia = provincia;
    }

    @Column(name = "TELEFONO", length = 50)
    public String getTelefono() {

	return this.telefono;
    }

    public void setTelefono(String telefono) {

	this.telefono = telefono;
    }

    @Column(name = "TELEFONOCELLULARE", length = 50)
    public String getTelefonocellulare() {

	return this.telefonocellulare;
    }

    public void setTelefonocellulare(String telefonocellulare) {

	this.telefonocellulare = telefonocellulare;
    }

    @Column(name = "FAX", length = 50)
    public String getFax() {

	return this.fax;
    }

    public void setFax(String fax) {

	this.fax = fax;
    }

    @Column(name = "PARTITAIVA", length = 32)
    public String getPartitaiva() {

	return this.partitaiva;
    }

    public void setPartitaiva(String partitaiva) {

	this.partitaiva = partitaiva;
    }

    @Column(name = "LEGALERAPPRESENTANTE", length = 60)
    public String getLegalerappresentante() {

	return this.legalerappresentante;
    }

    public void setLegalerappresentante(String legalerappresentante) {

	this.legalerappresentante = legalerappresentante;
    }

    @Column(name = "CODICEFISCALE", length = 32)
    public String getCodicefiscale() {

	return this.codicefiscale;
    }

    public void setCodicefiscale(String codicefiscale) {

	this.codicefiscale = codicefiscale;
    }

    @Column(name = "NOTE", length = 4000)
    public String getNote() {

	return this.note;
    }

    public void setNote(String note) {

	this.note = note;
    }

    @Column(name = "EMAIL", length = 320)
    public String getEmail() {

	return this.email;
    }

    public void setEmail(String email) {

	this.email = email;
    }

    @Column(name = "PEC", length = 320)
    public String getPec() {

	return pec;
    }

    public void setPec(String pec) {

	this.pec = pec;
    }

    @Column(name = "REGDITTE", length = 20)
    public String getRegditte() {

	return this.regditte;
    }

    public void setRegditte(String regditte) {

	this.regditte = regditte;
    }

    @Column(name = "REGTRIB", length = 20)
    public String getRegtrib() {

	return this.regtrib;
    }

    public void setRegtrib(String regtrib) {

	this.regtrib = regtrib;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "DATANASCITA", length = 7)
    public Date getDatanascita() {

	return this.datanascita;
    }

    public void setDatanascita(Date datanascita) {

	this.datanascita = datanascita;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "DATAREGDITTE", length = 7)
    public Date getDataregditte() {

	return this.dataregditte;
    }

    public void setDataregditte(Date dataregditte) {

	this.dataregditte = dataregditte;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "DATAREGTRIB", length = 7)
    public Date getDataregtrib() {

	return this.dataregtrib;
    }

    public void setDataregtrib(Date dataregtrib) {

	this.dataregtrib = dataregtrib;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "DATA_INIZIO_ATTIVITA", length = 7)
    public Date getDataInizioAttivita() {

	return dataInizioAttivita;
    }

    public void setDataInizioAttivita(Date dataInizioAttivita) {

	this.dataInizioAttivita = dataInizioAttivita;
    }

    @Column(name = "INVIOEMAIL", precision = 1, scale = 0)
    public Boolean getInvioemail() {

	return this.invioemail;
    }

    public void setInvioemail(Boolean invioemail) {

	this.invioemail = invioemail;
    }

    @Column(name = "SESSO", length = 1)
    public String getSesso() {

	return this.sesso;
    }

    public void setSesso(String sesso) {

	this.sesso = sesso;
    }

    @Column(name = "NOME", length = 60)
    public String getNome() {

	return this.nome;
    }

    public void setNome(String nome) {

	this.nome = nome;
    }

    @NotEmpty
    @Column(name = "TIPOANAGRAFE", length = 1)
    public String getTipoanagrafe() {

	return this.tipoanagrafe;
    }

    public void setTipoanagrafe(String tipoanagrafe) {

	this.tipoanagrafe = tipoanagrafe;
    }

    @Column(name = "INDIRIZZOLR", length = 80)
    public String getIndirizzolr() {

	return this.indirizzolr;
    }

    public void setIndirizzolr(String indirizzolr) {

	this.indirizzolr = indirizzolr;
    }

    @Column(name = "CITTALR", length = 50)
    public String getCittalr() {

	return this.cittalr;
    }

    public void setCittalr(String cittalr) {

	this.cittalr = cittalr;
    }

    @Column(name = "CAPLR", length = 15)
    public String getCaplr() {

	return this.caplr;
    }

    public void setCaplr(String caplr) {

	this.caplr = caplr;
    }

    @Column(name = "PROVINCIALR", length = 2)
    public String getProvincialr() {

	return this.provincialr;
    }

    public void setProvincialr(String provincialr) {

	this.provincialr = provincialr;
    }

    @Column(name = "TELEFONOLR", length = 50)
    public String getTelefonolr() {

	return this.telefonolr;
    }

    public void setTelefonolr(String telefonolr) {

	this.telefonolr = telefonolr;
    }

    @Column(name = "TELEFONOCELLULARELR", length = 50)
    public String getTelefonocellularelr() {

	return this.telefonocellularelr;
    }

    public void setTelefonocellularelr(String telefonocellularelr) {

	this.telefonocellularelr = telefonocellularelr;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "DATANOMINATIVO", length = 7)
    public Date getDatanominativo() {

	return this.datanominativo;
    }

    public void setDatanominativo(Date datanominativo) {

	this.datanominativo = datanominativo;
    }

    @Column(name = "INVIOEMAILTEC", precision = 1, scale = 0)
    public Boolean getInvioemailtec() {

	return this.invioemailtec;
    }

    public void setInvioemailtec(Boolean invioemailtec) {

	this.invioemailtec = invioemailtec;
    }

    @Column(name = "PASSWORD", length = 128)
    public String getPassword() {

	return this.password;
    }

    public void setPassword(String password) {

	this.password = password;
    }

    @Column(name = "INDIRIZZOCORRISPONDENZA", length = 80)
    public String getIndirizzocorrispondenza() {

	return this.indirizzocorrispondenza;
    }

    public void setIndirizzocorrispondenza(String indirizzocorrispondenza) {

	this.indirizzocorrispondenza = indirizzocorrispondenza;
    }

    @Column(name = "CITTACORRISPONDENZA", length = 50)
    public String getCittacorrispondenza() {

	return this.cittacorrispondenza;
    }

    public void setCittacorrispondenza(String cittacorrispondenza) {

	this.cittacorrispondenza = cittacorrispondenza;
    }

    @Column(name = "CAPCORRISPONDENZA", length = 15)
    public String getCapcorrispondenza() {

	return this.capcorrispondenza;
    }

    public void setCapcorrispondenza(String capcorrispondenza) {

	this.capcorrispondenza = capcorrispondenza;
    }

    @Column(name = "PROVINCIACORRISPONDENZA", length = 2)
    public String getProvinciacorrispondenza() {

	return this.provinciacorrispondenza;
    }

    public void setProvinciacorrispondenza(String provinciacorrispondenza) {

	this.provinciacorrispondenza = provinciacorrispondenza;
    }

    @Column(name = "PROVINCIAREA", length = 2)
    public String getProvinciarea() {

	return this.provinciarea;
    }

    public void setProvinciarea(String provinciarea) {

	this.provinciarea = provinciarea;
    }

    @Column(name = "NUMISCRREA", length = 20)
    public String getNumiscrrea() {

	return this.numiscrrea;
    }

    public void setNumiscrrea(String numiscrrea) {

	this.numiscrrea = numiscrrea;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "DATAISCRREA", length = 7)
    public Date getDataiscrrea() {

	return this.dataiscrrea;
    }

    public void setDataiscrrea(Date dataiscrrea) {

	this.dataiscrrea = dataiscrrea;
    }

    @Column(name = "CODICEFISCALELR", length = 20)
    public String getCodicefiscalelr() {

	return this.codicefiscalelr;
    }

    public void setCodicefiscalelr(String codicefiscalelr) {

	this.codicefiscalelr = codicefiscalelr;
    }

    @Column(name = "FLAG_NOPROFIT", precision = 1, scale = 0)
    public Boolean getFlagNoprofit() {

	return this.flagNoprofit;
    }

    public void setFlagNoprofit(Boolean flagNoprofit) {

	this.flagNoprofit = flagNoprofit;
    }

    @Column(name = "FLAG_MAIL_VERIFICATA", precision = 1, scale = 0)
    public boolean getFlagMailVerificata() {

	return flagMailVerificata;
    }

    public void setFlagMailVerificata(boolean flagMailVerificata) {

	this.flagMailVerificata = flagMailVerificata;
    }

    @Column(name = "FLAG_DISABILITATO", precision = 1, scale = 0)
    public Integer getFlagDisabilitato() {

	return this.flagDisabilitato;
    }

    public void setFlagDisabilitato(Integer flagDisabilitato) {

	this.flagDisabilitato = flagDisabilitato;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "DATA_DISABILITATO", length = 7)
    public Date getDataDisabilitato() {

	return this.dataDisabilitato;
    }

    public void setDataDisabilitato(Date dataDisabilitato) {

	this.dataDisabilitato = dataDisabilitato;
    }

    @Column(name = "CODICEELENCOPRO", precision = 4, scale = 0)
    public Short getCodiceelencopro() {

	return this.codiceelencopro;
    }

    public void setCodiceelencopro(Short codiceelencopro) {

	this.codiceelencopro = codiceelencopro;
    }

    @Column(name = "NUMEROELENCOPRO", length = 10)
    public String getNumeroelencopro() {

	return this.numeroelencopro;
    }

    public void setNumeroelencopro(String numeroelencopro) {

	this.numeroelencopro = numeroelencopro;
    }

    @Column(name = "PROVINCIAELENCOPRO", length = 50)
    public String getProvinciaelencopro() {

	return this.provinciaelencopro;
    }

    public void setProvinciaelencopro(String provinciaelencopro) {

	this.provinciaelencopro = provinciaelencopro;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "DATAINIZIOVALIDITA", length = 7)
    public Date getDatainiziovalidita() {

	return this.datainiziovalidita;
    }

    public void setDatainiziovalidita(Date datainiziovalidita) {

	this.datainiziovalidita = datainiziovalidita;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "DATAFINEVALIDITA", length = 7)
    public Date getDatafinevalidita() {

	return this.datafinevalidita;
    }

    public void setDatafinevalidita(Date datafinevalidita) {

	this.datafinevalidita = datafinevalidita;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "richiedentestorico")
    public Set<Istanze> getRichiedenteistanzestoricos() {

	return richiedenteistanzestoricos;
    }

    public void setRichiedenteistanzestoricos(Set<Istanze> richiedenteistanzestoricos) {

	this.richiedenteistanzestoricos = richiedenteistanzestoricos;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "titolarelegalestorico")
    public Set<Istanze> getTitolarelegaleistanzestoricos() {

	return titolarelegaleistanzestoricos;
    }

    public void setTitolarelegaleistanzestoricos(Set<Istanze> titolarelegaleistanzestoricos) {

	this.titolarelegaleistanzestoricos = titolarelegaleistanzestoricos;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "professionistastorico")
    public Set<Istanze> getProfessionistastoricoistanzestoricos() {

	return professionistastoricoistanzestoricos;
    }

    public void setProfessionistastoricoistanzestoricos(Set<Istanze> professionistastoricoistanzestoricos) {

	this.professionistastoricoistanzestoricos = professionistastoricoistanzestoricos;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "richiedentestorico")
    public Set<Istanzerichiedenti> getIstanzerichiedenteAnagrafestoricos() {

	return istanzerichiedenteAnagrafestoricos;
    }

    public void setIstanzerichiedenteAnagrafestoricos(Set<Istanzerichiedenti> istanzerichiedenteAnagrafestoricos) {

	this.istanzerichiedenteAnagrafestoricos = istanzerichiedenteAnagrafestoricos;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "procuratorestorico")
    public Set<Istanzerichiedenti> getIstanzerichiedentiProfessionistastoricos() {

	return istanzerichiedentiProfessionistastoricos;
    }

    public void setIstanzerichiedentiProfessionistastoricos(Set<Istanzerichiedenti> istanzerichiedentiProfessionistastoricos) {

	this.istanzerichiedentiProfessionistastoricos = istanzerichiedentiProfessionistastoricos;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "anagrafeCollegatastorico")
    public Set<Istanzerichiedenti> getIstanzerichiedentiTitolarelegalestoricos() {

	return istanzerichiedentiTitolarelegalestoricos;
    }

    public void setIstanzerichiedentiTitolarelegalestoricos(Set<Istanzerichiedenti> istanzerichiedentiTitolarelegalestoricos) {

	this.istanzerichiedentiTitolarelegalestoricos = istanzerichiedentiTitolarelegalestoricos;
    }

    /**
     * Torna la descrizione del richiedente formulata in maniera estesa
     * 
     * <pre>
     * se Tipoanagrafe = 'G' allora persona giuridica
     * 	 In.I.T. s.r.l. CF: AAABBB01H0OIUOI P.Iva: 0220123453456
     * altrimenti è persona fisica
     * 	 Bocci Riccardo CF: BCCRCR73H23G888O
     * </pre>
     * 
     * @return
     */
    @Transient
    public String getDescrizioneRichiedente() {

	String answer = "";
	if (StringUtils.isBlank(getTipoanagrafe())) {
	    return getNominativo();
	}
	String tNominativo = getNominativo() == null ? "" : getNominativo();
	if (getTipoanagrafe().equalsIgnoreCase(WebConstants.PERSONA_FISICA)) {
	    answer = tNominativo + " " + (getNome() == null ? "" : getNome());
	    if (StringUtils.isNotBlank(getCodicefiscale())) {
		answer += " CF: " + getCodicefiscale();
	    }
	} else {
	    answer = tNominativo;
	    String tFormaGiuridica = "";
	    if (getFormagiuridica() != null) {
		Formegiuridiche fg = getFormagiuridica();
		tFormaGiuridica = fg.getFormagiuridica();
	    }
	    answer += " " + tFormaGiuridica;
	    if (StringUtils.isNotBlank(getPartitaiva())) {
		answer += " P.Iva: " + getPartitaiva();
	    }
	    if (StringUtils.isNotBlank(getCodicefiscale())) {
		answer += " CF: " + getCodicefiscale();
	    }
	}
	if (getTipologia() != null) {
	    if (getTipologia().intValue() == -1) {
		answer += " T";
	    }
	}
	if (getFlagDisabilitato() != null && getFlagDisabilitato().equals(Integer.valueOf(1))) {
	    answer += " [Disabilitata]";
	}
	setDescrizioneRichiedente(answer);
	return descrizioneRichiedente;
    }

    public void setDescrizioneRichiedente(String descrizioneRichiedente) {

	this.descrizioneRichiedente = descrizioneRichiedente;
    }

    /**
     * Torna la descrizione della residenza di questa anagrafe formulata in maniera estesa nel formato<BR/>
     * INDIRIZZO, LOCALITA', CAP CITTA' PROVINCIA<BR/>
     * Es:
     * 
     * <pre>
     * 	via G. Carducci 62, Semonte, 06024 Gubbio PG
     * </pre>
     * 
     * @return
     */
    @Transient
    public String getDescrizioneResidenza() {

	String answer = "";
	if (StringUtils.isNotBlank(this.getIndirizzo())) {
	    answer = this.getIndirizzo();
	}
	if (StringUtils.isNotBlank(this.getCitta())) {
	    answer += ", " + this.getCitta();
	}
	try {
	    if (StringUtils.isNotBlank(this.getCap())
		    || (this.getComuneResidenza() != null && StringUtils.isNotBlank(this.getComuneResidenza().getCodicecomune())
			    || StringUtils.isNotBlank(this.getProvincia()))) {
		answer += ",";
		if (StringUtils.isNotBlank(this.getCap())) {
		    answer += " " + this.getCap();
		}
		if (this.getComuneResidenza() != null && StringUtils.isNotBlank(this.getComuneResidenza().getCodicecomune())) {
		    answer += " " + this.getComuneResidenza().getComune();
		}
		if (StringUtils.isNotBlank(this.getProvincia())) {
		    answer += " " + this.getProvincia();
		}
	    }
	} catch (Exception e) {
	    e.printStackTrace();
	}
	setDescrizioneResidenza(answer);
	return descrizioneResidenza;
    }

    public void setDescrizioneResidenza(String descrizioneResidenza) {

	this.descrizioneResidenza = descrizioneResidenza;
    }

    /**
     * Torna la descrizione dell' indirizzo di corrispondenza di questa anagrafe formulata in maniera estesa nel
     * formato<BR/>
     * INDIRIZZO, LOCALITA', CAP CITTA' PROVINCIA<BR/>
     * Es:
     * 
     * <pre>
     * 		via G. Carducci 62, Semonte, 06024 Gubbio PG
     * </pre>
     * 
     * @return
     */
    @Transient
    public String getCorrispondenza() {

	// String answer = "";
	// if (StringUtils.isNotBlank(this.getIndirizzocorrispondenza())) {
	// answer = this.getIndirizzo();
	// }
	// if (StringUtils.isNotBlank(this.getCittacorrispondenza())) {
	// answer += ", " + this.getCitta();
	// }
	// try {
	// if (StringUtils.isNotBlank(this.getCapcorrispondenza())
	// || (this.getComunecorrispondenza() != null &&
	// StringUtils.isNotBlank(this.getComunecorrispondenza().getCodicecomune()) || StringUtils
	// .isNotBlank(this.getProvinciacorrispondenza()))) {
	// answer += ",";
	// if (StringUtils.isNotBlank(this.getCapcorrispondenza())) {
	// answer += " " + this.getCap();
	// }
	// if (this.getComunecorrispondenza() != null &&
	// StringUtils.isNotBlank(this.getComunecorrispondenza().getComune())) {
	// answer += " " + this.getComunecorrispondenza().getComune();
	// }
	// if (StringUtils.isNotBlank(this.getProvinciacorrispondenza())) {
	// answer += " " + this.getProvinciacorrispondenza();
	// }
	// }
	// } catch (Exception e) {
	// e.printStackTrace();
	// }
	StringBuffer answer = new StringBuffer();
	if (StringUtils.isNotBlank(this.getIndirizzocorrispondenza())) {
	    answer.append(this.getIndirizzocorrispondenza()).append(",");
	}
	if (StringUtils.isNotBlank(this.getCittacorrispondenza())) {
	    answer.append(this.getCittacorrispondenza()).append(", ");
	}
	if (StringUtils.isNotBlank(this.getCapcorrispondenza())) {
	    answer.append(this.getCapcorrispondenza()).append(" ");
	}
	if (this.getComunecorrispondenza() != null && StringUtils.isNotBlank(this.getComunecorrispondenza().getCodicecomune())) {
	    answer.append(this.getComunecorrispondenza().getComune()).append(" ");
	}
	if (StringUtils.isNotBlank(this.getProvinciacorrispondenza())) {
	    answer.append("(").append(this.getProvinciacorrispondenza()).append(")");
	}
	setCorrispondenza(answer.toString());
	return corrispondenza;
    }

    public void setCorrispondenza(String corrispondenza) {

	this.corrispondenza = corrispondenza;
    }

    @Transient
    public String getRichiedente() {

	// String answer = "";
	// String tNome = getNome() == null ? "" : getNome();
	// String tNominativo = getNominativo() == null ? "" : getNominativo();
	// answer = tNominativo + " " + tNome;
	// setRichiedente(answer);
	StringBuffer answer = new StringBuffer();
	if (StringUtils.isNotBlank(getNominativo())) {
	    answer.append(getNominativo());
	}
	if (StringUtils.isNotBlank(getNome())) {
	    answer.append(" ").append(getNome());
	}
	if (getFormagiuridica() != null && getFormagiuridica().getId().getCodice() != null) {
	    answer.append(" - ").append(getFormagiuridica().getFormagiuridica());
	}
	if (StringUtils.isNotBlank(getCodicefiscale()) && StringUtils.isNotBlank(getPartitaiva())) {
	    answer.append(" (").append(getCodicefiscale()).append(", ").append(getPartitaiva()).append(")");
	} else {
	    if (StringUtils.isNotBlank(getPartitaiva())) {
		answer.append(" (").append(getPartitaiva()).append(")");
	    }
	    if (StringUtils.isNotBlank(getCodicefiscale())) {
		answer.append(" (").append(getCodicefiscale()).append(")");
	    }
	}
	if (StringUtils.isNotBlank(getTipoanagrafe())) {
	    answer.append("- [P").append(getTipoanagrafe()).append("]");
	}
	setRichiedente(answer.toString());
	return richiedente;
    }

    public void setRichiedente(String richiedente) {

	this.richiedente = richiedente;
    }

    @Transient
    public boolean getIsFirst() {

	return isFirst;
    }

    public void setIsFirst(boolean isFirst) {

	this.isFirst = isFirst;
    }

    @Transient
    public boolean getIsLast() {

	return isLast;
    }

    public void setIsLast(boolean isLast) {

	this.isLast = isLast;
    }

    @Column(name = "FO_UTENTETESTER", precision = 1, scale = 0)
    public Boolean getFoUtentetester() {

	return this.foUtentetester;
    }

    public void setFoUtentetester(Boolean foUtentetester) {

	this.foUtentetester = foUtentetester;
    }

    @Length(max = 50)
    @Column(name = "INAIL_MATRICOLA", length = 50)
    public String getInailMatricola() {

	return inailMatricola;
    }

    public void setInailMatricola(String inailMatricola) {

	this.inailMatricola = inailMatricola;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "INAIL_CODICESEDE", nullable = true)
    public Elencoinailbase getSedeInail() {

	return sedeInail;
    }

    public void setSedeInail(Elencoinailbase sedeInail) {

	this.sedeInail = sedeInail;
    }

    @Length(max = 50)
    @Column(name = "INPS_MATRICOLA", length = 50)
    public String getInpsMatricola() {

	return inpsMatricola;
    }

    public void setInpsMatricola(String inpsMatricola) {

	this.inpsMatricola = inpsMatricola;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "INPS_CODICESEDE", nullable = true)
    public Elencoinpsbase getSedeInps() {

	return sedeInps;
    }

    public void setSedeInps(Elencoinpsbase sedeInps) {

	this.sedeInps = sedeInps;
    }

    @Length(max = 50)
    @Column(name = "CASSAEDILE_MATRICOLA", length = 50)
    public String getCassaedileMatricola() {

	return cassaedileMatricola;
    }

    public void setCassaedileMatricola(String cassaedileMatricola) {

	this.cassaedileMatricola = cassaedileMatricola;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CASSAEDILE_CODICESEDE", nullable = true)
    public Elencocassaedilebase getSedeCassaedile() {

	return sedeCassaedile;
    }

    public void setSedeCassaedile(Elencocassaedilebase sedeCassaedile) {

	this.sedeCassaedile = sedeCassaedile;
    }

    @Column(name = "FLAG_IDENTIFICATO", precision = 1, scale = 0)
    public Boolean getFlagIdentificato() {

	return flagIdentificato;
    }

    public void setFlagIdentificato(Boolean flagIdentificato) {

	this.flagIdentificato = flagIdentificato;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumns({ @JoinColumn(name = "IDCOMUNE", referencedColumnName = "IDCOMUNE", nullable = false, insertable = false, updatable = false),
	    @JoinColumn(name = "OPER_IDENTIFICAZIONE", referencedColumnName = "CODICERESPONSABILE", nullable = false, insertable = false, updatable = false) })
    public Responsabili getOperatoreIdentificazione() {

	return operatoreIdentificazione;
    }

    public void setOperatoreIdentificazione(Responsabili operatoreIdentificazione) {

	this.operatoreIdentificazione = operatoreIdentificazione;
    }

    //FIXME WORKAROUND PER AGGIORNAMENTO CHIAVI ESTERNE COMPOSITE///
    private Integer operatoreIdentificazioneId;

    @Column(name = "OPER_IDENTIFICAZIONE")
    @SuppressWarnings("unused")
    private Integer getOperatoreIdentificazioneId() {

	if (null != this.getOperatoreIdentificazione()) {
	    if (null != this.getOperatoreIdentificazione().getId()) {
		this.operatoreIdentificazioneId = getOperatoreIdentificazione().getId().getCodice();
		return this.operatoreIdentificazioneId;
	    }
	}
	return null;
    }

    @SuppressWarnings("unused")
    private void setOperatoreIdentificazioneId(Integer operatoreIdentificazioneId) {

	if (null != this.getOperatoreIdentificazione()) {
	    if (null != this.getOperatoreIdentificazione().getId()) {
		this.operatoreIdentificazioneId = getOperatoreIdentificazione().getId().getCodice();
	    }
	}
    }

    //END FIX/////////////////////////////////////////////////////
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "DATA_IDENTIFICAZIONE")
    public Date getDataIdentificazione() {

	return dataIdentificazione;
    }

    public void setDataIdentificazione(Date dataIdentificazione) {

	this.dataIdentificazione = dataIdentificazione;
    }
}
