package it.gruppoinit.pal.gp.core.domain;

import java.math.BigDecimal;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.validator.Max;
import org.hibernate.validator.Min;
import org.hibernate.validator.NotNull;

// Generated 29-set-2008 17.18.00 by Hibernate Tools 3.2.2.GA
import it.gruppoinit.pal.gp.core.dao.helper.PkIdGenerator;

/**
 * Areedettagli generated by hbm2java
 */
@Entity
@Table(name = "AREEDETTAGLI")
public class Areedettagli implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private PkId id;
    private Stradario stradario;
    private Aree aree;
    private Boolean paridispari;
    private Integer civicoDa;
    private Integer civicoA;
    private BigDecimal kmDa;
    private BigDecimal kmA;

    public Areedettagli() {

	this.id = new PkId();
	this.stradario = new Stradario();
	this.aree = new Aree();
    }

    @EmbeddedId
    @GenericGenerator(name = "pkGenerator", strategy = "it.gruppoinit.pal.gp.core.dao.helper.PkIdGenerator", parameters = {
	    @Parameter(name = PkIdGenerator.CONFIG_PREFER_SEGMENT_PER_ENTITY, value = "true"),
	    @Parameter(name = PkIdGenerator.TABLE_PARAM, value = "SEQUENCETABLE"),
	    @Parameter(name = PkIdGenerator.VALUE_COLUMN_PARAM, value = "CURRVAL"),
	    @Parameter(name = PkIdGenerator.SEGMENT_COLUMN_PARAM, value = "SEQUENCENAME"),
	    @Parameter(name = PkIdGenerator.SEGMENT_VALUE_PARAM, value = "AREEDETTAGLI.ID") })
    @GeneratedValue(generator = "pkGenerator")
    @AttributeOverrides({ @AttributeOverride(name = "idcomune", column = @Column(name = "IDCOMUNE", nullable = false, length = 6)),
	    @AttributeOverride(name = "codice", column = @Column(name = "ID", nullable = false, precision = 4, scale = 0)) })
    public PkId getId() {

	return this.id;
    }

    public void setId(PkId id) {

	this.id = id;
    }

    @NotNull
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumns({ @JoinColumn(name = "IDCOMUNE", referencedColumnName = "IDCOMUNE", nullable = false, insertable = false, updatable = false),
	    @JoinColumn(name = "CODICESTRADARIO", referencedColumnName = "CODICESTRADARIO", nullable = false, insertable = false, updatable = false) })
    public Stradario getStradario() {

	return this.stradario;
    }

    public void setStradario(Stradario stradario) {

	this.stradario = stradario;
    }

    // FIXME WORKAROUND PER AGGIORNAMENTO CHIAVI ESTERNE COMPOSITE///
    // siccome la relazione con l'oggetto forza all'uso di proprietà insertable e updatable false
    // E' necessario mappare un' ulteriore properietà anche con visibilità privata
    // che permette l'aggiornamento e l'inserimento della stessa.
    private Integer stradarioId;

    @Column(name = "CODICESTRADARIO")
    @SuppressWarnings("unused")
    private Integer getStradarioId() {

	if (null != this.getStradario() && null != this.getStradario().getId()) {
	    this.stradarioId = getStradario().getId().getCodice();
	    return this.stradarioId;
	}
	return null;
    }

    @SuppressWarnings("unused")
    private void setStradarioId(Integer stradarioId) {

	if (null != this.getStradario() && null != this.getStradario().getId()) {
	    this.stradarioId = getStradario().getId().getCodice();
	}
    }

    @NotNull
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumns({ @JoinColumn(name = "IDCOMUNE", referencedColumnName = "IDCOMUNE", nullable = false, insertable = false, updatable = false),
	    @JoinColumn(name = "CODICEAREA", referencedColumnName = "CODICEAREA", nullable = false, insertable = false, updatable = false) })
    public Aree getAree() {

	return this.aree;
    }

    public void setAree(Aree aree) {

	this.aree = aree;
    }

    // FIXME WORKAROUND PER AGGIORNAMENTO CHIAVI ESTERNE COMPOSITE///
    // siccome la relazione con l'oggetto forza all'uso di proprietà insertable e updatable false
    // E' necessario mappare un' ulteriore properietà anche con visibilità privata
    // che permette l'aggiornamento e l'inserimento della stessa.
    private Integer areaId;

    @Column(name = "CODICEAREA")
    @SuppressWarnings("unused")
    private Integer getAreaId() {

	if (null != this.getAree() && null != this.getAree().getId()) {
	    this.areaId = getAree().getId().getCodice();
	    return this.areaId;
	}
	return null;
    }

    @SuppressWarnings("unused")
    private void setAreaId(Integer areaId) {

	if (null != this.getAree() && null != this.getAree().getId()) {
	    this.areaId = getAree().getId().getCodice();
	}
    }

    @Column(name = "PARIDISPARI", precision = 1, scale = 0)
    public Boolean getParidispari() {

	return this.paridispari;
    }

    public void setParidispari(Boolean paridispari) {

	this.paridispari = paridispari;
    }

    @Max(value = 99999)
    @Min(value = 1)
    @Column(name = "CIVICO_DA", precision = 5, scale = 0)
    public Integer getCivicoDa() {

	return this.civicoDa;
    }

    public void setCivicoDa(Integer civicoDa) {

	this.civicoDa = civicoDa;
    }

    @Max(value = 99999)
    @Min(value = 1)
    @Column(name = "CIVICO_A", precision = 5, scale = 0)
    public Integer getCivicoA() {

	return this.civicoA;
    }

    public void setCivicoA(Integer civicoA) {

	this.civicoA = civicoA;
    }

    @Min(value = 0)
    @Column(name = "KM_DA", precision = 8, scale = 3)
    public BigDecimal getKmDa() {

	return kmDa;
    }

    public void setKmDa(BigDecimal kmDa) {

	this.kmDa = kmDa;
    }

    @Min(value = 0)
    @Column(name = "KM_A", precision = 8, scale = 3)
    public BigDecimal getKmA() {

	return kmA;
    }

    public void setKmA(BigDecimal kmA) {

	this.kmA = kmA;
    }
}
