package it.gruppoinit.pal.gp.core.domain;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Type;

/**
 * Ateco generated by hbm2java
 */
@Entity
@Table(name = "ATECO")
public class Ateco implements java.io.Serializable {

    private static final long serialVersionUID = 2495693966634473435L;
    private Integer id;
    private Ateco ateco;
    private String codice;
    private String titolo;
    private String descrizione;
    private String codicebreve;
    private Set<Ateco> atecos = new HashSet<Ateco>(0);

    public Ateco() {

	// this.ateco = new Ateco(); LOOP
    }

    @Id
    @Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
    public Integer getId() {

	return this.id;
    }

    public void setId(Integer id) {

	this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "FKIDPADRE")
    public Ateco getAteco() {

	return this.ateco;
    }

    public void setAteco(Ateco ateco) {

	this.ateco = ateco;
    }

    @Column(name = "CODICE", nullable = false, length = 25)
    public String getCodice() {

	return this.codice;
    }

    public void setCodice(String codice) {

	this.codice = codice;
    }

    @Column(name = "TITOLO", nullable = false, length = 1000)
    public String getTitolo() {

	return this.titolo;
    }

    public void setTitolo(String titolo) {

	this.titolo = titolo;
    }

    @Column(name = "DESCRIZIONE")
    @Type(type = "org.springframework.orm.hibernate3.support.ClobStringType")
    public String getDescrizione() {

	return this.descrizione;
    }

    public void setDescrizione(String descrizione) {

	this.descrizione = descrizione;
    }

    @Column(name = "CODICEBREVE", length = 80)
    public String getCodicebreve() {

	return this.codicebreve;
    }

    public void setCodicebreve(String codicebreve) {

	this.codicebreve = codicebreve;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "ateco")
    public Set<Ateco> getAtecos() {

	return this.atecos;
    }

    public void setAtecos(Set<Ateco> atecos) {

	this.atecos = atecos;
    }
}
