package it.gruppoinit.pal.gp.core.domain;

import it.gruppoinit.pal.gp.core.dao.helper.PkIdGenerator;

import java.math.BigDecimal;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * CcItabella1 generated by hbm2java
 */
@Entity
@Table(name = "CC_ITABELLA1")
public class CcItabella1 implements java.io.Serializable {

    private static final long serialVersionUID = 2575703038492553276L;
    private PkId id;
    private CcIcalcoli ccIcalcoli;
    private Istanze istanze;
    private CcClassisuperfici ccClassisuperfici;
    private Short alloggi;
    private BigDecimal su;
    private BigDecimal rapportoSu;
    private BigDecimal incremento;
    private BigDecimal incrementoxclassi;

    public CcItabella1() {

	this.id = new PkId();
    }

    @EmbeddedId
    @GenericGenerator(name = "pkGenerator", strategy = "it.gruppoinit.pal.gp.core.dao.helper.PkIdGenerator", parameters = {
	    @Parameter(name = PkIdGenerator.CONFIG_PREFER_SEGMENT_PER_ENTITY, value = "true"),
	    @Parameter(name = PkIdGenerator.TABLE_PARAM, value = "SEQUENCETABLE"),
	    @Parameter(name = PkIdGenerator.VALUE_COLUMN_PARAM, value = "CURRVAL"),
	    @Parameter(name = PkIdGenerator.SEGMENT_COLUMN_PARAM, value = "SEQUENCENAME"),
	    @Parameter(name = PkIdGenerator.SEGMENT_VALUE_PARAM, value = "CC_ITABELLA1.ID") })
    @GeneratedValue(generator = "pkGenerator")
    @AttributeOverrides({ @AttributeOverride(name = "idcomune", column = @Column(name = "IDCOMUNE", nullable = false, length = 6)),
	    @AttributeOverride(name = "codice", column = @Column(name = "ID", nullable = false, precision = 6, scale = 0)) })
    public PkId getId() {

	return this.id;
    }

    public void setId(PkId id) {

	this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumns({ @JoinColumn(name = "IDCOMUNE", referencedColumnName = "IDCOMUNE", nullable = false, insertable = false, updatable = false),
	    @JoinColumn(name = "FK_CCIC_ID", referencedColumnName = "ID", nullable = false, insertable = false, updatable = false) })
    public CcIcalcoli getCcIcalcoli() {

	return this.ccIcalcoli;
    }

    public void setCcIcalcoli(CcIcalcoli ccIcalcoli) {

	this.ccIcalcoli = ccIcalcoli;
    }

    //FIXME WORKAROUND PER AGGIORNAMENTO CHIAVI ESTERNE COMPOSITE///
    private Integer ccIcalcoliId;

    @Column(name = "FK_CCIC_ID")
    @SuppressWarnings("unused")
    private Integer getCcIcalcoliId() {

	if (null != this.getCcIcalcoli()) {
	    if (null != this.getCcIcalcoli().getId()) {
		this.ccIcalcoliId = getCcIcalcoli().getId().getCodice();
		return this.ccIcalcoliId;
	    }
	}
	return null;
    }

    @SuppressWarnings("unused")
    private void setCcIcalcoliId(Integer ccIcalcoliId) {

	if (null != this.getCcIcalcoli()) {
	    if (null != this.getCcIcalcoli().getId()) {
		this.ccIcalcoliId = getCcIcalcoli().getId().getCodice();
	    }
	}
    }

    //END FIX/////////////////////////////////////////////////////
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumns({ @JoinColumn(name = "IDCOMUNE", referencedColumnName = "IDCOMUNE", nullable = false, insertable = false, updatable = false),
	    @JoinColumn(name = "CODICEISTANZA", referencedColumnName = "CODICEISTANZA", nullable = false, insertable = false, updatable = false) })
    public Istanze getIstanze() {

	return this.istanze;
    }

    public void setIstanze(Istanze istanze) {

	this.istanze = istanze;
    }

    //FIXME WORKAROUND PER AGGIORNAMENTO CHIAVI ESTERNE COMPOSITE///
    private Integer istanzeId;

    @Column(name = "CODICEISTANZA")
    @SuppressWarnings("unused")
    private Integer getIstanzeId() {

	if (null != this.getIstanze()) {
	    if (null != this.getIstanze().getId()) {
		this.istanzeId = getIstanze().getId().getCodice();
		return this.istanzeId;
	    }
	}
	return null;
    }

    @SuppressWarnings("unused")
    private void setIstanzeId(Integer istanzeId) {

	if (null != this.getIstanze()) {
	    if (null != this.getIstanze().getId()) {
		this.istanzeId = getIstanze().getId().getCodice();
	    }
	}
    }

    //END FIX/////////////////////////////////////////////////////
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumns({ @JoinColumn(name = "IDCOMUNE", referencedColumnName = "IDCOMUNE", nullable = false, insertable = false, updatable = false),
	    @JoinColumn(name = "FK_CCCS_ID", referencedColumnName = "ID", nullable = false, insertable = false, updatable = false) })
    public CcClassisuperfici getCcClassisuperfici() {

	return this.ccClassisuperfici;
    }

    public void setCcClassisuperfici(CcClassisuperfici ccClassisuperfici) {

	this.ccClassisuperfici = ccClassisuperfici;
    }

    //FIXME WORKAROUND PER AGGIORNAMENTO CHIAVI ESTERNE COMPOSITE///
    private Integer ccClassisuperficiId;

    @Column(name = "FK_CCCS_ID")
    @SuppressWarnings("unused")
    private Integer getCcClassisuperficiId() {

	if (null != this.getCcClassisuperfici()) {
	    if (null != this.getCcClassisuperfici().getId()) {
		this.ccClassisuperficiId = getCcClassisuperfici().getId().getCodice();
		return this.ccClassisuperficiId;
	    }
	}
	return null;
    }

    @SuppressWarnings("unused")
    private void setCcClassisuperficiId(Integer ccClassisuperficiId) {

	if (null != this.getCcClassisuperfici()) {
	    if (null != this.getCcClassisuperfici().getId()) {
		this.ccClassisuperficiId = getCcClassisuperfici().getId().getCodice();
	    }
	}
    }

    //END FIX/////////////////////////////////////////////////////
    @Column(name = "ALLOGGI", precision = 3, scale = 0)
    public Short getAlloggi() {

	return this.alloggi;
    }

    public void setAlloggi(Short alloggi) {

	this.alloggi = alloggi;
    }

    @Column(name = "SU", precision = 11)
    public BigDecimal getSu() {

	return this.su;
    }

    public void setSu(BigDecimal su) {

	this.su = su;
    }

    @Column(name = "RAPPORTO_SU", precision = 12, scale = 3)
    public BigDecimal getRapportoSu() {

	return this.rapportoSu;
    }

    public void setRapportoSu(BigDecimal rapportoSu) {

	this.rapportoSu = rapportoSu;
    }

    @Column(name = "INCREMENTO", precision = 5)
    public BigDecimal getIncremento() {

	return this.incremento;
    }

    public void setIncremento(BigDecimal incremento) {

	this.incremento = incremento;
    }

    @Column(name = "INCREMENTOXCLASSI", precision = 6, scale = 3)
    public BigDecimal getIncrementoxclassi() {

	return this.incrementoxclassi;
    }

    public void setIncrementoxclassi(BigDecimal incrementoxclassi) {

	this.incrementoxclassi = incrementoxclassi;
    }
}
