package it.gruppoinit.pal.gp.core.domain;

import it.gruppoinit.pal.gp.core.dao.helper.ORMHelper;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EmailanagrId generated by hbm2java
 */
@Embeddable
public class EmailanagrId implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -6695346515155655206L;
    private String idcomune;
    private Integer codiceemail;
    private Integer codiceanagrafica;

    public EmailanagrId() {

	this.idcomune = ORMHelper.getIdcomune();
    }

    @Column(name = "IDCOMUNE", nullable = false, length = 6)
    public String getIdcomune() {

	return this.idcomune;
    }

    public void setIdcomune(String idcomune) {

	this.idcomune = idcomune;
    }

    @Column(name = "CODICEEMAIL", nullable = false, precision = 6, scale = 0)
    public Integer getCodiceemail() {

	return this.codiceemail;
    }

    public void setCodiceemail(Integer codiceemail) {

	this.codiceemail = codiceemail;
    }

    @Column(name = "CODICEANAGRAFICA", nullable = false, precision = 4, scale = 0)
    public Integer getCodiceanagrafica() {

	return this.codiceanagrafica;
    }

    public void setCodiceanagrafica(Integer codiceanagrafica) {

	this.codiceanagrafica = codiceanagrafica;
    }

    public boolean equals(Object other) {

	if ((this == other))
	    return true;
	if ((other == null))
	    return false;
	if (!(other instanceof EmailanagrId))
	    return false;
	EmailanagrId castOther = (EmailanagrId) other;
	return ((this.getIdcomune() == castOther.getIdcomune()) || (this.getIdcomune() != null && castOther.getIdcomune() != null && this
		.getIdcomune().equals(castOther.getIdcomune())))
		&& ((this.getCodiceemail() == castOther.getCodiceemail()) || (this.getCodiceemail() != null && castOther.getCodiceemail() != null && this
			.getCodiceemail().equals(castOther.getCodiceemail())))
		&& ((this.getCodiceanagrafica() == castOther.getCodiceanagrafica()) || (this.getCodiceanagrafica() != null
			&& castOther.getCodiceanagrafica() != null && this.getCodiceanagrafica().equals(castOther.getCodiceanagrafica())));
    }

    public int hashCode() {

	int result = 17;
	result = 37 * result + (getIdcomune() == null ? 0 : this.getIdcomune().hashCode());
	result = 37 * result + (getCodiceemail() == null ? 0 : this.getCodiceemail().hashCode());
	result = 37 * result + (getCodiceanagrafica() == null ? 0 : this.getCodiceanagrafica().hashCode());
	return result;
    }
}
