package it.gruppoinit.pal.gp.core.domain;

// Generated 27-nov-2008 9.36.35 by Hibernate Tools 3.2.2.GA
import it.gruppoinit.pal.gp.core.dao.helper.ORMHelper;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/*
 * HelpbaseId generated by hbm2java
 */
@Embeddable
public class HelpbaseId implements java.io.Serializable {

    private static final long serialVersionUID = 2509484414450892309L;
    private String contenttype;
    private String software;
    private Integer tab;

    public HelpbaseId() {

	this.software = ORMHelper.getSoftware();
    }

    public HelpbaseId(String contenttype, Integer tab) {

	this.contenttype = contenttype;
	this.software = ORMHelper.getSoftware();
	this.tab = tab;
    }

    public HelpbaseId(String contenttype, Integer tab, String software) {

	this.contenttype = contenttype;
	this.software = software;
	this.tab = tab;
    }

    @Column(name = "CONTENTTYPE", nullable = false, length = 150)
    public String getContenttype() {

	return this.contenttype;
    }

    public void setContenttype(String contenttype) {

	this.contenttype = contenttype;
    }

    @Column(name = "SOFTWARE", nullable = false, length = 2)
    public String getSoftware() {

	return this.software;
    }

    public void setSoftware(String software) {

	this.software = software;
    }

    @Column(name = "TAB", nullable = false, precision = 1, scale = 0)
    public Integer getTab() {

	return this.tab;
    }

    public void setTab(Integer tab) {

	this.tab = tab;
    }

    public boolean equals(Object other) {

	if ((this == other))
	    return true;
	if ((other == null))
	    return false;
	if (!(other instanceof HelpbaseId))
	    return false;
	HelpbaseId castOther = (HelpbaseId) other;
	return ((this.getContenttype() == castOther.getContenttype()) || (this.getContenttype() != null && castOther.getContenttype() != null && this
		.getContenttype().equals(castOther.getContenttype())))
		&& ((this.getSoftware() == castOther.getSoftware()) || (this.getSoftware() != null && castOther.getSoftware() != null && this
			.getSoftware().equals(castOther.getSoftware())))
		&& ((this.getTab() == castOther.getTab()) || (this.getTab() != null && castOther.getTab() != null && this.getTab().equals(
			castOther.getTab())));
    }

    public int hashCode() {

	int result = 17;
	result = 37 * result + (getContenttype() == null ? 0 : this.getContenttype().hashCode());
	result = 37 * result + (getSoftware() == null ? 0 : this.getSoftware().hashCode());
	result = 37 * result + (getTab() == null ? 0 : this.getTab().hashCode());
	return result;
    }
}
