package it.gruppoinit.pal.gp.core.domain;

import it.gruppoinit.pal.gp.core.dao.helper.PkIdGenerator;

import java.math.BigDecimal;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * OTabellad generated by hbm2java
 */
@Entity
@Table(name = "O_TABELLAD")
public class OTabellad implements java.io.Serializable {

    private static final long serialVersionUID = 8076067869014139012L;
    private PkId id;
    private ODestinazioni destinazioni;
    private OTipioneri tipioneri;
    private OInterventi interventi;
    private OClassiaddetti classiaddetti;
    private Software software;
    private OValiditacoefficienti validitacoefficienti;
    private BigDecimal costo;

    public OTabellad() {

	this.id = new PkId();
    }

    @EmbeddedId
    @GenericGenerator(name = "pkGenerator", strategy = "it.gruppoinit.pal.gp.core.dao.helper.PkIdGenerator", parameters = {
	    @Parameter(name = PkIdGenerator.CONFIG_PREFER_SEGMENT_PER_ENTITY, value = "true"),
	    @Parameter(name = PkIdGenerator.TABLE_PARAM, value = "SEQUENCETABLE"),
	    @Parameter(name = PkIdGenerator.VALUE_COLUMN_PARAM, value = "CURRVAL"),
	    @Parameter(name = PkIdGenerator.SEGMENT_COLUMN_PARAM, value = "SEQUENCENAME"),
	    @Parameter(name = PkIdGenerator.SEGMENT_VALUE_PARAM, value = "O_TABELLAD.ID") })
    @GeneratedValue(generator = "pkGenerator")
    @AttributeOverrides({ @AttributeOverride(name = "idcomune", column = @Column(name = "IDCOMUNE", nullable = false, length = 6)),
	    @AttributeOverride(name = "codice", column = @Column(name = "ID", nullable = false, precision = 6, scale = 0)) })
    public PkId getId() {

	return this.id;
    }

    public void setId(PkId id) {

	this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumns({ @JoinColumn(name = "IDCOMUNE", referencedColumnName = "IDCOMUNE", nullable = false, insertable = false, updatable = false),
	    @JoinColumn(name = "FK_ODE_ID", referencedColumnName = "ID", nullable = false, insertable = false, updatable = false) })
    public ODestinazioni getDestinazioni() {

	return destinazioni;
    }

    public void setDestinazioni(ODestinazioni destinazioni) {

	this.destinazioni = destinazioni;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumns({ @JoinColumn(name = "IDCOMUNE", referencedColumnName = "IDCOMUNE", nullable = false, insertable = false, updatable = false),
	    @JoinColumn(name = "FK_OTO_ID", referencedColumnName = "ID", nullable = false, insertable = false, updatable = false) })
    public OTipioneri getTipioneri() {

	return tipioneri;
    }

    public void setTipioneri(OTipioneri tipioneri) {

	this.tipioneri = tipioneri;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumns({ @JoinColumn(name = "IDCOMUNE", referencedColumnName = "IDCOMUNE", nullable = false, insertable = false, updatable = false),
	    @JoinColumn(name = "FK_OIN_ID", referencedColumnName = "ID", nullable = false, insertable = false, updatable = false) })
    public OInterventi getInterventi() {

	return interventi;
    }

    public void setInterventi(OInterventi interventi) {

	this.interventi = interventi;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumns({ @JoinColumn(name = "IDCOMUNE", referencedColumnName = "IDCOMUNE", nullable = false, insertable = false, updatable = false),
	    @JoinColumn(name = "FK_OCA_ID", referencedColumnName = "ID", nullable = false, insertable = false, updatable = false) })
    public OClassiaddetti getClassiaddetti() {

	return classiaddetti;
    }

    public void setClassiaddetti(OClassiaddetti classiaddetti) {

	this.classiaddetti = classiaddetti;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SOFTWARE", nullable = false)
    public Software getSoftware() {

	return this.software;
    }

    public void setSoftware(Software software) {

	this.software = software;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumns({ @JoinColumn(name = "IDCOMUNE", referencedColumnName = "IDCOMUNE", nullable = false, insertable = false, updatable = false),
	    @JoinColumn(name = "FK_OVC_ID", referencedColumnName = "ID", nullable = false, insertable = false, updatable = false) })
    public OValiditacoefficienti getValiditacoefficienti() {

	return validitacoefficienti;
    }

    public void setValiditacoefficienti(OValiditacoefficienti validitacoefficienti) {

	this.validitacoefficienti = validitacoefficienti;
    }

    @Column(name = "COSTO", nullable = false, precision = 11)
    public BigDecimal getCosto() {

	return this.costo;
    }

    public void setCosto(BigDecimal costo) {

	this.costo = costo;
    }
}
