package it.gruppoinit.pal.gp.core.domain;

// Generated 23-ott-2013 14.41.14 by Hibernate Tools 3.4.0.CR1
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * PecInbox generated by hbm2java
 */
@Entity
@Table(name = "PEC_INBOX")
public class PecInbox implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1802492855983950390L;
    private PecInboxId id;
    private Responsabili responsabili;
    private Movimenti movimenti;
    private Istanze istanze;
    private Oggetti oggettoProtocollo;
    private Software software;
    private String pecSubject;
    private String pecFrom;
    private String pecTo;
    private String pecToCC;
    private Date pecDate;
    private Boolean flagProcessata;
    private String idprotocollo;
    private String numeroprotocollo;
    private Date dataprotocollo;
    private Set<PecInboxAllegati> allegatiPec = new HashSet<PecInboxAllegati>();
    private Boolean flagCancellata;
    private Boolean flagLetta;
    private String inLoginname;
    private Responsabili responsabileEvidenza;
    private Software softwareProt;
    private Comuni comuniProt;
    private MailConfig mailConfig;

    public PecInbox() {

	this.id = new PecInboxId();
	this.responsabili = new Responsabili();
	this.movimenti = new Movimenti();
	this.istanze = new Istanze();
	this.oggettoProtocollo = new Oggetti();
	this.software = new Software();
	this.responsabileEvidenza = new Responsabili();
	this.mailConfig = new MailConfig();
    }

    public PecInbox(PecInboxId id) {

	this.id = id;
	this.responsabili = new Responsabili();
	this.movimenti = new Movimenti();
	this.istanze = new Istanze();
	this.oggettoProtocollo = new Oggetti();
	this.software = new Software();
	this.responsabileEvidenza = new Responsabili();
    }

    @EmbeddedId
    @AttributeOverrides({ @AttributeOverride(name = "idcomune", column = @Column(name = "IDCOMUNE", nullable = false, length = 6)),
	    @AttributeOverride(name = "id", column = @Column(name = "ID", nullable = false, length = 200)) })
    public PecInboxId getId() {

	return this.id;
    }

    public void setId(PecInboxId id) {

	this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY, optional = true)
    @JoinColumns({ @JoinColumn(name = "CODICEOPERATORE", referencedColumnName = "CODICERESPONSABILE", insertable = false, updatable = false),
	    @JoinColumn(name = "IDCOMUNE", referencedColumnName = "IDCOMUNE", insertable = false, updatable = false) })
    public Responsabili getResponsabili() {

	return this.responsabili;
    }

    public void setResponsabili(Responsabili responsabili) {

	this.responsabili = responsabili;
    }

    // FIXWORKAROUND PER AGGIORNAMENTO CHIAVI ESTERNE COMPOSITE///
    private Integer responsabiliId;

    @Column(name = "CODICEOPERATORE")
    private Integer getResponsabiliId() {

	if (null != this.getResponsabili()) {
	    if (null != this.getResponsabili().getId()) {
		this.responsabiliId = getResponsabili().getId().getCodice();
		return this.responsabiliId;
	    }
	}
	return null;
    }

    @SuppressWarnings("unused")
    private void setResponsabiliId(Integer responsabiliId) {

	if (null != this.getResponsabili()) {
	    if (null != this.getResponsabili().getId()) {
		this.responsabiliId = getResponsabili().getId().getCodice();
	    }
	}
    }

    @ManyToOne(fetch = FetchType.LAZY, optional = true)
    @JoinColumns({ @JoinColumn(name = "CODICEMOVIMENTO", referencedColumnName = "CODICEMOVIMENTO", insertable = false, updatable = false),
	    @JoinColumn(name = "IDCOMUNE", referencedColumnName = "IDCOMUNE", insertable = false, updatable = false) })
    public Movimenti getMovimenti() {

	return this.movimenti;
    }

    public void setMovimenti(Movimenti movimenti) {

	this.movimenti = movimenti;
    }

    // FIXWORKAROUND PER AGGIORNAMENTO CHIAVI ESTERNE COMPOSITE///
    private Integer movimentiId;

    @Column(name = "CODICEMOVIMENTO")
    private Integer getMovimentiId() {

	if (null != this.getMovimenti()) {
	    if (null != this.getMovimenti().getId()) {
		this.movimentiId = getMovimenti().getId().getCodice();
		return this.movimentiId;
	    }
	}
	return null;
    }

    @SuppressWarnings("unused")
    private void setMovimentiId(Integer movimentiId) {

	if (null != this.getMovimenti()) {
	    if (null != this.getMovimenti().getId()) {
		this.movimentiId = getMovimenti().getId().getCodice();
	    }
	}
    }

    @ManyToOne(fetch = FetchType.LAZY, optional = true)
    @JoinColumns({ @JoinColumn(name = "CODICEISTANZA", referencedColumnName = "CODICEISTANZA", insertable = false, updatable = false),
	    @JoinColumn(name = "IDCOMUNE", referencedColumnName = "IDCOMUNE", insertable = false, updatable = false) })
    public Istanze getIstanze() {

	return this.istanze;
    }

    public void setIstanze(Istanze istanze) {

	this.istanze = istanze;
    }

    // FIXWORKAROUND PER AGGIORNAMENTO CHIAVI ESTERNE COMPOSITE///
    private Integer istanzeId;

    @Column(name = "CODICEISTANZA")
    private Integer getIstanzeId() {

	if (null != this.getIstanze()) {
	    if (null != this.getIstanze().getId()) {
		this.istanzeId = getIstanze().getId().getCodice();
		return this.istanzeId;
	    }
	}
	return null;
    }

    @SuppressWarnings("unused")
    private void setIstanzeId(Integer istanzeId) {

	if (null != this.getIstanze()) {
	    if (null != this.getIstanze().getId()) {
		this.istanzeId = getIstanze().getId().getCodice();
	    }
	}
    }

    @ManyToOne(fetch = FetchType.LAZY, optional = true)
    @JoinColumns({ @JoinColumn(name = "CODICEOGGETTOPROTOCOLLO", referencedColumnName = "CODICEOGGETTO", insertable = false, updatable = false),
	    @JoinColumn(name = "IDCOMUNE", referencedColumnName = "IDCOMUNE", insertable = false, updatable = false) })
    public Oggetti getOggettoProtocollo() {

	return this.oggettoProtocollo;
    }

    public void setOggettoProtocollo(Oggetti oggetti) {

	this.oggettoProtocollo = oggetti;
    }

    // FIXWORKAROUND PER AGGIORNAMENTO CHIAVI ESTERNE COMPOSITE///
    private Integer oggettoProtocolloId;

    @Column(name = "CODICEOGGETTOPROTOCOLLO")
    private Integer getOggettoProtocolloId() {

	if (null != this.getOggettoProtocollo()) {
	    if (null != this.getOggettoProtocollo().getId()) {
		this.oggettoProtocolloId = getOggettoProtocollo().getId().getCodice();
		return this.oggettoProtocolloId;
	    }
	}
	return null;
    }

    @SuppressWarnings("unused")
    private void setOggettoProtocolloId(Integer oggettoProtocolloId) {

	if (null != this.getOggettoProtocollo()) {
	    if (null != this.getOggettoProtocollo().getId()) {
		this.oggettoProtocolloId = getOggettoProtocollo().getId().getCodice();
	    }
	}
    }

    @Length(max = 4000)
    @Column(name = "PEC_SUBJECT", length = 4000)
    public String getPecSubject() {

	return this.pecSubject;
    }

    public void setPecSubject(String pecSubject) {

	this.pecSubject = pecSubject;
    }

    @Length(max = 4000)
    @Column(name = "PEC_FROM", length = 4000)
    public String getPecFrom() {

	return this.pecFrom;
    }

    public void setPecFrom(String pecFrom) {

	this.pecFrom = pecFrom;
    }

    @Length(max = 4000)
    @Column(name = "PEC_TO", length = 4000)
    public String getPecTo() {

	return this.pecTo;
    }

    public void setPecTo(String pecTo) {

	this.pecTo = pecTo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "PEC_DATE", length = 7)
    public Date getPecDate() {

	return this.pecDate;
    }

    public void setPecDate(Date pecDate) {

	this.pecDate = pecDate;
    }

    @NotNull
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SOFTWARE", nullable = false)
    public Software getSoftware() {

	return this.software;
    }

    public void setSoftware(Software software) {

	this.software = software;
    }

    @Column(name = "FLAG_PROCESSATA", precision = 1, scale = 0)
    public Boolean getFlagProcessata() {

	return this.flagProcessata;
    }

    public void setFlagProcessata(Boolean flagProcessata) {

	this.flagProcessata = flagProcessata;
    }

    @Length(max = 30)
    @Column(name = "IDPROTOCOLLO", length = 30)
    public String getIdprotocollo() {

	return this.idprotocollo;
    }

    public void setIdprotocollo(String idprotocollo) {

	this.idprotocollo = idprotocollo;
    }

    @Length(max = 30)
    @Column(name = "NUMEROPROTOCOLLO", length = 30)
    public String getNumeroprotocollo() {

	return this.numeroprotocollo;
    }

    public void setNumeroprotocollo(String numeroprotocollo) {

	this.numeroprotocollo = numeroprotocollo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "DATAPROTOCOLLO")
    public Date getDataprotocollo() {

	return this.dataprotocollo;
    }

    public void setDataprotocollo(Date dataprotocollo) {

	this.dataprotocollo = dataprotocollo;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pec")
    public Set<PecInboxAllegati> getAllegatiPec() {

	return allegatiPec;
    }

    public void setAllegatiPec(Set<PecInboxAllegati> allegatiPec) {

	this.allegatiPec = allegatiPec;
    }

    @Column(name = "FLAG_CANCELLATA", precision = 1, scale = 0)
    public Boolean getFlagCancellata() {

	return this.flagCancellata;
    }

    public void setFlagCancellata(Boolean flagCancellata) {

	this.flagCancellata = flagCancellata;
    }

    @Column(name = "FLAG_LETTA", precision = 1, scale = 0)
    public Boolean getFlagLetta() {

	return flagLetta;
    }

    public void setFlagLetta(Boolean flagLetta) {

	this.flagLetta = flagLetta;
    }

    @Length(max = 320)
    @Column(name = "IN_LOGINNAME", length = 320)
    public String getInLoginname() {

	return inLoginname;
    }

    public void setInLoginname(String inLoginname) {

	this.inLoginname = inLoginname;
    }

    @ManyToOne(fetch = FetchType.LAZY, optional = true)
    @JoinColumns({ @JoinColumn(name = "FK_RESP_EVIDENZA", referencedColumnName = "CODICERESPONSABILE", insertable = false, updatable = false),
	    @JoinColumn(name = "IDCOMUNE", referencedColumnName = "IDCOMUNE", insertable = false, updatable = false) })
    public Responsabili getResponsabileEvidenza() {

	return this.responsabileEvidenza;
    }

    public void setResponsabileEvidenza(Responsabili responsabileEvidenza) {

	this.responsabileEvidenza = responsabileEvidenza;
    }

    // FIXWORKAROUND PER AGGIORNAMENTO CHIAVI ESTERNE COMPOSITE///
    private Integer responsabileEvidenzaId;

    @Column(name = "FK_RESP_EVIDENZA")
    private Integer getResponsabileEvidenzaId() {

	if (null != this.getResponsabileEvidenza()) {
	    if (null != this.getResponsabileEvidenza().getId()) {
		this.responsabileEvidenzaId = getResponsabileEvidenza().getId().getCodice();
		return this.responsabileEvidenzaId;
	    }
	}
	return null;
    }

    @SuppressWarnings("unused")
    private void setResponsabileEvidenzaId(Integer responsabileEvidenzaId) {

	if (null != this.getResponsabileEvidenza()) {
	    if (null != this.getResponsabileEvidenza().getId()) {
		this.responsabileEvidenzaId = getResponsabileEvidenza().getId().getCodice();
	    }
	}
    }

    @Length(max = 4000)
    @Column(name = "PEC_TOCC", length = 4000, nullable = true)
    public String getPecToCC() {

	return pecToCC;
    }

    public void setPecToCC(String pecToCC) {

	this.pecToCC = pecToCC;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SOFTWARE_PROT")
    public Software getSoftwareProt() {

	return softwareProt;
    }

    public void setSoftwareProt(Software softwareProt) {

	this.softwareProt = softwareProt;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CODICECOMUNE_PROT")
    public Comuni getComuniProt() {

	return comuniProt;
    }

    public void setComuniProt(Comuni comuniProt) {

	this.comuniProt = comuniProt;
    }

    @NotNull
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumns({ @JoinColumn(name = "ACCOUNT_ID", referencedColumnName = "ID", insertable = false, updatable = false),
	    @JoinColumn(name = "IDCOMUNE", referencedColumnName = "IDCOMUNE", insertable = false, updatable = false) })
    public MailConfig getMailConfig() {

	return mailConfig;
    }

    public void setMailConfig(MailConfig mailConfig) {

	this.mailConfig = mailConfig;
    }

    private Integer mailConfigId;

    @Column(name = "ACCOUNT_ID")
    public Integer getMailConfigId() {

	if (null != this.getMailConfig()) {
	    if (null != this.getMailConfig().getId()) {
		this.mailConfigId = getMailConfig().getId().getCodice();
		return this.mailConfigId;
	    }
	}
	return null;
    }

    public void setMailConfigId(Integer mailConfigId) {

	if (null != this.getMailConfig()) {
	    if (null != this.getMailConfig().getId()) {
		this.mailConfigId = getMailConfig().getId().getCodice();
	    }
	}
    }
}
