package it.gruppoinit.pal.gp.core.domain;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Sorteggidettagliomovimenti generated by hbm2java
 */
@Entity
@Table(name = "SORTEGGIDETTAGLIOMOVIMENTI")
public class Sorteggidettagliomovimenti implements java.io.Serializable {

    private static final long serialVersionUID = 8752548823224423881L;
    private SorteggidettagliomovimentiId id;
    private Movimenti movimenti;
    private Sorteggidettaglio sorteggidettaglio;

    public Sorteggidettagliomovimenti() {

	this.id = new SorteggidettagliomovimentiId();
    }

    @EmbeddedId
    @AttributeOverrides({ @AttributeOverride(name = "idcomune", column = @Column(name = "IDCOMUNE", nullable = false, length = 6)),
	    @AttributeOverride(name = "sdmFkSdid", column = @Column(name = "SDM_FK_SDID", nullable = false, precision = 9, scale = 0)),
	    @AttributeOverride(name = "codicemovimento", column = @Column(name = "CODICEMOVIMENTO", nullable = false, precision = 6, scale = 0)) })
    public SorteggidettagliomovimentiId getId() {

	return this.id;
    }

    public void setId(SorteggidettagliomovimentiId id) {

	this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumns({ @JoinColumn(name = "IDCOMUNE", referencedColumnName = "IDCOMUNE", nullable = false, insertable = false, updatable = false),
	    @JoinColumn(name = "CODICEMOVIMENTO", referencedColumnName = "CODICEMOVIMENTO", nullable = false, insertable = false, updatable = false) })
    public Movimenti getMovimenti() {

	return this.movimenti;
    }

    public void setMovimenti(Movimenti movimenti) {

	this.movimenti = movimenti;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumns({ @JoinColumn(name = "IDCOMUNE", referencedColumnName = "IDCOMUNE", nullable = false, insertable = false, updatable = false),
	    @JoinColumn(name = "SDM_FK_SDID", referencedColumnName = "SD_ID", nullable = false, insertable = false, updatable = false) })
    public Sorteggidettaglio getSorteggidettaglio() {

	return this.sorteggidettaglio;
    }

    public void setSorteggidettaglio(Sorteggidettaglio sorteggidettaglio) {

	this.sorteggidettaglio = sorteggidettaglio;
    }
}
