package it.gruppoinit.pal.gp.core.domain;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * StpModalitaApertura generated by hbm2java
 */
@Entity
@Table(name = "STP_MODALITA_APERTURA")
public class StpModalitaApertura implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 3258658958675497308L;
    private String id;
    private String descrizione;
    private String tipoScheda;
    private Set<Naturaendo> schedaEndo1naturaendos = new HashSet<Naturaendo>(0);
    private Set<Naturaendo> schedaEndo2naturaendos = new HashSet<Naturaendo>(0);

    public StpModalitaApertura() {

    }

    @Id
    @Column(name = "ID", unique = true, nullable = false, length = 100)
    public String getId() {

	return this.id;
    }

    public void setId(String id) {

	this.id = id;
    }

    @Column(name = "DESCRIZIONE", nullable = false, length = 200)
    public String getDescrizione() {

	return this.descrizione;
    }

    public void setDescrizione(String descrizione) {

	this.descrizione = descrizione;
    }

    @Column(name = "TIPO_SCHEDA", length = 4)
    public String getTipoScheda() {

	return this.tipoScheda;
    }

    public void setTipoScheda(String tipoScheda) {

	this.tipoScheda = tipoScheda;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "stpModalitaAperturaSchedaEndo1")
    public Set<Naturaendo> getSchedaEndo1naturaendos() {

	return schedaEndo1naturaendos;
    }

    public void setSchedaEndo1naturaendos(Set<Naturaendo> schedaEndo1naturaendos) {

	this.schedaEndo1naturaendos = schedaEndo1naturaendos;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "stpModalitaAperturaSchedaEndo2")
    public Set<Naturaendo> getSchedaEndo2naturaendos() {

	return schedaEndo2naturaendos;
    }

    public void setSchedaEndo2naturaendos(Set<Naturaendo> schedaEndo2naturaendos) {

	this.schedaEndo2naturaendos = schedaEndo2naturaendos;
    }
}
