package it.gruppoinit.pal.gp.core.domain;

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VwIAttivitaautorizzazioni generated by hbm2java
 */
@Entity
@Table(name = "VW_I_ATTIVITAAUTORIZZAZIONI")
public class VwIAttivitaautorizzazioni implements java.io.Serializable {

    private static final long serialVersionUID = 6027145724171913304L;
    private VwIAttivitaautorizzazioniId id;
    private Integer iidattivita;
    private String autoriznumero;
    private Date autorizdata;
    private String autorizdataregistr;
    private String autorizresponsabile;
    private Integer fkidregistro;
    private Integer fkidistanza;
    private Integer codicemovimento;

    public VwIAttivitaautorizzazioni() {

    }

    @EmbeddedId
    @AttributeOverrides({ @AttributeOverride(name = "idcomune", column = @Column(name = "IDCOMUNE", nullable = false, length = 6)),
	    @AttributeOverride(name = "id", column = @Column(name = "ID", nullable = false, precision = 6, scale = 0)) })
    public VwIAttivitaautorizzazioniId getId() {

	return this.id;
    }

    public void setId(VwIAttivitaautorizzazioniId id) {

	this.id = id;
    }

    @Column(name = "I_IDATTIVITA", nullable = false, precision = 6, scale = 0)
    public Integer getIidattivita() {

	return iidattivita;
    }

    public void setIidattivita(Integer iidattivita) {

	this.iidattivita = iidattivita;
    }

    @Column(name = "AUTORIZNUMERO", length = 50)
    public String getAutoriznumero() {

	return autoriznumero;
    }

    public void setAutoriznumero(String autoriznumero) {

	this.autoriznumero = autoriznumero;
    }

    @Column(name = "AUTORIZDATA", length = 7)
    public Date getAutorizdata() {

	return autorizdata;
    }

    public void setAutorizdata(Date autorizdata) {

	this.autorizdata = autorizdata;
    }

    @Column(name = "AUTORIZDATAREGISTR", length = 7)
    public String getAutorizdataregistr() {

	return autorizdataregistr;
    }

    public void setAutorizdataregistr(String autorizdataregistr) {

	this.autorizdataregistr = autorizdataregistr;
    }

    @Column(name = "AUTORIZRESPONSABILE", length = 80)
    public String getAutorizresponsabile() {

	return autorizresponsabile;
    }

    public void setAutorizresponsabile(String autorizresponsabile) {

	this.autorizresponsabile = autorizresponsabile;
    }

    @Column(name = "FKIDREGISTRO", precision = 4, scale = 0)
    public Integer getFkidregistro() {

	return fkidregistro;
    }

    public void setFkidregistro(Integer fkidregistro) {

	this.fkidregistro = fkidregistro;
    }

    @Column(name = "FKIDISTANZA", precision = 6, scale = 0)
    public Integer getFkidistanza() {

	return fkidistanza;
    }

    public void setFkidistanza(Integer fkidistanza) {

	this.fkidistanza = fkidistanza;
    }

    @Column(name = "CODICEMOVIMENTO", precision = 6, scale = 0)
    public Integer getCodicemovimento() {

	return codicemovimento;
    }

    public void setCodicemovimento(Integer codicemovimento) {

	this.codicemovimento = codicemovimento;
    }
}
