SET IMPLICIT_TRANSACTIONS ON
GO
ALTER TABLE I_ATTIVITADYN2MODELLIT ADD CONSTRAINT FK_IATTIVD2MT_002 FOREIGN KEY ( IDCOMUNE, FK_IA_ID ) REFERENCES I_ATTIVITA ( IDCOMUNE, ID )
GO
COMMIT
GO
ALTER TABLE I_ATTIVITADYN2DATI ADD CONSTRAINT FK_IATTIVD2D_001 FOREIGN KEY ( IDCOMUNE, FK_IA_ID ) REFERENCES I_ATTIVITA ( IDCOMUNE, ID )
GO
COMMIT
GO
ALTER TABLE I_ATTIVITADYN2DATI_STORICO ADD CONSTRAINT FK_IATTIVD2DSTORICO_002 FOREIGN KEY ( IDCOMUNE, FK_IA_ID ) REFERENCES I_ATTIVITA ( IDCOMUNE, ID )
GO
COMMIT
GO
ALTER TABLE I_ATTIVITADYN2MODELLIT_STORICO ADD CONSTRAINT FK_IATTIVD2MTSTORICO_001 FOREIGN KEY ( IDCOMUNE, FK_IA_ID ) REFERENCES I_ATTIVITA ( IDCOMUNE, ID )
GO
COMMIT
GO
ALTER TABLE AUTORIZZAZIONI ALTER COLUMN AUTORIZNUMERO VARCHAR(50) NOT NULL
GO
COMMIT
GO
ALTER TABLE AUTORIZZAZIONI ALTER COLUMN AUTORIZDATA DATETIME NOT NULL
GO
COMMIT
GO
ALTER TABLE AUTORIZZAZIONI ALTER COLUMN FKIDREGISTRO NUMERIC(4,0) NOT NULL
GO
COMMIT
GO
ALTER TABLE AUTORIZZAZIONI ALTER COLUMN AUTORIZCOMUNE VARCHAR(5) NOT NULL
GO
COMMIT
GO
ALTER TABLE ISTANZE DROP CONSTRAINT FK_ISTANZE_ISTCOLLEGATA
GO
COMMIT
GO
ALTER TABLE TMP_CONTROMOVEFF ALTER COLUMN CODAMMRICHIEDENTERX NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE TMP_CONTROMOVEFF ALTER COLUMN CODAMMRICHIEDENTETX NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE TMP_CONTROMOVEFF ALTER COLUMN CODICEAMMINISTRAZIONERX NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE TMP_CONTROMOVEFF ALTER COLUMN CODICEAMMINISTRAZIONETX NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE TIPICAUSALIONERI DROP CONSTRAINT FK_TIPICAUSON_INTERESSI
GO
COMMIT
GO
ALTER TABLE TIPICAUSALIONERI ALTER COLUMN FK_TIPICAUSALIINTERESSI NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE TIPICAUSALIONERI ADD CONSTRAINT FK_TIPICAUSON_INTERESSI FOREIGN KEY(IDCOMUNE, FK_TIPICAUSALIINTERESSI) REFERENCES TIPICAUSALIONERI(IDCOMUNE, CO_ID)
GO
COMMIT
GO
CREATE TABLE DOMANDESTC_ALLEGATI(IDCOMUNE VARCHAR(6) NOT NULL,ID NUMERIC(6,0) NOT NULL,FK_DOMANDASTC_ID NUMERIC(6,0),CODICEOGGETTO NUMERIC(10,0))
GO
COMMIT
GO
ALTER TABLE DOMANDESTC_ALLEGATI ADD CONSTRAINT PK_DOMANDESTCALLEGATI PRIMARY KEY (IDCOMUNE, ID)
GO
COMMIT
GO
ALTER TABLE DOMANDESTC_ALLEGATI ADD CONSTRAINT FK_DOMSTCALL_DOMSTC FOREIGN KEY (IDCOMUNE, FK_DOMANDASTC_ID) REFERENCES DOMANDESTC(IDCOMUNE, ID)
GO
COMMIT
GO
ALTER TABLE DOMANDESTC_ALLEGATI ADD CONSTRAINT FK_DOMSTCALL_OGGETTI FOREIGN KEY (IDCOMUNE, CODICEOGGETTO) REFERENCES OGGETTI(IDCOMUNE, CODICEOGGETTO)
GO
COMMIT
GO
DROP VIEW VW_LISTAPRATICHE
GO
COMMIT
GO
CREATE VIEW VW_LISTAPRATICHE AS  
SELECT 
  ISTANZE.CODICECOMUNE          AS CODICECOMUNE, 
  ISTANZE.IDCOMUNE              AS IDCOMUNE, 
  ISTANZE.SOFTWARE              AS SOFTWARE, 
  SOFTWARE.DESCRIZIONELUNGA     AS DESCSOFTWARE, 
  ISTANZE.CODICEISTANZA         AS IDPRATICA, 
  ISTANZE.NUMEROISTANZA         AS NUMEROPRATICA, 
  CONVERT(VARCHAR,ISTANZE.DATA,103) AS DATAPRESENTAZIONE, 
  YEAR(ISTANZE.DATA) AS ANNOPRESENTAZIONE, 
  MONTH(ISTANZE.DATA) AS MESEPRESENTAZIONE, 
  ISTANZE.NUMEROPROTOCOLLO      AS NUMEROPROTOCOLLO, 
  CONVERT(VARCHAR,ISTANZE.DATAPROTOCOLLO,103) AS DATAPROTOCOLLO, 
  ISTANZE.CODICEINTERVENTOPROC  AS CODICEINTERVENTO, 
  VW_ALBEROPROC.SC_DESCRIZIONE  AS DESCRIZIONEINTERVENTO, 
  TIPIPROCEDURE.CODICEPROCEDURA AS CODICEPROCEDURA, 
  TIPIPROCEDURE.PROCEDURA       AS PROCEDURA, 
  ISTANZE.LAVORI                AS OGGETTO, 
  UPPER(ISTANZE.LAVORI)         AS OGGETTOU, 
  ISTANZE.CHIUSURA              AS CODSTATOPRATICA, 
  STATIISTANZA.STATO            AS STATOPRATICA, 
  RESPONSABILI.RESPONSABILE     AS RESPONSABILE, 
  RESPONSABILI.TELEFONOLAVORO   AS RESPONSABILE_TELEFONO, 
  ISNULL(STRADARIO.CODVIARIO,STRADARIO.CODICESTRADARIO) AS PR_CODVIARIO, 
  STRADARIO.PREFISSO + ' ' + STRADARIO.DESCRIZIONE AS PR_INDIRIZZO, 
  ISTANZESTRADARIO.CODICECIVICO AS PR_CODCIVICO, 
  ISTANZESTRADARIO.CIVICO                AS PR_CIVICO, 
  ISTANZE.CODICEAREA            AS CODICEZONIZZAZIONE, 
  AREE.DENOMINAZIONE            AS ZONIZZAZIONE, 
  ANAGRAFE.CODICEANAGRAFE       AS CODICERICHIEDENTE, 
  ISNULL(ANAGRAFE.CODICEFISCALE,'') AS CODICEFISCALE, 
  ISNULL(ANAGRAFE.PARTITAIVA,'') AS PARTITAIVA, 
  ANAGRAFE.NOMINATIVO + ' ' + ANAGRAFE.NOME AS NOMINATIVO, 
  ANAGRAFE.INDIRIZZO            AS INDIRIZZO, 
  ANAGRAFE.CAP                  AS CAP, 
  ANAGRAFE.CITTA                AS LOCALITA, 
  COMUNERESIDENZA.COMUNE        AS CITTA, 
  COMUNERESIDENZA.PROVINCIA     AS PROVINCIA, 
  TIPISOGGETTO.TIPOSOGGETTO     AS TIPORAPPORTO, 
  CATASTO.DESCRIZIONE           AS TIPOCATASTO, 
  ISTANZEMAPPALI.FOGLIO         AS FOGLIO, 
  ISTANZEMAPPALI.PARTICELLA     AS PARTICELLA, 
  ISTANZEMAPPALI.SUB            AS SUB, 
  TECNICO.CODICEANAGRAFE        AS TEC_CODICE, 
  TECNICO.NOMINATIVO + ' ' + TECNICO.NOME AS TEC_NOMINATIVO, 
  ISNULL(TECNICO.CODICEFISCALE,'') AS TEC_CODICEFISCALE, 
  ISNULL(TECNICO.PARTITAIVA,'') AS TEC_PARTITAIVA, 
  AZIENDA.CODICEANAGRAFE        AS AZ_CODICE, 
  AZIENDA.NOMINATIVO + ' ' + AZIENDA.NOME AS AZ_NOMINATIVO, 
  ISNULL(AZIENDA.CODICEFISCALE,'') AS AZ_CODICEFISCALE, 
  ISNULL(AZIENDA.PARTITAIVA,'') AS AZ_PARTITAIVA, 
  ISTRUTTORI.RESPONSABILE       AS ISTRUTTORE, 
  ISTRUTTORI.TELEFONOLAVORO     AS ISTRUTTORE_TELEFONO, 
  OPERATORI.RESPONSABILE        AS OPERATORE, 
  OPERATORI.TELEFONOLAVORO      AS OPERATORE_TELEFONO 
FROM    
ISTANZE  
    JOIN SOFTWARE ON SOFTWARE.CODICE = ISTANZE.SOFTWARE 
    JOIN ANAGRAFE ON ANAGRAFE.IDCOMUNE = ISTANZE.IDCOMUNE 
                      AND ANAGRAFE.CODICEANAGRAFE = ISTANZE.CODICERICHIEDENTE 
    JOIN STATIISTANZA ON STATIISTANZA.IDCOMUNE = ISTANZE.IDCOMUNE 
                          AND STATIISTANZA.SOFTWARE = ISTANZE.SOFTWARE 
                          AND STATIISTANZA.CODICESTATO = ISTANZE.CHIUSURA 
    JOIN VW_ALBEROPROC ON VW_ALBEROPROC.IDCOMUNE = ISTANZE.IDCOMUNE 
                        AND VW_ALBEROPROC.SC_ID = ISTANZE.CODICEINTERVENTOPROC 
    LEFT OUTER JOIN ANAGRAFE TECNICO ON TECNICO.IDCOMUNE = ISTANZE.IDCOMUNE  
                                  AND TECNICO.CODICEANAGRAFE = ISTANZE.CODICEPROFESSIONISTA 
    LEFT OUTER JOIN ANAGRAFE AZIENDA ON ISTANZE.IDCOMUNE = AZIENDA.IDCOMUNE 
                                  AND ISTANZE.CODICETITOLARELEGALE = AZIENDA.CODICEANAGRAFE 
    LEFT OUTER JOIN ISTANZESTRADARIO ON ISTANZE.IDCOMUNE = ISTANZESTRADARIO.IDCOMUNE 
                                  AND ISTANZE.CODICEISTANZA = ISTANZESTRADARIO.CODICEISTANZA  
                                  AND 1 = ISTANZESTRADARIO.PRIMARIO 
                                  LEFT OUTER JOIN STRADARIO ON STRADARIO.IDCOMUNE = ISTANZESTRADARIO.IDCOMUNE 
                                                        AND STRADARIO.CODICESTRADARIO = ISTANZESTRADARIO.CODICESTRADARIO  
    LEFT OUTER JOIN ISTANZEMAPPALI ON ISTANZE.IDCOMUNE = ISTANZEMAPPALI.IDCOMUNE  
                              AND ISTANZE.CODICEISTANZA = ISTANZEMAPPALI.FKCODICEISTANZA 
                              AND 1 = ISTANZEMAPPALI.PRIMARIO 
    LEFT OUTER JOIN RESPONSABILI ON ISTANZE.IDCOMUNE = RESPONSABILI.IDCOMUNE 
                            AND ISTANZE.CODICERESPONSABILEPROC = RESPONSABILI.CODICERESPONSABILE 
    LEFT OUTER JOIN COMUNI COMUNERESIDENZA ON ANAGRAFE.COMUNERESIDENZA = COMUNERESIDENZA.CODICECOMUNE 
    LEFT OUTER JOIN TIPISOGGETTO ON ISTANZE.IDCOMUNE = TIPISOGGETTO.IDCOMUNE 
                                  AND ISTANZE.FKCODICESOGGETTO = TIPISOGGETTO.CODICETIPOSOGGETTO 
    LEFT OUTER JOIN AREE ON ISTANZE.IDCOMUNE = AREE.IDCOMUNE 
                         AND ISTANZE.CODICEAREA = AREE.CODICEAREA 
    LEFT OUTER JOIN CATASTO ON ISTANZEMAPPALI.CODICECATASTO = CATASTO.CODICE 
    LEFT OUTER JOIN TIPIPROCEDURE ON ISTANZE.IDCOMUNE = TIPIPROCEDURE.IDCOMUNE 
                                  AND ISTANZE.CODICEPROCEDURA = TIPIPROCEDURE.CODICEPROCEDURA 
    LEFT OUTER JOIN RESPONSABILI ISTRUTTORI ON ISTANZE.IDCOMUNE = ISTRUTTORI.IDCOMUNE             
                                            AND ISTANZE.CODICEISTRUTTORE = ISTRUTTORI.CODICERESPONSABILE 
    LEFT OUTER JOIN RESPONSABILI OPERATORI ON OPERATORI.IDCOMUNE = ISTANZE.IDCOMUNE  
                                            AND OPERATORI.CODICERESPONSABILE = ISTANZE.CODICERESPONSABILE
GO
COMMIT
GO
CREATE INDEX IDX_ANAGRAFE_008 ON ANAGRAFE(IDCOMUNE,TIPOANAGRAFE)
GO
COMMIT
GO
ALTER TABLE FO_DOMANDE ADD CODICEOGGETTO_CART NUMERIC(10, 0)
GO
COMMIT
GO
ALTER TABLE FO_DOMANDE ADD CONSTRAINT FK_FO_DOMANDE_OGGETTI FOREIGN KEY (IDCOMUNE,CODICEOGGETTO_CART) REFERENCES OGGETTI (IDCOMUNE,CODICEOGGETTO)
GO
COMMIT
GO
ALTER TABLE LEGGI ALTER COLUMN LE_DESCRIZIONE VARCHAR(200)
GO
COMMIT
GO
ALTER TABLE MOVIMENTI ALTER COLUMN NOTE VARCHAR(4000)
GO
COMMIT
GO
UPDATE verticalizzazioniparametri SET VALORE = VALORE + '/stc?wsdl' WHERE PARAMETRO = 'STC_WS_URL'  and VALORE like '%services'
GO
COMMIT
GO
ALTER TABLE ALBEROPROC_DOCUMENTICAT ALTER COLUMN ID numeric(10)
GO
COMMIT
GO
ALTER TABLE ALBEROPROC_DOCUMENTI ALTER COLUMN FKIDCATEGORIA numeric(10)
GO
COMMIT
GO
ALTER TABLE TIPIMODALITAPAGAMENTO ALTER COLUMN MP_ID numeric(10)
GO
COMMIT
GO
ALTER TABLE ISTANZEONERI ALTER COLUMN FKMODALITAPAGAMENTO numeric(10)
GO
COMMIT
GO
ALTER TABLE ALBEROPROC ADD CONSTRAINT FK_ALBERO_PROC_PROT_TIPI_DOC FOREIGN KEY(IDCOMUNE, SC_PROTTIPODOCUMENTO) REFERENCES PROTOCOLLO_TIPIDOCUMENTO (IDCOMUNE, CODICE)
GO
COMMIT
GO
update comuni set codiceistat = '0'+codiceistat where codicestatoestero is null and len(codiceistat) = 5
GO
COMMIT
GO
ALTER TABLE CONFIGURAZIONE ALTER COLUMN CODAMMSPORTELLOUNICO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE CONFIGURAZIONE ALTER COLUMN CODICELASTESSAAMMINISTRAZIONE NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE CONFIGURAZIONE ALTER COLUMN CODICETUTTEAMMINISTRAZIONI NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE ALBEROPROC ADD CODICEOPERATORE_STC NUMERIC(4,0)
GO
COMMIT
GO
ALTER TABLE ALBEROPROC ADD CONSTRAINT FK_ALBEROPROC_OPESTC FOREIGN KEY (IDCOMUNE,CODICEOPERATORE_STC ) REFERENCES RESPONSABILI (IDCOMUNE, CODICERESPONSABILE)
GO
COMMIT
GO
ALTER TABLE ALLEGATI ADD NOTE_FRONTEND VARCHAR(4000)
GO
COMMIT
GO
ALTER TABLE ALBEROPROC_DOCUMENTI ADD NOTE_FRONTEND VARCHAR(4000)
GO
COMMIT
GO
ALTER TABLE TIPIPROCEDURE_DOCUMENTI ADD NOTE_FRONTEND VARCHAR(4000)
GO
COMMIT
GO
ALTER TABLE MOVIMENTI ADD CODICEOGGETTO_NOTIFICA NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE MOVIMENTI ADD CONSTRAINT FK_OGGETTI_MOV_NOTSTC FOREIGN KEY (IDCOMUNE,CODICEOGGETTO_NOTIFICA) REFERENCES OGGETTI (IDCOMUNE,CODICEOGGETTO)
GO
COMMIT
GO
ALTER TABLE ISTANZE_TEMPISTICA ADD DATAFINEEFFETTIVA DATETIME
GO
COMMIT
GO
ALTER TABLE ISTANZE_TEMPISTICA ADD GGAGGIUNTIVI NUMERIC(4,0)
GO
COMMIT
GO
ALTER TABLE TIPIPROCEDURE ADD FLAG_DISABILITATO NUMERIC(1,0)
GO
COMMIT
GO 
ALTER TABLE AMMINISTRAZIONI ADD FLAG_DISABILITATO NUMERIC(1,0)
GO
COMMIT
GO 
ALTER TABLE TIPIMOVIMENTO ADD FLAG_DISABILITATO NUMERIC(1,0)
GO
COMMIT
GO
ALTER TABLE LETTERETIPO ADD FLAG_DISABILITATO NUMERIC(1,0)
GO
COMMIT
GO
ALTER TABLE TIPIPROCEDURE_DOCUMENTI ADD PUBBLICA NUMERIC(1,0) NULL
GO
COMMIT
GO
ALTER TABLE TIPIPROCEDURE_DOCUMENTI ADD RICHIESTO NUMERIC(1,0) NULL
GO
COMMIT
GO
ALTER TABLE TIPIPROCEDURE_DOCUMENTI ADD FO_RICHIEDEFIRMA NUMERIC(1,0) NULL
GO
COMMIT
GO
ALTER TABLE TIPIPROCEDURE_DOCUMENTI ADD FO_TIPODOWNLOAD VARCHAR(30) NULL
GO
COMMIT
GO
ALTER TABLE ANAGRAFE ALTER COLUMN PARTITAIVA VARCHAR(32) 
GO
COMMIT
GO
ALTER TABLE ANAGRAFE ALTER COLUMN CODICEFISCALE VARCHAR(32)
GO
COMMIT
GO
ALTER TABLE ANAGRAFESTORICO ALTER COLUMN PARTITAIVA VARCHAR(32 )
GO
COMMIT
GO
ALTER TABLE ANAGRAFESTORICO ALTER COLUMN CODICEFISCALE VARCHAR(32)
GO
COMMIT
GO
ALTER TABLE DOMANDESTC ALTER COLUMN CODICEFISCALE_RICHIEDENTE VARCHAR(32)
GO
COMMIT
GO
ALTER TABLE ISTANZEFIDEJUSSIONI  ALTER COLUMN FK_RCO_ID NUMERIC(10, 0)
GO
COMMIT
GO
ALTER TABLE STP_ENDO_TIPO1 ADD CODICE_ENDO_REGIONALE VARCHAR(20)
GO
COMMIT
GO
drop view VW_MERCATIPRESENZETOTALI
GO
COMMIT
GO
CREATE View VW_MERCATIPRESENZETOTALI AS SELECT 'STORICO' AS ORIGINE, MERCATIPRESENZE_STORICO.IDCOMUNE, MERCATIPRESENZE_STORICO.ANNO, MERCATIPRESENZE_STORICO.CODICEANAGRAFE, MERCATIPRESENZE_STORICO.FK_AUTORIZZAZIONI_ID, MERCATIPRESENZE_STORICO.FKCODICEMERCATO, MERCATIPRESENZE_STORICO.FKIDMERCATIUSO, MERCATIPRESENZE_STORICO.FK_IDPOSTEGGIO AS FKIDPOSTEGGIO,  MERCATIPRESENZE_STORICO.NUMEROPRESENZE, ltrim(rtrim( ANAGRAFE.NOMINATIVO + ' ' + ANAGRAFE.NOME )) AS ANAGRAFE, ANAGRAFE.CODICEFISCALE, ANAGRAFE.PARTITAIVA, COMUNI.COMUNE AS COMUNERESIDENZA, CITTADINANZA.CITTADINANZA, CONVERT(DATETIME,ANAGRAFE.DATAREGDITTE, 103 ) AS DATAREGDITTE FROM MERCATIPRESENZE_STORICO inner join ANAGRAFE on ANAGRAFE.IDCOMUNE = MERCATIPRESENZE_STORICO.IDCOMUNE AND  ANAGRAFE.CODICEANAGRAFE = MERCATIPRESENZE_STORICO.CODICEANAGRAFE left outer join COMUNI on COMUNI.CODICECOMUNE = ANAGRAFE.COMUNERESIDENZA left outer join CITTADINANZA on CITTADINANZA.CODICE = ANAGRAFE.CODICECITTADINANZA UNION ALL  SELECT 'CALENDARIO' AS ORIGINE, MERCATIPRESENZE_T.IDCOMUNE,MERCATIPRESENZE_T.ANNO, MERCATIPRESENZE_D.CODICEANAGRAFE, MERCATIPRESENZE_D.FK_AUTORIZZAZIONI_ID, MERCATIPRESENZE_T.FKCODICEMERCATO, MERCATIPRESENZE_T.FKIDMERCATIUSO,MERCATIPRESENZE_D.FKIDPOSTEGGIO, 1 AS NUMEROPRESENZE, ltrim(rtrim( ANAGRAFE.NOMINATIVO + ' ' + ANAGRAFE.NOME )) AS ANAGRAFE, ANAGRAFE.CODICEFISCALE, ANAGRAFE.PARTITAIVA, COMUNI.COMUNE AS COMUNERESIDENZA, CITTADINANZA.CITTADINANZA, CONVERT(DATETIME,ANAGRAFE.DATAREGDITTE, 103 ) AS DATAREGDITTE FROM MERCATIPRESENZE_T inner join MERCATIPRESENZE_D on MERCATIPRESENZE_D.IDCOMUNE = MERCATIPRESENZE_T.IDCOMUNE AND MERCATIPRESENZE_D.FKIDTESTATA = MERCATIPRESENZE_T.ID inner join ANAGRAFE on ANAGRAFE.IDCOMUNE = MERCATIPRESENZE_D.IDCOMUNE AND ANAGRAFE.CODICEANAGRAFE = MERCATIPRESENZE_D.CODICEANAGRAFE left outer join COMUNI on COMUNI.CODICECOMUNE = ANAGRAFE.COMUNERESIDENZA left outer join CITTADINANZA on CITTADINANZA.CODICE = ANAGRAFE.CODICECITTADINANZA
GO
COMMIT
GO
DROP VIEW VW_CONCESSIONILISTA
GO
COMMIT
GO
CREATE VIEW VW_CONCESSIONILISTA AS SELECT IDCOMUNE, SOFTWARE, PROGRESSIVO, CONC_ID, CONC_NUMERO, CONC_DATARILASCIO, CONC_DATASCADENZA, CONC_CODICETIPO, CONC_TIPO, CONC_STAGIONALEA, CONC_STAGIONALEDA, CONC_ATTIVA, CONC_CODICETITOLARE, CONC_TITOLARE, CONC_TIT_CF, CONC_TIT_PIVA, CONC_TIT_TIPOANAGRAFE, AUT_NUMERO, AUT_DATA, AUT_CODREGISTRO, AUT_REGISTRO, IST_CODICEISTANZA, IST_NUMEROISTANZA, IST_CODICERICHIEDENTE, IST_NOMINATIVO, IST_CODICEFISCALE, IST_PARTITAIVA, IST_RIC_TIPOANAGRAFE, ICONC_CODICECAUSALE, ICONC_CAUSALE, ICONC_CODICECAUSALESTORICO, ICONC_CAUSALESTORICO, CONC_IDMERCATO, CONC_MERCATO, MERC_ATTIVO, CONC_IDPOSTEGGIO, CONC_POSTEGGIO, CONC_POS_LARGHEZZA, CONC_POS_LUNGHEZZA, CONC_POS_SUPERFICIE, POST_IDTIPOSPAZIO, POST_TIPOSPAZIO, CONC_IDMERCATIUSO, CONC_DESCRIZIONEUSO, PESO_MERCATO, MERC_IDUSO, CONC_POS_CODICESTRADARIO, DATA_STORICO FROM VW_ISTANZECONCESSIONILISTA
GO 
COMMIT 
GO
CREATE TABLE PROTOCOLLO_MEZZI
(
  IDCOMUNE VARCHAR(6) NOT NULL
, CODICE VARCHAR(50) NOT NULL
, DESCRIZIONE VARCHAR(100) NOT NULL
)
GO
COMMIT
GO
ALTER TABLE PROTOCOLLO_MEZZI ADD CONSTRAINT PROTOCOLLO_MEZZI_PK PRIMARY KEY (IDCOMUNE,CODICE)
GO
COMMIT
GO
CREATE TABLE RI_CARICHE(
CODICE VARCHAR(5) NOT NULL,
DESCRIZIONE VARCHAR(150)
)
GO
COMMIT
GO
ALTER TABLE RI_CARICHE ADD CONSTRAINT RI_CARICHE_PK PRIMARY KEY(CODICE)
GO
COMMIT
GO
ALTER TABLE TIPISOGGETTO ADD FK_RICA_CODICE VARCHAR(5)
GO
COMMIT
GO
ALTER TABLE TIPISOGGETTO ADD CONSTRAINT FK_TIPISOGG_RICARI FOREIGN KEY (FK_RICA_CODICE ) REFERENCES RI_CARICHE(CODICE)
GO
COMMIT
GO
CREATE TABLE RI_FORMEGIURIDICHE (
CODICE VARCHAR(5),
DESCRIZIONE VARCHAR(150)
)
GO
COMMIT
GO
ALTER TABLE RI_FORMEGIURIDICHE ADD CONSTRAINT RI_FORMEGIURIDICHE_PK PRIMARY KEY (CODICE)
GO
COMMIT
GO
CREATE TABLE ISTANZE_RI (
IDCOMUNE VARCHAR(6) NOT NULL,
ID NUMERIC(9,0) NOT NULL,
CODICEISTANZA NUMERIC(6,0),
UFFICIORI VARCHAR(2),
DATAPROTOCOLLORI VARCHAR(10),
NUMEROPROTOCOLLORI VARCHAR(50),
ANNO VARCHAR(4)
)
GO
COMMIT
GO
ALTER TABLE ISTANZE_RI ADD CONSTRAINT ISTANZE_RI_PK PRIMARY KEY (IDCOMUNE, ID)
GO
COMMIT
GO 
ALTER TABLE ISTANZE_RI ADD CONSTRAINT FK_ISTRI_ISTANZE FOREIGN KEY (IDCOMUNE, CODICEISTANZA) REFERENCES ISTANZE(IDCOMUNE, CODICEISTANZA)
GO
COMMIT
GO
CREATE INDEX IDX_ISTANZE_RI_001 ON ISTANZE_RI (IDCOMUNE, CODICEISTANZA)
GO
COMMIT
GO
CREATE TABLE I_ATTIVITA_SNAPSHOT
  (
    IDCOMUNE            VARCHAR(6) NOT NULL,
    ID                 NUMERIC(6,0) NOT NULL,
    DENOMINAZIONE       VARCHAR(150),
    CODICEISTANZAULTIMA NUMERIC(6,0),
    NUMEROPRESENZE      NUMERIC(4,0),
    ATTIVA              NUMERIC(1,0),
    OPERANTE            NUMERIC(1,0),
    DATA                DATETIME,
    FK_IA_ID            NUMERIC(6,0) NOT NULL
)
GO
COMMIT
GO
ALTER TABLE I_ATTIVITA_SNAPSHOT ADD CONSTRAINT PK_SNAPSHOT PRIMARY KEY (IDCOMUNE,ID)
GO
COMMIT
GO 
ALTER TABLE I_ATTIVITA_SNAPSHOT ADD CONSTRAINT FK_IATTIVITA_SNAPSHOT_ISTANZE FOREIGN KEY (IDCOMUNE, CODICEISTANZAULTIMA)  REFERENCES ISTANZE (IDCOMUNE, CODICEISTANZA)
GO
COMMIT
GO
ALTER TABLE I_ATTIVITA_SNAPSHOT ADD CONSTRAINT FK_IATTIVITA_SNAPSHOT_ATTIVITA FOREIGN KEY (IDCOMUNE, FK_IA_ID) REFERENCES I_ATTIVITA(IDCOMUNE, ID)
GO
COMMIT
GO
CREATE TABLE I_ATTIVITADYN2MOD_T_SNAPSHOT
(
  IDCOMUNE   VARCHAR(6) NOT NULL,
  FK_D2MT_ID NUMERIC(10,0)     NOT NULL,
  FK_IA_ID   NUMERIC(6,0)      NOT NULL,
  FK_IAS_ID  NUMERIC(6,0)      NOT NULL
)
GO
COMMIT
GO
  
ALTER TABLE I_ATTIVITADYN2MOD_T_SNAPSHOT ADD CONSTRAINT I_ATTIVITADYN2M_T_SNAPSHOT_PK PRIMARY KEY (IDCOMUNE, FK_D2MT_ID, FK_IA_ID,FK_IAS_ID)
GO
COMMIT
GO
ALTER TABLE I_ATTIVITADYN2MOD_T_SNAPSHOT ADD CONSTRAINT FK_IATTDYNMOD_T_SNAP_DYN_MOD_T FOREIGN KEY (IDCOMUNE, FK_D2MT_ID)   REFERENCES DYN2_MODELLIT (IDCOMUNE, ID)
GO
COMMIT
GO
ALTER TABLE I_ATTIVITADYN2MOD_T_SNAPSHOT ADD CONSTRAINT FK_IATT_DYNMOD_T_SNAP_I_ATT FOREIGN KEY (IDCOMUNE, FK_IA_ID) REFERENCES I_ATTIVITA (IDCOMUNE, ID)
GO
COMMIT
GO
ALTER TABLE I_ATTIVITADYN2MOD_T_SNAPSHOT ADD CONSTRAINT FK_IATT_DYNMODT_SNAP_IATT_S FOREIGN KEY (IDCOMUNE, FK_IAS_ID) REFERENCES I_ATTIVITA_SNAPSHOT (IDCOMUNE, ID)
GO
COMMIT
GO
CREATE TABLE I_ATTIVITADYN2DATI_SNAPSHOT 
  (
    IDCOMUNE  VARCHAR(6) NOT NULL,
    FK_IA_ID  NUMERIC(6,0) NOT NULL,
    FK_D2C_ID NUMERIC(10,0) NOT NULL,
    FK_IAS_ID NUMERIC(6,0) NOT NULL,
    INDICE NUMERIC(2,0) NOT NULL,
    INDICE_MOLTEPLICITA NUMERIC(2,0) NOT NULL,
    VALORE NTEXT,
    VALOREDECODIFICATO NTEXT
  )
GO
COMMIT
GO  
ALTER TABLE I_ATTIVITADYN2DATI_SNAPSHOT ADD CONSTRAINT I_ATTIVITADYN2DATI_SNAPSHOT_PK PRIMARY KEY (IDCOMUNE, FK_IA_ID, FK_D2C_ID,FK_IAS_ID, INDICE, INDICE_MOLTEPLICITA)
GO
COMMIT
GO 
ALTER TABLE I_ATTIVITADYN2DATI_SNAPSHOT ADD CONSTRAINT FK_IATTIVADYN2_DATI_S_DYN2C FOREIGN KEY (IDCOMUNE, FK_D2C_ID) REFERENCES DYN2_CAMPI (IDCOMUNE, ID)
GO
COMMIT
GO
ALTER TABLE I_ATTIVITADYN2DATI_SNAPSHOT ADD CONSTRAINT FK_IATTIVADYN2_DATI_S_I_ATT FOREIGN KEY (IDCOMUNE, FK_IA_ID) REFERENCES I_ATTIVITA (IDCOMUNE, ID)
GO
COMMIT
GO
ALTER TABLE I_ATTIVITADYN2DATI_SNAPSHOT ADD CONSTRAINT FK_IATT_DYN2_DATI_S_I_ATT_S FOREIGN KEY (IDCOMUNE, FK_IAS_ID) REFERENCES I_ATTIVITA_SNAPSHOT (IDCOMUNE, ID)
GO
COMMIT
GO
CREATE TABLE FO_MOVIMENTI 
(
  IDCOMUNE VARCHAR(6) NOT NULL 
, CODMOVORIG NUMERIC(8, 0) NOT NULL 
, TIPOMOVDAFARE VARCHAR(8) NOT NULL 
, DATI NTEXT NOT NULL 
, TRASMESSO NUMERIC(1, 0)
)
GO
COMMIT
GO
ALTER TABLE FO_MOVIMENTI ADD CONSTRAINT FO_MOVIMENTI_PK PRIMARY KEY (IDCOMUNE,CODMOVORIG,TIPOMOVDAFARE )
GO
COMMIT
GO
ALTER TABLE CONFIGURAZIONE ADD CODICEAMMINISTRAZIONE_IPA VARCHAR(20)
GO
COMMIT
GO
ALTER TABLE CONFIGURAZIONE ADD CODICE_AOO VARCHAR(20)
GO
COMMIT
GO
DROP INDEX IDX_DYN2_CAMPI_001
GO
COMMIT
GO
ALTER TABLE DYN2_CAMPI ALTER COLUMN NOMECAMPO VARCHAR(255) not null
GO
COMMIT
GO
CREATE UNIQUE INDEX IDX_DYN2_CAMPI_001 ON DYN2_CAMPI (IDCOMUNE,SOFTWARE,NOMECAMPO)
GO
COMMIT
GO
CREATE TABLE ALBEROPROC_D2MODTATT
  (
    IDCOMUNE         VARCHAR(6) NOT NULL,
    FK_SC_ID             NUMERIC(10,0) NOT NULL,
    FK_D2MT_ID       NUMERIC(10,0) NOT NULL
  )
GO
COMMIT
GO
ALTER TABLE ALBEROPROC_D2MODTATT ADD CONSTRAINT ALBEROPROC_D2MODTATT_PK PRIMARY KEY (IDCOMUNE,FK_SC_ID,FK_D2MT_ID)
GO
COMMIT
GO
ALTER TABLE ALBEROPROC_D2MODTATT ADD CONSTRAINT FK_ALBEROPROC_D2MODTATT_D2MT FOREIGN KEY (IDCOMUNE,FK_D2MT_ID) REFERENCES DYN2_MODELLIT (IDCOMUNE, ID)
GO
COMMIT
GO
ALTER TABLE ALBEROPROC_D2MODTATT ADD CONSTRAINT FK_ALBEROP_D2MODTATT_ALBPROC FOREIGN KEY (IDCOMUNE, FK_SC_ID) REFERENCES ALBEROPROC (IDCOMUNE,SC_ID)
GO
COMMIT
GO
ALTER TABLE PROT_GENERALE ADD PG_INDIRIZZOMITTENTE VARCHAR(4000)
GO
COMMIT
GO
ALTER TABLE PROT_GENERALE ADD PG_INDIRIZZOPERCONTODI VARCHAR(4000)
GO
COMMIT
GO
ALTER TABLE PROT_GENERALE ADD PG_INDIRIZZODESTINATARIO VARCHAR(4000)
GO
COMMIT
GO
ALTER TABLE PROT_ALTRIDESTINATARI ADD AD_INDIRIZZO VARCHAR(4000)
GO
COMMIT
GO
CREATE TABLE PROTOCOLLO_UFFICIREGISTRI (CODICEREGISTRO VARCHAR(10) NOT NULL, CODICEUFFICIO VARCHAR(10) NOT NULL, IDCOMUNE VARCHAR(6) NOT NULL)
GO
COMMIT
GO
ALTER TABLE PROTOCOLLO_UFFICIREGISTRI ADD CONSTRAINT PROTOCOLLO_UFFICIREGISTRI_PK PRIMARY KEY (CODICEREGISTRO,IDCOMUNE)
GO
COMMIT
GO
CREATE TABLE OGGETTI_METADATI (
	IDCOMUNE VARCHAR(6) NOT NULL,	
	CODICEOGGETTO NUMERIC(10,0) NOT NULL,
	CHIAVE VARCHAR(100) NOT NULL,
	VALORE VARCHAR(4000)
)
GO
COMMIT
GO
ALTER TABLE OGGETTI_METADATI ADD CONSTRAINT PK_OGGETTI_METADATI PRIMARY KEY(IDCOMUNE,CODICEOGGETTO, CHIAVE)
GO
COMMIT
GO
ALTER TABLE OGGETTI_METADATI ADD CONSTRAINT FK_OGGETTI_METADATI FOREIGN KEY (IDCOMUNE,CODICEOGGETTO) REFERENCES OGGETTI (IDCOMUNE,CODICEOGGETTO)
GO
COMMIT
GO
CREATE TABLE PROTOCOLLO_MODALITAINVIO(ICOMUNE VARCHAR(6) NOT NULL, CODICE VARCHAR(30) NOT NULL, DESCRIZIONE VARCHAR(300) NOT NULL)
GO
COMMIT
GO
ALTER TABLE PROTOCOLLO_MODALITAINVIO ADD CONSTRAINT PROTOCOLLO_MODALITAINVIO_PK PRIMARY KEY (ICOMUNE,CODICE)
GO
COMMIT
GO
ALTER TABLE MAPPATURE ALTER COLUMN ID NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE TIPIMOV_STC_MAPPING ALTER COLUMN ID NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE TIPIMOV_STC_ALBEROPROC ALTER COLUMN ID NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE TIPIMOV_STC_ALTRIDATI ALTER COLUMN ID NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE TIPIMOV_STC_MODELLI ALTER COLUMN ID NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE TIPISOGGETTO ADD ATRIB_QUALIFICASOGGETTO NUMERIC(1,0)
GO
COMMIT
GO
ALTER TABLE TIPIPROCEDURE ADD ATRIB_TIPORICHIESTA NUMERIC(1,0)
GO
COMMIT
GO
ALTER TABLE COMUNIASSOCIATI ADD CODICEAMMINISTRAZIONE_IPA VARCHAR(20)
GO
COMMIT
GO
ALTER TABLE COMUNIASSOCIATI ADD CODICEFISCALE VARCHAR(11)
GO
COMMIT
GO
ALTER TABLE COMUNIASSOCIATISOFTWARE ADD CODICE_ACCREDITAMENTO VARCHAR(30)
GO
COMMIT
GO
ALTER TABLE COMUNIASSOCIATISOFTWARE ADD CODICE_AOO VARCHAR(20)
GO
COMMIT
GO
CREATE TABLE RI_TIPIINTERVENTO(
CODICE VARCHAR(20) NOT NULL,
DESCRIZIONE VARCHAR(150)
)
GO
COMMIT
GO
ALTER TABLE RI_TIPIINTERVENTO ADD CONSTRAINT RI_TIPIINTERVENTO_PK PRIMARY KEY(CODICE)
GO
COMMIT
GO
ALTER TABLE ALBEROPROC ADD FK_RITI_CODICE VARCHAR(20)
GO
COMMIT
GO
ALTER TABLE ALBEROPROC ADD CONSTRAINT FK_RITIPIINT_ALBPROC FOREIGN KEY (FK_RITI_CODICE) REFERENCES RI_TIPIINTERVENTO(CODICE)
GO
COMMIT
GO
CREATE TABLE RI_TIPIPROCEDIMENTO(
CODICE VARCHAR(20) NOT NULL,
DESCRIZIONE VARCHAR(150)
)
GO
COMMIT
GO
ALTER TABLE RI_TIPIPROCEDIMENTO ADD CONSTRAINT RI_TIPIPROCEDIMENTO_PK PRIMARY KEY(CODICE)
GO
COMMIT
GO
ALTER TABLE TIPIPROCEDURE ADD FK_RITP_CODICE VARCHAR(20)
GO
COMMIT
GO
ALTER TABLE TIPIPROCEDURE ADD CONSTRAINT FK_RITIPIPROC_TIPROC FOREIGN KEY(FK_RITP_CODICE) REFERENCES RI_TIPIPROCEDIMENTO(CODICE)
GO
COMMIT
GO
ALTER TABLE OGGETTI ALTER COLUMN NOMEFILE VARCHAR(256)
GO
COMMIT
GO
ALTER TABLE TIPIMOV_STC_MAPPING ADD FLAG_ALLEGA_DOCUMENTI_ENDO NUMERIC(1,0)
GO
COMMIT
GO