ALTER TABLE ALBEROPROCPEOPLEOPER MODIFY SETTORE VARCHAR2(30);
ALTER TABLE ALBEROPROCPEOPLEOPER MODIFY OPERAZIONE VARCHAR2(30);

ALTER TABLE ISTANZEPROCURE MODIFY STC_ID_ALLEGATO VARCHAR2(500);
ALTER TABLE ISTANZEPROCURE MODIFY STC_ID_DOCUMENTO VARCHAR2(500);

ALTER TABLE DOCUMENTIISTANZA MODIFY STC_IDALLEGATO VARCHAR2(500);
ALTER TABLE DOCUMENTIISTANZA MODIFY STC_IDDOCUMENTO VARCHAR2(500);

ALTER TABLE ISTANZEALLEGATI MODIFY STC_IDDOCUMENTO VARCHAR2(500);
ALTER TABLE ISTANZEALLEGATI MODIFY STC_IDALLEGATO VARCHAR2(500);


ALTER TABLE MOVIMENTIALLEGATI MODIFY STC_IDDOCUMENTO VARCHAR2(500);
ALTER TABLE MOVIMENTIALLEGATI MODIFY STC_IDALLEGATO VARCHAR2(500);
