
update mercatipresenze_d set FLAG_ASSENZA_GIUST=0 where FLAG_ASSENZA_GIUST is null;
alter table mercatipresenze_d modify (FLAG_ASSENZA_GIUST NUMBER(1,0) DEFAULT 0 not null ) ;

CREATE INDEX IDX_DETTPOSDEB_IDPOSDEB ON DETT_POSIZIONE_DEBITORIA (IDCOMUNE,ID_POSIZIONE_DEBITORIA);
ALTER TABLE BLACKLIST_AUTORIZZAZIONI ADD (FK_IDMERCATIUSO NUMBER(4));
ALTER TABLE BLACKLIST_AUTORIZZAZIONI ADD CONSTRAINT FK_BL_AUTORIZ_USO FOREIGN KEY(IDCOMUNE,FK_IDMERCATIUSO) REFERENCES MERCATI_USO(IDCOMUNE,ID);
CREATE INDEX IDX_BL_AUTORIZ_004 ON BLACKLIST_AUTORIZZAZIONI (IDCOMUNE, FK_IDMERCATIUSO);


UPDATE pay_richieste SET n_chiamate=0 WHERE n_chiamate IS NULL; 
ALTER TABLE pay_richieste MODIFY n_chiamate number(9,0) DEFAULT 0 NOT NULL ; 

CREATE INDEX idx_pay_richieste_01 ON pay_richieste(idcomune,fk_posizione_debitoria,tipo_richiesta);
CREATE INDEX idx_pay_richieste_02 ON pay_richieste(idcomune,fk_profilo_ente,tipo_richiesta);
CREATE INDEX idx_pay_richieste_03 ON pay_richieste(idcomune,fk_evento);
CREATE INDEX idx_pay_richieste_04 ON pay_richieste(idcomune,fk_evento_out);
CREATE INDEX idx_pay_richieste_05 ON pay_richieste(idcomune,data_richiesta);


CREATE INDEX IDX_DETTPOSDEB_01 ON DETT_POSIZIONE_DEBITORIA(IDCOMUNE,STATO);
CREATE INDEX IDX_BLACKLIST_MOT_01 ON BLACKLIST_MOTIVI(IDCOMUNE,DATA_FINE_BL);


CREATE TABLE ALBEROPROC_MOVIMENTI(
IDCOMUNE VARCHAR2(6 CHAR) NOT NULL,
ID NUMBER(6,0) NOT NULL,
FK_SCID NUMBER(10,0) NOT NULL,
FK_TIPOMOVIMENTO VARCHAR2(8 CHAR),
FK_CODICEAMMINISTRAZIONE NUMBER(10,0) NULL );

ALTER TABLE ALBEROPROC_MOVIMENTI ADD CONSTRAINT PK_ALBEROPROCMOVIMENTI PRIMARY KEY(IDCOMUNE, ID);

ALTER TABLE  ALBEROPROC_MOVIMENTI ADD CONSTRAINT FK_ALBEROPROCMOV_TIPIMOV FOREIGN KEY(IDCOMUNE,FK_TIPOMOVIMENTO) REFERENCES TIPIMOVIMENTO (IDCOMUNE,TIPOMOVIMENTO);

ALTER TABLE  ALBEROPROC_MOVIMENTI ADD CONSTRAINT FK_ALBEROPROCMOV_ALBEROPROC FOREIGN KEY(IDCOMUNE,FK_SCID) REFERENCES ALBEROPROC (IDCOMUNE,SC_ID);

ALTER TABLE  ALBEROPROC_MOVIMENTI ADD CONSTRAINT FK_ALBEROPROCMOV_AMMINIST FOREIGN KEY(IDCOMUNE,FK_CODICEAMMINISTRAZIONE) REFERENCES AMMINISTRAZIONI (IDCOMUNE,CODICEAMMINISTRAZIONE);

CREATE INDEX IDX_ALBRPROCMOV_01 ON ALBEROPROC_MOVIMENTI(IDCOMUNE, FK_SCID);

CREATE INDEX IDX_MERCAPRESSTORICO_01 ON mercatipresenze_storico(IDCOMUNE,FK_AUTORIZZAZIONI_ID,FKCODICEMERCATO,FKIDMERCATIUSO);