ALTER TABLE VERTICALIZZAZIONIPARAMETRI MODIFY COLUMN VALORE VARCHAR(4000);
ALTER TABLE domandestc_allegati MODIFY id NUMERIC(10,0);
ALTER TABLE MERCATI ADD ACTIVE_WALLET_MARKET NUMERIC(1,0) DEFAULT 0 NOT NULL;
CREATE TABLE RICALCOLO_AREE (
  IDCOMUNE VARCHAR(6) NOT NULL,  
  ID VARCHAR(50) NOT NULL,
  DESCRIZIONE VARCHAR(1000) NULL,
  STATO VARCHAR(20) NOT NULL,
  DATAFINE DATETIME NOT NULL,
  DAFARE DECIMAL(6,0) NOT NULL,
  FATTI DECIMAL(6,0) NOT NULL,
  TOTALI DECIMAL(6,0) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8;

ALTER TABLE RICALCOLO_AREE ADD CONSTRAINT PK_RICALCOLOAREE PRIMARY KEY(IDCOMUNE,ID);

ALTER TABLE MOVIMENTIMAIL ADD COLUMN BOZZA NUMERIC(1,0) NOT NULL DEFAULT 0;

CREATE TABLE RICALCOLO_AREE_ISTANZE (
  IDCOMUNE VARCHAR(6) NOT NULL,
  RICALCOLO_ID VARCHAR(50) NOT NULL,
  ISTANZE_UUID VARCHAR(60) NOT NULL,
  ID_RICALCOLO_AREE VARCHAR(50) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8;

ALTER TABLE RICALCOLO_AREE_ISTANZE ADD CONSTRAINT PK_RICALCOLOAREEIST PRIMARY KEY(IDCOMUNE,RICALCOLO_ID,ISTANZE_UUID);
CREATE INDEX IDX_RIC_AREE_ISTANZE_001 ON RICALCOLO_AREE_ISTANZE (IDCOMUNE,ID_RICALCOLO_AREE);
ALTER TABLE RICALCOLO_AREE_ISTANZE ADD CONSTRAINT FK_RICALCOLO_AREE_IST FOREIGN KEY(IDCOMUNE,ID_RICALCOLO_AREE) REFERENCES RICALCOLO_AREE (IDCOMUNE,ID);

ALTER TABLE MERCATI ADD ASSENZE_PERCENTUALE NUMERIC(10,0);
ALTER TABLE MERCATI ADD ASSENZE_TIPO_CALCOLO VARCHAR(500);
ALTER TABLE MERCATIPRESENZE_T ADD FLG_GG_NULLA NUMERIC(1,0) DEFAULT 0;
ALTER TABLE MERCATIPRESENZE_T ADD ANNOTAZIONI_GG_NULLA VARCHAR(4000);

CREATE TABLE MERCATI_AUD_PRESENZE (
  IDCOMUNE VARCHAR(6) NOT NULL,
  ID DECIMAL(10,0) NOT NULL,
  CODICEOPERATORE DECIMAL(8,0) DEFAULT NULL,
  FK_ID_AUT_SORGENTE DECIMAL(6,0) NOT NULL,
  FK_ID_AUT_DEST DECIMAL(6,0) NOT NULL,
  DATA_OPERAZIONE DATETIME NOT NULL,
  NOTE VARCHAR(4000) DEFAULT NULL,
  TOT_PRESENZE DECIMAL(6,0) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8;

ALTER TABLE MERCATI_AUD_PRESENZE ADD CONSTRAINT PK_MERCATI_AUD_PRES PRIMARY KEY (IDCOMUNE,ID);
ALTER TABLE MERCATI_AUD_PRESENZE ADD CONSTRAINT FK_AUD_PRESENZE_RESP FOREIGN KEY (IDCOMUNE, CODICEOPERATORE) REFERENCES responsabili (IDCOMUNE, CODICERESPONSABILE);
ALTER TABLE MERCATI_AUD_PRESENZE ADD CONSTRAINT FK_AUD_PRESENZE_SORG FOREIGN KEY (IDCOMUNE, FK_ID_AUT_SORGENTE) REFERENCES autorizzazioni (IDCOMUNE, ID);
ALTER TABLE MERCATI_AUD_PRESENZE ADD CONSTRAINT FK_AUD_PRESENZE_DEST FOREIGN KEY (IDCOMUNE, FK_ID_AUT_DEST) REFERENCES autorizzazioni (IDCOMUNE, ID);

CREATE INDEX IDX_MERCAUDPRES_001 ON MERCATI_AUD_PRESENZE (IDCOMUNE, CODICEOPERATORE);
CREATE INDEX IDX_MERCAUDPRES_002 ON MERCATI_AUD_PRESENZE (IDCOMUNE, FK_ID_AUT_SORGENTE);
CREATE INDEX IDX_MERCAUDPRES_003 ON MERCATI_AUD_PRESENZE (IDCOMUNE, FK_ID_AUT_DEST);

ALTER TABLE MERCATIPRESENZE_STORICO ADD COLUMN DATA DATE;
UPDATE MERCATIPRESENZE_STORICO SET DATA = STR_TO_DATE(CONCAT('01/01/', ANNO), '%d/%m/%Y') WHERE DATA IS NULL;
ALTER TABLE MERCATIPRESENZE_STORICO MODIFY DATA DATE NOT NULL;

CREATE INDEX IDX_MERCPRESSTORICO_002 ON MERCATIPRESENZE_STORICO (IDCOMUNE, FKCODICEMERCATO, FKIDMERCATIUSO, CODICEANAGRAFE, ANNO, FK_AUTORIZZAZIONI_ID);
ALTER TABLE MERCATIPRESENZE_STORICO DROP INDEX IDX_MERCPRESSTORICO_001;
ALTER TABLE MERCATIPRESENZE_STORICO ADD CONSTRAINT IDX_MERCPRESSTORICO_003 UNIQUE (IDCOMUNE, FKCODICEMERCATO, FKIDMERCATIUSO, CODICEANAGRAFE, FK_AUTORIZZAZIONI_ID, DATA);

