<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="ComunicazionePosizioniDebitorieOTFImplService" targetNamespace="http://webservices.idp.tasgroup.it/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://webservices.idp.tasgroup.it/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns2="http://schemas.xmlsoap.org/soap/http" xmlns:ns1="http://www.cart.rete.toscana.it/servizi/iris_1_1/proxy" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:import namespace="http://www.cart.rete.toscana.it/servizi/iris_1_1/proxy" location="https://apistore.regione.umbria.it/registry/resource/_system/governance/apimgt/applicationdata/wsdls/ComunicazionePosizioniDebitorieOTF.wsdl">
    </wsdl:import>
  <wsdl:binding name="ComunicazionePosizioniDebitorieOTFImplServiceSoapBinding" type="ns1:ComunicazionePosizioniDebitorieOTF">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="IdpAllineamentoPendenzeEnteOTF">
      <soap:operation soapAction="IdpAllineamentoPendenzeEnteOTF" style="document"/>
      <wsdl:input name="IdpAllineamentoPendenzeEnteOTF">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="IdpAllineamentoPendenzeEnteOTFResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="IdpAllineamentoPendenzeMultiEnteOTF">
      <soap:operation soapAction="IdpAllineamentoPendenzeMultiEnteOTF" style="document"/>
      <wsdl:input name="IdpAllineamentoPendenzeMultiEnteOTF">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="IdpAllineamentoPendenzeMultiEnteOTFResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ComunicazionePosizioniDebitorieOTFImplService">
    <wsdl:port name="ComunicazionePosizioniDebitorieOTFPort" binding="tns:ComunicazionePosizioniDebitorieOTFImplServiceSoapBinding">
      <soap:address location="https://api.regione.umbria.it:443/pagoumbriacomunicazioneposizionedebitoria/1.0"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
