<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns1="http://www.cart.rete.toscana.it/servizi/iris_1_1/proxy" name="VerificaStatoPagamento" targetNamespace="http://www.cart.rete.toscana.it/servizi/iris_1_1/proxy">
  <wsdl:types>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ns3="http://www.cart.rete.toscana.it/servizi/iris_1_1/IdpEsito" xmlns:ns2="http://www.cart.rete.toscana.it/servizi/iris_1_1/IdpInformativaPagamento" xmlns:ns1="http://www.cart.rete.toscana.it/servizi/iris_1_1/IdpHeader" xmlns="http://www.cart.rete.toscana.it/servizi/iris_1_1/proxy" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://www.cart.rete.toscana.it/servizi/iris_1_1/proxy">
  <xs:import namespace="http://www.cart.rete.toscana.it/servizi/iris_1_1/IdpHeader"/>
  <xs:import namespace="http://www.cart.rete.toscana.it/servizi/iris_1_1/IdpInformativaPagamento"/>
  <xs:import namespace="http://www.cart.rete.toscana.it/servizi/iris_1_1/IdpEsito"/>
  <xs:element name="IdpVerificaStatoPagamenti">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ns2:IdpVerificaStatoPagamento"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="IdpVerificaStatoPagamenti.Esito">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ns3:IdpEsitoVerifica"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.cart.rete.toscana.it/servizi/iris_1_1/IdpInformativaPagamento" xmlns:ns2="http://www.cart.rete.toscana.it/servizi/iris_1_1/IdpInclude" xmlns:ns1="http://www.cart.rete.toscana.it/servizi/iris_1_1/IdpHeader" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://www.cart.rete.toscana.it/servizi/iris_1_1/IdpInformativaPagamento">
  <xs:import namespace="http://www.cart.rete.toscana.it/servizi/iris_1_1/IdpHeader"/>
  <xs:import namespace="http://www.cart.rete.toscana.it/servizi/iris_1_1/IdpInclude"/>
  <xs:element name="IdpInformativaPagamento" type="tns:IdpInformativaPagamento"/>
  <xs:element name="IdpVerificaStatoPagamento">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="IdpHeader" type="ns1:IdpHeader"/>
        <xs:element name="IdpBody">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="IdPagamento" type="tns:idPagamento"/>
              <xs:element minOccurs="0" name="richiestaInformazioniPagamento" type="xs:boolean"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="Versione" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="idPagamento">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="TipoPendenza" type="xs:string" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="Pagamento">
    <xs:sequence>
      <xs:element name="RiferimentoPagamento" type="tns:RiferimentoPagamento"/>
      <xs:element name="DataOraPagamento" type="xs:anySimpleType"/>
      <xs:element minOccurs="0" name="DataScadenzaPagamento" type="xs:anySimpleType"/>
      <xs:element name="Importo" type="xs:decimal"/>
      <xs:element minOccurs="0" name="RiferimentoDebitore" type="xs:string"/>
      <xs:element name="Esito" type="tns:TipoNotifica"/>
      <xs:element minOccurs="0" name="Pagante" type="tns:Pagante"/>
      <xs:element minOccurs="0" name="Transazione" type="tns:Transazione"/>
      <xs:element minOccurs="0" name="FlagQuietanzaCartacea" type="xs:boolean"/>
      <xs:element minOccurs="0" name="Note" type="xs:string"/>
      <xs:element minOccurs="0" name="Allegato" type="ns2:Allegato"/>
      <xs:element minOccurs="0" name="RiferimentoDebito" type="tns:RiferimentoDebito"/>
      <xs:element minOccurs="0" name="DescrizioneCausale" type="xs:string"/>
      <xs:element minOccurs="0" name="IdentificativoUnivocoVersamento" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="RiferimentoPagamento">
    <xs:sequence>
      <xs:element name="IdPagamento" type="xs:string"/>
    </xs:sequence>
    <xs:attribute name="TipoPagamento" type="ns2:TipoPagamento" use="required"/>
  </xs:complexType>
  <xs:complexType name="Pagante">
    <xs:sequence>
      <xs:element minOccurs="0" name="IdPagante" type="xs:string"/>
      <xs:element minOccurs="0" name="Descrizione" type="xs:string"/>
    </xs:sequence>
    <xs:attribute name="Tipo" type="xs:string"/>
  </xs:complexType>
  <xs:complexType name="Transazione">
    <xs:sequence>
      <xs:element name="CanalePagamento" type="tns:CanalePagamento"/>
      <xs:element name="MezzoPagamento" type="tns:MezzoPagamento"/>
      <xs:element minOccurs="0" name="DettaglioCanalePagamento" type="ns2:DettaglioCanalePagamento"/>
      <xs:element name="IdTransazione" type="xs:string"/>
      <xs:element name="DataOraTransazione" type="xs:anySimpleType"/>
      <xs:element minOccurs="0" name="CodiceAutorizzazione" type="xs:string"/>
      <xs:element minOccurs="0" name="DataOraAutorizzazione" type="xs:anySimpleType"/>
      <xs:element minOccurs="0" name="TipoSicurezza" type="xs:string"/>
      <xs:element name="ImportoTransato" type="xs:decimal"/>
      <xs:element minOccurs="0" name="DettaglioImportoTransato" type="tns:DettaglioImportoTransato"/>
      <xs:element minOccurs="0" name="Descrizione" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="CanalePagamento">
    <xs:sequence>
      <xs:element minOccurs="0" name="Descrizione" type="xs:string"/>
    </xs:sequence>
    <xs:attribute name="Tipo" type="xs:string" use="required"/>
  </xs:complexType>
  <xs:complexType name="MezzoPagamento">
    <xs:sequence>
      <xs:element minOccurs="0" name="Descrizione" type="xs:string"/>
    </xs:sequence>
    <xs:attribute name="Tipo" type="xs:string" use="required"/>
  </xs:complexType>
  <xs:complexType name="DettaglioImportoTransato">
    <xs:sequence>
      <xs:element maxOccurs="unbounded" name="Voce" type="tns:Voce"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="Voce">
    <xs:sequence>
      <xs:element name="Descrizione" type="xs:string"/>
      <xs:element name="Importo" type="xs:decimal"/>
    </xs:sequence>
    <xs:attribute name="Tipo" type="tns:TipoVoce" use="required"/>
  </xs:complexType>
  <xs:complexType name="RiferimentoDebito">
    <xs:sequence>
      <xs:element name="Pendenza" type="xs:string"/>
    </xs:sequence>
    <xs:attribute name="TipoDebito" type="xs:string" use="required"/>
  </xs:complexType>
  <xs:complexType name="IdpBody">
    <xs:sequence>
      <xs:element maxOccurs="unbounded" name="Pagamento" type="tns:Pagamento"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="IdpInformativaPagamento">
    <xs:sequence>
      <xs:element ref="ns1:IdpHeader"/>
      <xs:element name="IdpBody" type="tns:IdpBody"/>
    </xs:sequence>
    <xs:attribute name="Versione" type="xs:string" use="required"/>
  </xs:complexType>
  <xs:simpleType name="TipoNotifica">
    <xs:restriction base="xs:string">
      <xs:enumeration value="ESEGUITO"/>
      <xs:enumeration value="REGOLATO"/>
      <xs:enumeration value="INCASSO"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="TipoVoce">
    <xs:restriction base="xs:string">
      <xs:enumeration value="ImportoTransato"/>
      <xs:enumeration value="ImportoAutorizzato"/>
      <xs:enumeration value="ImportoCommissioni"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.cart.rete.toscana.it/servizi/iris_1_1/IdpInclude" elementFormDefault="qualified" targetNamespace="http://www.cart.rete.toscana.it/servizi/iris_1_1/IdpInclude" version="1.0">

  <xs:complexType name="DettaglioCanalePagamento">
    <xs:sequence>
      <xs:element minOccurs="0" name="Filiale" type="xs:string"/>
      <xs:element minOccurs="0" name="Sportello" type="xs:string"/>
      <xs:element minOccurs="0" name="IdTerminale" type="xs:string"/>
      <xs:element minOccurs="0" name="IdOperazione" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="Allegato">
    <xs:sequence>
      <xs:element minOccurs="0" name="Titolo" type="xs:string"/>
      <xs:element name="Codifica" type="tns:MIMETypeCode"/>
      <xs:element name="Contenuto" type="xs:base64Binary"/>
      <xs:element minOccurs="0" name="IdAntifalsificazione" type="xs:string"/>
    </xs:sequence>
    <xs:attribute name="Tipo" type="tns:ContentType" use="required"/>
  </xs:complexType>

  <xs:complexType name="CoordinateBancarie">
    <xs:sequence>
      <xs:element name="CodiceIBAN" type="xs:string"/>
      <xs:element name="Beneficiario" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="CIP">
    <xs:sequence>
      <xs:element name="Codice" type="xs:string"/>
    </xs:sequence>
    <xs:attribute name="Tipo" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:simpleType name="VerificaStatoPagamento">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Posizione non presente"/>
      <xs:enumeration value="Posizione non pagabile"/>
      <xs:enumeration value="Pagamento non eseguito"/>
      <xs:enumeration value="Pagamento eseguito"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="TipoPagamento">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Pagamento a Rate"/>
      <xs:enumeration value="Pagamento Unico"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="MIMETypeCode">
    <xs:restriction base="xs:string">
      <xs:enumeration value="GIF_"/>
      <xs:enumeration value="HTML"/>
      <xs:enumeration value="JPEG"/>
      <xs:enumeration value="LNK_"/>
      <xs:enumeration value="MSWD"/>
      <xs:enumeration value="MSEX"/>
      <xs:enumeration value="MSPP"/>
      <xs:enumeration value="PDF_"/>
      <xs:enumeration value="PNG_"/>
      <xs:enumeration value="TEXT"/>
      <xs:enumeration value="XML_"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="ContentType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Documento"/>
      <xs:enumeration value="Ricevuta"/>
      <xs:enumeration value="Quietanza"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="stTipoSoggetto">
    <xs:restriction base="xs:string">
      <xs:enumeration value="F"/>
      <xs:enumeration value="G"/>
    </xs:restriction>
  </xs:simpleType>

</xs:schema>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.cart.rete.toscana.it/servizi/iris_1_1/IdpHeader" xmlns:ns1="http://www.cart.rete.toscana.it/servizi/iris_1_1/IdpInclude" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://www.cart.rete.toscana.it/servizi/iris_1_1/IdpHeader">
  <xs:import namespace="http://www.cart.rete.toscana.it/servizi/iris_1_1/IdpInclude"/>
  <xs:element name="IdpHeader" type="tns:IdpHeader"/>
  <xs:element name="IdpOTF">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="URL_BACK" type="xs:string"/>
        <xs:element name="URL_CANCEL" type="xs:string"/>
        <xs:element minOccurs="0" name="OFFLINE_PAYMENT_METHODS" type="xs:boolean"/>
        <xs:element minOccurs="0" name="ID_PSP" type="xs:string"/>
        <xs:element minOccurs="0" name="DATI_VERSANTE" type="tns:DATI_VERSANTE_Type"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="IdpHeader">
    <xs:sequence>
      <xs:element name="TRT" type="tns:HeaderTRT"/>
      <xs:element name="E2E" type="tns:HeaderE2E"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="HeaderTRT">
    <xs:sequence>
      <xs:element name="ServiceName" type="tns:ServiceName"/>
      <xs:element name="MsgId" type="xs:string"/>
      <xs:element name="XMLCrtDt" type="xs:anySimpleType"/>
      <xs:element name="Sender" type="tns:TRTSender"/>
      <xs:element name="Receiver" type="tns:TRTReceiver"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="TRTSender">
    <xs:sequence>
      <xs:element name="SenderId" type="xs:string"/>
      <xs:element name="SenderSys" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="TRTReceiver">
    <xs:sequence>
      <xs:element name="ReceiverId" type="xs:string"/>
      <xs:element name="ReceiverSys" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="HeaderE2E">
    <xs:sequence>
      <xs:element name="E2ESrvcNm" type="xs:string"/>
      <xs:element name="E2EMsgId" type="xs:string"/>
      <xs:element name="XMLCrtDt" type="xs:anySimpleType"/>
      <xs:element name="Sender" type="tns:E2ESender"/>
      <xs:element name="Receiver" type="tns:E2EReceiver"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="E2ESender">
    <xs:sequence>
      <xs:element name="E2ESndrId" type="xs:string"/>
      <xs:element name="E2ESndrSys" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="E2EReceiver">
    <xs:sequence>
      <xs:element name="E2ERcvrId" type="xs:string"/>
      <xs:element name="E2ERcvrSys" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="DATI_VERSANTE_Type">
    <xs:sequence>
      <xs:element name="TIPO_SOGGETTO" type="ns1:stTipoSoggetto"/>
      <xs:element name="ID_FISCALE" type="xs:string"/>
      <xs:element name="ANAGRAFICA" type="xs:string"/>
      <xs:element minOccurs="0" name="E_MAIL" type="xs:string"/>
      <xs:element minOccurs="0" name="INDIRIZZO" type="xs:string"/>
      <xs:element minOccurs="0" name="NUMERO_CIVICO" type="xs:string"/>
      <xs:element minOccurs="0" name="CAP" type="xs:string"/>
      <xs:element minOccurs="0" name="LOCALITA" type="xs:string"/>
      <xs:element minOccurs="0" name="PROVINCIA" type="xs:string"/>
      <xs:element minOccurs="0" name="NAZIONE" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="ServiceName">
    <xs:restriction base="xs:string">
      <xs:enumeration value="IdpAllineamentoPendenze"/>
      <xs:enumeration value="IdpInformativaPagamento"/>
      <xs:enumeration value="IdpRendicontazioneEnti"/>
      <xs:enumeration value="IdpConfigurazioneEnte"/>
      <xs:enumeration value="IdpAutorizzazioneDiPagamento"/>
      <xs:enumeration value="IdpEstrattoContoDebitorio"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.cart.rete.toscana.it/servizi/iris_1_1/IdpEsito" xmlns:ns3="http://www.cart.rete.toscana.it/servizi/iris_1_1/IdpInformativaPagamento" xmlns:ns2="http://www.cart.rete.toscana.it/servizi/iris_1_1/IdpInclude" xmlns:ns1="http://www.cart.rete.toscana.it/servizi/iris_1_1/IdpHeader" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://www.cart.rete.toscana.it/servizi/iris_1_1/IdpEsito">
  <xs:import namespace="http://www.cart.rete.toscana.it/servizi/iris_1_1/IdpHeader"/>
  <xs:import namespace="http://www.cart.rete.toscana.it/servizi/iris_1_1/IdpInclude"/>
  <xs:import namespace="http://www.cart.rete.toscana.it/servizi/iris_1_1/IdpInformativaPagamento"/>
  <xs:element name="IdpEsito" type="tns:IdpEsito"/>
  <xs:element name="IdpEsitoOTF" type="tns:IdpEsitoOTF"/>
  <xs:element name="IdpEsitoVerifica">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="IdpHeader" type="ns1:IdpHeader"/>
        <xs:element name="IdpBody">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" minOccurs="0" name="StatoPagamento" type="tns:StatoPagamentoType"/>
              <xs:element maxOccurs="unbounded" minOccurs="0" name="InformazioniPagamento" type="tns:InformazioniPagamentoType"/>
              <xs:element minOccurs="0" name="Esito" type="tns:Esito"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="Versione" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="IdpMultiEsitoOTF" type="tns:IdpMultiEsitoOTF"/>
  <xs:complexType name="StatoPagamentoType">
    <xs:simpleContent>
      <xs:extension base="ns2:VerificaStatoPagamento">
        <xs:attribute name="IdPagamento" type="xs:string" use="required"/>
        <xs:attribute name="TipoPendenza" type="xs:string" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="InformazioniPagamentoType">
    <xs:sequence>
      <xs:element name="IdPagamento" type="xs:string"/>
      <xs:element name="TipoPendenza" type="xs:string"/>
      <xs:element name="Stato" type="tns:VerificaStatoPagamentoDettagliato"/>
      <xs:element name="DescrizioneStato" type="xs:string"/>
      <xs:element minOccurs="0" name="Pagamento" type="ns3:Pagamento"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="Esito">
    <xs:sequence>
      <xs:element name="Codice" type="xs:string"/>
      <xs:element name="Descrizione" type="xs:string"/>
      <xs:element minOccurs="0" name="Elemento" type="xs:string"/>
      <xs:element minOccurs="0" name="Note" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="Dettaglio">
    <xs:sequence>
      <xs:element name="Id" type="xs:string"/>
      <xs:element name="Stato" type="tns:StatoDettaglio"/>
      <xs:element minOccurs="0" name="Esiti" type="tns:Esiti"/>
      <xs:element minOccurs="0" name="Note" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="Esiti">
    <xs:sequence>
      <xs:element maxOccurs="unbounded" name="Esito" type="tns:Esito"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="IdpOTFType">
    <xs:sequence>
      <xs:element name="IdSessioneGW" type="xs:string"/>
      <xs:element name="UrlGW" type="xs:anyURI"/>
    </xs:sequence>
    <xs:attribute name="Versione" type="xs:string" use="required"/>
  </xs:complexType>
  <xs:complexType name="InfoDettaglio">
    <xs:sequence>
      <xs:element maxOccurs="unbounded" name="Dettaglio" type="tns:Dettaglio"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="IdpMultiEsitoOTFElement">
    <xs:sequence>
      <xs:element name="E2EMsgId" type="xs:string"/>
      <xs:element name="IdpBody" type="tns:IdpBodyType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="IdpBodyType">
    <xs:sequence>
      <xs:element name="InfoMessaggio" type="tns:InfoMessaggio"/>
      <xs:element minOccurs="0" name="InfoDettaglio" type="tns:InfoDettaglio"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="InfoMessaggio">
    <xs:sequence>
      <xs:element name="Stato" type="tns:StatoMessaggio"/>
      <xs:element minOccurs="0" name="Esiti" type="tns:Esiti"/>
      <xs:element minOccurs="0" name="Note" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="IdpMultiEsitoOTF">
    <xs:sequence>
      <xs:element minOccurs="0" name="IdpOTF" type="tns:IdpOTFType"/>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="IdpEsitoOTF" type="tns:IdpMultiEsitoOTFElement"/>
    </xs:sequence>
    <xs:attribute name="Versione" type="xs:string" use="required"/>
  </xs:complexType>
  <xs:complexType name="IdpEsito">
    <xs:sequence>
      <xs:element ref="ns1:IdpHeader"/>
      <xs:element name="IdpBody" type="tns:IdpBodyType"/>
    </xs:sequence>
    <xs:attribute name="Versione" type="xs:string" use="required"/>
  </xs:complexType>
  <xs:complexType name="IdpEsitoOTF">
    <xs:sequence>
      <xs:element ref="ns1:IdpHeader"/>
      <xs:element minOccurs="0" name="IdpOTF" type="tns:IdpOTFType"/>
      <xs:element name="IdpBody" type="tns:IdpBodyType"/>
    </xs:sequence>
    <xs:attribute name="Versione" type="xs:string" use="required"/>
  </xs:complexType>
  <xs:simpleType name="VerificaStatoPagamentoDettagliato">
    <xs:restriction base="xs:string">
      <xs:enumeration value="POSIZIONE_NON_PRESENTE"/>
      <xs:enumeration value="POSIZIONE_NON_PAGATA"/>
      <xs:enumeration value="POSIZIONE_NON_PAGABILE"/>
      <xs:enumeration value="POSIZIONE_PAGATA"/>
      <xs:enumeration value="POSIZIONE_PAGATA_SBF"/>
      <xs:enumeration value="POSIZIONE_CON_PAG_IN_CORSO"/>
      <xs:enumeration value="POSIZIONE_CON_DOC_EMESSO"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="StatoDettaglio">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Scartato"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="StatoMessaggio">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Elaborato Correttamente"/>
      <xs:enumeration value="Elaborato con Errori"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>
  </wsdl:types>
  <wsdl:message name="IdpVerificaStatoPagamenti">
    <wsdl:part element="ns1:IdpVerificaStatoPagamenti" name="IdpVerificaStatoPagamenti">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="IdpVerificaStatoPagamentiResponse">
    <wsdl:part element="ns1:IdpVerificaStatoPagamenti.Esito" name="IdpVerificaStatoPagamenti.Esito">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="VerificaStatoPagamento">
    <wsdl:operation name="IdpVerificaStatoPagamenti">
      <wsdl:input message="ns1:IdpVerificaStatoPagamenti" name="IdpVerificaStatoPagamenti">
    </wsdl:input>
      <wsdl:output message="ns1:IdpVerificaStatoPagamentiResponse" name="IdpVerificaStatoPagamentiResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>