CREATE INDEX IDX_ALBEROPROC_004 ON ALBEROPROC(IDCOMUNE, SOFTWARE,FLAG_ESCLUDI_RISULTATI_RICERCA);
create index  IDX_MESSAGGI_MAIL_001 ON MESSAGGI_MAIL(IDCOMUNE, MESSAGE_ID(255));
create index IDX_MESSAGGI_MAIL_002 on messaggi_mail (IDCOMUNE,ID_PADRE);