CREATE TABLE FIRMEREMOTE(IDCOMUNE VARCHAR2(6 CHAR) NOT NULL, ID NUMBER(10,0) NOT NULL, PROVIDER VARCHAR2(20 CHAR) NOT NULL, DESCRIZIONE VARCHAR2(50 CHAR) NOT NULL, ENDPOINT VARCHAR2(100 CHAR) NOT NULL, FLAG_ATTIVA NUMBER(1,0) NOT NULL);
ALTER TABLE FIRMEREMOTE ADD CONSTRAINT PK_FIRMEREMOTE PRIMARY KEY(IDCOMUNE,ID);
CREATE INDEX IDX_FIRMEREMOTE_001 ON FIRMEREMOTE(IDCOMUNE,PROVIDER);
CREATE INDEX IDX_FIRMEREMOTE_002 ON FIRMEREMOTE(IDCOMUNE,FLAG_ATTIVA);

CREATE TABLE FIRMEREMOTE_PARAMETRI(IDCOMUNE VARCHAR2(6 CHAR) NOT NULL, FK_IDFIRMAREMOTA NUMBER(10,0) NOT NULL, CHIAVE VARCHAR2(40 CHAR) NOT NULL, DESCRIZIONE VARCHAR2(500 CHAR) NOT NULL, OBBLIGATORIO NUMBER(1,0) NOT NULL, VISIBILE NUMBER(1,0) NOT NULL, READONLY NUMBER(1,0) NOT NULL, TIPOCAMPO VARCHAR2(20 CHAR) NOT NULL, VALOREDEFAULT VARCHAR2(200 CHAR), ORDINE NUMBER(3,0) NOT NULL);
ALTER TABLE FIRMEREMOTE_PARAMETRI ADD CONSTRAINT PK_FIRMEREMOTEPARAMETRI PRIMARY KEY(IDCOMUNE,FK_IDFIRMAREMOTA,CHIAVE);
ALTER TABLE FIRMEREMOTE_PARAMETRI ADD CONSTRAINT FK_FIRMEREMOTE FOREIGN KEY(IDCOMUNE,FK_IDFIRMAREMOTA) REFERENCES FIRMEREMOTE(IDCOMUNE,ID);

ALTER TABLE manifestazioni ADD COMPORTAMENTO_PRESENZE NUMBER(1,0);
UPDATE MANIFESTAZIONI SET COMPORTAMENTO_PRESENZE = 0 WHERE CODICE = 0;
UPDATE MANIFESTAZIONI SET COMPORTAMENTO_PRESENZE = 1 WHERE CODICE = 1;
INSERT INTO MANIFESTAZIONI (CODICE,DESCRIZIONE,COMPORTAMENTO_PRESENZE) VALUES (2, 'GRUPPO POSTEGGI', 1);
ALTER TABLE manifestazioni MODIFY COMPORTAMENTO_PRESENZE NUMBER(1,0) NOT NULL;


ALTER TABLE movimentimail MODIFY oggetto VARCHAR2(4000 CHAR);

alter table decodifiche add constraint PK_DECODIFICHE primary key (IDCOMUNE,ID);


ALTER TABLE TIPIDOCUMENTO ADD CODICEOGGETTO_XSL NUMBER(10,0);
ALTER TABLE TIPIDOCUMENTO ADD CONSTRAINT FK_TIPIDOCXSL_OGGETTI FOREIGN KEY(IDCOMUNE,CODICEOGGETTO_XSL) REFERENCES OGGETTI(IDCOMUNE,CODICEOGGETTO);



ALTER TABLE parametriesportazione ADD ordine NUMBER(4,0);
UPDATE parametriesportazione SET ordine=id WHERE ordine IS NULL;
ALTER TABLE parametriesportazione MODIFY  ordine NUMBER(4,0) NOT NULL;

ALTER TABLE PEOPLEPROCSPORTELLI MODIFY COLUMN PEOPLE_PROC VARCHAR2(50 CHAR);

CREATE TABLE TMP_ISTANZE(IDCOMUNE VARCHAR2(6 CHAR) NOT NULL, SESSIONID VARCHAR2(60 CHAR) NOT NULL, UUID VARCHAR2(60 CHAR) NOT NULL );
ALTER TABLE TMP_ISTANZE ADD CONSTRAINT PK_TMPISTANZE PRIMARY KEY(IDCOMUNE,SESSIONID,UUID);