ALTER TABLE DOMANDESTC MODIFY RICHIEDENTE VARCHAR2(250);
ALTER TABLE DYN2_CAMPI MODIFY (ETICHETTA VARCHAR2(200 CHAR));
ALTER TABLE DYN2_MODELLIT MODIFY (DESCRIZIONE VARCHAR2(150 CHAR));
ALTER TABLE ISTANZEONERI ADD (FLAG_ONERE_RATEIZZATO NUMBER(1,0) DEFAULT 0);
ALTER TABLE ISTANZEONERI ADD (IMPORTO_INTERESSE NUMBER(11,2)  DEFAULT 0);


ALTER TABLE ANAGRAFESTORICO MODIFY ID NUMBER(10,0);

ALTER TABLE ISTANZE MODIFY FK_RICHIEDENTESTORICO_ID NUMBER(10,0);
ALTER TABLE ISTANZE MODIFY FK_TITOLARELEGALESTORICO_ID NUMBER(10,0);
ALTER TABLE ISTANZE MODIFY FK_PROFESSIONISTASTORICO_ID NUMBER(10,0);

ALTER TABLE ISTANZERICHIEDENTI MODIFY FK_RICHIEDENTESTORICO_ID NUMBER(10,0);
ALTER TABLE ISTANZERICHIEDENTI MODIFY FK_ANAGRAFECOLLSTORICO_ID NUMBER(10,0);
ALTER TABLE ISTANZERICHIEDENTI MODIFY FK_PROCURATORESTORICO_ID NUMBER(10,0);

ALTER TABLE COMUNIASSOCIATI ADD DISATTIVO_FO NUMBER(1,0) DEFAULT 0;
ALTER TABLE dyn2_modellid ADD flg_spezza_tabella number(1);