ALTER TABLE INVENTARIOPROCEDIMENTIPEOPLE DROP CONSTRAINT INVENTARIOPROCEDIMENTIPEOPL_PK;
DROP INDEX INVENTARIOPROCEDIMENTIPEOPL_PK;
ALTER TABLE INVENTARIOPROCEDIMENTIPEOPLE ADD CONSTRAINT INVENTARIOPROCEDIMENTIPEOPL_PK PRIMARY KEY (IDCOMUNE, ID);
ALTER TABLE AUTORIZZAZIONI_CONCESSIONI ADD CONSTRAINT FK_AUTCONC_MERCATI_D FOREIGN KEY(IDCOMUNE,FK_IDPOSTEGGIO) REFERENCES MERCATI_D(IDCOMUNE,IDPOSTEGGIO);
ALTER TABLE MERCATI_D ADD CONSTRAINT FK_MERCATID_STRADARIO FOREIGN KEY(IDCOMUNE,FKCODICESTRADARIO) REFERENCES STRADARIO(IDCOMUNE,CODICESTRADARIO);
ALTER TABLE MERCATI_D ADD CONSTRAINT FK_MERCATID_MERCATI FOREIGN KEY(IDCOMUNE,FKCODICEMERCATO) REFERENCES MERCATI(IDCOMUNE,CODICEMERCATO);
ALTER TABLE MERCATI_DATTIVITAISTAT ADD CONSTRAINT FK_MERC_DATTIVIT_MERCATID FOREIGN KEY (IDCOMUNE, FKIDPOSTEGGIO) REFERENCES MERCATI_D (IDCOMUNE, IDPOSTEGGIO);
ALTER TABLE CONFIGURAZIONE MODIFY (ORARIO VARCHAR2(1000 CHAR));
ALTER TABLE OGGETTI MODIFY NOMEFILE VARCHAR2(216 CHAR);

ALTER TABLE FO_VISURA_CAMPI DROP CONSTRAINT FO_VISURA_CAMPI__FK1;
ALTER TABLE FO_VISURA_CAMPI DROP CONSTRAINT FO_VISURA_CAMPI__FK2;

ALTER TABLE FO_VISURA_CAMPI ADD CONSTRAINT FK_FO_VIS_CAMPI_CONTESTI_BASE FOREIGN KEY (FKIDCONTESTO) REFERENCES FO_VISURA_CONTESTI_BASE (ID);
ALTER TABLE FO_VISURA_CAMPI ADD CONSTRAINT FK_FO_VIS_CAMPI_CAMPI_BASE FOREIGN KEY (FKIDCAMPO) REFERENCES FO_VISURA_CAMPI_BASE (ID);


ALTER TABLE FO_VISURA_CAMPI ADD CONSTRAINT FK_FO_VIS_CAMPI_SOFTWARE FOREIGN KEY (SOFTWARE) REFERENCES SOFTWARE (CODICE);
ALTER TABLE MAIL_CONFIG MODIFY LOGINNAME VARCHAR2(320 CHAR);
Create Or Replace View VW_I_ATTIVITALISTA as Select I_ATTIVITA.CODICEISTANZAULTIMA as I_CODICEISTANZAULTIMA, I_ATTIVITA.ID as I_IDATTIVITA, I_ATTIVITA.IDCOMUNE, I_ATTIVITA.ATTIVA, I_ATTIVITA.OPERANTE, ISTANZE.SOFTWARE, I_ATTIVITA.DENOMINAZIONE, ISTANZE.NUMEROISTANZA, ISTANZE.CODICERICHIEDENTE, T_RICHIEDENTE.NOMINATIVO || ' ' || T_RICHIEDENTE.NOME as RICHIEDENTE, TRIM(T_RICHIEDENTE.CODICEFISCALE || ' ' || T_RICHIEDENTE.PARTITAIVA) as CF_PIVA_RICHIEDENTE, ISTANZE.FKCODICESOGGETTO, TIPISOGGETTO.TIPOSOGGETTO, ISTANZE.CODICECOMUNE, ISTANZE.CODICETITOLARELEGALE,  TRIM(T_AZIENDARICHIEDENTE.NOMINATIVO || ' ' || T_AZIENDARICHIEDENTE.NOME) as AZIENDARICHIEDENTE,  TRIM(T_AZIENDARICHIEDENTE.CODICEFISCALE || ' ' || T_AZIENDARICHIEDENTE.PARTITAIVA) as CF_PIVA_AZIENDARICHIEDENTE, ISTANZESTRADARIO.CODICESTRADARIO, STRADARIO.PREFISSO || ' ' || STRADARIO.DESCRIZIONE || ',' || NVL(ISTANZESTRADARIO.CIVICO,'') || NVL(ISTANZESTRADARIO.COLORE,'') as LOCALIZZAZIONE, ISTANZESTRADARIO.CIVICO From  I_ATTIVITA, ISTANZE, ANAGRAFE T_RICHIEDENTE, TIPISOGGETTO, ANAGRAFE T_AZIENDARICHIEDENTE, ISTANZESTRADARIO, STRADARIO Where ISTANZE.IDCOMUNE = I_ATTIVITA.IDCOMUNE and ISTANZE.CODICEISTANZA = I_ATTIVITA.CODICEISTANZAULTIMA and T_RICHIEDENTE.IDCOMUNE = ISTANZE.IDCOMUNE and T_RICHIEDENTE.CODICEANAGRAFE = ISTANZE.CODICERICHIEDENTE and T_AZIENDARICHIEDENTE.IDCOMUNE(+) = ISTANZE.IDCOMUNE and T_AZIENDARICHIEDENTE.CODICEANAGRAFE(+) = ISTANZE.CODICETITOLARELEGALE and TIPISOGGETTO.IDCOMUNE(+) = ISTANZE.IDCOMUNE and TIPISOGGETTO.CODICETIPOSOGGETTO(+) = ISTANZE.FKCODICESOGGETTO and ISTANZESTRADARIO.IDCOMUNE(+) = ISTANZE.IDCOMUNE and ISTANZESTRADARIO.CODICEISTANZA(+) = ISTANZE.CODICEISTANZA and ISTANZESTRADARIO.PRIMARIO(+)=1 and STRADARIO.IDCOMUNE(+) = ISTANZESTRADARIO.IDCOMUNE and STRADARIO.CODICESTRADARIO(+) = ISTANZESTRADARIO.CODICESTRADARIO WITH READ ONLY;
ALTER TABLE DYN2_CAMPIPROPRIETA MODIFY VALORE VARCHAR2(2000 CHAR);
ALTER TABLE STP_ENDO_TIPO2 ADD CODICE_ENDO_REGIONALE VARCHAR2(20 CHAR); 
ALTER TABLE STP_ENDO_TIPO2 ADD CODICE_TIPOLOGIA_ENDO NUMBER(4,0);

CREATE OR REPLACE FORCE VIEW VW_SCADENZARIO (IDCOMUNE, CODICESCADENZA, SOFTWARE, CODICEISTANZA, NUMEROPROTOCOLLO, DATAPROTOCOLLO, 
NUMEROISTANZA, CODSTATOISTANZA, DESCRSTATOISTANZA, CODMOVIMENTO, DESCRMOVIMENTO, DATAMOVIMENTO, CODMOVIMENTODAFARE, 
DESCRMOVIMENTODAFARE, DATASCADENZASTR, CODICEINVENTARIO, CODICEAMMINISTRAZIONE, RESPONSABILE, PROCEDIMENTO, PROCEDURA, 
MODULOSOFTWARE, AMM_AMMINISTRAZIONE, AMM_PARTITAIVA, AMM_PASSWORD, RIC_NOMINATIVO, RIC_CODICEFISCALE, RIC_PARTITAIVA, 
RIC_INDIRIZZO, RIC_CAP, RIC_LOCALITA, RIC_CITTA, RIC_PROVINCIA, RIC_PASSWORD, TEC_NOMINATIVO, TEC_CODICEFISCALE, 
TEC_PARTITAIVA, TEC_PASSWORD, AZ_NOMINATIVO, AZ_CODICEFISCALE, AZ_PARTITAIVA, AZ_PASSWORD, FK_FO_SOGGETTIESTERNI)
                                                            AS
  SELECT VW_BATCH_SCADENZARIO.IDCOMUNE                      AS IDCOMUNE,
    VW_BATCH_SCADENZARIO.ID                                 AS CODICESCADENZA,
    VW_BATCH_SCADENZARIO.SOFTWARE                           AS software,
    VW_BATCH_SCADENZARIO.CODICEISTANZA                      AS codiceistanza,
    ISTANZE.NUMEROPROTOCOLLO                                AS numeroprotocollo,
    ISTANZE.DATAPROTOCOLLO                                  AS dataprotocollo,
    ISTANZE.NUMEROISTANZA                                   AS NUMEROISTANZA,
    ISTANZE.CHIUSURA                                        AS CODSTATOISTANZA,
    STATIISTANZA.STATO                                      AS DESCRSTATOISTANZA,
    VW_BATCH_SCADENZARIO.CODICEMOVIMENTO                    AS CODMOVIMENTO,
    VW_BATCH_SCADENZARIO.DESCRMOVIMENTO                     AS DESCRMOVIMENTO,
    TO_CHAR(MOVIMENTI.DATA,'DD/MM/YYYY')                    AS DATAMOVIMENTO,
    VW_BATCH_SCADENZARIO.TIPOMOVIMENTODAFARE                AS CODMOVIMENTODAFARE,
    VW_BATCH_SCADENZARIO.DESCRMOVIMENTODAFARE               AS DESCRMOVIMENTODAFARE,
    TO_CHAR(VW_BATCH_SCADENZARIO.DATASCADENZA,'DD/MM/YYYY') AS DATASCADENZASTR,
    VW_BATCH_SCADENZARIO.codiceinventario                   AS codiceinventario,
    VW_BATCH_SCADENZARIO.CODICEAMMINISTRAZIONE              AS CODICEAMMINISTRAZIONE,
    RESPONSABILI.RESPONSABILE                               AS RESPONSABILE,
    INVENTARIOPROCEDIMENTI.PROCEDIMENTO                     AS PROCEDIMENTO,
    TIPIPROCEDURE.PROCEDURA                                 AS PROCEDURA,
    SOFTWARE.DESCRIZIONE                                    AS MODULOSOFTWARE,
    amministrazioni.AMMINISTRAZIONE                         AS AMM_amministrazione,
    AMMINISTRAZIONI.PARTITAIVA                              AS AMM_PARTITAIVA,
    AMMINISTRAZIONI.PASSWORD                                AS AMM_PASSWORD,
    ANAGRAFE.NOMINATIVO
    || ' '
    || ANAGRAFE.NOME               AS RIC_NOMINATIVO,
    NVL(ANAGRAFE.CODICEFISCALE,'') AS RIC_CODICEFISCALE,
    NVL(ANAGRAFE.PARTITAIVA,'')    AS RIC_PARTITAIVA,
    ANAGRAFE.INDIRIZZO             AS RIC_INDIRIZZO,
    ANAGRAFE.CAP                   AS RIC_CAP,
    ANAGRAFE.CITTA                 AS RIC_LOCALITA,
    COMUNERESIDENZA.COMUNE         AS RIC_CITTA,
    COMUNERESIDENZA.PROVINCIA      AS RIC_PROVINCIA,
    ANAGRAFE.PASSWORD              AS RIC_PASSWORD,
    TECNICO.NOMINATIVO
    || ' '
    || TECNICO.NOME               AS TEC_NOMINATIVO,
    NVL(TECNICO.CODICEFISCALE,'') AS TEC_CODICEFISCALE,
    NVL(TECNICO.PARTITAIVA,'')    AS TEC_PARTITAIVA,
    TECNICO.PASSWORD              AS TEC_PASSWORD,
    AZIENDA.NOMINATIVO
    || ' '
    || AZIENDA.NOME               AS AZ_NOMINATIVO,
    NVL(AZIENDA.CODICEFISCALE,'') AS AZ_CODICEFISCALE,
    NVL(AZIENDA.PARTITAIVA,'')    AS AZ_PARTITAIVA,
    AZIENDA.PASSWORD              AS AZ_PASSWORD,
    TIPIMOVIMENTO.FK_FO_SOGGETTIESTERNI
  FROM VW_BATCH_SCADENZARIO,
    ISTANZE,
    RESPONSABILI,
    INVENTARIOPROCEDIMENTI,
    MOVIMENTI,
    TIPIPROCEDURE,
    SOFTWARE,
    ANAGRAFE,
    COMUNI COMUNERESIDENZA,
    ANAGRAFE TECNICO,
    ANAGRAFE AZIENDA,
    STATIISTANZA,
    AMMINISTRAZIONI,
    TIPIMOVIMENTO
  WHERE ISTANZE.IDCOMUNE                        =VW_BATCH_SCADENZARIO.IDCOMUNE
  AND ISTANZE.CODICEISTANZA                     =VW_BATCH_SCADENZARIO.CODICEISTANZA
  AND RESPONSABILI.IDCOMUNE                     =ISTANZE.IDCOMUNE
  AND RESPONSABILI.CODICERESPONSABILE           =ISTANZE.CODICERESPONSABILE
  AND INVENTARIOPROCEDIMENTI.IDCOMUNE(+)        =VW_BATCH_SCADENZARIO.IDCOMUNE
  AND INVENTARIOPROCEDIMENTI.CODICEINVENTARIO(+)=VW_BATCH_SCADENZARIO.CODICEINVENTARIO
  AND MOVIMENTI.IDCOMUNE                        =VW_BATCH_SCADENZARIO.IDCOMUNE
  AND MOVIMENTI.CODICEMOVIMENTO                 =VW_BATCH_SCADENZARIO.CODICEMOVIMENTO
  AND TIPIMOVIMENTO.IDCOMUNE                    =VW_BATCH_SCADENZARIO.IDCOMUNE
  AND TIPIMOVIMENTO.TIPOMOVIMENTO               =VW_BATCH_SCADENZARIO.TIPOMOVIMENTODAFARE
  AND TIPIPROCEDURE.IDCOMUNE                    =ISTANZE.IDCOMUNE
  AND TIPIPROCEDURE.CODICEPROCEDURA             =ISTANZE.CODICEPROCEDURA
  AND SOFTWARE.CODICE                           =VW_BATCH_SCADENZARIO.SOFTWARE
  AND ANAGRAFE.IDCOMUNE                         = ISTANZE.IDCOMUNE
  AND ANAGRAFE.CODICEANAGRAFE                   = ISTANZE.CODICERICHIEDENTE
  AND COMUNERESIDENZA.CODICECOMUNE(+)           = ANAGRAFE.COMUNERESIDENZA
  AND TECNICO.IDCOMUNE(+)                       = ISTANZE.IDCOMUNE
  AND TECNICO.CODICEANAGRAFE(+)                 = ISTANZE.CODICEPROFESSIONISTA
  AND AZIENDA.IDCOMUNE(+)                       = ISTANZE.IDCOMUNE
  AND AZIENDA.CODICEANAGRAFE(+)                 = ISTANZE.CODICETITOLARELEGALE
  AND STATIISTANZA.IDCOMUNE                     = ISTANZE.IDCOMUNE
  AND STATIISTANZA.SOFTWARE                     = ISTANZE.SOFTWARE
  AND STATIISTANZA.CODICESTATO                  = ISTANZE.CHIUSURA
  AND AMMINISTRAZIONI.IDCOMUNE(+)               = VW_BATCH_SCADENZARIO.IDCOMUNE
  AND AMMINISTRAZIONI.CODICEAMMINISTRAZIONE(+)  = VW_BATCH_SCADENZARIO.CODICEAMMINISTRAZIONE WITH READ ONLY;
 
ALTER TABLE TIPIMOV_STC_MAPPING ADD FLAG_CREAINVIA_ALLEGATI NUMBER(1,0);
ALTER TABLE TIPIMOV_STC_MAPPING ADD FLAG_ALLEGA_DOCUMENTI_ISTANZA NUMBER(1,0);
ALTER TABLE TIPIMOV_STC_MAPPING ADD FLAG_PROTOCOLLA NUMBER(1,0);
ALTER TABLE TIPIMOV_STC_MAPPING ADD PROTOCOLLO_FLUSSO VARCHAR2(1 CHAR);
ALTER TABLE TIPIMOV_STC_MAPPING ADD PROTOCOLLO_TIPODOCUMENTO VARCHAR2(10 CHAR);
ALTER TABLE TIPIMOV_STC_MAPPING ADD PROTOCOLLO_OGGETTO NUMBER(4,0);
ALTER TABLE TIPIMOV_STC_MAPPING ADD PROTOCOLLO_MITTENTE NUMBER(10,0);
ALTER TABLE TIPIMOV_STC_MAPPING ADD FLAG_NOTIFICA_AUTOMATICA NUMBER(1,0);


ALTER TABLE TIPIMOV_STC_MAPPING ADD CONSTRAINT FK_TIPIMOV_STC_MAP_TIPI_DOC FOREIGN KEY (IDCOMUNE,PROTOCOLLO_TIPODOCUMENTO) REFERENCES PROTOCOLLO_TIPIDOCUMENTO(IDCOMUNE,CODICE);
ALTER TABLE TIPIMOV_STC_MAPPING ADD CONSTRAINT FK_TIPIMOV_STC_MAP_PROT_FL FOREIGN KEY (PROTOCOLLO_FLUSSO ) REFERENCES PROTOCOLLO_FLUSSO(CODICE );
ALTER TABLE TIPIMOV_STC_MAPPING ADD CONSTRAINT FK_TIPIMOV_STC_MAP_AMMIN FOREIGN KEY (IDCOMUNE,PROTOCOLLO_MITTENTE) REFERENCES AMMINISTRAZIONI(IDCOMUNE,CODICEAMMINISTRAZIONE);
ALTER TABLE TIPIMOV_STC_MAPPING ADD CONSTRAINT FK_TIPIMOV_STC_MAP_MAIL_TIPO FOREIGN KEY (IDCOMUNE,PROTOCOLLO_OGGETTO) REFERENCES MAILTIPO(IDCOMUNE,CODICEMAIL);

CREATE TABLE ALBEROPROC_ARENDO (
  IDCOMUNE VARCHAR2(6) NOT NULL 
, ID NUMBER(10, 0) NOT NULL 
, FK_SCID NUMBER(10, 0) NOT NULL 
, FK_FAMIGLIAENDO NUMBER(10, 0) NOT NULL 
, FK_CATEGORIAENDO NUMBER(10, 0) 
, CONSTRAINT ALBEROPROC_ARENDO_PK PRIMARY KEY 
  (
    IDCOMUNE 
  , ID 
  )
);
ALTER TABLE ALBEROPROC_ARENDO ADD CONSTRAINT ALBEROPROC_ARENDO_ALBEROP_FK1 FOREIGN KEY
( IDCOMUNE , FK_SCID ) REFERENCES ALBEROPROC ( IDCOMUNE , SC_ID );

ALTER TABLE ALBEROPROC_ARENDO ADD CONSTRAINT ALBEROPROC_ARENDO_TIPIFAM_FK1 FOREIGN KEY
( IDCOMUNE , FK_FAMIGLIAENDO ) REFERENCES TIPIFAMIGLIEENDO ( IDCOMUNE , CODICE );

ALTER TABLE ALBEROPROC_ARENDO ADD CONSTRAINT ALBEROPROC_ARENDO_TIPIEND_FK1 FOREIGN KEY
( IDCOMUNE , FK_CATEGORIAENDO ) REFERENCES TIPIENDO ( IDCOMUNE , CODICE );

CREATE INDEX IDX_MOVIMENTI_006 ON MOVIMENTI (IDCOMUNE, TIPOMOVIMENTO);

CREATE INDEX IDX_COMUNI_PROVINCE002 ON COMUNI (SIGLAPROVINCIA, PROVINCIA);

ALTER TABLE MOVIMENTIALLEGATI MODIFY DESCRIZIONE VARCHAR2(4000 CHAR);
ALTER TABLE ISTANZEALLEGATI MODIFY ALLEGATOEXTRA VARCHAR2(4000 CHAR);

ALTER TABLE CLMENU_JAVA ADD LINK_STANDARD VARCHAR2(150 CHAR);
COMMENT ON COLUMN CLMENU_JAVA.LINK_STANDARD IS 'LINK DI ACCESSO ALLA FUNZIONALITÀ STANDARD';

ALTER TABLE CONFIGURAZIONE ADD CONSTRAINT FK_MAIL_AMMENDO_MAILTIPO FOREIGN KEY (IDCOMUNE,MAIL_AMMENDO) REFERENCES MAILTIPO(IDCOMUNE,CODICEMAIL);
ALTER TABLE CONFIGURAZIONE ADD CONSTRAINT FK_MAIL_MOVRIC_MAILTIPO FOREIGN KEY (IDCOMUNE,MAIL_MOVIRIC) REFERENCES MAILTIPO(IDCOMUNE,CODICEMAIL);
ALTER TABLE CONFIGURAZIONE ADD CONSTRAINT FK_MAIL_MOVAMM_MAILTIPO FOREIGN KEY (IDCOMUNE,MAIL_MOVIAMM) REFERENCES MAILTIPO(IDCOMUNE,CODICEMAIL);
ALTER TABLE CONFIGURAZIONE ADD CONSTRAINT FK_MAIL_MOVNEG_MAILTIPO FOREIGN KEY (IDCOMUNE,MAIL_MOVINEG) REFERENCES MAILTIPO(IDCOMUNE,CODICEMAIL);
CREATE INDEX IDX_ANAGRAFE_006 ON ANAGRAFE (IDCOMUNE, NOMINATIVO, NOME);
ALTER TABLE MOVIMENTI ADD CODICEAMMINISTRAZIONE_STC NUMBER(10,0); 
ALTER TABLE MOVIMENTI ADD CONSTRAINT FK_MOVIMENTI_AMM_STC FOREIGN KEY (IDCOMUNE, CODICEAMMINISTRAZIONE_STC) REFERENCES AMMINISTRAZIONI (IDCOMUNE, CODICEAMMINISTRAZIONE);

CREATE UNIQUE INDEX IDX_ALBEROPROC_ARENDO_001 ON ALBEROPROC_ARENDO(IDCOMUNE, FK_SCID, FK_FAMIGLIAENDO, FK_CATEGORIAENDO);
CREATE OR REPLACE VIEW VW_ISTANZE_OPE_RUOLI AS SELECT RR.IDCOMUNE, RR.IDRUOLO, RR.CODICERESPONSABILE, IR.CODICEISTANZA FROM RESPONSABILIRUOLI RR INNER JOIN  ISTANZERUOLI IR ON RR.IDCOMUNE=IR.IDCOMUNE AND  RR.IDRUOLO = IR.IDRUOLO;
