ALTER TABLE AREE MODIFY(CODICEAREA NUMBER(8));
ALTER TABLE AREEDETTAGLI MODIFY(CODICEAREA  NUMBER(8));
ALTER TABLE AREE2 MODIFY(CODICEAREA NUMBER(8));
ALTER TABLE CC_COEFFCONTRIBUTO MODIFY(FK_AREE_CODICEAREA NUMBER(8));
ALTER TABLE CC_ICALCOLO_DCONTRIBUTO MODIFY(FK_AREE_CODICEAREA NUMBER(8));
ALTER TABLE ISTANZE MODIFY(CODICEAREA NUMBER(8));
ALTER TABLE ISTANZE MODIFY(CODICEAREA2 NUMBER(8));
ALTER TABLE ISTANZEAREE MODIFY(CODICEAREA  NUMBER(8));
ALTER TABLE O_ICALCOLOCONTRIBT MODIFY(FK_AREE_CODICEAREA_ZTO NUMBER(8));
ALTER TABLE O_ICALCOLOCONTRIBT MODIFY(FK_AREE_CODICEAREA_PRG NUMBER(8));
CREATE INDEX IDX_AUTCONC_001 ON AUTORIZZAZIONI_CONCESSIONI(IDCOMUNE,FK_CODICEMERCATO,FK_IDPOSTEGGIO);
CREATE INDEX IDX_AUTCONC_002 ON AUTORIZZAZIONI_CONCESSIONI(IDCOMUNE,FK_CODICEMERCATO,FK_IDMERCATIUSO,FK_IDPOSTEGGIO);
CREATE INDEX IDX_AUTCONC_003 ON AUTORIZZAZIONI_CONCESSIONI(IDCOMUNE,FK_IDPOSTEGGIO);
ALTER TABLE TIPIMOV_STC_ALTRIDATI MODIFY NOME_CAMPO VARCHAR2(100 CHAR);
ALTER TABLE INVENTARIOPROCEDIMENTIPEOPLE ADD ID NUMBER(10,0);
ALTER TABLE TIPIMOV_STC_MAPPING ADD NONINVIAREPROCEDIMENTI NUMBER(1,0);
COMMENT ON COLUMN TIPIMOV_STC_MAPPING.NONINVIAREPROCEDIMENTI IS 'se true indica ad STC di non inoltrare i procedimenti al destinatario durante la notifica attività';
ALTER TABLE AMMINISTRAZIONI MODIFY EMAIL VARCHAR2(320 CHAR);
ALTER TABLE AMMINISTRAZIONI MODIFY PEC VARCHAR2(320 CHAR);
ALTER TABLE ANAGRAFE MODIFY EMAIL VARCHAR2(320 CHAR);
ALTER TABLE ANAGRAFE MODIFY PEC VARCHAR2(320 CHAR);
ALTER TABLE ANAGRAFESTORICO MODIFY EMAIL VARCHAR2(320 CHAR);
ALTER TABLE ANAGRAFESTORICO MODIFY PEC VARCHAR2(320 CHAR);
ALTER TABLE CDSINVITATI MODIFY (CODICEINVITATO NUMBER(6, 0) NULL);
ALTER TABLE ISTANZEEVENTI MODIFY DESCRIZIONE VARCHAR2(4000 CHAR);
CREATE TABLE FO_VISURA_CONTESTI_BASE 
(
  ID VARCHAR2(50 CHAR) NOT NULL 
, CONTESTO VARCHAR2(150 CHAR) NOT NULL 
, CONSTRAINT FO_VISURA_CONTESTI_BASE_PK PRIMARY KEY 
  (
    ID 
  )
);
CREATE TABLE FO_VISURA_CAMPI_BASE 
(
  ID VARCHAR2(50 CHAR) NOT NULL 
, CAMPO VARCHAR2(150 CHAR) NOT NULL 
, CONSTRAINT FO_VISURA_CAMPI_BASE_PK PRIMARY KEY 
  (
    ID 
  )
);
CREATE TABLE FO_VISURA_CONTESTI_CAMPI_BASE 
(
  FKIDCONTESTO VARCHAR2(50 CHAR) NOT NULL 
, FKIDCAMPO VARCHAR2(50 CHAR) NOT NULL 
, CONSTRAINT FO_VISURA_CONTESTI_CAMPI__PK PRIMARY KEY 
  (
    FKIDCONTESTO 
  , FKIDCAMPO 
  )
);
create TABLE FO_VISURA_CAMPI 
(
  IDCOMUNE VARCHAR2(6 CHAR) not null,
  SOFTWARE VARCHAR2(2 CHAR) not null,
  FKIDCONTESTO VARCHAR2(50 CHAR) NOT NULL 
, FKIDCAMPO VARCHAR2(50 CHAR) NOT NULL 
, POSIZIONE NUMBER(3) 
, CONSTRAINT FO_VISURA_CAMPI_PK PRIMARY KEY 
  (
    IDCOMUNE,
    SOFTWARE,
    FKIDCONTESTO,
    FKIDCAMPO 
  )
);
ALTER TABLE FO_VISURA_CONTESTI_CAMPI_BASE
ADD CONSTRAINT FO_VISURA_CONTESTI_CAMPI__FK1 FOREIGN KEY
(
  FKIDCAMPO 
)
REFERENCES FO_VISURA_CAMPI_BASE
(
  ID 
);
ALTER TABLE FO_VISURA_CONTESTI_CAMPI_BASE
ADD CONSTRAINT FO_VISURA_CONTESTI_CAMPI__FK2 FOREIGN KEY
(
  FKIDCONTESTO 
)
REFERENCES FO_VISURA_CONTESTI_BASE
(
  ID 
);
ALTER TABLE FO_VISURA_CAMPI
ADD CONSTRAINT FO_VISURA_CAMPI__FK1 FOREIGN KEY
(
  FKIDCAMPO 
)
REFERENCES FO_VISURA_CAMPI_BASE
(
  ID 
);
ALTER TABLE FO_VISURA_CAMPI
ADD CONSTRAINT FO_VISURA_CAMPI__FK2 FOREIGN KEY
(
  FKIDCONTESTO 
)
REFERENCES FO_VISURA_CONTESTI_BASE
(
  ID 
);
ALTER TABLE STILI ADD CONSTRAINT STILI_PK PRIMARY KEY (ST_ID);
ALTER TABLE INVENTARIOPROCEDIMENTIPEOPLE MODIFY COD_PROC_PEOPLE VARCHAR2(50 CHAR);