ALTER TABLE AREE MODIFY CODICEAREA NUMERIC(8);
ALTER TABLE AREEDETTAGLI MODIFY CODICEAREA  NUMERIC(8);
ALTER TABLE AREE2 MODIFY CODICEAREA NUMERIC(8);
ALTER TABLE CC_COEFFCONTRIBUTO MODIFY FK_AREE_CODICEAREA NUMERIC(8);
ALTER TABLE CC_ICALCOLO_DCONTRIBUTO MODIFY FK_AREE_CODICEAREA NUMERIC(8);
ALTER TABLE ISTANZE MODIFY CODICEAREA NUMERIC(8);
ALTER TABLE ISTANZE MODIFY CODICEAREA2 NUMERIC(8);
ALTER TABLE ISTANZEAREE MODIFY CODICEAREA  NUMERIC(8);
ALTER TABLE O_ICALCOLOCONTRIBT MODIFY FK_AREE_CODICEAREA_ZTO NUMERIC(8);
ALTER TABLE O_ICALCOLOCONTRIBT MODIFY FK_AREE_CODICEAREA_PRG NUMERIC(8);
CREATE INDEX IDX_AUTCONC_001 ON AUTORIZZAZIONI_CONCESSIONI(IDCOMUNE,FK_CODICEMERCATO,FK_IDPOSTEGGIO);
CREATE INDEX IDX_AUTCONC_002 ON AUTORIZZAZIONI_CONCESSIONI(IDCOMUNE,FK_CODICEMERCATO,FK_IDMERCATIUSO,FK_IDPOSTEGGIO);
CREATE INDEX IDX_AUTCONC_003 ON AUTORIZZAZIONI_CONCESSIONI(IDCOMUNE,FK_IDPOSTEGGIO);
CREATE OR REPLACE ALGORITHM=TEMPTABLE View VW_BATCH_SCADENZARIO as SELECT mdf.codicemovimento as id,sysdate() as dataelaborazione,mdf.idcomune as idcomune,istanze.software as software,mdf.codiceistanza as codiceistanza,mf.codicemovimento as codicemovimento,ifnull(mf.movimento, tmf.movimento) as descrmovimento,mdf.tipomovimento as tipomovimentodafare,ifnull(mdf.movimento, tm.movimento) as descrmovimentodafare,mdf.codiceinventario as codiceinventario,mdf.codiceamministrazione as CODICEAMMINISTRAZIONE,mdf.data_scadenza as datascadenza FROM  movimenti mdf INNER JOIN istanze ON istanze.idcomune       =mdf.idcomune AND istanze.codiceistanza =mdf.codiceistanza INNER JOIN tipimovimento tm ON tm.idcomune       =mdf.idcomune AND tm.tipomovimento =mdf.tipomovimento LEFT JOIN movimenti_contromovimenti mcm ON mcm.idcomune              =mdf.idcomune AND mcm.codicecontromovimento=mdf.codicemovimento LEFT JOIN movimenti mf ON mf.idcomune              =mcm.idcomune and mf.codicemovimento      =mcm.codicemovimento left join tipimovimento tmf on tmf.idcomune=mf.idcomune and  tmf.tipomovimento=mf.tipomovimento WHERE mdf.data  is  NULL and (mdf.flag_disabilitato  is  NULL or mdf.flag_disabilitato = 0);
ALTER TABLE TIPIMOV_STC_ALTRIDATI MODIFY NOME_CAMPO VARCHAR(100);
ALTER TABLE INVENTARIOPROCEDIMENTIPEOPLE ADD ID NUMERIC(10,0);
ALTER TABLE TIPIMOV_STC_MAPPING ADD NONINVIAREPROCEDIMENTI NUMERIC(1,0);
ALTER TABLE AMMINISTRAZIONI MODIFY EMAIL VARCHAR(320);
ALTER TABLE AMMINISTRAZIONI MODIFY PEC VARCHAR(320);
ALTER TABLE ANAGRAFE MODIFY EMAIL VARCHAR(320);
ALTER TABLE ANAGRAFE MODIFY PEC VARCHAR(320);
ALTER TABLE ANAGRAFESTORICO MODIFY EMAIL VARCHAR(320);
ALTER TABLE ANAGRAFESTORICO MODIFY PEC VARCHAR(320);
ALTER TABLE CDSINVITATI MODIFY CODICEINVITATO NUMERIC(6, 0) NULL;
ALTER TABLE ISTANZEEVENTI MODIFY DESCRIZIONE VARCHAR(4000);
CREATE TABLE FO_VISURA_CONTESTI_BASE 
(
  ID VARCHAR(50) NOT NULL 
, CONTESTO VARCHAR(150) NOT NULL 
, CONSTRAINT FO_VISURA_CONTESTI_BASE_PK PRIMARY KEY 
  (
    ID 
  )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE FO_VISURA_CAMPI_BASE 
(
  ID VARCHAR(50) NOT NULL 
, CAMPO VARCHAR(150) NOT NULL 
, CONSTRAINT FO_VISURA_CAMPI_BASE_PK PRIMARY KEY 
  (
    ID 
  )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE FO_VISURA_CONTESTI_CAMPI_BASE 
(
  FKIDCONTESTO VARCHAR(50) NOT NULL 
, FKIDCAMPO VARCHAR(50) NOT NULL 
, CONSTRAINT FO_VISURA_CONTESTI_CAMPI__PK PRIMARY KEY 
  (
    FKIDCONTESTO 
  , FKIDCAMPO 
  )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create TABLE FO_VISURA_CAMPI 
(
  IDCOMUNE varchar(6) not null,
  SOFTWARE varchar(2) not null,
  FKIDCONTESTO VARCHAR(50) NOT NULL 
, FKIDCAMPO VARCHAR(50) NOT NULL 
, POSIZIONE numeric(3) 
, CONSTRAINT FO_VISURA_CAMPI_PK PRIMARY KEY 
  (
    IDCOMUNE,
    SOFTWARE,
    FKIDCONTESTO,
    FKIDCAMPO 
  )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE FO_VISURA_CONTESTI_CAMPI_BASE ADD CONSTRAINT FO_VISURA_CONTESTI_CAMPI__FK1 FOREIGN KEY(FKIDCAMPO) REFERENCES FO_VISURA_CAMPI_BASE(ID);
ALTER TABLE FO_VISURA_CONTESTI_CAMPI_BASE ADD CONSTRAINT FO_VISURA_CONTESTI_CAMPI__FK2 FOREIGN KEY(FKIDCONTESTO) REFERENCES FO_VISURA_CONTESTI_BASE(ID);
ALTER TABLE FO_VISURA_CAMPI ADD CONSTRAINT FO_VISURA_CAMPI__FK1 FOREIGN KEY(FKIDCAMPO) REFERENCES FO_VISURA_CAMPI_BASE (ID);
ALTER TABLE FO_VISURA_CAMPI ADD CONSTRAINT FO_VISURA_CAMPI__FK2 FOREIGN KEY (FKIDCONTESTO) REFERENCES FO_VISURA_CONTESTI_BASE (ID);
ALTER TABLE STILI ADD CONSTRAINT STILI_PK PRIMARY KEY (ST_ID);
ALTER TABLE INVENTARIOPROCEDIMENTIPEOPLE MODIFY COD_PROC_PEOPLE VARCHAR(50);