CREATE TABLE PROTOCOLLO_TIPIDOC_METADATI 
(
  IDCOMUNE VARCHAR(6) NOT NULL 
, FKTIPODOCUMENTO NUMERIC(10,0) NOT NULL 
, CODICE_METADATO VARCHAR(50) NOT NULL 
, DESCRIZIONE_METADATO VARCHAR(500) NOT NULL 
   
) ENGINE=InnoDB DEFAULT CHARSET=utf8;;

ALTER TABLE PROTOCOLLO_TIPIDOC_METADATI ADD CONSTRAINT PROTOCOLLO_TIPIDOC_METADAT_PK PRIMARY KEY (IDCOMUNE, FKTIPODOCUMENTO, CODICE_METADATO);

ALTER TABLE PROTOCOLLO_TIPIDOC_METADATI ADD CONSTRAINT PROTOCOLLO_TIPIDOC_METADA_FK1 FOREIGN KEY (IDCOMUNE,FKTIPODOCUMENTO) REFERENCES PROTOCOLLO_TIPIDOCUMENTO (IDCOMUNE,ID);

ALTER TABLE ALBEROPROC MODIFY SC_CODICE VARCHAR(34);