
INSERT INTO PAY_CONNECTOR_CONFIG_PARAMS(CONFIG_PARAM,DESCRIZIONE,CODICE_CONNETTORE) VALUES ('SCHED_CARICAM_MASS_STRATEGIA','Parametro per la gestione del caricamento massivo delle posizioni debitorie: Indicare la Strategia (es. MIP ==> GENOVA_NEXI il connettore MIP può gestire tracciati NEXI GENOVA)',NULL);

INSERT INTO PAY_CONNECTOR_CONFIG_PARAMS(CONFIG_PARAM,DESCRIZIONE,CODICE_CONNETTORE) VALUES ('SCHED_CARICAM_MASS_ATTIVO','Parametro per la gestione del caricamento massivo delle posizioni debitorie: Se attivare o meno l''elaborazione. Indicare i valori true, false',NULL);

INSERT INTO PAY_CONNECTOR_CONFIG_PARAMS(CONFIG_PARAM,DESCRIZIONE,CODICE_CONNETTORE) VALUES ('SCHED_CARICAM_MASS_QUARTZEXP','Parametro per la gestione del caricamento massivo delle posizioni debitorie: L''espressione QUARTZ per indicare la tempistica di schedulazione',NULL);


INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES ('COMPORTAMENTI_MERCATI','CRIT_ORD_GRAD_MERC_PREDEFINITO','Indica il criterio di ordinamento da applicare alla funzionalità mostra graduatoria spuntisti nel caso <b>NON SIA</b> attivo il flag MERCATI_CONFIGURAZIONE#FLAG_ATTIVA_GRAD_SPUNTISTI. <br/>Se non impostato prende il seguente ordinamento <b>coalesce(nominativogerente,nominativo), coalesce(nomegerente,nome)</b>.<br/>Lista delle colonne disponibili:<p><b>id as idautorizzazione,  autorizdata,autoriznumero,codiceanagrafe,nominativo,nome,partitaiva,codicefiscale, dataiscrrea, dataregditte, sum(numeropresenze) as numpresenze, idcomune, autorizcodcomune, autorizcomune, autoriginnumero,  codiceGerente,  nominativogerente,  nomegerente,  partitaivagerente, codicefiscalegerente,autorizcomprov,autorizcomsiglaprov,protocolloaut,dataprotocolloaut,codicetitolare,nominativotitolare,nometitolare,partitaivatitolare,codicefiscaletitolare,dataiscrreatitolare,dataregdittetitolare</b></p>');

 
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES ('COMPORTAMENTI_MERCATI','CRIT_ORD_GRAD_MERC_SE_CFGSPUNT','Indica il criterio di ordinamento da applicare alla funzionalità mostra graduatoria spuntisti nel caso <b>SIA</b> attivo il flag MERCATI_CONFIGURAZIONE#FLAG_ATTIVA_GRAD_SPUNTISTI. <br/>Se non impostato prende il seguente ordinamento <b>numpresenze DESC, dataregditte ASC, autorizzazioni.data_anzianita ASC</b>.<br/>Lista delle colonne disponibili:<p><b>id as idautorizzazione,  autorizdata,autoriznumero,codiceanagrafe,nominativo,nome,partitaiva,codicefiscale, dataiscrrea, dataregditte, sum(numeropresenze) as numpresenze, idcomune, autorizcodcomune, autorizcomune, autoriginnumero,  codiceGerente,  nominativogerente,  nomegerente,  partitaivagerente, codicefiscalegerente,autorizcomprov,autorizcomsiglaprov,protocolloaut,dataprotocolloaut,codicetitolare,nominativotitolare,nometitolare,partitaivatitolare,codicefiscaletitolare,dataiscrreatitolare,dataregdittetitolare</b></p>');
