<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" id="InvioInfocameraResult">
	<xs:simpleType name="StringaObbligatoria">
		<xs:restriction base="xs:string">
			<xs:whiteSpace value="collapse"/>
			<xs:minLength value="1"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="esitoOKKOobb">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:whiteSpace value="collapse"/>
			<xs:enumeration value="OK"/>
			<xs:enumeration value="KO"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="servizioSincronoobb">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:whiteSpace value="collapse"/>
			<xs:enumeration value="Sincrono"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="risposta">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="header">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="servizio" type="servizioSincronoobb"/>
							<xs:element name="userid" type="StringaObbligatoria"/>
							<xs:element name="chiave_modello">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="codice_fiscale" type="xs:string" minOccurs="0" maxOccurs="1"/>
										<xs:element name="codice_modello" type="xs:string" minOccurs="0" maxOccurs="1"/>
										<xs:element name="chiave_interna_pratica" type="xs:string" minOccurs="0" maxOccurs="1"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="messaggio">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="esito" type="esitoOKKOobb"/>
							<xs:element name="errore" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="codice" type="xs:string" minOccurs="0"/>
										<xs:element name="descrizione" type="xs:string" minOccurs="0"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>
