<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://adrigate.lepida.it" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://adrigate.lepida.it" xmlns:intf="http://adrigate.lepida.it" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->

   <wsdl:message name="DettaglioCompletoImpresaRequest">

      <wsdl:part name="sgl_prv_sede" type="xsd:string">

      </wsdl:part>

      <wsdl:part name="n_rea_sede" type="xsd:string">

      </wsdl:part>

      <wsdl:part name="switch_control" type="xsd:string">

      </wsdl:part>

      <wsdl:part name="user" type="xsd:string">

      </wsdl:part>

      <wsdl:part name="password" type="xsd:string">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="RicercaImpreseNReaResponse">

      <wsdl:part name="RicercaImpreseNReaReturn" type="xsd:string">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="DettaglioImpresaNReaRequest">

      <wsdl:part name="sgl_prv_sede" type="xsd:string">

      </wsdl:part>

      <wsdl:part name="n_rea_sede" type="xsd:string">

      </wsdl:part>

      <wsdl:part name="switch_control" type="xsd:string">

      </wsdl:part>

      <wsdl:part name="user" type="xsd:string">

      </wsdl:part>

      <wsdl:part name="password" type="xsd:string">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="DettaglioRidottoImpresaRequest">

      <wsdl:part name="sgl_prv_sede" type="xsd:string">

      </wsdl:part>

      <wsdl:part name="n_rea_sede" type="xsd:string">

      </wsdl:part>

      <wsdl:part name="switch_control" type="xsd:string">

      </wsdl:part>

      <wsdl:part name="user" type="xsd:string">

      </wsdl:part>

      <wsdl:part name="password" type="xsd:string">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="DettaglioPersoneConCaricaRequest">

      <wsdl:part name="fk_pri_cciaa_regz" type="xsd:string">

      </wsdl:part>

      <wsdl:part name="fk_pri_n_rea" type="xsd:string">

      </wsdl:part>

      <wsdl:part name="switch_control" type="xsd:string">

      </wsdl:part>

      <wsdl:part name="user" type="xsd:string">

      </wsdl:part>

      <wsdl:part name="password" type="xsd:string">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="RicercaImpreseNonCessatePerDenominazioneRequest">

      <wsdl:part name="denominazione_sede" type="xsd:string">

      </wsdl:part>

      <wsdl:part name="switch_control" type="xsd:string">

      </wsdl:part>

      <wsdl:part name="user" type="xsd:string">

      </wsdl:part>

      <wsdl:part name="password" type="xsd:string">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="DettaglioRidottoImpresaResponse">

      <wsdl:part name="DettaglioRidottoImpresaReturn" type="xsd:string">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="RicercaImpreseNonCessatePerCodiceFiscaleResponse">

      <wsdl:part name="RicercaImpreseNonCessatePerCodiceFiscaleReturn" type="xsd:string">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="RicercaImpresePerDenominazioneResponse">

      <wsdl:part name="RicercaImpresePerDenominazioneReturn" type="xsd:string">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="RicercaImpresePerDenominazioneRequest">

      <wsdl:part name="denominazione_sede" type="xsd:string">

      </wsdl:part>

      <wsdl:part name="switch_control" type="xsd:string">

      </wsdl:part>

      <wsdl:part name="user" type="xsd:string">

      </wsdl:part>

      <wsdl:part name="password" type="xsd:string">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="RicercaImpresePerCodiceFiscaleRequest">

      <wsdl:part name="codice_fiscale" type="xsd:string">

      </wsdl:part>

      <wsdl:part name="switch_control" type="xsd:string">

      </wsdl:part>

      <wsdl:part name="user" type="xsd:string">

      </wsdl:part>

      <wsdl:part name="password" type="xsd:string">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="RicercaImpresePerCodiceFiscaleResponse">

      <wsdl:part name="RicercaImpresePerCodiceFiscaleReturn" type="xsd:string">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="RicercaImpreseNReaRequest">

      <wsdl:part name="sgl_prv_sede" type="xsd:string">

      </wsdl:part>

      <wsdl:part name="n_rea_sede" type="xsd:string">

      </wsdl:part>

      <wsdl:part name="switch_control" type="xsd:string">

      </wsdl:part>

      <wsdl:part name="user" type="xsd:string">

      </wsdl:part>

      <wsdl:part name="password" type="xsd:string">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="DettaglioImpresaNReaResponse">

      <wsdl:part name="DettaglioImpresaNReaReturn" type="xsd:string">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="RicercaImpreseNonCessatePerDenominazioneResponse">

      <wsdl:part name="RicercaImpreseNonCessatePerDenominazioneReturn" type="xsd:string">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="DettaglioPersoneConCaricaResponse">

      <wsdl:part name="DettaglioPersoneConCaricaReturn" type="xsd:string">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="DettaglioCompletoImpresaResponse">

      <wsdl:part name="DettaglioCompletoImpresaReturn" type="xsd:string">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="RicercaImpreseNonCessatePerCodiceFiscaleRequest">

      <wsdl:part name="codice_fiscale" type="xsd:string">

      </wsdl:part>

      <wsdl:part name="switch_control" type="xsd:string">

      </wsdl:part>

      <wsdl:part name="user" type="xsd:string">

      </wsdl:part>

      <wsdl:part name="password" type="xsd:string">

      </wsdl:part>

   </wsdl:message>

   <wsdl:portType name="RicercaImprese">

      <wsdl:operation name="DettaglioPersoneConCarica" parameterOrder="fk_pri_cciaa_regz fk_pri_n_rea switch_control user password">

         <wsdl:input message="impl:DettaglioPersoneConCaricaRequest" name="DettaglioPersoneConCaricaRequest">

       </wsdl:input>

         <wsdl:output message="impl:DettaglioPersoneConCaricaResponse" name="DettaglioPersoneConCaricaResponse">

       </wsdl:output>

      </wsdl:operation>

      <wsdl:operation name="RicercaImpresePerCodiceFiscale" parameterOrder="codice_fiscale switch_control user password">

         <wsdl:input message="impl:RicercaImpresePerCodiceFiscaleRequest" name="RicercaImpresePerCodiceFiscaleRequest">

       </wsdl:input>

         <wsdl:output message="impl:RicercaImpresePerCodiceFiscaleResponse" name="RicercaImpresePerCodiceFiscaleResponse">

       </wsdl:output>

      </wsdl:operation>

      <wsdl:operation name="RicercaImpresePerDenominazione" parameterOrder="denominazione_sede switch_control user password">

         <wsdl:input message="impl:RicercaImpresePerDenominazioneRequest" name="RicercaImpresePerDenominazioneRequest">

       </wsdl:input>

         <wsdl:output message="impl:RicercaImpresePerDenominazioneResponse" name="RicercaImpresePerDenominazioneResponse">

       </wsdl:output>

      </wsdl:operation>

      <wsdl:operation name="DettaglioImpresaNRea" parameterOrder="sgl_prv_sede n_rea_sede switch_control user password">

         <wsdl:input message="impl:DettaglioImpresaNReaRequest" name="DettaglioImpresaNReaRequest">

       </wsdl:input>

         <wsdl:output message="impl:DettaglioImpresaNReaResponse" name="DettaglioImpresaNReaResponse">

       </wsdl:output>

      </wsdl:operation>

      <wsdl:operation name="DettaglioRidottoImpresa" parameterOrder="sgl_prv_sede n_rea_sede switch_control user password">

         <wsdl:input message="impl:DettaglioRidottoImpresaRequest" name="DettaglioRidottoImpresaRequest">

       </wsdl:input>

         <wsdl:output message="impl:DettaglioRidottoImpresaResponse" name="DettaglioRidottoImpresaResponse">

       </wsdl:output>

      </wsdl:operation>

      <wsdl:operation name="DettaglioCompletoImpresa" parameterOrder="sgl_prv_sede n_rea_sede switch_control user password">

         <wsdl:input message="impl:DettaglioCompletoImpresaRequest" name="DettaglioCompletoImpresaRequest">

       </wsdl:input>

         <wsdl:output message="impl:DettaglioCompletoImpresaResponse" name="DettaglioCompletoImpresaResponse">

       </wsdl:output>

      </wsdl:operation>

      <wsdl:operation name="RicercaImpreseNRea" parameterOrder="sgl_prv_sede n_rea_sede switch_control user password">

         <wsdl:input message="impl:RicercaImpreseNReaRequest" name="RicercaImpreseNReaRequest">

       </wsdl:input>

         <wsdl:output message="impl:RicercaImpreseNReaResponse" name="RicercaImpreseNReaResponse">

       </wsdl:output>

      </wsdl:operation>

      <wsdl:operation name="RicercaImpreseNonCessatePerCodiceFiscale" parameterOrder="codice_fiscale switch_control user password">

         <wsdl:input message="impl:RicercaImpreseNonCessatePerCodiceFiscaleRequest" name="RicercaImpreseNonCessatePerCodiceFiscaleRequest">

       </wsdl:input>

         <wsdl:output message="impl:RicercaImpreseNonCessatePerCodiceFiscaleResponse" name="RicercaImpreseNonCessatePerCodiceFiscaleResponse">

       </wsdl:output>

      </wsdl:operation>

      <wsdl:operation name="RicercaImpreseNonCessatePerDenominazione" parameterOrder="denominazione_sede switch_control user password">

         <wsdl:input message="impl:RicercaImpreseNonCessatePerDenominazioneRequest" name="RicercaImpreseNonCessatePerDenominazioneRequest">

       </wsdl:input>

         <wsdl:output message="impl:RicercaImpreseNonCessatePerDenominazioneResponse" name="RicercaImpreseNonCessatePerDenominazioneResponse">

       </wsdl:output>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="RicercaImpreseSoapBinding" type="impl:RicercaImprese">

      <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="DettaglioPersoneConCarica">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="DettaglioPersoneConCaricaRequest">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://adrigate.lepida.it" use="encoded"/>

         </wsdl:input>

         <wsdl:output name="DettaglioPersoneConCaricaResponse">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://adrigate.lepida.it" use="encoded"/>

         </wsdl:output>

      </wsdl:operation>

      <wsdl:operation name="RicercaImpresePerCodiceFiscale">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="RicercaImpresePerCodiceFiscaleRequest">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://adrigate.lepida.it" use="encoded"/>

         </wsdl:input>

         <wsdl:output name="RicercaImpresePerCodiceFiscaleResponse">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://adrigate.lepida.it" use="encoded"/>

         </wsdl:output>

      </wsdl:operation>

      <wsdl:operation name="RicercaImpresePerDenominazione">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="RicercaImpresePerDenominazioneRequest">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://adrigate.lepida.it" use="encoded"/>

         </wsdl:input>

         <wsdl:output name="RicercaImpresePerDenominazioneResponse">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://adrigate.lepida.it" use="encoded"/>

         </wsdl:output>

      </wsdl:operation>

      <wsdl:operation name="DettaglioImpresaNRea">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="DettaglioImpresaNReaRequest">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://adrigate.lepida.it" use="encoded"/>

         </wsdl:input>

         <wsdl:output name="DettaglioImpresaNReaResponse">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://adrigate.lepida.it" use="encoded"/>

         </wsdl:output>

      </wsdl:operation>

      <wsdl:operation name="DettaglioRidottoImpresa">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="DettaglioRidottoImpresaRequest">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://adrigate.lepida.it" use="encoded"/>

         </wsdl:input>

         <wsdl:output name="DettaglioRidottoImpresaResponse">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://adrigate.lepida.it" use="encoded"/>

         </wsdl:output>

      </wsdl:operation>

      <wsdl:operation name="DettaglioCompletoImpresa">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="DettaglioCompletoImpresaRequest">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://adrigate.lepida.it" use="encoded"/>

         </wsdl:input>

         <wsdl:output name="DettaglioCompletoImpresaResponse">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://adrigate.lepida.it" use="encoded"/>

         </wsdl:output>

      </wsdl:operation>

      <wsdl:operation name="RicercaImpreseNRea">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="RicercaImpreseNReaRequest">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://adrigate.lepida.it" use="encoded"/>

         </wsdl:input>

         <wsdl:output name="RicercaImpreseNReaResponse">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://adrigate.lepida.it" use="encoded"/>

         </wsdl:output>

      </wsdl:operation>

      <wsdl:operation name="RicercaImpreseNonCessatePerCodiceFiscale">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="RicercaImpreseNonCessatePerCodiceFiscaleRequest">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://adrigate.lepida.it" use="encoded"/>

         </wsdl:input>

         <wsdl:output name="RicercaImpreseNonCessatePerCodiceFiscaleResponse">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://adrigate.lepida.it" use="encoded"/>

         </wsdl:output>

      </wsdl:operation>

      <wsdl:operation name="RicercaImpreseNonCessatePerDenominazione">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="RicercaImpreseNonCessatePerDenominazioneRequest">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://adrigate.lepida.it" use="encoded"/>

         </wsdl:input>

         <wsdl:output name="RicercaImpreseNonCessatePerDenominazioneResponse">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://adrigate.lepida.it" use="encoded"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="RicercaImpreseService">

      <wsdl:port binding="impl:RicercaImpreseSoapBinding" name="RicercaImprese">

         <wsdlsoap:address location="https://adrier.lepida.it/AdriGate/services/RicercaImprese"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
