<definitions name="PddServiceEnte" targetNamespace="http://www.impresainungiorno.gov.it/suap/scrivania" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.impresainungiorno.gov.it/suap/scrivania" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<types>
		<xs:schema targetNamespace="http://www.impresainungiorno.gov.it/suap/scrivania" version="1.0" xmlns:ns1="http://www.impresainungiorno.gov.it/schema/suap/ente" xmlns:tns="http://www.impresainungiorno.gov.it/suap/scrivania" xmlns:xs="http://www.w3.org/2001/XMLSchema">
			<xs:import namespace="http://www.impresainungiorno.gov.it/schema/suap/ente" schemaLocation="SUAP-ente-1.1.1.xsd"/>
			<xs:element name="inviaSUAPEnte" type="tns:inviaSUAPEnte"/>
			<xs:element name="inviaSUAPEnteResponse" type="tns:inviaSUAPEnteResponse"/>
			<xs:complexType name="inviaSUAPEnte">
				<xs:sequence>
					<xs:element name="CooperazioneSUAPEnte" type="ns1:CooperazioneSUAPEnte"/>
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="inviaSUAPEnteResponse">
				<xs:sequence>
					<xs:element name="return" type="xs:string"/>
				</xs:sequence>
			</xs:complexType>
		</xs:schema>
	</types>
	<message name="PddServiceEnte_inviaSUAPEnte">
		<part element="tns:inviaSUAPEnte" name="inviaSUAPEnte"/>
	</message>
	<message name="PddServiceEnte_inviaSUAPEnteResponse">
		<part element="tns:inviaSUAPEnteResponse" name="inviaSUAPEnteResponse"/>
	</message>
	<portType name="PddServiceEnte">
		<operation name="inviaSUAPEnte" parameterOrder="inviaSUAPEnte">
			<input message="tns:PddServiceEnte_inviaSUAPEnte"/>
			<output message="tns:PddServiceEnte_inviaSUAPEnteResponse"/>
		</operation>
	</portType>
	<binding name="PddServiceEnteBinding" type="tns:PddServiceEnte">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="inviaSUAPEnte">
			<soap:operation soapAction="inviaSUAPEnte"/>
			<input>
				<soap:body use="literal"/>
			</input>
			<output>
				<soap:body use="literal"/>
			</output>
		</operation>
	</binding>
	<service name="PddServiceEnte">
		<port binding="tns:PddServiceEnteBinding" name="PddPortEnte">
			<soap:address location="http://127.0.0.1:8080/bosuap/pddServiceEnte"/>
		</port>
	</service>
</definitions>