ALTER TABLE METADATI_DIZ_BASE ADD CONTESTO VARCHAR(1);

create table CFG_METADATI_CMIS (
IDCOMUNE varchar(6) not null,
FK_METADATO_BASE varchar(30) not null,
MAPPING_CMIS varchar(100) not null
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

alter table CFG_METADATI_CMIS add constraint PK_CFG_METADATI_CMIS primary key (IDCOMUNE,FK_METADATO_BASE);
alter table CFG_METADATI_CMIS add constraint FK_CFGMETACMIS_DIZBASE FOREIGN key (FK_METADATO_BASE) REFERENCES METADATI_DIZ_BASE (ID);

ALTER TABLE CFG_METADATI_CMIS ADD TIPO_DATO_CMIS varchar(20);

ALTER TABLE ANAGRAFESTORICO ADD FK_CODICERESPONSABILE NUMERIC(8,0);
ALTER TABLE ANAGRAFESTORICO ADD CONSTRAINT FK_ANAGRAFE_STORICO_RESPONS FOREIGN KEY (IDCOMUNE,FK_CODICERESPONSABILE) REFERENCES RESPONSABILI(IDCOMUNE,CODICERESPONSABILE);

ALTER TABLE ALBEROPROC ADD(INIZIO_VALIDITA datetime);
ALTER TABLE ALBEROPROC ADD(FINE_VALIDITA datetime);

ALTER TABLE STRADARIO ADD COMUNE_LOCALIZZAZIONE VARCHAR(5);

ALTER TABLE STRADARIO ADD CONSTRAINT FK_STRADARIO_COMUNE_LOCALIZZ FOREIGN KEY (COMUNE_LOCALIZZAZIONE) REFERENCES COMUNI(CODICECOMUNE);

CREATE TABLE CONF_APPLICATIVE(
	IDCOMUNE VARCHAR(6) NOT NULL,
	CHIAVE   VARCHAR(50) NOT NULL,
	VALORE   VARCHAR(200)
)  ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE CONF_APPLICATIVE ADD CONSTRAINT PK_CONF_APPLICATIVE PRIMARY KEY (IDCOMUNE, CHIAVE);