alter table COMMISSIONIEDILIZIE_T modify NUMPROTOCOLLO VARCHAR2(60 CHAR) ;

ALTER TABLE FO_CONFIGURAZIONEBASE ADD IDRISORSA VARCHAR2(50 CHAR) NULL;
UPDATE FO_CONFIGURAZIONEBASE SET IDRISORSA = 'visura.' || REPLACE(REPLACE(REPLACE(LOWER(ETICHETTA),' ','_'),'.',''),'°','') WHERE IDRISORSA IS NULL;
ALTER TABLE FO_CONFIGURAZIONEBASE MODIFY IDRISORSA VARCHAR2(50 CHAR) NOT NULL;

ALTER TABLE PAY_PROFILI_ENTI_CREDITORI MODIFY CODICEAMMINISTRAZIONE NUMBER(10,0) NULL;

ALTER TABLE COMMEDILIZIE_ALLEGATI DROP CONSTRAINT FK_COMM_ALLEGATI_COMM_EDILT;
ALTER TABLE COMMEDILIZIE_APPELLO DROP CONSTRAINT FK_COMM_APP_COMMEDIL_T;
ALTER TABLE COMMEDILIZIE_CONVOCAZIONI DROP CONSTRAINT FK_COMM_CONV_COMMEDIL_T;
ALTER TABLE COMMEDILIZIE_MASSIVE_T DROP CONSTRAINT FK_COMMEDMASST_COMMEDT;
ALTER TABLE COMMEDILIZIE_VOTAZIONI DROP CONSTRAINT FK_VOTAZIONI_COMMISSIONE;
ALTER TABLE COMMISSIONI_EDILIZIE_LOG DROP CONSTRAINT FK_CMEDLZ_LOG_CMEDLZ_T;
ALTER TABLE COMMISSIONIEDILIZIE_R DROP CONSTRAINT FK_COMM_EDIL_COMMEDIL_T;


ALTER TABLE COMMEDILIZIE_ALLEGATI MODIFY CODICECOMMISSIONE NUMBER(10,0);
ALTER TABLE COMMEDILIZIE_APPELLO MODIFY CODICECOMMISSIONE NUMBER(10,0);
ALTER TABLE COMMEDILIZIE_CONVOCAZIONI MODIFY CODICECOMMISSIONE NUMBER(10,0);
ALTER TABLE COMMEDILIZIE_MASSIVE_T MODIFY FKID_COMMEDT_ID NUMBER(10,0);
ALTER TABLE COMMEDILIZIE_VOTAZIONI MODIFY CODICECOMMISSIONE NUMBER(10,0);
ALTER TABLE COMMISSIONIEDILIZIE_R MODIFY CODICECOMMISSIONE NUMBER(10,0);

ALTER TABLE COMMISSIONIEDILIZIE_T MODIFY CODICECOMMISSIONE NUMBER(10,0) ;


ALTER TABLE COMMEDILIZIE_ALLEGATI ADD CONSTRAINT FK_COMM_ALLEGATI_COMM_EDILT FOREIGN KEY (IDCOMUNE,CODICECOMMISSIONE) REFERENCES COMMISSIONIEDILIZIE_T(IDCOMUNE,CODICECOMMISSIONE); 
ALTER TABLE COMMEDILIZIE_APPELLO ADD CONSTRAINT FK_COMM_APP_COMMEDIL_T  FOREIGN KEY (IDCOMUNE,CODICECOMMISSIONE) REFERENCES COMMISSIONIEDILIZIE_T(IDCOMUNE,CODICECOMMISSIONE); 
ALTER TABLE COMMEDILIZIE_CONVOCAZIONI ADD CONSTRAINT FK_COMM_CONV_COMMEDIL_T FOREIGN KEY  (IDCOMUNE,CODICECOMMISSIONE) REFERENCES COMMISSIONIEDILIZIE_T(IDCOMUNE,CODICECOMMISSIONE); 
ALTER TABLE COMMEDILIZIE_MASSIVE_T ADD CONSTRAINT FK_COMMEDMASST_COMMEDT FOREIGN KEY  (IDCOMUNE,FKID_COMMEDT_ID) REFERENCES COMMISSIONIEDILIZIE_T(IDCOMUNE,CODICECOMMISSIONE); 
ALTER TABLE COMMEDILIZIE_VOTAZIONI ADD CONSTRAINT FK_VOTAZIONI_COMMISSIONE  FOREIGN KEY (IDCOMUNE,CODICECOMMISSIONE) REFERENCES COMMISSIONIEDILIZIE_T(IDCOMUNE,CODICECOMMISSIONE); 
ALTER TABLE COMMISSIONI_EDILIZIE_LOG ADD CONSTRAINT FK_CMEDLZ_LOG_CMEDLZ_T  FOREIGN KEY (IDCOMUNE,FK_COMMISSIONE) REFERENCES COMMISSIONIEDILIZIE_T(IDCOMUNE,CODICECOMMISSIONE); 
ALTER TABLE COMMISSIONIEDILIZIE_R ADD CONSTRAINT FK_COMM_EDIL_COMMEDIL_T  FOREIGN KEY (IDCOMUNE,CODICECOMMISSIONE) REFERENCES COMMISSIONIEDILIZIE_T(IDCOMUNE,CODICECOMMISSIONE); 

