ALTER TABLE domandestc MODIFY richiedente VARCHAR2(150);

alter table MERCATI_CONFIGURAZIONE add SEGNA_PRESENZA_SPUNT_NO_POST number(1,0);

ALTER TABLE GRUPPI_ISTRUTTORI_RESP DROP CONSTRAINT FK_GRP_ISTRUTTOR_ISTRUTT;

ALTER TABLE GRUPPI_ISTRUTTORI_RESP ADD CONSTRAINT FK_GRP_ISTRUTTOR_ISTRUTT FOREIGN KEY (IDCOMUNE, FK_GRP_ISTRUTTORI) REFERENCES GRUPPI_ISTRUTTORI (IDCOMUNE, ID);


ALTER TABLE GRUPPI_ISTRUTTORI_RESP DROP CONSTRAINT FK_GRP_ISTRUTTOR_RESP; 

ALTER TABLE GRUPPI_ISTRUTTORI_RESP ADD CONSTRAINT FK_GRP_ISTRUTTOR_RESP FOREIGN KEY (IDCOMUNE, FK_RESPOSABILE) REFERENCES RESPONSABILI (IDCOMUNE, CODICERESPONSABILE);

ALTER TABLE MOVIMENTI ADD ID_ATT_DEST VARCHAR2(250 CHAR);

ALTER TABLE MOVIMENTI ADD STATO_ATT_DEST VARCHAR2(250 CHAR);

ALTER TABLE AMMINISTRAZIONI MODIFY AMMINISTRAZIONE VARCHAR2(255);


CREATE TABLE ALLEGATI_DOC_SOGG_FIRMATARI (
  IDCOMUNE                  VARCHAR2(6) NOT NULL,
  ID                      NUMBER(10,0)     NOT NULL,
  FK_TIPO_SOGGETTO        NUMBER(10,0)     NOT NULL,
  FK_ALLEGATI_ID          NUMBER(10,0)     NOT NULL
);

ALTER TABLE ALLEGATI_DOC_SOGG_FIRMATARI
  ADD CONSTRAINT ALLEGATI_DOC_SOGG_FIRM_PK PRIMARY KEY (
    IDCOMUNE,
    ID
  );

ALTER TABLE ALLEGATI_DOC_SOGG_FIRMATARI
  ADD CONSTRAINT FK_SOGG_FIRM_ALLEGATI FOREIGN KEY (
    IDCOMUNE,
    FK_ALLEGATI_ID
  ) REFERENCES ALLEGATI (
    IDCOMUNE,
    ID
  );

ALTER TABLE ALLEGATI_DOC_SOGG_FIRMATARI
  ADD CONSTRAINT FK_ALL_SOGG_FIRM_TIPO_SOGG FOREIGN KEY (
    IDCOMUNE,
    FK_TIPO_SOGGETTO
  ) REFERENCES TIPISOGGETTO (
    IDCOMUNE,
    CODICETIPOSOGGETTO
  );

  
ALTER TABLE TIPOLOGIAREGISTRI add CODICECOMUNE VARCHAR2(5);
ALTER TABLE TIPOLOGIAREGISTRI ADD ( CONSTRAINT FK_TIPOLOGIAREGISTRI_COMUNI FOREIGN KEY (CODICECOMUNE) REFERENCES COMUNI(CODICECOMUNE));

ALTER TABLE GRADUATORIET_COM ADD FLG_TRASFORMA_PDF NUMBER(1,0);