UPDATE CLMENU_JAVA SET TIPO_FUNZIONALITA = 'S' WHERE ID IN ( 941, 942, 965, 967 );
UPDATE CLMENU_JAVA SET MENULINK_V2 = '0AJ' WHERE ID = 918;
UPDATE CLMENU_JAVA SET MENULINK_V2 = '0AJ1' WHERE ID = 783;
UPDATE CLMENU_JAVA SET MENULINK_V2 = '0AJ2' WHERE ID = 782;
UPDATE CLMENU_JAVA SET MENULINK_V2 = '0AJ3' WHERE ID = 781;
UPDATE CLMENU_JAVA SET MENULINK_V2 = '0AJ4' WHERE ID = 784;
UPDATE CLMENU_JAVA SET MENULINK_V2 = '0AJ5' WHERE ID = 951;
UPDATE CLMENU_JAVA SET MENULINK_V2 = '0AJ6' WHERE ID = 1042;
UPDATE CLMENU_JAVA SET MENULINK_V2 = '0AJ7' WHERE ID = 1045;


INSERT INTO VERTICALIZZAZIONIBASE(MODULO,DESCRIZIONE,FLAG_GESTCOMUNE) VALUES ('ABBONAMENTO_POSTEGGI','Permette la gestione degli abbonamenti sui posteggi dei mercati tramite borsellino elettronico che può essere collegato o meno con l''integrazione NODO_PAGAMENTI',1);
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES ('ABBONAMENTO_POSTEGGI','COMPORTAMENTO','Definisce vari comportamenti derivati dall''associare / presentare il borsellino legato direttamente agli operatori o ad un sottoinsieme di autorizzazioni/concessioni; valori ammessi: AUTORIZZAZIONI o OPERATORE');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES ('ABBONAMENTO_POSTEGGI','RIPARTIZIONE_CONTI_RICARICHE','Il parametro che va configurato indica la ripartizione dei conti/percentuale che verranno usati per creare una ricarica dell''abbonamento. Il parametro va inserito in questo formato <br />
<b>IDCONTO|PERCENTUALE;IDCONTO|PERCENTUALE</b><br />esempio: <b>1|65;2|35</b>
<br />dove<br />
1=conto COSAP<br />
65 la percentuale di ripartizione della ricarica per conto COSAP<br />
2=conto TARI<br />
35 la percentuale di ripartizione della ricarica per conto TARI<br />
<br />Con  <b>|</b> separatore conto/percentuale e <b>;</b> separatore nuovo conto.<br /> In questo modo è possibile sia configurare un solo conto (es 1|100) che più di due.<br/>
Quindi se la ricarica fosse di 10&euro; con questa configurazione <b>1|65;2|35</b><br/>6,5 € andrebbero nel conto COSAP<br/>3,5 € andrebbero nel conto TARI');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES ('ABBONAMENTO_POSTEGGI','SOGLIA_AVVISO','Indica l''importo minimo sotto il quale attivare l''avviso all''interno della Web App usata dai vigili');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES ('ABBONAMENTO_POSTEGGI','BLOCCA_ASSEGNAZIONE','Decide se bloccare l''assegnazione del posteggio in caso di credito insufficiente nel borsellino; valori ammessi 0 o vuoto se non deve bloccare, 1 se deve bloccare');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES ('ABBONAMENTO_POSTEGGI','STRATEGIA_INVIO_COMUNICAZIONI','Decide se comunicare le movimentazioni alla chiusura della giornata. Valori ammessi: NESSUNA (Non vengono inviate comunicazioni), CHIUSURA_GIORNATA (Vengono inviate alla chiusura della giornata). Se non impostato vale CHIUSURA_GIORNATA');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES ('WS_ATTI','MOV_PRECOMPILA_DOC_AUT','Indicare uno o più movimenti (separati con una virgola) che verranno utilizzati per precompilare gli allegati da passare al gestionale atti esterno');


INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES ('ABBONAMENTO_POSTEGGI','MESSAGGIO_CREDITO_SOTTO_SOGLIA','
Il messaggio per indicare l''avviso di credito sotto soglia. E'' possibile specificare le seguenti variabili.
<ul><li>#SOGLIA_AVVISO# il valore della soglia configurata nella regola sotto la quale mostrare l''avviso.
</li><li>#NUMERO_AUTORIZZAZIONE# Il numero dell''autorizzazione/concessione per il quale è generato l''avviso </li><li>#DATA_AUTORIZZAZIONE# La Data dell''autorizzazione/concessione per il quale è generato l''avviso </ul> <br/>Se non specificato il messaggio predefinito è ''L''autorizzazione ha attivato un abbonamento ma il suo credito è sotto la soglia configurata''');
INSERT INTO CLMENU_JAVA(ID,DESCRIZIONE,PAGINA,MENULINK,SOFTWARE,JSP,LINK_STANDARD,TIPO_FUNZIONALITA,MENULINK_V2) VALUES (1054,'Gestione abbonamenti','abbonamentoposteggi/list.htm?software=TT','00F','TT','JAVA','abbonamentoposteggi/list.htm?software=TT','S','00F');

UPDATE CLMENU_JAVA SET MENULINK = '73' WHERE ID = 1054;
UPDATE CLMENU_JAVA SET MENULINK = '00G', MENULINK_V2 = '00G' WHERE ID = 1007;
UPDATE CLMENU_JAVA SET MENULINK = '73', MENULINK_V2 = '73' WHERE ID = 1054;

INSERT INTO CLMENU_JAVA(ID,DESCRIZIONE,PAGINA,MENULINK,SOFTWARE,JSP,LINK_STANDARD,TIPO_FUNZIONALITA,MENULINK_V2) VALUES (1055,'Abbonamenti','abbonamenticonfig/view.htm?software=TT','00F','TT','JAVA','abbonamenticonfig/view.htm?software=TT','S','00F');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES ('ABBONAMENTO_POSTEGGI','COMUNICAZIONI_DESCRIZIONE','Contiene il nome che verrà assegnato alla comunicazione e che verrà visualizzato nel backend. E'' possibile indicare un testo fisso oppure utilizzare anche il segnaposto [-GIORNATA-] che riporterà la data di svolgimento nel formato dd/mm/yyyy. Se non impostato, viene riportato il seguente testo "Chiusura giornata [-GIORNATA-]"');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES ('ABBONAMENTO_POSTEGGI','COMUNICAZIONI_DESTINATARI','Valori possibili: SOLO_PEC, PEC_O_MAIL, SOLO_MAIL. Serve ad indicare al componente se le comunicazioni verranno inviate alla mail del destinatario (SOLO_MAIL) oppure alla pec del destinatario (SOLO_PEC) oppure all''indirizzo PEC e se non presente alla mail semplice del destinatario (PEC_O_MAIL). Se non impostato assume il valore di default PEC_O_MAIL');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES ('ABBONAMENTO_POSTEGGI','COMUNICAZIONI_MAIL_SENDER','Indicare il codice dell''account da utilizzare per inviare le email. E'' possibile reperire questo codice andando nella configurazione dei parametri mail del proprio modulo di competenza ( oppure in quello generico ) -> cliccare sul dettaglio dell''account da utilizzare e leggere nella barra degli indirizzi il numero indicato dopo "codice=". Se non impostato, non verrà inviata nessuna mail ( in alcuni casi potrebbe essere il protocollo ad inviare le email al destinatario a fronte della protocollazione ) (SE CONFIGURATO, VA INDICATO ANCHE IL PARAMETRO COMUNICAZIONI_MAIL_TEMPLATE)');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES ('ABBONAMENTO_POSTEGGI','COMUNICAZIONI_MAIL_TEMPLATE','Indicare il codice della mail tipo da utilizzare come oggetto/corpo della mail. Sarà possibile utilizzare solamente i segnaposti relativi alla sezione "Comunicazioni massive delle manifestazioni" (OBBLIGATORIO SE CONFIGURATO IL PARAMETRO COMUNICAZIONI_MAIL_SENDER)');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES ('ABBONAMENTO_POSTEGGI','COMUNICAZIONI_MAIL_ESCLUSIONI','Valori possibili 0 o 1. Se impostato a 0 o non valorizzato, il sistema includerà tra i destinatari della comunicazione anche quelli sprovvisti di recapito mail o pec; impostato a 1 il sistema NON includerà i destinatari sprovvisti di recapito mail o pec. Per default non ci sono esclusioni in modo da poter eventualmente integrare la mail/pec mancante ed inviargli successivamente la comunicazione in qualsiasi momento');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES ('ABBONAMENTO_POSTEGGI','COMUNICAZIONI_PROT_TEMPLATE','Indicare il codice del testo tipo da utilizzare come oggetto del protocollo o non impostare se non si desidera protocollare la comunicazione. Sarà possibile utilizzare solamente i segnaposti relativi alla sezione "Comunicazioni massive delle manifestazioni". L''attivazione di questo parametro rende obbligatori gli altri parametri per la protocollazione a seconda del protocollo integrato');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES ('ABBONAMENTO_POSTEGGI','COMUNICAZIONI_PROT_CLASSIFICA','Indicare il titolario su cui verranno effettuate le protocollazioni in uscita per le comunicazioni. (OBBLIGATORIO SE CONFIGURATO IL PARAMETRO COMUNICAZIONI_PROTOCOLLO_TEMPLATE)');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES ('ABBONAMENTO_POSTEGGI','COMUNICAZIONI_PROT_TIPODOC','Indicare il codice che, nel protocollo, indica il tipo di documento che si sta protocollando (PEC,COMUNICAZIONE,....) in uscita.  (OBBLIGATORIO SE CONFIGURATO IL PARAMETRO COMUNICAZIONI_PROTOCOLLO_TEMPLATE E PREVISTO DAL PROPRIO PROTOCOLLO)');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES ('ABBONAMENTO_POSTEGGI','COMUNICAZIONI_PROT_UFFICIO','Indicare il codice dell''amministrazione di backend, censita anche nel protocollo, con cui verranno effettuate le protocollazioni in uscita per le comunicazioni. (OBBLIGATORIO SE CONFIGURATO IL PARAMETRO COMUNICAZIONI_PROTOCOLLO_TEMPLATE)');

INSERT INTO VERTICALIZZAZIONIBASE(MODULO,DESCRIZIONE,FLAG_GESTCOMUNE) VALUES ('ANAGRAFE_VERIFICA_MAIL','La verticalizzazione permette di attivare il comportamento di verifica della mail associata ad una anagrafe. Viene usata ad esempio nell''app degli ambulanti per usare le funzionalità di abbonamento. All''utente viene richiesto di certificare la mail seguendo la procedura che prevede l''invio di un codice di verifica sulla mail indicata',1);
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('ANAGRAFE_VERIFICA_MAIL', 'VERIFICAMAIL_MAIL_TIPO', 'Questo parametro specifica la mail tipo che verrà usata per inviare il codice di verifica. I segnaposto usabili delle mail tipo sono quelli specificati con contesto ANAGRAFE ');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('ANAGRAFE_VERIFICA_MAIL', 'VERIFICAMAIL_ACCOUNTID', 'Questo parametro specifica l''identificativo dell''account mail usato per inviare le mail (Tabella MAIL_CONFIG.ID)');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES ('PROTOCOLLO_ACARIS','TIPO_FASCICOLAZIONE','Valori ammessi: FascicolazioneStandardService o FascicolazioneSuDossierService. Nel primo caso si segue la fascicolazione classica, cioè quando si fascicola un''istanza viene creato un nuovo fascicolo e le altre protocollazioni ( movimenti, autorizzazioni, ... ) vengono attaccate al fascicolo dell''istanza. Nel secondo caso ogni fascicolazione recupera il dossier in base all''azienda della pratica ( se non esiste lo crea ), recupera il fascicolo con descrizione indicata nel parametro obbligatorio DESCRIZIONE_FASCICOLO ( se non esiste lo crea ) e tutti i protocolli vengono legati a quel fascicolo. Se non impostato equivale a FascicolazioneStandardService');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES ('PROTOCOLLO_ACARIS','DESCRIZIONE_FASCICOLO','(OBBLIGATORIO se TIPO_FASCICOLAZIONE=FascicolazioneStandardService). Questa descrizione viene usata per ricercare il fascicolo ed eventualmente per crearlo se non trovata');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES ('PROTOCOLLO_ACARIS','SERIE_DOSSIER','(OBBLIGATORIO se TIPO_FASCICOLAZIONE=FascicolazioneStandardService). E'' il codice della serie di dossier sotto il quale effettuare la ricerca del dossier dell''azienda');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES ('PROTOCOLLO_ACARIS','TEMPLATE_DESCRIZIONE_DOSSIER','Contiene la descrizione da utilizzare per la creazione/ricerca di un dossier. E'' possibile utilizzare i segnaposti configurati nella sezione Gestione Metadati Contesti per l''ambito PROTOCOLLO_ACARIS');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES ('PROTOCOLLO_ACARIS','CODICE_DOSSIER_MIN','Indicare il numero minimo della sequenza da poter utilizzare come codice Dossier');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES ('PROTOCOLLO_ACARIS','CODICE_DOSSIER_MAX','Indicare il numero minimo della sequenza da poter utilizzare come codice Dossier');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES ('PROTOCOLLO_ACARIS','CODICE_DOSSIER_LENGTH','Indica la lunghezza del codice Dossier. Se la lunghezza del valore della sequenza è inferiore al parametro, verrà completata inserendo tanti 0 a sinistra quanti sono i caratteri mancanti per raggiunger questa lunghezza');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES ('PROTOCOLLO_ACARIS','URL_AUTENTICAZIONE','Url del servizio di autenticazione in grado di rilasciare un token applicativo OAUTH2');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES ('PROTOCOLLO_ACARIS','CONSUMER_KEY','Consumer KEY del servizio di autenticazione');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES ('PROTOCOLLO_ACARIS','CONSUMER_SECRET','Consumer secret del servizio di autenticazione');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES ('PROTOCOLLO_ACARIS','URL_BACKOFFICE_SERVICES','Url dei servizi che consentono di ottenere informazioni sulle entità utilizzate nel modulo back office di ACTA che gestisce la struttura organizzativa degli utenti che sono abilitati all’utilizzo del repository');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES ('PROTOCOLLO_ACARIS','URL_REPOSITORY_SERVICES','Url dei servizi ACTA che consentono di recuperare informazioni quali i repository disponibili, i metadati dell''ente, le configurazioni applicative');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES ('PROTOCOLLO_ACARIS','URL_OBJECT_SERVICES','Url dei servizi ACTA che offrono operazioni CRUD per l’oggetto coinvolto identificato dal proprio ID (object ID)');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES ('PROTOCOLLO_ACARIS','URL_NAVIGATION_SERVICES','Url dei servizi ACTA in cui sono definiti servizi di navigazione della gerarchia di oggetti del repository ');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES ('PROTOCOLLO_ACARIS','URL_RELATIONSHIP_SERVICES','Url dei servizi ACTA in aggiunta a quelli presenti tra i Navigation Services, che permette la navigazione dei legami tra oggetti');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES ('PROTOCOLLO_ACARIS','URL_DOCUMENT_SERVICES','Url dei servizi ACTA  appositamente creati per riunificare, in ottica di ottimizzazione, alcune delle operazioni di navigazione e creazione previste per la gestione del documento');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES ('PROTOCOLLO_ACARIS','URL_MANAGEMENT_SERVICES','Url dei servizi ACTA che permettono di operare su oggetti del modello concettuale di ACTA ed in aggiunta su entità di business non direttamente sotto il controllo di tale modello ma comunque necessarie per l''ERMS');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES ('PROTOCOLLO_ACARIS','URL_OFFICIALBOOK_SERVICES','Url dei servizi ACTA che mettono a disposizione un insieme di servizi per interagire con oggetti propri del modulo di gestione della protocollazione: creazione delle registrazioni di protocollo, navigazione dei legami tra gli oggetti del modulo e di recupero del dettaglio delle singole entità.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES ('PROTOCOLLO_ACARIS','TIPO_FASCICOLO','Può assumere uno dei seguenti valori: ANNUALE o LIBERO ed indica la tipologia di fascicolo che verrà gestita da VBG. Di default è LIBERO');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES ('PROTOCOLLO_ACARIS','APPLICATIVO_ALIMENTANTE','Permette di impostare, durante la trasmissione di ogni allegato, una proprietà testuale chiamata Applicativo Alimentante.');

INSERT INTO clmenu_java (ID, DESCRIZIONE, PAGINA, MENULINK, SOFTWARE, JSP, VERTICALIZZAZIONE, SOFTWAREESCLUSI, LINK_STANDARD, TIPO_FUNZIONALITA, LAYOUTTESTI, MENULINK_V2) VALUES(1056, 'Configurazione APP.IO', 'appioserviziconfig/list.htm?software=SOFTWARE', '786', '*', 'JAVA', NULL, 'PR,FI', 'appioserviziconfig/list.htm?software=SOFTWARE', 'S', NULL, '786');