ALTER TABLE commedilizie_votazioni ADD voto_fo NUMBER(1) DEFAULT 0 NOT NULL;


UPDATE COMMEDILIZIE_VOTAZIONI SET PRESENTE = 0 WHERE PRESENTE = NULL;
ALTER TABLE COMMEDILIZIE_VOTAZIONI MODIFY PRESENTE NUMBER(1,0) NOT NULL;
