CREATE TABLE PENTAHOCFG(
IDCOMUNE VARCHAR(6) NOT NULL,
IDENTEBASE VARCHAR(6) NULL,
IDMAILTIPO NUMERIC(4,0) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE PENTAHOCFG ADD CONSTRAINT PK_PENTAHOCFG PRIMARY KEY (IDCOMUNE);
ALTER TABLE PENTAHOCFG ADD CONSTRAINT FK_PENTAHOCFG_MAILTIPO FOREIGN KEY (IDCOMUNE,IDMAILTIPO) REFERENCES MAILTIPO(IDCOMUNE,CODICEMAIL);

CREATE TABLE TIPICONTESTOESPORTAZIONE(
CODICE VARCHAR(15) NOT NULL,
DESCRIZIONE VARCHAR(30) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE TIPICONTESTOESPORTAZIONE ADD CONSTRAINT PK_TIPICONTESTOESPORTAZIONE PRIMARY KEY (CODICE);

CREATE TABLE ESPORTAZIONI(
IDCOMUNE VARCHAR(6) NOT NULL,
ID NUMERIC(8,0) NOT NULL,
DESCRIZIONE VARCHAR(100) NOT NULL,
FK_TIPICONTESTOESP_CODICE VARCHAR(15) NOT NULL,
TRASFORMAZIONE VARCHAR(50) NOT NULL,
FLG_ABILITATA NUMERIC(1,0) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE ESPORTAZIONI ADD CONSTRAINT PK_ESPORTAZIONI PRIMARY KEY (IDCOMUNE,ID);
ALTER TABLE ESPORTAZIONI ADD CONSTRAINT  FK_ESPORTAZIONI_TIPOCONT_EXP FOREIGN KEY (FK_TIPICONTESTOESP_CODICE) REFERENCES TIPICONTESTOESPORTAZIONE(CODICE);

CREATE TABLE PARAMETRIESPORTAZIONE(
IDCOMUNE VARCHAR(6) NOT NULL,
ID NUMERIC(8,0) NOT NULL,
FK_ESPORTAZIONE NUMERIC(8,0) NOT NULL,
PARAMETRO VARCHAR(25) NOT NULL,
DESCRIZIONE VARCHAR(50)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE PARAMETRIESPORTAZIONE ADD CONSTRAINT PK_PARAMETRIESPORTAZIONE PRIMARY KEY (IDCOMUNE,ID);

ALTER TABLE PARAMETRIESPORTAZIONE ADD CONSTRAINT  FK_PARAMETRIEXP_EXP FOREIGN KEY (IDCOMUNE,FK_ESPORTAZIONE) REFERENCES ESPORTAZIONI(IDCOMUNE,ID);

ALTER TABLE ISTANZEDELETE DROP PRIMARY KEY;
ALTER TABLE ISTANZEDELETE ADD CONSTRAINT ISTANZEDELETE_PK PRIMARY KEY (IDCOMUNE, ID);

CREATE TABLE TMP_ESPORTAZIONI(
ID NUMERIC(10,0) NOT NULL,
IDCOMUNE VARCHAR(6) NOT NULL,
SESSIONID VARCHAR(60) NOT NULL,
CODICE NUMERIC(10,0) NOT NULL,
CODICECOMUNE VARCHAR(5) NOT NULL,
DATA DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE TMP_ESPORTAZIONI ADD CONSTRAINT PK_TMP_ESPORTAZIONI PRIMARY KEY (ID);

ALTER TABLE TEMP_LINKALLEGATI ADD NOMEDOCUMENTO VARCHAR(4000);

CREATE OR REPLACE VIEW VW_ISTANZEDYN2_DATI AS 
SELECT
ISTANZEDYN2DATI.IDCOMUNE, ISTANZEDYN2DATI.CODICEISTANZA, ISTANZEDYN2MODELLIT.FK_D2MT_ID AS IDMODELLO, 
 DYN2_MODELLID.POSVERTICALE, DYN2_MODELLID.POSORIZZONTALE, NULL AS TIPOTESTO, NULL AS TESTO, 
 ISTANZEDYN2DATI.INDICE, DYN2_CAMPI.ID AS IDCAMPO, DYN2_CAMPI.NOMECAMPO, ISTANZEDYN2DATI.VALORE 
FROM 
 DYN2_CAMPI
   LEFT JOIN ISTANZEDYN2DATI ON DYN2_CAMPI.IDCOMUNE = ISTANZEDYN2DATI.IDCOMUNE AND DYN2_CAMPI.ID = ISTANZEDYN2DATI.FK_D2C_ID
   INNER JOIN DYN2_MODELLID ON DYN2_MODELLID.IDCOMUNE = DYN2_CAMPI.IDCOMUNE AND DYN2_MODELLID.FK_D2C_ID = DYN2_CAMPI.ID
   INNER JOIN DYN2_MODELLIT ON DYN2_MODELLIT.IDCOMUNE = DYN2_MODELLID.IDCOMUNE AND DYN2_MODELLIT.ID = DYN2_MODELLID.FK_D2MT_ID 
   LEFT JOIN ISTANZEDYN2MODELLIT ON ISTANZEDYN2DATI.IDCOMUNE = ISTANZEDYN2MODELLIT.IDCOMUNE AND ISTANZEDYN2DATI.CODICEISTANZA = ISTANZEDYN2MODELLIT.CODICEISTANZA AND DYN2_MODELLIT.ID = ISTANZEDYN2MODELLIT.FK_D2MT_ID 
ORDER BY
  ISTANZEDYN2MODELLIT.IDCOMUNE, ISTANZEDYN2MODELLIT.CODICEISTANZA, ISTANZEDYN2MODELLIT.FK_D2MT_ID,
  DYN2_MODELLID.POSVERTICALE, DYN2_MODELLID.POSORIZZONTALE;
  
ALTER TABLE PROTOCOLLO_TIPIDOCUMENTO MODIFY CODICE VARCHAR(50);

ALTER TABLE ARCHIVIAZIONI_ISTANZE ADD ERRORE LONGTEXT;
ALTER TABLE ARCHIVIAZIONI_ISTANZE ADD ESCLUSA NUMERIC(1,0);

ALTER TABLE ISTANZE MODIFY FKIDPROTOCOLLO VARCHAR(30);
ALTER TABLE MOVIMENTI MODIFY FKIDPROTOCOLLO VARCHAR(30);
ALTER TABLE PEC_INBOX MODIFY IDPROTOCOLLO VARCHAR(30);

CREATE OR REPLACE ALGORITHM=MERGE VIEW VW_I_ATTIVITAINFORMAZIONI AS 
SELECT
  I_ATTIVITA.ID                  AS I_IDATTIVITA,
  ISTANZEATTIVITA.CODICEISTANZA  AS CODICEISTANZA,
  ISTANZEATTIVITA.CODICEATTIVITA AS CODICEATTIVITA,
  ISTANZEATTIVITA.METRIQ         AS METRIQ,
  ISTANZEATTIVITA.NOTE           AS NOTE,
  ISTANZEATTIVITA.IDCOMUNE       AS IDCOMUNE,
  ISTANZEATTIVITA.SOFTWARE       AS SOFTWARE,
  ISTANZEATTIVITA.IDATTIVITA     AS IDATTIVITA,
  SETTORI.CODICESETTORE          AS CODICESETTORE,
  SETTORI.SETTORE                AS SETTORE
FROM 
  I_ATTIVITA
    INNER JOIN ISTANZEATTIVITA ON I_ATTIVITA.IDCOMUNE = ISTANZEATTIVITA.IDCOMUNE AND I_ATTIVITA.CODICEISTANZAULTIMA = ISTANZEATTIVITA.CODICEISTANZA
    INNER JOIN ATTIVITA ON ISTANZEATTIVITA.IDCOMUNE = ATTIVITA.IDCOMUNE AND ISTANZEATTIVITA.CODICEATTIVITA = ATTIVITA.CODICEISTAT
    INNER JOIN SETTORI ON ATTIVITA.IDCOMUNE = SETTORI.IDCOMUNE AND ATTIVITA.CODICESETTORE = SETTORI.CODICESETTORE;
