ALTER TABLE ALBEROPROC_ARENDO MODIFY IDCOMUNE VARCHAR(6)COLLATE utf8_general_ci;

ALTER TABLE TIPIMOVIMENTO ADD FKSTATOISTANZA VARCHAR(2);
 
ALTER TABLE TIPIMOVIMENTO ADD CONSTRAINT FK_TIPIMOV_STATIISTANZA FOREIGN KEY (IDCOMUNE,SOFTWARE,FKSTATOISTANZA) REFERENCES STATIISTANZA(IDCOMUNE,SOFTWARE,CODICESTATO);

CREATE TABLE ISTANZEPROCURE (ID NUMERIC(10,0) NOT NULL,IDCOMUNE VARCHAR(6) NOT NULL,CODICEISTANZA NUMERIC(6,0),FK_ANAG_PROC NUMERIC(6,0),FK_ANAG_PROC_STORICO NUMERIC(6,0),FK_ANAG_RAPP NUMERIC(6,0),FK_ANAG_RAPP_STORICO NUMERIC(6,0),CODICEOGGETTOPROCURA NUMERIC(10,0),STC_ID_ALLEGATO VARCHAR(200),STC_ID_DOCUMENTO VARCHAR(200)) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE ISTANZEPROCURE ADD CONSTRAINT PK_ISTANZEPROCURE PRIMARY KEY (IDCOMUNE, ID);
ALTER TABLE ISTANZEPROCURE ADD CONSTRAINT FK_ISTPROC_ISTANZE FOREIGN KEY (IDCOMUNE, CODICEISTANZA) REFERENCES ISTANZE(IDCOMUNE, CODICEISTANZA);
ALTER TABLE ISTANZEPROCURE ADD CONSTRAINT FK_ISTPROC_ANPROC FOREIGN KEY (IDCOMUNE, FK_ANAG_PROC) REFERENCES ANAGRAFE(IDCOMUNE, CODICEANAGRAFE);
ALTER TABLE ISTANZEPROCURE ADD CONSTRAINT FK_ISTPROC_ANPROCST FOREIGN KEY (IDCOMUNE, FK_ANAG_PROC_STORICO) REFERENCES ANAGRAFESTORICO(IDCOMUNE, ID);
ALTER TABLE ISTANZEPROCURE ADD CONSTRAINT FK_ISTPROC_ANRAP FOREIGN KEY (IDCOMUNE, FK_ANAG_RAPP) REFERENCES ANAGRAFE(IDCOMUNE, CODICEANAGRAFE);
ALTER TABLE ISTANZEPROCURE ADD CONSTRAINT FK_ISTPROC_ANRAPST FOREIGN KEY (IDCOMUNE, FK_ANAG_RAPP_STORICO) REFERENCES ANAGRAFESTORICO(IDCOMUNE, ID);
ALTER TABLE ISTANZEPROCURE ADD CONSTRAINT FK_ISTPROC_OGGETTI FOREIGN KEY (IDCOMUNE, CODICEOGGETTOPROCURA) REFERENCES OGGETTI(IDCOMUNE, CODICEOGGETTO);

CREATE OR REPLACE ALGORITHM=TEMPTABLE VIEW VW_ISTANZE_OPE_RUOLI (IDCOMUNE, IDRUOLO, CODICERESPONSABILE, CODICEISTANZA) AS SELECT RR.IDCOMUNE,RR.IDRUOLO,RR.CODICERESPONSABILE,IR.CODICEISTANZA FROM RESPONSABILIRUOLI RR INNER JOIN ISTANZERUOLI IR on rr.idcomune =ir.idcomune and rr.idruolo = ir.idruolo inner join ruoli r ON r.idcomune=ir.idcomune and r.id =ir.idruolo AND (r.readonly=0 OR (r.flag_gestmovimenti=1 OR r.flag_disgestmovamm =1));

ALTER TABLE INVENTARIOPROCEDIMENTIONERI ADD NOTE VARCHAR(500);
ALTER TABLE ALBEROPROC_ONERI ADD NOTE VARCHAR(500);

CREATE TABLE RESPONSABILI_TM_SCA (IDCOMUNE VARCHAR(6) NOT NULL,CODICERESPONSABILE NUMERIC(4,0) NOT NULL,TIPOMOVIMENTO VARCHAR(8) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE RESPONSABILI_TM_SCA ADD CONSTRAINT PK_RESP_TM_SCA PRIMARY KEY (IDCOMUNE,CODICERESPONSABILE,TIPOMOVIMENTO);
ALTER TABLE RESPONSABILI_TM_SCA ADD CONSTRAINT FK_RESPTMSCA_RESP FOREIGN KEY(IDCOMUNE,CODICERESPONSABILE) REFERENCES RESPONSABILI(IDCOMUNE,CODICERESPONSABILE);
ALTER TABLE RESPONSABILI_TM_SCA ADD CONSTRAINT FK_RESPTMSCA_TIPIMOV FOREIGN KEY(IDCOMUNE,TIPOMOVIMENTO) REFERENCES TIPIMOVIMENTO(IDCOMUNE,TIPOMOVIMENTO);

CREATE TABLE RESPONSABILI_TM_AVV (IDCOMUNE VARCHAR(6) NOT NULL,CODICERESPONSABILE NUMERIC(4,0) NOT NULL,TIPOMOVIMENTO VARCHAR(8) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8;;

ALTER TABLE RESPONSABILI_TM_AVV ADD CONSTRAINT PK_RESP_TM_AVV PRIMARY KEY (IDCOMUNE,CODICERESPONSABILE,TIPOMOVIMENTO);
ALTER TABLE RESPONSABILI_TM_AVV ADD CONSTRAINT FK_RESPTMAVV_RESP FOREIGN KEY(IDCOMUNE,CODICERESPONSABILE) REFERENCES RESPONSABILI(IDCOMUNE,CODICERESPONSABILE);
ALTER TABLE RESPONSABILI_TM_AVV ADD CONSTRAINT FK_RESPTMAVV_TIPIMOV FOREIGN KEY(IDCOMUNE,TIPOMOVIMENTO) REFERENCES TIPIMOVIMENTO(IDCOMUNE,TIPOMOVIMENTO);

ALTER TABLE TIPIMOVIMENTO ADD FLAG_DISDAVISIONARE NUMERIC(1,0);

CREATE OR REPLACE ALGORITHM=TEMPTABLE VIEW VW_I_ATTIVITAINFORMAZIONI AS SELECT I_ATTIVITA.ID as I_IDATTIVITA, ISTANZEATTIVITA.CODICEISTANZA, ISTANZEATTIVITA.CODICEATTIVITA, ISTANZEATTIVITA.METRIQ, ISTANZEATTIVITA.NOTE, ISTANZEATTIVITA.IDCOMUNE, ISTANZEATTIVITA.SOFTWARE, ISTANZEATTIVITA.IDATTIVITA, SETTORI.CODICESETTORE, SETTORI.SETTORE FROM I_ATTIVITA, ISTANZEATTIVITA, ATTIVITA, SETTORI WHERE SETTORI.IDCOMUNE = ATTIVITA.IDCOMUNE AND SETTORI.CODICESETTORE = ATTIVITA.CODICESETTORE AND ATTIVITA.IDCOMUNE = ISTANZEATTIVITA.IDCOMUNE AND ATTIVITA.CODICEISTAT = ISTANZEATTIVITA.CODICEATTIVITA AND ISTANZEATTIVITA.IDCOMUNE = I_ATTIVITA.IDCOMUNE AND ISTANZEATTIVITA.CODICEISTANZA = I_ATTIVITA.CODICEISTANZAULTIMA;

ALTER table ISTANZE ADD CONSTRAINT FK_ISTANZE_ATTIVITA FOREIGN KEY (IDCOMUNE,FK_IDI_ATTIVITA) REFERENCES I_ATTIVITA (IDCOMUNE, ID);

ALTER TABLE STATIISTANZA ADD CONSTRAINT FK_STATI_COMPORTAMENTO FOREIGN KEY (FKCODCOMPORTAMENTO) REFERENCES STATICOMPORTAMENTO (CODCOMPORTAMENTO);
CREATE INDEX IDX_STATIISTANZA_001 ON STATIISTANZA (FKCODCOMPORTAMENTO);

ALTER TABLE ISTANZE MODIFY NUMEROISTANZA VARCHAR(60);
ALTER TABLE DOMANDESTC MODIFY NUMEROISTANZA VARCHAR(60);
ALTER TABLE DOMANDESTC MODIFY ID_DOMANDAMITT VARCHAR(60);

ALTER TABLE ISTANZE ADD DOMICILIO_ELETTRONICO VARCHAR(320);

CREATE OR REPLACE ALGORITHM=TEMPTABLE VIEW VW_I_ATTIVITAENDO AS SELECT I_ATTIVITA.IDCOMUNE, I_ATTIVITA.ID AS I_IDATTIVITA, ISTANZEPROCEDIMENTI.CODICEISTANZA, TIPIFAMIGLIEENDO.CODICE AS CODICEFAMIGLIA, TIPIFAMIGLIEENDO.TIPO AS FAMIGLIA, TIPIENDO.CODICE AS CODICETIPO, TIPIENDO.TIPO, ISTANZEPROCEDIMENTI.CODICEINVENTARIO, INVENTARIOPROCEDIMENTI.PROCEDIMENTO, ISTANZEPROCEDIMENTI.PERPROVVEDIMENTO, ISTANZEPROCEDIMENTI.ACQUISITO, ISTANZEPROCEDIMENTI.DATAATTIVAZIONE, ISTANZEPROCEDIMENTI.NOTE FROM I_ATTIVITA, ISTANZE, ISTANZEPROCEDIMENTI, ((INVENTARIOPROCEDIMENTI LEFT OUTER JOIN TIPIENDO ON INVENTARIOPROCEDIMENTI.IDCOMUNE = TIPIENDO.IDCOMUNE AND INVENTARIOPROCEDIMENTI.CODICETIPO = TIPIENDO.CODICE ) LEFT OUTER JOIN TIPIFAMIGLIEENDO ON TIPIENDO.IDCOMUNE = TIPIFAMIGLIEENDO.IDCOMUNE AND TIPIENDO.CODICEFAMIGLIAENDO = TIPIFAMIGLIEENDO.CODICE ) WHERE INVENTARIOPROCEDIMENTI.IDCOMUNE = ISTANZEPROCEDIMENTI.IDCOMUNE AND INVENTARIOPROCEDIMENTI.CODICEINVENTARIO = ISTANZEPROCEDIMENTI.CODICEINVENTARIO AND ISTANZEPROCEDIMENTI.IDCOMUNE = ISTANZE.IDCOMUNE AND ISTANZEPROCEDIMENTI.CODICEISTANZA = ISTANZE.CODICEISTANZA AND ISTANZE.IDCOMUNE = I_ATTIVITA.IDCOMUNE AND ISTANZE.FK_IDI_ATTIVITA = I_ATTIVITA.ID;

ALTER TABLE RESPONSABILI ADD FLAG_CANCELLAISTANZE NUMERIC(1,0);

ALTER TABLE RESPONSABILI ADD FLAG_CANCELLADOCUMENTISTC NUMERIC(1,0);

ALTER TABLE TIPIMOV_STC_MAPPING ADD FLAG_INVIASCHEDEISTANZA NUMERIC(1,0);

CREATE OR REPLACE ALGORITHM=TEMPTABLE VIEW VW_ISTANZECONCESSIONIPREC_TMP AS SELECT IDCOMUNE, CONC_ID, MAX(DATA_STORICO) AS DATA_STORICO FROM VW_ISTANZECONCESSIONILISTA WHERE PROGRESSIVO < 99999999 GROUP BY IDCOMUNE, CONC_ID;

CREATE OR REPLACE ALGORITHM=TEMPTABLE VIEW VW_ISTANZECONCESSIONIPREC AS 
SELECT  
  VW_ISTANZECONCESSIONILISTA.IDCOMUNE, VW_ISTANZECONCESSIONILISTA.CONC_ID, VW_ISTANZECONCESSIONILISTA.DATA_STORICO, MAX(PROGRESSIVO) AS PROGRESSIVO 
FROM  
  VW_ISTANZECONCESSIONILISTA, VW_ISTANZECONCESSIONIPREC_TMP 
WHERE  
 VW_ISTANZECONCESSIONILISTA.IDCOMUNE = VW_ISTANZECONCESSIONIPREC_TMP.IDCOMUNE AND 
 VW_ISTANZECONCESSIONILISTA.CONC_ID = VW_ISTANZECONCESSIONIPREC_TMP.CONC_ID AND 
 VW_ISTANZECONCESSIONILISTA.DATA_STORICO = VW_ISTANZECONCESSIONIPREC_TMP.DATA_STORICO AND 
 VW_ISTANZECONCESSIONILISTA.PROGRESSIVO < 99999999  
GROUP BY  
 VW_ISTANZECONCESSIONILISTA.IDCOMUNE, VW_ISTANZECONCESSIONILISTA.CONC_ID, VW_ISTANZECONCESSIONILISTA.DATA_STORICO;

CREATE OR REPLACE ALGORITHM=TEMPTABLE VIEW VW_ISTANZECONCESSIONILISTA as

SELECT 99999999 AS PROGRESSIVO, AUTORIZZAZIONI.AUTORIZRESPONSABILE AS CONC_AUTORIZRESPONSABILE, AUTORIZZAZIONI.IDCOMUNE, AUTORIZZAZIONI.FK_CAUSALE_ACQUISIZIONE AS ICONC_CODICECAUSALE, IFNULL(AUTORIZZAZIONI.DATA_CESSAZIONE,STR_TO_DATE('31/12/9999','%d/%m/%Y')) AS DATA_STORICO, ISTANZE.SOFTWARE, ISTANZE.CODICEISTANZA AS IST_CODICEISTANZA, ISTANZE.NUMEROISTANZA AS IST_NUMEROISTANZA, ISTANZE.CODICERICHIEDENTE AS IST_CODICERICHIEDENTE, ISTANZE.CODICETITOLARELEGALE AS IST_CODICETITOLARELEGALE, AUTORIZZAZIONI.ID AS CONC_ID, AUTORIZZAZIONI.AUTORIZNUMERO AS CONC_NUMERO, AUTORIZZAZIONI.AUTORIZDATA AS CONC_DATARILASCIO, AUTORIZZAZIONI.AUTORIZDATA AS DATARILASCIO, AUTORIZZAZIONI.DATASCADENZA AS CONC_DATASCADENZA, AUTORIZZAZIONI_CONCESSIONI.FK_TIPOCONCESSIONE AS CONC_CODICETIPO, CONCESSIONITIPI.DESCRIZIONE AS CONC_TIPO, AUTORIZZAZIONI_CONCESSIONI.STAGIONALEA AS CONC_STAGIONALEA, AUTORIZZAZIONI_CONCESSIONI.STAGIONALEDA AS CONC_STAGIONALEDA, AUTORIZZAZIONI.FLAG_ATTIVA AS CONC_ATTIVA, AUTORIZZAZIONI.FK_CODICEANAGRAFE AS CONC_CODICETITOLARE, CONCAT_WS('',TITOLARE.NOMINATIVO,' ',TITOLARE.NOME) AS CONC_TITOLARE, TITOLARE.CODICEFISCALE AS CONC_TIT_CF, TITOLARE.PARTITAIVA AS CONC_TIT_PIVA, TITOLARE.TIPOANAGRAFE AS CONC_TIT_TIPOANAGRAFE, AUT_COLLEGATA.AUTORIZNUMERO AS AUT_NUMERO, AUT_COLLEGATA.AUTORIZDATA AS AUT_DATA, AUT_COLLEGATA.AUTORIZDATA, AUT_COLLEGATA.FKIDREGISTRO AS AUT_CODREGISTRO, TIPOLOGIAREGISTRI.TR_DESCRIZIONE AS AUT_REGISTRO, CONCAT_WS('',IST_RICHIEDENTE.NOMINATIVO,' ',IST_RICHIEDENTE.NOME) AS IST_NOMINATIVO, IST_RICHIEDENTE.TIPOANAGRAFE AS IST_RIC_TIPOANAGRAFE, CONCAT_WS('',IST_AZIENDA.NOMINATIVO,' ',IST_AZIENDA.NOME) AS IST_NOMINATIVOAZIENDA, IST_AZIENDA.TIPOANAGRAFE AS IST_AZI_TIPOANAGRAFE, IST_AZIENDA.CODICEFISCALE AS IST_AZI_CODICEFISCALE, IST_AZIENDA.PARTITAIVA AS IST_AZI_PARTITAIVA, IST_RICHIEDENTE.CODICEFISCALE AS IST_CODICEFISCALE, IST_RICHIEDENTE.PARTITAIVA AS IST_PARTITAIVA, CAUS_ATTUALE.DESCRIZIONE AS ICONC_CAUSALE, AUTORIZZAZIONI.FK_CAUSALE_CESSAZIONE AS ICONC_CODICECAUSALESTORICO, CAUS_STORICO.DESCRIZIONE AS ICONC_CAUSALESTORICO, AUTORIZZAZIONI_CONCESSIONI.FK_CODICEMERCATO AS CONC_IDMERCATO, MERCATI.DESCRIZIONE AS CONC_MERCATO, MERCATI.ATTIVO AS MERC_ATTIVO, AUTORIZZAZIONI_CONCESSIONI.FK_IDPOSTEGGIO AS CONC_IDPOSTEGGIO, MERCATI_D.CODICEPOSTEGGIO AS CONC_POSTEGGIO, MERCATI_D.LARGHEZZA AS CONC_POS_LARGHEZZA, MERCATI_D.LUNGHEZZA AS CONC_POS_LUNGHEZZA, MERCATI_D.SUPERFICIE AS CONC_POS_SUPERFICIE, MERCATI_D.FKCODICETIPOSPAZIO AS POST_IDTIPOSPAZIO, POSTEGGITIPOSPAZIO.TIPOSPAZIO AS POST_TIPOSPAZIO, AUTORIZZAZIONI_CONCESSIONI.FK_IDMERCATIUSO AS CONC_IDMERCATIUSO, MERCATI_USO.DESCRIZIONE AS CONC_DESCRIZIONEUSO, MERCATI_USO.PESO AS PESO_MERCATO, MERCATI_USO.FKCODICEUSO AS MERC_IDUSO, MERCATI_D.FKCODICESTRADARIO AS CONC_POS_CODICESTRADARIO FROM ((AUTORIZZAZIONI LEFT OUTER JOIN TIPOLOGIAREGISTRI ON AUTORIZZAZIONI.IDCOMUNE = TIPOLOGIAREGISTRI.IDCOMUNE AND AUTORIZZAZIONI.FKIDREGISTRO = TIPOLOGIAREGISTRI.TR_ID) LEFT OUTER JOIN CONCESSIONICAUSALI CAUS_STORICO ON AUTORIZZAZIONI.IDCOMUNE = CAUS_STORICO.IDCOMUNE AND AUTORIZZAZIONI.FK_CAUSALE_CESSAZIONE = CAUS_STORICO.CODICECAUSALE), (AUTORIZZAZIONI_CONCESSIONI LEFT OUTER JOIN AUTORIZZAZIONI AUT_COLLEGATA ON AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE = AUT_COLLEGATA.IDCOMUNE AND AUTORIZZAZIONI_CONCESSIONI.FK_IDAUT_COLLEGATA = AUT_COLLEGATA.ID), CONCESSIONITIPI, ANAGRAFE TITOLARE, CONCESSIONICAUSALI CAUS_ATTUALE, ISTANZE LEFT OUTER JOIN ANAGRAFE IST_AZIENDA ON ISTANZE.IDCOMUNE = IST_AZIENDA.IDCOMUNE AND ISTANZE.CODICETITOLARELEGALE = IST_AZIENDA.CODICEANAGRAFE, ANAGRAFE IST_RICHIEDENTE, MERCATI, (MERCATI_D LEFT OUTER JOIN POSTEGGITIPOSPAZIO ON  MERCATI_D.IDCOMUNE = POSTEGGITIPOSPAZIO.IDCOMUNE AND MERCATI_D.FKCODICETIPOSPAZIO = POSTEGGITIPOSPAZIO.CODICE), MERCATI_USO WHERE AUTORIZZAZIONI.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND AUTORIZZAZIONI.ID = AUTORIZZAZIONI_CONCESSIONI.FK_IDAUT_ATTUALE AND CONCESSIONITIPI.TIPOCONCESSIONE = AUTORIZZAZIONI_CONCESSIONI.FK_TIPOCONCESSIONE AND TITOLARE.IDCOMUNE = AUTORIZZAZIONI.IDCOMUNE AND TITOLARE.CODICEANAGRAFE = AUTORIZZAZIONI.FK_CODICEANAGRAFE AND CAUS_ATTUALE.IDCOMUNE = AUTORIZZAZIONI.IDCOMUNE AND CAUS_ATTUALE.CODICECAUSALE = AUTORIZZAZIONI.FK_CAUSALE_ACQUISIZIONE AND ISTANZE.IDCOMUNE = AUTORIZZAZIONI.IDCOMUNE AND ISTANZE.CODICEISTANZA = AUTORIZZAZIONI.FKIDISTANZA AND IST_RICHIEDENTE.IDCOMUNE = ISTANZE.IDCOMUNE AND IST_RICHIEDENTE.CODICEANAGRAFE = ISTANZE.CODICERICHIEDENTE AND MERCATI.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND MERCATI.CODICEMERCATO = AUTORIZZAZIONI_CONCESSIONI.FK_CODICEMERCATO AND MERCATI_D.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND MERCATI_D.IDPOSTEGGIO = AUTORIZZAZIONI_CONCESSIONI.FK_IDPOSTEGGIO AND MERCATI_USO.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND MERCATI_USO.ID = AUTORIZZAZIONI_CONCESSIONI.FK_IDMERCATIUSO

UNION

SELECT AUTORIZZAZIONI_SUBENTRI.ID AS PROGRESSIVO, AUTORIZZAZIONI_SUBENTRI.AUTORIZRESPONSABILE AS CONC_AUTORIZRESPONSABILE, AUTORIZZAZIONI_SUBENTRI.IDCOMUNE, AUTORIZZAZIONI_SUBENTRI.FK_CAUSALE_ACQUISIZIONE AS ICONC_CODICECAUSALE, AUTORIZZAZIONI_SUBENTRI.DATA_CESSAZIONE AS DATA_STORICO, ISTANZE.SOFTWARE, ISTANZE.CODICEISTANZA AS IST_CODICEISTANZA, ISTANZE.NUMEROISTANZA AS IST_NUMEROISTANZA, ISTANZE.CODICERICHIEDENTE AS IST_CODICERICHIEDENTE, ISTANZE.CODICETITOLARELEGALE AS IST_CODICETITOLARELEGALE, AUTORIZZAZIONI_SUBENTRI.FK_IDAUT_ATTUALE AS CONC_ID, AUTORIZZAZIONI_SUBENTRI.AUTORIZNUMERO AS CONC_NUMERO, AUTORIZZAZIONI_SUBENTRI.AUTORIZDATA AS CONC_DATARILASCIO, AUTORIZZAZIONI_SUBENTRI.AUTORIZDATA AS DATARILASCIO, AUTORIZZAZIONI_SUBENTRI.DATASCADENZA AS CONC_DATASCADENZA, AUTORIZZAZIONI_CONCESSIONI.FK_TIPOCONCESSIONE AS CONC_CODICETIPO, CONCESSIONITIPI.DESCRIZIONE AS CONC_TIPO, AUTORIZZAZIONI_CONCESSIONI.STAGIONALEA AS CONC_STAGIONALEA, AUTORIZZAZIONI_CONCESSIONI.STAGIONALEDA AS CONC_STAGIONALEDA, 0 AS CONC_ATTIVA,AUTORIZZAZIONI_SUBENTRI.FK_CODICEANAGRAFE AS CONC_CODICETITOLARE, CONCAT_WS('',TITOLARE.NOMINATIVO,' ',TITOLARE.NOME) AS CONC_TITOLARE, TITOLARE.CODICEFISCALE AS CONC_TIT_CF, TITOLARE.PARTITAIVA AS CONC_TIT_PIVA, TITOLARE.TIPOANAGRAFE AS CONC_TIT_TIPOANAGRAFE, AUT_COLLEGATA.AUTORIZNUMERO AS AUT_NUMERO, AUT_COLLEGATA.AUTORIZDATA AS AUT_DATA, AUT_COLLEGATA.AUTORIZDATA,AUT_COLLEGATA.FKIDREGISTRO AS AUT_CODREGISTRO, TIPOLOGIAREGISTRI.TR_DESCRIZIONE AS AUT_REGISTRO, CONCAT_WS('',IST_RICHIEDENTE.NOMINATIVO,' ',IST_RICHIEDENTE.NOME) AS IST_NOMINATIVO, IST_RICHIEDENTE.TIPOANAGRAFE AS IST_RIC_TIPOANAGRAFE, CONCAT_WS('',IST_AZIENDA.NOMINATIVO,' ',IST_AZIENDA.NOME ) AS IST_NOMINATIVOAZIENDA, IST_AZIENDA.TIPOANAGRAFE AS IST_AZI_TIPOANAGRAFE, IST_AZIENDA.CODICEFISCALE AS IST_AZI_CODICEFISCALE, IST_AZIENDA.PARTITAIVA AS IST_AZI_PARTITAIVA, IST_RICHIEDENTE.CODICEFISCALE AS IST_CODICEFISCALE,IST_RICHIEDENTE.PARTITAIVA AS IST_PARTITAIVA, CAUS_ATTUALE.DESCRIZIONE AS ICONC_CAUSALE, AUTORIZZAZIONI_SUBENTRI.FK_CAUSALE_CESSAZIONE AS ICONC_CODICECAUSALESTORICO, CAUS_STORICO.DESCRIZIONE AS ICONC_CAUSALESTORICO, AUTORIZZAZIONI_CONCESSIONI.FK_CODICEMERCATO AS CONC_IDMERCATO, MERCATI.DESCRIZIONE AS CONC_MERCATO,MERCATI.ATTIVO AS MERC_ATTIVO, AUTORIZZAZIONI_CONCESSIONI.FK_IDPOSTEGGIO AS CONC_IDPOSTEGGIO, MERCATI_D.CODICEPOSTEGGIO AS CONC_POSTEGGIO, MERCATI_D.LARGHEZZA AS CONC_POS_LARGHEZZA,MERCATI_D.LUNGHEZZA AS CONC_POS_LUNGHEZZA,MERCATI_D.SUPERFICIE AS CONC_POS_SUPERFICIE, MERCATI_D.FKCODICETIPOSPAZIO AS POST_IDTIPOSPAZIO,POSTEGGITIPOSPAZIO.TIPOSPAZIO AS POST_TIPOSPAZIO, AUTORIZZAZIONI_CONCESSIONI.FK_IDMERCATIUSO AS CONC_IDMERCATIUSO, MERCATI_USO.DESCRIZIONE AS CONC_DESCRIZIONEUSO,MERCATI_USO.PESO AS PESO_MERCATO, MERCATI_USO.FKCODICEUSO AS MERC_IDUSO, MERCATI_D.FKCODICESTRADARIO AS CONC_POS_CODICESTRADARIO FROM (( AUTORIZZAZIONI_SUBENTRI LEFT OUTER JOIN TIPOLOGIAREGISTRI ON AUTORIZZAZIONI_SUBENTRI.IDCOMUNE = TIPOLOGIAREGISTRI.IDCOMUNE AND AUTORIZZAZIONI_SUBENTRI.FKIDREGISTRO = TIPOLOGIAREGISTRI.TR_ID )        LEFT OUTER JOIN CONCESSIONICAUSALI CAUS_STORICO ON  AUTORIZZAZIONI_SUBENTRI.IDCOMUNE = CAUS_STORICO.IDCOMUNE AND AUTORIZZAZIONI_SUBENTRI.FK_CAUSALE_CESSAZIONE = CAUS_STORICO.CODICECAUSALE ), ( AUTORIZZAZIONI_CONCESSIONI LEFT OUTER JOIN AUTORIZZAZIONI AUT_COLLEGATA ON  AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE = AUT_COLLEGATA.IDCOMUNE AND AUTORIZZAZIONI_CONCESSIONI.FK_IDAUT_COLLEGATA = AUT_COLLEGATA.ID ), CONCESSIONITIPI, ANAGRAFE TITOLARE, CONCESSIONICAUSALI CAUS_ATTUALE, ( ISTANZE LEFT OUTER JOIN ANAGRAFE IST_AZIENDA ON ISTANZE.IDCOMUNE = IST_AZIENDA.IDCOMUNE AND ISTANZE.CODICETITOLARELEGALE = IST_AZIENDA.CODICEANAGRAFE ), ANAGRAFE IST_RICHIEDENTE,MERCATI, ( MERCATI_D LEFT OUTER JOIN POSTEGGITIPOSPAZIO ON MERCATI_D.IDCOMUNE = POSTEGGITIPOSPAZIO.IDCOMUNE AND MERCATI_D.FKCODICETIPOSPAZIO = POSTEGGITIPOSPAZIO.CODICE ), MERCATI_USO WHERE AUTORIZZAZIONI_SUBENTRI.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND AUTORIZZAZIONI_SUBENTRI.FK_IDAUT_ATTUALE = AUTORIZZAZIONI_CONCESSIONI.FK_IDAUT_ATTUALE AND CONCESSIONITIPI.TIPOCONCESSIONE = AUTORIZZAZIONI_CONCESSIONI.FK_TIPOCONCESSIONE AND TITOLARE.IDCOMUNE = AUTORIZZAZIONI_SUBENTRI.IDCOMUNE AND TITOLARE.CODICEANAGRAFE = AUTORIZZAZIONI_SUBENTRI.FK_CODICEANAGRAFE AND CAUS_ATTUALE.IDCOMUNE = AUTORIZZAZIONI_SUBENTRI.IDCOMUNE AND CAUS_ATTUALE.CODICECAUSALE = AUTORIZZAZIONI_SUBENTRI.FK_CAUSALE_ACQUISIZIONE AND ISTANZE.IDCOMUNE = AUTORIZZAZIONI_SUBENTRI.IDCOMUNE AND ISTANZE.CODICEISTANZA = AUTORIZZAZIONI_SUBENTRI.FKIDISTANZA AND IST_RICHIEDENTE.IDCOMUNE = ISTANZE.IDCOMUNE AND IST_RICHIEDENTE.CODICEANAGRAFE = ISTANZE.CODICERICHIEDENTE AND MERCATI.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND MERCATI.CODICEMERCATO = AUTORIZZAZIONI_CONCESSIONI.FK_CODICEMERCATO AND MERCATI_D.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND MERCATI_D.IDPOSTEGGIO = AUTORIZZAZIONI_CONCESSIONI.FK_IDPOSTEGGIO AND MERCATI_USO.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND MERCATI_USO.ID = AUTORIZZAZIONI_CONCESSIONI.FK_IDMERCATIUSO;

ALTER TABLE FO_ARCONFIGURAZIONE  ADD FKID_SCHEDA_EC NUMERIC(10, 0);
ALTER TABLE FO_ARCONFIGURAZIONE  ADD FLG_SCHEDA_EC_RICHIEDEFIRMA NUMERIC(1, 0) ;

ALTER TABLE FO_ARCONFIGURAZIONE ADD CONSTRAINT FK_ARCONF_DYN2_MOD_T FOREIGN KEY (IDCOMUNE,FKID_SCHEDA_EC) REFERENCES DYN2_MODELLIT  (IDCOMUNE, ID);

ALTER TABLE CITTADINANZA ADD FLG_PAESE_COMUNITARIO NUMERIC(1, 0) ;

ALTER TABLE ALBEROPROC ADD CODICEOGGETTO_WORKFLOW NUMERIC(10);
ALTER TABLE ALBEROPROC ADD CONSTRAINT FK_ALBERO_PROC_OGG_WORKFLOW FOREIGN KEY (IDCOMUNE,CODICEOGGETTO_WORKFLOW) REFERENCES OGGETTI ( IDCOMUNE,CODICEOGGETTO);
ALTER TABLE DOMANDESTC MODIFY RICHIEDENTE VARCHAR(80);

ALTER TABLE AMMINISTRAZIONI MODIFY STC_IDENTE VARCHAR(20);
ALTER TABLE DOMANDESTC MODIFY ID_ENTEMITT VARCHAR(20);

CREATE TABLE TIPICAUSALIONINTERESSI (IDCOMUNE VARCHAR(6) NOT NULL, ID NUMERIC(8) NOT NULL, FK_IDTIPOCAUSALE NUMERIC(10) NOT NULL, GGRITARDOPAGAMENTO NUMERIC(4) NOT NULL, PERCENTUALE NUMERIC(8, 5) NOT NULL)  ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE TIPICAUSALIONINTERESSI ADD CONSTRAINT TIPICAUSALIONINTERESSI_PK PRIMARY KEY(IDCOMUNE,ID);
ALTER TABLE TIPICAUSALIONINTERESSI ADD CONSTRAINT FK_TIPICAUSALIINTERESSI_001 FOREIGN KEY(IDCOMUNE, FK_IDTIPOCAUSALE) REFERENCES TIPICAUSALIONERI(IDCOMUNE, CO_ID);

ALTER TABLE TIPICAUSALIONERI ADD FLG_TIPICAUSALIINTERESSI NUMERIC(1);
ALTER TABLE TIPICAUSALIONERI ADD FK_TIPICAUSALIINTERESSI NUMERIC(8);
ALTER TABLE TIPICAUSALIONERI ADD CONSTRAINT FK_TIPICAUSON_INTERESSI FOREIGN KEY(IDCOMUNE, FK_TIPICAUSALIINTERESSI) REFERENCES TIPICAUSALIONERI(IDCOMUNE, CO_ID);
 

ALTER TABLE ISTANZEONERI ADD FK_IDPADRE NUMERIC(10);
ALTER TABLE ISTANZEONERI ADD CONSTRAINT FK_ISTONERI_ISTONERIPADRE FOREIGN KEY(IDCOMUNE, FK_IDPADRE) REFERENCES ISTANZEONERI(IDCOMUNE, ID);

CREATE OR REPLACE ALGORITHM=TEMPTABLE VIEW VW_LISTAAUTORIZZAZIONI AS SELECT AUTORIZZAZIONI.IDCOMUNE, AUTORIZZAZIONI.FKIDISTANZA AS CODICEISTANZA,ISTANZE.NUMEROISTANZA,AUTORIZZAZIONI.AUTORIZNUMERO AS NUMEROAUTORIZZAZIONE,AUTORIZZAZIONI.AUTORIZDATA AS DATAAUTORIZZAZIONE,COMUNI.COMUNE AS COMUNEAUTORIZZAZIONE, TIPOLOGIAREGISTRI.TR_DESCRIZIONE AS REGISTRO, ANAGRAFE.CODICEANAGRAFE, CONCAT_WS('', ANAGRAFE.NOMINATIVO,' ', ANAGRAFE.NOME)  AS ANAGRAFICA, ISTANZE.LAVORI  AS OGGETTOISTANZA, STRADARIO.CODICESTRADARIO AS LOCALIZZAZIONECODICEVIA, CONCAT_WS('',STRADARIO.PREFISSO, ' ', STRADARIO.DESCRIZIONE) AS LOCALIZZAZIONE, ISTANZESTRADARIO.CIVICO  AS LOCALIZZAZIONECIVICO FROM AUTORIZZAZIONI LEFT JOIN ISTANZE ON AUTORIZZAZIONI.IDCOMUNE  =ISTANZE.IDCOMUNE AND AUTORIZZAZIONI.FKIDISTANZA=ISTANZE.CODICEISTANZA LEFT JOIN ISTANZESTRADARIO ON ISTANZESTRADARIO.IDCOMUNE  =ISTANZE.IDCOMUNE AND ISTANZESTRADARIO.CODICEISTANZA=ISTANZE.CODICEISTANZA LEFT JOIN STRADARIO ON ISTANZESTRADARIO.IDCOMUNE  =STRADARIO.IDCOMUNE AND ISTANZESTRADARIO.CODICESTRADARIO=STRADARIO.CODICESTRADARIO LEFT JOIN TIPOLOGIAREGISTRI ON TIPOLOGIAREGISTRI.IDCOMUNE=AUTORIZZAZIONI.IDCOMUNE AND TIPOLOGIAREGISTRI.TR_ID  =AUTORIZZAZIONI.FKIDREGISTRO, ANAGRAFE, COMUNI WHERE ANAGRAFE.IDCOMUNE = AUTORIZZAZIONI.IDCOMUNE AND ANAGRAFE.CODICEANAGRAFE = AUTORIZZAZIONI.FK_CODICEANAGRAFE AND COMUNI.CODICECOMUNE =AUTORIZZAZIONI.AUTORIZCOMUNE AND (ISTANZESTRADARIO.PRIMARIO=1 OR ISTANZESTRADARIO.PRIMARIO IS NULL);