Alter table conf_applicative modify CHIAVE varchar2(100);
ALTER TABLE pay_profili_enti_creditori ADD APPLICATION_CODE number(2,0) NULL  ;
comment on column pay_profili_enti_creditori.APPLICATION_CODE is  'IDENTIFICATIVO NUMERICO DELL''ARCHIVO DI PAGAMENTI ASSOCIATO A QUESTO SERVIZIO DELL''ENTE CREDITORE IN PAGOPA. UTILIZZATO PER LA GENERAZIONE DEL CODICE AVVISO CON AUX DIGIT = 0';

alter table istanzeeventi modify FKIDCATEGORIAEVENTO VARCHAR2(16) null;
ALTER TABLE CONTI ADD (DATASCADENZA DATE );

CREATE TABLE BOLL_CFG_TIPO(IDCOMUNE VARCHAR2(6 CHAR) NOT NULL,ID NUMBER(4,0) NOT NULL,DESCRIZIONE VARCHAR2(200 CHAR),PERIODO VARCHAR2(20 CHAR),FLAG_CONGUAGLIO NUMBER(1,0),FLAG_RAGGRUPPA_UTENZA NUMBER(1,0),IMPLEMENTAZIONE VARCHAR2(20 CHAR),FK_TIPISCADENZA_ID NUMBER(2,0));
ALTER TABLE BOLL_CFG_TIPO ADD CONSTRAINT PK_BLCFGTIPO PRIMARY KEY(IDCOMUNE,ID); 
ALTER TABLE BOLL_CFG_TIPO ADD CONSTRAINT FK_BLCFGTIPO_TIPISCAD FOREIGN KEY(FK_TIPISCADENZA_ID) REFERENCES TIPI_SCADENZA(ID);
CREATE TABLE BOLL_CFG_RUOLI(IDCOMUNE VARCHAR2(6 CHAR) NOT NULL,FK_BOLLCFGTIPO_ID NUMBER(4,0) NOT NULL,FK_RUOLI_ID NUMBER(4,0) NOT NULL);
ALTER TABLE BOLL_CFG_RUOLI ADD CONSTRAINT PK_BLCFGRUOLI PRIMARY KEY(IDCOMUNE,FK_BOLLCFGTIPO_ID,FK_RUOLI_ID);
ALTER TABLE BOLL_CFG_RUOLI ADD CONSTRAINT FK_BLLCFGRUOLI_BLLCFGTIPO FOREIGN KEY(IDCOMUNE,FK_BOLLCFGTIPO_ID) REFERENCES BOLL_CFG_TIPO(IDCOMUNE,ID);
ALTER TABLE BOLL_CFG_RUOLI ADD CONSTRAINT FK_BLLCFGRUOLI_RUOLI FOREIGN KEY(IDCOMUNE,FK_RUOLI_ID) REFERENCES RUOLI(IDCOMUNE,ID);
CREATE TABLE BOLL_CFG_MERCATI(IDCOMUNE VARCHAR2(6 CHAR) NOT NULL,FK_BOLLCFGTIPO_ID NUMBER(4,0) NOT NULL,FK_CODICEMERCATO NUMBER(4,0) NOT NULL);
ALTER TABLE BOLL_CFG_MERCATI ADD CONSTRAINT PK_CFGMERCATI PRIMARY KEY(IDCOMUNE,FK_BOLLCFGTIPO_ID,FK_CODICEMERCATO);
ALTER TABLE BOLL_CFG_MERCATI ADD CONSTRAINT FK_CFGMERCATI_BLLCFGTIPO FOREIGN KEY(IDCOMUNE,FK_BOLLCFGTIPO_ID) REFERENCES BOLL_CFG_TIPO(IDCOMUNE,ID);
ALTER TABLE BOLL_CFG_MERCATI ADD CONSTRAINT FK_CFGMERCATI_MERCATI FOREIGN KEY(IDCOMUNE,FK_CODICEMERCATO) REFERENCES MERCATI(IDCOMUNE,CODICEMERCATO);
CREATE TABLE BOLL_CFG_CAUSALIONERI(IDCOMUNE VARCHAR2(6 CHAR) NOT NULL,FK_BOLLCFGTIPO_ID NUMBER(4,0) NOT NULL,FK_CO_ID NUMBER(10,0) NOT NULL);
ALTER TABLE BOLL_CFG_CAUSALIONERI ADD CONSTRAINT PK_CFGCAUSALIONERI PRIMARY KEY(IDCOMUNE,FK_BOLLCFGTIPO_ID,FK_CO_ID);
ALTER TABLE BOLL_CFG_CAUSALIONERI ADD CONSTRAINT FK_CFGCAUSALIONERI_BLLCFGTIPO FOREIGN KEY(IDCOMUNE,FK_BOLLCFGTIPO_ID) REFERENCES BOLL_CFG_TIPO(IDCOMUNE,ID);
ALTER TABLE BOLL_CFG_CAUSALIONERI ADD CONSTRAINT FK_CFGCAUSALIONERI_MERCATI FOREIGN KEY(IDCOMUNE,FK_CO_ID) REFERENCES TIPICAUSALIONERI(IDCOMUNE,CO_ID);
ALTER TABLE BOLL_CFG_TIPO ADD SOFTWARE VARCHAR2(2 CHAR) NOT NULL ENABLE;
ALTER TABLE BOLL_CFG_TIPO ADD CONSTRAINT FK_CFGTIPO_SOFTWARE FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);


CREATE TABLE BOLL_GEST_TESTATA(
IDCOMUNE VARCHAR2(6 CHAR) NOT NULL
,ID NUMBER(4,0) NOT NULL
,FK_BOLLTIPO_ID NUMBER(4,0)
,DESCRIZIONE VARCHAR2(4000 CHAR)
,DALLA_DATA DATE
,ALLA_DATA DATE
,STATO VARCHAR2(10 CHAR)
,FLAG_CONGUAGLIO NUMBER(1,0)
,FLAG_RAGGRUPPA_UTENZA NUMBER(1,0)
,DATA_INSERIMENTO DATE
,PERIODO  VARCHAR2(20 CHAR)
,IMPLEMENTAZIONE VARCHAR2(20 CHAR)
,FK_TIPISCADENZA_ID NUMBER(2) );

ALTER TABLE BOLL_GEST_TESTATA ADD CONSTRAINT PK_BOLLGESTTESTATA PRIMARY KEY(IDCOMUNE,ID); ALTER TABLE BOLL_GEST_TESTATA ADD CONSTRAINT FK_BOLGESTEST_BOLCFGTI FOREIGN KEY(IDCOMUNE,FK_BOLLTIPO_ID)
    REFERENCES BOLL_CFG_TIPO(IDCOMUNE,ID);

ALTER TABLE BOLL_GEST_TESTATA ADD CONSTRAINT FK_BOLGESTEST_TIPISCAD FOREIGN KEY(FK_TIPISCADENZA_ID)
    REFERENCES TIPI_SCADENZA(ID);

CREATE TABLE BOLL_GEST_FILTRI(
IDCOMUNE VARCHAR2(6 CHAR) NOT NULL
,ID NUMBER(6,0) NOT NULL
,FK_SC_CODICE VARCHAR2(40 CHAR)
,FK_BOLLGEST_ID NUMBER(4,0)
,FK_CODICEINVENTARIO NUMBER(10, 0)
,CODICECOMUNE VARCHAR2(5 CHAR)
,FK_CODICEMERCATO NUMBER(4,0)
,FK_CO_ID NUMBER(10,0)

);

ALTER TABLE BOLL_GEST_FILTRI ADD CONSTRAINT PK_BOLLGESTFILTRI PRIMARY KEY(IDCOMUNE,ID); ALTER TABLE BOLL_GEST_FILTRI ADD CONSTRAINT FK_BOLGESTFI_BOLGESTT FOREIGN KEY(IDCOMUNE,FK_BOLLGEST_ID) REFERENCES BOLL_GEST_TESTATA(IDCOMUNE,ID);

ALTER TABLE BOLL_GEST_FILTRI ADD CONSTRAINT FK_BOLGESTFI_INVPROC FOREIGN KEY(IDCOMUNE,FK_CODICEINVENTARIO) REFERENCES INVENTARIOPROCEDIMENTI(IDCOMUNE,CODICEINVENTARIO);

ALTER TABLE BOLL_GEST_FILTRI ADD CONSTRAINT FK_BOLGESTFI_COMUNI FOREIGN KEY(CODICECOMUNE) REFERENCES COMUNI(CODICECOMUNE);

ALTER TABLE BOLL_GEST_FILTRI ADD CONSTRAINT FK_BOLGESTFI_TIPICAUSONERI FOREIGN KEY(IDCOMUNE,FK_CO_ID) REFERENCES TIPICAUSALIONERI(IDCOMUNE,CO_ID);

ALTER TABLE BOLL_GEST_FILTRI ADD CONSTRAINT FK_BOLGESTFI_MERCATI FOREIGN KEY(IDCOMUNE,FK_CODICEMERCATO) REFERENCES MERCATI(IDCOMUNE,CODICEMERCATO);

CREATE TABLE DETT_POSIZIONE_DEBITORIA(
IDCOMUNE VARCHAR2(6 CHAR) NOT NULL
,ID NUMBER(10,0) NOT NULL
,STATO varchar2(30 CHAR) NOT NULL
,DESC_STATO varchar2(500 CHAR) NULL
,ID_POSIZIONE_DEBITORIA NUMBER(10,0) 
,DATA_ULTIMO_STATO DATE);

ALTER TABLE DETT_POSIZIONE_DEBITORIA ADD CONSTRAINT PK_DETTPOSIZIONEDEBITORIA PRIMARY KEY(IDCOMUNE,ID);


CREATE TABLE BOLL_GEST_DETTAGLIO(
IDCOMUNE VARCHAR2(6 CHAR) NOT NULL
,ID NUMBER(10,0) NOT NULL
,FK_BOLLGEST_ID NUMBER(4,0)
,IMPORTO NUMBER(11,2)
,FLAG_VALIDATA NUMBER(1,0)
,FK_RETTIFICA_ID  NUMBER(10,0)
,DESCRIZIONE VARCHAR2(1000 CHAR)
,FLAG_INS_AUTO NUMBER(1,0)
,FK_CODICEANAGRAFE NUMBER(6,0)
,FK_CONTO_ID NUMBER(6,0)
,FK_POSDEBDETTAGLIO_ID NUMBER(10,0)
);

ALTER TABLE BOLL_GEST_DETTAGLIO ADD CONSTRAINT PK_BOLLGESTDETTAGLIO PRIMARY KEY(IDCOMUNE,ID);

ALTER TABLE BOLL_GEST_DETTAGLIO ADD CONSTRAINT FK_BOLLGESTD_BOLLGEST FOREIGN KEY(IDCOMUNE,FK_BOLLGEST_ID) REFERENCES BOLL_GEST_TESTATA(IDCOMUNE,ID);

ALTER TABLE BOLL_GEST_DETTAGLIO ADD CONSTRAINT FK_BOLLGESTD_BLGDRETT FOREIGN KEY(IDCOMUNE,FK_RETTIFICA_ID) REFERENCES BOLL_GEST_DETTAGLIO(IDCOMUNE,ID);

ALTER TABLE BOLL_GEST_DETTAGLIO ADD CONSTRAINT FK_BOLLGESTD_ANAGRAFE FOREIGN KEY(IDCOMUNE,FK_CODICEANAGRAFE) REFERENCES ANAGRAFE(IDCOMUNE,CODICEANAGRAFE);

ALTER TABLE BOLL_GEST_DETTAGLIO ADD CONSTRAINT FK_BOLLGESTD_CONTI FOREIGN KEY(IDCOMUNE,FK_CONTO_ID) REFERENCES CONTI(IDCOMUNE,ID);

ALTER TABLE BOLL_GEST_DETTAGLIO ADD CONSTRAINT FK_BOLLGESTD_POSDEB FOREIGN KEY(IDCOMUNE,FK_POSDEBDETTAGLIO_ID)
REFERENCES DETT_POSIZIONE_DEBITORIA(IDCOMUNE,ID);

CREATE TABLE BOLL_GEST_ISTANZEONERI(
IDCOMUNE VARCHAR2(6 CHAR) NOT NULL
,ID NUMBER(10,0) NOT NULL
,FK_BOLLGESTDET_ID NUMBER(10,0)
,FK_CODICEISTANZEONERI  NUMBER(10,0)
);

ALTER TABLE BOLL_GEST_ISTANZEONERI ADD CONSTRAINT PK_BOLLGESTISTANZEONERI PRIMARY KEY(IDCOMUNE,ID);

ALTER TABLE BOLL_GEST_ISTANZEONERI ADD CONSTRAINT FK_BOLLGESTISTONERI_BOLLGD FOREIGN KEY (IDCOMUNE,FK_BOLLGESTDET_ID) REFERENCES BOLL_GEST_DETTAGLIO(IDCOMUNE,ID);

ALTER TABLE BOLL_GEST_ISTANZEONERI ADD CONSTRAINT FK_BOLLGESTISTONERI_ISTONERI FOREIGN KEY (IDCOMUNE,FK_CODICEISTANZEONERI) REFERENCES ISTANZEONERI(IDCOMUNE,ID);

ALTER TABLE BOLL_CFG_TIPO MODIFY (DESCRIZIONE NOT NULL);
ALTER TABLE BOLL_CFG_TIPO MODIFY (PERIODO NOT NULL);
ALTER TABLE BOLL_CFG_TIPO MODIFY (FLAG_CONGUAGLIO NOT NULL);
ALTER TABLE BOLL_CFG_TIPO MODIFY (FLAG_RAGGRUPPA_UTENZA NOT NULL);
ALTER TABLE BOLL_CFG_TIPO MODIFY (IMPLEMENTAZIONE NOT NULL);
ALTER TABLE BOLL_CFG_TIPO MODIFY (FK_TIPISCADENZA_ID NOT NULL);
ALTER TABLE BOLL_GEST_TESTATA MODIFY (FK_BOLLTIPO_ID NOT NULL);
ALTER TABLE BOLL_GEST_TESTATA MODIFY (DESCRIZIONE NOT NULL);
ALTER TABLE BOLL_GEST_TESTATA MODIFY (DALLA_DATA NOT NULL);
ALTER TABLE BOLL_GEST_TESTATA MODIFY (ALLA_DATA NOT NULL);
ALTER TABLE BOLL_GEST_TESTATA MODIFY (STATO NOT NULL);
ALTER TABLE BOLL_GEST_TESTATA MODIFY (FLAG_CONGUAGLIO NOT NULL);
ALTER TABLE BOLL_GEST_TESTATA MODIFY (FLAG_RAGGRUPPA_UTENZA NOT NULL);
ALTER TABLE BOLL_GEST_TESTATA MODIFY (DATA_INSERIMENTO NOT NULL);
ALTER TABLE BOLL_GEST_TESTATA MODIFY (PERIODO NOT NULL);
ALTER TABLE BOLL_GEST_TESTATA MODIFY (IMPLEMENTAZIONE NOT NULL);
ALTER TABLE BOLL_GEST_TESTATA MODIFY (FK_TIPISCADENZA_ID NOT NULL);
ALTER TABLE BOLL_GEST_DETTAGLIO MODIFY (FK_BOLLGEST_ID NOT NULL);
ALTER TABLE BOLL_GEST_DETTAGLIO MODIFY (IMPORTO NOT NULL);
ALTER TABLE BOLL_GEST_DETTAGLIO MODIFY (FLAG_VALIDATA NOT NULL);
ALTER TABLE BOLL_GEST_DETTAGLIO MODIFY (DESCRIZIONE NOT NULL);
ALTER TABLE BOLL_GEST_DETTAGLIO MODIFY (FLAG_INS_AUTO NOT NULL);
ALTER TABLE BOLL_GEST_DETTAGLIO MODIFY (FK_CODICEANAGRAFE NOT NULL);
ALTER TABLE BOLL_GEST_DETTAGLIO MODIFY (FK_CONTO_ID NOT NULL);
ALTER TABLE BOLL_GEST_FILTRI MODIFY (FK_BOLLGEST_ID NOT NULL);
ALTER TABLE BOLL_GEST_FILTRI MODIFY (CODICECOMUNE NOT NULL);
ALTER TABLE BOLL_GEST_ISTANZEONERI MODIFY (FK_BOLLGESTDET_ID NOT NULL);
ALTER TABLE BOLL_GEST_ISTANZEONERI MODIFY (FK_CODICEISTANZEONERI NOT NULL);

  
CREATE TABLE pay_richieste(  
  ID NUMBER(9,0) NOT NULL,
  IDCOMUNE VARCHAR2(6) NOT NULL,
  TIPO_RICHIESTA VARCHAR2(30) NOT NULL,
  FK_POSIZIONE_DEBITORIA NUMBER(9,0) NOT NULL,
  FK_PROFILO_ENTE NUMBER(10,0) NOT NULL,
  DATA_RICHIESTA DATE NOT NULL,
  FK_EVENTO NUMBER(9,0),
  DATA_COMPLETAMENTO DATE,
  N_CHIAMATE NUMBER(9,0),
  FK_EVENTO_OUT number(9,0)
);

ALTER TABLE pay_richieste ADD CONSTRAINT PK_PAY_RICHIESTE PRIMARY KEY(IDCOMUNE,ID);
CREATE INDEX IDX_RICH_X_TIPO ON pay_richieste(FK_PROFILO_ENTE, TIPO_RICHIESTA);
ALTER TABLE pay_richieste ADD CONSTRAINT FK_RICH_POSDEB FOREIGN KEY (IDCOMUNE, FK_POSIZIONE_DEBITORIA) REFERENCES pay_posizioni_debitorie(IDCOMUNE, ID);
ALTER TABLE pay_richieste ADD CONSTRAINT FK_RICH_ENTE FOREIGN KEY (IDCOMUNE, FK_PROFILO_ENTE) REFERENCES pay_profili_enti_creditori(IDCOMUNE, ID);
ALTER TABLE pay_richieste ADD CONSTRAINT FK_RICH_EVENTO FOREIGN KEY (IDCOMUNE, FK_EVENTO) REFERENCES pay_io_eventi(IDCOMUNE, ID);


ALTER TABLE pay_connector_ws_endpoint   ADD QUARTZ_SCHEDULE VARCHAR2(100) NULL;
ALTER TABLE pay_connector_ws_endpoint   ADD FLAG_SOLO_SCHEDULATO NUMBER(1,0) DEFAULT '0'  NULL;
ALTER TABLE pay_connector_ws_endpoint   ADD MAX_CHIAMATE NUMBER(9,0) NULL;

ALTER TABLE BOLL_GEST_DETTAGLIO ADD (FLAG_ELIMINATA NUMBER(1) NOT NULL);
ALTER TABLE BOLL_GEST_DETTAGLIO ADD (NOTE_UTENTE VARCHAR2(4000) );
ALTER TABLE BOLL_GEST_DETTAGLIO ADD (NOTE_SISTEMA VARCHAR2(4000) );


ALTER TABLE pay_connector_config  ADD APPLICATION_CODE VARCHAR2(2) NULL;

ALTER TABLE boll_gest_dettaglio ADD flag_rettificata  NUMBER(1,0) NOT NULL;

CREATE TABLE TIPICAUSALIONERIDETTAGLIO (IDCOMUNE VARCHAR2(6 CHAR) NOT NULL, FKCAUSALE NUMBER(10,0) NOT NULL, FKCONTO NUMBER(6,0) NOT NULL, CONSTRAINT TIPICAUSALIONERIDETTAGLIO_PK PRIMARY KEY (IDCOMUNE, FKCAUSALE, FKCONTO) ENABLE);
ALTER TABLE TIPICAUSALIONERIDETTAGLIO ADD CONSTRAINT TIPICAUSALIONERIDETTAGLIO_FK1 FOREIGN KEY(IDCOMUNE, FKCAUSALE)REFERENCES TIPICAUSALIONERI(IDCOMUNE, CO_ID)ENABLE;
ALTER TABLE TIPICAUSALIONERIDETTAGLIO ADD CONSTRAINT TIPICAUSALIONERIDETTAGLIO_FK2 FOREIGN KEY(IDCOMUNE, FKCONTO)REFERENCES CONTI(IDCOMUNE, ID)ENABLE;
ALTER TABLE BOLL_GEST_FILTRI MODIFY (CODICECOMUNE NULL);



CREATE TABLE LIVELLO_SERVIZIO (
     IDCOMUNE VARCHAR2(6 char) NOT NULL
     ,  ID NUMBER(10) NOT NULL
     , DESCRIZIONE VARCHAR2(300 char)  NOT NULL
     , SEGNAPOSTO VARCHAR2(150 char)  NOT NULL );

ALTER TABLE LIVELLO_SERVIZIO ADD CONSTRAINT PK_LIVELLO_SERVIZIO PRIMARY KEY(IDCOMUNE, ID);

CREATE TABLE MERCATI_LIVELLO_SERVIZIO (
  IDCOMUNE VARCHAR2(6 char) NOT NULL
     , ID NUMBER(10) NOT NULL
     , DESCRIZIONE VARCHAR2(300 char) NOT NULL
     , FK_MERCATO_USO NUMBER(4)  NOT NULL
     , FK_SERVIZIO NUMBER(10)  NOT NULL
     , ATTIVO NUMBER(1)  NOT NULL
     , TARIFFA NUMBER(7,4)  NOT NULL
     , DATA_INIZIO_VALIDITA DATE NOT NULL
     , DATA_FINE_VALIDITA DATE
 , NOTE VARCHAR2(500 char)
);

ALTER TABLE MERCATI_LIVELLO_SERVIZIO ADD CONSTRAINT PK_MERCATI_LIVELLO_SERVIZIO PRIMARY KEY (IDCOMUNE,ID);

ALTER TABLE MERCATI_LIVELLO_SERVIZIO ADD CONSTRAINT FK_MER_SERV_LIV_SERV FOREIGN KEY (IDCOMUNE, FK_SERVIZIO) REFERENCES LIVELLO_SERVIZIO (IDCOMUNE,ID);

ALTER TABLE MERCATI_LIVELLO_SERVIZIO ADD CONSTRAINT FK_MER_SERV_USO  FOREIGN KEY (IDCOMUNE, FK_MERCATO_USO) REFERENCES MERCATI_USO (IDCOMUNE,ID);

CREATE TABLE MERCATI_CONTABILITA_TRIBUTI (
     IDCOMUNE VARCHAR2(6 char) NOT NULL
     , ID NUMBER(10) NOT NULL
     , DESCRIZIONE VARCHAR2(200 char) NOT NULL
     , FK_CONTI NUMBER(6) NOT NULL
     , DATA_INIZIO_VALIDITA DATE NOT NULL
     , DATA_FINE_VALIDITA DATE
     , FK_MERCATI_FORMULE NUMBER(10) NOT NULL

);

ALTER TABLE MERCATI_CONTABILITA_TRIBUTI ADD CONSTRAINT PK_MERCATI_CONTABILITA_TRIBUTI PRIMARY KEY (IDCOMUNE,ID);

CREATE TABLE MERCATI_FORMULE_CALCOLO (
     IDCOMUNE VARCHAR2(6 char) NOT NULL
     ,  ID NUMBER(10) NOT NULL
     , DESCRIZIONE VARCHAR2(300 char) NOT NULL
     , DATA_INIZIO_VALIDITA DATE NOT NULL  , DATA_FINE_VALIDITA DATE
     , FORMULA VARCHAR2(400 char) NOT NULL
     , FK_USO NUMBER(4) NOT NULL

);

ALTER TABLE MERCATI_FORMULE_CALCOLO ADD CONSTRAINT PK_MERCATI_FORMULE_CALCOLO  PRIMARY KEY (IDCOMUNE,ID);

ALTER TABLE MERCATI_CONTABILITA_TRIBUTI ADD CONSTRAINT FK_CONT_TRIB_MER_CONTI FOREIGN KEY (IDCOMUNE, FK_CONTI) REFERENCES CONTI (IDCOMUNE,ID);

ALTER TABLE MERCATI_CONTABILITA_TRIBUTI ADD CONSTRAINT FK_CONT_TRIB_MER_FORM  FOREIGN KEY (IDCOMUNE, FK_MERCATI_FORMULE) REFERENCES MERCATI_FORMULE_CALCOLO (IDCOMUNE, ID);

ALTER TABLE MERCATI_FORMULE_CALCOLO ADD CONSTRAINT FK_MERC_FORM_USO  FOREIGN KEY (IDCOMUNE, FK_USO) REFERENCES MERCATI_USO (IDCOMUNE,ID);

CREATE TABLE MERCATI_D_LIVELLO_SERVIZIO (
     IDCOMUNE VARCHAR2(6 char) NOT NULL
     , ID NUMBER (10) NOT NULL
     , FATTORE_MOLTIPLICATIVO NUMBER(5,2) NOT NULL
     , USA_MQ_POSTEGGIO NUMBER(1) NOT NULL
     , DATA_INIZIO DATE NOT NULL
     , DATA_FINE DATE
     , FK_MERCATO_D NUMBER(6) NOT NULL
     , FK_MERC_SERVIZIO NUMBER(10) NOT NULL

);

ALTER TABLE MERCATI_D_LIVELLO_SERVIZIO ADD CONSTRAINT PK_MERCATIDLIVELLOSERV  PRIMARY KEY (IDCOMUNE, ID);

ALTER TABLE MERCATI_D_LIVELLO_SERVIZIO  ADD CONSTRAINT FK_LIV_SERV_MERC_MERC_D FOREIGN KEY (IDCOMUNE,FK_MERCATO_D ) REFERENCES MERCATI_D (IDCOMUNE,IDPOSTEGGIO); ALTER TABLE MERCATI_D_LIVELLO_SERVIZIO ADD CONSTRAINT FK_LIV_MERC_D_LIVEL_SERV  FOREIGN KEY (IDCOMUNE, FK_MERC_SERVIZIO) REFERENCES MERCATI_LIVELLO_SERVIZIO (IDCOMUNE,ID);


ALTER TABLE pay_io_eventi modify DESC_ESITO VARCHAR2(1000);
ALTER TABLE pay_io_eventi modify CODICE_ESITO VARCHAR2(200);

COMMENT on COLUMN pay_richieste.FK_EVENTO is 'RIFERIMENTO AL PRIMO EVENTO DI INPUT DA CUI E'' SCATURITA LA RICHIESTA';

COMMENT on COLUMN pay_richieste.FK_EVENTO_OUT is 'RIFERIMENTO ALL''EVENTO DI OUTPUT CHE RAPPRESENTA L''ULTIMA CHIAMATA ESEGUITA PER SODDISFARE LA RICHIESTA';
alter table pay_richieste  ADD CONSTRAINT FK_RICH_EVENTO_OUT FOREIGN KEY (IDCOMUNE, FK_EVENTO_OUT) REFERENCES pay_io_eventi(IDCOMUNE, ID);

