ALTER TABLE PAY_PROFILI_ENTI_CREDITORI ADD (CODICE_SEGREGAZIONE NUMBER(2,0) );

COMMENT ON COLUMN PAY_PROFILI_ENTI_CREDITORI.CODICE_SEGREGAZIONE IS 'IDENTIFICATIVO NUMERICO DEL PUNTO DI EMISSIONE DEGLI IUV DI UN ENTE CREDITORE.';

ALTER TABLE TIPISOGGETTO MODIFY ORDINE NUMBER(4,0);

CREATE TABLE PAY_CONNECTOR_WS_ENDPOINT 
(
  CODICE_CONNETTORE VARCHAR2(20) NOT NULL 
, ID NUMBER(9,0) NOT NULL 
, ENDPOINT_URL VARCHAR2(256) NOT NULL 
, UTENTE VARCHAR2(50) 
, PASSWORD VARCHAR2(50) 
, TIMEOUT NUMBER(8,0)
, DESCRIZIONE VARCHAR2(100) 
, CONSTRAINT PAY_CONNECTOR_WS_ENDPOINT_PK PRIMARY KEY 
  (
    CODICE_CONNETTORE 
  , ID 
  )
  ENABLE 
);

ALTER TABLE PAY_CONNECTOR_CONFIG ADD (FK_WS_CARICAMENTO NUMBER(9) );

ALTER TABLE PAY_CONNECTOR_CONFIG ADD (FK_WS_ANNULLAMENTO NUMBER(9) );

ALTER TABLE PAY_CONNECTOR_CONFIG ADD (FK_WS_VERIFICA NUMBER(9) );

ALTER TABLE PAY_CONNECTOR_CONFIG ADD (FK_WS_ATTIVA_SESSIONE NUMBER(9) );

ALTER TABLE PAY_CONNECTOR_CONFIG ADD (FK_WS_AVVISO NUMBER(9) );

ALTER TABLE PAY_CONNECTOR_CONFIG ADD (FK_WS_NOTIFICA NUMBER(9) );

ALTER TABLE PAY_CONNECTOR_CONFIG ADD (FK_WS_SECURITY NUMBER(9) );

ALTER TABLE PAY_CONNECTOR_CONFIG ADD CONSTRAINT PAYCONN_FK_WSANNULLAM FOREIGN KEY(CODICE,FK_WS_ANNULLAMENTO) REFERENCES PAY_CONNECTOR_WS_ENDPOINT (CODICE_CONNETTORE, ID);

ALTER TABLE PAY_CONNECTOR_CONFIG ADD CONSTRAINT PAYCONN_FK_WSAVVISO FOREIGN KEY(CODICE,FK_WS_AVVISO) REFERENCES PAY_CONNECTOR_WS_ENDPOINT (CODICE_CONNETTORE,ID);

ALTER TABLE PAY_CONNECTOR_CONFIG ADD CONSTRAINT PAYCONN_FK_WSCARICAM FOREIGN KEY(CODICE,FK_WS_CARICAMENTO) REFERENCES PAY_CONNECTOR_WS_ENDPOINT (CODICE_CONNETTORE,ID) ;

ALTER TABLE PAY_CONNECTOR_CONFIG ADD CONSTRAINT PAYCONN_FK_WSNOTIFICA FOREIGN KEY(CODICE, FK_WS_NOTIFICA) REFERENCES PAY_CONNECTOR_WS_ENDPOINT(CODICE_CONNETTORE,ID);

ALTER TABLE PAY_CONNECTOR_CONFIG ADD CONSTRAINT PAYCONN_FK_WSSEC FOREIGN KEY(CODICE, FK_WS_SECURITY) REFERENCES PAY_CONNECTOR_WS_ENDPOINT(CODICE_CONNETTORE, ID);

ALTER TABLE PAY_CONNECTOR_CONFIG ADD CONSTRAINT PAYCONN_FK_WSSESSIONE FOREIGN KEY (CODICE,FK_WS_ATTIVA_SESSIONE) REFERENCES PAY_CONNECTOR_WS_ENDPOINT(CODICE_CONNETTORE,ID);

ALTER TABLE PAY_CONNECTOR_CONFIG ADD CONSTRAINT PAYCONN_FK_WSVERIFICA FOREIGN KEY(CODICE,FK_WS_VERIFICA ) REFERENCES PAY_CONNECTOR_WS_ENDPOINT (CODICE_CONNETTORE, ID) ;

COMMENT ON COLUMN PAY_CONNECTOR_CONFIG.FK_WS_CARICAMENTO IS 'FK AI PARAMETRI DI CONFIGURAZIONE DEL SERVIZIO PER IL CARICAMENTO DELLE POSIZIONI DEBITORIE';

COMMENT ON COLUMN PAY_CONNECTOR_CONFIG.FK_WS_ANNULLAMENTO IS 'FK AI PARAMETRI DI CONFIGURAZIONE DEL SERVIZIO DI ANNULLAMENTO DELLE POSIZIONI DEBITORIE';

COMMENT ON COLUMN PAY_CONNECTOR_CONFIG.FK_WS_VERIFICA IS 'FK AI PARAMETRI DI CONFIGURAZIONE DEL SERVIZIO DI VERIFICA DELLO STATO DI UNA POSIZIONE DEBITORIA';

COMMENT ON COLUMN PAY_CONNECTOR_CONFIG.FK_WS_ATTIVA_SESSIONE IS 'FK AI PARAMETRI DI CONFIGURAZIONE DEL SERVIZIO DI ATTIVAZIONE DI UNA SESSIONE DI PAGAMENTO';

COMMENT ON COLUMN PAY_CONNECTOR_CONFIG.FK_WS_AVVISO IS 'FK AI PARAMETRI DI CONFIGURAZIONE DEL SERVIZIO DI GENERAZIONE/INVIO DELL''AVVISO DI PAGAMENTO';

COMMENT ON COLUMN PAY_CONNECTOR_CONFIG.FK_WS_NOTIFICA IS 'FK AI PARAMETRI DI CONFIGURAZIONE DEL SERVIZIO ESPOSTO DAL NODO DI RICEZIONE DELLA NOTIFICA DELL''AVVENUTO PAGAMENTO';

COMMENT ON COLUMN PAY_CONNECTOR_CONFIG.FK_WS_SECURITY IS 'FK AI PARAMETRI DI CONFIGURAZIONE DEL SERVIZIO DI GENERAZIONE DEL TOKEN DI SICUREZZA';


ALTER TABLE PAY_PAGAMENTI ADD (ID_PSP VARCHAR2(50) );

ALTER TABLE PAY_PAGAMENTI ADD (RAG_SOC_PSP VARCHAR2(200) );

ALTER TABLE MERCATIPRESENZE_T ADD FLAG_FESTIVO NUMBER(1,0) DEFAULT 0;