alter table INVENTARIOPROCEDIMENTI modify PROCEDIMENTO varchar2(500 CHAR);

alter table TIPIBANDO add (FLAG_MULTIINTERVENTO NUMBER(1, 0));

alter table TIPIGRADUATORIET add (FLAG_PIANOROTAZIONE NUMBER(1, 0));

ALTER TABLE TIPIGRADUATORIET ADD (FLAG_ESPR_ART_TEMP NUMBER(1, 0));

CREATE TABLE BANDI_ALBEROPROC(
IDCOMUNE VARCHAR2(6) NOT NULL,
ID NUMBER (10,0)NOT NULL,
FKIDBANDO NUMBER(6,0) NOT NULL,
FKSCID NUMBER(10,0) NOT NULL, 
ORDINE NUMBER(2,0), 
PERCENTUALE_ESTRAZIONE NUMBER (2,0)
);

ALTER TABLE BANDI_ALBEROPROC ADD CONSTRAINT PK_BANDI_ALBEROPROC PRIMARY KEY (IDCOMUNE,ID);

ALTER TABLE BANDI_ALBEROPROC 
ADD CONSTRAINT FK_BANDIALBEROPROC_BANDI 
FOREIGN KEY (IDCOMUNE,FKIDBANDO) 
REFERENCES BANDI(IDCOMUNE,ID);

ALTER TABLE BANDI_ALBEROPROC 
ADD CONSTRAINT FK_BANDIALBEROPROC_ALBEROPROC 
FOREIGN KEY (IDCOMUNE,FKSCID) 
REFERENCES ALBEROPROC(IDCOMUNE,SC_ID);

CREATE TABLE TIPIGRADT_CFG_ROTAZIONE(
IDCOMUNE VARCHAR2(6) NOT NULL,
ID NUMBER (10,0)NOT NULL,
FK_TIPIGRADUATORIET NUMBER(6,0) NOT NULL,
FK_DYN2CAMPI_POST NUMBER(10,0) NOT NULL,
FK_DYN2CAMPI_USO NUMBER(10,0) NOT NULL,
FLAG_MULTIPLO NUMBER(1,0) 
);

ALTER TABLE TIPIGRADT_CFG_ROTAZIONE ADD CONSTRAINT PK_TIPIGRADT_CFG_ROTAZIONE PRIMARY KEY (IDCOMUNE,ID);

ALTER TABLE TIPIGRADT_CFG_ROTAZIONE 
ADD CONSTRAINT FK_TIPIGRAD_T_ROT 
FOREIGN KEY (IDCOMUNE,FK_TIPIGRADUATORIET) 
REFERENCES TIPIGRADUATORIET(IDCOMUNE,ID);

ALTER TABLE TIPIGRADT_CFG_ROTAZIONE 
ADD CONSTRAINT FK_TIPIGRAD_T_CAMPI_POST
FOREIGN KEY (IDCOMUNE,FK_DYN2CAMPI_POST) 
REFERENCES DYN2_CAMPI(IDCOMUNE,ID);

ALTER TABLE TIPIGRADT_CFG_ROTAZIONE 
ADD CONSTRAINT FK_TIPIGRAD_T_CAMPI_USO
FOREIGN KEY (IDCOMUNE,FK_DYN2CAMPI_USO) 
REFERENCES DYN2_CAMPI(IDCOMUNE,ID);

CREATE TABLE GRADUATORIET_PIANOROTAZIONE(
IDCOMUNE VARCHAR2(6) NOT NULL,
ID NUMBER (10,0)NOT NULL,
FKIDGRADUATORIED NUMBER(9,0) NOT NULL,
FKIDPOSTEGGIO NUMBER(6,0) NOT NULL,
FKIDUSO NUMBER(4,0) NOT NULL,
FKIDISTANZA NUMBER(6,0) NOT NULL
);

ALTER TABLE GRADUATORIET_PIANOROTAZIONE ADD CONSTRAINT PK_GRADUATORIET_PIANOROTAZIONE PRIMARY KEY (IDCOMUNE,ID);

ALTER TABLE GRADUATORIET_PIANOROTAZIONE 
ADD CONSTRAINT FK_GRAD_D_PAINO_ROT 
FOREIGN KEY (IDCOMUNE,FKIDGRADUATORIED) 
REFERENCES GRADUATORIED(IDCOMUNE,ID);

ALTER TABLE GRADUATORIET_PIANOROTAZIONE 
ADD CONSTRAINT FK_GRAD_D_MERCATID
FOREIGN KEY (IDCOMUNE,FKIDPOSTEGGIO) 
REFERENCES MERCATI_D(IDCOMUNE,IDPOSTEGGIO);

ALTER TABLE GRADUATORIET_PIANOROTAZIONE 
ADD CONSTRAINT FK_GRAD_D_MERCATI_USO
FOREIGN KEY (IDCOMUNE,FKIDUSO) 
REFERENCES MERCATI_USO(IDCOMUNE,ID);


ALTER TABLE GRADUATORIET_PIANOROTAZIONE 
ADD CONSTRAINT FK_GRAD_D_ISTANZE
FOREIGN KEY (IDCOMUNE,FKIDISTANZA) 
REFERENCES ISTANZE(IDCOMUNE,CODICEISTANZA);

CREATE TABLE TIPIGRADUATORIET_ESPR_ART(
IDCOMUNE VARCHAR2(6) NOT NULL,
ID NUMBER (10,0)NOT NULL,
FK_TIPIGRADUATORIET NUMBER(6,0) NOT NULL,
FK_DYN2CAMPI_DA_ID NUMBER(10,0) NOT NULL,
FK_DYN2CAMPI_A_ID NUMBER(10,0) NOT NULL,
FK_DYN2CAMPI_POST NUMBER(10,0) NOT NULL,
FLAG_MULTIPLO NUMBER(1,0)
);


ALTER TABLE TIPIGRADUATORIET_ESPR_ART ADD CONSTRAINT PK_TIPIGRADUATORIET_ESPR_ART PRIMARY KEY (IDCOMUNE,ID);

ALTER TABLE TIPIGRADUATORIET_ESPR_ART 
ADD CONSTRAINT FK_TIPIGRADT_ESPR_TIPIGRADT 
FOREIGN KEY (IDCOMUNE,FK_TIPIGRADUATORIET) 
REFERENCES TIPIGRADUATORIET(IDCOMUNE,ID);

ALTER TABLE TIPIGRADUATORIET_ESPR_ART 
ADD CONSTRAINT FK_TIPIGRADT_ESPR_DYN2CAMPI_DA
FOREIGN KEY (IDCOMUNE,FK_DYN2CAMPI_DA_ID) 
REFERENCES DYN2_CAMPI(IDCOMUNE,ID);

ALTER TABLE TIPIGRADUATORIET_ESPR_ART 
ADD CONSTRAINT FK_TIPIGRADT_ESPR_DYN2_CAMPI_A
FOREIGN KEY (IDCOMUNE,FK_DYN2CAMPI_A_ID) 
REFERENCES DYN2_CAMPI(IDCOMUNE,ID);

ALTER TABLE TIPIGRADUATORIET_ESPR_ART 
ADD CONSTRAINT FK_TIPIGRADT_ESPR_DYN2C_POST
FOREIGN KEY (IDCOMUNE,FK_DYN2CAMPI_POST) 
REFERENCES DYN2_CAMPI(IDCOMUNE,ID);

