INSERT INTO pay_connector_config_params (CONFIG_PARAM, DESCRIZIONE) VALUES ('DOCUMENTI_SU_FILESYSTEM', 'Specificando un percorso di una cartella su filesystem il nodo pagamenti salverà i documenti nella cartella specificata. Se la cartella non esiste verrà creata.');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('FVG_SUAP_IN_RETE', 'ALLINEA_SOLO_ENDO', 'Stablisice se allineare solamente gli endoprocedimenti o anche l''albero dei procedimenti. I valori ammessi sono 0 o vuoto (default): viene allineato tutto, 1: vengono allineati solamente gli endoprocedimenti');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_ATTIVO', 'SELEZIONA_ALLEGATI_PEC', 'Se impostato a 1 consente di selezionare quali degli allegati che verranno protocollati devono essere inviati anche per PEC; Se non valorizzato o 0 non sarà possibile fare la distinzione');

INSERT INTO DETT_POSIZIONE_DEBITORIA (IDCOMUNE,ID,ID_POSIZIONE_DEBITORIA,DATA_ULTIMO_STATO,STATO,DESC_STATO) 
(SELECT MERCATIPRESENZE_D.IDCOMUNE,MERCATIPRESENZE_D.FK_PAY_POS_DEB AS ID,
FK_PAY_POS_DEB AS ID_POSIZIONE_DEBITORIA, MAX(PAY_STATO_PAGAMENTI.DATA_EVENTO) AS DATA_ULTIMO_STATO, '.' AS STATO, '.' AS DESC_STATO
FROM MERCATIPRESENZE_D INNER JOIN PAY_POSIZIONI_DEBITORIE ON
PAY_POSIZIONI_DEBITORIE.IDCOMUNE = MERCATIPRESENZE_D.IDCOMUNE AND 
PAY_POSIZIONI_DEBITORIE.ID = MERCATIPRESENZE_D.FK_PAY_POS_DEB LEFT JOIN
DETT_POSIZIONE_DEBITORIA ON
MERCATIPRESENZE_D.IDCOMUNE = DETT_POSIZIONE_DEBITORIA.IDCOMUNE AND
MERCATIPRESENZE_D.FK_PAY_POS_DEB = DETT_POSIZIONE_DEBITORIA.ID
LEFT JOIN PAY_STATO_PAGAMENTI ON 
PAY_STATO_PAGAMENTI.IDCOMUNE = PAY_POSIZIONI_DEBITORIE.IDCOMUNE AND
PAY_STATO_PAGAMENTI.FK_POSIZIONE_DEBITORIA = PAY_POSIZIONI_DEBITORIE.ID
WHERE DETT_POSIZIONE_DEBITORIA.ID IS NULL
GROUP BY MERCATIPRESENZE_D.IDCOMUNE,MERCATIPRESENZE_D.FK_PAY_POS_DEB,
FK_PAY_POS_DEB);


INSERT INTO CLMENU_JAVA(ID, DESCRIZIONE, PAGINA, MENULINK, SOFTWARE, JSP, SOFTWAREESCLUSI, LINK_STANDARD, TIPO_FUNZIONALITA, MENULINK_V2) VALUES 
(1045, 'Livello servizio', 'livelloservizio/list.htm?software=SOFTWARE', '0AZ16', '*', 'JAVA', 'PR,FI', 'livelloservizio/list.htm?software=SOFTWARE', 'S', '0AZ16');    