update CLMENU_JAVA set menulink = '00BS' where id = 1026;
INSERT INTO VERTICALIZZAZIONIBASE (MODULO, DESCRIZIONE) VALUES ('PROTOCOLLO_EPROT', 'Verticalizzazione che serve per gestire il protocollo E-PROT, attualmente in uso all''Arpa Umbria, i servizi sono di tipo rest ed usa autenticazione basic.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_EPROT', 'URL_BASE', 'Parametro che sta ad indicare la url base di dove possono essere invocati i metodi del web service, da notare che il web service è di tipo rest e che viene utilizzata un''autenticazione di tipo basic, questo sta a significare che i metodi vengono inseriti direttamente sulla stringa relativa alla url, ad esempio, se si vuole invocare il metodo di lettura delle tipologie di documento va aggiunto, alla url, "/richiesta_tipi_documento", per il titolario "/richiesta_titolario", per le protocollazioni in entrata e uscita "/richiesta_protocollazione_ingresso" e "/richiesta_protocollazione_uscita, questo comunque viene fatto direttamente dal sistema e non va indicato in questo parametro, dove invece va inserita solamente la url base"');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_EPROT', 'USERNAME', 'Indicare la username per autenticarsi al web service che utilizza un tipo di autenticazione basic, le credenziali sono riferite agli utenti del protocollo.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_EPROT', 'PASSWORD', 'Indicare la password per autenticarsi al web service che utilizza un tipo di autenticazione basic, le credenziali sono riferite agli utenti del protocollo.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_INSIELMERCATO', 'REGISTRO', 'Indicare il registro relativo al protocollo, da questo parametro sarà possibile anche recuperare il parametro officecode che dovrà essere implementato sulla tabella PROTOCOLLO_UFFICIREGISTRI');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_INSIELMERCATO', 'CODICE_UFFICIO_OPERANTE', 'Indica il codice ufficio su cui un utente può operare, di norma va di pari passo con il software (SUAP, EDILIZIA, COMMERCIO....)');
INSERT INTO verticalizzazionibase (modulo, descrizione, flag_gestcomune) VALUES ('PAGAMENTI_LIVORNO', 'Modulo per la gestione dei pagamenti del comune di Livorno',0);
INSERT INTO verticalizzazioniparametribase (modulo, parametro, descrizione) VALUES ('PAGAMENTI_LIVORNO', 'WS_URL', 'Url del web service per la validazione dei codici digitali di pagamento (es.http://wscitel.comune.livorno.it:8080/axis2/services/ws_dia/) ');
INSERT INTO verticalizzazioniparametribase (modulo, parametro, descrizione) VALUES ('PAGAMENTI_LIVORNO', 'ID_CAMPO_DINAMICO', 'Id del campo dinamico in cui viene memorizzato il codice pagamento. Utilizzato per verificare che il codice non sia già stato usato');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) VALUES
('AREA_RISERVATA'
,'REG_INVMAIL_ATTIVA_INVIO'
,'Se attivato allora in fase di registrazione utente verrà inviata una mail all''indirizzo di posta elettronica dell''utente con le informazioni di registrazione. Valori possibili S o N');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) VALUES
('AREA_RISERVATA'
,'REG_INVMAIL_TIPO_MODELLO'
,'Se attivata la funzionalità di invio contestuale di una mail alla registrazione utente il parametro indica un codice valido di Mail/Testo tipo che individua la mail da inviare all''utente');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) VALUES
('AREA_RISERVATA'
,'REG_INVMAIL_LISTA_ID_CALLER'
,'Se attivata la funzionalità di invio mail contestuale alla registrazione utente indica una lista separata da '','' di identificativi ricavati dal token  (es: AREARISERVATA) usato nell''invocazione del WS inserimento anagrafe.');
INSERT INTO  VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_EPROT', 'REGISTRO', 'Parametro dove indicare il codice del registro di protocollo su cui si intende protocollare, è un parametro obbligatorio in quanto va necessariamente specificato nella request sul parametro REGISTRO.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_EGRAMMATA', 'FASCICOLO', 'Questo parametro si rende necessario per le protocollazioni in partenza, dove è obbligatorio indicare il fascicolo, con questo parametro si va ad indicare un fascicolo fisso, il formato da inserire è #ANNO#|NUMERO FASCICOLO|NUMERO SOTTO FASCICOLO dove per #ANNO# si intende l''anno corrente (va inserito proprio come indicato), questo è utile per indicare l''anno corrente e per far si che il sistema modifichi automaticamente l''anno al momento del bisogno. Un esempio su come inserire qusto parametro è: #ANNO#|1|0');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_EGRAMMATA2', 'FASCICOLO', 'Questo parametro si rende necessario per le protocollazioni in partenza, dove è obbligatorio indicare il fascicolo, con questo parametro si va ad indicare un fascicolo fisso, il formato da inserire è #ANNO#|NUMERO FASCICOLO|NUMERO SOTTO FASCICOLO dove per #ANNO# si intende l''anno corrente (va inserito proprio come indicato), questo è utile per indicare l''anno corrente e per far si che il sistema modifichi automaticamente l''anno al momento del bisogno. Un esempio su come inserire qusto parametro è: #ANNO#|1|0');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_DOCER', 'USA_DOCUMENTI_PEC', 'Questo parametro viene utilizzato durante la creazione dell''xml datipec da inviare al web service PEC di DocEr, e sta ad indicare se deve essere compilata la sezione Documenti (valore uguale a 1) o meno (valore diverso da 1 o non presente). Questo parametro si è reso necessario in quanto sono presenti due xsd differenti in DocEr uno dove è presente e obbligatorio compilare la sezione Documenti e uno no. In teoria il verticale (VBG) dovrebbe utilizzare l''xsd dove non è presente il nodo Documenti (lo dovrebbe utilizzare solamente il provider di protocollazione) ma abbiamo visto che questa parte non è ben chiara in quanto in alcune installazioni l''xsd di docer è uno in altre è un altro. Quindi, in attesa di chiarire la situzione si è previsto entrambe le soluzioni.');
