UPDATE METADATI_DIZ_BASE SET CONTESTO='I' WHERE CONTESTO IS NULL;

insert into metadati_diz_base (id, label,descrizione,contesto) values ('INITMD_COMUNE_ISTANZA','Comune dell''istanza','Viene riportato il comune dell''istanza','I');
insert into metadati_diz_base (id, label,descrizione,contesto) values ('INITMD_DATA_PROT_ISTANZA','Data protocollo dell''istanza','Viene riportata la data di protocollo dell''istanza','I');
insert into metadati_diz_base (id, label,descrizione,contesto) values ('INITMD_NUM_PROT_ISTANZA','Numero protocollo dell''istanza','Viene riportato il numero di protocollo dell''istanza','I');
insert into metadati_diz_base (id, label,descrizione,contesto) values ('INITMD_AZIENDA_PIVA','Partita IVA dell''azienda','Viene riportata la partita IVA dell''azienda dell''istanza','I');
insert into metadati_diz_base (id, label,descrizione,contesto) values ('INITMD_OGGETTO_ISTANZA','Oggetto dell''istanza','Viene riportato l''oggetto dell''istanza','I');
insert into metadati_diz_base (id, label,descrizione,contesto) values ('INITMD_INTERM_DESCRIZIONE','Nome e cognome dell''intermediario','Viene riportato il nome ed il cognome dell''intermediario incaricato','I');
insert into metadati_diz_base (id, label,descrizione,contesto) values ('INITMD_INTERM_CF','Codice fiscale dell''intermediario','Viene riportato il codice fiscale dell''intermediario incaricato','I');
insert into metadati_diz_base (id, label,descrizione,contesto) values ('INITMD_INTERM_PIVA','Partita IVA dell''intermediario','Viene riportata la partita IVA dell''intermediario incaricato','I');
insert into metadati_diz_base (id, label,descrizione,contesto) values ('INITMD_MOV_DESCRIZIONE','Descrizione del movimento','Viene riportata la descrizione del movimento/fase dell''iter della pratica','M');
insert into metadati_diz_base (id, label,descrizione,contesto) values ('INITMD_MOV_DATA','Data del movimento','Viene riportata la data del movimento/fase dell''iter della pratica','M');
insert into metadati_diz_base (id, label,descrizione,contesto) values ('INITMD_MOV_DATAPROT','Data del protocollo del movimento','Viene riportata la data del protocollo del movimento/fase dell''iter della pratica','M');
insert into metadati_diz_base (id, label,descrizione,contesto) values ('INITMD_MOV_NUMPROT','Numero del protocollo del movimento','Viene riportato il numero del protocollo del movimento/fase dell''iter della pratica','M');

INSERT INTO  VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_IRIDE', 'USA_NUM_ANNO_LEGGI', 'Questo parametro serve per indicare al plugin del protocollo per capire se la lettura del protocollo deve essere fatta invocando il metodo LeggiProtocollo oppure LeggiDocumento, nel primo caso la chiamata viene fatta passando il numero e l''anno del protocollo, nel secondo l''id del documento, di default, se valorizzato il campo FKIDPROTOCOLLO delle ISTANZE o MOVIMENTO viene invocato il metodo LeggiDocumento, valorizzando questo parametro a 1 il sistema forza la chiamata sempre utilizzando il metodo LeggiProtocollo, questo perchè il nuovo ws retrocompatibile IRIDE di Maggioli ha un bug su leggi documento che non ritorna gli allegati.');
insert into VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) values ('FILESYSTEM_CMIS', 'TIPO_DOCUMENTO_CMIS','L''object_type_id se diverso da "cmis:document". E'' importante perché ogni ente potrebbe avere il proprio e objectId' );

insert into VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, descrizione) values('AREA_RISERVATA','INTESTAZIONE_CERTIFICATO_INVIO','Testo da inserire nell''intestazione della pagina del certificato di invio');
insert into VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, descrizione) values('WSANAGRAFE_PARIX','CERCA_SOLO_CF','Se impostato a 1 allora ricerca le anagrafiche parix solamente per codice fiscale impresa');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_GEPROT', 'INVIO_PEC', 'Parametro che indica se deve essere attivata la funzionalità di invio pec per le protocollazioni in partenza, valorizzare a 1 se si desidera fare in modo che il sistema invii una pec per conto del sistema di protocollo, valorizzare con qualsiasi altro valore (meglio se 0 o non valorizzato) se si desidera che il sistema non invii una pec. Nel caso in cui sia attivo questo parametro (valore 1) il componente andrà ad invocare il metodo inviaEMail del web service di protocollo messo a disposizione da Sistematica.');
insert into VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, descrizione) values('PROTOCOLLO_ATTIVO','FLUSSO_MOSTRATO_DEFAULT','Se attivato, permette di impostare il flusso da mostrare di default nella maschera di protocollazione. Potrà assumere i seguenti valori: 1. Codice del Flusso (Es ''A'' : Arrivo) : Il Flusso proposto dalla maschera sarà quello per il codice inserito. 2. ''-'' : Verrà proposto nella maschera il valore "Seleziona". 3. Stringa vuota : Mantiene il comportamento attuale.');

INSERT INTO VERTICALIZZAZIONIBASE (MODULO, DESCRIZIONE, FLAG_GESTCOMUNE) VALUES ('PROTOCOLLO_KIBERNETES', 'Se attivo consente la protocollazione tramite il componente che si integra con il protocollo della ditta KIBERNETES.', '1');
INSERT INTO  VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_ATTIVO', 'NOMEFILE_MAXLENGTH', 'Indicare, con un valore intero, il numero massimo di caratteri, compresa l''estensione, che può contenere il nome file degli allegati che vengono inviati al protocollo. In caso di omissione di questo parametro il comportamento sarà quello indicato dal parametro NOMEFILE_ORIGINE di questa regola (PROTOCOLLO_ATTIVO), in caso di valorizzazione questo parametro avrà la precedenza. Ad esempio, se il parametro NOMEFILE_ORIGINE è impostato a 3 (quindi limitazione a 30 caratteri della descrizione), e questo parametro a 40, il nome file avrà la lunghezza di 40 caratteri.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) Values ('AUTENTICAZIONE_LDAP','LDAP_SEARCH_BASE_DN','Path dove effettuare la search dell''utente (utilizzato per la login in modalita search)');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) Values ('AUTENTICAZIONE_LDAP','LDAP_SEARCH_QUERY_FILTER','Query filter per ricercare un determinato utente registrato nel dominio (utilizzato per la login in modalita search) ');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_KIBERNETES', 'CODICEISTAT', 'E'' il codice con cui viene identificato l''ente sul sistema di protocollo e va indicato da tutti i metodi del web service, in genere viene valorizzato proprio con il codice istat del comune interessato, tuttavia si può ricavare invocando il metodo GetElencoIstat del web service.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_KIBERNETES', 'URL', 'Indicare l''indirizzo endpoint dove è installato il web service Kibernetes.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_KIBERNETES', 'USERNAME', 'Indicare in questo parametro lo username di accesso al web service, tenendo presente che i web service necessitano di autenticazione preemptive.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_KIBERNETES', 'PASSWORD', 'Indicare in questo parametro la password di accesso al web service (strettamente legata al parametro USERNAME chiaramente), tenendo presente che i web service necessitano di autenticazione preemptive.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_KIBERNETES', 'UFFICIO_PROTOCOLLANTE', 'Indicare l''ufficio UO che si occupa di protocollare, da non confondere con l''ufficio assegnatario che viene valorizzato con l''UO e RUOLO delle amministrazioni, anche se gli archivi da dove recuperare questo dato sono sempre gli stessi, ed è possibile interrogarli tramite il metodo search4UO.');
