# PARAMETRI DI DEPLOY
servizi.resolver.filter.path.ammessi=

# WEB SERVICE SECURITY
ws.token.pwd=REDACTED
ws.token.url=REDACTED
ws.token.user=REDACTED
ws.token.default.alias=CONSOLE

# CERTIFICATO PER VERIFICARE LA FIRMA DELL'AUTENTICAZIONE
authentication.public.key.cert=publicKeyAccettatore.cer

# possibilità di accedere ai servizi solo da url paranti Es: /d612/nuovadomanda
# se true allora solamente gli URL intercettati da ServiziResolverFilter saranno accedibili 
servizi.accedi-se-attiva-session=true

# DATI PER ACCESSO TRAMITE SERVIZIO
servizi.idcomunealias=CONSOLE
servizi.software=SS
# CODICE FISCALE DELL'UTENTE PER I SERVIZI ANONIMI (DEVE ESSERE PRESENTE IN ANAGRAFE)
servizi.userid=GGGGGGGGGGGGGGGG

app.aspnet=consolle-net-bo

# WEB SERVICE STC
ws.stc.url=REDACTED
ws.stc.user=REDACTED
ws.stc.pwd=REDACTED
ws.stc.id-nodo-mitt=1200
ws.stc.id-nodo-dest=400
ws.stc.timeout=300000

# CODICE FISCALE DELL'UTENTE UTILIZZATO DALL'NLA PER LA LOGIN APPLICATIVA (DEVE ESSERE PRESENTE IN ANAGRAFE)
nla.userid=GGGGGGGGGGGGGGGG

# FORCE HTTPS (se true forza la navigazione in https)
forceHttps=false

# PARAMETRI CART
# LISTA DEI CODICI_ENDO_REGIONALI SEPARATI DA VIRGOLA
cart.codici_endo_regionali.attivabili=ASL 1.E,ASL 2.E,ASL 3.E,ASL 7.E,ASL 8.E,ASL 10.E,ASL 9.E,ASL 11.E,ASL 12.E,ASL 13,ASL 13.1,ASL 13.2,ASL 14,ASL 15,ASL 16,ASL 16.1,ASL 16.2,ASL 17,ASL 18,ASL 19,ASL 20,ASL 21,ASL 21.1,ASL 22,ASL 23,ASL 24,ASL 25,ASL 26,ASL 27,ASL 28,ASL 29,ASL 30,ASL 31,ASL 32,ASL 33,ASL 34.1,ASL 34.2,ASL 34.3,ASL 35,ASL 36,ASL 37,ASL 34,ASL 39,ASL 40,ASL 38,ASL 41,ASL 42,ASL 43,ASL 44,ASL 45,ASL 46,ASL 47,ASL 48,ASL 49,ASL 50,ASL 51,ASL 52.1,ASL 52.2,ASL 52.3,ASL 52.4,ASL 52.5,ASL 53.1,ASL 53.2,ASL 53.3,ASL 53.4,ASL 54.1,ASL 54.2,ASL 54.3,ASL 54.4,ASL 54.5,ASL 54.6,ASL 56,ASL 57,ASL 58,ASL 59,ASL 60,ASL 61.1,ASL 61.2,ASL 62,ASL 63,ASL 64,ASL 65,ASL 66,ASL 67.1,ASL 67.2,ASL 68.1,ASL 68.2,ASL 69,ASL 68,ASL 70,ASL 71,ASL 72,ASL 73,ASL 74,ASL 75,ASL 76.1,ASL 76.2,ASL 76.3,ASL 78,ASL 79,ASL 80,ASL 81,ASL 82,ASL 83,ASL 84,ASL 85,ASL 86,ASL 16.3,ASL 51.1,ASL 62.1,ASL 62.2,ASL 62.3,ASL 62.4,ASL 63.1,ASL 63.2,ASL 63.3,ASL 63.4,ASL 63.5,ASL 67.3,ASL 70.1,ASL 70.2,ASL 70.3,ASL 70.4,PROV-1,PROV-2,PROV-3,PROV-4,PROV-5,PROV-6,PROVA

# WEB SERVICE REPORT (SP2CON)
lineacomune.ws.report.enable=false
lineacomune.ws.report.url=REDACTED
# WEB SERVICE FILETEMPORANEI (SP2CON)
lineacomune.ws.filetemporanei.enable=false
lineacomune.ws.filetemporanei.url=REDACTED
lineacomune.ws.filetemporanei.mtom=true

# WEB SERVICE PARIXGATE
ws.parixgate.url=REDACTED
ws.parixgate.user=REDACTED
ws.parixgate.psw=parix62649
ws.parixgate.switchcontroll=\u0020

# AUTHENTICATION WS PARIX GATE (Parametri del key store e password)
javax.net.ssl.trustStore=/usr/java/jdk1.6.0_45/jre/lib/security/cacerts
javax.net.ssl.trustStorePassword=REDACTED
javax.net.ssl.keyStore=/usr/java/jdk1.6.0_45/jre/lib/security/cacerts
javax.net.ssl.keyStorePassword=REDACTED
