# Comment out the Log4J listener in web.xml to activate Log4J.
log4j.rootLogger=ERROR, logfile

log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d %p [%c] servizi-ws - <%m>%n
 
log4j.appender.logfile=org.apache.log4j.RollingFileAppender
log4j.appender.logfile.File=${catalina.base}/logs/suap-accettatore.log
log4j.appender.logfile.MaxFileSize=1024KB
log4j.appender.logfile.MaxBackupIndex=10
log4j.appender.logfile.layout=org.apache.log4j.PatternLayout
log4j.appender.logfile.layout.ConversionPattern=%d %p [%c] - %m%n


log4j.logger.it.gruppoinit.sigepro.cart=ERROR
log4j.logger.it.gruppoinit.pal.gp.areariservata.cartfacct=ERROR
log4j.logger.it.gruppoinit.pal.gp.areariservata.filter=ERROR
log4j.logger.it.gruppoinit.pal.gp.areariservata.filter.TokenAuthenticationFilter=ERROR
log4j.logger.it.gruppoinit.pal.gp.areariservata.filter.TokenPartnerAppAuthenticationFilter=ERROR
log4j.logger.it.gruppoinit.pal.gp.areariservata.filter.IdComuneFilter=ERROR
log4j.logger.it.gruppoinit.pal.gp.areariservata.filter.RegistrationFilter=ERROR
log4j.logger.it.gruppoinit.pal.gp.areariservata.web=ERROR
log4j.logger.it.gruppoinit.pal.gp.areariservata.web.nuovaistanza=ERROR
#lasciare a INFO per vedere i passaggi dell'invio pratica
log4j.logger.it.gruppoinit.pal.gp.areariservata.web.nuovaistanza.NuovaIstanzaRiepilogoController=ERROR
log4j.logger.it.gruppoinit.pal.gp.areariservata.web.FileController=ERROR
log4j.logger.it.gruppoinit.pal.gp.areariservata.web.handler=ERROR
log4j.logger.it.gruppoinit.pal.gp.core.service.impl=ERROR
log4j.logger.it.lineacomune.ws=INFO
#TRACE visualizza xml domanda
log4j.logger.it.gruppoinit.pal.gp.areariservata.service.impl.NuovaIstanzaServiceImpl=ERROR
log4j.logger.it.gruppoinit.pal.gp.areariservata.service.impl.FirmaDigitaleServiceImpl=ERROR
log4j.logger.it.gruppoinit.pal.gp.areariservata.service.impl=ERROR
log4j.logger.it.gruppoinit.pal.gp.core.service.impl.=ERROR
#log per rfc 239
log4j.logger.it.gruppoinit.pal.gp.core.service.impl.SemProxyServiceImpl=INFO
log4j.logger.it.gruppoinit.pal.gp.core.service.impl.CartPresentazioneDomandaRfc239ServiceImpl=INFO
log4j.logger.it.gruppoinit.pal.gp.core.service.impl.CartPresentazioneDomandaRfc183ServiceImpl=INFO
log4j.logger.it.gruppoinit.pal.gp.core.service.impl.DomandeFrontOfficeServiceImpl=INFO
log4j.logger.it.gruppoinit.pal.gp.cartfacct.web.CartController=INFO
log4j.logger.org.apache=ERROR
log4j.logger.org.apache.velocity=OFF
log4j.logger.org.springframework=ERROR
log4j.logger.org.hibernate=ERROR
log4j.logger.org.apache.cxf=ERROR
#log delle chiamate soap(INFO=on,WARN=off)
log4j.logger.org.apache.cxf.services=ERROR

## impostare a DEBUG per visualizzare le query ed i parametri di binding(impostare type a TRACE per visualizzare anche i parametri di ritorno)
log4j.logger.org.hibernate.SQL=ERROR
log4j.logger.org.hibernate.type=ERROR

log4j.logger.it.gruppoinit.auditing.ricezione_stimoli_sem=ERROR
#log4j.logger.org.hibernate.cache=WARN
#log4j.logger.org.hibernate.jdbc=WARN
#log4j.logger.org.hibernate.type.AnyType=WARN
#log4j.logger.org.hibernate.type.BigDecimalType=WARN
#log4j.logger.org.hibernate.type.BigIntegerType=WARN
#log4j.logger.org.hibernate.type.BooleanType=WARN
#log4j.logger.org.hibernate.type.ByteType=WARN
#log4j.logger.org.hibernate.type.CalendarDateType=WARN
#log4j.logger.org.hibernate.type.CalendarType=WARN
#log4j.logger.org.hibernate.type.CharacterType=WARN
#log4j.logger.org.hibernate.type.DateType=WARN
#log4j.logger.org.hibernate.type.DbTimestampType=WARN
#log4j.logger.org.hibernate.type.DoubleType=WARN
#log4j.logger.org.hibernate.type.FloatType=WARN
#log4j.logger.org.hibernate.type.IdentifierBagType=WARN
#log4j.logger.org.hibernate.type.IntegerType=WARN
#log4j.logger.org.hibernate.type.LongType=WARN
#log4j.logger.org.hibernate.type.NullableType=WARN
#log4j.logger.org.hibernate.type.NumericBooleanType=WARN
#log4j.logger.org.hibernate.type.ShortType=WARN
#log4j.logger.org.hibernate.type.StringClobType=WARN
#log4j.logger.org.hibernate.type.StringType=WARN
#log4j.logger.org.hibernate.type.TextType=WARN
#log4j.logger.org.hibernate.type.TimestampType=WARN
#log4j.logger.org.hibernate.type.TimeType=WARN

log4j.logger.it.toscana.regione.suap.comunica=DEBUG, COMUNICAADAPTER_APPENDER 
log4j.logger.it.eng.suap.xengine.copertina=DEBUG, COMUNICAADAPTER_APPENDER
log4j.logger.it.toscana.regione.interoperability.cart=DEBUG, COMUNICAADAPTER_APPENDER
log4j.additivity.it.toscana.regione.suap.comunica=false 
log4j.additivity.it.eng.suap.xengine.copertina=false
log4j.additivity.it.toscana.regione.interoperability.cart=false 
log4j.appender.COMUNICAADAPTER_APPENDER=org.apache.log4j.RollingFileAppender
log4j.appender.COMUNICAADAPTER_APPENDER.File=${catalina.base}/logs/comunica-adapter.log
log4j.appender.COMUNICAADAPTER_APPENDER.layout=org.apache.log4j.PatternLayout
log4j.appender.COMUNICAADAPTER_APPENDER.layout.ConversionPattern=[%d{ISO8601}] %5p [%t] - %m%n
log4j.appender.COMUNICAADAPTER_APPENDER.MaxFileSize=5MB
log4j.appender.COMUNICAADAPTER_APPENDER.MaxBackupIndex=3

## c3p0 logger
#log4j.logger.com.mchange=WARN

# Axis
log4j.logger.org.apache.axis.transport.http.HTTPSender=ERROR
log4j.logger.org.apache.axis.client.Call=ERROR
log4j.logger.org.apache.axis.client.AxisClient=ERROR
log4j.logger.org.codehaus.xfire=ERROR
