ALTER TABLE INVENTARIOPROC_TIPITITOLO MODIFY TIPOTITOLO VARCHAR(400);
ALTER TABLE ALBEROPROC ADD LIVELLO_AUTENTICAZIONE NUMERIC(1, 0);
ALTER TABLE TEMP_LINKALLEGATI MODIFY NOMEDOCUMENTO VARCHAR(4000) NOT NULL;
CREATE INDEX IDX_IATTIVITANAPSHOT_001 ON I_ATTIVITA_SNAPSHOT (IDCOMUNE,FK_IA_ID);
CREATE INDEX IDX_DYN2MODELLID_001 ON DYN2_MODELLID(IDCOMUNE,FK_D2MT_ID, FK_D2C_ID);

ALTER TABLE TIPIPROCEDURE ADD FLAG_CHIUSURA_AUT NUMERIC(1,0) DEFAULT 0;
ALTER TABLE TIPIPROCEDURE ADD FK_STATO_CHIUS VARCHAR(2);
ALTER TABLE TIPIPROCEDURE ADD CONSTRAINT FK_TIPIPROC_STATIIST FOREIGN KEY (IDCOMUNE,SOFTWARE,FK_STATO_CHIUS) REFERENCES STATIISTANZA(IDCOMUNE,SOFTWARE,CODICESTATO);
