ALTER TABLE RUOLI ADD COD_DOCER VARCHAR(50);
ALTER TABLE RESPONSABILI ADD COD_UTE_DOCER VARCHAR(30);
ALTER TABLE RESPONSABILI ADD PASSWORD_UTE_DOCER VARCHAR(30);

CREATE TABLE OGGETTI_DOCER (
IDCOMUNE VARCHAR(6) NOT NULL,
ID NUMERIC(10,0) NOT NULL,
CODICEOGGETTO NUMERIC(10) NOT NULL,
DOC_ID VARCHAR(50),
UDOC_ID VARCHAR(50)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE OGGETTI_DOCER ADD CONSTRAINT PK_OGGETTIDOCER PRIMARY KEY(IDCOMUNE, ID);
ALTER TABLE OGGETTI_DOCER ADD CONSTRAINT FK_OGGETTIDOCER_OGGETTI FOREIGN KEY (IDCOMUNE, CODICEOGGETTO) REFERENCES OGGETTI (IDCOMUNE, CODICEOGGETTO);

CREATE TABLE METADATI_DIZ_BASE(
ID VARCHAR(30) NOT NULL,
LABEL VARCHAR(100) NOT NULL,
DESCRIZIONE VARCHAR(500) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE METADATI_DIZ_BASE ADD CONSTRAINT PK_METADATIDIZBASE PRIMARY KEY(ID);

CREATE TABLE PROT_TIPIDOCUMENTO_METADATI(
IDCOMUNE VARCHAR(6) NOT NULL,
FKIDPROTTPDOC NUMERIC(10,0) NOT NULL,
FKIDMETADATIDIZBASE VARCHAR(30) NOT NULL 
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE PROT_TIPIDOCUMENTO_METADATI ADD CONSTRAINT PK_TIPIDOCUMENTO_METADATI PRIMARY KEY (IDCOMUNE,FKIDPROTTPDOC,FKIDMETADATIDIZBASE);
ALTER TABLE PROT_TIPIDOCUMENTO_METADATI ADD CONSTRAINT FK_TIPIDOCUMENTOMD_TIPIDOC FOREIGN KEY (IDCOMUNE,FKIDPROTTPDOC) REFERENCES PROTOCOLLO_TIPIDOCUMENTO(IDCOMUNE,ID);
ALTER TABLE PROT_TIPIDOCUMENTO_METADATI ADD CONSTRAINT FK_TIPIDOCUMENTOMD_MDDZBASE FOREIGN KEY (FKIDMETADATIDIZBASE) REFERENCES METADATI_DIZ_BASE(ID);

ALTER TABLE DOCUMENTIISTANZA ADD ID_DOCER VARCHAR(50);
ALTER TABLE TIPOLOGIAREGISTRI ADD COD_REGISTRO_DOCER VARCHAR(50);
ALTER TABLE PROTOCOLLO_TIPIDOCUMENTO MODIFY CODICE VARCHAR(30);

ALTER TABLE ARCHIVIAZIONI ADD SOFTWARE VARCHAR(2);
ALTER TABLE ARCHIVIAZIONI ADD CONSTRAINT FK_ARCHIVIAZIONI_SOFTWARE FOREIGN KEY (SOFTWARE) REFERENCES SOFTWARE (CODICE);
ALTER TABLE JOB_REPOSITORY ADD SOFTWARE VARCHAR(2);


CREATE TABLE DYN2_REGOLE 
(
  IDCOMUNE VARCHAR(6) NOT NULL 
, ID NUMERIC(10,0) NOT NULL 
, DESCRIZIONE VARCHAR(200) NOT NULL 
, SOFTWARE VARCHAR(2)
, CONSTRAINT DYN2_REGOLE_PK PRIMARY KEY 
  (
    IDCOMUNE
  , ID 
  )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;;

CREATE TABLE DYN2_ESPRESSIONI 
(
  IDCOMUNE VARCHAR(6) NOT NULL 
, ID NUMERIC(10,0) NOT NULL 
, FK_REGOLA NUMERIC(10,0) NOT NULL 
, PROGRESSIVO NUMERIC(3, 0) NOT NULL 
, OPERATORE_LOGICO VARCHAR(5) 
, PARENTESI_APERTA VARCHAR(1) 
, FK_CAMPO NUMERIC(10,0)
, ATTRIBUTO_STC VARCHAR(200) 
, ID_SEMANTICO_CART VARCHAR(50) 
, OPERATORE_CONFRONTO VARCHAR(20) DEFAULT 'EQ' NOT NULL 
, VALORE_CONFRONTO VARCHAR(400)
, PARENTESI_CHIUSA VARCHAR(1)
, CONSTRAINT DYN2_ESPRESSIONI_PK PRIMARY KEY 
  (
    IDCOMUNE 
  , ID 
  )
 
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE DYN2_ESPRESSIONI ADD CONSTRAINT DYN2EXP_UK_PROGRESSIVO UNIQUE (IDCOMUNE,FK_REGOLA,PROGRESSIVO);

ALTER TABLE DYN2_ESPRESSIONI ADD CONSTRAINT DYN2EXP_FK_REGOLE FOREIGN KEY (IDCOMUNE,FK_REGOLA) REFERENCES DYN2_REGOLE (IDCOMUNE,ID) ON DELETE CASCADE;

ALTER TABLE DYN2_ESPRESSIONI ADD CONSTRAINT DYN2EXP_FK_CAMPO FOREIGN KEY (IDCOMUNE,FK_CAMPO) REFERENCES DYN2_CAMPI(IDCOMUNE,ID);
ALTER TABLE DYN2_ESPRESSIONI ADD CONSTRAINT DYN2EXP_CHK_OPCONFRONTO CHECK (OPERATORE_CONFRONTO IN ('EQ','NOT_EQ','GT','GT_EQ','LT','LT_EQ','IS_NULL','NOT_IS_NULL','IN','NOT_IN','MATCHES','NOT_MATCHES')) ;
ALTER TABLE DYN2_ESPRESSIONI ADD CONSTRAINT DYN2EXP_CHK_OPLOGICO CHECK (OPERATORE_LOGICO IN ('AND', 'OR')) ;
ALTER TABLE DYN2_ESPRESSIONI ADD CONSTRAINT DYN2EXP_CHK_PARAPERTA CHECK (PARENTESI_APERTA IN ('(')) ;

ALTER TABLE DYN2_ESPRESSIONI ADD CONSTRAINT DYN2EXP_CHK_PARCHIUSA CHECK (PARENTESI_CHIUSA IN (')')) ;
ALTER TABLE DYN2_MODELLID ADD FK_REGOLA_ATTIVO NUMERIC(10,0);
ALTER TABLE DYN2_MODELLID ADD FLG_OBBLIGATORIO NUMERIC(1, 0) DEFAULT 0;
ALTER TABLE DYN2_MODELLID ADD CONSTRAINT FK_DYN2MODED_DYN2REG_ATT FOREIGN KEY ( IDCOMUNE, FK_REGOLA_ATTIVO) REFERENCES DYN2_REGOLE (IDCOMUNE, ID);
ALTER TABLE DYN2_MODELLID ADD CONSTRAINT DYN2MODED_CHK_FLGOBB CHECK (FLG_OBBLIGATORIO IN (0, 1));

ALTER TABLE I_ATTIVITA MODIFY DENOMINAZIONE VARCHAR(700);
ALTER TABLE I_ATTIVITA_SNAPSHOT MODIFY DENOMINAZIONE VARCHAR(700);

CREATE TABLE ELENCOCASSAEDILEBASE(
  CODICE VARCHAR(4) NOT NULL,
  DESCRIZIONE VARCHAR(100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE ELENCOCASSAEDILEBASE ADD CONSTRAINT PK_ELENCOCASSAEDILEBASE PRIMARY KEY (CODICE);



ALTER TABLE ANAGRAFE ADD CASSAEDILE_MATRICOLA VARCHAR(10);
ALTER TABLE ANAGRAFE ADD CASSAEDILE_CODICESEDE VARCHAR(4);
ALTER TABLE ANAGRAFESTORICO ADD CASSAEDILE_MATRICOLA VARCHAR(10);
ALTER TABLE ANAGRAFESTORICO ADD CASSAEDILE_CODICESEDE  VARCHAR(4);

ALTER TABLE ANAGRAFE ADD CONSTRAINT FK_ANAG_ELENCOCASSAEDILE FOREIGN KEY (CASSAEDILE_CODICESEDE) REFERENCES ELENCOCASSAEDILEBASE (CODICE);

ALTER TABLE ANAGRAFESTORICO ADD CONSTRAINT FK_ANAGSTO_ELENCOCASSAEDILE FOREIGN KEY (CASSAEDILE_CODICESEDE) REFERENCES ELENCOCASSAEDILEBASE (CODICE);
