INSERT INTO comuni (CODICECOMUNE, COMUNE, SIGLAPROVINCIA, PROVINCIA, REGIONE, CAP, CF, CODICEISTAT, CODICEISTATREGIONE, CODICESTATOESTERO)
VALUES('I694','SESTRI PONENTE','GE','GENOVA','LIGURIA','16121','I694','016121','07',NULL);


INSERT INTO comuni (CODICECOMUNE, COMUNE, SIGLAPROVINCIA, PROVINCIA, REGIONE, CAP, CF, CODICEISTAT, CODICEISTATREGIONE, CODICESTATOESTERO)
VALUES('G231','PAGANICA','AQ','L''AQUILA','ABRUZZO','66804','G231','066804','13',NULL);

INSERT INTO comuni (CODICECOMUNE, COMUNE, SIGLAPROVINCIA, PROVINCIA, REGIONE, CAP, CF, CODICEISTAT, CODICEISTATREGIONE, CODICESTATOESTERO)
VALUES('H613','ROVERSANO','FC','FORLI''','EMILIA ROMAGNA','40803','H613','040803','08',NULL);

INSERT INTO VERTICALIZZAZIONIBASE (MODULO, DESCRIZIONE, FLAG_GESTCOMUNE) VALUES ('PROTOCOLLO_ELIOS', 'E'' il protocollo gestito dalla ditta E-Lios', '1');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_ELIOS', 'URL_PROTOCOLLO', 'Url di base per accedere alla lista dei servizi SOAP di integrazione con il protocollo. Es: http://185.199.49.8/WSElios/wsProtocollo.php');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_ELIOS', 'UTENTE', 'Utente utilizzato per l''autenticazione applicativa per le chiamate ai vari servizi');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_ELIOS', 'PASSWORD', 'Password utilizzata per l''autenticazione applicativa per le chiamate ai vari servizi');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_ELIOS', 'URL_AUTENTICAZIONE', 'Url di base per l''autenticazione applicativa. Es: http://185.199.49.8/WSElios/wsLogin.php');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_ELIOS', 'URL_CONFIGURAZIONE', 'Url di base per recuperare la configurazione del protocollo (classifiche, organigramma, ... ). Es: http://185.199.49.8/WSElios/wsConfigurazione.php');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_ELIOS', 'AREAOMOGENEA', 'Identificativo dell''area omogenea su cui avviene la protocollazione');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_ELIOS', 'ENTE', 'Nominativo dell''ente all''interno dell''applicativo del protocollo');


INSERT INTO comuni (CODICECOMUNE, COMUNE, SIGLAPROVINCIA, PROVINCIA, REGIONE, CAP, CF, CODICEISTAT, CODICEISTATREGIONE, CODICESTATOESTERO)
VALUES('M154','ZELARINO','VE','VENEZIA','VENETO','27808','M154','027808','05',NULL);
