## SECURITY
ws.token.url=REDACTED
ws.token.user=REDACTED
ws.token.pwd=REDACTED


## STC
stc.url=REDACTED
stc.userid=	SANZIONI
stc.password=REDACTED
stc.mtom=true
stc.timeout=480000


##Nodo mittente
stc.idNodoMittente=3400
stc.idEnteMittente=SANZIONI
stc.idSportelloMittente=SANZIONI
## Nodo destinatario
stc.idNodoDestinatario=400
## Lasciate vuoro se vogliamo ricavarlo dinamicamente dalla chiamata al NLA WS da parte del backoffice
stc.idSportelloDestinatario=CO

## WS OGGETTI
oggetti.ws.url=REDACTED
oggetti.ws.mtom=true
oggetti.ws.timeout=120000
oggetti.ws.attach.logging.interceptors=true


#BACKEND
ws.backend.url=REDACTED

#  CATEGORIA SANZIONI
categoria.sanzioni=Acconciatore,Altro,Artigiano,Cartelli pubblicitar,Circolo con somministrazione,Commercio grande struttura,Commercio in area pubblica,Commercio media struttura,Commercio vicinato,Estetista,Pubblico esercizio,Struttura ricettiva

# Codice comune nodo attivo

comune.attivo=E256
