ALTER TABLE INVENTARIOPROC_TIPITITOLO MODIFY TIPOTITOLO VARCHAR2(400);
ALTER TABLE ALBEROPROC ADD (LIVELLO_AUTENTICAZIONE NUMBER(1, 0));
ALTER TABLE TEMP_LINKALLEGATI MODIFY (NOMEDOCUMENTO VARCHAR2(4000) NOT NULL);
CREATE INDEX IDX_IATTIVITANAPSHOT_001 ON I_ATTIVITA_SNAPSHOT (IDCOMUNE,FK_IA_ID);
CREATE INDEX IDX_DYN2MODELLID_001 ON DYN2_MODELLID(IDCOMUNE,FK_D2MT_ID, FK_D2C_ID);

ALTER TABLE TIPIPROCEDURE ADD FLAG_CHIUSURA_AUT NUMBER(1,0) DEFAULT 0;
ALTER TABLE TIPIPROCEDURE ADD FK_STATO_CHIUS VARCHAR2(2);
ALTER TABLE TIPIPROCEDURE ADD CONSTRAINT FK_TIPIPROC_STATIIST FOREIGN KEY (IDCOMUNE,SOFTWARE,FK_STATO_CHIUS) REFERENCES STATIISTANZA(IDCOMUNE,SOFTWARE,CODICESTATO);
COMMENT ON COLUMN TIPIPROCEDURE.FLAG_CHIUSURA_AUT IS 'SE IMPOSTATO AD 1 ALLORA LE ISTANZE CON QUESTA PROCEDURA VERRANNO CHIUSE IN AUTOMATICO ALLA SCADENZA DEI TEMPI PREVISTI DALLA PROCEDURA';
COMMENT ON COLUMN TIPIPROCEDURE.FK_STATO_CHIUS IS 'NEL CASO CHE LA PROCEDURA PREVEDA LA CHIUSURA IN AUTOMATICO QUESTO RAPPRESENTA LO STATO IN CUI VERRA'' IMPOSTATA LA PRATICA CHIUSA';
