//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.01.20 at 02:20:34 PM CET
//
package it.gruppoinit.nlapec.schema.muta;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for modelloBschedaB6Type complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="modelloBschedaB6Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TITOLAREREQ_NOME1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TITOLAREREQ_COGNOME1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TITOLAREREQ_CF1" type="{http://www.muta.servizirl.it/schema/scia/1.0}codiceFiscaleType" minOccurs="0"/>
 *         &lt;element name="TITOLAREREQ_NOME2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TITOLAREREQ_COGNOME2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TITOLAREREQ_CF2" type="{http://www.muta.servizirl.it/schema/scia/1.0}codiceFiscaleType" minOccurs="0"/>
 *         &lt;element name="TITOLAREREQ_NOME3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TITOLAREREQ_COGNOME3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TITOLAREREQ_CF3" type="{http://www.muta.servizirl.it/schema/scia/1.0}codiceFiscaleType" minOccurs="0"/>
 *         &lt;element name="NUMERO_SCHEDE23" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "modelloBschedaB6Type", propOrder = { "titolarereqnome1", "titolarereqcognome1", "titolarereqcf1", "titolarereqnome2",
	"titolarereqcognome2", "titolarereqcf2", "titolarereqnome3", "titolarereqcognome3", "titolarereqcf3", "numeroschede23" })
public class ModelloBschedaB6Type {

    @XmlElement(name = "TITOLAREREQ_NOME1")
    protected String titolarereqnome1;
    @XmlElement(name = "TITOLAREREQ_COGNOME1")
    protected String titolarereqcognome1;
    @XmlElement(name = "TITOLAREREQ_CF1")
    protected String titolarereqcf1;
    @XmlElement(name = "TITOLAREREQ_NOME2")
    protected String titolarereqnome2;
    @XmlElement(name = "TITOLAREREQ_COGNOME2")
    protected String titolarereqcognome2;
    @XmlElement(name = "TITOLAREREQ_CF2")
    protected String titolarereqcf2;
    @XmlElement(name = "TITOLAREREQ_NOME3")
    protected String titolarereqnome3;
    @XmlElement(name = "TITOLAREREQ_COGNOME3")
    protected String titolarereqcognome3;
    @XmlElement(name = "TITOLAREREQ_CF3")
    protected String titolarereqcf3;
    @XmlElement(name = "NUMERO_SCHEDE23")
    protected BigInteger numeroschede23;

    /**
     * Gets the value of the titolarereqnome1 property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTITOLAREREQNOME1() {

	return titolarereqnome1;
    }

    /**
     * Sets the value of the titolarereqnome1 property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTITOLAREREQNOME1(String value) {

	this.titolarereqnome1 = value;
    }

    /**
     * Gets the value of the titolarereqcognome1 property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTITOLAREREQCOGNOME1() {

	return titolarereqcognome1;
    }

    /**
     * Sets the value of the titolarereqcognome1 property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTITOLAREREQCOGNOME1(String value) {

	this.titolarereqcognome1 = value;
    }

    /**
     * Gets the value of the titolarereqcf1 property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTITOLAREREQCF1() {

	return titolarereqcf1;
    }

    /**
     * Sets the value of the titolarereqcf1 property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTITOLAREREQCF1(String value) {

	this.titolarereqcf1 = value;
    }

    /**
     * Gets the value of the titolarereqnome2 property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTITOLAREREQNOME2() {

	return titolarereqnome2;
    }

    /**
     * Sets the value of the titolarereqnome2 property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTITOLAREREQNOME2(String value) {

	this.titolarereqnome2 = value;
    }

    /**
     * Gets the value of the titolarereqcognome2 property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTITOLAREREQCOGNOME2() {

	return titolarereqcognome2;
    }

    /**
     * Sets the value of the titolarereqcognome2 property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTITOLAREREQCOGNOME2(String value) {

	this.titolarereqcognome2 = value;
    }

    /**
     * Gets the value of the titolarereqcf2 property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTITOLAREREQCF2() {

	return titolarereqcf2;
    }

    /**
     * Sets the value of the titolarereqcf2 property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTITOLAREREQCF2(String value) {

	this.titolarereqcf2 = value;
    }

    /**
     * Gets the value of the titolarereqnome3 property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTITOLAREREQNOME3() {

	return titolarereqnome3;
    }

    /**
     * Sets the value of the titolarereqnome3 property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTITOLAREREQNOME3(String value) {

	this.titolarereqnome3 = value;
    }

    /**
     * Gets the value of the titolarereqcognome3 property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTITOLAREREQCOGNOME3() {

	return titolarereqcognome3;
    }

    /**
     * Sets the value of the titolarereqcognome3 property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTITOLAREREQCOGNOME3(String value) {

	this.titolarereqcognome3 = value;
    }

    /**
     * Gets the value of the titolarereqcf3 property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTITOLAREREQCF3() {

	return titolarereqcf3;
    }

    /**
     * Sets the value of the titolarereqcf3 property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTITOLAREREQCF3(String value) {

	this.titolarereqcf3 = value;
    }

    /**
     * Gets the value of the numeroschede23 property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getNUMEROSCHEDE23() {

	return numeroschede23;
    }

    /**
     * Sets the value of the numeroschede23 property.
     * 
     * @param value
     *            allowed object is {@link BigInteger }
     * 
     */
    public void setNUMEROSCHEDE23(BigInteger value) {

	this.numeroschede23 = value;
    }
}
