//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.01.20 at 02:20:34 PM CET
//
package it.gruppoinit.nlapec.schema.muta;

import javax.xml.bind.annotation.XmlEnum;

/**
 * <p>
 * Java class for statoType.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="statoType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="A"/>
 *     &lt;enumeration value="AAA"/>
 *     &lt;enumeration value="ABU"/>
 *     &lt;enumeration value="ADN"/>
 *     &lt;enumeration value="AFG"/>
 *     &lt;enumeration value="AJ"/>
 *     &lt;enumeration value="AL"/>
 *     &lt;enumeration value="AND"/>
 *     &lt;enumeration value="ARM"/>
 *     &lt;enumeration value="AUS"/>
 *     &lt;enumeration value="B"/>
 *     &lt;enumeration value="BD"/>
 *     &lt;enumeration value="BDS"/>
 *     &lt;enumeration value="BG"/>
 *     &lt;enumeration value="BH"/>
 *     &lt;enumeration value="BL"/>
 *     &lt;enumeration value="BO"/>
 *     &lt;enumeration value="BOS"/>
 *     &lt;enumeration value="BP"/>
 *     &lt;enumeration value="BR"/>
 *     &lt;enumeration value="BRG"/>
 *     &lt;enumeration value="BRM"/>
 *     &lt;enumeration value="BRN"/>
 *     &lt;enumeration value="BRU"/>
 *     &lt;enumeration value="BS"/>
 *     &lt;enumeration value="BUR"/>
 *     &lt;enumeration value="C"/>
 *     &lt;enumeration value="CDN"/>
 *     &lt;enumeration value="CH"/>
 *     &lt;enumeration value="CI"/>
 *     &lt;enumeration value="CK"/>
 *     &lt;enumeration value="CL"/>
 *     &lt;enumeration value="CNB"/>
 *     &lt;enumeration value="CO"/>
 *     &lt;enumeration value="CR"/>
 *     &lt;enumeration value="CRO"/>
 *     &lt;enumeration value="CS"/>
 *     &lt;enumeration value="CSI"/>
 *     &lt;enumeration value="CV"/>
 *     &lt;enumeration value="D"/>
 *     &lt;enumeration value="DDR"/>
 *     &lt;enumeration value="DK"/>
 *     &lt;enumeration value="DY"/>
 *     &lt;enumeration value="DZ"/>
 *     &lt;enumeration value="E"/>
 *     &lt;enumeration value="EAK"/>
 *     &lt;enumeration value="EAT"/>
 *     &lt;enumeration value="EAU"/>
 *     &lt;enumeration value="EC"/>
 *     &lt;enumeration value="EE"/>
 *     &lt;enumeration value="EIR"/>
 *     &lt;enumeration value="EK"/>
 *     &lt;enumeration value="ER"/>
 *     &lt;enumeration value="EST"/>
 *     &lt;enumeration value="ET"/>
 *     &lt;enumeration value="ETH"/>
 *     &lt;enumeration value="F"/>
 *     &lt;enumeration value="FI"/>
 *     &lt;enumeration value="FJI"/>
 *     &lt;enumeration value="FL"/>
 *     &lt;enumeration value="G"/>
 *     &lt;enumeration value="GAB"/>
 *     &lt;enumeration value="GB"/>
 *     &lt;enumeration value="GBA"/>
 *     &lt;enumeration value="GBG"/>
 *     &lt;enumeration value="GBJ"/>
 *     &lt;enumeration value="GBM"/>
 *     &lt;enumeration value="GBY"/>
 *     &lt;enumeration value="GBZ"/>
 *     &lt;enumeration value="GEO"/>
 *     &lt;enumeration value="GH"/>
 *     &lt;enumeration value="GR"/>
 *     &lt;enumeration value="GV"/>
 *     &lt;enumeration value="H"/>
 *     &lt;enumeration value="HK"/>
 *     &lt;enumeration value="HN"/>
 *     &lt;enumeration value="HV"/>
 *     &lt;enumeration value="I"/>
 *     &lt;enumeration value="IL"/>
 *     &lt;enumeration value="IND"/>
 *     &lt;enumeration value="IR"/>
 *     &lt;enumeration value="IRQ"/>
 *     &lt;enumeration value="IS"/>
 *     &lt;enumeration value="J"/>
 *     &lt;enumeration value="JA"/>
 *     &lt;enumeration value="JOR"/>
 *     &lt;enumeration value="K"/>
 *     &lt;enumeration value="KG"/>
 *     &lt;enumeration value="KL"/>
 *     &lt;enumeration value="KWT"/>
 *     &lt;enumeration value="KZ"/>
 *     &lt;enumeration value="L"/>
 *     &lt;enumeration value="LAO"/>
 *     &lt;enumeration value="LET"/>
 *     &lt;enumeration value="LIB"/>
 *     &lt;enumeration value="LIT"/>
 *     &lt;enumeration value="LS"/>
 *     &lt;enumeration value="M"/>
 *     &lt;enumeration value="MA"/>
 *     &lt;enumeration value="MAC"/>
 *     &lt;enumeration value="MAU"/>
 *     &lt;enumeration value="MC"/>
 *     &lt;enumeration value="MD"/>
 *     &lt;enumeration value="MEX"/>
 *     &lt;enumeration value="MG"/>
 *     &lt;enumeration value="MOC"/>
 *     &lt;enumeration value="MOL"/>
 *     &lt;enumeration value="MS"/>
 *     &lt;enumeration value="MT"/>
 *     &lt;enumeration value="N"/>
 *     &lt;enumeration value="NA"/>
 *     &lt;enumeration value="NAM"/>
 *     &lt;enumeration value="NEP"/>
 *     &lt;enumeration value="NF"/>
 *     &lt;enumeration value="NGN"/>
 *     &lt;enumeration value="NIC"/>
 *     &lt;enumeration value="NIG"/>
 *     &lt;enumeration value="NL"/>
 *     &lt;enumeration value="NZ"/>
 *     &lt;enumeration value="OMA"/>
 *     &lt;enumeration value="P"/>
 *     &lt;enumeration value="PA"/>
 *     &lt;enumeration value="PAK"/>
 *     &lt;enumeration value="PAN"/>
 *     &lt;enumeration value="PE"/>
 *     &lt;enumeration value="PL"/>
 *     &lt;enumeration value="PP"/>
 *     &lt;enumeration value="PTM"/>
 *     &lt;enumeration value="PU"/>
 *     &lt;enumeration value="PY"/>
 *     &lt;enumeration value="QAT"/>
 *     &lt;enumeration value="R"/>
 *     &lt;enumeration value="RA"/>
 *     &lt;enumeration value="RB"/>
 *     &lt;enumeration value="RBE"/>
 *     &lt;enumeration value="RC"/>
 *     &lt;enumeration value="RCA"/>
 *     &lt;enumeration value="RCB"/>
 *     &lt;enumeration value="RCF"/>
 *     &lt;enumeration value="RCH"/>
 *     &lt;enumeration value="RCL"/>
 *     &lt;enumeration value="RD"/>
 *     &lt;enumeration value="RH"/>
 *     &lt;enumeration value="RI"/>
 *     &lt;enumeration value="RL"/>
 *     &lt;enumeration value="RM"/>
 *     &lt;enumeration value="RMA"/>
 *     &lt;enumeration value="RMM"/>
 *     &lt;enumeration value="RNR"/>
 *     &lt;enumeration value="RNY"/>
 *     &lt;enumeration value="ROK"/>
 *     &lt;enumeration value="RSA"/>
 *     &lt;enumeration value="RSM"/>
 *     &lt;enumeration value="RSR"/>
 *     &lt;enumeration value="RU"/>
 *     &lt;enumeration value="RWA"/>
 *     &lt;enumeration value="RY"/>
 *     &lt;enumeration value="S"/>
 *     &lt;enumeration value="SA"/>
 *     &lt;enumeration value="SAL"/>
 *     &lt;enumeration value="SCV"/>
 *     &lt;enumeration value="SD"/>
 *     &lt;enumeration value="SER"/>
 *     &lt;enumeration value="SF"/>
 *     &lt;enumeration value="SGP"/>
 *     &lt;enumeration value="SK"/>
 *     &lt;enumeration value="SLK"/>
 *     &lt;enumeration value="SLO"/>
 *     &lt;enumeration value="SLV"/>
 *     &lt;enumeration value="SME"/>
 *     &lt;enumeration value="SN"/>
 *     &lt;enumeration value="SNE"/>
 *     &lt;enumeration value="SOM"/>
 *     &lt;enumeration value="SU"/>
 *     &lt;enumeration value="SUD"/>
 *     &lt;enumeration value="SWA"/>
 *     &lt;enumeration value="SY"/>
 *     &lt;enumeration value="SYR"/>
 *     &lt;enumeration value="T"/>
 *     &lt;enumeration value="TC"/>
 *     &lt;enumeration value="TCH"/>
 *     &lt;enumeration value="TG"/>
 *     &lt;enumeration value="TI"/>
 *     &lt;enumeration value="TN"/>
 *     &lt;enumeration value="TR"/>
 *     &lt;enumeration value="TT"/>
 *     &lt;enumeration value="TWA"/>
 *     &lt;enumeration value="TX"/>
 *     &lt;enumeration value="U"/>
 *     &lt;enumeration value="UAE"/>
 *     &lt;enumeration value="UCR"/>
 *     &lt;enumeration value="USA"/>
 *     &lt;enumeration value="UV"/>
 *     &lt;enumeration value="UZ"/>
 *     &lt;enumeration value="VN"/>
 *     &lt;enumeration value="WAC"/>
 *     &lt;enumeration value="WAG"/>
 *     &lt;enumeration value="WAL"/>
 *     &lt;enumeration value="WAN"/>
 *     &lt;enumeration value="WS"/>
 *     &lt;enumeration value="XXX"/>
 *     &lt;enumeration value="YU"/>
 *     &lt;enumeration value="YV"/>
 *     &lt;enumeration value="ZA"/>
 *     &lt;enumeration value="ZI"/>
 *     &lt;enumeration value="ZRE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum StatoType {
    A, AAA, ABU, ADN, AFG, AJ, AL, AND, ARM, AUS, B, BD, BDS, BG, BH, BL, BO, BOS, BP, BR, BRG, BRM, BRN, BRU, BS, BUR, C, CDN, CH, CI, CK, CL, CNB, CO, CR, CRO, CS, CSI, CV, D, DDR, DK, DY, DZ, E, EAK, EAT, EAU, EC, EE, EIR, EK, ER, EST, ET, ETH, F, FI, FJI, FL, G, GAB, GB, GBA, GBG, GBJ, GBM, GBY, GBZ, GEO, GH, GR, GV, H, HK, HN, HV, I, IL, IND, IR, IRQ, IS, J, JA, JOR, K, KG, KL, KWT, KZ, L, LAO, LET, LIB, LIT, LS, M, MA, MAC, MAU, MC, MD, MEX, MG, MOC, MOL, MS, MT, N, NA, NAM, NEP, NF, NGN, NIC, NIG, NL, NZ, OMA, P, PA, PAK, PAN, PE, PL, PP, PTM, PU, PY, QAT, R, RA, RB, RBE, RC, RCA, RCB, RCF, RCH, RCL, RD, RH, RI, RL, RM, RMA, RMM, RNR, RNY, ROK, RSA, RSM, RSR, RU, RWA, RY, S, SA, SAL, SCV, SD, SER, SF, SGP, SK, SLK, SLO, SLV, SME, SN, SNE, SOM, SU, SUD, SWA, SY, SYR, T, TC, TCH, TG, TI, TN, TR, TT, TWA, TX, U, UAE, UCR, USA, UV, UZ, VN, WAC, WAG, WAL, WAN, WS, XXX, YU, YV, ZA, ZI, ZRE;

    public String value() {

	return name();
    }

    public static StatoType fromValue(String v) {

	return valueOf(v);
    }
}
