create table SDEPROXY (
	IDENTE VARCHAR2(15) NOT NULL,
	ALIAS_ENTE    VARCHAR2(20),
	DESCRIZIONE VARCHAR2(255),
	CODICECATASTALECOMUNE VARCHAR2(5),
	WS_STRADARIO VARCHAR2(255),
	WS_ANAGRAFE_RESIDENTI VARCHAR2(255),
	WS_STATOPRATICA VARCHAR2(255),
	USERNAME_WS  VARCHAR2(15),
	PASSWORD_WS  VARCHAR2(15)
);
ALTER TABLE SDEPROXY ADD CONSTRAINT PK_SDEPROXY PRIMARY KEY (IDENTE);
ALTER TABLE SDEPROXY ADD CONSTRAINT FK_SDEPROXY_COMUNI FOREIGN KEY (CODICECATASTALECOMUNE) REFERENCES COMUNI (
CODICECOMUNE
);
CREATE TABLE SDECOMUNIASSOCIATI(
IDENTE VARCHAR2(6) NOT NULL,
CODICECATASTALECOMUNE VARCHAR2(5) NOT NULL
);
ALTER TABLE SDECOMUNIASSOCIATI ADD CONSTRAINT PK_SDECOMUNIASSOCIATI PRIMARY KEY (IDENTE, CODICECATASTALECOMUNE);
ALTER TABLE SDECOMUNIASSOCIATI ADD CONSTRAINT FK_SDECOMUNIASSOCIATI_PROXY FOREIGN KEY (IDENTE) REFERENCES SDEPROXY (IDENTE);
ALTER TABLE SDECOMUNIASSOCIATI ADD CONSTRAINT FK_SDECOMUNIASSOCIATI_COMUNI FOREIGN KEY (CODICECATASTALECOMUNE) REFERENCES COMUNI (CODICECOMUNE);

ALTER TABLE FO_DOMANDE add idente VARCHAR2(15);

ALTER TABLE STP_ENDO_TIPO2 ADD FLAG_REGIONALE NUMBER(1,0) DEFAULT 0; 
COMMENT ON COLUMN STP_ENDO_TIPO2.FLAG_REGIONALE IS 'SE IMPOSTATO A 1 INDICA CHE IL RECORD È STATO CREATO DALLA PROCEDURA DI ALLINEAMENTO AUTOMATICA';

ALTER TABLE STP_ENDO_TIPO1 ADD FLAG_REGIONALE NUMBER(1,0) DEFAULT 0; 
COMMENT ON COLUMN STP_ENDO_TIPO1.FLAG_REGIONALE IS 'SE IMPOSTATO A 1 INDICA CHE IL RECORD È STATO CREATO DALLA PROCEDURA DI ALLINEAMENTO AUTOMATICA';

ALTER TABLE ALBEROPROC_ENDO ADD FLAG_REGIONALE NUMBER(1,0) DEFAULT 0; 
COMMENT ON COLUMN ALBEROPROC_ENDO.FLAG_REGIONALE IS 'SE IMPOSTATO A 1 INDICA CHE IL RECORD È STATO CREATO DALLA PROCEDURA DI ALLINEAMENTO AUTOMATICA';


CREATE TABLE PRODOTTO(
  CODICE VARCHAR2(20) NOT NULL,
  PRODOTTO VARCHAR2(100)
);

ALTER TABLE PRODOTTO ADD CONSTRAINT PK_PRODOTTO PRIMARY KEY(CODICE);
ALTER TABLE PRODOTTO ADD IDENTIFICATIVO_MITTENTE VARCHAR2(10);
ALTER TABLE PRODOTTO ADD FLAG_MOD_MITTENTE NUMBER(1,0);