INSERT INTO VERTICALIZZAZIONIBASE (MODULO,DESCRIZIONE, FLAG_GESTCOMUNE) VALUES ('WSANAGRAFE_ANPR','Permette di scegilere quale e-service di ANPR',0);
 
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) VALUES ('WSANAGRAFE_ANPR','TIPO_SERVIZIO','Servizio per la consultazione della residenza di un cittadino ai fini di un accertamento Pattern Model applicati(C020) e Servizio per la consultazione dell''id univoco nazionale ai fini di un accertamento Pattern Model applicata(C030)');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) VALUES ('WSANAGRAFE_ANPR','C030_CHIAVE_PRIVATA','CODIFICA BASE64 DELLA CHIAVE PRIVATA PDND PER IL SERVIZIO C030');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) VALUES ('WSANAGRAFE_ANPR','C020_CHIAVE_PRIVATA','CODIFICA BASE64 DELLA CHIAVE PRIVATA PDND PER IL SERVIZIO C020');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) VALUES ('WSANAGRAFE_ANPR','C020_BASEURLAPI','URL DELL''API PER LE CHIAMATE AL SERVIZIO C020');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) VALUES ('WSANAGRAFE_ANPR','C030_BASEURLAPI','URL DELL''API PER LE CHIAMATE AL SERVIZIO C030');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) VALUES ('WSANAGRAFE_ANPR','C020_KIDPDND','KID DELLA CHIAVE PUBBLICA CARICATA SU PDND PER IL SERVIZIO C020');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) VALUES ('WSANAGRAFE_ANPR','C030_KIDPDND','KID DELLA CHIAVE PUBBLICA CARICATA SU PDND PER IL SERVIZIO C030');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) VALUES ('WSANAGRAFE_ANPR','C030_CLIENTIDPDND','CLIENTID RESTITUITO DA PDND AL CLIENT CENSITO SULLA PIATTAFORMA PER IL SERVIZIO C030');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) VALUES ('WSANAGRAFE_ANPR','C020_CLIENTIDPDND','CLIENTID RESTITUITO DA PDND AL CLIENT CENSITO SULLA PIATTAFORMA PER IL SERVIZIO C020');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) VALUES ('WSANAGRAFE_ANPR','C020_PURPOSEIDPDND','PURPOSEID RESTITUITO DALLA PDND A SEGUITO DELLA DICHIARAZIONE DELLA FINALITÀ PER IL SERVIZIO C020');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) VALUES ('WSANAGRAFE_ANPR','C030_PURPOSEIDPDND','PURPOSEID RESTITUITO DALLA PDND A SEGUITO DELLA DICHIARAZIONE DELLA FINALITÀ PER IL SERVIZIO C030');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) VALUES ('WSANAGRAFE_ANPR','C020_AUDPDND','USATA PER AUTORIZZAZIONE DELL’AUDIENCE PRESENTE NEL TOKEN PDND PER IL SERVIZIO C020 ES. auth.uat.interop.pagopa.it/client-assertion');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) VALUES ('WSANAGRAFE_ANPR','C030_AUDPDND','USATA PER AUTORIZZAZIONE DELL’AUDIENCE PRESENTE NEL TOKEN PDND PER IL SERVIZIO C030 ES. auth.uat.interop.pagopa.it/client-assertion');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) VALUES ('WSANAGRAFE_ANPR','C020_URLTOKENPDND','URL PER STACCARE IL TOKEN JWT DAL PDND PER IL SERVIZIO C020');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) VALUES ('WSANAGRAFE_ANPR','C030_URLTOKENPDND','URL PER STACCARE IL TOKEN JWT DAL PDND PER IL SERVIZIO C030');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) VALUES ('WSANAGRAFE_ANPR','C020_AUDTOKENAGIDJWTSIGNATURE','TOKEN AGID-JWT-SIGNATURE PER IL SERVIZIO C020');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) VALUES ('WSANAGRAFE_ANPR','C030_AUDTOKENAGIDJWTSIGNATURE','TOKEN AGID-JWT-SIGNATURE PER IL SERVIZIO C030');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) VALUES ('WSANAGRAFE_ANPR','C020_PROXYHOST','URL HOST PER IL PROXY PDND PER IL SERVIZIO C020');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) VALUES ('WSANAGRAFE_ANPR','C030_PROXYHOST','URL HOST PER IL PROXY PDND PER IL SERVIZIO C030');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) VALUES ('WSANAGRAFE_ANPR','C020_PROXYPORT','LA PORTA PER IL PROXY PDND PER IL SERVIZIO C020');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) VALUES ('WSANAGRAFE_ANPR','C030_PROXYPORT','LA PORTA PER IL PROXY PDND PER IL SERVIZIO C030');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) VALUES ('WSANAGRAFE_ANPR','C020_PROXYUSER','L''UTENTE PER IL PROXY PDND PER IL SERVIZIO C020');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) VALUES ('WSANAGRAFE_ANPR','C030_PROXYUSER','L''UTENTE PER IL PROXY PDND PER IL SERVIZIO C030');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) VALUES ('WSANAGRAFE_ANPR','C020_PROXYPWD','PASSWORD  PER IL PROXY PDND PER IL SERVIZIO C020');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) VALUES ('WSANAGRAFE_ANPR','C030_PROXYPWD','PASSWORD  PER IL PROXY PDND PER IL SERVIZIO C030');

UPDATE CLMENU_JAVA SET JSP = 'JAVA', PAGINA = 'report/createStatisticaPentahoPerModulo.htm?software=SOFTWARE', LINK_STANDARD = 'report/createStatisticaPentahoPerModulo.htm?software=SOFTWARE' WHERE ID = 58;
UPDATE CLMENU_JAVA SET DESCRIZIONE ='Carica pratiche ZIP' WHERE id=1041;

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES ('SIT_RAVENNA2','URL_WS_VBGRA012','Url del WS utilizzato per le ricerche al posto della vista VWVBGRA012');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES ('SIT_RAVENNA2','URL_WS_VBGPARTICELLECATASTALI','Url del WS utilizzato per le ricerche al posto della vista VWVBGPARTICELLE_CATASTALI');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES ('SIT_RAVENNA2','URL_WS_VBGRA147','Url del WS utilizzato per le ricerche al posto della vista VWVBGRA147');

INSERT INTO comuniassociazioni (CODICEASSOCIAZIONE, ASSOCIAZIONE) VALUES ('AL424', 'AUTORITA'' DI SISTEMA PORTUALE MAR ADRIATICO ORIENTALE');

INSERT INTO comuniassociazioni (CODICEASSOCIAZIONE, ASSOCIAZIONE) VALUES ('AC573', 'UNIONE VALLE DEL SAVIO');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES ('COMPORTAMENTI_MERCATI','ATTIVA_GIORNATE_NULLE','Se attivata, imposta il calcolo delle bollettazioni considerando il tipo di calcolo scelto per le giornate nulle. può assumere il valore S per sì o N per no');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_ATTIVO' , 'GESTIONE_ACCETTAZIONE', 'Può avere valore 0 o 1; in caso di valore 1 comparirà un bottone a fianco dei protocolli, per notificare al sistema protocollante, l''operatore che sta prendendo in carico il protocollo. Se 0 o non impostato, tale bottone non verrà mostrato');

INSERT INTO verticalizzazioniparametribase (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('COMPORTAMENTI_MERCATI','REGISTRO_AUT_PONTE','Rappresenta i codici della tabella TIPOLOGIAREGISTRI usati per definire le autorizzazioni PONTE ovvero CREATE dalle domande online per essere sostituite con nuove autorizzazioni. È possibile indicare una serie di codici separati da virgola ",".');