ALTER TABLE commedilizie_votazioni ADD voto_fo NUMERIC(1);

UPDATE commedilizie_votazioni SET voto_fo=0 where voto_fo is null;

ALTER TABLE commedilizie_votazioni MODIFY voto_fo NUMERIC(1) NOT NULL;

UPDATE COMMEDILIZIE_VOTAZIONI SET PRESENTE = 0 WHERE PRESENTE = NULL;

ALTER TABLE COMMEDILIZIE_VOTAZIONI MODIFY PRESENTE NUMERIC(1,0) NOT NULL;

alter table autorizzazioni add data_anzianita datetime;
alter table autorizzazioni_subentri add data_anzianita datetime;
alter table tipologiaregistri add flag_gestanzianita numeric(1,0) default 0 not null;

CREATE TABLE COMMEDILIZIE_MASSIVE_T(
	IDCOMUNE VARCHAR(6) NOT NULL,
	ID NUMERIC(6,0) NOT NULL,
	FKID_TESTATA NUMERIC(6,0) NOT NULL,
	FKID_COMMEDT_ID NUMERIC(6,0) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

ALTER TABLE COMMEDILIZIE_MASSIVE_T ADD CONSTRAINT PK_COMMEDILIZIEMASSIVET PRIMARY KEY(IDCOMUNE,ID);
ALTER TABLE COMMEDILIZIE_MASSIVE_T ADD CONSTRAINT FK_COMMEDMASST_MASSIVET FOREIGN KEY(IDCOMUNE,FKID_TESTATA) REFERENCES MASSIVE_TESTATA(IDCOMUNE,ID);
ALTER TABLE COMMEDILIZIE_MASSIVE_T ADD CONSTRAINT FK_COMMEDMASST_COMMEDT FOREIGN KEY(IDCOMUNE,FKID_COMMEDT_ID) REFERENCES COMMISSIONIEDILIZIE_T(IDCOMUNE,CODICECOMMISSIONE);

CREATE TABLE COMMEDILIZIE_MASSIVE_D(
	IDCOMUNE VARCHAR(6) NOT NULL,
	ID NUMERIC(6,0) NOT NULL,
	FKID_MASSIVE_D NUMERIC(6,0) NOT NULL,
	FKID_APPELLO NUMERIC(4,0) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

ALTER TABLE COMMEDILIZIE_MASSIVE_D ADD CONSTRAINT COMMEDILIZIE_MASSIVE_D PRIMARY KEY(IDCOMUNE,ID);
ALTER TABLE COMMEDILIZIE_MASSIVE_D ADD CONSTRAINT FK_COMMEDMASSD_MASSIVED FOREIGN KEY(IDCOMUNE,FKID_MASSIVE_D) REFERENCES MASSIVE_DETTAGLIO(IDCOMUNE,ID);
ALTER TABLE COMMEDILIZIE_MASSIVE_D ADD CONSTRAINT FK_COMMEDMASSD_COMMEDAPPELLO FOREIGN KEY(IDCOMUNE,FKID_APPELLO) REFERENCES COMMEDILIZIE_APPELLO(IDCOMUNE,ID);

CREATE INDEX IDX_COMMEDMASS_T_001 ON COMMEDILIZIE_MASSIVE_T(IDCOMUNE,FKID_TESTATA);
CREATE INDEX IDX_COMMEDMASS_T_002 ON COMMEDILIZIE_MASSIVE_T(IDCOMUNE,FKID_COMMEDT_ID);

CREATE INDEX IDX_COMMEDMASS_D_001 ON COMMEDILIZIE_MASSIVE_D(IDCOMUNE,FKID_MASSIVE_D);
CREATE INDEX IDX_COMMEDMASS_D_002 ON COMMEDILIZIE_MASSIVE_D(IDCOMUNE,FKID_APPELLO);

CREATE TABLE MASSIVE_DETT_DESTINATARI(
IDCOMUNE                VARCHAR(6) NOT NULL,
ID                      NUMERIC(6,0) NOT NULL,
FKID_MASSIVE_D          NUMERIC(6,0) NOT NULL,
CODICEANAGRAFE          NUMERIC(6,0),
CODICEAMMINISTRAZIONE   NUMERIC(8,0),
CODICERESPONSABILE      NUMERIC(8,0),
MAIL_DESTINATARIO       VARCHAR(100)
)  ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE MASSIVE_DETT_DESTINATARI ADD CONSTRAINT PK_MASSIVEDETTDESTINATARI PRIMARY KEY (IDCOMUNE,ID);
ALTER TABLE MASSIVE_DETT_DESTINATARI ADD CONSTRAINT FK_MASSIVEDETTDEST_DETT FOREIGN KEY (IDCOMUNE, FKID_MASSIVE_D) REFERENCES MASSIVE_DETTAGLIO(IDCOMUNE,ID); ALTER TABLE MASSIVE_DETT_DESTINATARI ADD CONSTRAINT FK_MASSIVEDETTDEST_ANAG FOREIGN KEY (IDCOMUNE,CODICEANAGRAFE) REFERENCES ANAGRAFE(IDCOMUNE,CODICEANAGRAFE);
ALTER TABLE MASSIVE_DETT_DESTINATARI ADD CONSTRAINT FK_MASSIVEDETTDEST_AMM FOREIGN KEY (IDCOMUNE,CODICEAMMINISTRAZIONE) REFERENCES AMMINISTRAZIONI(IDCOMUNE,CODICEAMMINISTRAZIONE);
ALTER TABLE MASSIVE_DETT_DESTINATARI ADD CONSTRAINT FK_MASSIVEDETTDEST_RESP FOREIGN KEY (IDCOMUNE,CODICERESPONSABILE) REFERENCES RESPONSABILI(IDCOMUNE,CODICERESPONSABILE);

CREATE INDEX IDX_MASSIVEDETTDEST_001 ON MASSIVE_DETT_DESTINATARI (IDCOMUNE, FKID_MASSIVE_D); 
CREATE INDEX IDX_MASSIVEDETTDEST_002 ON MASSIVE_DETT_DESTINATARI (IDCOMUNE,CODICEANAGRAFE);
CREATE INDEX IDX_MASSIVEDETTDEST_003 ON MASSIVE_DETT_DESTINATARI (IDCOMUNE,CODICEAMMINISTRAZIONE); 
CREATE INDEX IDX_MASSIVEDETTDEST_004 ON MASSIVE_DETT_DESTINATARI (IDCOMUNE,CODICERESPONSABILE);

alter table massive_dettaglio modify codiceanagrafe NUMERIC(6,0) null  ;
