package it.gruppoinit.pal.gp.core.dao.helper;

import org.junit.Assert;
import org.junit.Test;

public class SQLSelectHelperTests {

    @Test
    public void setSql_con_query_valida_non_genera_errori() {

	String query = "SELECT TRIM(ANAGRAFE.NOMINATIVO || ' ' || ANAGRAFE.NOME) AS TITOLARE, CASE WHEN ANAGRAFE.INDIRIZZOCORRISPONDENZA IS NOT NULL THEN ANAGRAFE.INDIRIZZOCORRISPONDENZA ELSE ANAGRAFE.INDIRIZZO END AS INDIRIZZO, CASE WHEN ANAGRAFE.INDIRIZZOCORRISPONDENZA IS NOT NULL THEN ANAGRAFE.CAPCORRISPONDENZA ELSE ANAGRAFE.CAP END AS CAP, CASE WHEN ANAGRAFE.INDIRIZZOCORRISPONDENZA IS NOT NULL THEN ANAGRAFE.PROVINCIACORRISPONDENZA ELSE ANAGRAFE.PROVINCIA END AS PROVINCIA, CASE WHEN ANAGRAFE.INDIRIZZOCORRISPONDENZA IS NOT NULL THEN NVL(CORRISPONDENZA.COMUNE,ANAGRAFE.CITTACORRISPONDENZA) ELSE NVL(RESIDENZA.COMUNE,ANAGRAFE.CITTA) END AS COMUNE, REPLACE(SUM(BOLL_GEST_DETTAGLIO.IMPORTO_TOTALE),'.',',') AS IMPORTO_TOTALE, BOLL_GEST_TESTATA.DESCRIZIONE AS CAUSALE, TO_CHAR(BOLL_GEST_TESTATA.DATA_SCADENZA,'DD/MM/YYYY') AS DATA_SCADENZA FROM DETT_POSIZIONE_DEBITORIA INNER JOIN BOLL_GEST_DETTAGLIO ON DETT_POSIZIONE_DEBITORIA.IDCOMUNE = BOLL_GEST_DETTAGLIO.IDCOMUNE AND DETT_POSIZIONE_DEBITORIA.ID = BOLL_GEST_DETTAGLIO.FK_POSDEBDETTAGLIO_ID INNER JOIN BOLL_GEST_TESTATA ON BOLL_GEST_DETTAGLIO.IDCOMUNE = BOLL_GEST_TESTATA.IDCOMUNE AND BOLL_GEST_DETTAGLIO.FK_BOLLGEST_ID = BOLL_GEST_TESTATA.ID INNER JOIN ANAGRAFE ON BOLL_GEST_DETTAGLIO.IDCOMUNE = ANAGRAFE.IDCOMUNE AND BOLL_GEST_DETTAGLIO.FK_CODICEANAGRAFE = ANAGRAFE.CODICEANAGRAFE LEFT  JOIN COMUNI RESIDENZA ON ANAGRAFE.COMUNERESIDENZA = RESIDENZA.CODICECOMUNE LEFT  JOIN COMUNI CORRISPONDENZA ON ANAGRAFE.COMUNECORRISPONDENZA = CORRISPONDENZA.CODICECOMUNE WHERE DETT_POSIZIONE_DEBITORIA.IDCOMUNE = '@PARAM.IDCOMUNE@' AND DETT_POSIZIONE_DEBITORIA.ID_POSIZIONE_DEBITORIA = @PARAM.ID_POSIZIONE_DEBITORIA@ GROUP BY ANAGRAFE.NOMINATIVO, ANAGRAFE.NOME, ANAGRAFE.INDIRIZZOCORRISPONDENZA, ANAGRAFE.CAPCORRISPONDENZA, ANAGRAFE.PROVINCIACORRISPONDENZA, NVL(CORRISPONDENZA.COMUNE,ANAGRAFE.CITTACORRISPONDENZA), ANAGRAFE.INDIRIZZO, ANAGRAFE.CAP, ANAGRAFE.PROVINCIA, NVL(RESIDENZA.COMUNE,ANAGRAFE.CITTA), BOLL_GEST_TESTATA.DESCRIZIONE, BOLL_GEST_TESTATA.DATA_SCADENZA";
	SQLSelectHelper ssh = new SQLSelectHelper();
	ssh.setSql(query);
	Assert.assertTrue("Non si sono verificati errori", true);
    }
}
