ALTER TABLE pay_registrazioni_causali DROP COLUMN FLAG_RIDUZIONE;
ALTER TABLE pay_registrazioni_causali DROP COLUMN FLAG_NOINCASSI; 
ALTER TABLE pay_registrazioni_causali ADD COLUMN PARAMETRI VARCHAR(100) NULL;

ALTER TABLE COMUNI MODIFY PROVINCIA VARCHAR(70);

ALTER TABLE TIPICAUSALIONERI ADD FLAG_GENERA_FATTURA NUMERIC(1,0) NOT NULL DEFAULT 0 ;
ALTER TABLE TIPICAUSALIONERI ADD FLAG_GENERA_AVVISO NUMERIC(1,0) NOT NULL DEFAULT 0 ;



ALTER TABLE pay_posizioni_debitorie DROP INDEX PAY_POSDEB_IDPSP_UIDX, ADD INDEX PAY_POSDEB_IDPSP (ID_POSIZIONE_PSP);

CREATE TABLE ISTANZEONERI_POSDEB_BATCH(
IDCOMUNE VARCHAR(6 ) NOT NULL,
FK_ISTANZEONERI_ID NUMERIC(10,0) NOT NULL, 
ID_POSIZIONE_DEBITORIA NUMERIC(10,0) NOT NULL, 
TIPO_DOCUMENTO VARCHAR(20) NOT NULL, 
FLAG_COMPLETATA NUMERIC(1,0) NOT NULL DEFAULT 0
) ENGINE=INNODB DEFAULT CHARSET=utf8;

ALTER TABLE ISTANZEONERI_POSDEB_BATCH ADD CONSTRAINT PK_ISTANZEONERI_POSDEB_BATCH PRIMARY KEY (IDCOMUNE,FK_ISTANZEONERI_ID,ID_POSIZIONE_DEBITORIA,TIPO_DOCUMENTO);

ALTER TABLE ISTANZEONERI_POSDEB_BATCH ADD CONSTRAINT FK_ISTONPOSDEBBATCH_ISTON FOREIGN KEY(IDCOMUNE,FK_ISTANZEONERI_ID) REFERENCES ISTANZEONERI(IDCOMUNE, ID); 
ALTER TABLE ISTANZEONERI_POSDEB_BATCH ADD CONSTRAINT FK_ISTONPOSDEBBATCH_DETTPOSDEB FOREIGN KEY(IDCOMUNE,ID_POSIZIONE_DEBITORIA)
REFERENCES DETT_POSIZIONE_DEBITORIA(IDCOMUNE, ID);

CREATE INDEX IDX_ISTONERI_POSDEB_BATCH_001 ON ISTANZEONERI_POSDEB_BATCH (IDCOMUNE,TIPO_DOCUMENTO,FLAG_COMPLETATA);
CREATE INDEX IDX_ISTONERI_POSDEB_BATCH_002 ON ISTANZEONERI_POSDEB_BATCH (IDCOMUNE,FK_ISTANZEONERI_ID); 
CREATE INDEX IDX_ISTONERI_POSDEB_BATCH_003 ON ISTANZEONERI_POSDEB_BATCH (IDCOMUNE,ID_POSIZIONE_DEBITORIA);

alter table pay_posizioni_debitorie add column riferimento_client varchar(20) null;

ALTER TABLE istanzeoneri MODIFY COLUMN fkidtipocausale NUMERIC(10,0) NOT NULL;
UPDATE istanzeoneri SET numerorata=1 WHERE numerorata IS NULL;
ALTER TABLE istanzeoneri MODIFY COLUMN numerorata NUMERIC(2,0) NOT NULL;


ALTER TABLE ISTANZE MODIFY COLUMN FKIDPROTOCOLLO VARCHAR(400);
ALTER TABLE MOVIMENTI MODIFY COLUMN FKIDPROTOCOLLO VARCHAR(400);

CREATE TABLE PROTOCOLLO_METADATI(IDCOMUNE VARCHAR(6) NOT NULL, FKIDPROTOCOLLO VARCHAR(400) NOT NULL, METADATO VARCHAR(50) NOT NULL, VALORE VARCHAR(400) NOT NULL);


alter table ISTANZEONERI add GUID_RATEIZZAZIONE varchar(40);




ALTER TABLE BOLL_CFG_TIPO  DROP FOREIGN KEY FK_BLCFGTIPO_TIPISCAD;
ALTER TABLE BOLL_GEST_TESTATA DROP FOREIGN KEY FK_BOLGESTEST_TIPISCAD;

ALTER TABLE BOLL_CFG_TIPO MODIFY FK_TIPISCADENZA_ID NUMERIC(3,0) NOT NULL;
ALTER TABLE BOLL_GEST_TESTATA MODIFY FK_TIPISCADENZA_ID NUMERIC(3,0) NOT NULL;
ALTER TABLE ONERITIPIRATEIZZAZIONE MODIFY SCADENZARATE NUMERIC(3,0) NOT NULL;
ALTER TABLE TIPI_SCADENZA MODIFY ID NUMERIC(3,0);

ALTER TABLE ONERITIPIRATEIZZAZIONE ADD CONSTRAINT FK_ONERITIPIRAT_TIPISCAD FOREIGN KEY(SCADENZARATE) REFERENCES TIPI_SCADENZA(ID);
ALTER TABLE BOLL_GEST_TESTATA ADD CONSTRAINT FK_BOLGESTEST_TIPISCAD FOREIGN KEY(FK_TIPISCADENZA_ID) REFERENCES TIPI_SCADENZA(ID);
ALTER TABLE BOLL_CFG_TIPO ADD CONSTRAINT FK_BLCFGTIPO_TIPISCAD FOREIGN KEY(FK_TIPISCADENZA_ID) REFERENCES TIPI_SCADENZA(ID);





ALTER TABLE AUTORIZZAZIONI ADD NUM_PREAVVISI_STORICO NUMERIC(4,0);

ALTER TABLE TIPICAUSALIONERIDETTAGLIO ADD FLAG_ATTIVO NUMERIC(1,0) NOT NULL DEFAULT 0;