CREATE TABLE dyn2_modelli_campi_collegati (
 IdComune VARCHAR(6) NOT NULL,
 FkIdModello DECIMAL(10,0) NOT NULL,
 FkIdCampo DECIMAL(10,0) NOT NULL,
 PRIMARY KEY (IdComune, FkIdModello, FkIdCampo),
 CONSTRAINT FK_MCC_MODELLI FOREIGN KEY (IdComune, FkIdModello) REFERENCES dyn2_modellit (IDCOMUNE, ID),
 CONSTRAINT FK_MCC_CAMPI FOREIGN KEY (IdComune, FkIdCampo) REFERENCES dyn2_campi (IDCOMUNE, ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;


ALTER TABLE pay_connector_config ADD COLUMN FK_WS_SINCRONIZZAZIONE_DEBITI DECIMAL(9,0);
ALTER TABLE pay_connector_config ADD KEY PAYCONN_FK_SINC_DEB (CODICE, FK_WS_SINCRONIZZAZIONE_DEBITI);
ALTER TABLE pay_connector_config ADD CONSTRAINT PAYCONN_FK_SINC_DEB FOREIGN KEY(CODICE, FK_WS_SINCRONIZZAZIONE_DEBITI) REFERENCES pay_connector_ws_endpoint (CODICE_CONNETTORE, ID);

ALTER TABLE ALBEROPROC_DOCUMENTI ADD COLUMN flag_firma_ute_loggato DECIMAL(1,0);

CREATE TABLE ALBEROPROC_COMUNI_ESCLUSI (IDCOMUNE VARCHAR(6) NOT NULL, FK_SCID DECIMAL(10,0) NOT NULL, CODICECOMUNE VARCHAR(5) NOT NULL) ENGINE=INNODB DEFAULT CHARSET=UTF8;
ALTER TABLE ALBEROPROC_COMUNI_ESCLUSI ADD PRIMARY KEY (IDCOMUNE, FK_SCID, CODICECOMUNE);
ALTER TABLE ALBEROPROC_COMUNI_ESCLUSI ADD CONSTRAINT FK_COMUNI_ESCLUSI_ALBERO FOREIGN KEY (IDCOMUNE, FK_SCID) REFERENCES ALBEROPROC (IDCOMUNE, SC_ID);
ALTER TABLE ALBEROPROC_COMUNI_ESCLUSI ADD CONSTRAINT FK_COMUNI_ESCLUSI_COMUNI FOREIGN KEY (CODICECOMUNE) REFERENCES COMUNI (CODICECOMUNE);

create table pay_posdeb_rifclient (idcomune varchar(6) not null,guid varchar(60) not null,fk_posizione_debitoria numeric(9,0) not null,riferimento_client varchar(60) not null,primary key (idcomune, guid), constraint fk_ppdrc_payposdeb foreign key (idcomune, fk_posizione_debitoria) references pay_posizioni_debitorie (idcomune, id)) ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE AUDITING (UUID VARCHAR(36) NOT NULL, ALIAS VARCHAR(50), SISTEMA_RIFERIMENTO VARCHAR(255), UTENTE VARCHAR(500), HOST VARCHAR(255), OGGETTO VARCHAR(255), METODO VARCHAR(255), PARAMETRI_REQUEST LONGTEXT, SERVER VARCHAR(500), DATA_OPERAZIONE DATETIME(6) NOT NULL) ENGINE=INNODB DEFAULT CHARSET=UTF8;
ALTER TABLE AUDITING ADD CONSTRAINT PK_AUDITING PRIMARY KEY (UUID);
CREATE TABLE AUDITING_MANIFESTAZIONI (UUID VARCHAR(36) NOT NULL, ALIAS VARCHAR(50), IDCOMUNE VARCHAR(6), SISTEMA_RIFERIMENTO VARCHAR(255), UTENTE VARCHAR(500), MANIFESTAZIONE VARCHAR(500), DATA_MANIFESTAZIONE DATETIME(6), TIPO_OPERAZIONE VARCHAR(255), OGGETTO VARCHAR(255), SERVER VARCHAR(500), DATA_OPERAZIONE DATETIME(6) NOT NULL) ENGINE=INNODB DEFAULT CHARSET=UTF8;
ALTER TABLE AUDITING_MANIFESTAZIONI ADD CONSTRAINT PK_AUDITING_MANIF PRIMARY KEY (UUID);

ALTER TABLE software MODIFY ordine DECIMAL (3,0);