INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (modulo, parametro, descrizione) VALUES('AREA_RISERVATA', 'QUESTIONARIO_FO_ATTIVO', 'Attiva o disattiva la funzionalità di questionario soddisfazione al termine della presentazione di una domanda (1 o 0, default 0)');
INSERT INTO VERTICALIZZAZIONIBASE(MODULO, FLAG_GESTCOMUNE, DESCRIZIONE) VALUES ('PROTOCOLLO_CIVILIANEXT',1,'Evoluzione del protocollo CIVILIA con servizi di tipo RESTsviluppato da Dedagroup, il web service necessita di autenticazione di tipo OAUTH');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_CIVILIANEXT','CODICELIVELLOORGANIGRAMMA','Codice dell''ufficio di competenza; ad esempio ABB53F768C719A19804E5040E5EF3ED5');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_CIVILIANEXT','CLIENT_ID','Parametro client_id da passare all''endpoint oauth 2.0');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_CIVILIANEXT','CLIENT_SECRET','Parametro secret da passare all''endpoint oauth 2.0');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_CIVILIANEXT','IDCODICEAOO','Indicare in questo parametro il valore relativo al codice AOO del protocollo, che sarà poi inserito nel parametro IdCodiceAOO della richieta json.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_CIVILIANEXT','IDREGISTRO','Identifica il registro in cui effettuare la protocollazione');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_CIVILIANEXT','URL_OAUTH','Endpoint relativo all''autenticazione oauth 2.0 da utilizzare per ottenere il token da usare poi per le chiamate al web service rest; ad esempio https://login.microsoftonline.com/2932a332-e8e6-48df-8c29-d328716f8688/oauth2/token');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_CIVILIANEXT','URL_WSAGGIUNGIALLEGATO','Endpoint del web service rest per l''aggiunta di allegati. Viene chiamato automaticamente in fase di protocollazione; ad esempio https://api.stagingenvironment.it/Protocollo/Protocollo/AggiungiAllegato');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_CIVILIANEXT','URL_WSANNULLAPROTOCOLLO','(DISMESSO)Endpoint del web service rest per l''annullamento di un protocollo; ad esempio https://api.stagingenvironment.it/Protocollo/Protocollo/AnnullaProtocollo');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_CIVILIANEXT','URL_WSASSEGNAZIONE','Endpoint del web service rest per l''assegnazione di un protocollo; ad esempio https://api.stagingenvironment.it/Protocollo/Protocollo/AssegnaPratica');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_CIVILIANEXT','URL_WSCERCAPRATICHE','Endpoint del web service rest per la lettura di un protocollo; ad esempio https://api.stagingenvironment.it/Protocollo/Protocollo/CercaPratiche?v=2');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_CIVILIANEXT','URL_WSESTRAITITOLARIO','Endpoint del web service rest che restituisce l''elenco delle classifiche; ad esempio http://api.stagingenvironment.it/Archivio/EstraiTitolario');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_CIVILIANEXT','URL_WSGETALLEGATI','Endpoint del web service rest per la lista degli allegati del protocollo; ad esempio https://api.stagingenvironment.it/Protocollo/Protocollo/GetAllegati');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_CIVILIANEXT','URL_WSGETALLEGATO','Endpoint del web service rest per il download di un allegato del protocollo; ad esempio https://api.stagingenvironment.it/Protocollo/Protocollo/GetAllegato');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_CIVILIANEXT','URL_WSPROTOCOLLO','Endpoint del web service rest per la protocollazione; ad esempio https://api.stagingenvironment.it/Protocollo/Protocollo/Protocollazione');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_CIVILIANEXT','URL_WSRESOURCE','Indicare la url che identifica la risorsa che contiene il token richiesto, in genere è sufficiente indicare la parte iniziale del ws indicato nel parametro URL_WSPROTOCOLLO, in pratica invece di http://api.civilianextdev.it/Protocollo/Protocollo/Protocolla inserire http://api.civilianext.dev.it. Fare attenzione perché potrebbe essere in HTTP anche se tutti gli URL sono in HTTPS');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_CIVILIANEXT','URL_WSRICERCALIVELLO','Endpoint del web service che recupera le informazioni degli operatori tramite la loro matricola; ad esempio https://api.stagingenvironment.it/Organigramma/RicercaLivello');

