CREATE TABLE RUBRICA(
 IDCOMUNE VARCHAR2(6 CHAR) NOT NULL,
 ID NUMBER(10,0) NOT NULL,
 DESCRIZIONE VARCHAR2(200),
 MAIL VARCHAR2(100),
 CHIAVE VARCHAR2(100)
);

ALTER TABLE RUBRICA  ADD CONSTRAINT RUBRICA_PK PRIMARY KEY (IDCOMUNE,ID);

create index IDX_RUBRICA_001 ON RUBRICA(IDCOMUNE, DESCRIZIONE);
