alter table tipisoggetto add FLAG_FO_MOD_PRATICA NUMERIC(1,0) default 0;
ALTER TABLE ALBEROPROC_PROTOCOLLO ADD SC_FASCNUMERO VARCHAR(50);

CREATE TABLE INVENTARIOPROC_ENDO(
  IDCOMUNE VARCHAR(6) NOT NULL,
  ID NUMERIC(10,0) NOT NULL,
  CODICEINVENTARIO_T NUMERIC(10,0) NOT NULL,
  CODICEINVENTARIO_D NUMERIC(10,0) NOT NULL,
  FLAG_PUBBLICA NUMERIC(1,0),
  FLAG_NECESSARIO NUMERIC(1,0),
  CODICECOMUNE VARCHAR(5)  
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE INVENTARIOPROC_ENDO ADD CONSTRAINT PK_INVENTARIOPROC_ENDO PRIMARY KEY (IDCOMUNE, ID);
ALTER TABLE INVENTARIOPROC_ENDO ADD CONSTRAINT FK_INVPROCENDO_INVPROC_T FOREIGN KEY (IDCOMUNE, CODICEINVENTARIO_T) REFERENCES INVENTARIOPROCEDIMENTI (IDCOMUNE, CODICEINVENTARIO);
ALTER TABLE INVENTARIOPROC_ENDO ADD CONSTRAINT FK_INVPROCENDO_INVPROC_D FOREIGN KEY (IDCOMUNE, CODICEINVENTARIO_D) REFERENCES INVENTARIOPROCEDIMENTI (IDCOMUNE, CODICEINVENTARIO);
ALTER TABLE INVENTARIOPROC_ENDO ADD CONSTRAINT FK_INVPROCENDO_COMUNI FOREIGN KEY (CODICECOMUNE) REFERENCES COMUNI (CODICECOMUNE);

create table LOCK_TABLE (
LOCK_NAME VARCHAR(25) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE LOCK_TABLE ADD CONSTRAINT PK_LOCK_TABLE PRIMARY KEY (LOCK_NAME);
