INSERT INTO COMUNI (CODICECOMUNE, COMUNE, SIGLAPROVINCIA, PROVINCIA, REGIONE, CAP, CF, CODICEISTAT, CODICEISTATREGIONE) VALUES ('A000', 'Comune di test', 'FI', 'Firenze', 'TOSCANA', '00000', 'A000', '999999', '09');

INSERT INTO COMUNI 
(CODICECOMUNE,COMUNE,SIGLAPROVINCIA,PROVINCIA,REGIONE,CAP,CF,CODICEISTAT,CODICEISTATREGIONE,CODICESTATOESTERO) 
VALUES 
('M347','SILLANO GIUNCUGNANO','LU','LUCCA','TOSCANA','55039','M347','046037','09',NULL);

INSERT INTO CODIFICA_ENTI_53
(CODICEISTAT, ENTE, CODIFICA)
VALUES
('046037','COMUNE DI SILLANO GIUNCUGNANO','13.13.1.M.000.046037');

INSERT INTO  COMUNI (CODICECOMUNE, COMUNE, SIGLAPROVINCIA, PROVINCIA, REGIONE, CAP, CF, CODICEISTAT, CODICEISTATREGIONE) VALUES ('B000', 'Comune di test 2', 'FI', 'FIRENZE', 'TOSCANA', '00000', 'B000', '999998', '09');


UPDATE STP_ENDO_TIPO2 SET FLAG_REGIONALE=1 WHERE CODICE_TIPOLOGIA_ENDO = 1;

UPDATE STP_ENDO_TIPO2 SET FLAG_REGIONALE=1 WHERE NOT TIPO='ENDO' AND CODICE_TIPOLOGIA_ENDO IS NULL;

UPDATE stp_endo_tipo1 SET FLAG_REGIONALE=1;
