<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net10.0;net48</TargetFrameworks>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<Configurations>Debug;Release;ReleaseFramework</Configurations>
		<Platforms>AnyCPU</Platforms>
	</PropertyGroup>

	<ItemGroup>
		<Folder Include="Properties\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="log4net" Version="3.3.2" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.10" />
		<PackageReference Include="Microsoft.VisualStudio.Threading" Version="18.7.23" />
		<PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="18.7.23">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="System.ServiceModel.Http" Version="10.0.652802" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\SIGePro.Manager.DTO\SIGePro.Manager.DTO.csproj" />
	  <ProjectReference Include="..\Frontoffice\Init.Sigepro.FrontEnd.AppLogic\Init.Sigepro.FrontEnd.AppLogic.csproj" />
	  <ProjectReference Include="..\VBG.Pagamenti.NodoPagamenti\VBG.Pagamenti.NodoPagamenti.csproj" />
	</ItemGroup>
</Project>
