8457=AFGHANISTAN
8426=ALBANIA
8496=ALGERIA
8427=ANDORRA
8497=ANGOLA
8633=ANGUILLA (ISOLA)
8634=ANTIGUA E BARBUDA
8698=ANTILLE BRITANNICHE
8635=ANTILLE OLANDESI
8699=ARABIA MERIDIONALE FEDERAZIONE
8700=ARABIA MERIDIONALE PROTETTORATO
8458=ARABIA SAUDITA
8556=ARGENTINA
8598=ARMENIA
8567=AUSTRALIA
8428=AUSTRIA
8599=AZERBAIGIAN
8542=BAHAMA
8459=BAHREIN
8600=BANGLADESH
8637=BARBADOS
8701=BASUTOLAND-SUD AFRICA BRITANNICO
8702=BECIUANIA-SUD AFRICA BRITANNICO
8429=BELGIO
8638=BELIZE
8612=BENIN
8630=BERMUDA (ISOLE)
8460=BHUTAN
8697=BIELORUSSIA=RUSSIA BIANCA
8461=BIRMANIA
8557=BOLIVIA
8703=BOPHUTHATSWANA
8575=BOSNIA ED ERZEGOVINA
8613=BOTSWANA
8558=BRASILE
8462=BRUNEI
8430=BULGARIA
8614=BURKINA
8499=BURUNDI
8463=CAMBOGIA
8500=CAMERUN
8543=CANADA
8501=CAPO VERDE
8704=CAROLINE (ISOLE)
8639=CAYMAN (ISOLE)
8576=CECA REPUBBLICA
8431=CECOSLOVACCHIA
8502=CENTRAFRICANA REPUBBLICA
8660=CHRISTMAS (ISOLA)
8503=CIAD
8559=CILE
8601=CINA REPUBBLICA POPOLARE
8467=CIPRO
8705=CISKEI
8456=CITTA' DEL VATICANO
8602=COCOS (ISOLE)
8560=COLOMBIA
8504=COMORE
8616=CONGO REPUBBLICA DEMOCRATICA
8505=CONGO REPUBBLICA POPOLARE
8661=COOK (ISOLE)
8468=COREA DEL NORD
8469=COREA DEL SUD
8498=COSTA D'AVORIO
8544=COSTA RICA
8440=CROAZIA
8455=CSI
8545=CUBA
8432=DANIMARCA
8690=DIPENDENZE AUSTRALIANE
8691=DIPENDENZE BRITANNICHE
8687=DIPENDENZE CANADESI
8692=DIPENDENZE FRANCESI
8693=DIPENDENZE NEOZELANDESI
8694=DIPENDENZE NORVEGESI ANTARTICHE
8688=DIPENDENZE NORVEGESI ARTICHE
8689=DIPENDENZE RUSSE
8695=DIPENDENZE STATUNITENSI
8696=DIPENDENZE SUDAFRICANE
8640=DOMINICA
8546=DOMINICANA REPUBBLICA
8561=ECUADOR
8506=EGITTO
8547=EL SALVADOR
8470=EMIRATI ARABI UNITI
8618=ERITREA
8577=ESTONIA
8507=ETIOPIA
8578=FAER OER (ISOLE)
8568=FIGI=VITI
8471=FILIPPINE
8433=FINLANDIA
8434=FRANCIA
8508=GABON
8509=GAMBIA
8603=GAZA (TERRITORIO DI)
8604=GEORGIA
8435=GERMANIA
8510=GHANA
8548=GIAMAICA
8472=GIAPPONE
8579=GIBILTERRA
8619=GIBUTI
8706=GILBERT E ELLICE (ISOLE)
8473=GIORDANIA
8580=GRAN BRETAGNA E IRLANDA DEL NORD
8437=GRECIA
8642=GRENADA
8631=GROENLANDIA
8643=GUADALUPA
8663=GUAM (ISOLA)
8549=GUATEMALA
8655=GUAYANA=GUIANA FRANCESE
8511=GUINEA
8512=GUINEA BISSAU
8513=GUINEA EQUATORIALE
8562=GUYANA
8550=HAITI
8551=HONDURAS
8707=HONG KONG
8708=IFNI
8474=INDIA
8475=INDONESIA
8476=IRAN
8477=IRAQ
8664=IRIAN OCCIDENTALE
8438=IRLANDA=EIRE
8439=ISLANDA
8665=ISOLE CILENE (PASQUA E SALA Y GOMEZ)
8478=ISRAELE
8574=ITALIA
8582=IUGOSLAVIA
8605=KAZAKISTAN
8514=KENYA
8606=KIRGHIZISTAN
8666=KIRIBATI
8722=KOSSOVO
8479=KUWAIT
8620=LA REUNION (ISOLA)
8480=LAOS
8621=LESOTHO
8583=LETTONIA
8481=LIBANO
8515=LIBERIA
8516=LIBIA
8584=LIECHTENSTEIN
8585=LITUANIA
8442=LUSSEMBURGO
8607=MACAO
8586=MACEDONIA
8667=MACQUARIE (ISOLE)
8517=MADAGASCAR
8518=MALAWI
8483=MALAYSIA
8482=MALDIVE
8519=MALI
8443=MALTA
8656=MALVINE=FALKLAND (ISOLE)
8587=MAN (ISOLA)
8709=MARCUS (ISOLE)
8668=MARIANNE (ISOLE)
8520=MAROCCO
8669=MARSHALL
8644=MARTINICA
8521=MAURITANIA
8522=MAURIZIO
8623=MAYOTTE (ISOLA)
8552=MESSICO
8670=MICRONESIA STATI FEDERATI
8671=MIDWAY (ISOLE)
8588=MOLDAVIA
8444=MONACO
8484=MONGOLIA
8645=MONTSERRAT
8523=MOZAMBICO
8624=NAMIBIA
8672=NAURU
8485=NEPAL
8553=NICARAGUA
8524=NIGER
8525=NIGERIA
8673=NIUE=SAVAGE (ISOLE)
8674=NORFOLK (ISOLE E ISOLE DEL MAR DEI CORALLI)
8590=NORMANNE (ISOLE)=ISOLE DEL CANALE
8445=NORVEGIA
8675=NUOVA CALEDONIA (ISOLE E DIPENDENZE)
8569=NUOVA ZELANDA
8486=OMAN
8446=PAESI BASSI
8487=PAKISTAN
8720=PALAU
8646=PANAMA ZONA DEL CANALE
8554=PANAMA'
8676=PAPUA NUOVA GUINEA
8570=PAPUASIA - NUOVA GUINEA
8563=PARAGUAY
8657=PERU'
8677=PITCAIRN (E DIPENDENZE)
8678=POLINESIA FRANCESE (ISOLE)
8448=PORTOGALLO
8648=PUERTO RICO
8488=QATAR
8608=REPUBBLICA DELLA CINA NAZIONALE=TAIWAN
8447=REPUBBLICA DI POLONIA
8449=ROMANIA
8625=RUANDA
8593=RUSSIA=FEDERAZIONE RUSSA
8710=RYUKYU (ISOLE)
8711=SAHARA MERIDIONALE
8712=SAHARA SETTENTRIONALE
8713=SAHARA SPAGNOLO
8649=SAINT KITTS E NEVIS=SAINT CHRISTOPHER E NEVIS
8650=SAINT LUCIA
8632=SAINT PIERRE ET MIQUELON (ISOLE)
8651=SAINT VINCENT E GRENADINE
8571=SALOMONE
8572=SAMOA
8681=SAMOA AMERICANE (ISOLE)
8450=SAN MARINO
8626=SANT'ELENA (ISOLA)
8627=SAO TOME' E PRINCIPE
8528=SEICELLE
8529=SENEGAL
8714=SERBIA E MONTENEGRO
8530=SIERRA LEONE
8715=SIKKIM
8489=SINGAPORE
8490=SIRIA
8595=SLOVACCHIA
8596=SLOVENIA
8531=SOMALIA
8451=SPAGNA
8464=SRI LANKA
8555=STATI UNITI D'AMERICA
8629=SUDAFRICANA REPUBBLICA
8533=SUDAN
8658=SURINAME
8452=SVEZIA
8453=SVIZZERA
8534=SWAZILAND
8609=TAGIKISTAN
8716=TANGANICA
8535=TANZANIA
8721=TERRITORI PALESTINESI
8491=THAILANDIA
8717=TIMOR (ISOLA)
8536=TOGO
8682=TOKELAU=ISOLE DELL'UNIONE
8573=TONGA=ISOLE DEGLI AMICI
8718=TRANSKEI
8659=TRINIDAD E TOBAGO
8537=TUNISIA
8492=TURCHIA
8610=TURKEMENISTAN
8652=TURKS E CAICOS (ISOLE)
8684=TUVALU
8597=UCRAINA
8538=UGANDA
8454=UNGHERIA
8565=URUGUAY
8611=UZBEKISTAN
8685=VANUATU
8719=VENDA
8566=VENEZUELA
8653=VERGINI AMERICANE (ISOLE)
8654=VERGINI BRITANNICHE (ISOLE)
8493=VIETNAM
8686=WALLIS E FUTUNA (ISOLE)
8494=YEMEN
8540=ZAMBIA
8541=ZIMBABWE
