spring.application.name=@project.name@
server.port=${PENTAHO_UTILS_SERVICE_PORT}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB

management.server.port=${PENTAHO_UTILS_MANAGEMENT_PORT}
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
