ALTER TABLE RESPONSABILI_TM_AVV DROP FOREIGN KEY FK_RESPTMAVV_RESP;
ALTER TABLE RESPONSABILI_TM_AVV MODIFY COLUMN CODICERESPONSABILE DECIMAL(8,0);
ALTER TABLE RESPONSABILI_TM_AVV ADD FOREIGN KEY FK_RESPTMAVV_RESP(IDCOMUNE,CODICERESPONSABILE) REFERENCES RESPONSABILI(IDCOMUNE,CODICERESPONSABILE);

CREATE TABLE PAY_REGCAUSALI_PARAMETRI(
IDCOMUNE  VARCHAR(6 )  NOT NULL,
ID        NUMERIC(6,0)     NOT NULL,
FK_PAYREGCAUSALE_ID NUMERIC(6) NOT NULL, CHIAVE VARCHAR(50) NOT NULL, VALORE VARCHAR(4000) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

ALTER TABLE PAY_REGCAUSALI_PARAMETRI ADD CONSTRAINT PK_PAYREGCAUSALIPARAMETRI PRIMARY KEY(IDCOMUNE,ID); ALTER TABLE PAY_REGCAUSALI_PARAMETRI ADD CONSTRAINT FK_PAYREGCAUSPARAM_PAYCAUS FOREIGN KEY(IDCOMUNE,FK_PAYREGCAUSALE_ID) REFERENCES PAY_REGISTRAZIONI_CAUSALI(IDCOMUNE,ID);

CREATE INDEX IDX_PAYREGCAUSALIPARAMETRI_001 ON PAY_REGCAUSALI_PARAMETRI(IDCOMUNE,FK_PAYREGCAUSALE_ID);
CREATE INDEX IDX_PAYREGCAUSALIPARAMETRI_002 ON PAY_REGCAUSALI_PARAMETRI(IDCOMUNE,FK_PAYREGCAUSALE_ID,CHIAVE);

DROP INDEX IDX_PAYREGCAUSALIPARAMETRI_002 ON PAY_REGCAUSALI_PARAMETRI;
CREATE UNIQUE INDEX IDX_PAYREGCAUSALIPARAMETRI_002 ON PAY_REGCAUSALI_PARAMETRI(IDCOMUNE,FK_PAYREGCAUSALE_ID,CHIAVE);
ALTER TABLE ISTANZEONERI MODIFY NR_DOCUMENTO VARCHAR(60);
ALTER TABLE INVENTARIOPROCEDIMENTIONERI MODIFY NOTE VARCHAR(4000);