
ALTER TABLE CLMENU_JAVA ADD MENULINK_V2 VARCHAR(6);

CREATE INDEX IDX_MOVIMENTI_006 ON MOVIMENTI(IDCOMUNE, STATO_ATT_DEST, ID_ATT_DEST);

create table CATEGORIE_EVENTI_MAIL(
IDCOMUNE VARCHAR(6) NOT NULL
,ID NUMERIC(4,0) NOT NULL
,DESCRIZIONE VARCHAR(200)
,FKIDCATEGORIAEVENTO VARCHAR(16)
,TRIGGER_TYPE VARCHAR(20)
,TRIGGER_TEXT VARCHAR(50)
,CODICEMAILTIPO NUMERIC (4,0)
,DESTINATARIMAIL VARCHAR(500)
,DESTINATARIAGGIUNTIVI VARCHAR(50)
,FLAG_ATTIVA NUMERIC (1,0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE CATEGORIE_EVENTI_MAIL ADD CONSTRAINT PK_CATEGORIEEVENTI_MAIL PRIMARY KEY(IDCOMUNE, ID);

ALTER TABLE CATEGORIE_EVENTI_MAIL ADD CONSTRAINT FK_CATEVENTIMAIL_CATEVBASE FOREIGN KEY(FKIDCATEGORIAEVENTO) REFERENCES CATEGORIEEVENTIBASE(ID);

CREATE INDEX IDX_CATEGORIEEVENTI_MAIL_001 ON CATEGORIE_EVENTI_MAIL (IDCOMUNE, FKIDCATEGORIAEVENTO);


ALTER TABLE TIPIMOV_STC_ALTRIDATI ADD flag_help NUMERIC(1,0) default 0;
ALTER TABLE TIPIMOV_STC_ALTRIDATI MODIFY HELP_TEXT VARCHAR(4000) ;

ALTER TABLE TIPIMOVIMENTO ADD FLAG_PUBBL_SCHEDE NUMERIC(1,0);
