CREATE TABLE dyn2_modelli_campi_collegati (
 IdComune varchar2(6) NOT NULL,
 FkIdModello number(10,0) NOT NULL,
 FkIdCampo number(10,0) NOT NULL,
 PRIMARY KEY (IdComune, FkIdModello, FkIdCampo),
 CONSTRAINT FK_MCC_MODELLI FOREIGN KEY (IdComune, FkIdModello) REFERENCES dyn2_modellit (IDCOMUNE, ID),
 CONSTRAINT FK_MCC_CAMPI FOREIGN KEY (IdComune, FkIdCampo) REFERENCES dyn2_campi (IDCOMUNE, ID)
);


ALTER TABLE pay_connector_config ADD  FK_WS_SINCRONIZZAZIONE_DEBITI number(9,0);

ALTER TABLE pay_connector_config ADD CONSTRAINT PAYCONN_FK_SINC_DEB FOREIGN KEY(CODICE, FK_WS_SINCRONIZZAZIONE_DEBITI) REFERENCES pay_connector_ws_endpoint (CODICE_CONNETTORE, ID);

ALTER TABLE ALBEROPROC_DOCUMENTI ADD flag_firma_ute_loggato number(1,0);

CREATE TABLE ALBEROPROC_COMUNI_ESCLUSI (IDCOMUNE VARCHAR2(6 CHAR) NOT NULL, FK_SCID NUMBER(10,0) NOT NULL, CODICECOMUNE VARCHAR2(5 CHAR) NOT NULL);
ALTER TABLE ALBEROPROC_COMUNI_ESCLUSI ADD PRIMARY KEY (IDCOMUNE, FK_SCID, CODICECOMUNE);
ALTER TABLE ALBEROPROC_COMUNI_ESCLUSI ADD CONSTRAINT FK_COMUNI_ESCLUSI_ALBERO FOREIGN KEY (IDCOMUNE, FK_SCID) REFERENCES ALBEROPROC (IDCOMUNE, SC_ID);
ALTER TABLE ALBEROPROC_COMUNI_ESCLUSI ADD CONSTRAINT FK_COMUNI_ESCLUSI_COMUNI FOREIGN KEY (CODICECOMUNE) REFERENCES COMUNI (CODICECOMUNE);

create table pay_posdeb_rifclient (idcomune VARCHAR2(6 CHAR) not null,guid VARCHAR2(60 CHAR) not null,fk_posizione_debitoria NUMBER(9,0) not null,riferimento_client VARCHAR2(60 CHAR) not null,primary key (idcomune, guid), constraint fk_ppdrc_payposdeb foreign key (idcomune, fk_posizione_debitoria) references pay_posizioni_debitorie (idcomune, id));

CREATE TABLE AUDITING (UUID VARCHAR2(36 CHAR) NOT NULL, ALIAS VARCHAR2(50 CHAR), SISTEMA_RIFERIMENTO VARCHAR2(255 CHAR), UTENTE VARCHAR2(500 CHAR), HOST VARCHAR2(255 CHAR), OGGETTO VARCHAR2(255 CHAR), METODO VARCHAR2(255 CHAR), PARAMETRI_REQUEST CLOB, SERVER VARCHAR2(500 CHAR), DATA_OPERAZIONE TIMESTAMP(6) NOT NULL);
ALTER TABLE AUDITING ADD CONSTRAINT PK_AUDITING PRIMARY KEY (UUID);
CREATE TABLE AUDITING_MANIFESTAZIONI (UUID VARCHAR2(36 CHAR) NOT NULL, ALIAS VARCHAR2(50 CHAR), IDCOMUNE VARCHAR2(6 CHAR), SISTEMA_RIFERIMENTO VARCHAR2(255 CHAR), UTENTE VARCHAR2(500 CHAR), MANIFESTAZIONE VARCHAR2(500 CHAR), DATA_MANIFESTAZIONE TIMESTAMP(6), TIPO_OPERAZIONE VARCHAR2(255 CHAR), OGGETTO VARCHAR2(255 CHAR), SERVER VARCHAR2(500 CHAR), DATA_OPERAZIONE TIMESTAMP(6) NOT NULL);
ALTER TABLE AUDITING_MANIFESTAZIONI ADD CONSTRAINT PK_AUDITING_MANIF PRIMARY KEY (UUID);

ALTER TABLE software MODIFY ordine NUMBER(3,0);