CREATE TABLE DOCUMENTI_CONDIVISI(
 IDCOMUNE VARCHAR(6) NOT NULL,
 ID NUMERIC(10,0) NOT NULL,
 CODICEOGGETTO NUMERIC(10,0),
 CODICEISTANZA NUMERIC(6,0),
 CODICEMOVIMENTO NUMERIC(8,0),
 STATO VARCHAR(25)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

ALTER TABLE DOCUMENTI_CONDIVISI ADD CONSTRAINT PK_DOCUMENTICONDIVISI PRIMARY KEY (IDCOMUNE,ID);
ALTER TABLE DOCUMENTI_CONDIVISI ADD CONSTRAINT FK_DOCCOND_OGGETTI FOREIGN KEY (IDCOMUNE,CODICEOGGETTO) REFERENCES OGGETTI(IDCOMUNE,CODICEOGGETTO);
ALTER TABLE DOCUMENTI_CONDIVISI ADD CONSTRAINT FK_DOCCOND_ISTANZE FOREIGN KEY (IDCOMUNE,CODICEISTANZA) REFERENCES ISTANZE(IDCOMUNE,CODICEISTANZA);
ALTER TABLE DOCUMENTI_CONDIVISI ADD CONSTRAINT FK_DOCCOND_MOVIMENTI FOREIGN KEY (IDCOMUNE,CODICEMOVIMENTO) REFERENCES MOVIMENTI(IDCOMUNE,CODICEMOVIMENTO);

CREATE TABLE DOCUMENTI_CONDIVISI_LOGS(
 IDCOMUNE VARCHAR(6) NOT NULL,
 ID NUMERIC(10,0) NOT NULL,
 FK_IDDOCCONDIVISO NUMERIC(10,0),
 DATA_LOG DATETIME,
 MESSAGGIO VARCHAR(250),
 DATI_ESTESI LONGTEXT ,
 LIVELLO VARCHAR(20)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

ALTER TABLE DOCUMENTI_CONDIVISI_LOGS ADD CONSTRAINT PK_DOCUMENTICONDIVISILOGS PRIMARY KEY (IDCOMUNE,ID);
ALTER TABLE DOCUMENTI_CONDIVISI_LOGS ADD CONSTRAINT FK_DOCCONDLOG_DOCCOND FOREIGN KEY (IDCOMUNE,FK_IDDOCCONDIVISO) REFERENCES DOCUMENTI_CONDIVISI(IDCOMUNE,ID);

CREATE TABLE ACCOUNT_FTP(
 IDCOMUNE VARCHAR(6) NOT NULL,
 ID NUMERIC(10,0) NOT NULL,
 INDIRIZZO VARCHAR(100),
 UTENTE VARCHAR(50),
 PASSWORD VARCHAR(50),
 UTENTEPROXY VARCHAR(50),
 PASSWORDPROXY VARCHAR(50),
 FTP_ATTIVO NUMERIC(1,0),
 FTP_ASCI NUMERIC(1,0)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

ALTER TABLE ACCOUNT_FTP ADD CONSTRAINT PK_ACCOUNTFTP PRIMARY KEY (IDCOMUNE, ID);


ALTER TABLE mercatipresenze_t ADD FLAG_POPOLA_CONCESSIONARI NUMERIC(1,0) DEFAULT 1 NULL;
ALTER TABLE mercatipresenze_t ADD FLAG_CONTEGGIA_PRES_ASS NUMERIC(1,0) DEFAULT 1 NULL;

CREATE OR REPLACE ALGORITHM=MERGE
VIEW VW_ASSENZECONCESSIONARI AS
SELECT COUNT(*) AS numero_assenze, mercati.codicemercato, MERCATI.descrizione AS MERCATO, mercati_uso.id AS codiceuso, mercati_uso.descrizione AS USO, mercati_d.idposteggio, MERCATI_D.codiceposteggio  AS POSTEGGIO, anagrafe.codiceanagrafe, ANAGRAFE.NOMINATIVO, ANAGRAFE.NOME, mercatipresenze_t.anno, mercatipresenze_t.software, mercatipresenze_t.idcomune  FROM  MERCATIPRESENZE_D,  ANAGRAFE,  MERCATI,  MERCATI_USO,  MERCATI_D,  MERCATIPRESENZE_T
  WHERE MERCATIPRESENZE_D.IDCOMUNE = mercatipresenze_t.idcomune AND MERCATIPRESENZE_D.fkidtestata = mercatipresenze_t.id
   AND mercatipresenze_d.idcomune = anagrafe.idcomune AND mercatipresenze_d.codiceconcessionario = anagrafe.codiceanagrafe
   AND MERCATI.IDCOMUNE = mercatipresenze_T.idcomune AND mercati.codicemercato = mercatipresenze_T.fkcodicemercato AND
   MERCATI_USO.IDCOMUNE = MERCATIPRESENZE_T.IDCOMUNE AND MERCATI_USO.id = MERCATIPRESENZE_T.fkidmercatiuso AND mercati_d.idcomune = MERCATIPRESENZE_D.idcomune
   AND mercati_d.idposteggio = mercatipresenze_d.fkidposteggio AND codiceconcessionario  IS NOT  NULL AND ( ( MERCATIPRESENZE_D.CODICEANAGRAFE <> CODICECONCESSIONARIO)
   OR MERCATIPRESENZE_D.CODICEANAGRAFE  IS  NULL ) AND ( flag_assenza_giust  IS  NULL OR flag_assenza_giust = 0)
   AND   mercatipresenze_t.FLAG_CONTEGGIA_PRES_ASS=1
   GROUP BY anagrafe.nominativo, anagrafe.nomE, MERCATI.descrizione, mercati_uso.descrizione, mercati_d.idposteggio, MERCATI_D.codiceposteggio, mercati.codicemercato, mercatipresenze_t.anno, mercatipresenze_t.software, mercatipresenze_t.idcomune, anagrafe.codiceanagrafe, mercati_uso.id ORDER BY mercato,uso, posteggio, nominativo,nome;

ALTER table decodifiche ADD ordine NUMERIC(4,0) null;

CREATE OR REPLACE ALGORITHM=TEMPTABLE View VW_MERCATIPRESENZETOTALI AS SELECT 'STORICO' AS ORIGINE, MERCATIPRESENZE_STORICO.IDCOMUNE, MERCATIPRESENZE_STORICO.ANNO, MERCATIPRESENZE_STORICO.CODICEANAGRAFE, MERCATIPRESENZE_STORICO.FK_AUTORIZZAZIONI_ID, MERCATIPRESENZE_STORICO.FKCODICEMERCATO, MERCATIPRESENZE_STORICO.FKIDMERCATIUSO, MERCATIPRESENZE_STORICO.FK_IDPOSTEGGIO AS FKIDPOSTEGGIO,  MERCATIPRESENZE_STORICO.NUMEROPRESENZE, TRIM( concat_ws('',ANAGRAFE.NOMINATIVO , ' ' , ANAGRAFE.NOME) ) AS ANAGRAFE, ANAGRAFE.CODICEFISCALE, ANAGRAFE.PARTITAIVA, COMUNI.COMUNE AS COMUNERESIDENZA, CITTADINANZA.CITTADINANZA, STR_TO_DATE(ANAGRAFE.DATAREGDITTE, '%d/%m/%Y' ) AS DATAREGDITTE FROM MERCATIPRESENZE_STORICO inner join ANAGRAFE on ANAGRAFE.IDCOMUNE = MERCATIPRESENZE_STORICO.IDCOMUNE AND ANAGRAFE.CODICEANAGRAFE = MERCATIPRESENZE_STORICO.CODICEANAGRAFE left outer join COMUNI on COMUNI.CODICECOMUNE = ANAGRAFE.COMUNERESIDENZA left outer join CITTADINANZA on CITTADINANZA.CODICE = ANAGRAFE.CODICECITTADINANZA UNION ALL  SELECT 'CALENDARIO' AS ORIGINE, MERCATIPRESENZE_T.IDCOMUNE, MERCATIPRESENZE_T.ANNO, MERCATIPRESENZE_D.CODICEANAGRAFE, MERCATIPRESENZE_D.FK_AUTORIZZAZIONI_ID, MERCATIPRESENZE_T.FKCODICEMERCATO, MERCATIPRESENZE_T.FKIDMERCATIUSO, MERCATIPRESENZE_D.FKIDPOSTEGGIO, MERCATIPRESENZE_D.NUMEROPRESENZE, TRIM( concat_ws('',ANAGRAFE.NOMINATIVO , ' ' , ANAGRAFE.NOME )) AS ANAGRAFE, ANAGRAFE.CODICEFISCALE, ANAGRAFE.PARTITAIVA, COMUNI.COMUNE AS COMUNERESIDENZA, CITTADINANZA.CITTADINANZA, STR_TO_DATE(ANAGRAFE.DATAREGDITTE, '%d/%m/%Y' ) AS DATAREGDITTE FROM MERCATIPRESENZE_T inner join MERCATIPRESENZE_D on MERCATIPRESENZE_D.IDCOMUNE = MERCATIPRESENZE_T.IDCOMUNE AND MERCATIPRESENZE_D.FKIDTESTATA = MERCATIPRESENZE_T.ID inner join ANAGRAFE on ANAGRAFE.IDCOMUNE = MERCATIPRESENZE_D.IDCOMUNE AND ANAGRAFE.CODICEANAGRAFE = MERCATIPRESENZE_D.CODICEANAGRAFE left outer join COMUNI on COMUNI.CODICECOMUNE = ANAGRAFE.COMUNERESIDENZA left outer join CITTADINANZA on CITTADINANZA.CODICE = ANAGRAFE.CODICECITTADINANZA  and mercatipresenze_t.FLAG_CONTEGGIA_PRES_ASS = 1;

ALTER TABLE DOCUMENTI_CONDIVISI_LOGS DROP FOREIGN KEY FK_DOCCONDLOG_DOCCOND;
ALTER TABLE DOCUMENTI_CONDIVISI DROP PRIMARY KEY;
ALTER TABLE DOCUMENTI_CONDIVISI_LOGS DROP PRIMARY KEY;
ALTER TABLE DOCUMENTI_CONDIVISI_LOGS ADD CONSTRAINT PK_DOCUMENTICONDIVISILOGS PRIMARY KEY (IDCOMUNE,ID);
ALTER TABLE DOCUMENTI_CONDIVISI ADD CONSTRAINT PK_DOCUMENTICONDIVISI PRIMARY KEY (IDCOMUNE,ID);
ALTER TABLE DOCUMENTI_CONDIVISI_LOGS ADD CONSTRAINT FK_DOCCONDLOG_DOCCOND FOREIGN KEY (IDCOMUNE,FK_IDDOCCONDIVISO) REFERENCES DOCUMENTI_CONDIVISI(IDCOMUNE,ID) ON DELETE CASCADE;


alter table domandestc add CODICECOMUNE VARCHAR(5);

alter table domandestc add constraint fk_domandestc_comuni foreign key (codicecomune) references comuni(codicecomune);
