//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Init.SIGePro.Manager.VerificaPagamentiLivorno {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.comune.livorno.it/aida", ConfigurationName="VerificaPagamentiLivorno.ws_diaSoap")]
    public interface ws_diaSoap {
        
        // CODEGEN: Generating message contract since element name codiceDia from namespace http://www.comune.livorno.it/aida is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.comune.livorno.it/aida/wm_dia", ReplyAction="*")]
        Init.SIGePro.Manager.VerificaPagamentiLivorno.wm_diaResponse wm_dia(Init.SIGePro.Manager.VerificaPagamentiLivorno.wm_diaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class wm_diaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="wm_dia", Namespace="http://www.comune.livorno.it/aida", Order=0)]
        public Init.SIGePro.Manager.VerificaPagamentiLivorno.wm_diaRequestBody Body;
        
        public wm_diaRequest() {
        }
        
        public wm_diaRequest(Init.SIGePro.Manager.VerificaPagamentiLivorno.wm_diaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.comune.livorno.it/aida")]
    public partial class wm_diaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string codiceDia;
        
        public wm_diaRequestBody() {
        }
        
        public wm_diaRequestBody(string codiceDia) {
            this.codiceDia = codiceDia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class wm_diaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="wm_diaResponse", Namespace="http://www.comune.livorno.it/aida", Order=0)]
        public Init.SIGePro.Manager.VerificaPagamentiLivorno.wm_diaResponseBody Body;
        
        public wm_diaResponse() {
        }
        
        public wm_diaResponse(Init.SIGePro.Manager.VerificaPagamentiLivorno.wm_diaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.comune.livorno.it/aida")]
    public partial class wm_diaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string wm_diaResult;
        
        public wm_diaResponseBody() {
        }
        
        public wm_diaResponseBody(string wm_diaResult) {
            this.wm_diaResult = wm_diaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ws_diaSoapChannel : Init.SIGePro.Manager.VerificaPagamentiLivorno.ws_diaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ws_diaSoapClient : System.ServiceModel.ClientBase<Init.SIGePro.Manager.VerificaPagamentiLivorno.ws_diaSoap>, Init.SIGePro.Manager.VerificaPagamentiLivorno.ws_diaSoap {
        
        public ws_diaSoapClient() {
        }
        
        public ws_diaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ws_diaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ws_diaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ws_diaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Init.SIGePro.Manager.VerificaPagamentiLivorno.wm_diaResponse Init.SIGePro.Manager.VerificaPagamentiLivorno.ws_diaSoap.wm_dia(Init.SIGePro.Manager.VerificaPagamentiLivorno.wm_diaRequest request) {
            return base.Channel.wm_dia(request);
        }
        
        public string wm_dia(string codiceDia) {
            Init.SIGePro.Manager.VerificaPagamentiLivorno.wm_diaRequest inValue = new Init.SIGePro.Manager.VerificaPagamentiLivorno.wm_diaRequest();
            inValue.Body = new Init.SIGePro.Manager.VerificaPagamentiLivorno.wm_diaRequestBody();
            inValue.Body.codiceDia = codiceDia;
            Init.SIGePro.Manager.VerificaPagamentiLivorno.wm_diaResponse retVal = ((Init.SIGePro.Manager.VerificaPagamentiLivorno.ws_diaSoap)(this)).wm_dia(inValue);
            return retVal.Body.wm_diaResult;
        }
    }
}
