CREATE TABLE ISTANZE_METADATI(
    IDCOMUNE VARCHAR2(6 CHAR) NOT NULL,
    CODICEISTANZA NUMBER(6,0) NOT NULL,
    CHIAVE VARCHAR2(60 CHAR) NOT NULL,
    VALORE VARCHAR2(500 CHAR) NOT NULL
);

ALTER TABLE ISTANZE_METADATI ADD CONSTRAINT PK_ISTANZE_METADATI PRIMARY KEY(IDCOMUNE,CODICEISTANZA,CHIAVE);
ALTER TABLE ISTANZE_METADATI ADD CONSTRAINT FK_ISTANZEMD_ISTANZE FOREIGN KEY(IDCOMUNE,CODICEISTANZA) REFERENCES ISTANZE(IDCOMUNE,CODICEISTANZA);
