CREATE TABLE PAY_MESSAGGI_RABBIT(IDCOMUNE VARCHAR2(6 CHAR) NOT NULL,GUID VARCHAR2(40 CHAR) NOT NULL,TOPIC VARCHAR2(50 CHAR) NOT NULL,MESSAGGIO CLOB NOT NULL,DATA_TRASMISSIONE DATE);
ALTER TABLE PAY_MESSAGGI_RABBIT ADD CONSTRAINT PK_PAYMESSAGGIRABBIT PRIMARY KEY (IDCOMUNE,GUID);
CREATE INDEX idx_pay_messaggirabbit_001 ON PAY_MESSAGGI_RABBIT (idcomune,guid);

CREATE TABLE PAY_MESSAGGI_RABBIT_PAGAMENTI ( IDCOMUNE VARCHAR2(6 CHAR) NOT NULL, FK_MSGRABBIT_GUID VARCHAR2(40 CHAR) NOT NULL, UUID_POSIZIONE_DEB VARCHAR2(60 CHAR) NOT NULL) ;

ALTER TABLE PAY_MESSAGGI_RABBIT_PAGAMENTI ADD CONSTRAINT PK_PAY_MESSAGGI_RABBIT_PAGAMENTI PRIMARY KEY (IDCOMUNE,FK_MSGRABBIT_GUID,UUID_POSIZIONE_DEB);
ALTER TABLE PAY_MESSAGGI_RABBIT_PAGAMENTI ADD CONSTRAINT FK_PMSGRABBITPAG_PAYMSGRABBIT FOREIGN KEY (IDCOMUNE, FK_MSGRABBIT_GUID) REFERENCES PAY_MESSAGGI_RABBIT (IDCOMUNE, GUID);

ALTER TABLE PAY_POSIZIONI_DEBITORIE ADD UUID VARCHAR2(60 CHAR);
UPDATE PAY_POSIZIONI_DEBITORIE SET UUID=Sys_Guid();
CREATE UNIQUE INDEX IDX_PAY_POS_DEB_001 ON PAY_POSIZIONI_DEBITORIE (IDCOMUNE,UUID);
ALTER TABLE PAY_POSIZIONI_DEBITORIE MODIFY UUID VARCHAR(60 CHAR) NOT NULL;

ALTER TABLE DETT_POSIZIONE_DEBITORIA ADD UUID VARCHAR2(60 CHAR);

ALTER TABLE messaggi_rabbit MODIFY topic VARCHAR2(100 CHAR) NOT NULL;
ALTER TABLE pay_messaggi_rabbit MODIFY topic VARCHAR2(100 CHAR) NOT NULL;



CREATE TABLE ASSEGNAZIONE_GRUPPI_TESTATA (
  IDCOMUNE VARCHAR2(6 CHAR) NOT NULL,
  ID NUMBER(10,0) NOT NULL,
  GRUPPO_ISTRUTTORI  NUMBER(10,0),
  AMBITO VARCHAR2(50 CHAR),
  DATA_APERTURA DATE,
  DATA_CHIUSURA DATE
) ;


ALTER TABLE ASSEGNAZIONE_GRUPPI_TESTATA ADD CONSTRAINT PK_ASSEGNAZIONEGRUPPITESTATA PRIMARY KEY (IDCOMUNE,ID);
ALTER TABLE ASSEGNAZIONE_GRUPPI_TESTATA ADD CONSTRAINT FK_GRUPPI_ISTRUTTORI FOREIGN KEY (IDCOMUNE, GRUPPO_ISTRUTTORI) REFERENCES GRUPPI_ISTRUTTORI (IDCOMUNE, ID);


CREATE TABLE ASSEGNAZIONE_GRUPPI_DETTAGLIO (
  IDCOMUNE VARCHAR2(6) NOT NULL,
  IDTESTATA number(10,0) NOT NULL,
  CODICEISTANZA number(6,0) NOT NULL
) ;


ALTER TABLE ASSEGNAZIONE_GRUPPI_DETTAGLIO ADD CONSTRAINT PK_ASSEGNAZIONEGRUPPIDETTAGLIO PRIMARY KEY (IDCOMUNE,IDTESTATA,CODICEISTANZA);
ALTER TABLE ASSEGNAZIONE_GRUPPI_DETTAGLIO ADD CONSTRAINT FK_ASSEGNAZIONEGRUPPITESTATA FOREIGN KEY (IDCOMUNE, IDTESTATA) REFERENCES ASSEGNAZIONE_GRUPPI_TESTATA (IDCOMUNE, ID);
ALTER TABLE ASSEGNAZIONE_GRUPPI_DETTAGLIO ADD CONSTRAINT FK_ISTANZE FOREIGN KEY (IDCOMUNE, CODICEISTANZA) REFERENCES ISTANZE (IDCOMUNE, CODICEISTANZA);

ALTER TABLE boll_gest_dett_rate DROP CONSTRAINT FK_BLDETRATE_BOLLGESTDET;
ALTER TABLE boll_gest_dett_rate MODIFY FK_BOLLGESTDET_ID NUMBER(10,0) ;
ALTER TABLE boll_gest_dett_rate ADD CONSTRAINT FK_BLDETRATE_BOLLGESTDET FOREIGN KEY (IDCOMUNE, FK_BOLLGESTDET_ID ) REFERENCES boll_gest_dettaglio(IDCOMUNE,ID);

ALTER TABLE scadenze_eliminate ADD UUID_ISTANZA VARCHAR2(60 CHAR);

ALTER TABLE scadenze_eliminate ADD SOFTWARE VARCHAR2(2 CHAR);

ALTER TABLE SCADENZE_ELIMINATE ADD CONSTRAINT FK_SCAD_ELIMINATE_SOFTWARE FOREIGN KEY (SOFTWARE) REFERENCES SOFTWARE(CODICE);

ALTER TABLE dyn2_modellid ADD FONTE_ESTERNA VARCHAR2(512 char);

ALTER TABLE dyn2_modellid ADD FONTE_INTERNA VARCHAR2(512 char);

alter table alberoproc_oneri add FLAG_IMPORTO_LIBERO number(1,0) default 0 not null;
alter table inventarioprocedimentioneri add FLAG_IMPORTO_LIBERO number(1,0) default 0 not null;

alter table statiistanza add ETICHETTA_SISTEMA_ESTERNO varchar2(100 char);


MERGE INTO TIPICONTROMOVIMENTO t1
USING
(     SELECT
idcomune,
TIPOMOVIMENTO,
TIPOCONTROMOVIMENTO,
AMMRITSU,
CODAMMSPORTELLOUNICO,
rnum
  FROM
(
SELECT
TIPICONTROMOVIMENTO.idcomune,
TIPICONTROMOVIMENTO.TIPOMOVIMENTO,
TIPICONTROMOVIMENTO.TIPOCONTROMOVIMENTO,
TIPICONTROMOVIMENTO.AMMRITSU,
configurazione.CODAMMSPORTELLOUNICO,
ROW_NUMBER() OVER(
        PARTITION BY TIPICONTROMOVIMENTO.idcomune,
        TIPICONTROMOVIMENTO.TIPOMOVIMENTO,
        TIPICONTROMOVIMENTO.TIPOCONTROMOVIMENTO,
        TIPICONTROMOVIMENTO.AMMRITSU
        ORDER BY TIPICONTROMOVIMENTO.idcomune ASC,
        TIPICONTROMOVIMENTO.TIPOMOVIMENTO ASC ,
        TIPICONTROMOVIMENTO.TIPOCONTROMOVIMENTO ASC
) AS rnum                               
FROM
TIPICONTROMOVIMENTO
 INNER JOIN configurazione ON  configurazione.idcomune=TIPICONTROMOVIMENTO.idcomune AND CONFIGURAZIONE.SOFTWARE='TT'
  WHERE TIPICONTROMOVIMENTO.AMMRITSU IS NULL
) where rnum=1
) t2
ON (
        t1.idcomune = t2.idcomune
        AND t1.TIPOMOVIMENTO = t2.TIPOMOVIMENTO
        AND t1.TIPOCONTROMOVIMENTO = t2.TIPOCONTROMOVIMENTO
)
WHEN MATCHED THEN
UPDATE SET t1.AMMRITSU=T2.CODAMMSPORTELLOUNICO WHERE T1.AMMRITSU IS NULL;

ALTER TABLE segnapostipersonalizzati ADD TEMPLATERTF_CLOB CLOB;
UPDATE segnapostipersonalizzati SET TEMPLATERTF_CLOB=TEMPLATERTF;
ALTER TABLE segnapostipersonalizzati DROP COLUMN TEMPLATERTF;
ALTER TABLE segnapostipersonalizzati ADD TEMPLATERTF CLOB;
UPDATE segnapostipersonalizzati SET TEMPLATERTF=TEMPLATERTF_CLOB;
ALTER TABLE segnapostipersonalizzati DROP COLUMN TEMPLATERTF_CLOB;
ALTER TABLE segnapostipersonalizzati MODIFY TEMPLATERTF  NOT NULL;

ALTER TABLE TIPIMOVIMENTO_RABBIT ADD CATEGORIA VARCHAR2(30 CHAR);

ALTER TABLE parametriesportazione MODIFY DESCRIZIONE VARCHAR2(200);

ALTER TABLE AMMINISTRAZIONI ADD CODICEIPA VARCHAR2(30 CHAR) NULL;

INSERT INTO movimenti_metadati(idcomune,codicemovimento,chiave,valore)
(
 SELECT
  movimenti.idcomune, movimenti.codicemovimento, 'UUID' AS chiave, idcomune || '-' || codicemovimento || '-' || codiceistanza AS VALORE
 FROM
  movimenti
 WHERE
  NOT EXISTS (
SELECT 1 FROM movimenti_metadati WHERE movimenti_metadati.idcomune = movimenti.idcomune AND movimenti_metadati.codicemovimento = movimenti.codicemovimento AND movimenti_metadati.chiave = 'UUID'
  )
);