CREATE TABLE PAY_MESSAGGI_RABBIT(IDCOMUNE VARCHAR(6) NOT NULL,GUID VARCHAR(40) NOT NULL,TOPIC VARCHAR(50) NOT NULL,MESSAGGIO LONGTEXT NOT NULL,DATA_TRASMISSIONE DATETIME) ENGINE=INNODB DEFAULT CHARSET=UTF8;
ALTER TABLE PAY_MESSAGGI_RABBIT ADD CONSTRAINT PK_PAYMESSAGGIRABBIT PRIMARY KEY (IDCOMUNE,GUID);
CREATE INDEX idx_pay_messaggirabbit_001 ON PAY_MESSAGGI_RABBIT (idcomune,guid);


CREATE TABLE PAY_MESSAGGI_RABBIT_PAGAMENTI ( IDCOMUNE VARCHAR(6) NOT NULL, FK_MSGRABBIT_GUID VARCHAR(40) NOT NULL, UUID_POSIZIONE_DEB VARCHAR(60) NOT NULL ) ENGINE=INNODB DEFAULT CHARSET=UTF8;

ALTER TABLE PAY_MESSAGGI_RABBIT_PAGAMENTI ADD CONSTRAINT PK_PAY_MESSAGGI_RABBIT_PAGAMENTI PRIMARY KEY (IDCOMUNE,FK_MSGRABBIT_GUID,UUID_POSIZIONE_DEB);
ALTER TABLE PAY_MESSAGGI_RABBIT_PAGAMENTI ADD CONSTRAINT FK_PMSGRABBITPAG_PAYMSGRABBIT FOREIGN KEY (IDCOMUNE, FK_MSGRABBIT_GUID) REFERENCES PAY_MESSAGGI_RABBIT (IDCOMUNE, GUID);

ALTER TABLE PAY_POSIZIONI_DEBITORIE ADD UUID VARCHAR(60);
UPDATE PAY_POSIZIONI_DEBITORIE SET UUID=UUID() where UUID is null;
CREATE UNIQUE INDEX IDX_PAY_POSIZIONI_DEBITORIE_001 ON PAY_POSIZIONI_DEBITORIE (IDCOMUNE,UUID);
ALTER TABLE PAY_POSIZIONI_DEBITORIE MODIFY UUID VARCHAR(60) NOT NULL;

ALTER TABLE DETT_POSIZIONE_DEBITORIA ADD UUID VARCHAR(60);

ALTER TABLE messaggi_rabbit MODIFY topic VARCHAR(100) NOT NULL;
ALTER TABLE pay_messaggi_rabbit MODIFY topic VARCHAR(100) NOT NULL;


CREATE TABLE ASSEGNAZIONE_GRUPPI_TESTATA (
  IDCOMUNE VARCHAR(6) NOT NULL,
  ID NUMERIC(10,0) NOT NULL,
  GRUPPO_ISTRUTTORI  NUMERIC(10,0),
  AMBITO VARCHAR(50),
  DATA_APERTURA DATETIME,
  DATA_CHIUSURA DATETIME
) ENGINE=INNODB DEFAULT CHARSET=utf8;


ALTER TABLE ASSEGNAZIONE_GRUPPI_TESTATA ADD CONSTRAINT PK_ASSEGNAZIONEGRUPPITESTATA PRIMARY KEY (IDCOMUNE,ID);
ALTER TABLE ASSEGNAZIONE_GRUPPI_TESTATA ADD CONSTRAINT FK_GRUPPI_ISTRUTTORI FOREIGN KEY (IDCOMUNE, GRUPPO_ISTRUTTORI) REFERENCES GRUPPI_ISTRUTTORI (IDCOMUNE, ID);




CREATE TABLE ASSEGNAZIONE_GRUPPI_DETTAGLIO (
  IDCOMUNE VARCHAR(6) NOT NULL,
  IDTESTATA NUMERIC(10,0) NOT NULL,
  CODICEISTANZA NUMERIC(6,0) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8;


ALTER TABLE ASSEGNAZIONE_GRUPPI_DETTAGLIO ADD CONSTRAINT PK_ASSEGNAZIONEGRUPPIDETTAGLIO PRIMARY KEY (IDCOMUNE,IDTESTATA,CODICEISTANZA);
ALTER TABLE ASSEGNAZIONE_GRUPPI_DETTAGLIO ADD CONSTRAINT FK_ASSEGNAZIONEGRUPPITESTATA FOREIGN KEY (IDCOMUNE, IDTESTATA) REFERENCES ASSEGNAZIONE_GRUPPI_TESTATA (IDCOMUNE, ID);
ALTER TABLE ASSEGNAZIONE_GRUPPI_DETTAGLIO ADD CONSTRAINT FK_ISTANZE FOREIGN KEY (IDCOMUNE, CODICEISTANZA) REFERENCES ISTANZE (IDCOMUNE, CODICEISTANZA);

ALTER TABLE boll_gest_dett_rate DROP FOREIGN KEY FK_BLDETRATE_BOLLGESTDET;
ALTER TABLE boll_gest_dett_rate MODIFY FK_BOLLGESTDET_ID DECIMAL(10,0) NOT NULL;
ALTER TABLE boll_gest_dett_rate ADD CONSTRAINT FK_BLDETRATE_BOLLGESTDET FOREIGN KEY (IDCOMUNE, FK_BOLLGESTDET_ID ) REFERENCES boll_gest_dettaglio(IDCOMUNE,ID);



ALTER TABLE scadenze_eliminate ADD UUID_ISTANZA VARCHAR(60);

ALTER TABLE scadenze_eliminate ADD SOFTWARE VARCHAR(2);

ALTER TABLE SCADENZE_ELIMINATE ADD CONSTRAINT FK_SCAD_ELIMINATE_SOFTWARE FOREIGN KEY (SOFTWARE) REFERENCES SOFTWARE(CODICE);


ALTER TABLE dyn2_modellid ADD FONTE_ESTERNA varchar(512);

ALTER TABLE dyn2_modellid ADD FONTE_INTERNA varchar(512);

alter table alberoproc_oneri add column FLAG_IMPORTO_LIBERO decimal(1,0) default 0 not null;
alter table inventarioprocedimentioneri add column FLAG_IMPORTO_LIBERO decimal(1,0) default 0 not null;

alter table statiistanza add ETICHETTA_SISTEMA_ESTERNO varchar(100);

UPDATE TIPICONTROMOVIMENTO
        INNER JOIN CONFIGURAZIONE ON
CONFIGURAZIONE.idcomune=TIPICONTROMOVIMENTO.idcomune AND
CONFIGURAZIONE.SOFTWARE='TT'
SET TIPICONTROMOVIMENTO.AMMRITSU=CONFIGURAZIONE.CODAMMSPORTELLOUNICO
WHERE TIPICONTROMOVIMENTO.AMMRITSU IS NULL;


ALTER TABLE segnapostipersonalizzati ADD TEMPLATERTF_CLOB TEXT;
UPDATE segnapostipersonalizzati SET TEMPLATERTF_CLOB=TEMPLATERTF;
ALTER TABLE segnapostipersonalizzati DROP COLUMN TEMPLATERTF;
ALTER TABLE segnapostipersonalizzati ADD TEMPLATERTF TEXT;
UPDATE segnapostipersonalizzati SET TEMPLATERTF=TEMPLATERTF_CLOB;
ALTER TABLE segnapostipersonalizzati DROP COLUMN TEMPLATERTF_CLOB;
ALTER TABLE segnapostipersonalizzati MODIFY TEMPLATERTF TEXT NOT NULL;

ALTER TABLE TIPIMOVIMENTO_RABBIT ADD CATEGORIA VARCHAR(30) NULL;

ALTER TABLE parametriesportazione MODIFY DESCRIZIONE VARCHAR(200);

ALTER TABLE AMMINISTRAZIONI ADD CODICEIPA VARCHAR(30) NULL;

INSERT INTO movimenti_metadati(idcomune,codicemovimento,chiave,valore)
(
 SELECT
  movimenti.idcomune, movimenti.codicemovimento, 'UUID' AS chiave, CONCAT_WS('-',idcomune, codicemovimento , codiceistanza) AS VALORE
 FROM
  movimenti
 WHERE
  NOT EXISTS (
SELECT 1 FROM movimenti_metadati WHERE movimenti_metadati.idcomune = movimenti.idcomune AND movimenti_metadati.codicemovimento = movimenti.codicemovimento AND movimenti_metadati.chiave = 'UUID'
  )
);