ALTER TABLE TIPISOGGETTOPEOPLE ADD CONSTRAINT FK_TIPI_SOGG_PEOLE_TIPI_SOGG FOREIGN KEY (IDCOMUNE, CODICETIPOSOGGETTO) REFERENCES TIPISOGGETTO (IDCOMUNE, CODICETIPOSOGGETTO);

ALTER TABLE ISTANZESTRADARIO MODIFY CIVICO VARCHAR2(40 BYTE);
 
ALTER TABLE ISTANZESTRADARIO MODIFY PIANO VARCHAR2(50 BYTE);
 
ALTER TABLE ISTANZESTRADARIO MODIFY QUARTIERE VARCHAR2(50 BYTE);

ALTER TABLE CONFIGURAZIONEUTENTE ADD CONSTRAINT CONFUTENTE_RESPONSABILI_FK1 FOREIGN KEY (IDCOMUNE,CODICERESPONSABILE) REFERENCES RESPONSABILI(IDCOMUNE, CODICERESPONSABILE);

CREATE INDEX IDX_ANAGRAFESTORICO_001 ON ANAGRAFESTORICO (IDCOMUNE,CODICEANAGRAFE,DATAINIZIOVALIDITA);

CREATE INDEX  IDX_ANAGRAFESTORICO_002 ON ANAGRAFESTORICO (IDCOMUNE,CODICEANAGRAFE,DATAFINEVALIDITA);

create or replace view vw_anagrafestorico_utilizzo as select idcomune, fk_richiedentestorico_id as idstorico, 'ISTANZE.FK_RICHIEDENTESTORICO_ID' as utilizzo from istanze where fk_richiedentestorico_id is not null union select idcomune, fk_titolarelegalestorico_id as idstorico, 'ISTANZE.FK_TITOLARELEGALESTORICO_ID' as utilizzo from istanze where fk_titolarelegalestorico_id is not null union select idcomune, fk_professionistastorico_id as idstorico, 'ISTANZE.FK_PROFESSIONISTASTORICO_ID' as utilizzo from istanze where fk_professionistastorico_id is not null union select idcomune, fk_richiedentestorico_id as idstorico, 'ISTANZERICHIEDENTI.FK_RICHIEDENTESTORICO_ID' as utilizzo from istanzerichiedenti where fk_richiedentestorico_id is not null union select idcomune, fk_anagrafecollstorico_id as idstorico, 'ISTANZERICHIEDENTI.FK_ANAGRAFECOLLSTORICO_ID' as utilizzo from istanzerichiedenti where fk_anagrafecollstorico_id is not null union select idcomune, fk_procuratorestorico_id as idstorico, 'ISTANZERICHIEDENTI.FK_PROCURATORESTORICO_ID' as utilizzo  from istanzerichiedenti where fk_procuratorestorico_id is not null;

ALTER TABLE TIPISOGGETTOPEOPLE MODIFY CODICETIPOSOGGETTO NUMBER(10,0);

ALTER TABLE FO_ARCONFIGURAZIONE ADD NOME_CONFIGURAZIONE_CONTENUTI VARCHAR2(50) ;

COMMENT ON COLUMN FO_ARCONFIGURAZIONE.NOME_CONFIGURAZIONE_CONTENUTI IS 'Specifica quale tipo di stili utilizzare nel portale dei contenuti';

ALTER TABLE alberoproc_dyn2modellit ADD ordine NUMBER(3);

ALTER TABLE tipiprocedure_dyn2modellit ADD ordine NUMBER(3);

ALTER TABLE inventarioprocdyn2modellit ADD ordine NUMBER(3);

ALTER TABLE RESPONSABILI ADD SCAD_DATAINIZIO DATE;
ALTER TABLE RESPONSABILI ADD SCAD_SOFTWARE VARCHAR(2);
ALTER TABLE RESPONSABILI ADD SCAD_OPERATORE NUMBER(4,0);
ALTER TABLE RESPONSABILI ADD SCAD_COMPORTAMENTO NUMBER(1,0);

ALTER TABLE RESPONSABILI ADD CONSTRAINT FK_RESPONSABILI_SCADOPE FOREIGN KEY (IDCOMUNE,SCAD_OPERATORE) REFERENCES RESPONSABILI (IDCOMUNE, CODICERESPONSABILE);

COMMENT ON COLUMN RESPONSABILI.SCAD_DATAINIZIO IS 'DETERMINA LA DATA A PARTIRE DALLA QUALE VERIFICARE LE SCADENZE'; 
COMMENT ON COLUMN RESPONSABILI.SCAD_SOFTWARE IS 'DETERMINA SE IMPOSTARE LO SCADENZARIO PER VALUTARE SOLAMENTE LE SCADENZE DI UN PARTICOLARE SOFTWARE'; 
COMMENT ON COLUMN RESPONSABILI.SCAD_OPERATORE IS 'DETERMINA SE IMPOSTARE LO SCADENZARIO PER VALUTARE LE SCADENZE IN CUI L''OPERATORE COMPARE COME OPERATORE/RESPONSABILE PROCEDIMENTO/ISTRUTTORE'; 
COMMENT ON COLUMN RESPONSABILI.SCAD_COMPORTAMENTO IS 'DETERMINA SE IMPOSTARE LO SCADENZARIO PER VALUTARE LE SCADENZA DELLE PRATICHE NELLO STATO APERTE O CHIUSE';

ALTER TABLE RESPONSABILI MODIFY SCADENZARIOPREC NUMBER(5,0);

ALTER TABLE tipiprocedure ADD CODICEOGGETTO_CERTINVIO number(10);

ALTER TABLE tipiprocedure  ADD CONSTRAINT fk_tipiprocedure_oggetti FOREIGN KEY (idcomune,CODICEOGGETTO_CERTINVIO) REFERENCES oggetti (idcomune,codiceoggetto);

delete from INTERESSI_LEGALI;
Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (1,TO_DATE('21-04-1942','dd-MM-yyyy'),TO_DATE('15-12-1990','dd-MM-yyyy'),5,null);
Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (2,TO_DATE('16-12-1990','dd-MM-yyyy'),TO_DATE('31-12-1996','dd-MM-yyyy'),10,'Legge 26 novembre 1990, n. 353'); 
Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (3,TO_DATE('01-01-1997','dd-MM-yyyy'),TO_DATE('31-12-1998','dd-MM-yyyy'),5,'Legge 23 dicembre 1996, n. 662'); 
Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (4,TO_DATE('01-01-1999','dd-MM-yyyy'),TO_DATE('31-12-2000','dd-MM-yyyy'),2.5,'D.M. 10 dicembre 1998');
Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (5,TO_DATE('01-01-2001','dd-MM-yyyy'),TO_DATE('31-12-2001','dd-MM-yyyy'),3.5,'D.M. 11 dicembre 2000');
Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (6,TO_DATE('01-01-2002','dd-MM-yyyy'),TO_DATE('31-12-2003','dd-MM-yyyy'),3,'D.M. 11 dicembre 2001');
Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (7,TO_DATE('01-01-2004','dd-MM-yyyy'),TO_DATE('31-12-2007','dd-MM-yyyy'),2.5,'D.M. 1 dicembre 2003');
Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (8,TO_DATE('01-01-2008','dd-MM-yyyy'),TO_DATE('31-12-2009','dd-MM-yyyy'),3,'D.M. 12 dicembre 2007');
Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (9,TO_DATE('01-01-2010','dd-MM-yyyy'),TO_DATE('31-12-2010','dd-MM-yyyy'),1,'D.M. 4 dicembre 2009');
Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (10,TO_DATE('01-01-2011','dd-MM-yyyy'),TO_DATE('31-12-2011','dd-MM-yyyy'),1.5,'D.M. 07 Dicembre 2010');
Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (11,TO_DATE('01-01-2012','dd-MM-yyyy'),null,2.5,'DM 12 dicembre 2011');

ALTER TABLE MOVIMENTIMAIL MODIFY DESTINATARIO VARCHAR2(600);
ALTER TABLE MOVIMENTIMAIL MODIFY DESTINATARIOCC  VARCHAR2(600);
ALTER TABLE MOVIMENTIMAIL MODIFY DESTINATARIOBCC  VARCHAR2(600);
 
ALTER TABLE anagrafe ADD FO_UTENTETESTER NUMBER(1,0);

COMMENT ON COLUMN anagrafe.FO_UTENTETESTER IS 'Se impostato a 1 quando l''utente entra nel FO può visualizzare tutti gli interventi senza filtrare per il flag pubbica';

ALTER TABLE anagrafestorico ADD FO_UTENTETESTER NUMBER(1,0);
