<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net48</TargetFrameworks>
    <RootNamespace>Init.SIGePro.Manager.Configuration</RootNamespace>
    <Configurations>Debug;Release;ReleaseFramework</Configurations>
    <Platforms>AnyCPU</Platforms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SIGePro.Manager.Authentication\SIGePro.Manager.Authentication.csproj" />
  </ItemGroup>

</Project>
