ALTER TABLE ALBEROPROC_ONERI MODIFY AO_FK_COID NUMBER(10,0) NOT NULL;
ALTER TABLE MERCATI ADD CODICEESTERNO VARCHAR2(8 CHAR) NULL;
create index IDX_ISTANZE_CODINTPROC ON ISTANZE(IDCOMUNE,CODICEINTERVENTOPROC);
create index IDX_ALBEROPROC_005 on alberoproc(IDCOMUNE, SOFTWARE,FKCODICEMERCATO,FKIDMERCATIUSO);