CREATE TABLE CODA_MESSAGGI_RABBIT (
IDCOMUNE VARCHAR2(6 CHAR) NOT NULL,
UUID VARCHAR2(60 CHAR) NOT NULL,
UUID_ISTANZA VARCHAR2(60 CHAR) NOT NULL,
UUID_MOVIMENTO VARCHAR2(60 CHAR),
UUID_POS_DEB VARCHAR(60 CHAR) NULL,
TOPIC VARCHAR2(100 CHAR) NOT NULL,
MESSAGGIO CLOB NOT NULL,
DATA_CREAZIONE DATE NOT NULL,
PROGRESSIVO NUMBER(15,0) NOT NULL,
DATA_TRASMISSIONE DATE
);
ALTER TABLE CODA_MESSAGGI_RABBIT ADD CONSTRAINT PK_CODA_MESSAGGI PRIMARY KEY (IDCOMUNE,UUID);

CREATE INDEX IDX_CODAMSGRABBIT_01 ON CODA_MESSAGGI_RABBIT (IDCOMUNE, DATA_CREAZIONE, PROGRESSIVO);
CREATE INDEX IDX_CODAMSGRABBIT_02 ON CODA_MESSAGGI_RABBIT (IDCOMUNE, UUID_ISTANZA);
CREATE INDEX IDX_CODAMSGRABBIT_03 ON CODA_MESSAGGI_RABBIT (IDCOMUNE, UUID_POS_DEB);

Create Or Replace View VW_I_ATTIVITALISTA as
 SELECT
      I_ATTIVITA.CODICEISTANZAULTIMA AS I_CODICEISTANZAULTIMA,
      I_ATTIVITA.ID AS I_IDATTIVITA,
      I_ATTIVITA.IDCOMUNE,
      I_ATTIVITA.ATTIVA,
      I_ATTIVITA.OPERANTE,
      ISTANZE.SOFTWARE,
      I_ATTIVITA.DENOMINAZIONE,
      ISTANZE.NUMEROISTANZA,
      ISTANZE.CODICERICHIEDENTE,
      T_RICHIEDENTE.NOMINATIVO || ' ' || T_RICHIEDENTE.NOME AS RICHIEDENTE,
      TRIM(T_RICHIEDENTE.CODICEFISCALE || ' ' || T_RICHIEDENTE.PARTITAIVA) AS CF_PIVA_RICHIEDENTE,
      ISTANZE.FKCODICESOGGETTO,
      TIPISOGGETTO.TIPOSOGGETTO,
      ISTANZE.CODICECOMUNE,
      ISTANZE.CODICETITOLARELEGALE,
      TRIM(T_AZIENDARICHIEDENTE.NOMINATIVO || ' ' || T_AZIENDARICHIEDENTE.NOME) AS AZIENDARICHIEDENTE,
      TRIM(T_AZIENDARICHIEDENTE.CODICEFISCALE || ' ' || T_AZIENDARICHIEDENTE.PARTITAIVA) AS CF_PIVA_AZIENDARICHIEDENTE,
      ISTANZESTRADARIO.CODICESTRADARIO,
      STRADARIO.PREFISSO || ' ' || STRADARIO.DESCRIZIONE || ',' || NVL(ISTANZESTRADARIO.CIVICO, '') || NVL(ISTANZESTRADARIO.COLORE, '') AS LOCALIZZAZIONE,
      ISTANZESTRADARIO.CIVICO,
    ISTANZESTRADARIO.CODICECIVICO AS CODICECIVICO,
    i_attivita.fk_iatipologie_id AS fk_iatipologie_id
FROM istanze
    inner JOIN anagrafe t_richiedente
        ON istanze.IDCOMUNE = t_richiedente.IDCOMUNE
       AND istanze.CODICERICHIEDENTE = t_richiedente.CODICEANAGRAFE
    INNER JOIN i_attivita
        ON i_attivita.IDCOMUNE = istanze.IDCOMUNE
       AND i_attivita.CODICEISTANZAULTIMA = istanze.CODICEISTANZA
    LEFT JOIN tipisoggetto
        ON istanze.IDCOMUNE = tipisoggetto.IDCOMUNE
       AND istanze.FKCODICESOGGETTO = tipisoggetto.CODICETIPOSOGGETTO
    LEFT JOIN istanzestradario
        ON istanzestradario.IDCOMUNE = istanze.IDCOMUNE
       AND istanzestradario.CODICEISTANZA = istanze.CODICEISTANZA
       AND istanzestradario.PRIMARIO = 1
    LEFT JOIN stradario
        ON stradario.IDCOMUNE = istanzestradario.IDCOMUNE
       AND stradario.CODICESTRADARIO = istanzestradario.CODICESTRADARIO
    left JOIN anagrafe t_aziendarichiedente
        ON istanze.IDCOMUNE = t_aziendarichiedente.IDCOMUNE
       AND istanze.CODICETITOLARELEGALE = t_aziendarichiedente.CODICEANAGRAFE;
       
ALTER TABLE RER_MEDIEGRANDI ADD SPECIALI NUMBER(10,2) NULL;
ALTER TABLE RER_MEDIEGRANDI ADD TIPOLOGIASPECIALI VARCHAR2(4000 CHAR) NULL;

ALTER TABLE RER_MEDIEGRANDI MODIFY COD_CENTROCOMMERCIALE VARCHAR2(20 CHAR);


ALTER TABLE RER_VICINATO ADD SPECIALI NUMBER(10,2) NULL;
ALTER TABLE RER_VICINATO ADD TIPOLOGIASPECIALI VARCHAR2(4000) NULL;
ALTER TABLE RER_VICINATO MODIFY COD_CENTROCOMMERCIALE VARCHAR2(20);



ALTER TABLE fo_domande_ssu ADD NON_ELABORABILE number(1,0) DEFAULT 0;

ALTER TABLE MAILTIPO ADD PROTOCOLLO_OGGETTO_MAIL VARCHAR2(512 CHAR);
ALTER TABLE MAILTIPO ADD PROTOCOLLO_CORPO_MAIL CLOB;

CREATE TABLE FO_DOMANDE_SSU_CORREZIONI (
  IDCOMUNE varchar2(6) NOT NULL,
  ID number(10,0) NOT NULL,
  FK_IDDOMANDA number(6,0) NOT NULL,
  PROCEDIMENTO_ID number(10,0) NOT NULL,
  CORREZIONE_RICHIESTA varchar2(2000),
  CREATA_IL date not null,
  CORRETTA_IL date null,
  PRIMARY KEY (IDCOMUNE,ID),
  CONSTRAINT FK_SSU_CORR_FO_DOMANDE FOREIGN KEY (IDCOMUNE, FK_IDDOMANDA) REFERENCES fo_domande (IDCOMUNE, ID)
);

DROP INDEX UC_DYN2METADATI;

CREATE TABLE fo_domande_ssu_audit (
    idComune      VARCHAR2(6 CHAR)     NOT NULL,
    id            NUMBER(6,0)          NOT NULL,
    fk_idDomanda  NUMBER(6,0)          NOT NULL,
    stato         NUMBER(3,0),
    data          DATE,
    errore        VARCHAR2(500 CHAR),
    CONSTRAINT PK_FO_DOM_SSU_AUDIT PRIMARY KEY (idComune, id),
    CONSTRAINT FK_AUDIT_FO_DOMANDE
        FOREIGN KEY (idComune, fk_idDomanda)
        REFERENCES fo_domande (idComune, id)
);

INSERT INTO pay_connector_config_params (CONFIG_PARAM,DESCRIZIONE,CODICE_CONNETTORE) VALUES ('ID_INSTALLAZIONE','Questo parametro può essere utilizzato dall''ente nelle sue chiamate REST o SOAP',null);
ALTER TABLE pay_profili_enti_creditori ADD LOGO_ENTE BLOB;

ALTER TABLE BLACKLIST_MOTIVI ADD DATA_ACCERTAMENTO DATE;
ALTER TABLE PAY_POSIZIONI_DEBITORIE ADD DATA_FINE_VALIDITA DATE;
ALTER TABLE DETT_POSIZIONE_DEBITORIA ADD DATA_FINE_VALIDITA DATE;

