INSERT INTO verticalizzazioniparametribase  (    modulo,    parametro,    descrizione   )   VALUES  (    'ASSEGNAZIONE_OPERATORI',    'GRUPPO_ISTRUTTORI_DEFAULT',    'Indicare l''identificativo del gruppo istruttori che deve essere preso di default per calcolare l''assegnazione dell''istruttore'  );
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (modulo, parametro, descrizione) VALUES ('I_ATTIVITA','CAMPO_DYN_FINE_ATT','Indica il nome del campo dinamico che riporta la data di fine periodo di occupazione temporaneo');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_ATTIVO', 'ALLEGATI_OBBLIGATORI', 'Valorizzare a 1 se il protocollo richiede necessariamente almeno un allegato, in caso di assenza sarà visualizzato un errore e non sarà possibile la protocollazione fino a quando non sarà allegato almento un documento. Tutti i valori diversi da 1 (o assenza del parametro) renderanno facoltativo l''inserimento di allegati.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_ATTIVO', 'DESCRFILE_MAXLENGTH', 'Indicare, con un valore intero, il numero massimo di caratteri della DESCRIZIONE del file degli allegati che vengono inviati al protocollo. Per descrizione del file si intende il contenuto presente dentro la gestione dei documenti dell''istanza / movimenti alla voce Descrizione. In caso di omissione non sarà applicato alcun controllo.');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_DOCAREA', 'GESTIONE_PEC', 'Indicare con valore 1 se il protocollo che utilizza gli standard docarea prevede delle modalità / servizi per inviare una pec. Va necessariamente indicato anche il parametro TIPOFORNITORE in quanto ogni gestione è a se stante. Tutti gli altri valori o se non indicato ignoreranno qualsiasi funzionalità di invio pec.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_DOCAREA', 'URL_PEC', 'Indicare in questo parametro l''eventuale url del servizio di invio pec, questo parametro va di pari passo con GESTIONE_PEC in quanto viene attivato solamente se il suddetto parametro è impostato con il valore 1.');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (  MODULO,    PARAMETRO,    DESCRIZIONE  )  VALUES  (    'SIT_QUAESTIOFLORENZIA',    'ATTIVA_LINK_CARTOGRAFICO',    'Indicare in questo parametro SE ATTIVARE LE FUNZIONALITA'' DI LINK CARTOGRAFICO LEGATE ALLE ATTIVITA'', VALORI POSSIBLI(1 o 0)'  );
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE  (    MODULO,    PARAMETRO,    DESCRIZIONE  )  VALUES  (    'SIT_QUAESTIOFLORENZIA',    'URL_LINK_CARTOGRAFICO',    'Indicare in questo parametro il link per richiamare il sito della cartografia. es: http://sitap2.comune.intranet/geoflorentia/?Modalita=8&Layer=sviluppo_economico:v_def_pubblici_esercizi&Query=id_attivita=[CODICEATTIVITA]&CodISTATComune=048017&Urlauthentication=SIGEPRO&CallbackURL=[RETURNTO]#'  );
insert INTO VERTICALIZZAZIONIPARAMETRIBASE   (    MODULO,    PARAMETRO,    DESCRIZIONE  )  VALUES  (    'SIT_QUAESTIOFLORENZIA',    'URL_BASE_LINK_BACK',    'Indicare in questo parametro il link per tornare al backoffice . es: http://suapbackoffice/backend/'  );

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_FOLIUM', 'CONTENUTO', 'Indica se l''allegato principale (se sono presenti allegati), debba essere inserito del documento principale del protocollo, in realtà dovrebbe essere sempre così, è stato però introdotto questo parametro per rendere retrocompatibile il compontente con le vecchie versioni che inserivano tutti gli allegati nei documenti allegati. Valorizzare a 1 se si desidera attivare questa funzionalità');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_FOLIUM', 'DISABILITA_MAIL_ARRIVO', 'Indica se deve essere disabilitata l''indicazione della mail / pec in arrivo, in quanto, altrimenti, Folium genera una pec con la ricevuta al cliente. Valorizzare a 1 se si desidera disabilitare questa funzionalità');
INSERT INTO  VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_IRIDE', 'UO_SMISTAMENTO', 'Indicare il codice UO (ufficio) che indica il mittente interno per le pratiche in arrivo, nel protocollo sta ad indicare lo smistamento, in pratica quale ufficio ha lavorato il documento (in arrivo).');
INSERT INTO COMUNIASSOCIAZIONI (CODICEASSOCIAZIONE, ASSOCIAZIONE) VALUES ('AD704', 'UNIONE DI COMUNI DELLA ROMAGNA FORLIVESE');

Insert into VERTICALIZZAZIONIBASE (MODULO,DESCRIZIONE,FLAG_GESTCOMUNE) values ('FVG_SUAP_IN_RETE','Se abilitato consente di creare prariche a partire dal protocollo SUAP IN RETE', null);

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE   (modulo, parametro, descrizione ) VALUES ('FVG_SUAP_IN_RETE','NLA_NODO_SUAP_INRETE','Indica il valore con cui è registrato il nodo NLA SUAP IN RETE su STC' );
