CREATE TABLE MERCATI_MASSIVE_T (
  IDCOMUNE VARCHAR2(6) NOT NULL,
  ID NUMBER(6) NOT NULL,
  FKID_TESTATA NUMBER(6) NOT NULL,
  CONSTRAINT PK_MERCATI_MASSIVE_T PRIMARY KEY (IDCOMUNE, ID),  
  CONSTRAINT FK_MERCMASSIVET_TESTATA FOREIGN KEY (IDCOMUNE, FKID_TESTATA) REFERENCES MASSIVE_TESTATA (IDCOMUNE, ID)
);

CREATE INDEX IDX_MERCMASSIVET_TESTATA ON MERCATI_MASSIVE_T (IDCOMUNE, FKID_TESTATA);

CREATE TABLE MERCATI_MASSIVE_D (
  IDCOMUNE VARCHAR2(6 CHAR) NOT NULL,
  ID NUMBER(6) NOT NULL,
  FKID_MASSIVE_D NUMBER(6) NOT NULL,
  FK_AUTORIZZAZIONE NUMBER(6) NOT NULL,
  CONSTRAINT PK_MERCATI_MASSIVE_D PRIMARY KEY (IDCOMUNE,ID),
  CONSTRAINT FK_MERCMASSIVED_MASSIVED FOREIGN KEY (IDCOMUNE, FKID_MASSIVE_D) REFERENCES MASSIVE_DETTAGLIO (IDCOMUNE, ID)
);
CREATE INDEX IDX_MERCMASSIVED_MASSIVED ON MERCATI_MASSIVE_D (IDCOMUNE,FKID_MASSIVE_D);
CREATE INDEX IDX_MERCMASSIVED_AUT ON MERCATI_MASSIVE_D (IDCOMUNE,FK_AUTORIZZAZIONE);

CREATE TABLE MERCATI_MASSIVE_D_AUT (
  IDCOMUNE VARCHAR2(6 CHAR) NOT NULL,
  ID VARCHAR2(50 CHAR) NOT NULL,
  FK_MERCATI_MASSIVE_D NUMBER(6) NOT NULL,
  FK_CODICEMERCATO NUMBER(4) NOT NULL,
  FK_POSTEGGIO NUMBER(6),
  FK_USO NUMBER(4),
  CONSTRAINT PK_MERCATI_MASSIVE_D_AUT PRIMARY KEY (IDCOMUNE,ID),
  CONSTRAINT FK_MMD_MASSIVED_AUT FOREIGN KEY (IDCOMUNE, FK_MERCATI_MASSIVE_D) REFERENCES MERCATI_MASSIVE_D (IDCOMUNE, ID)
);
CREATE INDEX IDX_MMD_MASSIVED_AUT ON MERCATI_MASSIVE_D_AUT (IDCOMUNE,FK_MERCATI_MASSIVE_D);
CREATE INDEX IDX_MMD_MASSIVED_MERC ON MERCATI_MASSIVE_D_AUT (IDCOMUNE,FK_CODICEMERCATO);

CREATE TABLE ISTANZE_MASSIVE_T ( 
  IDCOMUNE VARCHAR2(6 CHAR) NOT NULL, 
  ID NUMBER(6) NOT NULL, 
  FKID_TESTATA NUMBER(6) NOT NULL, 
  GRUPPO_TYPE VARCHAR2(8 CHAR) NOT NULL,
  CONSTRAINT PK_ISTANZE_MASSIVE_T PRIMARY KEY (IDCOMUNE,ID), 
  CONSTRAINT FK_ISTMASSIVET_TESTATA FOREIGN KEY (IDCOMUNE, FKID_TESTATA) REFERENCES MASSIVE_TESTATA (IDCOMUNE, ID) 
);
CREATE INDEX IDX_ISTMASSIVET_TESTATA ON ISTANZE_MASSIVE_T (IDCOMUNE,FKID_TESTATA);

CREATE TABLE ISTANZE_MASSIVE_D (
  IDCOMUNE varchar2(6 CHAR) NOT NULL,
  ID NUMBER(6) NOT NULL,
  FKID_MASSIVE_D NUMBER(6) NOT NULL,
  FLAG_MOVIMENTO NUMBER(1) NOT NULL,
  FK_TIPIMOVIMENTO VARCHAR2(8 CHAR) ,
  FK_AMMINISTRAZIONE NUMBER(10) ,
  CONSTRAINT PK_ISTANZE_MASSIVE_D PRIMARY KEY (IDCOMUNE,ID),
  CONSTRAINT FK_ISTMASSIVED_MASSIVED FOREIGN KEY (IDCOMUNE, FKID_MASSIVE_D) REFERENCES MASSIVE_DETTAGLIO (IDCOMUNE, ID)
);
CREATE INDEX IDX_ISTMASSIVED_MASSIVED ON ISTANZE_MASSIVE_D(IDCOMUNE,FKID_MASSIVE_D);

CREATE TABLE ISTANZE_MASSIVE_D_ISTANZE (
  IDCOMUNE VARCHAR2(6 CHAR) NOT NULL,
  ID NUMBER(6) NOT NULL,
  FKID_ISTANZEMD NUMBER(6) NOT NULL,
  FKCODICEISTANZA NUMBER(6) NOT NULL,
  FKMOVIMENTO NUMBER(8),
  CONSTRAINT PK_ISTANZE_MASSIVE_D_ISTANZE PRIMARY KEY (IDCOMUNE,ID),
  CONSTRAINT FK_ISTMASSIVETISD_ISTMASSIVED FOREIGN KEY (IDCOMUNE, FKID_ISTANZEMD) REFERENCES ISTANZE_MASSIVE_D (IDCOMUNE, ID)
);
CREATE INDEX IDX_ISTMASSIVETISD_ISTMASSIVED ON ISTANZE_MASSIVE_D_ISTANZE(IDCOMUNE,FKID_ISTANZEMD);
CREATE INDEX IDX_ISTMASSIVETISD_ISTANZE ON ISTANZE_MASSIVE_D_ISTANZE(IDCOMUNE,FKCODICEISTANZA);

CREATE TABLE MASSIVE_D_APPIO_CODA (
  IDCOMUNE VARCHAR2(6 CHAR) NOT NULL,
  FK_MASSIVE_D NUMBER(6,0) NOT NULL,
  FK_GUIDCODA VARCHAR2(40 CHAR) NOT NULL
);

ALTER TABLE MASSIVE_D_APPIO_CODA ADD CONSTRAINT PK_MASSIVE_D_APPIO_CODA PRIMARY KEY(IDCOMUNE,FK_MASSIVE_D,FK_GUIDCODA);
ALTER TABLE MASSIVE_D_APPIO_CODA ADD CONSTRAINT FK_MASdD_APPIOA_APP_IO_CODA FOREIGN KEY(IDCOMUNE,FK_GUIDCODA) REFERENCES APP_IO_CODA(IDCOMUNE,GUID);
ALTER TABLE MASSIVE_D_APPIO_CODA ADD CONSTRAINT FK_MASD_APPIOA_MASSIVE_D FOREIGN KEY(IDCOMUNE,FK_MASSIVE_D) REFERENCES MASSIVE_DETTAGLIO(IDCOMUNE,ID);

ALTER TABLE MERCATI_MASSIVE_T ADD SOFTWARE VARCHAR2(2 CHAR);
ALTER TABLE MERCATI_MASSIVE_T ADD CONSTRAINT FK_SOFTWARE_MERCATI_MASSIVE_T FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);

ALTER TABLE ISTANZE_MASSIVE_T ADD SOFTWARE VARCHAR2(2 CHAR);
ALTER TABLE ISTANZE_MASSIVE_T ADD CONSTRAINT FK_SOFTWARE_ISTANZE_MASSIVE_T FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);

ALTER TABLE boll_gest_dett_autorizz ADD fk_autsubentri_id NUMBER(6,0);
ALTER TABLE boll_gest_dett_autorizz ADD CONSTRAINT fk_bgdetaut_autsubid FOREIGN KEY (idcomune,fk_autsubentri_id) REFERENCES autorizzazioni_subentri(idcomune,id);

ALTER TABLE BLACKLIST_MOTIVI ADD CONTESTO VARCHAR2(20 CHAR);

CREATE TABLE BOLL_GEST_FASE1
(
  IDCOMUNE VARCHAR2(6 CHAR) NOT NULL,
  GUID VARCHAR2(60 CHAR) NOT NULL,
  PROVENIENZA VARCHAR2(20 CHAR) NOT NULL,
  SUBENTRO NUMBER(1,0) NOT NULL,
  IDGIORNATA NUMBER(6,0) NOT NULL,
  DATAGIORNATA DATE NOT NULL,
  IDPOSTEGGIO NUMBER(6,0) NOT NULL,
  IDANAGRAFE NUMBER(6,0) NOT NULL,
  IDRIFERIMENTO NUMBER(6,0) NOT NULL,
  IDAUTORIZZAZIONECONCESSIONE NUMBER(6,0) NULL,
  ASSENZAGIUSTIFICATA NUMBER(1,0) NOT NULL,
  CONCPRESENTE NUMBER(1,0) NOT NULL,
  SPUNTPRESENTE NUMBER(1,0) NOT NULL,
  CATMERC VARCHAR2(15 CHAR) NULL,
  IDUSO NUMBER(4,0) NOT NULL,
  IDAUTORIZZAZIONISUBENTRI NUMBER(6,0) NULL
);

CREATE INDEX IDX_BGFASE1_001 ON BOLL_GEST_FASE1(IDCOMUNE, GUID, IDUSO, DATAGIORNATA);
CREATE INDEX IDX_BGFASE1_002 ON BOLL_GEST_FASE1(IDCOMUNE, GUID, IDGIORNATA, IDPOSTEGGIO, IDUSO, IDANAGRAFE);
CREATE INDEX IDX_BGFASE1_003 ON BOLL_GEST_FASE1(IDCOMUNE, IDRIFERIMENTO);
CREATE INDEX IDX_BGFASE1_004 ON BOLL_GEST_FASE1(IDCOMUNE, GUID, IDANAGRAFE, IDPOSTEGGIO);


CREATE TABLE BOLL_GEST_FASE2
(
  IDCOMUNE VARCHAR2(6 CHAR) NOT NULL,
  GUID VARCHAR2(60 CHAR) NOT NULL,
  IDCALCOLO NUMBER(10,0) NOT NULL,
  CALCOLO VARCHAR2(300 CHAR) NOT NULL,
  INIZIO_VALIDITA_CALCOLO DATE NOT NULL,
  FINE_VALIDITA_CALCOLO DATE NOT NULL,
  FORMULA VARCHAR2(400 CHAR) NOT NULL,
  IDUSO NUMBER(4,0) NOT NULL,
  IDCONTABILITA NUMBER(10,0) NOT NULL,
  CONTABILITA VARCHAR2(200 CHAR) NOT NULL,
  INIZIO_VALIDITA_CONTABILITA DATE NOT NULL,
  FINE_VALIDITA_CONTABILITA DATE NOT NULL,
  IDCONTO NUMBER(6,0) NOT NULL,
  CONTO VARCHAR2(100 CHAR) NOT NULL,
  IVA NUMBER(5,0) NOT NULL,
  FINE_VALIDITA_CONTO DATE NOT NULL
);

CREATE INDEX IDX_BGFASE2_001 ON BOLL_GEST_FASE2(IDCOMUNE, GUID, IDUSO, INIZIO_VALIDITA_CALCOLO, FINE_VALIDITA_CALCOLO, INIZIO_VALIDITA_CONTABILITA, FINE_VALIDITA_CONTABILITA, FINE_VALIDITA_CONTO);

CREATE TABLE BOLL_GEST_FASE3
(
  IDCOMUNE VARCHAR2(6 CHAR) NOT NULL,
  GUID VARCHAR2(60 CHAR) NOT NULL,
  PROVENIENZA VARCHAR2(20 CHAR) NOT NULL,
  CALCOLO VARCHAR2(300 CHAR) NOT NULL,
  IDANAGRAFE NUMBER(6,0) NOT NULL,
  IDGIORNATA NUMBER(6,0) NOT NULL,
  IDPOSTEGGIO NUMBER(6,0) NOT NULL,
  IDUSO NUMBER(4,0) NOT NULL,
  CONCPRESENTE NUMBER(1,0) NOT NULL,
  SPUNTPRESENTE NUMBER(1,0) NOT NULL,
  ASSENZAGIUSTIFICATA NUMBER(1,0) NOT NULL,
  CATMERC VARCHAR2(15 CHAR) NULL,
  IDCONTO NUMBER(6,0) NOT NULL,
  FORMULA VARCHAR2(400 CHAR) NOT NULL,
  IMPORTO_SENZA_IVA NUMBER(11,2) NULL,
  IVA NUMBER(5,0) NOT NULL,
  IMPORTO_TOTALE NUMBER(11,2) NULL,
  FLAG_CONGUAGLIO NUMBER(1,0) NOT NULL
);

CREATE INDEX IDX_BGFASE3_001 ON BOLL_GEST_FASE3(IDCOMUNE, GUID, IDCONTO, IDANAGRAFE, IDPOSTEGGIO);
CREATE INDEX IDX_BGFASE3_002 ON BOLL_GEST_FASE3(IDCOMUNE, IDPOSTEGGIO);
CREATE INDEX IDX_BGFASE3_003 ON BOLL_GEST_FASE3(IDCOMUNE, IDGIORNATA, IDPOSTEGGIO, IDUSO, IDANAGRAFE);
CREATE INDEX IDX_BGFASE3_004 ON BOLL_GEST_FASE3(IDCOMUNE, GUID, IDGIORNATA, IDUSO, IDPOSTEGGIO, IDCONTO);

CREATE TABLE BOLL_GEST_FASE4
(
  IDCOMUNE VARCHAR2(6 CHAR) NOT NULL,
  GUID VARCHAR2(60 CHAR) NOT NULL,
  IDBOLLGEST NUMBER(4,0) NOT NULL,
  IDBOLLGESTDETT NUMBER(10,0) NOT NULL,
  IDMERCATO NUMBER(4,0) NOT NULL,
  IDPOSTEGGIO NUMBER(6,0) NOT NULL,
  FLAG_VALIDATA NUMBER(1,0) NOT NULL,
  FK_RETTIFICA_ID NUMBER(10,0) NULL,
  DESCRIZIONE VARCHAR2(1000 CHAR) NOT NULL,
  FLAG_INS_AUTO NUMBER(1,0) NOT NULL,
  FK_CODICEANAGRAFE NUMBER(6,0) NOT NULL,
  FK_CONTO_ID NUMBER(6,0) NOT NULL,
  FK_POSDEBDETTAGLIO_ID NUMBER(10,0) NULL,
  FLAG_ELIMINATA NUMBER(1,0) NOT NULL,
  NOTE_UTENTE VARCHAR2(4000 CHAR) NULL,
  NOTE_SISTEMA VARCHAR2(4000 CHAR) NULL,
  FLAG_RETTIFICATA NUMBER(1,0) NOT NULL,
  IMPORTO_SENZA_IVA NUMBER(11,2) NOT NULL,
  IVA NUMBER(2,0) NULL,
  IMPORTO_TOTALE NUMBER(11,2) NOT NULL,
  FLAG_CONGUAGLIO NUMBER(1,0) NOT NULL,
  DATA_SCADENZA DATE NULL
);

CREATE INDEX IDX_BGFASE4_001 ON BOLL_GEST_FASE4(IDCOMUNE, GUID, FK_CONTO_ID, FK_CODICEANAGRAFE, IDPOSTEGGIO);
CREATE INDEX IDX_BGFASE4_002 ON BOLL_GEST_FASE4(IDCOMUNE, GUID, FK_CODICEANAGRAFE, IDPOSTEGGIO);
CREATE INDEX IDX_BGFASE4_003 ON BOLL_GEST_FASE4(IDCOMUNE, IDBOLLGESTDETT);

CREATE TABLE BOLL_GEST_FASE5
(
  IDCOMUNE VARCHAR2(6 CHAR) NOT NULL,
  GUID VARCHAR2(60 CHAR) NOT NULL,
  FK_AUTORIZZAZIONE_ID NUMBER(6,0) NOT NULL,
  FK_BOLLGESTDET_ID NUMBER(10,0) NOT NULL,
  FK_BOLLGEST_ID NUMBER(4,0) NOT NULL,
  FK_AUTSUBENTRI_ID NUMBER(6,0) NULL
);

CREATE INDEX IDX_BGFASE5_001 ON BOLL_GEST_FASE5(IDCOMUNE, GUID);

ALTER TABLE BOLL_CFG_TIPO ADD (FLAG_CARICAM_MASSIVO NUMBER(1,0) DEFAULT 0 NOT NULL);

UPDATE verticalizzazionibase
SET
descrizione='(OBSOLETO) La funzionalità di configurazione delle firme remote e'' raggiungibile dal menu'' archivi-->archivi di base-->Gestione firme remote. ' || descrizione
WHERE
modulo = 'FIRMA_REMOTA_ARUBA' OR modulo ='FIRMA_REMOTA_INFOCERT';

CREATE TABLE CONFIGURAZIONI_METADATI (
        IDCOMUNE VARCHAR2 (6 CHAR) NOT NULL,
        FKIDCOMUNIASSOCIATISOFTWARE NUMERIC(8, 0) NOT NULL,
        CHIAVE VARCHAR2 (254 CHAR) NOT NULL,
        VALORE VARCHAR2 (4000 CHAR),
        SOFTWARE VARCHAR2 (2 CHAR),
        ORDINE NUMERIC(10, 0),
        CATEGORIA VARCHAR2(254 CHAR)
    );

ALTER TABLE CONFIGURAZIONI_METADATI ADD CONSTRAINT PK_CONFIGURAZIONI_METADATI PRIMARY KEY (IDCOMUNE, FKIDCOMUNIASSOCIATISOFTWARE, CHIAVE);

ALTER TABLE CONFIGURAZIONI_METADATI ADD CONSTRAINT FK_CONFIGUDATI_COMUNOFTWARE FOREIGN KEY (IDCOMUNE, FKIDCOMUNIASSOCIATISOFTWARE) REFERENCES COMUNIASSOCIATISOFTWARE (IDCOMUNE, ID);

UPDATE CONTI SET DATASCADENZA=TO_DATE('2999-12-31','YYYY-MM-DD') WHERE DATASCADENZA IS NULL;
ALTER TABLE CONTI MODIFY DATASCADENZA DATE NOT NULL;
ALTER TABLE CONTI MODIFY DESCRIZIONE VARCHAR2(100 CHAR) NOT NULL;   

UPDATE MERCATI_FORMULE_CALCOLO SET DATA_FINE_VALIDITA=TO_DATE('2999-12-31','YYYY-MM-DD') WHERE DATA_FINE_VALIDITA IS NULL;
ALTER TABLE MERCATI_FORMULE_CALCOLO MODIFY DATA_FINE_VALIDITA DATE NOT NULL;
       
UPDATE MERCATI_CONTABILITA_TRIBUTI SET DATA_FINE_VALIDITA=TO_DATE('2999-12-31','YYYY-MM-DD') WHERE DATA_FINE_VALIDITA IS NULL;
ALTER TABLE MERCATI_CONTABILITA_TRIBUTI MODIFY DATA_FINE_VALIDITA DATE NOT NULL;

ALTER TABLE prot_allegatiprotocollo MODIFY AD_DESCRIZIONE VARCHAR2(70);


ALTER TABLE prot_oggetti MODIFY  NOMEFILE VARCHAR2(256);


ALTER TABLE prot_oggetti
ADD (
    DIMENSIONE NUMBER,
    PERCORSO   VARCHAR2(512),
    AGGIORNA   TIMESTAMP
);

ALTER TABLE prot_oggetti RENAME COLUMN DIMENSIONE TO DIMENSIONE_FILE;
ALTER TABLE prot_oggetti MODIFY DIMENSIONE_FILE DECIMAL(9,0);
ALTER TABLE prot_oggetti MODIFY AGGIORNA VARCHAR2(20);


CREATE TABLE FO_RATING_MAIN (
    IDCOMUNE VARCHAR2(6 char) NOT NULL,
    ID NUMBER(6) NOT NULL,
    TIPO VARCHAR2(64 char) DEFAULT 'pagina' NOT NULL,
    TESTO VARCHAR2(256 char) NOT NULL,
    CONSTRAINT PK_FO_RATING_MAIN PRIMARY KEY (IDCOMUNE, ID),
    CONSTRAINT UQ_FO_RATING_MAIN_TIPO UNIQUE (IDCOMUNE, TIPO)
);

CREATE TABLE FO_RATING_SUB_QUESTION (
    IDCOMUNE VARCHAR2(6 char) NOT NULL,
    ID NUMBER(6) NOT NULL,
    IDRATINGMAIN NUMBER(6) NOT NULL,
    ISPOSITIVE NUMBER(1) NOT NULL,
    TESTO VARCHAR2(256 char) NOT NULL,
    CONSTRAINT PK_FO_RATING_SUB_QUESTION PRIMARY KEY (IDCOMUNE, ID),
    CONSTRAINT UQ_FO_RATING_SUB_QUESTION UNIQUE (IDCOMUNE, IDRATINGMAIN, ISPOSITIVE),
    CONSTRAINT FK_FO_RATINGSUBQ_MAIN FOREIGN KEY (IDCOMUNE, IDRATINGMAIN) REFERENCES FO_RATING_MAIN(IDCOMUNE, ID)
);

CREATE INDEX IDX_FO_RATINGSUBQ_MAIN ON FO_RATING_SUB_QUESTION (IDCOMUNE, IDRATINGMAIN);

CREATE TABLE FO_RATING_CHOICE (
    IDCOMUNE VARCHAR2(6) NOT NULL,
    ID NUMBER(6) NOT NULL,
    IDRATINGSUBQUESTION NUMBER(6) NOT NULL,
    TESTO VARCHAR2(256 char) NOT NULL,
    ORDINE NUMBER(6),
    CONSTRAINT PK_FO_RATING_CHOICE PRIMARY KEY (IDCOMUNE, ID),
    CONSTRAINT FK_FO_RATINGCHOICE_SUBQ FOREIGN KEY (IDCOMUNE, IDRATINGSUBQUESTION) REFERENCES FO_RATING_SUB_QUESTION(IDCOMUNE, ID)
);

CREATE INDEX IDX_FO_RATINGCHOICE_SUBQ ON FO_RATING_CHOICE (IDCOMUNE, IDRATINGSUBQUESTION);

CREATE TABLE FO_RATING_RESULT (
    IDCOMUNE VARCHAR2(6 char) NOT NULL,
    ID NUMBER(6) NOT NULL,
    IDENTIFIER VARCHAR2(64 char) NOT NULL,
    STARS NUMBER(6) NOT NULL,
    FKIDCHOICE NUMBER(6) NOT NULL,
    RATINGCOMMENT VARCHAR2(512 char) NULL,
    CONSTRAINT PK_FO_RATING_RESULT PRIMARY KEY (IDCOMUNE, ID),
    CONSTRAINT FK_FO_RATING_RESULT_CHOICE FOREIGN KEY (IDCOMUNE, FKIDCHOICE)
        REFERENCES FO_RATING_CHOICE(IDCOMUNE, ID)
);

CREATE INDEX IDX_FO_RATING_RESULT_CHOICE ON FO_RATING_RESULT (IDCOMUNE, FKIDCHOICE);
ALTER TABLE boll_cfg_tipo MODIFY SCADENZEPERIODI VARCHAR2(100 CHAR);


ALTER TABLE SORTEGGITESTATAINFO MODIFY VALORE VARCHAR2(4000 char);

CREATE TABLE FO_DOMANDE_SSU(
 IDCOMUNE VARCHAR2(6 char) NOT NULL,
 ID NUMBER(10,0) NOT NULL,
 FK_IDDOMANDA NUMBER(6,0) NOT NULL,
 CUI VARCHAR2(64 char) NOT NULL,
 NUMERO_DOMANDA_SSU VARCHAR2(64 char) NOT NULL,
 DATA_PRESENTAZIONE DATE NOT NULL,
 ALIAS VARCHAR2(10 char) NOT NULL,
 STATO NUMBER(3,0) NOT NULL,
 CODICEOGGETTO_RICEVUTA NUMBER(10,0) NULL,
 PRIMARY KEY (IDCOMUNE,ID),
 CONSTRAINT FK_SSU_FO_DOMANDE FOREIGN KEY (IDCOMUNE,FK_IDDOMANDA) REFERENCES FO_DOMANDE (IDCOMUNE,ID),
 CONSTRAINT FK_SSU_FO_OGG FOREIGN KEY (IDCOMUNE, CODICEOGGETTO_RICEVUTA) REFERENCES OGGETTI(IDCOMUNE, CODICEOGGETTO)
);