package it.gruppoinit.pal.gp.pay.domain;

import java.io.Serializable;
// Generated 4-set-2019 12.55.58 by Hibernate Tools 4.3.1
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.id.enhanced.TableGenerator;

import it.gruppoinit.pal.gp.core.domain.BaseDomainObject;
import it.gruppoinit.pal.gp.core.domain.IdAwareDomainObject;
import it.gruppoinit.pal.gp.core.domain.PkId;

/**
 * PaySessioniPagamento generated by hbm2java
 */
@Entity
@Table(name = "PAY_SESSIONI_PAGAMENTO")
public class PaySessioniPagamento extends BaseDomainObject implements Serializable, IdAwareDomainObject<PkId> {

    private static final long serialVersionUID = -7201427268961648367L;
    private PkId id;
    private PayPosizioniDebitorie posizioneDebitoria;
    private String idSessionePagamento;
    private Date dataInizio;
    private String digestSicurezza;
    private Boolean esito;
    private String urlRedirectEsito;

    public PaySessioniPagamento() {

	this.id = new PkId();
	this.posizioneDebitoria = new PayPosizioniDebitorie();
    }

    public PaySessioniPagamento(PkId id) {

	this.id = id;
	this.posizioneDebitoria = new PayPosizioniDebitorie();
    }

    @EmbeddedId
    @GenericGenerator(name = "pkGenerator", strategy = "it.gruppoinit.pal.gp.core.dao.helper.PkIdGenerator", parameters = {
	    @Parameter(name = TableGenerator.CONFIG_PREFER_SEGMENT_PER_ENTITY, value = "true"),
	    @Parameter(name = TableGenerator.TABLE_PARAM, value = "SEQUENCETABLE"),
	    @Parameter(name = TableGenerator.VALUE_COLUMN_PARAM, value = "CURRVAL"),
	    @Parameter(name = TableGenerator.SEGMENT_COLUMN_PARAM, value = "SEQUENCENAME"),
	    @Parameter(name = TableGenerator.SEGMENT_VALUE_PARAM, value = "PAY_SESSIONI_PAGAMENTO.ID") })
    @GeneratedValue(generator = "pkGenerator")
    @AttributeOverrides({ @AttributeOverride(name = "idcomune", column = @Column(name = "IDCOMUNE", nullable = false, length = 6)),
	    @AttributeOverride(name = "codice", column = @Column(name = "ID", nullable = false, precision = 6, scale = 0)) })
    public PkId getId() {

	return this.id;
    }

    public void setId(PkId id) {

	this.id = id;
    }

    @NotNull
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumns({ @JoinColumn(name = "FK_POSIZIONE_DEBITORIA", referencedColumnName = "ID", insertable = false, updatable = false),
	    @JoinColumn(name = "IDCOMUNE", referencedColumnName = "IDCOMUNE", insertable = false, updatable = false) })
    public PayPosizioniDebitorie getPosizioneDebitoria() {

	return this.posizioneDebitoria;
    }

    public void setPosizioneDebitoria(PayPosizioniDebitorie payPosizioniDebitorie) {

	this.posizioneDebitoria = payPosizioniDebitorie;
    }

    private Integer posizioneDebitoriaId;

    @Column(name = "FK_POSIZIONE_DEBITORIA")
    private Integer getPosizioneDebitoriaId() {

	if (null != this.getPosizioneDebitoria()) {
	    if (null != this.getPosizioneDebitoria().getId()) {
		this.posizioneDebitoriaId = getPosizioneDebitoria().getId().getCodice();
		return this.posizioneDebitoriaId;
	    }
	}
	return null;
    }

    @SuppressWarnings("unused")
    private void setPosizioneDebitoriaId(Integer posId) {

	if (null != this.getPosizioneDebitoria()) {
	    if (null != this.getPosizioneDebitoria().getId()) {
		this.posizioneDebitoriaId = getPosizioneDebitoria().getId().getCodice();
	    }
	}
    }

    @NotNull
    @Column(name = "ID_SESSIONE_PAGAMENTO", nullable = false, length = 50)
    public String getIdSessionePagamento() {

	return this.idSessionePagamento;
    }

    public void setIdSessionePagamento(String idSessionePagamento) {

	this.idSessionePagamento = idSessionePagamento;
    }

    @NotNull
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "DATA_INIZIO", nullable = false)
    public Date getDataInizio() {

	return this.dataInizio;
    }

    public void setDataInizio(Date dataInizio) {

	this.dataInizio = dataInizio;
    }

    @Column(name = "DIGEST_SICUREZZA", nullable = true, length = 255)
    public String getDigestSicurezza() {

	return this.digestSicurezza;
    }

    public void setDigestSicurezza(String digestSicurezza) {

	this.digestSicurezza = digestSicurezza;
    }

    @Column(name = "ESITO", nullable = true, precision = 1, scale = 0)
    public Boolean getEsito() {

	return this.esito;
    }

    public void setEsito(Boolean esito) {

	this.esito = esito;
    }

    @Column(name = "URL_REDIRECT_ESITO", nullable = true, length = 255)
    public String getUrlRedirectEsito() {

	return urlRedirectEsito;
    }

    public void setUrlRedirectEsito(String urlRedirectEsito) {

	this.urlRedirectEsito = urlRedirectEsito;
    }
}
