CREATE TABLE PAY_ALIQUOTE_IVA 
(	
ID NUMBER(3,0) NOT NULL,
DESCRIZIONE VARCHAR2(20) NOT NULL,
ALIQUOTA NUMBER(2,0) NOT NULL
);

ALTER TABLE PAY_ALIQUOTE_IVA  ADD CONSTRAINT PAY_ALIQUOTE_IVA_PK PRIMARY KEY (ID) ;

CREATE TABLE PAY_CONNECTOR_CONFIG 
(	
CODICE VARCHAR2(20) NOT NULL,
DESCRIZIONE VARCHAR2(50),
PAY_CONNECTOR_JAVA_CLASS VARCHAR2(255) NOT NULL 
);

ALTER TABLE PAY_CONNECTOR_CONFIG ADD CONSTRAINT PAY_CONNECTOR_CONFIG_PK PRIMARY KEY (CODICE) ;

COMMENT ON TABLE PAY_CONNECTOR_CONFIG  IS 'TABELLA PER LA CONFIGURAZIONE DEI CONNETTORI DI PAGAMENTO JAVA DEL NODO PAGAMENTI. I SERVIZI SPECIFICI DI CIASCUN PSP INTEGRATO IN VBG VENGONO GESTITI DAL CONNETTORE JAVA SPECIFICO DI QUEL PSP.';


 
CREATE TABLE PAY_CONTI
(
ID NUMBER(6,0) NOT NULL,
IDCOMUNE VARCHAR2(6) NOT NULL,
SOFTWARE VARCHAR2(2) NOT NULL,
DESCRIZIONE VARCHAR2(100) NOT NULL,
FK_AMMINISTRAZIONE NUMBER(4,0),
FK_ALIQUOTA_IVA NUMBER(3,0)
);

ALTER TABLE PAY_CONTI ADD CONSTRAINT PAY_CONTI_PK PRIMARY KEY (IDCOMUNE, ID);
ALTER TABLE PAY_CONTI ADD CONSTRAINT PAYCON_FK_AMMIN FOREIGN KEY (IDCOMUNE, FK_AMMINISTRAZIONE)  REFERENCES AMMINISTRAZIONI (IDCOMUNE, CODICEAMMINISTRAZIONE); 
ALTER TABLE PAY_CONTI ADD CONSTRAINT PAYCON_FK_IVA FOREIGN KEY (FK_ALIQUOTA_IVA) REFERENCES PAY_ALIQUOTE_IVA (ID);


COMMENT ON COLUMN PAY_CONTI.FK_AMMINISTRAZIONE IS 'RIFERIMENTO ALL''AMMINISTRAZIONE A CUI FA RIFERIMENTO IL CONTO';

COMMENT ON COLUMN PAY_CONTI.FK_ALIQUOTA_IVA IS 'ALIQUOTA IVA UTILIZZATA DI DEFAULT NELLE REGISTRAZIONI CONTABILI CHE AFFERISCONO AL CONTO'; COMMENT ON TABLE PAY_CONTI  IS 'CONTI PER LA CONTABILIZZAZIONE E L''AGGREGAZIONE DELLE POSIZIONI DEBITORIE';



CREATE TABLE PAY_REGISTRAZIONI_CAUSALI
(ID NUMBER(6,0) NOT NULL,
IDCOMUNE VARCHAR2(6) NOT NULL,
SOFTWARE VARCHAR2(2) NOT NULL,
DESCRIZIONE VARCHAR2(40) NOT NULL,
ORDINE NUMBER(6,0),
FLAG_RIDUZIONE NUMBER(1,0),
FLAG_NOINCASSI NUMBER(1,0)
) ;

ALTER TABLE PAY_REGISTRAZIONI_CAUSALI ADD CONSTRAINT PAY_REGISTRAZIONI_CAUSALI_PK PRIMARY KEY (IDCOMUNE, ID);


COMMENT ON COLUMN PAY_REGISTRAZIONI_CAUSALI.FLAG_RIDUZIONE IS 'SE IMPOSTATO A 1 LA REGISTRAZIONE CONTABILE DEVE ESSERE CON SEGNOO NEGATIVO';

COMMENT ON COLUMN PAY_REGISTRAZIONI_CAUSALI.FLAG_NOINCASSI IS 'SE IMPOSTATO A 1 LE REGISTRAZIONI CONTABILI CON QUESTA CAUSALE NON SARANNO RICOLLEGATE AL FLUSSO DI RERNDICONTAZIONE DEI PAGAMENTI';

COMMENT ON TABLE PAY_REGISTRAZIONI_CAUSALI  IS 'TABELLA DELLE CAUSALI DELLE REGISTRAZIONI CONTABILI';


CREATE TABLE PAY_IO_EVENTI 
(	
ID NUMBER(9,0) NOT NULL,
IDCOMUNE VARCHAR2(6) NOT NULL,
DATA DATE NOT NULL,
TIPO_EVENTO VARCHAR2(30) NOT NULL,
FLAG_ENTRATA NUMBER(1,0) NOT NULL,
ESITO NUMBER(1,0) NOT NULL,
ID_MESSAGGIO VARCHAR2(100),
CODICE_COMUNICAZIONE VARCHAR2(100),
DESC_ESITO VARCHAR2(100),
CODICE_ESITO VARCHAR2(20),
INFO VARCHAR2(400)
) ;

ALTER TABLE PAY_IO_EVENTI ADD CONSTRAINT PAY_IO_SERVIZI_PK PRIMARY KEY (IDCOMUNE, ID) ;

COMMENT ON COLUMN PAY_IO_EVENTI.TIPO_EVENTO IS 'STRINGA CHE CODIFICA DEL TIPO DI EVENTO';

COMMENT ON COLUMN PAY_IO_EVENTI.FLAG_ENTRATA IS '1=ENTRATA, 0= USCITA';

COMMENT ON COLUMN PAY_IO_EVENTI.ESITO IS '0=KO, 1=OK, 2=PARZIALE';

COMMENT ON COLUMN PAY_IO_EVENTI.ID_MESSAGGIO IS 'IDENTIFICATIVO UNIVOCO DEL MESSAGGIO';

COMMENT ON COLUMN PAY_IO_EVENTI.CODICE_COMUNICAZIONE IS 'CODICE CHE PUO'' SERVIRE PER METTERE IN RELAZIONE FRA LORO CHIAMATE DIVERSE COLLEGATE ALLA STESSA CONVERSAZIONE CLIENT SERVER';

COMMENT ON COLUMN PAY_IO_EVENTI.CODICE_ESITO IS 'CODIFICA DELL''ESITO SPECIFICA DEL PSP CHE SI INTEGRA IN VBG';

COMMENT ON COLUMN PAY_IO_EVENTI.INFO IS 'ALTRE INFO SPECIFICHE DELL''EVENTO';

COMMENT ON TABLE PAY_IO_EVENTI  IS 'TABELLA CHE TIENE TRACCIA DELLE CHIAMATE A O DA I SERVIZI WS DEL PSP E DI ALTRI EVENTI APPLICATIVI COME INVIO AVVISI, INTEGRAZIONE GESTIONALI ETC. VIENE TENUTA TRACCIA DEGLI ESITI DELLE CHIAMATE, LA DATE ORA IN CUI SI VERIFICANO, GLI ID UNIVOCI DEI MESSAGGI E CONSENTE DI MEMORIZZARE DEGLI IDENTIFICATIVI CHE CONSENTONO DI ASSOCIARE PIU'' CHIAMATE DIVERSE FUNZIONALMENTE COLLEGATE IN UNA UNICA CONVERSAZIONE CLIENT SERVER.';


CREATE TABLE PAY_REGISTRAZIONI_CONTABILI 
(	
IDCOMUNE VARCHAR2(6) NOT NULL,
ID NUMBER(9,0) NOT NULL,
DATA_REGISTRAZIONE DATE NOT NULL,
DESCRIZIONE VARCHAR2(200),
IMPORTO NUMBER(12,2) NOT NULL,
NOTE VARCHAR2(2000),
FK_CAUSALE_REG NUMBER(6,0) NOT NULL,
ANNO NUMBER(4,0) NOT NULL,
SOFTWARE VARCHAR2(2) NOT NULL,
FK_ANAGRAFE_TITOLARE NUMBER(6,0),
FK_REGCONT_SALDO NUMBER(9,0),
IVA NUMBER(2,0),
FK_CONTO NUMBER(6,0),
DESC_CAUSALE VARCHAR2(200),
DESC_CONTO VARCHAR2(50)
);

ALTER TABLE PAY_REGISTRAZIONI_CONTABILI ADD CONSTRAINT PAY_REGISTRAZIONI_CONTABIL_PK PRIMARY KEY (IDCOMUNE, ID); 
ALTER TABLE PAY_REGISTRAZIONI_CONTABILI ADD CONSTRAINT PAY_REGCONT_FK_ANAG FOREIGN KEY (IDCOMUNE, FK_ANAGRAFE_TITOLARE)  REFERENCES ANAGRAFE (IDCOMUNE, CODICEANAGRAFE); 
ALTER TABLE PAY_REGISTRAZIONI_CONTABILI ADD CONSTRAINT PAY_REGCONT_FK_REGCAUS FOREIGN KEY ( IDCOMUNE, FK_CAUSALE_REG) REFERENCES PAY_REGISTRAZIONI_CAUSALI (IDCOMUNE, ID); 
ALTER TABLE PAY_REGISTRAZIONI_CONTABILI ADD CONSTRAINT PAY_REGCONT_FK_REGCONT FOREIGN KEY (IDCOMUNE, FK_REGCONT_SALDO)  REFERENCES PAY_REGISTRAZIONI_CONTABILI (IDCOMUNE, ID); 
ALTER TABLE PAY_REGISTRAZIONI_CONTABILI ADD CONSTRAINT PAY_REGISTRAZIONI_CONTABI_FK1 FOREIGN KEY (IDCOMUNE, FK_CONTO) REFERENCES PAY_CONTI (IDCOMUNE, ID); 
 
COMMENT ON COLUMN PAY_REGISTRAZIONI_CONTABILI.IMPORTO IS 'IMPORTO LORDO COMPRENSIVO DI IVA. VALORI NEGATIVI INDICANO DEBITI DELLA PA VERSO ALTRI SOGGETTI';

COMMENT ON COLUMN PAY_REGISTRAZIONI_CONTABILI.FK_CAUSALE_REG IS 'CAUSALE DELLA REGISTRAZIONE CONTABILE DECODIFICATA NELLA TABELLA DELLE CAUSALI';

COMMENT ON COLUMN PAY_REGISTRAZIONI_CONTABILI.FK_ANAGRAFE_TITOLARE IS 'RIFERIMENTO AL TITOLARE DELLA REGISTRAZIONE OSSIA AL DEBITORE (O CREDITORE SE L''IMPORTO E'' NEGATIVO)';

COMMENT ON COLUMN PAY_REGISTRAZIONI_CONTABILI.FK_REGCONT_SALDO IS 'CAMPO UTILIZZATO PER GLI ACCORPAMENTI DI PIU'' REGISTRAZIONI CONTABILI IN UNICO CONTO CUMULATIVO. IN QUESTI CASI SI DOVRA'' CREARE UNA NUOVA REGISTRAZIONE CONTABILE AVENTE COME IMPORTO LA SOMMA DEGLI IMPORTI DA CUMULARE E SI DOVRA'' FLAGGARE COME DISATTIVE LE REGISTRAZIONI CHE SI SONO ACCORPATE E IMPOSTARE IN CIASCUNA LA FK ALLA NUOVA REGISTRAZIONE CONTABILE DI SALDO.';

COMMENT ON COLUMN PAY_REGISTRAZIONI_CONTABILI.IVA IS 'ALIQUOTA IVA DA SCORPORARE DALL''IMPORTO LORDO';

COMMENT ON COLUMN PAY_REGISTRAZIONI_CONTABILI.FK_CONTO IS 'RIFERIMENTO AL CONTO A CUI E'' ASSOCIATA LA REGISTRAZIONE';

COMMENT ON COLUMN PAY_REGISTRAZIONI_CONTABILI.DESC_CAUSALE IS 'TESTO DESCRITTIVO DELLA CAUSALE DELLA REGISTRAZIONE. IL NODO PAGAMENTI SE CONFIGURATO PER SCRIVERE LE REGISTRAZIONI CONTABILI MEMORIZZA IN QUESTO CAMPO LA CUSALE RICEVUTA DALLA CHIAMATA AL SERVIZIO. LA VALORIZZAZIONE DI FK_CAUSALE_REG TRAMITE LOOKUP IN TABELLA O LOGICHE DI MAPPING NON E'' NECESSARIA IN ASSENZA DI UNA GESTIONE CONTABILE DEGLI ONERI DA BO, PERCIO'' SARA FATTA O MENO IN BASE ALLA CONFIGURAZIONE DEL NODO PAGAMENTI.';

COMMENT ON COLUMN PAY_REGISTRAZIONI_CONTABILI.DESC_CONTO IS 'TESTO DESCRITTIVO DEL CONTO ASSOCIATO ALLA REGISTRAZIONE. IL NODO PAGAMENTI SE CONFIGURATO PER SCRIVERE LE REGISTRAZIONI CONTABILI MEMORIZZA IN QUESTO CAMPO LA DESCRIZIONE DEL CONTO RICEVUTO NALLA CHIAMATA AL SERVIZIO. LA VALORIZZAZIONE DI FK_CONTO TRAMITE LOOKUP IN TABELLA O LOGICHE DI MAPPING NON E'' NECESSARIA IN ASSENZA DI UNA GESTIONE CONTABILE DEGLI ONERI DA BO, PERCIO'' SARA FATTA O MENO IN BASE ALLA CONFIGURAZIONE DEL NODO PAGAMENTI.';

COMMENT ON TABLE PAY_REGISTRAZIONI_CONTABILI  IS 'TABELLA CHE REGISTRA GLI IMPORTI DOVUTI ALL''AMMINISTRAZIONE DA PARTE DI SOGGETTI DEBITORI, GLI IMPORTI SONO AGGREGABILI PER ANNO ED ASSOCIATI AD UNA CAUSALEDI REGISTRAZIONE E AD UN''ANAGRAFICA CHE INDIVIDUA IL SOGGETTO DEBITORE';




CREATE TABLE PAY_SOGGETTI_DEBITORI 
(	
ID NUMBER(9,0) NOT NULL, 
IDCOMUNE VARCHAR2(6) NOT NULL, 
NOME VARCHAR2(50) NOT NULL, 
COGNOME VARCHAR2(50), 
CF_PI VARCHAR2(16) NOT NULL, 
VIA VARCHAR2(255), 
CIVICO VARCHAR2(20), 
CAP VARCHAR2(6), 
LOCALITA VARCHAR2(50), 
PROVINCIA VARCHAR2(50), 
STATO VARCHAR2(50), 
EMAIL VARCHAR2(255), 
FLAG_ATTIVO NUMBER(1,0) DEFAULT 1 NOT NULL
);

ALTER TABLE PAY_SOGGETTI_DEBITORI ADD CONSTRAINT PAY_SOGGETTI_DEBITORI_PK PRIMARY KEY (IDCOMUNE, ID);

COMMENT ON COLUMN PAY_SOGGETTI_DEBITORI.FLAG_ATTIVO IS 'PER EVITARE DI INSERIRE PIU'' VOLTE GLI STESSI DATI IDENTICI PER GLI STESSI SOGGETTI CHE EFFETTUANO PIU'' PAGAMENTI. IL NODO INSERISCE RECORD NUOVI SOLO SE NON ESISTE GIA'' UN RECORD PER LO STESSO CFPI CON TUTTI I DATI IDENTICI. SE IL CF ESISTE GIA'' MA CON DATI DIVERSI ALLORA IL RECORD ESISTENTE VIENE IMPOSTATO ATTIVO=0 ED INSERITO IL NUOVO RECORD CON ATTIVO = 1.';

COMMENT ON TABLE PAY_SOGGETTI_DEBITORI  IS 'TABELLA IN CUI VENGONO MEMORIZZATI I DATI ANAGRAFICI DEI SOGGETTI DEBITORI';



CREATE TABLE PAY_POSIZIONI_DEBITORIE 
(	
ID NUMBER(9,0) NOT NULL, 
IDCOMUNE VARCHAR2(6) NOT NULL,
SOFTWARE VARCHAR2(2) NOT NULL,
DESCRIZIONE_CAUSALE VARCHAR2(200) NOT NULL, 
IMPORTO NUMBER(12,2) NOT NULL, 
DATA_SCADENZA DATE NOT NULL, 
NUM_RATA NUMBER(3,0), 
IUV VARCHAR2(100),
FK_REGISTRAZIONE_CONTABILE NUMBER(9,0), 
FK_SOGGETTO_DEBITORE NUMBER(9,0), 
FK_OGGETTO_RICEVUTA NUMBER(9,0), 
FK_OGGETTO_AVVISO NUMBER(9,0), 
FK_OGGETTO_FATTURA NUMBER(9,0), 
CODICE_AVVISO VARCHAR2(50), 
ID_POSIZIONE_PSP VARCHAR2(50), 
DATA_INVIO_A_PSP DATE, 
DATA_ANNULLAMENTO DATE, 
DATA_REGISTRAZIONE DATE NOT NULL, 
ANNO NUMBER(4,0) NOT NULL );

ALTER TABLE PAY_POSIZIONI_DEBITORIE  ADD CONSTRAINT PAY_POSIZIONI_DEBITORIE_PK PRIMARY KEY (IDCOMUNE, ID);

ALTER TABLE PAY_POSIZIONI_DEBITORIE  ADD CONSTRAINT PAY_POSDEB_FK_REGCONT FOREIGN KEY (IDCOMUNE, FK_REGISTRAZIONE_CONTABILE ) REFERENCES PAY_REGISTRAZIONI_CONTABILI (IDCOMUNE, ID); 
ALTER TABLE PAY_POSIZIONI_DEBITORIE  ADD CONSTRAINT PAY_POSDEB_FK_SOGDEB FOREIGN KEY (IDCOMUNE, FK_SOGGETTO_DEBITORE) REFERENCES PAY_SOGGETTI_DEBITORI (IDCOMUNE, ID); 
ALTER TABLE PAY_POSIZIONI_DEBITORIE  ADD CONSTRAINT PAY_POSDEB_FK_OGGFAT FOREIGN KEY (IDCOMUNE, FK_OGGETTO_FATTURA) REFERENCES OGGETTI (IDCOMUNE, CODICEOGGETTO); 
ALTER TABLE PAY_POSIZIONI_DEBITORIE  ADD CONSTRAINT PAY_POSDEB_FK_OGGRT FOREIGN KEY (IDCOMUNE, FK_OGGETTO_RICEVUTA) REFERENCES OGGETTI (IDCOMUNE, CODICEOGGETTO);
ALTER TABLE PAY_POSIZIONI_DEBITORIE  ADD  CONSTRAINT PAY_POSDEB_FK_OGGAVV FOREIGN KEY (IDCOMUNE, FK_OGGETTO_AVVISO) REFERENCES OGGETTI (IDCOMUNE, CODICEOGGETTO);


COMMENT ON COLUMN PAY_POSIZIONI_DEBITORIE.NUM_RATA IS 'NUMERO PROGRESSIVO DELLA RATA';

COMMENT ON COLUMN PAY_POSIZIONI_DEBITORIE.IUV IS 'IDENTIFICATIVO UNICO DEL VERSAMENTO: CODICE IDENTIFICATIVO UNIVOCO NECESSARIO PER ATTIVARE IL PAGAMENTO ONLINE TRAMITE PAGO-PA';

COMMENT ON COLUMN PAY_POSIZIONI_DEBITORIE.FK_REGISTRAZIONE_CONTABILE IS 'RIFERIMENTO ALLA REGISTRAZIONE CONTABILE DA CUI DERIVA LA POSIZIONE DEBITORIA';

COMMENT ON COLUMN PAY_POSIZIONI_DEBITORIE.FK_SOGGETTO_DEBITORE IS 'RIFERIMENTO AL SOGGETTO DEBITORE VALORIZZATO SOLO DAL NODO DEI PAGAMENTI PER LASCIARE TRACCIA STORICIZZATA DEI DATI ANAGRAFICI DELLA POSIZIONE DEB. AL SICURA DA MODIFICHE NELLA TABELLA ANAGRAFE';

COMMENT ON COLUMN PAY_POSIZIONI_DEBITORIE.FK_OGGETTO_RICEVUTA IS 'RICEVUTA TELEMATICA RECUPERATA DA PAGOPA';

COMMENT ON COLUMN PAY_POSIZIONI_DEBITORIE.FK_OGGETTO_AVVISO IS 'AVVISO DI PAGAMENTO';

COMMENT ON COLUMN PAY_POSIZIONI_DEBITORIE.FK_OGGETTO_FATTURA IS 'FATTURA SACRICATA DA INTEGRAZIONE CON GESTIONALE ESTERNO';

COMMENT ON COLUMN PAY_POSIZIONI_DEBITORIE.ID_POSIZIONE_PSP IS 'IDENTIFICATIVO UNIVOCO DELLA POSIZIONE DEBITORIA DEL PSP (PAYMENT SERVICE PROVIDER) DA USARE QUALORA IL FLUSSO DI RENDICONTAZIONE NON USI L''IUV PER IDENTIFICARE LE TRANSAZIONI';

COMMENT ON COLUMN PAY_POSIZIONI_DEBITORIE.DATA_INVIO_A_PSP IS 'IL FLAG SERVE PER DISTINGUERE I RECORD CHE SONO PRESENTI SOLO NEL NODO DEI PAGAMENTI DA QUELLI CHE SONO EFFETTIVAMENTE STATI TRASMESSI AL PSP MA IL PSP NON HA ANCORA COMUNICATO AL NODO GLI IUV (IL SERVIZIO PUO'' ESSERE ASINCRONO)';

COMMENT ON TABLE PAY_POSIZIONI_DEBITORIE  IS 'TABELLA CHE REGISTRA LE SINGOLE POSIZIONI DEBITORIE. OGNI POSIZIONE DEBITORIA RAPPRESENZA UN IMPORTO SALDABILE IN UN UNICA SOLUZIONE. UNA REGISTRAZIONE CONTABILE SUDDIVISA IN TRE RATE DARA'' LUOGO A TRE DISTINTE POSIZIONI DEBITORIE CIASCUNA CON LA SUA DATA DI SCADENZA. ';


CREATE UNIQUE INDEX PAY_POSDEB_UIDX ON PAY_POSIZIONI_DEBITORIE (IUV) ;


CREATE TABLE PAY_PAGAMENTI 
(	
ID NUMBER(9,0) NOT NULL,
DATA_SISTEMA DATE NOT NULL,
DATA_PAGAMENTO DATE,
IMPORTO_PAGATO NUMBER(12,2),
IUV VARCHAR2(200),
ID_POSIZIONE_PSP VARCHAR2(50),
RIF_PAGAMENTO VARCHAR2(50),
MODALITA_PAGAMENTO VARCHAR2(50),
FK_POSIZIONE_SALDATA NUMBER(9,0),
IDCOMUNE VARCHAR2(6), 
DESCRIZIONE_CAUSALE VARCHAR2(200), 
NOTE VARCHAR2(2000), 
FK_SOGGETTO_PAGATORE NUMBER(9,0) NOT NULL, 
FLAG_NOTIFICA NUMBER(1,0) DEFAULT 0, 
ID_FLUSSO_RENDICONTAZIONE VARCHAR2(50), 
DATA_ORA_INIZIO_TRANS DATE, 
DATA_ORA_AUTORIZZAZIONE DATE, 
IUR VARCHAR2(100), 
IMPORTO_TRANSATO NUMBER(12,2), 
IMPORTO_COMMISSIONI NUMBER(12,2)
);


ALTER TABLE PAY_PAGAMENTI ADD CONSTRAINT PAY_PAGAMENTI_PK PRIMARY KEY (IDCOMUNE, ID); 
ALTER TABLE PAY_PAGAMENTI ADD CONSTRAINT PAY_PAG_FK_POSDEB FOREIGN KEY (IDCOMUNE, FK_POSIZIONE_SALDATA )  REFERENCES PAY_POSIZIONI_DEBITORIE (IDCOMUNE, ID); 
ALTER TABLE PAY_PAGAMENTI ADD CONSTRAINT PAY_PAG_FK_SOGDEB FOREIGN KEY (IDCOMUNE, FK_SOGGETTO_PAGATORE)  REFERENCES PAY_SOGGETTI_DEBITORI (IDCOMUNE, ID);

 
COMMENT ON COLUMN PAY_PAGAMENTI.DATA_SISTEMA IS 'DATA DI REGISTRAZIONE A SISTEMA DELL''AVVENUTO PAGAMENTO';

COMMENT ON COLUMN PAY_PAGAMENTI.IUV IS 'IDENTIFICATIOVO UNIVOCO DEL VERSAMENTO PAGOPA';

COMMENT ON COLUMN PAY_PAGAMENTI.ID_POSIZIONE_PSP IS 'IDENTIFICATIVO UNIVOCO DELLA POSIZIONE DEBITORIA DEL PSP (PAYMENT SERVICE PROVIDER) DA USARE QUALORA IL FLUSSO DI RENDICONTAZIONE NON USI L''IUV PER IDENTIFICARE LE TRANSAZIONI';

COMMENT ON COLUMN PAY_PAGAMENTI.RIF_PAGAMENTO IS 'RIFERIMENTI DELL''AVVENUTO PAGAMENTO DA MOSTRARE AGLI UTENTI';

COMMENT ON COLUMN PAY_PAGAMENTI.MODALITA_PAGAMENTO IS 'TESTO DESCRITTIVO DELLA MODALITA'' DI PAGAMENTO';

COMMENT ON COLUMN PAY_PAGAMENTI.FK_POSIZIONE_SALDATA IS 'RIFERIMENTO ALLA POSIZIONE DEBITORIA DI CUI IL PAGAMENTO E'' IL SALDO';

COMMENT ON COLUMN PAY_PAGAMENTI.IDCOMUNE IS 'RIFERIMENTO ALLA POSIZIONE DEBITORIA DI CUI IL PAGAMENTO E'' IL SALDO';

COMMENT ON COLUMN PAY_PAGAMENTI.DESCRIZIONE_CAUSALE IS 'TESTO DESCRITTIVO DELLA CUSALE DEL VERSAMENTO';

COMMENT ON COLUMN PAY_PAGAMENTI.FK_SOGGETTO_PAGATORE IS 'RIFERIMENTO AL SOGGETTO CHE EFFETTUA IL PAGAMENTO (SE DIVERSO DAL DEBITORE)';

COMMENT ON COLUMN PAY_PAGAMENTI.FLAG_NOTIFICA IS '1=NOTIFICA DEL PAGAMENTO DAL PSP, 0=FLUSSO DI RENDICONTAZIONE DELL''ISTITUTO DI CREDITO CHE HA GESTITO LA TRANSAZIONE';

COMMENT ON TABLE PAY_PAGAMENTI  IS 'TABELLA PER LA REGISTRAZIONE DEI FLUSSI DI RENDICONTAZIONE E NOTIFICA DEI PAGAMENTI CONTENENTI LE INFO SULLE TRANSAZIONI AFFETTIVAMENTE ANDATE A BUON FINE. I PAYMENT ADAPTER (CONNETTORI DI PAGAMENTO SPECIFICI DEI PSP) DEVONO REGISTRARE IL FLUSSO DI RENDICONTAZIONE DI LORO INTERESSE TRAMITE SPECIFICI SERVIZI E METTERE IN RELAZIONE I RECORD DI QUESTA TABELLA CON LE POSIZIONI DEBITORIE DA CUI E'' PARTITA LA TRANSAZIONE TYRAMITE LA CORRISPONDENZA DELL''IUV O DI ALTRO IDENTIFICATIVO. LO STESSO PAGAMENTO PU0'' ENTRARE DUE VOLTE NELLA TABELLA: LA PRIMA COME NOTIFICA DELL''AVVENUTO PAGAMENTO DA PARTE DEL PSP, LA SECONDA COME RENDICONTAZIONE DELL''ISTITUTO DI CREDITO CHE HA EFFETTIVAMENTE GESTITO LA TRANSAZIONE ';


CREATE TABLE PAY_PROFILI_ENTI_CREDITORI 
(	
IDCOMUNE VARCHAR2(6) NOT NULL, 
ID NUMBER(10,0) NOT NULL,
CODICECOMUNE VARCHAR2(5),
CODICEAMMINISTRAZIONE NUMBER(10,0) NOT NULL, 
SOFTWARE VARCHAR2(2) NOT NULL, 
CBILL VARCHAR2(100), 
CC_POSTALE VARCHAR2(100), 
CF_CODICE_PROFILO VARCHAR2(20) NOT NULL
) ;


ALTER TABLE PAY_PROFILI_ENTI_CREDITORI ADD CONSTRAINT PAY_ENTI_CREDITORI_PK PRIMARY KEY (IDCOMUNE, ID);

ALTER TABLE PAY_PROFILI_ENTI_CREDITORI ADD CONSTRAINT PAY_EC_FK_AMMI FOREIGN KEY (IDCOMUNE, CODICEAMMINISTRAZIONE)  REFERENCES AMMINISTRAZIONI (IDCOMUNE, CODICEAMMINISTRAZIONE); 
ALTER TABLE PAY_PROFILI_ENTI_CREDITORI ADD CONSTRAINT PAY_EC_FK_COMUNI FOREIGN KEY (CODICECOMUNE) REFERENCES COMUNI (CODICECOMUNE);


COMMENT ON COLUMN PAY_PROFILI_ENTI_CREDITORI.CODICECOMUNE IS 'L''ASSENZA DEL CODICE COMUNE INDICA CHE LA CONFIGURAZIONE VALE PER TUTTI I COMUNI DEL GRUPPO (PER CUI NON ESISTE UNA CONFIGURAZIONE SPECIFICA)';

COMMENT ON COLUMN PAY_PROFILI_ENTI_CREDITORI.CF_CODICE_PROFILO IS 'IL CF E'' PASSATO AL NODO PAGAMENTI NELLE CHIAMATE AI SERVIZI E DA LI'' RECUPERA L''ID IDCOMUNE E IL SW DI RIFERIMENTO PER L''ESECUZIONE DEL SERVIZIO';

COMMENT ON TABLE PAY_PROFILI_ENTI_CREDITORI  IS 'TABELLA PER LA MEMORIZZAZIONE DEI DATI DEGLI ENTI CREDITORI DESTINATARI DEI PAGAMENTI GESTITI DAL NODO PAGAMENTI. 
LE CHIAMATE AI SERVIZI DEL NODO PAGAMENTI PREVEDONO IL PASSAGGIO DEL CF DELL''ENTE CREDITORE NELLA REQUEST. QUESTO CF E'' UTILIZZATO DAL NODO PER DETERMINARE L''IDCOMUNE SU CUI LAVORA IL SERVIZIO PER L''INTERA DURATA DELLA REQUEST.
LA GESTIONE DEGLI ENTI CREDITORI PUO'' ESSERE CUSTOMIZZATA PER SOFTWARE E PER CODICE COMUNE NEL CASO DI INSTALLAZIONI MULTICOMUNE.
';
 

CREATE UNIQUE INDEX UIX_EC_CF_CODICE_PROFILO ON PAY_PROFILI_ENTI_CREDITORI (CF_CODICE_PROFILO) ;


 
 
CREATE TABLE PAY_REG_CONTABILI_PAGAMENTI 
(	
ID NUMBER(9,0) NOT NULL,
IDCOMUNE VARCHAR2(6) NOT NULL,
FK_PAGAMENTO NUMBER(9,0) NOT NULL,
FK_REGISTRAZIONE_CONTABILE NUMBER(9,0) NOT NULL, 
IMPORTO_CONTABILIZZATO NUMBER(12,2) NOT NULL
)  ;

ALTER TABLE PAY_REG_CONTABILI_PAGAMENTI ADD CONSTRAINT PAY_REG_CONTABILI_PAGAMENT_PK PRIMARY KEY (IDCOMUNE, ID); 
ALTER TABLE PAY_REG_CONTABILI_PAGAMENTI ADD CONSTRAINT PAY_REGCONTPAG_FK_REGCONT FOREIGN KEY (IDCOMUNE, FK_REGISTRAZIONE_CONTABILE) REFERENCES PAY_REGISTRAZIONI_CONTABILI (IDCOMUNE, ID) ON DELETE CASCADE; 
ALTER TABLE PAY_REG_CONTABILI_PAGAMENTI ADD CONSTRAINT PAY_REGCONTPAG_FK_PAG FOREIGN KEY (IDCOMUNE,FK_PAGAMENTO) REFERENCES PAY_PAGAMENTI (IDCOMUNE,ID);

 
 
COMMENT ON COLUMN PAY_REG_CONTABILI_PAGAMENTI.FK_PAGAMENTO IS 'RIFERIMENTO AL PAGAMENTO CONTABILIZZATO';

COMMENT ON COLUMN PAY_REG_CONTABILI_PAGAMENTI.FK_REGISTRAZIONE_CONTABILE IS 'RIFEIMENTO ALLA REGISTRAZIONE CONTABILE A CUI VIENE ASSOCIATO L''AVVENUTO PAGAMENTO';

COMMENT ON COLUMN PAY_REG_CONTABILI_PAGAMENTI.IMPORTO_CONTABILIZZATO IS 'IMPORTO EFFETTIVAMENTE CONSIDERATO COME PAGAMENTO DELLA REGISTRAZIONE CONTABILE. E'' POSSIBILE CHE IN CONTABILITA'' I PAGAMENTI RICEVUTI VENGANO REGISTRTATI COME COMPENSAZIONE DI POSIZIONI DEBITORIE ANCORA APERTE DIVERSE DA QUELLA PER CUI IL DEBITORE HA EFFETTUATO IL VERSAMENTO. IN QUESTI CASI POTRTEBBE ESSERE CONSIDERATA SOLO UNA PARTE DELL''IMPORTO EFFETTIVAMENTE REGISTRATO DAL FLUSSO DI RENDICONTAZIONE';

COMMENT ON TABLE PAY_REG_CONTABILI_PAGAMENTI  IS 'TABELLA DI RELAZIONE N A M PER LA CONTABILIZZAZIONE DEI PAGAMENTI AVVENUTI CHE PROVENGONO DAL FLUSSO DI RENDICONTAZIONE. LA TABELLA ASSOCIA UNO O PIU'' PAGAMENTI ALLE REGISTRAZIONI CONTABILI. NLA PAGAMENTI COLLEGHERA'' SE POSSIBILE CIASCUN PAGAMENTO RICEVUTO ALLA REGISTRAZIONE CONTABILE CHE AVEVA EFFETTIVAMENTE GENERATO LA POSIZIONE DEBITORIA SALDATA, MA FUNZIONALITA'' DI CONTABILITA'' NEL BO POTREBBERO ANCHE CONSENTIRE DI CONSIDERARE UN PAGAMENTO COME COMPENSAZIONE DI UNA REGISTRAZIONE CONTABILE DIVERSA DA QUELLA PER CUI IL DEBITORE HA EFFETTIVAMENTE PAGATO (ES. IL PAGAMENTO DELLA PRIMA RATA 2019 VIENE CONTABILIZZATO COME PAGAMENTO DELL''ULTIMA RATA 2018 AL FINE DI POTER CHIUDERE LA COTABILITA'' 2018), IN QUESTI CASI E'' ANCHE POSSIBILE CHE L''IMPORTO ASSOCIATO COME PAGAMENTO SIA SOLO UNA FRAZIONE DELL''INTERO IMPORTO PAGATO EFFETTIVAMENTE DAL DEVITORE. ';

 
 
 
CREATE TABLE PAY_SESSIONI_PAGAMENTO 
(	
ID NUMBER(9,0) NOT NULL,
IDCOMUNE VARCHAR2(6) NOT NULL,
ID_SESSIONE_PAGAMENTO VARCHAR2(50) NOT NULL, 
DATA_INIZIO DATE NOT NULL, 
DIGEST_SICUREZZA VARCHAR2(255), 
ESITO NUMBER(1,0), 
FK_POSIZIONE_DEBITORIA NUMBER(9,0) NOT NULL 
);

ALTER TABLE PAY_SESSIONI_PAGAMENTO ADD CONSTRAINT PAY_SESSIONI_PAGAMENTO_PK PRIMARY KEY (IDCOMUNE, ID); 
ALTER TABLE PAY_SESSIONI_PAGAMENTO ADD CONSTRAINT PAY_SESSIONI_PAGAMENTO_FK1 FOREIGN KEY (IDCOMUNE, FK_POSIZIONE_DEBITORIA) REFERENCES PAY_POSIZIONI_DEBITORIE (IDCOMUNE, ID);
  
  
COMMENT ON COLUMN PAY_SESSIONI_PAGAMENTO.ID_SESSIONE_PAGAMENTO IS 'IDENTIFICATIVO VBG DELLA SESSIONE DI PAGAMENTO UTILIZZATO PER GESTIRNE L''ESITO, QUANDO L''UTENTE RITORNA DAL PORTALE DEI PAGAMENTI ALLA APP DA CUI ERA PARTITO IL NODO NLA RICEVE UNA CHIAMATA HTTP CONTENENTE L''ID PAGAMENTO FRA I PARAMETRI';

COMMENT ON COLUMN PAY_SESSIONI_PAGAMENTO.DATA_INIZIO IS 'DATA ORA DI CREAZIONE DELLA SESSIONE';

COMMENT ON COLUMN PAY_SESSIONI_PAGAMENTO.DIGEST_SICUREZZA IS 'CODICE DI SICUREZZA RICHIESTO COME PARAMETRO IN POST PER LA CHIAMATA DI ACCESSO INIZIALE AL PORTALE DEI PAGAMENTI';

COMMENT ON COLUMN PAY_SESSIONI_PAGAMENTO.ESITO IS 'L''ASSENZA DI ESITO NON SIGNIFICA CHE IL PAGAMENTO NON SIA ANDATO A BUON FINE POTREBBE MANCARE SOLO PERCHE'' L''UTENTE NON E'' RITORNATO INDIETRO ALL''APP CHIAMANTE AL TERMINE DELLA TRANSAZIONE';

COMMENT ON COLUMN PAY_SESSIONI_PAGAMENTO.FK_POSIZIONE_DEBITORIA IS 'RIFERIMENTO ALLA POSIZIONE DEBITORIA PER CUI SI CREA LA SESSIONE DI PAGAMENTO';

COMMENT ON TABLE PAY_SESSIONI_PAGAMENTO  IS 'TABELLA PER LA MEMORIZZAZIONE DEI PARAMETRI NECESSARI ALL''INDIRIZZAMENTO DEL SOGGETTO DEBITORE AL PORTALE DEI PAGAMENTI ONLINE E PER GESTIRE L''ESITO DELLA TRANSAZIONE NEL CASO IN CUI RITORNI ALLA NOSTRA APP AL TERMINE DELLA TRANSAZIONE';

 
CREATE TABLE PAY_STATO_PAGAMENTI 
(	
ID NUMBER(9,0) NOT NULL, 
IDCOMUNE VARCHAR2(6) NOT NULL, 
STATO VARCHAR2(30) NOT NULL, 
DESC_STATO VARCHAR2(200), 
FK_POSIZIONE_DEBITORIA NUMBER(9,0) NOT NULL, 
DATA_EVENTO DATE NOT NULL
);
 
ALTER TABLE PAY_STATO_PAGAMENTI ADD CONSTRAINT PAY_STATO_PAGAMENTI_PK PRIMARY KEY (IDCOMUNE, ID); 
ALTER TABLE PAY_STATO_PAGAMENTI ADD CONSTRAINT PAY_STAPAG_FK_POSDEB FOREIGN KEY (IDCOMUNE, FK_POSIZIONE_DEBITORIA) REFERENCES PAY_POSIZIONI_DEBITORIE (IDCOMUNE, ID) ON DELETE CASCADE;
	  
	  
COMMENT ON COLUMN PAY_STATO_PAGAMENTI.STATO IS 'STRINGA CHE CODIFICA LO STATO DEL PAGAMENTO';

COMMENT ON COLUMN PAY_STATO_PAGAMENTI.DESC_STATO IS 'TESTO LIBERO DESCRITTIVO DELLO STATO DEL PAGAMENTO';

COMMENT ON COLUMN PAY_STATO_PAGAMENTI.FK_POSIZIONE_DEBITORIA IS 'RIFERIMENTO ALLA POSIZIONE DEBITORIA A CUI FA RIFERIMENTO L''EVENTO';

COMMENT ON TABLE PAY_STATO_PAGAMENTI  IS 'TABELLA CHE STORICIZZA I PASSAGGI DI STATO DELLE SINGOLE POSIZIONI DEBITORIE';


ALTER TABLE MERCATIPRESENZE_D ADD FK_PAY_POS_DEB NUMBER(9,0);
alter table MERCATIPRESENZE_D ADD CONSTRAINT FK_PAYPOSDEB_SPUNT FOREIGN KEY(IDCOMUNE,FK_PAY_POS_DEB) REFERENCES PAY_POSIZIONI_DEBITORIE(IDCOMUNE,ID);


CREATE TABLE CONSENSI_INFORMATIVI(
IDCOMUNE VARCHAR2(6),
ID NUMBER(10,0),
CODICEOGGETTO NUMBER(10,0),
DESCRIZIONE VARCHAR2(100),
VERSIONE NUMBER(4),
CONTESTO VARCHAR2(50),
ORDINE NUMBER(4,0),
OBBLIGATORIO NUMBER(1,0),
DATA_INSERIMENTO DATE
);

ALTER TABLE CONSENSI_INFORMATIVI ADD CONSTRAINT PK_CONSENSIINFORMATIVI PRIMARY KEY(IDCOMUNE,ID);

ALTER TABLE CONSENSI_INFORMATIVI ADD CONSTRAINT FK_CONSINF_OGGETTI FOREIGN KEY(IDCOMUNE,CODICEOGGETTO) REFERENCES OGGETTI(IDCOMUNE, CODICEOGGETTO);


ALTER TABLE FO_CONSENSI_INFORMATIVI ADD FK_CONS_INFORM_ID NUMBER(10,0);

ALTER TABLE FO_CONSENSI_INFORMATIVI ADD CONSTRAINT FK_FOCONSINF_CONSINF FOREIGN KEY(IDCOMUNE,FK_CONS_INFORM_ID) REFERENCES CONSENSI_INFORMATIVI(IDCOMUNE, ID);


ALTER TABLE PAY_PROFILI_ENTI_CREDITORI  ADD ( CODICE_CONNETTORE VARCHAR2(20) NOT NULL );

COMMENT ON COLUMN PAY_PROFILI_ENTI_CREDITORI.CODICE_CONNETTORE IS 'FK ALLA CONFIGURAZIONE DEL CONNETTORE';

ALTER TABLE PAY_PROFILI_ENTI_CREDITORI ADD CONSTRAINT PAY_EC_FK_PAYCONN FOREIGN KEY (CODICE_CONNETTORE) REFERENCES PAY_CONNECTOR_CONFIG(  CODICE) ENABLE;

ALTER TABLE PAY_CONNECTOR_CONFIG MODIFY (DESCRIZIONE VARCHAR2(200 BYTE) );

ALTER TABLE PAY_SOGGETTI_DEBITORI MODIFY (NOME VARCHAR2(250 BYTE) );

ALTER TABLE PAY_SOGGETTI_DEBITORI MODIFY (COGNOME VARCHAR2(250 BYTE) );



ALTER TABLE PAY_PAGAMENTI MODIFY (IMPORTO_PAGATO NOT NULL);


ALTER TABLE AUTORIZZAZIONI_CSI ADD PROTOCOLLO VARCHAR2(10);
ALTER TABLE AUTORIZZAZIONI_CSI ADD DATA_PROTOCOLLO DATE; 


ALTER TABLE PAY_CONNECTOR_CONFIG ADD (WS_URL VARCHAR2(400) );

ALTER TABLE PAY_CONNECTOR_CONFIG ADD (WS_USR VARCHAR2(50) );

ALTER TABLE PAY_CONNECTOR_CONFIG ADD (WS_PWD VARCHAR2(50) );

ALTER TABLE PAY_CONNECTOR_CONFIG ADD (WS_TIMEOUT NUMBER(9, 0) );

COMMENT ON COLUMN PAY_CONNECTOR_CONFIG.WS_URL IS 'URL DELL''ENDPOINT DEL PSP INVOCATO DAL CONNETTORE';

COMMENT ON COLUMN PAY_CONNECTOR_CONFIG.WS_USR IS 'USERNAME PER WS CON AUTENTICAZIONE ';

COMMENT ON COLUMN PAY_CONNECTOR_CONFIG.WS_PWD IS 'PASSWORD PER WS CON AUTENTICAZIONE ';

COMMENT ON COLUMN PAY_CONNECTOR_CONFIG.WS_TIMEOUT IS 'TIMEOUT IMPOSTATO PER LE CHIAMATE AL WS';


ALTER TABLE PAY_REGISTRAZIONI_CAUSALI ADD (CODICE_VERSAMENTO VARCHAR2(20) );

COMMENT ON COLUMN PAY_REGISTRAZIONI_CAUSALI.CODICE_VERSAMENTO IS 'IDENTIFICATIVO DELLA CAUSALE DI VERSAMENTO DI DEFAULT DA INVIARE AL PSP';

ALTER TABLE PAY_PROFILI_ENTI_CREDITORI ADD (FK_CUSALE_REG_DEFAULT NUMBER(6,0) );


ALTER TABLE PAY_PROFILI_ENTI_CREDITORI ADD CONSTRAINT PAY_PROFILI_ENTI_CREDITOR_FK1 FOREIGN KEY( IDCOMUNE, FK_CUSALE_REG_DEFAULT) REFERENCES PAY_REGISTRAZIONI_CAUSALI (IDCOMUNE, ID) ENABLE;

COMMENT ON COLUMN PAY_PROFILI_ENTI_CREDITORI.FK_CUSALE_REG_DEFAULT IS 'CAUSALE DI REGISTRAZIONE DI DEFAULT PER IL PROFILO ENTE';



ALTER TABLE PAY_CONNECTOR_CONFIG ADD (URL_PORTALE_PAGAMENTI VARCHAR2(255));

COMMENT ON COLUMN PAY_CONNECTOR_CONFIG.URL_PORTALE_PAGAMENTI IS 'URL DELLA PAGINA DA INVOCARE PER ACCEDERE AL PAGAMENTO ONLINE';

ALTER TABLE PAY_CONNECTOR_CONFIG ADD (PWD_PORTALE_PAGAMENTI VARCHAR2(50) );

ALTER TABLE PAY_CONNECTOR_CONFIG ADD (ID_APP_PORTALE_PAGAMENTI VARCHAR2(50) );

COMMENT ON COLUMN PAY_CONNECTOR_CONFIG.PWD_PORTALE_PAGAMENTI IS 'PASSWORD DI SICUREZZA PER L''ACCESSO AL PORTALE DEI PAGAMENTI';

COMMENT ON COLUMN PAY_CONNECTOR_CONFIG.ID_APP_PORTALE_PAGAMENTI IS 'IDENTIFICATIVO DELL''APP DA CUI PARTE LA CHIAMATA AL PORTALE DEI PAGAMENTI';

ALTER TABLE PAY_SESSIONI_PAGAMENTO ADD (URL_REDIRECT_ESITO VARCHAR2(255) );

COMMENT ON COLUMN PAY_SESSIONI_PAGAMENTO.URL_REDIRECT_ESITO IS 'URL A CUI REINDIRIZZARE LA CHIAMATA DELL''ESITO DELL''AVVENUTO PAGAMENTO';

ALTER TABLE FO_DOMANDE ADD (CODICEINTERVENTO NUMBER(10) );

ALTER TABLE MERCATI ADD FLAG_ATTIVA_NODO_PAGAM NUMBER(1,0);
COMMENT ON COLUMN MERCATI.FLAG_ATTIVA_NODO_PAGAM IS 'Se attivato allora il mercato gestisce i pagamenti elettronici mediante il nodo pagamenti';
ALTER TABLE amministrazioni_anagrafe ADD INOLTRA_COMUNICAZIONE NUMERIC(1,0);



ALTER TABLE PAY_STATO_PAGAMENTI MODIFY (DESC_STATO VARCHAR2(500 BYTE) );

ALTER TABLE PAY_REGISTRAZIONI_CONTABILI DROP CONSTRAINT PAY_REGISTRAZIONI_CONTABI_FK1;

ALTER TABLE PAY_REGISTRAZIONI_CONTABILI DROP COLUMN FK_CONTO;


CREATE TABLE PAY_DETTAGLIO_IMPORTI 
(
  ID NUMBER(9) NOT NULL 
, IDCOMUNE VARCHAR2(6) NOT NULL 
, IMPORTO NUMBER(12, 2) NOT NULL 
, DESC_CAUSALE VARCHAR2(200) 
, FK_CONTO NUMBER(9, 0) 
, CONSTRAINT PAY_DETTAGLIO_IMPORTI_PK PRIMARY KEY 
  (
    ID 
  , IDCOMUNE 
  )
  ENABLE 
);

ALTER TABLE PAY_DETTAGLIO_IMPORTI ADD CONSTRAINT PAY_DETIMP_FK_CONTI FOREIGN KEY (  IDCOMUNE, FK_CONTO ) REFERENCES CONTI ( IDCOMUNE , ID) ENABLE;

COMMENT ON TABLE PAY_DETTAGLIO_IMPORTI IS 'TABELLA IN CUI VENGONO MEMORIZZATE LE RICHE DI DETTAGLIO CHE COMPONGONO L''IMPORTO DI UNA POSIZIONE DEBITORIA.';

COMMENT ON COLUMN PAY_DETTAGLIO_IMPORTI.FK_CONTO IS 'RIFERIMENTO AL CONTO A CUI FA RIFERIMENTO LA RIGA DI IMPORTO. LA FK PUNTA ALLA TABELLA CONTI CHE E'' GIA'' UTILIZZATA NEL BO PER IL CALCOLO E LA CONTABILIZZAIZONE DEGLI ONERI';

ALTER TABLE PAY_DETTAGLIO_IMPORTI ADD (FK_POSIZIONE_DEBITORIA NUMBER(9) NOT NULL);
ALTER TABLE PAY_DETTAGLIO_IMPORTI ADD CONSTRAINT PAY_DETIMP_FK_POSDEB FOREIGN KEY (IDCOMUNE,FK_POSIZIONE_DEBITORIA) REFERENCES PAY_POSIZIONI_DEBITORIE( IDCOMUNE, ID) ENABLE;

ALTER TABLE PAY_DETTAGLIO_IMPORTI ADD (DATI_RISCOSSIONE VARCHAR2(100) );

ALTER TABLE PAY_POSIZIONI_DEBITORIE MODIFY (IMPORTO NULL);

COMMENT ON COLUMN PAY_POSIZIONI_DEBITORIE.IMPORTO IS 'NON UTILIZZATO: L''IMPORTO E'' REGISTRATO NELLE RIGHE DI DETTAGLIO (PAY_DETTAGLIO_IMPORTI)';

ALTER TABLE PAY_POSIZIONI_DEBITORIE ADD ( QRCODE VARCHAR2(100) );

ALTER TABLE PAY_POSIZIONI_DEBITORIE ADD ( FK_PROFILO_ENTE NUMBER(10,0) );

ALTER TABLE PAY_POSIZIONI_DEBITORIE ADD CONSTRAINT PAY_POSDEB_FK_PROF FOREIGN KEY (  IDCOMUNE , FK_PROFILO_ENTE ) REFERENCES PAY_PROFILI_ENTI_CREDITORI (IDCOMUNE, ID ) ENABLE; 


ALTER TABLE PAY_PROFILI_ENTI_CREDITORI  ADD ( ID_APP_PSP VARCHAR2(50) );

COMMENT ON COLUMN PAY_PROFILI_ENTI_CREDITORI.ID_APP_PSP IS 'IDENTIFICATIVO DA INVIARE AL PSP PER IDENTIFICARE L''APPLICAZIONE CHE FRUISCE DEI SERVIZI DI PAGAMENTO';


ALTER TABLE PAY_PROFILI_ENTI_CREDITORI ADD (CF_CODICE_PROFILO_PSP VARCHAR2(20) );

COMMENT ON COLUMN PAY_PROFILI_ENTI_CREDITORI.CF_CODICE_PROFILO IS 'IL CODICE/CF E'' PASSATO AL NODO PAGAMENTI NELLE CHIAMATE AI SERVIZI E DA LI'' RECUPERA L''ID IDCOMUNE E IL SW DI RIFERIMENTO PER L''ESECUZIONE DEL SERVIZIO';

COMMENT ON COLUMN PAY_PROFILI_ENTI_CREDITORI.CF_CODICE_PROFILO_PSP IS 'CODICE/CF PASSATO ALLE CHIAMATE DEI SERVIZI DEL PSP DAI CONNETTORI DI PAGAMENTO';


ALTER TABLE PAY_CONNECTOR_CONFIG DROP COLUMN ID_APP_PORTALE_PAGAMENTI;

ALTER TABLE PAY_POSIZIONI_DEBITORIE DROP COLUMN IMPORTO;

ALTER TABLE PAY_PROFILI_ENTI_CREDITORI ADD (URL_ESITO_PAGAMENTO VARCHAR2(256) ); 
COMMENT ON COLUMN PAY_PROFILI_ENTI_CREDITORI.URL_ESITO_PAGAMENTO IS 'URL ASSOLUTO CHE GESTISCE L''ESITO DELLA SESSIONE DI PAGAMENTO QUANDO L''UTENTE TORNA ALLA APP DOPO AVER EFFETTUATO IL PAGAMENTO ONLINE';


ALTER TABLE PAY_CONNECTOR_CONFIG ADD (IN_WS_USR VARCHAR2(50) );

ALTER TABLE PAY_CONNECTOR_CONFIG ADD (IN_WS_PWD VARCHAR2(50) );

ALTER TABLE PAY_CONNECTOR_CONFIG ADD (IN_WS_TIMEOUT VARCHAR2(20) );

ALTER TABLE PAY_POSIZIONI_DEBITORIE MODIFY (DATA_SCADENZA NULL);

CREATE UNIQUE INDEX PAY_POSDEB_IDPSP_UIDX ON PAY_POSIZIONI_DEBITORIE (ID_POSIZIONE_PSP ASC);

CREATE OR REPLACE VIEW VW_PAY_POSIZIONIDEBITORIE AS SELECT
    PPD.ID,
    PSP.STATO,
    PSP.DESC_STATO,
    PPD.IUV,
    SUM(PIMP.IMPORTO) AS IMPORTO,
    PPD.ID_POSIZIONE_PSP,
    PPD.DESCRIZIONE_CAUSALE,
    PPD.CODICE_AVVISO,
    PPD.QRCODE,
    PSP.DATA_EVENTO,
    PPEC.CODICE_CONNETTORE,
    PPEC.CBILL,
    PPEC.CF_CODICE_PROFILO,
    PPEC.CF_CODICE_PROFILO_PSP,
    PPEC.ID_APP_PSP
FROM
    PAY_POSIZIONI_DEBITORIE PPD
    LEFT JOIN PAY_STATO_PAGAMENTI PSP ON PSP.IDCOMUNE = PPD.IDCOMUNE
                                         AND PSP.FK_POSIZIONE_DEBITORIA = PPD.ID
    LEFT JOIN PAY_PROFILI_ENTI_CREDITORI PPEC ON PPEC.IDCOMUNE = PPD.IDCOMUNE
                                                 AND PPEC.ID = PPD.FK_PROFILO_ENTE
    INNER JOIN PAY_DETTAGLIO_IMPORTI PIMP ON PPD.IDCOMUNE = PIMP.IDCOMUNE
                                             AND PPD.ID = PIMP.FK_POSIZIONE_DEBITORIA

GROUP BY
    PPD.ID,
    PPD.DESCRIZIONE_CAUSALE,
    PPD.IUV,
    PPD.CODICE_AVVISO,
    PPD.ID_POSIZIONE_PSP,
    PPD.QRCODE,
    PSP.STATO,
    PSP.DESC_STATO,
    PSP.DATA_EVENTO,
    PPEC.CODICE_CONNETTORE,
    PPEC.CBILL,
    PPEC.CF_CODICE_PROFILO,
    PPEC.CF_CODICE_PROFILO_PSP,
    PPEC.ID_APP_PSP;
    
ALTER TABLE PAY_PROFILI_ENTI_CREDITORI ADD (URL_ANNULLAMENTO_PAGAMENTO VARCHAR2(256) );

COMMENT ON COLUMN PAY_PROFILI_ENTI_CREDITORI.URL_ANNULLAMENTO_PAGAMENTO IS 'URL ASSOLUTO CHE GESTISCE IL RITORNO ALL''APP CHIAMANTE DOPO L''ANNULLAMENTO DEL PAGAMENTO ONLINE';


CREATE TABLE MERCATI_CFG_CONTI(
IDCOMUNE VARCHAR2(6),
ID NUMBER(4,0),
FK_CONTO NUMBER(6,0),
FK_CODICEISTAT VARCHAR2(15),
FK_CODICE_CONC_USO NUMBER(2,0),
DATAINZIOVAL DATE,
DATAFINEVAL DATE,
FLAG_MOLTIPLICA_MQ NUMBER(1,0),
IMPORTO NUMBER(8,5)
)
;

ALTER TABLE MERCATI_CFG_CONTI ADD CONSTRAINT PK_MERCATI_CFG_CONTI PRIMARY KEY (IDCOMUNE,ID);
ALTER TABLE MERCATI_CFG_CONTI ADD CONSTRAINT FK_MERCFGCONTI_CONTI FOREIGN KEY (IDCOMUNE,FK_CONTO) REFERENCES CONTI (IDCOMUNE,ID);
ALTER TABLE MERCATI_CFG_CONTI ADD CONSTRAINT FK_MERCFGCONTI_ATTIVITA FOREIGN KEY (IDCOMUNE,FK_CODICEISTAT) REFERENCES ATTIVITA (IDCOMUNE,CODICEISTAT);
ALTER TABLE MERCATI_CFG_CONTI ADD CONSTRAINT FK_MERCFGCONTI_CONCUSO FOREIGN KEY (IDCOMUNE,FK_CODICE_CONC_USO) REFERENCES CONCESSIONIUSO (IDCOMUNE,CODICE);


ALTER TABLE MERCATIPRESENZE_T ADD FK_CODICE_CONC_USO NUMBER(2,0);
ALTER TABLE MERCATIPRESENZE_T ADD CONSTRAINT FK_MERCPREST_CONCUSO FOREIGN KEY (IDCOMUNE,FK_CODICE_CONC_USO) REFERENCES CONCESSIONIUSO (IDCOMUNE,CODICE);



ALTER TABLE TEMP_LINKALLEGATI ADD DESCRIZIONE_DOCUMENTO VARCHAR2(4000) ;

alter table MERCATI_CFG_CONTI add SOFTWARE varchar2(2);

ALTER TABLE MERCATI_CFG_CONTI ADD CONSTRAINT FK_MERCFGCONTI_SOFTWARE FOREIGN KEY (SOFTWARE) REFERENCES SOFTWARE(CODICE);



alter table conti add anno_accertamento number(4,0);
alter table conti add numero_accertamento varchar2(35);

ALTER TABLE PAY_DETTAGLIO_IMPORTI ADD ANNO_ACCERTAMENTO number(4,0);
ALTER TABLE PAY_DETTAGLIO_IMPORTI ADD NUMERO_ACCERTAMENTO VARCHAR2(35);