CREATE OR REPLACE VIEW ldp_pratiche_indirizzi AS
    SELECT
        istanze.idcomune AS installazione,
        istanze.software AS modulo,
        istanze.codiceistanza AS idpratica,
        istanzestradario.id AS idindirizzo,
        stradario.codicestradario AS codicestradario,
        stradario.codviario AS codviario,
        stradario.prefisso AS toponimo,
        stradario.descrizione AS descvia,
        istanzestradario.codicecivico AS codicecivico,
        istanzestradario.civico AS civico,
        istanzestradario.colore AS colore,
        istanzestradario.frazione AS frazione,
        istanzestradario.circoscrizione AS circoscrizione,
        istanzestradario.cap AS cap,
        istanzestradario.km AS km,
        istanzestradario.esponente AS esponente,
        istanzestradario.scala AS scala,
        istanzestradario.interno AS interno,
        istanzestradario.esponenteinterno AS esponenteinterno,
        istanzestradario.fabbricato AS fabbricato,
        istanzestradario.piano AS piano,
        istanzestradario.quartiere AS quartiere,
        istanzestradario.id_punto_sit AS id_punto_sit,
        istanzestradario.uuid AS uuid,
        istanzestradario.latitudine AS latitudine,
        istanzestradario.longitudine AS longitudine,
                    istanzestradario.note AS note,
        istanzestradario.accesso_tipo AS accesso_tipo,
        istanzestradario.accesso_numero AS accesso_numero,
        istanzestradario.accesso_descrizione AS accesso_descrizione
    FROM
        istanze
        JOIN istanzestradario ON istanzestradario.idcomune = istanze.idcomune
                                 AND istanzestradario.codiceistanza = istanze.codiceistanza
        INNER JOIN stradario ON stradario.idcomune = istanzestradario.idcomune
                                AND stradario.codicestradario = istanzestradario.codicestradario;

ALTER TABLE ALBEROPROC ADD FLAG_ESCLUDI_RISULTATI_RICERCA NUMBER(1,0) default 0;
ALTER TABLE ISTANZEALLEGATI ADD (DATA DATE);
ALTER TABLE ISTANZEPROCURE ADD (DATA DATE);

CREATE TABLE MERCATI_CATEGORIE(
IDCOMUNE VARCHAR2(6) NOT NULL,
ID number(4,0) NOT NULL,
DESCRIZIONE VARCHAR2(100),
SOFTWARE VARCHAR2(2)
);
ALTER TABLE MERCATI_CATEGORIE ADD CONSTRAINT MERCATICATEGORIE_PK PRIMARY KEY(IDCOMUNE,ID); 
ALTER TABLE MERCATI_CATEGORIE ADD CONSTRAINT FK_MERCATICAT_SOFTWARE FOREIGN KEY (SOFTWARE) REFERENCES SOFTWARE(CODICE);

ALTER TABLE MERCATI ADD FK_CATEGORIA_MERCATO NUMBER(4,0); 
ALTER TABLE MERCATI ADD CONSTRAINT FK_MERCATI_CATEGORMER FOREIGN KEY(IDCOMUNE,FK_CATEGORIA_MERCATO) REFERENCES MERCATI_CATEGORIE(IDCOMUNE,ID); 
CREATE INDEX IDX_FK_MERCATI_CATEGORMER ON MERCATI(IDCOMUNE,FK_CATEGORIA_MERCATO);

ALTER TABLE MERCATI_CFG_CONTI ADD  FK_CATEGORIA_MERCATO NUMBER(4,0); 
ALTER TABLE MERCATI_CFG_CONTI ADD CONSTRAINT FK_MERCCFGCONTI_CATEGORMER FOREIGN KEY(IDCOMUNE,FK_CATEGORIA_MERCATO) REFERENCES MERCATI_CATEGORIE(IDCOMUNE,ID); 
CREATE INDEX IDX_FK_MERCFGCON_CATEGORMER ON MERCATI_CFG_CONTI(IDCOMUNE,FK_CATEGORIA_MERCATO);

ALTER TABLE MERCATI_CFG_CONTI ADD FK_POSTEGGISETTORI_ID  NUMBER(4,0) ; 
ALTER TABLE MERCATI_CFG_CONTI ADD CONSTRAINT FK_MERCCFGCONTI_POSTSETT FOREIGN KEY(IDCOMUNE,FK_POSTEGGISETTORI_ID) REFERENCES POSTEGGI_SETTORI(IDCOMUNE,ID); 
CREATE INDEX IDX_FK_MERCFGCON_POSTSETT ON MERCATI_CFG_CONTI(IDCOMUNE,FK_POSTEGGISETTORI_ID);

UPDATE (SELECT IP.DATA AS DATAPROCURA, 
               I.DATA AS DATAISTANZA
          FROM ISTANZEPROCURE IP,
               ISTANZE I 
         WHERE 
         IP.IDCOMUNE=I.IDCOMUNE AND IP.CODICEISTANZA=I.CODICEISTANZA AND
         IP.DATA  IS NULL)
   SET DATAPROCURA = DATAISTANZA;
   
   
UPDATE ( SELECT IA.DATA AS DATA_ALLEGATO,
               I.DATA AS DATA_ISTANZA
        FROM ISTANZEALLEGATI IA, 
             ISTANZE I
           
        WHERE 
             IA.IDCOMUNE=I.IDCOMUNE AND IA.CODICEISTANZA=I.CODICEISTANZA 
           
             AND IA.DATA IS  NULL  
 )
SET DATA_ALLEGATO = DATA_ISTANZA;

CREATE TABLE MOVIMENTI_ZIP_LOGICO (
    ID                    NUMBER(8,0) NOT NULL,
    IDCOMUNE              VARCHAR2(6) NOT NULL,
    CODICEMOVIMENTO       NUMBER(8,0),
    CODICEOGGETTO         NUMBER(10,0),
    FK_IDMOVIMENTIALLEGATI    NUMBER(8,0),
    FK_IDDOCUMENTIISTANZA     NUMBER(8,0),
    FK_IDISTANZEALLEGATI      NUMBER(8,0),
    FK_IDANAGRAFEDOCUMENTI    NUMBER(10,0),
    FK_IDISTANZEPROCURE       NUMBER(10,0),
    FK_IDCDSATTI 			  NUMBER(8,0)
);

ALTER TABLE MOVIMENTI_ZIP_LOGICO ADD (CONSTRAINT PK_MOVIMENTI_ZIP_LOGICO PRIMARY KEY (IDCOMUNE,ID));

ALTER TABLE MOVIMENTI_ZIP_LOGICO ADD (CONSTRAINT FK_MOVZIPLOGMOV_MOVIMENTO FOREIGN KEY (IDCOMUNE,CODICEMOVIMENTO) REFERENCES MOVIMENTI(IDCOMUNE,CODICEMOVIMENTO));
ALTER TABLE MOVIMENTI_ZIP_LOGICO ADD (CONSTRAINT FK_MOVZIPLOGMOV_OGGETTI FOREIGN KEY (IDCOMUNE,CODICEOGGETTO) REFERENCES OGGETTI(IDCOMUNE,CODICEOGGETTO));
ALTER TABLE MOVIMENTI_ZIP_LOGICO ADD (CONSTRAINT FK_MOVZIPLOGMOV_MOVALLEGATI FOREIGN KEY (IDCOMUNE,FK_IDMOVIMENTIALLEGATI) REFERENCES MOVIMENTIALLEGATI(IDCOMUNE,ID));
ALTER TABLE MOVIMENTI_ZIP_LOGICO ADD (CONSTRAINT FK_MOVZIPLOGMOV_DOCISTANZA FOREIGN KEY (IDCOMUNE,FK_IDDOCUMENTIISTANZA) REFERENCES DOCUMENTIISTANZA(IDCOMUNE,ID));
ALTER TABLE MOVIMENTI_ZIP_LOGICO ADD (CONSTRAINT FK_MOVZIPLOGMOV_ISTALLEGATI FOREIGN KEY (IDCOMUNE,FK_IDISTANZEALLEGATI) REFERENCES ISTANZEALLEGATI(IDCOMUNE,ID));
ALTER TABLE MOVIMENTI_ZIP_LOGICO ADD (CONSTRAINT FK_MOVZIPLOGMOV_ANAGRAFEDOC FOREIGN KEY (IDCOMUNE,FK_IDANAGRAFEDOCUMENTI) REFERENCES ANAGRAFEDOCUMENTI(IDCOMUNE,ID));
ALTER TABLE MOVIMENTI_ZIP_LOGICO ADD (CONSTRAINT FK_MOVZIPLOGMOV_ISTPROCURE FOREIGN KEY (IDCOMUNE,FK_IDISTANZEPROCURE) REFERENCES ISTANZEPROCURE(IDCOMUNE,ID));



ALTER TABLE MOVIMENTI_ZIP_LOGICO ADD CONSTRAINT FK_MOVZIPLOGMOV_CDSATTI FOREIGN KEY (IDCOMUNE,FK_IDCDSATTI) REFERENCES CDSATTI(IDCOMUNE,ID);

ALTER TABLE TIPIMOV_STC_MAPPING ADD FLAG_NOTIFICA_SUB_ENDO NUMBER(1,0);

ALTER TABLE AMMINISTRAZIONI ADD CODICECOMUNE VARCHAR2(5);

ALTER TABLE AMMINISTRAZIONI ADD CONSTRAINT FK_AMMINISTRAZIONI_COMUNI FOREIGN KEY(CODICECOMUNE) REFERENCES COMUNI(CODICECOMUNE);

ALTER TABLE ISTANZE ADD NATURA_ENDO_PRINCIPALE VARCHAR2(20);
