//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.10 at 02:03:29 PM CEST 
//


package it.gruppoinit.pal.gp.core.domain.autocompiler;

import it.gruppoinit.pal.gp.core.domain.autocompiler.AutocompilerApplication;

import it.gruppoinit.pal.gp.core.domain.autocompiler.AutocompilerApplication;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AutocompilerApplicationConfig complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AutocompilerApplicationConfig">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element name="autocompiler-application" type="{http://gruppoinit.it/sigepro/schemas/autocompiler}AutocompilerApplication"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AutocompilerApplicationConfig", propOrder = {
    "autocompilerApplications"
})
public class AutocompilerApplicationConfig {

    @XmlElement(name = "autocompiler-application", required = true)
    protected List<AutocompilerApplication> autocompilerApplications;

    /**
     * Gets the value of the autocompilerApplications property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the autocompilerApplications property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAutocompilerApplications().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AutocompilerApplication }
     * 
     * 
     */
    public List<AutocompilerApplication> getAutocompilerApplications() {
        if (autocompilerApplications == null) {
            autocompilerApplications = new ArrayList<AutocompilerApplication>();
        }
        return this.autocompilerApplications;
    }

}
