//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.10 at 02:03:29 PM CEST 
//


package it.gruppoinit.pal.gp.core.domain.autocompiler;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SearchResultAttributeMapping complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SearchResultAttributeMapping">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="result-attribute-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="destination-field-id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SearchResultAttributeMapping", propOrder = {

})
public class SearchResultAttributeMapping {

    @XmlElement(name = "result-attribute-name", required = true)
    protected String resultAttributeName;
    @XmlElement(name = "destination-field-id", required = true)
    protected String destinationFieldId;

    /**
     * Gets the value of the resultAttributeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultAttributeName() {
        return resultAttributeName;
    }

    /**
     * Sets the value of the resultAttributeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultAttributeName(String value) {
        this.resultAttributeName = value;
    }

    /**
     * Gets the value of the destinationFieldId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestinationFieldId() {
        return destinationFieldId;
    }

    /**
     * Sets the value of the destinationFieldId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestinationFieldId(String value) {
        this.destinationFieldId = value;
    }

}
