alter table LEGGI ADD CONSTRAINT FK_LEGGILEGGITIPI FOREIGN KEY(IDCOMUNE,LE_FKLTID) REFERENCES LEGGITIPI(IDCOMUNE,LT_ID);

 

alter table LEGGI modify LE_ID number(10,0);

alter table LEGGITIPI modify LT_ID number(10,0);

alter table DYN2_CAMPI modify ID number(10,0);

alter table DYN2_CAMPIPROPRIETA modify FK_D2C_ID number(10,0);

alter table DYN2_MODELLID modify ID number(10,0);

alter table DYN2_MODELLIDTESTI modify ID number(10,0);

alter table DYN2_MODELLIT modify ID number(10,0);

alter table INVENTARIOPROCDYN2MODELLIT modify CODICEINVENTARIO number(10,0);

alter table INVENTARIOPROCDYN2MODELLIT modify FK_D2MT_ID number(10,0);

alter table INVENTARIOPROCEDIMENTI modify CODICEINVENTARIO number(10,0);

alter table INVENTARIOPROCEDIMENTIINCOMP modify ID number(10,0);

alter table INVENTARIOPROCEDIMENTIONERI modify ID number(10,0);

alter table ALBEROPROC_ATECO modify FK_SCID number(10,0);

alter table ALBEROPROC_ATECO modify FK_IDATECO number(10,0);

alter table TEMPIFICAZIONI modify CODICETEMPIFICAZIONE number(10,0);

alter table TIPIENDO modify CODICE number(10,0);

alter table TIPIFAMIGLIEENDO modify CODICE number(10,0);

alter table TIPIPROCEDURE modify CODICEPROCEDURA number(10,0);

alter table ALBEROPROC modify SC_ID number(10,0);

alter table ALBEROPROC_ENDO modify FKSCID number(10,0);

alter table ALBEROPROC_ENDO modify CODICEINVENTARIO number(10,0);

alter table ALLEGATI modify ID number(10,0);

alter table AMMINISTRAZIONI modify CODICEAMMINISTRAZIONE number(10,0);

alter table AMMINISTRAZIONIREFERENTI modify ID number(10,0);

alter table NATURAENDO modify CODICENATURA number(10,0);

alter table NORMATIVE modify CODICENORMATIVA number(10,0);

alter table OGGETTI modify CODICEOGGETTO number(10,0);

alter table INVENTARIOPROC_LEGGI modify ID number(10,0);

 

 

ALTER TABLE ALBEROPROCPEOPLEOPER modify FKSC_ID number(10,0);

ALTER TABLE ALBEROPROCPEOPLEHREF modify FKSC_ID number(10,0);

ALTER TABLE ALBEROPROC_RUOLI modify FK_SC_ID number(10,0);

ALTER TABLE ALBERO_CAUSALI modify FK_SCID number(10,0);

ALTER TABLE STP_ENDO_TIPO2 modify FK_SC_ID number(10,0);

ALTER TABLE ALBEROPROC_ENDO modify FKSCID number(10,0);

ALTER TABLE ALBEROPROC_DOCUMENTI modify SM_FKSCID number(10,0);

ALTER TABLE ALBEROPROC_ONERI modify AO_FK_SCID number(10,0);

ALTER TABLE ALBEROPROC_LIMITI modify FKIDALBERO number(10,0);

ALTER TABLE ALBEROPROC_LEGGI modify SL_FKSCID number(10,0);

ALTER TABLE ALBEROPROC_DYN2MODELLIT modify FK_SC_ID number(10,0);

ALTER TABLE ISTANZE modify CODICEINTERVENTOPROC number(10,0);

ALTER TABLE ISTANZEALLEGATI modify FK_IDALLEGATO number(10,0);

ALTER TABLE COMMEDILIZIE_APPELLO modify CODICEAMMINISTRAZIONE number(10,0);

ALTER TABLE AMMINISTRAZIONIRUOLI modify CODICEAMMINISTRAZIONE number(10,0);

ALTER TABLE COMMEDILIZIE_TIPOLOGIE modify CODICEAMMINISTRAZIONE number(10,0);

ALTER TABLE PROTOCOLLO_REGISTRI modify IDMITTENTE number(10,0);

ALTER TABLE PROTOCOLLO_REGISTRI modify IDDESTINATARIO number(10,0);

ALTER TABLE TIPIMOV_STC_ALTRIDATI modify CODICEAMMINISTRAZIONE number(10,0);

ALTER TABLE TIPIMOV_STC_MAPPING modify CODICEAMMINISTRAZIONE number(10,0);

ALTER TABLE ALBO_PUBBLICAZIONI modify CODICEAMMINISTRAZIONE number(10,0);

ALTER TABLE TIPIMOV_STC_MODELLI modify CODICEAMMINISTRAZIONE number(10,0);

ALTER TABLE TIPIMOV_STC_ALBEROPROC modify CODICEAMMINISTRAZIONE number(10,0);

ALTER TABLE DOCUMENTI modify AMMINISTRAZIONE number(10,0);

ALTER TABLE CDSINVITATI modify CODICEAMMINISTRAZIONE number(10,0);

ALTER TABLE TEMPIRISPOSTA modify CODICEAMMINISTRAZIONE number(10,0);

ALTER TABLE BATCH_SCADENZARIO modify CODICEAMMINISTRAZIONE number(10,0);

ALTER TABLE TIPICONTROMOVIMENTO modify AMMRITSU number(10,0);

ALTER TABLE TIPICONTROMOVIMENTO modify AMMMOV number(10,0);

ALTER TABLE EMAIL modify CODICEAMMINISTRAZIONE number(10,0);

ALTER TABLE MOVIMENTI modify CODICEAMMINISTRAZIONE number(10,0);

ALTER TABLE AMMINISTRAZIONIRESPONSABILI modify CODICEAMMINISTRAZIONE number(10,0);

ALTER TABLE AMMINISTRAZIONIREFERENTI modify CODICEAMMINISTRAZIONE number(10,0);

ALTER TABLE ALLEGATI modify AMMINISTRAZIONE number(10,0);

ALTER TABLE ISTANZEONERI modify CODICEAMMINISTRAZIONE number(10,0);

ALTER TABLE INVENTARIOPROCEDIMENTI modify AMMINISTRAZIONE number(10,0);

ALTER TABLE ALBO_PUBBLICAZIONI modify CODICEUFFICIO number(10,0);

ALTER TABLE EMAIL modify CODICEUFFICIO number(10,0);

ALTER TABLE MOVIMENTI modify CODICEUFFICIO number(10,0);

ALTER TABLE INVENTARIOPROCEDIMENTI modify CODICEUFFICIO number(10,0);

ALTER TABLE MERCATI_CONFIGURAZIONE modify FK_D2CID_CAT_MERC number(10,0);

ALTER TABLE MERCATI_CONFIGURAZIONE modify FK_D2CID_COMUNE_AUT number(10,0);

ALTER TABLE MERCATI_CONFIGURAZIONE modify FK_D2CID_DATA_AUT number(10,0);

ALTER TABLE MERCATI_CONFIGURAZIONE modify FK_D2CID_NUM_AUT number(10,0);

ALTER TABLE CAMPIGRADUATORIA modify FK_D2C_ID number(10,0);

ALTER TABLE TIPIBANDOCAMPIGRADUAT modify FK_D2C_ID number(10,0);

ALTER TABLE TIPIBANDOOUTPUT modify FK_D2C_ID_RIF number(10,0);

ALTER TABLE TIPIBANDOOUTPUT modify FK_D2C_ID_OUT number(10,0);

ALTER TABLE TIPIGRADUATORIED modify FK_D2C_ID number(10,0);

ALTER TABLE DYN2_MODELLID modify FK_D2C_ID number(10,0);

ALTER TABLE I_ATTIVITADYN2DATI_STORICO modify FK_D2C_ID number(10,0);

ALTER TABLE I_ATTIVITADYN2DATI modify FK_D2C_ID number(10,0);

ALTER TABLE MERCATI_CONFIGURAZIONE modify FK_D2CID_COD_REG_AUT number(10,0);

ALTER TABLE ISTANZEDYN2DATI_STORICO modify FK_D2C_ID number(10,0);

ALTER TABLE ISTANZEDYN2DATI modify FK_D2C_ID number(10,0);

ALTER TABLE ANAGRAFEDYN2DATI_STORICO modify FK_D2C_ID number(10,0);

ALTER TABLE ANAGRAFEDYN2DATI modify FK_D2C_ID number(10,0);

ALTER TABLE MAPPATURE modify FKIDCAMPO number(10,0);

ALTER TABLE DYN2_MODELLID modify FK_D2MDT_ID number(10,0);

ALTER TABLE TIPIBANDO modify FK_D2MT_ID number(10,0);

ALTER TABLE TIPIMOV_STC_MODELLI modify FK_DYN2_MODELLIT_ID number(10,0);

ALTER TABLE DYN2_MODELLID modify FK_D2MT_ID number(10,0);

ALTER TABLE I_ATTIVITADYN2MODELLIT_STORICO modify FK_D2MT_ID number(10,0);

ALTER TABLE I_ATTIVITADYN2MODELLIT modify FK_D2MT_ID number(10,0);

ALTER TABLE I_ATTIVITADYN2DATI_STORICO modify FK_D2MT_ID number(10,0);

ALTER TABLE TIPIMOVIMENTIDYN2MODELLIT modify FK_D2MT_ID number(10,0);

ALTER TABLE MOVIMENTIDYN2MODELLIT modify FK_D2MT_ID number(10,0);

ALTER TABLE ISTANZEDYN2MODELLIT_STORICO modify FK_D2MT_ID number(10,0);

ALTER TABLE ISTANZEDYN2MODELLIT modify FK_D2MT_ID number(10,0);

ALTER TABLE ISTANZEDYN2DATI_STORICO modify FK_D2MT_ID number(10,0);

ALTER TABLE ANAGRAFEDYN2MODELLIT_STORICO modify FK_D2MT_ID number(10,0);

ALTER TABLE ANAGRAFEDYN2MODELLIT modify FK_D2MT_ID number(10,0);

ALTER TABLE ANAGRAFEDYN2DATI_STORICO modify FK_D2MT_ID number(10,0);

ALTER TABLE ALBEROPROC_DYN2MODELLIT modify FK_D2MT_ID number(10,0);

ALTER TABLE MAPPATURE modify FKIDSCHEDA number(10,0);

ALTER TABLE ENDO_CAUSALI modify FK_CODICEINVENTARIO number(10,0);

ALTER TABLE REGISTRAZIONI modify FK_CODICEINVENTARIO number(10,0);

ALTER TABLE STP_ENDO_TIPO1 modify CODICEINVENTARIO number(10,0);

ALTER TABLE BATCH_SCADENZARIO modify CODICEINVENTARIO number(10,0);

ALTER TABLE INVENTARIOPROC_LEGGI modify CODICEINVENTARIO number(10,0);

ALTER TABLE MOVIMENTI modify CODICEINVENTARIO number(10,0);

ALTER TABLE INVENTARIOPROCEDIMENTIINCOMP modify CODICEINVENTARIO number(10,0);

ALTER TABLE INVENTARIOPROCEDIMENTIINCOMP modify CODICEINCOMPATIBILE number(10,0);

ALTER TABLE INVENTARIOPROCEDIMENTIPEOPLE modify CODICEINVENTARIO number(10,0);

ALTER TABLE TMP_ISTANZEPROCEDIMENTICOLL modify CODICEINVENTARIO number(10,0);

ALTER TABLE TIPIMOVIMENTO_DIS modify CODICEINVENTARIO number(10,0);

ALTER TABLE STP_ENDO_TIPO2 modify CODICEINVENTARIO number(10,0);

ALTER TABLE ISTANZEONERI_DETTAGLIO modify CODICEINVENTARIO number(10,0);

ALTER TABLE ISTANZEONERI modify CODICEINVENTARIO number(10,0);

ALTER TABLE ISTANZEALLEGATI modify CODICEINVENTARIO number(10,0);

ALTER TABLE INVENTARIOPROCDYN2MODELLIT modify CODICEINVENTARIO number(10,0);

ALTER TABLE DOMANDEFRONT_ENDO modify CODICEINVENTARIO number(10,0);

ALTER TABLE CONTROLLOVERIFICHE modify CODICEINVENTARIO number(10,0);

ALTER TABLE ALBEROPROC_ENDO modify CODICEINVENTARIO number(10,0);

ALTER TABLE ISTANZEPROCEDIMENTI modify CODICEINVENTARIO number(10,0);

ALTER TABLE INVENTARIOPROCEDIMENTISOFTWARE modify CODICEINVENTARIO number(10,0);

ALTER TABLE INVENTARIOPROCEDIMENTIONERI modify CODICEINVENTARIO number(10,0);

ALTER TABLE DOCUMENTI modify CODICEINVENTARIO number(10,0);

ALTER TABLE TESTIESTESI modify CODICEINVENTARIO number(10,0);

ALTER TABLE ALLEGATI modify CODICEINVENTARIO number(10,0);

ALTER TABLE ALBEROPROC_LEGGI modify SL_FKLEID number(10,0);

ALTER TABLE INVENTARIOPROC_LEGGI modify FKLEID number(10,0);

ALTER TABLE TIPIPROCEDURE modify CODICENATURA number(10,0);

ALTER TABLE INVENTARIOPROCEDIMENTI modify CODICENATURA number(10,0);

ALTER TABLE LEGGI modify FK_NORMATIVE number(10,0);

ALTER TABLE TESTIESTESI modify TIPONORMA number(10,0);

ALTER TABLE BANDI_ALLEGATI modify CODICEOGGETTO number(10,0);

ALTER TABLE CE_ONERI modify CODICEOGGETTO number(10,0);

ALTER TABLE DOM_ALLEGATI modify CODICEOGGETTO number(10,0);

ALTER TABLE FO_ARCONFIGURAZIONE modify CODICEOGGETTO_FIRMA number(10,0);

ALTER TABLE FO_ARCONFIGURAZIONE modify CODICEOGGETTO_SOTTOSCRIZ number(10,0);

ALTER TABLE FO_DOMANDE modify CODICEOGGETTO number(10,0);

ALTER TABLE FO_DOMANDE_OGGETTI modify CODICEOGGETTO number(10,0);

ALTER TABLE FO_RICHIESTE modify CODICEOGGETTO number(10,0);

ALTER TABLE LETTERETIPO modify CODICEOGGETTO number(10,0);

ALTER TABLE MENU modify CODICEOGGETTO number(10,0);

ALTER TABLE MENU modify CODICEOGGETTO2 number(10,0);

ALTER TABLE MENUINFO modify CODICEOGGETTO1 number(10,0);

ALTER TABLE MENUINFO modify CODICEOGGETTO2 number(10,0);

ALTER TABLE MOVIMENTI modify CODICEOGGETTO number(10,0);

ALTER TABLE MULTIDOCUMENTIRIGHE modify CODICEOGGETTO number(10,0);

ALTER TABLE OGGETTIMULTIFORMATO modify CODICEOGGETTO number(10,0);

ALTER TABLE OGGETTIMULTIFORMATO modify CODICEOGGETTOCOLLEGATO number(10,0);

ALTER TABLE PERMCDSATTI modify CODICEOGGETTO number(10,0);

ALTER TABLE SORTEGGITESTATA modify CODICEOGGETTO number(10,0);

ALTER TABLE STILIFRONTOFFICE modify BUT_ALLEGATI number(10,0);

ALTER TABLE STILIFRONTOFFICE modify BUT_CALCOLA number(10,0);

ALTER TABLE STILIFRONTOFFICE modify BUT_CHIUDI number(10,0);

ALTER TABLE STILIFRONTOFFICE modify BUT_DATIANAGRAFICI number(10,0);

ALTER TABLE STILIFRONTOFFICE modify BUT_ENDOPROCEDIMENTI number(10,0);

ALTER TABLE STILIFRONTOFFICE modify BUT_ESCI number(10,0);

ALTER TABLE STILIFRONTOFFICE modify BUT_FRECCIA number(10,0);

ALTER TABLE STILIFRONTOFFICE modify BUT_HOME number(10,0);

ALTER TABLE STILIFRONTOFFICE modify BUT_INDIETRO number(10,0);

ALTER TABLE STILIFRONTOFFICE modify BUT_NUOVA number(10,0);

ALTER TABLE STILIFRONTOFFICE modify BUT_NUOVAISTANZA number(10,0);

ALTER TABLE STILIFRONTOFFICE modify BUT_PRECEDENTE number(10,0);

ALTER TABLE STILIFRONTOFFICE modify BUT_PROCEDI number(10,0);

ALTER TABLE STILIFRONTOFFICE modify BUT_REGISTRATI number(10,0);

ALTER TABLE STILIFRONTOFFICE modify BUT_STAMPA number(10,0);

ALTER TABLE STILIFRONTOFFICE modify BUT_SUCCESSIVA number(10,0);

ALTER TABLE STILIFRONTOFFICE modify DOT number(10,0);

ALTER TABLE STILIFRONTOFFICE modify ELEMENT_DOT number(10,0);

ALTER TABLE STILIFRONTOFFICE modify ELEMENT_DOTPRINCIPALI number(10,0);

ALTER TABLE STILIFRONTOFFICE modify ELEMENT_MENU number(10,0);

ALTER TABLE STILIFRONTOFFICE modify ICO_ANTEPRIMA number(10,0);

ALTER TABLE STILIFRONTOFFICE modify ICO_BINOCOLO number(10,0);

ALTER TABLE STILIFRONTOFFICE modify ICO_COLLEGAMENTO number(10,0);

ALTER TABLE STILIFRONTOFFICE modify ICO_MODELLO number(10,0);

ALTER TABLE STILIFRONTOFFICE modify ICO_TXT number(10,0);

ALTER TABLE STILIFRONTOFFICE modify ICO_UPLOAD number(10,0);

ALTER TABLE STILIFRONTOFFICE modify ICO_WORD number(10,0);

ALTER TABLE STILIFRONTOFFICE modify LABEL_INFO_INTERVENTO number(10,0);

ALTER TABLE STILIFRONTOFFICE modify LABEL_INFO_INTERVENTOON number(10,0);

ALTER TABLE STILIFRONTOFFICE modify LABEL_INFO_PERSONALI number(10,0);

ALTER TABLE STILIFRONTOFFICE modify LABEL_INFO_PERSONALION number(10,0);

ALTER TABLE STILIFRONTOFFICE modify LABEL_INSERIMENTO number(10,0);

ALTER TABLE STILIFRONTOFFICE modify LABEL_INSERIMENTOON number(10,0);

ALTER TABLE STILIFRONTOFFICE modify LABEL_RISULTATO number(10,0);

ALTER TABLE STILIFRONTOFFICE modify LABEL_RISULTATOON number(10,0);

ALTER TABLE STILIFRONTOFFICE modify LABEL_SERVIZI_ACCESSORI number(10,0);

ALTER TABLE STILIFRONTOFFICE modify LABEL_SERVIZI_PRINCIPALI number(10,0);

ALTER TABLE STILIFRONTOFFICE modify STYLEIE number(10,0);

ALTER TABLE STILIFRONTOFFICE modify WCAG1AA number(10,0);

ALTER TABLE LEGGI modify CODICEOGGETTO number(10,0);

ALTER TABLE DOM_DOCUMENTI modify CODICEOGGETTO number(10,0);

ALTER TABLE DOM_ALLEGATIENDO modify CODICEOGGETTO number(10,0);

ALTER TABLE COMMEDILIZIE_ALLEGATI modify CODICEOGGETTO number(10,0);

ALTER TABLE STILIFRONTOFFICE modify SFONDO_TABLEHOME number(10,0);

ALTER TABLE STILIFRONTOFFICE modify LABEL_DOCUMENTI_DA_SCARICARE number(10,0);

ALTER TABLE STILIFRONTOFFICE modify LOGO_SUAP number(10,0);

ALTER TABLE STILIFRONTOFFICE modify LOGO_COMUNE number(10,0);

ALTER TABLE STILIFRONTOFFICE modify ICO_UNDERC number(10,0);

ALTER TABLE STILIFRONTOFFICE modify ICO_RE number(10,0);

ALTER TABLE STILIFRONTOFFICE modify ICO_MSG1 number(10,0);

ALTER TABLE STILIFRONTOFFICE modify ICO_CESTINO number(10,0);

ALTER TABLE OGGETTIINFO modify CODICEOGGETTO number(10,0);

ALTER TABLE STILIFRONTOFFICE modify LABEL_ACCESSI number(10,0);

ALTER TABLE MERCATI modify CODICEOGGETTO number(10,0);

ALTER TABLE ALBO_PUBBLICAZIONI_ALLEGATI modify CODICEOGGETTO number(10,0);

ALTER TABLE ALBEROPROC_DOCUMENTICAT modify CODICEOGGETTO number(10,0);

ALTER TABLE STP_ENDO_TIPO1 modify CODICEOGGETTO number(10,0);

ALTER TABLE STP_ENDO_TIPO2 modify CODICEOGGETTO number(10,0);

ALTER TABLE DOCUMENTIISTANZA modify CODICEOGGETTO number(10,0);

ALTER TABLE CONFIGURAZIONE modify CODICEOGGETTOSTILI number(10,0);

ALTER TABLE CONFIGURAZIONE modify CODICEOGGETTO4 number(10,0);

ALTER TABLE CONFIGURAZIONE modify CODICEOGGETTO2 number(10,0);

ALTER TABLE CONFIGURAZIONE modify CODICEOGGETTOMODDOCTIPO number(10,0);

ALTER TABLE CDSATTI modify CODICEOGGETTO number(10,0);

ALTER TABLE COMUNIASSOCIATI modify SI_STEMMA number(10,0);

ALTER TABLE COMUNIASSOCIATISOFTWARE modify SI_STEMMA number(10,0);

ALTER TABLE TIPIPROCEDURE modify CODICEOGGETTOFACSDOMPREC number(10,0);

ALTER TABLE TIPIPROCEDURE modify CODICEOGGETTODIAGRAMMA number(10,0);

ALTER TABLE TIPIPROCEDURE modify CODICEOGGETTODOL number(10,0);

ALTER TABLE TIPIPROCEDURE modify CODICEOGGETTO number(10,0);

ALTER TABLE PROTOCOLLO modify CODICEOGGETTO number(10,0);

ALTER TABLE MODELLI modify CODICEOGGETTO number(10,0);

ALTER TABLE NEWS modify CODICEOGGETTO1 number(10,0);

ALTER TABLE NEWS modify CODICEOGGETTO4 number(10,0);

ALTER TABLE NEWS modify CODICEOGGETTO3 number(10,0);

ALTER TABLE NEWS modify CODICEOGGETTO2 number(10,0);

ALTER TABLE NORMEGENERALI modify CODICEOGGETTO number(10,0);

ALTER TABLE BACHECALAVOROCONFIGURAZIONE modify CERCOLAVOROOGGETTO number(10,0);

ALTER TABLE BACHECALAVOROCONFIGURAZIONE modify OFFROLAVOROOGGETTO number(10,0);

ALTER TABLE MOVIMENTIMAILALLEGATI modify CODICEOGGETTO number(10,0);

ALTER TABLE SETTORIAVVISI modify CODICEOGGETTO number(10,0);

ALTER TABLE TIPIPROCEDURE_DOCUMENTI modify CODICEOGGETTO number(10,0);

ALTER TABLE INFO modify CODICEOGGETTO number(10,0);

ALTER TABLE MOVIMENTIALLEGATI modify CODICEOGGETTO number(10,0);

ALTER TABLE ISTANZEALLEGATI modify CODICEOGGETTO number(10,0);

ALTER TABLE ANAGRAFEDOCUMENTI modify CODICEOGGETTO number(10,0);

ALTER TABLE ALBEROPROC_DOCUMENTI modify CODICEOGGETTO number(10,0);

ALTER TABLE ISTANZEPEOPLET modify CODICEOGGETTO number(10,0);

ALTER TABLE COLLAUDO modify CODICEOGGETTO number(10,0);

ALTER TABLE COLLAUDOVERIFICHE modify CODICEOGGETTO number(10,0);

ALTER TABLE CONTROLLOVERIFICHE modify CODICEOGGETTO number(10,0);

ALTER TABLE DOCUMENTI modify CODICEOGGETTO number(10,0);

ALTER TABLE TESTIESTESI modify CODICEOGGETTO number(10,0);

ALTER TABLE ALLEGATI modify CODICEOGGETTO number(10,0);

ALTER TABLE DOMANDESTC modify CODICEOGGETTO number(10,0);

ALTER TABLE INVENTARIOPROCEDIMENTI modify TEMPIFICAZIONE number(10,0);

ALTER TABLE INVENTARIOPROCEDIMENTI modify CODICETIPO number(10,0);

ALTER TABLE STP_CATEGORIE_ENDO1 modify CODICE_TIPO_ENDO number(10,0);

ALTER TABLE TIPIENDO modify CODICEFAMIGLIAENDO number(10,0);

ALTER TABLE STP_TIPOLOGIE_ENDO1 modify CODICE_TIPIFAMIGLIE_ENDO number(10,0);

ALTER TABLE TEMPIRISPOSTA modify CODICEPROCEDURA number(10,0);

ALTER TABLE ISTANZE modify CODICEPROCEDURA number(10,0);

ALTER TABLE ALBEROPROC modify FKIDPROCEDURA number(10,0);

ALTER TABLE TIPIPROCEDURE_DOCUMENTI modify TP_FKPROCEDURA number(10,0);

ALTER TABLE SUBPROCEDURE modify CODICEPROCEDURA number(10,0);

ALTER TABLE TIPICONTROMOVIMENTO modify CODICEPROCEDURA number(10,0);

ALTER TABLE IMPIANTIPROCEDURE modify CODICEPROCEDURA number(10,0);

ALTER TABLE LEGGI modify LE_FKLTID number(10,0);

ALTER TABLE COMMEDILIZIE_ALLEGATI ADD (ID NUMBER(8,0));

ALTER TABLE AMMINISTRAZIONI MODIFY STC_IDENTE VARCHAR(10 CHAR);

ALTER TABLE ISTANZEALLEGATI MODIFY (STC_IDDOCUMENTO VARCHAR2(200 CHAR) );

ALTER TABLE ISTANZEALLEGATI MODIFY (STC_IDALLEGATO VARCHAR2(200 CHAR) );

ALTER TABLE DOCUMENTIISTANZA MODIFY (STC_IDDOCUMENTO VARCHAR2(200 CHAR) );

ALTER TABLE DOCUMENTIISTANZA MODIFY (STC_IDALLEGATO VARCHAR2(200 CHAR) );

ALTER TABLE MOVIMENTIALLEGATI MODIFY (STC_IDDOCUMENTO VARCHAR2(200 CHAR) );

ALTER TABLE MOVIMENTIALLEGATI MODIFY (STC_IDALLEGATO VARCHAR2(200 CHAR) );

ALTER TABLE MAPPATURE MODIFY (NOMETAGPEOPLE VARCHAR2(100 CHAR) );

alter table movimenti_contromovimenti modify codicemovimento number(8,0);
ALTER TABLE MOVIMENTI_CONTROMOVIMENTI MODIFY CODICECONTROMOVIMENTO NUMBER(8,0);
ALTER TABLE AUTORIZZAZIONI MODIFY (CODICEMOVIMENTO NUMBER(8,0));                                
ALTER TABLE BATCH_SCADENZARIO MODIFY (CODICEMOVIMENTO NUMBER(8,0));                             
ALTER TABLE CDS MODIFY (CODICEMOVIMENTO NUMBER(8,0));                                           
ALTER TABLE COMMISSIONIEDILIZIE_R MODIFY (CODICEMOVIMENTO NUMBER(8,0));                         
ALTER TABLE COMMISSIONIEDILIZIE_R MODIFY (CODICEMOVIMENTORIENTRO NUMBER(8,0));                  
ALTER TABLE MOVIMENTI MODIFY (CODICEMOVIMENTO NUMBER(8,0));                                     
ALTER TABLE MOVIMENTIALLEGATI MODIFY (CODICEMOVIMENTO NUMBER(8,0));                             
ALTER TABLE MOVIMENTIDYN2MODELLIT MODIFY (CODICEMOVIMENTO NUMBER(8,0));                         
ALTER TABLE MOVIMENTIHUMMINGBIRD MODIFY (CODICEMOVIMENTO NUMBER(8,0));                          
ALTER TABLE PARERI MODIFY (MOVIMENTO NUMBER(8,0));                                              
ALTER TABLE SORTEGGIDETTAGLIOMOVIMENTI MODIFY (CODICEMOVIMENTO NUMBER(8,0));                    
ALTER TABLE TMP_CONTROMOVEFF MODIFY (CODICEMOVIMENTOTX NUMBER(8,0));                            
ALTER TABLE TMP_CONTROMOVEFF MODIFY (CODICEMOVIMENTORX NUMBER(8,0));                            
ALTER TABLE TMP_PIANIFICAZIONI MODIFY (CODICEMOVIMENTO NUMBER(8,0));                                                            
ALTER TABLE AUTORIZZAZIONI_SUBENTRI MODIFY (CODICEMOVIMENTO NUMBER(8,0));                       
alter table movimentimail modify (codicemovimento number(8,0));
alter table movimenti_tempistica modify codicemovimentoapertura number(8,0);
alter table movimenti_tempistica modify CODICEMOVIMENTOCHIUSURA number(8,0);

ALTER TABLE DOMANDESTC ADD (CODICESOFTWARE VARCHAR2(2 CHAR) NOT NULL);
