alter table TIPIMODALITAPAGAMENTO add (FLAG_DISABILITATO NUMBER(1, 0));


ALTER TABLE RESPONSABILI ADD (FK_OGGETTO_IMMAGINE NUMBER(10) );

ALTER TABLE RESPONSABILI ADD CONSTRAINT FK_RESPONSABILI_OGGETTI FOREIGN KEY (IDCOMUNE , FK_OGGETTO_IMMAGINE )REFERENCES OGGETTI (  IDCOMUNE, CODICEOGGETTO);

ALTER TABLE ISTANZE ADD UUID VARCHAR2(60);
UPDATE ISTANZE SET UUID=SYS_GUID();
CREATE UNIQUE INDEX IDX_UQ_ISTANZA_UIID_001 ON ISTANZE (IDCOMUNE,UUID);

CREATE OR REPLACE VIEW vw_listapratiche AS
SELECT
  ISTANZE.CODICECOMUNE,
  ISTANZE.IDCOMUNE,
  ISTANZE.SOFTWARE AS SOFTWARE,
  SOFTWARE.DESCRIZIONELUNGA AS DESCSOFTWARE,
  ISTANZE.CODICEISTANZA AS IDPRATICA,
  ISTANZE.NUMEROISTANZA AS NUMEROPRATICA,
  TO_CHAR(ISTANZE.DATA,'DD/MM/YYYY') AS DATAPRESENTAZIONE,
  TO_CHAR(ISTANZE.DATA,'YYYY') AS ANNOPRESENTAZIONE,
  TO_CHAR(ISTANZE.DATA,'MM') AS MESEPRESENTAZIONE,
  ISTANZE.NUMEROPROTOCOLLO,
  TO_CHAR(ISTANZE.DATAPROTOCOLLO,'DD/MM/YYYY') AS DATAPROTOCOLLO,
  ISTANZE.CODICEINTERVENTOPROC AS CODICEINTERVENTO,
  VW_ALBEROPROC.SC_DESCRIZIONE AS DESCRIZIONEINTERVENTO,
  TIPIPROCEDURE.CODICEPROCEDURA,
  TIPIPROCEDURE.PROCEDURA,
  ISTANZE.LAVORI AS OGGETTO,
  UPPER(ISTANZE.LAVORI) AS OGGETTOU,
  ISTANZE.CHIUSURA AS CODSTATOPRATICA,
  STATO AS STATOPRATICA,
  RESPONSABILI.RESPONSABILE,
  RESPONSABILI.TELEFONOLAVORO AS RESPONSABILE_TELEFONO,
  NVL(STRADARIO.CODVIARIO,STRADARIO.CODICESTRADARIO) AS PR_CODVIARIO,
  STRADARIO.PREFISSO || ' ' || STRADARIO.DESCRIZIONE AS PR_INDIRIZZO,
  ISTANZESTRADARIO.CODICECIVICO AS PR_CODCIVICO,
  ISTANZESTRADARIO.CIVICO AS PR_CIVICO,
  ISTANZE.CODICEAREA AS CODICEZONIZZAZIONE,
  AREE.DENOMINAZIONE AS ZONIZZAZIONE,
  ANAGRAFE.CODICEANAGRAFE AS CODICERICHIEDENTE,
  NVL(UPPER(ANAGRAFE.CODICEFISCALE), '') AS CODICEFISCALE,
  NVL(ANAGRAFE.PARTITAIVA, '') AS PARTITAIVA,
  ANAGRAFE.NOMINATIVO || ' ' || ANAGRAFE.NOME AS NOMINATIVO,
  ANAGRAFE.INDIRIZZO,
  ANAGRAFE.CAP,
  ANAGRAFE.CITTA AS LOCALITA,
  COMUNERESIDENZA.COMUNE AS CITTA,
  COMUNERESIDENZA.PROVINCIA,
  TIPISOGGETTO.TIPOSOGGETTO AS TIPORAPPORTO,
  CATASTO.DESCRIZIONE AS TIPOCATASTO,
  ISTANZEMAPPALI.FOGLIO,
  ISTANZEMAPPALI.PARTICELLA,
  ISTANZEMAPPALI.SUB,
  TECNICO.CODICEANAGRAFE AS TEC_CODICE,
  TECNICO.NOMINATIVO || ' ' || TECNICO.NOME AS TEC_NOMINATIVO,
  NVL(UPPER(TECNICO.CODICEFISCALE), '') AS TEC_CODICEFISCALE,
  NVL(TECNICO.PARTITAIVA, '') AS TEC_PARTITAIVA,
  AZIENDA.CODICEANAGRAFE AS AZ_CODICE,
  AZIENDA.NOMINATIVO || ' ' || AZIENDA.NOME AS AZ_NOMINATIVO,
  NVL(UPPER(AZIENDA.CODICEFISCALE), '') AS AZ_CODICEFISCALE,
  NVL(AZIENDA.PARTITAIVA, '') AS AZ_PARTITAIVA,
  ISTRUTTORI.RESPONSABILE AS ISTRUTTORE,
  ISTRUTTORI.TELEFONOLAVORO AS ISTRUTTORE_TELEFONO,
  OPERATORI.RESPONSABILE AS OPERATORE,
  OPERATORI.TELEFONOLAVORO AS OPERATORE_TELEFONO,
  ISTANZE.DOMICILIO_ELETTRONICO AS DOMICILIO_ELETTRONICO,
  DOMANDESTC.ID_SPORTELLOMITT,
  DOMANDESTC.ID_DOMANDAMITT,
  istanze.uuid AS uuid
FROM
  ISTANZE
                INNER JOIN SOFTWARE ON SOFTWARE.CODICE = ISTANZE.SOFTWARE
                INNER JOIN ANAGRAFE ON ANAGRAFE.IDCOMUNE = ISTANZE.IDCOMUNE AND ANAGRAFE.CODICEANAGRAFE = ISTANZE.CODICERICHIEDENTE
                INNER JOIN STATIISTANZA ON STATIISTANZA.IDCOMUNE = ISTANZE.IDCOMUNE AND STATIISTANZA.SOFTWARE = ISTANZE.SOFTWARE AND STATIISTANZA.CODICESTATO = ISTANZE.CHIUSURA
                INNER JOIN VW_ALBEROPROC ON VW_ALBEROPROC.IDCOMUNE = ISTANZE.IDCOMUNE AND VW_ALBEROPROC.SC_ID = ISTANZE.CODICEINTERVENTOPROC
                LEFT JOIN ANAGRAFE TECNICO ON TECNICO.IDCOMUNE = ISTANZE.IDCOMUNE AND TECNICO.CODICEANAGRAFE = ISTANZE.CODICEPROFESSIONISTA
                LEFT JOIN ANAGRAFE AZIENDA ON ISTANZE.IDCOMUNE = AZIENDA.IDCOMUNE AND ISTANZE.CODICETITOLARELEGALE = AZIENDA.CODICEANAGRAFE
                LEFT JOIN ISTANZESTRADARIO ON ISTANZE.IDCOMUNE = ISTANZESTRADARIO.IDCOMUNE AND ISTANZE.CODICEISTANZA = ISTANZESTRADARIO.CODICEISTANZA AND 1 = ISTANZESTRADARIO.PRIMARIO
                LEFT JOIN STRADARIO ON STRADARIO.IDCOMUNE = ISTANZESTRADARIO.IDCOMUNE AND STRADARIO.CODICESTRADARIO = ISTANZESTRADARIO.CODICESTRADARIO
                LEFT JOIN ISTANZEMAPPALI ON ISTANZE.IDCOMUNE = ISTANZEMAPPALI.IDCOMUNE AND ISTANZE.CODICEISTANZA = ISTANZEMAPPALI.FKCODICEISTANZA AND 1 = ISTANZEMAPPALI.PRIMARIO
                LEFT JOIN RESPONSABILI ON ISTANZE.IDCOMUNE = RESPONSABILI.IDCOMUNE AND ISTANZE.CODICERESPONSABILEPROC = RESPONSABILI.CODICERESPONSABILE
                LEFT JOIN COMUNI COMUNERESIDENZA ON ANAGRAFE.COMUNERESIDENZA = COMUNERESIDENZA.CODICECOMUNE
                LEFT JOIN TIPISOGGETTO ON ISTANZE.IDCOMUNE = TIPISOGGETTO.IDCOMUNE AND ISTANZE.FKCODICESOGGETTO = TIPISOGGETTO.CODICETIPOSOGGETTO
                LEFT JOIN AREE ON ISTANZE.IDCOMUNE = AREE.IDCOMUNE AND ISTANZE.CODICEAREA = AREE.CODICEAREA
                LEFT JOIN CATASTO ON ISTANZEMAPPALI.CODICECATASTO = CATASTO.CODICE
                LEFT JOIN TIPIPROCEDURE ON ISTANZE.IDCOMUNE = TIPIPROCEDURE.IDCOMUNE AND ISTANZE.CODICEPROCEDURA = TIPIPROCEDURE.CODICEPROCEDURA
                LEFT JOIN RESPONSABILI ISTRUTTORI ON ISTANZE.IDCOMUNE = ISTRUTTORI.IDCOMUNE AND ISTANZE.CODICEISTRUTTORE = ISTRUTTORI.CODICERESPONSABILE
                LEFT JOIN RESPONSABILI OPERATORI ON OPERATORI.IDCOMUNE = ISTANZE.IDCOMUNE AND OPERATORI.CODICERESPONSABILE = ISTANZE.CODICERESPONSABILE
                LEFT JOIN DOMANDESTC ON ISTANZE.IDCOMUNE = DOMANDESTC.IDCOMUNE AND ISTANZE.CODICEISTANZA = DOMANDESTC.CODICEISTANZA;

CREATE OR REPLACE VIEW VW_ALBEROPROC AS SELECT ALBEROPROC.IDCOMUNE, ALBEROPROC.SOFTWARE, ALBEROPROC.SC_ID, ALBEROPROC.SC_CODICE, ALBEROPROC.SC_PADRE, DECODE(ALBEROPROC_L1.SC_DESCRIZIONE,NULL,'',ALBEROPROC_L1.SC_DESCRIZIONE) || DECODE(ALBEROPROC_L2.SC_DESCRIZIONE,NULL,'',' - ' || ALBEROPROC_L2.SC_DESCRIZIONE) || DECODE(ALBEROPROC_L3.SC_DESCRIZIONE,NULL,'',' - ' || ALBEROPROC_L3.SC_DESCRIZIONE) || DECODE(ALBEROPROC_L4.SC_DESCRIZIONE,NULL,'',' - ' || ALBEROPROC_L4.SC_DESCRIZIONE) || DECODE(ALBEROPROC_L5.SC_DESCRIZIONE,NULL,'',' - ' || ALBEROPROC_L5.SC_DESCRIZIONE) || DECODE(ALBEROPROC_L6.SC_DESCRIZIONE,NULL,'',' - ' || ALBEROPROC_L6.SC_DESCRIZIONE) || DECODE(ALBEROPROC_L7.SC_DESCRIZIONE,NULL,'',' - ' || ALBEROPROC_L7.SC_DESCRIZIONE) || DECODE(ALBEROPROC_L8.SC_DESCRIZIONE,NULL,'',' - ' || ALBEROPROC_L8.SC_DESCRIZIONE) AS SC_DESCRIZIONE, DECODE(ALBEROPROC_L2.SC_DESCRIZIONE,NULL,'',ALBEROPROC_L1.SC_DESCRIZIONE) || DECODE(ALBEROPROC_L3.SC_DESCRIZIONE,NULL,'',' - ' || ALBEROPROC_L2.SC_DESCRIZIONE) || DECODE(ALBEROPROC_L4.SC_DESCRIZIONE,NULL,'',' - ' || ALBEROPROC_L3.SC_DESCRIZIONE) || DECODE(ALBEROPROC_L5.SC_DESCRIZIONE,NULL,'',' - ' || ALBEROPROC_L4.SC_DESCRIZIONE) || DECODE(ALBEROPROC_L6.SC_DESCRIZIONE,NULL,'',' - ' || ALBEROPROC_L5.SC_DESCRIZIONE) || DECODE(ALBEROPROC_L7.SC_DESCRIZIONE,NULL,'',' - ' || ALBEROPROC_L6.SC_DESCRIZIONE) || DECODE(ALBEROPROC_L8.SC_DESCRIZIONE,NULL,'',' - ' || ALBEROPROC_L7.SC_DESCRIZIONE) AS SC_DESCRIZIONEPADRE, ALBEROPROC.SC_DESCRIZIONE AS SC_DESCRIZIONEBREVE, ALBEROPROC_L1.SC_DESCRIZIONE AS DESCR_L1, ALBEROPROC_L2.SC_DESCRIZIONE AS DESCR_L2, ALBEROPROC_L3.SC_DESCRIZIONE AS DESCR_L3, ALBEROPROC_L4.SC_DESCRIZIONE AS DESCR_L4, ALBEROPROC_L5.SC_DESCRIZIONE AS DESCR_L5, ALBEROPROC_L6.SC_DESCRIZIONE AS DESCR_L6, ALBEROPROC_L7.SC_DESCRIZIONE AS DESCR_L7, ALBEROPROC_L8.SC_DESCRIZIONE AS DESCR_L8, ALBEROPROC.SC_ORDINE AS ORDINE0, NVL(ALBEROPROC_L1.SC_ORDINE,0) AS ORDINE1, NVL(ALBEROPROC_L2.SC_ORDINE,0) AS ORDINE2, NVL(ALBEROPROC_L3.SC_ORDINE,0) AS ORDINE3, NVL(ALBEROPROC_L4.SC_ORDINE,0)  AS ORDINE4, NVL(ALBEROPROC_L5.SC_ORDINE,0)  AS ORDINE5, NVL(ALBEROPROC_L6.SC_ORDINE,0)  AS ORDINE6, NVL(ALBEROPROC_L7.SC_ORDINE,0)  AS ORDINE7, NVL(ALBEROPROC_L8.SC_ORDINE,0)  AS ORDINE8, DECODE(ALBEROPROC_L8.FKCODICEMERCATO,NULL,DECODE(ALBEROPROC_L7.FKCODICEMERCATO,NULL,DECODE(ALBEROPROC_L6.FKCODICEMERCATO,NULL,DECODE(ALBEROPROC_L5.FKCODICEMERCATO,NULL,DECODE(ALBEROPROC_L4.FKCODICEMERCATO,NULL,DECODE(ALBEROPROC_L3.FKCODICEMERCATO,NULL,DECODE(ALBEROPROC_L2.FKCODICEMERCATO,NULL,ALBEROPROC_L1.FKCODICEMERCATO,ALBEROPROC_L2.FKCODICEMERCATO),ALBEROPROC_L3.FKCODICEMERCATO),ALBEROPROC_L4.FKCODICEMERCATO),ALBEROPROC_L5.FKCODICEMERCATO),ALBEROPROC_L6.FKCODICEMERCATO),ALBEROPROC_L7.FKCODICEMERCATO),ALBEROPROC_L8.FKCODICEMERCATO) AS FKCODICEMERCATO, DECODE(ALBEROPROC_L8.FKIDMERCATIUSO,NULL,DECODE(ALBEROPROC_L7.FKIDMERCATIUSO,NULL,DECODE(ALBEROPROC_L6.FKIDMERCATIUSO,NULL,DECODE(ALBEROPROC_L5.FKIDMERCATIUSO,NULL,DECODE(ALBEROPROC_L4.FKIDMERCATIUSO,NULL,DECODE(ALBEROPROC_L3.FKIDMERCATIUSO,NULL,DECODE(ALBEROPROC_L2.FKIDMERCATIUSO,NULL,ALBEROPROC_L1.FKIDMERCATIUSO,ALBEROPROC_L2.FKIDMERCATIUSO),ALBEROPROC_L3.FKIDMERCATIUSO),ALBEROPROC_L4.FKIDMERCATIUSO),ALBEROPROC_L5.FKIDMERCATIUSO),ALBEROPROC_L6.FKIDMERCATIUSO),ALBEROPROC_L7.FKIDMERCATIUSO),ALBEROPROC_L8.FKIDMERCATIUSO)  AS FKIDMERCATIUSO, ALBEROPROC.SC_ATTIVO, ALBEROPROC.PROGRESSIVOISTANZE, ALBEROPROC.SC_PUBBLICA || ALBEROPROC_L1.SC_PUBBLICA || ALBEROPROC_L2.SC_PUBBLICA || ALBEROPROC_L3.SC_PUBBLICA || ALBEROPROC_L4.SC_PUBBLICA || ALBEROPROC_L5.SC_PUBBLICA || ALBEROPROC_L6.SC_PUBBLICA || ALBEROPROC_L7.SC_PUBBLICA || ALBEROPROC_L8.SC_PUBBLICA AS PUBBLICA FROM ALBEROPROC LEFT JOIN ALBEROPROC ALBEROPROC_L1 ON ALBEROPROC_L1.IDCOMUNE = ALBEROPROC.IDCOMUNE AND ALBEROPROC_L1.SOFTWARE = ALBEROPROC.SOFTWARE AND ALBEROPROC_L1.SC_CODICE = SUBSTR(ALBEROPROC.SC_CODICE, 0, 2) AND LENGTH(ALBEROPROC_L1.SC_CODICE)=2 LEFT JOIN ALBEROPROC ALBEROPROC_L2 ON ALBEROPROC_L2.IDCOMUNE = ALBEROPROC_L1.IDCOMUNE AND ALBEROPROC_L2.SOFTWARE = ALBEROPROC_L1.SOFTWARE AND ALBEROPROC_L2.SC_CODICE = SUBSTR(ALBEROPROC.SC_CODICE, 0, 4) AND LENGTH(ALBEROPROC_L2.SC_CODICE)=4 LEFT JOIN ALBEROPROC ALBEROPROC_L3 ON ALBEROPROC_L3.IDCOMUNE = ALBEROPROC_L2.IDCOMUNE AND ALBEROPROC_L3.SOFTWARE = ALBEROPROC_L2.SOFTWARE AND ALBEROPROC_L3.SC_CODICE = SUBSTR(ALBEROPROC.SC_CODICE, 0, 6) AND LENGTH(ALBEROPROC_L3.SC_CODICE)=6 LEFT JOIN ALBEROPROC ALBEROPROC_L4 ON ALBEROPROC_L4.IDCOMUNE = ALBEROPROC_L3.IDCOMUNE AND ALBEROPROC_L4.SOFTWARE = ALBEROPROC_L3.SOFTWARE AND ALBEROPROC_L4.SC_CODICE = SUBSTR(ALBEROPROC.SC_CODICE, 0, 8) AND LENGTH(ALBEROPROC_L4.SC_CODICE)=8 LEFT JOIN ALBEROPROC ALBEROPROC_L5 ON ALBEROPROC_L5.IDCOMUNE = ALBEROPROC_L4.IDCOMUNE AND ALBEROPROC_L5.SOFTWARE = ALBEROPROC_L4.SOFTWARE AND ALBEROPROC_L5.SC_CODICE = SUBSTR(ALBEROPROC.SC_CODICE, 0, 10) AND LENGTH(ALBEROPROC_L5.SC_CODICE)=10 LEFT JOIN ALBEROPROC ALBEROPROC_L6 ON ALBEROPROC_L6.IDCOMUNE = ALBEROPROC_L5.IDCOMUNE AND ALBEROPROC_L6.SOFTWARE = ALBEROPROC_L5.SOFTWARE AND ALBEROPROC_L6.SC_CODICE = SUBSTR(ALBEROPROC.SC_CODICE, 0, 12) AND LENGTH(ALBEROPROC_L6.SC_CODICE)=12 LEFT JOIN ALBEROPROC ALBEROPROC_L7 ON ALBEROPROC_L7.IDCOMUNE = ALBEROPROC_L6.IDCOMUNE AND ALBEROPROC_L7.SOFTWARE = ALBEROPROC_L6.SOFTWARE AND ALBEROPROC_L7.SC_CODICE = SUBSTR(ALBEROPROC.SC_CODICE, 0, 14) AND LENGTH(ALBEROPROC_L7.SC_CODICE)=14 LEFT JOIN ALBEROPROC ALBEROPROC_L8 ON ALBEROPROC_L8.IDCOMUNE = ALBEROPROC_L7.IDCOMUNE AND ALBEROPROC_L8.SOFTWARE = ALBEROPROC_L7.SOFTWARE AND ALBEROPROC_L8.SC_CODICE = SUBSTR(ALBEROPROC.SC_CODICE, 0, 16) AND LENGTH(ALBEROPROC_L8.SC_CODICE)=16;
ALTER TABLE softwareattivi ADD flag_subvisura NUMBER(1,0);
ALTER TABLE TIPIMOVIMENTO ADD FLAG_AGGIORNA_RIEPILOGO NUMBER(1,0);

CREATE INDEX DX_MOVIMENTI_007 ON MOVIMENTI (IDCOMUNE, ID_ATT_DEST, DATA);
ALTER table layouttesti MODIFY codicetesto VARCHAR2(128);
ALTER table layouttestibase MODIFY codicetesto VARCHAR2(128);


CREATE TABLE NOTIFICA_PAGAMENTI (
IDDOMANDA VARCHAR2(50) NOT NULL ENABLE, 
MESSAGGIO VARCHAR2(4000) NOT NULL ENABLE, 
ESITO VARCHAR2(2) NOT NULL ENABLE, 
DATA VARCHAR2(20) NOT NULL ENABLE, 
IDCOMUNE VARCHAR2(6) NOT NULL ENABLE, 
NUMEROOPERAZIONE VARCHAR2(50) NOT NULL ENABLE, 
IDORDINE VARCHAR2(50) NOT NULL ENABLE, 
IDTRANSAZIONE VARCHAR2(10) NOT NULL ENABLE, 
TIPOPAGAMENTO VARCHAR2(10) NOT NULL ENABLE 
);
ALTER TABLE NOTIFICA_PAGAMENTI ADD CONSTRAINT NOTIFICA_PAGAMENTI_PK PRIMARY KEY (IDCOMUNE, NUMEROOPERAZIONE);

alter table statiistanza add OSPLDP_STATO_PRATICA varchar2(20);