ALTER TABLE MAIL_CONFIG ADD ID NUMBER(5,0);
ALTER TABLE MAIL_CONFIG ADD DESCRIZIONE VARCHAR2 (500);
ALTER TABLE MAIL_CONFIG ADD FLAG_DISABILITATO  NUMBER(1,0) DEFAULT 0;
ALTER TABLE MAIL_CONFIG ADD FLAG_PRINCIPALE  NUMBER(1,0) DEFAULT 0;
ALTER TABLE MAIL_CONFIG ADD CODICECOMUNE VARCHAR2(5);

ALTER TABLE MAIL_CONFIG DROP CONSTRAINT MAIL_CONFIG_PK;

ALTER TABLE MOVIMENTIMAIL ADD ACCOUNT_ID NUMBER(5,0);
ALTER TABLE PEC_INBOX ADD  ACCOUNT_ID NUMBER (5,0);

ALTER TABLE ALBEROPROC ADD FLG_ACCESSO_ATTI NUMBER (1,0) DEFAULT 0;

CREATE TABLE ISTANZE_ACCESSO_ATTI_T(
IDCOMUNE  VARCHAR2(6) NOT NULL,
ID NUMBER(9,0) NOT NULL,       
CODICEISTANZA NUMBER(6,0) NOT NULL,
DATAINIZIO DATE,
DATAFINE DATE,
CODICEOPERATORE NUMBER(8,0) NOT NULL,     
FLG_PUBBLICA NUMBER(1,0)
);

ALTER TABLE ISTANZE_ACCESSO_ATTI_T ADD CONSTRAINT PK_ISTANZE_ACCESSO_AGLI_ATTI_T PRIMARY KEY(IDCOMUNE,ID);
ALTER TABLE ISTANZE_ACCESSO_ATTI_T ADD CONSTRAINT FK_IST_ATTI_T_IST FOREIGN KEY(IDCOMUNE,CODICEISTANZA) REFERENCES ISTANZE(IDCOMUNE,CODICEISTANZA);
ALTER TABLE ISTANZE_ACCESSO_ATTI_T ADD CONSTRAINT FK_IST_ATTI_T_RESP FOREIGN KEY(IDCOMUNE,CODICEOPERATORE) REFERENCES RESPONSABILI(IDCOMUNE,CODICERESPONSABILE);


CREATE TABLE ISTANZE_ACCESSO_ATTI_D(
IDCOMUNE  VARCHAR2(6) NOT NULL,
ID NUMBER(9,0) NOT NULL,
FK_IDACCESSO_ATTI NUMBER(9,0) NOT NULL,
CODICEISTANZA NUMBER(6,0) NOT NULL,
FLG_VISUALIZZA_DOC NUMBER(1,0)
);

ALTER TABLE ISTANZE_ACCESSO_ATTI_D ADD CONSTRAINT PK_ISTANZE_ACCESSO_AGLI_ATTI_D PRIMARY KEY(IDCOMUNE,ID);
ALTER TABLE ISTANZE_ACCESSO_ATTI_D ADD CONSTRAINT FK_IST_ATTI_D_IST FOREIGN KEY (IDCOMUNE, CODICEISTANZA) REFERENCES ISTANZE(IDCOMUNE,CODICEISTANZA);
ALTER TABLE ISTANZE_ACCESSO_ATTI_D ADD CONSTRAINT FK_IST_ATTI_D_T FOREIGN KEY (IDCOMUNE,FK_IDACCESSO_ATTI) REFERENCES ISTANZE_ACCESSO_ATTI_T(IDCOMUNE, ID);



CREATE TABLE ISTANZE_ACCESSO_ATTI_ANAGRAFE (
IDCOMUNE VARCHAR2(6) NOT NULL,
FK_IDACCESSO_ATTI NUMBER(9,0) NOT NULL,
CODICEANAGRAFE NUMBER(6,0) NOT NULL
); 

ALTER TABLE ISTANZE_ACCESSO_ATTI_ANAGRAFE ADD CONSTRAINT ISTAN_ACCESSO_ATTI_ANAGR_PK PRIMARY KEY(IDCOMUNE, FK_IDACCESSO_ATTI, CODICEANAGRAFE);
ALTER TABLE ISTANZE_ACCESSO_ATTI_ANAGRAFE ADD CONSTRAINT FK_IST_ACC_ATT_ANG_ACC_T FOREIGN KEY(IDCOMUNE,FK_IDACCESSO_ATTI) REFERENCES ISTANZE_ACCESSO_ATTI_T(IDCOMUNE,ID);
ALTER TABLE ISTANZE_ACCESSO_ATTI_ANAGRAFE ADD CONSTRAINT FK_IST_ACC_ATT_ANAG_ACC_ANAG FOREIGN KEY(IDCOMUNE,CODICEANAGRAFE) REFERENCES ANAGRAFE(IDCOMUNE,CODICEANAGRAFE);



CREATE TABLE ISTANZE_ACCESSO_ATTI_LOG (
IDCOMUNE VARCHAR2(6) NOT NULL,
UUID VARCHAR2(50) NOT NULL,
FK_IDACCESSO_ATTI NUMBER(9,0) NOT NULL,
DATAORA DATE,
CODICEANAGRAFE NUMBER(6,0) NOT NULL,
CODICEISTANZA NUMBER(6,0) NOT NULL
);

UPDATE ISTANZE_ACCESSO_ATTI_LOG SET UUID = Sys_Guid();

ALTER TABLE ISTANZE_ACCESSO_ATTI_LOG ADD CONSTRAINT ISTANZE_ACCESSO_ATTI_LOG_PK PRIMARY KEY(IDCOMUNE, UUID);

ALTER TABLE ISTANZE_ACCESSO_ATTI_LOG ADD CONSTRAINT FK_ATTI_LOG_CODICEANAGRAFE FOREIGN KEY(IDCOMUNE, CODICEANAGRAFE) REFERENCES ANAGRAFE(IDCOMUNE, CODICEANAGRAFE);
ALTER TABLE ISTANZE_ACCESSO_ATTI_LOG ADD CONSTRAINT FK_ATTI_LOG_CODICEISTANZA FOREIGN KEY(IDCOMUNE, CODICEISTANZA) REFERENCES ISTANZE(IDCOMUNE, CODICEISTANZA);
ALTER TABLE ISTANZE_ACCESSO_ATTI_LOG ADD CONSTRAINT FK_IDACC_ATTI_T FOREIGN KEY(IDCOMUNE,FK_IDACCESSO_ATTI) REFERENCES ISTANZE_ACCESSO_ATTI_T(IDCOMUNE,ID);

ALTER TABLE ANAGRAFE ADD DATA_INIZIO_ATTIVITA DATE;
ALTER TABLE ANAGRAFESTORICO ADD DATA_INIZIO_ATTIVITA DATE;

ALTER TABLE ISTANZE_ACCESSO_ATTI_T ADD DESCRIZIONE_FASCICOLO VARCHAR2(500);