INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_DOCAREA', 'ABILITA_WARN_FIRMA', 'Al momento abilitato solamente se il parametro TIPOFORNITORE è impostato a MAGGIOLI. Se valorizzato a 1, indica che, se in fase di inserimento file al protocollo, viene restituito un errore di verifica firma (quindi qualche file non firmato correttamente), la protocollazione va avanti ugualmente visualizzando un warning finale dove viene descritto il problema e su quale file avviene.');
INSERT INTO VERTICALIZZAZIONIBASE (MODULO, DESCRIZIONE) VALUES ('PROTOCOLLO_STUDIOK', 'Se abilitato consente di utilizzare le funzionalità del protocollo STUDIO K, quest''ultimo estende le funzionalità del PROTOCOLLO_SICRAWEB. In particolare, dalla versione 1.6 del web service è possibile assegnare protocolli ad uffici e inviare PEC per protocolli in partenza. In caso di versione inferiore alla 1.6 contattare Studio K per far aggiornare il web service oppure utilizzare la verticalizzazione PROTOCOLLO_SICRAWEB in quanto era una copia del ws di protocollo creato da Maggioli (Sicraweb appunto).');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_STUDIOK', 'URL', 'Url del web service di protocollazione da utilizzare.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_STUDIOK', 'CONNECTIONSTRING', 'Questo parametro serve per potersi autenticare al web service di protocollazione quindi è obbligatoria la sua presenza, praticamente è un token che deve essere fornito dal fornitore di protocollo, l''esempio per l''ambiente di test è 99#testuser@QGT.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_STUDIOK', 'CODICEAMMINISTRAZIONE', 'E'' un paramtro di base del sistema di protocollo, che indica su quale ente deve essere fatta la chiamata, è un parametro obbligatorio e deve essere fornito dal fornitore di protocollo.');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_STUDIOK', 'CODICEAOO', 'Codice IPA dell’AOO mittente del protocollo in uscita, ovvero dell’ente stesso.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_STUDIOK', 'INVIOPEC', 'Il web service di protocollo mette a disposizione del client il sistema di inviare una pec per i protocolli in uscita, valorizzare a 1 se si desidera usiufruire di questa funzionalità, qualsiasi altro valore o non valorizzato per non usufruirne.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('CART', 'NOTIFICA_COMPIL_PROTOCOLLO', 'Il parametro definisce il comportamento su come popolare il tag NOTIFICA.NUMEROPROTOCOLLO nella comunicazione enti terzi di RT quando il movimento di notifica non ha popolato il protocollo. Il parametro può assumere i valori: 0 – comunica errore “movimento non protocollato”; 1 – mette il numero di pratica sul tag del protocollo della notifica; 2 – mette il numero di protocollo della pratica sul tag del protocollo della notifica; 3 – setta il numero di pratica sul tag del protocollo della notifica (anche in presenza del numero protocollo sul movimento)');

INSERT INTO VERTICALIZZAZIONIBASE (MODULO, DESCRIZIONE) VALUES ('RFC239', 'Se abilitata, attiva l''integrazione con il sistema Rete dei SUAP della Regione Toscana secondo il protocollo RFC239');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('RFC239', 'MOV_VALUTAZIONE_INTEGRAZIONE', 'Codice del tipo movimento per la ricezione dello stimolo di valutazione integrazione dal BOE3');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('RFC239', 'MOV_INVIO_INTEGRAZIONI', 'Codice del tipo movimento per la ricezione dello stimolo di invio integrazioni dal FACCT');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('RFC239', 'MOV_VALUTAZIONE_CONFORMAZIONI', 'Codice del tipo movimento per la ricezione dello stimolo di valutazione conformazioni dal BOE3');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('RFC239', 'MOV_INVIO_CONFORMAZIONI', 'Codice del tipo movimento per la ricezione dello stimolo di invio conformazioni dal FACCT');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('RFC239', 'MOV_ESITO_NEGATIVO', 'Codice del tipo movimento per la ricezione dello stimolo di esito negativo dal BOE3');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('RFC239', 'MOV_COMUNICAZIONE', 'Codice del tipo movimento per la ricezione dello stimolo di comunicazione dal BOE3');
