//------------------------------------------------------------------------------
// <auto-generated>
//     Questo codice è stato generato da uno strumento.
//
//     Le modifiche apportate a questo file possono causare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VBG.Frontend.AppLogic.WsMappatureService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VBG.Frontend.AppLogic.WsMappatureService.IWsMappatureService")]
    public interface IWsMappatureService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsMappatureService/GetMappature", ReplyAction="http://tempuri.org/IWsMappatureService/GetMappatureResponse")]
        Init.SIGePro.Manager.DTO.Mappature.MappaturaDto[] GetMappature(string token, string software);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsMappatureService/GetMappature", ReplyAction="http://tempuri.org/IWsMappatureService/GetMappatureResponse")]
        System.Threading.Tasks.Task<Init.SIGePro.Manager.DTO.Mappature.MappaturaDto[]> GetMappatureAsync(string token, string software);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IWsMappatureServiceChannel : VBG.Frontend.AppLogic.WsMappatureService.IWsMappatureService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class WsMappatureServiceClient : System.ServiceModel.ClientBase<VBG.Frontend.AppLogic.WsMappatureService.IWsMappatureService>, VBG.Frontend.AppLogic.WsMappatureService.IWsMappatureService
    {
        
        /// <summary>
        /// Implementare questo metodo parziale per configurare l'endpoint servizio.
        /// </summary>
        /// <param name="serviceEndpoint">Endpoint da configurare</param>
        /// <param name="clientCredentials">Credenziali del client</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WsMappatureServiceClient() : 
                base(WsMappatureServiceClient.GetDefaultBinding(), WsMappatureServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IWsMappatureService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WsMappatureServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(WsMappatureServiceClient.GetBindingForEndpoint(endpointConfiguration), WsMappatureServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WsMappatureServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WsMappatureServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WsMappatureServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WsMappatureServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WsMappatureServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public Init.SIGePro.Manager.DTO.Mappature.MappaturaDto[] GetMappature(string token, string software)
        {
            return base.Channel.GetMappature(token, software);
        }
        
        public System.Threading.Tasks.Task<Init.SIGePro.Manager.DTO.Mappature.MappaturaDto[]> GetMappatureAsync(string token, string software)
        {
            return base.Channel.GetMappatureAsync(token, software);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IWsMappatureService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("L\'endpoint denominato \'{0}\' non è stato trovato.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IWsMappatureService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:2640/sigepro.net/WebServices/WsAreaRiservata/WcfServices/Mappatu" +
                        "re/WsMappatureService.svc");
            }
            throw new System.InvalidOperationException(string.Format("L\'endpoint denominato \'{0}\' non è stato trovato.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return WsMappatureServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IWsMappatureService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return WsMappatureServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IWsMappatureService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IWsMappatureService,
        }
    }
}
