CREATE TABLE PENTAHOCFG(
IDCOMUNE VARCHAR2(6) NOT NULL,
IDENTEBASE VARCHAR2(6) NULL,
IDMAILTIPO NUMBER(4,0) NULL
);
ALTER TABLE PENTAHOCFG ADD CONSTRAINT PK_PENTAHOCFG PRIMARY KEY (IDCOMUNE);
ALTER TABLE PENTAHOCFG ADD CONSTRAINT FK_PENTAHOCFG_MAILTIPO FOREIGN KEY (IDCOMUNE,IDMAILTIPO) REFERENCES MAILTIPO(IDCOMUNE,CODICEMAIL);


CREATE TABLE TIPICONTESTOESPORTAZIONE(
CODICE VARCHAR2(15) NOT NULL,
DESCRIZIONE VARCHAR2(30) NOT NULL
);

ALTER TABLE TIPICONTESTOESPORTAZIONE ADD CONSTRAINT PK_TIPICONTESTOESPORTAZIONE PRIMARY KEY (CODICE);

CREATE TABLE ESPORTAZIONI(
IDCOMUNE VARCHAR2(6) NOT NULL,
ID NUMBER(8,0) NOT NULL,
DESCRIZIONE VARCHAR2(100) NOT NULL,
FK_TIPICONTESTOESP_CODICE VARCHAR2(15) NOT NULL,
TRASFORMAZIONE VARCHAR2(50) NOT NULL,
FLG_ABILITATA NUMBER(1,0) NOT NULL
);

ALTER TABLE ESPORTAZIONI ADD CONSTRAINT PK_ESPORTAZIONI PRIMARY KEY (IDCOMUNE,ID);
ALTER TABLE ESPORTAZIONI ADD CONSTRAINT  FK_ESPORTAZIONI_TIPOCONT_EXP FOREIGN KEY (FK_TIPICONTESTOESP_CODICE) REFERENCES TIPICONTESTOESPORTAZIONE(CODICE);

CREATE TABLE PARAMETRIESPORTAZIONE(
IDCOMUNE VARCHAR2(6) NOT NULL,
ID NUMBER(8,0) NOT NULL,
FK_ESPORTAZIONE NUMBER(8,0) NOT NULL,
PARAMETRO VARCHAR2(25) NOT NULL,
DESCRIZIONE VARCHAR2(50)
);

ALTER TABLE PARAMETRIESPORTAZIONE ADD CONSTRAINT PK_PARAMETRIESPORTAZIONE PRIMARY KEY (IDCOMUNE,ID);

ALTER TABLE PARAMETRIESPORTAZIONE ADD CONSTRAINT  FK_PARAMETRIEXP_EXP FOREIGN KEY (IDCOMUNE,FK_ESPORTAZIONE) REFERENCES ESPORTAZIONI(IDCOMUNE,ID);

ALTER TABLE ISTANZEDELETE DROP PRIMARY KEY DROP INDEX;
ALTER TABLE ISTANZEDELETE ADD CONSTRAINT ISTANZEDELETE_PK PRIMARY KEY (IDCOMUNE, ID);

CREATE TABLE TMP_ESPORTAZIONI(
ID NUMBER(10,0) NOT NULL,
IDCOMUNE VARCHAR2(6) NOT NULL,
SESSIONID VARCHAR2(60) NOT NULL,
CODICE NUMBER(10,0) NOT NULL,
CODICECOMUNE VARCHAR2(5) NOT NULL,
DATA DATE NOT NULL
);

ALTER TABLE TMP_ESPORTAZIONI ADD CONSTRAINT PK_TMP_ESPORTAZIONI PRIMARY KEY (ID);

ALTER TABLE TEMP_LINKALLEGATI ADD (NOMEDOCUMENTO VARCHAR2(4000 CHAR));

CREATE OR REPLACE VIEW VW_ISTANZEDYN2_DATI AS 
SELECT
ISTANZEDYN2DATI.IDCOMUNE, ISTANZEDYN2DATI.CODICEISTANZA, ISTANZEDYN2MODELLIT.FK_D2MT_ID AS IDMODELLO, 
 DYN2_MODELLID.POSVERTICALE, DYN2_MODELLID.POSORIZZONTALE, NULL AS TIPOTESTO, NULL AS TESTO, 
 ISTANZEDYN2DATI.INDICE, DYN2_CAMPI.ID AS IDCAMPO, DYN2_CAMPI.NOMECAMPO, TO_CHAR(ISTANZEDYN2DATI.VALORE) AS VALORE 
FROM 
 DYN2_CAMPI
   LEFT JOIN ISTANZEDYN2DATI ON DYN2_CAMPI.IDCOMUNE = ISTANZEDYN2DATI.IDCOMUNE AND DYN2_CAMPI.ID = ISTANZEDYN2DATI.FK_D2C_ID
   INNER JOIN DYN2_MODELLID ON DYN2_MODELLID.IDCOMUNE = DYN2_CAMPI.IDCOMUNE AND DYN2_MODELLID.FK_D2C_ID = DYN2_CAMPI.ID
   INNER JOIN DYN2_MODELLIT ON DYN2_MODELLIT.IDCOMUNE = DYN2_MODELLID.IDCOMUNE AND DYN2_MODELLIT.ID = DYN2_MODELLID.FK_D2MT_ID 
   LEFT JOIN ISTANZEDYN2MODELLIT ON ISTANZEDYN2DATI.IDCOMUNE = ISTANZEDYN2MODELLIT.IDCOMUNE AND ISTANZEDYN2DATI.CODICEISTANZA = ISTANZEDYN2MODELLIT.CODICEISTANZA AND DYN2_MODELLIT.ID = ISTANZEDYN2MODELLIT.FK_D2MT_ID 
ORDER BY
  ISTANZEDYN2MODELLIT.IDCOMUNE, ISTANZEDYN2MODELLIT.CODICEISTANZA, ISTANZEDYN2MODELLIT.FK_D2MT_ID,
  DYN2_MODELLID.POSVERTICALE, DYN2_MODELLID.POSORIZZONTALE;

ALTER TABLE PROTOCOLLO_TIPIDOCUMENTO MODIFY (CODICE VARCHAR2(50));

ALTER TABLE ARCHIVIAZIONI_ISTANZE ADD ERRORE CLOB;
ALTER TABLE ARCHIVIAZIONI_ISTANZE ADD ESCLUSA NUMBER(1,0);

ALTER TABLE ISTANZE MODIFY FKIDPROTOCOLLO VARCHAR2(30);
ALTER TABLE MOVIMENTI MODIFY FKIDPROTOCOLLO VARCHAR2(30);
ALTER TABLE PEC_INBOX MODIFY IDPROTOCOLLO VARCHAR2(30);