package it.gruppoinit.pal.gp.core.scheduler.task;

public class Query {

    public static final String SELECT_ISTANZE_DA_ELABORARE = ""
	    + "SELECT ISTANZE.IDCOMUNE AS IDCOMUNE,ISTANZE.CODICECOMUNE AS CODICECOMUNE,ISTANZE.CODICEPRATICATEL AS CODICEPRATICATEL,"
	    + "ISTANZE.CODICEISTANZA AS CODICEISTANZA,ISTANZE.NUMEROISTANZA AS NUMEROISTANZA,ISTANZE.DATA AS DATAISTANZA,ISTANZE.NUMEROPROTOCOLLO AS NUMEROPROTOCOLLO,"
	    + "ISTANZE.DATAPROTOCOLLO AS DATAPROTOCOLLO,ANAGRAFE.NOME AS NOMERICHIEDENTE,ANAGRAFE.NOMINATIVO AS COGNOMERICHIEDENTE,ANAGRAFE.CODICEFISCALE AS CFRICHIEDENTE,ANAGRAFE.PARTITAIVA AS PIVARICHIEDENTE,"
	    + "TITOLARELEGALE.NOME AS NOMETITOLARE,TITOLARELEGALE.NOMINATIVO AS NOMINATIVOTITOLARE,TITOLARELEGALE.CODICEFISCALE AS CFTITOLARE,TITOLARELEGALE.PARTITAIVA AS PIVATITOLARE,"
	    + "AUTORIZZAZIONI.AUTORIZNUMERO AS AUTORIZNUMERO,AUTORIZZAZIONI.AUTORIZDATA AS AUTORIZDATA "
	    + "FROM ISTANZE LEFT OUTER JOIN ISTANZE_ELABORATE ON "
	    + "ISTANZE.IDCOMUNE=ISTANZE_ELABORATE.IDCOMUNE AND ISTANZE.CODICEISTANZA=ISTANZE_ELABORATE.CODICEISTANZA INNER JOIN ANAGRAFE ON "
	    + "ISTANZE.IDCOMUNE=ANAGRAFE.IDCOMUNE AND ISTANZE.CODICERICHIEDENTE=ANAGRAFE.CODICEANAGRAFE INNER JOIN AUTORIZZAZIONI ON "
	    + "ISTANZE.IDCOMUNE=AUTORIZZAZIONI.IDCOMUNE AND ISTANZE.CODICEISTANZA=AUTORIZZAZIONI.FKIDISTANZA INNER JOIN ISTANZEDYN2MODELLIT ON "
	    + "ISTANZE.IDCOMUNE=ISTANZEDYN2MODELLIT.IDCOMUNE AND ISTANZE.CODICEISTANZA=ISTANZEDYN2MODELLIT.CODICEISTANZA "
	    + "LEFT JOIN ANAGRAFE TITOLARELEGALE ON ISTANZE.IDCOMUNE=TITOLARELEGALE.IDCOMUNE AND ISTANZE.CODICETITOLARELEGALE=TITOLARELEGALE.CODICEANAGRAFE "    
	    + "WHERE ISTANZEDYN2MODELLIT.FK_D2MT_ID=? AND ISTANZE_ELABORATE.CODICEISTANZA IS NULL";
    public static final String SELECT_DATI_SCHEDA_FIERE = ""
	    + "SELECT DENOMIN.VALORE DENOMIN,COMUNE.VALORE COMUNE_SVOLGIMENTO,SEDE.VALORE LUOGO_SVOLGIMENTO,CLASSIF_FG.VALORE CLASSIF_FG,CLASSIF_FS.VALORE "
	    + "CLASSIF_FS,CLASSIF_MM.VALORE CLASSIF_MM,CLASSIF_E.VALORE CLASSIF_E,QUALIF_I.VALORE QUALIF_I,QUALIF_R.VALORE QUALIF_R,QUALIF_N.VALORE QUALIF_N "
	    + "FROM ISTANZEDYN2DATI DENOMIN INNER JOIN ISTANZEDYN2DATI COMUNE ON DENOMIN.IDCOMUNE=COMUNE.IDCOMUNE AND DENOMIN.CODICEISTANZA=COMUNE.CODICEISTANZA "
	    + "INNER JOIN ISTANZEDYN2DATI SEDE ON DENOMIN.IDCOMUNE=SEDE.IDCOMUNE AND DENOMIN.CODICEISTANZA=SEDE.CODICEISTANZA "
	    + "LEFT JOIN ISTANZEDYN2DATI CLASSIF_FG ON DENOMIN.IDCOMUNE=CLASSIF_FG.IDCOMUNE AND DENOMIN.CODICEISTANZA=CLASSIF_FG.CODICEISTANZA AND CLASSIF_FG.FK_D2C_ID=? "
	    + "LEFT JOIN ISTANZEDYN2DATI CLASSIF_FS ON DENOMIN.IDCOMUNE=CLASSIF_FS.IDCOMUNE AND DENOMIN.CODICEISTANZA=CLASSIF_FS.CODICEISTANZA AND CLASSIF_FS.FK_D2C_ID=? "
	    + "LEFT JOIN ISTANZEDYN2DATI CLASSIF_MM ON DENOMIN.IDCOMUNE=CLASSIF_MM.IDCOMUNE AND DENOMIN.CODICEISTANZA=CLASSIF_MM.CODICEISTANZA AND CLASSIF_MM.FK_D2C_ID=? "
	    + "LEFT JOIN ISTANZEDYN2DATI CLASSIF_E ON DENOMIN.IDCOMUNE=CLASSIF_E.IDCOMUNE AND DENOMIN.CODICEISTANZA=CLASSIF_E.CODICEISTANZA AND CLASSIF_E.FK_D2C_ID=? "
	    + "LEFT JOIN ISTANZEDYN2DATI QUALIF_I ON DENOMIN.IDCOMUNE=QUALIF_I.IDCOMUNE AND DENOMIN.CODICEISTANZA=QUALIF_I.CODICEISTANZA AND QUALIF_I.FK_D2C_ID=? "
	    + "LEFT JOIN ISTANZEDYN2DATI QUALIF_R ON DENOMIN.IDCOMUNE=QUALIF_R.IDCOMUNE AND DENOMIN.CODICEISTANZA=QUALIF_R.CODICEISTANZA AND QUALIF_R.FK_D2C_ID=? "
	    + "LEFT JOIN ISTANZEDYN2DATI QUALIF_N ON DENOMIN.IDCOMUNE=QUALIF_N.IDCOMUNE AND DENOMIN.CODICEISTANZA=QUALIF_N.CODICEISTANZA AND QUALIF_N.FK_D2C_ID=? "
	    + "WHERE DENOMIN.CODICEISTANZA=? AND DENOMIN.IDCOMUNE=? AND DENOMIN.FK_D2C_ID=? AND COMUNE.FK_D2C_ID=? AND SEDE.FK_D2C_ID=?";
    public static final String SELECT_DATI_SCHEDA_FIERE_SUAPE = ""
	    + "SELECT DENOMIN.VALORE DENOMIN,COMUNE.VALORE COMUNE_SVOLGIMENTO,SEDE.VALORE LUOGO_SVOLGIMENTO,CLASSIF_FG.VALORE CLASSIF_FG,CLASSIF_FS.VALORE "
	    + "CLASSIF_FS,CLASSIF_MM.VALORE CLASSIF_MM,CLASSIF_E.VALORE CLASSIF_E "
	    + "FROM ISTANZEDYN2DATI DENOMIN INNER JOIN ISTANZEDYN2DATI COMUNE ON DENOMIN.IDCOMUNE=COMUNE.IDCOMUNE AND DENOMIN.CODICEISTANZA=COMUNE.CODICEISTANZA "
	    + "INNER JOIN ISTANZEDYN2DATI SEDE ON DENOMIN.IDCOMUNE=SEDE.IDCOMUNE AND DENOMIN.CODICEISTANZA=SEDE.CODICEISTANZA "
	    + "LEFT JOIN ISTANZEDYN2DATI CLASSIF_FG ON DENOMIN.IDCOMUNE=CLASSIF_FG.IDCOMUNE AND DENOMIN.CODICEISTANZA=CLASSIF_FG.CODICEISTANZA AND CLASSIF_FG.FK_D2C_ID=? "
	    + "LEFT JOIN ISTANZEDYN2DATI CLASSIF_FS ON DENOMIN.IDCOMUNE=CLASSIF_FS.IDCOMUNE AND DENOMIN.CODICEISTANZA=CLASSIF_FS.CODICEISTANZA AND CLASSIF_FS.FK_D2C_ID=? "
	    + "LEFT JOIN ISTANZEDYN2DATI CLASSIF_MM ON DENOMIN.IDCOMUNE=CLASSIF_MM.IDCOMUNE AND DENOMIN.CODICEISTANZA=CLASSIF_MM.CODICEISTANZA AND CLASSIF_MM.FK_D2C_ID=? "
	    + "LEFT JOIN ISTANZEDYN2DATI CLASSIF_E ON DENOMIN.IDCOMUNE=CLASSIF_E.IDCOMUNE AND DENOMIN.CODICEISTANZA=CLASSIF_E.CODICEISTANZA AND CLASSIF_E.FK_D2C_ID=? "
	    + "WHERE DENOMIN.CODICEISTANZA=? AND DENOMIN.IDCOMUNE=? AND DENOMIN.FK_D2C_ID=? AND COMUNE.FK_D2C_ID=? AND SEDE.FK_D2C_ID=?";
    public static final String SELECT_DATI_SCHEDA_FIERE_DAL_AL = ""
	    + "SELECT DAL.VALOREDECODIFICATO DAL,AL.VALOREDECODIFICATO AL "
	    + "FROM ISTANZEDYN2DATI DAL INNER JOIN ISTANZEDYN2DATI AL ON DAL.IDCOMUNE=AL.IDCOMUNE AND DAL.CODICEISTANZA=AL.CODICEISTANZA AND DAL.INDICE_MOLTEPLICITA=AL.INDICE_MOLTEPLICITA "
	    + "WHERE DAL.CODICEISTANZA=? AND DAL.IDCOMUNE=? AND DAL.FK_D2C_ID=? AND AL.FK_D2C_ID=?";
    public static final String SELECT_DATI_SCHEDA_FIERE_MERCEOLOGIE = ""
	    + "SELECT MERCEOLOGIE.VALOREDECODIFICATO MERCEOLOGIA,MERCEOLOGIE_ALTRO.VALORE ALTRO "
	    + "FROM ISTANZEDYN2DATI MERCEOLOGIE LEFT JOIN ISTANZEDYN2DATI MERCEOLOGIE_ALTRO ON MERCEOLOGIE.IDCOMUNE=MERCEOLOGIE_ALTRO.IDCOMUNE "
	    + "AND MERCEOLOGIE.CODICEISTANZA=MERCEOLOGIE_ALTRO.CODICEISTANZA AND MERCEOLOGIE.INDICE_MOLTEPLICITA=MERCEOLOGIE_ALTRO.INDICE_MOLTEPLICITA "
	    + "AND MERCEOLOGIE_ALTRO.FK_D2C_ID=? WHERE MERCEOLOGIE.CODICEISTANZA=? AND MERCEOLOGIE.IDCOMUNE=? AND MERCEOLOGIE.FK_D2C_ID=? ORDER BY MERCEOLOGIE.INDICE_MOLTEPLICITA";
    public static final String SELECT_DATI_SCHEDA_SAGRE_SUAPE = ""
	    + "SELECT DENOMIN.VALORE DENOMIN,COMUNE.VALORE COMUNE_SVOLGIMENTO,SEDE.VALORE LUOGO_SVOLGIMENTO,SEDE_CIVICO.VALORE LUOGO_SVOLGIMENTO_CIVICO,"
	    + "DAL.VALOREDECODIFICATO DAL,AL.VALOREDECODIFICATO AL,"
	    + "TIPOLOGIA_A.VALORE TIPOLOGIA_A, TIPOLOGIA_B.VALORE TIPOLOGIA_B "
	    + "FROM ISTANZEDYN2DATI DENOMIN INNER JOIN ISTANZEDYN2DATI COMUNE ON DENOMIN.IDCOMUNE=COMUNE.IDCOMUNE AND DENOMIN.CODICEISTANZA=COMUNE.CODICEISTANZA "
	    + "INNER JOIN ISTANZEDYN2DATI SEDE ON DENOMIN.IDCOMUNE=SEDE.IDCOMUNE AND DENOMIN.CODICEISTANZA=SEDE.CODICEISTANZA "
	    + "INNER JOIN ISTANZEDYN2DATI DAL ON DENOMIN.IDCOMUNE=DAL.IDCOMUNE AND DENOMIN.CODICEISTANZA=DAL.CODICEISTANZA "
	    + "INNER JOIN ISTANZEDYN2DATI AL ON DENOMIN.IDCOMUNE=AL.IDCOMUNE AND DENOMIN.CODICEISTANZA=AL.CODICEISTANZA "
	    + "LEFT JOIN ISTANZEDYN2DATI TIPOLOGIA_A ON DENOMIN.IDCOMUNE=TIPOLOGIA_A.IDCOMUNE AND DENOMIN.CODICEISTANZA=TIPOLOGIA_A.CODICEISTANZA AND TIPOLOGIA_A.FK_D2C_ID=? "
	    + "LEFT JOIN ISTANZEDYN2DATI TIPOLOGIA_B ON DENOMIN.IDCOMUNE=TIPOLOGIA_B.IDCOMUNE AND DENOMIN.CODICEISTANZA=TIPOLOGIA_B.CODICEISTANZA AND TIPOLOGIA_B.FK_D2C_ID=? "
	    + "LEFT JOIN ISTANZEDYN2DATI SEDE_CIVICO ON DENOMIN.IDCOMUNE=SEDE_CIVICO.IDCOMUNE AND DENOMIN.CODICEISTANZA=SEDE_CIVICO.CODICEISTANZA AND SEDE_CIVICO.FK_D2C_ID=? "
	    + "WHERE DENOMIN.CODICEISTANZA=? AND DENOMIN.IDCOMUNE=? AND DENOMIN.FK_D2C_ID=? AND COMUNE.FK_D2C_ID=? AND SEDE.FK_D2C_ID=? AND DAL.FK_D2C_ID=? AND AL.FK_D2C_ID=?";
    public static final String INSERT_ISTANZE_ELABORATE = "INSERT INTO ISTANZE_ELABORATE (IDCOMUNE,CODICEISTANZA) VALUES (?,?)";
}
