ALTER TABLE RESPONSABILI ADD PESO_CARICO_LAVORO NUMERIC(3);
ALTER TABLE RESPONSABILI ADD FLAG_MOD_RESP_SORT NUMERIC(1,0);
DROP INDEX IDX_UQ_ISTANZA_UIID_001 ON istanze;
alter table istanze add constraint IDX_UQ_ISTANZA_UIID_001 UNIQUE(idcomune,uuid);

ALTER TABLE alberoproc ADD FLAG_AR_REDIRECT NUMERIC(1);

ALTER TABLE MOVIMENTI MODIFY CODICEISTANZA NUMERIC(6,0) NOT NULL;

ALTER TABLE ALBEROPROC MODIFY SC_CODICE VARCHAR(40);

alter table ISTANZEPROCURE add CODICEOGGETTO_DOCIDE NUMERIC(10,0);
alter table ISTANZEPROCURE add constraint FK_ISTPROC_IDENT_OGGETTI FOREIGN KEY(IDCOMUNE,CODICEOGGETTO_DOCIDE) REFERENCES OGGETTI (IDCOMUNE, CODICEOGGETTO);

alter table ISTANZEPROCURE add STC_ID_DOC_DOCIDE VARCHAR(500) ;
alter table ISTANZEPROCURE add STC_ID_ALL_DOCIDE VARCHAR(500) ;
