//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.20 at 10:59:58 AM CET 
//


package it.gruppoinit.sigepro.schemas.messages.mailtipo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="token" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="codicemailtipo" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="codiceistanza" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="codicemovimento" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "MailtipoRequest")
public class MailtipoRequest {

    @XmlElement(required = true)
    protected String token;
    protected int codicemailtipo;
    @XmlElement(required = true, type = Integer.class, nillable = true)
    protected Integer codiceistanza;
    @XmlElement(required = true, type = Integer.class, nillable = true)
    protected Integer codicemovimento;

    /**
     * Gets the value of the token property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToken() {
        return token;
    }

    /**
     * Sets the value of the token property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToken(String value) {
        this.token = value;
    }

    /**
     * Gets the value of the codicemailtipo property.
     * 
     */
    public int getCodicemailtipo() {
        return codicemailtipo;
    }

    /**
     * Sets the value of the codicemailtipo property.
     * 
     */
    public void setCodicemailtipo(int value) {
        this.codicemailtipo = value;
    }

    /**
     * Gets the value of the codiceistanza property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCodiceistanza() {
        return codiceistanza;
    }

    /**
     * Sets the value of the codiceistanza property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCodiceistanza(Integer value) {
        this.codiceistanza = value;
    }

    /**
     * Gets the value of the codicemovimento property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCodicemovimento() {
        return codicemovimento;
    }

    /**
     * Sets the value of the codicemovimento property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCodicemovimento(Integer value) {
        this.codicemovimento = value;
    }

}
