CREATE TABLE MOVIMENTI_IO_COMUNICAZIONI (IDCOMUNE VARCHAR(6) NOT NULL, CODICECOMUNE VARCHAR(5) NOT NULL, SOFTWARE VARCHAR(2) NOT NULL, CODICEMOVIMENTO DECIMAL(8,0) NOT NULL, CODICEANAGRAFE DECIMAL(6,0) NOT NULL, MESSAGE_ID VARCHAR(36) NOT NULL, FISCAL_CODE VARCHAR(16) NOT NULL, DATAINVIO DATETIME NOT NULL, SENDER_ALLOWED DECIMAL(1,0) NOT NULL, CREATED_AT TIMESTAMP, NOTIFICATION_STATUS VARCHAR(50), NOTIFICATION_WEBHOOK VARCHAR(50), NOTIFICATION_EMAIL VARCHAR(50), ERRORE VARCHAR(4000), FLAG_COMPLETATO DECIMAL(1,0) NOT NULL) ENGINE=INNODB DEFAULT CHARSET=UTF8;
ALTER TABLE MOVIMENTI_IO_COMUNICAZIONI ADD CONSTRAINT PK_MOVIMENTI_IO_COMUNICAZIONI PRIMARY KEY(IDCOMUNE,CODICECOMUNE,SOFTWARE,CODICEMOVIMENTO,CODICEANAGRAFE);
ALTER TABLE MOVIMENTI_IO_COMUNICAZIONI ADD CONSTRAINT FK_MOVIMENTIIOCOM_MOVIMENTI FOREIGN KEY(IDCOMUNE,CODICEMOVIMENTO) REFERENCES MOVIMENTI (IDCOMUNE, CODICEMOVIMENTO);
ALTER TABLE MOVIMENTI_IO_COMUNICAZIONI ADD CONSTRAINT FK_MOVIMENTIIOCOM_ANAGRAFE FOREIGN KEY(IDCOMUNE,CODICEANAGRAFE) REFERENCES ANAGRAFE (IDCOMUNE, CODICEANAGRAFE);
ALTER TABLE MOVIMENTI_IO_COMUNICAZIONI ADD CONSTRAINT FK_MOVIMENTIIOCOM_COMUNI FOREIGN KEY(CODICECOMUNE) REFERENCES COMUNI (CODICECOMUNE);
ALTER TABLE MOVIMENTI_IO_COMUNICAZIONI ADD CONSTRAINT FK_MOVIMENTIIOCOM_SOFTWARE FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE (CODICE);
CREATE UNIQUE INDEX IDX_MOVIMENTIIOCOM_001 ON MOVIMENTI_IO_COMUNICAZIONI (MESSAGE_ID ASC);
CREATE INDEX IDX_MOVIMENTIIOCOM_002 ON MOVIMENTI_IO_COMUNICAZIONI(IDCOMUNE, CODICEMOVIMENTO);
CREATE INDEX IDX_MOVIMENTIIOCOM_003 ON MOVIMENTI_IO_COMUNICAZIONI(IDCOMUNE, CODICEANAGRAFE);
CREATE INDEX IDX_MOVIMENTIIOCOM_004 ON MOVIMENTI_IO_COMUNICAZIONI(CODICECOMUNE);
CREATE INDEX IDX_MOVIMENTIIOCOM_005 ON MOVIMENTI_IO_COMUNICAZIONI(SOFTWARE);
CREATE INDEX IDX_MOVIMENTIIOCOM_006 ON MOVIMENTI_IO_COMUNICAZIONI (FLAG_COMPLETATO ASC);
CREATE INDEX IDX_MOVIMENTI_IOAPP ON MOVIMENTI (PUBBLICA DESC, DATAPROTOCOLLO DESC);

CREATE TABLE CONFIGURAZIONE_APP_IO (
    IDCOMUNE VARCHAR(6) NOT NULL,
    CODICECOMUNE VARCHAR(5) NOT NULL,
    SOFTWARE VARCHAR(2) NOT NULL,
    URL_PORTALE_SERVIZI VARCHAR(200) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

ALTER TABLE CONFIGURAZIONE_APP_IO ADD CONSTRAINT PK_CONFIGURAZIONE_APP_IO PRIMARY KEY(IDCOMUNE,CODICECOMUNE,SOFTWARE);
ALTER TABLE CONFIGURAZIONE_APP_IO ADD CONSTRAINT FK_CONFIGURAZIONEAPPIO_COMUNI FOREIGN KEY(CODICECOMUNE) REFERENCES COMUNI (CODICECOMUNE);
ALTER TABLE CONFIGURAZIONE_APP_IO ADD CONSTRAINT FK_CONFIGURAZIONEAPPIO_SOFT FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE (CODICE);
CREATE INDEX IDX_CONFIGURAZIONEAPPIO_001 ON CONFIGURAZIONE_APP_IO(CODICECOMUNE);
CREATE INDEX IDX_CONFIGURAZIONEAPPIO_002 ON CONFIGURAZIONE_APP_IO(SOFTWARE);

DROP INDEX PAY_POSDEB_UIDX on PAY_POSIZIONI_DEBITORIE;
CREATE UNIQUE INDEX PAY_POSDEB_UIDX ON PAY_POSIZIONI_DEBITORIE(IDCOMUNE,IUV);

ALTER TABLE CONCESSIONICAUSALI ADD FLAG_CAUSALI_AFFITTO NUMERIC(1,0) DEFAULT 0;
ALTER TABLE AUTORIZZAZIONI ADD DATA_FINE_AFFITTO DATETIME;
ALTER TABLE AUTORIZZAZIONI_SUBENTRI ADD DATA_FINE_AFFITTO DATETIME;

ALTER TABLE PAY_CONNECTOR_WS_ENDPOINT MODIFY PASSWORD VARCHAR(70);
ALTER TABLE DECODIFICHE MODIFY TABELLA VARCHAR(100);


ALTER TABLE DECODIFICHE ADD ID NUMERIC(10,0);

UPDATE DECODIFICHE JOIN (SELECT @seq_val := 0) r SET id=@seq_val:=@seq_val+1 WHERE ID IS NULL;