# Comment out the Log4J listener in web.xml to activate Log4J.
log4j.rootLogger=WARN, logfile

log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d %p [%c] %nAREA RISERVATA - <%m>%n

log4j.appender.logfile=org.apache.log4j.RollingFileAppender
log4j.appender.logfile.File=${catalina.base}/logs/gp-areariservata.log
log4j.appender.logfile.MaxFileSize=1024KB
log4j.appender.logfile.MaxBackupIndex=10
log4j.appender.logfile.layout=org.apache.log4j.PatternLayout
log4j.appender.logfile.layout.ConversionPattern=%d %p [%c] - %m%n


log4j.appender.auditsufileweblogfile=org.apache.log4j.DailyRollingFileAppender
log4j.appender.auditsufileweblogfile.File=${catalina.base}/logs/audit/gp-areariservata-audit-web.log
log4j.appender.auditsufileweblogfile.DatePattern='.'yyyy-MM-dd-HH'.txt'
#log4j.appender.auditsufileweblogfile.MaxBackupIndex=20
#log4j.appender.auditsufileweblogfile.MaxFileSize=10240KB
log4j.appender.auditsufileweblogfile.layout=org.apache.log4j.PatternLayout
log4j.appender.auditsufileweblogfile.layout.ConversionPattern=%d %n%m%n

log4j.appender.auditsufileserviceerrorlogfile=org.apache.log4j.DailyRollingFileAppender
log4j.appender.auditsufileserviceerrorlogfile.File=${catalina.base}/logs/audit/gp-areariservata-audit-servicerror.log
log4j.appender.auditsufileserviceerrorlogfile.DatePattern='.'yyyy-MM-dd'.txt'
#log4j.appender.auditsufileserviceerrorlogfile.MaxBackupIndex=20
#log4j.appender.auditsufileserviceerrorlogfile.MaxFileSize=10240KB
log4j.appender.auditsufileserviceerrorlogfile.layout=org.apache.log4j.PatternLayout
log4j.appender.auditsufileserviceerrorlogfile.layout.ConversionPattern=%d %n%m%n

log4j.appender.loggermodificheistanze=org.apache.log4j.DailyRollingFileAppender
log4j.appender.loggermodificheistanze.File=${catalina.base}/logs/audit/gp-areariservata-modifiche-istanze.log
log4j.appender.loggermodificheistanze.DatePattern='.'yyyy-MM-dd'.txt'
#log4j.appender.loggermodificheistanze.MaxBackupIndex=20
#log4j.appender.loggermodificheistanze.MaxFileSize=10240KB
log4j.appender.loggermodificheistanze.layout=org.apache.log4j.PatternLayout
log4j.appender.loggermodificheistanze.layout.ConversionPattern=%d %n%m%n

log4j.appender.loggerarchivibackoffice=org.apache.log4j.DailyRollingFileAppender
log4j.appender.loggerarchivibackoffice.File=${catalina.base}/logs/audit/gp-areariservata-archivi.log
log4j.appender.loggerarchivibackoffice.DatePattern='.'yyyy-MM-dd'.txt'
#log4j.appender.loggerarchivibackoffice.MaxBackupIndex=20
#log4j.appender.loggerarchivibackoffice.MaxFileSize=10240KB
log4j.appender.loggerarchivibackoffice.layout=org.apache.log4j.PatternLayout
log4j.appender.loggerarchivibackoffice.layout.ConversionPattern=%d %n%m%n

log4j.appender.bollettazione_appender=org.apache.log4j.DailyRollingFileAppender
log4j.appender.bollettazione_appender.File=${catalina.base}/logs/audit/gp-backoffice-bollettazione.log
log4j.appender.bollettazione_appender.DatePattern='.'yyyy-MM-dd'.txt'
log4j.appender.bollettazione_appender.layout=org.apache.log4j.PatternLayout
log4j.appender.bollettazione_appender.layout.ConversionPattern=%d %n%m%n

log4j.appender.oggetti_appender=org.apache.log4j.DailyRollingFileAppender
log4j.appender.oggetti_appender.File=${catalina.base}/logs/audit/gp-areariservata-oggetti.log
log4j.appender.oggetti_appender.DatePattern='.'yyyy-MM-dd'.txt'
log4j.appender.oggetti_appender.layout=org.apache.log4j.PatternLayout
log4j.appender.oggetti_appender.layout.ConversionPattern=%d %n%m%n

log4j.appender.abbonamento_appender=org.apache.log4j.DailyRollingFileAppender
log4j.appender.abbonamento_appender.File=${catalina.base}/logs/audit/gp-areariservata-abbonamento.log
log4j.appender.abbonamento_appender.DatePattern='.'yyyy-MM-dd'.txt'
log4j.appender.abbonamento_appender.layout=org.apache.log4j.PatternLayout
log4j.appender.abbonamento_appender.layout.ConversionPattern=%d %n%m%n

log4j.appender.qrcode_appender=org.apache.log4j.DailyRollingFileAppender
log4j.appender.qrcode_appender.File=${catalina.base}/logs/audit/gp-areariservata-qrcode.log
log4j.appender.qrcode_appender.DatePattern='.'yyyy-MM-dd'.txt'
log4j.appender.qrcode_appender.layout=org.apache.log4j.PatternLayout
log4j.appender.qrcode_appender.layout.ConversionPattern=%d %n%m%n

log4j.logger.it.gruppoinit.sigepro.cart=WARN
log4j.logger.it.gruppoinit.pal.gp.areariservata.cartfacct=WARN
log4j.logger.it.gruppoinit.pal.gp.areariservata.filter=WARN
log4j.logger.it.gruppoinit.pal.gp.areariservata.filter.TokenAuthenticationFilter=INFO
log4j.logger.it.gruppoinit.pal.gp.areariservata.filter.IdComuneFilter=INFO
log4j.logger.it.gruppoinit.pal.gp.areariservata.filter.RegistrationFilter=INFO
log4j.logger.it.gruppoinit.pal.gp.areariservata.web=WARN
log4j.logger.it.gruppoinit.pal.gp.areariservata.web.nuovaistanza=WARN
#lasciare a INFO per vedere i passaggi dell'invio pratica
log4j.logger.it.gruppoinit.pal.gp.areariservata.web.nuovaistanza.NuovaIstanzaRiepilogoController=WARN
log4j.logger.it.gruppoinit.pal.gp.areariservata.web.FileController=WARN
log4j.logger.it.gruppoinit.pal.gp.areariservata.web.handler=WARN
log4j.logger.it.gruppoinit.pal.gp.core.service.impl=WARN
log4j.logger.it.lineacomune.ws=INFO
#TRACE visualizza xml domanda
log4j.logger.it.gruppoinit.pal.gp.areariservata.service.impl.NuovaIstanzaServiceImpl=WARN
log4j.logger.it.gruppoinit.pal.gp.areariservata.service.impl.FirmaDigitaleServiceImpl=WARN
log4j.logger.it.gruppoinit.pal.gp.areariservata.service.impl=WARN
log4j.logger.org.apache=WARN
log4j.logger.org.springframework=WARN
log4j.logger.org.hibernate=WARN
log4j.logger.org.apache.cxf=WARN
#log delle chiamate soap(INFO=on,WARN=off)
log4j.logger.org.apache.cxf.services=WARN

## impostare a DEBUG per visualizzare le query ed i parametri di binding(impostare type a TRACE per visualizzare anche i parametri di ritorno)
log4j.logger.org.hibernate.SQL=WARN
log4j.logger.org.hibernate.type=WARN
#log4j.logger.org.hibernate.cache=WARN
#log4j.logger.org.hibernate.jdbc=WARN
#log4j.logger.org.hibernate.type.AnyType=WARN
#log4j.logger.org.hibernate.type.BigDecimalType=WARN
#log4j.logger.org.hibernate.type.BigIntegerType=WARN
#log4j.logger.org.hibernate.type.BooleanType=WARN
#log4j.logger.org.hibernate.type.ByteType=WARN
#log4j.logger.org.hibernate.type.CalendarDateType=WARN
#log4j.logger.org.hibernate.type.CalendarType=WARN
#log4j.logger.org.hibernate.type.CharacterType=WARN
#log4j.logger.org.hibernate.type.DateType=WARN
#log4j.logger.org.hibernate.type.DbTimestampType=WARN
#log4j.logger.org.hibernate.type.DoubleType=WARN
#log4j.logger.org.hibernate.type.FloatType=WARN
#log4j.logger.org.hibernate.type.IdentifierBagType=WARN
#log4j.logger.org.hibernate.type.IntegerType=WARN
#log4j.logger.org.hibernate.type.LongType=WARN
#log4j.logger.org.hibernate.type.NullableType=WARN
#log4j.logger.org.hibernate.type.NumericBooleanType=WARN
#log4j.logger.org.hibernate.type.ShortType=WARN
#log4j.logger.org.hibernate.type.StringClobType=WARN
#log4j.logger.org.hibernate.type.StringType=WARN
#log4j.logger.org.hibernate.type.TextType=WARN
#log4j.logger.org.hibernate.type.TimestampType=WARN
#log4j.logger.org.hibernate.type.TimeType=WARN

## c3p0 logger
#log4j.logger.com.mchange=WARN

#impostazioni di log per AuditingSuFile per il layer web
log4j.logger.it.gruppoinit.auditing.web_activity=WARN, auditsufileweblogfile
log4j.additivity.it.gruppoinit.auditing.web_activity=false

#impostazioni di log per AuditingSuFile per gli errori dei services
log4j.logger.it.gruppoinit.auditing.service_errors=WARN, auditsufileserviceerrorlogfile
log4j.additivity.it.gruppoinit.auditing.service_errors=false

#impostazioni di log per le cancellazioni dei dati dell'istanza
log4j.logger.it.gruppoinit.auditing.dml_activity=DEBUG, loggermodificheistanze
log4j.additivity.it.gruppoinit.auditing.dml_activity=false

#impostazioni di log per tracciare le operazioni di del ws archivibackoffice
log4j.logger.it.gruppoinit.pal.gp.core.utils.LoggerArchiviBackoffice=INFO, loggerarchivibackoffice
log4j.additivity.it.gruppoinit.pal.gp.core.utils.LoggerArchiviBackoffice=false

#impostazioni di log per tracciare il processo di bollettazione 
log4j.logger.bollettazione=INFO, bollettazione_appender
log4j.additivity.bollettazione=false

#impostazioni di log per tracciare quanto avviene sugli oggetti
log4j.logger.features.oggetti=INFO, oggetti_appender
log4j.additivity.features.oggetti=false

#impostazioni di log per tracciare le attività sugli abbonamenti
log4j.logger.abbonamento = INFO, abbonamento_appender
log4j.additivity.abbonamento=false

#impostazioni di log per tracciare la stampigliatura del QRcode
log4j.logger.qrcode=INFO, qrcode_appender
log4j.additivity.qrcode=false
