package it.gruppoinit.pal.gp.backoffice.definitions.mailtipo;

import it.gruppoinit.pal.gp.backoffice.schemas.messages.mailtipo.MailtipoFrontendRequest;
import it.gruppoinit.pal.gp.backoffice.schemas.messages.mailtipo.MailtipoResponse;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.1 2012-06-28T10:26:43.232+02:00 Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://gruppoinit.it/sigepro/definitions/mailtipo", name = "Mailtipo")
@XmlSeeAlso({ it.gruppoinit.pal.gp.backoffice.schemas.messages.mailtipo.ObjectFactory.class })
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Mailtipo {

    @WebResult(name = "MailtipoResponse", targetNamespace = "http://gruppoinit.it/sigepro/schemas/messages/mailtipo", partName = "MailtipoResponse")
    @WebMethod(operationName = "Mailtipo", action = "replaceOggettoCorpo")
    public it.gruppoinit.pal.gp.backoffice.schemas.messages.mailtipo.MailtipoResponse mailtipo(
	    @WebParam(partName = "MailtipoRequest", name = "MailtipoRequest", targetNamespace = "http://gruppoinit.it/sigepro/schemas/messages/mailtipo") it.gruppoinit.pal.gp.backoffice.schemas.messages.mailtipo.MailtipoRequest mailtipoRequest);

    @WebResult(name = "MailtipoResponse", targetNamespace = "http://gruppoinit.it/sigepro/schemas/messages/mailtipo", partName = "MailtipoResponse")
    @WebMethod(operationName = "MailtipoFrontend", action = "mailtipoFrontendRequest")
    public MailtipoResponse mailtipoFrontend(
	    @WebParam(partName = "MailtipoFrontendRequest", name = "MailtipoFrontendRequest", targetNamespace = "http://gruppoinit.it/sigepro/schemas/messages/mailtipo") MailtipoFrontendRequest mailtipoFrontendRequest);


    @WebResult(name = "MailtipoResponseProtokol", targetNamespace = "http://gruppoinit.it/sigepro/schemas/messages/mailtipo", partName = "MailtipoResponseProtokol")
    @WebMethod(operationName = "MailtipoProtokol", action = "replaceOggettoCorpoProtokol")
    public it.gruppoinit.pal.gp.backoffice.schemas.messages.mailtipo.MailtipoResponseProtokol mailtipoProtokol(
	    @WebParam(partName = "MailtipoRequest", name = "MailtipoRequest", targetNamespace = "http://gruppoinit.it/sigepro/schemas/messages/mailtipo") it.gruppoinit.pal.gp.backoffice.schemas.messages.mailtipo.MailtipoRequestProtokol mailtipoRequestProtokol);


}
