<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:ax24="http://model.repertorio.webred.it/xsd" 
	xmlns:ax22="http://repertorio.webred.it/xsd" 
	attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://ws.repertorio.webred.it" xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	xmlns:ax23="http://model.repertorio.webred.it/xsd" xmlns:ax21="http://repertorio.webred.it/xsd">
	<xs:import schemaLocation="repertorioWSversion.xsd" namespace="http://model.repertorio.webred.it/xsd"/>
	<xs:import schemaLocation="repertorioWSexception.xsd" namespace="http://repertorio.webred.it/xsd"/>
	<xs:element name="RepertorioWSRepositoryManagerException">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" name="RepositoryManagerException" nillable="true" type="ax21:RepositoryManagerException"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="uploadProcedimento">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" name="bustaXML" nillable="true" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="uploadProcedimentoResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" name="return" type="xs:boolean"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="getVersioneRemota">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" name="servizio" nillable="true" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="getVersioneRemotaResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" minOccurs="0" name="return" nillable="true" type="ax23:RepositoryVersion"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="getVersione">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" name="servizio" nillable="true" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="getVersioneResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" minOccurs="0" name="return" nillable="true" type="ax23:RepositoryVersion"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="getUltimaVersione">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" name="servizio" nillable="true" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="getUltimaVersioneResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" name="return" nillable="true" type="ax23:RepositoryVersion"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="downloadRepositoryLocale">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" name="servizio" nillable="true" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="downloadRepositoryLocaleResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" name="return" nillable="true" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="downloadRepositoryByVersLocale">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" name="repVers" nillable="true" type="ax23:RepositoryVersion"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="downloadRepositoryByVersLocaleResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" name="return" nillable="true" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="downloadRepositoryByVers">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" name="repVers" nillable="true" type="ax23:RepositoryVersion"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="downloadRepositoryByVersResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" name="return" nillable="true" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="downloadRepository">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" name="servizio" nillable="true" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="downloadRepositoryResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" name="return" nillable="true" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="creaNuovoRepository">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" name="bustaXML" nillable="true" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="creaNuovoRepositoryResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" name="return" type="xs:boolean"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>