
ALTER TABLE MOVIMENTI_ZIP_LOGICO_TESTATA ADD CODICEOGGETTO_DOC_ALL NUMBER(10,0);
ALTER TABLE MOVIMENTI_ZIP_LOGICO_TESTATA ADD CONSTRAINT FK_MOVZIPLOGT_OGGETTI FOREIGN KEY(IDCOMUNE,CODICEOGGETTO_DOC_ALL)REFERENCES OGGETTI(IDCOMUNE,CODICEOGGETTO);

ALTER TABLE ESPORTAZIONI ADD SOFTWARE VARCHAR2(2 char);
ALTER TABLE ESPORTAZIONI ADD CONSTRAINT FK_ESPORTAZIONI_SOFTWARE FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);


UPDATE (
    SELECT      movimentiallegati.codiceoggetto as codoggmovallegati,
                movimenti_zip_logico.codiceoggetto as codoggziplogicoall
          FROM movimenti_zip_logico
            INNER JOIN movimentiallegati ON 
            movimentiallegati.idcomune=movimenti_zip_logico.idcomune AND
            movimentiallegati.id=movimenti_zip_logico.FK_IDMOVIMENTIALLEGATI 
            where 
            movimenti_zip_logico.codiceoggetto IS NULL AND movimentiallegati.codiceoggetto IS NOT NULL AND movimenti_zip_logico.FK_IDMOVIMENTIALLEGATI IS NOT NULL
         )
   SET codoggziplogicoall = codoggmovallegati;

CREATE TABLE SEGNAPOSTI(SEGNAPOSTO VARCHAR2(64 CHAR) NOT NULL, TEMPLATEBASE VARCHAR2(4000 CHAR) NOT NULL, TEMPLATEBASERTF VARCHAR2(4000 CHAR) NOT NULL);
ALTER TABLE SEGNAPOSTI ADD CONSTRAINT SEGNAPOSTI_PK PRIMARY KEY(SEGNAPOSTO);
CREATE TABLE SEGNAPOSTIPERSONALIZZATI(IDCOMUNE VARCHAR2(6 CHAR) NOT NULL, SEGNAPOSTO VARCHAR2(64 CHAR) NOT NULL, SOFTWARE VARCHAR2(2 CHAR) NOT NULL, TEMPLATE VARCHAR2(4000 CHAR) NOT NULL, TEMPLATERTF VARCHAR2(4000 CHAR) NOT NULL);
ALTER TABLE SEGNAPOSTIPERSONALIZZATI ADD CONSTRAINT SEGNAPOSTIPERSONALIZZATI_PK PRIMARY KEY(IDCOMUNE,SEGNAPOSTO,SOFTWARE);
ALTER TABLE SEGNAPOSTIPERSONALIZZATI ADD CONSTRAINT FK_SEGNAPOSTI FOREIGN KEY(SEGNAPOSTO) REFERENCES SEGNAPOSTI(SEGNAPOSTO);
ALTER TABLE SEGNAPOSTIPERSONALIZZATI ADD CONSTRAINT FK_SEGNAPOSTI_SOFTWARE FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);
 
 
