DELETE FROM INTERESSI_LEGALI;

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (1,TO_DATE('21-04-1942','dd-MM-yyyy'),TO_DATE('15-12-1990','dd-MM-yyyy'),5,null);

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (2,TO_DATE('16-12-1990','dd-MM-yyyy'),TO_DATE('31-12-1996','dd-MM-yyyy'),10,'Legge 26 novembre 1990, n. 353'); 

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (3,TO_DATE('01-01-1997','dd-MM-yyyy'),TO_DATE('31-12-1998','dd-MM-yyyy'),5,'Legge 23 dicembre 1996, n. 662'); 

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (4,TO_DATE('01-01-1999','dd-MM-yyyy'),TO_DATE('31-12-2000','dd-MM-yyyy'),2.5,'D.M. 10 dicembre 1998');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (5,TO_DATE('01-01-2001','dd-MM-yyyy'),TO_DATE('31-12-2001','dd-MM-yyyy'),3.5,'D.M. 11 dicembre 2000');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (6,TO_DATE('01-01-2002','dd-MM-yyyy'),TO_DATE('31-12-2003','dd-MM-yyyy'),3,'D.M. 11 dicembre 2001');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (7,TO_DATE('01-01-2004','dd-MM-yyyy'),TO_DATE('31-12-2007','dd-MM-yyyy'),2.5,'D.M. 1 dicembre 2003');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (8,TO_DATE('01-01-2008','dd-MM-yyyy'),TO_DATE('31-12-2009','dd-MM-yyyy'),3,'D.M. 12 dicembre 2007');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (9,TO_DATE('01-01-2010','dd-MM-yyyy'),TO_DATE('31-12-2010','dd-MM-yyyy'),1,'D.M. 4 dicembre 2009');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (10,TO_DATE('01-01-2011','dd-MM-yyyy'),TO_DATE('31-12-2011','dd-MM-yyyy'),1.5,'D.M. 07 Dicembre 2010');

insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (11,TO_DATE('01-01-2012','dd-MM-yyyy'),TO_DATE('31-12-2013','dd-MM-yyyy'),2.5,'DM 12 dicembre 2011'); 

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (12,to_date('01-01-2014','dd-MM-yyyy'),TO_DATE('31-12-2014','dd-MM-yyyy'),1,'Dm Economia 13.12.2013');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (13,to_date('01-01-2015','dd-MM-yyyy'),TO_DATE('31-12-2015','dd-MM-yyyy'),0.5,'Dm Economia 11.12.2014'); 

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (14,to_date('01-01-2016','dd-MM-yyyy'),to_date('31-12-2016','dd-MM-yyyy'),0.2,'Dm Economia 11.12.2015');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (15,to_date('01-01-2017','dd-MM-yyyy'),to_date('31-12-2017','dd-MM-yyyy'),0.1,'Dm economia e finanze 07/12/2016,G.U.14/12/2016');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (16,to_date('01-01-2018','dd-MM-yyyy'),to_date('31-12-2018','dd-MM-yyyy'),0.3,'Dm economia e finanze 13/12/2017,G.U.15/12/2017');


Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (17,to_date('01-01-2019','dd-MM-yyyy'),to_date('31-12-2019','dd-MM-yyyy'),0.8,'Dm economia 12/12/2018,G.U. 302 31/12/2018');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (18,to_date('01-01-2020','dd-MM-yyyy'),to_date('31-12-2020','dd-MM-yyyy'),0.05,'Dm economia Dm Economia 12/12/2019');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (19,to_date('01-01-2021','dd-MM-yyyy'),to_date('31-12-2021','dd-MM-yyyy'),0.01,'Dm Economia 11/12/2020');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (20,to_date('01-01-2022','dd-MM-yyyy'),null,1.25,'Dm Economia 13/12/2021');


CREATE TABLE DYN2_MASSIVE(IDCOMUNE VARCHAR2(6 CHAR) NOT NULL, ID NUMBER(10,0) NOT NULL, DESCRIZIONE VARCHAR2(100 CHAR) NOT NULL, DATA_INIZIO DATE NOT NULL, DATA_FINE DATE );
ALTER TABLE DYN2_MASSIVE ADD CONSTRAINT PK_DYN2MASSIVE PRIMARY KEY (IDCOMUNE,ID);
CREATE INDEX IDX_DYN2MASSIVE_001 ON DYN2_MASSIVE (IDCOMUNE, DATA_INIZIO);
CREATE TABLE DYN2_MASSIVEFILTRI(IDCOMUNE VARCHAR2(6 CHAR) NOT NULL, FKIDELABORAZIONE NUMBER(10,0) NOT NULL, FILTRO VARCHAR2(50 CHAR) NOT NULL, VALORE VARCHAR2(4000 CHAR) NOT NULL);
ALTER TABLE DYN2_MASSIVEFILTRI ADD CONSTRAINT PK_DYN2MASSIVEFILTRI PRIMARY KEY (IDCOMUNE,FKIDELABORAZIONE,FILTRO);
ALTER TABLE DYN2_MASSIVEFILTRI ADD CONSTRAINT FK_DYN2FILTRI_MASSIVE FOREIGN KEY (IDCOMUNE,FKIDELABORAZIONE) REFERENCES DYN2_MASSIVE(IDCOMUNE,ID);
CREATE TABLE DYN2_MASSIVESCHEDE(IDCOMUNE VARCHAR2(6 CHAR) NOT NULL, FKIDELABORAZIONE NUMBER(10,0) NOT NULL, FK_D2MT_ID NUMBER(10,0) NOT NULL, ORDINE NUMBER(2,0) NOT NULL );
ALTER TABLE DYN2_MASSIVESCHEDE ADD CONSTRAINT PK_DYN2MASSIVESCHEDE PRIMARY KEY (IDCOMUNE,FKIDELABORAZIONE,FK_D2MT_ID);
ALTER TABLE DYN2_MASSIVESCHEDE ADD CONSTRAINT FK_DYN2SCHEDE_MASSIVE FOREIGN KEY (IDCOMUNE,FKIDELABORAZIONE) REFERENCES DYN2_MASSIVE(IDCOMUNE,ID);
ALTER TABLE DYN2_MASSIVESCHEDE ADD CONSTRAINT FK_DYN2SCHEDE_SCHEDE FOREIGN KEY (IDCOMUNE,FK_D2MT_ID) REFERENCES DYN2_MODELLIT(IDCOMUNE,ID);
CREATE INDEX IDX_DYN2MASSIVESCHEDE_001 ON DYN2_MASSIVESCHEDE (IDCOMUNE, FKIDELABORAZIONE, ORDINE);
CREATE INDEX IDX_DYN2MASSIVESCHEDE_002 ON DYN2_MASSIVESCHEDE (IDCOMUNE, FK_D2MT_ID);
CREATE TABLE DYN2_MASSIVEISTANZE(IDCOMUNE VARCHAR2(6 CHAR) NOT NULL, FKIDELABORAZIONE NUMBER(10,0) NOT NULL, CODICEISTANZA NUMBER(6,0) NOT NULL, STATOESECUZIONE VARCHAR2 (50 CHAR) NOT NULL, LOG VARCHAR2(4000 CHAR) );
ALTER TABLE DYN2_MASSIVEISTANZE ADD CONSTRAINT PK_DYN2MASSIVEISTANZE PRIMARY KEY (IDCOMUNE,FKIDELABORAZIONE,CODICEISTANZA);
ALTER TABLE DYN2_MASSIVEISTANZE ADD CONSTRAINT FK_DYN2ISTANZE_MASSIVE FOREIGN KEY (IDCOMUNE,FKIDELABORAZIONE) REFERENCES DYN2_MASSIVE(IDCOMUNE,ID);
ALTER TABLE DYN2_MASSIVEISTANZE ADD CONSTRAINT FK_DYN2ISTANZE_ISTANZE FOREIGN KEY (IDCOMUNE,CODICEISTANZA) REFERENCES ISTANZE(IDCOMUNE,CODICEISTANZA);
CREATE INDEX IDX_DYN2MASSIVEISTANZE_001 ON DYN2_MASSIVEISTANZE (IDCOMUNE, FKIDELABORAZIONE, STATOESECUZIONE);
CREATE INDEX IDX_DYN2MASSIVEISTANZE_002 ON DYN2_MASSIVEISTANZE (IDCOMUNE, CODICEISTANZA);

ALTER TABLE DYN2_MASSIVE MODIFY DATA_INIZIO DATE NULL;
ALTER TABLE DYN2_MASSIVE ADD SOFTWARE VARCHAR2(2 CHAR) NOT NULL;

ALTER TABLE COMMISSIONIEDILIZIE_R MODIFY ORDINE NUMBER(6,0);


CREATE TABLE BOLL_CFG_TIPO_RATE(IDCOMUNE VARCHAR2(6 CHAR) NOT NULL, ID NUMBER(10,0) NOT NULL, FK_BOLLCFGTIPO_ID NUMBER(4,0) NOT NULL, FK_RANGERATE NUMBER(4,0) NOT NULL);
ALTER TABLE BOLL_CFG_TIPO_RATE ADD CONSTRAINT PK_BLCFGRATE PRIMARY KEY (IDCOMUNE,ID);
ALTER TABLE BOLL_CFG_TIPO_RATE ADD CONSTRAINT FK_BLCFGRATE_BLCFGTIPO FOREIGN KEY (IDCOMUNE,FK_BOLLCFGTIPO_ID) REFERENCES BOLL_CFG_TIPO(IDCOMUNE,ID);
ALTER TABLE BOLL_CFG_TIPO_RATE ADD CONSTRAINT FK_BLCFGRATE_RANGERATE FOREIGN KEY (IDCOMUNE,FK_RANGERATE) REFERENCES RANGE_RATEIZZAZIONI(IDCOMUNE,ID);
CREATE INDEX IDX_BLCFGRATE_001 ON BOLL_CFG_TIPO_RATE (IDCOMUNE, FK_BOLLCFGTIPO_ID);
CREATE INDEX IDX_BLCFGRATE_002 ON BOLL_CFG_TIPO_RATE (IDCOMUNE, FK_RANGERATE);
CREATE TABLE BOLL_GEST_DETT_RATE(IDCOMUNE VARCHAR2(6 CHAR) NOT NULL, ID NUMBER(10,0) NOT NULL, FK_BOLLGESTDET_ID NUMBER(4,0) NOT NULL, NUMERORATA NUMBER(2,0) NOT NULL, SCADENZA DATE NOT NULL, FK_POSDEBDETTAGLIO_ID NUMBER(10,0));
ALTER TABLE BOLL_GEST_DETT_RATE ADD CONSTRAINT PK_BLDETRATE PRIMARY KEY (IDCOMUNE,ID);
ALTER TABLE BOLL_GEST_DETT_RATE ADD CONSTRAINT FK_BLDETRATE_BOLLGESTDET FOREIGN KEY (IDCOMUNE,FK_BOLLGESTDET_ID) REFERENCES BOLL_GEST_DETTAGLIO(IDCOMUNE,ID);
ALTER TABLE BOLL_GEST_DETT_RATE ADD CONSTRAINT FK_BLDETRATE_POSDEBDETTAGLIO FOREIGN KEY (IDCOMUNE,FK_POSDEBDETTAGLIO_ID) REFERENCES DETT_POSIZIONE_DEBITORIA(IDCOMUNE,ID);
CREATE INDEX IDX_BLDETRATE_001 ON BOLL_GEST_DETT_RATE (IDCOMUNE, FK_BOLLGESTDET_ID);
CREATE INDEX IDX_BLDETRATE_002 ON BOLL_GEST_DETT_RATE (IDCOMUNE, FK_POSDEBDETTAGLIO_ID);

ALTER TABLE ONERITIPIRATEIZZAZIONE ADD SCADENZEPERIODI VARCHAR2(60 CHAR);

ALTER TABLE ONERITIPIRATEIZZAZIONE MODIFY FREQUENZARATE VARCHAR2(60 CHAR) NULL;

ALTER TABLE BOLL_CFG_TIPO ADD SCADENZEPERIODI VARCHAR2(60 CHAR) NULL;

ALTER TABLE BOLL_GEST_DETT_RATE ADD IMPORTO_TOTALE NUMBER(11,2) NOT NULL;
