/* PORTATO IN VBG_04_CREAZIONE_INDICI.SQL
Alter table LEGGI ADD CONSTRAINT FK_LEGGILEGGITIPI FOREIGN KEY(IDCOMUNE,LE_FKLTID) REFERENCES LEGGITIPI(IDCOMUNE,LT_ID)
GO
COMMIT
GO
 */
SET IMPLICIT_TRANSACTIONS OFF
GO
alter table LEGGI ALTER COLUMN LE_ID NUMERIC(10,0)
GO
COMMIT
GO
alter table LEGGITIPI ALTER COLUMN LT_ID NUMERIC(10,0)
GO
COMMIT
GO
alter table DYN2_CAMPI ALTER COLUMN ID NUMERIC(10,0)
GO
COMMIT
GO
alter table DYN2_CAMPIPROPRIETA ALTER COLUMN FK_D2C_ID NUMERIC(10,0)
GO
COMMIT
GO
alter table DYN2_MODELLID ALTER COLUMN ID NUMERIC(10,0)
GO
COMMIT
GO
alter table DYN2_MODELLIDTESTI ALTER COLUMN ID NUMERIC(10,0)
GO
COMMIT
GO
alter table DYN2_MODELLIT ALTER COLUMN ID NUMERIC(10,0)
GO
COMMIT
GO
alter table INVENTARIOPROCDYN2MODELLIT ALTER COLUMN CODICEINVENTARIO NUMERIC(10,0)
GO
COMMIT
GO
alter table INVENTARIOPROCDYN2MODELLIT ALTER COLUMN FK_D2MT_ID NUMERIC(10,0)
GO
COMMIT
GO
alter table INVENTARIOPROCEDIMENTI ALTER COLUMN CODICEINVENTARIO NUMERIC(10,0)
GO
COMMIT
GO
alter table INVENTARIOPROCEDIMENTIINCOMP ALTER COLUMN ID NUMERIC(10,0)
GO
COMMIT
GO
alter table INVENTARIOPROCEDIMENTIONERI ALTER COLUMN ID NUMERIC(10,0)
GO
COMMIT
GO
alter table ALBEROPROC_ATECO ALTER COLUMN FK_SCID NUMERIC(10,0)
GO
COMMIT
GO
alter table ALBEROPROC_ATECO ALTER COLUMN FK_IDATECO NUMERIC(10,0)
GO
COMMIT
GO
alter table TEMPIFICAZIONI ALTER COLUMN CODICETEMPIFICAZIONE NUMERIC(10,0)
GO
COMMIT
GO
alter table TIPIENDO ALTER COLUMN CODICE NUMERIC(10,0)
GO
COMMIT
GO
alter table TIPIFAMIGLIEENDO ALTER COLUMN CODICE NUMERIC(10,0)
GO
COMMIT
GO
alter table TIPIPROCEDURE ALTER COLUMN CODICEPROCEDURA NUMERIC(10,0)
GO
COMMIT
GO
alter table ALBEROPROC ALTER COLUMN SC_ID NUMERIC(10,0)
GO
COMMIT
GO
alter table ALBEROPROC_ENDO ALTER COLUMN FKSCID NUMERIC(10,0)
GO
COMMIT
GO
alter table ALBEROPROC_ENDO ALTER COLUMN CODICEINVENTARIO NUMERIC(10,0)
GO
COMMIT
GO
alter table ALLEGATI ALTER COLUMN ID NUMERIC(10,0)
GO
COMMIT
GO
alter table AMMINISTRAZIONI ALTER COLUMN CODICEAMMINISTRAZIONE NUMERIC(10,0)
GO
COMMIT
GO
alter table AMMINISTRAZIONIREFERENTI ALTER COLUMN ID NUMERIC(10,0)
GO
COMMIT
GO
alter table NATURAENDO ALTER COLUMN CODICENATURA NUMERIC(10,0)
GO
COMMIT
GO
alter table NORMATIVE ALTER COLUMN CODICENORMATIVA NUMERIC(10,0)
GO
COMMIT
GO
alter table OGGETTI ALTER COLUMN CODICEOGGETTO NUMERIC(10,0)
GO
COMMIT
GO
alter table INVENTARIOPROC_LEGGI ALTER COLUMN ID NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE ALBEROPROCPEOPLEOPER ALTER COLUMN FKSC_ID NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE ALBEROPROCPEOPLEHREF ALTER COLUMN FKSC_ID NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE ALBEROPROC_RUOLI ALTER COLUMN FK_SC_ID NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE ALBERO_CAUSALI ALTER COLUMN FK_SCID NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE STP_ENDO_TIPO2 ALTER COLUMN FK_SC_ID NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE ALBEROPROC_ENDO ALTER COLUMN FKSCID NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE ALBEROPROC_DOCUMENTI ALTER COLUMN SM_FKSCID NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE ALBEROPROC_ONERI ALTER COLUMN AO_FK_SCID NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE ALBEROPROC_ATECO ALTER COLUMN FK_SCID NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE ALBEROPROC_LIMITI ALTER COLUMN FKIDALBERO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE ALBEROPROC_LEGGI ALTER COLUMN SL_FKSCID NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE ALBEROPROC_DYN2MODELLIT ALTER COLUMN FK_SC_ID NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE ISTANZE ALTER COLUMN CODICEINTERVENTOPROC NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE ISTANZEALLEGATI ALTER COLUMN FK_IDALLEGATO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE COMMEDILIZIE_APPELLO ALTER COLUMN CODICEAMMINISTRAZIONE NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE AMMINISTRAZIONIRUOLI ALTER COLUMN CODICEAMMINISTRAZIONE NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE COMMEDILIZIE_TIPOLOGIE ALTER COLUMN CODICEAMMINISTRAZIONE NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE PROTOCOLLO_REGISTRI ALTER COLUMN IDMITTENTE NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE PROTOCOLLO_REGISTRI ALTER COLUMN IDDESTINATARIO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE TIPIMOV_STC_ALTRIDATI ALTER COLUMN CODICEAMMINISTRAZIONE NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE TIPIMOV_STC_MAPPING ALTER COLUMN CODICEAMMINISTRAZIONE NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE ALBO_PUBBLICAZIONI ALTER COLUMN CODICEAMMINISTRAZIONE NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE TIPIMOV_STC_MODELLI ALTER COLUMN CODICEAMMINISTRAZIONE NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE TIPIMOV_STC_ALBEROPROC ALTER COLUMN CODICEAMMINISTRAZIONE NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE DOCUMENTI ALTER COLUMN AMMINISTRAZIONE NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE CDSINVITATI ALTER COLUMN CODICEAMMINISTRAZIONE NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE TEMPIRISPOSTA ALTER COLUMN CODICEAMMINISTRAZIONE NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE BATCH_SCADENZARIO ALTER COLUMN CODICEAMMINISTRAZIONE NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE TIPICONTROMOVIMENTO ALTER COLUMN AMMRITSU NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE TIPICONTROMOVIMENTO ALTER COLUMN AMMMOV NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE EMAIL ALTER COLUMN CODICEAMMINISTRAZIONE NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE MOVIMENTI ALTER COLUMN CODICEAMMINISTRAZIONE NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE AMMINISTRAZIONIRESPONSABILI ALTER COLUMN CODICEAMMINISTRAZIONE NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE AMMINISTRAZIONIREFERENTI ALTER COLUMN CODICEAMMINISTRAZIONE NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE ALLEGATI ALTER COLUMN AMMINISTRAZIONE NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE ISTANZEONERI ALTER COLUMN CODICEAMMINISTRAZIONE NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE INVENTARIOPROCEDIMENTI ALTER COLUMN AMMINISTRAZIONE NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE ALBO_PUBBLICAZIONI ALTER COLUMN CODICEUFFICIO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE EMAIL ALTER COLUMN CODICEUFFICIO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE MOVIMENTI ALTER COLUMN CODICEUFFICIO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE INVENTARIOPROCEDIMENTI ALTER COLUMN CODICEUFFICIO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE MERCATI_CONFIGURAZIONE ALTER COLUMN FK_D2CID_CAT_MERC NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE MERCATI_CONFIGURAZIONE ALTER COLUMN FK_D2CID_COMUNE_AUT NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE MERCATI_CONFIGURAZIONE ALTER COLUMN FK_D2CID_DATA_AUT NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE MERCATI_CONFIGURAZIONE ALTER COLUMN FK_D2CID_NUM_AUT NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE CAMPIGRADUATORIA ALTER COLUMN FK_D2C_ID NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE TIPIBANDOCAMPIGRADUAT ALTER COLUMN FK_D2C_ID NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE TIPIBANDOOUTPUT ALTER COLUMN FK_D2C_ID_RIF NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE TIPIBANDOOUTPUT ALTER COLUMN FK_D2C_ID_OUT NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE TIPIGRADUATORIED ALTER COLUMN FK_D2C_ID NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE DYN2_MODELLID ALTER COLUMN FK_D2C_ID NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE I_ATTIVITADYN2DATI_STORICO ALTER COLUMN FK_D2C_ID NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE I_ATTIVITADYN2DATI ALTER COLUMN FK_D2C_ID NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE MERCATI_CONFIGURAZIONE ALTER COLUMN FK_D2CID_COD_REG_AUT NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE ISTANZEDYN2DATI_STORICO ALTER COLUMN FK_D2C_ID NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE ISTANZEDYN2DATI ALTER COLUMN FK_D2C_ID NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE ANAGRAFEDYN2DATI_STORICO ALTER COLUMN FK_D2C_ID NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE ANAGRAFEDYN2DATI ALTER COLUMN FK_D2C_ID NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE MAPPATURE ALTER COLUMN FKIDCAMPO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE DYN2_MODELLID ALTER COLUMN FK_D2MDT_ID NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE TIPIBANDO ALTER COLUMN FK_D2MT_ID NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE TIPIMOV_STC_MODELLI ALTER COLUMN FK_DYN2_MODELLIT_ID NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE DYN2_MODELLID ALTER COLUMN FK_D2MT_ID NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE I_ATTIVITADYN2MODELLIT_STORICO ALTER COLUMN FK_D2MT_ID NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE I_ATTIVITADYN2MODELLIT ALTER COLUMN FK_D2MT_ID NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE I_ATTIVITADYN2DATI_STORICO ALTER COLUMN FK_D2MT_ID NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE TIPIMOVIMENTIDYN2MODELLIT ALTER COLUMN FK_D2MT_ID NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE MOVIMENTIDYN2MODELLIT ALTER COLUMN FK_D2MT_ID NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE ISTANZEDYN2MODELLIT_STORICO ALTER COLUMN FK_D2MT_ID NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE ISTANZEDYN2MODELLIT ALTER COLUMN FK_D2MT_ID NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE ISTANZEDYN2DATI_STORICO ALTER COLUMN FK_D2MT_ID NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE ANAGRAFEDYN2MODELLIT_STORICO ALTER COLUMN FK_D2MT_ID NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE ANAGRAFEDYN2MODELLIT ALTER COLUMN FK_D2MT_ID NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE ANAGRAFEDYN2DATI_STORICO ALTER COLUMN FK_D2MT_ID NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE ALBEROPROC_DYN2MODELLIT ALTER COLUMN FK_D2MT_ID NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE MAPPATURE ALTER COLUMN FKIDSCHEDA NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE ENDO_CAUSALI ALTER COLUMN FK_CODICEINVENTARIO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE REGISTRAZIONI ALTER COLUMN FK_CODICEINVENTARIO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE STP_ENDO_TIPO1 ALTER COLUMN CODICEINVENTARIO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE BATCH_SCADENZARIO ALTER COLUMN CODICEINVENTARIO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE INVENTARIOPROC_LEGGI ALTER COLUMN CODICEINVENTARIO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE MOVIMENTI ALTER COLUMN CODICEINVENTARIO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE INVENTARIOPROCEDIMENTIINCOMP ALTER COLUMN CODICEINVENTARIO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE INVENTARIOPROCEDIMENTIINCOMP ALTER COLUMN CODICEINCOMPATIBILE NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE INVENTARIOPROCEDIMENTIPEOPLE ALTER COLUMN CODICEINVENTARIO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE TMP_ISTANZEPROCEDIMENTICOLL ALTER COLUMN CODICEINVENTARIO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE TIPIMOVIMENTO_DIS ALTER COLUMN CODICEINVENTARIO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE STP_ENDO_TIPO2 ALTER COLUMN CODICEINVENTARIO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE ISTANZEONERI_DETTAGLIO ALTER COLUMN CODICEINVENTARIO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE ISTANZEONERI ALTER COLUMN CODICEINVENTARIO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE ISTANZEALLEGATI ALTER COLUMN CODICEINVENTARIO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE INVENTARIOPROCDYN2MODELLIT ALTER COLUMN CODICEINVENTARIO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE DOMANDEFRONT_ENDO ALTER COLUMN CODICEINVENTARIO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE CONTROLLOVERIFICHE ALTER COLUMN CODICEINVENTARIO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE ALBEROPROC_ENDO ALTER COLUMN CODICEINVENTARIO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE ISTANZEPROCEDIMENTI ALTER COLUMN CODICEINVENTARIO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE INVENTARIOPROCEDIMENTISOFTWARE ALTER COLUMN CODICEINVENTARIO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE INVENTARIOPROCEDIMENTIONERI ALTER COLUMN CODICEINVENTARIO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE DOCUMENTI ALTER COLUMN CODICEINVENTARIO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE TESTIESTESI ALTER COLUMN CODICEINVENTARIO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE ALLEGATI ALTER COLUMN CODICEINVENTARIO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE ALBEROPROC_LEGGI ALTER COLUMN SL_FKLEID NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE INVENTARIOPROC_LEGGI ALTER COLUMN FKLEID NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE TIPIPROCEDURE ALTER COLUMN CODICENATURA NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE INVENTARIOPROCEDIMENTI ALTER COLUMN CODICENATURA NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE LEGGI ALTER COLUMN FK_NORMATIVE NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE TESTIESTESI ALTER COLUMN TIPONORMA NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE BANDI_ALLEGATI ALTER COLUMN CODICEOGGETTO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE CE_ONERI ALTER COLUMN CODICEOGGETTO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE DOM_ALLEGATI ALTER COLUMN CODICEOGGETTO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE FO_ARCONFIGURAZIONE ALTER COLUMN CODICEOGGETTO_FIRMA NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE FO_ARCONFIGURAZIONE ALTER COLUMN CODICEOGGETTO_SOTTOSCRIZ NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE FO_DOMANDE ALTER COLUMN CODICEOGGETTO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE FO_DOMANDE_OGGETTI ALTER COLUMN CODICEOGGETTO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE FO_RICHIESTE ALTER COLUMN CODICEOGGETTO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE LETTERETIPO ALTER COLUMN CODICEOGGETTO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE MENU ALTER COLUMN CODICEOGGETTO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE MENU ALTER COLUMN CODICEOGGETTO2 NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE MENUINFO ALTER COLUMN CODICEOGGETTO1 NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE MENUINFO ALTER COLUMN CODICEOGGETTO2 NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE MOVIMENTI ALTER COLUMN CODICEOGGETTO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE MULTIDOCUMENTIRIGHE ALTER COLUMN CODICEOGGETTO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE OGGETTIMULTIFORMATO ALTER COLUMN CODICEOGGETTO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE OGGETTIMULTIFORMATO ALTER COLUMN CODICEOGGETTOCOLLEGATO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE PERMCDSATTI ALTER COLUMN CODICEOGGETTO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE SORTEGGITESTATA ALTER COLUMN CODICEOGGETTO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE STILIFRONTOFFICE ALTER COLUMN BUT_ALLEGATI NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE STILIFRONTOFFICE ALTER COLUMN BUT_CALCOLA NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE STILIFRONTOFFICE ALTER COLUMN BUT_CHIUDI NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE STILIFRONTOFFICE ALTER COLUMN BUT_DATIANAGRAFICI NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE STILIFRONTOFFICE ALTER COLUMN BUT_ENDOPROCEDIMENTI NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE STILIFRONTOFFICE ALTER COLUMN BUT_ESCI NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE STILIFRONTOFFICE ALTER COLUMN BUT_FRECCIA NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE STILIFRONTOFFICE ALTER COLUMN BUT_HOME NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE STILIFRONTOFFICE ALTER COLUMN BUT_INDIETRO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE STILIFRONTOFFICE ALTER COLUMN BUT_NUOVA NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE STILIFRONTOFFICE ALTER COLUMN BUT_NUOVAISTANZA NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE STILIFRONTOFFICE ALTER COLUMN BUT_PRECEDENTE NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE STILIFRONTOFFICE ALTER COLUMN BUT_PROCEDI NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE STILIFRONTOFFICE ALTER COLUMN BUT_REGISTRATI NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE STILIFRONTOFFICE ALTER COLUMN BUT_STAMPA NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE STILIFRONTOFFICE ALTER COLUMN BUT_SUCCESSIVA NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE STILIFRONTOFFICE ALTER COLUMN DOT NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE STILIFRONTOFFICE ALTER COLUMN ELEMENT_DOT NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE STILIFRONTOFFICE ALTER COLUMN ELEMENT_DOTPRINCIPALI NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE STILIFRONTOFFICE ALTER COLUMN ELEMENT_MENU NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE STILIFRONTOFFICE ALTER COLUMN ICO_ANTEPRIMA NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE STILIFRONTOFFICE ALTER COLUMN ICO_BINOCOLO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE STILIFRONTOFFICE ALTER COLUMN ICO_COLLEGAMENTO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE STILIFRONTOFFICE ALTER COLUMN ICO_MODELLO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE STILIFRONTOFFICE ALTER COLUMN ICO_TXT NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE STILIFRONTOFFICE ALTER COLUMN ICO_UPLOAD NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE STILIFRONTOFFICE ALTER COLUMN ICO_WORD NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE STILIFRONTOFFICE ALTER COLUMN LABEL_INFO_INTERVENTO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE STILIFRONTOFFICE ALTER COLUMN LABEL_INFO_INTERVENTOON NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE STILIFRONTOFFICE ALTER COLUMN LABEL_INFO_PERSONALI NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE STILIFRONTOFFICE ALTER COLUMN LABEL_INFO_PERSONALION NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE STILIFRONTOFFICE ALTER COLUMN LABEL_INSERIMENTO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE STILIFRONTOFFICE ALTER COLUMN LABEL_INSERIMENTOON NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE STILIFRONTOFFICE ALTER COLUMN LABEL_RISULTATO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE STILIFRONTOFFICE ALTER COLUMN LABEL_RISULTATOON NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE STILIFRONTOFFICE ALTER COLUMN LABEL_SERVIZI_ACCESSORI NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE STILIFRONTOFFICE ALTER COLUMN LABEL_SERVIZI_PRINCIPALI NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE STILIFRONTOFFICE ALTER COLUMN STYLEIE NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE STILIFRONTOFFICE ALTER COLUMN WCAG1AA NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE LEGGI ALTER COLUMN CODICEOGGETTO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE DOM_DOCUMENTI ALTER COLUMN CODICEOGGETTO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE DOM_ALLEGATIENDO ALTER COLUMN CODICEOGGETTO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE COMMEDILIZIE_ALLEGATI ALTER COLUMN CODICEOGGETTO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE STILIFRONTOFFICE ALTER COLUMN SFONDO_TABLEHOME NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE STILIFRONTOFFICE ALTER COLUMN LABEL_DOCUMENTI_DA_SCARICARE NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE STILIFRONTOFFICE ALTER COLUMN LOGO_SUAP NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE STILIFRONTOFFICE ALTER COLUMN LOGO_COMUNE NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE STILIFRONTOFFICE ALTER COLUMN ICO_UNDERC NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE STILIFRONTOFFICE ALTER COLUMN ICO_RE NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE STILIFRONTOFFICE ALTER COLUMN ICO_MSG1 NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE STILIFRONTOFFICE ALTER COLUMN ICO_CESTINO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE OGGETTIINFO ALTER COLUMN CODICEOGGETTO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE STILIFRONTOFFICE ALTER COLUMN LABEL_ACCESSI NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE MERCATI ALTER COLUMN CODICEOGGETTO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE ALBO_PUBBLICAZIONI_ALLEGATI ALTER COLUMN CODICEOGGETTO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE ALBEROPROC_DOCUMENTICAT ALTER COLUMN CODICEOGGETTO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE STP_ENDO_TIPO1 ALTER COLUMN CODICEOGGETTO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE STP_ENDO_TIPO2 ALTER COLUMN CODICEOGGETTO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE DOCUMENTIISTANZA ALTER COLUMN CODICEOGGETTO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE CONFIGURAZIONE ALTER COLUMN CODICEOGGETTOSTILI NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE CONFIGURAZIONE ALTER COLUMN CODICEOGGETTO4 NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE CONFIGURAZIONE ALTER COLUMN CODICEOGGETTO2 NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE CONFIGURAZIONE ALTER COLUMN CODICEOGGETTOMODDOCTIPO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE CDSATTI ALTER COLUMN CODICEOGGETTO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE COMUNIASSOCIATI ALTER COLUMN SI_STEMMA NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE COMUNIASSOCIATISOFTWARE ALTER COLUMN SI_STEMMA NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE TIPIPROCEDURE ALTER COLUMN CODICEOGGETTOFACSDOMPREC NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE TIPIPROCEDURE ALTER COLUMN CODICEOGGETTODIAGRAMMA NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE TIPIPROCEDURE ALTER COLUMN CODICEOGGETTODOL NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE TIPIPROCEDURE ALTER COLUMN CODICEOGGETTO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE PROTOCOLLO ALTER COLUMN CODICEOGGETTO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE MODELLI ALTER COLUMN CODICEOGGETTO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE NEWS ALTER COLUMN CODICEOGGETTO1 NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE NEWS ALTER COLUMN CODICEOGGETTO4 NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE NEWS ALTER COLUMN CODICEOGGETTO3 NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE NEWS ALTER COLUMN CODICEOGGETTO2 NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE NORMEGENERALI ALTER COLUMN CODICEOGGETTO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE BACHECALAVOROCONFIGURAZIONE ALTER COLUMN CERCOLAVOROOGGETTO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE BACHECALAVOROCONFIGURAZIONE ALTER COLUMN OFFROLAVOROOGGETTO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE MOVIMENTIMAILALLEGATI ALTER COLUMN CODICEOGGETTO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE SETTORIAVVISI ALTER COLUMN CODICEOGGETTO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE TIPIPROCEDURE_DOCUMENTI ALTER COLUMN CODICEOGGETTO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE INFO ALTER COLUMN CODICEOGGETTO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE MOVIMENTIALLEGATI ALTER COLUMN CODICEOGGETTO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE ISTANZEALLEGATI ALTER COLUMN CODICEOGGETTO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE ANAGRAFEDOCUMENTI ALTER COLUMN CODICEOGGETTO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE ALBEROPROC_DOCUMENTI ALTER COLUMN CODICEOGGETTO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE ISTANZEPEOPLET ALTER COLUMN CODICEOGGETTO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE COLLAUDO ALTER COLUMN CODICEOGGETTO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE COLLAUDOVERIFICHE ALTER COLUMN CODICEOGGETTO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE CONTROLLOVERIFICHE ALTER COLUMN CODICEOGGETTO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE DOCUMENTI ALTER COLUMN CODICEOGGETTO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE TESTIESTESI ALTER COLUMN CODICEOGGETTO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE ALLEGATI ALTER COLUMN CODICEOGGETTO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE DOMANDESTC ALTER COLUMN CODICEOGGETTO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE INVENTARIOPROCEDIMENTI ALTER COLUMN TEMPIFICAZIONE NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE INVENTARIOPROCEDIMENTI ALTER COLUMN CODICETIPO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE STP_CATEGORIE_ENDO1 ALTER COLUMN CODICE_TIPO_ENDO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE TIPIENDO ALTER COLUMN CODICEFAMIGLIAENDO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE STP_TIPOLOGIE_ENDO1 ALTER COLUMN CODICE_TIPIFAMIGLIE_ENDO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE TEMPIRISPOSTA ALTER COLUMN CODICEPROCEDURA NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE ISTANZE ALTER COLUMN CODICEPROCEDURA NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE ALBEROPROC ALTER COLUMN FKIDPROCEDURA NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE TIPIPROCEDURE_DOCUMENTI ALTER COLUMN TP_FKPROCEDURA NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE SUBPROCEDURE ALTER COLUMN CODICEPROCEDURA NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE TIPICONTROMOVIMENTO ALTER COLUMN CODICEPROCEDURA NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE IMPIANTIPROCEDURE ALTER COLUMN CODICEPROCEDURA NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE LEGGI ALTER COLUMN LE_FKLTID NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE COMMEDILIZIE_ALLEGATI ADD ID NUMERIC(8,0)
GO
COMMIT
GO
ALTER TABLE AMMINISTRAZIONI ALTER COLUMN STC_IDENTE VARCHAR(10)
GO
COMMIT
GO
ALTER TABLE ISTANZEALLEGATI ALTER COLUMN STC_IDDOCUMENTO VARCHAR(200) 
GO
COMMIT
GO
ALTER TABLE ISTANZEALLEGATI ALTER COLUMN STC_IDALLEGATO VARCHAR(200) 
GO
COMMIT
GO
ALTER TABLE DOCUMENTIISTANZA ALTER COLUMN STC_IDDOCUMENTO VARCHAR(200) 
GO
COMMIT
GO
ALTER TABLE DOCUMENTIISTANZA ALTER COLUMN STC_IDALLEGATO VARCHAR(200) 
GO
COMMIT
GO
ALTER TABLE MOVIMENTIALLEGATI ALTER COLUMN STC_IDDOCUMENTO VARCHAR(200) 
GO
COMMIT
GO
ALTER TABLE MOVIMENTIALLEGATI ALTER COLUMN STC_IDALLEGATO VARCHAR(200) 
GO
COMMIT
GO
ALTER TABLE MAPPATURE ALTER COLUMN NOMETAGPEOPLE VARCHAR(100) 
GO
COMMIT
GO
alter table movimenti_contromovimenti ALTER COLUMN codicemovimento NUMERIC(8,0)
GO
COMMIT
GO
ALTER TABLE MOVIMENTI_CONTROMOVIMENTI ALTER COLUMN CODICECONTROMOVIMENTO NUMERIC(8,0)
GO
COMMIT
GO
ALTER TABLE AUTORIZZAZIONI ALTER COLUMN CODICEMOVIMENTO NUMERIC(8,0)
GO
COMMIT
GO
ALTER TABLE BATCH_SCADENZARIO ALTER COLUMN CODICEMOVIMENTO NUMERIC(8,0)
GO
COMMIT
GO
ALTER TABLE CDS ALTER COLUMN CODICEMOVIMENTO NUMERIC(8,0)
GO
COMMIT
GO
ALTER TABLE COMMISSIONIEDILIZIE_R ALTER COLUMN CODICEMOVIMENTO NUMERIC(8,0)
GO
COMMIT
GO
ALTER TABLE COMMISSIONIEDILIZIE_R ALTER COLUMN CODICEMOVIMENTORIENTRO NUMERIC(8,0)
GO
COMMIT
GO
ALTER TABLE MOVIMENTI ALTER COLUMN CODICEMOVIMENTO NUMERIC(8,0)
GO
COMMIT
GO
ALTER TABLE MOVIMENTIALLEGATI ALTER COLUMN CODICEMOVIMENTO NUMERIC(8,0)
GO
COMMIT
GO
ALTER TABLE MOVIMENTIDYN2MODELLIT ALTER COLUMN CODICEMOVIMENTO NUMERIC(8,0)
GO
COMMIT
GO
ALTER TABLE MOVIMENTIHUMMINGBIRD ALTER COLUMN CODICEMOVIMENTO NUMERIC(8,0)
GO
COMMIT
GO
ALTER TABLE PARERI ALTER COLUMN MOVIMENTO NUMERIC(8,0)
GO
COMMIT
GO
ALTER TABLE SORTEGGIDETTAGLIOMOVIMENTI ALTER COLUMN CODICEMOVIMENTO NUMERIC(8,0)
GO
COMMIT
GO
ALTER TABLE TMP_CONTROMOVEFF ALTER COLUMN CODICEMOVIMENTOTX NUMERIC(8,0)
GO
COMMIT
GO
ALTER TABLE TMP_CONTROMOVEFF ALTER COLUMN CODICEMOVIMENTORX NUMERIC(8,0)
GO
COMMIT
GO
ALTER TABLE TMP_PIANIFICAZIONI ALTER COLUMN CODICEMOVIMENTO NUMERIC(8,0)
GO
COMMIT
GO
ALTER TABLE AUTORIZZAZIONI_SUBENTRI ALTER COLUMN CODICEMOVIMENTO NUMERIC(8,0)
GO
COMMIT
GO
alter table movimentimail ALTER COLUMN codicemovimento NUMERIC(8,0)
GO
COMMIT
GO
alter table movimenti_tempistica ALTER COLUMN codicemovimentoapertura NUMERIC(8,0)
GO
COMMIT
GO
alter table movimenti_tempistica ALTER COLUMN CODICEMOVIMENTOCHIUSURA NUMERIC(8,0)
GO
COMMIT
GO
ALTER TABLE DOMANDESTC ADD CODICESOFTWARE VARCHAR(2) NULL
GO
COMMIT
GO