SET IMPLICIT_TRANSACTIONS ON 
GO
ALTER TABLE COMMEDILIZIE_ALLEGATI ALTER COLUMN ID NUMERIC(8,0) NOT NULL
GO
COMMIT
GO
ALTER TABLE COMMEDILIZIE_ALLEGATI ADD CONSTRAINT COMMEDILIZIE_ALLEGATI_PK PRIMARY KEY(IDCOMUNE, ID)
GO
COMMIT
GO
ALTER TABLE MAIL_CONFIG ALTER COLUMN SOFTWARE VARCHAR(2) NOT NULL
GO
COMMIT
GO
ALTER TABLE MAIL_CONFIG ADD CONSTRAINT MAIL_CONFIG_PK PRIMARY KEY(IDCOMUNE,SOFTWARE)
GO
COMMIT
GO