
CREATE TABLE INVENTARIOPROC_ENDO(
  IDCOMUNE varchar(6) NOT NULL,
  ID numeric(10,0) NOT NULL,
  CODICEINVENTARIO_T numeric(10,0) NOT NULL,
  CODICEINVENTARIO_D numeric(10,0) NOT NULL,
  FLAG_PUBBLICA numeric(1,0),
  FLAG_NECESSARIO numeric(1,0)
)ENGINE=INNODB DEFAULT CHARSET=utf8;
 
ALTER TABLE INVENTARIOPROC_ENDO ADD CONSTRAINT PK_INVENTARIOPROC_ENDO PRIMARY KEY (IDCOMUNE, ID);
 
ALTER TABLE INVENTARIOPROC_ENDO ADD CONSTRAINT FK_INVPROCENDO_INVPROC_T FOREIGN KEY (IDCOMUNE, CODICEINVENTARIO_T) REFERENCES INVENTARIOPROCEDIMENTI (IDCOMUNE, CODICEINVENTARIO);
 
ALTER TABLE INVENTARIOPROC_ENDO ADD CONSTRAINT FK_INVPROCENDO_INVPROC_D FOREIGN KEY (IDCOMUNE, CODICEINVENTARIO_D) REFERENCES INVENTARIOPROCEDIMENTI (IDCOMUNE, CODICEINVENTARIO);

Alter table ALBEROPROC_ENDO add FLAG_INTERVENTO numeric(1,0);
Alter table ALBEROPROC_ENDO add DESCRIZIONE varchar(300);


CREATE TABLE ALBEROPROC_ENDO_LOC(
  IDCOMUNE varchar(6) NOT NULL,
  ID numeric(10,0) NOT NULL,
  FK_CI_IDCOMUNE varchar(6) NOT NULL,
  FK_CI_CODICE numeric(10,0) NOT NULL,
  FK_AP_IDCOMUNE varchar(6) NOT NULL,
  FK_AP_SCID numeric(10,0) NOT NULL,
  FLAG_PUBBLICA numeric(1,0),
  FLAG_NECESSARIO numeric(1,0),
 DESCRIZIONE varchar(300),
FLAG_INTERVENTO numeric(1,0)
)ENGINE=INNODB DEFAULT CHARSET=utf8;

ALTER TABLE ALBEROPROC_ENDO_LOC ADD CONSTRAINT PK_ALBEROPROC_ENDO_LOC PRIMARY KEY (IDCOMUNE, ID);

ALTER TABLE ALBEROPROC_ENDO_LOC ADD CONSTRAINT FK_APROCENDOLOC_INVPROC FOREIGN KEY (FK_CI_IDCOMUNE, FK_CI_CODICE) REFERENCES INVENTARIOPROCEDIMENTI (IDCOMUNE, CODICEINVENTARIO);

ALTER TABLE ALBEROPROC_ENDO_LOC ADD CONSTRAINT FK_APROCENDOLOC_APROC FOREIGN KEY (FK_AP_IDCOMUNE, FK_AP_SCID) REFERENCES ALBEROPROC (IDCOMUNE, SC_ID);

CREATE INDEX IDX_ALBEROPROC_ENDO_LOC_001 ON ALBEROPROC_ENDO_LOC (FK_AP_IDCOMUNE, FK_AP_SCID, IDCOMUNE);

alter table sdeproxy add IDCOMUNEBASE varchar(6);