ALTER TABLE COMMISSIONIEDILIZIE_T ADD ( FLAG_SINCRONA NUMERIC(1,0) DEFAULT 1, DATA_FINE DATETIME);

ALTER TABLE COMMEDILIZIE_TIPOLOGIE ADD  FLAG_UPLOAD_DOC_PARERE NUMERIC(1,0) DEFAULT 0;

CREATE TABLE COMMEDR_DOCIST(
    IDCOMUNE VARCHAR (6) NOT NULL,
    ID NUMERIC(10,0) NOT NULL,
    FK_COMMEDILIZIER NUMERIC (6,0) NOT NULL,
    FK_CODICEISTANZA NUMERIC(6,0) NOT NULL,
    FK_DOCUMENTIISTANZA NUMERIC (8,0) NOT NULL 
)ENGINE=INNODB DEFAULT CHARSET=UTF8;

ALTER TABLE COMMEDR_DOCIST ADD CONSTRAINT PK_COMMEDR_DOCIST PRIMARY KEY (IDCOMUNE,ID);
ALTER TABLE COMMEDR_DOCIST ADD CONSTRAINT FK_COMMEDRDIST_COMEDILIZIER FOREIGN KEY (IDCOMUNE,FK_COMMEDILIZIER) REFERENCES COMMISSIONIEDILIZIE_R(IDCOMUNE,ID);
ALTER TABLE COMMEDR_DOCIST ADD CONSTRAINT FK_COMMEDRDIST_IST FOREIGN KEY (IDCOMUNE,FK_CODICEISTANZA) REFERENCES ISTANZE(IDCOMUNE,CODICEISTANZA);
ALTER TABLE COMMEDR_DOCIST ADD CONSTRAINT FK_COMMEDRDIST_DOCISTANZA FOREIGN KEY (IDCOMUNE,FK_DOCUMENTIISTANZA) REFERENCES DOCUMENTIISTANZA(IDCOMUNE,ID);

CREATE TABLE COMMEDR_ISTALL (
    IDCOMUNE VARCHAR(6) NOT NULL,
    ID NUMERIC(10,0) NOT NULL,
    FK_COMMEDILIZIER NUMERIC(6,0) NOT NULL,
    FK_CODICEISTANZA NUMERIC(6,0) NOT NULL,
    FK_ISTANZEALLEGATI NUMERIC(8,0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE COMMEDR_ISTALL ADD CONSTRAINT PK_COMMEDR_ISTALL PRIMARY KEY (IDCOMUNE,ID);
ALTER TABLE COMMEDR_ISTALL ADD CONSTRAINT FK_COMMEDRISTALL_COMMEDILIZIER FOREIGN KEY (IDCOMUNE,FK_COMMEDILIZIER) REFERENCES COMMISSIONIEDILIZIE_R(IDCOMUNE,ID);
ALTER TABLE COMMEDR_ISTALL ADD CONSTRAINT FK_COMMEDRISTALL_ISTANZE FOREIGN KEY (IDCOMUNE,FK_CODICEISTANZA) REFERENCES ISTANZE(IDCOMUNE,CODICEISTANZA);
ALTER TABLE COMMEDR_ISTALL ADD CONSTRAINT FK_COMMEDRISTALL_ISTALLEGATI FOREIGN KEY (IDCOMUNE,FK_ISTANZEALLEGATI) REFERENCES ISTANZEALLEGATI(IDCOMUNE,ID);

CREATE TABLE COMMEDR_MOVALL(
	IDCOMUNE VARCHAR (6) NOT NULL,
	ID NUMERIC(10,0)  NOT NULL ,
	FK_COMMEDILIZIER NUMERIC (6,0)  NOT NULL,
	FK_CODICEISTANZA NUMERIC(6,0) NOT NULL,
	FK_MOVIMENTIALLEGATI NUMERIC(8,0) 
)ENGINE=INNODB DEFAULT CHARSET=UTF8;
                
ALTER TABLE COMMEDR_MOVALL ADD CONSTRAINT PK_COMMEDR_MOVALL PRIMARY KEY (IDCOMUNE,ID);
ALTER TABLE COMMEDR_MOVALL ADD CONSTRAINT FK_COMMEDRMOVALL_COMEDILIZIER FOREIGN KEY (IDCOMUNE,FK_COMMEDILIZIER) REFERENCES COMMISSIONIEDILIZIE_R (IDCOMUNE,ID);
ALTER TABLE COMMEDR_MOVALL ADD CONSTRAINT FK_COMMEDRMOVALL_ISTANZE FOREIGN KEY (IDCOMUNE, FK_CODICEISTANZA) REFERENCES ISTANZE(IDCOMUNE,CODICEISTANZA );
ALTER TABLE COMMEDR_MOVALL ADD CONSTRAINT FK_COMMEDRMOVALL_MOVALLEGATI FOREIGN KEY (IDCOMUNE,FK_MOVIMENTIALLEGATI) REFERENCES MOVIMENTIALLEGATI(IDCOMUNE, ID);

ALTER TABLE COMMEDILIZIE_APPELLO ADD CODICEANAGRAFE NUMERIC(6,0);
ALTER TABLE COMMEDILIZIE_APPELLO ADD CONSTRAINT FK_COMEDAPPELLO_ANAGRAFE FOREIGN KEY (IDCOMUNE, CODICEANAGRAFE ) REFERENCES ANAGRAFE (IDCOMUNE, CODICEANAGRAFE);

CREATE TABLE COMMEDILIZIE_APPELLO_PRATICHE (
    IDCOMUNE VARCHAR(6) NOT NULL,
    ID NUMERIC(10,0) NOT NULL,
    FK_APPELLO NUMERIC(4,0) NOT NULL,
    FK_COMMEDILIZIER NUMERIC(6,0) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE COMMEDILIZIE_APPELLO_PRATICHE ADD CONSTRAINT PK_COMMEDLZ_APPELLO_PRATICHE PRIMARY KEY (IDCOMUNE,ID);
ALTER TABLE COMMEDILIZIE_APPELLO_PRATICHE ADD CONSTRAINT FK_CMEDLZ_APP_PRAT_CMEDLZ_APP FOREIGN KEY (IDCOMUNE,FK_APPELLO) REFERENCES COMMEDILIZIE_APPELLO(IDCOMUNE,ID);
ALTER TABLE COMMEDILIZIE_APPELLO_PRATICHE ADD CONSTRAINT FK_CMEDLZ_APP_PRAT_CMEDLZ_R FOREIGN KEY (IDCOMUNE,FK_COMMEDILIZIER) REFERENCES COMMISSIONIEDILIZIE_R(IDCOMUNE,ID);

CREATE TABLE COMMISSIONI_EDILIZIE_LOG (
    IDCOMUNE VARCHAR(6) NOT NULL,
    ID NUMERIC(10,0) NOT NULL,
    CATEGORIA VARCHAR(50),
    DATA DATETIME NOT NULL,
    FK_COMMISSIONE NUMERIC(10,0) NOT NULL,
    MESSAGGIO VARCHAR(4000) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE COMMISSIONI_EDILIZIE_LOG ADD CONSTRAINT PK_COMMISSIONI_EDILIZIE_LOG PRIMARY KEY (IDCOMUNE,ID);
ALTER TABLE COMMISSIONI_EDILIZIE_LOG ADD CONSTRAINT FK_CMEDLZ_LOG_CMEDLZ_T FOREIGN KEY (IDCOMUNE,FK_COMMISSIONE) REFERENCES COMMISSIONIEDILIZIE_T(IDCOMUNE,CODICECOMMISSIONE);


ALTER TABLE COMMISSIONIEDILIZIE_T MODIFY FLAG_SINCRONA NUMERIC(1,0) NOT NULL;
ALTER TABLE COMMEDILIZIE_TIPOLOGIE MODIFY FLAG_UPLOAD_DOC_PARERE NUMERIC (1,0) NOT NULL;

ALTER TABLE commedilizie_allegati ADD COLUMN flag_pubblica NUMERIC(1,0) DEFAULT 0 NOT NULL ;

alter table COMMEDILIZIE_VOTAZIONI add parere varchar(4000); 
alter table COMMEDILIZIE_VOTAZIONI add codiceoggetto NUMERIC(10,0);

alter table COMMEDILIZIE_VOTAZIONI add constraint FK_COMMEDIVOT_OGGETTI FOREIGN KEY (IDCOMUNE,CODICEOGGETTO) REFERENCES OGGETTI(IDCOMUNE, CODICEOGGETTO);

INSERT INTO MAPOGGETTI (NOMETABELLA, NOMECAMPO) VALUES('COMMEDILIZIE_VOTAZIONI','CODICEOGGETTO');

CREATE INDEX IDX_NON_PUBB on alberoproc (IDCOMUNE, SOFTWARE, FLAG_ESCLUDI_RISULTATI_RICERCA, SC_CODICE);

CREATE TABLE COMMEDILIZIE_ALL_FIRMA(
    IDCOMUNE VARCHAR(6) NOT NULL,
    ID NUMERIC(4,0) NOT NULL,
    FK_COMMEDILIZIE_APPELLO_ID NUMERIC(4,0) NOT NULL,
    FK_COMM_ALLEGATI_ID NUMERIC(8,0) NOT NULL,
    HASH_SHA_256 VARCHAR(64),
    DATA_FIRMA DATETIME
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

ALTER TABLE COMMEDILIZIE_ALL_FIRMA ADD CONSTRAINT PK_COMMEDILIZIE_ALL_FIRMA PRIMARY KEY(IDCOMUNE,ID);

ALTER TABLE COMMEDILIZIE_ALL_FIRMA ADD CONSTRAINT FK_COMMEDIALLFIRMA_APPELLO FOREIGN KEY(IDCOMUNE,FK_COMMEDILIZIE_APPELLO_ID) REFERENCES COMMEDILIZIE_APPELLO(IDCOMUNE,ID);
ALTER TABLE COMMEDILIZIE_ALL_FIRMA ADD CONSTRAINT FK_COMMEDIALLFIRMA_ALLEGATI FOREIGN KEY(IDCOMUNE,FK_COMM_ALLEGATI_ID) REFERENCES COMMEDILIZIE_ALLEGATI(IDCOMUNE,ID);

CREATE INDEX IDX_COMMEDIAPPELLOPRAT_001 ON COMMEDILIZIE_APPELLO_PRATICHE(IDCOMUNE,FK_COMMEDILIZIER);

CREATE TABLE TMP_OGGETTI_COPIA(
    IDCOMUNE VARCHAR(6),
    CODICEOGGETTO NUMERIC(10,0)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

ALTER TABLE TMP_OGGETTI_COPIA ADD CONSTRAINT PK_TMP_OGGETTI_COPIA PRIMARY KEY (IDCOMUNE,CODICEOGGETTO);

create table layouttesti_audit (
	idcomune varchar(6) not null,
	id NUMERIC(10,0) not null,
	data datetime not null,
	software varchar(2) NOT NULL,
	codicetesto varchar(128) not null,
messaggio varchar(2000) not null
)ENGINE=INNODB DEFAULT CHARSET=UTF8;

ALTER TABLE layouttesti_audit ADD CONSTRAINT layouttesti_audit_pk PRIMARY KEY (idcomune, id);
