CREATE TABLE STAR_CONFIGONERI
(
  ID NUMERIC(10,0) NOT NULL
, IDCOMUNE VARCHAR(6) NOT NULL
, FLG_ONLINE_ENTITERZI NUMERIC(1,0) DEFAULT 1 , INFO_PAGAMENTI_FO LONGTEXT , CODICE_COMUNE NUMERIC(6) , CONSTRAINT STAR_CONFIGONERI_PK PRIMARY KEY
  (
    ID
  , IDCOMUNE
  )

) ENGINE=INNODB DEFAULT CHARSET=utf8
;


