INSERT INTO VERTICALIZZAZIONIBASE(MODULO,DESCRIZIONE,FLAG_GESTCOMUNE) VALUES ('PROTOCOLLO_ITALSOFT','Se attivo consente la protocollazione tramite il componente che si integra con il protocollo della ditta Palitalsoft',1);
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES ('PROTOCOLLO_ITALSOFT','CODICE_UFFICIO','Codice dell''ufficio utilizzato in fase di inserimento protocollo');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES ('PROTOCOLLO_ITALSOFT','DOMAIN_CODE','Codice ente per l''autenticazione applicativa');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES ('PROTOCOLLO_ITALSOFT','URL_PROTOCOLLAZIONE','Url del WS di protocollazione');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES ('PROTOCOLLO_ITALSOFT','USER_NAME','Nome utente per l''autenticazione applicativa');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES ('PROTOCOLLO_ITALSOFT','USER_PASSWORD','Password utente per l''autenticazione applicativa');
