<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://sigepro.init.it/rte/definitions" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://sigepro.init.it/rte/definitions" xmlns:sch1="http://sigepro.init.it/rte/types" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:sch0="http://sigepro.init.it/rte">
  <wsdl:types>
    <schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://sigepro.init.it/rte/elements" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:sch0="http://sigepro.init.it/rte" xmlns:sch1="http://sigepro.init.it/rte/types" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://sigepro.init.it/rte" xmlns:types="http://sigepro.init.it/rte/types" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
			<import namespace="http://sigepro.init.it/rte" schemaLocation="nla.xsd"/>
		</schema>
  </wsdl:types>
  <wsdl:message name="RichiestaPraticheListaNLAResponse">
    <wsdl:part name="RichiestaPraticheListaNLAResponse" element="sch0:RichiestaPraticheListaNLAResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="InserimentoAttivitaNLAResponse">
    <wsdl:part name="InserimentoAttivitaNLAResponse" element="sch0:InserimentoAttivitaNLAResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="InserimentoPraticaNLAResponse">
    <wsdl:part name="InserimentoPraticaNLAResponse" element="sch0:InserimentoPraticaNLAResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="InserimentoAttivitaNLARequest">
    <wsdl:part name="InserimentoAttivitaNLARequest" element="sch0:InserimentoAttivitaNLARequest">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="TestNLAResponse">
    <wsdl:part name="TestNLAResponse" element="sch0:TestNLAResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="AggiungiDocumentiNLARequest">
    <wsdl:part name="AggiungiDocumentiNLARequest" element="sch0:AggiungiDocumentiNLARequest">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="AggiungiDocumentiNLAResponse">
    <wsdl:part name="AggiungiDocumentiNLAResponse" element="sch0:AggiungiDocumentiNLAResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="TestNLARequest">
    <wsdl:part name="TestNLARequest" element="sch0:TestNLARequest">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="InserimentoPraticaNLARequest">
    <wsdl:part name="InserimentoPraticaNLARequest" element="sch0:InserimentoPraticaNLARequest">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="AllegatoBinarioNLARequest">
    <wsdl:part name="AllegatoBinarioNLARequest" element="sch0:AllegatoBinarioNLARequest">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="AllegatoBinarioNLAResponse">
    <wsdl:part name="AllegatoBinarioNLAResponse" element="sch0:AllegatoBinarioNLAResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="RichiestaPraticaNLARequest">
    <wsdl:part name="RichiestaPraticaNLARequest" element="sch0:RichiestaPraticaNLARequest">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="RichiestaPraticheListaNLARequest">
    <wsdl:part name="RichiestaPraticheListaNLARequest" element="sch0:RichiestaPraticheListaNLARequest">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="RichiestaPraticaNLAResponse">
    <wsdl:part name="RichiestaPraticaNLAResponse" element="sch0:RichiestaPraticaNLAResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="Nla">
    <wsdl:operation name="RichiestaPraticheListaNLA">
      <wsdl:input name="RichiestaPraticheListaNLARequest" message="tns:RichiestaPraticheListaNLARequest">
    </wsdl:input>
      <wsdl:output name="RichiestaPraticheListaNLAResponse" message="tns:RichiestaPraticheListaNLAResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="InserimentoPraticaNLA">
      <wsdl:input name="InserimentoPraticaNLARequest" message="tns:InserimentoPraticaNLARequest">
    </wsdl:input>
      <wsdl:output name="InserimentoPraticaNLAResponse" message="tns:InserimentoPraticaNLAResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="RichiestaPraticaNLA">
      <wsdl:input name="RichiestaPraticaNLARequest" message="tns:RichiestaPraticaNLARequest">
    </wsdl:input>
      <wsdl:output name="RichiestaPraticaNLAResponse" message="tns:RichiestaPraticaNLAResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="TestNLA">
      <wsdl:input name="TestNLARequest" message="tns:TestNLARequest">
    </wsdl:input>
      <wsdl:output name="TestNLAResponse" message="tns:TestNLAResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="InserimentoAttivitaNLA">
      <wsdl:input name="InserimentoAttivitaNLARequest" message="tns:InserimentoAttivitaNLARequest">
    </wsdl:input>
      <wsdl:output name="InserimentoAttivitaNLAResponse" message="tns:InserimentoAttivitaNLAResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="AllegatoBinarioNLA">
      <wsdl:input name="AllegatoBinarioNLARequest" message="tns:AllegatoBinarioNLARequest">
    </wsdl:input>
      <wsdl:output name="AllegatoBinarioNLAResponse" message="tns:AllegatoBinarioNLAResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="AggiungiDocumentiNLA">
      <wsdl:input name="AggiungiDocumentiNLARequest" message="tns:AggiungiDocumentiNLARequest">
    </wsdl:input>
      <wsdl:output name="AggiungiDocumentiNLAResponse" message="tns:AggiungiDocumentiNLAResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="NlaSoap11" type="tns:Nla">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="RichiestaPraticheListaNLA">
      <soap:operation soapAction=""/>
      <wsdl:input name="RichiestaPraticheListaNLARequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="RichiestaPraticheListaNLAResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="InserimentoPraticaNLA">
      <soap:operation soapAction=""/>
      <wsdl:input name="InserimentoPraticaNLARequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="InserimentoPraticaNLAResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="RichiestaPraticaNLA">
      <soap:operation soapAction=""/>
      <wsdl:input name="RichiestaPraticaNLARequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="RichiestaPraticaNLAResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="TestNLA">
      <soap:operation soapAction=""/>
      <wsdl:input name="TestNLARequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="TestNLAResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="InserimentoAttivitaNLA">
      <soap:operation soapAction=""/>
      <wsdl:input name="InserimentoAttivitaNLARequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="InserimentoAttivitaNLAResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="AllegatoBinarioNLA">
      <soap:operation soapAction=""/>
      <wsdl:input name="AllegatoBinarioNLARequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="AllegatoBinarioNLAResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="AggiungiDocumentiNLA">
      <soap:operation soapAction=""/>
      <wsdl:input name="AggiungiDocumentiNLARequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="AggiungiDocumentiNLAResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="NlaService">
    <wsdl:port name="NlaSoap11" binding="tns:NlaSoap11">
      <soap:address location="http://devel3/ibcstc/services/nla"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
