package it.gruppoinit.sigepro.definitions.movimenti;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.5.1 2012-10-26T11:52:48.295+02:00 Generated source version: 2.5.1
 * 
 */
@WebServiceClient(name = "MovimentiService", wsdlLocation = "", targetNamespace = "http://gruppoinit.it/sigepro/definitions/movimenti")
public class MovimentiService extends Service {

    public final static URL WSDL_LOCATION = null;
    public final static QName SERVICE = new QName("http://gruppoinit.it/sigepro/definitions/movimenti", "MovimentiService");
    public final static QName MovimentiSoap11 = new QName("http://gruppoinit.it/sigepro/definitions/movimenti", "MovimentiSoap11");

    public MovimentiService(URL wsdlLocation) {

	super(wsdlLocation, SERVICE);
    }

    public MovimentiService(URL wsdlLocation, QName serviceName) {

	super(wsdlLocation, serviceName);
    }

    public MovimentiService() {

	super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return returns Movimenti
     */
    @WebEndpoint(name = "MovimentiSoap11")
    public Movimenti getMovimentiSoap11() {

	return super.getPort(MovimentiSoap11, Movimenti.class);
    }

    /**
     * 
     * @param features
     *            A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy. Supported features not in
     *            the <code>features</code> parameter will have their default values.
     * @return returns Movimenti
     */
    @WebEndpoint(name = "MovimentiSoap11")
    public Movimenti getMovimentiSoap11(WebServiceFeature... features) {

	return super.getPort(MovimentiSoap11, Movimenti.class, features);
    }
}
