CREATE TABLE CODIFICA_ENTI_RFC53 (
CODICEISTAT VARCHAR2(6)
, ENTE VARCHAR2(250)
, CODIFICA VARCHAR2(30)
, PRIMARY KEY (CODICEISTAT)
);

CREATE INDEX IDX_GRADUATORIED_001 ON GRADUATORIED(IDCOMUNE,FK_GT_ID);

CREATE INDEX IDX_CAMPIGRADUATORIA_001 ON CAMPIGRADUATORIA(IDCOMUNE,FK_GD_ID);

CREATE INDEX IDX_GRADUATORIET_001 ON GRADUATORIET(IDCOMUNE,FK_TGT_ID);

CREATE INDEX IDX_GRADUATORIED_002 ON GRADUATORIED(IDCOMUNE,CODICEISTANZA);

CREATE INDEX IDX_AUTORIZ_SUBENTRI_001 ON AUTORIZZAZIONI_SUBENTRI(IDCOMUNE, FK_IDAUT_ATTUALE);

ALTER TABLE GRADUATORIET_COM ADD (PROT_DOPO_CREAZIONE_ALLEGATO NUMBER(1,0));
ALTER TABLE ELENCHIPROFESSIONALIBASE ADD FLAG_REGIONALE NUMBER(1,0);
alter table anagrafe modify provinciaelencopro varchar2(50);
alter table anagrafestorico modify provinciaelencopro varchar2(50);

create table RUOLI_PROTOCOLLO(
IDCOMUNE VARCHAR2(6) NOT NULL
,ID   NUMBER(10,0) NOT NULL
,IDRUOLO NUMBER(4,0)
,RUOLO_EXT VARCHAR2(50)
,CODICECOMUNE VARCHAR2(5)
,SOFTWARE VARCHAR2(2)
);
ALTER TABLE RUOLI_PROTOCOLLO ADD CONSTRAINT PK_RUOLI_PROTOCOLLO PRIMARY KEY (IDCOMUNE, ID);
ALTER TABLE RUOLI_PROTOCOLLO ADD CONSTRAINT FK_RUOLIPROT_RUOLI FOREIGN KEY(IDCOMUNE,IDRUOLO) REFERENCES RUOLI(IDCOMUNE, ID);
ALTER TABLE RUOLI_PROTOCOLLO ADD CONSTRAINT FK_RUOLIPROT_COMUNI FOREIGN KEY(CODICECOMUNE) REFERENCES COMUNI(CODICECOMUNE);
ALTER TABLE RUOLI_PROTOCOLLO ADD CONSTRAINT FK_RUOLIPROT_SOFTWARE FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);

ALTER TABLE TIPIMOV_STC_MAPPING ADD (FLAG_CONVERTIPDF NUMBER(1,0));