ALTER TABLE TIPIMOV_STC_MAPPING ADD FLAG_ALLEGADOC_PRATICA NUMBER(1,0);

alter table alberoproc modify sc_descrizione varchar2(500);

ALTER TABLE TIPIMOVIMENTO ADD FLAG_ACCEDI_A_SCHEDE NUMBER(1,0);


CREATE OR REPLACE VIEW VW_DOCUMENTIISTANZA AS 
SELECT 'DOCUMENTI' AS TIPOLOGIA, DOCUMENTIISTANZA.ID AS ID, DOCUMENTIISTANZA.DOCUMENTO AS DESCRIZIONE, DOCUMENTIISTANZA.DATA, DOCUMENTIISTANZA.CODICEOGGETTO, DOCUMENTIISTANZA.STC_IDALLEGATO, DOCUMENTIISTANZA.STC_IDDOCUMENTO, DOCUMENTIISTANZA.CODICEISTANZA, NULL AS CODICEMOVIMENTO, NULL AS CODICEINVENTARIO, DOCUMENTIISTANZA.IDCOMUNE FROM DOCUMENTIISTANZA 
UNION 
SELECT 'MOVIMENTI' AS TIPOLOGIA, MOVIMENTIALLEGATI.ID AS ID, MOVIMENTIALLEGATI.DESCRIZIONE, MOVIMENTI.DATA, MOVIMENTIALLEGATI.CODICEOGGETTO, MOVIMENTIALLEGATI.STC_IDALLEGATO, MOVIMENTIALLEGATI.STC_IDDOCUMENTO, MOVIMENTI.CODICEISTANZA, MOVIMENTI.CODICEMOVIMENTO, NULL AS CODICEINVENTARIO, MOVIMENTI.IDCOMUNE FROM MOVIMENTI, MOVIMENTIALLEGATI WHERE MOVIMENTIALLEGATI.IDCOMUNE = MOVIMENTI.IDCOMUNE AND MOVIMENTIALLEGATI.CODICEMOVIMENTO = MOVIMENTI.CODICEMOVIMENTO 
UNION 
SELECT 'ENDOPROCEDIMENTI' AS TIPOLOGIA, ISTANZEALLEGATI.ID, ISTANZEALLEGATI.ALLEGATOEXTRA AS DESCRIZIONE, ISTANZEPROCEDIMENTI.DATAATTIVAZIONE AS DATA, ISTANZEALLEGATI.CODICEOGGETTO, ISTANZEALLEGATI.STC_IDALLEGATO, ISTANZEALLEGATI.STC_IDDOCUMENTO, ISTANZEALLEGATI.CODICEISTANZA, NULL AS CODICEMOVIMENTO, ISTANZEALLEGATI.CODICEINVENTARIO, ISTANZEALLEGATI.IDCOMUNE FROM INVENTARIOPROCEDIMENTI, ISTANZEALLEGATI, ISTANZEPROCEDIMENTI WHERE INVENTARIOPROCEDIMENTI.IDCOMUNE = ISTANZEPROCEDIMENTI.IDCOMUNE AND INVENTARIOPROCEDIMENTI.CODICEINVENTARIO = ISTANZEPROCEDIMENTI.CODICEINVENTARIO AND ISTANZEPROCEDIMENTI.IDCOMUNE = ISTANZEALLEGATI.IDCOMUNE AND ISTANZEPROCEDIMENTI.CODICEINVENTARIO = ISTANZEALLEGATI.CODICEINVENTARIO AND ISTANZEPROCEDIMENTI.CODICEISTANZA = ISTANZEALLEGATI.CODICEISTANZA 
UNION 
SELECT 'PROCURE' AS TIPOLOGIA, ISTANZEPROCURE.ID, 'PROCURA' AS DESCRIZIONE, ISTANZE.DATA, ISTANZEPROCURE.CODICEOGGETTOPROCURA AS CODICEOGGETTO, ISTANZEPROCURE.STC_ID_ALLEGATO AS STC_IDALLEGATO, ISTANZEPROCURE.STC_ID_DOCUMENTO AS STC_IDDOCUMENTO, ISTANZEPROCURE.CODICEISTANZA, NULL AS CODICEMOVIMENTO, NULL AS CODICEINVENTARIO, ISTANZEPROCURE.IDCOMUNE FROM ISTANZEPROCURE, ISTANZE WHERE ISTANZEPROCURE.IDCOMUNE = ISTANZE.IDCOMUNE AND ISTANZEPROCURE.CODICEISTANZA = ISTANZE.CODICEISTANZA;


CREATE TABLE SUBPROCEDURE_BACK_v_2_45 AS SELECT * FROM SUBPROCEDURE;
ALTER TABLE SUBPROCEDURE ADD SUBPROCEDURA_CLOB CLOB;
UPDATE SUBPROCEDURE SET SUBPROCEDURA_CLOB=SUBPROCEDURA;
ALTER TABLE SUBPROCEDURE DROP COLUMN SUBPROCEDURA;
ALTER TABLE SUBPROCEDURE ADD SUBPROCEDURA CLOB;
UPDATE SUBPROCEDURE SET SUBPROCEDURA=SUBPROCEDURA_CLOB;
ALTER TABLE SUBPROCEDURE DROP COLUMN SUBPROCEDURA_CLOB;

ALTER TABLE LEGGI MODIFY LE_DESCRIZIONE VARCHAR2(1000);


ALTER TABLE TIPIBANDO ADD FLAG_BOLKESTEIN NUMBER(1,0);

ALTER TABLE MERCATI_CONFIGURAZIONE ADD FK_D2CID_MERCATO NUMBER(10,0);
ALTER TABLE MERCATI_CONFIGURAZIONE ADD FK_D2CID_USO NUMBER(10,0);
ALTER TABLE MERCATI_CONFIGURAZIONE ADD FK_D2CID_POSTEGGIO NUMBER(10,0);
ALTER TABLE MERCATI_CONFIGURAZIONE ADD FK_D2CID_ASSEGNATARIA NUMBER(10,0);

ALTER TABLE MERCATI_CONFIGURAZIONE ADD CONSTRAINT FK_MERCCONF_D2BOCME FOREIGN KEY(IDCOMUNE,FK_D2CID_MERCATO) REFERENCES DYN2_CAMPI(IDCOMUNE,ID);
ALTER TABLE MERCATI_CONFIGURAZIONE ADD CONSTRAINT FK_MERCCONF_D2BOCMU FOREIGN KEY(IDCOMUNE,FK_D2CID_USO) REFERENCES DYN2_CAMPI(IDCOMUNE,ID);
ALTER TABLE MERCATI_CONFIGURAZIONE ADD CONSTRAINT FK_MERCCONF_D2CBOPO FOREIGN KEY(IDCOMUNE,FK_D2CID_POSTEGGIO) REFERENCES DYN2_CAMPI(IDCOMUNE,ID);
ALTER TABLE MERCATI_CONFIGURAZIONE ADD CONSTRAINT FK_MERCCONF_D2CBOASS FOREIGN KEY(IDCOMUNE,FK_D2CID_ASSEGNATARIA) REFERENCES DYN2_CAMPI(IDCOMUNE,ID);



CREATE TABLE GRADUATORIED_BOLKESTEIN(
IDCOMUNE VARCHAR2(6) NOT NULL,
ID NUMBER(10,0) NOT NULL,
FK_GRADUATORIED_ID NUMBER(9,0),
CODICEMERCATO NUMBER(4,0),
CODICEUSO NUMBER(4,0),
IDPOSTEGGIO NUMBER(6,0),   
INDICE NUMBER(4,0),
PUNTEGGIO NUMBER(10,0),
ASSEGNATARIA NUMBER(1,0),
POSIZIONE_GRADUATORIA NUMBER(10,0)
);

ALTER TABLE GRADUATORIED_BOLKESTEIN ADD CONSTRAINT PK_GRADUATORIEDBOLKESTEIN PRIMARY KEY(IDCOMUNE,ID);
ALTER TABLE GRADUATORIED_BOLKESTEIN ADD CONSTRAINT FK_GRADDBOLK_GRADD FOREIGN KEY(IDCOMUNE,FK_GRADUATORIED_ID) REFERENCES GRADUATORIED(IDCOMUNE,ID);
ALTER TABLE GRADUATORIED_BOLKESTEIN ADD CONSTRAINT FK_GRADDBOLK_MERC FOREIGN KEY(IDCOMUNE,CODICEMERCATO) REFERENCES MERCATI(IDCOMUNE,CODICEMERCATO);
ALTER TABLE GRADUATORIED_BOLKESTEIN ADD CONSTRAINT FK_GRADDBOLK_MERCU FOREIGN KEY(IDCOMUNE,CODICEUSO) REFERENCES MERCATI_USO(IDCOMUNE,ID);
ALTER TABLE GRADUATORIED_BOLKESTEIN ADD CONSTRAINT FK_GRADDBOLK_MERCD FOREIGN KEY(IDCOMUNE,IDPOSTEGGIO) REFERENCES MERCATI_D(IDCOMUNE,IDPOSTEGGIO);


CREATE TABLE ALBEROPROC_BOLKESTEIN(
IDCOMUNE VARCHAR2(6) NOT NULL,
ID NUMBER(10,0) NOT NULL,
FKSCID NUMBER(10,0),
CODICEMERCATO NUMBER(4,0),
CODICEUSO NUMBER(4,0),
IDPOSTEGGIO NUMBER(6,0)
);

ALTER TABLE ALBEROPROC_BOLKESTEIN ADD CONSTRAINT PK_ALBEROPROCBOLKESTEIN PRIMARY KEY(IDCOMUNE,ID);
ALTER TABLE ALBEROPROC_BOLKESTEIN ADD CONSTRAINT FK_ALBPBOLK_ALBPROC FOREIGN KEY(IDCOMUNE,FKSCID) REFERENCES ALBEROPROC(IDCOMUNE,SC_ID);
ALTER TABLE ALBEROPROC_BOLKESTEIN ADD CONSTRAINT FK_ALBPBOLK_MERC FOREIGN KEY(IDCOMUNE,CODICEMERCATO) REFERENCES MERCATI(IDCOMUNE,CODICEMERCATO);
ALTER TABLE ALBEROPROC_BOLKESTEIN ADD CONSTRAINT FK_ALBPBOLK_MERCU FOREIGN KEY(IDCOMUNE,CODICEUSO) REFERENCES MERCATI_USO(IDCOMUNE,ID);
ALTER TABLE ALBEROPROC_BOLKESTEIN ADD CONSTRAINT FK_ALBPBOLK_MERCD FOREIGN KEY(IDCOMUNE,IDPOSTEGGIO) REFERENCES MERCATI_D(IDCOMUNE,IDPOSTEGGIO);



ALTER TABLE GRADUATORIET_COM ADD CODICEMERCATO NUMBER(4,0);
ALTER TABLE GRADUATORIET_COM ADD CODICEUSO NUMBER(4,0);
ALTER TABLE GRADUATORIET_COM ADD IDPOSTEGGIO NUMBER(6,0);

ALTER TABLE GRADUATORIET_COM ADD CONSTRAINT FK_GRADTCOM_MERC FOREIGN KEY(IDCOMUNE,CODICEMERCATO) REFERENCES MERCATI(IDCOMUNE,CODICEMERCATO);
ALTER TABLE GRADUATORIET_COM ADD CONSTRAINT FK_GRADTCOM_MERCU FOREIGN KEY(IDCOMUNE,CODICEUSO) REFERENCES MERCATI_USO(IDCOMUNE,ID);
ALTER TABLE GRADUATORIET_COM ADD CONSTRAINT FK_GRADTCOM_MERCD FOREIGN KEY(IDCOMUNE,IDPOSTEGGIO) REFERENCES MERCATI_D(IDCOMUNE,IDPOSTEGGIO);

