ALTER TABLE COMMEDILIZIE_VOTAZIONI ADD NUMEROPROTOCOLLO VARCHAR(30);
ALTER TABLE COMMEDILIZIE_VOTAZIONI ADD DATAPROTOCOLLO DATETIME;
ALTER TABLE COMMEDILIZIE_VOTAZIONI ADD FKIDPROTOCOLLO VARCHAR(400);

ALTER TABLE COMMEDILIZIE_APPELLO ADD PIN VARCHAR(10);