ALTER TABLE I_ATTIVITADYN2MODELLIT ADD CONSTRAINT FK_IATTIVD2MT_002 FOREIGN KEY ( IDCOMUNE, FK_IA_ID ) REFERENCES I_ATTIVITA ( IDCOMUNE, ID );
ALTER TABLE I_ATTIVITADYN2DATI ADD CONSTRAINT FK_IATTIVD2D_001 FOREIGN KEY ( IDCOMUNE, FK_IA_ID ) REFERENCES I_ATTIVITA ( IDCOMUNE, ID );
ALTER TABLE I_ATTIVITADYN2DATI_STORICO ADD CONSTRAINT FK_IATTIVD2DSTORICO_002 FOREIGN KEY ( IDCOMUNE, FK_IA_ID ) REFERENCES I_ATTIVITA ( IDCOMUNE, ID );
ALTER TABLE I_ATTIVITADYN2MODELLIT_STORICO ADD CONSTRAINT FK_IATTIVD2MTSTORICO_001 FOREIGN KEY ( IDCOMUNE, FK_IA_ID ) REFERENCES I_ATTIVITA ( IDCOMUNE, ID );

ALTER TABLE AUTORIZZAZIONI MODIFY COLUMN AUTORIZNUMERO VARCHAR(50) NOT NULL;
ALTER TABLE AUTORIZZAZIONI MODIFY COLUMN AUTORIZDATA DATETIME NOT NULL;
ALTER TABLE AUTORIZZAZIONI MODIFY COLUMN FKIDREGISTRO NUMERIC(4,0) NOT NULL;
ALTER TABLE AUTORIZZAZIONI MODIFY COLUMN AUTORIZCOMUNE VARCHAR(5) NOT NULL;

ALTER TABLE ISTANZE DROP FOREIGN KEY FK_ISTANZE_ISTCOLLEGATA;

ALTER TABLE TMP_CONTROMOVEFF MODIFY COLUMN CODAMMRICHIEDENTERX NUMERIC(10,0);
ALTER TABLE TMP_CONTROMOVEFF MODIFY COLUMN CODAMMRICHIEDENTETX NUMERIC(10,0);
ALTER TABLE TMP_CONTROMOVEFF MODIFY COLUMN CODICEAMMINISTRAZIONERX NUMERIC(10,0);
ALTER TABLE TMP_CONTROMOVEFF MODIFY COLUMN CODICEAMMINISTRAZIONETX NUMERIC(10,0);

ALTER TABLE TIPICAUSALIONERI DROP FOREIGN KEY FK_TIPICAUSON_INTERESSI;
ALTER TABLE TIPICAUSALIONERI MODIFY COLUMN FK_TIPICAUSALIINTERESSI DECIMAL(10);
ALTER TABLE TIPICAUSALIONERI ADD CONSTRAINT FK_TIPICAUSON_INTERESSI FOREIGN KEY(IDCOMUNE, FK_TIPICAUSALIINTERESSI) REFERENCES TIPICAUSALIONERI(IDCOMUNE, CO_ID);

CREATE TABLE DOMANDESTC_ALLEGATI(IDCOMUNE VARCHAR(6) NOT NULL,ID NUMERIC(6,0) NOT NULL,FK_DOMANDASTC_ID NUMERIC(6,0),CODICEOGGETTO NUMERIC(10,0)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE DOMANDESTC_ALLEGATI ADD CONSTRAINT PK_DOMANDESTCALLEGATI PRIMARY KEY (IDCOMUNE, ID);
ALTER TABLE DOMANDESTC_ALLEGATI ADD CONSTRAINT FK_DOMSTCALL_DOMSTC FOREIGN KEY (IDCOMUNE, FK_DOMANDASTC_ID) REFERENCES DOMANDESTC(IDCOMUNE, ID); 
ALTER TABLE DOMANDESTC_ALLEGATI ADD CONSTRAINT FK_DOMSTCALL_OGGETTI FOREIGN KEY (IDCOMUNE, CODICEOGGETTO) REFERENCES OGGETTI(IDCOMUNE, CODICEOGGETTO);

CREATE OR REPLACE ALGORITHM=MERGE VIEW VW_LISTAPRATICHE AS  
SELECT 
  ISTANZE.CODICECOMUNE          AS CODICECOMUNE, 
  ISTANZE.IDCOMUNE              AS IDCOMUNE, 
  ISTANZE.SOFTWARE              AS SOFTWARE, 
  SOFTWARE.DESCRIZIONELUNGA     AS DESCSOFTWARE, 
  ISTANZE.CODICEISTANZA         AS IDPRATICA, 
  ISTANZE.NUMEROISTANZA         AS NUMEROPRATICA, 
  DATE_FORMAT(ISTANZE.DATA,_utf8'%d/%m/%Y') AS DATAPRESENTAZIONE, 
  DATE_FORMAT(ISTANZE.DATA,_utf8'%Y') AS ANNOPRESENTAZIONE, 
  DATE_FORMAT(ISTANZE.DATA,_utf8'%m') AS MESEPRESENTAZIONE, 
  ISTANZE.NUMEROPROTOCOLLO      AS NUMEROPROTOCOLLO, 
  DATE_FORMAT(ISTANZE.DATAPROTOCOLLO,_utf8'%d/%m/%Y') AS DATAPROTOCOLLO, 
  ISTANZE.CODICEINTERVENTOPROC  AS CODICEINTERVENTO, 
  VW_ALBEROPROC.SC_DESCRIZIONE  AS DESCRIZIONEINTERVENTO, 
  TIPIPROCEDURE.CODICEPROCEDURA AS CODICEPROCEDURA, 
  TIPIPROCEDURE.PROCEDURA       AS PROCEDURA, 
  ISTANZE.LAVORI                AS OGGETTO, 
  UCASE(ISTANZE.LAVORI)         AS OGGETTOU, 
  ISTANZE.CHIUSURA              AS CODSTATOPRATICA, 
  STATIISTANZA.STATO            AS STATOPRATICA, 
  RESPONSABILI.RESPONSABILE     AS RESPONSABILE, 
  RESPONSABILI.TELEFONOLAVORO   AS RESPONSABILE_TELEFONO, 
  IFNULL(STRADARIO.CODVIARIO,STRADARIO.CODICESTRADARIO) AS PR_CODVIARIO, 
  CONCAT_WS(_utf8'',STRADARIO.PREFISSO,_utf8' ',STRADARIO.DESCRIZIONE) AS PR_INDIRIZZO, 
  ISTANZESTRADARIO.CODICECIVICO AS PR_CODCIVICO, 
  ISTANZESTRADARIO.CIVICO                AS PR_CIVICO, 
  ISTANZE.CODICEAREA            AS CODICEZONIZZAZIONE, 
  AREE.DENOMINAZIONE            AS ZONIZZAZIONE, 
  ANAGRAFE.CODICEANAGRAFE       AS CODICERICHIEDENTE, 
  IFNULL(ANAGRAFE.CODICEFISCALE,_utf8'') AS CODICEFISCALE, 
  IFNULL(ANAGRAFE.PARTITAIVA,_utf8'') AS PARTITAIVA, 
  CONCAT_WS(_utf8'',ANAGRAFE.NOMINATIVO,_utf8' ',ANAGRAFE.NOME) AS NOMINATIVO, 
  ANAGRAFE.INDIRIZZO            AS INDIRIZZO, 
  ANAGRAFE.CAP                  AS CAP, 
  ANAGRAFE.CITTA                AS LOCALITA, 
  COMUNERESIDENZA.COMUNE        AS CITTA, 
  COMUNERESIDENZA.PROVINCIA     AS PROVINCIA, 
  TIPISOGGETTO.TIPOSOGGETTO     AS TIPORAPPORTO, 
  CATASTO.DESCRIZIONE           AS TIPOCATASTO, 
  ISTANZEMAPPALI.FOGLIO         AS FOGLIO, 
  ISTANZEMAPPALI.PARTICELLA     AS PARTICELLA, 
  ISTANZEMAPPALI.SUB            AS SUB, 
  TECNICO.CODICEANAGRAFE        AS TEC_CODICE, 
  CONCAT_WS(_utf8'',TECNICO.NOMINATIVO,_utf8' ',TECNICO.NOME) AS TEC_NOMINATIVO, 
  IFNULL(TECNICO.CODICEFISCALE,_utf8'') AS TEC_CODICEFISCALE, 
  IFNULL(TECNICO.PARTITAIVA,_utf8'') AS TEC_PARTITAIVA, 
  AZIENDA.CODICEANAGRAFE        AS AZ_CODICE, 
  CONCAT_WS(_utf8'',AZIENDA.NOMINATIVO,_utf8' ',AZIENDA.NOME) AS AZ_NOMINATIVO, 
  IFNULL(AZIENDA.CODICEFISCALE,_utf8'') AS AZ_CODICEFISCALE, 
  IFNULL(AZIENDA.PARTITAIVA,_utf8'') AS AZ_PARTITAIVA, 
  ISTRUTTORI.RESPONSABILE       AS ISTRUTTORE, 
  ISTRUTTORI.TELEFONOLAVORO     AS ISTRUTTORE_TELEFONO, 
  OPERATORI.RESPONSABILE        AS OPERATORE, 
  OPERATORI.TELEFONOLAVORO      AS OPERATORE_TELEFONO 
FROM    
ISTANZE  
    JOIN SOFTWARE ON SOFTWARE.CODICE = ISTANZE.SOFTWARE 
    JOIN ANAGRAFE ON ANAGRAFE.IDCOMUNE = ISTANZE.IDCOMUNE 
                      AND ANAGRAFE.CODICEANAGRAFE = ISTANZE.CODICERICHIEDENTE 
    JOIN STATIISTANZA ON STATIISTANZA.IDCOMUNE = ISTANZE.IDCOMUNE 
                          AND STATIISTANZA.SOFTWARE = ISTANZE.SOFTWARE 
                          AND STATIISTANZA.CODICESTATO = ISTANZE.CHIUSURA 
    JOIN VW_ALBEROPROC ON VW_ALBEROPROC.IDCOMUNE = ISTANZE.IDCOMUNE 
                        AND VW_ALBEROPROC.SC_ID = ISTANZE.CODICEINTERVENTOPROC 
    LEFT OUTER JOIN ANAGRAFE TECNICO ON TECNICO.IDCOMUNE = ISTANZE.IDCOMUNE  
                                  AND TECNICO.CODICEANAGRAFE = ISTANZE.CODICEPROFESSIONISTA 
    LEFT OUTER JOIN ANAGRAFE AZIENDA ON ISTANZE.IDCOMUNE = AZIENDA.IDCOMUNE 
                                  AND ISTANZE.CODICETITOLARELEGALE = AZIENDA.CODICEANAGRAFE 
    LEFT OUTER JOIN ISTANZESTRADARIO ON ISTANZE.IDCOMUNE = ISTANZESTRADARIO.IDCOMUNE 
                                  AND ISTANZE.CODICEISTANZA = ISTANZESTRADARIO.CODICEISTANZA  
                                  AND 1 = ISTANZESTRADARIO.PRIMARIO 
                                  LEFT OUTER JOIN STRADARIO ON STRADARIO.IDCOMUNE = ISTANZESTRADARIO.IDCOMUNE 
                                                        AND STRADARIO.CODICESTRADARIO = ISTANZESTRADARIO.CODICESTRADARIO  
    LEFT OUTER JOIN ISTANZEMAPPALI ON ISTANZE.IDCOMUNE = ISTANZEMAPPALI.IDCOMUNE  
                              AND ISTANZE.CODICEISTANZA = ISTANZEMAPPALI.FKCODICEISTANZA 
                              AND 1 = ISTANZEMAPPALI.PRIMARIO 
    LEFT OUTER JOIN RESPONSABILI ON ISTANZE.IDCOMUNE = RESPONSABILI.IDCOMUNE 
                            AND ISTANZE.CODICERESPONSABILEPROC = RESPONSABILI.CODICERESPONSABILE 
    LEFT OUTER JOIN COMUNI COMUNERESIDENZA ON ANAGRAFE.COMUNERESIDENZA = COMUNERESIDENZA.CODICECOMUNE 
    LEFT OUTER JOIN TIPISOGGETTO ON ISTANZE.IDCOMUNE = TIPISOGGETTO.IDCOMUNE 
                                  AND ISTANZE.FKCODICESOGGETTO = TIPISOGGETTO.CODICETIPOSOGGETTO 
    LEFT OUTER JOIN AREE ON ISTANZE.IDCOMUNE = AREE.IDCOMUNE 
                         AND ISTANZE.CODICEAREA = AREE.CODICEAREA 
    LEFT OUTER JOIN CATASTO ON ISTANZEMAPPALI.CODICECATASTO = CATASTO.CODICE 
    LEFT OUTER JOIN TIPIPROCEDURE ON ISTANZE.IDCOMUNE = TIPIPROCEDURE.IDCOMUNE 
                                  AND ISTANZE.CODICEPROCEDURA = TIPIPROCEDURE.CODICEPROCEDURA 
    LEFT OUTER JOIN RESPONSABILI ISTRUTTORI ON ISTANZE.IDCOMUNE = ISTRUTTORI.IDCOMUNE             
                                            AND ISTANZE.CODICEISTRUTTORE = ISTRUTTORI.CODICERESPONSABILE 
    LEFT OUTER JOIN RESPONSABILI OPERATORI ON OPERATORI.IDCOMUNE = ISTANZE.IDCOMUNE  
                                            AND OPERATORI.CODICERESPONSABILE = ISTANZE.CODICERESPONSABILE;

CREATE INDEX IDX_ANAGRAFE_008 ON ANAGRAFE(IDCOMUNE,TIPOANAGRAFE);

ALTER TABLE FO_DOMANDE ADD CODICEOGGETTO_CART NUMERIC(10, 0);
ALTER TABLE FO_DOMANDE ADD CONSTRAINT FK_FO_DOMANDE_OGGETTI FOREIGN KEY (IDCOMUNE,CODICEOGGETTO_CART) REFERENCES OGGETTI (IDCOMUNE,CODICEOGGETTO);
ALTER TABLE LEGGI MODIFY COLUMN LE_DESCRIZIONE VARCHAR(200);
ALTER TABLE MOVIMENTI MODIFY COLUMN NOTE VARCHAR(4000);

UPDATE verticalizzazioniparametri SET VALORE = CONCAT_WS(_utf8'',VALORE,_utf8'/stc?wsdl') WHERE PARAMETRO = 'STC_WS_URL'  and VALORE like '%services';

ALTER TABLE ALBEROPROC_DOCUMENTICAT MODIFY COLUMN ID numeric(10);

ALTER TABLE ALBEROPROC_DOCUMENTI MODIFY COLUMN FKIDCATEGORIA numeric(10);

ALTER TABLE TIPIMODALITAPAGAMENTO MODIFY COLUMN MP_ID numeric(10); 

ALTER TABLE ISTANZEONERI MODIFY COLUMN FKMODALITAPAGAMENTO numeric(10);


ALTER TABLE ALBEROPROC ADD CONSTRAINT FK_ALBERO_PROC_PROT_TIPI_DOC FOREIGN KEY(IDCOMUNE, SC_PROTTIPODOCUMENTO) REFERENCES PROTOCOLLO_TIPIDOCUMENTO (IDCOMUNE, CODICE);

update comuni set codiceistat = CONCAT('0', codiceistat) where codicestatoestero is null and length(codiceistat) = 5;

ALTER TABLE CONFIGURAZIONE MODIFY COLUMN CODAMMSPORTELLOUNICO NUMERIC(10,0);

ALTER TABLE CONFIGURAZIONE MODIFY COLUMN CODICELASTESSAAMMINISTRAZIONE NUMERIC(10,0);

ALTER TABLE CONFIGURAZIONE MODIFY COLUMN CODICETUTTEAMMINISTRAZIONI NUMERIC(10,0);

ALTER TABLE ALBEROPROC ADD CODICEOPERATORE_STC NUMERIC(4,0);

ALTER TABLE ALBEROPROC ADD CONSTRAINT FK_ALBEROPROC_OPESTC FOREIGN KEY (IDCOMUNE,CODICEOPERATORE_STC ) REFERENCES RESPONSABILI (IDCOMUNE, CODICERESPONSABILE);

ALTER TABLE ALLEGATI ADD NOTE_FRONTEND VARCHAR(4000);
ALTER TABLE ALBEROPROC_DOCUMENTI ADD NOTE_FRONTEND VARCHAR(4000);

ALTER TABLE TIPIPROCEDURE_DOCUMENTI ADD NOTE_FRONTEND VARCHAR(4000);

ALTER TABLE MOVIMENTI ADD CODICEOGGETTO_NOTIFICA NUMERIC(10,0);
ALTER TABLE MOVIMENTI ADD CONSTRAINT FK_OGGETTI_MOV_NOTSTC FOREIGN KEY (IDCOMUNE,CODICEOGGETTO_NOTIFICA) REFERENCES OGGETTI (IDCOMUNE,CODICEOGGETTO);


ALTER TABLE ISTANZE_TEMPISTICA ADD DATAFINEEFFETTIVA DATETIME;

ALTER TABLE ISTANZE_TEMPISTICA ADD GGAGGIUNTIVI NUMERIC(4,0);


ALTER TABLE TIPIPROCEDURE ADD FLAG_DISABILITATO NUMERIC(1,0); 
ALTER TABLE AMMINISTRAZIONI ADD FLAG_DISABILITATO NUMERIC(1,0); 
ALTER TABLE TIPIMOVIMENTO ADD FLAG_DISABILITATO NUMERIC(1,0);
ALTER TABLE LETTERETIPO ADD FLAG_DISABILITATO NUMERIC(1,0);

ALTER TABLE TIPIPROCEDURE_DOCUMENTI ADD PUBBLICA NUMERIC(1,0) NULL;
ALTER TABLE TIPIPROCEDURE_DOCUMENTI ADD RICHIESTO NUMERIC(1,0) NULL;
ALTER TABLE TIPIPROCEDURE_DOCUMENTI ADD FO_RICHIEDEFIRMA NUMERIC(1,0) NULL;
ALTER TABLE TIPIPROCEDURE_DOCUMENTI ADD FO_TIPODOWNLOAD VARCHAR(30) NULL;

ALTER TABLE ANAGRAFE MODIFY COLUMN PARTITAIVA VARCHAR(32) ;

ALTER TABLE ANAGRAFE MODIFY COLUMN CODICEFISCALE VARCHAR(32);

ALTER TABLE ANAGRAFESTORICO MODIFY COLUMN PARTITAIVA VARCHAR(32 );

ALTER TABLE ANAGRAFESTORICO MODIFY COLUMN CODICEFISCALE VARCHAR(32);

ALTER TABLE DOMANDESTC MODIFY COLUMN CODICEFISCALE_RICHIEDENTE VARCHAR(32);

ALTER TABLE ISTANZEFIDEJUSSIONI  MODIFY COLUMN FK_RCO_ID NUMERIC(10, 0);
ALTER TABLE STP_ENDO_TIPO1 ADD CODICE_ENDO_REGIONALE VARCHAR(20);

CREATE OR REPLACE ALGORITHM=TEMPTABLE View VW_MERCATIPRESENZETOTALI AS SELECT 'STORICO' AS ORIGINE, MERCATIPRESENZE_STORICO.IDCOMUNE, MERCATIPRESENZE_STORICO.ANNO, MERCATIPRESENZE_STORICO.CODICEANAGRAFE, MERCATIPRESENZE_STORICO.FK_AUTORIZZAZIONI_ID, MERCATIPRESENZE_STORICO.FKCODICEMERCATO, MERCATIPRESENZE_STORICO.FKIDMERCATIUSO, MERCATIPRESENZE_STORICO.FK_IDPOSTEGGIO AS FKIDPOSTEGGIO,  MERCATIPRESENZE_STORICO.NUMEROPRESENZE, TRIM( concat_ws('',ANAGRAFE.NOMINATIVO , ' ' , ANAGRAFE.NOME) ) AS ANAGRAFE, ANAGRAFE.CODICEFISCALE, ANAGRAFE.PARTITAIVA, COMUNI.COMUNE AS COMUNERESIDENZA, CITTADINANZA.CITTADINANZA, STR_TO_DATE(ANAGRAFE.DATAREGDITTE, '%d/%m/%Y' ) AS DATAREGDITTE FROM MERCATIPRESENZE_STORICO inner join ANAGRAFE on ANAGRAFE.IDCOMUNE = MERCATIPRESENZE_STORICO.IDCOMUNE AND ANAGRAFE.CODICEANAGRAFE = MERCATIPRESENZE_STORICO.CODICEANAGRAFE left outer join COMUNI on COMUNI.CODICECOMUNE = ANAGRAFE.COMUNERESIDENZA left outer join CITTADINANZA on CITTADINANZA.CODICE = ANAGRAFE.CODICECITTADINANZA UNION ALL  SELECT 'CALENDARIO' AS ORIGINE, MERCATIPRESENZE_T.IDCOMUNE, MERCATIPRESENZE_T.ANNO, MERCATIPRESENZE_D.CODICEANAGRAFE, MERCATIPRESENZE_D.FK_AUTORIZZAZIONI_ID, MERCATIPRESENZE_T.FKCODICEMERCATO, MERCATIPRESENZE_T.FKIDMERCATIUSO, MERCATIPRESENZE_D.FKIDPOSTEGGIO, 1 AS NUMEROPRESENZE, TRIM( concat_ws('',ANAGRAFE.NOMINATIVO , ' ' , ANAGRAFE.NOME )) AS ANAGRAFE, ANAGRAFE.CODICEFISCALE, ANAGRAFE.PARTITAIVA, COMUNI.COMUNE AS COMUNERESIDENZA, CITTADINANZA.CITTADINANZA, STR_TO_DATE(ANAGRAFE.DATAREGDITTE, '%d/%m/%Y' ) AS DATAREGDITTE FROM MERCATIPRESENZE_T inner join MERCATIPRESENZE_D on MERCATIPRESENZE_D.IDCOMUNE = MERCATIPRESENZE_T.IDCOMUNE AND MERCATIPRESENZE_D.FKIDTESTATA = MERCATIPRESENZE_T.ID inner join ANAGRAFE on ANAGRAFE.IDCOMUNE = MERCATIPRESENZE_D.IDCOMUNE AND ANAGRAFE.CODICEANAGRAFE = MERCATIPRESENZE_D.CODICEANAGRAFE left outer join COMUNI on COMUNI.CODICECOMUNE = ANAGRAFE.COMUNERESIDENZA left outer join CITTADINANZA on CITTADINANZA.CODICE = ANAGRAFE.CODICECITTADINANZA;

CREATE OR REPLACE ALGORITHM=TEMPTABLE VIEW VW_CONCESSIONILISTA AS SELECT IDCOMUNE, SOFTWARE, PROGRESSIVO, CONC_ID, CONC_NUMERO, CONC_DATARILASCIO, CONC_DATASCADENZA, CONC_CODICETIPO, CONC_TIPO, CONC_STAGIONALEA, CONC_STAGIONALEDA, CONC_ATTIVA, CONC_CODICETITOLARE, CONC_TITOLARE, CONC_TIT_CF, CONC_TIT_PIVA, CONC_TIT_TIPOANAGRAFE, AUT_NUMERO, AUT_DATA, AUT_CODREGISTRO, AUT_REGISTRO, IST_CODICEISTANZA, IST_NUMEROISTANZA, IST_CODICERICHIEDENTE, IST_NOMINATIVO, IST_CODICEFISCALE, IST_PARTITAIVA, IST_RIC_TIPOANAGRAFE, ICONC_CODICECAUSALE, ICONC_CAUSALE, ICONC_CODICECAUSALESTORICO, ICONC_CAUSALESTORICO, CONC_IDMERCATO, CONC_MERCATO, MERC_ATTIVO, CONC_IDPOSTEGGIO, CONC_POSTEGGIO, CONC_POS_LARGHEZZA, CONC_POS_LUNGHEZZA, CONC_POS_SUPERFICIE, POST_IDTIPOSPAZIO, POST_TIPOSPAZIO, CONC_IDMERCATIUSO, CONC_DESCRIZIONEUSO, PESO_MERCATO, MERC_IDUSO, CONC_POS_CODICESTRADARIO, DATA_STORICO FROM VW_ISTANZECONCESSIONILISTA;


CREATE TABLE PROTOCOLLO_MEZZI
(
  IDCOMUNE VARCHAR(6) NOT NULL
, CODICE VARCHAR(50) NOT NULL
, DESCRIZIONE VARCHAR(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8; 

ALTER TABLE PROTOCOLLO_MEZZI ADD CONSTRAINT PROTOCOLLO_MEZZI_PK PRIMARY KEY (IDCOMUNE,CODICE);

CREATE TABLE RI_CARICHE(
CODICE VARCHAR(5) NOT NULL,
DESCRIZIONE VARCHAR(150)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE RI_CARICHE ADD CONSTRAINT RI_CARICHE_PK PRIMARY KEY(CODICE);
ALTER TABLE TIPISOGGETTO ADD FK_RICA_CODICE VARCHAR(5);

ALTER TABLE TIPISOGGETTO ADD CONSTRAINT FK_TIPISOGG_RICARI FOREIGN KEY (FK_RICA_CODICE ) REFERENCES RI_CARICHE(CODICE);

CREATE TABLE RI_FORMEGIURIDICHE (
CODICE VARCHAR(5),
DESCRIZIONE VARCHAR(150)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE RI_FORMEGIURIDICHE ADD CONSTRAINT RI_FORMEGIURIDICHE_PK PRIMARY KEY (CODICE);

CREATE TABLE ISTANZE_RI (
IDCOMUNE VARCHAR(6) NOT NULL,
ID NUMERIC(9,0) NOT NULL,
CODICEISTANZA NUMERIC(6,0),
UFFICIORI VARCHAR(2),
DATAPROTOCOLLORI VARCHAR(10),
NUMEROPROTOCOLLORI VARCHAR(50),
ANNO VARCHAR(4)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE ISTANZE_RI ADD CONSTRAINT ISTANZE_RI_PK PRIMARY KEY (IDCOMUNE, ID); 
ALTER TABLE ISTANZE_RI ADD CONSTRAINT FK_ISTRI_ISTANZE FOREIGN KEY (IDCOMUNE, CODICEISTANZA) REFERENCES ISTANZE(IDCOMUNE, CODICEISTANZA);

CREATE INDEX IDX_ISTANZE_RI_001 ON ISTANZE_RI (IDCOMUNE, CODICEISTANZA);


CREATE TABLE I_ATTIVITA_SNAPSHOT
  (
    IDCOMUNE            VARCHAR(6) NOT NULL,
    ID                 NUMERIC(6,0) NOT NULL,
    DENOMINAZIONE       VARCHAR(150),
    CODICEISTANZAULTIMA NUMERIC(6,0),
    NUMEROPRESENZE      NUMERIC(4,0),
    ATTIVA              NUMERIC(1,0),
    OPERANTE            NUMERIC(1,0),
    DATA                DATETIME,
    FK_IA_ID            NUMERIC(6,0) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
  
ALTER TABLE I_ATTIVITA_SNAPSHOT ADD CONSTRAINT PK_SNAPSHOT PRIMARY KEY (IDCOMUNE,ID); 
ALTER TABLE I_ATTIVITA_SNAPSHOT ADD CONSTRAINT FK_IATTIVITA_SNAPSHOT_ISTANZE FOREIGN KEY (IDCOMUNE, CODICEISTANZAULTIMA)  REFERENCES ISTANZE (IDCOMUNE, CODICEISTANZA);
ALTER TABLE I_ATTIVITA_SNAPSHOT ADD CONSTRAINT FK_IATTIVITA_SNAPSHOT_ATTIVITA FOREIGN KEY (IDCOMUNE, FK_IA_ID) REFERENCES I_ATTIVITA(IDCOMUNE, ID);

CREATE TABLE I_ATTIVITADYN2MOD_T_SNAPSHOT
(
  IDCOMUNE   VARCHAR(6) NOT NULL,
  FK_D2MT_ID NUMERIC(10,0)     NOT NULL,
  FK_IA_ID   NUMERIC(6,0)      NOT NULL,
  FK_IAS_ID  NUMERIC(6,0)      NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
  
ALTER TABLE I_ATTIVITADYN2MOD_T_SNAPSHOT ADD CONSTRAINT I_ATTIVITADYN2M_T_SNAPSHOT_PK PRIMARY KEY (IDCOMUNE, FK_D2MT_ID, FK_IA_ID,FK_IAS_ID);
ALTER TABLE I_ATTIVITADYN2MOD_T_SNAPSHOT ADD CONSTRAINT FK_IATTDYNMOD_T_SNAP_DYN_MOD_T FOREIGN KEY (IDCOMUNE, FK_D2MT_ID)   REFERENCES DYN2_MODELLIT (IDCOMUNE, ID);
ALTER TABLE I_ATTIVITADYN2MOD_T_SNAPSHOT ADD CONSTRAINT FK_IATT_DYNMOD_T_SNAP_I_ATT FOREIGN KEY (IDCOMUNE, FK_IA_ID) REFERENCES I_ATTIVITA (IDCOMUNE, ID);
ALTER TABLE I_ATTIVITADYN2MOD_T_SNAPSHOT ADD CONSTRAINT FK_IATT_DYNMODT_SNAP_IATT_S FOREIGN KEY (IDCOMUNE, FK_IAS_ID) REFERENCES I_ATTIVITA_SNAPSHOT (IDCOMUNE, ID);

CREATE TABLE I_ATTIVITADYN2DATI_SNAPSHOT 
  (
    IDCOMUNE  VARCHAR(6) NOT NULL,
    FK_IA_ID  NUMERIC(6,0) NOT NULL,
    FK_D2C_ID NUMERIC(10,0) NOT NULL,
    FK_IAS_ID NUMERIC(6,0) NOT NULL,
    INDICE NUMERIC(2,0) NOT NULL,
    INDICE_MOLTEPLICITA NUMERIC(2,0) NOT NULL,
    VALORE LONGTEXT,
    VALOREDECODIFICATO LONGTEXT
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8;  
   
ALTER TABLE I_ATTIVITADYN2DATI_SNAPSHOT ADD CONSTRAINT I_ATTIVITADYN2DATI_SNAPSHOT_PK PRIMARY KEY (IDCOMUNE, FK_IA_ID, FK_D2C_ID,FK_IAS_ID, INDICE, INDICE_MOLTEPLICITA); 
ALTER TABLE I_ATTIVITADYN2DATI_SNAPSHOT ADD CONSTRAINT FK_IATTIVADYN2_DATI_S_DYN2C FOREIGN KEY (IDCOMUNE, FK_D2C_ID) REFERENCES DYN2_CAMPI (IDCOMUNE, ID);
ALTER TABLE I_ATTIVITADYN2DATI_SNAPSHOT ADD CONSTRAINT FK_IATTIVADYN2_DATI_S_I_ATT FOREIGN KEY (IDCOMUNE, FK_IA_ID) REFERENCES I_ATTIVITA (IDCOMUNE, ID);
ALTER TABLE I_ATTIVITADYN2DATI_SNAPSHOT ADD CONSTRAINT FK_IATT_DYN2_DATI_S_I_ATT_S FOREIGN KEY (IDCOMUNE, FK_IAS_ID) REFERENCES I_ATTIVITA_SNAPSHOT (IDCOMUNE, ID);

CREATE TABLE FO_MOVIMENTI 
(
  IDCOMUNE VARCHAR(6) NOT NULL 
, CODMOVORIG NUMERIC(8, 0) NOT NULL 
, TIPOMOVDAFARE VARCHAR(8) NOT NULL 
, DATI LONGTEXT NOT NULL 
, TRASMESSO NUMERIC(1, 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE FO_MOVIMENTI ADD CONSTRAINT FO_MOVIMENTI_PK PRIMARY KEY (IDCOMUNE,CODMOVORIG,TIPOMOVDAFARE );

ALTER TABLE CONFIGURAZIONE ADD CODICEAMMINISTRAZIONE_IPA VARCHAR(20);
ALTER TABLE CONFIGURAZIONE ADD CODICE_AOO VARCHAR(20);

ALTER TABLE DYN2_CAMPI DROP INDEX IDX_DYN2_CAMPI_001;
ALTER TABLE DYN2_CAMPI MODIFY NOMECAMPO VARCHAR(255);
ALTER TABLE DYN2_CAMPI ADD UNIQUE INDEX IDX_DYN2_CAMPI_001 (IDCOMUNE,SOFTWARE,NOMECAMPO); 


CREATE TABLE ALBEROPROC_D2MODTATT
  (
    IDCOMUNE         VARCHAR(6) NOT NULL,
    FK_SC_ID             NUMERIC(10,0) NOT NULL,
    FK_D2MT_ID       NUMERIC(10,0) NOT NULL
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE ALBEROPROC_D2MODTATT ADD CONSTRAINT ALBEROPROC_D2MODTATT_PK PRIMARY KEY (IDCOMUNE,FK_SC_ID,FK_D2MT_ID); 
ALTER TABLE ALBEROPROC_D2MODTATT ADD CONSTRAINT FK_ALBEROPROC_D2MODTATT_D2MT FOREIGN KEY (IDCOMUNE,FK_D2MT_ID) REFERENCES DYN2_MODELLIT (IDCOMUNE, ID);
ALTER TABLE ALBEROPROC_D2MODTATT ADD CONSTRAINT FK_ALBEROP_D2MODTATT_ALBPROC FOREIGN KEY (IDCOMUNE, FK_SC_ID) REFERENCES ALBEROPROC (IDCOMUNE,SC_ID);

ALTER TABLE PROT_GENERALE ADD PG_INDIRIZZOPERCONTODI VARCHAR(4000);
ALTER TABLE PROT_GENERALE ADD PG_INDIRIZZODESTINATARIO VARCHAR(4000);

ALTER TABLE PROT_ALTRIDESTINATARI ADD AD_INDIRIZZO VARCHAR(4000);

CREATE TABLE PROTOCOLLO_UFFICIREGISTRI (CODICEREGISTRO VARCHAR(10) NOT NULL, CODICEUFFICIO VARCHAR(10) NOT NULL, IDCOMUNE VARCHAR(6) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE PROTOCOLLO_UFFICIREGISTRI ADD CONSTRAINT PROTOCOLLO_UFFICIREGISTRI_PK PRIMARY KEY (CODICEREGISTRO,IDCOMUNE);

CREATE TABLE OGGETTI_METADATI (
	IDCOMUNE VARCHAR(6) NOT NULL,	
	CODICEOGGETTO NUMERIC(10,0) NOT NULL,
	CHIAVE VARCHAR(100) NOT NULL,
	VALORE VARCHAR(4000)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE OGGETTI_METADATI ADD CONSTRAINT PK_OGGETTI_METADATI PRIMARY KEY(IDCOMUNE,CODICEOGGETTO, CHIAVE);
ALTER TABLE OGGETTI_METADATI ADD CONSTRAINT FK_OGGETTI_METADATI FOREIGN KEY (IDCOMUNE,CODICEOGGETTO) REFERENCES OGGETTI (IDCOMUNE,CODICEOGGETTO);

CREATE TABLE PROTOCOLLO_MODALITAINVIO(ICOMUNE VARCHAR(6) NOT NULL, CODICE VARCHAR(30) NOT NULL, DESCRIZIONE VARCHAR(300) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE PROTOCOLLO_MODALITAINVIO ADD CONSTRAINT PROTOCOLLO_MODALITAINVIO_PK PRIMARY KEY (ICOMUNE,CODICE);

ALTER TABLE MAPPATURE MODIFY COLUMN ID NUMERIC(10,0);
ALTER TABLE TIPIMOV_STC_MAPPING MODIFY COLUMN ID NUMERIC(10,0);
ALTER TABLE TIPIMOV_STC_ALBEROPROC MODIFY COLUMN ID NUMERIC(10,0);
ALTER TABLE TIPIMOV_STC_ALTRIDATI MODIFY COLUMN ID NUMERIC(10,0);
ALTER TABLE TIPIMOV_STC_MODELLI MODIFY COLUMN ID NUMERIC(10,0);

ALTER TABLE TIPISOGGETTO ADD ATRIB_QUALIFICASOGGETTO NUMERIC(1,0);
ALTER TABLE TIPIPROCEDURE ADD ATRIB_TIPORICHIESTA NUMERIC(1,0);
ALTER TABLE COMUNIASSOCIATI ADD CODICEAMMINISTRAZIONE_IPA VARCHAR(20);
ALTER TABLE COMUNIASSOCIATI ADD CODICEFISCALE VARCHAR(11);
ALTER TABLE COMUNIASSOCIATISOFTWARE ADD CODICE_ACCREDITAMENTO VARCHAR(30);
ALTER TABLE COMUNIASSOCIATISOFTWARE ADD CODICE_AOO VARCHAR(20);

CREATE TABLE RI_TIPIINTERVENTO(
CODICE VARCHAR(20) NOT NULL,
DESCRIZIONE VARCHAR(150)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE RI_TIPIINTERVENTO ADD CONSTRAINT RI_TIPIINTERVENTO_PK PRIMARY KEY(CODICE); 
ALTER TABLE ALBEROPROC ADD FK_RITI_CODICE VARCHAR(20);
ALTER TABLE ALBEROPROC ADD CONSTRAINT FK_RITIPIINT_ALBPROC FOREIGN KEY (FK_RITI_CODICE) REFERENCES RI_TIPIINTERVENTO(CODICE);

CREATE TABLE RI_TIPIPROCEDIMENTO(
CODICE VARCHAR(20) NOT NULL,
DESCRIZIONE VARCHAR(150)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE RI_TIPIPROCEDIMENTO ADD CONSTRAINT RI_TIPIPROCEDIMENTO_PK PRIMARY KEY(CODICE); 
ALTER TABLE TIPIPROCEDURE ADD FK_RITP_CODICE VARCHAR(20);
ALTER TABLE TIPIPROCEDURE ADD CONSTRAINT FK_RITIPIPROC_TIPROC FOREIGN KEY(FK_RITP_CODICE) REFERENCES RI_TIPIPROCEDIMENTO(CODICE);

ALTER TABLE OGGETTI MODIFY COLUMN NOMEFILE VARCHAR(256);
ALTER TABLE TIPIMOV_STC_MAPPING ADD FLAG_ALLEGA_DOCUMENTI_ENDO NUMERIC(1,0);