CREATE TABLE STP_TIPOLOGIE_ENDO2
(
   IDCOMUNE varchar(6) not null,
   ID NUMERIC(4,0) NOT NULL,
   DESCRIZIONE VARCHAR(100)
)  ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE STP_TIPOLOGIE_ENDO2 ADD CONSTRAINT STP_TIPOLOGIE_ENDO2_PK PRIMARY KEY (IDCOMUNE,ID);
