ALTER TABLE INVENTARIOPROCEDIMENTISOFTWARE MODIFY ID NUMERIC(10,0);

CREATE TABLE MOVIMENTIMAIL_BACKV2_20 AS SELECT * FROM MOVIMENTIMAIL;
ALTER TABLE MOVIMENTIMAIL ADD CORPO_CLOB TEXT;
UPDATE MOVIMENTIMAIL SET CORPO_CLOB=CORPO;
ALTER TABLE MOVIMENTIMAIL DROP COLUMN CORPO;
ALTER TABLE MOVIMENTIMAIL ADD CORPO TEXT;
UPDATE MOVIMENTIMAIL SET CORPO=CORPO_CLOB;
ALTER TABLE MOVIMENTIMAIL DROP COLUMN CORPO_CLOB;

CREATE TABLE MAILTIPO_BACK_v_2_20 AS SELECT * FROM MAILTIPO;
ALTER TABLE MAILTIPO ADD CORPO_CLOB TEXT;
UPDATE MAILTIPO SET CORPO_CLOB=CORPO;
ALTER TABLE MAILTIPO DROP COLUMN CORPO;
ALTER TABLE MAILTIPO ADD CORPO TEXT;
UPDATE MAILTIPO SET CORPO=CORPO_CLOB;
ALTER TABLE MAILTIPO DROP COLUMN CORPO_CLOB;


CREATE OR REPLACE ALGORITHM=TEMPTABLE VIEW VW_ISTANZECONCESSIONILISTA AS SELECT 99999999 AS PROGRESSIVO,AUTORIZZAZIONI.AUTORIZRESPONSABILE AS CONC_AUTORIZRESPONSABILE,AUTORIZZAZIONI.IDCOMUNE AS IDCOMUNE,AUTORIZZAZIONI.FK_CAUSALE_ACQUISIZIONE AS ICONC_CODICECAUSALE,IFNULL(AUTORIZZAZIONI.DATA_CESSAZIONE,STR_TO_DATE('31/12/9999','%D/%M/%Y')) AS DATA_STORICO,ISTANZE.SOFTWARE AS SOFTWARE,ISTANZE.CODICEISTANZA AS IST_CODICEISTANZA,ISTANZE.NUMEROISTANZA AS IST_NUMEROISTANZA,ISTANZE.CODICERICHIEDENTE AS IST_CODICERICHIEDENTE,AUTORIZZAZIONI.ID AS CONC_ID,AUTORIZZAZIONI.AUTORIZNUMERO AS CONC_NUMERO,AUTORIZZAZIONI.AUTORIZDATA AS CONC_DATARILASCIO,AUTORIZZAZIONI.AUTORIZDATA AS DATARILASCIO,AUTORIZZAZIONI.DATASCADENZA AS CONC_DATASCADENZA,AUTORIZZAZIONI_CONCESSIONI.FK_TIPOCONCESSIONE AS CONC_CODICETIPO,CONCESSIONITIPI.DESCRIZIONE AS CONC_TIPO,AUTORIZZAZIONI_CONCESSIONI.STAGIONALEA AS CONC_STAGIONALEA,AUTORIZZAZIONI_CONCESSIONI.STAGIONALEDA AS CONC_STAGIONALEDA,AUTORIZZAZIONI.FLAG_ATTIVA AS CONC_ATTIVA,AUTORIZZAZIONI.FK_CODICEANAGRAFE AS CONC_CODICETITOLARE,AUTORIZZAZIONI.FKIDREGISTRO AS CONC_FKIDREGISTRO,CONC_REGISTRO.TR_DESCRIZIONE AS CONC_REGISTRO,CONCAT_WS('',TITOLARE.NOMINATIVO,' ',TITOLARE.NOME) AS CONC_TITOLARE,TITOLARE.CODICEFISCALE AS CONC_TIT_CF,TITOLARE.PARTITAIVA AS CONC_TIT_PIVA,TITOLARE.TIPOANAGRAFE AS CONC_TIT_TIPOANAGRAFE,AUT_COLLEGATA.AUTORIZNUMERO AS AUT_NUMERO,AUT_COLLEGATA.AUTORIZDATA AS AUT_DATA,AUT_COLLEGATA.AUTORIZDATA AS AUTORIZDATA,AUT_COLLEGATA.FKIDREGISTRO AS AUT_CODREGISTRO,TIPOLOGIAREGISTRI.TR_DESCRIZIONE AS AUT_REGISTRO,CONCAT_WS('',IST_RICHIEDENTE.NOMINATIVO,' ',IST_RICHIEDENTE.NOME) AS IST_NOMINATIVO,IST_RICHIEDENTE.TIPOANAGRAFE AS IST_RIC_TIPOANAGRAFE,CONCAT_WS('',IST_AZIENDA.NOMINATIVO,' ',IST_AZIENDA.NOME) AS IST_NOMINATIVOAZIENDA,IST_AZIENDA.TIPOANAGRAFE AS IST_AZI_TIPOANAGRAFE,IST_RICHIEDENTE.CODICEFISCALE AS IST_CODICEFISCALE,IST_RICHIEDENTE.PARTITAIVA AS IST_PARTITAIVA,CAUS_ATTUALE.DESCRIZIONE AS ICONC_CAUSALE,AUTORIZZAZIONI.FK_CAUSALE_CESSAZIONE AS ICONC_CODICECAUSALESTORICO,CAUS_STORICO.DESCRIZIONE AS ICONC_CAUSALESTORICO,AUTORIZZAZIONI_CONCESSIONI.FK_CODICEMERCATO AS CONC_IDMERCATO,MERCATI.DESCRIZIONE AS CONC_MERCATO,MERCATI.ATTIVO AS MERC_ATTIVO,AUTORIZZAZIONI_CONCESSIONI.FK_IDPOSTEGGIO AS CONC_IDPOSTEGGIO,MERCATI_D.CODICEPOSTEGGIO AS CONC_POSTEGGIO,MERCATI_D.LARGHEZZA AS CONC_POS_LARGHEZZA,MERCATI_D.LUNGHEZZA AS CONC_POS_LUNGHEZZA,MERCATI_D.SUPERFICIE AS CONC_POS_SUPERFICIE,MERCATI_D.FKCODICETIPOSPAZIO AS POST_IDTIPOSPAZIO,POSTEGGITIPOSPAZIO.TIPOSPAZIO AS POST_TIPOSPAZIO,AUTORIZZAZIONI_CONCESSIONI.FK_IDMERCATIUSO AS CONC_IDMERCATIUSO,MERCATI_USO.DESCRIZIONE AS CONC_DESCRIZIONEUSO,MERCATI_USO.PESO AS PESO_MERCATO,MERCATI_USO.FKCODICEUSO AS MERC_IDUSO,MERCATI_D.FKCODICESTRADARIO AS CONC_POS_CODICESTRADARIO,MERCATI_D.NOTE AS CONC_POS_NOTE, VW_ENTILOCALI.COMUNE AS CONC_ENTERILASCIO FROM AUTORIZZAZIONI INNER JOIN VW_ENTILOCALI ON AUTORIZZAZIONI.AUTORIZCOMUNE = VW_ENTILOCALI.CODICECOMUNE INNER JOIN ISTANZE ON AUTORIZZAZIONI.IDCOMUNE = ISTANZE.IDCOMUNE AND AUTORIZZAZIONI.FKIDISTANZA = ISTANZE.CODICEISTANZA LEFT JOIN ANAGRAFE IST_AZIENDA ON ISTANZE.IDCOMUNE = IST_AZIENDA.IDCOMUNE AND ISTANZE.CODICETITOLARELEGALE = IST_AZIENDA.CODICEANAGRAFE INNER JOIN ANAGRAFE IST_RICHIEDENTE ON ISTANZE.IDCOMUNE = IST_RICHIEDENTE.IDCOMUNE AND ISTANZE.CODICERICHIEDENTE = IST_RICHIEDENTE.CODICEANAGRAFE INNER JOIN TIPOLOGIAREGISTRI CONC_REGISTRO ON  AUTORIZZAZIONI.IDCOMUNE = CONC_REGISTRO.IDCOMUNE AND AUTORIZZAZIONI.FKIDREGISTRO = CONC_REGISTRO.TR_ID INNER JOIN ANAGRAFE TITOLARE ON AUTORIZZAZIONI.IDCOMUNE = TITOLARE.IDCOMUNE AND AUTORIZZAZIONI.FK_CODICEANAGRAFE = TITOLARE.CODICEANAGRAFE INNER JOIN CONCESSIONICAUSALI CAUS_ATTUALE ON AUTORIZZAZIONI.IDCOMUNE = CAUS_ATTUALE.IDCOMUNE AND AUTORIZZAZIONI.FK_CAUSALE_ACQUISIZIONE = CAUS_ATTUALE.CODICECAUSALE INNER JOIN AUTORIZZAZIONI_CONCESSIONI ON  AUTORIZZAZIONI.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND AUTORIZZAZIONI.ID = AUTORIZZAZIONI_CONCESSIONI.FK_IDAUT_ATTUALE INNER JOIN MERCATI ON AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE = MERCATI.IDCOMUNE AND AUTORIZZAZIONI_CONCESSIONI.FK_CODICEMERCATO = MERCATI.CODICEMERCATO INNER JOIN MERCATI_D ON AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE = MERCATI_D.IDCOMUNE AND AUTORIZZAZIONI_CONCESSIONI.FK_IDPOSTEGGIO = MERCATI_D.IDPOSTEGGIO INNER JOIN MERCATI_USO ON AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE = MERCATI_USO.IDCOMUNE AND AUTORIZZAZIONI_CONCESSIONI.FK_IDMERCATIUSO = MERCATI_USO.ID LEFT OUTER JOIN POSTEGGITIPOSPAZIO ON MERCATI_D.IDCOMUNE = POSTEGGITIPOSPAZIO.IDCOMUNE AND MERCATI_D.FKCODICETIPOSPAZIO = POSTEGGITIPOSPAZIO.CODICE INNER JOIN CONCESSIONITIPI ON AUTORIZZAZIONI_CONCESSIONI.FK_TIPOCONCESSIONE = CONCESSIONITIPI.TIPOCONCESSIONE LEFT JOIN CONCESSIONICAUSALI CAUS_STORICO ON AUTORIZZAZIONI.IDCOMUNE = CAUS_STORICO.IDCOMUNE AND AUTORIZZAZIONI.FK_CAUSALE_CESSAZIONE = CAUS_STORICO.CODICECAUSALE LEFT JOIN AUTORIZZAZIONI AUT_COLLEGATA ON  AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE = AUT_COLLEGATA.IDCOMUNE AND AUTORIZZAZIONI_CONCESSIONI.FK_IDAUT_COLLEGATA = AUT_COLLEGATA.ID LEFT JOIN TIPOLOGIAREGISTRI ON AUT_COLLEGATA.IDCOMUNE = TIPOLOGIAREGISTRI.IDCOMUNE AND AUT_COLLEGATA.FKIDREGISTRO = TIPOLOGIAREGISTRI.TR_ID UNION SELECT AUTORIZZAZIONI_SUBENTRI.ID AS PROGRESSIVO,AUTORIZZAZIONI_SUBENTRI.AUTORIZRESPONSABILE AS CONC_AUTORIZRESPONSABILE,AUTORIZZAZIONI_SUBENTRI.IDCOMUNE AS IDCOMUNE,AUTORIZZAZIONI_SUBENTRI.FK_CAUSALE_ACQUISIZIONE AS ICONC_CODICECAUSALE,AUTORIZZAZIONI_SUBENTRI.DATA_CESSAZIONE AS DATA_STORICO,ISTANZE.SOFTWARE AS SOFTWARE,ISTANZE.CODICEISTANZA AS IST_CODICEISTANZA,ISTANZE.NUMEROISTANZA AS IST_NUMEROISTANZA,ISTANZE.CODICERICHIEDENTE AS IST_CODICERICHIEDENTE,AUTORIZZAZIONI_SUBENTRI.FK_IDAUT_ATTUALE AS CONC_ID,AUTORIZZAZIONI_SUBENTRI.AUTORIZNUMERO AS CONC_NUMERO,AUTORIZZAZIONI_SUBENTRI.AUTORIZDATA AS CONC_DATARILASCIO,AUTORIZZAZIONI_SUBENTRI.AUTORIZDATA AS DATARILASCIO,AUTORIZZAZIONI_SUBENTRI.DATASCADENZA AS CONC_DATASCADENZA,AUTORIZZAZIONI_CONCESSIONI.FK_TIPOCONCESSIONE AS CONC_CODICETIPO,CONCESSIONITIPI.DESCRIZIONE AS CONC_TIPO,AUTORIZZAZIONI_CONCESSIONI.STAGIONALEA AS CONC_STAGIONALEA,AUTORIZZAZIONI_CONCESSIONI.STAGIONALEDA AS CONC_STAGIONALEDA,0 AS CONC_ATTIVA,AUTORIZZAZIONI_SUBENTRI.FK_CODICEANAGRAFE AS CONC_CODICETITOLARE,AUTORIZZAZIONI_SUBENTRI.FKIDREGISTRO AS CONC_FKIDREGISTRO,CONC_REGISTRO.TR_DESCRIZIONE AS CONC_REGISTRO,CONCAT_WS('',TITOLARE.NOMINATIVO,' ',TITOLARE.NOME) AS CONC_TITOLARE,TITOLARE.CODICEFISCALE AS CONC_TIT_CF,TITOLARE.PARTITAIVA AS CONC_TIT_PIVA,TITOLARE.TIPOANAGRAFE AS CONC_TIT_TIPOANAGRAFE,AUT_COLLEGATA.AUTORIZNUMERO AS AUT_NUMERO,AUT_COLLEGATA.AUTORIZDATA AS AUT_DATA,AUT_COLLEGATA.AUTORIZDATA AS AUTORIZDATA,AUT_COLLEGATA.FKIDREGISTRO AS AUT_CODREGISTRO,TIPOLOGIAREGISTRI.TR_DESCRIZIONE AS AUT_REGISTRO,CONCAT_WS('',IST_RICHIEDENTE.NOMINATIVO,' ',IST_RICHIEDENTE.NOME) AS IST_NOMINATIVO,IST_RICHIEDENTE.TIPOANAGRAFE AS IST_RIC_TIPOANAGRAFE,CONCAT_WS('',IST_AZIENDA.NOMINATIVO,' ',IST_AZIENDA.NOME) AS IST_NOMINATIVOAZIENDA,IST_AZIENDA.TIPOANAGRAFE AS IST_AZI_TIPOANAGRAFE,IST_RICHIEDENTE.CODICEFISCALE AS IST_CODICEFISCALE,IST_RICHIEDENTE.PARTITAIVA AS IST_PARTITAIVA,CAUS_ATTUALE.DESCRIZIONE AS ICONC_CAUSALE,AUTORIZZAZIONI_SUBENTRI.FK_CAUSALE_CESSAZIONE AS ICONC_CODICECAUSALESTORICO,CAUS_STORICO.DESCRIZIONE AS ICONC_CAUSALESTORICO,AUTORIZZAZIONI_CONCESSIONI.FK_CODICEMERCATO AS CONC_IDMERCATO,MERCATI.DESCRIZIONE AS CONC_MERCATO,MERCATI.ATTIVO AS MERC_ATTIVO,AUTORIZZAZIONI_CONCESSIONI.FK_IDPOSTEGGIO AS CONC_IDPOSTEGGIO,MERCATI_D.CODICEPOSTEGGIO AS CONC_POSTEGGIO,MERCATI_D.LARGHEZZA AS CONC_POS_LARGHEZZA,MERCATI_D.LUNGHEZZA AS CONC_POS_LUNGHEZZA,MERCATI_D.SUPERFICIE AS CONC_POS_SUPERFICIE,MERCATI_D.FKCODICETIPOSPAZIO AS POST_IDTIPOSPAZIO,POSTEGGITIPOSPAZIO.TIPOSPAZIO AS POST_TIPOSPAZIO,AUTORIZZAZIONI_CONCESSIONI.FK_IDMERCATIUSO AS CONC_IDMERCATIUSO,MERCATI_USO.DESCRIZIONE AS CONC_DESCRIZIONEUSO,MERCATI_USO.PESO AS PESO_MERCATO,MERCATI_USO.FKCODICEUSO AS MERC_IDUSO,MERCATI_D.FKCODICESTRADARIO AS CONC_POS_CODICESTRADARIO,MERCATI_D.NOTE AS CONC_POS_NOTE, VW_ENTILOCALI.COMUNE AS CONC_ENTERILASCIO FROM AUTORIZZAZIONI_SUBENTRI INNER JOIN VW_ENTILOCALI ON VW_ENTILOCALI.CODICECOMUNE = AUTORIZZAZIONI_SUBENTRI.AUTORIZCOMUNE INNER JOIN ISTANZE ON AUTORIZZAZIONI_SUBENTRI.IDCOMUNE = ISTANZE.IDCOMUNE AND AUTORIZZAZIONI_SUBENTRI.FKIDISTANZA = ISTANZE.CODICEISTANZA LEFT JOIN ANAGRAFE IST_AZIENDA ON ISTANZE.IDCOMUNE = IST_AZIENDA.IDCOMUNE AND ISTANZE.CODICETITOLARELEGALE = IST_AZIENDA.CODICEANAGRAFE INNER JOIN ANAGRAFE IST_RICHIEDENTE ON ISTANZE.IDCOMUNE = IST_RICHIEDENTE.IDCOMUNE AND ISTANZE.CODICERICHIEDENTE = IST_RICHIEDENTE.CODICEANAGRAFE LEFT JOIN CONCESSIONICAUSALI CAUS_STORICO ON AUTORIZZAZIONI_SUBENTRI.IDCOMUNE = CAUS_STORICO.IDCOMUNE AND AUTORIZZAZIONI_SUBENTRI.FK_CAUSALE_CESSAZIONE = CAUS_STORICO.CODICECAUSALE INNER JOIN CONCESSIONICAUSALI CAUS_ATTUALE ON AUTORIZZAZIONI_SUBENTRI.IDCOMUNE = CAUS_ATTUALE.IDCOMUNE AND AUTORIZZAZIONI_SUBENTRI.FK_CAUSALE_ACQUISIZIONE = CAUS_ATTUALE.CODICECAUSALE INNER JOIN ANAGRAFE TITOLARE ON AUTORIZZAZIONI_SUBENTRI.IDCOMUNE = TITOLARE.IDCOMUNE AND AUTORIZZAZIONI_SUBENTRI.FK_CODICEANAGRAFE = TITOLARE.CODICEANAGRAFE INNER JOIN TIPOLOGIAREGISTRI CONC_REGISTRO ON AUTORIZZAZIONI_SUBENTRI.IDCOMUNE = CONC_REGISTRO.IDCOMUNE AND AUTORIZZAZIONI_SUBENTRI.FKIDREGISTRO = CONC_REGISTRO.TR_ID INNER JOIN AUTORIZZAZIONI_CONCESSIONI ON AUTORIZZAZIONI_SUBENTRI.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND AUTORIZZAZIONI_SUBENTRI.FK_IDAUT_ATTUALE = AUTORIZZAZIONI_CONCESSIONI.FK_IDAUT_ATTUALE INNER JOIN MERCATI_USO ON AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE = MERCATI_USO.IDCOMUNE AND AUTORIZZAZIONI_CONCESSIONI.FK_IDMERCATIUSO = MERCATI_USO.ID INNER JOIN MERCATI_D ON AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE = MERCATI_D.IDCOMUNE AND AUTORIZZAZIONI_CONCESSIONI.FK_IDPOSTEGGIO = MERCATI_D.IDPOSTEGGIO LEFT JOIN POSTEGGITIPOSPAZIO ON MERCATI_D.IDCOMUNE = POSTEGGITIPOSPAZIO.IDCOMUNE AND MERCATI_D.FKCODICETIPOSPAZIO = POSTEGGITIPOSPAZIO.CODICE INNER JOIN MERCATI ON AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE = MERCATI.IDCOMUNE AND AUTORIZZAZIONI_CONCESSIONI.FK_CODICEMERCATO = MERCATI.CODICEMERCATO INNER JOIN CONCESSIONITIPI ON CONCESSIONITIPI.TIPOCONCESSIONE = AUTORIZZAZIONI_CONCESSIONI.FK_TIPOCONCESSIONE LEFT JOIN AUTORIZZAZIONI AUT_COLLEGATA ON AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE = AUT_COLLEGATA.IDCOMUNE AND AUTORIZZAZIONI_CONCESSIONI.FK_IDAUT_COLLEGATA = AUT_COLLEGATA.ID LEFT JOIN TIPOLOGIAREGISTRI ON AUT_COLLEGATA.IDCOMUNE = TIPOLOGIAREGISTRI.IDCOMUNE AND AUT_COLLEGATA.FKIDREGISTRO = TIPOLOGIAREGISTRI.TR_ID;


ALTER TABLE ANAGRAFE MODIFY CAP VARCHAR(15);
ALTER TABLE ANAGRAFE MODIFY CAPLR VARCHAR(15);
ALTER TABLE ANAGRAFE MODIFY CAPCORRISPONDENZA VARCHAR(15);

ALTER TABLE ANAGRAFESTORICO MODIFY CAP VARCHAR(15);
ALTER TABLE ANAGRAFESTORICO MODIFY CAPLR VARCHAR(15);
ALTER TABLE ANAGRAFESTORICO MODIFY CAPCORRISPONDENZA VARCHAR(15);

CREATE INDEX IDX_MOVMAIL_MOVIMENTI ON MOVIMENTIMAIL (IDCOMUNE, CODICEMOVIMENTO);

CREATE TABLE ELENCOINAILBASE(
  CODICE VARCHAR(6) NOT NULL,
  DESCRIZIONE VARCHAR(50)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE ELENCOINAILBASE ADD CONSTRAINT PK_ELENCOINAILBASE PRIMARY KEY (CODICE);

CREATE TABLE ELENCOINPSBASE(
  CODICE VARCHAR(6) NOT NULL,
  DESCRIZIONE VARCHAR(50)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE ELENCOINPSBASE ADD CONSTRAINT PK_ELENCOINPSBASE PRIMARY KEY (CODICE);

ALTER TABLE ANAGRAFE ADD INAIL_MATRICOLA VARCHAR(16);
ALTER TABLE ANAGRAFE ADD INAIL_CODICESEDE VARCHAR(6);
ALTER TABLE ANAGRAFE ADD INPS_MATRICOLA VARCHAR(16);
ALTER TABLE ANAGRAFE ADD INPS_CODICESEDE VARCHAR(6);

ALTER TABLE ANAGRAFESTORICO ADD INAIL_MATRICOLA VARCHAR(16);
ALTER TABLE ANAGRAFESTORICO ADD INAIL_CODICESEDE VARCHAR(6);
ALTER TABLE ANAGRAFESTORICO ADD INPS_MATRICOLA VARCHAR(16);
ALTER TABLE ANAGRAFESTORICO ADD INPS_CODICESEDE VARCHAR(6);

ALTER TABLE ANAGRAFE ADD CONSTRAINT FK_ANAG_ELENCOINAIL FOREIGN KEY (INAIL_CODICESEDE) REFERENCES ELENCOINAILBASE(CODICE);
ALTER TABLE ANAGRAFE ADD CONSTRAINT FK_ANAG_ELENCOINPS FOREIGN KEY (INPS_CODICESEDE) REFERENCES ELENCOINPSBASE(CODICE);
ALTER TABLE ANAGRAFESTORICO ADD CONSTRAINT FK_ANAGSTO_ELENCOINAIL FOREIGN KEY (INAIL_CODICESEDE) REFERENCES ELENCOINAILBASE(CODICE);
ALTER TABLE ANAGRAFESTORICO ADD CONSTRAINT FK_ANAGSTO_ELENCOINPS FOREIGN KEY (INPS_CODICESEDE) REFERENCES ELENCOINPSBASE(CODICE);


CREATE TABLE ANAGRAFEDOCUMENTI_DURC(
IDCOMUNE VARCHAR(6) NOT NULL,
ID NUMERIC(10,0) NOT NULL,
FK_ANAGRAFEDOC_ID  NUMERIC(10,0) NOT NULL,
REQUESTID VARCHAR(50),
RESULTCODE VARCHAR(5),
RESULTDESCRIPTION VARCHAR(300),
CIP VARCHAR(20),
PROTOCOL VARCHAR(10),
ISSUEDATE DATETIME,
EXPIRATIONDATE DATETIME,
CODICEOGGETTO NUMERIC(10,0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE ANAGRAFEDOCUMENTI_DURC ADD CONSTRAINT PK_ANAGRAFEDOCUMENTIDURC PRIMARY KEY(IDCOMUNE, ID);
ALTER TABLE ANAGRAFEDOCUMENTI_DURC ADD CONSTRAINT FK_ANAGRDOCUDURC_ANAGDOC FOREIGN KEY(IDCOMUNE, FK_ANAGRAFEDOC_ID) REFERENCES ANAGRAFEDOCUMENTI (IDCOMUNE, ID);
ALTER TABLE ANAGRAFEDOCUMENTI_DURC ADD CONSTRAINT FK_ANAGRDOCUDURC_OGGETTI FOREIGN KEY(IDCOMUNE, CODICEOGGETTO) REFERENCES OGGETTI (IDCOMUNE, CODICEOGGETTO);


ALTER TABLE PEC_INBOX ADD FK_RESP_EVIDENZA NUMERIC(4,0);

ALTER TABLE PEC_INBOX ADD CONSTRAINT PEC_INBOX_RESP_EVIDENZA FOREIGN KEY (IDCOMUNE,FK_RESP_EVIDENZA) REFERENCES RESPONSABILI (IDCOMUNE,CODICERESPONSABILE);


ALTER TABLE INVENTARIOPROC_TIPITITOLO ADD FLG_NON_PUBBLICARE NUMERIC(1,0) DEFAULT 0;
ALTER TABLE INVENTARIOPROC_TIPITITOLO ADD FLG_ALL_OBBLIGATORIO NUMERIC(1,0) DEFAULT 0;

ALTER TABLE PEC_INBOX ADD PEC_TOCC VARCHAR(4000);

ALTER TABLE FAQ ADD ORDINE NUMERIC(3,0);
ALTER TABLE NORMATIVE ADD ORDINE NUMERIC(3,0);
ALTER TABLE NEWS ADD SOMMARIO VARCHAR(400);

CREATE TABLE ALBEROPROC_FO_TOP(
IDCOMUNE VARCHAR(6) NOT NULL,
ID NUMERIC(6,0) NOT NULL, 
SOFTWARE VARCHAR (2) NOT NULL, 
DESCRIZIONE VARCHAR(256) NOT NULL,
FK_SCID NUMERIC(10,0) NOT NULL,
ORDINE NUMERIC(3,0) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE ALBEROPROC_FO_TOP ADD CONSTRAINT PK_ALBPROCFOTOP PRIMARY KEY (IDCOMUNE,ID);
ALTER TABLE ALBEROPROC_FO_TOP ADD CONSTRAINT FK_ALBPROCFOTOP_ALBEROPROC FOREIGN KEY (IDCOMUNE,FK_SCID) REFERENCES ALBEROPROC(IDCOMUNE, SC_ID);
ALTER TABLE ALBEROPROC_FO_TOP ADD CONSTRAINT FK_ALBPROCFOTOP_SOFTWARE FOREIGN KEY (SOFTWARE) REFERENCES SOFTWARE(CODICE);

CREATE TABLE INVENTARIOPROC_FO_TOP(
IDCOMUNE VARCHAR(6) NOT NULL,
ID NUMERIC(6,0) NOT NULL,
SOFTWARE VARCHAR (2) NOT NULL,
DESCRIZIONE VARCHAR(256) NOT NULL,
FK_CODICEINVENTARIO NUMERIC(10,0) NOT NULL,
ORDINE NUMERIC(3,0) NOT NULL 
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE INVENTARIOPROC_FO_TOP ADD CONSTRAINT PK_INVENTARIOPROCFOTOP PRIMARY KEY (IDCOMUNE,ID);
ALTER TABLE INVENTARIOPROC_FO_TOP ADD CONSTRAINT FK_INVPROCFOTOP_INVPROC FOREIGN KEY (IDCOMUNE, FK_CODICEINVENTARIO) REFERENCES INVENTARIOPROCEDIMENTI(IDCOMUNE, CODICEINVENTARIO);
ALTER TABLE INVENTARIOPROC_FO_TOP ADD CONSTRAINT FK_INVPROCFOTOP_SOFTWARE FOREIGN KEY (SOFTWARE) REFERENCES SOFTWARE(CODICE);

ALTER TABLE NORMEGENERALI MODIFY ORDINE NUMERIC(3);

ALTER TABLE COMMEDILIZIE_APPELLO DROP FOREIGN KEY FK_COMM_EDIL_APP_RESP;
ALTER TABLE RESPONSABILI_TM_SCA DROP FOREIGN KEY FK_RESPTMSCA_RESP;
ALTER TABLE RESPONSABILI_TM_AVV DROP FOREIGN KEY FK_RESPTMAVV_RESP;
ALTER TABLE CONFIGURAZIONEUTENTE DROP FOREIGN KEY CONFUTENTE_RESPONSABILI_FK1;
ALTER TABLE RESPONSABILIRUOLI DROP FOREIGN KEY FK_RESPONSABILIRUOLI_RESP;
ALTER TABLE PROTOCOLLO_RESPONSABILIFLUSSI DROP FOREIGN KEY FK_PROTRESPFLUSSI_RESPONSABILI;
ALTER TABLE REGISTRAZIONI DROP FOREIGN KEY FK_REG_RESPONSAB;
ALTER TABLE REGISTRAZIONI DROP FOREIGN KEY FK_REG_RESPONSAB1;
ALTER TABLE ALBO_PUBBLICAZIONI DROP FOREIGN KEY FK_PUBBLICAZIONI_RESPONSABILI;
ALTER TABLE CONFIGURAZIONE DROP FOREIGN KEY FK_CONF_RESPONSABILI;
ALTER TABLE PERMISTANZE DROP FOREIGN KEY FK_PERIST_RESPONSABILI;
ALTER TABLE ALBEROPROC DROP FOREIGN KEY FK_ALBEROPROC_RESPISTRUTTORIA;
ALTER TABLE AMMINISTRAZIONIRESPONSABILI DROP FOREIGN KEY FK_AMMRESP_RESPONSABILI;
ALTER TABLE ALBEROPROC DROP FOREIGN KEY FK_ALBEROPROC_RESPPROC;
ALTER TABLE MOVIMENTI DROP FOREIGN KEY FK_MOVIMENTI_RESPONS;
ALTER TABLE CLPERMMENU DROP FOREIGN KEY FK_CLPERMMENU_RESPONSABILI;
ALTER TABLE RESPONSABILICOMUNI DROP FOREIGN KEY FK_RESPCOMUNI_RESPONSABILI;
ALTER TABLE ISTANZE DROP FOREIGN KEY FK_ISTANZE_RESPISTRUT;
ALTER TABLE ISTANZE DROP FOREIGN KEY FK_ISTANZE_RESPPROC;
ALTER TABLE ISTANZE DROP FOREIGN KEY FK_ISTANZE_OPERATORI;
ALTER TABLE ISTANZEONERI DROP FOREIGN KEY FK_ISTONERI_RESPONSABILI;
ALTER TABLE RESPONSABILISOFTWARE DROP FOREIGN KEY FK_RESPSOFTWARE_RESPONSABILI;
ALTER TABLE RESPONSABILISOFTWARE DROP index FK_RESPSOFTWARE_RESPONSABILI;
ALTER TABLE RESPONSABILI DROP FOREIGN KEY FK_RESPONSABILI_SCADOPE;
ALTER TABLE ALBEROPROC DROP FOREIGN KEY FK_ALBEROPROC_OPESTC;
ALTER TABLE LINK_PREFERITI_UTENTE DROP FOREIGN KEY FK_LINK_PREF_UTENTE_RESP;
ALTER TABLE DOCUMENTI_CONTABILITA DROP FOREIGN KEY FK_DOC_CONTAB_RESP;
ALTER TABLE PEC_INBOX DROP FOREIGN KEY PEC_INBOX_RESPONSABILI_FK1;
ALTER TABLE DOCUMENTI_DA_FIRMARE DROP FOREIGN KEY DOCUMENTI_DA_FIRMARE_RESP_FK1;
ALTER TABLE DOCUMENTI_DA_FIRMARE DROP FOREIGN KEY DOCUMENTI_DA_FIRMARE_RESP_FK2;
ALTER TABLE PEC_INBOX DROP FOREIGN KEY PEC_INBOX_RESP_EVIDENZA;

ALTER TABLE RESPONSABILI MODIFY CODICERESPONSABILE NUMERIC(8,0);
ALTER TABLE CONFIGURAZIONEUTENTE MODIFY CODICERESPONSABILE NUMERIC(8,0);
ALTER TABLE RESPONSABILIRUOLI MODIFY CODICERESPONSABILE NUMERIC(8,0);
ALTER TABLE PROTOCOLLO_RESPONSABILIFLUSSI MODIFY CODICERESPONSABILE NUMERIC(8,0);
ALTER TABLE REGISTRAZIONI MODIFY CODICEOPERATORE NUMERIC(8,0);
ALTER TABLE REGISTRAZIONI MODIFY CODICEUTENTESISTEMA NUMERIC(8,0);
ALTER TABLE ALBO_PUBBLICAZIONI MODIFY CODICERESPONSABILE NUMERIC(8,0);
ALTER TABLE CONFIGURAZIONE MODIFY CODICERESPONSABILE NUMERIC(8,0);
ALTER TABLE PERMISTANZE MODIFY CODICERESPONSABILE NUMERIC(8,0);
ALTER TABLE ALBEROPROC MODIFY CODICERESPISTRUTTORIA NUMERIC(8,0);
ALTER TABLE AMMINISTRAZIONIRESPONSABILI MODIFY CODICERESPONSABILE NUMERIC(8,0);
ALTER TABLE ALBEROPROC MODIFY CODICERESPONSABILE NUMERIC(8,0);
ALTER TABLE MOVIMENTI MODIFY CODICERESPONSABILE NUMERIC(8,0);
ALTER TABLE CLPERMMENU MODIFY CODICERESPONSABILE NUMERIC(8,0);
ALTER TABLE RESPONSABILICOMUNI MODIFY CODICERESPONSABILE NUMERIC(8,0);
ALTER TABLE ISTANZE MODIFY CODICEISTRUTTORE NUMERIC(8,0);
ALTER TABLE ISTANZE MODIFY CODICERESPONSABILEPROC NUMERIC(8,0);
ALTER TABLE ISTANZE MODIFY CODICERESPONSABILE NUMERIC(8,0);
ALTER TABLE ISTANZEONERI MODIFY CODICEUTENTE NUMERIC(8,0);
ALTER TABLE RESPONSABILISOFTWARE MODIFY CODICERESPONSABILE NUMERIC(8,0);
ALTER TABLE RESPONSABILI MODIFY SCAD_OPERATORE NUMERIC(8,0);
ALTER TABLE ALBEROPROC MODIFY CODICEOPERATORE_STC NUMERIC(8,0);
ALTER TABLE LINK_PREFERITI_UTENTE MODIFY CODICERESPONSABILE NUMERIC(8,0);
ALTER TABLE DOCUMENTI_CONTABILITA MODIFY CODICERESPONSABILE NUMERIC(8,0);
ALTER TABLE PEC_INBOX MODIFY CODICEOPERATORE NUMERIC(8,0);
ALTER TABLE DOCUMENTI_DA_FIRMARE MODIFY CODICERICHIEDENTE NUMERIC(8,0);
ALTER TABLE DOCUMENTI_DA_FIRMARE MODIFY CODICEFIRMATARIO NUMERIC(8,0);
ALTER TABLE PEC_INBOX MODIFY FK_RESP_EVIDENZA NUMERIC(8,0);


ALTER TABLE COMMEDILIZIE_APPELLO ADD CONSTRAINT FK_COMM_EDIL_APP_RESP FOREIGN KEY (IDCOMUNE,CODICERESPONSABILE) REFERENCES RESPONSABILI (IDCOMUNE, CODICERESPONSABILE);
ALTER TABLE RESPONSABILI_TM_SCA ADD CONSTRAINT FK_RESPTMSCA_RESP FOREIGN KEY (IDCOMUNE,CODICERESPONSABILE) REFERENCES RESPONSABILI (IDCOMUNE, CODICERESPONSABILE);
ALTER TABLE RESPONSABILI_TM_AVV ADD CONSTRAINT FK_RESPTMAVV_RESP FOREIGN KEY (IDCOMUNE,CODICERESPONSABILE) REFERENCES RESPONSABILI (IDCOMUNE, CODICERESPONSABILE);
ALTER TABLE CONFIGURAZIONEUTENTE ADD CONSTRAINT CONFUTENTE_RESPONSABILI_FK1 FOREIGN KEY (IDCOMUNE,CODICERESPONSABILE) REFERENCES RESPONSABILI (IDCOMUNE, CODICERESPONSABILE);
ALTER TABLE RESPONSABILIRUOLI ADD CONSTRAINT FK_RESPONSABILIRUOLI_RESP FOREIGN KEY (IDCOMUNE,CODICERESPONSABILE) REFERENCES RESPONSABILI (IDCOMUNE, CODICERESPONSABILE);
ALTER TABLE PROTOCOLLO_RESPONSABILIFLUSSI ADD CONSTRAINT FK_PROTRESPFLUSSI_RESPONSABILI FOREIGN KEY (IDCOMUNE,CODICERESPONSABILE) REFERENCES RESPONSABILI (IDCOMUNE, CODICERESPONSABILE);
ALTER TABLE REGISTRAZIONI ADD CONSTRAINT FK_REG_RESPONSAB FOREIGN KEY (IDCOMUNE,CODICEOPERATORE) REFERENCES RESPONSABILI (IDCOMUNE, CODICERESPONSABILE);
ALTER TABLE REGISTRAZIONI ADD CONSTRAINT FK_REG_RESPONSAB1 FOREIGN KEY (IDCOMUNE,CODICEUTENTESISTEMA) REFERENCES RESPONSABILI (IDCOMUNE, CODICERESPONSABILE);
ALTER TABLE ALBO_PUBBLICAZIONI ADD CONSTRAINT FK_PUBBLICAZIONI_RESPONSABILI FOREIGN KEY (IDCOMUNE,CODICERESPONSABILE) REFERENCES RESPONSABILI (IDCOMUNE, CODICERESPONSABILE);
ALTER TABLE CONFIGURAZIONE ADD CONSTRAINT FK_CONF_RESPONSABILI FOREIGN KEY (IDCOMUNE,CODICERESPONSABILE) REFERENCES RESPONSABILI (IDCOMUNE, CODICERESPONSABILE);
ALTER TABLE PERMISTANZE ADD CONSTRAINT FK_PERIST_RESPONSABILI FOREIGN KEY (IDCOMUNE,CODICERESPONSABILE) REFERENCES RESPONSABILI (IDCOMUNE, CODICERESPONSABILE);
ALTER TABLE ALBEROPROC ADD CONSTRAINT FK_ALBEROPROC_RESPISTRUTTORIA FOREIGN KEY (IDCOMUNE,CODICERESPISTRUTTORIA) REFERENCES RESPONSABILI (IDCOMUNE, CODICERESPONSABILE);
ALTER TABLE AMMINISTRAZIONIRESPONSABILI ADD CONSTRAINT FK_AMMRESP_RESPONSABILI FOREIGN KEY (IDCOMUNE,CODICERESPONSABILE) REFERENCES RESPONSABILI (IDCOMUNE, CODICERESPONSABILE);
ALTER TABLE ALBEROPROC ADD CONSTRAINT FK_ALBEROPROC_RESPPROC FOREIGN KEY (IDCOMUNE,CODICERESPONSABILE) REFERENCES RESPONSABILI (IDCOMUNE, CODICERESPONSABILE);
ALTER TABLE MOVIMENTI ADD CONSTRAINT FK_MOVIMENTI_RESPONS FOREIGN KEY (IDCOMUNE,CODICERESPONSABILE) REFERENCES RESPONSABILI (IDCOMUNE, CODICERESPONSABILE);
ALTER TABLE CLPERMMENU ADD CONSTRAINT FK_CLPERMMENU_RESPONSABILI FOREIGN KEY (IDCOMUNE,CODICERESPONSABILE) REFERENCES RESPONSABILI (IDCOMUNE, CODICERESPONSABILE);
ALTER TABLE RESPONSABILICOMUNI ADD CONSTRAINT FK_RESPCOMUNI_RESPONSABILI FOREIGN KEY (IDCOMUNE,CODICERESPONSABILE) REFERENCES RESPONSABILI (IDCOMUNE, CODICERESPONSABILE);
ALTER TABLE ISTANZE ADD CONSTRAINT FK_ISTANZE_RESPISTRUT FOREIGN KEY (IDCOMUNE,CODICEISTRUTTORE) REFERENCES RESPONSABILI (IDCOMUNE, CODICERESPONSABILE);
ALTER TABLE ISTANZE ADD CONSTRAINT FK_ISTANZE_RESPPROC FOREIGN KEY (IDCOMUNE,CODICERESPONSABILEPROC) REFERENCES RESPONSABILI (IDCOMUNE, CODICERESPONSABILE);
ALTER TABLE ISTANZE ADD CONSTRAINT FK_ISTANZE_OPERATORI FOREIGN KEY (IDCOMUNE,CODICERESPONSABILE) REFERENCES RESPONSABILI (IDCOMUNE, CODICERESPONSABILE);
ALTER TABLE ISTANZEONERI ADD CONSTRAINT FK_ISTONERI_RESPONSABILI FOREIGN KEY (IDCOMUNE,CODICEUTENTE) REFERENCES RESPONSABILI (IDCOMUNE, CODICERESPONSABILE);
ALTER TABLE RESPONSABILISOFTWARE ADD CONSTRAINT FK_RESPSOFTWARE_RESPONSABILI FOREIGN KEY (IDCOMUNE,CODICERESPONSABILE) REFERENCES RESPONSABILI (IDCOMUNE, CODICERESPONSABILE);
ALTER TABLE RESPONSABILI ADD CONSTRAINT FK_RESPONSABILI_SCADOPE FOREIGN KEY (IDCOMUNE,SCAD_OPERATORE) REFERENCES RESPONSABILI (IDCOMUNE, CODICERESPONSABILE);
ALTER TABLE ALBEROPROC ADD CONSTRAINT FK_ALBEROPROC_OPESTC FOREIGN KEY (IDCOMUNE,CODICEOPERATORE_STC) REFERENCES RESPONSABILI (IDCOMUNE, CODICERESPONSABILE);
ALTER TABLE LINK_PREFERITI_UTENTE ADD CONSTRAINT FK_LINK_PREF_UTENTE_RESP FOREIGN KEY (IDCOMUNE,CODICERESPONSABILE) REFERENCES RESPONSABILI (IDCOMUNE, CODICERESPONSABILE);
ALTER TABLE DOCUMENTI_CONTABILITA ADD CONSTRAINT FK_DOC_CONTAB_RESP FOREIGN KEY (IDCOMUNE,CODICERESPONSABILE) REFERENCES RESPONSABILI (IDCOMUNE, CODICERESPONSABILE);
ALTER TABLE PEC_INBOX ADD CONSTRAINT PEC_INBOX_RESPONSABILI_FK1 FOREIGN KEY (IDCOMUNE,CODICEOPERATORE) REFERENCES RESPONSABILI (IDCOMUNE, CODICERESPONSABILE);
ALTER TABLE DOCUMENTI_DA_FIRMARE ADD CONSTRAINT DOCUMENTI_DA_FIRMARE_RESP_FK1 FOREIGN KEY (IDCOMUNE,CODICERICHIEDENTE) REFERENCES RESPONSABILI (IDCOMUNE, CODICERESPONSABILE);
ALTER TABLE DOCUMENTI_DA_FIRMARE ADD CONSTRAINT DOCUMENTI_DA_FIRMARE_RESP_FK2 FOREIGN KEY (IDCOMUNE,CODICEFIRMATARIO) REFERENCES RESPONSABILI (IDCOMUNE, CODICERESPONSABILE);
ALTER TABLE PEC_INBOX ADD CONSTRAINT PEC_INBOX_RESP_EVIDENZA FOREIGN KEY (IDCOMUNE,FK_RESP_EVIDENZA) REFERENCES RESPONSABILI (IDCOMUNE, CODICERESPONSABILE);

alter table anagrafedocumenti modify codiceanagrafe NUMERIC(6,0) NULL;
alter table anagrafedocumenti modify idtipodocumento NUMERIC(4,0) NULL;

CREATE INDEX IDX_OGGETTI_METADATI_001 ON OGGETTI_METADATI(IDCOMUNE, CHIAVE, VALORE);

CREATE TABLE ARCHIVIAZIONI (
IDCOMUNE VARCHAR(6) NOT NULL,
ID NUMERIC(10,0) NOT NULL,
ID_JOB VARCHAR(100) NOT NULL,
DATA DATE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE ARCHIVIAZIONI ADD CONSTRAINT PK_ARCHIVIAZIONI PRIMARY KEY(IDCOMUNE, ID);
CREATE TABLE ARCHIVIAZIONI_ISTANZE (
IDCOMUNE VARCHAR(6) NOT NULL,
ID NUMERIC(10,0) NOT NULL,
CODICEISTANZA NUMERIC(6,0) NOT NULL,
FK_ARCHIVIAZIONI_ID NUMERIC(10,0) NOT NULL,
PARZIALE NUMERIC(1,0) DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE ARCHIVIAZIONI_ISTANZE ADD CONSTRAINT PK_ARCHIVIAZIONI_ISTANZE PRIMARY KEY(IDCOMUNE, ID);
ALTER TABLE ARCHIVIAZIONI_ISTANZE ADD CONSTRAINT FK_ARCH_ISTANZE_ARCH FOREIGN KEY(IDCOMUNE, FK_ARCHIVIAZIONI_ID) REFERENCES ARCHIVIAZIONI (IDCOMUNE, ID);
ALTER TABLE ARCHIVIAZIONI_ISTANZE ADD CONSTRAINT FK_ARCH_ISTANZE_ISTANZE FOREIGN KEY(IDCOMUNE, CODICEISTANZA) REFERENCES ISTANZE (IDCOMUNE, CODICEISTANZA);

CREATE TABLE ARCHIVIAZIONI_OGGETTI (
IDCOMUNE VARCHAR(6) NOT NULL,
ID NUMERIC(10,0) NOT NULL,
FK_ARCHIVIAZIONI_ISTANZE_ID NUMERIC(10,0) NOT NULL,
FK_ARCHIVIAZIONI_ID NUMERIC(10,0) NOT NULL,
CODICEOGGETTO NUMERIC(10,0) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE ARCHIVIAZIONI_OGGETTI ADD CONSTRAINT PK_ARCHIVIAZIONI_OGGETTI PRIMARY KEY(IDCOMUNE, ID);
ALTER TABLE ARCHIVIAZIONI_OGGETTI ADD CONSTRAINT FK_ARCH_OGGETTI_ARCH_ISTANZE FOREIGN KEY(IDCOMUNE, FK_ARCHIVIAZIONI_ISTANZE_ID) REFERENCES ARCHIVIAZIONI_ISTANZE (IDCOMUNE, ID);
alter table ARCHIVIAZIONI_OGGETTI add constraint FK_ARCH_OGGETTI_ARCH_ID foreign key(IDCOMUNE, FK_ARCHIVIAZIONI_ID) references ARCHIVIAZIONI (IDCOMUNE, ID);
ALTER TABLE ARCHIVIAZIONI_OGGETTI ADD CONSTRAINT FK_ARCH_OGGETTI_OGGETTI FOREIGN KEY(IDCOMUNE, CODICEOGGETTO) REFERENCES OGGETTI (IDCOMUNE, CODICEOGGETTO);

ALTER TABLE INVENTARIOPROCDYN2MODELLIT ADD FK_TIPILOCALIZZAZIONE_ID NUMERIC(10);
ALTER TABLE INVENTARIOPROCDYN2MODELLIT ADD CONSTRAINT FK_TIPI_LOCALIZZAZIONE FOREIGN KEY (IDCOMUNE,FK_TIPILOCALIZZAZIONE_ID) REFERENCES TIPI_LOCALIZZAZIONI (IDCOMUNE,ID);
CREATE INDEX IDX_IATTIVITA_002 ON I_ATTIVITA(IDCOMUNE, DENOMINAZIONE);

CREATE TABLE JOB_REPOSITORY(
ID NUMERIC(6,0) NOT NULL,
IDCOMUNEALIAS VARCHAR(20),
JOB_NAME VARCHAR(255),
DESCRIPTION VARCHAR(255),
ACTIVE NUMERIC(1,0),
TRIGGER_TYPE VARCHAR(255),
START_DELAY NUMERIC(10,0),
REPEAT_INTERVAL NUMERIC(10,0),
CRON_EXPRESSION VARCHAR(255),
JOB_CLASS_NAME VARCHAR(255)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

ALTER TABLE JOB_REPOSITORY ADD CONSTRAINT PK_JOBREPOSITORY PRIMARY KEY (ID);
CREATE INDEX IDX_MOVIMENTIMAIL_MSGID ON MOVIMENTIMAIL (IDCOMUNE, MESSAGE_ID);
CREATE INDEX IDX_MOVIMENTIMAIL_IDPADRE ON MOVIMENTIMAIL (IDCOMUNE, ID_PADRE);
