ALTER TABLE dyn2_modellid MODIFY posorizzontale NUMBER(2,0);

ALTER TABLE PDF_MAPPATURE DROP PRIMARY KEY;
ALTER TABLE PDF_MAPPATURE MODIFY LABEL VARCHAR2(255);
alter table PDF_MAPPATURE ADD CONSTRAINT PK_PDF_MAPPATURE PRIMARY KEY (LABEL);

CREATE TABLE TIPI_LOCALIZZAZIONI 
(
  IDCOMUNE VARCHAR2(6 char) NOT NULL 
, ID NUMBER(10, 0) NOT NULL 
, DESCRIZIONE VARCHAR2(50 char) NOT NULL 
, CONSTRAINT TIPI_LOCALIZZAZIONI_PK PRIMARY KEY 
  (
    IDCOMUNE 
  , ID 
  )
);

ALTER TABLE istanzestradario ADD tipolocalizzazione_id NUMBER(10,0);
ALTER TABLE ISTANZESTRADARIO ADD CONSTRAINT FK_ISTANZESTRADARIO_TIPILOC FOREIGN KEY (IDCOMUNE, TIPOLOCALIZZAZIONE_ID) REFERENCES TIPI_LOCALIZZAZIONI( IDCOMUNE, ID );


ALTER TABLE istanzestradario ADD ( uuid VARCHAR2(50 char));
UPDATE istanzestradario SET uuid = Sys_Guid();

ALTER TABLE ISTANZESTRADARIO ADD LATITUDINE VARCHAR2(50);
ALTER TABLE ISTANZESTRADARIO ADD LONGITUDINE VARCHAR2(50);

ALTER TABLE MERCATI ADD TIPOCONTEGGIO_PRESENZE NUMBER (2,0);

COMMENT ON COLUMN MERCATI.TIPOCONTEGGIO_PRESENZE IS '1 - Assegna per ogni giornata; 2 - Assegna presenza unica';


CREATE OR REPLACE FORCE VIEW VW_MERCATIPRESENZETOTALI (ORIGINE, IDCOMUNE, ANNO, CODICEANAGRAFE, FK_AUTORIZZAZIONI_ID, FKCODICEMERCATO, FKIDMERCATIUSO, FKIDPOSTEGGIO, NUMEROPRESENZE, ANAGRAFE, CODICEFISCALE, PARTITAIVA, COMUNERESIDENZA, CITTADINANZA, DATAREGDITTE) AS SELECT 'STORICO' AS ORIGINE, MERCATIPRESENZE_STORICO.IDCOMUNE, MERCATIPRESENZE_STORICO.ANNO, MERCATIPRESENZE_STORICO.CODICEANAGRAFE, MERCATIPRESENZE_STORICO.FK_AUTORIZZAZIONI_ID, MERCATIPRESENZE_STORICO.FKCODICEMERCATO, MERCATIPRESENZE_STORICO.FKIDMERCATIUSO, MERCATIPRESENZE_STORICO.FK_IDPOSTEGGIO AS FKIDPOSTEGGIO, MERCATIPRESENZE_STORICO.NUMEROPRESENZE, TRIM( ANAGRAFE.NOMINATIVO || ' ' || ANAGRAFE.NOME ) AS ANAGRAFE, ANAGRAFE.CODICEFISCALE, ANAGRAFE.PARTITAIVA, COMUNI.COMUNE AS COMUNERESIDENZA, CITTADINANZA.CITTADINANZA, TO_CHAR(ANAGRAFE.DATAREGDITTE, 'DD/MM/YYYY' ) AS DATAREGDITTE FROM MERCATIPRESENZE_STORICO, ANAGRAFE, COMUNI, CITTADINANZA WHERE ANAGRAFE.IDCOMUNE = MERCATIPRESENZE_STORICO.IDCOMUNE AND ANAGRAFE.CODICEANAGRAFE = MERCATIPRESENZE_STORICO.CODICEANAGRAFE AND COMUNI.CODICECOMUNE(+) = ANAGRAFE.COMUNERESIDENZA AND CITTADINANZA.CODICE(+) = ANAGRAFE.CODICECITTADINANZA UNION ALL SELECT 'CALENDARIO' AS ORIGINE, MERCATIPRESENZE_T.IDCOMUNE, MERCATIPRESENZE_T.ANNO, MERCATIPRESENZE_D.CODICEANAGRAFE, MERCATIPRESENZE_D.FK_AUTORIZZAZIONI_ID, MERCATIPRESENZE_T.FKCODICEMERCATO, MERCATIPRESENZE_T.FKIDMERCATIUSO, MERCATIPRESENZE_D.FKIDPOSTEGGIO, MERCATIPRESENZE_D.NUMEROPRESENZE, TRIM( ANAGRAFE.NOMINATIVO || ' ' || ANAGRAFE.NOME ) AS ANAGRAFE, ANAGRAFE.CODICEFISCALE, ANAGRAFE.PARTITAIVA, COMUNI.COMUNE AS COMUNERESIDENZA, CITTADINANZA.CITTADINANZA, TO_CHAR(ANAGRAFE.DATAREGDITTE, 'DD/MM/YYYY' ) AS DATAREGDITTE FROM MERCATIPRESENZE_T, MERCATIPRESENZE_D, ANAGRAFE, COMUNI, CITTADINANZA WHERE ANAGRAFE.IDCOMUNE = MERCATIPRESENZE_D.IDCOMUNE AND ANAGRAFE.CODICEANAGRAFE = MERCATIPRESENZE_D.CODICEANAGRAFE AND COMUNI.CODICECOMUNE(+) = ANAGRAFE.COMUNERESIDENZA AND CITTADINANZA.CODICE(+) = ANAGRAFE.CODICECITTADINANZA AND MERCATIPRESENZE_D.IDCOMUNE = MERCATIPRESENZE_T.IDCOMUNE AND MERCATIPRESENZE_D.FKIDTESTATA = MERCATIPRESENZE_T.ID;

ALTER TABLE PEC_INBOX ADD (IN_LOGINNAME VARCHAR2(320 CHAR) );

CREATE TABLE MERCATI_ELABPRESENZE(
IDCOMUNE  VARCHAR2(6) NOT NULL,
ID        NUMBER(4,0) NOT NULL,
FK_CODICEMERCATO NUMBER(4,0) NOT NULL,
ANNO NUMBER(4,0) NOT NULL,
DATA_ELABORAZIONE DATE
);
ALTER TABLE MERCATI_ELABPRESENZE ADD CONSTRAINT PK_MERCATIELABPRE PRIMARY KEY (IDCOMUNE, ID);
ALTER TABLE MERCATI_ELABPRESENZE ADD CONSTRAINT FK_MERELABP_MERCATI FOREIGN KEY (IDCOMUNE, FK_CODICEMERCATO) REFERENCES MERCATI(IDCOMUNE, CODICEMERCATO);
ALTER TABLE MERCATIPRESENZE_D MODIFY PROPRIETARIO NUMBER(4,0);

alter table ISTANZEALLEGATI add (NECESSARIO NUMBER(1, 0));
COMMENT ON COLUMN ISTANZEALLEGATI.VERIFICATO IS 'Dismesso vedi redmine segnalazione num 485';
alter table DOCUMENTIISTANZA add (CONTROLLOOK NUMBER(1, 0));
alter table MOVIMENTIALLEGATI add (CONTROLLOOK NUMBER(1, 0));

ALTER TABLE CONTENTTYPES MODIFY CT_MIMETYPE VARCHAR2(100);

ALTER TABLE DYN2_MODELLID MODIFY POSORIZZONTALE NUMBER(2,0);

ALTER TABLE TIPIMOV_STC_MAPPING ADD FLAG_NOTIFICAINTERAPRATICA NUMBER(1,0);