//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System;
using System.Xml.Serialization;

namespace VBG.Backend.Protocollo.AppLogic.Core.Auriga.Folder.TrovaDocFolder
{

    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlRoot("Lista", Namespace = "", IsNullable = false)]
    public class Lista
    {
        [XmlElement("Riga")]
        public List<Riga> Righe { get; set; } = new List<Riga>();

        [XmlAttribute("NroTotaleRecord")]
        public int NroTotaleRecord { get; set; }

        [XmlAttribute("NroPagine")]
        public int NroPagine { get; set; }
    }

    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    public class Riga
    {
        [XmlElement("Colonna")]
        public List<Colonna> Colonne { get; set; } = new List<Colonna>();
    }

    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    public class Colonna
    {
        [XmlAttribute("Nro")]
        public int Nro { get; set; }

        [XmlText]
        public string Valore { get; set; }
    }
}