INSERT INTO MAPOGGETTI(NOMETABELLA, NOMECAMPO) VALUES ('PAYER_LOG','CODICEOGGETTO');

UPDATE FO_ARJ_STEPS_BASE SET DIPENDE_DA_STEP='INTERVENTO' WHERE NOME_STEP='INSERIMENTO_ANAGRAFICHE' OR NOME_STEP='INSERIMENTO_ANAGRAFE_DEFAULT';
UPDATE FO_ARJ_STEPS_BASE SET ordine_default=5 WHERE  NOME_STEP='INSERIMENTO_ANAGRAFICHE' OR NOME_STEP='INSERIMENTO_ANAGRAFE_DEFAULT';
UPDATE FO_ARJ_STEPS_BASE SET ordine_default=3 WHERE  NOME_STEP='INTERVENTO';

UPDATE FO_ARJ_DOMANDE SET FLAG_INVALIDATA=0 WHERE FLAG_INVALIDATA IS NULL;

INSERT INTO CLMENU_JAVA (ID, DESCRIZIONE,PAGINA,MENULINK,SOFTWARE,JSP,LAYOUTTESTI,VERTICALIZZAZIONE,SOFTWAREESCLUSI,LINK_STANDARD,TIPO_FUNZIONALITA) VALUES  (1008,'Domande da Frontend in compilazione','foarjdomande/list.htm?software=SOFTWARE','5S3','*','JAVA',0,NULL,'PR,FI,AB','foarjdomande/list.htm?software=SOFTWARE','S');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_HALLEY','URL_WS_DIZIONARIO','Inserire qui l''endpoint che indica il web service per fare le chiamate alle funzionalità di recupero dati relativo alle classifiche e uffici');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_HALLEY','USA_WS_CLASSIFICHE','Se = a 1 indica che le classifiche devono essere recuperate tramite web service messo a disposizione dal protocollo halley, altrimenti il sistema funzionerà in maniera standard, ossia mappando le varie classifiche direttamente sull''albero degli interventi. Questo parametro è direttamente legato al parametro URL_WS_DIZIONARIO, infatti se si decide di recuperare le classifiche da web service, deve ovviamente essere indicato anche l''end point del web service'); 

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('AREA_RISERVATA','RETURN_TO_URL_PER_SERVIZI','Specifica l''url a cui tornare quando si accede all''Area Riservata tramite url parlante');

insert into VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) values('AREA_RISERVATA','CENTRO_SERVIZI','Se 1 vengono abilitate le funzionalità di Centro Servizi che permettono di attivare un intervento attraverso una url diretta con possibilità di configurare se è un servizio autenticato e chi è il destinatario del servizio (nodo BACKOFFICE , nodo PEC, altro nodo). Per l''accesso diretto ad un singolo servizio tramite url parlante configurare il parametro CENTRO_SERVIZI_URL_BREVI');

insert into VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) values('AREA_RISERVATA','CENTRO_SERVIZI_URL_BREVI','Ha valore solo se attivo il parametro CENTRO_SERVIZI. Se presente vincola l''accesso all''Area Riservata solo tramite url parlanti es. /servizi/servizio001');

DELETE FROM FO_ARJ_STEPS;
DELETE FROM FO_ARJ_STEPS_BASE;


Insert into FO_ARJ_STEPS_BASE (NOME_STEP,LINK_FUNZIONE,TITOLO,DESCRIZIONE,FLAG_OBBLIGATORIO,DIPENDE_DA_STEP,INCOMPATIBILE_CON_STEP,ORDINE_DEFAULT) values ('BENVENUTO','../nuovaistanzabenvenuto/view.htm','Benvenuto','Le pagine che seguono rappresentano il percorso guidato per la presentazione on line di una istanza.<br />Il percorso per inviare la pratica on line è composto da una serie di step (schede).<br />In fondo a destra si trova la numerazione delle pagine e in nero viene evidenziato lo step che si sta compilando.','0',null,null,'1');


Insert into FO_ARJ_STEPS_BASE (NOME_STEP,LINK_FUNZIONE,TITOLO,DESCRIZIONE,FLAG_OBBLIGATORIO,DIPENDE_DA_STEP,INCOMPATIBILE_CON_STEP,ORDINE_DEFAULT) values ('INFORMATIVA','../nuovaistanzainformativa/view.htm','Informativa privacy','INFORMATIVA AI SENSI DELL''ART. 13 DEL DECRETO LEGISLATIVO N. 196/2003, "CODICE IN MATERIA DI PROTEZIONE DEI DATI PERSONALI"
 
Si informa, ai sensi dell''art. 13 del D. Lgs. n. 196 del 30 giugno 2003 ("Codice in materia di protezione dei dati personali"), che il Comune di Ponteratto, in qualità di "Titolare" del trattamento, è tenuto a fornirle informazioni in merito all''utilizzo dei suoi dati personali.
Per trattamento si intende qualunque operazione o complesso di operazioni concernenti "la raccolta, la registrazione, l''organizzazione, la conservazione, la consultazione, l''elaborazione, la modificazione, la selezione, l''estrazione, il raffronto, l''utilizzo,l''interconnessione, il blocco, la comunicazione, la diffusione, la cancellazione e la distruzione di dati, anche se non registrati in una banca dati".
La raccolta dei suoi dati personali viene effettuata registrando i dati da lei stesso forniti, in qualità di interessato, al momento della iscrizione al sistema di autenticazione federato.
 
I dati personali sono trattati per le finalità previste dal procedimento. Per garantire l''efficienza del servizio la informiamo inoltre che i dati potrebbero essere utilizzati per effettuare prove tecniche e di verifica.
In relazione alle finalità descritte, il trattamento dei dati personali avviene mediante strumenti manuali, informatici e telematici con logiche strettamente correlate alle finalità sopra evidenziate e, comunque, in modo da garantire la sicurezza e la riservatezza dei dati stessi. Adempiute le finalità prefissate, i dati verranno cancellati o trasformati in forma anonima.
 
Ai sensi dell''art. 13, 1° comma lett. b) e c), si evidenzia che il trattamento dei dati da parte del Comune è essenziale per l''adempimento degli obblighi di legge e che, pertanto, il mancato conferimento di tali dati impedisce l''utilizzo del servizio offerto on line.
I suoi dati personali potranno essere conosciuti esclusivamente dagli operatori dell''ufficio del SUAP del Comune di Ponteratto e da tutti gli operatori degli altri uffici comunali interessati dal procedimento, individuati quali Incaricati del trattamento.
Si precisa inoltre che i dati verranno comunicati a terzi esclusivamente in adempimento di specifici obblighi di legge, ovvero qualora tale comunicazione risulti necessaria o funzionale alla gestione del servizio, previa designazione in qualità di Responsabili del trattamento e garantendo il medesimo livello di protezione.
 
Si informa, infine, che l''art. 7 del Decreto Legislativo n. 196/2003, riportato di seguito integralmente, attribuisce all''interessato specifici diritti a garanzia della corretta acquisizione e del corretto utilizzo dei dati trattati ed in particolare:
L''interessato ha diritto di ottenere la conferma dell''esistenza o meno di dati personali che lo riguardano, anche se non ancora registrati, e la loro comunicazione in forma intelligibile.L''interessato ha diritto di ottenere l''indicazione: 
dell''origine dei dati personali;
delle finalità e modalità del trattamento; della logica applicata in caso di trattamento effettuato con l''ausilio di strumenti elettronici; degli estremi identificativi del titolare, dei responsabili e del rappresentante designato ai sensi dell''articolo 5, comma 2; dei soggetti o delle categorie di soggetti ai quali i dati personali possono essere comunicati o che possono venirne a conoscenza in qualità di rappresentante designato nel territorio dello Stato, di responsabili o incaricati. 
L''interessato ha diritto di ottenere:l''aggiornamento, la rettificazione ovvero, quando vi ha interesse, l''integrazione dei dati; la cancellazione, la trasformazione in forma anonima o il blocco dei dati trattati in violazione di legge, compresi quelli di cui non è necessaria la conservazione in relazione agli scopi per i quali i dati sono stati raccolti o successivamente trattati; ','0',null,null,'2'); 
Insert into FO_ARJ_STEPS_BASE (NOME_STEP,LINK_FUNZIONE,TITOLO,DESCRIZIONE,FLAG_OBBLIGATORIO,DIPENDE_DA_STEP,INCOMPATIBILE_CON_STEP,ORDINE_DEFAULT) values ('ANAGRAFE','../nuovaistanzaanagrafesingola/view.htm','Anagrafe','In questa scheda vanno inseriti tutti i soggetti, persone fisiche e giuridiche, coinvolti nella pratica che si sta presentando. I soggetti possono essere l''interessato, l''azienda coinvolta, l''intermediario ...','0','INTERVENTO','(null)','3');
Insert into FO_ARJ_STEPS_BASE (NOME_STEP,LINK_FUNZIONE,TITOLO,DESCRIZIONE,FLAG_OBBLIGATORIO,DIPENDE_DA_STEP,INCOMPATIBILE_CON_STEP,ORDINE_DEFAULT) values ('LOCALIZZAZIONE','../nuovaistanzalocalizzazione/view.htm','Localizzazione','È possibile in questa sezione inserire nel campo "Indirizzo" la localizzazione dell''intervento. <br />Selezionare un indirizzo compreso nello stradario comunale dopo aver digitato nel campo "Denominazione" almeno due lettere della localizzazione, quindi completare l''indirizzo indicando il civico ed eventuali note.<br />Se l''intervento ricade in una zona ancora non censita digitare "NON DEFINITO" nel campo "Denominazione" e nel campo "Note" immettere una localizzazione di massima (frazione, zona, etc.)','0',null,null,'4'); 
Insert into FO_ARJ_STEPS_BASE (NOME_STEP,LINK_FUNZIONE,TITOLO,DESCRIZIONE,FLAG_OBBLIGATORIO,DIPENDE_DA_STEP,INCOMPATIBILE_CON_STEP,ORDINE_DEFAULT) values ('INTERVENTO','../nuovaistanzaintervento/view.htm','Intervento','In questa sezione è possibile individuare l''attività della propria azienda secondo la classificazione adottata dallo sportello unico del comune','0',null,null,'5'); 
Insert into FO_ARJ_STEPS_BASE (NOME_STEP,LINK_FUNZIONE,TITOLO,DESCRIZIONE,FLAG_OBBLIGATORIO,DIPENDE_DA_STEP,INCOMPATIBILE_CON_STEP,ORDINE_DEFAULT) values ('PROCEDIMENTI','../nuovaistanzaprocedimenti/view.htm','Procedimenti','In questa sezione è possibile attivare gli endoprocedimenti utili al completamento dell''istanza.<br />Gli endo-procedimenti già selezionati sono proposti dal sistema in base alla compilazione degli step precedenti.','0','INTERVENTO',null,'6');
Insert into FO_ARJ_STEPS_BASE (NOME_STEP,LINK_FUNZIONE,TITOLO,DESCRIZIONE,FLAG_OBBLIGATORIO,DIPENDE_DA_STEP,INCOMPATIBILE_CON_STEP,ORDINE_DEFAULT) values ('ALLEGATI','../nuovaistanzaallegati/view.htm','Allegati','Gli allegati che riportano il simbolo (<b>*</b>) sono obbligatori. Sarà cura del richiedente o della persona incaricata allegare i documenti proposti nell''elenco. <br />Il bottone "Sfoglia" permette di cercare il documento da caricare , una volta selezionato cliccare sulla voce "Carica". <br />','0','INTERVENTO',null,'7'); 
Insert into FO_ARJ_STEPS_BASE (NOME_STEP,LINK_FUNZIONE,TITOLO,DESCRIZIONE,FLAG_OBBLIGATORIO,DIPENDE_DA_STEP,INCOMPATIBILE_CON_STEP,ORDINE_DEFAULT) values ('SCHEDE','../nuovaistanzaschede/view.htm','Schede','...','0','INTERVENTO',null,'8');
Insert into FO_ARJ_STEPS_BASE (NOME_STEP,LINK_FUNZIONE,TITOLO,DESCRIZIONE,FLAG_OBBLIGATORIO,DIPENDE_DA_STEP,INCOMPATIBILE_CON_STEP,ORDINE_DEFAULT) values ('ONERI','../nuovaistanzaoneri/view.htm','Riepilogo diritti/oneri','Questa scheda riepiloga quanti diritti di istruttoria/oneri/bolli devono essere corrisposti con riferimento all''intervento e agli endoprocedimenti attivati.
Per i pagamenti per i quali si possiede già la ricevuta si ricorda che questa deve essere firmata digitalmente. I pagamenti possono essere effettuati mediante bollettino utilizzando le seguenti coordinate: 
<b>c/c postale n. XXXX intestato a Comune di XXXXX- Direzione XXXXXX.</b>','0','INTERVENTO',null,'9');


INSERT INTO verticalizzazionibase(modulo, descrizione) VALUES('PROTOCOLLO_EGRAMMATA', 'Se attivato consente di eseguire la protocollazione con il protocollo EGRAMMATA, al momento non abbiamo a disposizioni ambienti di test.');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES('PROTOCOLLO_EGRAMMATA', 'URL_PROTO', 'Indicare l''url del web service da contattare per eseguire l''inserimento di un protocollo con il sistema di protocollazione e-grammata');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES('PROTOCOLLO_EGRAMMATA', 'URL_LEGGI', 'Indicare l''url del web service da contattare per eseguire la lettura di un protocollo con il sistema di protocollazione e-grammata');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES('PROTOCOLLO_EGRAMMATA', 'USER_ID', 'Indicare qui l''userid dell''utente con cui invocare il sistema di protocollazione, le credenziali sono le stesse degli utenti già presenti nel software di protocollo.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES('PROTOCOLLO_EGRAMMATA', 'PASSWORD', 'Indicare qui la password dell''utente con cui invocare il sistema di protocollazione, le credenziali sono le stesse degli utenti già presenti nel software di protocollo.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES('PROTOCOLLO_EGRAMMATA', 'ID_UNITA', '[Facoltativo] Indica l''identificativo della postazione di lavoro dell''utente nel caso in cui l''utente stesso abbia più postazioni di lavoro, questo parametro è dello stesso tipo del parametro LIVELLI_UNITA, in questo caso è possibile usare indifferentemente uno o entrambi i parametri se richiesti.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES('PROTOCOLLO_EGRAMMATA', 'LIVELLI_UNITA', '[Facoltativo] Indica il livello della postazione di lavoro dell''utente nel caso in cui l''utente stesso abbia più postazioni di lavoro, questo parametro è dello stesso tipo del parametro ID_UNITA, in questo caso è possibile usare indifferentemente uno o entrambi i parametri se richiesti.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES('PROTOCOLLO_EGRAMMATA', 'REGISTRO', 'Indicare il registro da usare per eseguire l''inserimento dei protocolli. Valori ammessi: PG=Protocollo Generale; PP=Protocollo Particolare; R=Repertorio; N=Corrispondenza non protocollata'); 

INSERT INTO MAPOGGETTI VALUES ('GRADUATORIED_COM','CODICEOGGETTO');
INSERT INTO ELENCHIPROFESSIONALIBASE(EP_ID, EP_DESCRIZIONE, EP_ATRIBCODICE) VALUES (19,'Ordine dei biologi',6);
UPDATE ELENCHIPROFESSIONALIBASE SET EP_ATRIBCODICE = 6 WHERE EP_ID IN ( 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7);

INSERT INTO COMUNI(CODICECOMUNE, COMUNE, SIGLAPROVINCIA, PROVINCIA, REGIONE, CF, CODICEISTATREGIONE) VALUES ('E254', 'GUAZZINA', 'MI', 'MILANO', 'LOMBARDIA', 'E254', '03');
INSERT INTO COMUNI(CODICECOMUNE, COMUNE, SIGLAPROVINCIA, PROVINCIA, REGIONE, CF, CODICEISTATREGIONE) VALUES ('D625', 'FIUMENERO', 'BG', 'BERGAMO', 'LOMBARDIA', 'D625', '03');
INSERT INTO COMUNI(CODICECOMUNE, COMUNE, SIGLAPROVINCIA, PROVINCIA, REGIONE, CF, CODICEISTATREGIONE) VALUES ('H510', 'ROMANO'' BRIANZA', 'CO', 'COMO', 'LOMBARDIA', 'H510', '03');

INSERT INTO VERTICALIZZAZIONIBASE(MODULO, DESCRIZIONE) VALUES('GENERA_COD_PRATICA_TELEMATICA','Se attivata consente di generare il codice pratica telematica nella fase di inserimento dell''istanza nel caso questo non venga passato.');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES('PROTOCOLLO_SIGEDO','URL_CGI_UO','Se valorizzato indica l''url cgi da chiamare per ottenere l''uo in base all''utente corrente che effettua la protocollazione, questo sistema è stato studiato solamente per il Comune di Firenze perchè si verificava il caso che alcuni utenti, non facenti parte all''uo indicata nel parametro UO, non potevano leggere i protocolli, nemmeno se erano stati loro stessi a crearli. L''applicativo cgi è stato sviluppato da Fabio Lo Giudice del Comune di Firenze. In questo parametro va specificato l''url inserendo la stringa fino al parametro di querystring senza inserirne il valore, ad esempio: http://url_cgi_per_restituire_la_uo?MATRICOLA=');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_SIGEDO', 'DESCRIZIONE_ENTE', 'Indicare in questo parametro la descrizione dell''ente, ad esempio - COMUNE DI FIRENZE -, questo valore andrà preso in considerazione nel caso in cui, durante una lettura di un protocollo in partenza, non venga individuato l''ufficio (smistamento) mittente del protocollo stesso; in questo caso il mittente prenderà il valore inserito in questo parametro'); 

INSERT INTO MAPOGGETTI(NOMETABELLA, NOMECAMPO) VALUES ('TIPIPROCEDURE','CODOGGETTO_RICEVUTACART');

INSERT INTO RI_FORMEGIURIDICHE(CODICE,DESCRIZIONE) VALUES('RS','SOCIETA'' A RESPONSABILITA'' LIMITATA SEMPLIFICATA');
INSERT INTO RI_FORMEGIURIDICHE(CODICE,DESCRIZIONE) VALUES('RR','SOCIETA'' A RESPONSABILITA'' LIMITATA A CAPITALE RIDOTTO');

INSERT INTO CATEGORIEEVENTIBASE (ID, DESCRIZIONE) VALUES ('COMUN-GRADUAT','Eventi relativi all''invio delle comunicazioni per le graduatorie');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) VALUES('PAYER_ADAPTER','USA_CODICEFISCALE_TECNICO','Valori possibili S o N. Se S allora il codice fiscale passato, utilizzato per recuperare le scadenze di pagamento, viene ricercato sia nel campo del richiedente (ISTANZE.CODICERICHIEDENTE) che in quello del tecnico dell''istanza (ISTANZE.CODICEPROFESSIONISTA). Di default (se valore vuoto o non presente) il codice fiscale viene ricercato solamente in quello del richiedente dell''istanza (ISTANZE.CODICERICHIEDENTE).');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE)VALUES('PAYER_ADAPTER','TIPOLOGIA_SERVIZIO','Indica il valore che viene inviato da PayER nel tag RequestResponseLista.tipologiaServizio e RecuperaDatiBollettinoResponse.tipologiaServizio. Il valore deve essere concordato con Lepida e deve essere configurato obbligatoriamente.' );

INSERT INTO MAPOGGETTI (NOMETABELLA, NOMECAMPO) VALUES ('PEC_INBOX','CODICEOGGETTOPROTOCOLLO');
INSERT INTO MAPOGGETTI (NOMETABELLA, NOMECAMPO) VALUES ('PEC_INBOX_ALLEGATI','CODICEOGGETTO');

INSERT INTO SOFTWARE (CODICE,DESCRIZIONE, MODULOOPZIONALE,DESCRIZIONELUNGA,ACCESSORAPIDO, ORDINE) VALUES ('TA','TARES',1,'Tributo comunale sui Rifiuti e sui Servizi',0,53);

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PEOPLE', 'IMPORT_XML_PEOPLE', 'I valori ammessi sono S o N. Se posto a S, nei documenti associati all''istanza viene inserito l''XML della pratica PEOPLE, se valorizzato a N o non valorizzato, tale file non viene inserito.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PEOPLE', 'XMLMOD_ESPONENTE', 'Parametro per individuare l''esponente della localizzazione nella pratica people tramite identificativo XML_MOD');

INSERT INTO VERTICALIZZAZIONIBASE (MODULO, DESCRIZIONE) VALUES ('TARES_BARI','Gestione delle domande TARES del comune di Bari');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO, DESCRIZIONE) VALUES ('TARES_BARI','URL_SERVIZIO','Indirizzo del web service dei servizi TARES');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO, DESCRIZIONE) VALUES ('TARES_BARI','IDENTIFICATIVO_UTENTE','Nome utente da utilizzare per le chiamate al web service');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO, DESCRIZIONE) VALUES ('TARES_BARI','PASSWORD','Password da utilizzare per le chiamate al web service');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO, DESCRIZIONE) VALUES ('TARES_BARI','INDIRIZZO_PEC','Indirizzo pec (utilizzo non chiaro)');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO, DESCRIZIONE) VALUES ('AREA_RISERVATA','URL_PAGINA_INIZIALE','Url della pagina iniziale dell''area riservata');
UPDATE PEC_INBOX SET FLAG_PROCESSATA=1, FLAG_CANCELLATA=1;
INSERT INTO CLMENU_JAVA(ID,DESCRIZIONE,PAGINA,MENULINK,SOFTWARE,JSP,LAYOUTTESTI,VERTICALIZZAZIONE,SOFTWAREESCLUSI,LINK_STANDARD,TIPO_FUNZIONALITA) VALUES (1009,'Pannello gestione PEC','pecinbox/inbox.htm?software=SOFTWARE','109','*','JAVA',0,NULL, 'PR,FI,AB','pecinbox/inbox.htm?software=SOFTWARE','E');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) VALUES('NLA-RICEZIONE-PEC','INVIA_EVENTO_N_MSG_NONLETTI','Dopo ogni processamento se non presente (o = S) viene inserito un evento che riporta in descrizione il numero di messaggi da leggere presenti nella casella PEC alla in cui è stata eseguita la funzionalità di processaMessaggi');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) VALUES ('PROTOCOLLO_ATTIVO','COD_ALBERO_ROOT_PROTOCOLL','E'' il codice della voce d''albero degli interventi che la funzionalita'' "Pannello Gestione PEC" usa per recuperare la root per la creazione del controllo di selezione Intervento. Se non indicato o nullo vengono selezionate tutte le voci.');


INSERT INTO VERTICALIZZAZIONIBASE (MODULO, DESCRIZIONE) VALUES ('PROTOCOLLO_FOLIUM', 'Se attivato, consente di eseguire la protocollazione con il protocollo FOLIUM, questo protocollo è gestito dalla ditta DedaGroup ed è presente al Comune di Carmignano, non è stato fornito alcun ambiente di test, ma, modificando il registro (parametro registro) si può accedere ad un eventuale ambiente di test creato dal cliente.');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_FOLIUM', 'URL', '(Obbligatorio) Indicare qui l''indirizzo del web service di protocollazione.');
 
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_FOLIUM', 'REGISTRO', 'Inserire il valore del registro da utilizzare in fase di inserimento protocollo e in fase di lettura protocollo, il valore inserito può discriminare un ambiente di test da quello di produzione, se non specificato automaticamente sarà utilizzato l''ambiente di produzione.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_FOLIUM', 'USERNAME', '(Obbligatorio) Username di autenticazione ad ogni metodo del web service del protocollo FOLIUM. Ogni metodo del web service infatti richiede come parametro fisso anche la classe WSAuthentication nella quale deve essere specificata la proprietà username che corrisponderà a questo parametro.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_FOLIUM', 'PASSWORD', '(Obbligatorio) Password di autenticazione ad ogni metodo del web service del protocollo FOLIUM. Ogni metodo del web service infatti richiede come parametro fisso anche la classe WSAuthentication nella quale deve essere specificata la proprietà password che corrisponderà a questo parametro.');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_FOLIUM', 'CODICE_ENTE', '(Obbligatorio) Codice Ente di autenticazione ad ogni metodo del web service del protocollo FOLIUM. Ogni metodo del web service infatti richiede come parametro fisso anche la classe WSAuthentication nella quale deve essere specificata la proprietà codiceente che corrisponderà a questo parametro.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_FOLIUM', 'APPLICAZIONE', '(Obbligatorio) Applicazione chiamante al web service, questo parametro fa parte dell''autenticazione che viene invocata ad ogni metodo del web service del protocollo FOLIUM. Ogni metodo del web service infatti richiede come parametro fisso anche la classe WSAuthentication nella quale deve essere specificata la proprietà applicazione che corrisponderà a questo parametro.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_FOLIUM', 'AOO', '(Obbligatorio) Codice Aoo, questo parametro fa parte dell''autenticazione che viene invocata ad ogni metodo del web service del protocollo FOLIUM. Ogni metodo del web service infatti richiede come parametro fisso anche la classe WSAuthentication nella quale deve essere specificata la proprietà aoo che corrisponderà a questo parametro.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_FOLIUM', 'BINDING', 'Indicare in questo parametro il nome del binding che il componente client deve usare per creare la connessione al web service, se non non valorizzato verrà usato quello di default (defaultHttpBinding)');

UPDATE CLMENU_JAVA SET PAGINA='nlaservizi/list.htm?software=SOFTWARE',SOFTWARE='*',SOFTWAREESCLUSI='PR,FI,AB',LINK_STANDARD='nlaservizi/list.htm?software=SOFTWARE', TIPO_FUNZIONALITA='S' WHERE ID=1007;
UPDATE CLMENU_JAVA SET LINK_STANDARD=PAGINA WHERE ID IN(873,457);
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_FOLIUM', 'CODICE_CC', 'Indica il codice per conoscenza da utilizzare in fase di protocollazione. Sulla maschera di protocollazione è presente un campo a tendina denominato -Trasmesso per- legato all''anagrafica (Mittente / Destinatario), questo campo viene popolato dai valori presenti nella tabella PROTOCOLLO_MODALITAINVIO, indicando il codice in questo campo, quando l''operatore selezionerà nella tendina -Trasmesso per- il valore con lo stesso codice, l''anagrafica selezionata sarà considerata per conoscenza. Se non valorizzato il destinatario (mittente) del protocollo non sarà mai per conoscenza.');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_DOCPRO', 'CODICEAMMINISTRAZIONE', 'Indicare in questo parametro il Codice dell''amministrazione, questo dato andrà a valorizzare gli elementi CODICEAMMINISTRAZIONE della segnatura che viene inviata al metodo protocollazione del web service. Se non valorizzato questo dato verrà preso dal parametro CODICEENTE come succedeva in passato.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_DOCAREA', 'CODICEAMMINISTRAZIONE', 'Indicare in questo parametro il Codice dell''amministrazione, questo dato andrà a valorizzare gli elementi CODICEAMMINISTRAZIONE della segnatura che viene inviata al metodo protocollazione del web service. Se non valorizzato questo dato verrà preso dal parametro CODICEENTE come succedeva in passato.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_DOCER', 'CODICEAMMINISTRAZIONE', 'Indicare in questo parametro il Codice dell''amministrazione, questo dato andrà a valorizzare gli elementi CODICEAMMINISTRAZIONE della segnatura che viene inviata al metodo protocollazione del web service. Se non valorizzato questo dato verrà preso dal parametro CODICEENTE come succedeva in passato.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_HALLEY', 'CODICEAMMINISTRAZIONE', 'Indicare in questo parametro il Codice dell''amministrazione, questo dato andrà a valorizzare gli elementi CODICEAMMINISTRAZIONE della segnatura che viene inviata al metodo protocollazione del web service. Se non valorizzato questo dato verrà preso dal parametro CODICEENTE come succedeva in passato.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_SIGEDO', 'CODICEAMMINISTRAZIONE', 'Indicare in questo parametro il Codice dell''amministrazione, questo dato andrà a valorizzare gli elementi CODICEAMMINISTRAZIONE della segnatura che viene inviata al metodo protocollazione del web service. Se non valorizzato questo dato verrà preso dal parametro CODICEENTE come succedeva in passato.');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('NLA-RICEZIONE-PEC', 'CHECK_REPLY', 'I valori ammessi sono S o N. Se posto a S per ogni PEC presente nella INBOX controlla se si tratta di una Reply-to relativa ad una PEC inviata da VBG (ed in caso positivo genera il contromovimento associato al movimento da cui era stata inviata la PEC). Se posto a N o non valorizzato non vengono elaborate tali tipologie di PEC.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_FOLIUM', 'USA_WSCLASSIFICHE', 'Indica se per il recupero delle classifiche, sull''albero degli interventi, debba essere usato l''apposito metodo messo a disposizione dal web service (valore = 1) oppure no (valore 0, vuoto o non presente).');

UPDATE INVENTARIOPROC_TIPITITOLO SET FLG_MOSTRA_DATA=1,FLG_MOSTRA_NUMERO=1,FLG_MOSTRA_RILASCIATO_DA=1;

