package com.paevolution.appiogateway.utils;

public enum FieldEnum {
    ID_TRANSAZIONE, SENDER_ALLOWED, PREFERRED_LANGUAGES, CREATED_AT, WEBHOOK_NOTIFICATION, EMAIL_NOTIFICATION, STATUS, STATO_MESSAGGIO
}
