ALTER TABLE PROTOCOLLO_REGISTRI DROP FOREIGN KEY FK_PROTREG_TIPOLOGIAREG;
ALTER TABLE PROTOCOLLO_REGISTRI DROP PRIMARY KEY;
ALTER TABLE PROTOCOLLO_REGISTRI MODIFY ID NUMERIC(10,0) NOT NULL;

ALTER TABLE PROTOCOLLO_REGISTRI ADD CONSTRAINT PROTOCOLLO_REGISTRI_PK PRIMARY KEY (IDCOMUNE, ID);