ALTER TABLE ARCHIVIAZIONI ADD ERRORE VARCHAR(1000);

ALTER TABLE PROTOCOLLO_MEZZI ADD (CODICECOMUNE VARCHAR(5) );
ALTER TABLE PROTOCOLLO_MEZZI ADD (SOFTWARE VARCHAR(2) );
ALTER TABLE PROTOCOLLO_MEZZI ADD CONSTRAINT FK_PROT_MEZZ_COMUNI FOREIGN KEY(CODICECOMUNE) REFERENCES COMUNI (CODICECOMUNE); 
ALTER TABLE PROTOCOLLO_MEZZI ADD CONSTRAINT FK_PROT_MEZZ_SOFTWARE FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE (CODICE); 

ALTER TABLE PROTOCOLLO_MODALITAINVIO ADD (CODICECOMUNE VARCHAR(5) );
ALTER TABLE PROTOCOLLO_MODALITAINVIO ADD (SOFTWARE VARCHAR(2) );
ALTER TABLE PROTOCOLLO_MODALITAINVIO ADD CONSTRAINT FK_PROT_MOD_INV_COMUNI FOREIGN KEY(CODICECOMUNE) REFERENCES COMUNI (CODICECOMUNE); 
ALTER TABLE PROTOCOLLO_MODALITAINVIO ADD CONSTRAINT FK_PROT_MOD_INV_SOFTWARE FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE (CODICE);

ALTER TABLE PROTOCOLLO_SEQUENZE ADD (CODICECOMUNE VARCHAR(5) );
ALTER TABLE PROTOCOLLO_SEQUENZE ADD (SOFTWARE VARCHAR(2) );
ALTER TABLE PROTOCOLLO_SEQUENZE ADD CONSTRAINT FK_PROT_SEQUEN_COMUNI FOREIGN KEY(CODICECOMUNE) REFERENCES COMUNI (CODICECOMUNE); 
ALTER TABLE PROTOCOLLO_SEQUENZE ADD CONSTRAINT FK_PROT_SEQUEN_SOFTWARE FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE (CODICE);

ALTER TABLE PROTOCOLLO_SMISTAMENTI ADD (CODICECOMUNE VARCHAR(5) );
ALTER TABLE PROTOCOLLO_SMISTAMENTI ADD (SOFTWARE VARCHAR(2) );
ALTER TABLE PROTOCOLLO_SMISTAMENTI ADD CONSTRAINT FK_PROT_SMISTAM_COMUNI FOREIGN KEY(CODICECOMUNE) REFERENCES COMUNI (CODICECOMUNE); 
ALTER TABLE PROTOCOLLO_SMISTAMENTI ADD CONSTRAINT FK_PROT_SMISTAM_SOFTWARE FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE (CODICE);

ALTER TABLE PROTOCOLLO_TIPIDOCUMENTO ADD (CODICECOMUNE VARCHAR(5) );
ALTER TABLE PROTOCOLLO_TIPIDOCUMENTO ADD (SOFTWARE VARCHAR(2) );
ALTER TABLE PROTOCOLLO_TIPIDOCUMENTO ADD CONSTRAINT FK_PROT_TIPODOC_COMUNI FOREIGN KEY(CODICECOMUNE) REFERENCES COMUNI (CODICECOMUNE); 
ALTER TABLE PROTOCOLLO_TIPIDOCUMENTO ADD CONSTRAINT FK_PROT_TIPODOC_SOFTWARE FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE (CODICE);

ALTER TABLE PROTOCOLLO_UFFICIREGISTRI ADD (CODICECOMUNE VARCHAR(5) );
ALTER TABLE PROTOCOLLO_UFFICIREGISTRI ADD (SOFTWARE VARCHAR(2) );
ALTER TABLE PROTOCOLLO_UFFICIREGISTRI ADD CONSTRAINT FK_PROT_UFF_COMUNI FOREIGN KEY(CODICECOMUNE) REFERENCES COMUNI (CODICECOMUNE); 
ALTER TABLE PROTOCOLLO_UFFICIREGISTRI ADD CONSTRAINT FK_PROT_UFF_SOFTWARE FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE (CODICE);

CREATE TABLE AMMINISTR_PROTOCOLLO 
(
  IDCOMUNE VARCHAR(10) NOT NULL 
, ID NUMERIC(10, 0) NOT NULL 
, CODICECOMUNE VARCHAR(5) 
, CODICEAMMINISTRAZIONE NUMERIC (10,0)
, SOFTWARE VARCHAR(2) 
, PROT_UO VARCHAR(100) 
, PROT_RUOLO VARCHAR(100) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE AMMINISTR_PROTOCOLLO ADD CONSTRAINT PK_AMMINISTR_PROTOCOLLO PRIMARY KEY(IDCOMUNE, ID); 
ALTER TABLE AMMINISTR_PROTOCOLLO ADD CONSTRAINT FK_AMM_PROT_AMM FOREIGN KEY(IDCOMUNE, CODICEAMMINISTRAZIONE) REFERENCES AMMINISTRAZIONI (IDCOMUNE, CODICEAMMINISTRAZIONE); 
ALTER TABLE AMMINISTR_PROTOCOLLO ADD CONSTRAINT FK_AMM_PROT_COMUNI FOREIGN KEY(CODICECOMUNE) REFERENCES COMUNI (CODICECOMUNE); 
ALTER TABLE AMMINISTR_PROTOCOLLO ADD CONSTRAINT FK_AMM_PROT_SOFTWARE FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE (CODICE);


CREATE TABLE ALBEROPROC_PROTOCOLLO
(
IDCOMUNE VARCHAR(10) NOT NULL 
,ID NUMERIC (10, 0) NOT NULL 
,FKSCID NUMERIC (10, 0)
,CODICECOMUNE VARCHAR(5) 
,CODICEAMMINISTRAZIONE NUMERIC (10,0)
,SC_PROTCLASSIFICA VARCHAR(50) 
,SC_PROTTIPODOCUMENTO VARCHAR(50)
,SC_PROTCODTESTO NUMERIC (4, 0)
,SC_PROTAUTOMATICA NUMERIC (1, 0)
,SC_FASCCLASSIFICA VARCHAR(50)
,SC_FASCCODTESTO NUMERIC (4, 0)
,SC_FASCAUTOMATICA NUMERIC (1, 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE ALBEROPROC_PROTOCOLLO ADD CONSTRAINT PK_ALBER_PROTOCOLLO PRIMARY KEY(IDCOMUNE, ID); 
ALTER TABLE ALBEROPROC_PROTOCOLLO ADD CONSTRAINT FK_ALBER_PROT_AMM FOREIGN KEY(IDCOMUNE, CODICEAMMINISTRAZIONE) REFERENCES AMMINISTRAZIONI(IDCOMUNE, CODICEAMMINISTRAZIONE); 
ALTER TABLE ALBEROPROC_PROTOCOLLO ADD CONSTRAINT FK_ALBER_PROT_COMUNI FOREIGN KEY(CODICECOMUNE) REFERENCES COMUNI (CODICECOMUNE);

ALTER TABLE PEC_INBOX ADD SOFTWARE_PROT VARCHAR(2);
ALTER TABLE PEC_INBOX ADD CODICECOMUNE_PROT VARCHAR(5);

ALTER TABLE PEC_INBOX ADD CONSTRAINT FK_PECINBOX_SOFTWAREPROT FOREIGN KEY (SOFTWARE_PROT) REFERENCES SOFTWARE(CODICE);
ALTER TABLE PEC_INBOX ADD CONSTRAINT FK_PECINBOX_COMUNIPROT FOREIGN KEY (CODICECOMUNE_PROT) REFERENCES COMUNI(CODICECOMUNE);
ALTER TABLE PROTOCOLLO_REGISTRI MODIFY IDTIPODOCUMENTO VARCHAR(50);
ALTER TABLE MAPPATURE MODIFY NOMETAGPEOPLE VARCHAR(400);

ALTER TABLE ALBEROPROC_PROTOCOLLO ADD CONSTRAINT FK_ALBPROCPROT_MAILTP2 FOREIGN KEY(IDCOMUNE,SC_FASCCODTESTO) REFERENCES MAILTIPO(IDCOMUNE,CODICEMAIL);
ALTER TABLE ALBEROPROC_PROTOCOLLO ADD CONSTRAINT FK_ALBPROCPROT_MAILTP1 FOREIGN KEY(IDCOMUNE,SC_PROTCODTESTO) REFERENCES MAILTIPO(IDCOMUNE,CODICEMAIL);

ALTER TABLE CONFIGURAZIONE MODIFY ORARIO VARCHAR(1500);
