ALTER TABLE VERTICALIZZAZIONIBASE ADD FLAG_GESTCOMUNE NUMERIC(1, 0);
ALTER TABLE VERTICALIZZAZIONI ADD CODICECOMUNE VARCHAR(5);
ALTER TABLE VERTICALIZZAZIONI ADD CONSTRAINT FK_VERT_COMUNI FOREIGN KEY(CODICECOMUNE) REFERENCES COMUNI (CODICECOMUNE); 
ALTER TABLE VERTICALIZZAZIONIPARAMETRI ADD CODICECOMUNE VARCHAR(5);
ALTER TABLE VERTICALIZZAZIONIPARAMETRI ADD CONSTRAINT FK_VERT_PARAM_COMUNI FOREIGN KEY(CODICECOMUNE) REFERENCES COMUNI (CODICECOMUNE);

ALTER TABLE VERTICALIZZAZIONI ADD ID NUMERIC(6,0);
ALTER TABLE VERTICALIZZAZIONIPARAMETRI ADD ID NUMERIC(6,0);