ALTER TABLE PROTOCOLLO_REGISTRI ADD CODICECOMUNE VARCHAR(5);
ALTER TABLE PROTOCOLLO_REGISTRI ADD CONSTRAINT FK_PROTREGISTRI_COMUNI FOREIGN KEY (CODICECOMUNE) REFERENCES COMUNI(CODICECOMUNE);
ALTER TABLE PROTOCOLLO_REGISTRI ADD ID NUMERIC(10,0) NULL;