CREATE TABLE FIRMEREMOTE(IDCOMUNE VARCHAR(6) NOT NULL,ID DECIMAL(10,0) NOT NULL, PROVIDER VARCHAR(20) NOT NULL, DESCRIZIONE VARCHAR(50) NOT NULL,ENDPOINT VARCHAR(100) NOT NULL,FLAG_ATTIVA DECIMAL(1,0) NOT NULL) ENGINE=INNODB DEFAULT CHARSET=utf8;
ALTER TABLE FIRMEREMOTE ADD CONSTRAINT PK_FIRMEREMOTE PRIMARY KEY(IDCOMUNE,ID);
CREATE INDEX IDX_FIRMEREMOTE_001 ON FIRMEREMOTE(IDCOMUNE,PROVIDER);
CREATE INDEX IDX_FIRMEREMOTE_002 ON FIRMEREMOTE(IDCOMUNE,FLAG_ATTIVA);

CREATE TABLE FIRMEREMOTE_PARAMETRI(IDCOMUNE VARCHAR(6) NOT NULL, FK_IDFIRMAREMOTA DECIMAL(10,0) NOT NULL, CHIAVE VARCHAR(40) NOT NULL, DESCRIZIONE VARCHAR(500) NOT NULL, OBBLIGATORIO DECIMAL(1,0) NOT NULL, VISIBILE DECIMAL(1,0) NOT NULL, READONLY DECIMAL(1,0) NOT NULL, TIPOCAMPO VARCHAR(20) NOT NULL, VALOREDEFAULT VARCHAR(200), ORDINE DECIMAL(3,0) NOT NULL) ENGINE=INNODB DEFAULT CHARSET=utf8;
ALTER TABLE FIRMEREMOTE_PARAMETRI ADD CONSTRAINT PK_FIRMEREMOTEPARAMETRI PRIMARY KEY(IDCOMUNE,FK_IDFIRMAREMOTA,CHIAVE);
ALTER TABLE FIRMEREMOTE_PARAMETRI ADD CONSTRAINT FK_FIRMEREMOTE FOREIGN KEY(IDCOMUNE,FK_IDFIRMAREMOTA) REFERENCES FIRMEREMOTE(IDCOMUNE,ID);

ALTER TABLE manifestazioni ADD COMPORTAMENTO_PRESENZE NUMERIC(1,0);
UPDATE MANIFESTAZIONI SET COMPORTAMENTO_PRESENZE = 0 WHERE CODICE = 0;
UPDATE MANIFESTAZIONI SET COMPORTAMENTO_PRESENZE = 1 WHERE CODICE = 1;
INSERT INTO MANIFESTAZIONI (CODICE,DESCRIZIONE,COMPORTAMENTO_PRESENZE) VALUES (2, 'GRUPPO POSTEGGI', 1);
ALTER TABLE manifestazioni MODIFY COMPORTAMENTO_PRESENZE NUMERIC(1,0) NOT NULL;


ALTER TABLE movimentimail MODIFY oggetto VARCHAR(4000);

alter table decodifiche add constraint PK_DECODIFICHE primary key (IDCOMUNE,ID);

ALTER TABLE TIPIDOCUMENTO ADD CODICEOGGETTO_XSL NUMERIC(10,0);
ALTER TABLE TIPIDOCUMENTO ADD CONSTRAINT FK_TIPIDOCXSL_OGGETTI FOREIGN KEY(IDCOMUNE,CODICEOGGETTO_XSL) REFERENCES OGGETTI(IDCOMUNE,CODICEOGGETTO);

ALTER TABLE parametriesportazione ADD ordine NUMERIC(4,0);
UPDATE parametriesportazione SET ordine=id WHERE ordine IS NULL;
ALTER TABLE parametriesportazione MODIFY  ordine NUMERIC(4,0) NOT NULL;

ALTER TABLE PEOPLEPROCSPORTELLI MODIFY COLUMN PEOPLE_PROC VARCHAR(50);

CREATE TABLE TMP_ISTANZE ( IDCOMUNE VARCHAR(6) NOT NULL, SESSIONID VARCHAR(60) NOT NULL, UUID VARCHAR(60) NOT NULL ) ENGINE=INNODB DEFAULT CHARSET=utf8;
ALTER TABLE TMP_ISTANZE ADD CONSTRAINT PK_TMPISTANZE PRIMARY KEY(IDCOMUNE,SESSIONID,UUID);
