
CREATE TABLE AT_TESTATA(
IDCOMUNE VARCHAR2(6 CHAR) NOT NULL,
ID NUMBER(4,0) NOT NULL,
DESCRIZIONE VARCHAR2(255) NOT NULL,
TIPOLOGIA VARCHAR2(25) NOT NULL,
DATA_INSERIMENTO DATE,
CODICERESPONSABILE NUMBER(8,0) NOT NULL);
ALTER TABLE AT_TESTATA ADD CONSTRAINT PK_AT_TESTATA PRIMARY KEY (IDCOMUNE,ID);
ALTER TABLE AT_TESTATA ADD CONSTRAINT FK_ATTESTATA_RESPONSABILI FOREIGN KEY (IDCOMUNE,CODICERESPONSABILE) REFERENCES RESPONSABILI(IDCOMUNE,CODICERESPONSABILE);


CREATE TABLE AT_ESITO_GRUPPO(
IDCOMUNE VARCHAR2(6 CHAR) NOT NULL,
ID NUMBER(6,0) NOT NULL,
FKID_AT_TESTATA NUMBER(4,0) NOT NULL,
ORDINE NUMBER(4,0) DEFAULT 0 NOT NULL ,
CODICEISTANZA NUMBER(6,0)
);
ALTER TABLE AT_ESITO_GRUPPO ADD CONSTRAINT PK_AT_ESITO_GRUPPO PRIMARY KEY(IDCOMUNE,ID);
ALTER TABLE AT_ESITO_GRUPPO ADD CONSTRAINT FK_ATESITOGRUPPO_TESTATA FOREIGN KEY (IDCOMUNE,FKID_AT_TESTATA) REFERENCES AT_TESTATA(IDCOMUNE,ID);
ALTER TABLE AT_ESITO_GRUPPO ADD CONSTRAINT FK_ATESITOGRUPPO_ISTANZE FOREIGN KEY (IDCOMUNE,CODICEISTANZA) REFERENCES ISTANZE(IDCOMUNE,CODICEISTANZA);
CREATE INDEX IDX_AT_ESITO_GRUPPO_001 ON AT_ESITO_GRUPPO(IDCOMUNE,FKID_AT_TESTATA);

CREATE TABLE AT_ESITO_ERRORI(
IDCOMUNE VARCHAR2(6 CHAR) NOT NULL,
ID NUMBER(6,0) NOT NULL,
FKID_AT_ESITO_GRUPPO NUMBER(6,0) NOT NULL,
TIPO_ERRORE VARCHAR2(50),
DESCRIZIONE_ERRORE VARCHAR2(4000),
FLAG_VERIFICATO NUMBER(1,0) DEFAULT 0 NOT NULL);

ALTER TABLE AT_ESITO_ERRORI ADD CONSTRAINT PK_AT_ESITO_ERRORI PRIMARY KEY(IDCOMUNE,ID);
ALTER TABLE AT_ESITO_ERRORI ADD CONSTRAINT FK_ATESITOERRORI_GRUPPO FOREIGN KEY(IDCOMUNE,FKID_AT_ESITO_GRUPPO) REFERENCES AT_ESITO_GRUPPO(IDCOMUNE,ID);
CREATE INDEX IDX_AT_ESITO_ERRORI_001 ON AT_ESITO_ERRORI(IDCOMUNE,FKID_AT_ESITO_GRUPPO);

CREATE TABLE AT_ESITI_ERRORE_TRACCIATO(
IDCOMUNE VARCHAR2(6 CHAR) NOT NULL,
ID NUMBER(6,0) NOT NULL,
FKID_ATESITO_ERRORI NUMBER(6,0) NOT NULL,
TRACCIATO_RECORD VARCHAR2(500 CHAR),
POS_NEL_TRACCIATO NUMBER(6,0));

ALTER TABLE AT_ESITI_ERRORE_TRACCIATO ADD CONSTRAINT PK_AT_ESITI_ERRORE_TRACCIATO PRIMARY KEY(IDCOMUNE,ID);
ALTER TABLE AT_ESITI_ERRORE_TRACCIATO ADD CONSTRAINT FK_ATESITIERRORETR_ESERR FOREIGN KEY (IDCOMUNE,FKID_ATESITO_ERRORI) REFERENCES AT_ESITO_ERRORI(IDCOMUNE,ID);
CREATE INDEX IDX_AT_ESITI_ERRORE_TR_001 ON AT_ESITI_ERRORE_TRACCIATO(IDCOMUNE,FKID_ATESITO_ERRORI);



alter table AT_TESTATA add software varchar(2);
alter table AT_TESTATA add constraint FK_ATTESTATA_SOFTWARE FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);

alter table at_esito_errori add intestazione varchar2(200 char);


CREATE TABLE ALBERO_COEFFICIENTI_T( IDCOMUNE VARCHAR2(6 CHAR) NOT NULL, ID NUMBER(10,0) NOT NULL, FK_SCID NUMBER(10,0) NOT NULL, DESCRIZIONE VARCHAR2(500 CHAR) NOT NULL, NOTE VARCHAR2(4000 CHAR) NULL, ATTIVO NUMBER(1,0) NOT NULL);
ALTER TABLE ALBERO_COEFFICIENTI_T ADD CONSTRAINT PK_ALBERO_COEFFICIENTI_T PRIMARY KEY(IDCOMUNE,ID);
ALTER TABLE ALBERO_COEFFICIENTI_T ADD CONSTRAINT FK_COEFFICIENTI_ALBERO FOREIGN KEY(IDCOMUNE,FK_SCID) REFERENCES ALBEROPROC (IDCOMUNE,SC_ID);
CREATE INDEX IDX_COEFFICIENTITESTATA_001 ON ALBERO_COEFFICIENTI_T(IDCOMUNE,FK_SCID);
CREATE TABLE ALBERO_COEFFICIENTI_R( IDCOMUNE VARCHAR2(6 CHAR) NOT NULL, ID NUMBER(10,0) NOT NULL, FK_IDTESTATA NUMBER(10,0) NOT NULL, CODICE_COEFFICENTE VARCHAR2(3 CHAR) NOT NULL, DESCRIZIONE VARCHAR2(500 CHAR) NOT NULL, NOTE VARCHAR2(4000 CHAR) NULL, VALORE VARCHAR2(50 CHAR) NOT NULL, TIPO VARCHAR2(50 CHAR) NOT NULL, VISIBILE NUMBER(1,0) NOT NULL );
ALTER TABLE ALBERO_COEFFICIENTI_R ADD CONSTRAINT PK_ALBERO_COEFFICIENTI_R PRIMARY KEY(IDCOMUNE,ID);
ALTER TABLE ALBERO_COEFFICIENTI_R ADD CONSTRAINT FK_COEFFICIENTI_TESTATA FOREIGN KEY(IDCOMUNE,FK_IDTESTATA) REFERENCES ALBERO_COEFFICIENTI_T (IDCOMUNE,ID);
CREATE INDEX IDX_COEFFICIENTIDETTAGLIO_001 ON ALBERO_COEFFICIENTI_R(IDCOMUNE,FK_IDTESTATA);
