
CREATE TABLE INVENTARIOPROC_ENDO(
  IDCOMUNE VARCHAR2(6) NOT NULL,
  ID NUMBER(10,0) NOT NULL,
  CODICEINVENTARIO_T NUMBER(10,0) NOT NULL,
  CODICEINVENTARIO_D NUMBER(10,0) NOT NULL,
  FLAG_PUBBLICA NUMBER(1,0),
  FLAG_NECESSARIO NUMBER(1,0)
);
 
ALTER TABLE INVENTARIOPROC_ENDO ADD CONSTRAINT PK_INVENTARIOPROC_ENDO PRIMARY KEY (IDCOMUNE, ID);
 
ALTER TABLE INVENTARIOPROC_ENDO ADD CONSTRAINT FK_INVPROCENDO_INVPROC_T FOREIGN KEY (IDCOMUNE, CODICEINVENTARIO_T) REFERENCES INVENTARIOPROCEDIMENTI (IDCOMUNE, CODICEINVENTARIO);
 
ALTER TABLE INVENTARIOPROC_ENDO ADD CONSTRAINT FK_INVPROCENDO_INVPROC_D FOREIGN KEY (IDCOMUNE, CODICEINVENTARIO_D) REFERENCES INVENTARIOPROCEDIMENTI (IDCOMUNE, CODICEINVENTARIO);

Alter table ALBEROPROC_ENDO add FLAG_INTERVENTO NUMBER(1,0);
Alter table ALBEROPROC_ENDO add DESCRIZIONE VARCHAR2(300);


CREATE TABLE ALBEROPROC_ENDO_LOC(
  IDCOMUNE VARCHAR2(6) NOT NULL,
  ID NUMBER(10,0) NOT NULL,
  FK_CI_IDCOMUNE VARCHAR2(6) NOT NULL,
  FK_CI_CODICE NUMBER(10,0) NOT NULL,
  FK_AP_IDCOMUNE VARCHAR2(6) NOT NULL,
  FK_AP_SCID NUMBER(10,0) NOT NULL,
  FLAG_PUBBLICA NUMBER(1,0),
  FLAG_NECESSARIO NUMBER(1,0),
 DESCRIZIONE VARCHAR2(300),
FLAG_INTERVENTO NUMBER(1,0)
);

ALTER TABLE ALBEROPROC_ENDO_LOC ADD CONSTRAINT PK_ALBEROPROC_ENDO_LOC PRIMARY KEY (IDCOMUNE, ID);

ALTER TABLE ALBEROPROC_ENDO_LOC ADD CONSTRAINT FK_APROCENDOLOC_INVPROC FOREIGN KEY (FK_CI_IDCOMUNE, FK_CI_CODICE) REFERENCES INVENTARIOPROCEDIMENTI (IDCOMUNE, CODICEINVENTARIO);

ALTER TABLE ALBEROPROC_ENDO_LOC ADD CONSTRAINT FK_APROCENDOLOC_APROC FOREIGN KEY (FK_AP_IDCOMUNE, FK_AP_SCID) REFERENCES ALBEROPROC (IDCOMUNE, SC_ID);

CREATE INDEX IDX_ALBEROPROC_ENDO_LOC_001 ON ALBEROPROC_ENDO_LOC (FK_AP_IDCOMUNE, FK_AP_SCID, IDCOMUNE);

alter table sdeproxy add IDCOMUNEBASE VARCHAR2(6);