alter table TIPIMODALITAPAGAMENTO add FLAG_DISABILITATO NUMERIC(1, 0);

ALTER TABLE RESPONSABILI ADD FK_OGGETTO_IMMAGINE numeric(10) ;

ALTER TABLE RESPONSABILI ADD CONSTRAINT FK_RESPONSABILI_OGGETTI FOREIGN KEY (IDCOMUNE , FK_OGGETTO_IMMAGINE )REFERENCES OGGETTI (  IDCOMUNE, CODICEOGGETTO);

ALTER TABLE ISTANZE ADD UUID VARCHAR(60);
UPDATE ISTANZE SET UUID=UUID();
CREATE UNIQUE INDEX IDX_UQ_ISTANZA_UIID_001 ON ISTANZE (IDCOMUNE,UUID);


create or replace VIEW  vw_listapratiche  AS 
SELECT
   istanze.CODICECOMUNE           AS  CODICECOMUNE ,
   istanze.IDCOMUNE               AS  IDCOMUNE ,
   istanze.SOFTWARE               AS  SOFTWARE ,
  software.DESCRIZIONELUNGA      AS  DESCSOFTWARE ,
   istanze.CODICEISTANZA          AS  IDPRATICA ,
   istanze.NUMEROISTANZA          AS  NUMEROPRATICA ,
  DATE_FORMAT( istanze.DATA ,'%d/%m/%Y') AS  DATAPRESENTAZIONE ,
  DATE_FORMAT( istanze.DATA ,'%Y') AS  ANNOPRESENTAZIONE ,
  DATE_FORMAT( istanze.DATA ,'%m') AS  MESEPRESENTAZIONE ,
   istanze.NUMEROPROTOCOLLO       AS  NUMEROPROTOCOLLO ,
  DATE_FORMAT( istanze.DATAPROTOCOLLO ,'%d/%m/%Y') AS  DATAPROTOCOLLO ,
   istanze.CODICEINTERVENTOPROC   AS  CODICEINTERVENTO ,
   vw_alberoproc.Sc_Descrizione   AS  DESCRIZIONEINTERVENTO ,
   tipiprocedure.CODICEPROCEDURA  AS  CODICEPROCEDURA ,
   tipiprocedure.PROCEDURA        AS  PROCEDURA ,
   istanze.LAVORI                 AS  OGGETTO ,
  UCASE( istanze.LAVORI )         AS  OGGETTOU ,
   istanze.CHIUSURA               AS  CODSTATOPRATICA ,
   statiistanza.STATO             AS  STATOPRATICA ,
   responsabili.RESPONSABILE      AS  RESPONSABILE ,
   responsabili.TELEFONOLAVORO    AS  RESPONSABILE_TELEFONO ,
  IFNULL( stradario.CODVIARIO , stradario.CODICESTRADARIO ) AS  PR_CODVIARIO ,
  CONCAT_WS('', stradario.PREFISSO ,' ', stradario.DESCRIZIONE ) AS  PR_INDIRIZZO ,
   istanzestradario.CODICECIVICO  AS  PR_CODCIVICO ,
   istanzestradario.CIVICO        AS  PR_CIVICO ,
   istanze.CODICEAREA             AS  CODICEZONIZZAZIONE ,
   aree.DENOMINAZIONE             AS  ZONIZZAZIONE ,
   anagrafe.CODICEANAGRAFE        AS  CODICERICHIEDENTE ,
  IFNULL( anagrafe.CODICEFISCALE ,'') AS  CODICEFISCALE ,
  IFNULL( anagrafe.PARTITAIVA ,'') AS  PARTITAIVA ,
  CONCAT_WS('', anagrafe.NOMINATIVO ,' ', anagrafe.NOME ) AS  NOMINATIVO ,
   anagrafe.INDIRIZZO             AS  INDIRIZZO ,
   anagrafe.CAP                   AS  CAP ,
   anagrafe.CITTA                 AS  LOCALITA ,
   comuneresidenza.COMUNE         AS  CITTA ,
   comuneresidenza.PROVINCIA      AS  PROVINCIA ,
   tipisoggetto.TIPOSOGGETTO      AS  TIPORAPPORTO ,
   catasto.DESCRIZIONE            AS  TIPOCATASTO ,
   istanzemappali.FOGLIO          AS  FOGLIO ,
   istanzemappali.PARTICELLA      AS  PARTICELLA ,
   istanzemappali.SUB             AS  SUB ,
   tecnico.CODICEANAGRAFE         AS  TEC_CODICE ,
  CONCAT_WS('', tecnico.NOMINATIVO ,' ', tecnico.NOME ) AS  TEC_NOMINATIVO ,
  IFNULL( tecnico.CODICEFISCALE ,'') AS  TEC_CODICEFISCALE ,
  IFNULL( tecnico.PARTITAIVA ,'') AS  TEC_PARTITAIVA ,
   azienda.CODICEANAGRAFE         AS  AZ_CODICE ,
  CONCAT_WS('', azienda.NOMINATIVO ,' ', azienda.NOME ) AS  AZ_NOMINATIVO ,
  IFNULL( azienda.CODICEFISCALE ,'') AS  AZ_CODICEFISCALE ,
  IFNULL( azienda.PARTITAIVA ,'') AS  AZ_PARTITAIVA ,
   istruttori.RESPONSABILE        AS  ISTRUTTORE ,
   istruttori.TELEFONOLAVORO      AS  ISTRUTTORE_TELEFONO ,
   operatori.RESPONSABILE         AS  OPERATORE ,
   operatori.TELEFONOLAVORO       AS  OPERATORE_TELEFONO ,
   istanze.DOMICILIO_ELETTRONICO  AS  DOMICILIO_ELETTRONICO ,
   domandestc.ID_SPORTELLOMITT    AS  ID_SPORTELLOMITT ,
   domandestc.ID_DOMANDAMITT      AS  ID_DOMANDAMITT,
         istanze.uuid AS uuid
FROM (((((((((((((((((( istanze 
                    JOIN  software 
                      ON (( istanze.SOFTWARE  =  software.CODICE )))
                   JOIN  anagrafe 
                     ON ((( istanze.IDCOMUNE  =  anagrafe.IDCOMUNE )
                          AND ( istanze.CODICERICHIEDENTE  =  anagrafe.CODICEANAGRAFE ))))
                  JOIN  statiistanza 
                    ON ((( istanze.IDCOMUNE  =  statiistanza.IDCOMUNE )
                         AND ( istanze.SOFTWARE  =  statiistanza.SOFTWARE )
                         AND ( istanze.CHIUSURA  =  statiistanza.CODICESTATO ))))
                 JOIN  vw_alberoproc 
                   ON ((( istanze.IDCOMUNE  =  vw_alberoproc.idcomune )
                        AND ( istanze.CODICEINTERVENTOPROC  =  vw_alberoproc.sc_id ))))
                LEFT JOIN  anagrafe   tecnico 
                  ON ((( istanze.IDCOMUNE  =  tecnico.IDCOMUNE )
                       AND ( istanze.CODICEPROFESSIONISTA  =  tecnico.CODICEANAGRAFE ))))
               LEFT JOIN  anagrafe   azienda 
                 ON ((( istanze.IDCOMUNE  =  azienda.IDCOMUNE )
                      AND ( istanze.CODICETITOLARELEGALE  =  azienda.CODICEANAGRAFE ))))
              LEFT JOIN  istanzestradario 
                ON ((( istanze.IDCOMUNE  =  istanzestradario.IDCOMUNE )
                     AND ( istanze.CODICEISTANZA  =  istanzestradario.CODICEISTANZA )
                     AND ( istanzestradario.PRIMARIO  = 1))))
             LEFT JOIN  stradario 
               ON ((( istanzestradario.IDCOMUNE  =  stradario.IDCOMUNE )
                    AND ( istanzestradario.CODICESTRADARIO  =  stradario.CODICESTRADARIO ))))
            LEFT JOIN  istanzemappali 
              ON ((( istanze.IDCOMUNE  =  istanzemappali.IDCOMUNE )
                   AND ( istanze.CODICEISTANZA  =  istanzemappali.FKCODICEISTANZA )
                   AND ( istanzemappali.PRIMARIO  = 1))))
           LEFT JOIN  responsabili 
             ON ((( istanze.IDCOMUNE  =  responsabili.IDCOMUNE )
                  AND ( istanze.CODICERESPONSABILEPROC  =  responsabili.CODICERESPONSABILE ))))
          LEFT JOIN  comuni   comuneresidenza 
            ON (( anagrafe.COMUNERESIDENZA  =  comuneresidenza.CODICECOMUNE )))
         LEFT JOIN  tipisoggetto 
           ON ((( istanze.IDCOMUNE  =  tipisoggetto.IDCOMUNE )
                AND ( istanze.FKCODICESOGGETTO  =  tipisoggetto.CODICETIPOSOGGETTO ))))
        LEFT JOIN  aree 
          ON ((( istanze.IDCOMUNE  =  aree.IDCOMUNE )
               AND ( istanze.CODICEAREA  =  aree.CODICEAREA ))))
       LEFT JOIN  catasto 
         ON (( istanzemappali.CODICECATASTO  =  catasto.CODICE )))
      LEFT JOIN  tipiprocedure 
        ON ((( istanze.IDCOMUNE  =  tipiprocedure.IDCOMUNE )
             AND ( istanze.CODICEPROCEDURA  =  tipiprocedure.CODICEPROCEDURA ))))
     LEFT JOIN  responsabili   istruttori 
       ON ((( istanze.IDCOMUNE  =  istruttori.IDCOMUNE )
            AND ( istanze.CODICEISTRUTTORE  =  istruttori.CODICERESPONSABILE ))))
    LEFT JOIN  responsabili   operatori 
      ON ((( operatori.IDCOMUNE  =  istanze.IDCOMUNE )
           AND ( operatori.CODICERESPONSABILE  =  istanze.CODICERESPONSABILE ))))
   LEFT JOIN  domandestc 
     ON ((( istanze.IDCOMUNE  =  domandestc.IDCOMUNE )
          AND ( istanze.CODICEISTANZA  =  domandestc.CODICEISTANZA ))));

CREATE OR REPLACE ALGORITHM=MERGE VIEW VW_ALBEROPROC AS SELECT ALBEROPROC.IDCOMUNE, ALBEROPROC.SOFTWARE, ALBEROPROC.SC_ID, ALBEROPROC.SC_CODICE, ALBEROPROC.SC_PADRE, CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT((CASE ISNULL(ALBEROPROC_L1.SC_DESCRIZIONE) WHEN 1 THEN '' ELSE CONCAT(ALBEROPROC_L1.SC_DESCRIZIONE,' - ') END)),(CASE ISNULL(ALBEROPROC_L2.SC_DESCRIZIONE) WHEN 1 THEN '' ELSE CONCAT(ALBEROPROC_L2.SC_DESCRIZIONE,' - ') END)),(CASE ISNULL(ALBEROPROC_L3.SC_DESCRIZIONE) WHEN 1 THEN '' ELSE CONCAT(ALBEROPROC_L3.SC_DESCRIZIONE,' - ') END)),(CASE ISNULL(ALBEROPROC_L4.SC_DESCRIZIONE) WHEN 1 THEN '' ELSE CONCAT(ALBEROPROC_L4.SC_DESCRIZIONE,' - ') END)),(CASE ISNULL(ALBEROPROC_L5.SC_DESCRIZIONE) WHEN 1 THEN '' ELSE CONCAT(ALBEROPROC_L5.SC_DESCRIZIONE,' - ') END)),(CASE ISNULL(ALBEROPROC_L6.SC_DESCRIZIONE) WHEN 1 THEN '' ELSE CONCAT(ALBEROPROC_L6.SC_DESCRIZIONE,' - ') END)),(CASE ISNULL(ALBEROPROC_L7.SC_DESCRIZIONE) WHEN 1 THEN '' ELSE CONCAT(ALBEROPROC_L7.SC_DESCRIZIONE,' - ') END)),(CASE ISNULL(ALBEROPROC_L8.SC_DESCRIZIONE) WHEN 1 THEN '' ELSE CONCAT(ALBEROPROC_L8.SC_DESCRIZIONE,' - ') END)) AS SC_DESCRIZIONE, CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT((CASE ISNULL(ALBEROPROC_L2.SC_DESCRIZIONE) WHEN 1 THEN '' ELSE CONCAT(ALBEROPROC_L1.SC_DESCRIZIONE,' - ') END)),(CASE ISNULL(ALBEROPROC_L3.SC_DESCRIZIONE) WHEN 1 THEN '' ELSE CONCAT(ALBEROPROC_L2.SC_DESCRIZIONE,' - ') END)),(CASE ISNULL(ALBEROPROC_L4.SC_DESCRIZIONE) WHEN 1 THEN '' ELSE CONCAT(ALBEROPROC_L3.SC_DESCRIZIONE,' - ') END)),(CASE ISNULL(ALBEROPROC_L5.SC_DESCRIZIONE) WHEN 1 THEN '' ELSE CONCAT(ALBEROPROC_L4.SC_DESCRIZIONE,' - ') END)),(CASE ISNULL(ALBEROPROC_L6.SC_DESCRIZIONE) WHEN 1 THEN '' ELSE CONCAT(ALBEROPROC_L5.SC_DESCRIZIONE,' - ') END)),(CASE ISNULL(ALBEROPROC_L7.SC_DESCRIZIONE) WHEN 1 THEN '' ELSE CONCAT(ALBEROPROC_L6.SC_DESCRIZIONE,' - ') END)),(CASE ISNULL(ALBEROPROC_L8.SC_DESCRIZIONE) WHEN 1 THEN '' ELSE CONCAT(ALBEROPROC_L7.SC_DESCRIZIONE,' - ') END)) AS SC_DESCRIZIONEPADRE, ALBEROPROC.SC_DESCRIZIONE AS SC_DESCRIZIONEBREVE, ALBEROPROC_L1.SC_DESCRIZIONE AS DESCR_L1, ALBEROPROC_L2.SC_DESCRIZIONE AS DESCR_L2, ALBEROPROC_L3.SC_DESCRIZIONE AS DESCR_L3, ALBEROPROC_L4.SC_DESCRIZIONE AS DESCR_L4, ALBEROPROC_L5.SC_DESCRIZIONE AS DESCR_L5, ALBEROPROC_L6.SC_DESCRIZIONE AS DESCR_L6, ALBEROPROC_L7.SC_DESCRIZIONE AS DESCR_L7, ALBEROPROC_L8.SC_DESCRIZIONE AS DESCR_L8, ALBEROPROC.SC_ORDINE AS ORDINE0, IFNULL(ALBEROPROC_L1.SC_ORDINE,0) AS ORDINE1, IFNULL(ALBEROPROC_L2.SC_ORDINE,0) AS ORDINE2, IFNULL(ALBEROPROC_L3.SC_ORDINE,0) AS ORDINE3, IFNULL(ALBEROPROC_L4.SC_ORDINE,0) AS ORDINE4, IFNULL(ALBEROPROC_L5.SC_ORDINE,0) AS ORDINE5, IFNULL(ALBEROPROC_L6.SC_ORDINE,0) AS ORDINE6, IFNULL(ALBEROPROC_L7.SC_ORDINE,0) AS ORDINE7, IFNULL(ALBEROPROC_L8.SC_ORDINE,0) AS ORDINE8, (CASE ISNULL(ALBEROPROC_L8.FKCODICEMERCATO) WHEN 1 THEN (CASE ISNULL(ALBEROPROC_L7.FKCODICEMERCATO) WHEN 1 THEN (CASE ISNULL(ALBEROPROC_L6.FKCODICEMERCATO) WHEN 1 THEN (CASE ISNULL(ALBEROPROC_L5.FKCODICEMERCATO) WHEN 1 THEN (CASE ISNULL(ALBEROPROC_L4.FKCODICEMERCATO) WHEN 1 THEN (CASE ISNULL(ALBEROPROC_L3.FKCODICEMERCATO) WHEN 1 THEN (CASE ISNULL(ALBEROPROC_L2.FKCODICEMERCATO) WHEN 1 THEN (CASE ISNULL(ALBEROPROC_L1.FKCODICEMERCATO) WHEN 1 THEN NULL ELSE ALBEROPROC_L1.FKCODICEMERCATO END) ELSE ALBEROPROC_L2.FKCODICEMERCATO END) ELSE ALBEROPROC_L3.FKCODICEMERCATO END) ELSE ALBEROPROC_L4.FKCODICEMERCATO END) ELSE ALBEROPROC_L5.FKCODICEMERCATO END) ELSE ALBEROPROC_L6.FKCODICEMERCATO END) ELSE ALBEROPROC_L7.FKCODICEMERCATO END) ELSE ALBEROPROC_L8.FKCODICEMERCATO END) AS FKCODICEMERCATO, (CASE ISNULL(ALBEROPROC_L8.FKIDMERCATIUSO) WHEN 1 THEN (CASE ISNULL(ALBEROPROC_L7.FKIDMERCATIUSO) WHEN 1 THEN (CASE ISNULL(ALBEROPROC_L6.FKIDMERCATIUSO) WHEN 1 THEN (CASE ISNULL(ALBEROPROC_L5.FKIDMERCATIUSO) WHEN 1 THEN (CASE ISNULL(ALBEROPROC_L4.FKIDMERCATIUSO) WHEN 1 THEN (CASE ISNULL(ALBEROPROC_L3.FKIDMERCATIUSO) WHEN 1 THEN (CASE ISNULL(ALBEROPROC_L2.FKIDMERCATIUSO) WHEN 1 THEN (CASE ISNULL(ALBEROPROC_L1.FKIDMERCATIUSO) WHEN 1 THEN NULL ELSE ALBEROPROC_L1.FKIDMERCATIUSO END) ELSE ALBEROPROC_L2.FKIDMERCATIUSO END) ELSE ALBEROPROC_L3.FKIDMERCATIUSO END) ELSE ALBEROPROC_L4.FKIDMERCATIUSO END) ELSE ALBEROPROC_L5.FKIDMERCATIUSO END) ELSE ALBEROPROC_L6.FKIDMERCATIUSO END) ELSE ALBEROPROC_L7.FKIDMERCATIUSO END) ELSE ALBEROPROC_L8.FKIDMERCATIUSO END) AS FKIDMERCATIUSO, ALBEROPROC.SC_ATTIVO, ALBEROPROC.PROGRESSIVOISTANZE, CONCAT_WS('',ALBEROPROC.SC_PUBBLICA,ALBEROPROC_L1.SC_PUBBLICA,ALBEROPROC_L2.SC_PUBBLICA,ALBEROPROC_L3.SC_PUBBLICA,ALBEROPROC_L4.SC_PUBBLICA,ALBEROPROC_L5.SC_PUBBLICA,ALBEROPROC_L6.SC_PUBBLICA,ALBEROPROC_L7.SC_PUBBLICA,ALBEROPROC_L8.SC_PUBBLICA) AS PUBBLICA FROM ALBEROPROC LEFT JOIN ALBEROPROC ALBEROPROC_L1 ON ALBEROPROC.IDCOMUNE = ALBEROPROC_L1.IDCOMUNE AND ALBEROPROC.SOFTWARE = ALBEROPROC_L1.SOFTWARE AND SUBSTR(ALBEROPROC.SC_CODICE,1,2) = ALBEROPROC_L1.SC_CODICE AND LENGTH(ALBEROPROC_L1.SC_CODICE) = 2 LEFT JOIN ALBEROPROC ALBEROPROC_L2 ON ALBEROPROC_L1.IDCOMUNE = ALBEROPROC_L2.IDCOMUNE AND ALBEROPROC_L1.SOFTWARE = ALBEROPROC_L2.SOFTWARE AND SUBSTR(ALBEROPROC.SC_CODICE,1,4) = ALBEROPROC_L2.SC_CODICE AND LENGTH(ALBEROPROC_L2.SC_CODICE) = 4 LEFT JOIN ALBEROPROC ALBEROPROC_L3 ON ALBEROPROC_L2.IDCOMUNE = ALBEROPROC_L3.IDCOMUNE AND ALBEROPROC_L2.SOFTWARE = ALBEROPROC_L3.SOFTWARE AND SUBSTR(ALBEROPROC.SC_CODICE,1,6) = ALBEROPROC_L3.SC_CODICE AND LENGTH(ALBEROPROC_L3.SC_CODICE) = 6 LEFT JOIN ALBEROPROC ALBEROPROC_L4 ON ALBEROPROC_L3.IDCOMUNE = ALBEROPROC_L4.IDCOMUNE AND ALBEROPROC_L3.SOFTWARE = ALBEROPROC_L4.SOFTWARE AND SUBSTR(ALBEROPROC.SC_CODICE,1,8) = ALBEROPROC_L4.SC_CODICE AND LENGTH(ALBEROPROC_L4.SC_CODICE) = 8 LEFT JOIN ALBEROPROC ALBEROPROC_L5 ON ALBEROPROC_L4.IDCOMUNE = ALBEROPROC_L5.IDCOMUNE AND ALBEROPROC_L4.SOFTWARE = ALBEROPROC_L5.SOFTWARE AND SUBSTR(ALBEROPROC.SC_CODICE,1,10) = ALBEROPROC_L5.SC_CODICE AND LENGTH(ALBEROPROC_L5.SC_CODICE) = 10 LEFT JOIN ALBEROPROC ALBEROPROC_L6 ON ALBEROPROC_L5.IDCOMUNE = ALBEROPROC_L6.IDCOMUNE AND ALBEROPROC_L5.SOFTWARE = ALBEROPROC_L6.SOFTWARE AND SUBSTR(ALBEROPROC.SC_CODICE,1,12) = ALBEROPROC_L6.SC_CODICE AND LENGTH(ALBEROPROC_L6.SC_CODICE) = 12 LEFT JOIN ALBEROPROC ALBEROPROC_L7 ON ALBEROPROC_L6.IDCOMUNE = ALBEROPROC_L7.IDCOMUNE AND ALBEROPROC_L6.SOFTWARE = ALBEROPROC_L7.SOFTWARE AND SUBSTR(ALBEROPROC.SC_CODICE,1,14) = ALBEROPROC_L7.SC_CODICE AND LENGTH(ALBEROPROC_L7.SC_CODICE) = 14 LEFT JOIN ALBEROPROC ALBEROPROC_L8 ON ALBEROPROC_L7.IDCOMUNE = ALBEROPROC_L8.IDCOMUNE AND ALBEROPROC_L7.SOFTWARE = ALBEROPROC_L8.SOFTWARE AND SUBSTR(ALBEROPROC.SC_CODICE,1,16) = ALBEROPROC_L8.SC_CODICE AND LENGTH(ALBEROPROC_L8.SC_CODICE) = 16;          
ALTER TABLE SOFTWAREATTIVI ADD flag_subvisura numeric(1,0);
ALTER TABLE TIPIMOVIMENTO ADD FLAG_AGGIORNA_RIEPILOGO NUMERIC(1,0);

CREATE INDEX DX_MOVIMENTI_007 ON MOVIMENTI (IDCOMUNE, ID_ATT_DEST, DATA);

ALTER table layouttesti MODIFY codicetesto VARCHAR(128);
ALTER table layouttestibase MODIFY codicetesto VARCHAR(128);


CREATE TABLE NOTIFICA_PAGAMENTI (
IDDOMANDA VARCHAR(50) NOT NULL , 
MESSAGGIO VARCHAR(4000) NOT NULL , 
ESITO VARCHAR(2) NOT NULL , 
DATA VARCHAR(20) NOT NULL , 
IDCOMUNE VARCHAR(6) NOT NULL , 
NUMEROOPERAZIONE VARCHAR(50) NOT NULL , 
IDORDINE VARCHAR(50) NOT NULL , 
IDTRANSAZIONE VARCHAR(10) NOT NULL , 
TIPOPAGAMENTO VARCHAR(10) NOT NULL  
);
ALTER TABLE NOTIFICA_PAGAMENTI ADD CONSTRAINT NOTIFICA_PAGAMENTI_PK PRIMARY KEY (IDCOMUNE, NUMEROOPERAZIONE);

alter table statiistanza add OSPLDP_STATO_PRATICA VARCHAR(20);