CREATE TABLE PEC_INBOX
(
	"IDCOMUNE"   VARCHAR2(6 BYTE) NOT NULL ENABLE,
  	"ID"  VARCHAR2(128 CHAR) NOT NULL ENABLE,
    "PEC_SUBJECT"    VARCHAR2(4000 BYTE),
    "PEC_FROM"       VARCHAR2(4000 BYTE),
    "PEC_TO"         VARCHAR2(4000 BYTE),
    "PEC_DATE"       DATE,
    "SOFTWARE"   VARCHAR2(2 BYTE),
    CONSTRAINT "PEC_INBOX_PK" PRIMARY KEY ("IDCOMUNE", "ID"),
    CONSTRAINT "PEC_INBOX_SOFTWARE" FOREIGN KEY ("SOFTWARE") REFERENCES "SOFTWARE" ("CODICE") ENABLE
);
Alter index "PEC_INBOX_PK" rebuild  tablespace "SIGE2IDX";