ALTER TABLE TIPIGRADT_CFG_ROTAZIONE ADD FK_DYN2CAMPI_ORDINE NUMERIC(10, 0) NOT NULL;

ALTER TABLE TIPIGRADT_CFG_ROTAZIONE ADD CONSTRAINT FK_TIPIGRAD_T_CAMPI_ORDINE FOREIGN KEY (IDCOMUNE,FK_DYN2CAMPI_ORDINE) REFERENCES DYN2_CAMPI(IDCOMUNE,ID);

CREATE TABLE ARCHIVIAZIONI_BACKV2_26 AS SELECT * FROM ARCHIVIAZIONI;

alter table ARCHIVIAZIONI add NUMERO NUMERIC(4,0);

alter table ARCHIVIAZIONI add TMP_NAME TEXT;
update ARCHIVIAZIONI set TMP_NAME=ERRORE;
alter table ARCHIVIAZIONI drop column ERRORE;
alter table ARCHIVIAZIONI add ERRORE TEXT;
update ARCHIVIAZIONI set ERRORE=TMP_NAME;
alter table ARCHIVIAZIONI drop column TMP_NAME;

alter table DOCUMENTIISTANZA modify FKIDCATEGORIA NUMERIC(10,0);

ALTER TABLE DYN2_ESPRESSIONI MODIFY PARENTESI_APERTA VARCHAR(3);

ALTER TABLE DYN2_ESPRESSIONI MODIFY PARENTESI_CHIUSA VARCHAR(3);

ALTER TABLE MERCATI ADD FK_D2CID_PREF_POS NUMERIC(10, 0);
