echo off
clear
rem lanciare dalla cartella in cui si trova il progetto
call dotnet nuget disable source vbg_library
call dotnet-svcutil -u "Connected Services/Init.Sigepro.FrontEnd.AppLogic.ConfigurazioneAreaRiservataService"
call dotnet-svcutil -u "Connected Services/Init.Sigepro.FrontEnd.AppLogic.AlboPretorioService"
call dotnet-svcutil -u "Connected Services/Init.Sigepro.FrontEnd.AppLogic.AutorizzazioniTransitiService"
call dotnet-svcutil -u "Connected Services/Init.Sigepro.FrontEnd.AppLogic.BackendQrCodeWs"
call dotnet-svcutil -u "Connected Services/Init.Sigepro.FrontEnd.AppLogic.BookmarksWebService"
call dotnet-svcutil -u "Connected Services/Init.Sigepro.FrontEnd.AppLogic.CommissioniAccessoPINWs"
call dotnet-svcutil -u "Connected Services/Init.Sigepro.FrontEnd.AppLogic.CommissioniWs"
call dotnet-svcutil -u "Connected Services/Init.Sigepro.FrontEnd.AppLogic.CreazioneAnagrafeService"
call dotnet-svcutil -u "Connected Services/Init.Sigepro.FrontEnd.AppLogic.FVGWebService"
call dotnet-svcutil -u "Connected Services/Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService"
call dotnet-svcutil -u "Connected Services/Init.Sigepro.FrontEnd.AppLogic.LivornoServiziDrupal"
call dotnet-svcutil -u "Connected Services/Init.Sigepro.FrontEnd.AppLogic.RicercheAnagraficheWebService"
call dotnet-svcutil -u "Connected Services/Init.Sigepro.FrontEnd.AppLogic.ServizioPrecompilazionePDF"
call dotnet-svcutil -u "Connected Services/Init.Sigepro.FrontEnd.AppLogic.SigeproAutorizzazioniService"
call dotnet-svcutil -u "Connected Services/Init.Sigepro.FrontEnd.AppLogic.SigeproSitWebService"
call dotnet-svcutil -u "Connected Services/Init.Sigepro.FrontEnd.AppLogic.StcService"
call dotnet-svcutil -u "Connected Services/Init.Sigepro.FrontEnd.AppLogic.VisuraMobileServices"
call dotnet-svcutil -u "Connected Services/Init.Sigepro.FrontEnd.AppLogic.VotazioniCommissioniWs"
call dotnet-svcutil -u "Connected Services/Init.Sigepro.FrontEnd.AppLogic.WsAccessoAtti"
call dotnet-svcutil -u "Connected Services/Init.Sigepro.FrontEnd.AppLogic.WsEntiTerzi"
call dotnet-svcutil -u "Connected Services/Init.Sigepro.FrontEnd.AppLogic.WsFileConverterService"
call dotnet-svcutil -u "Connected Services/Init.Sigepro.FrontEnd.AppLogic.WsInterventi"
rem call dotnet-svcutil -u "Connected Services/Init.Sigepro.FrontEnd.AppLogic.WsInterventiAteco"
call dotnet-svcutil -u "Connected Services/Init.Sigepro.FrontEnd.AppLogic.WsModulisticaFrontoffice"
call dotnet-svcutil -u "Connected Services/Init.Sigepro.FrontEnd.AppLogic.WsNodoPagamenti"
call dotnet-svcutil -u "Connected Services/Init.Sigepro.FrontEnd.AppLogic.WsQuestionarioFo"
call dotnet-svcutil -u "Connected Services/Init.Sigepro.FrontEnd.AppLogic.WsUrlAccessoConsoleService"
call dotnet-svcutil -u "Connected Services/Init.Sigepro.FrontEnd.AppLogic.WsVerificaFirmaDigitale"
call dotnet-svcutil -u "Connected Services/Init.Sigepro.Frontend.AppLogic.WsOneri"
call dotnet-svcutil -u "Connected Services/Init.Sigepro.Frontend.AppLogic.WsComuniService"
call dotnet-svcutil -u "Connected Services/Init.Sigepro.FrontEnd.AppLogic.WsVbgDatiDinamici"
call dotnet-svcutil -u "Connected Services/Init.Sigepro.Frontend.AppLogic.WsStradario"
call dotnet-svcutil -u "Connected Services/Init.Sigepro.FrontEnd.AppLogic.WsEndoprocedimenti"
call dotnet-svcutil -u "Connected Services/Init.Sigepro.FrontEnd.AppLogic.AllegatiDomandaWs"
call dotnet-svcutil -u "Connected Services/Init.Sigepro.FrontEnd.AppLogic.WsEndoFrontoffice"
call dotnet-svcutil -u "Connected Services/Init.Sigepro.FrontEnd.AppLogic.WsTipiSoggettoService"
call dotnet-svcutil -u "Connected Services/VBG.Frontend.AppLogic.WsDatiDomandaService"
call dotnet-svcutil -u "Connected Services/VBG.Frontend.AppLogic.WsRicercheVisuraService"
call dotnet-svcutil -u "Connected Services/VBG.Frontend.AppLogic.WsSoggettiFirmatariService"
call dotnet-svcutil -u "Connected Services/VBG.Frontend.AppLogic.WsTabelleDiBaseService"
call dotnet-svcutil -u "Connected Services/VBG.Frontend.AppLogic.WsMappatureService"
call dotnet-svcutil -u "Connected Services/VBG.Frontend.AppLogic.WsRisorseTestualiService"
call dotnet-svcutil -u "Connected Services/VBG.Frontend.AppLogic.WsIntegrazioneLDPService" 
call dotnet-svcutil -u "Connected Services/Init.Sigepro.FrontEnd.AppLogic.WebServiceReferences.IstanzeService" 
call dotnet-svcutil -u "Connected Services/VBG.Frontend.AppLogic.WsConfigurazioneContenutiService" 
call dotnet-svcutil -u "Connected Services/VBG.FrontEnd.AppLogic.WsAnagraficheService" 
call dotnet nuget enable source vbg_library
