<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net48</TargetFrameworks>
    <RootNamespace>Init.SIGePro.Manager.Validator</RootNamespace>
    <Configurations>Debug;Release;ReleaseFramework</Configurations>
    <Platforms>AnyCPU</Platforms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PersonalLib2\PersonalLib2.csproj" />
    <ProjectReference Include="..\SIGePro.Data\SIGePro.Data.csproj" />
    <ProjectReference Include="..\SIGePro.Exceptions\SIGePro.Exceptions.csproj" />
    <ProjectReference Include="..\SIGePro.Manager.Utils\SIGePro.Manager.Utils.csproj" />
  </ItemGroup>

</Project>
