ALTER TABLE MERCATIPRESENZE_T ADD FLAG_CHIUSURA_APPELLO NUMERIC(1,0);
ALTER TABLE MERCATIPRESENZE_T ADD DATA_CHIUSURA_APPELLO DATETIME;
ALTER TABLE MERCATIPRESENZE_T ADD RESP_CHIUSURA_APPELLO NUMERIC(8,0);
ALTER TABLE MERCATIPRESENZE_T ADD CONSTRAINT FK_MERCPREST_RESPAPPELLO FOREIGN KEY(IDCOMUNE, RESP_CHIUSURA_APPELLO) REFERENCES RESPONSABILI(IDCOMUNE,CODICERESPONSABILE);
CREATE INDEX IDX_MERCPREST_RESPAPPELLO ON MERCATIPRESENZE_T(IDCOMUNE,RESP_CHIUSURA_APPELLO);

ALTER TABLE MERCATI_SPUNTE ADD FLAG_FILTRO_CATMERC NUMERIC(1,0);

alter table autorizzazioni add note_sistema VARCHAR(4000);
alter table autorizzazioni add note VARCHAR(4000);

ALTER TABLE mercatipresenze_d add fk_codiceistat VARCHAR(15);
alter table mercatipresenze_d add constraint fk_mercpresenzed_istat foreign key (idcomune,fk_codiceistat) references attivita(idcomune,codiceistat);


alter table autorizzazioni add autorig_numero VARCHAR(40);
alter table autorizzazioni add autorig_data DATETIME;
alter table autorizzazioni add autorig_codcomune VARCHAR(5);



alter table mercatipresenze_d add flag_rinuncia_presenza numeric(1,0);

CREATE TABLE POSTEGGI_SETTORI(
IDCOMUNE                VARCHAR(6)  NOT NULL,
ID                      NUMERIC(4,0) NOT NULL,
CODICESETTORE           VARCHAR(10) NOT NULL, 
SETTORE                 VARCHAR(50)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE POSTEGGI_SETTORI ADD CONSTRAINT PK_POSTEGGI_SETTORI PRIMARY KEY(IDCOMUNE,ID);

ALTER TABLE MERCATI_D ADD FK_POSTEGGISETTORI_ID NUMERIC(4,0);
ALTER TABLE MERCATI_D ADD CONSTRAINT FK_MERCATID_POSTSETT_ID FOREIGN KEY (IDCOMUNE,FK_POSTEGGISETTORI_ID) REFERENCES POSTEGGI_SETTORI(IDCOMUNE,ID);

alter table mercati_d add identificativo_percorso numeric(4,0);



create table AUTORIZZAZIONI_SUBENTRI_CONC(
IDCOMUNE          VARCHAR(6)  NOT NULL ,
ID                  NUMERIC(6,0) NOT NULL,
FK_AUTSUB_ID        NUMERIC(6,0) NOT NULL,
FK_CODICEMERCATO            NUMERIC(4,0),   
FK_IDMERCATIUSO             NUMERIC(4,0),  
FK_IDPOSTEGGIO              NUMERIC(6,0),   
FK_TIPOCONCESSIONE          VARCHAR(2), 
STAGIONALEDA                VARCHAR(4),
STAGIONALEA                 VARCHAR(4),
DATASCADENZA                DATETIME,
FK_IDAUT_ATTUALE            NUMERIC(6,0),
FK_IDAUT_COLLEGATA          NUMERIC(6,0)   
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

alter table AUTORIZZAZIONI_SUBENTRI_CONC ADD CONSTRAINT PK_AUTO_SUBENTRI_CONC PRIMARY KEY(IDCOMUNE,ID);

alter table AUTORIZZAZIONI_SUBENTRI_CONC ADD CONSTRAINT FK_AUTSUBCONC_MERCATI FOREIGN KEY(IDCOMUNE,FK_CODICEMERCATO) REFERENCES MERCATI(IDCOMUNE,CODICEMERCATO);
CREATE INDEX IDX_AUTSUBCONC_001 ON AUTORIZZAZIONI_SUBENTRI_CONC (IDCOMUNE,FK_CODICEMERCATO);

alter table AUTORIZZAZIONI_SUBENTRI_CONC ADD CONSTRAINT FK_AUTSUBCONC_MERCUSO FOREIGN KEY(IDCOMUNE,FK_IDMERCATIUSO) REFERENCES MERCATI_USO(IDCOMUNE,ID);
CREATE INDEX IDX_AUTSUBCONC_002 ON AUTORIZZAZIONI_SUBENTRI_CONC(IDCOMUNE,FK_IDMERCATIUSO);


alter table AUTORIZZAZIONI_SUBENTRI_CONC ADD CONSTRAINT FK_AUTSUBCONC_POSTEGGI FOREIGN KEY(IDCOMUNE,FK_IDPOSTEGGIO) REFERENCES MERCATI_D(IDCOMUNE,IDPOSTEGGIO);
CREATE INDEX IDX_AUTSUBCONC_003 ON AUTORIZZAZIONI_SUBENTRI_CONC(IDCOMUNE,FK_IDPOSTEGGIO);


alter table AUTORIZZAZIONI_SUBENTRI_CONC ADD CONSTRAINT FK_AUTSUBCONC_AUT FOREIGN KEY(IDCOMUNE,FK_IDAUT_ATTUALE) REFERENCES AUTORIZZAZIONI(IDCOMUNE,ID);
CREATE INDEX IDX_AUTSUBCONC_004 ON AUTORIZZAZIONI_SUBENTRI_CONC(IDCOMUNE,FK_IDAUT_ATTUALE);


alter table AUTORIZZAZIONI_SUBENTRI_CONC ADD CONSTRAINT FK_AUTSUBCONC_AUTCOL FOREIGN KEY(IDCOMUNE,FK_IDAUT_COLLEGATA) REFERENCES AUTORIZZAZIONI(IDCOMUNE,ID);
CREATE INDEX IDX_AUTSUBCONC_005 ON AUTORIZZAZIONI_SUBENTRI_CONC(IDCOMUNE,FK_IDAUT_COLLEGATA);

alter table AUTORIZZAZIONI_SUBENTRI_CONC ADD CONSTRAINT FK_AUTSUBCONC_CONCTIPI FOREIGN KEY(FK_TIPOCONCESSIONE) REFERENCES CONCESSIONITIPI(TIPOCONCESSIONE);

alter table AUTORIZZAZIONI_SUBENTRI_CONC ADD CONSTRAINT FK_AUTSUBCONC_AUTSUB FOREIGN KEY(IDCOMUNE,FK_AUTSUB_ID) REFERENCES AUTORIZZAZIONI_SUBENTRI(IDCOMUNE,ID);
CREATE INDEX IDX_AUTSUBCONC_006 ON AUTORIZZAZIONI_SUBENTRI_CONC(IDCOMUNE,FK_AUTSUB_ID);




create table AUTORIZZAZIONI_SOGGETTI (
IDCOMUNE VARCHAR(6) NOT NULL,
ID NUMERIC(6,0) NOT NULL,
FK_AUTORIZZAZIONI_ID NUMERIC(6,0) NOT NULL, 
FK_CODICEANAGRAFE NUMERIC(6,0) NOT NULL 
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE AUTORIZZAZIONI_SOGGETTI ADD CONSTRAINT PK_AUTORIZZAZIONI_SOGGETTI PRIMARY KEY(IDCOMUNE,ID); 
ALTER TABLE AUTORIZZAZIONI_SOGGETTI ADD CONSTRAINT FK_AUTSOGGETTI_ANAGRAFE FOREIGN KEY(IDCOMUNE,FK_CODICEANAGRAFE) REFERENCES ANAGRAFE (IDCOMUNE,CODICEANAGRAFE); 
CREATE INDEX IDX_AUTSOGG_001 ON AUTORIZZAZIONI_SOGGETTI(IDCOMUNE,FK_CODICEANAGRAFE);

ALTER TABLE AUTORIZZAZIONI_SOGGETTI ADD CONSTRAINT FK_AUTSOGGETTI_AUTORIZZAZIONI FOREIGN KEY(IDCOMUNE,FK_AUTORIZZAZIONI_ID) REFERENCES AUTORIZZAZIONI (IDCOMUNE,ID); 
CREATE INDEX IDX_AUTSOGG_002 ON AUTORIZZAZIONI_SOGGETTI(IDCOMUNE,FK_AUTORIZZAZIONI_ID);





CREATE TABLE AUTORIZZAZIONI_CSI (
IDCOMUNE VARCHAR(6) NOT NULL,
ID NUMERIC(10,0) NOT NULL,
FK_AUTORIZZAZIONI_ID NUMERIC(6,0),
FK_CODICEGERENTE  NUMERIC(6,0),
STATO_AUTORIZZAZIONE VARCHAR(50),
STATO_WARNING VARCHAR(50),
VALIDA_SPUNTA NUMERIC(1,0),
CAUSALE_SOSPENSIONE VARCHAR(30),
DATA_SOSP_DA DATETIME,
DATA_SOSP_A DATETIME,
DATA_INIZIO_GERENZA DATETIME,
DATA_FINE_GERENZA DATETIME
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE AUTORIZZAZIONI_CSI ADD CONSTRAINT PK_AUTORIZZAZIONI_CSI PRIMARY KEY(IDCOMUNE,ID);

ALTER TABLE AUTORIZZAZIONI_CSI ADD CONSTRAINT FK_AUTORIZ_CSI_AUTORIZ FOREIGN KEY(IDCOMUNE,FK_AUTORIZZAZIONI_ID) REFERENCES AUTORIZZAZIONI(IDCOMUNE,ID);
CREATE INDEX IDX_AUTORIZZAZIONI_CSI_001 ON AUTORIZZAZIONI_CSI (IDCOMUNE,FK_AUTORIZZAZIONI_ID);

ALTER TABLE AUTORIZZAZIONI_CSI ADD CONSTRAINT FK_AUTORIZ_CSI_ANAG FOREIGN KEY(IDCOMUNE,FK_CODICEGERENTE) REFERENCES ANAGRAFE(IDCOMUNE,CODICEANAGRAFE);
CREATE INDEX IDX_AUTORIZZAZIONI_CSI_002 ON AUTORIZZAZIONI_CSI (IDCOMUNE,FK_CODICEGERENTE);

ALTER TABLE AUTORIZZAZIONI_CSI ADD AUT_PRECEDENTE_NUMERO VARCHAR(50);
ALTER TABLE AUTORIZZAZIONI_CSI ADD AUT_PRECEDENTE_DATA DATETIME;
ALTER TABLE AUTORIZZAZIONI_CSI ADD AUT_PRECEDENTE_COMUNE VARCHAR(5);

CREATE INDEX IDX_AUTORIZZAZIONI_CSI_003 ON AUTORIZZAZIONI_CSI(IDCOMUNE, AUT_PRECEDENTE_NUMERO);



ALTER TABLE  AUTORIZZAZIONI_SUBENTRI DROP COLUMN STAGIONALE_DA;
ALTER TABLE  AUTORIZZAZIONI_SUBENTRI DROP COLUMN STAGIONALE_A;

ALTER TABLE  AUTORIZZAZIONI_SUBENTRI add STAGIONALE_DA VARCHAR(4);
ALTER TABLE  AUTORIZZAZIONI_SUBENTRI add STAGIONALE_A VARCHAR(4);


UPDATE AUTORIZZAZIONI_SUBENTRI A 
	JOIN AUTORIZZAZIONI_CONCESSIONI B 
	ON A.IDCOMUNE = B.IDCOMUNE AND A.FK_IDAUT_ATTUALE = B.FK_IDAUT_ATTUALE   
 SET A.STAGIONALE_DA = B.STAGIONALEDA 
 WHERE A.STAGIONALE_DA IS NULL;
 
UPDATE AUTORIZZAZIONI_SUBENTRI A 
    JOIN AUTORIZZAZIONI_CONCESSIONI B ON A.IDCOMUNE = B.IDCOMUNE 
    AND  A.FK_IDAUT_ATTUALE = B.FK_IDAUT_ATTUALE
    SET A.STAGIONALE_A = B.STAGIONALEA
 WHERE A.STAGIONALE_A IS NULL;
             


ALTER TABLE AUTORIZZAZIONI_SUBENTRI_CONC DROP FOREIGN KEY FK_AUTSUBCONC_AUTCOL;

DROP INDEX IDX_AUTSUBCONC_005 ON AUTORIZZAZIONI_SUBENTRI_CONC;

ALTER TABLE AUTORIZZAZIONI_SUBENTRI_CONC DROP COLUMN FK_IDAUT_COLLEGATA;

ALTER TABLE AUTORIZZAZIONI_SUBENTRI_CONC ADD FK_IDAUTSUB_AUTCOLL NUMERIC(6,0);

ALTER TABLE AUTORIZZAZIONI_SUBENTRI_CONC ADD CONSTRAINT FK_IDAUTSUB_AUTSUBCOLL_CONC FOREIGN KEY (IDCOMUNE, FK_IDAUTSUB_AUTCOLL)
            REFERENCES AUTORIZZAZIONI_SUBENTRI (IDCOMUNE, ID) ;

CREATE INDEX IDX_AUT_SUB_CONC_001 ON AUTORIZZAZIONI_SUBENTRI_CONC(IDCOMUNE, FK_IDAUTSUB_AUTCOLL);


CREATE OR REPLACE ALGORITHM=MERGE VIEW VW_COMUNIASSOCIATIINFO AS SELECT COMUNIASSOCIATI.*, COMUNI.CODICEISTAT FROM COMUNIASSOCIATI INNER JOIN COMUNI ON COMUNIASSOCIATI.CODICECOMUNE = COMUNI.CODICECOMUNE;

CREATE OR REPLACE ALGORITHM=TEMPTABLE VIEW VW_ISTANZECONCESSIONILISTA AS SELECT 99999999 AS PROGRESSIVO, AUTORIZZAZIONI.AUTORIZRESPONSABILE AS CONC_AUTORIZRESPONSABILE, AUTORIZZAZIONI.IDCOMUNE, AUTORIZZAZIONI.FK_CAUSALE_ACQUISIZIONE AS ICONC_CODICECAUSALE, IFNULL(AUTORIZZAZIONI.DATA_CESSAZIONE,STR_TO_DATE('31/12/9999','%d/%m/%Y')) AS DATA_STORICO, ISTANZE.SOFTWARE, ISTANZE.CODICEISTANZA AS IST_CODICEISTANZA, ISTANZE.NUMEROISTANZA AS IST_NUMEROISTANZA, ISTANZE.CODICERICHIEDENTE AS IST_CODICERICHIEDENTE, AUTORIZZAZIONI.ID AS CONC_ID, AUTORIZZAZIONI.AUTORIZNUMERO AS CONC_NUMERO, AUTORIZZAZIONI.AUTORIZDATA AS CONC_DATARILASCIO, AUTORIZZAZIONI.AUTORIZDATA AS DATARILASCIO, AUTORIZZAZIONI.DATASCADENZA AS CONC_DATASCADENZA, AUTORIZZAZIONI_CONCESSIONI.FK_TIPOCONCESSIONE AS CONC_CODICETIPO, CONCESSIONITIPI.DESCRIZIONE AS CONC_TIPO, AUTORIZZAZIONI_CONCESSIONI.STAGIONALEA AS CONC_STAGIONALEA, AUTORIZZAZIONI_CONCESSIONI.STAGIONALEDA AS CONC_STAGIONALEDA, AUTORIZZAZIONI.FLAG_ATTIVA AS CONC_ATTIVA, AUTORIZZAZIONI.FK_CODICEANAGRAFE AS CONC_CODICETITOLARE, AUTORIZZAZIONI.FKIDREGISTRO AS CONC_FKIDREGISTRO, CONC_REGISTRO.TR_DESCRIZIONE AS CONC_REGISTRO, CONCAT_WS('',TITOLARE.NOMINATIVO,' ',TITOLARE.NOME) AS CONC_TITOLARE, TITOLARE.CODICEFISCALE AS CONC_TIT_CF, TITOLARE.PARTITAIVA AS CONC_TIT_PIVA, TITOLARE.TIPOANAGRAFE AS CONC_TIT_TIPOANAGRAFE, AUT_COLLEGATA.AUTORIZNUMERO AS AUT_NUMERO, AUT_COLLEGATA.AUTORIZDATA AS AUT_DATA, AUT_COLLEGATA.AUTORIZDATA, AUT_COLLEGATA.FKIDREGISTRO AS AUT_CODREGISTRO, TIPOLOGIAREGISTRI.TR_DESCRIZIONE AS AUT_REGISTRO, CONCAT_WS('',IST_RICHIEDENTE.NOMINATIVO,' ',IST_RICHIEDENTE.NOME) AS IST_NOMINATIVO, IST_RICHIEDENTE.TIPOANAGRAFE AS IST_RIC_TIPOANAGRAFE, CONCAT_WS('',IST_AZIENDA.NOMINATIVO,' ',IST_AZIENDA.NOME) AS IST_NOMINATIVOAZIENDA, IST_AZIENDA.TIPOANAGRAFE AS IST_AZI_TIPOANAGRAFE, IST_RICHIEDENTE.CODICEFISCALE AS IST_CODICEFISCALE, IST_RICHIEDENTE.PARTITAIVA AS IST_PARTITAIVA, CAUS_ATTUALE.DESCRIZIONE AS ICONC_CAUSALE, AUTORIZZAZIONI.FK_CAUSALE_CESSAZIONE AS ICONC_CODICECAUSALESTORICO, CAUS_STORICO.DESCRIZIONE AS ICONC_CAUSALESTORICO, AUTORIZZAZIONI_CONCESSIONI.FK_CODICEMERCATO AS CONC_IDMERCATO, MERCATI.DESCRIZIONE AS CONC_MERCATO, MERCATI.ATTIVO AS MERC_ATTIVO, AUTORIZZAZIONI_CONCESSIONI.FK_IDPOSTEGGIO AS CONC_IDPOSTEGGIO, MERCATI_D.CODICEPOSTEGGIO AS CONC_POSTEGGIO, MERCATI_D.LARGHEZZA AS CONC_POS_LARGHEZZA, MERCATI_D.LUNGHEZZA AS CONC_POS_LUNGHEZZA, MERCATI_D.SUPERFICIE AS CONC_POS_SUPERFICIE, MERCATI_D.FKCODICETIPOSPAZIO AS POST_IDTIPOSPAZIO, POSTEGGITIPOSPAZIO.TIPOSPAZIO AS POST_TIPOSPAZIO, AUTORIZZAZIONI_CONCESSIONI.FK_IDMERCATIUSO AS CONC_IDMERCATIUSO, MERCATI_USO.DESCRIZIONE AS CONC_DESCRIZIONEUSO, MERCATI_USO.PESO AS PESO_MERCATO, MERCATI_USO.FKCODICEUSO AS MERC_IDUSO, MERCATI_D.FKCODICESTRADARIO AS CONC_POS_CODICESTRADARIO, MERCATI_D.NOTE AS CONC_POS_NOTE, VW_ENTILOCALI.COMUNE AS CONC_ENTERILASCIO FROM AUTORIZZAZIONI INNER JOIN TIPOLOGIAREGISTRI CONC_REGISTRO ON AUTORIZZAZIONI.IDCOMUNE = CONC_REGISTRO.IDCOMUNE AND AUTORIZZAZIONI.FKIDREGISTRO = CONC_REGISTRO.TR_ID INNER JOIN AUTORIZZAZIONI_CONCESSIONI ON AUTORIZZAZIONI.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND AUTORIZZAZIONI.ID = AUTORIZZAZIONI_CONCESSIONI.FK_IDAUT_ATTUALE LEFT  JOIN AUTORIZZAZIONI AUT_COLLEGATA ON AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE = AUT_COLLEGATA.IDCOMUNE AND AUTORIZZAZIONI_CONCESSIONI.FK_IDAUT_COLLEGATA = AUT_COLLEGATA.ID LEFT  JOIN TIPOLOGIAREGISTRI ON AUT_COLLEGATA.IDCOMUNE = TIPOLOGIAREGISTRI.IDCOMUNE AND AUT_COLLEGATA.FKIDREGISTRO = TIPOLOGIAREGISTRI.TR_ID INNER JOIN CONCESSIONITIPI ON AUTORIZZAZIONI_CONCESSIONI.FK_TIPOCONCESSIONE = CONCESSIONITIPI.TIPOCONCESSIONE INNER JOIN ANAGRAFE TITOLARE ON AUTORIZZAZIONI.IDCOMUNE = TITOLARE.IDCOMUNE AND AUTORIZZAZIONI.FK_CODICEANAGRAFE = TITOLARE.CODICEANAGRAFE INNER JOIN CONCESSIONICAUSALI CAUS_ATTUALE ON AUTORIZZAZIONI.IDCOMUNE = CAUS_ATTUALE.IDCOMUNE AND AUTORIZZAZIONI.FK_CAUSALE_ACQUISIZIONE = CAUS_ATTUALE.CODICECAUSALE LEFT  JOIN CONCESSIONICAUSALI CAUS_STORICO ON AUTORIZZAZIONI.IDCOMUNE = CAUS_STORICO.IDCOMUNE AND AUTORIZZAZIONI.FK_CAUSALE_CESSAZIONE = CAUS_STORICO.CODICECAUSALE INNER JOIN ISTANZE ON AUTORIZZAZIONI.IDCOMUNE = ISTANZE.IDCOMUNE AND AUTORIZZAZIONI.FKIDISTANZA = ISTANZE.CODICEISTANZA INNER JOIN ANAGRAFE IST_RICHIEDENTE ON ISTANZE.IDCOMUNE = IST_RICHIEDENTE.IDCOMUNE AND ISTANZE.CODICERICHIEDENTE = IST_RICHIEDENTE.CODICEANAGRAFE INNER JOIN MERCATI ON AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE = MERCATI.IDCOMUNE AND AUTORIZZAZIONI_CONCESSIONI.FK_CODICEMERCATO = MERCATI.CODICEMERCATO INNER JOIN MERCATI_D ON AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE = MERCATI_D.IDCOMUNE AND AUTORIZZAZIONI_CONCESSIONI.FK_IDPOSTEGGIO = MERCATI_D.IDPOSTEGGIO LEFT  JOIN POSTEGGITIPOSPAZIO ON MERCATI_D.IDCOMUNE = POSTEGGITIPOSPAZIO.IDCOMUNE AND MERCATI_D.FKCODICETIPOSPAZIO = POSTEGGITIPOSPAZIO.CODICE INNER JOIN MERCATI_USO ON AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE = MERCATI_USO.IDCOMUNE AND AUTORIZZAZIONI_CONCESSIONI.FK_IDMERCATIUSO = MERCATI_USO.ID LEFT  JOIN ANAGRAFE IST_AZIENDA ON ISTANZE.IDCOMUNE = IST_AZIENDA.IDCOMUNE AND ISTANZE.CODICETITOLARELEGALE = IST_AZIENDA.CODICEANAGRAFE INNER JOIN VW_ENTILOCALI ON AUTORIZZAZIONI.AUTORIZCOMUNE = VW_ENTILOCALI.CODICECOMUNE UNION SELECT AUTORIZZAZIONI_SUBENTRI.ID AS PROGRESSIVO, AUTORIZZAZIONI_SUBENTRI.AUTORIZRESPONSABILE AS CONC_AUTORIZRESPONSABILE, AUTORIZZAZIONI_SUBENTRI.IDCOMUNE, AUTORIZZAZIONI_SUBENTRI.FK_CAUSALE_ACQUISIZIONE AS ICONC_CODICECAUSALE, AUTORIZZAZIONI_SUBENTRI.DATA_CESSAZIONE AS DATA_STORICO, ISTANZE.SOFTWARE, ISTANZE.CODICEISTANZA AS IST_CODICEISTANZA, ISTANZE.NUMEROISTANZA AS IST_NUMEROISTANZA, ISTANZE.CODICERICHIEDENTE AS IST_CODICERICHIEDENTE, AUTORIZZAZIONI_SUBENTRI.FK_IDAUT_ATTUALE AS CONC_ID, AUTORIZZAZIONI_SUBENTRI.AUTORIZNUMERO AS CONC_NUMERO, AUTORIZZAZIONI_SUBENTRI.AUTORIZDATA AS CONC_DATARILASCIO, AUTORIZZAZIONI_SUBENTRI.AUTORIZDATA AS DATARILASCIO, AUTORIZZAZIONI_SUBENTRI.DATASCADENZA AS CONC_DATASCADENZA, AUTORIZZAZIONI_SUBENTRI_CONC.FK_TIPOCONCESSIONE AS CONC_CODICETIPO, CONCESSIONITIPI.DESCRIZIONE AS CONC_TIPO, AUTORIZZAZIONI_SUBENTRI_CONC.STAGIONALEA AS CONC_STAGIONALEA, AUTORIZZAZIONI_SUBENTRI_CONC.STAGIONALEDA AS CONC_STAGIONALEDA, 0 AS CONC_ATTIVA, AUTORIZZAZIONI_SUBENTRI.FK_CODICEANAGRAFE AS CONC_CODICETITOLARE, AUTORIZZAZIONI_SUBENTRI.FKIDREGISTRO AS CONC_FKIDREGISTRO, CONC_REGISTRO.TR_DESCRIZIONE AS CONC_REGISTRO, CONCAT_WS('',TITOLARE.NOMINATIVO,' ',TITOLARE.NOME) AS CONC_TITOLARE, TITOLARE.CODICEFISCALE AS CONC_TIT_CF, TITOLARE.PARTITAIVA AS CONC_TIT_PIVA, TITOLARE.TIPOANAGRAFE AS CONC_TIT_TIPOANAGRAFE, AUT_COLLEGATA.AUTORIZNUMERO AS AUT_NUMERO, AUT_COLLEGATA.AUTORIZDATA AS AUT_DATA, AUT_COLLEGATA.AUTORIZDATA, AUT_COLLEGATA.FKIDREGISTRO AS AUT_CODREGISTRO, TIPOLOGIAREGISTRI.TR_DESCRIZIONE AS AUT_REGISTRO, CONCAT_WS('',IST_RICHIEDENTE.NOMINATIVO,' ',IST_RICHIEDENTE.NOME) AS IST_NOMINATIVO, IST_RICHIEDENTE.TIPOANAGRAFE AS IST_RIC_TIPOANAGRAFE, CONCAT_WS('',IST_AZIENDA.NOMINATIVO,' ',IST_AZIENDA.NOME) AS IST_NOMINATIVOAZIENDA, IST_AZIENDA.TIPOANAGRAFE AS IST_AZI_TIPOANAGRAFE, IST_RICHIEDENTE.CODICEFISCALE AS IST_CODICEFISCALE, IST_RICHIEDENTE.PARTITAIVA AS IST_PARTITAIVA, CAUS_ATTUALE.DESCRIZIONE AS ICONC_CAUSALE, AUTORIZZAZIONI_SUBENTRI.FK_CAUSALE_CESSAZIONE AS ICONC_CODICECAUSALESTORICO, CAUS_STORICO.DESCRIZIONE AS ICONC_CAUSALESTORICO, AUTORIZZAZIONI_SUBENTRI_CONC.FK_CODICEMERCATO AS CONC_IDMERCATO, MERCATI.DESCRIZIONE AS CONC_MERCATO, MERCATI.ATTIVO AS MERC_ATTIVO, AUTORIZZAZIONI_SUBENTRI_CONC.FK_IDPOSTEGGIO AS CONC_IDPOSTEGGIO, MERCATI_D.CODICEPOSTEGGIO AS CONC_POSTEGGIO, MERCATI_D.LARGHEZZA AS CONC_POS_LARGHEZZA, MERCATI_D.LUNGHEZZA AS CONC_POS_LUNGHEZZA, MERCATI_D.SUPERFICIE AS CONC_POS_SUPERFICIE, MERCATI_D.FKCODICETIPOSPAZIO AS POST_IDTIPOSPAZIO, POSTEGGITIPOSPAZIO.TIPOSPAZIO AS POST_TIPOSPAZIO, AUTORIZZAZIONI_SUBENTRI_CONC.FK_IDMERCATIUSO AS CONC_IDMERCATIUSO, MERCATI_USO.DESCRIZIONE AS CONC_DESCRIZIONEUSO, MERCATI_USO.PESO AS PESO_MERCATO, MERCATI_USO.FKCODICEUSO AS MERC_IDUSO, MERCATI_D.FKCODICESTRADARIO AS CONC_POS_CODICESTRADARIO, MERCATI_D.NOTE AS CONC_POS_NOTE, VW_ENTILOCALI.COMUNE AS CONC_ENTERILASCIO FROM AUTORIZZAZIONI_SUBENTRI INNER JOIN TIPOLOGIAREGISTRI CONC_REGISTRO ON AUTORIZZAZIONI_SUBENTRI.IDCOMUNE = CONC_REGISTRO.IDCOMUNE AND AUTORIZZAZIONI_SUBENTRI.FKIDREGISTRO = CONC_REGISTRO.TR_ID INNER JOIN AUTORIZZAZIONI_SUBENTRI_CONC ON AUTORIZZAZIONI_SUBENTRI.IDCOMUNE = AUTORIZZAZIONI_SUBENTRI_CONC.IDCOMUNE AND AUTORIZZAZIONI_SUBENTRI.ID = AUTORIZZAZIONI_SUBENTRI_CONC.FK_AUTSUB_ID LEFT  JOIN AUTORIZZAZIONI_SUBENTRI AUT_COLLEGATA ON AUTORIZZAZIONI_SUBENTRI_CONC.IDCOMUNE = AUT_COLLEGATA.IDCOMUNE AND AUTORIZZAZIONI_SUBENTRI_CONC.FK_IDAUTSUB_AUTCOLL = AUT_COLLEGATA.ID LEFT  JOIN TIPOLOGIAREGISTRI ON AUT_COLLEGATA.IDCOMUNE = TIPOLOGIAREGISTRI.IDCOMUNE AND AUT_COLLEGATA.FKIDREGISTRO = TIPOLOGIAREGISTRI.TR_ID INNER JOIN CONCESSIONITIPI ON AUTORIZZAZIONI_SUBENTRI_CONC.FK_TIPOCONCESSIONE = CONCESSIONITIPI.TIPOCONCESSIONE INNER JOIN ANAGRAFE TITOLARE ON AUTORIZZAZIONI_SUBENTRI.IDCOMUNE = TITOLARE.IDCOMUNE AND AUTORIZZAZIONI_SUBENTRI.FK_CODICEANAGRAFE = TITOLARE.CODICEANAGRAFE INNER JOIN CONCESSIONICAUSALI CAUS_ATTUALE ON AUTORIZZAZIONI_SUBENTRI.IDCOMUNE = CAUS_ATTUALE.IDCOMUNE AND AUTORIZZAZIONI_SUBENTRI.FK_CAUSALE_ACQUISIZIONE = CAUS_ATTUALE.CODICECAUSALE LEFT  JOIN CONCESSIONICAUSALI CAUS_STORICO ON AUTORIZZAZIONI_SUBENTRI.IDCOMUNE = CAUS_STORICO.IDCOMUNE AND AUTORIZZAZIONI_SUBENTRI.FK_CAUSALE_CESSAZIONE = CAUS_STORICO.CODICECAUSALE INNER JOIN ISTANZE ON AUTORIZZAZIONI_SUBENTRI.IDCOMUNE = ISTANZE.IDCOMUNE AND AUTORIZZAZIONI_SUBENTRI.FKIDISTANZA = ISTANZE.CODICEISTANZA INNER JOIN ANAGRAFE IST_RICHIEDENTE ON ISTANZE.IDCOMUNE = IST_RICHIEDENTE.IDCOMUNE AND ISTANZE.CODICERICHIEDENTE = IST_RICHIEDENTE.CODICEANAGRAFE INNER JOIN MERCATI ON AUTORIZZAZIONI_SUBENTRI_CONC.IDCOMUNE = MERCATI.IDCOMUNE AND AUTORIZZAZIONI_SUBENTRI_CONC.FK_CODICEMERCATO = MERCATI.CODICEMERCATO INNER JOIN MERCATI_D ON AUTORIZZAZIONI_SUBENTRI_CONC.IDCOMUNE = MERCATI_D.IDCOMUNE AND AUTORIZZAZIONI_SUBENTRI_CONC.FK_IDPOSTEGGIO = MERCATI_D.IDPOSTEGGIO LEFT  JOIN POSTEGGITIPOSPAZIO ON MERCATI_D.IDCOMUNE = POSTEGGITIPOSPAZIO.IDCOMUNE AND MERCATI_D.FKCODICETIPOSPAZIO = POSTEGGITIPOSPAZIO.CODICE INNER JOIN MERCATI_USO ON AUTORIZZAZIONI_SUBENTRI_CONC.IDCOMUNE = MERCATI_USO.IDCOMUNE AND AUTORIZZAZIONI_SUBENTRI_CONC.FK_IDMERCATIUSO = MERCATI_USO.ID LEFT  JOIN ANAGRAFE IST_AZIENDA ON ISTANZE.IDCOMUNE = IST_AZIENDA.IDCOMUNE AND ISTANZE.CODICETITOLARELEGALE = IST_AZIENDA.CODICEANAGRAFE INNER JOIN VW_ENTILOCALI ON AUTORIZZAZIONI_SUBENTRI.AUTORIZCOMUNE = VW_ENTILOCALI.CODICECOMUNE;
alter table AUTORIZZAZIONI_CSI ADD TIPOLOGIA_BATTITORI VARCHAR(1) DEFAULT 'N';

ALTER TABLE MERCATIPRESENZE_D ADD FK_CODICECOLLABORATORE NUMERIC(6,0);

ALTER TABLE MERCATIPRESENZE_D ADD CONSTRAINT FK_MERCPRESD_ANAGCOLLAB FOREIGN KEY (IDCOMUNE,FK_CODICECOLLABORATORE) REFERENCES ANAGRAFE (IDCOMUNE,CODICEANAGRAFE);
CREATE INDEX IDX_MERCATIPRESENZED_ANACOLL ON MERCATIPRESENZE_D (IDCOMUNE,FK_CODICECOLLABORATORE);


ALTER TABLE AUTORIZZAZIONI ADD DATA_RILASCIO DATETIME;
ALTER TABLE AUTORIZZAZIONI_SUBENTRI ADD DATA_RILASCIO DATETIME;

CREATE OR REPLACE ALGORITHM=TEMPTABLE VIEW VW_ISTANZECONCESSIONILISTA AS SELECT 99999999 AS PROGRESSIVO , AUTORIZZAZIONI.AUTORIZRESPONSABILE AS CONC_AUTORIZRESPONSABILE , AUTORIZZAZIONI.IDCOMUNE , AUTORIZZAZIONI.FK_CAUSALE_ACQUISIZIONE AS ICONC_CODICECAUSALE , IFNULL(AUTORIZZAZIONI.DATA_CESSAZIONE,STR_TO_DATE('31/12/9999','%d/%m/%Y')) AS DATA_STORICO , ISTANZE.SOFTWARE , ISTANZE.CODICEISTANZA AS IST_CODICEISTANZA , ISTANZE.NUMEROISTANZA AS IST_NUMEROISTANZA , ISTANZE.CODICERICHIEDENTE AS IST_CODICERICHIEDENTE , AUTORIZZAZIONI.ID AS CONC_ID , AUTORIZZAZIONI.AUTORIZNUMERO AS CONC_NUMERO , AUTORIZZAZIONI.AUTORIZDATA AS CONC_DATAVALIDITA , AUTORIZZAZIONI.AUTORIZDATA AS DATAVALIDITA                         , AUTORIZZAZIONI.DATA_RILASCIO AS CONC_DATARILASCIO , AUTORIZZAZIONI.DATA_RILASCIO AS DATARILASCIO , AUTORIZZAZIONI.DATASCADENZA AS CONC_DATASCADENZA , AUTORIZZAZIONI_CONCESSIONI.FK_TIPOCONCESSIONE AS CONC_CODICETIPO , CONCESSIONITIPI.DESCRIZIONE AS CONC_TIPO , AUTORIZZAZIONI_CONCESSIONI.STAGIONALEA AS CONC_STAGIONALEA , AUTORIZZAZIONI_CONCESSIONI.STAGIONALEDA AS CONC_STAGIONALEDA , AUTORIZZAZIONI.FLAG_ATTIVA AS CONC_ATTIVA , AUTORIZZAZIONI.FK_CODICEANAGRAFE AS CONC_CODICETITOLARE , AUTORIZZAZIONI.FKIDREGISTRO AS CONC_FKIDREGISTRO , CONC_REGISTRO.TR_DESCRIZIONE AS CONC_REGISTRO , CONCAT_WS('',TITOLARE.NOMINATIVO,' ',TITOLARE.NOME) AS CONC_TITOLARE , TITOLARE.CODICEFISCALE AS CONC_TIT_CF , TITOLARE.PARTITAIVA AS CONC_TIT_PIVA , TITOLARE.TIPOANAGRAFE AS CONC_TIT_TIPOANAGRAFE , AUT_COLLEGATA.AUTORIZNUMERO AS AUT_NUMERO , AUT_COLLEGATA.AUTORIZDATA AS AUT_DATA , AUT_COLLEGATA.AUTORIZDATA , AUT_COLLEGATA.FKIDREGISTRO AS AUT_CODREGISTRO , TIPOLOGIAREGISTRI.TR_DESCRIZIONE AS AUT_REGISTRO , CONCAT_WS('',IST_RICHIEDENTE.NOMINATIVO,' ',IST_RICHIEDENTE.NOME) AS IST_NOMINATIVO , IST_RICHIEDENTE.TIPOANAGRAFE AS IST_RIC_TIPOANAGRAFE , CONCAT_WS('',IST_AZIENDA.NOMINATIVO,' ',IST_AZIENDA.NOME) AS IST_NOMINATIVOAZIENDA , IST_AZIENDA.TIPOANAGRAFE AS IST_AZI_TIPOANAGRAFE , IST_RICHIEDENTE.CODICEFISCALE AS IST_CODICEFISCALE , IST_RICHIEDENTE.PARTITAIVA AS IST_PARTITAIVA , CAUS_ATTUALE.DESCRIZIONE AS ICONC_CAUSALE , AUTORIZZAZIONI.FK_CAUSALE_CESSAZIONE AS ICONC_CODICECAUSALESTORICO , CAUS_STORICO.DESCRIZIONE AS ICONC_CAUSALESTORICO , AUTORIZZAZIONI_CONCESSIONI.FK_CODICEMERCATO AS CONC_IDMERCATO , MERCATI.DESCRIZIONE AS CONC_MERCATO , MERCATI.ATTIVO AS MERC_ATTIVO , AUTORIZZAZIONI_CONCESSIONI.FK_IDPOSTEGGIO AS CONC_IDPOSTEGGIO , MERCATI_D.CODICEPOSTEGGIO AS CONC_POSTEGGIO , MERCATI_D.LARGHEZZA AS CONC_POS_LARGHEZZA , MERCATI_D.LUNGHEZZA AS CONC_POS_LUNGHEZZA , MERCATI_D.SUPERFICIE AS CONC_POS_SUPERFICIE , MERCATI_D.FKCODICETIPOSPAZIO AS POST_IDTIPOSPAZIO , POSTEGGITIPOSPAZIO.TIPOSPAZIO AS POST_TIPOSPAZIO , AUTORIZZAZIONI_CONCESSIONI.FK_IDMERCATIUSO AS CONC_IDMERCATIUSO , MERCATI_USO.DESCRIZIONE AS CONC_DESCRIZIONEUSO , MERCATI_USO.PESO AS PESO_MERCATO , MERCATI_USO.FKCODICEUSO AS MERC_IDUSO , MERCATI_D.FKCODICESTRADARIO AS CONC_POS_CODICESTRADARIO , MERCATI_D.NOTE AS CONC_POS_NOTE , VW_ENTILOCALI.COMUNE AS CONC_ENTERILASCIO FROM AUTORIZZAZIONI INNER JOIN TIPOLOGIAREGISTRI CONC_REGISTRO ON AUTORIZZAZIONI.IDCOMUNE = CONC_REGISTRO.IDCOMUNE AND AUTORIZZAZIONI.FKIDREGISTRO = CONC_REGISTRO.TR_ID INNER JOIN AUTORIZZAZIONI_CONCESSIONI ON AUTORIZZAZIONI.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND AUTORIZZAZIONI.ID = AUTORIZZAZIONI_CONCESSIONI.FK_IDAUT_ATTUALE LEFT JOIN AUTORIZZAZIONI AUT_COLLEGATA ON AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE = AUT_COLLEGATA.IDCOMUNE AND AUTORIZZAZIONI_CONCESSIONI.FK_IDAUT_COLLEGATA = AUT_COLLEGATA.ID LEFT JOIN TIPOLOGIAREGISTRI ON AUT_COLLEGATA.IDCOMUNE = TIPOLOGIAREGISTRI.IDCOMUNE AND AUT_COLLEGATA.FKIDREGISTRO = TIPOLOGIAREGISTRI.TR_ID INNER JOIN CONCESSIONITIPI ON AUTORIZZAZIONI_CONCESSIONI.FK_TIPOCONCESSIONE = CONCESSIONITIPI.TIPOCONCESSIONE INNER JOIN ANAGRAFE TITOLARE ON AUTORIZZAZIONI.IDCOMUNE = TITOLARE.IDCOMUNE AND AUTORIZZAZIONI.FK_CODICEANAGRAFE = TITOLARE.CODICEANAGRAFE INNER JOIN CONCESSIONICAUSALI CAUS_ATTUALE ON AUTORIZZAZIONI.IDCOMUNE = CAUS_ATTUALE.IDCOMUNE AND AUTORIZZAZIONI.FK_CAUSALE_ACQUISIZIONE = CAUS_ATTUALE.CODICECAUSALE LEFT JOIN CONCESSIONICAUSALI CAUS_STORICO ON AUTORIZZAZIONI.IDCOMUNE = CAUS_STORICO.IDCOMUNE AND AUTORIZZAZIONI.FK_CAUSALE_CESSAZIONE = CAUS_STORICO.CODICECAUSALE INNER JOIN ISTANZE ON AUTORIZZAZIONI.IDCOMUNE = ISTANZE.IDCOMUNE AND AUTORIZZAZIONI.FKIDISTANZA = ISTANZE.CODICEISTANZA INNER JOIN ANAGRAFE IST_RICHIEDENTE ON ISTANZE.IDCOMUNE = IST_RICHIEDENTE.IDCOMUNE AND ISTANZE.CODICERICHIEDENTE = IST_RICHIEDENTE.CODICEANAGRAFE INNER JOIN MERCATI ON AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE = MERCATI.IDCOMUNE AND AUTORIZZAZIONI_CONCESSIONI.FK_CODICEMERCATO = MERCATI.CODICEMERCATO INNER JOIN MERCATI_D ON AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE = MERCATI_D.IDCOMUNE AND AUTORIZZAZIONI_CONCESSIONI.FK_IDPOSTEGGIO = MERCATI_D.IDPOSTEGGIO LEFT JOIN POSTEGGITIPOSPAZIO ON MERCATI_D.IDCOMUNE = POSTEGGITIPOSPAZIO.IDCOMUNE AND MERCATI_D.FKCODICETIPOSPAZIO = POSTEGGITIPOSPAZIO.CODICE INNER JOIN MERCATI_USO ON AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE = MERCATI_USO.IDCOMUNE AND AUTORIZZAZIONI_CONCESSIONI.FK_IDMERCATIUSO = MERCATI_USO.ID LEFT JOIN ANAGRAFE IST_AZIENDA ON ISTANZE.IDCOMUNE = IST_AZIENDA.IDCOMUNE AND ISTANZE.CODICETITOLARELEGALE = IST_AZIENDA.CODICEANAGRAFE INNER JOIN VW_ENTILOCALI ON AUTORIZZAZIONI.AUTORIZCOMUNE = VW_ENTILOCALI.CODICECOMUNE UNION SELECT AUTORIZZAZIONI_SUBENTRI.ID AS PROGRESSIVO , AUTORIZZAZIONI_SUBENTRI.AUTORIZRESPONSABILE AS CONC_AUTORIZRESPONSABILE , AUTORIZZAZIONI_SUBENTRI.IDCOMUNE , AUTORIZZAZIONI_SUBENTRI.FK_CAUSALE_ACQUISIZIONE AS ICONC_CODICECAUSALE , AUTORIZZAZIONI_SUBENTRI.DATA_CESSAZIONE AS DATA_STORICO , ISTANZE.SOFTWARE , ISTANZE.CODICEISTANZA AS IST_CODICEISTANZA , ISTANZE.NUMEROISTANZA AS IST_NUMEROISTANZA , ISTANZE.CODICERICHIEDENTE AS IST_CODICERICHIEDENTE , AUTORIZZAZIONI_SUBENTRI.FK_IDAUT_ATTUALE AS CONC_ID , AUTORIZZAZIONI_SUBENTRI.AUTORIZNUMERO AS CONC_NUMERO, AUTORIZZAZIONI_SUBENTRI.AUTORIZDATA AS CONC_DATAVALIDITA , AUTORIZZAZIONI_SUBENTRI.AUTORIZDATA AS DATAVALIDITA                   , AUTORIZZAZIONI_SUBENTRI.DATA_RILASCIO AS CONC_DATARILASCIO , AUTORIZZAZIONI_SUBENTRI.DATA_RILASCIO AS DATARILASCIO , AUTORIZZAZIONI_SUBENTRI.DATASCADENZA AS CONC_DATASCADENZA , AUTORIZZAZIONI_SUBENTRI_CONC.FK_TIPOCONCESSIONE AS CONC_CODICETIPO , CONCESSIONITIPI.DESCRIZIONE AS CONC_TIPO , AUTORIZZAZIONI_SUBENTRI_CONC.STAGIONALEA AS CONC_STAGIONALEA , AUTORIZZAZIONI_SUBENTRI_CONC.STAGIONALEDA AS CONC_STAGIONALEDA , 0 AS CONC_ATTIVA , AUTORIZZAZIONI_SUBENTRI.FK_CODICEANAGRAFE AS CONC_CODICETITOLARE , AUTORIZZAZIONI_SUBENTRI.FKIDREGISTRO AS CONC_FKIDREGISTRO , CONC_REGISTRO.TR_DESCRIZIONE AS CONC_REGISTRO , CONCAT_WS('',TITOLARE.NOMINATIVO,' ',TITOLARE.NOME) AS CONC_TITOLARE , TITOLARE.CODICEFISCALE AS CONC_TIT_CF , TITOLARE.PARTITAIVA AS CONC_TIT_PIVA , TITOLARE.TIPOANAGRAFE AS CONC_TIT_TIPOANAGRAFE , AUT_COLLEGATA.AUTORIZNUMERO AS AUT_NUMERO , AUT_COLLEGATA.AUTORIZDATA AS AUT_DATA , AUT_COLLEGATA.AUTORIZDATA , AUT_COLLEGATA.FKIDREGISTRO AS AUT_CODREGISTRO , TIPOLOGIAREGISTRI.TR_DESCRIZIONE AS AUT_REGISTRO , CONCAT_WS('',IST_RICHIEDENTE.NOMINATIVO,' ',IST_RICHIEDENTE.NOME) AS IST_NOMINATIVO , IST_RICHIEDENTE.TIPOANAGRAFE AS IST_RIC_TIPOANAGRAFE , CONCAT_WS('',IST_AZIENDA.NOMINATIVO,' ',IST_AZIENDA.NOME) AS IST_NOMINATIVOAZIENDA , IST_AZIENDA.TIPOANAGRAFE AS IST_AZI_TIPOANAGRAFE , IST_RICHIEDENTE.CODICEFISCALE AS IST_CODICEFISCALE , IST_RICHIEDENTE.PARTITAIVA AS IST_PARTITAIVA , CAUS_ATTUALE.DESCRIZIONE AS ICONC_CAUSALE , AUTORIZZAZIONI_SUBENTRI.FK_CAUSALE_CESSAZIONE AS ICONC_CODICECAUSALESTORICO , CAUS_STORICO.DESCRIZIONE AS ICONC_CAUSALESTORICO , AUTORIZZAZIONI_SUBENTRI_CONC.FK_CODICEMERCATO AS CONC_IDMERCATO , MERCATI.DESCRIZIONE AS CONC_MERCATO , MERCATI.ATTIVO AS MERC_ATTIVO , AUTORIZZAZIONI_SUBENTRI_CONC.FK_IDPOSTEGGIO AS CONC_IDPOSTEGGIO , MERCATI_D.CODICEPOSTEGGIO AS CONC_POSTEGGIO , MERCATI_D.LARGHEZZA AS CONC_POS_LARGHEZZA , MERCATI_D.LUNGHEZZA AS CONC_POS_LUNGHEZZA , MERCATI_D.SUPERFICIE AS CONC_POS_SUPERFICIE , MERCATI_D.FKCODICETIPOSPAZIO AS POST_IDTIPOSPAZIO , POSTEGGITIPOSPAZIO.TIPOSPAZIO AS POST_TIPOSPAZIO , AUTORIZZAZIONI_SUBENTRI_CONC.FK_IDMERCATIUSO AS CONC_IDMERCATIUSO , MERCATI_USO.DESCRIZIONE AS CONC_DESCRIZIONEUSO , MERCATI_USO.PESO AS PESO_MERCATO , MERCATI_USO.FKCODICEUSO AS MERC_IDUSO , MERCATI_D.FKCODICESTRADARIO AS CONC_POS_CODICESTRADARIO , MERCATI_D.NOTE AS CONC_POS_NOTE , VW_ENTILOCALI.COMUNE AS CONC_ENTERILASCIO FROM AUTORIZZAZIONI_SUBENTRI INNER JOIN TIPOLOGIAREGISTRI CONC_REGISTRO ON AUTORIZZAZIONI_SUBENTRI.IDCOMUNE = CONC_REGISTRO.IDCOMUNE AND AUTORIZZAZIONI_SUBENTRI.FKIDREGISTRO = CONC_REGISTRO.TR_ID INNER JOIN AUTORIZZAZIONI_SUBENTRI_CONC ON AUTORIZZAZIONI_SUBENTRI.IDCOMUNE = AUTORIZZAZIONI_SUBENTRI_CONC.IDCOMUNE AND AUTORIZZAZIONI_SUBENTRI.ID = AUTORIZZAZIONI_SUBENTRI_CONC.FK_AUTSUB_ID LEFT JOIN AUTORIZZAZIONI_SUBENTRI AUT_COLLEGATA ON AUTORIZZAZIONI_SUBENTRI_CONC.IDCOMUNE = AUT_COLLEGATA.IDCOMUNE AND AUTORIZZAZIONI_SUBENTRI_CONC.FK_IDAUTSUB_AUTCOLL = AUT_COLLEGATA.ID LEFT JOIN TIPOLOGIAREGISTRI ON AUT_COLLEGATA.IDCOMUNE = TIPOLOGIAREGISTRI.IDCOMUNE AND AUT_COLLEGATA.FKIDREGISTRO = TIPOLOGIAREGISTRI.TR_ID INNER JOIN CONCESSIONITIPI ON AUTORIZZAZIONI_SUBENTRI_CONC.FK_TIPOCONCESSIONE = CONCESSIONITIPI.TIPOCONCESSIONE INNER JOIN ANAGRAFE TITOLARE ON AUTORIZZAZIONI_SUBENTRI.IDCOMUNE = TITOLARE.IDCOMUNE AND AUTORIZZAZIONI_SUBENTRI.FK_CODICEANAGRAFE = TITOLARE.CODICEANAGRAFE INNER JOIN CONCESSIONICAUSALI CAUS_ATTUALE ON AUTORIZZAZIONI_SUBENTRI.IDCOMUNE = CAUS_ATTUALE.IDCOMUNE AND AUTORIZZAZIONI_SUBENTRI.FK_CAUSALE_ACQUISIZIONE = CAUS_ATTUALE.CODICECAUSALE LEFT JOIN CONCESSIONICAUSALI CAUS_STORICO ON AUTORIZZAZIONI_SUBENTRI.IDCOMUNE = CAUS_STORICO.IDCOMUNE AND AUTORIZZAZIONI_SUBENTRI.FK_CAUSALE_CESSAZIONE = CAUS_STORICO.CODICECAUSALE INNER JOIN ISTANZE ON AUTORIZZAZIONI_SUBENTRI.IDCOMUNE = ISTANZE.IDCOMUNE AND AUTORIZZAZIONI_SUBENTRI.FKIDISTANZA = ISTANZE.CODICEISTANZA INNER JOIN ANAGRAFE IST_RICHIEDENTE ON ISTANZE.IDCOMUNE = IST_RICHIEDENTE.IDCOMUNE AND ISTANZE.CODICERICHIEDENTE = IST_RICHIEDENTE.CODICEANAGRAFE INNER JOIN MERCATI ON AUTORIZZAZIONI_SUBENTRI_CONC.IDCOMUNE = MERCATI.IDCOMUNE AND AUTORIZZAZIONI_SUBENTRI_CONC.FK_CODICEMERCATO = MERCATI.CODICEMERCATO INNER JOIN MERCATI_D ON AUTORIZZAZIONI_SUBENTRI_CONC.IDCOMUNE = MERCATI_D.IDCOMUNE AND AUTORIZZAZIONI_SUBENTRI_CONC.FK_IDPOSTEGGIO = MERCATI_D.IDPOSTEGGIO LEFT JOIN POSTEGGITIPOSPAZIO ON MERCATI_D.IDCOMUNE = POSTEGGITIPOSPAZIO.IDCOMUNE AND MERCATI_D.FKCODICETIPOSPAZIO = POSTEGGITIPOSPAZIO.CODICE INNER JOIN MERCATI_USO ON AUTORIZZAZIONI_SUBENTRI_CONC.IDCOMUNE = MERCATI_USO.IDCOMUNE AND AUTORIZZAZIONI_SUBENTRI_CONC.FK_IDMERCATIUSO = MERCATI_USO.ID LEFT JOIN ANAGRAFE IST_AZIENDA ON ISTANZE.IDCOMUNE = IST_AZIENDA.IDCOMUNE AND ISTANZE.CODICETITOLARELEGALE = IST_AZIENDA.CODICEANAGRAFE INNER JOIN VW_ENTILOCALI ON AUTORIZZAZIONI_SUBENTRI.AUTORIZCOMUNE = VW_ENTILOCALI.CODICECOMUNE ;

CREATE OR REPLACE ALGORITHM=TEMPTABLE VIEW VW_CONCESSIONILISTA AS 
SELECT IDCOMUNE, SOFTWARE, PROGRESSIVO, CONC_ID, CONC_NUMERO,CONC_DATAVALIDITA, CONC_DATARILASCIO, CONC_DATASCADENZA, CONC_CODICETIPO, CONC_TIPO, CONC_STAGIONALEA, CONC_STAGIONALEDA, CONC_ATTIVA, CONC_CODICETITOLARE, CONC_TITOLARE, CONC_TIT_CF, CONC_TIT_PIVA, CONC_TIT_TIPOANAGRAFE, CONC_FKIDREGISTRO, CONC_REGISTRO, AUT_NUMERO, AUT_DATA, AUT_CODREGISTRO, AUT_REGISTRO, IST_CODICEISTANZA, IST_NUMEROISTANZA, IST_CODICERICHIEDENTE, IST_NOMINATIVO, IST_CODICEFISCALE, IST_PARTITAIVA, IST_RIC_TIPOANAGRAFE, ICONC_CODICECAUSALE, ICONC_CAUSALE, ICONC_CODICECAUSALESTORICO, ICONC_CAUSALESTORICO, CONC_IDMERCATO, CONC_MERCATO, MERC_ATTIVO, CONC_IDPOSTEGGIO, CONC_POSTEGGIO, CONC_POS_LARGHEZZA, CONC_POS_LUNGHEZZA, CONC_POS_SUPERFICIE, POST_IDTIPOSPAZIO, POST_TIPOSPAZIO, CONC_IDMERCATIUSO, CONC_DESCRIZIONEUSO, PESO_MERCATO, MERC_IDUSO, CONC_POS_CODICESTRADARIO, DATA_STORICO, CONC_ENTERILASCIO FROM VW_ISTANZECONCESSIONILISTA;

create table BATTITORI_CSI(
IDCOMUNE VARCHAR(6) NOT NULL,
ID NUMERIC(10,0) NOT NULL,
FK_IDAUTORIZZAZIONE NUMERIC(6,0) NOT NULL,
FK_GS_ID NUMERIC(2,0),
SIAP_DENOMINAZIONE VARCHAR(100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE BATTITORI_CSI ADD CONSTRAINT PK_BATTITORI_CSI PRIMARY KEY (IDCOMUNE,ID);
ALTER TABLE BATTITORI_CSI ADD CONSTRAINT FK_BATTCSI_AUTORIZZAZIONI FOREIGN KEY (IDCOMUNE,FK_IDAUTORIZZAZIONE) REFERENCES AUTORIZZAZIONI(IDCOMUNE,ID);
ALTER TABLE BATTITORI_CSI ADD CONSTRAINT FK_BATTCSI_GIORNISETTIMANA FOREIGN KEY (FK_GS_ID) REFERENCES GIORNISETTIMANA(GS_ID);


ALTER TABLE MERCATI ADD CIRCOSCRIZIONE VARCHAR(50);
alter table istanzestradario modify esponente varchar(25);

ALTER TABLE RESPONSABILI ADD CIRCOSCRIZIONE VARCHAR(50);

CREATE TABLE AUTORIZ_SUB_BK20190703 AS SELECT * FROM Autorizzazioni_Subentri;