ALTER TABLE TEMP_LINKALLEGATI ADD PIN NUMBER(10,0);
ALTER TABLE TEMP_LINKALLEGATI MODIFY CODICEOGGETTO NUMBER(10,0) NULL;





CREATE TABLE TIPO_COMUNICAZIONI_T (
  CODICE VARCHAR2(15 ) NOT NULL 
, DESCRIZIONE VARCHAR2(500 ) NOT NULL
);

ALTER TABLE  TIPO_COMUNICAZIONI_T ADD CONSTRAINT PK_TIPO_COMUNICAZIONI_T PRIMARY KEY 
(
CODICE
);

INSERT INTO TIPO_COMUNICAZIONI_T (CODICE,DESCRIZIONE) VALUES ('CONCESSIONI', 'COMUNICAZIONI AI CONCESSIONARI');


CREATE TABLE COMUNICAZIONI_T
(
  IDCOMUNE VARCHAR2(6 ) NOT NULL 
, ID NUMBER(10, 0) NOT NULL 
, DATA DATE NOT NULL 
, DESCRIZIONE VARCHAR2(500 ) 
, TIPOMOVIMENTO VARCHAR2(8 ) 
, FLG_PROTOCOLLA NUMBER(1, 0) 
, CODICELETTERA NUMBER(10, 0) 
, CODICEMAIL NUMBER(4, 0) 
, AMMINISTRAZIONE_PROT NUMBER(10, 0) 
, FLAG_METTIALLAFIRMA NUMBER(1, 0) 
, LISTA_FIRMATARI VARCHAR2(200 ) 
, FLG_TRASFORMA_PDF NUMBER(1, 0) 
, PROT_DOPO_CREAZIONE_ALLEGATO NUMBER(1, 0) 
, FLAG_PREVEDE_PRESENZA_ISTANZA NUMBER(1, 0)
, FK_TIPO_COMUNICAZIONI_T VARCHAR2(15 ) NOT NULL
, STATO_ELABORAZIONE  NUMBER (1,0)
);

ALTER TABLE COMUNICAZIONI_T ADD CONSTRAINT PK_COMUNICAZIONI_T PRIMARY KEY 
(
IDCOMUNE 
, ID 
);

ALTER TABLE COMUNICAZIONI_T ADD CONSTRAINT FK_COMUN_T_TIPO_COM_T FOREIGN KEY
( 
 FK_TIPO_COMUNICAZIONI_T 
)
REFERENCES TIPO_COMUNICAZIONI_T
( 
 CODICE 
)
;

ALTER TABLE COMUNICAZIONI_T ADD CONSTRAINT FK_COMUN_T_AMM_PROT FOREIGN KEY
(
  IDCOMUNE 
, AMMINISTRAZIONE_PROT 
)
REFERENCES AMMINISTRAZIONI
(
  IDCOMUNE 
, CODICEAMMINISTRAZIONE 
)
;

ALTER TABLE COMUNICAZIONI_T ADD CONSTRAINT FK_COMUN_T_LETT_TIPO FOREIGN KEY
(
  IDCOMUNE 
, CODICELETTERA 
)
REFERENCES LETTERETIPO
(
  IDCOMUNE 
, CODICELETTERA 
)
;

ALTER TABLE COMUNICAZIONI_T ADD CONSTRAINT FFK_COMUN_T_MAILTIPO FOREIGN KEY
(
  IDCOMUNE 
, CODICEMAIL 
)
REFERENCES MAILTIPO
(
  IDCOMUNE 
, CODICEMAIL 
)
;

ALTER TABLE COMUNICAZIONI_T ADD CONSTRAINT FK_COMUN_T_TIPOMOV FOREIGN KEY
(
  IDCOMUNE 
, TIPOMOVIMENTO 
)
REFERENCES TIPIMOVIMENTO
(
  IDCOMUNE 
, TIPOMOVIMENTO 
)
;

CREATE TABLE COMUNICAZIONI_T_MERCATO
(
  IDCOMUNE VARCHAR2(6 ) NOT NULL 
, ID NUMBER(10, 0) NOT NULL 
, CODICEMERCATO NUMBER (4,0) NOT NULL
, FK_COMUNICAZIONI_T NUMBER (10, 0) NOT NULL 
);

ALTER TABLE COMUNICAZIONI_T_MERCATO ADD CONSTRAINT PK_COMUNICAZIONI_T_MERCATO PRIMARY KEY   (IDCOMUNE,ID);

ALTER TABLE COMUNICAZIONI_T_MERCATO ADD CONSTRAINT FK_COMUN_T_MERC_MERCATO FOREIGN KEY
(
  IDCOMUNE 
, CODICEMERCATO 
)
REFERENCES MERCATI
(
  IDCOMUNE 
, CODICEMERCATO 
)
;

ALTER TABLE COMUNICAZIONI_T_MERCATO ADD CONSTRAINT FK_COMUN_T_MERC_COMUN_T FOREIGN KEY
(
  IDCOMUNE 
, FK_COMUNICAZIONI_T 
)
REFERENCES COMUNICAZIONI_T
(
  IDCOMUNE 
, ID 
)
;

CREATE TABLE COMUNICAZIONI_D_CONCESSIONI
(
  IDCOMUNE VARCHAR2(6 ) NOT NULL 
, ID NUMBER(10, 0) NOT NULL 
, FK_AUTORIZZAZIONI_CONCESSIONI NUMBER(6, 0) NOT NULL 
, FK_COMUNICAZIONI_D NUMBER (10, 0) NOT NULL 

);

ALTER TABLE COMUNICAZIONI_D_CONCESSIONI ADD  CONSTRAINT PK_COMUNICAZIONI_D_CONCESSIONI PRIMARY KEY 
  (
    IDCOMUNE 
  , ID 
  );

ALTER TABLE COMUNICAZIONI_D_CONCESSIONI ADD CONSTRAINT FK_COMUN_D_CONC_CONC FOREIGN KEY
(
  IDCOMUNE 
, FK_AUTORIZZAZIONI_CONCESSIONI 
)
REFERENCES AUTORIZZAZIONI_CONCESSIONI
(
  IDCOMUNE 
, ID 
)
;




CREATE TABLE COMUNICAZIONI_D 
(
  IDCOMUNE VARCHAR2(6 ) NOT NULL 
, ID NUMBER(10, 0) NOT NULL 
, CODICEMOVIMENTO NUMBER(8, 0) 
, FLG_PROTOCOLLATO NUMBER(1, 0) NOT NULL 
, CODICEOGGETTO NUMBER(10, 0) 
, FK_IDMAIL NUMBER(8, 0)
, STATO_ELABORAZIONE  NUMBER (1,0) NOT NULL
, FK_COMUNICAZIONI_T NUMBER(10, 0) NOT NULL
) ;




ALTER TABLE COMUNICAZIONI_D ADD CONSTRAINT PK_COMUNICAZIONI_D PRIMARY KEY 
(
IDCOMUNE 
, ID 
);

ALTER TABLE COMUNICAZIONI_D ADD CONSTRAINT FK_COMUN_D_COMUN_T FOREIGN KEY
(
  IDCOMUNE 
, FK_COMUNICAZIONI_T
)
REFERENCES COMUNICAZIONI_T
(
  IDCOMUNE 
, ID 
);

ALTER TABLE COMUNICAZIONI_D ADD CONSTRAINT FK_COMUN_D_MOVIM FOREIGN KEY
(
  IDCOMUNE 
, CODICEMOVIMENTO 
)
REFERENCES MOVIMENTI
(
  IDCOMUNE 
, CODICEMOVIMENTO 
)
;

ALTER TABLE COMUNICAZIONI_D ADD CONSTRAINT FK_COMUN_D_MOV_MAIL FOREIGN KEY
(
  IDCOMUNE 
, FK_IDMAIL 
)
REFERENCES MOVIMENTIMAIL
(
  IDCOMUNE 
, ID 
)
;

ALTER TABLE COMUNICAZIONI_D ADD CONSTRAINT FK_COMUN_D_OGGETTI FOREIGN KEY
(
  IDCOMUNE 
, CODICEOGGETTO 
)
REFERENCES OGGETTI
(
  IDCOMUNE 
, CODICEOGGETTO 
)
;


ALTER TABLE COMUNICAZIONI_D_CONCESSIONI ADD CONSTRAINT FK_FK_COMUN_D_CONC_COMUNIC_D FOREIGN KEY
(
  IDCOMUNE 
, FK_COMUNICAZIONI_D 
)
REFERENCES COMUNICAZIONI_D
(
  IDCOMUNE 
, ID 
);

CREATE TABLE TMP_STATI_COMUNICAZIONI_D
(
   IDCOMUNE  VARCHAR2(6 ) NOT NULL
,  POSIZIONE NUMBER(2, 0) NOT NULL
, FK_COMUNICAZIONI_D NUMBER(10, 0) NOT NULL 
, EVENTO VARCHAR2(500) 
, STATO  VARCHAR2(50) NOT NULL
);
