CREATE TABLE DOCUMENTI_CONDIVISI(
 IDCOMUNE VARCHAR2(6 CHAR) NOT NULL,
 ID NUMBER(10,0) NOT NULL,
 CODICEOGGETTO NUMBER(10,0),
 CODICEISTANZA NUMBER(6,0),
 CODICEMOVIMENTO NUMBER(8,0),
 STATO VARCHAR2(25 CHAR)
);
ALTER TABLE DOCUMENTI_CONDIVISI ADD CONSTRAINT PK_DOCUMENTICONDIVISI PRIMARY KEY (IDCOMUNE,ID);
ALTER TABLE DOCUMENTI_CONDIVISI ADD CONSTRAINT FK_DOCCOND_OGGETTI FOREIGN KEY (IDCOMUNE,CODICEOGGETTO) REFERENCES OGGETTI(IDCOMUNE,CODICEOGGETTO);
ALTER TABLE DOCUMENTI_CONDIVISI ADD CONSTRAINT FK_DOCCOND_ISTANZE FOREIGN KEY (IDCOMUNE,CODICEISTANZA) REFERENCES ISTANZE(IDCOMUNE,CODICEISTANZA);
ALTER TABLE DOCUMENTI_CONDIVISI ADD CONSTRAINT FK_DOCCOND_MOVIMENTI FOREIGN KEY (IDCOMUNE,CODICEMOVIMENTO) REFERENCES MOVIMENTI(IDCOMUNE,CODICEMOVIMENTO);
COMMENT ON COLUMN DOCUMENTI_CONDIVISI.STATO IS 'da condividere, condiviso'; 

CREATE TABLE DOCUMENTI_CONDIVISI_LOGS(
 IDCOMUNE VARCHAR2(6 CHAR) NOT NULL,
 ID NUMBER(10,0) NOT NULL,
 FK_IDDOCCONDIVISO NUMBER(10,0),
 DATA_LOG DATE,
 MESSAGGIO VARCHAR2(250 CHAR),
 DATI_ESTESI CLOB,
 LIVELLO VARCHAR2(20 CHAR)
);
ALTER TABLE DOCUMENTI_CONDIVISI_LOGS ADD CONSTRAINT PK_DOCUMENTICONDIVISILOGS PRIMARY KEY (IDCOMUNE,ID);
ALTER TABLE DOCUMENTI_CONDIVISI_LOGS ADD CONSTRAINT FK_DOCCONDLOG_DOCCOND FOREIGN KEY (IDCOMUNE,FK_IDDOCCONDIVISO) REFERENCES DOCUMENTI_CONDIVISI(IDCOMUNE,ID);

COMMENT ON COLUMN DOCUMENTI_CONDIVISI_LOGS.LIVELLO IS 'SUCCESS, ERROR'; 

CREATE TABLE ACCOUNT_FTP(
 IDCOMUNE VARCHAR2(6 CHAR) NOT NULL,
 ID NUMBER(10,0) NOT NULL,
 INDIRIZZO VARCHAR2(100 CHAR),
 UTENTE VARCHAR2(50 CHAR),
 PASSWORD VARCHAR2(50 CHAR),
 UTENTEPROXY VARCHAR2(50 CHAR),
 PASSWORDPROXY VARCHAR2(50 CHAR),
 FTP_ATTIVO NUMBER(1,0),
 FTP_ASCI NUMBER(1,0)
);

ALTER TABLE ACCOUNT_FTP ADD CONSTRAINT PK_ACCOUNTFTP PRIMARY KEY (IDCOMUNE, ID);

ALTER TABLE mercatipresenze_t ADD FLAG_POPOLA_CONCESSIONARI NUMBER(1,0) DEFAULT 1 NULL;
ALTER TABLE mercatipresenze_t ADD FLAG_CONTEGGIA_PRES_ASS NUMBER(1,0) DEFAULT 1 NULL; 

COMMENT ON COLUMN mercatipresenze_t.flag_festivo IS 'Campo dismesso, utilizzare i campi FLAG_POPOLA_CONCESSIONARI e FLAG_CONTEGGIA_PRES_ASS';
COMMENT ON COLUMN mercatipresenze_t.flag_domenica IS 'Campo dismesso, utilizzare i campi FLAG_POPOLA_CONCESSIONARI e FLAG_CONTEGGIA_PRES_ASS';


CREATE OR REPLACE FORCE VIEW VW_ASSENZECONCESSIONARI ("NUMERO_ASSENZE", "CODICEMERCATO", "MERCATO", "CODICEUSO", "USO", "IDPOSTEGGIO", "POSTEGGIO", "CODICEANAGRAFE", "NOMINATIVO", "NOME", "ANNO", "SOFTWARE", "IDCOMUNE") AS
  SELECT COUNT(*) AS numero_assenze , mercati.codicemercato , MERCATI.descrizione AS MERCATO , mercati_uso.id AS codiceuso , mercati_uso.descrizione AS USO , mercati_d.idposteggio, MERCATI_D.codiceposteggio AS POSTEGGIO , anagrafe.codiceanagrafe , ANAGRAFE.NOMINATIVO , ANAGRAFE.NOME , mercatipresenze_t.anno , mercatipresenze_t.software , mercatipresenze_t.idcomune FROM MERCATIPRESENZE_D, ANAGRAFE , MERCATI , MERCATI_USO , MERCATI_D , MERCATIPRESENZE_T WHERE MERCATIPRESENZE_D.IDCOMUNE = mercatipresenze_t.idcomune AND MERCATIPRESENZE_D.fkidtestata = mercatipresenze_t.id AND mercatipresenze_d.idcomune = anagrafe.idcomune AND mercatipresenze_d.codiceconcessionario= anagrafe.codiceanagrafe AND MERCATI.IDCOMUNE = mercatipresenze_T.idcomune AND mercati.codicemercato = mercatipresenze_T.fkcodicemercato AND MERCATI_USO.IDCOMUNE =MERCATIPRESENZE_T.IDCOMUNE AND MERCATI_USO.id =MERCATIPRESENZE_T.fkidmercatiuso AND mercati_d.idcomune = MERCATIPRESENZE_D.idcomune AND mercati_d.idposteggio =mercatipresenze_d.fkidposteggio AND codiceconcessionario IS NOT NULL AND ( ( MERCATIPRESENZE_D.CODICEANAGRAFE != CODICECONCESSIONARIO) OR MERCATIPRESENZE_D.CODICEANAGRAFE IS NULL ) AND ( flag_assenza_giust IS NULL OR flag_assenza_giust =0) AND mercatipresenze_t.FLAG_CONTEGGIA_PRES_ASS=1  GROUP BY anagrafe.nominativo, anagrafe.nomE , MERCATI.descrizione , mercati_uso.descrizione , mercati_d.idposteggio, MERCATI_D.codiceposteggio , mercati.codicemercato , mercatipresenze_t.anno , mercatipresenze_t.software, mercatipresenze_t.idcomune, anagrafe.codiceanagrafe , mercati_uso.id ORDER BY mercato , uso , posteggio , nominativo , nome;

ALTER table decodifiche ADD ordine NUMBER(4,0) null;

CREATE OR REPLACE FORCE VIEW VW_MERCATIPRESENZETOTALI ("ORIGINE", "IDCOMUNE", "ANNO", "CODICEANAGRAFE", "FK_AUTORIZZAZIONI_ID", "FKCODICEMERCATO", "FKIDMERCATIUSO", "FKIDPOSTEGGIO", "NUMEROPRESENZE", "ANAGRAFE", "CODICEFISCALE", "PARTITAIVA", "COMUNERESIDENZA", "CITTADINANZA", "DATAREGDITTE") AS
  SELECT 'STORICO' AS ORIGINE, MERCATIPRESENZE_STORICO.IDCOMUNE, MERCATIPRESENZE_STORICO.ANNO, MERCATIPRESENZE_STORICO.CODICEANAGRAFE, MERCATIPRESENZE_STORICO.FK_AUTORIZZAZIONI_ID, MERCATIPRESENZE_STORICO.FKCODICEMERCATO, MERCATIPRESENZE_STORICO.FKIDMERCATIUSO, MERCATIPRESENZE_STORICO.FK_IDPOSTEGGIO AS FKIDPOSTEGGIO, MERCATIPRESENZE_STORICO.NUMEROPRESENZE, TRIM( ANAGRAFE.NOMINATIVO || ' ' || ANAGRAFE.NOME ) AS ANAGRAFE, ANAGRAFE.CODICEFISCALE, ANAGRAFE.PARTITAIVA, COMUNI.COMUNE AS COMUNERESIDENZA, CITTADINANZA.CITTADINANZA, TO_CHAR(ANAGRAFE.DATAREGDITTE, 'DD/MM/YYYY' ) AS DATAREGDITTE FROM MERCATIPRESENZE_STORICO, ANAGRAFE, COMUNI, CITTADINANZA WHERE ANAGRAFE.IDCOMUNE = MERCATIPRESENZE_STORICO.IDCOMUNE AND ANAGRAFE.CODICEANAGRAFE = MERCATIPRESENZE_STORICO.CODICEANAGRAFE AND COMUNI.CODICECOMUNE(+) = ANAGRAFE.COMUNERESIDENZA AND CITTADINANZA.CODICE(+) = ANAGRAFE.CODICECITTADINANZA UNION ALL SELECT 'CALENDARIO' AS ORIGINE, MERCATIPRESENZE_T.IDCOMUNE, MERCATIPRESENZE_T.ANNO, MERCATIPRESENZE_D.CODICEANAGRAFE, MERCATIPRESENZE_D.FK_AUTORIZZAZIONI_ID, MERCATIPRESENZE_T.FKCODICEMERCATO, MERCATIPRESENZE_T.FKIDMERCATIUSO, MERCATIPRESENZE_D.FKIDPOSTEGGIO, MERCATIPRESENZE_D.NUMEROPRESENZE, TRIM( ANAGRAFE.NOMINATIVO || ' ' || ANAGRAFE.NOME ) AS ANAGRAFE, ANAGRAFE.CODICEFISCALE, ANAGRAFE.PARTITAIVA, COMUNI.COMUNE AS COMUNERESIDENZA, CITTADINANZA.CITTADINANZA, TO_CHAR(ANAGRAFE.DATAREGDITTE, 'DD/MM/YYYY' ) AS DATAREGDITTE FROM MERCATIPRESENZE_T, MERCATIPRESENZE_D, ANAGRAFE, COMUNI, CITTADINANZA WHERE ANAGRAFE.IDCOMUNE = MERCATIPRESENZE_D.IDCOMUNE AND ANAGRAFE.CODICEANAGRAFE = MERCATIPRESENZE_D.CODICEANAGRAFE AND COMUNI.CODICECOMUNE(+) = ANAGRAFE.COMUNERESIDENZA AND CITTADINANZA.CODICE(+) = ANAGRAFE.CODICECITTADINANZA AND MERCATIPRESENZE_D.IDCOMUNE = MERCATIPRESENZE_T.IDCOMUNE AND MERCATIPRESENZE_D.FKIDTESTATA = MERCATIPRESENZE_T.ID and mercatipresenze_t.FLAG_CONTEGGIA_PRES_ASS = 1;

  
ALTER TABLE DOCUMENTI_CONDIVISI_LOGS DROP CONSTRAINT FK_DOCCONDLOG_DOCCOND;
ALTER TABLE DOCUMENTI_CONDIVISI DROP PRIMARY KEY;
ALTER TABLE DOCUMENTI_CONDIVISI_LOGS DROP PRIMARY KEY;
ALTER TABLE DOCUMENTI_CONDIVISI_LOGS ADD CONSTRAINT PK_DOCUMENTICONDIVISILOGS PRIMARY KEY (IDCOMUNE,ID);
ALTER TABLE DOCUMENTI_CONDIVISI ADD CONSTRAINT PK_DOCUMENTICONDIVISI PRIMARY KEY (IDCOMUNE,ID);
ALTER TABLE DOCUMENTI_CONDIVISI_LOGS ADD CONSTRAINT FK_DOCCONDLOG_DOCCOND FOREIGN KEY (FK_IDDOCCONDIVISO, IDCOMUNE)REFERENCES DOCUMENTI_CONDIVISI(ID, IDCOMUNE) ON DELETE CASCADE ENABLE;


alter table domandestc add CODICECOMUNE VARCHAR2(5 CHAR);

alter table domandestc add constraint fk_domandestc_comuni foreign key (codicecomune) references comuni(codicecomune);
