<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Globals">
    <SccProjectName>Svn</SccProjectName>
    <SccProvider>SubversionScc</SccProvider>
    <SccAuxPath>Svn</SccAuxPath>
    <SccLocalPath>Svn</SccLocalPath>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net48</TargetFrameworks>
    <RootNamespace>Init.Sigepro.Frontend.Pagamenti</RootNamespace>
    <LangVersion>preview</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="log4net" Version="2.0.15" />
    <PackageReference Include="Ninject" Version="3.3.6" />
	<PackageReference Include="System.ServiceModel.Http" Version="4.10.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\SIGePro.Manager.DTO\SIGePro.Manager.DTO.csproj" />
    <ProjectReference Include="..\..\VBG.Pagamenti.NodoPagamenti\VBG.Pagamenti.NodoPagamenti.csproj" />
    <ProjectReference Include="..\Init.Sigepro.FrontEnd.Infrastructure\Init.Sigepro.FrontEnd.Infrastructure.csproj" />
    <ProjectReference Include="..\PayServerClientNative\PayServerClientNative\PayServerClientNative.csproj" />
  </ItemGroup>

</Project>