<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<Configurations>Debug;Release;ReleaseFramework</Configurations>
		<Platforms>AnyCPU</Platforms>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="log4net" Version="3.3.2" />
	  <PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="18.7.23">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\VBG.Pagamenti.NodoPagamenti\VBG.Pagamenti.NodoPagamenti.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Update="Service References\EntraNextService\Reference.svcmap">
			<Generator>WCF Proxy Generator</Generator>
		</None>
	</ItemGroup>
</Project>
