INSERT INTO COMUNI (CODICECOMUNE, COMUNE, SIGLAPROVINCIA, PROVINCIA, CF) VALUES ('Z159', 'MONTENEGRO', 'EE', 'STATIESTERI', 'Z159');
INSERT INTO COMUNI (CODICECOMUNE, COMUNE, SIGLAPROVINCIA, PROVINCIA, CF) VALUES ('Z158', 'SERBIA', 'EE', 'STATIESTERI', 'Z158');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES('PROTOCOLLO_ATTIVO','CLASSIFICADEFAULT_BO','E'' la classifica di default che viene recuperata nelle maschere di protocollazione quando non ne viene recuperata nessun''altra(ad esempio tramite la configurazione dell''albero degli interventi). Usato ad esempio per il Pannello Gestione PEC che non può recuperare la configurazione dall''intervento');
INSERT
INTO VERTICALIZZAZIONIPARAMETRIBASE
  (
    MODULO,
    PARAMETRO,
    DESCRIZIONE
  )
  VALUES
  (
    'PROTOCOLLO_ATTIVO',
    'CLASSIFICA_FASC_DEFAULT_BO',
    'E'' la classifica di default per la <b>FASCICOLAZIONE</b> che viene recuperata nelle maschere di protocollazione quando non ne viene recuperata nessun''altra(ad esempio tramite la configurazione dell''albero degli interventi). Usato ad esempio per il Pannello Gestione PEC che non può recuperare la configurazione dall''intervento');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_SICRAWEB', 'URL', 'Inserire qui l''url dove raggiungere il web service sicraweb, questo web service espone le funzionalità di registrazione protocollo e lettura protocollo. Sono stati forniti degli ambienti di test sia da Maggioli: http://www.cedaf.it/client/services/ProWSApi?wsdl, che da studio k: http://www.studiok.it:9091/ws_sici/ProWSApi.asmx?wsdl');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_SICRAWEB', 'CODICEAMMINISTRAZIONE', 'Indicare in questo parametro il valore del codice dell''amministrazione dell''ente a cui si intende protocollare, questo tipo di dato è obbligatorio e deve essere fornito dall''amministratore del sistema di protocollo, non ha infatti niente a che vedere con le amministrazioni di del Backoffice.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_SICRAWEB', 'CODICEAOO', 'Codice IPA dell’AOO mittente del protocollo in uscita, ovvero dell’ente stesso.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_SICRAWEB', 'USA_MONO_MITTDEST', 'Indica se deve rispettare il vincolo presenta anche sul protocollo docarea e relativo al fatto che non può inserire più di un mittente / destinatario nella registrazione di un protocollo. Valorizzando questo parametro a 1 allora il sistema inserirà solamente il primo mittente / destinatario nell''elemento Mittente o Destinatario altrimenti inserirà tutti i mittenti / destinatari dentro l''array dell''elemento MittentiMulti e DestinataroMulti.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_SICRAWEB', 'INVIA_SEGNATURA', 'Se valorizzato a 1 consente, in fase di protocollazione istanza o movimento da backoffice, di allegare il file di profilazione (segnatura.xml) che sarebbe il file che viene inviato al web service per eseguire la protocollazione. Questa funzionalità viene usata nel momento in cui non sia presente nessun allegato da inviare al protocollo e solo se questo parametro è valorizzato a 1.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_SICRAWEB', 'CONNECTIONSTRING', 'E'' un parametro che deve essere fornito dagli amministratori del protocollo in collaborazione con il fornitore, riguarda l''identificativo delle credenziali di connessione.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_SIPRWEB', 'FTP_PATH_ALLEGATI', 'Percorso cartella FTP del server dedicato. Lunghezza massima 256 caratteri. Parametro obbligatorio. Inserire qui il path ftp che serve come appoggio per inserire i files allegati ad uno specifico protocollo. Durante la protocollazione infatti, se sono presenti dei files, questi vengono appoggiati sul percorso indicato in questo parametro, per poi essere recuperati dal web service stesso durante l''operazione di inserimento allegato, deve essere quindi il client del protocollo a fare upload dei file su questo percorso');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_SIPRWEB', 'URLALLEGATI', 'E'' l''URL del web service che serve per invocare la funzionalità di inserimento files ad un determinato protocollo. Questa funzionalità viene invocata solo dopo aver protocollato e serve appunto per allegare file al protocollo restituito.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_SIPRWEB', 'CODICE_CC', 'Indica il codice per conoscenza da utilizzare in fase di protocollazione. Sulla maschera di protocollazione è presente un campo a tendina denominato -Trasmesso per- legato all''anagrafica (Mittente / Destinatario), questo campo viene popolato dai valori presenti nella tabella PROTOCOLLO_MODALITAINVIO, indicando il codice in questo campo, quando l''operatore selezionerà nella tendina -Trasmesso per- il valore con lo stesso codice, l''anagrafica selezionata sarà considerata per conoscenza. Se non valorizzato il destinatario (mittente) del protocollo non sarà mai per conoscenza.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_SIPRWEB', 'NOME_DIR_CONDIVISA', 'Indicare il nome della cartella condivisa sul server di protocollo, il fornitore o il CED del comune deve fornire il nome (solo il nome e non tutto il path) della cartella di appoggio utilizzata dal sistema di protocollo per recuperare i files allegati durante l''inserimento di un protocollo.');

INSERT INTO CLMENU_JAVA (ID,DESCRIZIONE,PAGINA,MENULINK,SOFTWARE,JSP,LAYOUTTESTI,VERTICALIZZAZIONE,SOFTWAREESCLUSI,LINK_STANDARD,TIPO_FUNZIONALITA) VALUES(1012,'Allineamento stradario','stradario/createAllineaStradario.htm?software=TT','7C','TT','JAVA',0,NULL,NULL,'stradario/createAllineaStradario.htm?software=TT','E');


INSERT
INTO CLMENU_JAVA
  (
    ID,
    DESCRIZIONE,
    PAGINA,
    MENULINK,
    SOFTWARE,
    JSP,
    LAYOUTTESTI,
    VERTICALIZZAZIONE,
    SOFTWAREESCLUSI,
    LINK_STANDARD,
    TIPO_FUNZIONALITA
  )
  VALUES
  (
    1014,
    'Azioni Protocollo',
    'azioniprotocollo/search.htm?software=SOFTWARE',
    '106',
    '*',
    'JAVA',
    0,
    'PROTOCOLLO_ATTIVO',
    'PR,FI,AB',
    'azioniprotocollo/search.htm?software=SOFTWARE',
    'E'
  );

INSERT
INTO CLMENU_JAVA
  (
    ID,
    DESCRIZIONE,
    PAGINA,
    MENULINK,
    SOFTWARE,
    JSP,
    LAYOUTTESTI,
    VERTICALIZZAZIONE,
    SOFTWAREESCLUSI,
    LINK_STANDARD,
    TIPO_FUNZIONALITA
  )
  VALUES
  (
    1013,
    'Azioni Protocollo',
    'azioniprotocollo/search.htm?software=TT',
    '13',
    'TT',
    'JAVA',
    0,
   'PROTOCOLLO_ATTIVO',
    'PR,FI,AB',
    'azioniprotocollo/search.htm?software=TT',
    'E'
  );

  
INSERT INTO VERTICALIZZAZIONIBASE (MODULO, DESCRIZIONE) VALUES ('PROTOCOLLO_SIPRWEBTEST', 'Questa verticalizzazione è stata creata per rendere più semplici le operazioni in ambiente di test del protocollo siprweb, l''ambiente di test e produzione di questo tipo di protocollo infatti hanno due wsdl differenti, pertanto necessitano di due componenti differenti. Per chiamare questa verticalizzazione è necessario impostare a PROTOCOLLO_SIPRWEBTEST il parametro TIPO_PROTOCOLLO della verticalizzazione PROTOCOLLO_ATTIVO.');
 
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES('PROTOCOLLO_SIPRWEBTEST','AMBIENTE','OBSOLETO, NON USARE. Inizialmente si era deciso di usare questo parametro per individuare il tipo di ambiente, i namespace dei web service di test e produzione però erano diversi quindi bisognava creare due componenti diversi o comunque delle soluzioni lunghe e dispendiose, per questo si è deciso di usare solamente le classi dell''ambiente di produzione, pur essendo presenti anche quelle di test; qui la vecchia descrizione del parametro. Indica il tipo di ambiente di protocollo che si intende utilizzare, TEST o PRODUZIONE, prende come valori T = Ambiente di Test, P = Ambiente di Produzione. Se si intende cambiare ambiente, oltre a questo parametro, vanno comunque modificati anche gli altri parametri (URL) presenti in questo modulo. Si è deciso di introdurre questo parametro in quanto i namespace dei wsdl dei webservice sono diversi in base al tipo di ambiente invocato, creando quindi la necessità di creare due classi proxy (una di Test e una di Produzione appunto) per ogni webservice presente in questo tipo di protocollo, il valore presente indicherà al componente, che si occupa della gestione del protocollo, di invocare la classe giusta in base all''esigenza del momento. Ad esempio il namespace presente sul wsdl di test del webservice dei TipiDocumento è - http://SIPrWeb/WebService.nsf/TipoDocService.wsdl - mentre per quello di produzione è - http://sipr/WebService.nsf/TipoDocService.wsdl - IMPORTANTE: questo parametro è obbligatorio, se non valorizzato sarà sollevata un''eccezione.');
 
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES('PROTOCOLLO_SIPRWEBTEST','CODICE_CC','Indica il codice per conoscenza da utilizzare in fase di protocollazione. Sulla maschera di protocollazione è presente un campo a tendina denominato -Trasmesso per- legato all''anagrafica (Mittente / Destinatario), questo campo viene popolato dai valori presenti nella tabella PROTOCOLLO_MODALITAINVIO, indicando il codice in questo campo, quando l''operatore selezionerà nella tendina -Trasmesso per- il valore con lo stesso codice, l''anagrafica selezionata sarà considerata per conoscenza. Se non valorizzato il destinatario (mittente) del protocollo non sarà mai per conoscenza.');
 
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES('PROTOCOLLO_SIPRWEBTEST','FTP_PATH_ALLEGATI','Percorso cartella FTP del server dedicato. Lunghezza massima 256 caratteri. Parametro obbligatorio. Inserire qui il path ftp che serve come appoggio per inserire i files allegati ad uno specifico protocollo. Durante la protocollazione infatti, se sono presenti dei files, questi vengono appoggiati sul percorso indicato in questo parametro, per poi essere recuperati dal web service stesso durante l''operazione di inserimento allegato, deve essere quindi il client del protocollo a fare upload dei file su questo percorso');
 
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES('PROTOCOLLO_SIPRWEBTEST','NOME_DIR_CONDIVISA','Indicare il nome della cartella condivisa sul server di protocollo, il fornitore o il CED del comune deve fornire il nome (solo il nome e non tutto il path) della cartella di appoggio utilizzata dal sistema di protocollo per recuperare i files allegati durante l''inserimento di un protocollo.');
 
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES('PROTOCOLLO_SIPRWEBTEST','URLALLEGATI','E'' l''URL del web service che serve per invocare la funzionalità di inserimento files ad un determinato protocollo. Questa funzionalità viene invocata solo dopo aver protocollato e serve appunto per allegare file al protocollo restituito.');
 
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES('PROTOCOLLO_SIPRWEBTEST','URLCLASSIFICHE','E'' l''URL per invocare la lista delle classifiche');
 
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES('PROTOCOLLO_SIPRWEBTEST','URLLEGGI','E'' l''URL per invocare la lettura di un protocollo');
 
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES('PROTOCOLLO_SIPRWEBTEST','URLPROTOCOLLA','E'' l''URL per invocare la richiesta di un protocollo');
 
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES('PROTOCOLLO_SIPRWEBTEST','URLTIPIDOCUMENTO','E'' l''URL per invocare la lista dei tipi documento');
 
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES('PROTOCOLLO_SIPRWEBTEST','USA_WS_CLASSIFICHE','Indica se per il recupero delle classifiche, sull''albero degli interventi, debba essere usato il metodo messo a disposizione del web service (valore = 1) oppure no (valore 0, vuoto o non presente). E'' stato deciso di inserire questo parametro in quanto recuperare le classifiche da web service potrebbe essere macchinoso rendendo la pagina del dettaglio degli interventi molto lenta se i dati dovessero essere molti. Oltre tutto i dati potrebbero creare una lunga lista difficilmente leggibile dagli utenti. In ultimo, se dovesso essere modificati i codici, questi non sarebbero più direttamente visibili sul campo Classifica nel dettaglio degli interventi in quanto non più presenti nella lista.');
 
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES('PROTOCOLLO_SIPRWEBTEST','USA_WS_TIPIDOC','Indica se per il recupero delle tipologie di documento, sull''albero degli interventi, debba essere usato il metodo messo a disposizione del web service (valore = 1) oppure no (valore 0, vuoto o non presente). E'' stato deciso di inserire questo parametro in quanto recuperare le tipologie di documento da web service potrebbe essere macchinoso rendendo la pagina del dettaglio degli interventi molto lenta se i dati dovessero essere molti. Oltre tutto i dati potrebbero creare una lunga lista difficilmente leggibile dagli utenti. In ultimo, se dovesso essere modificati i codici');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_SIPRWEBTEST', 'DOMINIO', 'Parametro riguardante il salvataggio dei files allegati, il web service infatti costringe il client a salvare files in una cartella condivisa sul server del protocollo, alla quale vanno indicate le credenziali tra le quali il DOMINIO che va indicato in questo parametro');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_SIPRWEBTEST', 'USERNAME', 'Parametro riguardante il salvataggio dei files allegati, il web service infatti costringe il client a salvare files in una cartella condivisa sul server del protocollo, alla quale vanno indicate le credenziali tra le quali lo USERNAME che va indicato in questo parametro');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_SIPRWEBTEST', 'PASSWORD', 'Parametro riguardante il salvataggio dei files allegati, il web service infatti costringe il client a salvare files in una cartella condivisa sul server del protocollo, alla quale vanno indicate le credenziali tra le quali la PASSWORD che va indicata in questo parametro');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_SIPRWEB', 'DOMINIO', 'Parametro riguardante il salvataggio dei files allegati, il web service infatti costringe il client a salvare files in una cartella condivisa sul server del protocollo, alla quale vanno indicate le credenziali tra le quali il DOMINIO che va indicato in questo parametro');
 
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_SIPRWEB', 'USERNAME', 'Parametro riguardante il salvataggio dei files allegati, il web service infatti costringe il client a salvare files in una cartella condivisa sul server del protocollo, alla quale vanno indicate le credenziali tra le quali lo USERNAME che va indicato in questo parametro');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_SIPRWEB', 'PASSWORD', 'Parametro riguardante il salvataggio dei files allegati, il web service infatti costringe il client a salvare files in una cartella condivisa sul server del protocollo, alla quale vanno indicate le credenziali tra le quali la PASSWORD che va indicata in questo parametro');

INSERT INTO SOFTWARE(CODICE,DESCRIZIONE,MODULOOPZIONALE,DESCRIZIONELUNGA,ACCESSORAPIDO,ORDINE) VALUES ('XU','AUA',1,'Autorizzazione Unica Ambientale',0,58);

UPDATE CLMENU_JAVA set VERTICALIZZAZIONE='SIT_ATTIVO' where id = 1012;

INSERT INTO VERTICALIZZAZIONIBASE(MODULO, DESCRIZIONE) VALUES ('PROTOCOLLO_EGRAMMATA2', 'Sistema di protocollazione E-Grammata usato al momento della creazione solamente dal Comune di Ferrara, il fornitore è Engineering. Questa versione sostituisce quella facente riferimento alla verticalizzazione PROTOCOLLO_EGRAMMATA in quanto, quella precedente, non supportava l''invio degli allegati.');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_EGRAMMATA2', 'CODICEENTE', 'Codice ente che richiama il WS, si tratta del codice numerico che identifica la AOO (obbligatorio)');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_EGRAMMATA2', 'USERNAME', 'Username dell’utente con cui si autentica al WS (obbligatorio)');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_EGRAMMATA2', 'PASSWORD', 'Password dell’utente con cui si autentica al WS (obbligatorio)');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_EGRAMMATA2', 'PASSWORD_USERAPP', 'Password dell’utente con cui si identifica ed autentica all’Applicazione di Protocollo, lo username viene identificato con il parametro USERAPP (obbligatorio)');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_EGRAMMATA2', 'USERAPP', 'UserApp dell’utente con cui si identifica ed autentica all’Applicazione di Protocollo (obbligatorio)');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_EGRAMMATA2', 'URL_PROTOCOLLO', 'Url relativo al web service che consente di protocollare (obbligatorio)'); 

INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('010000','AGRIGENTO');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('010100','SCIACCA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('020000','ALESSANDRIA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('030000','ANCONA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('040000','AOSTA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('050000','AREZZO');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('060000','ASCOLI PICENO');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('070000','ASTI');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('080000','AVELLINO');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('090000','BARI');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('090100','ANDRIA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('100000','BELLUNO');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('110000','BENEVENTO');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('120000','BERGAMO');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('130000','BOLOGNA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('130100','IMOLA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('140000','BOLZANO');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('150000','BRESCIA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('160000','BRINDISI');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('170000','CAGLIARI');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('170100','IGLESIAS');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('180000','CALTANISSETTA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('190000','CAMPOBASSO');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('200000','CASERTA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('200100','AVERSA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('210000','CATANIA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('220000','CATANZARO');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('220100','LAMEZIA TERME');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('220200','VIBO VALENTIA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('220300','CROTONE');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('230000','CHIETI');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('240000','COMO');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('240100','LECCO');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('250000','COSENZA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('250100','ROSSANO CALABRO');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('260000','CREMONA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('270000','CUNEO');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('270001','ALBA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('280000','ENNA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('290000','FERRARA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('300000','FIRENZE');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('300100','PRATO');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('300002','EMPOLI');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('310000','FOGGIA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('320000','FORLI''');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('320100','RIMINI');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('320001','CESENA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('330000','FROSINONE');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('330100','CASSINO');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('340000','GENOVA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('340100','SESTRI LEVANTE');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('340200','GENOVA PONENTE');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('350000','GORIZIA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('360000','GROSSETO');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('370000','IMPERIA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('380000','L''AQUILA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('380100','SULMONA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('380200','AVEZZANO');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('390000','LA SPEZIA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('400000','LATINA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('410000','LECCE');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('410100','CASARANO');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('420000','LIVORNO');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('420100','PIOMBINO');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('430000','LUCCA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('440000','MACERATA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('450000','MANTOVA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('460000','MASSA CARRARA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('470000','MATERA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('480000','MESSINA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('490000','MILANO');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('490100','MONZA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('490200','MILANO NORD');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('490300','MILANO MISSORI');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('490400','MILANO FIORI');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('490500','MILANO-CORVETTO');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('490800','LEGNANO');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('490104','SEREGNO');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('492700','LODI');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('490103','DESIO');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('500000','MODENA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('510000','NAPOLI');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('510100','CASTELLAMMARE');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('510200','NOLA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('510300','NAPOLI ARZANO');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('510400','NA SOCCAVO');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('510500','NAPOLI VOMERO');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('510600','POZZUOLI');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('520000','NOVARA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('520100','VERBANO-CUSIO-OSSOLA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('530000','NUORO');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('540000','PADOVA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('550000','PALERMO');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('550200','PALERMO/SUD');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('560000','PARMA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('570000','PAVIA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('580000','PERUGIA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('580100','CITTA'' DI CASTELLO');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('590000','PESARO');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('600000','PESCARA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('610000','PIACENZA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('620000','PISA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('630000','PISTOIA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('640000','POTENZA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('650000','RAGUSA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('660000','RAVENNA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('670000','REGGIO CALABRIA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('680000','REGGIO NELL''EMILIA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('690000','RIETI');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('700000','ROMA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('700100','ROMA EUR');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('700200','ROMA M.VERDE GIANICOL.');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('700300','LIDO DI OSTIA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('700400','ROMA-MONTESACRO');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('700500','ROMA CENTRO');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('700600','CIVITAVECCHIA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('700900','ROMA CASILINO PRENEST');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('701000','ROMA TUSCOLANO');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('701200','ROMA AURELIO');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('701300','ROMA TIBURTINO');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('701400','ROMA-FLAMINIO');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('701500','POMEZIA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('710000','ROVIGO');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('720000','SALERNO');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('720100','NOCERA INFERIORE');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('720200','BATTIPAGLIA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('730000','SASSARI');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('740000','SAVONA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('750000','SIENA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('760000','SIRACUSA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('760100','NOTO');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('770000','SONDRIO');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('780000','TARANTO');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('790000','TERAMO');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('800000','TERNI');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('810000','TORINO');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('810100','MONCALIERI');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('810200','IVREA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('810300','TORINO/NORD');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('810500','PINEROLO');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('810600','COLLEGNO');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('820000','TRAPANI');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('830000','TRENTO');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('840000','TREVISO');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('840001','CONEGLIANO');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('850000','TRIESTE');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('860000','UDINE');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('870000','VARESE');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('870002','BUSTO ARSIZIO');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('880000','VENEZIA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('880100','SAN DONA'' DI PIAVE');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('890000','VERCELLI');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('890100','BIELLA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('900000','VERONA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('910000','VICENZA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('920000','VITERBO');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('930000','PORDENONE');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('940000','ISERNIA');
INSERT INTO ELENCOINPSBASE (CODICE, DESCRIZIONE) VALUES ('950000','ORISTANO');

INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('11100','ALESSANDRIA');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('11130','CASALE MONFERRATO (AL)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('11131','NOVI LIGURE (AL)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('11200','ASTI');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('11300','CUNEO');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('11331','SALUZZO (CN)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('11332','ALBA (CN)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('11400','NOVARA');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('11500','TORINO CENTRO');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('11520','IVREA');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('11523','CHIVASSO (TO)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('11540','MONCALIERI (TO)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('11542','RIVOLI (TO)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('11560','PINEROLO (TO)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('11570','TORINO SUD');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('11580','TORINO NORD');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('11581','CIRIE'' (TO)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('11600','VERCELLI');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('11620','BIELLA');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('11700','VERBANO CUSIO OSSOLA');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('11730','DOMODOSSOLA (VB)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('12100','AOSTA - SEDE REGIONALE');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('13100','BERGAMO');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('13140','TREVIGLIO');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('13200','BRESCIA');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('13232','BRENO (BS)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('13233','MANERBIO (BS)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('13240','PALAZZOLO SULL''OGLIO');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('13300','COMO');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('13320','LECCO');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('13400','CREMONA');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('13430','CREMA (CR)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('13500','MANTOVA');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('13600','MILANO PORTA NUOVA');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('13609','RHO (MI)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('13620','LEGNANO');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('13621','LODI');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('13622','MONZA');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('13623','SESTO S.GIOVANNI');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('13640','MILANO BONCOMPAGNI');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('13670','MILANO SABAUDIA');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('13680','MILANO MAZZINI');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('13700','PAVIA');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('13730','VIGEVANO');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('13800','SONDRIO');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('13900','VARESE');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('13920','BUSTO ARSIZIO (VA)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('13921','GALLARATE (VA)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('13922','SARONNO (VA)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('14100','BOLZANO');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('14110','BRESSANONE (BZ)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('14120','MERANO');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('14200','DIREZIONE PROVINCIALE DI TRENTO');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('14220','ROVERETO (TN)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('15100','BELLUNO');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('15200','PADOVA');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('15202','CITTADELLA (PD)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('15300','ROVIGO');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('15400','TREVISO');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('15401','CONEGLIANO (TV)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('15500','VENEZIA CENTRO STORICO');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('15510','VENEZIA TERRAFERMA');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('15530','SAN DONA'' DI PIAVE (VE)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('15600','VERONA');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('15640','LEGNAGO (VR)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('15700','BASSANO DEL GRAPPA (VI)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('15710','VICENZA');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('15732','SCHIO (VI)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('16100','GORIZIA');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('16120','MONFALCONE (GO)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('16200','TRIESTE');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('16300','UDINE');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('16301','CERVIGNANO (UD)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('16321','TOLMEZZO');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('16700','PORDENONE');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('17100','GENOVA');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('17101','GENOVA SAMPIERDARENA (GE)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('17160','CHIAVARI');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('17200','IMPERIA');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('17300','LA SPEZIA');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('17301','SARZANA (SP)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('17400','SAVONA');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('17430','ALBENGA');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('17431','CARCARE (SV)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('18100','BOLOGNA');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('18130','CASALECCHIO DI RENO');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('18160','IMOLA');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('18200','FERRARA');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('18300','FORLI''');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('18320','RIMINI');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('18330','CESENA');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('18400','MODENA');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('18500','PARMA');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('18600','PIACENZA');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('18700','RAVENNA');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('18715','LUGO (RA)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('18730','FAENZA (RA)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('18800','REGGIO EMILIA');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('21100','AREZZO');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('21200','CARRARA');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('21210','MASSA (MS)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('21230','AULLA (MS)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('21300','FIRENZE- PORTE NUOVE');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('21320','PRATO');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('21330','EMPOLI (FI)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('21400','GROSSETO');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('21500','LIVORNO');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('21520','PIOMBINO');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('21521','PORTOFERRAIO (LI)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('21600','LUCCA');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('21630','VIAREGGIO (LU)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('21700','PISA');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('21730','PONTEDERA (PI)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('21800','PISTOIA');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('21900','SIENA');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('22100','PERUGIA');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('22110','FOLIGNO (PG)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('22131','CITTA'' DI CASTELLO (PG)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('22200','TERNI');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('22230','ORVIETO (TR)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('23100','ANCONA');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('23130','JESI (AN)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('23131','SENIGALLIA (AN)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('23132','FABRIANO (AN)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('23200','ASCOLI PICENO');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('23230','FERMO');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('23300','MACERATA');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('23331','CIVITANOVA MARCHE (MC)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('23400','PESARO');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('23401','FANO');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('24100','FROSINONE');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('24110','CASSINO (FR)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('24131','SORA (FR)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('24200','LATINA');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('24230','FORMIA (LT)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('24300','RIETI');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('24400','ROMA CENTRO');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('24401','ROMA AURELIO');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('24441','ROMA TUSCOLANO');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('24442','CIVITAVECCHIA (RM)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('24443','VELLETRI');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('24444','NETTUNO (RM)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('24460','TIVOLI');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('24470','ROMA NOMENTANO');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('24480','ROMA LAURENTINO');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('24500','VITERBO');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('24530','CIVITA CASTELLANA (VT)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('31100','CHIETI');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('31110','LANCIANO (CH)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('31200','L''AQUILA');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('31210','AVEZZANO (AQ)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('31231','SULMONA (AQ)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('31300','PESCARA');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('31400','TERAMO');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('32100','CAMPOBASSO');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('32130','TERMOLI (CB)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('32200','ISERNIA');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('33100','AVELLINO');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('33101','S. ANGELO DEI LOMBARDI (AV)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('33200','BENEVENTO');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('33201','SANT'' AGATA DEI GOTI (BN)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('33300','CASERTA');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('33310','AVERSA (CE)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('33400','NAPOLI');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('33401','NAPOLI CAMPI FLEGREI (NA)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('33403','NAPOLI VIA DE GASPERI (NA)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('33420','CASTELLAMMARE DI STABIA (NA)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('33470','NOLA');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('33500','SALERNO');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('33530','BATTIPAGLIA (SA)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('33531','NOCERA INFERIORE (SA)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('33532','SALA CONSILINA (SA)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('34100','BARI');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('34110','BARLETTA');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('34140','MONOPOLI (BA)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('34141','ALTAMURA (BA)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('34200','BRINDISI');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('34300','FOGGIA');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('34310','MANFREDONIA (FG)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('34400','LECCE');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('34401','MAGLIE (LE)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('34402','CASARANO (LE)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('35100','MATERA');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('35200','POTENZA');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('35201','MELFI (PZ)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('35230','LAGONEGRO (PZ)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('36100','CATANZARO');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('36110','VIBO VALENTIA');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('36200','COSENZA');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('36201','PAOLA (CS)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('36202','ROSSANO (CS)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('36230','CASTROVILLARI (CS)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('36300','REGGIO CALABRIA');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('36302','LOCRI (RC)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('36303','PALMI');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('36400','CROTONE');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('41100','AGRIGENTO');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('41200','CALTANISSETTA');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('41300','CATANIA');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('41302','CALTAGIRONE (CT)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('41400','ENNA');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('41500','MESSINA');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('41520','MILAZZO');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('41600','PALERMO DEL FANTE');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('41630','TERMINI IMERESE (PA)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('41640','PALERMO TITONE');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('41700','RAGUSA');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('41800','SIRACUSA');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('41900','TRAPANI');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('41901','MAZARA DEL VALLO (TP)');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('42100','CAGLIARI');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('42130','CARBONIA');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('42200','NUORO');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('42300','SASSARI');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('42330','OLBIA');
INSERT INTO ELENCOINAILBASE (CODICE, DESCRIZIONE) VALUES ('42400','ORISTANO');

INSERT INTO MAPOGGETTI (NOMETABELLA,NOMECAMPO) VALUES ('ANAGRAFEDOCUMENTI_DURC','CODICEOGGETTO');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('GEST_CANCELLAZIONI', 'PASSWORD_SBLOCCO_PEC', 'Se attiva la verticalizzazione, contiene la password da usare in caso si voglia sbloccare una PEC in carico ad un''altro operatore.');

INSERT INTO COMUNI(CODICECOMUNE, COMUNE, SIGLAPROVINCIA, PROVINCIA, REGIONE, CF, CODICEISTATREGIONE) VALUES ('C873', 'COLLESCIPOLI', 'TR', 'TERNI', 'UMBRIA', 'C873', '10');
INSERT INTO COMUNI(CODICECOMUNE, COMUNE, SIGLAPROVINCIA, PROVINCIA, REGIONE, CF, CODICEISTATREGIONE) VALUES ('D580', 'FIGINO DI MILANO', 'MI', 'MILANO', 'LOMBARDIA', 'D580', '03');

UPDATE INVENTARIOPROC_TIPITITOLO SET FLG_ALL_OBBLIGATORIO = 0 WHERE FLG_ALL_OBBLIGATORIO IS NULL;
update INVENTARIOPROC_TIPITITOLO set FLG_NON_PUBBLICARE=0 where FLG_NON_PUBBLICARE is null;

UPDATE SORTEGGITESTATAINFO SET NOME = 'label.codice_archivio_pratiche' WHERE UPPER(NOME)='CODICETIPOARCHIVIO';
UPDATE SORTEGGITESTATAINFO SET NOME = 'label.archivio_pratiche' WHERE UPPER(NOME)='DESCRIZIONETIPOARCHIVIO';
UPDATE SORTEGGITESTATAINFO SET NOME = 'label.codice_tipo_intervento' WHERE UPPER(NOME)='CODICEINTERVENTOPROC';
UPDATE SORTEGGITESTATAINFO SET NOME = 'label.tipologia_intervento' WHERE UPPER(NOME)='INTERVENTOPROC';
UPDATE SORTEGGITESTATAINFO SET NOME = 'label.codice_tipo_procedura' WHERE UPPER(NOME)='CODICEPROCEDURA';
UPDATE SORTEGGITESTATAINFO SET NOME = 'label.tipo_procedura' WHERE UPPER(NOME)='PROCEDURA';
UPDATE SORTEGGITESTATAINFO SET NOME = 'label.data_movimento_dal' WHERE UPPER(NOME)='DATADAL';
UPDATE SORTEGGITESTATAINFO SET NOME = 'label.data_movimento_al' WHERE UPPER(NOME)='DATAAL';
UPDATE SORTEGGITESTATAINFO SET NOME = 'label.codice_tipomovimento' WHERE UPPER(NOME)='CODICETIPOMOVIMENTO';
UPDATE SORTEGGITESTATAINFO SET NOME = 'label.tipomovimento' WHERE UPPER(NOME)='DESCRIZIONETIPOMOVIMENTO';
UPDATE SORTEGGITESTATAINFO SET NOME = 'label.tipo_ricerca_mov' WHERE UPPER(NOME)='TIPORICERCAMOVIMENTO';
UPDATE SORTEGGITESTATAINFO SET NOME = 'label.tipologia_esito' WHERE UPPER(NOME)='TIPOLOGIAESITO';
UPDATE SORTEGGITESTATAINFO SET NOME = 'label.percentuale' WHERE UPPER(NOME)='PERC';
UPDATE SORTEGGITESTATAINFO SET NOME = 'label.estrazione_gruppi' WHERE UPPER(NOME)='GRUPPI';
UPDATE SORTEGGITESTATAINFO SET NOME = 'label.arrotondamento' WHERE UPPER(NOME)='ARROTONDAMENTO';
UPDATE SORTEGGITESTATAINFO SET NOME = 'label.esclude' WHERE UPPER(NOME)='ESCLUDE';
UPDATE SORTEGGITESTATAINFO SET NOME = 'label.lista_estrazioni' WHERE UPPER(NOME)='LISTAESTRAZIONI';
UPDATE SORTEGGITESTATAINFO SET NOME = 'label.lista_categorie' WHERE UPPER(NOME)='LISTACATEGORIE';
UPDATE SORTEGGITESTATAINFO SET NOME = 'label.movimento_generato' WHERE UPPER(NOME)='MOVIMENTOGENERATO';

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PEOPLE', 'XMLMOD_CAP', 'Parametro per individuare il CAP della localizzazione nella pratica people tramite identificativo XML_MOD');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PEOPLE', 'XMLMOD_SCALA', 'Parametro per individuare la SCALA della localizzazione nella pratica people tramite identificativo XML_MOD');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PEOPLE', 'XMLMOD_PIANO', 'Parametro per individuare il PIANO della localizzazione nella pratica people tramite identificativo XML_MOD');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PEOPLE', 'XMLMOD_INTERNO', 'Parametro per individuare l''INTERNO della localizzazione nella pratica people tramite identificativo XML_MOD');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PEOPLE', 'XMLMOD_ESPONENTE_INTERNO', 'Parametro per individuare l''ESPONENTE INTERNO della localizzazione nella pratica people tramite identificativo XML_MOD');
insert into verticalizzazioniparametribase(modulo, parametro, descrizione) values('PROTOCOLLO_ATTIVO', 'PROXY_ADDRESS', 'Valorizzare questo parametro nel momento il server che ospita VBG esca tramite un proxy, percui sia necessario specificare l''indirizzo per raggiungere il web service, come ad esempio succede sulla server farm di Linea Comune. In questo parametro va quindi specificato l''url del proxy. Precedentemente questo parametro era valorizzato dentro il binding del web service presente dentro il file bindings.config, quindi il sistema andrà a cercare il valore inserito dentro il binding nel caso in cui questo parametro sia assente o non valorizzato. IMPORTANTE: Questo parametro è utilizzabile solo con web service in cui lo stub sia stato creato con WCF altrimenti non è possibile indicare l''url del proxy');


INSERT INTO COMUNI(CODICECOMUNE, COMUNE, SIGLAPROVINCIA, PROVINCIA, REGIONE, CF, CODICEISTATREGIONE) VALUES ('I521', 'SCHEGGIA', 'PG', 'PERUGIA', 'UMBRIA', 'I521', '10');
INSERT INTO COMUNI(CODICECOMUNE, COMUNE, SIGLAPROVINCIA, PROVINCIA, REGIONE, CF, CODICEISTATREGIONE) VALUES ('C874', 'COLLESTATTE', 'TR', 'TERNI', 'UMBRIA', 'C874', '10');
INSERT INTO COMUNI(CODICECOMUNE, COMUNE, SIGLAPROVINCIA, PROVINCIA, REGIONE, CF, CODICEISTATREGIONE) VALUES ('F159', 'MESTRE', 'VE', 'VENEZIA', 'VENETO', 'F159', '05');
INSERT INTO COMUNI(CODICECOMUNE, COMUNE, SIGLAPROVINCIA, PROVINCIA, REGIONE, CF, CODICEISTATREGIONE) VALUES ('I334', 'SANT EUFEMIA LAMEZIA', 'CZ', 'CATANZARO', 'CALABRIA', 'I334', '18');
INSERT INTO COMUNI(CODICECOMUNE, COMUNE, SIGLAPROVINCIA, PROVINCIA, REGIONE, CF, CODICEISTATREGIONE) VALUES ('Z999', 'APOLIDE (PAESI NON CLASSIFICATI)', 'EE', 'STATIESTERI', null, 'Z999', NULL);
INSERT INTO COMUNI(CODICECOMUNE, COMUNE, SIGLAPROVINCIA, PROVINCIA, REGIONE, CF, CODICEISTATREGIONE) VALUES ('L822', 'VEZZI', 'GE', 'GENOVA', 'LIGURIA', 'L822', '07');
INSERT INTO COMUNI(CODICECOMUNE, COMUNE, SIGLAPROVINCIA, PROVINCIA, REGIONE, CF, CODICEISTATREGIONE) VALUES ('L275', 'TORRE ORSINA', 'TR', 'TERNI', 'UMBRIA', 'L275', '10');
INSERT INTO COMUNI(CODICECOMUNE, COMUNE, SIGLAPROVINCIA, PROVINCIA, REGIONE, CF, CODICEISTATREGIONE) VALUES ('B458', 'CAMARDA', 'AQ', 'L''AQUILA', 'ABRUZZO', 'B458', '13');
INSERT INTO COMUNI(CODICECOMUNE, COMUNE, SIGLAPROVINCIA, PROVINCIA, REGIONE, CF, CODICEISTATREGIONE) VALUES ('G322', 'PAPIGNO', 'TR', 'TERNI', 'UMBRIA', 'G322', '10');
INSERT INTO COMUNI(CODICECOMUNE, COMUNE, SIGLAPROVINCIA, PROVINCIA, REGIONE, CF, CODICEISTATREGIONE) VALUES ('E418', 'LAINO BRUZIO', 'CS', 'COSENZA', 'CALABRIA', 'E418', '18');
INSERT INTO COMUNI(CODICECOMUNE, COMUNE, SIGLAPROVINCIA, PROVINCIA, REGIONE, CF, CODICEISTATREGIONE) VALUES ('E080', 'GOLESE', 'PR', 'PARMA', 'EMILIA ROMAGNA', 'E080', '08');
INSERT INTO COMUNI(CODICECOMUNE, COMUNE, SIGLAPROVINCIA, PROVINCIA, REGIONE, CF, CODICEISTATREGIONE) VALUES ('G595', 'PIEDILUCO', 'TR', 'TERNI', 'UMBRIA', 'G595', '10');
INSERT INTO COMUNI(CODICECOMUNE, COMUNE, SIGLAPROVINCIA, PROVINCIA, REGIONE, CF, CODICEISTATREGIONE) VALUES ('Z111', ' GERMANIA REPUBBLICA DEMOCRATICA', 'EE', 'STATIESTERI', NULL, 'Z111', NULL);

INSERT INTO SOFTWARE(CODICE, DESCRIZIONE, MODULOOPZIONALE, DESCRIZIONELUNGA, ACCESSORAPIDO, ORDINE) VALUES ('CN', 'Concessioni Precarie', '1', 'Concessioni Precarie', '0', '58');
insert into verticalizzazioniparametribase(modulo, parametro, descrizione) values('PROTOCOLLO_SICRAWEB', 'URL_WS_ALLEGATI', 'Indicare qui l''url dove sono esposti i servizi web per la lettura degli allegati, il protocollo sicraweb infatti, dispone di un web service diverso da quello di protocollazione per la lettura dei documenti.');

INSERT INTO CLMENU_JAVA
  (
    ID,
    DESCRIZIONE,
    PAGINA,
    MENULINK,
    SOFTWARE,
    JSP,
    LAYOUTTESTI,
    VERTICALIZZAZIONE,
    SOFTWAREESCLUSI,
    LINK_STANDARD,
    TIPO_FUNZIONALITA
  )
  VALUES
  (
    1015,
    'Endoprocedimenti principali del frontend',
    'inventarioprocfotop/list.htm?software=SOFTWARE',
    '853',
    '*',
    'JAVA',
    0,
    null,
    'PR,FI,AB',
    'inventarioprocfotop/list.htm?software=SOFTWARE',
    'E'
  );

INSERT INTO CLMENU_JAVA(
    ID,
    DESCRIZIONE,
    PAGINA,
    MENULINK,
    SOFTWARE,
    JSP,
    LAYOUTTESTI,
    VERTICALIZZAZIONE,
    SOFTWAREESCLUSI,
    LINK_STANDARD,
    TIPO_FUNZIONALITA
  )
  VALUES
  (
    1016,
    'Interventi principali del frontend',
    'alberoprocfotop/list.htm?software=SOFTWARE',
    '854',
    '*',
    'JAVA',
    0,
    null,
    'PR,FI,AB',
    'alberoprocfotop/list.htm?software=SOFTWARE',
    'E'
  );

  INSERT INTO COMUNI(CODICECOMUNE, COMUNE, SIGLAPROVINCIA, PROVINCIA, REGIONE, CF, CODICEISTATREGIONE) VALUES ('C575', 'CESI', 'TR', 'TERNI', 'UMBRIA', 'C575', '10');
  
insert into verticalizzazionibase(modulo, descrizione) values('PROTOCOLLO_TINN', 'E'' il protocollo gestito dalla ditta Tinn in Abruzzo, in teoria, questo protocollo, dovrebbe essere standard docarea, in realtà non lo è in quanto il fornitore non riesce a gestire gli allegati in modo DIME / MIME passandoli quindi direttamente sulla richiesta soap, i metodi hanno inoltre piccole modifiche rispetto a quanto specificato nei documenti docarea (maiuscole, minuscole, nomi di proprietà diversi....), quindi è stato necessario creare una verticalizzazione e relativi parametri uguali a quelli della verticalizzazione PROTOCOLLO_DOCAREA. In realtà questo tipo di protocollo, da certi punti di vista è molto simile al protocollo halley. I servizi di test TINN sono esposti su http://5.98.16.12:7099, qui si possono fare delle prove');
insert into verticalizzazioniparametribase(modulo, parametro, descrizione) values('PROTOCOLLO_TINN','OPERATORE','(Obbligatorio) Username di autenticazione al web service del protocollo TINN, è il parametro username che viene passato al web method Login. Deve essere fornito dal fornitore del protocollo');
insert into verticalizzazioniparametribase(modulo, parametro, descrizione) values('PROTOCOLLO_TINN','URL','(Obbligatorio) End point del web service per invocare i servizi, ad esempio per il protocollo TINN l''ambiente di test è presente su http://5.98.16.12:7099/wsdl/DOCAREAProto?wsdl');
insert into verticalizzazioniparametribase(modulo, parametro, descrizione) values('PROTOCOLLO_TINN','PASSWORD','Password di autenticazione al web service del protocollo TINN, è il parametro password che viene passato al web method Login. Deve essere fornito dal fornitore del protocollo');
insert into verticalizzazioniparametribase(modulo, parametro, descrizione) values('PROTOCOLLO_TINN','CODICEENTE','Codice Ente, questo parametro va ad aggiungersi a username e password e serve per l''autenticazione al web service del protocollo TINN, è il parametro codiceente che viene passato al web method Login. Deve essere fornito dal fornitore del protocollo');
insert into verticalizzazioniparametribase(modulo, parametro, descrizione) values('PROTOCOLLO_TINN','INVIA_ALL_MOV_AVVIO','(Facoltativo) Se valorizzato a 1 va a cercare in automatico, solamente durante la protocollazione da istanza, gli allegati caricati nel movimento di avvio dell''istanza stessa, se esistono questi vengono inviati al protocollo TINN.Se valorizzato con valore diverso da 1 o non valorizzato la funzionalità appena descritta non sarà svolta.');
insert into verticalizzazioniparametribase(modulo, parametro, descrizione) values('PROTOCOLLO_TINN','INVIA_SEGNATURA','(Facoltativo) Se valorizzato a 1 consente, in fase di protocollazione istanza o movimento da backoffice, di inviare il file segnatura.xml che sarebbe il file che viene inviato al web service per eseguire la protocollazione; se valorizzato a 0 o non valorizzato non esegue nessuna funzionalità.');
insert into verticalizzazioniparametribase(modulo, parametro, descrizione) values('PROTOCOLLO_TINN','CODICE_AOO','(Facoltativo) E'' il codice dell''Area Organizzativa Omogenea, va fornito dagli amministratori del protocollo. In precedenza veniva passato un parametro fisso con valore = ''AOO'' è stato modificato in quanto in alcuni casi (ad esempio Piacenza e Asp Roma) veniva richiesto un valore diverso. Sulle specifiche TINN (che sono le stesse docarea) viene descritto come: viene inizializzato con un valore che identifica l''ambito dell''applicazione.Ad esempio questo codice potrebbe essere utilizzato,per individuare i messaggi provenienti dal portale.Ovviamente si puo’ scegliere come nel caso a) di usare una codifica del tipo P_X dove X e’ il nome dell’applicazione chiamante.Questo valore viene inserito nel file segnatura.xml dentro Intestazione-->Identificatore-->CodiceAOO e dentro Intestazione -->Classifica -->CodiceAOO Se non valorizzato il parametro prenderà il valore di AOO');
insert into verticalizzazioniparametribase(modulo, parametro, descrizione) values('PROTOCOLLO_TINN','TIPO_DOCUMENTO_ALLEGATO','(Facoltativo) Specificare il valore del tipo documento allegato ossia quei documenti allegati al protocollo escluso quello principale. Se non valorizzato prenderà il valore = ''Allegato'' che era il valore fisso che veniva passato in precedenza. Viene valorizzato nel file segnatura.xml dentro Intestazione --> Descrizione --> Documento --> TipoDocumento successivamente a quello principale.');
insert into verticalizzazioniparametribase(modulo, parametro, descrizione) values('PROTOCOLLO_TINN','TIPO_DOCUMENTO_PRINCIPALE','(Facoltativo) Specificare il valore del tipo documento principale. ossia quel documento principale o di richiesta del protocollo. Se non valorizzato prenderà il valore = ''Principale'' che era il valore fisso che veniva passato in precedenza. E'' stato parametrizzato perchè a Piacenza viene richiesto un valore specifico che è ''TRAS''. Viene valorizzato nel file segnatura.xml dentro Intestazione --> Descrizione --> Documento --> TipoDocumento');
insert into verticalizzazioniparametribase(modulo, parametro, descrizione) values('PROTOCOLLO_TINN','APPLICATIVO_PROTOCOLLO','(Facoltativo) Indica il nome dell''applicativo del protocollo, questa voce sarà inserita dentro il file segnatura.xml dentro l''attributo -nome- di <ApplicativoProtocollo/>. NB. Se lasciato vuoto o non attivato prenderà il valore inserito dentro il parametro CODICEENTE');
insert into verticalizzazioniparametribase(modulo, parametro, descrizione) values('PROTOCOLLO_TINN','UO','(Facoltativo) Indica l''ufficio di smistamento del protocollo TINN, questa voce sarà inserita dentro il file segnatura.xml dentro il nodo <ApplicativoProtocollo> valorizzando un nuovo parametro con nome -uo-. E'' facoltativo ma il protocollo GS4 di ADS (Piacenza) lo richiede necessariamente.');
insert into verticalizzazioniparametribase(modulo, parametro, descrizione) values('PROTOCOLLO_TINN','CODICEAMMINISTRAZIONE','Indicare in questo parametro il Codice dell''amministrazione, questo dato andrà a valorizzare gli elementi CODICEAMMINISTRAZIONE della segnatura che viene inviata al metodo protocollazione del web service. Se non valorizzato questo dato verrà preso dal parametro CODICEENTE come succedeva in passato.');
insert into verticalizzazioniparametribase(modulo, parametro, descrizione) values('PROTOCOLLO_TINN','URL_WS_DIZIONARIO','Inserire qui l''endpoint che indica il web service per fare le chiamate alle funzionalità di recupero dati relativo alle classifiche e uffici');
insert into verticalizzazioniparametribase(modulo, parametro, descrizione) values('PROTOCOLLO_TINN','USA_WS_CLASSIFICHE','Se = a 1 indica che le classifiche devono essere recuperate tramite web service messo a disposizione dal protocollo TINN, altrimenti il sistema funzionerà in maniera standard, ossia mappando le varie classifiche direttamente sull''albero degli interventi. Questo parametro è direttamente legato al parametro URL_WS_DIZIONARIO, infatti se si decide di recuperare le classifiche da web service, deve ovviamente essere indicato anche l''end point del web service');


insert into verticalizzazionibase (modulo, descrizione) values ('ARCHIVIAZIONE_DOC_LEGALDOC', 'abilita l''integrazione con il sistema di archiviazione documentale LegalDoc Folders di Infocert');
insert into verticalizzazioniparametribase (modulo, parametro, descrizione) values ('ARCHIVIAZIONE_DOC_LEGALDOC','DATA_FOLDER_PATH','percorso della cartella locale di LegalDocs dove archiviare i file');
insert into verticalizzazioniparametribase (modulo, parametro, descrizione) values ('ARCHIVIAZIONE_DOC_LEGALDOC','SERVICE','attributo obbligatorio all''interno del file di avvio che identifica il servizio finale al quale sono indirizzati i file da trasferire tramite LegalDoc Connector. Il contenuto di questo campo è case sensitive e deve corrispondere all''identificativo fornito dal gestore per il servizio prescelto');
insert into verticalizzazioniparametribase (modulo, parametro, descrizione) values ('ARCHIVIAZIONE_DOC_LEGALDOC','END_USER_ID','attributo facoltativo all''interno del file di avvio che può essere usato per identificare l''utente finale, di norma rappresentato da un cliente del cliente intermediario (es. Banca1, Banca2...); il contenuto di questo campo è libero e, se presente, viene riportato nei messaggi PEC di segnalazione');
insert into verticalizzazioniparametribase (modulo, parametro, descrizione) values ('ARCHIVIAZIONE_DOC_LEGALDOC','NOME','attributo facoltativo all''interno del file di avvio ad uso del Cliente per descrivere la tipologia di file che costituisce il job; il contenuto di questo campo è libero e, se presente, viene riportato nei messaggi PEC di segnalazione');
insert into verticalizzazioniparametribase (modulo, parametro, descrizione) values ('ARCHIVIAZIONE_DOC_LEGALDOC','FEEDBACK_EMAIL','attributo facoltativo all''interno del file di avvio che può essere usato per specificare l''indirizzo di PEC a cui inviare l''eventuale notifica di errore del job; se questo campo non è presente, la notifica viene inviata all''indirizzo PEC specificato in fase di registrazione');
insert into verticalizzazioniparametribase (modulo, parametro, descrizione) values ('ARCHIVIAZIONE_DOC_LEGALDOC','FILE_EXTENSIONS','lista di estensioni di file dichiarate in fase contrattuale. (separate dal carattere '';'')');
insert into verticalizzazioniparametribase (modulo, parametro, descrizione) values ('ARCHIVIAZIONE_DOC_LEGALDOC','SGD','parametro obbligatorio fornito da InfoCert in fase contrattuale; indica il codice del Sistema di Gestione Documentale (SGD) per il quale si sta effettuando il trasferimento');
insert into verticalizzazioniparametribase (modulo, parametro, descrizione) values ('ARCHIVIAZIONE_DOC_LEGALDOC','DATA_MAX_CONS','parametro facoltativo per richiedere la conservazione dei dati inviati entro una certa data; la data massima di conservazione richiesta deve essere di almeno tre giorni successiva alla data di invio dei file. La data deve essere espressa nel formato dd-mm-aaaa');
insert into verticalizzazioniparametribase (modulo, parametro, descrizione) values ('ARCHIVIAZIONE_DOC_LEGALDOC','MAX_NUM_FILES','numero massimo di file per singola archiviazione');
insert into verticalizzazioniparametribase (modulo, parametro, descrizione) values ('ARCHIVIAZIONE_DOC_LEGALDOC','MAX_NUM_ISTANZE_PER_QUERY','numero massimo di record della tabella ISTANZE da recuperare dalla query che individua le istanze da archiviare');
insert into verticalizzazioniparametribase (modulo, parametro, descrizione) values ('ARCHIVIAZIONE_DOC_LEGALDOC','MAX_FILE_SIZE','dimensione massima in byte del singolo file');
insert into verticalizzazioniparametribase (modulo, parametro, descrizione) values ('ARCHIVIAZIONE_DOC_LEGALDOC','MAX_FILE_NAME_LENGTH','lunghezza massima in caratteri del nome del singolo file');
insert into verticalizzazioniparametribase (modulo, parametro, descrizione) values ('ARCHIVIAZIONE_DOC_LEGALDOC','DALLA_DATA','filtro opzionale applicato alla colonna DATAFINEEFFETTIVA della tabella ISTANZE_TEMPISTICA');
insert into verticalizzazioniparametribase (modulo, parametro, descrizione) values ('ARCHIVIAZIONE_DOC_LEGALDOC','ALLA_DATA','filtro opzionale applicato alla colonna DATAFINEEFFETTIVA della tabella ISTANZE_TEMPISTICA');

insert into verticalizzazioniparametribase(modulo, parametro, descrizione) values('PROTOCOLLO_ATTIVO', 'OGGETTO_UPPERCASE', 'Solo se valorizzato a 1, il componente .net Protocollo Manager trasforma la stringa dell''oggetto tutta in maiuscolo, oggetto quindi che viene successivamente inviato al sistema di protocollo in maiuscolo anche se sulla maschera di protocollazione viene scritto in minuscolo');

INSERT INTO COMUNI(CODICECOMUNE, COMUNE, SIGLAPROVINCIA, PROVINCIA, CF) VALUES ('Z160', 'KOSSOVO', 'EE', 'STATIESTERI', 'Z160');
insert into CLMENU_JAVA (ID,DESCRIZIONE,PAGINA,MENULINK,SOFTWARE,JSP,LAYOUTTESTI,VERTICALIZZAZIONE,SOFTWAREESCLUSI,LINK_STANDARD,TIPO_FUNZIONALITA) values (1017,'Archiviazione documentale','archiviazioni/list.htm','7E','TT','JAVA',0,NULL,'PR,FI,AB','archiviazioni/list.htm','E');

INSERT INTO VERTICALIZZAZIONIBASE VALUES ('MAIL_SERVICE','Regola letta dall''applicazione MailService per personalizzare alcune funzionalita'' in fase di invio mail.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE VALUES('MAIL_SERVICE','TIPO_RICEVUTA','Parametro per istruire il tipo di ricevuta (breve, sintetica, completa) che il gestore PEC deve generare. I valori ammessi sono: "breve" la ricevuta breve di avvenuta consegna include il testo del messaggio originale, mentre eventuali file allegati sono sostituiti con file di testo contenenti hash crittografici. "sintetica" contiene unicamente i dati di certificazione (mittente, destinatario, oggetto, riferimenti temporali e identificativi del messaggio), in modo analogo alla precedente, ma non riporta né il testo del messaggio originale né i file allegati (permette la verifica dei soli contenuti trasmessi nell''oggetto). "completa" questo tipo di ricevuta consiste in un messaggio di posta elettronica che riporta sia in formato leggibile, sia all''interno di un file xml allegato, i dati di certificazione (mittente, destinatario, oggetto, riferimenti temporali e identificativo del messaggio) e gli allegati originali. Il valore di default se non specificato e'' "completa" .');