ALTER TABLE TIPIGRADT_CFG_ROTAZIONE ADD (FK_DYN2CAMPI_ORDINE NUMBER(10, 0) NOT NULL);

ALTER TABLE TIPIGRADT_CFG_ROTAZIONE ADD CONSTRAINT FK_TIPIGRAD_T_CAMPI_ORDINE FOREIGN KEY (IDCOMUNE,FK_DYN2CAMPI_ORDINE) REFERENCES DYN2_CAMPI(IDCOMUNE,ID);

CREATE TABLE ARCHIVIAZIONI_BACKV2_26 AS SELECT * FROM ARCHIVIAZIONI;

alter table ARCHIVIAZIONI add NUMERO number(4,0);

alter table ARCHIVIAZIONI add TMP_NAME CLOB;
update ARCHIVIAZIONI set TMP_NAME=ERRORE;
alter table ARCHIVIAZIONI drop column ERRORE;
alter table ARCHIVIAZIONI rename column TMP_NAME to ERRORE;



alter table documentiistanza modify FKIDCATEGORIA number(10,0);

ALTER TABLE DYN2_ESPRESSIONI MODIFY (PARENTESI_APERTA VARCHAR2(3) );

ALTER TABLE DYN2_ESPRESSIONI MODIFY (PARENTESI_CHIUSA VARCHAR2(3) );

COMMENT ON COLUMN DYN2_ESPRESSIONI.PARENTESI_APERTA IS 'APRE UNA O PIU'' PARENTESI NELL''ESPRESSIONE';

COMMENT ON COLUMN DYN2_ESPRESSIONI.PARENTESI_CHIUSA IS 'CONSENTE DI SPECIFICARE UNA P PIU'' PARENTESI CHIUSE DOPO QUESTA ESPRESSIONE';

ALTER TABLE DYN2_ESPRESSIONI DROP CONSTRAINT DYN2EXP_CHK_PARAPERTA;

ALTER TABLE DYN2_ESPRESSIONI DROP CONSTRAINT DYN2EXP_CHK_PARCHIUSA;

ALTER TABLE MERCATI ADD(FK_D2CID_PREF_POS NUMBER(10, 0));