INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_ATTIVO', 'TRASFORMA_IN_PDF', 'Valori: 0 (default) e 1. Se impostato a 1 i file verranno trasformati in PDF prima di essere inviati al protocollo');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_ATTIVO', 'ESTENSIONI_AMMESSE', 'Contiene la lista delle esetensioni degli allegati che potranno essere inviati al protocollo ( Es. xlsx;pdf;rtf ). Qualora valorizzata, eventuali allegati con estensioni che non rientrano nella lista delle estensioni ammesse non verranno trasmessi al protocollo');
Insert into COMUNI (CODICECOMUNE,COMUNE,SIGLAPROVINCIA,PROVINCIA,REGIONE,CAP,CF,CODICEISTAT,CODICEISTATREGIONE,CODICESTATOESTERO) values ('H351','RIVIERA D''ADDA','BG','BERGAMO','LOMBARDIA','24060','H351','016181','03',null);
Insert into COMUNI (CODICECOMUNE,COMUNE,SIGLAPROVINCIA,PROVINCIA,REGIONE,CAP,CF,CODICEISTAT,CODICEISTATREGIONE,CODICESTATOESTERO) values ('L732','VENEGONO','VA','VARESE','LOMBARDIA','21040','L732','012899','03',null);
INSERT INTO clmenu_java(id, descrizione, pagina, menulink, software, jsp, softwareesclusi, link_standard, tipo_funzionalita, menulink_v2) VALUES (1052, 'Punteggi dei Bandi', 'alberocoefficientit/list.htm?software=SOFTWARE', '0AD', '*', 'JAVA', 'PR,FI', 'alberocoefficientit/list.htm?software=SOFTWARE', 'S', '0AD');
INSERT INTO MAPOGGETTI (NOMETABELLA,NOMECAMPO) VALUES('ARCHIVIAZIONI_OGGETTI','CODICEOGGETTO');
INSERT INTO MAPOGGETTI (NOMETABELLA,NOMECAMPO) VALUES('COMUNICAZIONI_D','CODICEOGGETTO');
INSERT INTO MAPOGGETTI (NOMETABELLA,NOMECAMPO) VALUES('DOCUMENTI_AUTORIZZAZIONE','CODICEOGGETTO');
INSERT INTO MAPOGGETTI (NOMETABELLA,NOMECAMPO) VALUES('EQUITALIATRACCIATO','CODICEOGGETTO');
INSERT INTO MAPOGGETTI (NOMETABELLA,NOMECAMPO) VALUES('FO_ARJ_DOMANDE','CODICEOGGETTO_RICEVUTA');
INSERT INTO MAPOGGETTI (NOMETABELLA,NOMECAMPO) VALUES('ISTANZERICHIEDENTI','CODICEOGGETTO_PROCURA');
INSERT INTO MAPOGGETTI (NOMETABELLA,NOMECAMPO) VALUES('MASSIVE_D_ALLEGATI','CODICEOGGETTO');
INSERT INTO MAPOGGETTI (NOMETABELLA,NOMECAMPO) VALUES('MASSIVE_T_ALLEGATI','CODICEOGGETTO');
INSERT INTO MAPOGGETTI (NOMETABELLA,NOMECAMPO) VALUES('MOVIMENTI_ZIP_LOGICO','CODICEOGGETTO');
INSERT INTO MAPOGGETTI (NOMETABELLA,NOMECAMPO) VALUES('RESPONSABILI','FK_OGGETTO_IMMAGINE');



INSERT INTO comuni (CODICECOMUNE, COMUNE, SIGLAPROVINCIA, PROVINCIA, REGIONE, CAP, CF, CODICEISTAT, CODICEISTATREGIONE, CODICESTATOESTERO) VALUES('B027','BORGO PANIGALE','BO','BOLOGNA','EMILIA ROMAGNA','37801','B027','037801','08',NULL);
INSERT INTO comuni (CODICECOMUNE, COMUNE, SIGLAPROVINCIA, PROVINCIA, REGIONE, CAP, CF, CODICEISTAT, CODICEISTATREGIONE, CODICESTATOESTERO) VALUES('L099','TEODORANO','FC','FORLI''','EMILIA ROMAGNA','47014','L099','047014','08',NULL);