#PROPERTIES PER LA CREAZIONE DELLE SESSION FACTORY

#HIBERNATE OPTIONS
hibernate.connection.provider_class=org.hibernate.connection.C3P0ConnectionProvider
hibernate.connection.release_mode=on_close
hibernate.generate_statistics=false
hibernate.show_sql=false
hibernate.use_sql_comments=false
hibernate.format_sql=false
hibernate.cache.use_second_level_cache=false

#C3P0 OPTIONS
hibernate.c3p0.min_size=10
hibernate.c3p0.max_size=100
hibernate.c3p0.acquire_increment=5
c3p0.numHelperThreads=3
c3p0.checkoutTimeout=10000
hibernate.c3p0.timeout=1800
hibernate.c3p0.max_statements=0
hibernate.c3p0.idle_test_period=600

#JDBC DRIVERS (composto da chiave db.driver + nome del provider su tabella comunisecurity)
db.driver.Oracle=oracle.jdbc.OracleDriver
db.driver.Oracle9i=oracle.jdbc.OracleDriver
db.driver.Oracle10g=oracle.jdbc.OracleDriver
db.driver.MySql=com.mysql.jdbc.Driver
db.driver.MySqlInnoDB=com.mysql.jdbc.Driver
db.driver.MySqlMyISAM=com.mysql.jdbc.Driver
db.driver.PostgreSQL=org.postgresql.Driver
#db.driver.SQLServer=com.microsoft.jdbc.sqlserver.SQLServerDriver
#da utilizzare con i driver jdbc-2.0, sqljdbc4.jar(per JRE6) o sqljdbc.jar(per JRE5)
#db.driver.SQLServer=com.microsoft.sqlserver.jdbc.SQLServerDriver
db.driver.SQLServer=net.sourceforge.jtds.jdbc.Driver

#HIBERNATE DIALECTS (composto da chiave hibernate.dialect + nome del provider su tabella comunisecurity)
hibernate.dialect.Oracle=org.hibernate.dialect.Oracle8iDialect
hibernate.dialect.Oracle9i=org.hibernate.dialect.Oracle9iDialect
hibernate.dialect.Oracle10g=org.hibernate.dialect.Oracle10gDialect
hibernate.dialect.MySql=org.hibernate.dialect.MySQLDialect
hibernate.dialect.MySqlInnoDB=org.hibernate.dialect.MySQLInnoDBDialect
hibernate.dialect.MySqlMyISAM=org.hibernate.dialect.MySQLMyISAMDialect
hibernate.dialect.PostgreSQL=org.hibernate.dialect.PostgreSQLDialect
hibernate.dialect.SQLServer=org.hibernate.dialect.SQLServerDialect

