# PARAMETRI DI DEPLOY
idcomunealias=GESTCAL
idcomune=DEF

# SECURITY
ws.token.url=REDACTED
ws.token.user=REDACTED
ws.token.pwd=REDACTED

# SCHEDULER
# false=disabilitato, true=abilitato
scheduler.enable=true
# tipo cron, simple
scheduler.type=cron
# espressione per tipo cron (Seconds, Minutes, Hours, Day of month, Month, Day of week, Year)
scheduler.cron.expression=0 0/2 * * * ?
# valori per tipo simple (millis)
scheduler.simple.startDelay=120000
scheduler.simple.repeatInterval=120000

# SCHEDE DINAMICHE
# sagre suape
exporter.suape.db.feste_sagre.codiceScheda=90000357
exporter.suape.db.dyn2dati.feste_sagre.dal.id=90005314
exporter.suape.db.dyn2dati.feste_sagre.al.id=90005315
exporter.suape.db.dyn2dati.feste_sagre.denominazione.id=90005312
exporter.suape.db.dyn2dati.feste_sagre.tipologia_a.id=90005319
exporter.suape.db.dyn2dati.feste_sagre.tipologia_b.id=90005320
exporter.suape.db.dyn2dati.feste_sagre.comune.id=90005317
exporter.suape.db.dyn2dati.feste_sagre.luogo_svolgimento.id=90005318
exporter.suape.db.dyn2dati.feste_sagre.luogo_svolgimento_civico.id=90005779
# fiere suape
exporter.suape.db.fiere_mostre.codiceScheda=90000385
exporter.suape.db.dyn2dati.fiere_mostre.dal.id=90005690
exporter.suape.db.dyn2dati.fiere_mostre.al.id=90005636
exporter.suape.db.dyn2dati.fiere_mostre.denominazione.id=90005634
exporter.suape.db.dyn2dati.fiere_mostre.merceologia.id=90005639
exporter.suape.db.dyn2dati.fiere_mostre.merceologia_altro.id=90006268
exporter.suape.db.dyn2dati.fiere_mostre.comune.id=90005637
exporter.suape.db.dyn2dati.fiere_mostre.luogo_svolgimento.id=90005638
exporter.suape.db.dyn2dati.fiere_mostre.classificazione_fg.id=90005640
exporter.suape.db.dyn2dati.fiere_mostre.classificazione_fs.id=90005641
exporter.suape.db.dyn2dati.fiere_mostre.classificazione_mm.id=90005642
exporter.suape.db.dyn2dati.fiere_mostre.classificazione_e.id=90005643
# fiere regione umbria
exporter.regione.db.codiceScheda=11
exporter.regione.db.dyn2dati.fiere_mostre.dal.id=114
exporter.regione.db.dyn2dati.fiere_mostre.al.id=115
exporter.regione.db.dyn2dati.fiere_mostre.denominazione.id=110
exporter.regione.db.dyn2dati.fiere_mostre.merceologia.id=120
exporter.regione.db.dyn2dati.fiere_mostre.merceologia_altro.id=894
exporter.regione.db.dyn2dati.fiere_mostre.comune.id=116
exporter.regione.db.dyn2dati.fiere_mostre.luogo_svolgimento.id=117
exporter.regione.db.dyn2dati.fiere_mostre.classificazione_fg.id=127
exporter.regione.db.dyn2dati.fiere_mostre.classificazione_fs.id=129
exporter.regione.db.dyn2dati.fiere_mostre.classificazione_mm.id=130
exporter.regione.db.dyn2dati.fiere_mostre.classificazione_e.id=132
exporter.regione.db.dyn2dati.fiere_mostre.qualifica_i.id=193
exporter.regione.db.dyn2dati.fiere_mostre.qualifica_r.id=195
exporter.regione.db.dyn2dati.fiere_mostre.qualifica_n.id=196

## devel3
#exporter.regione.db.codiceScheda=255
#exporter.regione.db.dyn2dati.fiere_mostre.dal.id=2607
#exporter.regione.db.dyn2dati.fiere_mostre.al.id=2608
#exporter.regione.db.dyn2dati.fiere_mostre.denominazione.id=2609
#exporter.regione.db.dyn2dati.fiere_mostre.merceologia.id=2612
#exporter.regione.db.dyn2dati.fiere_mostre.merceologia_altro.id=2613
#exporter.regione.db.dyn2dati.fiere_mostre.comune.id=2610
#exporter.regione.db.dyn2dati.fiere_mostre.luogo_svolgimento.id=2611
#exporter.regione.db.dyn2dati.fiere_mostre.classificazione_fg.id=2614
#exporter.regione.db.dyn2dati.fiere_mostre.classificazione_fs.id=2615
#exporter.regione.db.dyn2dati.fiere_mostre.classificazione_mm.id=2616
#exporter.regione.db.dyn2dati.fiere_mostre.classificazione_e.id=2617
#exporter.regione.db.dyn2dati.fiere_mostre.qualifica_i.id=2618
#exporter.regione.db.dyn2dati.fiere_mostre.qualifica_r.id=2619
#exporter.regione.db.dyn2dati.fiere_mostre.qualifica_n.id=2620
