# Comment out the Log4J listener in web.xml to activate Log4J.
log4j.rootLogger=INFO, logfile

log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d %p [%c] %nGESTIONE CALENDARI - <%m>%n

log4j.appender.logfile=org.apache.log4j.RollingFileAppender
log4j.appender.logfile.File=${catalina.base}/logs/gestionecalendari.log
log4j.appender.logfile.MaxFileSize=1024KB
log4j.appender.logfile.MaxBackupIndex=10
log4j.appender.logfile.layout=org.apache.log4j.PatternLayout
log4j.appender.logfile.layout.ConversionPattern=%d %p [%c] - %m%n

log4j.logger.org.apache=WARN
log4j.logger.org.springframework=WARN
log4j.logger.org.hibernate=WARN

## impostare a DEBUG per visualizzare le query ed i parametri di binding(impostare type a TRACE per visualizzare anche i parametri di ritorno)
log4j.logger.org.hibernate.SQL=WARN
log4j.logger.org.hibernate.type=WARN
#log4j.logger.org.hibernate.cache=WARN
#log4j.logger.org.hibernate.jdbc=WARN
#log4j.logger.org.hibernate.type.AnyType=WARN
#log4j.logger.org.hibernate.type.BigDecimalType=WARN
#log4j.logger.org.hibernate.type.BigIntegerType=WARN
#log4j.logger.org.hibernate.type.BooleanType=WARN
#log4j.logger.org.hibernate.type.ByteType=WARN
#log4j.logger.org.hibernate.type.CalendarDateType=WARN
#log4j.logger.org.hibernate.type.CalendarType=WARN
#log4j.logger.org.hibernate.type.CharacterType=WARN
#log4j.logger.org.hibernate.type.DateType=WARN
#log4j.logger.org.hibernate.type.DbTimestampType=WARN
#log4j.logger.org.hibernate.type.DoubleType=WARN
#log4j.logger.org.hibernate.type.FloatType=WARN
#log4j.logger.org.hibernate.type.IdentifierBagType=WARN
#log4j.logger.org.hibernate.type.IntegerType=WARN
#log4j.logger.org.hibernate.type.LongType=WARN
#log4j.logger.org.hibernate.type.NullableType=WARN
#log4j.logger.org.hibernate.type.NumericBooleanType=WARN
#log4j.logger.org.hibernate.type.ShortType=WARN
#log4j.logger.org.hibernate.type.StringClobType=WARN
#log4j.logger.org.hibernate.type.StringType=WARN
#log4j.logger.org.hibernate.type.TextType=WARN
#log4j.logger.org.hibernate.type.TimestampType=WARN
#log4j.logger.org.hibernate.type.TimeType=WARN

## c3p0 logger
#log4j.logger.com.mchange=WARN
