CREATE TABLE CODIFICA_ENTI_RFC53 (
CODICEISTAT VARCHAR(6)
, ENTE VARCHAR(250)
, CODIFICA VARCHAR(30)
, PRIMARY KEY (CODICEISTAT)
)ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE INDEX IDX_GRADUATORIED_001 ON GRADUATORIED(IDCOMUNE,FK_GT_ID);

CREATE INDEX IDX_CAMPIGRADUATORIA_001 ON CAMPIGRADUATORIA(IDCOMUNE,FK_GD_ID);

CREATE INDEX IDX_GRADUATORIET_001 ON GRADUATORIET(IDCOMUNE,FK_TGT_ID);

CREATE INDEX IDX_GRADUATORIED_002 ON GRADUATORIED(IDCOMUNE,CODICEISTANZA);

CREATE INDEX IDX_AUTORIZ_SUBENTRI_001 ON AUTORIZZAZIONI_SUBENTRI(IDCOMUNE, FK_IDAUT_ATTUALE);

ALTER TABLE GRADUATORIET_COM ADD PROT_DOPO_CREAZIONE_ALLEGATO NUMERIC(1,0);
ALTER TABLE ELENCHIPROFESSIONALIBASE ADD FLAG_REGIONALE NUMERIC(1,0);

alter table anagrafe modify provinciaelencopro varchar(50);
alter table anagrafestorico modify provinciaelencopro varchar(50);

create table RUOLI_PROTOCOLLO(
IDCOMUNE VARCHAR(6) NOT NULL
,ID   NUMERIC(10,0) NOT NULL
,IDRUOLO NUMERIC(4,0)
,RUOLO_EXT VARCHAR(50)
,CODICECOMUNE VARCHAR(5)
,SOFTWARE VARCHAR(2)
)ENGINE=INNODB DEFAULT CHARSET=UTF8;
ALTER TABLE RUOLI_PROTOCOLLO ADD CONSTRAINT PK_RUOLI_PROTOCOLLO PRIMARY KEY (IDCOMUNE, ID);
ALTER TABLE RUOLI_PROTOCOLLO ADD CONSTRAINT FK_RUOLIPROT_RUOLI FOREIGN KEY(IDCOMUNE,IDRUOLO) REFERENCES RUOLI(IDCOMUNE, ID);
ALTER TABLE RUOLI_PROTOCOLLO ADD CONSTRAINT FK_RUOLIPROT_COMUNI FOREIGN KEY(CODICECOMUNE) REFERENCES COMUNI(CODICECOMUNE);
ALTER TABLE RUOLI_PROTOCOLLO ADD CONSTRAINT FK_RUOLIPROT_SOFTWARE FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);

ALTER TABLE TIPIMOV_STC_MAPPING ADD FLAG_CONVERTIPDF NUMERIC(1,0);

