CREATE TABLE PAY_ALIQUOTE_IVA 
(	
ID NUMERIC(3,0) NOT NULL,
DESCRIZIONE VARCHAR(20) NOT NULL,
ALIQUOTA NUMERIC(2,0) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE PAY_ALIQUOTE_IVA  ADD CONSTRAINT PAY_ALIQUOTE_IVA_PK PRIMARY KEY (ID) ;

CREATE TABLE PAY_CONNECTOR_CONFIG 
(	
CODICE VARCHAR(20) NOT NULL,
DESCRIZIONE VARCHAR(50),
PAY_CONNECTOR_JAVA_CLASS VARCHAR(255) NOT NULL 
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE PAY_CONNECTOR_CONFIG ADD CONSTRAINT PAY_CONNECTOR_CONFIG_PK PRIMARY KEY (CODICE) ;


 
CREATE TABLE PAY_CONTI
(
ID NUMERIC(6,0) NOT NULL,
IDCOMUNE VARCHAR(6) NOT NULL,
SOFTWARE VARCHAR(2) NOT NULL,
DESCRIZIONE VARCHAR(100) NOT NULL,
FK_AMMINISTRAZIONE NUMERIC(4,0),
FK_ALIQUOTA_IVA NUMERIC(3,0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE PAY_CONTI ADD CONSTRAINT PAY_CONTI_PK PRIMARY KEY (IDCOMUNE, ID);
ALTER TABLE PAY_CONTI ADD CONSTRAINT PAYCON_FK_AMMIN FOREIGN KEY (IDCOMUNE, FK_AMMINISTRAZIONE)  REFERENCES AMMINISTRAZIONI (IDCOMUNE, CODICEAMMINISTRAZIONE); 
ALTER TABLE PAY_CONTI ADD CONSTRAINT PAYCON_FK_IVA FOREIGN KEY (FK_ALIQUOTA_IVA) REFERENCES PAY_ALIQUOTE_IVA (ID);



CREATE TABLE PAY_REGISTRAZIONI_CAUSALI
(ID NUMERIC(6,0) NOT NULL,
IDCOMUNE VARCHAR(6) NOT NULL,
SOFTWARE VARCHAR(2) NOT NULL,
DESCRIZIONE VARCHAR(40) NOT NULL,
ORDINE NUMERIC(6,0),
FLAG_RIDUZIONE NUMERIC(1,0),
FLAG_NOINCASSI NUMERIC(1,0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE PAY_REGISTRAZIONI_CAUSALI ADD CONSTRAINT PAY_REGISTRAZIONI_CAUSALI_PK PRIMARY KEY (IDCOMUNE, ID);


CREATE TABLE PAY_IO_EVENTI 
(	
ID NUMERIC(9,0) NOT NULL,
IDCOMUNE VARCHAR(6) NOT NULL,
DATA DATETIME NOT NULL,
TIPO_EVENTO VARCHAR(30) NOT NULL,
FLAG_ENTRATA NUMERIC(1,0) NOT NULL,
ESITO NUMERIC(1,0) NOT NULL,
ID_MESSAGGIO VARCHAR(100),
CODICE_COMUNICAZIONE VARCHAR(100),
DESC_ESITO VARCHAR(100),
CODICE_ESITO VARCHAR(20),
INFO VARCHAR(400)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE PAY_IO_EVENTI ADD CONSTRAINT PAY_IO_SERVIZI_PK PRIMARY KEY (IDCOMUNE, ID) ;



CREATE TABLE PAY_REGISTRAZIONI_CONTABILI 
(	
IDCOMUNE VARCHAR(6) NOT NULL,
ID NUMERIC(9,0) NOT NULL,
DATA_REGISTRAZIONE DATETIME NOT NULL,
DESCRIZIONE VARCHAR(200),
IMPORTO NUMERIC(12,2) NOT NULL,
NOTE VARCHAR(2000),
FK_CAUSALE_REG NUMERIC(6,0) NOT NULL,
ANNO NUMERIC(4,0) NOT NULL,
SOFTWARE VARCHAR(2) NOT NULL,
FK_ANAGRAFE_TITOLARE NUMERIC(6,0),
FK_REGCONT_SALDO NUMERIC(9,0),
IVA NUMERIC(2,0),
FK_CONTO NUMERIC(6,0),
DESC_CAUSALE VARCHAR(200),
DESC_CONTO VARCHAR(50)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE PAY_REGISTRAZIONI_CONTABILI ADD CONSTRAINT PAY_REGISTRAZIONI_CONTABIL_PK PRIMARY KEY (IDCOMUNE, ID); 
ALTER TABLE PAY_REGISTRAZIONI_CONTABILI ADD CONSTRAINT PAY_REGCONT_FK_ANAG FOREIGN KEY (IDCOMUNE, FK_ANAGRAFE_TITOLARE)  REFERENCES ANAGRAFE (IDCOMUNE, CODICEANAGRAFE); 
ALTER TABLE PAY_REGISTRAZIONI_CONTABILI ADD CONSTRAINT PAY_REGCONT_FK_REGCAUS FOREIGN KEY ( IDCOMUNE, FK_CAUSALE_REG) REFERENCES PAY_REGISTRAZIONI_CAUSALI (IDCOMUNE, ID); 
ALTER TABLE PAY_REGISTRAZIONI_CONTABILI ADD CONSTRAINT PAY_REGCONT_FK_REGCONT FOREIGN KEY (IDCOMUNE, FK_REGCONT_SALDO)  REFERENCES PAY_REGISTRAZIONI_CONTABILI (IDCOMUNE, ID); 
ALTER TABLE PAY_REGISTRAZIONI_CONTABILI ADD CONSTRAINT PAY_REGISTRAZIONI_CONTABI_FK1 FOREIGN KEY (IDCOMUNE, FK_CONTO) REFERENCES PAY_CONTI (IDCOMUNE, ID); 
 



CREATE TABLE PAY_SOGGETTI_DEBITORI 
(	
ID NUMERIC(9,0) NOT NULL, 
IDCOMUNE VARCHAR(6) NOT NULL, 
NOME VARCHAR(50) NOT NULL, 
COGNOME VARCHAR(50), 
CF_PI VARCHAR(16) NOT NULL, 
VIA VARCHAR(255), 
CIVICO VARCHAR(20), 
CAP VARCHAR(6), 
LOCALITA VARCHAR(50), 
PROVINCIA VARCHAR(50), 
STATO VARCHAR(50), 
EMAIL VARCHAR(255), 
FLAG_ATTIVO NUMERIC(1,0) DEFAULT 1 NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE PAY_SOGGETTI_DEBITORI ADD CONSTRAINT PAY_SOGGETTI_DEBITORI_PK PRIMARY KEY (IDCOMUNE, ID);


CREATE TABLE PAY_POSIZIONI_DEBITORIE 
(	
ID NUMERIC(9,0) NOT NULL, 
IDCOMUNE VARCHAR(6) NOT NULL,
SOFTWARE VARCHAR(2) NOT NULL,
DESCRIZIONE_CAUSALE VARCHAR(200) NOT NULL, 
IMPORTO NUMERIC(12,2) NOT NULL, 
DATA_SCADENZA DATETIME NOT NULL, 
NUM_RATA NUMERIC(3,0), 
IUV VARCHAR(100),
FK_REGISTRAZIONE_CONTABILE NUMERIC(9,0), 
FK_SOGGETTO_DEBITORE NUMERIC(9,0), 
FK_OGGETTO_RICEVUTA NUMERIC(9,0), 
FK_OGGETTO_AVVISO NUMERIC(9,0), 
FK_OGGETTO_FATTURA NUMERIC(9,0), 
CODICE_AVVISO VARCHAR(50), 
ID_POSIZIONE_PSP VARCHAR(50), 
DATA_INVIO_A_PSP DATETIME, 
DATA_ANNULLAMENTO DATETIME, 
DATA_REGISTRAZIONE DATETIME NOT NULL, 
ANNO NUMERIC(4,0) NOT NULL 
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE PAY_POSIZIONI_DEBITORIE  ADD CONSTRAINT PAY_POSIZIONI_DEBITORIE_PK PRIMARY KEY (IDCOMUNE, ID);

ALTER TABLE PAY_POSIZIONI_DEBITORIE  ADD CONSTRAINT PAY_POSDEB_FK_REGCONT FOREIGN KEY (IDCOMUNE, FK_REGISTRAZIONE_CONTABILE ) REFERENCES PAY_REGISTRAZIONI_CONTABILI (IDCOMUNE, ID); 
ALTER TABLE PAY_POSIZIONI_DEBITORIE  ADD CONSTRAINT PAY_POSDEB_FK_SOGDEB FOREIGN KEY (IDCOMUNE, FK_SOGGETTO_DEBITORE) REFERENCES PAY_SOGGETTI_DEBITORI (IDCOMUNE, ID); 
ALTER TABLE PAY_POSIZIONI_DEBITORIE  ADD CONSTRAINT PAY_POSDEB_FK_OGGFAT FOREIGN KEY (IDCOMUNE, FK_OGGETTO_FATTURA) REFERENCES OGGETTI (IDCOMUNE, CODICEOGGETTO); 
ALTER TABLE PAY_POSIZIONI_DEBITORIE  ADD CONSTRAINT PAY_POSDEB_FK_OGGRT FOREIGN KEY (IDCOMUNE, FK_OGGETTO_RICEVUTA) REFERENCES OGGETTI (IDCOMUNE, CODICEOGGETTO);
ALTER TABLE PAY_POSIZIONI_DEBITORIE  ADD  CONSTRAINT PAY_POSDEB_FK_OGGAVV FOREIGN KEY (IDCOMUNE, FK_OGGETTO_AVVISO) REFERENCES OGGETTI (IDCOMUNE, CODICEOGGETTO);




CREATE UNIQUE INDEX PAY_POSDEB_UIDX ON PAY_POSIZIONI_DEBITORIE (IUV) ;


CREATE TABLE PAY_PAGAMENTI 
(	
ID NUMERIC(9,0) NOT NULL,
DATA_SISTEMA DATETIME NOT NULL,
DATA_PAGAMENTO DATETIME,
IMPORTO_PAGATO NUMERIC(12,2),
IUV VARCHAR(200),
ID_POSIZIONE_PSP VARCHAR(50),
RIF_PAGAMENTO VARCHAR(50),
MODALITA_PAGAMENTO VARCHAR(50),
FK_POSIZIONE_SALDATA NUMERIC(9,0),
IDCOMUNE VARCHAR(6), 
DESCRIZIONE_CAUSALE VARCHAR(200), 
NOTE VARCHAR(2000), 
FK_SOGGETTO_PAGATORE NUMERIC(9,0) NOT NULL, 
FLAG_NOTIFICA NUMERIC(1,0) DEFAULT 0, 
ID_FLUSSO_RENDICONTAZIONE VARCHAR(50), 
DATA_ORA_INIZIO_TRANS DATETIME, 
DATA_ORA_AUTORIZZAZIONE DATETIME, 
IUR VARCHAR(100), 
IMPORTO_TRANSATO NUMERIC(12,2), 
IMPORTO_COMMISSIONI NUMERIC(12,2)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


ALTER TABLE PAY_PAGAMENTI ADD CONSTRAINT PAY_PAGAMENTI_PK PRIMARY KEY (IDCOMUNE, ID); 
ALTER TABLE PAY_PAGAMENTI ADD CONSTRAINT PAY_PAG_FK_POSDEB FOREIGN KEY (IDCOMUNE, FK_POSIZIONE_SALDATA )  REFERENCES PAY_POSIZIONI_DEBITORIE (IDCOMUNE, ID); 
ALTER TABLE PAY_PAGAMENTI ADD CONSTRAINT PAY_PAG_FK_SOGDEB FOREIGN KEY (IDCOMUNE, FK_SOGGETTO_PAGATORE)  REFERENCES PAY_SOGGETTI_DEBITORI (IDCOMUNE, ID);



CREATE TABLE PAY_PROFILI_ENTI_CREDITORI 
(	
IDCOMUNE VARCHAR(6) NOT NULL, 
ID NUMERIC(10,0) NOT NULL,
CODICECOMUNE VARCHAR(5),
CODICEAMMINISTRAZIONE NUMERIC(10,0) NOT NULL, 
SOFTWARE VARCHAR(2) NOT NULL, 
CBILL VARCHAR(100), 
CC_POSTALE VARCHAR(100), 
CF_CODICE_PROFILO VARCHAR(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


ALTER TABLE PAY_PROFILI_ENTI_CREDITORI ADD CONSTRAINT PAY_ENTI_CREDITORI_PK PRIMARY KEY (IDCOMUNE, ID);

ALTER TABLE PAY_PROFILI_ENTI_CREDITORI ADD CONSTRAINT PAY_EC_FK_AMMI FOREIGN KEY (IDCOMUNE, CODICEAMMINISTRAZIONE)  REFERENCES AMMINISTRAZIONI (IDCOMUNE, CODICEAMMINISTRAZIONE); 
ALTER TABLE PAY_PROFILI_ENTI_CREDITORI ADD CONSTRAINT PAY_EC_FK_COMUNI FOREIGN KEY (CODICECOMUNE) REFERENCES COMUNI (CODICECOMUNE);

 

CREATE UNIQUE INDEX UIX_EC_CF_CODICE_PROFILO ON PAY_PROFILI_ENTI_CREDITORI (CF_CODICE_PROFILO) ;


 
 
CREATE TABLE PAY_REG_CONTABILI_PAGAMENTI 
(	
ID NUMERIC(9,0) NOT NULL,
IDCOMUNE VARCHAR(6) NOT NULL,
FK_PAGAMENTO NUMERIC(9,0) NOT NULL,
FK_REGISTRAZIONE_CONTABILE NUMERIC(9,0) NOT NULL, 
IMPORTO_CONTABILIZZATO NUMERIC(12,2) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE PAY_REG_CONTABILI_PAGAMENTI ADD CONSTRAINT PAY_REG_CONTABILI_PAGAMENT_PK PRIMARY KEY (IDCOMUNE, ID); 
ALTER TABLE PAY_REG_CONTABILI_PAGAMENTI ADD CONSTRAINT PAY_REGCONTPAG_FK_REGCONT FOREIGN KEY (IDCOMUNE, FK_REGISTRAZIONE_CONTABILE) REFERENCES PAY_REGISTRAZIONI_CONTABILI (IDCOMUNE, ID) ON DELETE CASCADE; 
ALTER TABLE PAY_REG_CONTABILI_PAGAMENTI ADD CONSTRAINT PAY_REGCONTPAG_FK_PAG FOREIGN KEY (IDCOMUNE, FK_PAGAMENTO) REFERENCES PAY_PAGAMENTI (IDCOMUNE, ID);


 
CREATE TABLE PAY_SESSIONI_PAGAMENTO 
(	
ID NUMERIC(9,0) NOT NULL,
IDCOMUNE VARCHAR(6) NOT NULL,
ID_SESSIONE_PAGAMENTO VARCHAR(50) NOT NULL, 
DATA_INIZIO DATETIME NOT NULL, 
DIGEST_SICUREZZA VARCHAR(255), 
ESITO NUMERIC(1,0), 
FK_POSIZIONE_DEBITORIA NUMERIC(9,0) NOT NULL 
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE PAY_SESSIONI_PAGAMENTO ADD CONSTRAINT PAY_SESSIONI_PAGAMENTO_PK PRIMARY KEY (IDCOMUNE, ID); 
ALTER TABLE PAY_SESSIONI_PAGAMENTO ADD CONSTRAINT PAY_SESSIONI_PAGAMENTO_FK1 FOREIGN KEY (IDCOMUNE, FK_POSIZIONE_DEBITORIA) REFERENCES PAY_POSIZIONI_DEBITORIE (IDCOMUNE, ID);
  
 
CREATE TABLE PAY_STATO_PAGAMENTI 
(	
ID NUMERIC(9,0) NOT NULL, 
IDCOMUNE VARCHAR(6) NOT NULL, 
STATO VARCHAR(30) NOT NULL, 
DESC_STATO VARCHAR(200), 
FK_POSIZIONE_DEBITORIA NUMERIC(9,0) NOT NULL, 
DATA_EVENTO DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
 
ALTER TABLE PAY_STATO_PAGAMENTI ADD CONSTRAINT PAY_STATO_PAGAMENTI_PK PRIMARY KEY (IDCOMUNE, ID); 
ALTER TABLE PAY_STATO_PAGAMENTI ADD CONSTRAINT PAY_STAPAG_FK_POSDEB FOREIGN KEY (IDCOMUNE, FK_POSIZIONE_DEBITORIA) REFERENCES PAY_POSIZIONI_DEBITORIE (IDCOMUNE, ID) ON DELETE CASCADE;
	  
	  

ALTER TABLE MERCATIPRESENZE_D ADD FK_PAY_POS_DEB NUMERIC(9,0);
alter table MERCATIPRESENZE_D ADD CONSTRAINT FK_PAYPOSDEB_SPUNT FOREIGN KEY(IDCOMUNE,FK_PAY_POS_DEB) REFERENCES PAY_POSIZIONI_DEBITORIE(IDCOMUNE,ID);


CREATE TABLE CONSENSI_INFORMATIVI(
IDCOMUNE VARCHAR(6),
ID NUMERIC(10,0),
CODICEOGGETTO NUMERIC(10,0),
DESCRIZIONE VARCHAR(100),
VERSIONE NUMERIC(4),
CONTESTO VARCHAR(50),
ORDINE NUMERIC(4,0),
OBBLIGATORIO NUMERIC(1,0),
DATA_INSERIMENTO DATETIME
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE CONSENSI_INFORMATIVI ADD CONSTRAINT PK_CONSENSIINFORMATIVI PRIMARY KEY(IDCOMUNE,ID);

ALTER TABLE CONSENSI_INFORMATIVI ADD CONSTRAINT FK_CONSINF_OGGETTI FOREIGN KEY(IDCOMUNE,CODICEOGGETTO) REFERENCES OGGETTI(IDCOMUNE, CODICEOGGETTO);


ALTER TABLE FO_CONSENSI_INFORMATIVI ADD FK_CONS_INFORM_ID NUMERIC(10,0);

ALTER TABLE FO_CONSENSI_INFORMATIVI ADD CONSTRAINT FK_FOCONSINF_CONSINF FOREIGN KEY(IDCOMUNE,FK_CONS_INFORM_ID) REFERENCES CONSENSI_INFORMATIVI(IDCOMUNE, ID);


ALTER TABLE PAY_PROFILI_ENTI_CREDITORI  ADD CODICE_CONNETTORE VARCHAR(20) NOT NULL;


ALTER TABLE PAY_PROFILI_ENTI_CREDITORI ADD CONSTRAINT PAY_EC_FK_PAYCONN FOREIGN KEY (CODICE_CONNETTORE) REFERENCES PAY_CONNECTOR_CONFIG(  CODICE) ;

ALTER TABLE PAY_CONNECTOR_CONFIG MODIFY DESCRIZIONE VARCHAR(200);

ALTER TABLE PAY_SOGGETTI_DEBITORI MODIFY NOME VARCHAR(250 );

ALTER TABLE PAY_SOGGETTI_DEBITORI MODIFY COGNOME VARCHAR(250);




ALTER TABLE PAY_PAGAMENTI MODIFY COLUMN IMPORTO_PAGATO NUMERIC(12,2) NOT NULL;


ALTER TABLE AUTORIZZAZIONI_CSI ADD PROTOCOLLO VARCHAR(10);
ALTER TABLE AUTORIZZAZIONI_CSI ADD DATA_PROTOCOLLO DATETIME; 


ALTER TABLE PAY_CONNECTOR_CONFIG ADD WS_URL VARCHAR(400);

ALTER TABLE PAY_CONNECTOR_CONFIG ADD WS_USR VARCHAR(50);

ALTER TABLE PAY_CONNECTOR_CONFIG ADD WS_PWD VARCHAR(50);


ALTER TABLE PAY_CONNECTOR_CONFIG ADD WS_TIMEOUT NUMERIC(9, 0);


ALTER TABLE PAY_REGISTRAZIONI_CAUSALI ADD CODICE_VERSAMENTO VARCHAR(20);


ALTER TABLE PAY_PROFILI_ENTI_CREDITORI ADD FK_CUSALE_REG_DEFAULT NUMERIC(6,0);

ALTER TABLE PAY_PROFILI_ENTI_CREDITORI ADD CONSTRAINT PAY_PROFILI_ENTI_CREDITOR_FK1 FOREIGN KEY( IDCOMUNE, FK_CUSALE_REG_DEFAULT) REFERENCES PAY_REGISTRAZIONI_CAUSALI (IDCOMUNE, ID);



ALTER TABLE PAY_CONNECTOR_CONFIG ADD URL_PORTALE_PAGAMENTI VARCHAR(255);


ALTER TABLE PAY_CONNECTOR_CONFIG ADD PWD_PORTALE_PAGAMENTI VARCHAR(50) ;

ALTER TABLE PAY_CONNECTOR_CONFIG ADD ID_APP_PORTALE_PAGAMENTI VARCHAR(50);



ALTER TABLE PAY_SESSIONI_PAGAMENTO ADD URL_REDIRECT_ESITO VARCHAR(255);


ALTER TABLE FO_DOMANDE ADD CODICEINTERVENTO NUMERIC(10);

ALTER TABLE MERCATI ADD FLAG_ATTIVA_NODO_PAGAM NUMERIC(1,0);


ALTER TABLE amministrazioni_anagrafe ADD INOLTRA_COMUNICAZIONE NUMERIC(1,0);



ALTER TABLE PAY_STATO_PAGAMENTI MODIFY DESC_STATO VARCHAR(500);

ALTER TABLE PAY_REGISTRAZIONI_CONTABILI DROP FOREIGN KEY PAY_REGISTRAZIONI_CONTABI_FK1;

ALTER TABLE PAY_REGISTRAZIONI_CONTABILI DROP COLUMN FK_CONTO;


CREATE TABLE PAY_DETTAGLIO_IMPORTI 
(
  ID NUMERIC(9) NOT NULL 
, IDCOMUNE VARCHAR(6) NOT NULL 
, IMPORTO NUMERIC(12, 2) NOT NULL 
, DESC_CAUSALE VARCHAR(200) 
, FK_CONTO NUMERIC(9, 0) 
, CONSTRAINT PAY_DETTAGLIO_IMPORTI_PK PRIMARY KEY 
  (
    ID 
  , IDCOMUNE 
  )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE PAY_DETTAGLIO_IMPORTI ADD CONSTRAINT PAY_DETIMP_FK_CONTI FOREIGN KEY (  IDCOMUNE, FK_CONTO ) REFERENCES CONTI ( IDCOMUNE , ID) ;


ALTER TABLE PAY_DETTAGLIO_IMPORTI ADD FK_POSIZIONE_DEBITORIA NUMERIC(9) NOT NULL;

ALTER TABLE PAY_DETTAGLIO_IMPORTI ADD CONSTRAINT PAY_DETIMP_FK_POSDEB FOREIGN KEY (  IDCOMUNE, FK_POSIZIONE_DEBITORIA) REFERENCES PAY_POSIZIONI_DEBITORIE(IDCOMUNE, ID);

ALTER TABLE PAY_DETTAGLIO_IMPORTI ADD DATI_RISCOSSIONE VARCHAR(100);

ALTER TABLE PAY_POSIZIONI_DEBITORIE ADD  QRCODE VARCHAR(100);

ALTER TABLE PAY_POSIZIONI_DEBITORIE ADD FK_PROFILO_ENTE NUMERIC(10,0);

ALTER TABLE PAY_POSIZIONI_DEBITORIE ADD CONSTRAINT PAY_POSDEB_FK_PROF FOREIGN KEY (  IDCOMUNE , FK_PROFILO_ENTE ) REFERENCES PAY_PROFILI_ENTI_CREDITORI (IDCOMUNE, ID ) ; 


ALTER TABLE PAY_PROFILI_ENTI_CREDITORI  ADD ID_APP_PSP VARCHAR(50);



ALTER TABLE PAY_PROFILI_ENTI_CREDITORI ADD CF_CODICE_PROFILO_PSP VARCHAR(20);



ALTER TABLE PAY_CONNECTOR_CONFIG DROP COLUMN ID_APP_PORTALE_PAGAMENTI;

ALTER TABLE PAY_POSIZIONI_DEBITORIE DROP COLUMN IMPORTO;

ALTER TABLE PAY_PROFILI_ENTI_CREDITORI ADD URL_ESITO_PAGAMENTO VARCHAR(256); 

ALTER TABLE PAY_CONNECTOR_CONFIG ADD IN_WS_USR VARCHAR(50) ;

ALTER TABLE PAY_CONNECTOR_CONFIG ADD IN_WS_PWD VARCHAR(50);

ALTER TABLE PAY_CONNECTOR_CONFIG ADD IN_WS_TIMEOUT VARCHAR(20);

ALTER TABLE PAY_POSIZIONI_DEBITORIE MODIFY COLUMN DATA_SCADENZA DATETIME NULL;

ALTER TABLE PAY_POSIZIONI_DEBITORIE  ADD  UNIQUE INDEX PAY_POSDEB_IDPSP_UIDX (ID_POSIZIONE_PSP);



CREATE OR REPLACE VIEW VW_PAY_POSIZIONIDEBITORIE AS SELECT
    PPD.ID,
    PSP.STATO,
    PSP.DESC_STATO,
    PPD.IUV,
    SUM(PIMP.IMPORTO) AS IMPORTO,
    PPD.ID_POSIZIONE_PSP,
    PPD.DESCRIZIONE_CAUSALE,
    PPD.CODICE_AVVISO,
    PPD.QRCODE,
    PSP.DATA_EVENTO,
    PPEC.CODICE_CONNETTORE,
    PPEC.CBILL,
    PPEC.CF_CODICE_PROFILO,
    PPEC.CF_CODICE_PROFILO_PSP,
    PPEC.ID_APP_PSP
FROM
    PAY_POSIZIONI_DEBITORIE PPD
    LEFT JOIN PAY_STATO_PAGAMENTI PSP ON PSP.IDCOMUNE = PPD.IDCOMUNE
                                         AND PSP.FK_POSIZIONE_DEBITORIA = PPD.ID
    LEFT JOIN PAY_PROFILI_ENTI_CREDITORI PPEC ON PPEC.IDCOMUNE = PPD.IDCOMUNE
                                                 AND PPEC.ID = PPD.FK_PROFILO_ENTE
    INNER JOIN PAY_DETTAGLIO_IMPORTI PIMP ON PPD.IDCOMUNE = PIMP.IDCOMUNE
                                             AND PPD.ID = PIMP.FK_POSIZIONE_DEBITORIA

GROUP BY
    PPD.ID,
    PPD.DESCRIZIONE_CAUSALE,
    PPD.IUV,
    PPD.CODICE_AVVISO,
    PPD.ID_POSIZIONE_PSP,
    PPD.QRCODE,
    PSP.STATO,
    PSP.DESC_STATO,
    PSP.DATA_EVENTO,
    PPEC.CODICE_CONNETTORE,
    PPEC.CBILL,
    PPEC.CF_CODICE_PROFILO,
    PPEC.CF_CODICE_PROFILO_PSP,
    PPEC.ID_APP_PSP;

ALTER TABLE pay_profili_enti_creditori ADD COLUMN URL_ANNULLAMENTO_PAGAMENTO VARCHAR(256) NULL;

CREATE TABLE MERCATI_CFG_CONTI(
IDCOMUNE VARCHAR(6),
ID NUMERIC(4,0),
FK_CONTO NUMERIC(6,0),
FK_CODICEISTAT VARCHAR(15),
FK_CODICE_CONC_USO NUMERIC(2,0),
DATAINZIOVAL DATETIME,
DATAFINEVAL DATETIME,
FLAG_MOLTIPLICA_MQ NUMERIC(1,0),
IMPORTO NUMERIC(8,5)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


ALTER TABLE MERCATI_CFG_CONTI ADD CONSTRAINT PK_MERCATI_CFG_CONTI PRIMARY KEY (IDCOMUNE,ID);
ALTER TABLE MERCATI_CFG_CONTI ADD CONSTRAINT FK_MERCFGCONTI_CONTI FOREIGN KEY (IDCOMUNE,FK_CONTO) REFERENCES CONTI (IDCOMUNE,ID);
ALTER TABLE MERCATI_CFG_CONTI ADD CONSTRAINT FK_MERCFGCONTI_ATTIVITA FOREIGN KEY (IDCOMUNE,FK_CODICEISTAT) REFERENCES ATTIVITA (IDCOMUNE,CODICEISTAT);
ALTER TABLE MERCATI_CFG_CONTI ADD CONSTRAINT FK_MERCFGCONTI_CONCUSO FOREIGN KEY (IDCOMUNE,FK_CODICE_CONC_USO) REFERENCES CONCESSIONIUSO (IDCOMUNE,CODICE);


ALTER TABLE MERCATIPRESENZE_T ADD FK_CODICE_CONC_USO NUMERIC(2,0);
ALTER TABLE MERCATIPRESENZE_T ADD CONSTRAINT FK_MERCPREST_CONCUSO FOREIGN KEY (IDCOMUNE,FK_CODICE_CONC_USO) REFERENCES CONCESSIONIUSO (IDCOMUNE,CODICE);

ALTER TABLE TEMP_LINKALLEGATI ADD DESCRIZIONE_DOCUMENTO VARCHAR(4000) ;

alter table MERCATI_CFG_CONTI add SOFTWARE varchar(2);

ALTER TABLE MERCATI_CFG_CONTI ADD CONSTRAINT FK_MERCFGCONTI_SOFTWARE FOREIGN KEY (SOFTWARE) REFERENCES SOFTWARE(CODICE);



alter table conti add anno_accertamento NUMERIC(4,0);
alter table conti add numero_accertamento varchar(35);


ALTER TABLE PAY_DETTAGLIO_IMPORTI ADD ANNO_ACCERTAMENTO NUMERIC(4,0);
ALTER TABLE PAY_DETTAGLIO_IMPORTI ADD NUMERO_ACCERTAMENTO VARCHAR(35);