ALTER TABLE pay_registrazioni_causali DROP COLUMN FLAG_RIDUZIONE;
ALTER TABLE pay_registrazioni_causali DROP COLUMN FLAG_NOINCASSI; 
ALTER TABLE pay_registrazioni_causali ADD PARAMETRI VARCHAR2(100) NULL;

ALTER TABLE COMUNI MODIFY PROVINCIA VARCHAR2(70 CHAR);

ALTER TABLE TIPICAUSALIONERI ADD FLAG_GENERA_FATTURA NUMBER(1,0) DEFAULT 0 NOT NULL; 
ALTER TABLE TIPICAUSALIONERI ADD FLAG_GENERA_AVVISO NUMBER(1,0) DEFAULT 0 NOT NULL;

comment on column TIPICAUSALIONERI.FLAG_GENERA_FATTURA is 'Indica se le posizioni debitorie create per questa causale devono richiedere la generazione della fattura al nodo pagamenti'; 
comment on column TIPICAUSALIONERI.FLAG_GENERA_AVVISO is 'Indica se le posizioni debitorie create per questa causale devono richiedere la generazione dell''avviso al nodo pagamenti'; 

CREATE TABLE ISTANZEONERI_POSDEB_BATCH(
IDCOMUNE VARCHAR2(6 CHAR) NOT NULL,
FK_ISTANZEONERI_ID NUMBER(10,0) NOT NULL,
ID_POSIZIONE_DEBITORIA NUMBER(10,0) NOT NULL,
TIPO_DOCUMENTO VARCHAR2(20 CHAR) NOT NULL,
FLAG_COMPLETATA NUMBER(1,0) DEFAULT 0 NOT NULL
);


ALTER TABLE ISTANZEONERI_POSDEB_BATCH ADD CONSTRAINT PK_ISTANZEONERI_POSDEB_BATCH PRIMARY KEY(IDCOMUNE,FK_ISTANZEONERI_ID,ID_POSIZIONE_DEBITORIA,TIPO_DOCUMENTO);

ALTER TABLE ISTANZEONERI_POSDEB_BATCH ADD CONSTRAINT FK_ISTONPOSDEBBATCH_ISTON FOREIGN KEY(IDCOMUNE,FK_ISTANZEONERI_ID) REFERENCES ISTANZEONERI(IDCOMUNE, ID); 
ALTER TABLE ISTANZEONERI_POSDEB_BATCH ADD CONSTRAINT FK_ISTONPOSDEBBATCH_DETTPOSDEB FOREIGN KEY(IDCOMUNE,ID_POSIZIONE_DEBITORIA)
REFERENCES DETT_POSIZIONE_DEBITORIA(IDCOMUNE, ID);

CREATE INDEX IDX_ISTONERI_POSDEB_BATCH_001 ON ISTANZEONERI_POSDEB_BATCH (IDCOMUNE,TIPO_DOCUMENTO,FLAG_COMPLETATA);
CREATE INDEX IDX_ISTONERI_POSDEB_BATCH_002 ON ISTANZEONERI_POSDEB_BATCH (IDCOMUNE,FK_ISTANZEONERI_ID); 
CREATE INDEX IDX_ISTONERI_POSDEB_BATCH_003 ON ISTANZEONERI_POSDEB_BATCH (IDCOMUNE,ID_POSIZIONE_DEBITORIA);


DROP INDEX PAY_POSDEB_IDPSP_UIDX;
CREATE INDEX PAY_POSDEB_IDPSP ON pay_posizioni_debitorie (ID_POSIZIONE_PSP);


alter table pay_posizioni_debitorie add riferimento_client varchar2(20 char) null;

ALTER TABLE istanzeoneri MODIFY fkidtipocausale NUMBER(10,0) NOT NULL;
UPDATE istanzeoneri SET numerorata=1 WHERE numerorata IS NULL;
ALTER TABLE istanzeoneri MODIFY numerorata NUMBER(2,0) NOT NULL;


ALTER TABLE ISTANZE MODIFY (FKIDPROTOCOLLO VARCHAR2(400 CHAR) );
ALTER TABLE MOVIMENTI MODIFY (FKIDPROTOCOLLO VARCHAR2(400 CHAR) );

CREATE TABLE PROTOCOLLO_METADATI (IDCOMUNE VARCHAR2(6 CHAR) NOT NULL, FKIDPROTOCOLLO VARCHAR2(400 CHAR) NOT NULL, METADATO VARCHAR2(50 CHAR) NOT NULL, VALORE VARCHAR2(400 CHAR) NOT NULL);

ALTER TABLE PROTOCOLLO_METADATI ADD CONSTRAINT PROTOCOLLO_METADATI_PK PRIMARY KEY (IDCOMUNE,FKIDPROTOCOLLO,METADATO) ENABLE;

alter table ISTANZEONERI add GUID_RATEIZZAZIONE varchar2(40 char);



ALTER TABLE BOLL_CFG_TIPO  DROP CONSTRAINT FK_BLCFGTIPO_TIPISCAD;
ALTER TABLE BOLL_GEST_TESTATA DROP CONSTRAINT FK_BOLGESTEST_TIPISCAD;

ALTER TABLE BOLL_CFG_TIPO MODIFY FK_TIPISCADENZA_ID NUMBER(3,0) NOT NULL;
ALTER TABLE BOLL_GEST_TESTATA MODIFY FK_TIPISCADENZA_ID NUMBER(3,0) NOT NULL;
ALTER TABLE ONERITIPIRATEIZZAZIONE MODIFY SCADENZARATE NUMBER(3,0) NOT NULL;
ALTER TABLE TIPI_SCADENZA MODIFY ID NUMBER(3,0);

ALTER TABLE ONERITIPIRATEIZZAZIONE ADD CONSTRAINT FK_ONERITIPIRAT_TIPISCAD FOREIGN KEY(SCADENZARATE) REFERENCES TIPI_SCADENZA(ID);
ALTER TABLE BOLL_GEST_TESTATA ADD CONSTRAINT FK_BOLGESTEST_TIPISCAD FOREIGN KEY(FK_TIPISCADENZA_ID) REFERENCES TIPI_SCADENZA(ID);
ALTER TABLE BOLL_CFG_TIPO ADD CONSTRAINT FK_BLCFGTIPO_TIPISCAD FOREIGN KEY(FK_TIPISCADENZA_ID) REFERENCES TIPI_SCADENZA(ID);


ALTER TABLE BOLL_CFG_TIPO MODIFY FK_TIPISCADENZA_ID NUMBER(3,0) NOT NULL;
ALTER TABLE BOLL_GEST_TESTATA MODIFY FK_TIPISCADENZA_ID NUMBER(3,0) NOT NULL;
ALTER TABLE ONERITIPIRATEIZZAZIONE MODIFY SCADENZARATE NUMBER(3,0) NOT NULL;
ALTER TABLE TIPI_SCADENZA MODIFY ID NUMBER(3,0);
ALTER TABLE ONERITIPIRATEIZZAZIONE ADD CONSTRAINT FK_ONERITIPIRAT_TIPISCAD FOREIGN KEY(SCADENZARATE) REFERENCES TIPI_SCADENZA(ID);






ALTER TABLE AUTORIZZAZIONI ADD NUM_PREAVVISI_STORICO NUMBER(4,0);

ALTER TABLE TIPICAUSALIONERIDETTAGLIO ADD FLAG_ATTIVO NUMBER(1,0) DEFAULT 0 NOT NULL;