ALTER TABLE TIPISOGGETTOPEOPLE ADD CONSTRAINT FK_TIPI_SOGG_PEOLE_TIPI_SOGG FOREIGN KEY (IDCOMUNE, CODICETIPOSOGGETTO) REFERENCES TIPISOGGETTO (IDCOMUNE, CODICETIPOSOGGETTO);


ALTER TABLE CONFIGURAZIONEUTENTE ADD CONSTRAINT CONFUTENTE_RESPONSABILI_FK1 FOREIGN KEY (IDCOMUNE,CODICERESPONSABILE) REFERENCES RESPONSABILI(IDCOMUNE, CODICERESPONSABILE);

CREATE INDEX IDX_ANAGRAFESTORICO_001 ON ANAGRAFESTORICO (IDCOMUNE,CODICEANAGRAFE,DATAINIZIOVALIDITA);

CREATE INDEX  IDX_ANAGRAFESTORICO_002 ON ANAGRAFESTORICO (IDCOMUNE,CODICEANAGRAFE,DATAFINEVALIDITA);

CREATE OR REPLACE ALGORITHM=TEMPTABLE VIEW VW_ANAGRAFESTORICO_UTILIZZO AS SELECT IDCOMUNE, FK_RICHIEDENTESTORICO_ID AS IDSTORICO, 'ISTANZE.FK_RICHIEDENTESTORICO_ID' AS UTILIZZO FROM ISTANZE WHERE FK_RICHIEDENTESTORICO_ID IS NOT NULL UNION SELECT IDCOMUNE, FK_TITOLARELEGALESTORICO_ID AS IDSTORICO, 'ISTANZE.FK_TITOLARELEGALESTORICO_ID' AS UTILIZZO FROM ISTANZE WHERE FK_TITOLARELEGALESTORICO_ID IS NOT NULL UNION SELECT IDCOMUNE, FK_PROFESSIONISTASTORICO_ID AS IDSTORICO, 'ISTANZE.FK_PROFESSIONISTASTORICO_ID' AS UTILIZZO FROM ISTANZE WHERE FK_PROFESSIONISTASTORICO_ID IS NOT NULL UNION SELECT IDCOMUNE, FK_RICHIEDENTESTORICO_ID AS IDSTORICO, 'ISTANZERICHIEDENTI.FK_RICHIEDENTESTORICO_ID' AS UTILIZZO FROM ISTANZERICHIEDENTI WHERE FK_RICHIEDENTESTORICO_ID IS NOT NULL UNION SELECT IDCOMUNE, FK_ANAGRAFECOLLSTORICO_ID AS IDSTORICO, 'ISTANZERICHIEDENTI.FK_ANAGRAFECOLLSTORICO_ID' AS UTILIZZO FROM ISTANZERICHIEDENTI WHERE FK_ANAGRAFECOLLSTORICO_ID IS NOT NULL UNION SELECT IDCOMUNE, FK_PROCURATORESTORICO_ID AS IDSTORICO, 'ISTANZERICHIEDENTI.FK_PROCURATORESTORICO_ID' AS UTILIZZO  FROM ISTANZERICHIEDENTI WHERE FK_PROCURATORESTORICO_ID IS NOT NULL;

ALTER TABLE TIPISOGGETTOPEOPLE MODIFY CODICETIPOSOGGETTO NUMERIC(10,0);

ALTER TABLE FO_ARCONFIGURAZIONE ADD NOME_CONFIGURAZIONE_CONTENUTI VARCHAR(50) ;

ALTER TABLE ALBEROPROC_DYN2MODELLIT ADD ORDINE NUMERIC(3,0);

ALTER TABLE TIPIPROCEDURE_DYN2MODELLIT ADD ORDINE NUMERIC(3,0);

ALTER TABLE INVENTARIOPROCDYN2MODELLIT ADD ORDINE NUMERIC(3,0);

ALTER TABLE RESPONSABILI ADD SCAD_DATAINIZIO DATE;
ALTER TABLE RESPONSABILI ADD SCAD_SOFTWARE VARCHAR(2);
ALTER TABLE RESPONSABILI ADD SCAD_OPERATORE NUMERIC(4,0);
ALTER TABLE RESPONSABILI ADD SCAD_COMPORTAMENTO NUMERIC(1,0);

ALTER TABLE RESPONSABILI ADD CONSTRAINT FK_RESPONSABILI_SCADOPE FOREIGN KEY (IDCOMUNE,SCAD_OPERATORE) REFERENCES RESPONSABILI (IDCOMUNE, CODICERESPONSABILE);


ALTER TABLE RESPONSABILI MODIFY SCADENZARIOPREC NUMERIC(5,0);

ALTER TABLE TIPIPROCEDURE ADD CODICEOGGETTO_CERTINVIO NUMERIC(10,0);

ALTER TABLE TIPIPROCEDURE ADD CONSTRAINT FK_TIPIPROCEDURE_OGGETTI FOREIGN KEY (IDCOMUNE,CODICEOGGETTO_CERTINVIO) REFERENCES OGGETTI (IDCOMUNE,CODICEOGGETTO);

delete from INTERESSI_LEGALI;
Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (1,STR_TO_DATE('21-04-1942','%d-%m-%Y'),STR_TO_DATE('15-12-1990','%d-%m-%Y'),5,null);
Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (2,STR_TO_DATE('16-12-1990','%d-%m-%Y'),STR_TO_DATE('31-12-1996','%d-%m-%Y'),10,'Legge 26 novembre 1990, n. 353'); 
Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (3,STR_TO_DATE('01-01-1997','%d-%m-%Y'),STR_TO_DATE('31-12-1998','%d-%m-%Y'),5,'Legge 23 dicembre 1996, n. 662'); 
Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (4,STR_TO_DATE('01-01-1999','%d-%m-%Y'),STR_TO_DATE('31-12-2000','%d-%m-%Y'),2.5,'D.M. 10 dicembre 1998');
Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (5,STR_TO_DATE('01-01-2001','%d-%m-%Y'),STR_TO_DATE('31-12-2001','%d-%m-%Y'),3.5,'D.M. 11 dicembre 2000');
Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (6,STR_TO_DATE('01-01-2002','%d-%m-%Y'),STR_TO_DATE('31-12-2003','%d-%m-%Y'),3,'D.M. 11 dicembre 2001');
Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (7,STR_TO_DATE('01-01-2004','%d-%m-%Y'),STR_TO_DATE('31-12-2007','%d-%m-%Y'),2.5,'D.M. 1 dicembre 2003');
Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (8,STR_TO_DATE('01-01-2008','%d-%m-%Y'),STR_TO_DATE('31-12-2009','%d-%m-%Y'),3,'D.M. 12 dicembre 2007');
Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (9,STR_TO_DATE('01-01-2010','%d-%m-%Y'),STR_TO_DATE('31-12-2010','%d-%m-%Y'),1,'D.M. 4 dicembre 2009');
Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (10,STR_TO_DATE('01-01-2011','%d-%m-%Y'),STR_TO_DATE('31-12-2011','%d-%m-%Y'),1.5,'D.M. 07 Dicembre 2010');
Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (11,STR_TO_DATE('01-01-2012','%d-%m-%Y'),null,2.5,'DM 12 dicembre 2011');

ALTER TABLE MOVIMENTIMAIL MODIFY DESTINATARIO VARCHAR(600);
ALTER TABLE MOVIMENTIMAIL MODIFY DESTINATARIOCC  VARCHAR(600);
ALTER TABLE MOVIMENTIMAIL MODIFY DESTINATARIOBCC  VARCHAR(600);
 
ALTER TABLE ANAGRAFE ADD FO_UTENTETESTER NUMERIC(1);
ALTER TABLE ANAGRAFESTORICO ADD FO_UTENTETESTER NUMERIC(1);