INSERT INTO CLMENU_JAVA(ID,DESCRIZIONE,PAGINA,MENULINK,SOFTWARE,JSP,VERTICALIZZAZIONE,SOFTWAREESCLUSI,LINK_STANDARD,TIPO_FUNZIONALITA,LAYOUTTESTI,MENULINK_V2) VALUES (1058,'Gestione firme remote','firmaremota/list.htm?software=TT','00H','TT','JAVA',NULL,NULL,'firmaremota/list.htm?software=TT','S',NULL,'00H');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('RIC_ANAG_COLL_CSI','DECODIFICHE_TAB_RAGGR_LR','Nella ricerca delle anagrafiche viene fatta una lookup nella tabella DECODIFICHE con la coppia TABELLA/RAGGRUPPAMENTO. Ritorna, se configurata, la lista dati delle cariche AEEP che identificano un soggetto come legale rappresentante o assimilabile di una azienda. Il formato del valore deve essere TABELLA#RAGGRUPPAMENTO (ES: CARICHE_AEEP#LEGALE_RAPPRESENTANTE)');
        
INSERT INTO verticalizzazioniparametribase (MODULO, PARAMETRO, DESCRIZIONE) VALUES('COMPORTAMENTI_MERCATI','COD_TIPODOC_STAMPA','Se configurato allora significa che è possibile in APP-AMBULANTI attivare la stampa PDF delle autorizzazioni. Deve corrispondere ad un valore configurato nella tabella/colonna TIPIDOCUMENTO.IDTIPODOCUMENTO. Verra'' preso il documento salvato nella colonna CODICEOGGETTO_XSL. Il documento deve essere in formato XSLT (XSL Transform) per produrre un HTML ed essere convertito in html mediante il merge con i dati XML');

UPDATE CLMENU_JAVA SET DESCRIZIONE = 'Pagamenti Autorizzazioni/Concessioni' WHERE ID = 1057;

INSERT INTO software (CODICE,DESCRIZIONE,MODULOOPZIONALE,DESCRIZIONELUNGA,ACCESSORAPIDO,ORDINE) VALUES ('LT','Locazioni turistiche',1,'Locazioni turistiche',0,42);
         
         
INSERT INTO verticalizzazionibase (MODULO, DESCRIZIONE, FLAG_GESTCOMUNE) VALUES ('PROTOCOLLO_INSIELREST', 'Evoluzione del protocollo INSIEL con servizi di tipo REST, il web service necessita di autenticazione di tipo OAUTH2', 1);



INSERT INTO verticalizzazioniparametribase (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_INSIELREST', 'ATTIVA_MONF', 'Viene attivato se assume il valore 1, in tutti gli altri casi non viene attivato. Questo parametro indica se il componente deve seguire le regole imposte dal Comune di Monfalcone in ambito di protocollazione. Le regole riguardano la compilazione della denominazione anagrafica da inviare al protocollo insiel, e sono: <NOME> <COGNOME> <LOCALITA_RESIDENZA> (<LOCALITA_SEDE_RESIDENZA> se azienda); se la località coincide con una provincia allora va indicata la sigla, quindi <NOME> <COGNOME> <SIGLAPROVINCIA>, se la località coincide con MONFALCONE allora va indicato il valore CITTA'', quindi <NOME> <COGNOME> CITTA''');
INSERT INTO verticalizzazioniparametribase (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_INSIELREST', 'CLIENT_ID', 'Parametro client_id da passare all''endpoint oauth 2.0');
INSERT INTO verticalizzazioniparametribase (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_INSIELREST', 'CLIENT_SECRET', 'Parametro secret da passare all''endpoint oauth 2.0');
INSERT INTO verticalizzazioniparametribase (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_INSIELREST', 'CODICEREGISTRO', 'Indicare il registro relativo al protocollo, da questo parametro sarà possibile anche recuperare il parametro officecode che dovrà essere implementato sulla tabella PROTOCOLLO_UFFICIREGISTRI');
INSERT INTO verticalizzazioniparametribase (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_INSIELREST', 'CODICEUTENTE', 'E'' l''utente con cui avviene l''autenticazione al web service che coincide con quello cui avviene la protocollazione; se non valorizzato il sistema andrà a cercare il valore nel parametro OPERATORE della verticalizzazione PROTOCOLLO_ATTIVO, in quanto, da questo parametro, è possibile utilizzare dei segnalibri nel caso in cui gli operatori del protocollo siano mappati con quelli del backoffice.');
INSERT INTO verticalizzazioniparametribase (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_INSIELREST', 'CODICE_UFFICIO_OPERANTE', 'Indica il codice ufficio operante del protocollo di Insiel DA NON CONFONDERE con il codice ufficio che va configurato sull''amministrazione nel campo RUOLO e va di pari passo con il registro.');
INSERT INTO verticalizzazioniparametribase (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_INSIELREST', 'DISABILITA_ANNULLA_PROTOCOLLO', 'Consente di disabilitare la possibilità di annullare il protocollo da backoffice. Il web service di Insiel espone i metodi abilitati ad annullare un protocollo, questo però potrebbe non essere accettato dai responsabili. Al Comune di Pordenone ad esempio è stato espressamente chiesto di non dare la possibilità agli operatori di backoffice di eseguire le operazioni di annullamente, che devono essere adibite solamente agli operatori di protocollo. Se valorizzato a 1 elimina la scritta Annulla presente sotto il numero di protocollo nell''istanza o movimento, se uguale a 0 o non valorizzato la stessa scritta sarà visualizzata con annessa possibilità di annullamento.');
INSERT INTO verticalizzazioniparametribase (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_INSIELREST', 'DISABILITA_VALIDAZ_CAP_ITA', 'Valore 1 o 0, se valorizzato a 1 indica che deve essere disabilitato il controllo, da parte del componente che si interfaccia col protocollo, relativo alla validazione di un cap con formato italiano, quindi con solo caratteri numerici e con lunghezza da 4 a 6 caratteri.');
INSERT INTO verticalizzazioniparametribase (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_INSIELREST', 'ESCLUDI_CLASSIFICA', 'Se selezionato consente di ignorare i dati di classifica inviati dal backoffice al componente che gestisce il protocollo Insiel, questo in quanto il protocollo considera la classifica come facoltativa mentre, lato backoffice, è un dato obbligatorio che deve necessariamente essere valorizzato per essere validato, il componente .net che fa da tramite tra le due applicazioni si prenderà carico di gestire (se = 0 o assente) o meno (se valorizzato a 1) la classifica in base al valore di questo parametro. Ad esempio il Comune di Trieste non interessa questo tipo di dato mentro quello di Pordenone si.');
INSERT INTO verticalizzazioniparametribase (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_INSIELREST', 'INVIA_PEC', 'Valore 1 o 0, indica se deve essere richiesto anche l''invio di una pec per i protocolli in partenza. Valido solo per la versione 3 del PROTOCOLLO_INSIEL.');
INSERT INTO verticalizzazioniparametribase (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_INSIELREST', 'MITTENTE_PEC', 'E'' il mittente da utilizzare per fare in modo che il sistema di protocollo determini da chi venga inviata una pec . Tale dato deve necessariamente essere presente anche nel sistema di protocollo. Non è un dato obbligatorio in quanto se non individuato il protocollo userà il proprio principale ma serve nel caso in cui l''ente decida di inviarlo da un mittente dedicato specifico.');
INSERT INTO verticalizzazioniparametribase (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_INSIELREST', 'TIPI_DOCUMENTO_WS', 'Indica la modalità di recupero dati dei tipi documento. Questi possono essere recuperati dalla tabella di VBG Protocollo_TipiDocumento, SE VALORIZZATO A 0 OPPURE A NULL, oppure direttamente dal web service di Insiel, invocando il metodo getTipiDoc, SE VALORIZZATO A 1. Nel primo caso i dati saranno più gestibili, ad esempio indicando solamente i tipi documento necessari all''integrazione, nel secondo avremmo un allineamento certo dei dati in quanto vengono invocati direttamente dagli archivi del protocollo, ma potrebbe anche esserci una mole di dati enorme che renderebbe difficoltosa la gestione di questo dato agli operatori; ad esempio al Comune di Trieste sono presenti più di 200 tipi documento, mentre ne viene utilizzato solamente uno, almeno per le pratiche provenienti da VBG.');
INSERT INTO verticalizzazioniparametribase (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_INSIELREST', 'TIPO_AGGIORNAMENTO_ANAG', 'Questo parametro determina come deve essere aggiornata un''anagrafica quando si richiede un protocollo. Da notare che questo parametro viene utilizzato solamente per la versione 3 del PROTOCOLLO_INSIEL (valore PROTOCOLLO_INSIEL3 su parametro TIPOPROTOCOLLO della regola PROTOCOLLO_ATTIVO) e solo se la ricerca dell''anagrafica per codice fiscale o partita iva viene soddisfatta, altrimenti inserisce una nuova anagrafica.');
INSERT INTO verticalizzazioniparametribase (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_INSIELREST', 'TIPO_GESTIONE_PEC', 'Nome fuorviante, perchè indica come gestire le anagrafiche quando viene richiesto un protocollo, in realtà, serve più che altro per l''invio pec, in quanto non è presente un elemento dove poter indicare l''indirizzo, ma viene recuperato direttamente dall''anagrafe del protocollo, motivo per il quale è comunque il backoffice a gestire questo tipo di dato.');
INSERT INTO verticalizzazioniparametribase (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_INSIELREST', 'TIPO_UFFICIO_ITERATTI', 'Inserire in questo parametro il valore necessario a far avviare ITERATTI in fase di protocollazione, di norma viene inserito il parametro DITER.');
INSERT INTO verticalizzazioniparametribase (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_INSIELREST', 'URL_OAUTH', 'Endpoint relativo all''autenticazione oauth 2.0 da utilizzare per ottenere il token da usare poi per le chiamate al web service rest. es: https://is.regione.fvg.it/oauth2/token.');
INSERT INTO verticalizzazioniparametribase (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_INSIELREST', 'URL_OAUTH_TEST', 'Endpoint di test relativo all''autenticazione oauth 2.0 da utilizzare per ottenere il token da usare poi per le chiamate al web service rest. es: https://is.regione.fvg.it/oauth2/token.');
INSERT INTO verticalizzazioniparametribase (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_INSIELREST', 'URL_WSCOLLAUDO', 'Endpoint del web service rest di collaudo.');
INSERT INTO verticalizzazioniparametribase (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_INSIELREST', 'URL_WSPRODUZIONE', 'Endpoint del web service rest di produzione.');
INSERT INTO verticalizzazioniparametribase (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_INSIELREST', 'USA_LIVELLI_CLASSIFICA', 'Questo parametro indica se il componente che adatta la richiesta da inviare al protocollo, deve utilizzare il valore indicato nella classifica come codice (valore a 0 o non valorizzato); oppure come livelli (valorizzare a 1); nel secondo caso va configurata una classifica a più livelli, separati da un punto ".", ad esempio 8.1.1.4, 8 è il primo livello, 1 il secondo, 1 il terzo e 4 il quarto, il tutto fino a 8 livelli.');
INSERT INTO verticalizzazioniparametribase (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_INSIELREST', 'USA_WS_CLASSIFICHE', 'Indica la modalità di recupero dati relativamente alle voci di titolario (classificazione). Se valorizzato a 1 saranno recuperate tramite apposito metodo del web service, altrimenti sarà utilizzato il metodo classico, ossia o da tabella protocollo_classifiche oppure tramite testo libero.');
INSERT INTO verticalizzazioniparametribase (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_INSIELREST', 'USA_WS_TEST', 'Se impostato a 1 indica l''utilizzo del WS di collaudo. Se impostato a 0 invece indica l''utilizzo del WS di produzione.');
INSERT INTO verticalizzazioniparametribase (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_INSIELREST', 'USA_PREDISPONI_ANAGRAFICA', 'Se impostato a 0 indica l''utilizzo della vecchia logica in cui si chiama prima il metodo di ricerca anagrafica e successivamente quello di creazione o aggiornamento. Se impostato a 1 invece indica l''utilizzo del nuovo metodo predisponi-anagrafica del WS rest. Tenere presente che la nuova logica esegue la ricerca dell''anagrafica per tutti i parametri passati: DENOMINAZIONE, CODICE FISCALE, PARTITA IVA, NOME/COGNOME.');

INSERT INTO VERTICALIZZAZIONIBASE (MODULO,DESCRIZIONE,FLAG_GESTCOMUNE) VALUES ('PRATICA_DA_SISTEMA_ESTERNO','Se attiva sulla funzionalità Azioni Protocollo è possibile inserire direttamente una pratica da un sistema esterno con modellazione Impresa in un giorno e Faldone Telematico',0);
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) VALUES ('STC','NLA_IDNODO_INFOCAMERE','Identificativo - registrato su STC - del nodo di integrazione con impresainungiorno(nla-infocamere)');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) VALUES ('PRATICA_DA_SISTEMA_ESTERNO','IDNODO_INFOCAMERE','Identificativo - registrato su STC - del nodo di integrazione con il nodo nla-infocamere');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) VALUES ('PRATICA_DA_SISTEMA_ESTERNO','NLA_IDNODO','Id del nodo NLA BACKOFFICE registrato su STC');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_INSIELREST', 'DISATTIVA_CTRL_DOCS', 'Impostando il parametro a 1 indica al componente di protocollazione di Insiel di non procedere con il controllo sulla duplicazione dei documenti, sarà quindi possibile inviare più documenti identici (con lo stesso codice hash), cosa che di default non è possibile fare in quanto il protocollo blocca la protocollazione.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('SIT_JESI', 'USERNAME', 'Indicare lo username che viene fornito dal fornitore del SIT');

INSERT INTO VERTICALIZZAZIONIBASE(MODULO,DESCRIZIONE,FLAG_GESTCOMUNE) VALUES ('GEECO','Permette la gestione integrata delle localizzazioni tramite il software cartografico Geeco',0);
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES('GEECO','AUTH_COMMUNITY_BACK','Indica la community utilizzata per accedere al backend e serve per non dover fare nuovamente login. Es. wrup');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES('GEECO','AUTH_COMMUNITY_FRONT','Indica la community utilizzata per accedere al frontend e serve per non dover fare nuovamente login. Es. spid-gaspcmto');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES('GEECO','AUTH_LEVEL_BACK','Indica il livello utilizzato per accedere al backend e serve per non dover fare nuovamente login. Es. liv1');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES('GEECO','AUTH_LEVEL_FRONT','Indica il livello utilizzato per accedere al frontend e serve per non dover fare nuovamente login. Es. liv1');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES('GEECO','APIINFO_UUID_BACK','Contiene il parametro ApiInfo.uuid da passare a GEECO per le chiamate da backend');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES('GEECO','APIINFO_UUID_FRONT','Contiene il parametro ApiInfo.uuid da passare a GEECO per le chiamate da frontend');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES('GEECO','EDITING_LAYER_BACK','Contiene l''identificativo del livello editabile da passare a GEECO per le chiamate da backend');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES('GEECO','EDITING_LAYER_FRONT','Contiene l''identificativo del livello editabile da passare a GEECO per le chiamate da frontend');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES('GEECO','URL_COMPONENTE_BACK','Indicare la url del componente di integrazione utilizzato dal backend (es. http://localhost:8080)');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES('GEECO','URL_COMPONENTE_FRONT','Indicare la url del componente di integrazione utilizzato dal frontend (es. http://localhost:8080)');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES('GEECO','MODELLO_ALTRI_DATI','Inserire il codice testuale della scheda dinamica su cui verranno riportati i dati recuperati tramite l''integrazione');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO,PARAMETRO,DESCRIZIONE) VALUES('GEECO','CAMPO_ALTRI_DATI','Inserire il nome del campo dinamico su cui verranno riportati i dati recuperati tramite l''integrazione. I dati vengono riportati in formato JSON per essere poi lavorati tramite formule');