CREATE TABLE CODA_MESSAGGI_RABBIT (
IDCOMUNE VARCHAR(6) NOT NULL,
UUID VARCHAR(60) NOT NULL,
UUID_ISTANZA VARCHAR(60) NULL,
UUID_MOVIMENTO VARCHAR(60) NULL,
UUID_POS_DEB VARCHAR(60) NULL,
TOPIC VARCHAR(100) NOT NULL,
MESSAGGIO LONGTEXT NOT NULL,
DATA_CREAZIONE DATETIME NOT NULL,
PROGRESSIVO DECIMAL(15,0) NOT NULL,
DATA_TRASMISSIONE DATETIME
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
ALTER TABLE CODA_MESSAGGI_RABBIT ADD CONSTRAINT PK_CODA_MESSAGGI PRIMARY KEY (IDCOMUNE,UUID);

CREATE INDEX IDX_CODAMSGRABBIT_01 ON CODA_MESSAGGI_RABBIT (IDCOMUNE, DATA_CREAZIONE, PROGRESSIVO);
CREATE INDEX IDX_CODAMSGRABBIT_02 ON CODA_MESSAGGI_RABBIT (IDCOMUNE, UUID_ISTANZA);
CREATE INDEX IDX_CODAMSGRABBIT_03 ON CODA_MESSAGGI_RABBIT (IDCOMUNE, UUID_POS_DEB);

CREATE OR REPLACE
ALGORITHM = MERGE VIEW `vw_i_attivitalista` AS
SELECT
    `i_attivita`.`CODICEISTANZAULTIMA` AS `I_CODICEISTANZAULTIMA`,
    `i_attivita`.`ID` AS `I_IDATTIVITA`,
    `i_attivita`.`IDCOMUNE` AS `IDCOMUNE`,
    `i_attivita`.`ATTIVA` AS `ATTIVA`,
    `i_attivita`.`OPERANTE` AS `OPERANTE`,
    `istanze`.`SOFTWARE` AS `SOFTWARE`,
    `i_attivita`.`DENOMINAZIONE` AS `DENOMINAZIONE`,
    `istanze`.`NUMEROISTANZA` AS `NUMEROISTANZA`,
    `istanze`.`CODICERICHIEDENTE` AS `CODICERICHIEDENTE`,
    CONCAT_WS('', `t_richiedente`.`NOMINATIVO`, ' ', `t_richiedente`.`NOME`) AS `RICHIEDENTE`,
    TRIM(CONCAT_WS('', `t_richiedente`.`CODICEFISCALE`, ' ', `t_richiedente`.`PARTITAIVA`)) AS `CF_PIVA_RICHIEDENTE`,
    `istanze`.`FKCODICESOGGETTO` AS `FKCODICESOGGETTO`,
    `tipisoggetto`.`TIPOSOGGETTO` AS `TIPOSOGGETTO`,
    `istanze`.`CODICECOMUNE` AS `CODICECOMUNE`,
    `istanze`.`CODICETITOLARELEGALE` AS `CODICETITOLARELEGALE`,
    TRIM(CONCAT_WS('', `t_aziendarichiedente`.`NOMINATIVO`, ' ', `t_aziendarichiedente`.`NOME`)) AS `AZIENDARICHIEDENTE`,
    TRIM(CONCAT_WS('', `t_aziendarichiedente`.`CODICEFISCALE`, ' ', `t_aziendarichiedente`.`PARTITAIVA`)) AS `CF_PIVA_AZIENDARICHIEDENTE`,
    `istanzestradario`.`CODICESTRADARIO` AS `CODICESTRADARIO`,
    CONCAT_WS('', `stradario`.`PREFISSO`, ' ', `stradario`.`DESCRIZIONE`, ',', IFNULL(`istanzestradario`.`CIVICO`, ''), IFNULL(`istanzestradario`.`COLORE`, '')) AS `LOCALIZZAZIONE`,
    `istanzestradario`.`CIVICO` AS `CIVICO`,
     ISTANZESTRADARIO.CODICECIVICO AS CODICECIVICO,
     i_attivita.fk_iatipologie_id AS fk_iatipologie_id
FROM
    ((((((`istanze`
LEFT JOIN `anagrafe` `t_aziendarichiedente` ON
    (((`istanze`.`IDCOMUNE` = `t_aziendarichiedente`.`IDCOMUNE`) AND (`istanze`.`CODICETITOLARELEGALE` = `t_aziendarichiedente`.`CODICEANAGRAFE`))))
LEFT JOIN `tipisoggetto` ON
    (((`istanze`.`IDCOMUNE` = `tipisoggetto`.`IDCOMUNE`) AND (`istanze`.`FKCODICESOGGETTO` = `tipisoggetto`.`CODICETIPOSOGGETTO`))))
LEFT JOIN `istanzestradario` ON
    (((`istanzestradario`.`IDCOMUNE` = `istanze`.`IDCOMUNE`) AND (`istanzestradario`.`CODICEISTANZA` = `istanze`.`CODICEISTANZA`) AND (`istanzestradario`.`PRIMARIO` = 1))))
LEFT JOIN `stradario` ON
    (((`stradario`.`IDCOMUNE` = `istanzestradario`.`IDCOMUNE`) AND (`stradario`.`CODICESTRADARIO` = `istanzestradario`.`CODICESTRADARIO`))))
JOIN `i_attivita`)
JOIN `anagrafe` `t_richiedente`)
WHERE
    ((`istanze`.`IDCOMUNE` = `i_attivita`.`IDCOMUNE`)
        AND (`istanze`.`CODICEISTANZA` = `i_attivita`.`CODICEISTANZAULTIMA`)
            AND (`t_richiedente`.`IDCOMUNE` = `istanze`.`IDCOMUNE`)
                AND (`t_richiedente`.`CODICEANAGRAFE` = `istanze`.`CODICERICHIEDENTE`));
                

ALTER TABLE RER_MEDIEGRANDI
  ADD COLUMN SPECIALI DECIMAL(10,2) NULL,
  ADD COLUMN TIPOLOGIASPECIALI VARCHAR(4000) NULL;

ALTER TABLE RER_MEDIEGRANDI MODIFY COLUMN COD_CENTROCOMMERCIALE VARCHAR(20);
 
 
ALTER TABLE RER_VICINATO
  ADD COLUMN SPECIALI DECIMAL(10,2) NULL,
  ADD COLUMN TIPOLOGIASPECIALI VARCHAR(4000) NULL;

ALTER TABLE RER_VICINATO
MODIFY COLUMN COD_CENTROCOMMERCIALE VARCHAR(20);

ALTER TABLE fo_domande_ssu ADD COLUMN NON_ELABORABILE DECIMAL(1,0) DEFAULT 0;

ALTER TABLE MAILTIPO ADD PROTOCOLLO_OGGETTO_MAIL VARCHAR(512);
ALTER TABLE MAILTIPO ADD PROTOCOLLO_CORPO_MAIL LONGTEXT;


CREATE TABLE FO_DOMANDE_SSU_CORREZIONI (
  IDCOMUNE varchar(6) NOT NULL,
  ID decimal(10,0) NOT NULL,
  FK_IDDOMANDA decimal(6,0) NOT NULL,
  PROCEDIMENTO_ID decimal(10,0) NOT NULL,
  CORREZIONE_RICHIESTA varchar(2000),
  CREATA_IL datetime not null,
  CORRETTA_IL datetime null,
  PRIMARY KEY (IDCOMUNE,ID),
  CONSTRAINT FK_SSU_CORR_FO_DOMANDE FOREIGN KEY (IDCOMUNE, FK_IDDOMANDA) REFERENCES fo_domande (IDCOMUNE, ID)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE fo_domande_ssu_audit (
    idComune VARCHAR(6) NOT NULL,
    id DECIMAL(6,0) NOT NULL,
    fk_idDomanda DECIMAL(6,0) NOT NULL,
    stato DECIMAL(3,0) NULL,
    data DATETIME NULL,
    errore VARCHAR(500) NULL,
    CONSTRAINT PK_FO_DOM_SSU_AUDIT PRIMARY KEY (idComune, id),
    CONSTRAINT FK_AUDIT_FO_DOMANDE
      FOREIGN KEY (idComune, fk_idDomanda)
      REFERENCES fo_domande (idComune, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO pay_connector_config_params (CONFIG_PARAM,DESCRIZIONE,CODICE_CONNETTORE) VALUES ('ID_INSTALLAZIONE','Questo parametro può essere utilizzato dall''ente nelle sue chiamate REST o SOAP',null);

ALTER TABLE pay_profili_enti_creditori ADD COLUMN LOGO_ENTE LONGBLOB;

ALTER TABLE BLACKLIST_MOTIVI ADD COLUMN DATA_ACCERTAMENTO DATE;
ALTER TABLE PAY_POSIZIONI_DEBITORIE ADD COLUMN DATA_FINE_VALIDITA DATE;
ALTER TABLE DETT_POSIZIONE_DEBITORIA ADD COLUMN DATA_FINE_VALIDITA DATE;
