ALTER TABLE SERVIZI MODIFY CODICECOMUNE VARCHAR(6);
ALTER TABLE SERVIZI MODIFY SOFTWARE VARCHAR(2);
ALTER TABLE MESSAGGI ADD COLUMN IDENTIFICATIVO_SERVIZIO VARCHAR(50) NOT NULL;
ALTER TABLE MESSAGGI MODIFY CODICECOMUNE VARCHAR(6);
ALTER TABLE MESSAGGI MODIFY SOFTWARE VARCHAR(2);
DROP INDEX IDX_SERVIZI_01 ON SERVIZI;
DROP INDEX UKDOA63WLB8QPNVK6YUCGOSQIWS ON SERVIZI;
ALTER TABLE MESSAGGI DROP COLUMN CODICECOMUNE;
ALTER TABLE MESSAGGI DROP COLUMN SOFTWARE;
ALTER TABLE SERVIZI DROP COLUMN CODICECOMUNE;
ALTER TABLE SERVIZI DROP COLUMN SOFTWARE;

