CREATE TABLE  mercati_massive_t  (
   IDCOMUNE  varchar(6) NOT NULL,
   ID  decimal(6,0) NOT NULL,
   FKID_TESTATA  decimal(6,0) NOT NULL,
  PRIMARY KEY ( IDCOMUNE , ID ),
  KEY  FK_MERCMASSIVET_TESTATA  ( IDCOMUNE , FKID_TESTATA ),
  CONSTRAINT  FK_MERCMASSIVET_TESTATA  FOREIGN KEY ( IDCOMUNE ,  FKID_TESTATA ) REFERENCES  massive_testata  ( IDCOMUNE ,  ID )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE  mercati_massive_d  (
   IDCOMUNE  varchar(6) NOT NULL,
   ID  decimal(6,0) NOT NULL,
   FKID_MASSIVE_D  decimal(6,0) NOT NULL,
   FK_AUTORIZZAZIONE  decimal(6,0) NOT NULL,
  PRIMARY KEY ( IDCOMUNE , ID ),
  KEY  FK_MERCMASSIVED_MASSIVED  ( IDCOMUNE , FKID_MASSIVE_D ),
  KEY  FK_MERCMASSIVED_AUT  ( IDCOMUNE , FK_AUTORIZZAZIONE ),
  CONSTRAINT  FK_MERCMASSIVED_MASSIVED  FOREIGN KEY ( IDCOMUNE ,  FKID_MASSIVE_D ) REFERENCES  massive_dettaglio  ( IDCOMUNE ,  ID )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE  mercati_massive_d_aut  (
   IDCOMUNE  varchar(6) NOT NULL,
   ID  varchar(50) NOT NULL,
   FK_MERCATI_MASSIVE_D  decimal(6,0) NOT NULL,
   FK_CODICEMERCATO  decimal(4,0) NOT NULL,
   FK_POSTEGGIO  decimal(6,0) DEFAULT NULL,
   FK_USO  decimal(4,0) DEFAULT NULL,
  PRIMARY KEY ( IDCOMUNE , ID ),
  KEY  FK_MMD_MASSIVED_AUT  ( IDCOMUNE , FK_MERCATI_MASSIVE_D ),
  KEY  FK_MMD_MASSIVED_MERC  ( IDCOMUNE , FK_CODICEMERCATO ),
  CONSTRAINT  FK_MMD_MASSIVED_AUT  FOREIGN KEY ( IDCOMUNE ,  FK_MERCATI_MASSIVE_D ) REFERENCES  mercati_massive_d  ( IDCOMUNE ,  ID )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE  istanze_massive_t  (
   IDCOMUNE  varchar(6) NOT NULL,
   ID  decimal(6,0) NOT NULL,
   FKID_TESTATA  decimal(6,0) NOT NULL,
   GRUPPO_TYPE  varchar(8) NOT NULL,
  PRIMARY KEY ( IDCOMUNE , ID ),
  KEY  FK_ISTMASSIVET_TESTATA  ( IDCOMUNE , FKID_TESTATA ),
  CONSTRAINT  FK_ISTMASSIVET_TESTATA  FOREIGN KEY ( IDCOMUNE ,  FKID_TESTATA ) REFERENCES  massive_testata  ( IDCOMUNE ,  ID )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE  istanze_massive_d  (
   IDCOMUNE  varchar(6) NOT NULL,
   ID  decimal(6,0) NOT NULL,
   FKID_MASSIVE_D  decimal(6,0) NOT NULL,
   FLAG_MOVIMENTO  decimal(1,0) NOT NULL,
   FK_TIPIMOVIMENTO  varchar(8) DEFAULT NULL,
   FK_AMMINISTRAZIONE  decimal(10,0) DEFAULT NULL,
  PRIMARY KEY ( IDCOMUNE , ID ),
  KEY  FK_ISTMASSIVED_MASSIVED  ( IDCOMUNE , FKID_MASSIVE_D ),
  CONSTRAINT  FK_ISTMASSIVED_MASSIVED  FOREIGN KEY ( IDCOMUNE ,  FKID_MASSIVE_D ) REFERENCES  massive_dettaglio  ( IDCOMUNE ,  ID )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE  istanze_massive_d_istanze  (
   IDCOMUNE  varchar(6) NOT NULL,
   ID  decimal(6,0) NOT NULL,
   FKID_ISTANZEMD  decimal(6,0) NOT NULL,
   FKCODICEISTANZA  decimal(6,0) NOT NULL,
   FKMOVIMENTO  decimal(8,0) DEFAULT NULL,
  PRIMARY KEY ( IDCOMUNE , ID ),
  KEY  FK_ISTMASSIVETISD_ISTMASSIVED  ( IDCOMUNE , FKID_ISTANZEMD ),
  KEY  FK_ISTMASSIVETISD_ISTANZE  ( IDCOMUNE , FKCODICEISTANZA ),
  CONSTRAINT  FK_ISTMASSIVETISD_ISTMASSIVED  FOREIGN KEY ( IDCOMUNE ,  FKID_ISTANZEMD ) REFERENCES  istanze_massive_d  ( IDCOMUNE ,  ID )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE MASSIVE_D_APPIO_CODA (
  IDCOMUNE VARCHAR(6) NOT NULL,
  FK_MASSIVE_D NUMERIC(6,0) NOT NULL,
  FK_GUIDCODA VARCHAR(40) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8;

 
ALTER TABLE MASSIVE_D_APPIO_CODA ADD CONSTRAINT PK_MASSIVE_D_APPIO_CODA PRIMARY KEY(IDCOMUNE,FK_MASSIVE_D,FK_GUIDCODA);
ALTER TABLE MASSIVE_D_APPIO_CODA ADD CONSTRAINT FK_MASSIVE_D_APPIO_CODA_APP_IO_CODA FOREIGN KEY(IDCOMUNE,FK_GUIDCODA) REFERENCES APP_IO_CODA(IDCOMUNE,GUID);
ALTER TABLE MASSIVE_D_APPIO_CODA ADD CONSTRAINT FK_MASSIVE_D_APPIO_CODA_MASSIVE_D FOREIGN KEY(IDCOMUNE,FK_MASSIVE_D) REFERENCES MASSIVE_DETTAGLIO(IDCOMUNE,ID);

ALTER TABLE MERCATI_MASSIVE_T ADD COLUMN SOFTWARE VARCHAR(2);
ALTER TABLE MERCATI_MASSIVE_T ADD CONSTRAINT FK_SOFTWARE_MERCATI_MASSIVE_T FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);

ALTER TABLE ISTANZE_MASSIVE_T ADD COLUMN SOFTWARE VARCHAR(2);
ALTER TABLE ISTANZE_MASSIVE_T ADD CONSTRAINT FK_SOFTWARE_ISTANZE_MASSIVE_T FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);

ALTER TABLE boll_gest_dett_autorizz ADD fk_autsubentri_id NUMERIC(6,0);
ALTER TABLE boll_gest_dett_autorizz ADD CONSTRAINT fk_bgdetaut_autsubid FOREIGN KEY (idcomune,fk_autsubentri_id) REFERENCES autorizzazioni_subentri(idcomune,id);

ALTER TABLE BLACKLIST_MOTIVI ADD CONTESTO VARCHAR(20);

CREATE TABLE BOLL_GEST_FASE1
(
  IDCOMUNE VARCHAR(6) NOT NULL,
  GUID VARCHAR(60) NOT NULL,
  PROVENIENZA VARCHAR(20) NOT NULL,
  SUBENTRO DECIMAL(1,0) NOT NULL,
  IDGIORNATA DECIMAL(6,0) NOT NULL,
  DATAGIORNATA DATETIME NOT NULL,
  IDPOSTEGGIO DECIMAL(6,0) NOT NULL,
  IDANAGRAFE DECIMAL(6,0) NOT NULL,
  IDRIFERIMENTO DECIMAL(6,0) NOT NULL,
  IDAUTORIZZAZIONECONCESSIONE DECIMAL(6,0) NULL,
  ASSENZAGIUSTIFICATA DECIMAL(1,0) NOT NULL,
  CONCPRESENTE DECIMAL(1,0) NOT NULL,
  SPUNTPRESENTE DECIMAL(1,0) NOT NULL,
  CATMERC VARCHAR(15) NULL,
  IDUSO DECIMAL(4,0) NOT NULL,
  IDAUTORIZZAZIONISUBENTRI DECIMAL(6,0) NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8;

ALTER TABLE BOLL_GEST_FASE1 ADD INDEX IDX_BGFASE1_001(IDCOMUNE, GUID, IDUSO, DATAGIORNATA);
ALTER TABLE BOLL_GEST_FASE1 ADD INDEX IDX_BGFASE1_002(IDCOMUNE, GUID, IDGIORNATA, IDPOSTEGGIO, IDUSO, IDANAGRAFE);
ALTER TABLE BOLL_GEST_FASE1 ADD INDEX IDX_BGFASE1_003(IDCOMUNE, IDRIFERIMENTO);
ALTER TABLE BOLL_GEST_FASE1 ADD INDEX IDX_BGFASE1_004(IDCOMUNE, GUID, IDANAGRAFE, IDPOSTEGGIO);


CREATE TABLE BOLL_GEST_FASE2
(
  IDCOMUNE VARCHAR(6) NOT NULL,
  GUID VARCHAR(60) NOT NULL,
  IDCALCOLO DECIMAL(10,0) NOT NULL,
  CALCOLO VARCHAR(300) NOT NULL,
  INIZIO_VALIDITA_CALCOLO DATETIME NOT NULL,
  FINE_VALIDITA_CALCOLO DATETIME NOT NULL,
  FORMULA VARCHAR(400) NOT NULL,
  IDUSO DECIMAL(4,0) NOT NULL,
  IDCONTABILITA DECIMAL(10,0) NOT NULL,
  CONTABILITA VARCHAR(200) NOT NULL,
  INIZIO_VALIDITA_CONTABILITA DATETIME NOT NULL,
  FINE_VALIDITA_CONTABILITA DATETIME NOT NULL,
  IDCONTO DECIMAL(6,0) NOT NULL,
  CONTO VARCHAR(100) NOT NULL,
  IVA DECIMAL(5,0) NOT NULL,
  FINE_VALIDITA_CONTO DATETIME NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8;

ALTER TABLE BOLL_GEST_FASE2 ADD INDEX IDX_BGFASE2_001(IDCOMUNE, GUID, IDUSO, INIZIO_VALIDITA_CALCOLO, FINE_VALIDITA_CALCOLO, INIZIO_VALIDITA_CONTABILITA, FINE_VALIDITA_CONTABILITA, FINE_VALIDITA_CONTO);

CREATE TABLE BOLL_GEST_FASE3
(
  IDCOMUNE VARCHAR(6) NOT NULL,
  GUID VARCHAR(60) NOT NULL,
  PROVENIENZA VARCHAR(20) NOT NULL,
  CALCOLO VARCHAR(300) NOT NULL,
  IDANAGRAFE DECIMAL(6,0) NOT NULL,
  IDGIORNATA DECIMAL(6,0) NOT NULL,
  IDPOSTEGGIO DECIMAL(6,0) NOT NULL,
  IDUSO DECIMAL(4,0) NOT NULL,
  CONCPRESENTE DECIMAL(1,0) NOT NULL,
  SPUNTPRESENTE DECIMAL(1,0) NOT NULL,
  ASSENZAGIUSTIFICATA DECIMAL(1,0) NOT NULL,
  CATMERC VARCHAR(15) NULL,
  IDCONTO DECIMAL(6,0) NOT NULL,
  FORMULA VARCHAR(400) NOT NULL,
  IMPORTO_SENZA_IVA DECIMAL(11,2) NULL,
  IVA DECIMAL(5,0) NOT NULL,
  IMPORTO_TOTALE DECIMAL(11,2) NULL,
  FLAG_CONGUAGLIO DECIMAL(1,0) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8;

ALTER TABLE BOLL_GEST_FASE3 ADD INDEX IDX_BGFASE3_001(IDCOMUNE, GUID, IDCONTO, IDANAGRAFE, IDPOSTEGGIO);
ALTER TABLE BOLL_GEST_FASE3 ADD INDEX IDX_BGFASE3_002(IDCOMUNE, IDPOSTEGGIO);
ALTER TABLE BOLL_GEST_FASE3 ADD INDEX IDX_BGFASE3_003(IDCOMUNE, IDGIORNATA, IDPOSTEGGIO, IDUSO, IDANAGRAFE);
ALTER TABLE BOLL_GEST_FASE3 ADD INDEX IDX_BGFASE3_004(IDCOMUNE, GUID, IDGIORNATA, IDUSO, IDPOSTEGGIO, IDCONTO);

CREATE TABLE BOLL_GEST_FASE4
(
  IDCOMUNE VARCHAR(6) NOT NULL,
  GUID VARCHAR(60) NOT NULL,
  IDBOLLGEST DECIMAL(4,0) NOT NULL,
  IDBOLLGESTDETT DECIMAL(10,0) NOT NULL,
  IDMERCATO DECIMAL(4,0) NOT NULL,
  IDPOSTEGGIO DECIMAL(6,0) NOT NULL,
  FLAG_VALIDATA DECIMAL(1,0) NOT NULL,
  FK_RETTIFICA_ID DECIMAL(10,0) NULL,
  DESCRIZIONE VARCHAR(1000) NOT NULL,
  FLAG_INS_AUTO DECIMAL(1,0) NOT NULL,
  FK_CODICEANAGRAFE DECIMAL(6,0) NOT NULL,
  FK_CONTO_ID DECIMAL(6,0) NOT NULL,
  FK_POSDEBDETTAGLIO_ID DECIMAL(10,0) NULL,
  FLAG_ELIMINATA DECIMAL(1,0) NOT NULL,
  NOTE_UTENTE VARCHAR(4000) NULL,
  NOTE_SISTEMA VARCHAR(4000) NULL,
  FLAG_RETTIFICATA DECIMAL(1,0) NOT NULL,
  IMPORTO_SENZA_IVA DECIMAL(11,2) NOT NULL,
  IVA DECIMAL(2,0) NULL,
  IMPORTO_TOTALE DECIMAL(11,2) NOT NULL,
  FLAG_CONGUAGLIO DECIMAL(1,0) NOT NULL,
  DATA_SCADENZA DATETIME NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8;

ALTER TABLE BOLL_GEST_FASE4 ADD INDEX IDX_BGFASE4_001(IDCOMUNE, GUID, FK_CONTO_ID, FK_CODICEANAGRAFE, IDPOSTEGGIO);
ALTER TABLE BOLL_GEST_FASE4 ADD INDEX IDX_BGFASE4_002(IDCOMUNE, GUID, FK_CODICEANAGRAFE, IDPOSTEGGIO);
ALTER TABLE BOLL_GEST_FASE4 ADD INDEX IDX_BGFASE4_003(IDCOMUNE, IDBOLLGESTDETT);

CREATE TABLE BOLL_GEST_FASE5
(
  IDCOMUNE VARCHAR(6) NOT NULL,
  GUID VARCHAR(60) NOT NULL,
  FK_AUTORIZZAZIONE_ID DECIMAL(6,0) NOT NULL,
  FK_BOLLGESTDET_ID DECIMAL(10,0) NOT NULL,
  FK_BOLLGEST_ID DECIMAL(4,0) NOT NULL,
  FK_AUTSUBENTRI_ID DECIMAL(6,0) NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8;

ALTER TABLE BOLL_GEST_FASE5 ADD INDEX IDX_BGFASE5_001(IDCOMUNE, GUID);


UPDATE verticalizzazionibase
SET
descrizione=CONCAT('(OBSOLETO) La funzionalità di configurazione delle firme remote e'' raggiungibile dal menu'' archivi-->archivi di base-->Gestione firme remote. ',descrizione)
WHERE
modulo = 'FIRMA_REMOTA_ARUBA' OR modulo ='FIRMA_REMOTA_INFOCERT';



CREATE TABLE CONFIGURAZIONI_METADATI (
        IDCOMUNE VARCHAR(6) NOT NULL,
        FKIDCOMUNIASSOCIATISOFTWARE DECIMAL(8, 0) NOT NULL,
        CHIAVE VARCHAR(254) NOT NULL,
        VALORE VARCHAR(4000),        
        SOFTWARE VARCHAR (2),
        ORDINE NUMERIC(10, 0),
        CATEGORIA VARCHAR(254)
    ) ENGINE = INNODB DEFAULT CHARSET = utf8;

ALTER TABLE CONFIGURAZIONI_METADATI ADD CONSTRAINT PK_CONFIGURAZIONI_METADATI PRIMARY KEY (IDCOMUNE, FKIDCOMUNIASSOCIATISOFTWARE, CHIAVE);
ALTER TABLE CONFIGURAZIONI_METADATI ADD CONSTRAINT FK_CONFIGURAZIONIMETADATI_COMUNIASSOCIATISOFTWARE FOREIGN KEY (IDCOMUNE, FKIDCOMUNIASSOCIATISOFTWARE) REFERENCES COMUNIASSOCIATISOFTWARE (IDCOMUNE, ID);

UPDATE CONTI SET DATASCADENZA='2999-12-31' WHERE DATASCADENZA IS NULL;
ALTER TABLE CONTI MODIFY DATASCADENZA DATETIME NOT NULL;
ALTER TABLE CONTI MODIFY DESCRIZIONE VARCHAR(100) NOT NULL;   

UPDATE MERCATI_FORMULE_CALCOLO SET DATA_FINE_VALIDITA='2999-12-31' WHERE DATA_FINE_VALIDITA IS NULL;
ALTER TABLE MERCATI_FORMULE_CALCOLO MODIFY DATA_FINE_VALIDITA DATETIME NOT NULL;
       
UPDATE MERCATI_CONTABILITA_TRIBUTI SET DATA_FINE_VALIDITA='2999-12-31' WHERE DATA_FINE_VALIDITA IS NULL;
ALTER TABLE MERCATI_CONTABILITA_TRIBUTI MODIFY DATA_FINE_VALIDITA DATETIME NOT NULL;
 
ALTER TABLE prot_allegatiprotocollo MODIFY COLUMN AD_DESCRIZIONE VARCHAR(70);

ALTER TABLE prot_oggetti MODIFY COLUMN NOMEFILE VARCHAR(256);

ALTER TABLE prot_oggetti ADD COLUMN DIMENSIONE INT AFTER NOMEFILE, ADD COLUMN PERCORSO VARCHAR(512) AFTER DIMENSIONE, ADD COLUMN AGGIORNA DATETIME AFTER PERCORSO;

ALTER TABLE prot_oggetti CHANGE COLUMN DIMENSIONE DIMENSIONE_FILE DECIMAL(9,0) DEFAULT NULL;


ALTER TABLE prot_oggetti CHANGE COLUMN AGGIORNA AGGIORNA VARCHAR(20) DEFAULT NULL;

CREATE TABLE FO_RATING_MAIN (
    idComune VARCHAR(6) NOT NULL,
    id DECIMAL(6,0) NOT NULL,
    tipo VARCHAR(64) NOT NULL DEFAULT 'pagina',
    testo VARCHAR(256) NOT NULL,
    CONSTRAINT PK_FO_RATING_MAIN PRIMARY KEY (idComune, id),
    CONSTRAINT UQ_FO_RATING_MAIN_TIPO UNIQUE (idComune, tipo)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE FO_RATING_SUB_QUESTION (
    idComune VARCHAR(6) NOT NULL,
    id DECIMAL(6,0) NOT NULL,
    idRatingMain DECIMAL(6,0) NOT NULL,
    isPositive TINYINT(1) NOT NULL,
    testo VARCHAR(256) NOT NULL,
    CONSTRAINT PK_FO_RATING_SUB_QUESTION PRIMARY KEY (idComune, id),
    CONSTRAINT UQ_FO_RATING_SUB_QUESTION UNIQUE (idComune, idRatingMain, isPositive),
    FOREIGN KEY (idComune, idRatingMain)
        REFERENCES FO_RATING_MAIN(idComune, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE FO_RATING_CHOICE (
    idComune VARCHAR(6) NOT NULL,
    id DECIMAL(6,0) NOT NULL,
    idRatingSubQuestion DECIMAL(6,0) NOT NULL,
    testo VARCHAR(256) NOT NULL,
    ordine INT,
    PRIMARY KEY (idComune, id),
    FOREIGN KEY (idComune, idRatingSubQuestion)
        REFERENCES FO_RATING_SUB_QUESTION(idComune, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE FO_RATING_RESULT (
    idComune VARCHAR(6) NOT NULL,
    id DECIMAL(6,0) NOT NULL,
    identifier VARCHAR(64) NOT NULL,
    stars DECIMAL(6,0) NOT NULL,
    fkIdChoice DECIMAL(6,0) NOT NULL,
    ratingComment VARCHAR(512) NULL,
    CONSTRAINT PK_FO_RATING_RESULT PRIMARY KEY (idComune, id),
    CONSTRAINT FK_FO_RATING_RESULT_CHOICE FOREIGN KEY (idComune, fkIdChoice)
        REFERENCES FO_RATING_CHOICE(idComune, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE INDEX IDX_FO_RATING_RESULT_CHOICE ON FO_RATING_RESULT (idComune, fkIdChoice);

ALTER TABLE boll_cfg_tipo MODIFY SCADENZEPERIODI VARCHAR(100);

ALTER TABLE SORTEGGITESTATAINFO MODIFY VALORE VARCHAR(4000);


create table FO_DOMANDE_SSU (
IDCOMUNE varchar(6) NOT NULL,
ID DECIMAL(10,0) NOT NULL,
FK_IDDOMANDA decimal(6,0) NOT NULL,
CUI VARCHAR(64) NOT NULL,
NUMERO_DOMANDA_SSU VARCHAR(64) NOT NULL,
DATA_PRESENTAZIONE datetime not null,
ALIAS VARCHAR(10) NOT NULL,
STATO DECIMAL(3,0) NOT NULL,
CODICEOGGETTO_RICEVUTA decimal(10,0) NULL,
PRIMARY KEY (IDCOMUNE,ID),
CONSTRAINT FK_SSU_FO_DOMANDE FOREIGN KEY (IDCOMUNE,FK_IDDOMANDA) REFERENCES FO_DOMANDE (IDCOMUNE,ID),
CONSTRAINT FK_SSU_FO_OGG FOREIGN KEY (IDCOMUNE, CODICEOGGETTO_RICEVUTA) REFERENCES OGGETTI(IDCOMUNE, CODICEOGGETTO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

