SET IMPLICIT_TRANSACTIONS ON
GO
ALTER TABLE STP_TIPOLOGIE_ENDO2  ADD FKIDAZIONE NUMERIC(4, 0) 
GO
COMMIT
GO
ALTER TABLE STP_TIPOLOGIE_ENDO2  ADD CONSTRAINT FK_STP_TIPOL_ENDO2_AZIONI FOREIGN KEY (FKIDAZIONE) REFERENCES AZIONI(AZ_ID)
GO
COMMIT
GO
ALTER TABLE AMMINISTRAZIONI  ADD CODICE_CART VARCHAR(10)
GO
COMMIT
GO
ALTER TABLE AMMINISTRAZIONI ADD TIPOMOVIMENTO_CART VARCHAR(8) 
GO
COMMIT
GO
ALTER TABLE AMMINISTRAZIONI ADD CONSTRAINT FK_AMMINIST_TIPO_MOV_CART FOREIGN KEY (IDCOMUNE,TIPOMOVIMENTO_CART) REFERENCES TIPIMOVIMENTO(IDCOMUNE,TIPOMOVIMENTO)
GO
COMMIT
GO
CREATE TABLE STP_MODALITA_APERTURA 
(
  ID VARCHAR(100) NOT NULL, 
  DESCRIZIONE VARCHAR(200) NOT NULL,
  TIPO_SCHEDA VARCHAR(4)
)
GO
COMMIT
GO
ALTER TABLE STP_MODALITA_APERTURA ADD CONSTRAINT PK_STP_MOD_APERTURA PRIMARY KEY (ID)
GO
COMMIT
GO
ALTER TABLE NATURAENDO ADD FK_MOD_APERTURA_SCHEDA1 VARCHAR(100)
GO
COMMIT
GO
ALTER TABLE NATURAENDO ADD FK_MOD_APERTURA_SCHEDA2 VARCHAR(100)
GO
COMMIT
GO
ALTER TABLE NATURAENDO ADD CONSTRAINT FK_STP_MOD_APER_NATURA_ENDO2 FOREIGN KEY(FK_MOD_APERTURA_SCHEDA2) REFERENCES STP_MODALITA_APERTURA(ID)
GO
COMMIT
GO
ALTER TABLE NATURAENDO ADD CONSTRAINT FK_STP_MOD_APER_NATURA_ENDO1 FOREIGN KEY(FK_MOD_APERTURA_SCHEDA1) REFERENCES STP_MODALITA_APERTURA(ID) 
GO
COMMIT
GO
ALTER TABLE PROTOCOLLO_MODALITAINVIO ADD IDCOMUNE VARCHAR(6)
GO
COMMIT
GO
UPDATE PROTOCOLLO_MODALITAINVIO SET IDCOMUNE = ICOMUNE
GO
COMMIT
GO
ALTER TABLE PROTOCOLLO_MODALITAINVIO DROP PRIMARY KEY
GO
COMMIT
GO
ALTER TABLE PROTOCOLLO_MODALITAINVIO MODIFY (IDCOMUNE NOT NULL)
GO
COMMIT
GO
ALTER TABLE PROTOCOLLO_MODALITAINVIO ADD CONSTRAINT PK_PROTOCOLLO_MODALITAINVIO PRIMARY KEY (IDCOMUNE,CODICE)
GO
COMMIT
GO
ALTER TABLE PROTOCOLLO_MODALITAINVIO DROP COLUMN ICOMUNE
GO
COMMIT
GO
ALTER TABLE STP_ENDO_TIPO2 ADD FK_MODAPERTURAID VARCHAR(100)
GO
COMMIT
GO
ALTER TABLE STP_ENDO_TIPO2 ADD CONSTRAINT FK_STPMODAPERTURA_ID FOREIGN KEY(FK_MODAPERTURAID) REFERENCES STP_MODALITA_APERTURA(ID)
GO
COMMIT
GO
DROP VIEW VW_I_ATTIVITAAUTORIZZAZIONI
GO
COMMIT
GO
CREATE VIEW VW_I_ATTIVITAAUTORIZZAZIONI AS
SELECT
  I_ATTIVITA.ID                      AS I_IDATTIVITA,
  AUTORIZZAZIONI.AUTORIZNUMERO       AS AUTORIZNUMERO,
  AUTORIZZAZIONI.AUTORIZDATA         AS AUTORIZDATA,
  AUTORIZZAZIONI.AUTORIZDATAREGISTR  AS AUTORIZDATAREGISTR,
  AUTORIZZAZIONI.AUTORIZRESPONSABILE AS AUTORIZRESPONSABILE,
  AUTORIZZAZIONI.FKIDREGISTRO        AS FKIDREGISTRO,
  AUTORIZZAZIONI.FKIDISTANZA         AS FKIDISTANZA,
  AUTORIZZAZIONI.IDCOMUNE            AS IDCOMUNE,
  AUTORIZZAZIONI.CODICEMOVIMENTO     AS CODICEMOVIMENTO,
  AUTORIZZAZIONI.ID                  AS ID,
  AUTORIZZAZIONI.DATA_CESSAZIONE     AS DATA_CESSAZIONE 
FROM ((I_ATTIVITA
    JOIN AUTORIZZAZIONI)
   JOIN ISTANZE)
WHERE ((ISTANZE.IDCOMUNE = I_ATTIVITA.IDCOMUNE)
       AND (ISTANZE.FK_IDI_ATTIVITA = I_ATTIVITA.ID)
       AND (AUTORIZZAZIONI.IDCOMUNE = ISTANZE.IDCOMUNE)
       AND (AUTORIZZAZIONI.FKIDISTANZA = ISTANZE.CODICEISTANZA))
GO
COMMIT
GO
ALTER TABLE DOCUMENTIISTANZA ALTER COLUMN DOCUMENTO VARCHAR(4000) NOT NULL
GO
COMMIT
GO
ALTER TABLE MOVIMENTI ADD NUMPROT_MITTENTE VARCHAR(30)
GO
COMMIT
GO
ALTER TABLE MOVIMENTI ADD DATA_PROT_MITTENTE DATETIME
GO
COMMIT
GO
alter table TMP_ST_ONERI ALTER COLUMN  FK_RCO_ID NUMERIC(10)
GO
COMMIT
GO
alter table TMP_ST_ONERI ALTER COLUMN  FK_CO_ID NUMERIC(10)
GO
COMMIT
GO
ALTER TABLE ELENCHIPROFESSIONALIBASE ALTER COLUMN EP_DESCRIZIONE VARCHAR(50)
GO
COMMIT
GO
ALTER TABLE MERCATI ADD FLAG_CONSORZIO NUMERIC(1,0)
GO
COMMIT
GO
CREATE TABLE MERCATI_CONSORZI(
IDCOMUNE VARCHAR(6) NOT NULL,
ID NUMERIC(4,0) NOT NULL,
FK_CODICE_MERCATO NUMERIC(4,0) NOT NULL,
FK_ANAG_CONSORZIO NUMERIC(6,0) NOT NULL,
DATA_INIZIO_ESERCIZIO DATETIME,
DATA_FINE_ESERCIZIO DATETIME
)
GO
COMMIT
GO
ALTER TABLE MERCATI_CONSORZI ADD CONSTRAINT PK_MERCATICONSORZI PRIMARY KEY(IDCOMUNE, ID)
GO
COMMIT
GO
ALTER TABLE MERCATI_CONSORZI ADD CONSTRAINT FK_MERCATICONSORZI_MERC FOREIGN KEY (IDCOMUNE,FK_CODICE_MERCATO) REFERENCES MERCATI (IDCOMUNE,CODICEMERCATO)
GO
COMMIT
GO
ALTER TABLE MERCATI_CONSORZI ADD CONSTRAINT FK_MERCATICONSORZI_ANAG FOREIGN KEY (IDCOMUNE,FK_ANAG_CONSORZIO) REFERENCES ANAGRAFE (IDCOMUNE,CODICEANAGRAFE)
GO
COMMIT
GO
ALTER TABLE MERCATI_CONTI ADD FLAG_IMPORTOMENSILE NUMERIC(1,0)
GO
COMMIT
GO
ALTER TABLE MERCATI_CONTI ADD PERCENTUALE_CONSORZIO NUMERIC(5,2)
GO
COMMIT
GO
ALTER TABLE MERCATI_D_CONTI ADD FLAG_IMPORTOMENSILE NUMERIC(1,0)
GO
COMMIT
GO
ALTER TABLE MERCATI_D_CONTI ADD PERCENTUALE_CONSORZIO NUMERIC(5,2)
GO
COMMIT
GO
ALTER TABLE ELENCHIPROFESSIONALIBASE ADD EP_ATRIBCODICE NUMBER(4)
GO
COMMIT
GO
CREATE TABLE FO_ARJ_STEPS_TESTATA
(
    IDCOMUNE                       VARCHAR(6),
    ID                             NUMERIC(6,0),
    SOFTWARE                       VARCHAR(2),
    DESCRIZIONE                    VARCHAR(4000),
    CONSTRAINT FO_ARJ_STEPS_TESTATA_PK PRIMARY KEY (IDCOMUNE, ID),
    CONSTRAINT FK_FOARJSTEPSTESTATA_SOFTWARE FOREIGN KEY (SOFTWARE) REFERENCES SOFTWARE (CODICE)
) 
GO
COMMIT
GO

CREATE TABLE FO_ARJ_STEPS
(
    IDCOMUNE                       VARCHAR(6),
    ID                             NUMERIC(6,0),
    NOME                           VARCHAR(200),
    TITOLO                         VARCHAR(400),
    DESCRIZIONE                    VARCHAR(4000),
    ORDINE                         NUMERIC(2,0),
    ABILITATO                      NUMERIC(1,0),
      FK_FO_ARJ_STEPS_TESTATA      NUMERIC(6,0),
    CONSTRAINT FO_ARJ_STEPS_PK PRIMARY KEY (IDCOMUNE, ID) ,
    CONSTRAINT FK_FOARJSTEPS_FOARJSTEPSTESTA FOREIGN KEY (IDCOMUNE, FK_FO_ARJ_STEPS_TESTATA) REFERENCES FO_ARJ_STEPS_TESTATA (IDCOMUNE, ID) 
) 
GO
COMMIT
GO

CREATE TABLE FO_ARJ_STEPS_PARAMS
(
    IDCOMUNE                       VARCHAR(6),
    ID                             NUMERIC(6,0),
    CHIAVE                         VARCHAR(200),
    VALORE                         VARCHAR(400),
      FK_FO_ARJ_STEPS              NUMERIC(6,0),
    CONSTRAINT FO_ARJ_STEPS_PARAMS_PK PRIMARY KEY (IDCOMUNE, ID) ,
    CONSTRAINT FK_FOARJSTEPSPARAMS_FOARJSTEPS FOREIGN KEY (IDCOMUNE, FK_FO_ARJ_STEPS) REFERENCES FO_ARJ_STEPS (IDCOMUNE, ID) 
) 
GO
COMMIT
GO

CREATE TABLE FO_ARJ_DOMANDE
(
    IDCOMUNE                       VARCHAR(6),
    ID                             NUMERIC(6,0),
    SOFTWARE                       VARCHAR(2),
    CODICEANAGRAFE                 NUMERIC(6,0),
    CODICEOGGETTO                  NUMERIC(10,0),
    CODICEISTANZA                  NUMERIC(6,0),
    DATA_INVIO                     DATE,
    DATA_ULTIMA_MODIFICA           DATE,
    ID_DOMANDA                     VARCHAR(50),
    STEP                                 NUMERIC(2,0),
    CONSTRAINT FO_ARJ_DOMANDE_PK PRIMARY KEY (IDCOMUNE, ID) ,
    CONSTRAINT FK_FOARJDOMANDE_OGG FOREIGN KEY (IDCOMUNE, CODICEOGGETTO) REFERENCES OGGETTI (IDCOMUNE, CODICEOGGETTO) ,
    CONSTRAINT FK_FOARJDOMANDE_ANAGRAFE FOREIGN KEY (IDCOMUNE, CODICEANAGRAFE) REFERENCES ANAGRAFE (IDCOMUNE, CODICEANAGRAFE) ,
    CONSTRAINT FK_FOARJDOMANDE_SOFTWARE FOREIGN KEY (SOFTWARE) REFERENCES SOFTWARE (CODICE)
) 
GO
COMMIT
GO


ALTER TABLE FO_ARJ_DOMANDE ADD CODICEOGGETTO_RIEPILOGO NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE FO_ARJ_DOMANDE ADD CONSTRAINT FK_FOARJDOMANDE_OGGRIEPI_OGG FOREIGN KEY (IDCOMUNE, CODICEOGGETTO_RIEPILOGO) REFERENCES OGGETTI (IDCOMUNE, CODICEOGGETTO)
GO
COMMIT
GO
