ALTER TABLE I_ATTIVITADYN2MODELLIT ADD CONSTRAINT FK_IATTIVD2MT_002 FOREIGN KEY ( IDCOMUNE, FK_IA_ID ) REFERENCES I_ATTIVITA ( IDCOMUNE, ID );
ALTER TABLE I_ATTIVITADYN2DATI ADD CONSTRAINT FK_IATTIVD2D_001 FOREIGN KEY ( IDCOMUNE, FK_IA_ID ) REFERENCES I_ATTIVITA ( IDCOMUNE, ID );
ALTER TABLE I_ATTIVITADYN2DATI_STORICO ADD CONSTRAINT FK_IATTIVD2DSTORICO_002 FOREIGN KEY ( IDCOMUNE, FK_IA_ID ) REFERENCES I_ATTIVITA ( IDCOMUNE, ID );
ALTER TABLE I_ATTIVITADYN2MODELLIT_STORICO ADD CONSTRAINT FK_IATTIVD2MTSTORICO_001 FOREIGN KEY ( IDCOMUNE, FK_IA_ID ) REFERENCES I_ATTIVITA ( IDCOMUNE, ID );
ALTER TABLE AUTORIZZAZIONI MODIFY (AUTORIZNUMERO NOT NULL);
ALTER TABLE AUTORIZZAZIONI MODIFY (AUTORIZDATA NOT NULL);
ALTER TABLE AUTORIZZAZIONI MODIFY (FKIDREGISTRO NOT NULL);
ALTER TABLE AUTORIZZAZIONI MODIFY (AUTORIZCOMUNE NOT NULL);
ALTER TABLE ISTANZE DROP CONSTRAINT FK_ISTANZE_ISTCOLLEGATA;

ALTER TABLE TMP_CONTROMOVEFF MODIFY CODAMMRICHIEDENTERX NUMBER(10,0);
ALTER TABLE TMP_CONTROMOVEFF MODIFY CODAMMRICHIEDENTETX NUMBER(10,0);
ALTER TABLE TMP_CONTROMOVEFF MODIFY CODICEAMMINISTRAZIONERX NUMBER(10,0);
ALTER TABLE TMP_CONTROMOVEFF MODIFY CODICEAMMINISTRAZIONETX NUMBER(10,0);

ALTER TABLE MOVIMENTI MODIFY NOTE VARCHAR2(4000 CHAR);

ALTER TABLE TIPICAUSALIONERI drop constraint FK_TIPICAUSON_INTERESSI;
ALTER TABLE TIPICAUSALIONERI  MODIFY (FK_TIPICAUSALIINTERESSI NUMBER(10, 0) );
ALTER TABLE TIPICAUSALIONERI ADD CONSTRAINT FK_TIPICAUSON_INTERESSI FOREIGN KEY(IDCOMUNE, FK_TIPICAUSALIINTERESSI) REFERENCES TIPICAUSALIONERI(IDCOMUNE, CO_ID);

CREATE TABLE DOMANDESTC_ALLEGATI(
  IDCOMUNE VARCHAR2(6) NOT NULL,
  ID NUMBER(6,0) NOT NULL,
  FK_DOMANDASTC_ID NUMBER(6,0),
  CODICEOGGETTO NUMBER(10,0)
);

ALTER TABLE DOMANDESTC_ALLEGATI ADD CONSTRAINT PK_DOMANDESTCALLEGATI PRIMARY KEY (IDCOMUNE, ID);
ALTER TABLE DOMANDESTC_ALLEGATI ADD CONSTRAINT FK_DOMSTCALL_DOMSTC FOREIGN KEY (IDCOMUNE, FK_DOMANDASTC_ID) REFERENCES DOMANDESTC(IDCOMUNE, ID); 
ALTER TABLE DOMANDESTC_ALLEGATI ADD CONSTRAINT FK_DOMSTCALL_OGGETTI FOREIGN KEY (IDCOMUNE, CODICEOGGETTO) REFERENCES OGGETTI(IDCOMUNE, CODICEOGGETTO);

COMMENT ON TABLE DOMANDESTC_ALLEGATI IS 'Tabella degli allegati relativi ad una pratica STC';
COMMENT ON COLUMN DOMANDESTC_ALLEGATI.FK_DOMANDASTC_ID IS 'Chiave esterna verso Domandestc';
COMMENT ON COLUMN DOMANDESTC_ALLEGATI.CODICEOGGETTO IS 'Chiave esterna verso Oggetti';

CREATE OR REPLACE VIEW VW_LISTAPRATICHE (
  CODICECOMUNE,
  IDCOMUNE,
  SOFTWARE,
  DESCSOFTWARE,
  IDPRATICA,
  NUMEROPRATICA,
  DATAPRESENTAZIONE,
  ANNOPRESENTAZIONE,
  MESEPRESENTAZIONE,
  NUMEROPROTOCOLLO,
  DATAPROTOCOLLO,
  CODICEINTERVENTO,
  DESCRIZIONEINTERVENTO,
  CODICEPROCEDURA,
  PROCEDURA,
  OGGETTO,
  OGGETTOU,
  CODSTATOPRATICA,
  STATOPRATICA,
  RESPONSABILE,
  RESPONSABILE_TELEFONO,
  PR_CODVIARIO,
  PR_INDIRIZZO,
  PR_CODCIVICO,
  PR_CIVICO,
  CODICEZONIZZAZIONE,
  ZONIZZAZIONE,
  CODICERICHIEDENTE,
  CODICEFISCALE,
  PARTITAIVA,
  NOMINATIVO,
  INDIRIZZO,
  CAP,
  LOCALITA,
  CITTA,
  PROVINCIA,
  TIPORAPPORTO,
  TIPOCATASTO,
  FOGLIO,
  PARTICELLA,
  SUB,
  TEC_CODICE,
  TEC_NOMINATIVO,
  TEC_CODICEFISCALE,
  TEC_PARTITAIVA,
  AZ_CODICE,
  AZ_NOMINATIVO,
  AZ_CODICEFISCALE,
  AZ_PARTITAIVA,
  ISTRUTTORE,
  ISTRUTTORE_TELEFONO,
  OPERATORE,
  OPERATORE_TELEFONO
) AS
SELECT 
  ISTANZE.CODICECOMUNE,
  ISTANZE.IDCOMUNE, ISTANZE.SOFTWARE AS SOFTWARE,SOFTWARE.DESCRIZIONELUNGA AS DESCSOFTWARE,ISTANZE.CODICEISTANZA AS IDPRATICA,ISTANZE.NUMEROISTANZA AS NUMEROPRATICA, TO_CHAR(ISTANZE.DATA,'DD/MM/YYYY') AS DATAPRESENTAZIONE, TO_CHAR(ISTANZE.DATA,'YYYY') AS ANNOPRESENTAZIONE, TO_CHAR(ISTANZE.DATA,'MM') AS MESEPRESENTAZIONE, ISTANZE.NUMEROPROTOCOLLO, TO_CHAR(ISTANZE.DATAPROTOCOLLO,'DD/MM/YYYY') AS DATAPROTOCOLLO, ISTANZE.CODICEINTERVENTOPROC AS CODICEINTERVENTO, VW_ALBEROPROC.SC_DESCRIZIONE AS DESCRIZIONEINTERVENTO, TIPIPROCEDURE.CODICEPROCEDURA, TIPIPROCEDURE.PROCEDURA, ISTANZE.LAVORI AS OGGETTO, UPPER(ISTANZE.LAVORI) AS OGGETTOU, ISTANZE.CHIUSURA AS CODSTATOPRATICA, STATO AS STATOPRATICA, RESPONSABILI.RESPONSABILE, RESPONSABILI.TELEFONOLAVORO AS RESPONSABILE_TELEFONO, NVL(STRADARIO.CODVIARIO,STRADARIO.CODICESTRADARIO) AS PR_CODVIARIO, STRADARIO.PREFISSO || ' ' || STRADARIO.DESCRIZIONE AS PR_INDIRIZZO, ISTANZESTRADARIO.CODICECIVICO AS PR_CODCIVICO, ISTANZESTRADARIO.CIVICO AS PR_CIVICO, ISTANZE.CODICEAREA AS CODICEZONIZZAZIONE, AREE.DENOMINAZIONE AS ZONIZZAZIONE, ANAGRAFE.CODICEANAGRAFE AS CODICERICHIEDENTE, NVL(UPPER(ANAGRAFE.CODICEFISCALE), '') AS CODICEFISCALE, NVL(ANAGRAFE.PARTITAIVA, '') AS PARTITAIVA, ANAGRAFE.NOMINATIVO || ' ' || ANAGRAFE.NOME AS NOMINATIVO, ANAGRAFE.INDIRIZZO, ANAGRAFE.CAP, ANAGRAFE.CITTA AS LOCALITA, COMUNERESIDENZA.COMUNE AS CITTA, COMUNERESIDENZA.PROVINCIA, TIPISOGGETTO.TIPOSOGGETTO AS TIPORAPPORTO, CATASTO.DESCRIZIONE AS TIPOCATASTO, ISTANZEMAPPALI.FOGLIO, ISTANZEMAPPALI.PARTICELLA, ISTANZEMAPPALI.SUB, TECNICO.CODICEANAGRAFE AS TEC_CODICE, TECNICO.NOMINATIVO || ' ' || TECNICO.NOME AS TEC_NOMINATIVO, NVL(UPPER(TECNICO.CODICEFISCALE), '') AS TEC_CODICEFISCALE, NVL(TECNICO.PARTITAIVA, '') AS TEC_PARTITAIVA, AZIENDA.CODICEANAGRAFE AS AZ_CODICE , AZIENDA.NOMINATIVO || ' ' || AZIENDA.NOME AS AZ_NOMINATIVO, NVL(UPPER(AZIENDA.CODICEFISCALE), '') AS AZ_CODICEFISCALE, NVL(AZIENDA.PARTITAIVA, '') AS AZ_PARTITAIVA, ISTRUTTORI.RESPONSABILE AS ISTRUTTORE, ISTRUTTORI.TELEFONOLAVORO AS ISTRUTTORE_TELEFONO, OPERATORI.RESPONSABILE AS OPERATORE, OPERATORI.TELEFONOLAVORO AS OPERATORE_TELEFONO FROM ISTANZE JOIN SOFTWARE ON SOFTWARE.CODICE = ISTANZE.SOFTWARE JOIN ANAGRAFE ON ANAGRAFE.IDCOMUNE = ISTANZE.IDCOMUNE AND ANAGRAFE.CODICEANAGRAFE = ISTANZE.CODICERICHIEDENTE JOIN STATIISTANZA ON STATIISTANZA.IDCOMUNE = ISTANZE.IDCOMUNE AND STATIISTANZA.SOFTWARE = ISTANZE.SOFTWARE AND STATIISTANZA.CODICESTATO = ISTANZE.CHIUSURA JOIN VW_ALBEROPROC ON VW_ALBEROPROC.IDCOMUNE = ISTANZE.IDCOMUNE AND VW_ALBEROPROC.SC_ID = ISTANZE.CODICEINTERVENTOPROC LEFT OUTER JOIN ANAGRAFE TECNICO ON TECNICO.IDCOMUNE = ISTANZE.IDCOMUNE AND TECNICO.CODICEANAGRAFE = ISTANZE.CODICEPROFESSIONISTA LEFT OUTER JOIN ANAGRAFE AZIENDA ON ISTANZE.IDCOMUNE = AZIENDA.IDCOMUNE AND ISTANZE.CODICETITOLARELEGALE = AZIENDA.CODICEANAGRAFE LEFT OUTER JOIN ISTANZESTRADARIO ON ISTANZE.IDCOMUNE = ISTANZESTRADARIO.IDCOMUNE AND ISTANZE.CODICEISTANZA = ISTANZESTRADARIO.CODICEISTANZA AND 1 = ISTANZESTRADARIO.PRIMARIO LEFT OUTER JOIN STRADARIO ON STRADARIO.IDCOMUNE = ISTANZESTRADARIO.IDCOMUNE AND STRADARIO.CODICESTRADARIO = ISTANZESTRADARIO.CODICESTRADARIO LEFT OUTER JOIN ISTANZEMAPPALI ON ISTANZE.IDCOMUNE = ISTANZEMAPPALI.IDCOMUNE AND ISTANZE.CODICEISTANZA = ISTANZEMAPPALI.FKCODICEISTANZA AND 1 = ISTANZEMAPPALI.PRIMARIO LEFT OUTER JOIN RESPONSABILI ON ISTANZE.IDCOMUNE = RESPONSABILI.IDCOMUNE AND ISTANZE.CODICERESPONSABILEPROC = RESPONSABILI.CODICERESPONSABILE LEFT OUTER JOIN COMUNI COMUNERESIDENZA ON ANAGRAFE.COMUNERESIDENZA = COMUNERESIDENZA.CODICECOMUNE LEFT OUTER JOIN TIPISOGGETTO ON ISTANZE.IDCOMUNE = TIPISOGGETTO.IDCOMUNE AND ISTANZE.FKCODICESOGGETTO = TIPISOGGETTO.CODICETIPOSOGGETTO LEFT OUTER JOIN AREE ON ISTANZE.IDCOMUNE = AREE.IDCOMUNE AND ISTANZE.CODICEAREA = AREE.CODICEAREA LEFT OUTER JOIN CATASTO ON ISTANZEMAPPALI.CODICECATASTO = CATASTO.CODICE LEFT OUTER JOIN TIPIPROCEDURE ON ISTANZE.IDCOMUNE = TIPIPROCEDURE.IDCOMUNE AND ISTANZE.CODICEPROCEDURA = TIPIPROCEDURE.CODICEPROCEDURA LEFT OUTER JOIN RESPONSABILI ISTRUTTORI ON ISTANZE.IDCOMUNE = ISTRUTTORI.IDCOMUNE AND ISTANZE.CODICEISTRUTTORE = ISTRUTTORI.CODICERESPONSABILE LEFT OUTER JOIN RESPONSABILI OPERATORI ON OPERATORI.IDCOMUNE = ISTANZE.IDCOMUNE AND OPERATORI.CODICERESPONSABILE = ISTANZE.CODICERESPONSABILE;

CREATE INDEX IDX_ANAGRAFE_008 ON ANAGRAFE(IDCOMUNE,TIPOANAGRAFE);

ALTER TABLE FO_DOMANDE ADD (CODICEOGGETTO_CART NUMBER(10, 0) );

ALTER TABLE FO_DOMANDE ADD CONSTRAINT FK_FO_DOMANDE_OGGETTI FOREIGN KEY (IDCOMUNE,CODICEOGGETTO_CART) REFERENCES OGGETTI (IDCOMUNE,CODICEOGGETTO);

ALTER TABLE LEGGI MODIFY LE_DESCRIZIONE VARCHAR2(200 CHAR);

ALTER TABLE MOVIMENTI MODIFY (NOTE VARCHAR2(4000 CHAR) );

UPDATE verticalizzazioniparametri SET VALORE = VALORE || '/stc?wsdl' WHERE PARAMETRO = 'STC_WS_URL' and VALORE like '%services';

ALTER TABLE ALBEROPROC_DOCUMENTICAT MODIFY ID NUMBER(10);

ALTER TABLE ALBEROPROC_DOCUMENTI MODIFY FKIDCATEGORIA NUMBER(10);

ALTER TABLE TIPIMODALITAPAGAMENTO MODIFY MP_ID NUMBER(10); 

ALTER TABLE ISTANZEONERI MODIFY FKMODALITAPAGAMENTO NUMBER(10);

ALTER TABLE ALBEROPROC ADD CONSTRAINT FK_ALBERO_PROC_PROT_TIPI_DOC FOREIGN KEY(IDCOMUNE, SC_PROTTIPODOCUMENTO) REFERENCES PROTOCOLLO_TIPIDOCUMENTO (IDCOMUNE, CODICE);

update comuni set codiceistat = '0' || codiceistat where codicestatoestero is null and length(codiceistat) = 5;

ALTER TABLE CONFIGURAZIONE MODIFY CODAMMSPORTELLOUNICO NUMBER(10,0);

ALTER TABLE CONFIGURAZIONE MODIFY CODICELASTESSAAMMINISTRAZIONE NUMBER(10,0);

ALTER TABLE CONFIGURAZIONE MODIFY CODICETUTTEAMMINISTRAZIONI NUMBER(10,0);

ALTER TABLE ALBEROPROC ADD CODICEOPERATORE_STC NUMBER(4,0);
COMMENT ON COLUMN ALBEROPROC.CODICEOPERATORE_STC IS 'CODICE OPERATORE DA ASSOCIARE DI DEFAULT DURANTE UN''INSERIMENTO ISTANZA PROVENIENTE DA STC';
ALTER TABLE ALBEROPROC ADD CONSTRAINT FK_ALBEROPROC_OPESTC FOREIGN KEY (IDCOMUNE,CODICEOPERATORE_STC ) REFERENCES RESPONSABILI (IDCOMUNE, CODICERESPONSABILE);

ALTER TABLE ALLEGATI ADD NOTE_FRONTEND VARCHAR2(4000 CHAR);
COMMENT ON COLUMN ALLEGATI.NOTE_FRONTEND IS 'NOTE CHE SERVONO A SPECIFICARE MEGLIO COSA È RICHIESTO IN ALLEGATO AL RICHIEDENTE DI FRONTEND';
ALTER TABLE ALBEROPROC_DOCUMENTI ADD NOTE_FRONTEND VARCHAR2(4000 CHAR);
COMMENT ON COLUMN ALBEROPROC_DOCUMENTI.NOTE_FRONTEND IS 'NOTE CHE SERVONO A SPECIFICARE MEGLIO COSA È RICHIESTO IN ALLEGATO AL RICHIEDENTE DI FRONTEND';
ALTER TABLE TIPIPROCEDURE_DOCUMENTI ADD NOTE_FRONTEND VARCHAR2(4000 CHAR);
COMMENT ON COLUMN TIPIPROCEDURE_DOCUMENTI.NOTE_FRONTEND IS 'NOTE CHE SERVONO A SPECIFICARE MEGLIO COSA È RICHIESTO IN ALLEGATO AL RICHIEDENTE DI FRONTEND';

ALTER TABLE MOVIMENTI ADD CODICEOGGETTO_NOTIFICA NUMBER(10,0);
ALTER TABLE MOVIMENTI ADD CONSTRAINT FK_OGGETTI_MOV_NOTSTC FOREIGN KEY (IDCOMUNE,CODICEOGGETTO_NOTIFICA) REFERENCES OGGETTI (IDCOMUNE,CODICEOGGETTO);
COMMENT ON COLUMN MOVIMENTI.CODICEOGGETTO_NOTIFICA IS 'RIFERIMENTO ALL''XML INVIATO DURANTE LA NOTIFICA STC';

ALTER TABLE ISTANZE_TEMPISTICA ADD DATAFINEEFFETTIVA DATE;
COMMENT ON COLUMN ISTANZE_TEMPISTICA.DATAFINEEFFETTIVA IS 'LA DATA DI CHIUSURA DEI TEMPI DEL PRODEDIMENTO INDICATA DALLA DATA DEL MOVIMENTO DI CHIUSURA (PROCEDURA.IDCHIUSURAISTANZA)';
ALTER TABLE ISTANZE_TEMPISTICA ADD GGAGGIUNTIVI NUMBER(4,0);
COMMENT ON COLUMN ISTANZE_TEMPISTICA.GGAGGIUNTIVI IS 'E'' LA SOMMATORIA DI EVENTUALI PROROGHE E SOSPENSIONI. IL DETTAGLIO DI OGNI SINGOLA PROROGA E SOSPENSIONE È NELLA TABELLA MOVIMENTI_TEMPISTICA';

ALTER TABLE TIPIPROCEDURE ADD FLAG_DISABILITATO NUMBER(1,0); 
ALTER TABLE AMMINISTRAZIONI ADD FLAG_DISABILITATO NUMBER(1,0); 
ALTER TABLE TIPIMOVIMENTO ADD FLAG_DISABILITATO NUMBER(1,0);
ALTER TABLE LETTERETIPO ADD FLAG_DISABILITATO NUMBER(1,0);
COMMENT ON COLUMN TIPIPROCEDURE.FLAG_DISABILITATO IS 'SE 1 ALLORA IL RECORD È DA CONSIDERARSI DISABILITATO'; 
COMMENT ON COLUMN AMMINISTRAZIONI.FLAG_DISABILITATO IS 'SE 1 ALLORA IL RECORD È DA CONSIDERARSI DISABILITATO'; 
COMMENT ON COLUMN TIPIMOVIMENTO.FLAG_DISABILITATO IS 'SE 1 ALLORA IL RECORD È DA CONSIDERARSI DISABILITATO'; 
COMMENT ON COLUMN LETTERETIPO.FLAG_DISABILITATO IS 'SE 1 ALLORA IL RECORD È DA CONSIDERARSI DISABILITATO';

ALTER TABLE TIPIPROCEDURE_DOCUMENTI ADD (PUBBLICA NUMBER(1,0) NULL,RICHIESTO NUMBER(1,0) NULL,FO_RICHIEDEFIRMA NUMBER(1,0) NULL,FO_TIPODOWNLOAD VARCHAR2(30 CHAR) NULL);

ALTER TABLE ANAGRAFE MODIFY (PARTITAIVA VARCHAR2(32 CHAR) );

ALTER TABLE ANAGRAFE MODIFY (CODICEFISCALE VARCHAR2(32 CHAR) );

ALTER TABLE ANAGRAFESTORICO MODIFY (PARTITAIVA VARCHAR2(32 CHAR) );

ALTER TABLE ANAGRAFESTORICO MODIFY (CODICEFISCALE VARCHAR2(32 CHAR) );

ALTER TABLE DOMANDESTC MODIFY (CODICEFISCALE_RICHIEDENTE VARCHAR2(32 CHAR) );

ALTER TABLE ISTANZEFIDEJUSSIONI  MODIFY (FK_RCO_ID NUMBER(10, 0) );

ALTER TABLE STP_ENDO_TIPO1 ADD CODICE_ENDO_REGIONALE VARCHAR2(20 CHAR);

CREATE OR REPLACE VIEW VW_MERCATIPRESENZETOTALI AS
SELECT 'STORICO' AS ORIGINE, MERCATIPRESENZE_STORICO.IDCOMUNE, MERCATIPRESENZE_STORICO.ANNO, MERCATIPRESENZE_STORICO.CODICEANAGRAFE, MERCATIPRESENZE_STORICO.FK_AUTORIZZAZIONI_ID, MERCATIPRESENZE_STORICO.FKCODICEMERCATO, MERCATIPRESENZE_STORICO.FKIDMERCATIUSO, MERCATIPRESENZE_STORICO.FK_IDPOSTEGGIO AS FKIDPOSTEGGIO,  MERCATIPRESENZE_STORICO.NUMEROPRESENZE, TRIM( ANAGRAFE.NOMINATIVO || ' ' || ANAGRAFE.NOME ) AS ANAGRAFE, ANAGRAFE.CODICEFISCALE, ANAGRAFE.PARTITAIVA, COMUNI.COMUNE AS COMUNERESIDENZA, CITTADINANZA.CITTADINANZA, TO_CHAR(ANAGRAFE.DATAREGDITTE, 'DD/MM/YYYY' ) AS DATAREGDITTE FROM MERCATIPRESENZE_STORICO, ANAGRAFE, COMUNI, CITTADINANZA WHERE ANAGRAFE.IDCOMUNE = MERCATIPRESENZE_STORICO.IDCOMUNE AND ANAGRAFE.CODICEANAGRAFE = MERCATIPRESENZE_STORICO.CODICEANAGRAFE AND COMUNI.CODICECOMUNE(+) = ANAGRAFE.COMUNERESIDENZA AND CITTADINANZA.CODICE(+) = ANAGRAFE.CODICECITTADINANZA
UNION ALL 
SELECT 'CALENDARIO' AS ORIGINE, MERCATIPRESENZE_T.IDCOMUNE, MERCATIPRESENZE_T.ANNO, MERCATIPRESENZE_D.CODICEANAGRAFE, MERCATIPRESENZE_D.FK_AUTORIZZAZIONI_ID, MERCATIPRESENZE_T.FKCODICEMERCATO, MERCATIPRESENZE_T.FKIDMERCATIUSO, MERCATIPRESENZE_D.FKIDPOSTEGGIO, 1 AS NUMEROPRESENZE, TRIM( ANAGRAFE.NOMINATIVO || ' ' || ANAGRAFE.NOME ) AS ANAGRAFE, ANAGRAFE.CODICEFISCALE, ANAGRAFE.PARTITAIVA, COMUNI.COMUNE AS COMUNERESIDENZA, CITTADINANZA.CITTADINANZA, TO_CHAR(ANAGRAFE.DATAREGDITTE, 'DD/MM/YYYY' ) AS DATAREGDITTE FROM MERCATIPRESENZE_T, MERCATIPRESENZE_D, ANAGRAFE, COMUNI, CITTADINANZA WHERE ANAGRAFE.IDCOMUNE = MERCATIPRESENZE_D.IDCOMUNE AND ANAGRAFE.CODICEANAGRAFE = MERCATIPRESENZE_D.CODICEANAGRAFE AND COMUNI.CODICECOMUNE(+) = ANAGRAFE.COMUNERESIDENZA AND CITTADINANZA.CODICE(+) = ANAGRAFE.CODICECITTADINANZA AND MERCATIPRESENZE_D.IDCOMUNE = MERCATIPRESENZE_T.IDCOMUNE AND MERCATIPRESENZE_D.FKIDTESTATA = MERCATIPRESENZE_T.ID;

CREATE OR REPLACE VIEW VW_CONCESSIONILISTA AS SELECT IDCOMUNE, SOFTWARE, PROGRESSIVO, CONC_ID, CONC_NUMERO, CONC_DATARILASCIO, CONC_DATASCADENZA, CONC_CODICETIPO, CONC_TIPO, CONC_STAGIONALEA, CONC_STAGIONALEDA, CONC_ATTIVA, CONC_CODICETITOLARE, CONC_TITOLARE, CONC_TIT_CF, CONC_TIT_PIVA, CONC_TIT_TIPOANAGRAFE, AUT_NUMERO, AUT_DATA, AUT_CODREGISTRO, AUT_REGISTRO, IST_CODICEISTANZA, IST_NUMEROISTANZA, IST_CODICERICHIEDENTE, IST_NOMINATIVO, IST_CODICEFISCALE, IST_PARTITAIVA, IST_RIC_TIPOANAGRAFE, ICONC_CODICECAUSALE, ICONC_CAUSALE, ICONC_CODICECAUSALESTORICO, ICONC_CAUSALESTORICO, CONC_IDMERCATO, CONC_MERCATO, MERC_ATTIVO, CONC_IDPOSTEGGIO, CONC_POSTEGGIO, CONC_POS_LARGHEZZA, CONC_POS_LUNGHEZZA, CONC_POS_SUPERFICIE, POST_IDTIPOSPAZIO, POST_TIPOSPAZIO, CONC_IDMERCATIUSO, CONC_DESCRIZIONEUSO, PESO_MERCATO, MERC_IDUSO, CONC_POS_CODICESTRADARIO, DATA_STORICO FROM VW_ISTANZECONCESSIONILISTA;


CREATE TABLE PROTOCOLLO_MEZZI
(
  IDCOMUNE VARCHAR2(6) NOT NULL
, CODICE VARCHAR2(50) NOT NULL
, DESCRIZIONE VARCHAR2(100) NOT NULL
); 

ALTER TABLE PROTOCOLLO_MEZZI ADD CONSTRAINT PROTOCOLLO_MEZZI_PK PRIMARY KEY (IDCOMUNE,CODICE);

CREATE TABLE RI_CARICHE(
CODICE VARCHAR2(5 CHAR) NOT NULL,
DESCRIZIONE VARCHAR2(150 CHAR)
);
ALTER TABLE RI_CARICHE ADD CONSTRAINT RI_CARICHE_PK PRIMARY KEY(CODICE);
ALTER TABLE TIPISOGGETTO ADD FK_RICA_CODICE VARCHAR2(5 CHAR);

ALTER TABLE TIPISOGGETTO ADD CONSTRAINT FK_TIPISOGG_RICARI FOREIGN KEY (FK_RICA_CODICE ) REFERENCES RI_CARICHE(CODICE);

CREATE TABLE RI_FORMEGIURIDICHE (
CODICE VARCHAR2(5 CHAR),
DESCRIZIONE VARCHAR2(150 CHAR)
);
COMMENT ON TABLE RI_FORMEGIURIDICHE IS 'TABELLA CHE CONTIENE LE INFORMAZIONI DELLE FORMEGIURIDICHE COME CATALOGATE DA REGISTRO IMPRESE. IL RIFERIMENTO VA SALVATO NEL CAMPO FORMEGIURIDICHE.CODICECCIAA';
ALTER TABLE RI_FORMEGIURIDICHE ADD CONSTRAINT RI_FORMEGIURIDICHE_PK PRIMARY KEY (CODICE);

CREATE TABLE ISTANZE_RI (
IDCOMUNE VARCHAR2(6 CHAR) NOT NULL,
ID NUMBER(9,0) NOT NULL,
CODICEISTANZA NUMBER(6,0),
UFFICIORI VARCHAR2(2),
DATAPROTOCOLLORI VARCHAR2(10),
NUMEROPROTOCOLLORI VARCHAR2(50),
ANNO VARCHAR2(4)
);

COMMENT ON TABLE ISTANZE_RI IS 'TABELLA CHE CONTIENE I RIFERIMENTI AL PROTOCOLLO RILASCIATO DA REGISTRO IMPRESE'; 
COMMENT ON COLUMN ISTANZE_RI.UFFICIORI IS 'SIGLA DELLA PROVINCIA DELLA CAMERA COMPETENTE PER LA PRATICA'; 
COMMENT ON COLUMN ISTANZE_RI.NUMEROPROTOCOLLORI IS 'NUMERO DEL PROTOCOLLO RILASCIATO DA REGISTRO IMPRESE'; 
COMMENT ON COLUMN ISTANZE_RI.DATAPROTOCOLLORI IS 'DATA DEL PROTOCOLLO RILASCIATO DA REGISTRO IMPRESE'; 
COMMENT ON COLUMN ISTANZE_RI.ANNO IS 'ANNO DEL PROTOCOLLO RILASCIATO DA REGISTRO IMPRESE';

ALTER TABLE ISTANZE_RI ADD CONSTRAINT ISTANZE_RI_PK PRIMARY KEY (IDCOMUNE, ID); 
ALTER TABLE ISTANZE_RI ADD CONSTRAINT FK_ISTRI_ISTANZE FOREIGN KEY (IDCOMUNE, CODICEISTANZA) REFERENCES ISTANZE(IDCOMUNE, CODICEISTANZA);

CREATE INDEX IDX_ISTANZE_RI_001 ON ISTANZE_RI (IDCOMUNE, CODICEISTANZA);

CREATE TABLE I_ATTIVITA_SNAPSHOT
  (
    IDCOMUNE            VARCHAR2(6) NOT NULL,
    ID                 NUMBER(6,0) NOT NULL,
    DENOMINAZIONE       VARCHAR2(150 CHAR),
    CODICEISTANZAULTIMA NUMBER(6,0),
    NUMEROPRESENZE      NUMBER(4,0),
    ATTIVA              NUMBER(1,0),
    OPERANTE            NUMBER(1,0),
    DATA                DATE,
    FK_IA_ID            NUMBER(6,0) NOT NULL
);
  
ALTER TABLE I_ATTIVITA_SNAPSHOT ADD CONSTRAINT PK_SNAPSHOT PRIMARY KEY (IDCOMUNE,ID); 
ALTER TABLE I_ATTIVITA_SNAPSHOT ADD CONSTRAINT FK_IATTIVITA_SNAPSHOT_ISTANZE FOREIGN KEY (IDCOMUNE, CODICEISTANZAULTIMA)  REFERENCES ISTANZE (IDCOMUNE, CODICEISTANZA);
ALTER TABLE I_ATTIVITA_SNAPSHOT ADD CONSTRAINT FK_IATTIVITA_SNAPSHOT_ATTIVITA FOREIGN KEY (IDCOMUNE, FK_IA_ID) REFERENCES I_ATTIVITA(IDCOMUNE, ID);

CREATE TABLE I_ATTIVITADYN2MOD_T_SNAPSHOT
(
  IDCOMUNE   VARCHAR2(6) NOT NULL,
  FK_D2MT_ID NUMBER(10,0)     NOT NULL,
  FK_IA_ID   NUMBER(6,0)      NOT NULL,
  FK_IAS_ID  NUMBER(6,0)      NOT NULL
);
  
ALTER TABLE I_ATTIVITADYN2MOD_T_SNAPSHOT ADD CONSTRAINT I_ATTIVITADYN2M_T_SNAPSHOT_PK PRIMARY KEY (IDCOMUNE, FK_D2MT_ID, FK_IA_ID,FK_IAS_ID);
ALTER TABLE I_ATTIVITADYN2MOD_T_SNAPSHOT ADD CONSTRAINT FK_IATTDYNMOD_T_SNAP_DYN_MOD_T FOREIGN KEY (IDCOMUNE, FK_D2MT_ID)   REFERENCES DYN2_MODELLIT (IDCOMUNE, ID);
ALTER TABLE I_ATTIVITADYN2MOD_T_SNAPSHOT ADD CONSTRAINT FK_IATT_DYNMOD_T_SNAP_I_ATT FOREIGN KEY (IDCOMUNE, FK_IA_ID) REFERENCES I_ATTIVITA (IDCOMUNE, ID);
ALTER TABLE I_ATTIVITADYN2MOD_T_SNAPSHOT ADD CONSTRAINT FK_IATT_DYNMODT_SNAP_IATT_S FOREIGN KEY (IDCOMUNE, FK_IAS_ID) REFERENCES I_ATTIVITA_SNAPSHOT (IDCOMUNE, ID);

CREATE TABLE I_ATTIVITADYN2DATI_SNAPSHOT 
  (
    IDCOMUNE  VARCHAR2(6) NOT NULL,
    FK_IA_ID  NUMBER(6,0) NOT NULL,
    FK_D2C_ID NUMBER(10,0) NOT NULL,
    FK_IAS_ID NUMBER(6,0) NOT NULL,
    INDICE NUMBER(2,0) NOT NULL,
    INDICE_MOLTEPLICITA NUMBER(2,0) NOT NULL,
    VALORE CLOB,
    VALOREDECODIFICATO CLOB
  );  
   
ALTER TABLE I_ATTIVITADYN2DATI_SNAPSHOT ADD CONSTRAINT I_ATTIVITADYN2DATI_SNAPSHOT_PK PRIMARY KEY (IDCOMUNE, FK_IA_ID, FK_D2C_ID,FK_IAS_ID, INDICE, INDICE_MOLTEPLICITA); 
ALTER TABLE I_ATTIVITADYN2DATI_SNAPSHOT ADD CONSTRAINT FK_IATTIVADYN2_DATI_S_DYN2C FOREIGN KEY (IDCOMUNE, FK_D2C_ID) REFERENCES DYN2_CAMPI (IDCOMUNE, ID);
ALTER TABLE I_ATTIVITADYN2DATI_SNAPSHOT ADD CONSTRAINT FK_IATTIVADYN2_DATI_S_I_ATT FOREIGN KEY (IDCOMUNE, FK_IA_ID) REFERENCES I_ATTIVITA (IDCOMUNE, ID);
ALTER TABLE I_ATTIVITADYN2DATI_SNAPSHOT ADD CONSTRAINT FK_IATT_DYN2_DATI_S_I_ATT_S FOREIGN KEY (IDCOMUNE, FK_IAS_ID) REFERENCES I_ATTIVITA_SNAPSHOT (IDCOMUNE, ID);

CREATE TABLE FO_MOVIMENTI 
(
  IDCOMUNE VARCHAR2(6) NOT NULL 
, CODMOVORIG NUMBER(8, 0) NOT NULL 
, TIPOMOVDAFARE VARCHAR2(8) NOT NULL 
, DATI CLOB NOT NULL 
, TRASMESSO NUMBER(1, 0)
);

ALTER TABLE FO_MOVIMENTI ADD CONSTRAINT FO_MOVIMENTI_PK PRIMARY KEY (IDCOMUNE,CODMOVORIG,TIPOMOVDAFARE );

ALTER TABLE CONFIGURAZIONE ADD CODICEAMMINISTRAZIONE_IPA VARCHAR2(20);
ALTER TABLE CONFIGURAZIONE ADD CODICE_AOO VARCHAR2(20);

COMMENT ON COLUMN CONFIGURAZIONE.CODICEAMMINISTRAZIONE_IPA IS 'Codice amministrazione definita nell''indice delle pubbliche amministrazioni (IPA), al momento utilizzato nelle comunicazioni con Registro imprese per identificare l''amministrazione comunale mittente. Ve definito solamente nel software TT';
COMMENT ON COLUMN CONFIGURAZIONE.CODICE_AOO IS 'Codice Area Omogenea Organizzativa (Con l''acronimo AOO sono identificati gli uffici di protocollo delle Amministrazioni che gestiscono i flussi documentali in entrata e in uscita dall''Amministrazione). Serve per identificare il relativo codice nelle comunicazioni verso enti esterni. Ve definito solamente per ogni software ad eccezione di TT. Al momento viene utilizzato nella comunicazione con registro imprese.';

DROP INDEX IDX_DYN2_CAMPI_001;
ALTER TABLE DYN2_CAMPI MODIFY NOMECAMPO VARCHAR2(255 BYTE);
CREATE UNIQUE INDEX IDX_DYN2_CAMPI_001 ON DYN2_CAMPI (IDCOMUNE,SOFTWARE,NOMECAMPO);

CREATE TABLE ALBEROPROC_D2MODTATT
  (
    IDCOMUNE         VARCHAR2(6 BYTE) NOT NULL,
    FK_SC_ID             NUMBER(10,0) NOT NULL,
    FK_D2MT_ID       NUMBER(10,0) NOT NULL
  );

ALTER TABLE ALBEROPROC_D2MODTATT ADD CONSTRAINT ALBEROPROC_D2MODTATT_PK PRIMARY KEY (IDCOMUNE,FK_SC_ID,FK_D2MT_ID); 
ALTER TABLE ALBEROPROC_D2MODTATT ADD CONSTRAINT FK_ALBEROPROC_D2MODTATT_D2MT FOREIGN KEY (IDCOMUNE,FK_D2MT_ID) REFERENCES DYN2_MODELLIT (IDCOMUNE, ID);
ALTER TABLE ALBEROPROC_D2MODTATT ADD CONSTRAINT FK_ALBEROP_D2MODTATT_ALBPROC FOREIGN KEY (IDCOMUNE, FK_SC_ID) REFERENCES ALBEROPROC (IDCOMUNE,SC_ID);


ALTER TABLE PROT_GENERALE ADD PG_INDIRIZZOMITTENTE VARCHAR2(4000) ;
ALTER TABLE PROT_GENERALE ADD PG_INDIRIZZOPERCONTODI VARCHAR2(4000);
ALTER TABLE PROT_GENERALE ADD PG_INDIRIZZODESTINATARIO VARCHAR2(4000);

ALTER TABLE PROT_ALTRIDESTINATARI ADD AD_INDIRIZZO VARCHAR2(4000);

CREATE TABLE PROTOCOLLO_UFFICIREGISTRI (CODICEREGISTRO VARCHAR2(10) NOT NULL, CODICEUFFICIO VARCHAR2(10) NOT NULL, IDCOMUNE VARCHAR2(6) NOT NULL);
ALTER TABLE PROTOCOLLO_UFFICIREGISTRI ADD CONSTRAINT PROTOCOLLO_UFFICIREGISTRI_PK PRIMARY KEY (CODICEREGISTRO,IDCOMUNE);

COMMENT ON TABLE PROTOCOLLO_UFFICIREGISTRI IS 'Questa tabella serve per recuperare il valore del codice ufficio (campo CODICEUFFICIO) responsabile del registro (CAMPO CODICEREGISTRO) nel protocollo di INSIEL MERCATO ed eventualmente INSIEL (che però ha un web service apposito quindi non è obbligatorio usare questa tabella). E'' una tabella non gestita da VBG che deve essere valorizzata direttamente da database, i dati devono essere comunicati dai proprietari del protocollo di INSIEL MERCATO (O INSIEL). Il codice registro viene inserito nella tabella AMMINISTRAZIONI.PROT_UO'' che viene usato come filtro (oltre a idcomune) durante il processo di protocollazione del protocollo insiel mercato recuperando quindi il valore del codice ufficio che è obbligatorio.';

CREATE TABLE OGGETTI_METADATI (
	IDCOMUNE VARCHAR2(6) NOT NULL,	
	CODICEOGGETTO NUMBER(10,0) NOT NULL,
	CHIAVE VARCHAR2(100) NOT NULL,
	VALORE VARCHAR2(4000)
);

ALTER TABLE OGGETTI_METADATI ADD CONSTRAINT PK_OGGETTI_METADATI PRIMARY KEY(IDCOMUNE,CODICEOGGETTO, CHIAVE);
ALTER TABLE OGGETTI_METADATI ADD CONSTRAINT FK_OGGETTI_METADATI FOREIGN KEY (IDCOMUNE, CODICEOGGETTO) REFERENCES OGGETTI (IDCOMUNE,CODICEOGGETTO);
COMMENT ON COLUMN OGGETTI_METADATI.CODICEOGGETTO IS 'CHIAVE ESTERNA VERSO LA TABELLA OGGETTI'; 
COMMENT ON COLUMN OGGETTI_METADATI.CHIAVE IS 'NOME O CHIAVE DEL METADATO'; 
COMMENT ON COLUMN OGGETTI_METADATI.VALORE IS 'VALORE DEL METADATO';

CREATE TABLE PROTOCOLLO_MODALITAINVIO(ICOMUNE VARCHAR2(6) NOT NULL, CODICE VARCHAR2(30) NOT NULL, DESCRIZIONE VARCHAR2(300) NOT NULL);
ALTER TABLE PROTOCOLLO_MODALITAINVIO ADD CONSTRAINT PROTOCOLLO_MODALITAINVIO_PK PRIMARY KEY (ICOMUNE,CODICE);
COMMENT ON TABLE PROTOCOLLO_MODALITAINVIO IS 'Contiene i dati relativi alla modalità di invio del protocollo, ad esempio: Per Conoscenza, Forma Diretta, Per Sottocopia....E'' una funzionalità strettamente relativa al protocollo, in particolare questi dati vengono visualizzati sull''interfaccia di protocollazione dentro una dropdownlist di fianco alle amministrazioni / anagrafiche mittente per i protocolli in arrivo, amministrazioni / anagrafiche destinatari per i protocolli in partenza. Se questa tabella non è valorizzata i dropdownlist non saranno visualizzati. La richiesta è stata fatta dal Comune di Trieste.';

ALTER TABLE MAPPATURE MODIFY ID NUMBER(10,0);
ALTER TABLE TIPIMOV_STC_MAPPING MODIFY ID NUMBER(10,0);
ALTER TABLE TIPIMOV_STC_ALBEROPROC MODIFY ID NUMBER(10,0);
ALTER TABLE TIPIMOV_STC_ALTRIDATI MODIFY ID NUMBER(10,0);
ALTER TABLE TIPIMOV_STC_MODELLI MODIFY ID NUMBER(10,0);


ALTER TABLE TIPISOGGETTO ADD ATRIB_QUALIFICASOGGETTO NUMBER(1,0);
ALTER TABLE TIPIPROCEDURE ADD ATRIB_TIPORICHIESTA NUMBER(1,0);
ALTER TABLE COMUNIASSOCIATI ADD CODICEAMMINISTRAZIONE_IPA VARCHAR2(20);
ALTER TABLE COMUNIASSOCIATI ADD CODICEFISCALE VARCHAR2(11);
ALTER TABLE COMUNIASSOCIATISOFTWARE ADD CODICE_ACCREDITAMENTO VARCHAR2(30);
ALTER TABLE COMUNIASSOCIATISOFTWARE ADD CODICE_AOO VARCHAR2(20);

COMMENT ON COLUMN TIPISOGGETTO.ATRIB_QUALIFICASOGGETTO IS 'Codice della qualifica del soggetto attribuita dall''anagrafe tributaria in fase di invio dati';
COMMENT ON COLUMN TIPIPROCEDURE.ATRIB_TIPORICHIESTA IS 'Codice della tipologia di richiesta attribuita dall''anagrafe tributaria in fase di invio dati';
COMMENT ON COLUMN COMUNIASSOCIATI.CODICEAMMINISTRAZIONE_IPA IS 'Codice amministrazione definita nell''indice delle pubbliche amministrazioni (IPA), al momento utilizzato nelle comunicazioni con Registro imprese per identificare l''amministrazione comunale mittente. Ve definito solamente nel software TT ';
COMMENT ON COLUMN COMUNIASSOCIATI.CODICEFISCALE IS 'Codice fiscale o partita iva dell''ente';
COMMENT ON COLUMN COMUNIASSOCIATISOFTWARE.CODICE_ACCREDITAMENTO IS 'Contiene il codice accreditamento dello sportello';
COMMENT ON COLUMN COMUNIASSOCIATISOFTWARE.CODICE_AOO IS 'Codice Area Omogenea Organizzativa (Con l''acronimo AOO sono identificati gli uffici di protocollo delle Amministrazioni che gestiscono i flussi documentali in entrata e in uscita dall''Amministrazione). Serve per identificare il relativo codice nelle comunicazioni verso enti esterni. Ve definito solamente per ogni software ad eccezione di TT. Al momento viene utilizzato nella comunicazione con registro imprese. ';


CREATE TABLE RI_TIPIINTERVENTO(
CODICE VARCHAR2(20) NOT NULL,
DESCRIZIONE VARCHAR2(150)
);
ALTER TABLE RI_TIPIINTERVENTO ADD CONSTRAINT RI_TIPIINTERVENTO_PK PRIMARY KEY(CODICE); 
ALTER TABLE ALBEROPROC ADD FK_RITI_CODICE VARCHAR2(20);
ALTER TABLE ALBEROPROC ADD CONSTRAINT FK_RITIPIINT_ALBPROC FOREIGN KEY (FK_RITI_CODICE) REFERENCES RI_TIPIINTERVENTO(CODICE);

CREATE TABLE RI_TIPIPROCEDIMENTO(
CODICE VARCHAR2(20) NOT NULL,
DESCRIZIONE VARCHAR2(150)
);
ALTER TABLE RI_TIPIPROCEDIMENTO ADD CONSTRAINT RI_TIPIPROCEDIMENTO_PK PRIMARY KEY(CODICE); 
ALTER TABLE TIPIPROCEDURE ADD FK_RITP_CODICE VARCHAR2(20);
ALTER TABLE TIPIPROCEDURE ADD CONSTRAINT FK_RITIPIPROC_TIPROC FOREIGN KEY(FK_RITP_CODICE) REFERENCES RI_TIPIPROCEDIMENTO(CODICE);

ALTER TABLE OGGETTI MODIFY NOMEFILE VARCHAR2(256);

ALTER TABLE TIPIMOV_STC_MAPPING ADD FLAG_ALLEGA_DOCUMENTI_ENDO NUMBER(1,0);
COMMENT ON COLUMN TIPIMOV_STC_MAPPING.FLAG_ALLEGA_DOCUMENTI_ENDO IS 'SE SPUNTATO IN FASE DI VISUALIZZAZIONE NOTIFICA SARANNO SELEZIONATI DI DEFAULT TUTTI I DOCUMENTI DELL''ENDO';