CREATE TABLE STP_TIPOLOGIE_ENDO2
(
   IDCOMUNE varchar2(6) not null,
   ID NUMBER(4,0) NOT NULL,
   DESCRIZIONE VARCHAR2(100)
);

ALTER TABLE STP_TIPOLOGIE_ENDO2 ADD CONSTRAINT STP_TIPOLOGIE_ENDO2_PK PRIMARY KEY (IDCOMUNE,ID);

COMMENT ON COLUMN STP_TIPOLOGIE_ENDO2.ID IS 'CODICE DELLA TIPOLOGIA ENDO DI TIPO 2 CHE RAPPRESENTA L''IDENTIFICATIVO CART (/invioDizionario/tipologiaEndoTipo2/@id)';
COMMENT ON COLUMN STP_TIPOLOGIE_ENDO2.DESCRIZIONE IS 'DESCRIZIONE DELLA TIPOLOGIA ENDO DI TIPO 2 CHE RAPPRESENTA L''IDENTIFICATIVO CART (/invioDizionario/tipologiaEndoTipo2/nome)';
