ALTER TABLE METADATI_DIZ_BASE ADD CONTESTO VARCHAR2(1);

ALTER TABLE ALBEROPROC ADD(INIZIO_VALIDITA DATE);
ALTER TABLE ALBEROPROC ADD(FINE_VALIDITA DATE);

ALTER TABLE STRADARIO ADD(COMUNE_LOCALIZZAZIONE VARCHAR2(5));
ALTER TABLE STRADARIO ADD CONSTRAINT FK_STRADARIO_COMUNE_LOCALIZZ FOREIGN KEY (COMUNE_LOCALIZZAZIONE) REFERENCES COMUNI(CODICECOMUNE);

CREATE TABLE CONF_APPLICATIVE(
	IDCOMUNE VARCHAR2(6) NOT NULL,
	CHIAVE   VARCHAR2(50) NOT NULL,
	VALORE   VARCHAR2(200)
);

ALTER TABLE CONF_APPLICATIVE ADD CONSTRAINT PK_CONF_APPLICATIVE PRIMARY KEY (IDCOMUNE, CHIAVE);