#parametri timeout delle chiamate WS
ws.timeout=300000

## parametri per comunicazione con STC
stcWsUrl=REDACTED
stcMtomEnabled=true
nlaUserId=NLA-ATTI
nlaPassword=REDACTED
idNodo=4100

## PARAMETRI CONFIGURAZIONE OGGETTI SERVICE WS
oggetti.ws.mtom.enabled=true
oggetti.ws.path.to.wsdl=/services/oggetti?wsdl
oggetti.ws.attach.logging.interceptors=true

## PARAMETRI CONFIGURAZIONE MOVIMENTI SERVICE WS
movimenti.ws.path.to.wsdl=/services/movimenti?wsdl

## parametri per comunicazione con Sigepro Security
ws.token.pwd=REDACTED
ws.token.url=REDACTED
ws.token.user=REDACTED
ws.token.idcomunealias=E625

## Parametri ws atti 
attiWsUrl=REDACTED
attiMtomEnabled=true

attiWsUsername=REDACTED



