#####

intestazione.richiesta.mittente.country=it
intestazione.richiesta.mittente.orgunit=orgMitt
intestazione.richiesta.mittente.text=ComuneDiPordenone
intestazione.richiesta.destinatario.country=it
intestazione.richiesta.destinatario.orgunit=org
intestazione.richiesta.destinatario.text=UICCIAAPortaleImprese
intestazione.richiesta.servizio.text=interazioni-ri
intestazione.richiesta.comunicazione.text=EGOV_IT_ServizioSincrono
intestazione.richiesta.accordoservizio.text=IdentificativoAccordoServizio
