SET IMPLICIT_TRANSACTIONS ON
GO
CREATE TABLE ALBEROPROC_TIPISOGGETTO(
IDCOMUNE VARCHAR(6) NOT NULL,
ID NUMERIC(6,0) NOT NULL,
FK_SCID NUMERIC(10,0) NOT NULL,
FK_CODICETIPOSOGGETTO NUMERIC(10,0) NOT NULL
)
GO
COMMIT
GO
ALTER TABLE ALBEROPROC_TIPISOGGETTO ADD CONSTRAINT PK_ALBEROPROC_TIPISOGGETTO PRIMARY KEY(IDCOMUNE, ID)
GO
COMMIT
GO
ALTER TABLE ALBEROPROC_TIPISOGGETTO ADD CONSTRAINT FK_APTS_TIPISOGGETTO FOREIGN KEY(IDCOMUNE, FK_CODICETIPOSOGGETTO) REFERENCES TIPISOGGETTO(IDCOMUNE, CODICETIPOSOGGETTO)
GO
COMMIT
GO
ALTER TABLE ALBEROPROC_TIPISOGGETTO ADD CONSTRAINT FK_APTS_ALBEROPROC FOREIGN KEY(IDCOMUNE, FK_SCID) REFERENCES ALBEROPROC(IDCOMUNE, SC_ID)
GO
COMMIT
GO
DROP VIEW VW_ENTILOCALI
GO
COMMIT
GO
CREATE VIEW VW_ENTILOCALI AS SELECT CODICECOMUNE, COMUNE FROM COMUNI WHERE CODICESTATOESTERO IS NULL UNION SELECT CODICEASSOCIAZIONE AS CODICECOMUNE, ASSOCIAZIONE AS COMUNE FROM COMUNIASSOCIAZIONI
GO
COMMIT
GO
ALTER TABLE FO_ARJ_DOMANDE ADD FLAG_INVALIDATA NUMERIC(1,0)
GO
COMMIT
GO
ALTER TABLE FO_ARJ_DOMANDE ADD DATA_INVALIDATA DATETIME
GO
COMMIT
GO
CREATE TABLE FO_ARJ_DOMANDE_STEPS_ESEGUITI(
ID NUMERIC(6,0) NOT NULL,
IDCOMUNE VARCHAR(6) NOT NULL,
FK_FO_ARJ_DOMANDE NUMERIC(6,0) NOT NULL,
FK_FO_ARJ_STEPS_BASE VARCHAR(50) NOT NULL
)
GO
COMMIT
GO
ALTER TABLE FO_ARJ_DOMANDE_STEPS_ESEGUITI ADD CONSTRAINT FOARJDOMANDESTEPSESEGUITI_PK PRIMARY KEY
(
  IDCOMUNE, ID
)
GO
COMMIT
GO
ALTER TABLE FO_ARJ_DOMANDE_STEPS_ESEGUITI ADD CONSTRAINT STEPSESEGUITI_FOARJDOMANDE FOREIGN KEY ( IDCOMUNE, FK_FO_ARJ_DOMANDE) REFERENCES FO_ARJ_DOMANDE ( IDCOMUNE, ID )
GO
COMMIT
GO
ALTER TABLE FO_ARJ_DOMANDE_STEPS_ESEGUITI ADD CONSTRAINT STEPSESEGUITI_FOARJSTEPSBA FOREIGN KEY ( FK_FO_ARJ_STEPS_BASE) REFERENCES FO_ARJ_STEPS_BASE ( NOME_STEP )
GO
COMMIT
GO
CREATE TABLE PAYER_ATTIVAZIONI 
(
CODICECOMUNE VARCHAR(5) NOT NULL, 
ALIAS VARCHAR(20) NOT NULL ,
IDCOMUNE VARCHAR(6) NOT NULL,
CONSTRAINT PAYER_ATTIVAZIONI_PK PRIMARY KEY (CODICECOMUNE )
)
GO
COMMIT
GO
CREATE TABLE PAYER_LOG
(
IDCOMUNE VARCHAR(6) NOT NULL,
CODICE NUMERIC(10,0) NOT NULL,
CODICEOGGETTO NUMERIC(10,0) NOT NULL,
PROGRESSIVO NUMERIC(8,0) NOT NULL,
NUM_DOCUMENTO VARCHAR(23),
NUM_RATA NUMERIC(2,0),
IMPORTO  NUMERIC (8,2),
ISTANZA NUMERIC(6,0),
CAUSALE_ONERE NUMERIC(10,0),
FK_ONERI NUMERIC(10,0),
ERRORE LONGTEXT,
CODICE_ERRORE VARCHAR(4), 
FLAG_ERRORE NUMERIC(1,0) NOT NULL,
DATA_PAGAMENTO DATETIME,
DATA_REGISTRAZIONE DATETIME
)
GO
COMMIT
GO
ALTER TABLE PAYER_LOG ADD CONSTRAINT PK_APAYER_LOG PRIMARY KEY(IDCOMUNE, CODICE) 
GO
COMMIT
GO
ALTER TABLE PAYER_LOG ADD CONSTRAINT FK_PAYERLOG_OGGETTI FOREIGN KEY(IDCOMUNE, CODICEOGGETTO) REFERENCES OGGETTI(IDCOMUNE, CODICEOGGETTO)
GO
COMMIT
GO
alter table FO_ARJ_DOMANDE add FLAG_FLUSSO_DA_INTERVENTO NUMERIC(1,0)
GO
COMMIT
GO
alter table FO_ARJ_DOMANDE add FK_FO_ARJ_SERVIZI NUMERIC(6,0)
GO
COMMIT
GO
alter table FO_ARJ_DOMANDE add constraint FK_FOARJDOMANDE_FOARJSERVIZI foreign key (IDCOMUNE, FK_FO_ARJ_SERVIZI) references FO_ARJ_SERVIZI (IDCOMUNE, ID)
GO
COMMIT
GO
alter table FO_ARJ_SERVIZI ALTER COLUMN URL_SERVIZIO VARCHAR(200) not null
GO
COMMIT
GO
alter table FO_ARJ_SERVIZI add constraint UIDX_FOARJSERVIZI_001 unique (IDCOMUNE, URL_SERVIZIO)
GO
COMMIT
GO
alter table FO_ARJ_DOMANDE add CODICEOGGETTO_RICEVUTA NUMERIC(10,0)
GO
COMMIT
GO
alter table FO_ARJ_DOMANDE add constraint FK_FOARJDOMANDE_OGGRICE_OGG foreign key (IDCOMUNE, CODICEOGGETTO_RICEVUTA) references OGGETTI (IDCOMUNE, CODICEOGGETTO)
GO
COMMIT
GO
CREATE TABLE GRADUATORIET_COM
(
IDCOMUNE VARCHAR(6) NOT NULL,
ID NUMERIC(10,0) NOT NULL,
FK_GT_ID NUMERIC(6,0) NOT NULL,
DATA DATE NOT NULL,
DESCRIZIONE VARCHAR(500) NOT NULL,
TIPOMOVIMENTO VARCHAR (8) NOT NULL,
FLG_PROTOCOLLA  NUMERIC (1,0) NOT NULL,
CODICELETTERA NUMERIC(10,0), 
CODICEMAIL NUMERIC (4,0),
DESTINATARI VARCHAR(1) NOT NULL,
POSIZIONE_DA NUMERIC (4,0), 
POSIZIONE_AL NUMERIC(4,0), 
DYN2FILTRI VARCHAR(2000),
AMMINISTRAZIONE_PROT NUMERIC(10, 0)
) 
GO
COMMIT
GO
ALTER TABLE GRADUATORIET_COM ADD CONSTRAINT PK_GRADUATORIET_COM PRIMARY KEY(IDCOMUNE, ID)
GO
COMMIT
GO 
ALTER TABLE GRADUATORIET_COM ADD CONSTRAINT FK_GRADUAT_COM_GRADUA_T FOREIGN KEY(IDCOMUNE, FK_GT_ID) REFERENCES GRADUATORIET(IDCOMUNE, ID)
GO
COMMIT
GO
ALTER TABLE GRADUATORIET_COM ADD CONSTRAINT FK_GRADUAT_COM_TIPOMOV FOREIGN KEY(IDCOMUNE, TIPOMOVIMENTO) REFERENCES TIPIMOVIMENTO(IDCOMUNE, TIPOMOVIMENTO)
GO
COMMIT
GO
ALTER TABLE GRADUATORIET_COM ADD CONSTRAINT FK_GRADUAT_COM_LETT_TIPO FOREIGN KEY(IDCOMUNE, CODICELETTERA) REFERENCES LETTERETIPO(IDCOMUNE, CODICELETTERA)
GO
COMMIT
GO
ALTER TABLE GRADUATORIET_COM ADD CONSTRAINT FK_GRADUAT_COM_MAILTIPO FOREIGN KEY(IDCOMUNE, CODICEMAIL) REFERENCES MAILTIPO(IDCOMUNE, CODICEMAIL)
GO
COMMIT
GO
ALTER TABLE GRADUATORIET_COM ADD CONSTRAINT FK_GRADUAT_AMM_PROT FOREIGN KEY(IDCOMUNE, AMMINISTRAZIONE_PROT) REFERENCES AMMINISTRAZIONI(IDCOMUNE, CODICEAMMINISTRAZIONE)
GO
COMMIT
GO
CREATE TABLE GRADUATORIED_COM
(
IDCOMUNE VARCHAR(6) NOT NULL,
ID NUMERIC(10,0) NOT NULL,
FK_IDTESTATA NUMERIC(10,0) NOT NULL,
FK_GD_ID NUMERIC(9,0) NOT NULL,
CODICEMOVIMENTO NUMERIC (8,0),
FLG_PROTOCOLLATO  NUMERIC (1,0) NOT NULL,
CODICEOGGETTO NUMERIC(10,0), 
FK_IDMAIL NUMERIC (8,0)
)
GO
COMMIT
GO
ALTER TABLE GRADUATORIED_COM ADD CONSTRAINT PK_GRADUATORIED_COM PRIMARY KEY(IDCOMUNE, ID)
GO
COMMIT
GO
ALTER TABLE GRADUATORIED_COM ADD CONSTRAINT FK_GRAD_D_COM_GRAD_T_COM FOREIGN KEY(IDCOMUNE, FK_IDTESTATA) REFERENCES GRADUATORIET_COM(IDCOMUNE, ID)
GO
COMMIT
GO
ALTER TABLE GRADUATORIED_COM ADD CONSTRAINT FK_GRAD_D_COM_GRADUA_D FOREIGN KEY(IDCOMUNE, FK_GD_ID) REFERENCES GRADUATORIED(IDCOMUNE, ID)
GO
COMMIT
GO
ALTER TABLE GRADUATORIED_COM ADD CONSTRAINT FK_GRAD_D_COM_MOVIM FOREIGN KEY(IDCOMUNE, CODICEMOVIMENTO) REFERENCES MOVIMENTI(IDCOMUNE, CODICEMOVIMENTO)
GO
COMMIT
GO
ALTER TABLE GRADUATORIED_COM ADD CONSTRAINT FK_GRAD_D_COM_OGGETTI FOREIGN KEY(IDCOMUNE, CODICEOGGETTO) REFERENCES OGGETTI(IDCOMUNE, CODICEOGGETTO)
GO
COMMIT
GO
ALTER TABLE GRADUATORIED_COM ADD CONSTRAINT FK_GRAD_D_COM_MOV_MAIL FOREIGN KEY(IDCOMUNE, FK_IDMAIL) REFERENCES MOVIMENTIMAIL(IDCOMUNE, ID)
GO
COMMIT
GO
ALTER TABLE INVENTARIOPROC_TIPITITOLO ADD FLG_MOSTRA_DATA NUMERIC(1,0)
GO
COMMIT
GO
ALTER TABLE INVENTARIOPROC_TIPITITOLO ADD FLG_MOSTRA_NUMERO NUMERIC(1,0)
GO
COMMIT
GO
ALTER TABLE INVENTARIOPROC_TIPITITOLO ADD FLG_MOSTRA_RILASCIATO_DA NUMERIC(1,0)
GO
COMMIT
GO
ALTER TABLE INVENTARIOPROC_TIPITITOLO ADD FLG_RICHIEDE_ALLEGATO NUMERIC(1,0)
GO
COMMIT
GO
ALTER TABLE INVENTARIOPROC_TIPITITOLO ADD FLG_VERIFICA_FIRMA_ALLEGATO NUMERIC(1,0)
GO
COMMIT
GO
ALTER TABLE FO_ARJ_STEPS_PARAMS_BASE ADD FK_FO_ARJ_STEP_BASE VARCHAR(50)
GO
COMMIT
GO
ALTER TABLE FO_ARJ_STEPS_PARAMS_BASE ADD CONSTRAINT FK_FOARJSTEPPARMBASE_STEPBASE FOREIGN KEY (FK_FO_ARJ_STEP_BASE) REFERENCES FO_ARJ_STEPS_BASE (NOME_STEP)
GO
COMMIT
GO
ALTER TABLE TIPIPROCEDURE ADD CODOGGETTO_RICEVUTACART NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE TIPIPROCEDURE ADD CONSTRAINT FK_TPROC_CODRICCART FOREIGN KEY(IDCOMUNE, CODOGGETTO_RICEVUTACART) REFERENCES OGGETTI(IDCOMUNE,CODICEOGGETTO)
GO
COMMIT
GO
ALTER TABLE ANAGRAFEDOCUMENTI ADD FLAG_XMLVISURAPARIX NUMERIC(1,0)
GO
COMMIT
GO
ALTER TABLE PEC_INBOX ADD FLAG_PROCESSATA NUMERIC(1, 0) DEFAULT 0
GO
COMMIT
GO
ALTER TABLE PEC_INBOX ADD CODICEISTANZA NUMERIC(6, 0) 
GO
COMMIT
GO
ALTER TABLE PEC_INBOX ADD CODICEMOVIMENTO NUMERIC(8, 0)
GO
COMMIT
GO
ALTER TABLE PEC_INBOX ADD CODICEOPERATORE NUMERIC(4, 0)
GO
COMMIT
GO
ALTER TABLE PEC_INBOX ADD IDPROTOCOLLO VARCHAR(15)
GO
COMMIT
GO
ALTER TABLE PEC_INBOX ADD NUMEROPROTOCOLLO VARCHAR(30)
GO
COMMIT
GO
ALTER TABLE PEC_INBOX ADD DATAPROTOCOLLO DATETIME
GO
COMMIT
GO
ALTER TABLE PEC_INBOX ADD CODICEOGGETTOPROTOCOLLO NUMERIC(10, 0)
GO
COMMIT
GO
ALTER TABLE PEC_INBOX ADD CONSTRAINT PEC_INBOX_FK_ISTANZE FOREIGN KEY(IDCOMUNE, CODICEISTANZA) REFERENCES ISTANZE(IDCOMUNE, CODICEISTANZA)
GO
COMMIT
GO
ALTER TABLE PEC_INBOX ADD CONSTRAINT PEC_INBOX_MOVIMENTI_FK1 FOREIGN KEY(IDCOMUNE, CODICEMOVIMENTO) REFERENCES MOVIMENTI(IDCOMUNE, CODICEMOVIMENTO)
GO
COMMIT
GO
ALTER TABLE PEC_INBOX ADD CONSTRAINT PEC_INBOX_RESPONSABILI_FK1 FOREIGN KEY (IDCOMUNE, CODICEOPERATORE) REFERENCES RESPONSABILI(IDCOMUNE, CODICERESPONSABILE)
GO
COMMIT
GO
ALTER TABLE PEC_INBOX ADD CONSTRAINT CHK_FLG_PROCESSATA CHECK (FLAG_PROCESSATA IN (0, 1))
GO
COMMIT
GO
ALTER TABLE PEC_INBOX ADD CONSTRAINT PEC_INBOX_FK_OGGETTI FOREIGN KEY (IDCOMUNE, CODICEOGGETTOPROTOCOLLO) REFERENCES OGGETTI (IDCOMUNE, CODICEOGGETTO)
GO
COMMIT
GO
CREATE TABLE PEC_INBOX_ALLEGATI 
(
  IDCOMUNE VARCHAR(6) NOT NULL 
, ID NUMERIC(8, 0) NOT NULL 
, FKIDPEC VARCHAR(128) NOT NULL 
, CODICEOGGETTO NUMERIC(10, 0) NOT NULL 
, FLAG_CORPO NUMERIC(1, 0) DEFAULT 0
, CONSTRAINT PEC_INBOX_ALLEGATI_PK PRIMARY KEY 
  (
    IDCOMUNE 
  , ID 
  )
)
GO
COMMIT
GO
ALTER TABLE PEC_INBOX_ALLEGATI ADD CONSTRAINT PECALLEGATI_FK_OGGETTI FOREIGN KEY (IDCOMUNE, CODICEOGGETTO) REFERENCES OGGETTI (IDCOMUNE, CODICEOGGETTO)
GO
COMMIT
GO
ALTER TABLE PEC_INBOX_ALLEGATI ADD CONSTRAINT PECALLEGATI_FK_PEC FOREIGN KEY (IDCOMUNE, FKIDPEC) REFERENCES PEC_INBOX(IDCOMUNE, ID)
GO
COMMIT
GO
ALTER TABLE DOMANDESTC MODIFY ID_DOMANDAMITT VARCHAR(150)
GO
COMMIT
GO
ALTER TABLE PEC_INBOX ADD FLAG_CANCELLATA NUMERIC(1, 0);
GO
COMMIT
GO
ALTER TABLE PROTOCOLLO_TIPIDOCUMENTO  MODIFY CODICE VARCHAR(50)
GO
COMMIT
GO
DROP TABLE FO_ARJ_STEPS_PARAMS
GO
COMMIT
GO
DROP TABLE FO_ARJ_STEPS_PARAMS_BASE
GO
COMMIT
GO
CREATE TABLE FO_ARJ_STEPS_PARAMS_BASE(
ID NUMERIC(6,0) NOT NULL,
CHIAVE VARCHAR(200) NOT NULL,
DESCRIZIONE VARCHAR(500) NOT NULL,
FK_FO_ARJ_STEP_BASE VARCHAR(50) NOT NULL,
  CONSTRAINT FO_ARJ_STEPS_PARAMS_BASE_PK PRIMARY KEY (ID) ENABLE,
  CONSTRAINT FK_FOARJSTEPPARMBASE_STEPBASE FOREIGN KEY (FK_FO_ARJ_STEP_BASE) REFERENCES FO_ARJ_STEPS_BASE (NOME_STEP) ENABLE
)
GO
COMMIT
GO
CREATE TABLE FO_ARJ_STEPS_PARAMS(
IDCOMUNE VARCHAR(6) NOT NULL,
ID NUMERIC(6,0) NOT NULL,
FK_PARAMS_BASE NUMERIC(6,0) NOT NULL,
VALORE VARCHAR(400),
FK_FO_ARJ_STEPS NUMERIC(6,0) NOT NULL,
 CONSTRAINT FO_ARJ_STEPS_PARAMS_PK PRIMARY KEY (IDCOMUNE, ID) ,
 CONSTRAINT FK_FOARJSTEPSPARAMS_FOARJSTEPS FOREIGN KEY (IDCOMUNE, FK_FO_ARJ_STEPS) REFERENCES FO_ARJ_STEPS (IDCOMUNE, ID) ,
 CONSTRAINT FK_FOARJSTEPSPARAMS_BASE FOREIGN KEY (FK_PARAMS_BASE) REFERENCES FO_ARJ_STEPS_PARAMS_BASE (ID) 
)
GO
COMMIT
GO
Drop View VW_STATISTICHEISTANZE
GO
COMMIT
GO
Create  View VW_STATISTICHEISTANZE as SELECT DISTINCT ISTANZE.IDCOMUNE as f_idcomune,
ISTANZE.SOFTWARE as f_software,
ISTANZE.DATA as f_data,
ISNULL(ISTANZE.codiceResponsabile,
-1) as f_responsabile,
ISNULL(ISTANZE.codiceprofessionista,
-1) as f_professionista,
ISNULL(ISTANZE.CODICEINTERVENTOPROC,
ISTANZE.CODICEINTERVENTO) as f_codiceintervento,
ISNULL(ISTANZE.METRIQUADRATI,
0) as f_metriquadrati,
ISNULL(ISTANZE.CODICEPROCEDURA,
-1) as f_procedura,
ISNULL(ISTANZEATTIVITA.CodiceAttivita,
' ') as f_dettaglioinformazioni,
ISNULL(SETTORI.CodiceSettore,
-1) as f_tipoinformazioni,
ISNULL(ISTANZEAREE.CODICEAREA,
-1) as f_zonizzazione,
ISNULL(AUTORIZZAZIONI.FKIDREGISTRO,
-1) as f_registro,
ISNULL(ISTANZE.CHIUSURA,
' ') as f_stato,
ISTANZE.CODICEISTANZA,
ISTANZE.CODICERESPONSABILE,
ISTANZE.CODICERICHIEDENTE,
ISTANZE.CODICEPROFESSIONISTA,
ISTANZE.DATA,
ISTANZE.NUMEROPROTOCOLLO,
ISTANZE.DATAPROTOCOLLO,
ISTANZE.CODICEINTERVENTO,
ISTANZE.LAVORI,
ISTANZE.CODICEPROCEDURA,
ISTANZE.CODICEAREA,
ISTANZE.CODICELOTTO,
ISTANZE.PASSWORD,
ISTANZE.ATTIVA,
ISTANZE.FOGLIO,
ISTANZE.PARTICELLA,
ISTANZE.SUB,
ISTANZE.CODICESETTORE,
ISTANZE.VARIANTEPR,
ISTANZE.CODICEIMPIANTO,
ISTANZE.CODICEATTIVITA,
ISTANZE.FLAGVIA,
ISTANZE.CHIUSURA,
ISTANZE.PROGREGAUT,
ISTANZE.LAVORIESTESA,
ISTANZE.CODICEARCHIVIO,
ISTANZE.CODICESTRADARIO,
ISTANZE.CIVICO,
ISTANZE.AUTORIZNUMERO,
ISTANZE.AUTORIZDATA,
ISTANZE.AUTORIZDATAREGISTR,
ISTANZE.AUTORIZRESPONSABILE,
ISTANZE.TIPOMOVAVVIO,
ISTANZE.TIPOARCHIVIO,
ISTANZE.CODICECOMUNE,
ISTANZE.SOFTWARE,
ISTANZE.IDMODELLO,
ISTANZE.CODICEINTERVENTOPROC,
ISTANZE.NUMEROISTANZA,
ISTANZE.IDCOMUNE,
ISTANZE.SETITOLARELEGALE,
ISTANZE.FKIDTIPOLOGIAISTANZA,
ISTANZE.CODICETITOLARELEGALE,
ISTANZE.FKTOID,
ISTANZE.METRIQUADRATI,
ISTANZE.GIORNOCHIUSURA,
ISTANZE.CODISTANZACOLLEGATA,
ISTANZE.AZIONE,
ISTANZE.FKIDREGISTRO,
ISTANZE.NOMEATTIVITA,
ISTANZE.FKIDFORMATO,
ISTANZE.POSIZIONEARCHIVIO,
ISTANZE.BASE,
ISTANZE.ALTEZZA,
ISTANZE.FACCE,
ISTANZE.FKIDPROTOCOLLO,
ISTANZE.FKCODICESOGGETTO,
ISTANZE.CODICEISTRUTTORE,
ISTANZE.CODICERESPONSABILEPROC,
ISTANZE.CODICEAREA2,
ISTANZE.FK_IDI_ATTIVITA,
ISTANZE.DATAVALIDITA,
ISTANZE.I_ATTIVITAORDINE,
ISTANZE.CREATO_DA_STC,
ISTANZE.DESCRSOGGETTO,
ISTANZE.DOMICILIO_ELETTRONICO 
 FROM ISTANZE LEFT OUTER JOIN ISTANZEATTIVITA LEFT OUTER JOIN ATTIVITA LEFT OUTER JOIN SETTORI ON ATTIVITA.IDCOMUNE=SETTORI.IDCOMUNE  AND ATTIVITA.CODICESETTORE=SETTORI.CODICESETTORE ON ISTANZEATTIVITA.IDCOMUNE=ATTIVITA.IDCOMUNE  AND ISTANZEATTIVITA.CODICEATTIVITA=ATTIVITA.CODICEISTAT ON ISTANZE.IDCOMUNE=ISTANZEATTIVITA.IDCOMUNE  AND ISTANZE.CODICEISTANZA=ISTANZEATTIVITA.CODICEISTANZA  LEFT OUTER JOIN ISTANZEAREE ON ISTANZE.IDCOMUNE=ISTANZEAREE.IDCOMUNE  AND ISTANZE.CODICEISTANZA=ISTANZEAREE.CODICEISTANZA  LEFT OUTER JOIN AUTORIZZAZIONI ON ISTANZE.IDCOMUNE=AUTORIZZAZIONI.IDCOMUNE  AND ISTANZE.CODICEISTANZA=AUTORIZZAZIONI.FKIDISTANZA
GO
COMMIT
GO
CREATE TABLE NLA_SERVIZI_ALTRI_DATI(
IDCOMUNE VARCHAR(6) NOT NULL,
ID NUMERIC(4,0) NOT NULL,
NOMEPARAMETRO VARCHAR(50) NOT NULL,
VALORE VARCHAR(200),
FK_NLASERVIZIID NUMERIC(6,0) NOT NULL
)
GO
COMMIT
GO
ALTER TABLE NLA_SERVIZI_ALTRI_DATI ADD CONSTRAINT PK_NLA_SERVIZI_ALTRI_DATI PRIMARY KEY(IDCOMUNE, ID)
GO
COMMIT
GO
ALTER TABLE NLA_SERVIZI_ALTRI_DATI ADD CONSTRAINT FK_NSADATI_NLA_SERVIZI FOREIGN KEY(IDCOMUNE, FK_NLASERVIZIID) REFERENCES NLA_SERVIZI(IDCOMUNE, ID)
GO
COMMIT
GO
CREATE TABLE DOCUMENTI_DA_FIRMARE (
    IDCOMUNE VARCHAR(6) NOT NULL,
    ID NUMERIC(6,0) NOT NULL,
    CODICERICHIEDENTE NUMERIC(4,0) NOT NULL,
    CODICEFIRMATARIO NUMERIC(4,0) NOT NULL,
    DATA_RICHIESTA DATETIME,
    FLAG_DA_FIRMARE VARCHAR(20),
    DATA_FIRMA DATETIME,
    CODICEISTANZA NUMERIC(6,0) NOT NULL,
    CODICEMOVALLEGATI NUMERIC(8,0) NOT NULL,
    CODICEOGGETTO NUMERIC(10) NOT NULL,
    ANNOTAZIONI_RICHIEDENTE VARCHAR(4000),
    ANNOTAZIONI_FIRMATARIO VARCHAR(4000),
    FLAG_LETTO NUMERIC(1,0)
)
GO
COMMIT
GO
ALTER TABLE DOCUMENTI_DA_FIRMARE ADD CONSTRAINT DOCUMENTI_DA_FIRMARE_PK PRIMARY KEY (IDCOMUNE, ID)
GO
COMMIT
GO
ALTER TABLE DOCUMENTI_DA_FIRMARE ADD CONSTRAINT DOCUMENTI_DA_FIRMARE_RESP_FK2 FOREIGN KEY (IDCOMUNE, CODICEFIRMATARIO) REFERENCES RESPONSABILI (IDCOMUNE, CODICERESPONSABILE)
GO
COMMIT
GO
ALTER TABLE DOCUMENTI_DA_FIRMARE ADD CONSTRAINT DOCUMENTI_DA_FIRMARE_RESP_FK1 FOREIGN KEY (IDCOMUNE, CODICERICHIEDENTE) REFERENCES RESPONSABILI (IDCOMUNE, CODICERESPONSABILE)
GO
COMMIT
GO
ALTER TABLE DOCUMENTI_DA_FIRMARE ADD CONSTRAINT DOCUMENTI_DA_FIRMARE_ISTA_FK1 FOREIGN KEY (IDCOMUNE, CODICEISTANZA) REFERENCES ISTANZE (IDCOMUNE, CODICEISTANZA)
GO
COMMIT
GO
ALTER TABLE DOCUMENTI_DA_FIRMARE ADD CONSTRAINT DOCUMENTI_DA_FIRMARE_MOVI_FK1 FOREIGN KEY (IDCOMUNE, CODICEMOVALLEGATI) REFERENCES MOVIMENTIALLEGATI (IDCOMUNE, ID)
GO
COMMIT
GO
ALTER TABLE DOCUMENTI_DA_FIRMARE ADD CONSTRAINT DOCUMENTI_DA_FIRMARE_OGGE_FK1 FOREIGN KEY (IDCOMUNE, CODICEOGGETTO) REFERENCES OGGETTI (IDCOMUNE, CODICEOGGETTO)
GO
COMMIT
GO
ALTER TABLE I_ATTIVITADYN2DATI_SNAPSHOT ADD (AUTOINS NUMERIC(1,0))
GO
COMMIT
GO
ALTER TABLE I_ATTIVITADYN2DATI ADD (AUTOINS NUMERIC(1,0))
GO
COMMIT
GO