<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://gruppoinit.it/sigepro/schemas/messages/base" elementFormDefault="qualified" xmlns:xmime="http://www.w3.org/2005/05/xmlmime"
	xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://gruppoinit.it/sigepro/schemas/messages/base">
	<complexType name="AllegatoBaseType">
		<sequence>
			<element name="id" type="integer" minOccurs="0" maxOccurs="1" />
			<element name="descrizione" type="string" minOccurs="0" maxOccurs="1" />
			<element name="fileName" type="string" />
			<element name="mimeType" type="string" minOccurs="0" maxOccurs="1" />
			<element name="binaryData" type="base64Binary" minOccurs="0" maxOccurs="1" xmime:expectedContentTypes="application/octet-stream" />
		</sequence>
	</complexType>
</schema>