CREATE TABLE ALBEROPROC_COMUNI_ESCLUSI ( idcomune VARCHAR(6) NOT NULL, fk_scid DECIMAL(10,0) NOT NULL, codicecomune VARCHAR(5) NOT NULL ) ENGINE=INNODB DEFAULT CHARSET=utf8;
ALTER TABLE ALBEROPROC_COMUNI_ESCLUSI ADD PRIMARY KEY (idcomune, fk_scid, codicecomune); 
ALTER TABLE ALBEROPROC_COMUNI_ESCLUSI ADD CONSTRAINT FK_COMUNI_ESCLUSI_ALBERO FOREIGN KEY (idcomune, fk_scid) REFERENCES alberoproc (idcomune, sc_id); 
ALTER TABLE ALBEROPROC_COMUNI_ESCLUSI ADD CONSTRAINT FK_COMUNI_ESCLUSI_COMUNI FOREIGN KEY (codicecomune) REFERENCES comuni (codicecomune);
