ALTER TABLE AUTORIZZAZIONI_SUBENTRI ADD (FK_MERCATO NUMERIC(4,0));
ALTER TABLE AUTORIZZAZIONI_SUBENTRI ADD (FK_USO NUMERIC(4,0));
ALTER TABLE AUTORIZZAZIONI_SUBENTRI ADD (FK_MERCATOD NUMERIC(6,0));
ALTER TABLE AUTORIZZAZIONI_SUBENTRI ADD (FK_CONCESSIONITIPI VARCHAR(2));
ALTER TABLE AUTORIZZAZIONI_SUBENTRI ADD (STAGIONALE_DA DATETIME );
ALTER TABLE AUTORIZZAZIONI_SUBENTRI ADD (STAGIONALE_A DATETIME );

ALTER TABLE AUTORIZZAZIONI_SUBENTRI ADD CONSTRAINT FK_AUT_SUB_MERCATO FOREIGN KEY(IDCOMUNE,FK_MERCATO) REFERENCES MERCATI(IDCOMUNE,CODICEMERCATO);
ALTER TABLE AUTORIZZAZIONI_SUBENTRI ADD CONSTRAINT FK_AUT_SUB_MERC_USO FOREIGN KEY(IDCOMUNE,FK_USO) REFERENCES MERCATI_USO(IDCOMUNE,ID);
ALTER TABLE AUTORIZZAZIONI_SUBENTRI ADD CONSTRAINT FK_AUT_SUB_MERCATOD FOREIGN KEY(IDCOMUNE,FK_MERCATOD) REFERENCES MERCATI_D(IDCOMUNE,IDPOSTEGGIO);
ALTER TABLE AUTORIZZAZIONI_SUBENTRI ADD CONSTRAINT FK_AUT_SUB_CONCTIPI FOREIGN KEY(FK_CONCESSIONITIPI) REFERENCES CONCESSIONITIPI(TIPOCONCESSIONE);

ALTER TABLE I_ATTIVITA ADD (DATA_INIZIO DATETIME);
ALTER TABLE I_ATTIVITA ADD (DATA_FINE DATETIME);

ALTER TABLE fo_domande ADD CODICEISTANZA_ORIGINE numeric(6, 0);

CREATE TABLE PROTOCOLLO_CLASSIFICHE 
(
  IDCOMUNE VARCHAR(6) NOT NULL 
, CODICE VARCHAR(50) NOT NULL 
, DESCRIZIONE VARCHAR(100) NOT NULL 
, CODICECOMUNE VARCHAR(5) 
, SOFTWARE VARCHAR(2) 
, ID NUMERIC(10) NOT NULL 
  
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE PROTOCOLLO_CLASSIFICHE ADD CONSTRAINT PROTOCOLLO_CLASSIFICHE_PK PRIMARY KEY(  IDCOMUNE   , ID ) ;

ALTER TABLE PROTOCOLLO_CLASSIFICHE ADD CONSTRAINT PROT_CLASSIFICHE_COMUNI FOREIGN KEY(  CODICECOMUNE ) REFERENCES COMUNI(  CODICECOMUNE) ;

ALTER TABLE PROTOCOLLO_CLASSIFICHE ADD CONSTRAINT PROT_CLASSIFICHE_SOFTWARE FOREIGN KEY (   SOFTWARE) REFERENCES SOFTWARE (   CODICE ) ;

ALTER TABLE PROTOCOLLO_CLASSIFICHE  MODIFY DESCRIZIONE VARCHAR(500);

CREATE TABLE ISTANZE_INOLTRATE_TRIB   (
    IDCOMUNE      VARCHAR(6),
    CODICEISTANZA NUMERIC(6,0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE ISTANZE_INOLTRATE_TRIB ADD CONSTRAINT PK_ISTANZE_INOLTRATE_TRIB PRIMARY KEY (idcomune,codiceistanza);

CREATE TABLE PEOPLEPROCSPORTELLI (
ID NUMERIC(10) NOT NULL, 
IDCOMUNE VARCHAR(6 ) NOT NULL, 
CODICECOMUNE VARCHAR(5 ), 
PEOPLE_PROC VARCHAR(20 ), 
SOFTWARE VARCHAR(2 )
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
   
ALTER TABLE PEOPLEPROCSPORTELLI ADD CONSTRAINT PEOPLEPROCSPORTELLI_PK PRIMARY KEY (IDCOMUNE, ID);

DELETE FROM INTERESSI_LEGALI;

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (1,STR_TO_DATE('21-04-1942','%d-%m-%Y'),STR_TO_DATE('15-12-1990','%d-%m-%Y'),5,null);

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (2,STR_TO_DATE('16-12-1990','%d-%m-%Y'),STR_TO_DATE('31-12-1996','%d-%m-%Y'),10,'Legge 26 novembre 1990, n. 353'); 

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (3,STR_TO_DATE('01-01-1997','%d-%m-%Y'),STR_TO_DATE('31-12-1998','%d-%m-%Y'),5,'Legge 23 dicembre 1996, n. 662'); 

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (4,STR_TO_DATE('01-01-1999','%d-%m-%Y'),STR_TO_DATE('31-12-2000','%d-%m-%Y'),2.5,'D.M. 10 dicembre 1998');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (5,STR_TO_DATE('01-01-2001','%d-%m-%Y'),STR_TO_DATE('31-12-2001','%d-%m-%Y'),3.5,'D.M. 11 dicembre 2000');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (6,STR_TO_DATE('01-01-2002','%d-%m-%Y'),STR_TO_DATE('31-12-2003','%d-%m-%Y'),3,'D.M. 11 dicembre 2001');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (7,STR_TO_DATE('01-01-2004','%d-%m-%Y'),STR_TO_DATE('31-12-2007','%d-%m-%Y'),2.5,'D.M. 1 dicembre 2003');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (8,STR_TO_DATE('01-01-2008','%d-%m-%Y'),STR_TO_DATE('31-12-2009','%d-%m-%Y'),3,'D.M. 12 dicembre 2007');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (9,STR_TO_DATE('01-01-2010','%d-%m-%Y'),STR_TO_DATE('31-12-2010','%d-%m-%Y'),1,'D.M. 4 dicembre 2009');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (10,STR_TO_DATE('01-01-2011','%d-%m-%Y'),STR_TO_DATE('31-12-2011','%d-%m-%Y'),1.5,'D.M. 07 Dicembre 2010');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (11,STR_TO_DATE('01-01-2012','%d-%m-%Y'),STR_TO_DATE('31-12-2013','%d-%m-%Y'),2.5,'DM 12 dicembre 2011');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (12,STR_TO_DATE('01-01-2014','%d-%m-%Y'),STR_TO_DATE('31-12-2014','%d-%m-%Y'),1,'Dm Economia 13.12.2013');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (13,STR_TO_DATE('01-01-2015','%d-%m-%Y'),STR_TO_DATE('31-12-2015','%d-%m-%Y'),0.5,'Dm Economia 11.12.2014');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (14,STR_TO_DATE('01-01-2016','%d-%m-%Y'),STR_TO_DATE('31-12-2016','%d-%m-%Y') ,0.2,'Dm Economia 11.12.2015');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (15,STR_TO_DATE('01-01-2017', '%d-%m-%Y'),null,0.1,'Dm economia e finanze 07/12/2016,G.U.14/12/2016');

ALTER TABLE SORTEGGIDETTAGLIO ADD FLAG_INTERVENTO_OBBLIGATORIO NUMERIC(1,0);