INSERT INTO clmenu_java (
    id,
    descrizione,
    pagina,
    menulink,
    software,
    jsp,
    layouttesti,
    softwareesclusi,
    VERTICALIZZAZIONE,
    link_standard,
    tipo_funzionalita,
    menulink_v2
) VALUES (
    1041,
    'Inoltro pratiche ZIP',
    'operazioniesterne/caricaPraticaView.htm?software=SOFTWARE',
    '10A',
    '*',
    'JAVA',
    '0',
    'AB',
    'API_SERVICE',
    'operazioniesterne/caricaPraticaView.htm?software=SOFTWARE',
    'S',
    '10A'
);

INSERT INTO verticalizzazioniparametribase (modulo, parametro, descrizione) VALUES ('NODO_PAGAMENTI','AR_URL_BACK','Usato da area riservata: Url di ritorno quando l''utente interrompe il pagamento e ritorna alla presentazione della pratica (es. ~/Reserved/InserimentoIstanza/GestionePagamentiNodoPagamenti.aspx)');
INSERT INTO verticalizzazioniparametribase (modulo, parametro, descrizione) VALUES ('NODO_PAGAMENTI','AR_URL_RITORNO','Usato da area riservata: Url di ritorno quando per comunicare l''esito di un pagamento terminato (es. ~/Reserved/InserimentoIstanza/pagamenti/VerificaStatoPagamentiNodoPagamenti.aspx)');
INSERT INTO verticalizzazioniparametribase (modulo, parametro, descrizione) VALUES ('NODO_PAGAMENTI','AR_COD_FISC_ENTE_CREDITORE','Usato da area riservata: Codice fiscale dell''ente creditore');

UPDATE COMUNI SET SIGLAPROVINCIA = 'FM', PROVINCIA = 'FERMO', CAP = '63824', CODICEISTAT = '109001' WHERE CODICECOMUNE = 'A233';
UPDATE COMUNI SET SIGLAPROVINCIA = 'FM', PROVINCIA = 'FERMO', CAP = '63857', CODICEISTAT = '109002' WHERE CODICECOMUNE = 'A252';
UPDATE COMUNI SET SIGLAPROVINCIA = 'FM', PROVINCIA = 'FERMO', CAP = '63838', CODICEISTAT = '109003' WHERE CODICECOMUNE = 'A760';
UPDATE COMUNI SET SIGLAPROVINCIA = 'FM', PROVINCIA = 'FERMO', CAP = '63828', CODICEISTAT = '109004' WHERE CODICECOMUNE = 'B534';
UPDATE COMUNI SET SIGLAPROVINCIA = 'FM', PROVINCIA = 'FERMO', CAP = '63837', CODICEISTAT = '109005' WHERE CODICECOMUNE = 'D477';
UPDATE COMUNI SET SIGLAPROVINCIA = 'FM', PROVINCIA = 'FERMO', CAP = '63900', CODICEISTAT = '109006' WHERE CODICECOMUNE = 'D542';
UPDATE COMUNI SET SIGLAPROVINCIA = 'FM', PROVINCIA = 'FERMO', CAP = '63816', CODICEISTAT = '109007' WHERE CODICECOMUNE = 'D760';
UPDATE COMUNI SET SIGLAPROVINCIA = 'FM', PROVINCIA = 'FERMO', CAP = '63844', CODICEISTAT = '109008' WHERE CODICECOMUNE = 'E208';
UPDATE COMUNI SET SIGLAPROVINCIA = 'FM', PROVINCIA = 'FERMO', CAP = '63823', CODICEISTAT = '109009' WHERE CODICECOMUNE = 'E447';
UPDATE COMUNI SET SIGLAPROVINCIA = 'FM', PROVINCIA = 'FERMO', CAP = '63832', CODICEISTAT = '109010' WHERE CODICECOMUNE = 'E807';
UPDATE COMUNI SET SIGLAPROVINCIA = 'FM', PROVINCIA = 'FERMO', CAP = '63834', CODICEISTAT = '109011' WHERE CODICECOMUNE = 'F021';
UPDATE COMUNI SET SIGLAPROVINCIA = 'FM', PROVINCIA = 'FERMO', CAP = '63842', CODICEISTAT = '109012' WHERE CODICECOMUNE = 'F379';
UPDATE COMUNI SET SIGLAPROVINCIA = 'FM', PROVINCIA = 'FERMO', CAP = '63835', CODICEISTAT = '109013' WHERE CODICECOMUNE = 'F428';
UPDATE COMUNI SET SIGLAPROVINCIA = 'FM', PROVINCIA = 'FERMO', CAP = '63855', CODICEISTAT = '109014' WHERE CODICECOMUNE = 'F493';
UPDATE COMUNI SET SIGLAPROVINCIA = 'FM', PROVINCIA = 'FERMO', CAP = '63858', CODICEISTAT = '109015' WHERE CODICECOMUNE = 'F509';
UPDATE COMUNI SET SIGLAPROVINCIA = 'FM', PROVINCIA = 'FERMO', CAP = '63846', CODICEISTAT = '109016' WHERE CODICECOMUNE = 'F517';
UPDATE COMUNI SET SIGLAPROVINCIA = 'FM', PROVINCIA = 'FERMO', CAP = '63833', CODICEISTAT = '109017' WHERE CODICECOMUNE = 'F520';
UPDATE COMUNI SET SIGLAPROVINCIA = 'FM', PROVINCIA = 'FERMO', CAP = '63812', CODICEISTAT = '109018' WHERE CODICECOMUNE = 'F522';
UPDATE COMUNI SET SIGLAPROVINCIA = 'FM', PROVINCIA = 'FERMO', CAP = '63841', CODICEISTAT = '109019' WHERE CODICECOMUNE = 'F536';
UPDATE COMUNI SET SIGLAPROVINCIA = 'FM', PROVINCIA = 'FERMO', CAP = '63853', CODICEISTAT = '109020' WHERE CODICECOMUNE = 'F549';
UPDATE COMUNI SET SIGLAPROVINCIA = 'FM', PROVINCIA = 'FERMO', CAP = '63852', CODICEISTAT = '109021' WHERE CODICECOMUNE = 'F599';
UPDATE COMUNI SET SIGLAPROVINCIA = 'FM', PROVINCIA = 'FERMO', CAP = '63825', CODICEISTAT = '109022' WHERE CODICECOMUNE = 'F614';
UPDATE COMUNI SET SIGLAPROVINCIA = 'FM', PROVINCIA = 'FERMO', CAP = '63815', CODICEISTAT = '109023' WHERE CODICECOMUNE = 'F626';
UPDATE COMUNI SET SIGLAPROVINCIA = 'FM', PROVINCIA = 'FERMO', CAP = '63813', CODICEISTAT = '109024' WHERE CODICECOMUNE = 'F653';
UPDATE COMUNI SET SIGLAPROVINCIA = 'FM', PROVINCIA = 'FERMO', CAP = '63847', CODICEISTAT = '109025' WHERE CODICECOMUNE = 'F664';
UPDATE COMUNI SET SIGLAPROVINCIA = 'FM', PROVINCIA = 'FERMO', CAP = '63836', CODICEISTAT = '109026' WHERE CODICECOMUNE = 'F665';
UPDATE COMUNI SET SIGLAPROVINCIA = 'FM', PROVINCIA = 'FERMO', CAP = '63843', CODICEISTAT = '109027' WHERE CODICECOMUNE = 'F697';
UPDATE COMUNI SET SIGLAPROVINCIA = 'FM', PROVINCIA = 'FERMO', CAP = '63826', CODICEISTAT = '109028' WHERE CODICECOMUNE = 'F722';
UPDATE COMUNI SET SIGLAPROVINCIA = 'FM', PROVINCIA = 'FERMO', CAP = '63851', CODICEISTAT = '109029' WHERE CODICECOMUNE = 'G137';
UPDATE COMUNI SET SIGLAPROVINCIA = 'FM', PROVINCIA = 'FERMO', CAP = '63827', CODICEISTAT = '109030' WHERE CODICECOMUNE = 'G403';
UPDATE COMUNI SET SIGLAPROVINCIA = 'FM', PROVINCIA = 'FERMO', CAP = '63848', CODICEISTAT = '109031' WHERE CODICECOMUNE = 'G516';
UPDATE COMUNI SET SIGLAPROVINCIA = 'FM', PROVINCIA = 'FERMO', CAP = '63845', CODICEISTAT = '109032' WHERE CODICECOMUNE = 'G873';
UPDATE COMUNI SET SIGLAPROVINCIA = 'FM', PROVINCIA = 'FERMO', CAP = '63822', CODICEISTAT = '109033' WHERE CODICECOMUNE = 'G920';
UPDATE COMUNI SET SIGLAPROVINCIA = 'FM', PROVINCIA = 'FERMO', CAP = '63821', CODICEISTAT = '109034' WHERE CODICECOMUNE = 'G921';
UPDATE COMUNI SET SIGLAPROVINCIA = 'FM', PROVINCIA = 'FERMO', CAP = '63831', CODICEISTAT = '109035' WHERE CODICECOMUNE = 'H182';
UPDATE COMUNI SET SIGLAPROVINCIA = 'FM', PROVINCIA = 'FERMO', CAP = '63854', CODICEISTAT = '109036' WHERE CODICECOMUNE = 'I315';
UPDATE COMUNI SET SIGLAPROVINCIA = 'FM', PROVINCIA = 'FERMO', CAP = '63811', CODICEISTAT = '109037' WHERE CODICECOMUNE = 'I324';
UPDATE COMUNI SET SIGLAPROVINCIA = 'FM', PROVINCIA = 'FERMO', CAP = '63839', CODICEISTAT = '109038' WHERE CODICECOMUNE = 'C070';
UPDATE COMUNI SET SIGLAPROVINCIA = 'FM', PROVINCIA = 'FERMO', CAP = '63856', CODICEISTAT = '109039' WHERE CODICECOMUNE = 'I774';
UPDATE COMUNI SET SIGLAPROVINCIA = 'FM', PROVINCIA = 'FERMO', CAP = '63814', CODICEISTAT = '109040' WHERE CODICECOMUNE = 'L279';


INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE(MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_ATTIVO', 'VERIFICA_DOCUMENTI_ISTANZA', 'Parametro utilizzato solamente in fase di protocollazione istanza in automatico; Valori: 0 o vuoto - non viene effettuato nessun controllo ( default ); 1 - verifica che non siano presenti righe di DOCUMENTIISTANZA senza aver valorizzato CODICEOGGETTO, se presenti viene sollevata una eccezione');


INSERT INTO verticalizzazioniparametribase (MODULO,PARAMETRO,DESCRIZIONE) VALUES ('AREA_RISERVATA','URL_VISURA_ISTANZA_CONSOLE','Url da utilizzare per effettuare la visura al termine della presentazione istanza tramite la console. Funziona a patto che: 1-La security utilizzata sia la stessa della console, 2-La console .net riesce a staccare un token applicativo con la stessa username e password sul comune in cui si fa la visura, 3-L''alias utilizzato dal comune su cui si fa la visura sia lo stesso utilizzato come sportello destinatario nei parametri di stc');

INSERT INTO VERTICALIZZAZIONIBASE (MODULO,DESCRIZIONE,FLAG_GESTCOMUNE) VALUES ('PROCEDI_MARCHE','Gestione dell''integrazione con i servizi regionali del portale ProcediMarche','0');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) VALUES ('PROCEDI_MARCHE','PROCEDI_MARCHE_URL','Rappresenta l''URI per raggiungere i WS di Procedi Marche');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROCEDI_MARCHE', 'PROCEDI_MARCHE_PWD', 'Password per l''autenticazione dei servizi');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROCEDI_MARCHE', 'PROCEDI_MARCHE_USR', 'Username per l''autenticazione dei servizi');

INSERT INTO CONTENTTYPES (CT_MIMETYPE, CT_EXTENSION) VALUES ('application/timestamp-reply', ';tsr;');
INSERT INTO CONTENTTYPES (CT_MIMETYPE, CT_EXTENSION) VALUES ('application/timestamped-data', ';tsd;');

INSERT INTO clmenu_java (
    id,
    descrizione,
    pagina,
    menulink,
    software,
    jsp,
    layouttesti,
    softwareesclusi,
    link_standard,
    tipo_funzionalita,
    menulink_v2
) VALUES (
    1042,
    'Categorie manifestazioni',
    'mercaticategorie/list.htm?software=SOFTWARE',
    '0AZ15',
    '*',
    'JAVA',
    '0',
    'AB,PR',
    'mercaticategorie/list.htm?software=SOFTWARE',
    'S',
    '0AZ15'
);


INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROCEDI_MARCHE', 'PROCEDI_MARCHE_CF_ENTE', 'Identificativo dell''ente da trasmettere con i dati del proecimento');