package it.gruppoinit.pal.gp.core.domain;

// default package
// Generated 22-ott-2009 11.57.38 by Hibernate Tools 3.2.5.Beta
import java.util.HashSet;
import java.util.Set;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Comuniassociati generated by hbm2java
 */
@Entity
@Table(name = "COMUNIASSOCIATI")
public class Comuniassociati implements java.io.Serializable {

    private static final long serialVersionUID = 8565054281597469304L;
    private ComuniassociatiId id;
    private Oggetti oggetti;
    private String siIntestazione1;
    private String siIntestazione2;
    private String siIntestazione3;
    private String siPdp1;
    private String siPdp2;
    private Comuni comune;
    private String codiceamministrazioneIpa;
    private String codicefiscale;
    private String codiceEntePayer;
    private Set<Comuniassociatisoftware> comuniassociatisoftwares = new HashSet<Comuniassociatisoftware>(0);

    public Comuniassociati() {

	this.id = new ComuniassociatiId();
    }

    public Comuniassociati(ComuniassociatiId id) {

	this.id = id;
    }

    @EmbeddedId
    @AttributeOverrides({ @AttributeOverride(name = "idcomune", column = @Column(name = "IDCOMUNE", nullable = false, length = 6)),
	    @AttributeOverride(name = "codicecomune", column = @Column(name = "CODICECOMUNE", nullable = false, length = 5)) })
    public ComuniassociatiId getId() {

	return this.id;
    }

    public void setId(ComuniassociatiId id) {

	this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumns({ @JoinColumn(name = "IDCOMUNE", referencedColumnName = "IDCOMUNE", nullable = false, insertable = false, updatable = false),
	    @JoinColumn(name = "SI_STEMMA", referencedColumnName = "CODICEOGGETTO", nullable = false, insertable = false, updatable = false) })
    public Oggetti getOggetti() {

	return this.oggetti;
    }

    public void setOggetti(Oggetti oggetti) {

	this.oggetti = oggetti;
    }

    @Column(name = "SI_INTESTAZIONE1", length = 100)
    public String getSiIntestazione1() {

	return this.siIntestazione1;
    }

    public void setSiIntestazione1(String siIntestazione1) {

	this.siIntestazione1 = siIntestazione1;
    }

    @Column(name = "SI_INTESTAZIONE2", length = 100)
    public String getSiIntestazione2() {

	return this.siIntestazione2;
    }

    public void setSiIntestazione2(String siIntestazione2) {

	this.siIntestazione2 = siIntestazione2;
    }

    @Column(name = "SI_INTESTAZIONE3", length = 100)
    public String getSiIntestazione3() {

	return this.siIntestazione3;
    }

    public void setSiIntestazione3(String siIntestazione3) {

	this.siIntestazione3 = siIntestazione3;
    }

    @Column(name = "SI_PDP1")
    public String getSiPdp1() {

	return this.siPdp1;
    }

    public void setSiPdp1(String siPdp1) {

	this.siPdp1 = siPdp1;
    }

    @Column(name = "SI_PDP2")
    public String getSiPdp2() {

	return this.siPdp2;
    }

    public void setSiPdp2(String siPdp2) {

	this.siPdp2 = siPdp2;
    }

    @Length(max = 20)
    @Column(name = "CODICEAMMINISTRAZIONE_IPA", length = 20)
    public String getCodiceamministrazioneIpa() {

	return codiceamministrazioneIpa;
    }

    public void setCodiceamministrazioneIpa(String codiceamministrazioneIpa) {

	this.codiceamministrazioneIpa = codiceamministrazioneIpa;
    }

    @Length(max = 11)
    @Column(name = "CODICEFISCALE", length = 11)
    public String getCodicefiscale() {

	return codicefiscale;
    }

    public void setCodicefiscale(String codicefiscale) {

	this.codicefiscale = codicefiscale;
    }

    @Length(max = 5)
    @Column(name = "CODICE_ENTE_PAYER", length = 5)
    public String getCodiceEntePayer() {

	return codiceEntePayer;
    }

    public void setCodiceEntePayer(String codiceEntePayer) {

	this.codiceEntePayer = codiceEntePayer;
    }

    @NotNull
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CODICECOMUNE", referencedColumnName = "CODICECOMUNE", nullable = false, insertable = false, updatable = false)
    public Comuni getComune() {

	return this.comune;
    }

    public void setComune(Comuni comune) {

	this.comune = comune;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "comuniassociati")
    public Set<Comuniassociatisoftware> getComuniassociatisoftwares() {

	return this.comuniassociatisoftwares;
    }

    public void setComuniassociatisoftwares(Set<Comuniassociatisoftware> comuniassociatisoftwares) {

	this.comuniassociatisoftwares = comuniassociatisoftwares;
    }
}
