package it.gruppoinit.pal.gp.core.domain;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Table;

import org.hibernate.annotations.Type;

/**
 * Dyn2ModelliScript generated by hbm2java
 */
@Entity
@Table(name = "DYN2_MODELLI_SCRIPT")
public class Dyn2ModelliScript implements java.io.Serializable {

    private static final long serialVersionUID = -8113200806843142095L;
    private Dyn2ModelliScriptId id;
    private byte[] script;

    public Dyn2ModelliScript() {

	this.id = new Dyn2ModelliScriptId();
    }

    @EmbeddedId
    @AttributeOverrides({ @AttributeOverride(name = "idcomune", column = @Column(name = "IDCOMUNE", nullable = false, length = 6)),
	    @AttributeOverride(name = "fkD2mtId", column = @Column(name = "FK_D2MT_ID", nullable = false, precision = 6, scale = 0)),
	    @AttributeOverride(name = "evento", column = @Column(name = "EVENTO", nullable = false, length = 15)) })
    public Dyn2ModelliScriptId getId() {

	return this.id;
    }

    public void setId(Dyn2ModelliScriptId id) {

	this.id = id;
    }

    @Column(name = "SCRIPT")
    @Basic(fetch = FetchType.LAZY)
    @Type(type = "org.springframework.orm.hibernate3.support.BlobByteArrayType")
    public byte[] getScript() {

	return script;
    }

    public void setScript(byte[] script) {

	this.script = script;
    }
}
