package it.gruppoinit.pal.gp.core.domain;

// Generated 22-dic-2008 16.40.09 by Hibernate Tools 3.2.4.CR1
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MercatiConfigurazione generated by hbm2java
 * 
 * @author fabrizioc
 */
@Entity
@Table(name = "MERCATI_CONFIGURAZIONE")
public class MercatiConfigurazione implements java.io.Serializable {

    private static final long serialVersionUID = 8360377257415924553L;
    private MercatiConfigurazioneId id;
    private Conti contoDefault;
    private Settori settori;
    private Software software;
    private Tipologiaregistri registroConcessioni;
    private Concessionitipi tipoConcessione;
    private Short durata;
    private String durataTipo;
    private Concessionicausali causaleConcessione;
    private Tipologiaregistri registroAutorizzazioni;
    private Letteretipo letteraTipo;
    private Dyn2Modellit dyn2Modellit;
    private Conti contoInteressi;
    private Dyn2Campi dyn2CampiByFkMerconfDyn2campiCm;
    private Dyn2Campi dyn2CampiByFkMerconfDyn2campiDa;
    private Dyn2Campi dyn2CampiByFkMerconfDyn2campiCa;
    private Dyn2Campi dyn2CampiByFkMerconfDyn2campiNa;
    private Dyn2Campi dyn2CampiByFkMerconfDyn2campiCodregaut;
    private String catMercUso;

    public MercatiConfigurazione() {

	this.id = new MercatiConfigurazioneId();
	this.contoDefault = new Conti();
	this.contoInteressi = new Conti();
	this.settori = new Settori();
	this.software = new Software();
	this.registroConcessioni = new Tipologiaregistri();
	this.tipoConcessione = new Concessionitipi();
	this.causaleConcessione = new Concessionicausali();
	this.registroAutorizzazioni = new Tipologiaregistri();
	this.letteraTipo = new Letteretipo();
	this.dyn2Modellit = new Dyn2Modellit();
	this.dyn2CampiByFkMerconfDyn2campiCm = new Dyn2Campi();
	this.dyn2CampiByFkMerconfDyn2campiDa = new Dyn2Campi();
	this.dyn2CampiByFkMerconfDyn2campiCa = new Dyn2Campi();
	this.dyn2CampiByFkMerconfDyn2campiNa = new Dyn2Campi();
	this.dyn2CampiByFkMerconfDyn2campiCodregaut = new Dyn2Campi();
    }

    @EmbeddedId
    @AttributeOverrides({ @AttributeOverride(name = "software", column = @Column(name = "SOFTWARE", nullable = false, length = 2)),
	    @AttributeOverride(name = "idcomune", column = @Column(name = "IDCOMUNE", nullable = false, length = 6)) })
    public MercatiConfigurazioneId getId() {

	return this.id;
    }

    public void setId(MercatiConfigurazioneId id) {

	this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumns({ @JoinColumn(name = "FK_CONTO_DEFAULT", referencedColumnName = "ID", insertable = false, updatable = false),
	    @JoinColumn(name = "IDCOMUNE", referencedColumnName = "IDCOMUNE", insertable = false, updatable = false) })
    public Conti getContoDefault() {

	return this.contoDefault;
    }

    public void setContoDefault(Conti contoDefault) {

	this.contoDefault = contoDefault;
    }

    // FIXME WORKAROUND PER AGGIORNAMENTO CHIAVI ESTERNE COMPOSITE///
    private Integer contoDefaultId;

    @Column(name = "FK_CONTO_DEFAULT")
    @SuppressWarnings("unused")
    private Integer getContoDefaultId() {

	if (null != this.getContoDefault()) {
	    if (null != this.getContoDefault().getId()) {
		this.contoDefaultId = getContoDefault().getId().getCodice();
		return this.contoDefaultId;
	    }
	}
	return null;
    }

    @SuppressWarnings("unused")
    private void setContoDefaultId(Integer contoDefaultId) {

	if (null != this.getContoDefault()) {
	    if (null != this.getContoDefault().getId()) {
		this.contoDefaultId = getContoDefault().getId().getCodice();
	    }
	}
    }

    // END FIX/////////////////////////////////////////////////////
    // END FIX/////////////////////////////////////////////////////
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumns({ @JoinColumn(name = "FK_CODICESETTORE", referencedColumnName = "CODICESETTORE", insertable = false, updatable = false),
	    @JoinColumn(name = "IDCOMUNE", referencedColumnName = "IDCOMUNE", insertable = false, updatable = false) })
    public Settori getSettori() {

	return this.settori;
    }

    public void setSettori(Settori settori) {

	this.settori = settori;
    }

    // FIXME WORKAROUND PER AGGIORNAMENTO CHIAVI ESTERNE COMPOSITE///
    private String codicesettore;

    @Column(name = "FK_CODICESETTORE")
    @SuppressWarnings("unused")
    private String getCodicesettoreId() {

	if (null != this.getSettori()) {
	    if (null != this.getSettori().getId()) {
		this.codicesettore = getSettori().getId().getCodicesettore();
		return this.codicesettore;
	    }
	}
	return null;
    }

    @SuppressWarnings("unused")
    private void setCodicesettoreId(String codicesettore) {

	if (null != this.getSettori()) {
	    if (null != this.getSettori().getId()) {
		this.codicesettore = getSettori().getId().getCodicesettore();
	    }
	}
    }

    // END FIX/////////////////////////////////////////////////////
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SOFTWARE", insertable = false, updatable = false)
    public Software getSoftware() {

	return this.software;
    }

    public void setSoftware(Software software) {

	this.software = software;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumns({ @JoinColumn(name = "FK_TRID_CON", referencedColumnName = "TR_ID", insertable = false, updatable = false),
	    @JoinColumn(name = "IDCOMUNE", referencedColumnName = "IDCOMUNE", insertable = false, updatable = false) })
    public Tipologiaregistri getRegistroConcessioni() {

	return registroConcessioni;
    }

    public void setRegistroConcessioni(Tipologiaregistri registroConcessioni) {

	this.registroConcessioni = registroConcessioni;
    }

    // FIXME WORKAROUND PER AGGIORNAMENTO CHIAVI ESTERNE COMPOSITE///
    private Integer registroConcessioniId;

    @Column(name = "FK_TRID_CON")
    @SuppressWarnings("unused")
    private Integer getRegistroConcessioniId() {

	if (null != this.getRegistroConcessioni()) {
	    if (null != this.getRegistroConcessioni().getId()) {
		this.registroConcessioniId = getRegistroConcessioni().getId().getCodice();
		return this.registroConcessioniId;
	    }
	}
	return null;
    }

    @SuppressWarnings("unused")
    private void setRegistroConcessioniId(Integer registroConcessioniId) {

	if (null != this.getRegistroConcessioni()) {
	    if (null != this.getRegistroConcessioni().getId()) {
		this.registroConcessioniId = getRegistroConcessioni().getId().getCodice();
	    }
	}
    }

    // END FIX/////////////////////////////////////////////////////
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "FK_TIPICONCESSIONE", referencedColumnName = "TIPOCONCESSIONE", insertable = false, updatable = false)
    public Concessionitipi getTipoConcessione() {

	return tipoConcessione;
    }

    public void setTipoConcessione(Concessionitipi tipoConcessione) {

	this.tipoConcessione = tipoConcessione;
    }

    // FIXME WORKAROUND PER AGGIORNAMENTO CHIAVI ESTERNE COMPOSITE///
    private String tipoConcessioneId;

    @Column(name = "FK_TIPICONCESSIONE")
    @SuppressWarnings("unused")
    private String getTipoConcessioneId() {

	if (null != this.getTipoConcessione()) {
	    if (null != this.getTipoConcessione().getTipoconcessione() && !this.getTipoConcessione().getTipoconcessione().equals("")) {
		this.tipoConcessioneId = getTipoConcessione().getTipoconcessione();
		return this.tipoConcessioneId;
	    }
	}
	return null;
    }

    @SuppressWarnings("unused")
    private void setTipoConcessioneId(String tipoConcessioneId) {

	if (null != this.getTipoConcessione()) {
	    if (null != this.getTipoConcessione().getTipoconcessione() && !this.getTipoConcessione().getTipoconcessione().equals("")) {
		this.tipoConcessioneId = getTipoConcessione().getTipoconcessione();
	    }
	}
    }

    // END FIX/////////////////////////////////////////////////////
    @Column(name = "DURATA", precision = 4, scale = 0)
    public Short getDurata() {

	return durata;
    }

    public void setDurata(Short durata) {

	this.durata = durata;
    }

    @Column(name = "DURATA_TIPO", length = 1)
    public String getDurataTipo() {

	return durataTipo;
    }

    public void setDurataTipo(String durataTipo) {

	this.durataTipo = durataTipo;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumns({ @JoinColumn(name = "FK_CODICECAUSALE", referencedColumnName = "CODICECAUSALE", insertable = false, updatable = false),
	    @JoinColumn(name = "IDCOMUNE", referencedColumnName = "IDCOMUNE", insertable = false, updatable = false) })
    public Concessionicausali getCausaleConcessione() {

	return causaleConcessione;
    }

    public void setCausaleConcessione(Concessionicausali causaleConcessione) {

	this.causaleConcessione = causaleConcessione;
    }

    // FIXME WORKAROUND PER AGGIORNAMENTO CHIAVI ESTERNE COMPOSITE///
    private Integer causaleConcessioneId;

    @Column(name = "FK_CODICECAUSALE")
    @SuppressWarnings("unused")
    private Integer getCausaleConcessioneId() {

	if (null != this.getCausaleConcessione()) {
	    if (null != this.getCausaleConcessione().getId()) {
		this.causaleConcessioneId = getCausaleConcessione().getId().getCodice();
		return this.causaleConcessioneId;
	    }
	}
	return null;
    }

    @SuppressWarnings("unused")
    private void setCausaleConcessioneId(Integer causaleConcessioneId) {

	if (null != this.getCausaleConcessione()) {
	    if (null != this.getCausaleConcessione().getId()) {
		this.causaleConcessioneId = getCausaleConcessione().getId().getCodice();
	    }
	}
    }

    // END FIX/////////////////////////////////////////////////////
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumns({ @JoinColumn(name = "FK_TRID_AUT", referencedColumnName = "TR_ID", insertable = false, updatable = false),
	    @JoinColumn(name = "IDCOMUNE", referencedColumnName = "IDCOMUNE", insertable = false, updatable = false) })
    public Tipologiaregistri getRegistroAutorizzazioni() {

	return registroAutorizzazioni;
    }

    public void setRegistroAutorizzazioni(Tipologiaregistri registroAutorizzazioni) {

	this.registroAutorizzazioni = registroAutorizzazioni;
    }

    // FIXME WORKAROUND PER AGGIORNAMENTO CHIAVI ESTERNE COMPOSITE///
    private Integer registroAutorizzazioniId;

    @Column(name = "FK_TRID_AUT")
    @SuppressWarnings("unused")
    private Integer getRegistroAutorizzazioniId() {

	if (null != this.getRegistroAutorizzazioni()) {
	    if (null != this.getRegistroAutorizzazioni().getId()) {
		this.registroAutorizzazioniId = getRegistroAutorizzazioni().getId().getCodice();
		return this.registroAutorizzazioniId;
	    }
	}
	return null;
    }

    @SuppressWarnings("unused")
    private void setRegistroAutorizzazioniId(Integer registroAutorizzazioniId) {

	if (null != this.getRegistroAutorizzazioni()) {
	    if (null != this.getRegistroAutorizzazioni().getId()) {
		this.registroAutorizzazioniId = getRegistroAutorizzazioni().getId().getCodice();
	    }
	}
    }

    // END FIX/////////////////////////////////////////////////////
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumns({ @JoinColumn(name = "FK_CODICELETTERA", referencedColumnName = "CODICELETTERA", insertable = false, updatable = false),
	    @JoinColumn(name = "IDCOMUNE", referencedColumnName = "IDCOMUNE", insertable = false, updatable = false) })
    public Letteretipo getLetteraTipo() {

	return letteraTipo;
    }

    public void setLetteraTipo(Letteretipo letteraTipo) {

	this.letteraTipo = letteraTipo;
    }

    // FIXME WORKAROUND PER AGGIORNAMENTO CHIAVI ESTERNE COMPOSITE///
    private Integer letteraTipoId;

    @Column(name = "FK_CODICELETTERA")
    @SuppressWarnings("unused")
    private Integer getLetteraTipoId() {

	if (null != this.getLetteraTipo()) {
	    if (null != this.getLetteraTipo().getId()) {
		this.letteraTipoId = getLetteraTipo().getId().getCodice();
		return this.letteraTipoId;
	    }
	}
	return null;
    }

    @SuppressWarnings("unused")
    private void setLetteraTipoId(Integer letteraTipoId) {

	if (null != this.getLetteraTipo()) {
	    if (null != this.getLetteraTipo().getId()) {
		this.letteraTipoId = getLetteraTipo().getId().getCodice();
	    }
	}
    }

    // END FIX/////////////////////////////////////////////////////
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumns({ @JoinColumn(name = "FK_DYN2MODELLIT", referencedColumnName = "ID", insertable = false, updatable = false),
	    @JoinColumn(name = "IDCOMUNE", referencedColumnName = "IDCOMUNE", insertable = false, updatable = false) })
    public Dyn2Modellit getDyn2Modellit() {

	return dyn2Modellit;
    }

    public void setDyn2Modellit(Dyn2Modellit dyn2Modellit) {

	this.dyn2Modellit = dyn2Modellit;
    }

    // FIXME WORKAROUND PER AGGIORNAMENTO CHIAVI ESTERNE COMPOSITE///
    private Integer dyn2modellitId;

    @Column(name = "FK_DYN2MODELLIT")
    @SuppressWarnings("unused")
    private Integer getDyn2ModellitId() {

	if (null != this.getDyn2Modellit()) {
	    if (null != this.getDyn2Modellit().getId()) {
		this.dyn2modellitId = getDyn2Modellit().getId().getCodice();
		return this.dyn2modellitId;
	    }
	}
	return null;
    }

    @SuppressWarnings("unused")
    private void setDyn2ModellitId(Integer dyn2modellitId) {

	if (null != this.getDyn2Modellit()) {
	    if (null != this.getDyn2Modellit().getId()) {
		this.dyn2modellitId = getDyn2Modellit().getId().getCodice();
	    }
	}
    }

    // END FIX/////////////////////////////////////////////////////
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumns({ @JoinColumn(name = "FK_CONTO_INTERESSI", referencedColumnName = "ID", insertable = false, updatable = false),
	    @JoinColumn(name = "IDCOMUNE", referencedColumnName = "IDCOMUNE", insertable = false, updatable = false) })
    public Conti getContoInteressi() {

	return this.contoInteressi;
    }

    public void setContoInteressi(Conti contoInteressi) {

	this.contoInteressi = contoInteressi;
    }

    // FIXME WORKAROUND PER AGGIORNAMENTO CHIAVI ESTERNE COMPOSITE///
    private Integer contoInteressiId;

    @Column(name = "FK_CONTO_INTERESSI")
    @SuppressWarnings("unused")
    private Integer getContoInteressiId() {

	if (null != this.getContoInteressi()) {
	    if (null != this.getContoInteressi().getId()) {
		this.contoInteressiId = getContoInteressi().getId().getCodice();
		return this.contoInteressiId;
	    }
	}
	return null;
    }

    @SuppressWarnings("unused")
    private void setContoInteressiId(Integer contoInteressiId) {

	if (null != this.getContoInteressi()) {
	    if (null != this.getContoInteressi().getId()) {
		this.contoInteressiId = getContoInteressi().getId().getCodice();
	    }
	}
    }

    // END FIX/////////////////////////////////////////////////////
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumns({ @JoinColumn(name = "IDCOMUNE", referencedColumnName = "IDCOMUNE", insertable = false, updatable = false),
	    @JoinColumn(name = "FK_D2CID_CAT_MERC", referencedColumnName = "ID", insertable = false, updatable = false) })
    public Dyn2Campi getDyn2CampiByFkMerconfDyn2campiCm() {

	return this.dyn2CampiByFkMerconfDyn2campiCm;
    }

    public void setDyn2CampiByFkMerconfDyn2campiCm(Dyn2Campi dyn2CampiByFkMerconfDyn2campiCm) {

	this.dyn2CampiByFkMerconfDyn2campiCm = dyn2CampiByFkMerconfDyn2campiCm;
    }

    // FIXME WORKAROUND PER AGGIORNAMENTO CHIAVI ESTERNE COMPOSITE///
    private Integer dyn2CampiByFkMerconfDyn2campiCmId;

    @Column(name = "FK_D2CID_CAT_MERC")
    @SuppressWarnings("unused")
    private Integer getDyn2CampiByFkMerconfDyn2campiCmId() {

	if (null != this.getDyn2CampiByFkMerconfDyn2campiCm()) {
	    if (null != this.getDyn2CampiByFkMerconfDyn2campiCm().getId()) {
		this.dyn2CampiByFkMerconfDyn2campiCmId = getDyn2CampiByFkMerconfDyn2campiCm().getId().getCodice();
		return this.dyn2CampiByFkMerconfDyn2campiCmId;
	    }
	}
	return null;
    }

    @SuppressWarnings("unused")
    private void setDyn2CampiByFkMerconfDyn2campiCmId(Integer dyn2CampiByFkMerconfDyn2campiCmId) {

	if (null != this.getDyn2CampiByFkMerconfDyn2campiCm()) {
	    if (null != this.getDyn2CampiByFkMerconfDyn2campiCm().getId()) {
		this.dyn2CampiByFkMerconfDyn2campiCmId = getDyn2CampiByFkMerconfDyn2campiCm().getId().getCodice();
	    }
	}
    }

    // END FIX/////////////////////////////////////////////////////
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumns({ @JoinColumn(name = "IDCOMUNE", referencedColumnName = "IDCOMUNE", insertable = false, updatable = false),
	    @JoinColumn(name = "FK_D2CID_DATA_AUT", referencedColumnName = "ID", insertable = false, updatable = false) })
    public Dyn2Campi getDyn2CampiByFkMerconfDyn2campiDa() {

	return this.dyn2CampiByFkMerconfDyn2campiDa;
    }

    public void setDyn2CampiByFkMerconfDyn2campiDa(Dyn2Campi dyn2CampiByFkMerconfDyn2campiDa) {

	this.dyn2CampiByFkMerconfDyn2campiDa = dyn2CampiByFkMerconfDyn2campiDa;
    }

    // FIXME WORKAROUND PER AGGIORNAMENTO CHIAVI ESTERNE COMPOSITE///
    private Integer dyn2CampiByFkMerconfDyn2campiDaId;

    @Column(name = "FK_D2CID_DATA_AUT")
    @SuppressWarnings("unused")
    private Integer getDyn2CampiByFkMerconfDyn2campiDaId() {

	if (null != this.getDyn2CampiByFkMerconfDyn2campiDa()) {
	    if (null != this.getDyn2CampiByFkMerconfDyn2campiDa().getId()) {
		this.dyn2CampiByFkMerconfDyn2campiDaId = getDyn2CampiByFkMerconfDyn2campiDa().getId().getCodice();
		return this.dyn2CampiByFkMerconfDyn2campiDaId;
	    }
	}
	return null;
    }

    @SuppressWarnings("unused")
    private void setDyn2CampiByFkMerconfDyn2campiDaId(Integer dyn2CampiByFkMerconfDyn2campiDaId) {

	if (null != this.getDyn2CampiByFkMerconfDyn2campiDa()) {
	    if (null != this.getDyn2CampiByFkMerconfDyn2campiDa().getId()) {
		this.dyn2CampiByFkMerconfDyn2campiDaId = getDyn2CampiByFkMerconfDyn2campiDa().getId().getCodice();
	    }
	}
    }

    // END FIX/////////////////////////////////////////////////////
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumns({ @JoinColumn(name = "IDCOMUNE", referencedColumnName = "IDCOMUNE", insertable = false, updatable = false),
	    @JoinColumn(name = "FK_D2CID_COMUNE_AUT", referencedColumnName = "ID", insertable = false, updatable = false) })
    public Dyn2Campi getDyn2CampiByFkMerconfDyn2campiCa() {

	return this.dyn2CampiByFkMerconfDyn2campiCa;
    }

    public void setDyn2CampiByFkMerconfDyn2campiCa(Dyn2Campi dyn2CampiByFkMerconfDyn2campiCa) {

	this.dyn2CampiByFkMerconfDyn2campiCa = dyn2CampiByFkMerconfDyn2campiCa;
    }

    // FIXME WORKAROUND PER AGGIORNAMENTO CHIAVI ESTERNE COMPOSITE///
    private Integer dyn2CampiByFkMerconfDyn2campiCaId;

    @Column(name = "FK_D2CID_COMUNE_AUT")
    @SuppressWarnings("unused")
    private Integer getDyn2CampiByFkMerconfDyn2campiCaId() {

	if (null != this.getDyn2CampiByFkMerconfDyn2campiCa()) {
	    if (null != this.getDyn2CampiByFkMerconfDyn2campiCa().getId()) {
		this.dyn2CampiByFkMerconfDyn2campiCaId = getDyn2CampiByFkMerconfDyn2campiCa().getId().getCodice();
		return this.dyn2CampiByFkMerconfDyn2campiCaId;
	    }
	}
	return null;
    }

    @SuppressWarnings("unused")
    private void setDyn2CampiByFkMerconfDyn2campiCaId(Integer dyn2CampiByFkMerconfDyn2campiCaId) {

	if (null != this.getDyn2CampiByFkMerconfDyn2campiCa()) {
	    if (null != this.getDyn2CampiByFkMerconfDyn2campiCa().getId()) {
		this.dyn2CampiByFkMerconfDyn2campiCaId = getDyn2CampiByFkMerconfDyn2campiCa().getId().getCodice();
	    }
	}
    }

    // END FIX/////////////////////////////////////////////////////
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumns({ @JoinColumn(name = "IDCOMUNE", referencedColumnName = "IDCOMUNE", insertable = false, updatable = false),
	    @JoinColumn(name = "FK_D2CID_NUM_AUT", referencedColumnName = "ID", insertable = false, updatable = false) })
    public Dyn2Campi getDyn2CampiByFkMerconfDyn2campiNa() {

	return this.dyn2CampiByFkMerconfDyn2campiNa;
    }

    public void setDyn2CampiByFkMerconfDyn2campiNa(Dyn2Campi dyn2CampiByFkMerconfDyn2campiNa) {

	this.dyn2CampiByFkMerconfDyn2campiNa = dyn2CampiByFkMerconfDyn2campiNa;
    }

    // FIXME WORKAROUND PER AGGIORNAMENTO CHIAVI ESTERNE COMPOSITE///
    private Integer dyn2CampiByFkMerconfDyn2campiNaId;

    @Column(name = "FK_D2CID_NUM_AUT")
    @SuppressWarnings("unused")
    private Integer getDyn2CampiByFkMerconfDyn2campiNaId() {

	if (null != this.getDyn2CampiByFkMerconfDyn2campiNa()) {
	    if (null != this.getDyn2CampiByFkMerconfDyn2campiNa().getId()) {
		this.dyn2CampiByFkMerconfDyn2campiNaId = getDyn2CampiByFkMerconfDyn2campiNa().getId().getCodice();
		return this.dyn2CampiByFkMerconfDyn2campiNaId;
	    }
	}
	return null;
    }

    @SuppressWarnings("unused")
    private void setDyn2CampiByFkMerconfDyn2campiNaId(Integer dyn2CampiByFkMerconfDyn2campiNaId) {

	if (null != this.getDyn2CampiByFkMerconfDyn2campiNa()) {
	    if (null != this.getDyn2CampiByFkMerconfDyn2campiNa().getId()) {
		this.dyn2CampiByFkMerconfDyn2campiNaId = getDyn2CampiByFkMerconfDyn2campiNa().getId().getCodice();
	    }
	}
    }

    // END FIX/////////////////////////////////////////////////////
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumns({ @JoinColumn(name = "IDCOMUNE", referencedColumnName = "IDCOMUNE", insertable = false, updatable = false),
	    @JoinColumn(name = "FK_D2CID_COD_REG_AUT", referencedColumnName = "ID", insertable = false, updatable = false) })
    public Dyn2Campi getDyn2CampiByFkMerconfDyn2campiCodregaut() {

	return this.dyn2CampiByFkMerconfDyn2campiCodregaut;
    }

    public void setDyn2CampiByFkMerconfDyn2campiCodregaut(Dyn2Campi dyn2CampiByFkMerconfDyn2campiCodregaut) {

	this.dyn2CampiByFkMerconfDyn2campiCodregaut = dyn2CampiByFkMerconfDyn2campiCodregaut;
    }

    // FIXME WORKAROUND PER AGGIORNAMENTO CHIAVI ESTERNE COMPOSITE///
    private Integer dyn2CampiByFkMerconfDyn2campiCodregautId;

    @Column(name = "FK_D2CID_COD_REG_AUT")
    @SuppressWarnings("unused")
    private Integer getDyn2CampiByFkMerconfDyn2campiCodregautId() {

	if (null != this.getDyn2CampiByFkMerconfDyn2campiCodregaut()) {
	    if (null != this.getDyn2CampiByFkMerconfDyn2campiCodregaut().getId()) {
		this.dyn2CampiByFkMerconfDyn2campiCodregautId = getDyn2CampiByFkMerconfDyn2campiCodregaut().getId().getCodice();
		return this.dyn2CampiByFkMerconfDyn2campiCodregautId;
	    }
	}
	return null;
    }

    @SuppressWarnings("unused")
    private void setDyn2CampiByFkMerconfDyn2campiCodregautId(Integer dyn2CampiByFkMerconfDyn2campiCodregautId) {

	if (null != this.getDyn2CampiByFkMerconfDyn2campiCodregaut()) {
	    if (null != this.getDyn2CampiByFkMerconfDyn2campiCodregaut().getId()) {
		this.dyn2CampiByFkMerconfDyn2campiCodregautId = getDyn2CampiByFkMerconfDyn2campiCodregaut().getId().getCodice();
	    }
	}
    }

    // END FIX/////////////////////////////////////////////////////
    @Column(name = "CAT_MERC_USO", length = 2)
    public String getCatMercUso() {

	return this.catMercUso;
    }

    public void setCatMercUso(String catMercUso) {

	this.catMercUso = catMercUso;
    }
}
