package it.gruppoinit.pal.gp.core.domain;

// Generated 27-feb-2009 13.16.36 by Hibernate Tools 3.2.4.CR1
import it.gruppoinit.pal.gp.core.dao.helper.PkIdGenerator;
import it.gruppoinit.pal.gp.core.domain.web.MetadatiBean;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.annotations.Type;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotEmpty;

/*
 * Oggetti generated by hbm2java
 */
@Entity
@Table(name = "OGGETTI")
public class Oggetti implements java.io.Serializable {

    private static final long serialVersionUID = 2822747568398325402L;
    private PkId id;
    private String nomefile;
    private String percorso;
    private byte[] oggetto;
    private Integer dimensioneFile;
    private byte[] nonUsareContenutoBLOB;
    private List<MetadatiBean> metadatiTransient = new ArrayList<MetadatiBean>();

    public Oggetti() {

	this.id = new PkId();
    }

    public Oggetti(PkId id) {

	this.id = id;
    }

    @EmbeddedId
    @GenericGenerator(name = "pkGenerator", strategy = "it.gruppoinit.pal.gp.core.dao.helper.PkIdGenerator", parameters = {
	    @Parameter(name = PkIdGenerator.CONFIG_PREFER_SEGMENT_PER_ENTITY, value = "true"),
	    @Parameter(name = PkIdGenerator.TABLE_PARAM, value = "SEQUENCETABLE"),
	    @Parameter(name = PkIdGenerator.VALUE_COLUMN_PARAM, value = "CURRVAL"),
	    @Parameter(name = PkIdGenerator.SEGMENT_COLUMN_PARAM, value = "SEQUENCENAME"),
	    @Parameter(name = PkIdGenerator.SEGMENT_VALUE_PARAM, value = "OGGETTI.CODICEOGGETTO") })
    @GeneratedValue(generator = "pkGenerator")
    @AttributeOverrides({ @AttributeOverride(name = "idcomune", column = @Column(name = "IDCOMUNE", nullable = false, length = 6)),
	    @AttributeOverride(name = "codice", column = @Column(name = "CODICEOGGETTO", nullable = false, precision = 10, scale = 0)) })
    public PkId getId() {

	return this.id;
    }

    public void setId(PkId id) {

	this.id = id;
    }

    @NotEmpty
    @Length(max = 256)
    @Column(name = "NOMEFILE", length = 256)
    public String getNomefile() {

	return this.nomefile;
    }

    public void setNomefile(String nomefile) {

	this.nomefile = nomefile;
    }

    @Column(name = "OGGETTO")
    @Basic(fetch = FetchType.LAZY)
    @Type(type = "org.springframework.orm.hibernate3.support.BlobByteArrayType")
    public byte[] getNonUsareContenutoBLOB() {

	return nonUsareContenutoBLOB;
    }

    public void setNonUsareContenutoBLOB(byte[] nonUsareContenutoBLOB) {

	this.nonUsareContenutoBLOB = nonUsareContenutoBLOB;
    }

    @Transient
    public byte[] getOggetto() {

	return this.oggetto;
    }

    public void setOggetto(byte[] oggetto) {

	this.oggetto = oggetto;
    }

    @Column(name = "DIMENSIONE_FILE", precision = 9, scale = 0)
    public Integer getDimensioneFile() {

	return dimensioneFile;
    }

    public void setDimensioneFile(Integer dimensioneFile) {

	this.dimensioneFile = dimensioneFile;
    }

    @Transient
    private String getDimensioneFileInBytes() {

	if (null == this.dimensioneFile) {
	    return "";
	}
	return String.valueOf(this.dimensioneFile) + " Bytes ";
    }

    @Transient
    private String getDimensioneFileInKb() {

	if (null == this.dimensioneFile) {
	    return "";
	}
	return String.valueOf(this.dimensioneFile / 1000) + " Kb ";
    }

    @Transient
    private String getDimensioneFileInMb() {

	if (null == this.dimensioneFile) {
	    return "";
	}
	return String.valueOf(this.dimensioneFile / 1000000) + " Mb ";
    }

    @Transient
    public String getDimensioneFileLeggibile() {

	if (null == this.dimensioneFile) {
	    return "";
	}
	if (this.dimensioneFile < 1000) {
	    return getDimensioneFileInBytes();
	} else if (this.dimensioneFile < 1000000) {
	    return getDimensioneFileInKb();
	} else {
	    return getDimensioneFileInMb();
	}
    }

    /**
     * @return the percorso
     */
    @Length(max = 128)
    @Column(name = "PERCORSO", length = 128)
    public String getPercorso() {

	return percorso;
    }

    /**
     * @param percorso
     *            the percorso to set
     */
    public void setPercorso(String percorso) {

	this.percorso = percorso;
    }

    @Transient
    public List<MetadatiBean> getMetadatiTransient() {

	return metadatiTransient;
    }

    public void setMetadatiTransient(List<MetadatiBean> metadatiTransient) {

	this.metadatiTransient = metadatiTransient;
    }
}
