package it.gruppoinit.pal.gp.core.domain;

import it.gruppoinit.pal.gp.core.dao.helper.PkIdGenerator;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.validator.Length;
import org.hibernate.validator.Pattern;

/**
 * Tipiorariodettaglio generated by hbm2java
 */
@Entity
@Table(name = "TIPIORARIODETTAGLIO")
public class Tipiorariodettaglio implements java.io.Serializable {

    private static final long serialVersionUID = -4252946426882769303L;
    private PkId id;
    private Tipiapertura tipiapertura;
    private Tipiorario tipiorario;
    private Giornisettimana giornisectimana;
    private String oaDalleore;
    private String oaAlleore;
    private String oaDalleorepom;
    private String oaAlleorepom;
    private String oaDatainizio; // Dismesso
    private String oaDatafine; // Dismesso	

    public Tipiorariodettaglio() {

	this.id = new PkId();
	this.giornisectimana = new Giornisettimana();
	this.tipiorario = new Tipiorario();
	this.tipiapertura = new Tipiapertura();
    }

    @EmbeddedId
    @GenericGenerator(name = "pkGenerator", strategy = "it.gruppoinit.pal.gp.core.dao.helper.PkIdGenerator", parameters = {
	    @Parameter(name = PkIdGenerator.CONFIG_PREFER_SEGMENT_PER_ENTITY, value = "true"),
	    @Parameter(name = PkIdGenerator.TABLE_PARAM, value = "SEQUENCETABLE"),
	    @Parameter(name = PkIdGenerator.VALUE_COLUMN_PARAM, value = "CURRVAL"),
	    @Parameter(name = PkIdGenerator.SEGMENT_COLUMN_PARAM, value = "SEQUENCENAME"),
	    @Parameter(name = PkIdGenerator.SEGMENT_VALUE_PARAM, value = "TIPIORARIODETTAGLIO.OA_ID") })
    @GeneratedValue(generator = "pkGenerator")
    @AttributeOverrides({ @AttributeOverride(name = "idcomune", column = @Column(name = "IDCOMUNE", nullable = false, length = 6)),
	    @AttributeOverride(name = "codice", column = @Column(name = "OA_ID", nullable = false, precision = 6, scale = 0)) })
    public PkId getId() {

	return this.id;
    }

    public void setId(PkId id) {

	this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumns({ @JoinColumn(name = "IDCOMUNE", referencedColumnName = "IDCOMUNE", nullable = false, insertable = false, updatable = false),
	    @JoinColumn(name = "OA_FKIDORARIO", referencedColumnName = "TA_ID", nullable = false, insertable = false, updatable = false) })
    public Tipiapertura getTipiapertura() {

	return this.tipiapertura;
    }

    public void setTipiapertura(Tipiapertura tipiapertura) {

	this.tipiapertura = tipiapertura;
    }

    // FIXME WORKAROUND PER AGGIORNAMENTO CHIAVI ESTERNE COMPOSITE///
    private Integer tipiaperturaId;

    @Column(name = "OA_FKIDORARIO")
    @SuppressWarnings("unused")
    private Integer getTipiaperturaId() {

	if (null != this.getTipiapertura()) {
	    if (null != this.getTipiapertura().getId()) {
		this.tipiaperturaId = getTipiapertura().getId().getCodice();
		return this.tipiaperturaId;
	    }
	}
	return null;
    }

    @SuppressWarnings("unused")
    private void setTipiaperturaId(Integer tipiaperturaId) {

	if (null != this.getTipiapertura()) {
	    if (null != this.getTipiapertura().getId()) {
		this.tipiaperturaId = getTipiapertura().getId().getCodice();
	    }
	}
    }

    // END FIX/////////////////////////////////////////////////////
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumns({ @JoinColumn(name = "IDCOMUNE", referencedColumnName = "IDCOMUNE", nullable = false, insertable = false, updatable = false),
	    @JoinColumn(name = "OA_FKIDTIPORARIO", referencedColumnName = "TO_ID", nullable = false, insertable = false, updatable = false) })
    public Tipiorario getTipiorario() {

	return this.tipiorario;
    }

    public void setTipiorario(Tipiorario tipiorario) {

	this.tipiorario = tipiorario;
    }

    // FIXME WORKAROUND PER AGGIORNAMENTO CHIAVI ESTERNE COMPOSITE///
    private Integer tipiorarioId;

    @Column(name = "OA_FKIDTIPORARIO")
    @SuppressWarnings("unused")
    private Integer getTipiorarioId() {

	if (null != this.getTipiorario()) {
	    if (null != this.getTipiorario().getId()) {
		this.tipiorarioId = getTipiorario().getId().getCodice();
		return this.tipiorarioId;
	    }
	}
	return null;
    }

    @SuppressWarnings("unused")
    private void setTipiorarioId(Integer tipiorarioId) {

	if (null != this.getTipiorario()) {
	    if (null != this.getTipiorario().getId()) {
		this.tipiorarioId = getTipiorario().getId().getCodice();
	    }
	}
    }

    // END FIX/////////////////////////////////////////////////////
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "OA_FKIDGIORNO", referencedColumnName = "GS_ID", nullable = false)
    public Giornisettimana getGiornisectimana() {

	return giornisectimana;
    }

    public void setGiornisectimana(Giornisettimana giornisectimana) {

	this.giornisectimana = giornisectimana;
    }

    @Pattern(regex = "((([0-1][0-9])|([2-2][0-4]))\\:([0-5][0-9]))*", message = "{validator.hour}")
    @Length(max = 5)
    @Column(name = "OA_DALLEORE", length = 5)
    public String getOaDalleore() {

	return this.oaDalleore;
    }

    public void setOaDalleore(String oaDalleore) {

	this.oaDalleore = oaDalleore;
    }

    @Pattern(regex = "((([0-1][0-9])|([2-2][0-4]))\\:([0-5][0-9]))*", message = "{validator.hour}")
    @Length(max = 5)
    @Column(name = "OA_ALLEORE", length = 5)
    public String getOaAlleore() {

	return this.oaAlleore;
    }

    public void setOaAlleore(String oaAlleore) {

	this.oaAlleore = oaAlleore;
    }

    @Pattern(regex = "((([0-1][0-9])|([2-2][0-4]))\\:([0-5][0-9]))*", message = "{validator.hour}")
    @Length(max = 5)
    @Column(name = "OA_DALLEOREPOM", length = 5)
    public String getOaDalleorepom() {

	return this.oaDalleorepom;
    }

    public void setOaDalleorepom(String oaDalleorepom) {

	this.oaDalleorepom = oaDalleorepom;
    }

    @Pattern(regex = "((([0-1][0-9])|([2-2][0-4]))\\:([0-5][0-9]))*", message = "{validator.hour}")
    @Length(max = 5)
    @Column(name = "OA_ALLEOREPOM", length = 5)
    public String getOaAlleorepom() {

	return this.oaAlleorepom;
    }

    public void setOaAlleorepom(String oaAlleorepom) {

	this.oaAlleorepom = oaAlleorepom;
    }

    @Column(name = "OA_DATAINIZIO", length = 8)
    public String getOaDatainizio() {

	return this.oaDatainizio;
    }

    public void setOaDatainizio(String oaDatainizio) {

	this.oaDatainizio = oaDatainizio;
    }

    @Column(name = "OA_DATAFINE", length = 8)
    public String getOaDatafine() {

	return this.oaDatafine;
    }

    public void setOaDatafine(String oaDatafine) {

	this.oaDatafine = oaDatafine;
    }
}
