package it.gruppoinit.pal.gp.core.domain;

import it.gruppoinit.pal.gp.core.dao.helper.PkIdGenerator;

import java.math.BigDecimal;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.validator.Max;

/**
 * Tipicausalioninteressi generated by hbm2java
 */
@Entity
@Table(name = "TIPICAUSALIONINTERESSI")
public class Tipicausalioninteressi implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 5341751806229156028L;
    private PkId id;
    private Tipicausalioneri tipicausalioneri;
    private Integer ggritardopagamento;
    private BigDecimal percentuale;
    private Integer ggritardopagamentoPrecedente;

    public Tipicausalioninteressi() {

	this.id = new PkId();
	this.tipicausalioneri = new Tipicausalioneri();
	this.ggritardopagamentoPrecedente = new Integer(0);
	this.percentuale = new BigDecimal(0).setScale(5);
    }

    @EmbeddedId
    @GenericGenerator(name = "pkGenerator", strategy = "it.gruppoinit.pal.gp.core.dao.helper.PkIdGenerator", parameters = {
	    @Parameter(name = PkIdGenerator.CONFIG_PREFER_SEGMENT_PER_ENTITY, value = "true"),
	    @Parameter(name = PkIdGenerator.TABLE_PARAM, value = "SEQUENCETABLE"),
	    @Parameter(name = PkIdGenerator.VALUE_COLUMN_PARAM, value = "CURRVAL"),
	    @Parameter(name = PkIdGenerator.SEGMENT_COLUMN_PARAM, value = "SEQUENCENAME"),
	    @Parameter(name = PkIdGenerator.SEGMENT_VALUE_PARAM, value = "TIPICAUSALIONINTERESSI.ID") })
    @GeneratedValue(generator = "pkGenerator")
    @AttributeOverrides({ @AttributeOverride(name = "idcomune", column = @Column(name = "IDCOMUNE", nullable = false, length = 6)),
	    @AttributeOverride(name = "codice", column = @Column(name = "ID", nullable = false, precision = 8, scale = 0)) })
    public PkId getId() {

	return this.id;
    }

    public void setId(PkId id) {

	this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumns({ @JoinColumn(name = "IDCOMUNE", referencedColumnName = "IDCOMUNE", nullable = false, insertable = false, updatable = false),
	    @JoinColumn(name = "FK_IDTIPOCAUSALE", referencedColumnName = "CO_ID", nullable = false, insertable = false, updatable = false) })
    public Tipicausalioneri getTipicausalioneri() {

	return this.tipicausalioneri;
    }

    public void setTipicausalioneri(Tipicausalioneri tipicausalioneri) {

	this.tipicausalioneri = tipicausalioneri;
    }

    //FIXME WORKAROUND PER AGGIORNAMENTO CHIAVI ESTERNE COMPOSITE///
    private Integer tipicausalioneriId;

    @Column(name = "FK_IDTIPOCAUSALE")
    @SuppressWarnings("unused")
    private Integer getTipicausalioneriId() {

	if (null != this.getTipicausalioneri()) {
	    if (null != this.getTipicausalioneri().getId()) {
		this.tipicausalioneriId = getTipicausalioneri().getId().getCodice();
		return this.tipicausalioneriId;
	    }
	}
	return null;
    }

    @SuppressWarnings("unused")
    private void setTipicausalioneriId(Integer tipicausalioneriId) {

	if (null != this.getTipicausalioneri()) {
	    if (null != this.getTipicausalioneri().getId()) {
		this.tipicausalioneriId = getTipicausalioneri().getId().getCodice();
	    }
	}
    }

    //END FIX/////////////////////////////////////////////////////
    // @NotNull (fatta una bussiness validation)
    @Max(value = 9999)
    @Column(name = "GGRITARDOPAGAMENTO", nullable = false, precision = 4, scale = 0)
    public Integer getGgritardopagamento() {

	return this.ggritardopagamento;
    }

    public void setGgritardopagamento(Integer ggritardopagamento) {

	this.ggritardopagamento = ggritardopagamento;
    }

    // @NotNull (fatta una bussiness validation)
    @Max(value = 9999)
    @Column(name = "PERCENTUALE", nullable = false, precision = 8, scale = 5)
    public BigDecimal getPercentuale() {

	return this.percentuale;
    }

    public void setPercentuale(BigDecimal percentuale) {

	this.percentuale = percentuale;
    }

    @Transient
    public Integer getGgritardopagamentoPrecedente() {

	return ggritardopagamentoPrecedente;
    }

    public void setGgritardopagamentoPrecedente(Integer ggritardopagamentoPrecedente) {

	this.ggritardopagamentoPrecedente = ggritardopagamentoPrecedente;
    }
}
