package it.gruppoinit.pal.gp.core.domain;

// Generated 2-set-2009 11.30.38 by Hibernate Tools 3.2.4.CR1
import it.gruppoinit.pal.gp.core.dao.helper.PkIdGenerator;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.StringUtils;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.validator.Length;
import org.hibernate.validator.Max;
import org.hibernate.validator.NotEmpty;

/*
 * Tipisoggetto generated by hbm2java
 */
@Entity
@Table(name = "TIPISOGGETTO")
public class Tipisoggetto implements java.io.Serializable {

    private static final long serialVersionUID = -7530720398412187855L;
    private PkId id;
    private String tiposoggetto;
    private Software software;
    private Boolean flagqualita;
    private String utilizzo;
    private String tipoanagrafe;
    private String tipodato;
    private Boolean foObbligatorio;
    private Boolean richiedianagrafecoll;
    private Boolean flgDatialbo;
    private Boolean flgSpecificadescrizione;
    private Boolean flgLegalerap;
    private Integer ordine;
    private RiCariche riCariche;
    private Integer atribQualificasoggetto;
    //    private Set<Tipisoggettopeople> tipisoggettopeoples = new HashSet<Tipisoggettopeople>(0);
    private Set<AlberoprocTipisoggetto> alberoprocTipisoggettos = new HashSet<AlberoprocTipisoggetto>(0);
    private String tipisoggettipeopleTransient;

    public Tipisoggetto() {

	this.id = new PkId();
	this.software = new Software();
	this.riCariche = new RiCariche();
    }

    @EmbeddedId
    @GenericGenerator(name = "pkGenerator", strategy = "it.gruppoinit.pal.gp.core.dao.helper.PkIdGenerator", parameters = {
	    @Parameter(name = PkIdGenerator.CONFIG_PREFER_SEGMENT_PER_ENTITY, value = "true"),
	    @Parameter(name = PkIdGenerator.TABLE_PARAM, value = "SEQUENCETABLE"),
	    @Parameter(name = PkIdGenerator.VALUE_COLUMN_PARAM, value = "CURRVAL"),
	    @Parameter(name = PkIdGenerator.SEGMENT_COLUMN_PARAM, value = "SEQUENCENAME"),
	    @Parameter(name = PkIdGenerator.SEGMENT_VALUE_PARAM, value = "TIPISOGGETTO.CODICETIPOSOGGETTO") })
    @GeneratedValue(generator = "pkGenerator")
    @AttributeOverrides({ @AttributeOverride(name = "idcomune", column = @Column(name = "IDCOMUNE", nullable = false, length = 6)),
	    @AttributeOverride(name = "codice", column = @Column(name = "CODICETIPOSOGGETTO", nullable = false, precision = 10, scale = 0)) })
    public PkId getId() {

	return this.id;
    }

    public void setId(PkId id) {

	this.id = id;
    }

    @NotEmpty
    @Length(max = 128)
    @Column(name = "TIPOSOGGETTO", length = 128)
    public String getTiposoggetto() {

	return this.tiposoggetto;
    }

    public void setTiposoggetto(String tiposoggetto) {

	this.tiposoggetto = tiposoggetto;
    }

    @Column(name = "FLAGQUALITA", precision = 1, scale = 0)
    public Boolean getFlagqualita() {

	return this.flagqualita;
    }

    public void setFlagqualita(Boolean flagqualita) {

	this.flagqualita = flagqualita;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SOFTWARE", nullable = false)
    public Software getSoftware() {

	return this.software;
    }

    public void setSoftware(Software software) {

	this.software = software;
    }

    @Column(name = "UTILIZZO", length = 1)
    public String getUtilizzo() {

	return this.utilizzo;
    }

    public void setUtilizzo(String utilizzo) {

	this.utilizzo = utilizzo;
    }

    @Column(name = "TIPOANAGRAFE", length = 1)
    public String getTipoanagrafe() {

	return this.tipoanagrafe;
    }

    public void setTipoanagrafe(String tipoanagrafe) {

	this.tipoanagrafe = tipoanagrafe;
    }

    @Column(name = "TIPODATO", length = 1)
    public String getTipodato() {

	return this.tipodato;
    }

    public void setTipodato(String tipodato) {

	this.tipodato = tipodato;
    }

    @Column(name = "FO_OBBLIGATORIO", precision = 1, scale = 0)
    public Boolean getFoObbligatorio() {

	return this.foObbligatorio;
    }

    public void setFoObbligatorio(Boolean foObbligatorio) {

	this.foObbligatorio = foObbligatorio;
    }

    @Column(name = "RICHIEDIANAGRAFECOLL", precision = 1, scale = 0)
    public Boolean getRichiedianagrafecoll() {

	return this.richiedianagrafecoll;
    }

    public void setRichiedianagrafecoll(Boolean richiedianagrafecoll) {

	this.richiedianagrafecoll = richiedianagrafecoll;
    }

    @Column(name = "FLG_DATIALBO", length = 1)
    public Boolean getFlgDatialbo() {

	return this.flgDatialbo;
    }

    public void setFlgDatialbo(Boolean flgDatialbo) {

	this.flgDatialbo = flgDatialbo;
    }

    @Column(name = "FLG_SPECIFICADESCRIZIONE", precision = 1, scale = 0)
    public Boolean getFlgSpecificadescrizione() {

	return this.flgSpecificadescrizione;
    }

    public void setFlgSpecificadescrizione(Boolean flgSpecificadescrizione) {

	this.flgSpecificadescrizione = flgSpecificadescrizione;
    }

    @Column(name = "FLG_LEGALERAP", precision = 1, scale = 0)
    public Boolean getFlgLegalerap() {

	return this.flgLegalerap;
    }

    public void setFlgLegalerap(Boolean flgLegalerap) {

	this.flgLegalerap = flgLegalerap;
    }

    @Max(value = 99)
    //@Pattern(regex="([0-9]*)|()" , message = "{validator.period}")
    @Column(name = "ORDINE", precision = 2, scale = 0)
    public Integer getOrdine() {

	return this.ordine;
    }

    public void setOrdine(Integer ordine) {

	this.ordine = ordine;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "FK_RICA_CODICE")
    public RiCariche getRiCariche() {

	return this.riCariche;
    }

    public void setRiCariche(RiCariche riCariche) {

	this.riCariche = riCariche;
    }

    //@Length(max = 1)
    @Column(name = "ATRIB_QUALIFICASOGGETTO ", length = 1)
    public Integer getAtribQualificasoggetto() {

	return atribQualificasoggetto;
    }

    public void setAtribQualificasoggetto(Integer atribQualificasoggetto) {

	this.atribQualificasoggetto = atribQualificasoggetto;
    }

    //    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tipisoggetto")
    //    public Set<Tipisoggettopeople> getTipisoggettopeoples() {
    //
    //	return this.tipisoggettopeoples;
    //    }
    //
    //    public void setTipisoggettopeoples(Set<Tipisoggettopeople> tipisoggettopeoples) {
    //
    //	this.tipisoggettopeoples = tipisoggettopeoples;
    //    }
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tipisoggetto")
    public Set<AlberoprocTipisoggetto> getAlberoprocTipisoggettos() {

	return this.alberoprocTipisoggettos;
    }

    public void setAlberoprocTipisoggettos(Set<AlberoprocTipisoggetto> alberoprocTipisoggettos) {

	this.alberoprocTipisoggettos = alberoprocTipisoggettos;
    }

    @Transient
    public String getTipisoggettipeopleTransient() {

	StringBuffer ris = new StringBuffer();
	//	if (!this.tipisoggettopeoples.isEmpty()) {
	//	    Set<Tipisoggettopeople> set = this.tipisoggettopeoples;
	//	    for (Tipisoggettopeople tipisoggettopeople : set) {
	//		ris.append(tipisoggettopeople.getId().getTiporapprpeople()).append(", ");
	//	    }
	//	}
	String risultato = StringUtils.removeEnd(ris.toString(), ", ");
	return risultato;
    }
}
