package it.gruppoinit.pal.gp.core.domain;

// Generated 4-ago-2009 15.40.52 by Hibernate Tools 3.2.5.Beta
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VwProcedimentiStpId generated by hbm2java
 */
@Embeddable
public class VwProcedimentiStpId implements java.io.Serializable {

    private static final long serialVersionUID = 7814451720115956239L;
    private String idcomune;
    private String codicestp;
    private Integer codiceinventario;

    public VwProcedimentiStpId() {

    }

    public VwProcedimentiStpId(String idcomune, int codiceinventario) {

	this.idcomune = idcomune;
	this.codiceinventario = codiceinventario;
    }

    public VwProcedimentiStpId(String idcomune, String codicestp, int codiceinventario) {

	this.idcomune = idcomune;
	this.codicestp = codicestp;
	this.codiceinventario = codiceinventario;
    }

    @Column(name = "IDCOMUNE", nullable = false, length = 6)
    public String getIdcomune() {

	return this.idcomune;
    }

    public void setIdcomune(String idcomune) {

	this.idcomune = idcomune;
    }

    @Column(name = "CODICESTP", length = 40)
    public String getCodicestp() {

	return this.codicestp;
    }

    public void setCodicestp(String codicestp) {

	this.codicestp = codicestp;
    }

    @Column(name = "CODICEINVENTARIO", nullable = false, precision = 6, scale = 0)
    public int getCodiceinventario() {

	return this.codiceinventario;
    }

    public void setCodiceinventario(int codiceinventario) {

	this.codiceinventario = codiceinventario;
    }

    public boolean equals(Object other) {

	if ((this == other))
	    return true;
	if ((other == null))
	    return false;
	if (!(other instanceof VwProcedimentiStpId))
	    return false;
	VwProcedimentiStpId castOther = (VwProcedimentiStpId) other;
	return ((this.getIdcomune() == castOther.getIdcomune()) || (this.getIdcomune() != null && castOther.getIdcomune() != null && this
		.getIdcomune().equals(castOther.getIdcomune())))
		&& ((this.getCodicestp() == castOther.getCodicestp()) || (this.getCodicestp() != null && castOther.getCodicestp() != null && this
			.getCodicestp().equals(castOther.getCodicestp())));
    }

    public int hashCode() {

	int result = 17;
	result = 37 * result + (getIdcomune() == null ? 0 : this.getIdcomune().hashCode());
	result = 37 * result + (getCodicestp() == null ? 0 : this.getCodicestp().hashCode());
	result = 37 * result + (getCodicestp() == null ? 0 : this.getCodicestp().hashCode());
	return result;
    }
}
