DELETE FROM INTERESSI_LEGALI;

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (1,TO_DATE('21-04-1942','dd-MM-yyyy'),TO_DATE('15-12-1990','dd-MM-yyyy'),5,null);

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (2,TO_DATE('16-12-1990','dd-MM-yyyy'),TO_DATE('31-12-1996','dd-MM-yyyy'),10,'Legge 26 novembre 1990, n. 353'); 

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (3,TO_DATE('01-01-1997','dd-MM-yyyy'),TO_DATE('31-12-1998','dd-MM-yyyy'),5,'Legge 23 dicembre 1996, n. 662'); 

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (4,TO_DATE('01-01-1999','dd-MM-yyyy'),TO_DATE('31-12-2000','dd-MM-yyyy'),2.5,'D.M. 10 dicembre 1998');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (5,TO_DATE('01-01-2001','dd-MM-yyyy'),TO_DATE('31-12-2001','dd-MM-yyyy'),3.5,'D.M. 11 dicembre 2000');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (6,TO_DATE('01-01-2002','dd-MM-yyyy'),TO_DATE('31-12-2003','dd-MM-yyyy'),3,'D.M. 11 dicembre 2001');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (7,TO_DATE('01-01-2004','dd-MM-yyyy'),TO_DATE('31-12-2007','dd-MM-yyyy'),2.5,'D.M. 1 dicembre 2003');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (8,TO_DATE('01-01-2008','dd-MM-yyyy'),TO_DATE('31-12-2009','dd-MM-yyyy'),3,'D.M. 12 dicembre 2007');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (9,TO_DATE('01-01-2010','dd-MM-yyyy'),TO_DATE('31-12-2010','dd-MM-yyyy'),1,'D.M. 4 dicembre 2009');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (10,TO_DATE('01-01-2011','dd-MM-yyyy'),TO_DATE('31-12-2011','dd-MM-yyyy'),1.5,'D.M. 07 Dicembre 2010');

insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (11,TO_DATE('01-01-2012','dd-MM-yyyy'),TO_DATE('31-12-2013','dd-MM-yyyy'),2.5,'DM 12 dicembre 2011'); 

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (12,to_date('01-01-2014','dd-MM-yyyy'),TO_DATE('31-12-2014','dd-MM-yyyy'),1,'Dm Economia 13.12.2013');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (13,to_date('01-01-2015','dd-MM-yyyy'),TO_DATE('31-12-2015','dd-MM-yyyy'),0.5,'Dm Economia 11.12.2014'); 

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (14,to_date('01-01-2016','dd-MM-yyyy'),to_date('31-12-2016','dd-MM-yyyy'),0.2,'Dm Economia 11.12.2015');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (15,to_date('01-01-2017','dd-MM-yyyy'),to_date('31-12-2017','dd-MM-yyyy'),0.1,'Dm economia e finanze 07/12/2016,G.U.14/12/2016');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (16,to_date('01-01-2018','dd-MM-yyyy'),to_date('31-12-2018','dd-MM-yyyy'),0.3,'Dm economia e finanze 13/12/2017,G.U.15/12/2017');

Insert into INTERESSI_LEGALI (ID,DATA_INIZIO,DATA_FINE,TASSO_PERCENTUALE,DISPOSIZIONE_NORMATIVA) values (17,to_date('01-01-2019','dd-MM-yyyy'),NULL,0.8,'Dm economia 12/12/2018,G.U. 302 31/12/2018');


ALTER TABLE INVENTARIOPROCEDIMENTIONERI ADD DYN2CAMPI_ONERI_FRONT NUMBER(10,0);
ALTER TABLE ALBEROPROC_ONERI ADD DYN2CAMPI_ONERI_FRONT NUMBER(10,0);

ALTER TABLE INVENTARIOPROCEDIMENTIONERI ADD CONSTRAINT FK_INV_PROC_ONERI_DYN2C FOREIGN KEY (IDCOMUNE,DYN2CAMPI_ONERI_FRONT) REFERENCES DYN2_CAMPI(IDCOMUNE,ID);

ALTER TABLE ALBEROPROC_ONERI ADD CONSTRAINT FK_ALB_PROC_ONERI_DYN2C FOREIGN KEY (IDCOMUNE,DYN2CAMPI_ONERI_FRONT) REFERENCES DYN2_CAMPI(IDCOMUNE,ID);



CREATE TABLE EQUITALIA_TRACCIATI_CFG(
  IDCOMUNE VARCHAR2(6) NOT NULL,
  ID NUMBER(10,0) NOT NULL,
  SOFTWARE VARCHAR2 (2) NOT NULL,
  CODICE_ENTE_CREDITORE VARCHAR2(10),
  TIPO_UFFICIO VARCHAR2(5),
  CODICE_UFFICIO VARCHAR2(10),
  TIPO_MINUTA VARCHAR2(1),
  TIPO_CARTELLAZIONE VARCHAR2(5),
  SPECIE_DEL_RUOLO VARCHAR2(5),
  TIPO_ISCRIZIONE VARCHAR2(5),
  TIPO_COMPENSO VARCHAR2(5),
  RILASCIO VARCHAR2(5),
  TESTO_MODALITA_OPPOSIZIONE VARCHAR2(5),
  TESTO_COMUNICAZIONE_CONTRIB VARCHAR2(5),
  INVIO_TESTO_SING_CONTRIB VARCHAR2(5),
  TIPOLOGIA_ENTE VARCHAR2(5),
  INVIO_VOLANTINO VARCHAR2(5),
  MODALITA_STAMPA_VOLANTINO VARCHAR2(5),
  COMUNICAZIONE_CONTRIB VARCHAR2(5),
  FLAG_PROVENIENZA VARCHAR2(5),
  CODICE_MOV_ANNO_DEBITO VARCHAR2(8) NOT NULL,
  CODICE_MOV_DATA_ATTO VARCHAR2(8) NOT NULL,
  CODICE_MOV_DATA_NOTIFICA_ATTO VARCHAR2(8) NOT NULL );

ALTER TABLE EQUITALIA_TRACCIATI_CFG ADD CONSTRAINT PK_EQUITALIA_TRACCIATI_CFG PRIMARY KEY (IDCOMUNE, ID);



ALTER TABLE EQUITALIA_TRACCIATI_CFG ADD CODIFICA_TIPOLOGIA_ATTO VARCHAR2(5); 
ALTER TABLE EQUITALIA_TRACCIATI_CFG ADD CODICE_TIPO_ATTO VARCHAR2(5); 
ALTER TABLE EQUITALIA_TRACCIATI_CFG ADD DYN_2_CAMPI_TESTO_VERBALE VARCHAR2(50);


ALTER TABLE EQUITALIA_TRACCIATI_CFG ADD MAP_EQ_IN_SAN_AMM_COM_ONER NUMBER(10,0);
ALTER TABLE EQUITALIA_TRACCIATI_CFG ADD MAP_EQ_IN_SP_SAN_AMM_COM_ONER NUMBER (10,0);


CREATE TABLE EQUITALIATRACCIATO(
  IDCOMUNE VARCHAR2(6) NOT NULL,
  ID NUMBER(10,0) NOT NULL,
  SOFTWARE VARCHAR2 (2) NOT NULL,
  DATA_CREAZIONE DATE NOT NULL,
  PROGRESSIVO_ANNO NUMBER (5,0) NOT NULL ,
  ANNO VARCHAR2 (4) NOT NULL,
  CODICEOGGETTO NUMBER(10,0),
  CODICERESPONSABILE NUMBER (8,0)
);

ALTER TABLE EQUITALIATRACCIATO ADD CONSTRAINT PK_EQUITALIATRACCIATO PRIMARY KEY (IDCOMUNE, ID);

ALTER TABLE EQUITALIATRACCIATO ADD CONSTRAINT FK_EQUIT_TRACC_OGGETTI FOREIGN KEY (IDCOMUNE,CODICEOGGETTO) REFERENCES OGGETTI(IDCOMUNE,CODICEOGGETTO);
ALTER TABLE EQUITALIATRACCIATO ADD CONSTRAINT FK_EQUIT_TRACC_RESP FOREIGN KEY (IDCOMUNE,CODICERESPONSABILE) REFERENCES RESPONSABILI(IDCOMUNE,CODICERESPONSABILE);


CREATE TABLE EQUITALIATRACCIATO_D(
  IDCOMUNE VARCHAR2(6) NOT NULL,
  ID NUMBER(10,0) NOT NULL,
  FK_TRACCIATO_EQ NUMBER(10,0) NOT NULL,
  FK_ISTANZA NUMBER (6,0) NOT NULL
);

ALTER TABLE EQUITALIATRACCIATO_D ADD CONSTRAINT PK_EQUITALIATRACCIATO_D PRIMARY KEY (IDCOMUNE, ID);

ALTER TABLE EQUITALIATRACCIATO_D ADD CONSTRAINT FK_EQUIT_TRACC_D FOREIGN KEY (IDCOMUNE,FK_TRACCIATO_EQ) REFERENCES EQUITALIATRACCIATO(IDCOMUNE,ID);

ALTER TABLE EQUITALIATRACCIATO_D ADD CONSTRAINT FK_EQUIT_TRACC_IST FOREIGN KEY (IDCOMUNE,FK_ISTANZA) REFERENCES ISTANZE(IDCOMUNE,CODICEISTANZA);

ALTER TABLE EQUITALIA_TRACCIATI_CFG ADD CODICE_MOV_ISTANZA_A_RUOLO VARCHAR2(8);


ALTER TABLE EQUITALIA_TRACCIATI_CFG MODIFY MAP_EQ_IN_SAN_AMM_COM_ONER VARCHAR2(50);
ALTER TABLE EQUITALIA_TRACCIATI_CFG MODIFY MAP_EQ_IN_SP_SAN_AMM_COM_ONER VARCHAR2(50);

ALTER TABLE EQUITALIA_TRACCIATI_CFG ADD DYN_2_CAMPI_DATA_VERBALE  VARCHAR2(50);
ALTER TABLE EQUITALIA_TRACCIATI_CFG ADD DYN_2_CAMPI_NUMERO_VERBALE  VARCHAR2(50);


ALTER TABLE MAIL_CONFIG  MODIFY LOGINPASS VARCHAR2(300 CHAR);

ALTER TABLE MAIL_CONFIG  MODIFY IN_LOGINPASS VARCHAR2(300 CHAR);

ALTER TABLE EQUITALIA_TRACCIATI_CFG ADD CODICE_REG_AUT_ORDINANZA VARCHAR2(50);
ALTER TABLE EQUITALIA_TRACCIATI_CFG ADD DYN2_CAMPI_FILTRO_AMBITO  VARCHAR2(50);


CREATE TABLE DECODIFICHE(IDCOMUNE VARCHAR2(6 CHAR) NOT NULL, TABELLA VARCHAR2(64 CHAR) NOT NULL, CHIAVE VARCHAR2(20 CHAR) NOT NULL, VALORE VARCHAR2(2000 CHAR) NOT NULL, FLG_DISABILITATO NUMBER(1,0) NOT NULL);
CREATE INDEX IDX_DECODIFICHE_001 ON DECODIFICHE (IDCOMUNE, TABELLA, CHIAVE);
ALTER TABLE TIPICONTESTOESPORTAZIONE  MODIFY (DESCRIZIONE VARCHAR2(100 CHAR));

create table FO_CONSENSI_INFORMATIVI(
IDCOMUNE VARCHAR2(6),
ID NUMBER(10,0),
IDENTIFICATIVO_UTENTE VARCHAR2(50),
FLAG_CONSENSO NUMBER(1,0) DEFAULT 0,
DATA_AVVENUTO_CONSENSO DATE,
CONTESTO VARCHAR2(50),
TESTO_CONSENSO CLOB
);

ALTER TABLE FO_CONSENSI_INFORMATIVI ADD CONSTRAINT PK_FO_CONSENSI_INFORMATIVI PRIMARY KEY (IDCOMUNE, ID);
CREATE INDEX IDX_FO_CONSINFO_IDUTE ON FO_CONSENSI_INFORMATIVI (IDCOMUNE, IDENTIFICATIVO_UTENTE);

ALTER TABLE DECODIFICHE ADD (RAGGRUPPAMENTO VARCHAR2(20 CHAR) );

ALTER TABLE dyn2_campi MODIFY etichetta VARCHAR2(2000);

ALTER TABLE ISTANZEPROCEDIMENTI MODIFY TIPO_ATTO VARCHAR2(1000 CHAR);
ALTER TABLE CONFIGURAZIONE ADD PROGRESSIVO_REGISTRI_AUT VARCHAR2(35);
ALTER TABLE TIPOLOGIAREGISTRI ADD FLAG_USA_PROGR_CONF NUMBER(1,0) DEFAULT 0;

