INSERT INTO verticalizzazioniparametribase(modulo, parametro, descrizione) VALUES('PROTOCOLLO_URBI', 'ATTIVA_FASC_CONTESTUALE','Attiva la fascicolazione contestualmente alla protocollazione in un''unica chiamata solo per le protocollazioni da movimento. Da utilizzare nei casi in cui nel protocollo urbi siano state attivate delle configurazioni che rendano necessari i dati di fascicolazione contestualmente alla protocollazione in partenza come ad esempio avviente all''ente ATO Monza. Il componente è compatibile con il parametro GESTISCI_FASCICOLAZIONE della regola PROTOCOLLO_ATTIVO. Attivandolo, in fase di protocollazione da un movimento, il componente andrà a recuperare il dato relativo al fascicolo andando a rileggere il protocollo dell''istanza da dove riesce a ricavare il codice del fascicolo che verrà poi utilizzato, se non presente non sarà possibile protocollare in partenza mentre in arrivo si (anche se verranno visualizzati dei warnings), ovviamente l''istanza dovrà avere i riferimenti di protocollazione. Non utilizzare tale configurazione se l''ente prevede di utilizzare la protocollazione per bollettazioni');


INSERT INTO COMUNI (CODICECOMUNE, COMUNE, SIGLAPROVINCIA, PROVINCIA, REGIONE, CAP, CF, CODICEISTAT, CODICEISTATREGIONE, CODICESTATOESTERO) VALUES('A046', 'ACQUATE', 'CO', 'COMO', 'LOMBARDIA', NULL, 'A406', '013802', '03', NULL);
INSERT INTO COMUNI (CODICECOMUNE, COMUNE, SIGLAPROVINCIA, PROVINCIA, REGIONE, CAP, CF, CODICEISTAT, CODICEISTATREGIONE, CODICESTATOESTERO) VALUES('A563', 'BAGNO', 'AQ', 'L''AQUILA', 'ABRUZZO', NULL, 'A563', '066802', '13', NULL);
INSERT INTO COMUNI (CODICECOMUNE, COMUNE, SIGLAPROVINCIA, PROVINCIA, REGIONE, CAP, CF, CODICEISTAT, CODICEISTATREGIONE, CODICESTATOESTERO) VALUES('B210', 'BROZZI', 'FI', 'FIRENZE', 'TOSCANA', NULL, 'B210', '048801', '09', NULL);
INSERT INTO COMUNI (CODICECOMUNE, COMUNE, SIGLAPROVINCIA, PROVINCIA, REGIONE, CAP, CF, CODICEISTAT, CODICEISTATREGIONE, CODICESTATOESTERO) VALUES('D887', 'GALLUZZO', 'FI', 'FIRENZE', 'TOSCANA', NULL, 'D887' , '048802', '09', NULL);
INSERT INTO COMUNI (CODICECOMUNE, COMUNE, SIGLAPROVINCIA, PROVINCIA, REGIONE, CAP, CF, CODICEISTAT, CODICEISTATREGIONE, CODICESTATOESTERO) VALUES('F466', 'MONTECELIO', 'RM', 'ROMA', 'LAZIO', NULL, 'F466', '058801', '12', NULL);
INSERT INTO COMUNI (CODICECOMUNE, COMUNE, SIGLAPROVINCIA, PROVINCIA, REGIONE, CAP, CF, CODICEISTAT, CODICEISTATREGIONE, CODICESTATOESTERO) VALUES('H902', 'SAN GIOVANNI/ST. JOHANN IN AHRN', 'BZ', 'BOLZANO', 'PROV. AUT. BOLZANO', NULL, 'H902', '021883', '04', NULL);


INSERT INTO COMUNI (CODICECOMUNE, COMUNE, SIGLAPROVINCIA, PROVINCIA, REGIONE, CAP, CF, CODICEISTAT, CODICEISTATREGIONE, CODICESTATOESTERO) VALUES ('H934', 'VILLA SAN GIUSEPPE', 'RC', 'REGGIO CALABRIA', 'CALABRIA', NULL, 'H934', '080820', '18', NULL);

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_JIRIDE', 'TIPO_ASSEGNAZIONE_COPIA_DEF', 'Impostare il valore che si desidera utilizzare per definire che tipo di assegnazione deve essere effettuata per la creazione di una copia, utilizzata soprattutto in ambito di protocollazione interna con più destinatari. I valore che possono essere indicati sono: COMPETENZA e CONOSCENZA, se non indicato niente o se verrà indicata una stringa non corretta (attenzione, va scritto in maiuscolo), di default verrà applicato il valore CONOSCENZA.');

INSERT INTO verticalizzazioniparametribase (MODULO, PARAMETRO, DESCRIZIONE) VALUES('COMPORTAMENTI_MERCATI','CHIUS_GG_MERC_CHECK_GG_PREC','Alla chiusura della giornata di mercato decide se effettuare il controllo di chiusura delle giornate precedenti. Valori ammessi <b>S / N</b>, Valore predefinito <b>S</b>');

INSERT INTO clmenu_java (ID, DESCRIZIONE, PAGINA, MENULINK, SOFTWARE, JSP, VERTICALIZZAZIONE, SOFTWAREESCLUSI, LINK_STANDARD, TIPO_FUNZIONALITA, LAYOUTTESTI, MENULINK_V2) VALUES(1057, 'Pagamenti aut/conc', 'autorizzazioni/ricercaPagamentiAutorizzazioniConcessione.htm?software=SOFTWARE', '10H5', '*', 'JAVA', NULL, NULL, 'autorizzazioni/ricercaPagamentiAutorizzazioniConcessione.htm?software=SOFTWARE', 'S', NULL, '10H5');