ALTER TABLE conf_applicative modify CHIAVE VARCHAR(100);
ALTER TABLE pay_profili_enti_creditori ADD COLUMN APPLICATION_CODE numeric(2,0) NULL  ;

alter table istanzeeventi modify FKIDCATEGORIAEVENTO VARCHAR(16) null;
ALTER TABLE CONTI ADD DATASCADENZA DATETIME;

CREATE TABLE BOLL_CFG_TIPO(IDCOMUNE VARCHAR(6) NOT NULL,ID NUMERIC(4,0) NOT NULL,DESCRIZIONE VARCHAR(200),PERIODO VARCHAR(20),FLAG_CONGUAGLIO NUMERIC(1,0),FLAG_RAGGRUPPA_UTENZA NUMERIC(1,0),IMPLEMENTAZIONE VARCHAR(20),FK_TIPISCADENZA_ID NUMERIC(2,0))ENGINE=INNODB DEFAULT CHARSET=UTF8;
ALTER TABLE BOLL_CFG_TIPO ADD CONSTRAINT PK_BLCFGTIPO PRIMARY KEY(IDCOMUNE,ID); 
ALTER TABLE BOLL_CFG_TIPO ADD CONSTRAINT FK_BLCFGTIPO_TIPISCAD FOREIGN KEY(FK_TIPISCADENZA_ID) REFERENCES TIPI_SCADENZA(ID);
CREATE TABLE BOLL_CFG_RUOLI(IDCOMUNE VARCHAR(6) NOT NULL,FK_BOLLCFGTIPO_ID NUMERIC(4,0) NOT NULL, FK_RUOLI_ID NUMERIC(4,0) NOT NULL )ENGINE=INNODB DEFAULT CHARSET=UTF8;
ALTER TABLE BOLL_CFG_RUOLI ADD CONSTRAINT PK_BLCFGRUOLI PRIMARY KEY(IDCOMUNE,FK_BOLLCFGTIPO_ID,FK_RUOLI_ID);
ALTER TABLE BOLL_CFG_RUOLI ADD CONSTRAINT FK_BLLCFGRUOLI_BLLCFGTIPO FOREIGN KEY(IDCOMUNE,FK_BOLLCFGTIPO_ID) REFERENCES BOLL_CFG_TIPO(IDCOMUNE,ID);
ALTER TABLE BOLL_CFG_RUOLI ADD CONSTRAINT FK_BLLCFGRUOLI_RUOLI FOREIGN KEY(IDCOMUNE,FK_RUOLI_ID) REFERENCES RUOLI(IDCOMUNE,ID);
CREATE TABLE BOLL_CFG_MERCATI(IDCOMUNE VARCHAR(6) NOT NULL,FK_BOLLCFGTIPO_ID NUMERIC(4,0) NOT NULL, FK_CODICEMERCATO NUMERIC(4,0) NOT NULL )ENGINE=INNODB DEFAULT CHARSET=UTF8;
ALTER TABLE BOLL_CFG_MERCATI ADD CONSTRAINT PK_CFGMERCATI PRIMARY KEY(IDCOMUNE,FK_BOLLCFGTIPO_ID,FK_CODICEMERCATO);
ALTER TABLE BOLL_CFG_MERCATI ADD CONSTRAINT FK_CFGMERCATI_BLLCFGTIPO FOREIGN KEY(IDCOMUNE,FK_BOLLCFGTIPO_ID) REFERENCES BOLL_CFG_TIPO(IDCOMUNE,ID);
ALTER TABLE BOLL_CFG_MERCATI ADD CONSTRAINT FK_CFGMERCATI_MERCATI FOREIGN KEY(IDCOMUNE,FK_CODICEMERCATO) REFERENCES MERCATI(IDCOMUNE,CODICEMERCATO);
CREATE TABLE BOLL_CFG_CAUSALIONERI(IDCOMUNE VARCHAR(6) NOT NULL,FK_BOLLCFGTIPO_ID NUMERIC(4,0) NOT NULL, FK_CO_ID NUMERIC(10,0) NOT NULL )ENGINE=INNODB DEFAULT CHARSET=UTF8;
ALTER TABLE BOLL_CFG_CAUSALIONERI ADD CONSTRAINT PK_CFGCAUSALIONERI PRIMARY KEY(IDCOMUNE,FK_BOLLCFGTIPO_ID,FK_CO_ID);
ALTER TABLE BOLL_CFG_CAUSALIONERI ADD CONSTRAINT FK_CFGCAUSALIONERI_BLLCFGTIPO FOREIGN KEY(IDCOMUNE,FK_BOLLCFGTIPO_ID) REFERENCES BOLL_CFG_TIPO(IDCOMUNE,ID);
ALTER TABLE BOLL_CFG_CAUSALIONERI ADD CONSTRAINT FK_CFGCAUSALIONERI_MERCATI FOREIGN KEY(IDCOMUNE,FK_CO_ID) REFERENCES TIPICAUSALIONERI(IDCOMUNE,CO_ID);
ALTER TABLE BOLL_CFG_TIPO ADD SOFTWARE VARCHAR(2) NOT NULL;
ALTER TABLE BOLL_CFG_TIPO ADD CONSTRAINT FK_CFGTIPO_SOFTWARE FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);


CREATE TABLE BOLL_GEST_TESTATA(
IDCOMUNE VARCHAR(6) NOT NULL
,ID numeric(4,0) NOT NULL
,FK_BOLLTIPO_ID numeric(4,0)
,DESCRIZIONE VARCHAR(4000)
,DALLA_DATA DATETIME
,ALLA_DATA DATETIME
,STATO VARCHAR(10)
,FLAG_CONGUAGLIO numeric(1,0)
,FLAG_RAGGRUPPA_UTENZA numeric(1,0)
,DATA_INSERIMENTO DATETIME
,PERIODO  VARCHAR(20)
,IMPLEMENTAZIONE VARCHAR(20)
,FK_TIPISCADENZA_ID numeric(2) ) ENGINE=INNODB DEFAULT CHARSET=utf8;

ALTER TABLE BOLL_GEST_TESTATA ADD CONSTRAINT PK_BOLLGESTTESTATA PRIMARY KEY(IDCOMUNE,ID); ALTER TABLE BOLL_GEST_TESTATA ADD CONSTRAINT FK_BOLGESTEST_BOLCFGTI FOREIGN KEY(IDCOMUNE,FK_BOLLTIPO_ID)
    REFERENCES BOLL_CFG_TIPO(IDCOMUNE,ID);

ALTER TABLE BOLL_GEST_TESTATA ADD CONSTRAINT FK_BOLGESTEST_TIPISCAD FOREIGN KEY(FK_TIPISCADENZA_ID)
    REFERENCES TIPI_SCADENZA(ID);

CREATE TABLE BOLL_GEST_FILTRI(
IDCOMUNE VARCHAR(6) NOT NULL
,ID numeric(6,0) NOT NULL
,FK_SC_CODICE VARCHAR(40)
,FK_BOLLGEST_ID numeric(4,0)
,FK_CODICEINVENTARIO numeric(10, 0)
,CODICECOMUNE VARCHAR(5)
,FK_CODICEMERCATO numeric(4,0)
,FK_CO_ID numeric(10,0)

) ENGINE=INNODB DEFAULT CHARSET=utf8;

ALTER TABLE BOLL_GEST_FILTRI ADD CONSTRAINT PK_BOLLGESTFILTRI PRIMARY KEY(IDCOMUNE,ID);

ALTER TABLE BOLL_GEST_FILTRI ADD CONSTRAINT FK_BOLGESTFI_BOLGESTT FOREIGN KEY(IDCOMUNE,FK_BOLLGEST_ID) REFERENCES BOLL_GEST_TESTATA(IDCOMUNE,ID);

ALTER TABLE BOLL_GEST_FILTRI ADD CONSTRAINT FK_BOLGESTFI_INVPROC FOREIGN KEY(IDCOMUNE,FK_CODICEINVENTARIO) REFERENCES INVENTARIOPROCEDIMENTI(IDCOMUNE,CODICEINVENTARIO);

ALTER TABLE BOLL_GEST_FILTRI ADD CONSTRAINT FK_BOLGESTFI_COMUNI FOREIGN KEY(CODICECOMUNE) REFERENCES COMUNI(CODICECOMUNE);

ALTER TABLE BOLL_GEST_FILTRI ADD CONSTRAINT FK_BOLGESTFI_TIPICAUSONERI FOREIGN KEY(IDCOMUNE,FK_CO_ID) REFERENCES TIPICAUSALIONERI(IDCOMUNE,CO_ID);

ALTER TABLE BOLL_GEST_FILTRI ADD CONSTRAINT FK_BOLGESTFI_MERCATI FOREIGN KEY(IDCOMUNE,FK_CODICEMERCATO) REFERENCES MERCATI(IDCOMUNE,CODICEMERCATO);

CREATE TABLE DETT_POSIZIONE_DEBITORIA(
IDCOMUNE VARCHAR(6) NOT NULL
,ID numeric(10,0) NOT NULL
,STATO VARCHAR(30) NOT NULL
,DESC_STATO VARCHAR(500) NULL
,ID_POSIZIONE_DEBITORIA NUMERIC(10,0)
,DATA_ULTIMO_STATO DATETIME) ENGINE=INNODB DEFAULT CHARSET=utf8;

ALTER TABLE DETT_POSIZIONE_DEBITORIA ADD CONSTRAINT PK_DETTPOSIZIONEDEBITORIA PRIMARY KEY(IDCOMUNE,ID);


CREATE TABLE BOLL_GEST_DETTAGLIO(
IDCOMUNE VARCHAR(6) NOT NULL
,ID numeric(10,0) NOT NULL
,FK_BOLLGEST_ID numeric(4,0)
,IMPORTO numeric(11,2)
,FLAG_VALIDATA numeric(1,0)
,FK_RETTIFICA_ID  numeric(10,0)
,DESCRIZIONE VARCHAR(1000)
,FLAG_INS_AUTO numeric(1,0)
,FK_CODICEANAGRAFE numeric(6,0)
,FK_CONTO_ID numeric(6,0)
,FK_POSDEBDETTAGLIO_ID numeric(10,0)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

ALTER TABLE BOLL_GEST_DETTAGLIO ADD CONSTRAINT PK_BOLLGESTDETTAGLIO PRIMARY KEY(IDCOMUNE,ID);
ALTER TABLE BOLL_GEST_DETTAGLIO ADD CONSTRAINT FK_BOLLGESTD_BOLLGEST FOREIGN KEY(IDCOMUNE,FK_BOLLGEST_ID) REFERENCES BOLL_GEST_TESTATA(IDCOMUNE,ID);
ALTER TABLE BOLL_GEST_DETTAGLIO ADD CONSTRAINT FK_BOLLGESTD_BLGDRETT FOREIGN KEY(IDCOMUNE,FK_RETTIFICA_ID) REFERENCES BOLL_GEST_DETTAGLIO(IDCOMUNE,ID);
ALTER TABLE BOLL_GEST_DETTAGLIO ADD CONSTRAINT FK_BOLLGESTD_ANAGRAFE FOREIGN KEY(IDCOMUNE,FK_CODICEANAGRAFE) REFERENCES ANAGRAFE(IDCOMUNE,CODICEANAGRAFE);
ALTER TABLE BOLL_GEST_DETTAGLIO ADD CONSTRAINT FK_BOLLGESTD_CONTI FOREIGN KEY(IDCOMUNE,FK_CONTO_ID) REFERENCES CONTI(IDCOMUNE,ID);
ALTER TABLE BOLL_GEST_DETTAGLIO ADD CONSTRAINT FK_BOLLGESTD_POSDEB FOREIGN KEY(IDCOMUNE,FK_POSDEBDETTAGLIO_ID) REFERENCES DETT_POSIZIONE_DEBITORIA(IDCOMUNE,ID);

CREATE TABLE BOLL_GEST_ISTANZEONERI(
IDCOMUNE VARCHAR(6) NOT NULL
,ID numeric(10,0) NOT NULL
,FK_BOLLGESTDET_ID numeric(10,0)
,FK_CODICEISTANZEONERI  numeric(10,0)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

ALTER TABLE BOLL_GEST_ISTANZEONERI ADD CONSTRAINT PK_BOLLGESTISTANZEONERI PRIMARY KEY(IDCOMUNE,ID);
ALTER TABLE BOLL_GEST_ISTANZEONERI ADD CONSTRAINT FK_BOLLGESTISTONERI_BOLLGD FOREIGN KEY (IDCOMUNE,FK_BOLLGESTDET_ID) REFERENCES BOLL_GEST_DETTAGLIO(IDCOMUNE,ID);
ALTER TABLE BOLL_GEST_ISTANZEONERI ADD CONSTRAINT FK_BOLLGESTISTONERI_ISTONERI FOREIGN KEY (IDCOMUNE,FK_CODICEISTANZEONERI) REFERENCES ISTANZEONERI(IDCOMUNE,ID);

ALTER TABLE BOLL_CFG_TIPO MODIFY DESCRIZIONE VARCHAR(200) NOT NULL;
ALTER TABLE BOLL_CFG_TIPO MODIFY PERIODO VARCHAR(20) NOT NULL;
ALTER TABLE BOLL_CFG_TIPO MODIFY FLAG_CONGUAGLIO NUMERIC(1,0) NOT NULL;
ALTER TABLE BOLL_CFG_TIPO MODIFY FLAG_RAGGRUPPA_UTENZA NUMERIC(1,0) NOT NULL;
ALTER TABLE BOLL_CFG_TIPO MODIFY IMPLEMENTAZIONE VARCHAR(20) NOT NULL;
ALTER TABLE BOLL_CFG_TIPO MODIFY FK_TIPISCADENZA_ID NUMERIC(2,0) NOT NULL;
ALTER TABLE BOLL_GEST_TESTATA MODIFY FK_BOLLTIPO_ID NUMERIC(4,0) NOT NULL;
ALTER TABLE BOLL_GEST_TESTATA MODIFY DESCRIZIONE VARCHAR(4000) NOT NULL;
ALTER TABLE BOLL_GEST_TESTATA MODIFY DALLA_DATA DATETIME NOT NULL;
ALTER TABLE BOLL_GEST_TESTATA MODIFY ALLA_DATA DATETIME NOT NULL;
ALTER TABLE BOLL_GEST_TESTATA MODIFY STATO VARCHAR(10) NOT NULL;
ALTER TABLE BOLL_GEST_TESTATA MODIFY FLAG_CONGUAGLIO NUMERIC(1,0)  NOT NULL;
ALTER TABLE BOLL_GEST_TESTATA MODIFY FLAG_RAGGRUPPA_UTENZA NUMERIC(1,0)  NOT NULL;
ALTER TABLE BOLL_GEST_TESTATA MODIFY DATA_INSERIMENTO DATETIME NOT NULL;
ALTER TABLE BOLL_GEST_TESTATA MODIFY PERIODO VARCHAR(20) NOT NULL;
ALTER TABLE BOLL_GEST_TESTATA MODIFY IMPLEMENTAZIONE VARCHAR(20) NOT NULL;
ALTER TABLE BOLL_GEST_TESTATA MODIFY FK_TIPISCADENZA_ID NUMERIC(2,0) NOT NULL;
ALTER TABLE BOLL_GEST_DETTAGLIO MODIFY FK_BOLLGEST_ID NUMERIC(4,0) NOT NULL;
ALTER TABLE BOLL_GEST_DETTAGLIO MODIFY IMPORTO NUMERIC(11,2) NOT NULL;
ALTER TABLE BOLL_GEST_DETTAGLIO MODIFY FLAG_VALIDATA  NUMERIC(1,0) NOT NULL;
ALTER TABLE BOLL_GEST_DETTAGLIO MODIFY DESCRIZIONE VARCHAR(1000) NOT NULL;
ALTER TABLE BOLL_GEST_DETTAGLIO MODIFY FLAG_INS_AUTO  NUMERIC(1,0) NOT NULL;
ALTER TABLE BOLL_GEST_DETTAGLIO MODIFY FK_CODICEANAGRAFE  NUMERIC(6,0) NOT NULL;
ALTER TABLE BOLL_GEST_DETTAGLIO MODIFY FK_CONTO_ID NUMERIC(6,0) NOT NULL;
ALTER TABLE BOLL_GEST_FILTRI MODIFY FK_BOLLGEST_ID NUMERIC(4,0) NOT NULL;
ALTER TABLE BOLL_GEST_FILTRI MODIFY CODICECOMUNE  VARCHAR(5) NOT NULL;
ALTER TABLE BOLL_GEST_ISTANZEONERI MODIFY FK_BOLLGESTDET_ID NUMERIC(10,0) NOT NULL;
ALTER TABLE BOLL_GEST_ISTANZEONERI MODIFY FK_CODICEISTANZEONERI NUMERIC(10,0) NOT NULL;

  
CREATE TABLE pay_richieste(  
  ID numeric(9,0) NOT NULL,
  IDCOMUNE VARCHAR(6) NOT NULL,
  TIPO_RICHIESTA VARCHAR(30) NOT NULL,
  FK_POSIZIONE_DEBITORIA numeric(9,0) NOT NULL,
  FK_PROFILO_ENTE numeric(10,0) NOT NULL,
  DATA_RICHIESTA DATETIME NOT NULL,
  FK_EVENTO numeric(9,0),
  DATA_COMPLETAMENTO DATETIME,
  N_CHIAMATE numeric(9,0),
  FK_EVENTO_OUT numeric(9,0)
) ENGINE=INNODB DEFAULT CHARSET=utf8;
 
ALTER TABLE pay_richieste ADD CONSTRAINT PK_PAY_RICHIESTE PRIMARY KEY(IDCOMUNE,ID);
CREATE INDEX IDX_RICH_X_TIPO ON pay_richieste(FK_PROFILO_ENTE, TIPO_RICHIESTA);
ALTER TABLE pay_richieste ADD CONSTRAINT FK_RICH_POSDEB FOREIGN KEY (IDCOMUNE, FK_POSIZIONE_DEBITORIA) REFERENCES pay_posizioni_debitorie(IDCOMUNE, ID);
ALTER TABLE pay_richieste ADD CONSTRAINT FK_RICH_ENTE FOREIGN KEY (IDCOMUNE, FK_PROFILO_ENTE) REFERENCES pay_profili_enti_creditori(IDCOMUNE, ID);
ALTER TABLE pay_richieste ADD CONSTRAINT FK_RICH_EVENTO FOREIGN KEY (IDCOMUNE, FK_EVENTO) REFERENCES pay_io_eventi(IDCOMUNE, ID);


ALTER TABLE pay_connector_ws_endpoint  ADD COLUMN QUARTZ_SCHEDULE VARCHAR(100) NULL;
ALTER TABLE pay_connector_ws_endpoint   ADD COLUMN FLAG_SOLO_SCHEDULATO numeric(1,0) DEFAULT '0'  NULL;
ALTER TABLE pay_connector_ws_endpoint   ADD COLUMN MAX_CHIAMATE numeric(9,0) NULL;

ALTER TABLE BOLL_GEST_DETTAGLIO ADD FLAG_ELIMINATA NUMERIC(1,0) NOT NULL;
ALTER TABLE BOLL_GEST_DETTAGLIO ADD NOTE_UTENTE VARCHAR(4000);
ALTER TABLE BOLL_GEST_DETTAGLIO ADD NOTE_SISTEMA VARCHAR(4000);



ALTER TABLE pay_connector_config  ADD COLUMN APPLICATION_CODE VARCHAR(2) NULL;

ALTER TABLE boll_gest_dettaglio ADD flag_rettificata numeric(1,0) NOT NULL;


CREATE TABLE TIPICAUSALIONERIDETTAGLIO (IDCOMUNE VARCHAR(6) NOT NULL, FKCAUSALE NUMERIC(10,0) NOT NULL, FKCONTO NUMERIC(6,0) NOT NULL, CONSTRAINT TIPICAUSALIONERIDETTAGLIO_PK PRIMARY KEY (IDCOMUNE, FKCAUSALE, FKCONTO)) ENGINE=INNODB DEFAULT CHARSET=utf8;
ALTER TABLE TIPICAUSALIONERIDETTAGLIO ADD CONSTRAINT TIPICAUSALIONERIDETTAGLIO_FK1 FOREIGN KEY(IDCOMUNE, FKCAUSALE) REFERENCES TIPICAUSALIONERI(IDCOMUNE, CO_ID);
ALTER TABLE TIPICAUSALIONERIDETTAGLIO ADD CONSTRAINT TIPICAUSALIONERIDETTAGLIO_FK2 FOREIGN KEY(IDCOMUNE, FKCONTO)REFERENCES CONTI(IDCOMUNE, ID);
ALTER TABLE BOLL_GEST_FILTRI MODIFY CODICECOMUNE VARCHAR(5) NULL;

CREATE TABLE LIVELLO_SERVIZIO (
     IDCOMUNE VARCHAR(6) NOT NULL
     ,  ID numeric(10) NOT NULL
     , DESCRIZIONE VARCHAR(300)  NOT NULL
     , SEGNAPOSTO VARCHAR(150)  NOT NULL )  ENGINE=INNODB DEFAULT CHARSET=utf8;

ALTER TABLE LIVELLO_SERVIZIO ADD CONSTRAINT PK_LIVELLO_SERVIZIO PRIMARY KEY(IDCOMUNE, ID);

CREATE TABLE MERCATI_LIVELLO_SERVIZIO (
  IDCOMUNE VARCHAR(6) NOT NULL
     , ID numeric(10) NOT NULL
     , DESCRIZIONE VARCHAR(300) NOT NULL
     , FK_MERCATO_USO numeric(4)  NOT NULL
     , FK_SERVIZIO numeric(10)  NOT NULL
     , ATTIVO numeric(1)  NOT NULL
     , TARIFFA numeric(7,4)  NOT NULL
     , DATA_INIZIO_VALIDITA DATETIME NOT NULL
     , DATA_FINE_VALIDITA DATETIME
 , NOTE VARCHAR(500)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

ALTER TABLE MERCATI_LIVELLO_SERVIZIO ADD CONSTRAINT PK_MERCATI_LIVELLO_SERVIZIO PRIMARY KEY (IDCOMUNE,ID);

ALTER TABLE MERCATI_LIVELLO_SERVIZIO ADD CONSTRAINT FK_MER_SERV_LIV_SERV FOREIGN KEY (IDCOMUNE, FK_SERVIZIO) REFERENCES LIVELLO_SERVIZIO (IDCOMUNE,ID);

ALTER TABLE MERCATI_LIVELLO_SERVIZIO ADD CONSTRAINT FK_MER_SERV_USO  FOREIGN KEY (IDCOMUNE, FK_MERCATO_USO) REFERENCES MERCATI_USO (IDCOMUNE,ID);

CREATE TABLE MERCATI_CONTABILITA_TRIBUTI (
     IDCOMUNE VARCHAR(6) NOT NULL
     , ID numeric(10) NOT NULL
     , DESCRIZIONE VARCHAR(200) NOT NULL
     , FK_CONTI numeric(6) NOT NULL
     , DATA_INIZIO_VALIDITA DATETIME NOT NULL
     , DATA_FINE_VALIDITA DATETIME
     , FK_MERCATI_FORMULE numeric(10) NOT NULL

) ENGINE=INNODB DEFAULT CHARSET=utf8;

ALTER TABLE MERCATI_CONTABILITA_TRIBUTI ADD CONSTRAINT PK_MERCATI_CONTABILITA_TRIBUTI PRIMARY KEY (IDCOMUNE,ID);

CREATE TABLE MERCATI_FORMULE_CALCOLO (
     IDCOMUNE VARCHAR(6) NOT NULL
     ,  ID numeric(10) NOT NULL
     , DESCRIZIONE VARCHAR(300) NOT NULL
     , DATA_INIZIO_VALIDITA DATETIME NOT NULL  , DATA_FINE_VALIDITA DATETIME
     , FORMULA VARCHAR(400) NOT NULL
     , FK_USO numeric(4) NOT NULL

) ENGINE=INNODB DEFAULT CHARSET=utf8;

ALTER TABLE MERCATI_FORMULE_CALCOLO ADD CONSTRAINT PK_MERCATI_FORMULE_CALCOLO  PRIMARY KEY (IDCOMUNE,ID);

ALTER TABLE MERCATI_CONTABILITA_TRIBUTI ADD CONSTRAINT FK_CONT_TRIB_MER_CONTI FOREIGN KEY (IDCOMUNE, FK_CONTI) REFERENCES CONTI (IDCOMUNE,ID);

ALTER TABLE MERCATI_CONTABILITA_TRIBUTI ADD CONSTRAINT FK_CONT_TRIB_MER_FORM  FOREIGN KEY (IDCOMUNE, FK_MERCATI_FORMULE) REFERENCES MERCATI_FORMULE_CALCOLO (IDCOMUNE, ID);

ALTER TABLE MERCATI_FORMULE_CALCOLO ADD CONSTRAINT FK_MERC_FORM_USO  FOREIGN KEY (IDCOMUNE, FK_USO) REFERENCES MERCATI_USO (IDCOMUNE,ID);

CREATE TABLE MERCATI_D_LIVELLO_SERVIZIO (
     IDCOMUNE VARCHAR(6) NOT NULL
     , ID numeric (10) NOT NULL
     , FATTORE_MOLTIPLICATIVO numeric(5,2) NOT NULL
     , USA_MQ_POSTEGGIO numeric(1) NOT NULL
     , DATA_INIZIO DATETIME NOT NULL
     , DATA_FINE DATETIME
     , FK_MERCATO_D numeric(6) NOT NULL
     , FK_MERC_SERVIZIO numeric(10) NOT NULL

) ENGINE=INNODB DEFAULT CHARSET=utf8;

ALTER TABLE MERCATI_D_LIVELLO_SERVIZIO ADD CONSTRAINT PK_MERCATIDLIVELLOSERV  PRIMARY KEY (IDCOMUNE, ID);

ALTER TABLE MERCATI_D_LIVELLO_SERVIZIO  ADD CONSTRAINT FK_LIV_SERV_MERC_MERC_D FOREIGN KEY (IDCOMUNE,FK_MERCATO_D ) REFERENCES MERCATI_D (IDCOMUNE,IDPOSTEGGIO); ALTER TABLE MERCATI_D_LIVELLO_SERVIZIO ADD CONSTRAINT FK_LIV_MERC_D_LIVEL_SERV  FOREIGN KEY (IDCOMUNE, FK_MERC_SERVIZIO) REFERENCES MERCATI_LIVELLO_SERVIZIO (IDCOMUNE,ID);


ALTER TABLE pay_io_eventi modify DESC_ESITO VARCHAR(1000);
ALTER TABLE pay_io_eventi modify CODICE_ESITO VARCHAR(200);

alter table pay_richieste  ADD CONSTRAINT FK_RICH_EVENTO_OUT FOREIGN KEY (IDCOMUNE, FK_EVENTO_OUT) REFERENCES pay_io_eventi(IDCOMUNE, ID);

