-- appio_gw.stato_messaggio definition

CREATE TABLE `stato_messaggio` (
  `ID` bigint(10) NOT NULL AUTO_INCREMENT,
  `NOME` varchar(200) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `STATO_MESSAGGIO_PK` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;


-- appio_gw.tipo_connettore definition

CREATE TABLE `tipo_connettore` (
  `ID` bigint(10) NOT NULL AUTO_INCREMENT,
  `NOME` varchar(200) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `TIPO_CONNETTORE_NOME_IDX` (`NOME`),
  UNIQUE KEY `TIPO_CONNETTORE_PK` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;


-- appio_gw.servizi definition

CREATE TABLE `servizi` (
  `ID` bigint(10) NOT NULL AUTO_INCREMENT,
  `ID_SERVIZIO` varchar(50) NOT NULL,
  `IDCOMUNE` varchar(6) NOT NULL,
  `CODICECOMUNE` varchar(6) NOT NULL,
  `SOFTWARE` varchar(2) NOT NULL,
  `NOME_SERVIZIO` varchar(50) DEFAULT NULL,
  `DIPARTIMENTO` varchar(50) DEFAULT NULL,
  `ENTE` varchar(50) DEFAULT NULL,
  `CODICE_FISCALE_ENTE` varchar(25) DEFAULT NULL,
  `CHIAVE_PRIMARIA` varchar(32) DEFAULT NULL,
  `CHIAVE_SECONDARIA` varchar(32) DEFAULT NULL,
  `FK_TIPO_CONNETTORE` bigint(10) DEFAULT NULL,
  `CLIENT_ID` varchar(32) DEFAULT NULL,
  `CLIENT_SECRET` varchar(32) DEFAULT NULL,
  `CLIENT_REGISTRATION_ID` varchar(32) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UKDOA63WLB8QPNVK6YUCGOSQIWS` (`ID_SERVIZIO`,`IDCOMUNE`,`CODICECOMUNE`,`SOFTWARE`),
  UNIQUE KEY `SERVIZI_PK` (`ID`),
  UNIQUE KEY `IDX_SERVIZI_02` (`ID_SERVIZIO`),
  UNIQUE KEY `IDX_SERVIZI_01` (`IDCOMUNE`,`CODICECOMUNE`,`SOFTWARE`),
  UNIQUE KEY `CLIENT_REGISTRATION_IDX` (`CLIENT_REGISTRATION_ID`),
  KEY `SERVIZI_TIPO_CONN_FK` (`FK_TIPO_CONNETTORE`),
  CONSTRAINT `SERVIZI_TIPO_CONN_FK` FOREIGN KEY (`FK_TIPO_CONNETTORE`) REFERENCES `tipo_connettore` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;


-- appio_gw.messaggi definition

CREATE TABLE messaggi (
  ID bigint(10) NOT NULL AUTO_INCREMENT,
  IDCOMUNE varchar(6) NOT NULL,
  CODICECOMUNE varchar(6) NOT NULL,
  SOFTWARE varchar(2) NOT NULL,
  TIME_TO_LIVE decimal(6,0) NOT NULL DEFAULT '3600',
  SUBJECT varchar(120) DEFAULT NULL,
  MARKDOWN longtext,
  AMOUNT decimal(10,0) DEFAULT NULL,
  NOTICE_NUMBER varchar(17) DEFAULT NULL,
  INVALID_AFTER_DUE_DATE decimal(1,0) DEFAULT NULL,
  NRE varchar(15) DEFAULT NULL,
  IUP varchar(16) DEFAULT NULL,
  PRESCRIBER_FISCAL_CODE varchar(16) DEFAULT NULL,
  DUE_DATE timestamp,
  EMAIL varchar(320) DEFAULT NULL,
  FISCAL_CODE varchar(16) DEFAULT NULL,
  ID_TRANSAZIONE varchar(100) DEFAULT NULL,
  SENDER_ALLOWED decimal(1,0) DEFAULT NULL,
  PREFERRED_LANGUAGES varchar(200) DEFAULT NULL,
  CREATED_AT timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FK_SERVIZI bigint(10) DEFAULT NULL,
  MESSAGE_ID varchar(36) NOT NULL,
  EMAIL_NOTIFICATION varchar(50) DEFAULT NULL,
  WEBHOOK_NOTIFICATION varchar(50) DEFAULT NULL,
  STATUS varchar(50) DEFAULT NULL,
  FK_STATO_MESSAGGIO bigint(10) DEFAULT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY MESSAGGI_PK (ID),
  UNIQUE KEY MESSAGGI_MESSAGE_ID_IDX (MESSAGE_ID),
  UNIQUE KEY IDX_MESSAGGI_01 (ID_TRANSAZIONE),
  KEY MESSAGGI_SERVIZI_FK (FK_SERVIZI),
  KEY MESSAGGI_STATO_MESSAGGIO_FK (FK_STATO_MESSAGGIO),
  CONSTRAINT MESSAGGI_SERVIZI_FK FOREIGN KEY (FK_SERVIZI) REFERENCES servizi (ID),
  CONSTRAINT MESSAGGI_STATO_MESSAGGIO_FK FOREIGN KEY (FK_STATO_MESSAGGIO) REFERENCES stato_messaggio (ID)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;


-- appio_gw.problem definition

CREATE TABLE problem (
  MESSAGGI_ID bigint(10) NOT NULL,
  TYPE varchar(200) DEFAULT NULL,
  TITLE varchar(200) DEFAULT NULL,
  STATUS decimal(3,0) DEFAULT NULL,
  DETAIL varchar(200) DEFAULT NULL,
  INSTANCE varchar(200) DEFAULT NULL,
  PRIMARY KEY (MESSAGGI_ID),
  UNIQUE KEY PROBLEM_PK (MESSAGGI_ID),
  CONSTRAINT PROBLEM_MESSAGGI_FK FOREIGN KEY (MESSAGGI_ID) REFERENCES messaggi (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;