spring.application.name=segnalazioniProxy

# Configurazione del server
server.port=${SEGNALAZIONI_SERVER_PORT}
server.servlet.context-path=/api-segnalazioni-proxy

# Configurazione del datasource (MySQL)
spring.datasource.url=REDACTED
spring.datasource.username=REDACTED
spring.datasource.password=REDACTED
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurazione JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Disattiva i log di SQL generati da Hibernate
spring.jpa.properties.hibernate.show_sql=false

# Sicurezza
#spring.security.basic.enabled=true

# Swagger (descrizione API)
swagger.api.title=Gestione Segnalazioni API
swagger.api.description=API per la gestione delle segnalazioni
swagger.api.version=1.0.0


# URL BASE
# http://vbg.backend:8281/backend
# URL base da quale partire per invocare i web service java

# SERVIZI VBG
gestorefile.url=REDACTED

# ALLEGATI
allegati.max-number=3
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

# SCHEDULER
# 5*60*1000ms = 300000ms = 5 minuti
scheduler.msFrequency=${SCHEDULER_FREQUENCY}
# Abilita o disabilita lo scheduler
scheduler.autoStartup=${SCHEDULER_AUTOSTARTUP}

# BASIC AUTH
basicauth.user=REDACTED
basicauth.password=REDACTED

# Allow nulls in JSON
spring.jackson.default-property-inclusion=always
# PARAMETRI FISSI PERSONA FISICA
persona-fisica.codice-fiscale=UTANON0000000000
persona-fisica.nome=ANONIMO
persona-fisica.cognome=CITTADINO
persona-fisica.sesso=M


management.server.port=${API_SEGNALAZIONI_MANAGEMENT_PORT:8081}
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true

