//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Init.SIGePro.Protocollo.LeggiProtocolloEGrammata2Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://195.62.187.39:8080/egrammata/services/WSRicercaProtocollo", ConfigurationName="LeggiProtocolloEGrammata2Service.WSRicercaProtocollo")]
    public interface WSRicercaProtocollo {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://protocollo.webservices.eng) of message ricercaRequest does not match the default value (http://195.62.187.39:8080/egrammata/services/WSRicercaProtocollo)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        Init.SIGePro.Protocollo.LeggiProtocolloEGrammata2Service.ricercaResponse ricerca(Init.SIGePro.Protocollo.LeggiProtocolloEGrammata2Service.ricercaRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://protocollo.webservices.eng) of message ricercaNSRequest does not match the default value (http://195.62.187.39:8080/egrammata/services/WSRicercaProtocollo)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        Init.SIGePro.Protocollo.LeggiProtocolloEGrammata2Service.ricercaNSResponse ricercaNS(Init.SIGePro.Protocollo.LeggiProtocolloEGrammata2Service.ricercaNSRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ricerca", WrapperNamespace="http://protocollo.webservices.eng", IsWrapped=true)]
    public partial class ricercaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string codEnte;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string indirizzoIP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string xml;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string hash;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string userApp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string postazione;
        
        public ricercaRequest() {
        }
        
        public ricercaRequest(string codEnte, string username, string password, string indirizzoIP, string xml, string hash, string userApp, string postazione) {
            this.codEnte = codEnte;
            this.username = username;
            this.password = password;
            this.indirizzoIP = indirizzoIP;
            this.xml = xml;
            this.hash = hash;
            this.userApp = userApp;
            this.postazione = postazione;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ricercaResponse", WrapperNamespace="http://195.62.187.39:8080/egrammata/services/WSRicercaProtocollo", IsWrapped=true)]
    public partial class ricercaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string ricercaReturn;
        
        public ricercaResponse() {
        }
        
        public ricercaResponse(string ricercaReturn) {
            this.ricercaReturn = ricercaReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ricercaNS", WrapperNamespace="http://protocollo.webservices.eng", IsWrapped=true)]
    public partial class ricercaNSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string codEnte;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string indirizzoIP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string xml;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string hash;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string userApp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string postazione;
        
        public ricercaNSRequest() {
        }
        
        public ricercaNSRequest(string codEnte, string username, string password, string indirizzoIP, string xml, string hash, string userApp, string postazione) {
            this.codEnte = codEnte;
            this.username = username;
            this.password = password;
            this.indirizzoIP = indirizzoIP;
            this.xml = xml;
            this.hash = hash;
            this.userApp = userApp;
            this.postazione = postazione;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ricercaNSResponse", WrapperNamespace="http://195.62.187.39:8080/egrammata/services/WSRicercaProtocollo", IsWrapped=true)]
    public partial class ricercaNSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string ricercaNSReturn;
        
        public ricercaNSResponse() {
        }
        
        public ricercaNSResponse(string ricercaNSReturn) {
            this.ricercaNSReturn = ricercaNSReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSRicercaProtocolloChannel : Init.SIGePro.Protocollo.LeggiProtocolloEGrammata2Service.WSRicercaProtocollo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSRicercaProtocolloClient : System.ServiceModel.ClientBase<Init.SIGePro.Protocollo.LeggiProtocolloEGrammata2Service.WSRicercaProtocollo>, Init.SIGePro.Protocollo.LeggiProtocolloEGrammata2Service.WSRicercaProtocollo {
        
        public WSRicercaProtocolloClient() {
        }
        
        public WSRicercaProtocolloClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSRicercaProtocolloClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSRicercaProtocolloClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSRicercaProtocolloClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Init.SIGePro.Protocollo.LeggiProtocolloEGrammata2Service.ricercaResponse Init.SIGePro.Protocollo.LeggiProtocolloEGrammata2Service.WSRicercaProtocollo.ricerca(Init.SIGePro.Protocollo.LeggiProtocolloEGrammata2Service.ricercaRequest request) {
            return base.Channel.ricerca(request);
        }
        
        public string ricerca(string codEnte, string username, string password, string indirizzoIP, string xml, string hash, string userApp, string postazione) {
            Init.SIGePro.Protocollo.LeggiProtocolloEGrammata2Service.ricercaRequest inValue = new Init.SIGePro.Protocollo.LeggiProtocolloEGrammata2Service.ricercaRequest();
            inValue.codEnte = codEnte;
            inValue.username = username;
            inValue.password = password;
            inValue.indirizzoIP = indirizzoIP;
            inValue.xml = xml;
            inValue.hash = hash;
            inValue.userApp = userApp;
            inValue.postazione = postazione;
            Init.SIGePro.Protocollo.LeggiProtocolloEGrammata2Service.ricercaResponse retVal = ((Init.SIGePro.Protocollo.LeggiProtocolloEGrammata2Service.WSRicercaProtocollo)(this)).ricerca(inValue);
            return retVal.ricercaReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Init.SIGePro.Protocollo.LeggiProtocolloEGrammata2Service.ricercaNSResponse Init.SIGePro.Protocollo.LeggiProtocolloEGrammata2Service.WSRicercaProtocollo.ricercaNS(Init.SIGePro.Protocollo.LeggiProtocolloEGrammata2Service.ricercaNSRequest request) {
            return base.Channel.ricercaNS(request);
        }
        
        public string ricercaNS(string codEnte, string username, string password, string indirizzoIP, string xml, string hash, string userApp, string postazione) {
            Init.SIGePro.Protocollo.LeggiProtocolloEGrammata2Service.ricercaNSRequest inValue = new Init.SIGePro.Protocollo.LeggiProtocolloEGrammata2Service.ricercaNSRequest();
            inValue.codEnte = codEnte;
            inValue.username = username;
            inValue.password = password;
            inValue.indirizzoIP = indirizzoIP;
            inValue.xml = xml;
            inValue.hash = hash;
            inValue.userApp = userApp;
            inValue.postazione = postazione;
            Init.SIGePro.Protocollo.LeggiProtocolloEGrammata2Service.ricercaNSResponse retVal = ((Init.SIGePro.Protocollo.LeggiProtocolloEGrammata2Service.WSRicercaProtocollo)(this)).ricercaNS(inValue);
            return retVal.ricercaNSReturn;
        }
    }
}
