alter table tipisoggetto add FLAG_FO_MOD_PRATICA number(1,0) default 0;
ALTER TABLE ALBEROPROC_PROTOCOLLO ADD SC_FASCNUMERO VARCHAR2(50);

CREATE TABLE INVENTARIOPROC_ENDO(
  IDCOMUNE VARCHAR2(6) NOT NULL,
  ID NUMBER(10,0) NOT NULL,
  CODICEINVENTARIO_T NUMBER(10,0) NOT NULL,
  CODICEINVENTARIO_D NUMBER(10,0) NOT NULL,
  FLAG_PUBBLICA NUMBER(1,0),
  FLAG_NECESSARIO NUMBER(1,0),
  CODICECOMUNE VARCHAR2(5)  
);

ALTER TABLE INVENTARIOPROC_ENDO ADD CONSTRAINT PK_INVENTARIOPROC_ENDO PRIMARY KEY (IDCOMUNE, ID);
ALTER TABLE INVENTARIOPROC_ENDO ADD CONSTRAINT FK_INVPROCENDO_INVPROC_T FOREIGN KEY (IDCOMUNE, CODICEINVENTARIO_T) REFERENCES INVENTARIOPROCEDIMENTI (IDCOMUNE, CODICEINVENTARIO);
ALTER TABLE INVENTARIOPROC_ENDO ADD CONSTRAINT FK_INVPROCENDO_INVPROC_D FOREIGN KEY (IDCOMUNE, CODICEINVENTARIO_D) REFERENCES INVENTARIOPROCEDIMENTI (IDCOMUNE, CODICEINVENTARIO);
ALTER TABLE INVENTARIOPROC_ENDO ADD CONSTRAINT FK_INVPROCENDO_COMUNI FOREIGN KEY (CODICECOMUNE) REFERENCES COMUNI (CODICECOMUNE);

create table LOCK_TABLE (
LOCK_NAME VARCHAR2(25) NOT NULL
);

ALTER TABLE LOCK_TABLE ADD CONSTRAINT PK_LOCK_TABLE PRIMARY KEY (LOCK_NAME);
