# PARAMETRI PER COMUNICAZIONE CON STC (registrare il nodo in STC)
ws.stc.url=REDACTED
ws.stc.user=REDACTED
ws.stc.pwd=REDACTED
# PARAMETRI PER COMUNICAZIONE CON SIGEPROSECURITY (registrare il nodo in sigeprosecurity)
ws.token.url=REDACTED
ws.token.user=REDACTED
ws.token.pwd=REDACTED
