#PARAMETRI DI DEPLOY
#
#JDBC CONNECTION OPTIONS
##------------ DRIVER ---------------------------------##
#
# com.mysql.jdbc.Driver
# oracle.jdbc.OracleDriver
# org.postgresql.Driver
# net.sourceforge.jtds.jdbc.Driver
#
##-----------------------------------------------------##
jdbc.driverClassName=com.mysql.jdbc.Driver
##-------STRINGHE DI CONNESSIONE-----------------------##
#
# jdbc:oracle:thin:@HOST:1521:SID
# jdbc:postgresql://HOST:5432:/DATABASE
# jdbc:mysql://HOST:3306/DATABASE?autoReconnect=true
# jdbc:jtds:sqlserver://DBMSSQL2005:1433/sigepro
#
##-----------------------------------------------------##
jdbc.url=REDACTED
jdbc.username=REDACTED
jdbc.password=REDACTED

#C3P0 OPTIONS

jdbc.c3p0.minPoolSize=5
jdbc.c3p0.maxPoolSize=20
jdbc.c3p0.acquireIncrement=5
jdbc.c3p0.idleConnectionTestPeriod=600
jdbc.c3p0.maxIdleTime=1800
jdbc.c3p0.maxStatements=50

#HIBERNATE OPTIONS
##------------ DIALETTI -------------------------------##
#
# org.hibernate.dialect.MySQLDialect
# org.hibernate.dialect.MySQLInnoDBDialect
# org.hibernate.dialect.MySQLMyISAMDialect
# org.hibernate.dialect.Oracle8iDialect
# org.hibernate.dialect.Oracle10gDialect
# org.hibernate.dialect.Oracle9iDialect
# org.hibernate.dialect.PostgreSQLDialect
# org.hibernate.dialect.SQLServerDialect
#
##-----------------------------------------------------##
hibernate.dialect=org.hibernate.dialect.MySQLInnoDBDialect
hibernate.connection.release_mode=on_close
hibernate.generate_statistics=false
hibernate.show_sql=false
hibernate.use_sql_comments=false
hibernate.format_sql=false

#LOB HANDLER
##------------ HANDLER --------------------------------##
# oracle
# default
##-----------------------------------------------------##
hibernate.lobhandler=default
