log4j.rootLogger=WARN, logfile

log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d %p [%c] %nSTC - <%m>%n

log4j.appender.logfile=org.apache.log4j.RollingFileAppender
log4j.appender.logfile.File=${catalina.base}/logs/stc.log
log4j.appender.logfile.MaxFileSize=10240KB
log4j.appender.logfile.MaxBackupIndex=10
log4j.appender.logfile.layout=org.apache.log4j.PatternLayout
log4j.appender.logfile.layout.ConversionPattern=%d{dd/MM/yyyy hh:mm:ss} %p [%c] %n - <%m>%n

log4j.appender.upgractivitylogfile =org.apache.log4j.RollingFileAppender
log4j.appender.upgractivitylogfile.File=${catalina.base}/logs/stc-upgr-activity.log
log4j.appender.upgractivitylogfile.MaxBackupIndex=20
log4j.appender.upgractivitylogfile.MaxFileSize=10240KB
log4j.appender.upgractivitylogfile.layout=org.apache.log4j.PatternLayout
log4j.appender.upgractivitylogfile.layout.ConversionPattern=%d [%t] %-5p - %m%n

log4j.appender.upgrerrorlogfile=org.apache.log4j.RollingFileAppender
log4j.appender.upgrerrorlogfile.File=${catalina.base}/logs/stc-upgr-error.log
log4j.appender.upgrerrorlogfile.MaxBackupIndex=20
log4j.appender.upgrerrorlogfile.MaxFileSize=10240KB
log4j.appender.upgrerrorlogfile.layout=org.apache.log4j.PatternLayout
log4j.appender.upgrerrorlogfile.layout.ConversionPattern=%d [%t] %-5p - %m%n

log4j.appender.upgrexceptionlogfile=org.apache.log4j.RollingFileAppender
log4j.appender.upgrexceptionlogfile.File=${catalina.base}/logs/stc-upgr-exception.log
log4j.appender.upgrexceptionlogfile.MaxBackupIndex=20
log4j.appender.upgrexceptionlogfile.MaxFileSize=10240KB
log4j.appender.upgrexceptionlogfile.layout=org.apache.log4j.PatternLayout
log4j.appender.upgrexceptionlogfile.layout.ConversionPattern=%d [%t] %-5p %c %n - %m%n

#log4j.logger.org.springframework.security=WARN
log4j.logger.org.apache.cxf=WARN
#log delle chiamate soap(INFO=on,WARN=off)
log4j.logger.org.apache.cxf.services=WARN
log4j.logger.org.springframework=WARN
#log4j.logger.org.hibernate=INFO
#log4j.logger.org.hibernate.connection=WARN

## impostare a DEBUG per visualizzare tutte le query
log4j.logger.org.hibernate.SQL=WARN

## impostare a DEBUG per visualizzare i parametri di binding o a TRACE per visualizzare anche i parametri di ritorno
log4j.logger.org.hibernate.type=WARN

log4j.logger.it.gruppoinit.stc=WARN

#impostazioni di log per UPGR4J
#file in cui vengono loggate tutte le attività di UPGR
log4j.logger.it.gruppoinit.upgr.activity=DEBUG, upgractivitylogfile
log4j.additivity.it.gruppoinit.upgr.activity=false

#file in cui vengono loggati solo gli errori di UPGR uno per riga senza lo stack delle eccezioni
log4j.logger.it.gruppoinit.upgr.error=WARN, upgrerrorlogfile
log4j.additivity.it.gruppoinit.upgr.error=false

#file in cui vengono loggate tutte le eccezioni di UPGR con la stampa dello stack delle eccezioni
log4j.logger.it.gruppoinit.upgr.exception=ERROR, upgrexceptionlogfile
log4j.additivity.it.gruppoinit.upgr.exception=false
