ALTER TABLE CONFIGURAZIONE_CALCOLI ADD VERSIONE DECIMAL(2,0) NULL;
UPDATE CONFIGURAZIONE_CALCOLI SET VERSIONE = 1 WHERE VERSIONE IS NULL;
ALTER TABLE CONFIGURAZIONE_CALCOLI MODIFY VERSIONE DECIMAL(2,0) NOT NULL;

alter table tipimovimento_rabbit drop foreign key FK_MAILTIPO_TIPIMOVRABBIT;
alter table tipimovimento_rabbit drop foreign key FK_TIPIMOV_TIPIMOVRABBIT;
alter table tipimovimento_rabbit drop primary key;

alter table tipimovimento_rabbit add constraint pk_tipimov_rabbit PRIMARY KEY(idcomune,fk_tipimovimento,topic);
alter table tipimovimento_rabbit add constraint FK_MAILTIPO_TIPIMOVRABBIT FOREIGN KEY (IDCOMUNE, fk_mailtipo) REFERENCES mailtipo (IDCOMUNE, CODICEMAIL);
alter table tipimovimento_rabbit add constraint FK_TIPIMOV_TIPIMOVRABBIT FOREIGN KEY (IDCOMUNE, fk_tipimovimento) REFERENCES tipimovimento (IDCOMUNE, TIPOMOVIMENTO);


ALTER TABLE tipisoggetto ADD flag_riceve_notifiche NUMERIC(1,0);
UPDATE tipisoggetto SET flag_riceve_notifiche = 0 WHERE flag_riceve_notifiche IS NULL;
ALTER TABLE tipisoggetto MODIFY flag_riceve_notifiche NUMERIC(1,0) NOT NULL DEFAULT 0;

ALTER TABLE app_io_coda MODIFY COLUMN STATO_MESSAGGIO VARCHAR(500);

alter table tipimovimento_rabbit modify fk_mailtipo decimal(4,0);

alter table statiistanza add column flag_filtrabile_front decimal(1,0);

CREATE TABLE MOVIMENTI_METADATI(IDCOMUNE VARCHAR(6) NOT NULL, CODICEMOVIMENTO DECIMAL(8,0) NOT NULL, CHIAVE VARCHAR(60) NOT NULL, VALORE VARCHAR(500)  NOT NULL )ENGINE=INNODB DEFAULT CHARSET=utf8;
ALTER TABLE MOVIMENTI_METADATI ADD CONSTRAINT PK_MOVIMENTI_METADATI PRIMARY KEY(IDCOMUNE,CODICEMOVIMENTO,CHIAVE);
ALTER TABLE MOVIMENTI_METADATI ADD CONSTRAINT FK_MOVIMENTIMETADATI_001 FOREIGN KEY(IDCOMUNE,CODICEMOVIMENTO) REFERENCES MOVIMENTI(IDCOMUNE,CODICEMOVIMENTO);
CREATE INDEX IDX_MOVIMENTIMETADATI_001 ON MOVIMENTI_METADATI(IDCOMUNE,CODICEMOVIMENTO);
CREATE TABLE SCADENZE_ELIMINATE(IDCOMUNE VARCHAR(6) NOT NULL, UUID VARCHAR(60) NOT NULL) ENGINE=INNODB DEFAULT CHARSET=utf8;
ALTER TABLE SCADENZE_ELIMINATE ADD CONSTRAINT PK_SCADENZEELIMINATE PRIMARY KEY(IDCOMUNE,UUID);

CREATE TABLE MESSAGGI_RABBIT_MOVIMENTI(IDCOMUNE VARCHAR(6) NOT NULL, FK_MSGRABBIT_GUID VARCHAR(40) NOT NULL, UUID_MOVIMENTO VARCHAR(60) NOT NULL) ENGINE=INNODB DEFAULT CHARSET=utf8;
ALTER TABLE MESSAGGI_RABBIT_MOVIMENTI ADD CONSTRAINT PK_MSG_RABBIT_MOVIMENTI PRIMARY KEY (IDCOMUNE,FK_MSGRABBIT_GUID, UUID_MOVIMENTO);
ALTER TABLE MESSAGGI_RABBIT_MOVIMENTI ADD CONSTRAINT FK_MSGRABBITMOV_MSGRABBIT FOREIGN KEY (IDCOMUNE,FK_MSGRABBIT_GUID) REFERENCES MESSAGGI_RABBIT(IDCOMUNE,GUID);

CREATE TABLE MESSAGGI_RABBIT_ISTANZE (IDCOMUNE VARCHAR(6) NOT NULL, FK_MSGRABBIT_GUID VARCHAR(40) NOT NULL, UUID_ISTANZA VARCHAR(60) NOT NULL) ENGINE=INNODB DEFAULT CHARSET=UTF8;
ALTER TABLE MESSAGGI_RABBIT_ISTANZE ADD CONSTRAINT PK_MSGRABBIT_ISTANZE  PRIMARY KEY (IDCOMUNE,FK_MSGRABBIT_GUID, UUID_ISTANZA);
ALTER TABLE MESSAGGI_RABBIT_ISTANZE ADD CONSTRAINT FK_MSGRABBIT_MSG_RABBIT FOREIGN KEY (IDCOMUNE,FK_MSGRABBIT_GUID) REFERENCES MESSAGGI_RABBIT (IDCOMUNE,GUID);


CREATE TABLE MESSAGGI_RABBIT_PAGAMENTI (
  IDCOMUNE VARCHAR(6) NOT NULL,
  FK_MSGRABBIT_GUID VARCHAR(40) NOT NULL,
  UUID_POSIZIONE_DEB VARCHAR(60) NOT NULL
 ) ENGINE=INNODB DEFAULT CHARSET=UTF8;

ALTER TABLE MESSAGGI_RABBIT_PAGAMENTI ADD CONSTRAINT PK_MESSAGGI_RABBIT_PAGAMENTI PRIMARY KEY (IDCOMUNE,FK_MSGRABBIT_GUID,UUID_POSIZIONE_DEB);
ALTER TABLE MESSAGGI_RABBIT_PAGAMENTI ADD CONSTRAINT FK_MSGRABBITPAG_MSGRABBIT FOREIGN KEY (IDCOMUNE, FK_MSGRABBIT_GUID) REFERENCES MESSAGGI_RABBIT (IDCOMUNE, GUID);

