ALTER TABLE FESTE_SAGRE ADD DATA_INSERIMENTO DATE;
ALTER TABLE FIERE_MOSTRE ADD DATA_INSERIMENTO DATE;

ALTER TABLE FIERE_MOSTRE ADD TIPOLOGIA VARCHAR(50);

ALTER TABLE RESPONSABILI ADD GESTIONE_AREEPUBBLICHE NUMERIC(1,0)  DEFAULT 0;

CREATE TABLE MANIF_AREE_PUBBLICHE(
IDCOMUNE VARCHAR(6) NOT NULL,
ID NUMERIC(10,0) NOT NULL,
DATA_INSERIMENTO DATE NOT NULL,
TIPOLOGIA VARCHAR (50),
DENOMINAZIONE VARCHAR (150) NOT NULL,
FK_COMUNE_SVOLGIMENTO VARCHAR(5) NOT NULL,
MON NUMERIC(1,0),
TUE NUMERIC(1,0),
WEN NUMERIC(1,0),
THU NUMERIC(1,0),
FRID NUMERIC(1,0),
SAT NUMERIC(1,0),
SUN NUMERIC(1,0),
CADENZA VARCHAR (50),
PERIODO_SVOLGIMENTO VARCHAR(500),
NUMERO_POSTEGGI_ASSEGNATI NUMERIC(6,0),
NUMERO_POSTEGGI_SPUNTISTI NUMERIC(6,0)
) ENGINE=INNODB DEFAULT CHARSET=utf8;



ALTER TABLE MANIF_AREE_PUBBLICHE ADD CONSTRAINT PK_MANIF_AREE_PUBBLICHE PRIMARY KEY (IDCOMUNE,ID);
ALTER TABLE MANIF_AREE_PUBBLICHE ADD CONSTRAINT FK_COMUNI FOREIGN KEY (FK_COMUNE_SVOLGIMENTO) REFERENCES COMUNI(CODICECOMUNE);

ALTER TABLE RESPONSABILI ADD GESTIONE_INSERIMENTO_ANAGRAFICHE NUMERIC(1,0)  DEFAULT 0;

/**
 * TABELLA ANAGRAFE_IMPRESE 
 * 
 *
 */

CREATE TABLE ANAGRAFE_IMPRESA(
IDCOMUNE VARCHAR(6) NOT NULL,
ID NUMERIC(10,0) NOT NULL,
COGNOME VARCHAR(100) NOT NULL,
NOME VARCHAR(100) NOT NULL,
COMUNE_NASCITA VARCHAR(5),
PROVINCIA_NASCITA VARCHAR(2),
CODICEFISCALE VARCHAR(20) NOT NULL,
CITTADINANZA NUMERIC(4,0),
SESSO VARCHAR(1),
COMUNE_RESIDENZA VARCHAR(5),
PROVINCIA_RESIDENZA VARCHAR(2),
CAP VARCHAR(5),
INDIRIZZO VARCHAR(200),
CIVICO VARCHAR(10),
PERMESSO_CARTA_SOGGIORNO VARCHAR(100),
DATA_RILASCIO_PERMESSO_SOGG DATE,
RILASCIATO_DA VARCHAR(100),
MOTIVO_RILASCIO VARCHAR(500),
DATA_FINE_VALIDITA_PERM DATE,
DATA_RINNOVO_PERM DATE,
ESTREMI_RACCOMANDATA_RINNOV VARCHAR (200),
IN_QUALITA_DI VARCHAR (100),
DENOMINAZIONE VARCHAR (200),
CF_PI VARCHAR (20),
COMUNE_SEDE_LEGALE VARCHAR(5),
PROV_SEDE_LEGALE VARCHAR(2),
CAP_SEDE_LEGALE VARCHAR(5),
TOPONIMO_SEDE_LEGALE VARCHAR (10),
INDIRIZZO_SEDE_LEGALE VARCHAR(100),
CIVICO_SEDE_LEGALE VARCHAR(10),
TELEFONO_SEDE_LEGALE VARCHAR(100),
ISCRIZIONE_REG_IMPRESE DATE,
NUMERO_REG_IMPRESE VARCHAR (100),
CAMERA_COMM_IAA VARCHAR(100)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

ALTER TABLE ANAGRAFE_IMPRESA ADD CONSTRAINT PK_ANAGRAFE_IMPRESA PRIMARY KEY (IDCOMUNE,ID);
ALTER TABLE ANAGRAFE_IMPRESA ADD CONSTRAINT FK_COMUNE_NASCITA FOREIGN KEY (COMUNE_NASCITA) REFERENCES COMUNI_ITALIANI(CODICECOMUNE);
ALTER TABLE ANAGRAFE_IMPRESA ADD CONSTRAINT FK_CITTADINANZA FOREIGN KEY (CITTADINANZA) REFERENCES CITTADINANZA(CODICE);
ALTER TABLE ANAGRAFE_IMPRESA ADD CONSTRAINT FK_COMUNE_RESIDENZA FOREIGN KEY (COMUNE_RESIDENZA) REFERENCES COMUNI_ITALIANI(CODICECOMUNE);
ALTER TABLE ANAGRAFE_IMPRESA ADD CONSTRAINT FK_COMUNE_SEDE_LEGALE FOREIGN KEY (COMUNE_SEDE_LEGALE) REFERENCES COMUNI_ITALIANI(CODICECOMUNE);


/**
 * TABELLA CONFIGURAZIONI EMAIL
 */

CREATE TABLE CONFIGURAZIONE_EMAIL(
IDCOMUNE VARCHAR(6) NOT NULL,
ID NUMERIC(10,0) NOT NULL,
MAIL_FROM VARCHAR(100) NOT NULL,
MAIL_TO VARCHAR(500) NOT NULL,
MAIL_SERVER VARCHAR(100) NOT NULL,
MAIL_PORT VARCHAR(10) NOT NULL,
MAIL_USE_AUTENTICATION NUMERIC(1,0) NOT NULL,
MAIL_PROTOCOLL VARCHAR(20) NOT NULL,
MAIL_USER VARCHAR(100),
MAIL_PASSWORD VARCHAR(100),
MAIL_INVIO_DISABILITATO NUMERIC(1,0) NOT NULL,
MAIL_OGGETTO VARCHAR(200) NOT NULL,
MAIL_CORPO VARCHAR(800) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8;

ALTER TABLE CONFIGURAZIONE_EMAIL ADD CONSTRAINT PK_CONFIGURAZIONE_EMAIL PRIMARY KEY (IDCOMUNE,ID);


ALTER TABLE COMUNIASSOCIATI ADD ONSITE NUMERIC(1,0)  DEFAULT 0;


