CREATE DATABASE gestione_calendari CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE USER 'gest_cal'@'%' IDENTIFIED BY 'gest_cal';
GRANT ALL PRIVILEGES ON gestione_calendari.* TO 'gest_cal'@'%';
FLUSH PRIVILEGES;

CREATE TABLE comuniassociati (     
       IDCOMUNE VARCHAR(6) NOT NULL
     , CODICECOMUNE VARCHAR(5) NOT NULL
     , IMPORT_AUTOMATICO DECIMAL(1)
     , ONSITE DECIMAL(1)
     , PRIMARY KEY (IDCOMUNE, CODICECOMUNE)
);

CREATE TABLE responsabili (
	   IDCOMUNE VARCHAR(6) NOT NULL
     , CODICERESPONSABILE DECIMAL(8) NOT NULL    
     , RESPONSABILE VARCHAR(60)
     , USERID VARCHAR(250)
     , AMMINISTRATORE DECIMAL(1)
     , PASSWORD VARCHAR(32)
     , STRONG_AUTH_ID VARCHAR(250)
     , READONLY DECIMAL(1)
     , DISABILITATO DECIMAL(1)
     , GESTIONE_FIERE_MOSTRE DECIMAL(1)
     , GESTIONE_FESTE_SAGRE DECIMAL(1)
     , PRIMARY KEY (IDCOMUNE, CODICERESPONSABILE)
);
CREATE UNIQUE INDEX USERID_UNIQUE ON responsabili (IDCOMUNE ASC, USERID ASC);

CREATE TABLE comuni (
       CODICECOMUNE VARCHAR(5) NOT NULL
     , COMUNE VARCHAR(128)
     , SIGLAPROVINCIA VARCHAR(2)
     , PROVINCIA VARCHAR(20)
     , REGIONE VARCHAR(25)
     , CAP VARCHAR(5)
     , CF VARCHAR(5)
     , CODICEISTAT VARCHAR(6)
     , CODICEISTATREGIONE VARCHAR(2)
     , CODICESTATOESTERO VARCHAR(3)
     , PRIMARY KEY (CODICECOMUNE)
);

CREATE TABLE responsabilicomuni (
	   IDCOMUNE VARCHAR(6) NOT NULL
	 , CODICECOMUNE VARCHAR(5) NOT NULL
     , CODICERESPONSABILE DECIMAL(8) NOT NULL
     , PRIMARY KEY (IDCOMUNE, CODICECOMUNE, CODICERESPONSABILE)
     , CONSTRAINT FK_RESPCOMUNI_COMUNI FOREIGN KEY (CODICECOMUNE)
                  REFERENCES comuni (CODICECOMUNE) ON DELETE NO ACTION ON UPDATE NO ACTION
     , CONSTRAINT FK_RESPON_COM_COMUNI_ASS FOREIGN KEY (IDCOMUNE, CODICECOMUNE)
                  REFERENCES comuniassociati (IDCOMUNE, CODICECOMUNE) ON DELETE NO ACTION ON UPDATE NO ACTION
     , CONSTRAINT FK_RESPCOMUNI_RESPONSABILI FOREIGN KEY (IDCOMUNE, CODICERESPONSABILE)
                  REFERENCES responsabili (IDCOMUNE, CODICERESPONSABILE) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE fiere_mostre (
	   IDCOMUNE VARCHAR(6) NOT NULL
	 , ID DECIMAL(6) NOT NULL
	 , DENOMINAZIONE VARCHAR(250)
     , ID_ISTANZA VARCHAR(200)
     , NUMEROISTANZA VARCHAR(60)
     , DATAISTANZA	DATE
     , NUM_PROTOCOLLOISTANZA VARCHAR(30)
     , NUM_AUTORIZZAZIONE VARCHAR(30)
     , DATA_AUTORIZZAZIONE DATE
     , LUOGO_SVOLGIMENTO VARCHAR(200)
     , ORGANIZZATORE VARCHAR(150)   
     , CLASSIFICAZIONE VARCHAR(100)
     , QUALIFICA VARCHAR(100)
     , CODICECOMUNE VARCHAR(5)
     , CODICECOMUNE_SVOLGIMENTO VARCHAR(5)
     , PRIMARY KEY (IDCOMUNE, ID)
     , CONSTRAINT FK_FIERE_MOSTRE_COMUNI FOREIGN KEY (CODICECOMUNE)
                  REFERENCES comuni (CODICECOMUNE) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE fiere_mostre_periodi (
	   IDCOMUNE VARCHAR(6) NOT NULL
	 , ID DECIMAL(6) NOT NULL	 
     , DAL DATE
     , AL DATE
     , ID_FIERE_MOSTRE DECIMAL(6) NOT NULL
     , PRIMARY KEY (IDCOMUNE, ID)
     , CONSTRAINT FK_PERIODI_FIEREMOSTRE FOREIGN KEY (IDCOMUNE, ID_FIERE_MOSTRE)
                  REFERENCES fiere_mostre (IDCOMUNE, ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE fiere_mostre_merceologie (
	   IDCOMUNE VARCHAR(6) NOT NULL
	 , ID DECIMAL(6) NOT NULL	 
     , MERCEOLOGIA VARCHAR(100)
     , ID_FIERE_MOSTRE DECIMAL(6) NOT NULL
     , PRIMARY KEY (IDCOMUNE, ID)
     , CONSTRAINT FK_MERCEOLOGIE_FIEREMOSTRE FOREIGN KEY (IDCOMUNE, ID_FIERE_MOSTRE)
                  REFERENCES fiere_mostre (IDCOMUNE, ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE feste_sagre (
	   IDCOMUNE VARCHAR(6) NOT NULL
     , ID DECIMAL(6) NOT NULL
     , DENOMINAZIONE VARCHAR(250)
     , ID_ISTANZA VARCHAR(200)
     , NUMEROISTANZA VARCHAR(60)
     , DATAISTANZA	DATE
     , DAL DATE
     , AL DATE
     , NUM_PROTOCOLLOISTANZA VARCHAR(30)
     , NUM_AUTORIZZAZIONE VARCHAR(30)
     , DATA_AUTORIZZAZIONE DATE
     , TIPOLOGIA VARCHAR(100)
     , LUOGO_SVOLGIMENTO VARCHAR(200)
     , ORGANIZZATORE VARCHAR(150)    
     , CODICECOMUNE VARCHAR(5)
     , CODICECOMUNE_SVOLGIMENTO VARCHAR(5)
     , PRIMARY KEY (IDCOMUNE, ID)
     , CONSTRAINT FK_FESTE_SAGRE_COMUNI FOREIGN KEY (CODICECOMUNE)
                  REFERENCES comuni (CODICECOMUNE) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE sequencetable (
  	  IDCOMUNE VARCHAR(6) NOT NULL,
  	  SEQUENCENAME VARCHAR(50) NOT NULL,
  	  CURRVAL DECIMAL(8) NOT NULL,
  	  PRIMARY KEY (IDCOMUNE, SEQUENCENAME)
);

insert into responsabili (CODICERESPONSABILE,RESPONSABILE,AMMINISTRATORE,PASSWORD,IDCOMUNE,USERID,READONLY,DISABILITATO,GESTIONE_FIERE_MOSTRE,GESTIONE_FESTE_SAGRE) values (1,"Amministratore",1,"202cb962ac59075b964b07152d234b70","DEF","admin",0,0,1,1);
