DROP TABLE FESTE_SAGRE;
DROP TABLE FIERE_MOSTRE_PERIODI;
DROP TABLE FIERE_MOSTRE_MERCEOLOGIE;
DROP TABLE FIERE_MOSTRE;
DROP TABLE RESPONSABILICOMUNI;
DROP TABLE RESPONSABILI;
DROP TABLE COMUNIASSOCIATI;
DROP TABLE COMUNI;
DROP TABLE SEQUENCETABLE;

CREATE TABLE comuniassociati (     
       IDCOMUNE VARCHAR2(6 CHAR) NOT NULL
     , CODICECOMUNE VARCHAR2(5 CHAR) NOT NULL
     , IMPORT_AUTOMATICO NUMBER(1)
     , ONSITE NUMBER(1)
     , PRIMARY KEY (IDCOMUNE, CODICECOMUNE)
);

CREATE TABLE responsabili (
	   IDCOMUNE VARCHAR2(6 CHAR) NOT NULL
     , CODICERESPONSABILE NUMBER(8) NOT NULL    
     , RESPONSABILE VARCHAR2(60 CHAR)
     , USERID VARCHAR2(250 CHAR)
     , AMMINISTRATORE NUMBER(1)
     , PASSWORD VARCHAR2(32 CHAR)
     , STRONG_AUTH_ID VARCHAR2(250 CHAR)
     , READONLY NUMBER(1)
     , DISABILITATO NUMBER(1)
     , GESTIONE_FIERE_MOSTRE NUMBER(1)
     , GESTIONE_FESTE_SAGRE NUMBER(1)
     , PRIMARY KEY (IDCOMUNE, CODICERESPONSABILE)
);
CREATE UNIQUE INDEX USERID_UNIQUE ON responsabili (IDCOMUNE ASC, USERID ASC);

CREATE TABLE comuni (
       CODICECOMUNE VARCHAR2(5 CHAR) NOT NULL
     , COMUNE VARCHAR2(128 CHAR)
     , SIGLAPROVINCIA VARCHAR2(2 CHAR)
     , PROVINCIA VARCHAR2(20 CHAR)
     , REGIONE VARCHAR2(25 CHAR)
     , CAP VARCHAR2(5 CHAR)
     , CF VARCHAR2(5 CHAR)
     , CODICEISTAT VARCHAR2(6 CHAR)
     , CODICEISTATREGIONE VARCHAR2(2 CHAR)
     , CODICESTATOESTERO VARCHAR2(3 CHAR)
     , PRIMARY KEY (CODICECOMUNE)
);

CREATE TABLE responsabilicomuni (
	   IDCOMUNE VARCHAR2(6 CHAR) NOT NULL
	 , CODICECOMUNE VARCHAR2(5 CHAR) NOT NULL
     , CODICERESPONSABILE NUMBER(8) NOT NULL
     , PRIMARY KEY (IDCOMUNE, CODICECOMUNE, CODICERESPONSABILE)
     , CONSTRAINT FK_RESPCOMUNI_COMUNI FOREIGN KEY (CODICECOMUNE)
                  REFERENCES comuni (CODICECOMUNE)
     , CONSTRAINT FK_RESPON_COM_COMUNI_ASS FOREIGN KEY (IDCOMUNE, CODICECOMUNE)
                  REFERENCES comuniassociati (IDCOMUNE, CODICECOMUNE)
     , CONSTRAINT FK_RESPCOMUNI_RESPONSABILI FOREIGN KEY (IDCOMUNE, CODICERESPONSABILE)
                  REFERENCES responsabili (IDCOMUNE, CODICERESPONSABILE)
);

CREATE TABLE fiere_mostre (
	   IDCOMUNE VARCHAR2(6 CHAR) NOT NULL
	 , ID NUMBER(6) NOT NULL
	 , DENOMINAZIONE VARCHAR2(250 CHAR)
     , ID_ISTANZA VARCHAR2(200 CHAR)
     , NUMEROISTANZA VARCHAR2(60 CHAR)
     , DATAISTANZA	DATE
     , NUM_PROTOCOLLOISTANZA VARCHAR2(30 CHAR)
     , NUM_AUTORIZZAZIONE VARCHAR2(30 CHAR)
     , DATA_AUTORIZZAZIONE DATE
     , LUOGO_SVOLGIMENTO VARCHAR2(200 CHAR)
     , ORGANIZZATORE VARCHAR2(150 CHAR)   
     , CLASSIFICAZIONE VARCHAR2(100 CHAR)
     , QUALIFICA VARCHAR2(100 CHAR)
     , CODICECOMUNE VARCHAR2(5 CHAR)
     , CODICECOMUNE_SVOLGIMENTO VARCHAR2(5 CHAR)
     , PRIMARY KEY (IDCOMUNE, ID)
     , CONSTRAINT FK_FIERE_MOSTRE_COMUNI FOREIGN KEY (CODICECOMUNE)
                  REFERENCES comuni (CODICECOMUNE)
);

CREATE TABLE fiere_mostre_periodi (
	   IDCOMUNE VARCHAR2(6 CHAR) NOT NULL
	 , ID NUMBER(6) NOT NULL	 
     , DAL DATE
     , AL DATE
     , ID_FIERE_MOSTRE NUMBER(6) NOT NULL
     , PRIMARY KEY (IDCOMUNE, ID)
     , CONSTRAINT FK_PERIODI_FIEREMOSTRE FOREIGN KEY (IDCOMUNE, ID_FIERE_MOSTRE)
                  REFERENCES fiere_mostre (IDCOMUNE, ID)
);

CREATE TABLE fiere_mostre_merceologie (
	   IDCOMUNE VARCHAR2(6 CHAR) NOT NULL
	 , ID NUMBER(6) NOT NULL	 
     , MERCEOLOGIA VARCHAR2(100 CHAR)
     , ID_FIERE_MOSTRE NUMBER(6) NOT NULL
     , PRIMARY KEY (IDCOMUNE, ID)
     , CONSTRAINT FK_MERCEOLOGIE_FIEREMOSTRE FOREIGN KEY (IDCOMUNE, ID_FIERE_MOSTRE)
                  REFERENCES fiere_mostre (IDCOMUNE, ID)
);

CREATE TABLE feste_sagre (
	   IDCOMUNE VARCHAR2(6 CHAR) NOT NULL
     , ID NUMBER(6) NOT NULL
     , DENOMINAZIONE VARCHAR2(250 CHAR)
     , ID_ISTANZA VARCHAR2(200 CHAR)
     , NUMEROISTANZA VARCHAR2(60 CHAR)
     , DATAISTANZA	DATE
     , DAL DATE
     , AL DATE
     , NUM_PROTOCOLLOISTANZA VARCHAR2(30 CHAR)
     , NUM_AUTORIZZAZIONE VARCHAR2(30 CHAR)
     , DATA_AUTORIZZAZIONE DATE
     , TIPOLOGIA VARCHAR2(100 CHAR)
     , LUOGO_SVOLGIMENTO VARCHAR2(200 CHAR)
     , ORGANIZZATORE VARCHAR2(150 CHAR)    
     , CODICECOMUNE VARCHAR2(5 CHAR)
     , CODICECOMUNE_SVOLGIMENTO VARCHAR2(5 CHAR)
     , PRIMARY KEY (IDCOMUNE, ID)
     , CONSTRAINT FK_FESTE_SAGRE_COMUNI FOREIGN KEY (CODICECOMUNE)
                  REFERENCES comuni (CODICECOMUNE)
);

CREATE TABLE sequencetable (
  	  IDCOMUNE VARCHAR2(6 CHAR) NOT NULL,
  	  SEQUENCENAME VARCHAR2(50 CHAR) NOT NULL,
  	  CURRVAL NUMBER(8) NOT NULL,
  	  PRIMARY KEY (IDCOMUNE, SEQUENCENAME)
);

insert into responsabili (CODICERESPONSABILE,RESPONSABILE,AMMINISTRATORE,PASSWORD,IDCOMUNE,USERID,READONLY,DISABILITATO,GESTIONE_FIERE_MOSTRE,GESTIONE_FESTE_SAGRE) values (1,'Amministratore',1,'202cb962ac59075b964b07152d234b70','DEF','admin',0,0,1,1);

