package it.gruppoinit.pal.gp.core.dao.helper;

public enum SnapshotType {
    SAVE_ATTIVITA_SNAPSHOT, COLLEGA_ISTANZA_SNAPSHOT, SCOLLEGA_ISTANZA_SNAPSHOT, CALCOLA_DATA_VALIDITA_ISTANZA_SNAPSHOT, AGGIORNA_SNAPSHOT_A_PARTIRE_DA
}
