ALTER TABLE ONERITIPIRATEIZZAZIONE ADD (TIPOLOGIA_RATEIZZAZIONE VARCHAR2(100));
ALTER TABLE TIPIMOV_STC_MAPPING MODIFY (PROTOCOLLO_TIPODOCUMENTO VARCHAR2(30 CHAR) );
ALTER TABLE ISTANZEPROCEDIMENTI ADD (DESCRIZIONE_ENDOPROCEDIMENTO VARCHAR2(1500));


ALTER TABLE istanzeprocure MODIFY FK_ANAG_PROC_STORICO NUMBER(10,0);


ALTER TABLE istanzeprocure MODIFY FK_ANAG_RAPP_STORICO NUMBER(10,0);
