//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Init.Sigepro.FrontEnd.Reserved.InserimentoIstanza {
    
    
    public partial class DettagliAnagraficaPg {
        
        /// <summary>
        /// ANAGRAFE_PK control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden ANAGRAFE_PK;
        
        /// <summary>
        /// TipoSoggetto control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.Common.ComboTipiSoggetto TipoSoggetto;
        
        /// <summary>
        /// txtDescrizioneEstesa control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtDescrizioneEstesa;
        
        /// <summary>
        /// Nominativo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.TextBox Nominativo;
        
        /// <summary>
        /// CodiceFormaGiuridica control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.DropDownList CodiceFormaGiuridica;
        
        /// <summary>
        /// CodiceFiscale control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.TextBox CodiceFiscale;
        
        /// <summary>
        /// PartitaIva control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.TextBox PartitaIva;
        
        /// <summary>
        /// DataNominativo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.DateTextBox DataNominativo;
        
        /// <summary>
        /// acComuneSedeLegale control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.Autocomplete acComuneSedeLegale;
        
        /// <summary>
        /// Indirizzo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.TextBox Indirizzo;
        
        /// <summary>
        /// Citta control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.TextBox Citta;
        
        /// <summary>
        /// Cap control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.TextBox Cap;
        
        /// <summary>
        /// RegDitte control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.TextBox RegDitte;
        
        /// <summary>
        /// DataRegDitte control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.DateTextBox DataRegDitte;
        
        /// <summary>
        /// acProvinciaCCIAA control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.Autocomplete acProvinciaCCIAA;
        
        /// <summary>
        /// RegTrib control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.TextBox RegTrib;
        
        /// <summary>
        /// RegTribData control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.DateTextBox RegTribData;
        
        /// <summary>
        /// acComuneRegTrib control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.Autocomplete acComuneRegTrib;
        
        /// <summary>
        /// NumIscrREA control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.TextBox NumIscrREA;
        
        /// <summary>
        /// DataIscrREA control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.DateTextBox DataIscrREA;
        
        /// <summary>
        /// acProvinciaREA control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.Autocomplete acProvinciaREA;
        
        /// <summary>
        /// txtNumeroInps control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.TextBox txtNumeroInps;
        
        /// <summary>
        /// acSedeINPS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.Autocomplete acSedeINPS;
        
        /// <summary>
        /// txtNumeroINAIL control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.TextBox txtNumeroINAIL;
        
        /// <summary>
        /// acSedeINAIL control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.Autocomplete acSedeINAIL;
        
        /// <summary>
        /// Telefono control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.TextBox Telefono;
        
        /// <summary>
        /// TelefonoCellulare control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.TextBox TelefonoCellulare;
        
        /// <summary>
        /// Fax control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.TextBox Fax;
        
        /// <summary>
        /// email control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.TextBox email;
        
        /// <summary>
        /// emailPec control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.TextBox emailPec;
        
        /// <summary>
        /// acComuneCorrispondenza control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.Autocomplete acComuneCorrispondenza;
        
        /// <summary>
        /// IndirizzoCorrispondenza control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.TextBox IndirizzoCorrispondenza;
        
        /// <summary>
        /// CittaCorrispondenza control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.TextBox CittaCorrispondenza;
        
        /// <summary>
        /// CapCorrispondenza control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.TextBox CapCorrispondenza;
        
        /// <summary>
        /// cmdConfirm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button cmdConfirm;
        
        /// <summary>
        /// cmdCancel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton cmdCancel;
    }
}
