SET IMPLICIT_TRANSACTIONS ON
GO
ALTER TABLE INVENTARIOPROCEDIMENTIPEOPLE ADD CONSTRAINT INVENTARIOPROCEDIMENTIPEOPL_PK PRIMARY KEY(IDCOMUNE,ID)
GO
ALTER TABLE INVENTARIOPROCEDIMENTIPEOPLE DROP CONSTRAINT INVENTARIOPROCEDIMENTIPEOPL_PK
GO
COMMIT
ALTER TABLE AUTORIZZAZIONI_CONCESSIONI ADD CONSTRAINT FK_AUTCONC_MERCATI_D FOREIGN KEY(IDCOMUNE,FK_IDPOSTEGGIO) REFERENCES MERCATI_D(IDCOMUNE,IDPOSTEGGIO)
GO
COMMIT
ALTER TABLE MERCATI_D ADD CONSTRAINT FK_MERCATID_STRADARIO FOREIGN KEY(IDCOMUNE,FKCODICESTRADARIO) REFERENCES STRADARIO(IDCOMUNE,CODICESTRADARIO)
GO
COMMIT
ALTER TABLE MERCATI_D ADD CONSTRAINT FK_MERCATID_MERCATI FOREIGN KEY(IDCOMUNE,FKCODICEMERCATO) REFERENCES MERCATI(IDCOMUNE,CODICEMERCATO)
GO
COMMIT
ALTER TABLE MERCATI_DATTIVITAISTAT ADD CONSTRAINT FK_MERC_DATTIVIT_MERCATID FOREIGN KEY (IDCOMUNE, FKIDPOSTEGGIO) REFERENCES MERCATI_D (IDCOMUNE, IDPOSTEGGIO)
GO
COMMIT
GO
ALTER TABLE CONFIGURAZIONE ALTER COLUMN ORARIO VARCHAR(1000)
GO
COMMIT
GO
ALTER TABLE OGGETTI ALTER COLUMN NOMEFILE VARCHAR(216)
GO
COMMIT
GO
ALTER TABLE FO_VISURA_CAMPI DROP CONSTRAINT FO_VISURA_CAMPI__FK1
GO
COMMIT
GO
ALTER TABLE FO_VISURA_CAMPI DROP CONSTRAINT FO_VISURA_CAMPI__FK2
GO
COMMIT
GO
ALTER TABLE FO_VISURA_CAMPI ADD CONSTRAINT FK_FO_VIS_CAMPI_CONTESTI_BASE FOREIGN KEY (FKIDCONTESTO) REFERENCES FO_VISURA_CONTESTI_BASE (ID)
GO
COMMIT
GO
ALTER TABLE FO_VISURA_CAMPI ADD CONSTRAINT FK_FO_VIS_CAMPI_CAMPI_BASE FOREIGN KEY (FKIDCAMPO) REFERENCES FO_VISURA_CAMPI_BASE (ID)
GO
COMMIT
GO
ALTER TABLE FO_VISURA_CAMPI ADD CONSTRAINT FK_FO_VIS_CAMPI_SOFTWARE FOREIGN KEY (SOFTWARE) REFERENCES SOFTWARE (CODICE)
GO
COMMIT
GO
ALTER TABLE MAIL_CONFIG ALTER COLUMN LOGINNAME VARCHAR(320)
GO
COMMIT
GO
Drop View VW_I_ATTIVITALISTA
GO
COMMIT
GO
Create  View VW_I_ATTIVITALISTA as SELECT I_ATTIVITA.CODICEISTANZAULTIMA as I_CODICEISTANZAULTIMA,
I_ATTIVITA.ID as I_IDATTIVITA,
I_ATTIVITA.IDCOMUNE,
I_ATTIVITA.ATTIVA,
I_ATTIVITA.OPERANTE,
ISTANZE.SOFTWARE,
I_ATTIVITA.DENOMINAZIONE,
ISTANZE.NUMEROISTANZA,
ISTANZE.CODICERICHIEDENTE,
ISNULL(T_RICHIEDENTE.NOMINATIVO,
'') + ISNULL(' ',
'') + ISNULL(T_RICHIEDENTE.NOME,
'') as RICHIEDENTE,
RTrim(LTrim(ISNULL(T_RICHIEDENTE.CODICEFISCALE,
'')) + ISNULL(' ',
'') + ISNULL(T_RICHIEDENTE.PARTITAIVA,
'')) as CF_PIVA_RICHIEDENTE,
ISTANZE.FKCODICESOGGETTO,
TIPISOGGETTO.TIPOSOGGETTO,
ISTANZE.CODICECOMUNE,
ISTANZE.CODICETITOLARELEGALE,
RTrim(LTrim(ISNULL(T_AZIENDARICHIEDENTE.NOMINATIVO,
'')) + ISNULL(' ',
'') + ISNULL(T_AZIENDARICHIEDENTE.NOME,
'')) as AZIENDARICHIEDENTE,
RTrim(LTrim(ISNULL(T_AZIENDARICHIEDENTE.CODICEFISCALE,
'')) + ISNULL(' ',
'') + ISNULL(T_AZIENDARICHIEDENTE.PARTITAIVA,
'')) as CF_PIVA_AZIENDARICHIEDENTE,
ISTANZESTRADARIO.CODICESTRADARIO,
ISNULL(STRADARIO.PREFISSO,
'') + ISNULL(' ',
'') + ISNULL(STRADARIO.DESCRIZIONE,
'') + ISNULL(',',
'') + ISNULL(ISNULL(ISTANZESTRADARIO.CIVICO,''),
'') + ISNULL(ISNULL(ISTANZESTRADARIO.COLORE,''),
'') as LOCALIZZAZIONE,
ISTANZESTRADARIO.CIVICO FROM ISTANZE LEFT OUTER JOIN ANAGRAFE T_AZIENDARICHIEDENTE ON ISTANZE.IDCOMUNE=T_AZIENDARICHIEDENTE.IDCOMUNE  AND ISTANZE.CODICETITOLARELEGALE=T_AZIENDARICHIEDENTE.CODICEANAGRAFE  LEFT OUTER JOIN TIPISOGGETTO ON ISTANZE.IDCOMUNE=TIPISOGGETTO.IDCOMUNE  AND
 ISTANZE.FKCODICESOGGETTO=TIPISOGGETTO.CODICETIPOSOGGETTO
 LEFT OUTER JOIN ISTANZESTRADARIO ON ISTANZESTRADARIO.IDCOMUNE = ISTANZE.IDCOMUNE AND ISTANZESTRADARIO.CODICEISTANZA = ISTANZE.CODICEISTANZA AND ISTANZESTRADARIO.PRIMARIO = 1
 LEFT OUTER JOIN STRADARIO ON STRADARIO.IDCOMUNE = ISTANZESTRADARIO.IDCOMUNE AND STRADARIO.CODICESTRADARIO = ISTANZESTRADARIO.CODICESTRADARIO, 
I_ATTIVITA,
ANAGRAFE T_RICHIEDENTE
 WHERE ISTANZE.IDCOMUNE = I_ATTIVITA.IDCOMUNE AND ISTANZE.CODICEISTANZA = I_ATTIVITA.CODICEISTANZAULTIMA AND T_RICHIEDENTE.IDCOMUNE = ISTANZE.IDCOMUNE AND T_RICHIEDENTE.CODICEANAGRAFE = ISTANZE.CODICERICHIEDENTE 
GO
COMMIT
GO
ALTER TABLE DYN2_CAMPIPROPRIETA ALTER COLUMN VALORE VARCHAR(2000)
GO
COMMIT
GO
ALTER TABLE STP_ENDO_TIPO2 ADD CODICE_ENDO_REGIONALE VARCHAR(20)
GO
COMMIT
GO
ALTER TABLE STP_ENDO_TIPO2 ADD CODICE_TIPOLOGIA_ENDO NUMERIC(4,0)
GO
COMMIT
GO
DROP VIEW VW_SCADENZARIO
GO
COMMIT
GO
CREATE VIEW VW_SCADENZARIO as 
  SELECT VW_BATCH_SCADENZARIO.IDCOMUNE                      AS IDCOMUNE,
    VW_BATCH_SCADENZARIO.ID                                 AS CODICESCADENZA,
    VW_BATCH_SCADENZARIO.SOFTWARE                           AS software,
    VW_BATCH_SCADENZARIO.CODICEISTANZA                      AS codiceistanza,
    ISTANZE.NUMEROPROTOCOLLO                                AS numeroprotocollo,
    ISTANZE.DATAPROTOCOLLO                                  AS dataprotocollo,
    ISTANZE.NUMEROISTANZA                                   AS NUMEROISTANZA,
    ISTANZE.CHIUSURA                                        AS CODSTATOISTANZA,
    STATIISTANZA.STATO                                      AS DESCRSTATOISTANZA,
    VW_BATCH_SCADENZARIO.CODICEMOVIMENTO                    AS CODMOVIMENTO,
    VW_BATCH_SCADENZARIO.DESCRMOVIMENTO                     AS DESCRMOVIMENTO,
    CONVERT(VARCHAR,MOVIMENTI.DATA,103)                    AS DATAMOVIMENTO,
    VW_BATCH_SCADENZARIO.TIPOMOVIMENTODAFARE                AS CODMOVIMENTODAFARE,
    VW_BATCH_SCADENZARIO.DESCRMOVIMENTODAFARE               AS DESCRMOVIMENTODAFARE,
    CONVERT(VARCHAR,VW_BATCH_SCADENZARIO.DATASCADENZA,103) AS DATASCADENZASTR,
    VW_BATCH_SCADENZARIO.codiceinventario                   AS codiceinventario,
    VW_BATCH_SCADENZARIO.CODICEAMMINISTRAZIONE              AS CODICEAMMINISTRAZIONE,
    RESPONSABILI.RESPONSABILE                               AS RESPONSABILE,
    INVENTARIOPROCEDIMENTI.PROCEDIMENTO                     AS PROCEDIMENTO,
    TIPIPROCEDURE.PROCEDURA                                 AS PROCEDURA,
    SOFTWARE.DESCRIZIONE                                    AS MODULOSOFTWARE,
    AMMINISTRAZIONI.AMMINISTRAZIONE                         AS AMM_amministrazione,
    AMMINISTRAZIONI.PARTITAIVA                              AS AMM_PARTITAIVA,
    AMMINISTRAZIONI.PASSWORD                                AS AMM_PASSWORD,
    ANAGRAFE.NOMINATIVO + ' ' + ANAGRAFE.NOME AS RIC_NOMINATIVO,
    ISNULL(ANAGRAFE.CODICEFISCALE,'') AS RIC_CODICEFISCALE,
    ISNULL(ANAGRAFE.PARTITAIVA,'')    AS RIC_PARTITAIVA,
    ANAGRAFE.INDIRIZZO             AS RIC_INDIRIZZO,
    ANAGRAFE.CAP                   AS RIC_CAP,
    ANAGRAFE.CITTA                 AS RIC_LOCALITA,
    COMUNERESIDENZA.COMUNE         AS RIC_CITTA,
    COMUNERESIDENZA.PROVINCIA      AS RIC_PROVINCIA,
    ANAGRAFE.PASSWORD              AS RIC_PASSWORD,
    TECNICO.NOMINATIVO + ' ' + TECNICO.NOME AS TEC_NOMINATIVO,
    ISNULL(TECNICO.CODICEFISCALE,'') AS TEC_CODICEFISCALE,
    ISNULL(TECNICO.PARTITAIVA,'')    AS TEC_PARTITAIVA,
    TECNICO.PASSWORD              AS TEC_PASSWORD,
    AZIENDA.NOMINATIVO + ' ' + AZIENDA.NOME AS AZ_NOMINATIVO,
    ISNULL(AZIENDA.CODICEFISCALE,'') AS AZ_CODICEFISCALE,
    ISNULL(AZIENDA.PARTITAIVA,'')    AS AZ_PARTITAIVA,
    AZIENDA.PASSWORD              AS AZ_PASSWORD,
    TIPIMOVIMENTO.FK_FO_SOGGETTIESTERNI
  FROM VW_BATCH_SCADENZARIO
  JOIN ISTANZE ON ISTANZE.IDCOMUNE = VW_BATCH_SCADENZARIO.IDCOMUNE
  AND ISTANZE.CODICEISTANZA = VW_BATCH_SCADENZARIO.CODICEISTANZA
  JOIN RESPONSABILI ON RESPONSABILI.IDCOMUNE = ISTANZE.IDCOMUNE
  AND RESPONSABILI.CODICERESPONSABILE = ISTANZE.CODICERESPONSABILE
  JOIN MOVIMENTI ON MOVIMENTI.IDCOMUNE = VW_BATCH_SCADENZARIO.IDCOMUNE
  AND MOVIMENTI.CODICEMOVIMENTO = VW_BATCH_SCADENZARIO.CODICEMOVIMENTO
  JOIN TIPIMOVIMENTO ON TIPIMOVIMENTO.IDCOMUNE = VW_BATCH_SCADENZARIO.IDCOMUNE
  AND TIPIMOVIMENTO.TIPOMOVIMENTO  = VW_BATCH_SCADENZARIO.TIPOMOVIMENTODAFARE
  JOIN TIPIPROCEDURE ON TIPIPROCEDURE.IDCOMUNE = ISTANZE.IDCOMUNE
  AND TIPIPROCEDURE.CODICEPROCEDURA = ISTANZE.CODICEPROCEDURA
  JOIN SOFTWARE ON SOFTWARE.CODICE = VW_BATCH_SCADENZARIO.SOFTWARE
  JOIN ANAGRAFE ON ANAGRAFE.IDCOMUNE = ISTANZE.IDCOMUNE
  AND ANAGRAFE.CODICEANAGRAFE = ISTANZE.CODICERICHIEDENTE
  JOIN STATIISTANZA ON STATIISTANZA.IDCOMUNE = ISTANZE.IDCOMUNE
  AND STATIISTANZA.SOFTWARE = ISTANZE.SOFTWARE
  AND STATIISTANZA.CODICESTATO = ISTANZE.CHIUSURA
  LEFT OUTER JOIN AMMINISTRAZIONI ON AMMINISTRAZIONI.IDCOMUNE = VW_BATCH_SCADENZARIO.IDCOMUNE
  AND AMMINISTRAZIONI.CODICEAMMINISTRAZIONE = VW_BATCH_SCADENZARIO.CODICEAMMINISTRAZIONE
  LEFT OUTER JOIN INVENTARIOPROCEDIMENTI ON INVENTARIOPROCEDIMENTI.IDCOMUNE = VW_BATCH_SCADENZARIO.IDCOMUNE
  AND INVENTARIOPROCEDIMENTI.CODICEINVENTARIO = VW_BATCH_SCADENZARIO.CODICEINVENTARIO
  LEFT OUTER JOIN COMUNI COMUNERESIDENZA ON COMUNERESIDENZA.CODICECOMUNE = ANAGRAFE.COMUNERESIDENZA
  LEFT OUTER JOIN ANAGRAFE TECNICO ON TECNICO.IDCOMUNE = ISTANZE.IDCOMUNE
  AND TECNICO.CODICEANAGRAFE = ISTANZE.CODICEPROFESSIONISTA
  LEFT OUTER JOIN ANAGRAFE AZIENDA ON AZIENDA.IDCOMUNE = ISTANZE.IDCOMUNE
  AND AZIENDA.CODICEANAGRAFE = ISTANZE.CODICETITOLARELEGALE
GO
COMMIT
GO
ALTER TABLE TIPIMOV_STC_MAPPING ADD FLAG_CREAINVIA_ALLEGATI NUMERIC(1,0)
GO
COMMIT
GO
ALTER TABLE TIPIMOV_STC_MAPPING ADD FLAG_ALLEGA_DOCUMENTI_ISTANZA NUMERIC(1,0)
GO
COMMIT
GO
ALTER TABLE TIPIMOV_STC_MAPPING ADD FLAG_PROTOCOLLA NUMERIC(1,0)
GO
COMMIT
GO
ALTER TABLE TIPIMOV_STC_MAPPING ADD PROTOCOLLO_FLUSSO VARCHAR(1)
GO
COMMIT
GO
ALTER TABLE TIPIMOV_STC_MAPPING ADD PROTOCOLLO_TIPODOCUMENTO VARCHAR(10)
GO
COMMIT
GO
ALTER TABLE TIPIMOV_STC_MAPPING ADD PROTOCOLLO_OGGETTO NUMERIC(4,0)
GO
COMMIT
GO
ALTER TABLE TIPIMOV_STC_MAPPING ADD PROTOCOLLO_MITTENTE NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE TIPIMOV_STC_MAPPING ADD FLAG_NOTIFICA_AUTOMATICA NUMERIC(1,0)
GO
COMMIT
GO
ALTER TABLE TIPIMOV_STC_MAPPING ADD CONSTRAINT FK_TIPIMOV_STC_MAP_TIPI_DOC FOREIGN KEY (IDCOMUNE,PROTOCOLLO_TIPODOCUMENTO) REFERENCES PROTOCOLLO_TIPIDOCUMENTO(IDCOMUNE,CODICE)
GO
COMMIT
GO
ALTER TABLE TIPIMOV_STC_MAPPING ADD CONSTRAINT FK_TIPIMOV_STC_MAP_PROT_FL FOREIGN KEY (PROTOCOLLO_FLUSSO ) REFERENCES PROTOCOLLO_FLUSSO(CODICE )
GO
COMMIT
GO
ALTER TABLE TIPIMOV_STC_MAPPING ADD CONSTRAINT FK_TIPIMOV_STC_MAP_AMMIN FOREIGN KEY (IDCOMUNE,PROTOCOLLO_MITTENTE) REFERENCES AMMINISTRAZIONI(IDCOMUNE,CODICEAMMINISTRAZIONE)
GO
COMMIT
GO
ALTER TABLE TIPIMOV_STC_MAPPING ADD CONSTRAINT FK_TIPIMOV_STC_MAP_MAIL_TIPO FOREIGN KEY (IDCOMUNE,PROTOCOLLO_OGGETTO) REFERENCES MAILTIPO(IDCOMUNE,CODICEMAIL)
GO
COMMIT
GO
CREATE TABLE ALBEROPROC_ARENDO ( IDCOMUNE VARCHAR(6) NOT NULL , ID NUMERIC(10, 0) NOT NULL , FK_SCID NUMERIC(10, 0) NOT NULL , FK_FAMIGLIAENDO NUMERIC(10, 0) NOT NULL , FK_CATEGORIAENDO NUMERIC(10, 0) , CONSTRAINT ALBEROPROC_ARENDO_PK PRIMARY KEY ( IDCOMUNE , ID ) )
GO
COMMIT
GO
ALTER TABLE ALBEROPROC_ARENDO ADD CONSTRAINT ALBEROPROC_ARENDO_ALBEROP_FK1 FOREIGN KEY ( IDCOMUNE , FK_SCID ) REFERENCES ALBEROPROC ( IDCOMUNE , SC_ID )
GO
COMMIT
GO
ALTER TABLE ALBEROPROC_ARENDO ADD CONSTRAINT ALBEROPROC_ARENDO_TIPIFAM_FK1 FOREIGN KEY ( IDCOMUNE , FK_FAMIGLIAENDO ) REFERENCES TIPIFAMIGLIEENDO ( IDCOMUNE , CODICE )
GO
COMMIT
GO
ALTER TABLE ALBEROPROC_ARENDO ADD CONSTRAINT ALBEROPROC_ARENDO_TIPIEND_FK1 FOREIGN KEY ( IDCOMUNE , FK_CATEGORIAENDO ) REFERENCES TIPIENDO ( IDCOMUNE , CODICE )
GO
COMMIT
GO
CREATE INDEX IDX_MOVIMENTI_006 ON MOVIMENTI (IDCOMUNE, TIPOMOVIMENTO)
GO
COMMIT
GO
CREATE INDEX IDX_COMUNI_PROVINCE002 ON COMUNI (SIGLAPROVINCIA, PROVINCIA)
GO
COMMIT
GO
ALTER TABLE MOVIMENTIALLEGATI ALTER COLUMN DESCRIZIONE VARCHAR(4000)
GO
COMMIT
GO
ALTER TABLE ISTANZEALLEGATI ALTER COLUMN ALLEGATOEXTRA VARCHAR(4000)
GO
COMMIT
GO
ALTER TABLE CLMENU_JAVA ADD LINK_STANDARD VARCHAR(150)
GO
COMMIT
GO
ALTER TABLE CONFIGURAZIONE ADD CONSTRAINT FK_MAIL_AMMENDO_MAILTIPO FOREIGN KEY (IDCOMUNE,MAIL_AMMENDO) REFERENCES MAILTIPO(IDCOMUNE,CODICEMAIL)
GO
COMMIT
GO
ALTER TABLE CONFIGURAZIONE ADD CONSTRAINT FK_MAIL_MOVRIC_MAILTIPO FOREIGN KEY (IDCOMUNE,MAIL_MOVIRIC) REFERENCES MAILTIPO(IDCOMUNE,CODICEMAIL)
GO
COMMIT
GO
ALTER TABLE CONFIGURAZIONE ADD CONSTRAINT FK_MAIL_MOVAMM_MAILTIPO FOREIGN KEY (IDCOMUNE,MAIL_MOVIAMM) REFERENCES MAILTIPO(IDCOMUNE,CODICEMAIL)
GO
COMMIT
GO
ALTER TABLE CONFIGURAZIONE ADD CONSTRAINT FK_MAIL_MOVNEG_MAILTIPO FOREIGN KEY (IDCOMUNE,MAIL_MOVINEG) REFERENCES MAILTIPO(IDCOMUNE,CODICEMAIL)
GO
COMMIT
GO
CREATE INDEX IDX_ANAGRAFE_006 ON ANAGRAFE (IDCOMUNE, NOMINATIVO, NOME)
GO
COMMIT
GO
ALTER TABLE MOVIMENTI ADD CODICEAMMINISTRAZIONE_STC NUMERIC(10,0)
GO
COMMIT
GO
 ALTER TABLE MOVIMENTI ADD CONSTRAINT FK_MOVIMENTI_AMM_STC FOREIGN KEY (IDCOMUNE, CODICEAMMINISTRAZIONE_STC) REFERENCES AMMINISTRAZIONI (IDCOMUNE, CODICEAMMINISTRAZIONE)
GO
COMMIT
GO
CREATE UNIQUE INDEX IDX_ALBEROPROC_ARENDO_001 ON ALBEROPROC_ARENDO(IDCOMUNE, FK_SCID, FK_FAMIGLIAENDO, FK_CATEGORIAENDO)
GO
COMMIT
GO
CREATE VIEW VW_ISTANZE_OPE_RUOLI AS SELECT RR.IDCOMUNE, RR.IDRUOLO, RR.CODICERESPONSABILE, IR.CODICEISTANZA FROM RESPONSABILIRUOLI RR INNER JOIN  ISTANZERUOLI IR ON RR.IDCOMUNE=IR.IDCOMUNE AND  RR.IDRUOLO = IR.IDRUOLO
GO
COMMIT
GO
-- ALTER TABLE ALBEROPROC_DYN2MODELLIT ADD FLAG_FACOLTATIVA NUMERIC(1, 0)  
-- GO
-- COMMIT
-- GO
-- ALTER TABLE INVENTARIOPROCDYN2MODELLIT ADD FLAG_FACOLTATIVA NUMERIC(1, 0)
-- GO
-- COMMIT
-- GO