<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0;net48</TargetFrameworks>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<Configurations>Debug;Release</Configurations>
		<Platforms>AnyCPU</Platforms>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="log4net" Version="3.3.2" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.10" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.10" />
		<PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="18.7.23">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Frontoffice\Init.Sigepro.FrontEnd.Infrastructure\Init.Sigepro.FrontEnd.Infrastructure.csproj" />
	</ItemGroup>

</Project>
