<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <PackageId>SIGePro.Data</PackageId>
    <Configurations>Debug;Release</Configurations>
    <Platforms>AnyCPU</Platforms>
	  <LangVersion>9.0</LangVersion>
	  <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="log4net" Version="3.3.2" />
    <PackageReference Include="VBG.DatiDinamici.Standard" Version="10.1.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Init.Utils\Init.Utils.csproj" />
    <ProjectReference Include="..\PersonalLib2\PersonalLib2.csproj" />
  </ItemGroup>


</Project>