SET IMPLICIT_TRANSACTIONS ON
GO
ALTER TABLE TIPIMOVIMENTO ADD FKSTATOISTANZA VARCHAR(2)
GO
COMMIT
GO
ALTER TABLE TIPIMOVIMENTO ADD CONSTRAINT FK_TIPIMOV_STATIISTANZA FOREIGN KEY (IDCOMUNE,SOFTWARE,FKSTATOISTANZA) REFERENCES STATIISTANZA(IDCOMUNE,SOFTWARE,CODICESTATO)
GO
COMMIT
GO
CREATE TABLE ISTANZEPROCURE (ID NUMERIC(10,0) NOT NULL,IDCOMUNE VARCHAR(6) NOT NULL,CODICEISTANZA NUMERIC(6,0),FK_ANAG_PROC NUMERIC(6,0),FK_ANAG_PROC_STORICO NUMERIC(6,0),FK_ANAG_RAPP NUMERIC(6,0),FK_ANAG_RAPP_STORICO NUMERIC(6,0),CODICEOGGETTOPROCURA NUMERIC(10,0),STC_ID_ALLEGATO VARCHAR(200),STC_ID_DOCUMENTO VARCHAR(200))
GO
COMMIT
GO
ALTER TABLE ISTANZEPROCURE ADD CONSTRAINT PK_ISTANZEPROCURE PRIMARY KEY (IDCOMUNE, ID)
GO
COMMIT
GO
ALTER TABLE ISTANZEPROCURE ADD CONSTRAINT FK_ISTPROC_ISTANZE FOREIGN KEY (IDCOMUNE, CODICEISTANZA) REFERENCES ISTANZE(IDCOMUNE, CODICEISTANZA)
GO
COMMIT
GO
ALTER TABLE ISTANZEPROCURE ADD CONSTRAINT FK_ISTPROC_ANPROC FOREIGN KEY (IDCOMUNE, FK_ANAG_PROC) REFERENCES ANAGRAFE(IDCOMUNE, CODICEANAGRAFE)
GO
COMMIT
GO
ALTER TABLE ISTANZEPROCURE ADD CONSTRAINT FK_ISTPROC_ANPROCST FOREIGN KEY (IDCOMUNE, FK_ANAG_PROC_STORICO) REFERENCES ANAGRAFESTORICO(IDCOMUNE, ID)
GO
COMMIT
GO
ALTER TABLE ISTANZEPROCURE ADD CONSTRAINT FK_ISTPROC_ANRAP FOREIGN KEY (IDCOMUNE, FK_ANAG_RAPP) REFERENCES ANAGRAFE(IDCOMUNE, CODICEANAGRAFE)
GO
COMMIT
GO
ALTER TABLE ISTANZEPROCURE ADD CONSTRAINT FK_ISTPROC_ANRAPST FOREIGN KEY (IDCOMUNE, FK_ANAG_RAPP_STORICO) REFERENCES ANAGRAFESTORICO(IDCOMUNE, ID)
GO
COMMIT
GO
ALTER TABLE ISTANZEPROCURE ADD CONSTRAINT FK_ISTPROC_OGGETTI FOREIGN KEY (IDCOMUNE, CODICEOGGETTOPROCURA) REFERENCES OGGETTI(IDCOMUNE, CODICEOGGETTO)
GO
COMMIT
GO
DROP VIEW VW_ISTANZE_OPE_RUOLI;
GO
COMMIT
GO
CREATE VIEW VW_ISTANZE_OPE_RUOLI (IDCOMUNE, IDRUOLO, CODICERESPONSABILE, CODICEISTANZA) AS SELECT RR.IDCOMUNE,RR.IDRUOLO,RR.CODICERESPONSABILE,IR.CODICEISTANZA FROM RESPONSABILIRUOLI RR INNER JOIN ISTANZERUOLI IR on rr.idcomune =ir.idcomune and rr.idruolo = ir.idruolo inner join ruoli r ON r.idcomune=ir.idcomune and r.id =ir.idruolo AND (r.readonly=0 OR (r.flag_gestmovimenti=1 OR r.flag_disgestmovamm =1))
GO
COMMIT
GO
ALTER TABLE INVENTARIOPROCEDIMENTIONERI ADD NOTE VARCHAR(500)
GO
COMMIT
GO
ALTER TABLE ALBEROPROC_ONERI ADD NOTE VARCHAR(500)
GO
COMMIT
GO
CREATE TABLE RESPONSABILI_TM_SCA (IDCOMUNE VARCHAR(6) NOT NULL,CODICERESPONSABILE NUMERIC(4,0) NOT NULL,TIPOMOVIMENTO VARCHAR(8) NOT NULL)
GO
COMMIT
GO
ALTER TABLE RESPONSABILI_TM_SCA ADD CONSTRAINT PK_RESP_TM_SCA PRIMARY KEY (IDCOMUNE,CODICERESPONSABILE,TIPOMOVIMENTO)
GO
COMMIT
GO
ALTER TABLE RESPONSABILI_TM_SCA ADD CONSTRAINT FK_RESPTMSCA_RESP FOREIGN KEY(IDCOMUNE,CODICERESPONSABILE) REFERENCES RESPONSABILI(IDCOMUNE,CODICERESPONSABILE)
GO
COMMIT
GO
ALTER TABLE RESPONSABILI_TM_SCA ADD CONSTRAINT FK_RESPTMSCA_TIPIMOV FOREIGN KEY(IDCOMUNE,TIPOMOVIMENTO) REFERENCES TIPIMOVIMENTO(IDCOMUNE,TIPOMOVIMENTO)
GO
COMMIT
GO
CREATE TABLE RESPONSABILI_TM_AVV (IDCOMUNE VARCHAR(6) NOT NULL,CODICERESPONSABILE NUMERIC(4,0) NOT NULL,TIPOMOVIMENTO VARCHAR(8) NOT NULL)
GO
COMMIT
GO
ALTER TABLE RESPONSABILI_TM_AVV  ADD CONSTRAINT PK_RESP_TM_AVV PRIMARY KEY (IDCOMUNE,CODICERESPONSABILE,TIPOMOVIMENTO)
GO
COMMIT
GO
ALTER TABLE RESPONSABILI_TM_AVV ADD CONSTRAINT FK_RESPTMAVV_RESP FOREIGN KEY(IDCOMUNE,CODICERESPONSABILE) REFERENCES RESPONSABILI(IDCOMUNE,CODICERESPONSABILE)
GO
COMMIT
GO
ALTER TABLE RESPONSABILI_TM_AVV ADD CONSTRAINT FK_RESPTMAVV_TIPIMOV FOREIGN KEY(IDCOMUNE,TIPOMOVIMENTO) REFERENCES TIPIMOVIMENTO(IDCOMUNE,TIPOMOVIMENTO)
GO
COMMIT
GO
ALTER TABLE TIPIMOVIMENTO ADD FLAG_DISDAVISIONARE NUMERIC(1,0)
GO
COMMIT
GO
DROP VIEW VW_I_ATTIVITAINFORMAZIONI
GO
COMMIT
GO
CREATE VIEW VW_I_ATTIVITAINFORMAZIONI AS SELECT I_ATTIVITA.ID as I_IDATTIVITA, ISTANZEATTIVITA.CODICEISTANZA, ISTANZEATTIVITA.CODICEATTIVITA, ISTANZEATTIVITA.METRIQ, ISTANZEATTIVITA.NOTE, ISTANZEATTIVITA.IDCOMUNE, ISTANZEATTIVITA.SOFTWARE, ISTANZEATTIVITA.IDATTIVITA, SETTORI.CODICESETTORE, SETTORI.SETTORE FROM I_ATTIVITA, ISTANZEATTIVITA, ATTIVITA, SETTORI WHERE SETTORI.IDCOMUNE = ATTIVITA.IDCOMUNE AND SETTORI.CODICESETTORE = ATTIVITA.CODICESETTORE AND ATTIVITA.IDCOMUNE = ISTANZEATTIVITA.IDCOMUNE AND ATTIVITA.CODICEISTAT = ISTANZEATTIVITA.CODICEATTIVITA AND ISTANZEATTIVITA.IDCOMUNE = I_ATTIVITA.IDCOMUNE AND ISTANZEATTIVITA.CODICEISTANZA = I_ATTIVITA.CODICEISTANZAULTIMA
GO
COMMIT
GO
ALTER table ISTANZE ADD CONSTRAINT FK_ISTANZE_ATTIVITA FOREIGN KEY (IDCOMUNE,FK_IDI_ATTIVITA) REFERENCES I_ATTIVITA (IDCOMUNE, ID)
GO
COMMIT
GO
ALTER TABLE STATIISTANZA ADD CONSTRAINT FK_STATI_COMPORTAMENTO FOREIGN KEY (FKCODCOMPORTAMENTO) REFERENCES STATICOMPORTAMENTO (CODCOMPORTAMENTO)
GO
COMMIT
GO
CREATE INDEX IDX_STATIISTANZA_001 ON STATIISTANZA (FKCODCOMPORTAMENTO)
GO
COMMIT
GO
ALTER TABLE ISTANZE MODIFY NUMEROISTANZA VARCHAR(60)
GO
COMMIT
GO
ALTER TABLE DOMANDESTC MODIFY NUMEROISTANZA VARCHAR(60)
GO
COMMIT
GO
ALTER TABLE DOMANDESTC MODIFY ID_DOMANDAMITT VARCHAR(60)
GO
COMMIT
GO
ALTER TABLE ISTANZE ADD DOMICILIO_ELETTRONICO VARCHAR(320)
GO
COMMIT
GO
CREATE  VIEW VW_I_ATTIVITAENDO as SELECT I_ATTIVITA.IDCOMUNE, I_ATTIVITA.ID AS I_IDATTIVITA, ISTANZEPROCEDIMENTI.CODICEISTANZA, TIPIFAMIGLIEENDO.CODICE AS CODICEFAMIGLIA, TIPIFAMIGLIEENDO.TIPO AS FAMIGLIA, TIPIENDO.CODICE AS CODICETIPO, TIPIENDO.TIPO, ISTANZEPROCEDIMENTI.CODICEINVENTARIO, INVENTARIOPROCEDIMENTI.PROCEDIMENTO, ISTANZEPROCEDIMENTI.PERPROVVEDIMENTO, ISTANZEPROCEDIMENTI.ACQUISITO, ISTANZEPROCEDIMENTI.DATAATTIVAZIONE, ISTANZEPROCEDIMENTI.NOTE FROM I_ATTIVITA, ISTANZE, ISTANZEPROCEDIMENTI, ((INVENTARIOPROCEDIMENTI LEFT OUTER JOIN TIPIENDO ON INVENTARIOPROCEDIMENTI.IDCOMUNE = TIPIENDO.IDCOMUNE AND INVENTARIOPROCEDIMENTI.CODICETIPO = TIPIENDO.CODICE ) LEFT OUTER JOIN TIPIFAMIGLIEENDO ON TIPIENDO.IDCOMUNE = TIPIFAMIGLIEENDO.IDCOMUNE AND TIPIENDO.CODICEFAMIGLIAENDO = TIPIFAMIGLIEENDO.CODICE ) WHERE INVENTARIOPROCEDIMENTI.IDCOMUNE = ISTANZEPROCEDIMENTI.IDCOMUNE AND INVENTARIOPROCEDIMENTI.CODICEINVENTARIO = ISTANZEPROCEDIMENTI.CODICEINVENTARIO AND ISTANZEPROCEDIMENTI.IDCOMUNE = ISTANZE.IDCOMUNE AND ISTANZEPROCEDIMENTI.CODICEISTANZA = ISTANZE.CODICEISTANZA AND ISTANZE.IDCOMUNE = I_ATTIVITA.IDCOMUNE AND ISTANZE.FK_IDI_ATTIVITA = I_ATTIVITA.ID  WITH CHECK OPTION
GO
COMMIT
GO
ALTER TABLE RESPONSABILI ADD FLAG_CANCELLAISTANZE NUMERIC(1,0)
GO
COMMIT
GO
ALTER TABLE RESPONSABILI ADD FLAG_CANCELLADOCUMENTISTC NUMERIC(1,0)
GO
COMMIT
GO
ALTER TABLE TIPIMOV_STC_MAPPING ADD FLAG_INVIASCHEDEISTANZA NUMERIC(1,0)
GO
COMMIT
GO
CREATE VIEW VW_ISTANZECONCESSIONIPREC_TMP AS SELECT IDCOMUNE, CONC_ID, MAX(DATA_STORICO) AS DATA_STORICO FROM VW_ISTANZECONCESSIONILISTA WHERE PROGRESSIVO < 99999999 GROUP BY IDCOMUNE, CONC_ID
GO
COMMIT
GO
CREATE VIEW VW_ISTANZECONCESSIONIPREC AS 
SELECT  
  VW_ISTANZECONCESSIONILISTA.IDCOMUNE, VW_ISTANZECONCESSIONILISTA.CONC_ID, VW_ISTANZECONCESSIONILISTA.DATA_STORICO, MAX(PROGRESSIVO) AS PROGRESSIVO 
FROM  
  VW_ISTANZECONCESSIONILISTA, VW_ISTANZECONCESSIONIPREC_TMP 
WHERE  
 VW_ISTANZECONCESSIONILISTA.IDCOMUNE = VW_ISTANZECONCESSIONIPREC_TMP.IDCOMUNE AND 
 VW_ISTANZECONCESSIONILISTA.CONC_ID = VW_ISTANZECONCESSIONIPREC_TMP.CONC_ID AND 
 VW_ISTANZECONCESSIONILISTA.DATA_STORICO = VW_ISTANZECONCESSIONIPREC_TMP.DATA_STORICO AND 
 VW_ISTANZECONCESSIONILISTA.PROGRESSIVO < 99999999
GROUP BY VW_ISTANZECONCESSIONILISTA.IDCOMUNE, VW_ISTANZECONCESSIONILISTA.CONC_ID, VW_ISTANZECONCESSIONILISTA.DATA_STORICO
GO
COMMIT
GO
CREATE VIEW VW_ISTANZECONCESSIONILISTA as SELECT 99999999 as PROGRESSIVO,AUTORIZZAZIONI.AUTORIZRESPONSABILE as CONC_AUTORIZRESPONSABILE,AUTORIZZAZIONI.IDCOMUNE,AUTORIZZAZIONI.FK_CAUSALE_ACQUISIZIONE as ICONC_CODICECAUSALE, isnull(AUTORIZZAZIONI.DATA_CESSAZIONE,CONVERT(DATETIME,'31/12/9999',103)) as DATA_STORICO, ISTANZE.SOFTWARE,ISTANZE.CODICEISTANZA as IST_CODICEISTANZA,ISTANZE.NUMEROISTANZA as IST_NUMEROISTANZA,ISTANZE.CODICERICHIEDENTE as IST_CODICERICHIEDENTE,ISTANZE.CODICETITOLARELEGALE AS IST_CODICETITOLARELEGALE,AUTORIZZAZIONI.ID as CONC_ID,AUTORIZZAZIONI.AUTORIZNUMERO as CONC_NUMERO,AUTORIZZAZIONI.AUTORIZDATA as CONC_DATARILASCIO,AUTORIZZAZIONI.AUTORIZDATA as DATARILASCIO,AUTORIZZAZIONI.DATASCADENZA as CONC_DATASCADENZA,AUTORIZZAZIONI_CONCESSIONI.FK_TIPOCONCESSIONE as CONC_CODICETIPO,CONCESSIONITIPI.DESCRIZIONE as CONC_TIPO,AUTORIZZAZIONI_CONCESSIONI.STAGIONALEA as CONC_STAGIONALEA,AUTORIZZAZIONI_CONCESSIONI.STAGIONALEDA as CONC_STAGIONALEDA,AUTORIZZAZIONI.FLAG_ATTIVA as CONC_ATTIVA,AUTORIZZAZIONI.FK_CODICEANAGRAFE as CONC_CODICETITOLARE,''+TITOLARE.NOMINATIVO+' '+TITOLARE.NOME as CONC_TITOLARE,TITOLARE.CODICEFISCALE as CONC_TIT_CF,TITOLARE.PARTITAIVA as CONC_TIT_PIVA,TITOLARE.TIPOANAGRAFE as CONC_TIT_TIPOANAGRAFE,AUT_COLLEGATA.AUTORIZNUMERO as AUT_NUMERO,AUT_COLLEGATA.AUTORIZDATA as AUT_DATA,AUT_COLLEGATA.AUTORIZDATA,AUT_COLLEGATA.FKIDREGISTRO as AUT_CODREGISTRO,TIPOLOGIAREGISTRI.TR_DESCRIZIONE as AUT_REGISTRO,(''+IST_RICHIEDENTE.NOMINATIVO+' '+IST_RICHIEDENTE.NOME) as IST_NOMINATIVO,IST_RICHIEDENTE.TIPOANAGRAFE as IST_RIC_TIPOANAGRAFE,(''+IST_AZIENDA.NOMINATIVO+' '+IST_AZIENDA.NOME) asIST_NOMINATIVOAZIENDA,IST_AZIENDA.TIPOANAGRAFE as IST_AZI_TIPOANAGRAFE, IST_AZIENDA.CODICEFISCALE AS IST_AZI_CODICEFISCALE, IST_AZIENDA.PARTITAIVA AS IST_AZI_PARTITAIVA,IST_RICHIEDENTE.CODICEFISCALE as IST_CODICEFISCALE,IST_RICHIEDENTE.PARTITAIVA as IST_PARTITAIVA,CAUS_ATTUALE.DESCRIZIONE as ICONC_CAUSALE,AUTORIZZAZIONI.FK_CAUSALE_CESSAZIONE as ICONC_CODICECAUSALESTORICO,CAUS_STORICO.DESCRIZIONE as ICONC_CAUSALESTORICO,AUTORIZZAZIONI_CONCESSIONI.FK_CODICEMERCATO as CONC_IDMERCATO,MERCATI.DESCRIZIONE as CONC_MERCATO,MERCATI.ATTIVO as MERC_ATTIVO,AUTORIZZAZIONI_CONCESSIONI.FK_IDPOSTEGGIO as CONC_IDPOSTEGGIO,MERCATI_D.CODICEPOSTEGGIO as CONC_POSTEGGIO,MERCATI_D.LARGHEZZA as CONC_POS_LARGHEZZA,MERCATI_D.LUNGHEZZA as CONC_POS_LUNGHEZZA,MERCATI_D.SUPERFICIE as CONC_POS_SUPERFICIE,MERCATI_D.FKCODICETIPOSPAZIO as POST_IDTIPOSPAZIO,POSTEGGITIPOSPAZIO.TIPOSPAZIO as POST_TIPOSPAZIO,AUTORIZZAZIONI_CONCESSIONI.FK_IDMERCATIUSO as CONC_IDMERCATIUSO,MERCATI_USO.DESCRIZIONE as CONC_DESCRIZIONEUSO,MERCATI_USO.PESO as PESO_MERCATO,MERCATI_USO.FKCODICEUSO as MERC_IDUSO,MERCATI_D.FKCODICESTRADARIO as CONC_POS_CODICESTRADARIO FROM AUTORIZZAZIONI_CONCESSIONI LEFT OUTER JOIN AUTORIZZAZIONI AUT_COLLEGATA ON AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE=AUT_COLLEGATA.IDCOMUNE  AND AUTORIZZAZIONI_CONCESSIONI.FK_IDAUT_COLLEGATA=AUT_COLLEGATA.ID,AUTORIZZAZIONI LEFT OUTER JOIN TIPOLOGIAREGISTRI ON AUTORIZZAZIONI.IDCOMUNE=TIPOLOGIAREGISTRI.IDCOMUNE  AND AUTORIZZAZIONI.FKIDREGISTRO=TIPOLOGIAREGISTRI.TR_ID  LEFT OUTER JOIN CONCESSIONICAUSALI CAUS_STORICO ON AUTORIZZAZIONI.IDCOMUNE=CAUS_STORICO.IDCOMUNE  AND AUTORIZZAZIONI.FK_CAUSALE_CESSAZIONE=CAUS_STORICO.CODICECAUSALE,MERCATI_D LEFT OUTER JOIN POSTEGGITIPOSPAZIO ON MERCATI_D.IDCOMUNE=POSTEGGITIPOSPAZIO.IDCOMUNE  AND   MERCATI_D.FKCODICETIPOSPAZIO=POSTEGGITIPOSPAZIO.CODICE,ISTANZE LEFT OUTER JOIN ANAGRAFE IST_AZIENDA ON ISTANZE.IDCOMUNE=IST_AZIENDA.IDCOMUNE  AND ISTANZE.CODICETITOLARELEGALE=IST_AZIENDA.CODICEANAGRAFE,CONCESSIONITIPI,ANAGRAFE TITOLARE,CONCESSIONICAUSALI CAUS_ATTUALE,ANAGRAFE   IST_RICHIEDENTE,MERCATI,MERCATI_USO WHERE AUTORIZZAZIONI.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND AUTORIZZAZIONI.ID = AUTORIZZAZIONI_CONCESSIONI.FK_IDAUT_ATTUALE AND CONCESSIONITIPI.TIPOCONCESSIONE = AUTORIZZAZIONI_CONCESSIONI.FK_TIPOCONCESSIONE AND TITOLARE.IDCOMUNE =  AUTORIZZAZIONI.IDCOMUNE AND TITOLARE.CODICEANAGRAFE = AUTORIZZAZIONI.FK_CODICEANAGRAFE AND CAUS_ATTUALE.IDCOMUNE = AUTORIZZAZIONI.IDCOMUNE AND CAUS_ATTUALE.CODICECAUSALE = AUTORIZZAZIONI.FK_CAUSALE_ACQUISIZIONE AND ISTANZE.IDCOMUNE = AUTORIZZAZIONI.IDCOMUNE AND ISTANZE.CODICEISTANZA = AUTORIZZAZIONI.FKIDISTANZA AND IST_RICHIEDENTE.IDCOMUNE = ISTANZE.IDCOMUNE AND IST_RICHIEDENTE.CODICEANAGRAFE = ISTANZE.CODICERICHIEDENTE AND MERCATI.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND MERCATI.CODICEMERCATO = AUTORIZZAZIONI_CONCESSIONI.FK_CODICEMERCATO AND MERCATI_D.IDCOMUNE =   AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND MERCATI_D.IDPOSTEGGIO = AUTORIZZAZIONI_CONCESSIONI.FK_IDPOSTEGGIO AND MERCATI_USO.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND MERCATI_USO.ID =   AUTORIZZAZIONI_CONCESSIONI.FK_IDMERCATIUSO UNION SELECT AUTORIZZAZIONI_SUBENTRI.ID as PROGRESSIVO,AUTORIZZAZIONI_SUBENTRI.AUTORIZRESPONSABILE as CONC_AUTORIZRESPONSABILE,AUTORIZZAZIONI_SUBENTRI.IDCOMUNE,AUTORIZZAZIONI_SUBENTRI.FK_CAUSALE_ACQUISIZIONE as ICONC_CODICECAUSALE,AUTORIZZAZIONI_SUBENTRI.DATA_CESSAZIONE as DATA_STORICO,ISTANZE.SOFTWARE,ISTANZE.CODICEISTANZA as   IST_CODICEISTANZA,ISTANZE.NUMEROISTANZA as IST_NUMEROISTANZA,ISTANZE.CODICERICHIEDENTE as IST_CODICERICHIEDENTE,ISTANZE.CODICETITOLARELEGALE AS IST_CODICETITOLARELEGALE,AUTORIZZAZIONI_SUBENTRI.FK_IDAUT_ATTUALE as CONC_ID,AUTORIZZAZIONI_SUBENTRI.AUTORIZNUMERO as CONC_NUMERO,AUTORIZZAZIONI_SUBENTRI.AUTORIZDATA as   CONC_DATARILASCIO,AUTORIZZAZIONI_SUBENTRI.AUTORIZDATA as DATARILASCIO,AUTORIZZAZIONI_SUBENTRI.DATASCADENZA as CONC_DATASCADENZA,AUTORIZZAZIONI_CONCESSIONI.FK_TIPOCONCESSIONE as CONC_CODICETIPO,CONCESSIONITIPI.DESCRIZIONE as CONC_TIPO,AUTORIZZAZIONI_CONCESSIONI.STAGIONALEA as   CONC_STAGIONALEA,AUTORIZZAZIONI_CONCESSIONI.STAGIONALEDA as CONC_STAGIONALEDA,0 as CONC_ATTIVA,AUTORIZZAZIONI_SUBENTRI.FK_CODICEANAGRAFE as CONC_CODICETITOLARE,(''+TITOLARE.NOMINATIVO+' '+TITOLARE.NOME) as   CONC_TITOLARE,TITOLARE.CODICEFISCALE as CONC_TIT_CF,TITOLARE.PARTITAIVA as CONC_TIT_PIVA,TITOLARE.TIPOANAGRAFE as CONC_TIT_TIPOANAGRAFE,AUT_COLLEGATA.AUTORIZNUMERO as AUT_NUMERO,AUT_COLLEGATA.AUTORIZDATA as AUT_DATA,AUT_COLLEGATA.AUTORIZDATA,AUT_COLLEGATA.FKIDREGISTRO as AUT_CODREGISTRO,TIPOLOGIAREGISTRI.TR_DESCRIZIONE as   AUT_REGISTRO,(''+IST_RICHIEDENTE.NOMINATIVO+' '+IST_RICHIEDENTE.NOME) as IST_NOMINATIVO,IST_RICHIEDENTE.TIPOANAGRAFE as IST_RIC_TIPOANAGRAFE,(''+IST_AZIENDA.NOMINATIVO+' '+IST_AZIENDA.NOME) as IST_NOMINATIVOAZIENDA,IST_AZIENDA.TIPOANAGRAFE as IST_AZI_TIPOANAGRAFE, IST_AZIENDA.CODICEFISCALE AS IST_AZI_CODICEFISCALE, IST_AZIENDA.PARTITAIVA AS IST_AZI_PARTITAIVA,IST_RICHIEDENTE.CODICEFISCALE as   IST_CODICEFISCALE,IST_RICHIEDENTE.PARTITAIVA as IST_PARTITAIVA,CAUS_ATTUALE.DESCRIZIONE as ICONC_CAUSALE,AUTORIZZAZIONI_SUBENTRI.FK_CAUSALE_CESSAZIONE as ICONC_CODICECAUSALESTORICO,CAUS_STORICO.DESCRIZIONE as   ICONC_CAUSALESTORICO,AUTORIZZAZIONI_CONCESSIONI.FK_CODICEMERCATO as CONC_IDMERCATO,MERCATI.DESCRIZIONE as CONC_MERCATO,MERCATI.ATTIVO as MERC_ATTIVO,AUTORIZZAZIONI_CONCESSIONI.FK_IDPOSTEGGIO as CONC_IDPOSTEGGIO,MERCATI_D.CODICEPOSTEGGIO as CONC_POSTEGGIO,MERCATI_D.LARGHEZZA as CONC_POS_LARGHEZZA,MERCATI_D.LUNGHEZZA as CONC_POS_LUNGHEZZA,MERCATI_D.SUPERFICIE as CONC_POS_SUPERFICIE,MERCATI_D.FKCODICETIPOSPAZIO as POST_IDTIPOSPAZIO,POSTEGGITIPOSPAZIO.TIPOSPAZIO as   POST_TIPOSPAZIO,AUTORIZZAZIONI_CONCESSIONI.FK_IDMERCATIUSO as CONC_IDMERCATIUSO,MERCATI_USO.DESCRIZIONE as CONC_DESCRIZIONEUSO,MERCATI_USO.PESO as PESO_MERCATO,MERCATI_USO.FKCODICEUSO as MERC_IDUSO,MERCATI_D.FKCODICESTRADARIO as CONC_POS_CODICESTRADARIO FROM AUTORIZZAZIONI_CONCESSIONI LEFT OUTER JOIN AUTORIZZAZIONI AUT_COLLEGATA ON   AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE=AUT_COLLEGATA.IDCOMUNE  AND AUTORIZZAZIONI_CONCESSIONI.FK_IDAUT_COLLEGATA=AUT_COLLEGATA.ID,AUTORIZZAZIONI_SUBENTRI LEFT OUTER JOIN TIPOLOGIAREGISTRI ON AUTORIZZAZIONI_SUBENTRI.IDCOMUNE=TIPOLOGIAREGISTRI.IDCOMUNE  AND AUTORIZZAZIONI_SUBENTRI.FKIDREGISTRO=TIPOLOGIAREGISTRI.TR_ID  LEFT OUTER JOIN CONCESSIONICAUSALI CAUS_STORICO ON   AUTORIZZAZIONI_SUBENTRI.IDCOMUNE=CAUS_STORICO.IDCOMUNE  AND AUTORIZZAZIONI_SUBENTRI.FK_CAUSALE_CESSAZIONE=CAUS_STORICO.CODICECAUSALE,MERCATI_D LEFT OUTER JOIN POSTEGGITIPOSPAZIO ON MERCATI_D.IDCOMUNE=POSTEGGITIPOSPAZIO.IDCOMUNE  AND   MERCATI_D.FKCODICETIPOSPAZIO=POSTEGGITIPOSPAZIO.CODICE,ISTANZE LEFT OUTER JOIN ANAGRAFE IST_AZIENDA ON ISTANZE.IDCOMUNE=IST_AZIENDA.IDCOMUNE  AND ISTANZE.CODICETITOLARELEGALE=IST_AZIENDA.CODICEANAGRAFE,CONCESSIONITIPI,ANAGRAFE TITOLARE,CONCESSIONICAUSALI CAUS_ATTUALE,ANAGRAFE   IST_RICHIEDENTE,MERCATI,MERCATI_USO WHERE AUTORIZZAZIONI_SUBENTRI.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND AUTORIZZAZIONI_SUBENTRI.FK_IDAUT_ATTUALE = AUTORIZZAZIONI_CONCESSIONI.FK_IDAUT_ATTUALE AND CONCESSIONITIPI.TIPOCONCESSIONE = AUTORIZZAZIONI_CONCESSIONI.FK_TIPOCONCESSIONE AND TITOLARE.IDCOMUNE = AUTORIZZAZIONI_SUBENTRI.IDCOMUNE AND TITOLARE.CODICEANAGRAFE = AUTORIZZAZIONI_SUBENTRI.FK_CODICEANAGRAFE AND CAUS_ATTUALE.IDCOMUNE = AUTORIZZAZIONI_SUBENTRI.IDCOMUNE AND CAUS_ATTUALE.CODICECAUSALE = AUTORIZZAZIONI_SUBENTRI.FK_CAUSALE_ACQUISIZIONE AND ISTANZE.IDCOMUNE = AUTORIZZAZIONI_SUBENTRI.IDCOMUNE AND ISTANZE.CODICEISTANZA =   AUTORIZZAZIONI_SUBENTRI.FKIDISTANZA AND IST_RICHIEDENTE.IDCOMUNE = ISTANZE.IDCOMUNE AND IST_RICHIEDENTE.CODICEANAGRAFE = ISTANZE.CODICERICHIEDENTE AND MERCATI.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND MERCATI.CODICEMERCATO = AUTORIZZAZIONI_CONCESSIONI.FK_CODICEMERCATO AND MERCATI_D.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND MERCATI_D.IDPOSTEGGIO =   AUTORIZZAZIONI_CONCESSIONI.FK_IDPOSTEGGIO AND MERCATI_USO.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND MERCATI_USO.ID =   AUTORIZZAZIONI_CONCESSIONI.FK_IDMERCATIUSO
GO
COMMIT
GO
ALTER TABLE FO_ARCONFIGURAZIONE  ADD FKID_SCHEDA_EC NUMERIC(10, 0)
GO
COMMIT
GO
ALTER TABLE FO_ARCONFIGURAZIONE  ADD FLG_SCHEDA_EC_RICHIEDEFIRMA NUMERIC(1, 0)
GO
COMMIT
GO
ALTER TABLE FO_ARCONFIGURAZIONE ADD CONSTRAINT FK_ARCONF_DYN2_MOD_T FOREIGN KEY (IDCOMUNE,FKID_SCHEDA_EC) REFERENCES DYN2_MODELLIT  (IDCOMUNE, ID)
GO
COMMIT
GO
ALTER TABLE CITTADINANZA ADD FLG_PAESE_COMUNITARIO NUMERIC(1, 0) 
GO
COMMIT
GO
ALTER TABLE ALBEROPROC ADD CODICEOGGETTO_WORKFLOW NUMERIC(10)
GO
COMMIT
GO
ALTER TABLE ALBEROPROC ADD CONSTRAINT FK_ALBERO_PROC_OGG_WORKFLOW FOREIGN KEY (IDCOMUNE,CODICEOGGETTO_WORKFLOW) REFERENCES OGGETTI ( IDCOMUNE,CODICEOGGETTO)
GO
COMMIT
GO
ALTER TABLE DOMANDESTC ALTER COLUMN RICHIEDENTE VARCHAR(80) NULL
GO
COMMIT
GO
ALTER TABLE AMMINISTRAZIONI MODIFY STC_IDENTE VARCHAR(20)
GO
COMMIT
GO
ALTER TABLE DOMANDESTC MODIFY ID_ENTEMITT VARCHAR(20)
GO
COMMIT
GO
CREATE TABLE TIPICAUSALIONINTERESSI (IDCOMUNE VARCHAR(6) NOT NULL, ID NUMERIC(8) NOT NULL, FK_IDTIPOCAUSALE NUMERIC(10) NOT NULL, 
	GGRITARDOPAGAMENTO NUMERIC(4) NOT NULL, PERCENTUALE NUMERIC(8, 5) NOT NULL)
GO
COMMIT
GO	
ALTER TABLE TIPICAUSALIONINTERESSI ADD CONSTRAINT TIPICAUSALIONINTERESSI_PK PRIMARY KEY(IDCOMUNE,ID)
GO
COMMIT
GO
ALTER TABLE TIPICAUSALIONINTERESSI ADD CONSTRAINT FK_TIPICAUSALIINTERESSI_001 FOREIGN KEY(IDCOMUNE, FK_IDTIPOCAUSALE) REFERENCES TIPICAUSALIONERI(IDCOMUNE, CO_ID)
GO
COMMIT
GO
ALTER TABLE TIPICAUSALIONERI ADD FLG_TIPICAUSALIINTERESSI NUMERIC(1)
GO
COMMIT
GO
ALTER TABLE TIPICAUSALIONERI ADD FK_TIPICAUSALIINTERESSI NUMERIC(8)
GO
COMMIT
GO
ALTER TABLE TIPICAUSALIONERI ADD CONSTRAINT FK_TIPICAUSON_INTERESSI FOREIGN KEY(IDCOMUNE, FK_TIPICAUSALIINTERESSI) REFERENCES TIPICAUSALIONERI(IDCOMUNE, CO_ID)
GO
COMMIT
GO
ALTER TABLE ISTANZEONERI ADD FK_IDPADRE NUMERIC(10)
GO
COMMIT
GO
ALTER TABLE ISTANZEONERI ADD CONSTRAINT FK_ISTONERI_ISTONERIPADRE FOREIGN KEY(IDCOMUNE, FK_IDPADRE) REFERENCES ISTANZEONERI(IDCOMUNE, ID)
GO
COMMIT
GO
CREATE VIEW VW_LISTAAUTORIZZAZIONI AS SELECT AUTORIZZAZIONI.IDCOMUNE, AUTORIZZAZIONI.FKIDISTANZA AS CODICEISTANZA,ISTANZE.NUMEROISTANZA,AUTORIZZAZIONI.AUTORIZNUMERO AS NUMEROAUTORIZZAZIONE,AUTORIZZAZIONI.AUTORIZDATA AS DATAAUTORIZZAZIONE,COMUNI.COMUNE AS COMUNEAUTORIZZAZIONE, TIPOLOGIAREGISTRI.TR_DESCRIZIONE AS REGISTRO, ANAGRAFE.CODICEANAGRAFE,  (ANAGRAFE.NOMINATIVO + ' ' + ANAGRAFE.NOME)  AS ANAGRAFICA, ISTANZE.LAVORI  AS OGGETTOISTANZA, STRADARIO.CODICESTRADARIO AS LOCALIZZAZIONECODICEVIA, (STRADARIO.PREFISSO+ ' '+ STRADARIO.DESCRIZIONE) AS LOCALIZZAZIONE, ISTANZESTRADARIO.CIVICO  AS LOCALIZZAZIONECIVICO FROM AUTORIZZAZIONI LEFT JOIN ISTANZE ON AUTORIZZAZIONI.IDCOMUNE  =ISTANZE.IDCOMUNE AND AUTORIZZAZIONI.FKIDISTANZA=ISTANZE.CODICEISTANZA LEFT JOIN ISTANZESTRADARIO ON ISTANZESTRADARIO.IDCOMUNE  =ISTANZE.IDCOMUNE AND ISTANZESTRADARIO.CODICEISTANZA=ISTANZE.CODICEISTANZA LEFT JOIN STRADARIO ON ISTANZESTRADARIO.IDCOMUNE  =STRADARIO.IDCOMUNE AND ISTANZESTRADARIO.CODICESTRADARIO=STRADARIO.CODICESTRADARIO LEFT JOIN TIPOLOGIAREGISTRI ON TIPOLOGIAREGISTRI.IDCOMUNE=AUTORIZZAZIONI.IDCOMUNE AND TIPOLOGIAREGISTRI.TR_ID  =AUTORIZZAZIONI.FKIDREGISTRO, ANAGRAFE, COMUNI WHERE ANAGRAFE.IDCOMUNE = AUTORIZZAZIONI.IDCOMUNE AND ANAGRAFE.CODICEANAGRAFE = AUTORIZZAZIONI.FK_CODICEANAGRAFE AND COMUNI.CODICECOMUNE =AUTORIZZAZIONI.AUTORIZCOMUNE AND (ISTANZESTRADARIO.PRIMARIO=1 OR ISTANZESTRADARIO.PRIMARIO IS NULL)
GO
COMMIT
GO