ALTER TABLE pay_profili_enti_creditori ADD COLUMN CODICE_SEGREGAZIONE NUMERIC(2,0) NULL;

ALTER TABLE TIPISOGGETTO MODIFY ORDINE NUMERIC(4,0);


CREATE TABLE PAY_CONNECTOR_WS_ENDPOINT 
(
  CODICE_CONNETTORE VARCHAR(20) NOT NULL 
, ID NUMERIC(9,0) NOT NULL 
, ENDPOINT_URL VARCHAR(256) NOT NULL 
, UTENTE VARCHAR(50) 
, PASSWORD VARCHAR(50) 
, TIMEOUT NUMERIC(8,0)
, DESCRIZIONE VARCHAR(100) 
, CONSTRAINT PAY_CONNECTOR_WS_ENDPOINT_PK PRIMARY KEY 
  (
    CODICE_CONNETTORE 
  , ID 
  )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE PAY_CONNECTOR_CONFIG ADD (FK_WS_CARICAMENTO NUMERIC(9,0) );

ALTER TABLE PAY_CONNECTOR_CONFIG ADD (FK_WS_ANNULLAMENTO NUMERIC(9,0) );

ALTER TABLE PAY_CONNECTOR_CONFIG ADD (FK_WS_VERIFICA NUMERIC(9,0) );

ALTER TABLE PAY_CONNECTOR_CONFIG ADD (FK_WS_ATTIVA_SESSIONE NUMERIC(9,0) );

ALTER TABLE PAY_CONNECTOR_CONFIG ADD (FK_WS_AVVISO NUMERIC(9,0) );

ALTER TABLE PAY_CONNECTOR_CONFIG ADD (FK_WS_NOTIFICA NUMERIC(9,0) );

ALTER TABLE PAY_CONNECTOR_CONFIG ADD (FK_WS_SECURITY NUMERIC(9,0) );

ALTER TABLE PAY_CONNECTOR_CONFIG ADD CONSTRAINT PAYCONN_FK_WSANNULLAM FOREIGN KEY(CODICE,FK_WS_ANNULLAMENTO) REFERENCES PAY_CONNECTOR_WS_ENDPOINT (CODICE_CONNETTORE, ID);

ALTER TABLE PAY_CONNECTOR_CONFIG ADD CONSTRAINT PAYCONN_FK_WSAVVISO FOREIGN KEY(CODICE,FK_WS_AVVISO) REFERENCES PAY_CONNECTOR_WS_ENDPOINT (CODICE_CONNETTORE,ID);

ALTER TABLE PAY_CONNECTOR_CONFIG ADD CONSTRAINT PAYCONN_FK_WSCARICAM FOREIGN KEY(CODICE,FK_WS_CARICAMENTO) REFERENCES PAY_CONNECTOR_WS_ENDPOINT (CODICE_CONNETTORE,ID) ;

ALTER TABLE PAY_CONNECTOR_CONFIG ADD CONSTRAINT PAYCONN_FK_WSNOTIFICA FOREIGN KEY(CODICE, FK_WS_NOTIFICA) REFERENCES PAY_CONNECTOR_WS_ENDPOINT(CODICE_CONNETTORE,ID);

ALTER TABLE PAY_CONNECTOR_CONFIG ADD CONSTRAINT PAYCONN_FK_WSSEC FOREIGN KEY(CODICE, FK_WS_SECURITY) REFERENCES PAY_CONNECTOR_WS_ENDPOINT(CODICE_CONNETTORE, ID);

ALTER TABLE PAY_CONNECTOR_CONFIG ADD CONSTRAINT PAYCONN_FK_WSSESSIONE FOREIGN KEY (CODICE,FK_WS_ATTIVA_SESSIONE) REFERENCES PAY_CONNECTOR_WS_ENDPOINT(CODICE_CONNETTORE,ID);

ALTER TABLE PAY_CONNECTOR_CONFIG ADD CONSTRAINT PAYCONN_FK_WSVERIFICA FOREIGN KEY(CODICE,FK_WS_VERIFICA ) REFERENCES PAY_CONNECTOR_WS_ENDPOINT (CODICE_CONNETTORE, ID) ;

ALTER TABLE PAY_PAGAMENTI ADD (ID_PSP VARCHAR(50) );

ALTER TABLE PAY_PAGAMENTI ADD (RAG_SOC_PSP VARCHAR(200) );

ALTER TABLE MERCATIPRESENZE_T ADD FLAG_FESTIVO NUMERIC(1,0) DEFAULT 0;
