/**
 * Please modify this class to meet your needs This class is not complete
 */
package it.gruppoinit.pal.gp.pay.connector.easybridge.ws;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.1.18 2021-10-01T12:41:34.815+02:00 Generated source version: 3.1.18
 * 
 */
@javax.jws.WebService(serviceName = "WEBS_EasyBridgeInterface", portName = "WEBS_EasyBridgeInterfaceSoap12", targetNamespace = "http://easybridge.eu/bridge/", wsdlLocation = "file:/C:/sviluppo/workspaces/COMPONENTI/test/src/WEBS_EasyBridgeInterface.wsdl", endpointInterface = "it.gruppoinit.pal.gp.pay.connector.easybridge.ws.WEBSEasyBridgeInterfaceSoap")
public class EasyBridgeEsitoInterfaceSoap12Impl {

    private static final Logger LOG = Logger.getLogger(EasyBridgeEsitoInterfaceSoap12Impl.class.getName());

    /* (non-Javadoc)
     * @see it.gruppoinit.pal.gp.pay.connector.easybridge.ws.WEBSEasyBridgeInterfaceSoap#pdpExportAny(java.lang.String identificativoDominio, java.lang.String identificativoBU, java.lang.String param)*
     */
    public it.gruppoinit.pal.gp.pay.connector.easybridge.ws.model.Output pdpExportAny(java.lang.String identificativoDominio,
	    java.lang.String identificativoBU, java.lang.String param) {

	LOG.info("Executing operation pdpExportAny");
	System.out.println(identificativoDominio);
	System.out.println(identificativoBU);
	System.out.println(param);
	try {
	    it.gruppoinit.pal.gp.pay.connector.easybridge.ws.model.Output _return = new it.gruppoinit.pal.gp.pay.connector.easybridge.ws.model.Output();
	    _return.setParam("Param977641123");
	    return _return;
	} catch (java.lang.Exception ex) {
	    ex.printStackTrace();
	    throw new RuntimeException(ex);
	}
    }

    /* (non-Javadoc)
     * @see it.gruppoinit.pal.gp.pay.connector.easybridge.ws.WEBSEasyBridgeInterfaceSoap#intExecuteDistant(java.lang.String identificativoDominio, java.lang.String identificativoBU, java.lang.String param)*
     */
    public it.gruppoinit.pal.gp.pay.connector.easybridge.ws.model.Output intExecuteDistant(java.lang.String identificativoDominio,
	    java.lang.String identificativoBU, java.lang.String param) {

	LOG.info("Executing operation intExecuteDistant");
	System.out.println(identificativoDominio);
	System.out.println(identificativoBU);
	System.out.println(param);
	try {
	    it.gruppoinit.pal.gp.pay.connector.easybridge.ws.model.Output _return = new it.gruppoinit.pal.gp.pay.connector.easybridge.ws.model.Output();
	    _return.setParam("Param-1078605807");
	    return _return;
	} catch (java.lang.Exception ex) {
	    ex.printStackTrace();
	    throw new RuntimeException(ex);
	}
    }

    /* (non-Javadoc)
     * @see it.gruppoinit.pal.gp.pay.connector.easybridge.ws.WEBSEasyBridgeInterfaceSoap#pdpGeneraIUV(java.lang.String identificativoDominio, java.lang.String identificativoBU, java.lang.String param)*
     */
    public it.gruppoinit.pal.gp.pay.connector.easybridge.ws.model.Output pdpGeneraIUV(java.lang.String identificativoDominio,
	    java.lang.String identificativoBU, java.lang.String param) {

	LOG.info("Executing operation pdpGeneraIUV");
	System.out.println(identificativoDominio);
	System.out.println(identificativoBU);
	System.out.println(param);
	try {
	    it.gruppoinit.pal.gp.pay.connector.easybridge.ws.model.Output _return = new it.gruppoinit.pal.gp.pay.connector.easybridge.ws.model.Output();
	    _return.setParam("Param75923569");
	    return _return;
	} catch (java.lang.Exception ex) {
	    ex.printStackTrace();
	    throw new RuntimeException(ex);
	}
    }

    /* (non-Javadoc)
     * @see it.gruppoinit.pal.gp.pay.connector.easybridge.ws.WEBSEasyBridgeInterfaceSoap#pdpInviaCarrelloRPT(java.lang.String identificativoDominio, java.lang.String identificativoBU, java.lang.String param)*
     */
    public it.gruppoinit.pal.gp.pay.connector.easybridge.ws.model.Output pdpInviaCarrelloRPT(java.lang.String identificativoDominio,
	    java.lang.String identificativoBU, java.lang.String param) {

	LOG.info("Executing operation pdpInviaCarrelloRPT");
	System.out.println(identificativoDominio);
	System.out.println(identificativoBU);
	System.out.println(param);
	try {
	    it.gruppoinit.pal.gp.pay.connector.easybridge.ws.model.Output _return = new it.gruppoinit.pal.gp.pay.connector.easybridge.ws.model.Output();
	    _return.setParam("Param1027989096");
	    return _return;
	} catch (java.lang.Exception ex) {
	    ex.printStackTrace();
	    throw new RuntimeException(ex);
	}
    }

    /* (non-Javadoc)
     * @see it.gruppoinit.pal.gp.pay.connector.easybridge.ws.WEBSEasyBridgeInterfaceSoap#pdpRecuperaRT(java.lang.String identificativoDominio, java.lang.String identificativoBU, java.lang.String param)*
     */
    public it.gruppoinit.pal.gp.pay.connector.easybridge.ws.model.Output pdpRecuperaRT(java.lang.String identificativoDominio,
	    java.lang.String identificativoBU, java.lang.String param) {

	LOG.info("Executing operation pdpRecuperaRT");
	System.out.println(identificativoDominio);
	System.out.println(identificativoBU);
	System.out.println(param);
	try {
	    it.gruppoinit.pal.gp.pay.connector.easybridge.ws.model.Output _return = new it.gruppoinit.pal.gp.pay.connector.easybridge.ws.model.Output();
	    _return.setParam("Param62446067");
	    return _return;
	} catch (java.lang.Exception ex) {
	    ex.printStackTrace();
	    throw new RuntimeException(ex);
	}
    }

    /* (non-Javadoc)
     * @see it.gruppoinit.pal.gp.pay.connector.easybridge.ws.WEBSEasyBridgeInterfaceSoap#pdpPredisponiCodiciGraficiIUV(java.lang.String identificativoDominio, java.lang.String identificativoBU, java.lang.String param)*
     */
    public it.gruppoinit.pal.gp.pay.connector.easybridge.ws.model.Output pdpPredisponiCodiciGraficiIUV(java.lang.String identificativoDominio,
	    java.lang.String identificativoBU, java.lang.String param) {

	LOG.info("Executing operation pdpPredisponiCodiciGraficiIUV");
	System.out.println(identificativoDominio);
	System.out.println(identificativoBU);
	System.out.println(param);
	try {
	    it.gruppoinit.pal.gp.pay.connector.easybridge.ws.model.Output _return = new it.gruppoinit.pal.gp.pay.connector.easybridge.ws.model.Output();
	    _return.setParam("Param430565156");
	    return _return;
	} catch (java.lang.Exception ex) {
	    ex.printStackTrace();
	    throw new RuntimeException(ex);
	}
    }

    /* (non-Javadoc)
     * @see it.gruppoinit.pal.gp.pay.connector.easybridge.ws.WEBSEasyBridgeInterfaceSoap#pdpRecuperaRPT(java.lang.String identificativoDominio, java.lang.String identificativoBU, java.lang.String param)*
     */
    public it.gruppoinit.pal.gp.pay.connector.easybridge.ws.model.Output pdpRecuperaRPT(java.lang.String identificativoDominio,
	    java.lang.String identificativoBU, java.lang.String param) {

	LOG.info("Executing operation pdpRecuperaRPT");
	System.out.println(identificativoDominio);
	System.out.println(identificativoBU);
	System.out.println(param);
	try {
	    it.gruppoinit.pal.gp.pay.connector.easybridge.ws.model.Output _return = new it.gruppoinit.pal.gp.pay.connector.easybridge.ws.model.Output();
	    _return.setParam("Param-1393923765");
	    return _return;
	} catch (java.lang.Exception ex) {
	    ex.printStackTrace();
	    throw new RuntimeException(ex);
	}
    }

    /* (non-Javadoc)
     * @see it.gruppoinit.pal.gp.pay.connector.easybridge.ws.WEBSEasyBridgeInterfaceSoap#pdpRichiediStornoRT(java.lang.String identificativoDominio, java.lang.String identificativoBU, java.lang.String param)*
     */
    public it.gruppoinit.pal.gp.pay.connector.easybridge.ws.model.Output pdpRichiediStornoRT(java.lang.String identificativoDominio,
	    java.lang.String identificativoBU, java.lang.String param) {

	LOG.info("Executing operation pdpRichiediStornoRT");
	System.out.println(identificativoDominio);
	System.out.println(identificativoBU);
	System.out.println(param);
	try {
	    it.gruppoinit.pal.gp.pay.connector.easybridge.ws.model.Output _return = new it.gruppoinit.pal.gp.pay.connector.easybridge.ws.model.Output();
	    _return.setParam("Param-2132169988");
	    return _return;
	} catch (java.lang.Exception ex) {
	    ex.printStackTrace();
	    throw new RuntimeException(ex);
	}
    }

    /* (non-Javadoc)
     * @see it.gruppoinit.pal.gp.pay.connector.easybridge.ws.WEBSEasyBridgeInterfaceSoap#pdpChiediSceltaWISP(java.lang.String identificativoDominio, java.lang.String identificativoBU, java.lang.String param)*
     */
    public it.gruppoinit.pal.gp.pay.connector.easybridge.ws.model.Output pdpChiediSceltaWISP(java.lang.String identificativoDominio,
	    java.lang.String identificativoBU, java.lang.String param) {

	LOG.info("Executing operation pdpChiediSceltaWISP");
	System.out.println(identificativoDominio);
	System.out.println(identificativoBU);
	System.out.println(param);
	try {
	    it.gruppoinit.pal.gp.pay.connector.easybridge.ws.model.Output _return = new it.gruppoinit.pal.gp.pay.connector.easybridge.ws.model.Output();
	    _return.setParam("Param1515219779");
	    return _return;
	} catch (java.lang.Exception ex) {
	    ex.printStackTrace();
	    throw new RuntimeException(ex);
	}
    }

    /* (non-Javadoc)
     * @see it.gruppoinit.pal.gp.pay.connector.easybridge.ws.WEBSEasyBridgeInterfaceSoap#pdpChiediStatoRPT(java.lang.String identificativoDominio, java.lang.String identificativoBU, java.lang.String param)*
     */
    public it.gruppoinit.pal.gp.pay.connector.easybridge.ws.model.Output pdpChiediStatoRPT(java.lang.String identificativoDominio,
	    java.lang.String identificativoBU, java.lang.String param) {

	LOG.info("Executing operation pdpChiediStatoRPT");
	System.out.println(identificativoDominio);
	System.out.println(identificativoBU);
	System.out.println(param);
	try {
	    it.gruppoinit.pal.gp.pay.connector.easybridge.ws.model.Output _return = new it.gruppoinit.pal.gp.pay.connector.easybridge.ws.model.Output();
	    _return.setParam("Param90692975");
	    return _return;
	} catch (java.lang.Exception ex) {
	    ex.printStackTrace();
	    throw new RuntimeException(ex);
	}
    }

    /* (non-Javadoc)
     * @see it.gruppoinit.pal.gp.pay.connector.easybridge.ws.WEBSEasyBridgeInterfaceSoap#pdpRecuperaDebit(java.lang.String identificativoDominio, java.lang.String identificativoBU, java.lang.String param)*
     */
    public it.gruppoinit.pal.gp.pay.connector.easybridge.ws.model.Output pdpRecuperaDebit(java.lang.String identificativoDominio,
	    java.lang.String identificativoBU, java.lang.String param) {

	LOG.info("Executing operation pdpRecuperaDebit");
	System.out.println(identificativoDominio);
	System.out.println(identificativoBU);
	System.out.println(param);
	try {
	    it.gruppoinit.pal.gp.pay.connector.easybridge.ws.model.Output _return = new it.gruppoinit.pal.gp.pay.connector.easybridge.ws.model.Output();
	    _return.setParam("Param514273111");
	    return _return;
	} catch (java.lang.Exception ex) {
	    ex.printStackTrace();
	    throw new RuntimeException(ex);
	}
    }

    /* (non-Javadoc)
     * @see it.gruppoinit.pal.gp.pay.connector.easybridge.ws.WEBSEasyBridgeInterfaceSoap#pdpGenAnalogRT(java.lang.String identificativoDominio, java.lang.String identificativoBU, java.lang.String param)*
     */
    public it.gruppoinit.pal.gp.pay.connector.easybridge.ws.model.Output pdpGenAnalogRT(java.lang.String identificativoDominio,
	    java.lang.String identificativoBU, java.lang.String param) {

	LOG.info("Executing operation pdpGenAnalogRT");
	System.out.println(identificativoDominio);
	System.out.println(identificativoBU);
	System.out.println(param);
	try {
	    it.gruppoinit.pal.gp.pay.connector.easybridge.ws.model.Output _return = new it.gruppoinit.pal.gp.pay.connector.easybridge.ws.model.Output();
	    _return.setParam("Param-192892700");
	    return _return;
	} catch (java.lang.Exception ex) {
	    ex.printStackTrace();
	    throw new RuntimeException(ex);
	}
    }

    /* (non-Javadoc)
     * @see it.gruppoinit.pal.gp.pay.connector.easybridge.ws.WEBSEasyBridgeInterfaceSoap#pdpExportFile(java.lang.String identificativoDominio, java.lang.String identificativoBU, java.lang.String param)*
     */
    public it.gruppoinit.pal.gp.pay.connector.easybridge.ws.model.Output pdpExportFile(java.lang.String identificativoDominio,
	    java.lang.String identificativoBU, java.lang.String param) {

	LOG.info("Executing operation pdpExportFile");
	System.out.println(identificativoDominio);
	System.out.println(identificativoBU);
	System.out.println(param);
	try {
	    it.gruppoinit.pal.gp.pay.connector.easybridge.ws.model.Output _return = new it.gruppoinit.pal.gp.pay.connector.easybridge.ws.model.Output();
	    _return.setParam("Param-1446377922");
	    return _return;
	} catch (java.lang.Exception ex) {
	    ex.printStackTrace();
	    throw new RuntimeException(ex);
	}
    }

    /* (non-Javadoc)
     * @see it.gruppoinit.pal.gp.pay.connector.easybridge.ws.WEBSEasyBridgeInterfaceSoap#pdpInviaRPT(java.lang.String identificativoDominio, java.lang.String identificativoBU, java.lang.String param)*
     */
    public it.gruppoinit.pal.gp.pay.connector.easybridge.ws.model.Output pdpInviaRPT(java.lang.String identificativoDominio,
	    java.lang.String identificativoBU, java.lang.String param) {

	LOG.info("Executing operation pdpInviaRPT");
	System.out.println(identificativoDominio);
	System.out.println(identificativoBU);
	System.out.println(param);
	try {
	    it.gruppoinit.pal.gp.pay.connector.easybridge.ws.model.Output _return = new it.gruppoinit.pal.gp.pay.connector.easybridge.ws.model.Output();
	    _return.setParam("Param-439743194");
	    return _return;
	} catch (java.lang.Exception ex) {
	    ex.printStackTrace();
	    throw new RuntimeException(ex);
	}
    }

    /* (non-Javadoc)
     * @see it.gruppoinit.pal.gp.pay.connector.easybridge.ws.WEBSEasyBridgeInterfaceSoap#pdpVerificaMarcaDaBolloDigitale(java.lang.String identificativoDominio, java.lang.String identificativoBU, java.lang.String param)*
     */
    public it.gruppoinit.pal.gp.pay.connector.easybridge.ws.model.Output pdpVerificaMarcaDaBolloDigitale(java.lang.String identificativoDominio,
	    java.lang.String identificativoBU, java.lang.String param) {

	LOG.info("Executing operation pdpVerificaMarcaDaBolloDigitale");
	System.out.println(identificativoDominio);
	System.out.println(identificativoBU);
	System.out.println(param);
	try {
	    it.gruppoinit.pal.gp.pay.connector.easybridge.ws.model.Output _return = new it.gruppoinit.pal.gp.pay.connector.easybridge.ws.model.Output();
	    _return.setParam("Param-1202606930");
	    return _return;
	} catch (java.lang.Exception ex) {
	    ex.printStackTrace();
	    throw new RuntimeException(ex);
	}
    }

    /* (non-Javadoc)
     * @see it.gruppoinit.pal.gp.pay.connector.easybridge.ws.WEBSEasyBridgeInterfaceSoap#pdpCancellaPagamento(java.lang.String identificativoDominio, java.lang.String identificativoBU, java.lang.String param)*
     */
    public it.gruppoinit.pal.gp.pay.connector.easybridge.ws.model.Output pdpCancellaPagamento(java.lang.String identificativoDominio,
	    java.lang.String identificativoBU, java.lang.String param) {

	LOG.info("Executing operation pdpCancellaPagamento");
	System.out.println(identificativoDominio);
	System.out.println(identificativoBU);
	System.out.println(param);
	try {
	    it.gruppoinit.pal.gp.pay.connector.easybridge.ws.model.Output _return = new it.gruppoinit.pal.gp.pay.connector.easybridge.ws.model.Output();
	    _return.setParam("Param1255582910");
	    return _return;
	} catch (java.lang.Exception ex) {
	    ex.printStackTrace();
	    throw new RuntimeException(ex);
	}
    }

    /* (non-Javadoc)
     * @see it.gruppoinit.pal.gp.pay.connector.easybridge.ws.WEBSEasyBridgeInterfaceSoap#pdpCaricaPagamento(java.lang.String identificativoDominio, java.lang.String identificativoBU, java.lang.String param)*
     */
    public it.gruppoinit.pal.gp.pay.connector.easybridge.ws.model.Output pdpCaricaPagamento(java.lang.String identificativoDominio,
	    java.lang.String identificativoBU, java.lang.String param) {

	LOG.info("Executing operation pdpCaricaPagamento");
	System.out.println(identificativoDominio);
	System.out.println(identificativoBU);
	System.out.println(param);
	try {
	    it.gruppoinit.pal.gp.pay.connector.easybridge.ws.model.Output _return = new it.gruppoinit.pal.gp.pay.connector.easybridge.ws.model.Output();
	    _return.setParam("Param-803893198");
	    return _return;
	} catch (java.lang.Exception ex) {
	    ex.printStackTrace();
	    throw new RuntimeException(ex);
	}
    }

    /* (non-Javadoc)
     * @see it.gruppoinit.pal.gp.pay.connector.easybridge.ws.WEBSEasyBridgeInterfaceSoap#pdpPaymentNotice(java.lang.String identificativoDominio, java.lang.String identificativoBU, java.lang.String param)*
     */
    public it.gruppoinit.pal.gp.pay.connector.easybridge.ws.model.Output pdpPaymentNotice(java.lang.String identificativoDominio,
	    java.lang.String identificativoBU, java.lang.String param) {

	LOG.info("Executing operation pdpPaymentNotice");
	System.out.println(identificativoDominio);
	System.out.println(identificativoBU);
	System.out.println(param);
	try {
	    it.gruppoinit.pal.gp.pay.connector.easybridge.ws.model.Output _return = new it.gruppoinit.pal.gp.pay.connector.easybridge.ws.model.Output();
	    _return.setParam("Param1217301738");
	    return _return;
	} catch (java.lang.Exception ex) {
	    ex.printStackTrace();
	    throw new RuntimeException(ex);
	}
    }

    /* (non-Javadoc)
     * @see it.gruppoinit.pal.gp.pay.connector.easybridge.ws.WEBSEasyBridgeInterfaceSoap#pdpGeneraRPT(java.lang.String identificativoDominio, java.lang.String identificativoBU, java.lang.String param)*
     */
    public it.gruppoinit.pal.gp.pay.connector.easybridge.ws.model.Output pdpGeneraRPT(java.lang.String identificativoDominio,
	    java.lang.String identificativoBU, java.lang.String param) {

	LOG.info("Executing operation pdpGeneraRPT");
	System.out.println(identificativoDominio);
	System.out.println(identificativoBU);
	System.out.println(param);
	try {
	    it.gruppoinit.pal.gp.pay.connector.easybridge.ws.model.Output _return = new it.gruppoinit.pal.gp.pay.connector.easybridge.ws.model.Output();
	    _return.setParam("Param-1080196539");
	    return _return;
	} catch (java.lang.Exception ex) {
	    ex.printStackTrace();
	    throw new RuntimeException(ex);
	}
    }

    /* (non-Javadoc)
     * @see it.gruppoinit.pal.gp.pay.connector.easybridge.ws.WEBSEasyBridgeInterfaceSoap#pdpAttivaPagamento(java.lang.String identificativoDominio, java.lang.String identificativoBU, java.lang.String param)*
     */
    public it.gruppoinit.pal.gp.pay.connector.easybridge.ws.model.Output pdpAttivaPagamento(java.lang.String identificativoDominio,
	    java.lang.String identificativoBU, java.lang.String param) {

	LOG.info("Executing operation pdpAttivaPagamento");
	System.out.println(identificativoDominio);
	System.out.println(identificativoBU);
	System.out.println(param);
	try {
	    it.gruppoinit.pal.gp.pay.connector.easybridge.ws.model.Output _return = new it.gruppoinit.pal.gp.pay.connector.easybridge.ws.model.Output();
	    _return.setParam("Param-1780435637");
	    return _return;
	} catch (java.lang.Exception ex) {
	    ex.printStackTrace();
	    throw new RuntimeException(ex);
	}
    }
}
