<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.11" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.10" />
    <PackageReference Include="RestSharp" Version="114.0.0" />
	  <PackageReference Include="System.ServiceModel.Http" Version="10.0.652802" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\PersonalLib2\PersonalLib2.csproj" />
    <ProjectReference Include="..\SIGePro.Data\SIGePro.Data.csproj" />
    <ProjectReference Include="..\SIGePro.Manager.Authentication\SIGePro.Manager.Authentication.csproj" />
    <ProjectReference Include="..\SIGePro.Manager\SIGePro.Manager.csproj" />
    <ProjectReference Include="..\VBG.Backend.Protocollo\VBG.Backend.Protocollo.Verticalizzazioni.Shared.csproj" />
    <ProjectReference Include="..\VBG.Shared.Infrastructure\VBG.Shared.Infrastructure.csproj" />
  </ItemGroup>

</Project>