CREATE TABLE ALBEROPROC_METADATI(IDCOMUNE VARCHAR(6),FK_SCID DECIMAL(10,0),CHIAVE VARCHAR(100),VALORE VARCHAR(4000)) ENGINE=INNODB DEFAULT CHARSET=utf8;
ALTER TABLE ALBEROPROC_METADATI ADD PRIMARY KEY(IDCOMUNE,FK_SCID,CHIAVE);

ALTER TABLE ALBEROPROC_METADATI ADD CONSTRAINT ALBEROPROC_METADATI_FK1 FOREIGN KEY (IDCOMUNE,FK_SCID) REFERENCES ALBEROPROC(IDCOMUNE,SC_ID);

ALTER TABLE ISTANZEONERI ADD FK_POSDEBDETTAGLIO_ID NUMERIC(10,0); 

ALTER TABLE ISTANZEONERI ADD CONSTRAINT FK_ISTONERI_DETTPOSDEB FOREIGN KEY(IDCOMUNE,FK_POSDEBDETTAGLIO_ID) REFERENCES DETT_POSIZIONE_DEBITORIA(IDCOMUNE,ID);

CREATE INDEX IDX_ISTONERI_DETTPOSDEB  ON ISTANZEONERI (IDCOMUNE,FK_POSDEBDETTAGLIO_ID);


alter table BOLL_CFG_TIPO add FLAG_IGNORA_SUBENTRI NUMERIC(1,0);



ALTER TABLE mercati_d ADD data_creazione DATETIME;
UPDATE mercati_d SET data_creazione=STR_TO_DATE('1900-01-01','%Y-%m-%d') WHERE  data_creazione IS NULL;

ALTER TABLE mercati_uso ADD data_creazione DATETIME;
UPDATE mercati_uso SET  data_creazione=STR_TO_DATE('1900-01-01','%Y-%m-%d') WHERE  data_creazione IS NULL;


ALTER TABLE BOLL_CFG_TIPO ADD FLAG_RICHIESTA_FATTURA NUMERIC(1,0);
UPDATE BOLL_CFG_TIPO SET FLAG_RICHIESTA_FATTURA=0 WHERE FLAG_RICHIESTA_FATTURA IS NULL;

ALTER TABLE PAY_CONNECTOR_CONFIG ADD COLUMN FK_WS_FATTURA DECIMAL(9,0) NULL;
ALTER TABLE PAY_CONNECTOR_CONFIG ADD COLUMN FK_WS_RICEVUTA DECIMAL(9,0) NULL;
ALTER TABLE PAY_CONNECTOR_CONFIG ADD COLUMN FK_WS_IUV DECIMAL(9,0) NULL;
ALTER TABLE PAY_CONNECTOR_CONFIG ADD CONSTRAINT PAYCONN_FK_RICEVUTA FOREIGN KEY (CODICE, FK_WS_RICEVUTA) REFERENCES PAY_CONNECTOR_WS_ENDPOINT(CODICE_CONNETTORE, ID);
ALTER TABLE PAY_CONNECTOR_CONFIG ADD CONSTRAINT PAYCONN_FK_FATTURA FOREIGN KEY (CODICE, FK_WS_FATTURA) REFERENCES PAY_CONNECTOR_WS_ENDPOINT(CODICE_CONNETTORE, ID);
ALTER TABLE PAY_CONNECTOR_CONFIG ADD CONSTRAINT PAYCONN_FK_IUV FOREIGN KEY (CODICE, FK_WS_IUV) REFERENCES PAY_CONNECTOR_WS_ENDPOINT(CODICE_CONNETTORE, ID);



ALTER TABLE PAY_POSIZIONI_DEBITORIE DROP FOREIGN KEY PAY_POSDEB_FK_OGGAVV;
ALTER TABLE PAY_POSIZIONI_DEBITORIE DROP FOREIGN KEY PAY_POSDEB_FK_OGGFAT;
ALTER TABLE PAY_POSIZIONI_DEBITORIE DROP FOREIGN KEY PAY_POSDEB_FK_OGGRT;

ALTER TABLE PAY_POSIZIONI_DEBITORIE MODIFY FK_OGGETTO_RICEVUTA  DECIMAL(10,0) ;
ALTER TABLE PAY_POSIZIONI_DEBITORIE MODIFY FK_OGGETTO_AVVISO  DECIMAL(10,0) ;
ALTER TABLE PAY_POSIZIONI_DEBITORIE MODIFY FK_OGGETTO_FATTURA  DECIMAL(10,0) ;


CREATE TABLE PAY_DOCUMENTI( 
 IDCOMUNE VARCHAR(6) NOT NULL,
 ID DECIMAL(10,0) NOT NULL,
 NOME_DOCUMENTO VARCHAR(256) NOT NULL,
 NOME_FILESYSTEM VARCHAR(256),
 PERCORSO VARCHAR(256),
 DATI_FILE BLOB,
 DIMENSIONE DECIMAL(9,0),
 PRIMARY KEY (IDCOMUNE, ID)
)  ENGINE=INNODB DEFAULT CHARSET=utf8;

ALTER TABLE PAY_POSIZIONI_DEBITORIE ADD CONSTRAINT PAY_POSDEB_FK_DOCFATT FOREIGN KEY (IDCOMUNE, FK_OGGETTO_FATTURA) REFERENCES PAY_DOCUMENTI(IDCOMUNE, ID);
ALTER TABLE PAY_POSIZIONI_DEBITORIE ADD CONSTRAINT PAY_POSDEB_FK_DOCRICEV FOREIGN KEY (IDCOMUNE, FK_OGGETTO_RICEVUTA) REFERENCES PAY_DOCUMENTI(IDCOMUNE, ID);
ALTER TABLE PAY_POSIZIONI_DEBITORIE ADD CONSTRAINT PAY_POSDEB_FK_DOCAVVISO FOREIGN KEY (IDCOMUNE, FK_OGGETTO_AVVISO) REFERENCES PAY_DOCUMENTI(IDCOMUNE, ID);



create TABLE BOLL_GEST_DETT_AUTORIZZ(
IDCOMUNE VARCHAR(6) NOT NULL,
ID NUMERIC(10,0) NOT NULL,
FK_AUTORIZZAZIONE_ID NUMERIC(6,0),
FK_BOLLGESTDET_ID NUMERIC(10,0)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

ALTER TABLE BOLL_GEST_DETT_AUTORIZZ ADD CONSTRAINT PK_BOLL_GEST_DETT_AUTORIZZ PRIMARY KEY(IDCOMUNE, ID); 
ALTER TABLE BOLL_GEST_DETT_AUTORIZZ ADD CONSTRAINT FK_BGESTDETTAUT_AUTORIZZAZIONI FOREIGN KEY(IDCOMUNE, FK_AUTORIZZAZIONE_ID) REFERENCES AUTORIZZAZIONI(IDCOMUNE,ID); 
ALTER TABLE BOLL_GEST_DETT_AUTORIZZ ADD CONSTRAINT FK_BGESTDETTAUT_BOLL_GESTD FOREIGN KEY(IDCOMUNE, FK_BOLLGESTDET_ID) REFERENCES BOLL_GEST_DETTAGLIO(IDCOMUNE,ID);


CREATE TABLE BOLL_GEST_MERCATI_DETT(
IDCOMUNE VARCHAR(6) NOT NULL,
ID NUMERIC(10,0) NOT NULL,
FK_ID_GEST_AUTORIZZAZIONI NUMERIC(10,0) NOT NULL, 
FK_IDPOSTEGGIO NUMERIC(6,0) NOT NULL, 
FK_MERCATO_USO NUMERIC(4,0) NOT NULL,
FK_MERCATIPRESENZET_ID NUMERIC(6,0) NOT NULL,
IMPORTO_TOTALE DECIMAL(11,2) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

ALTER TABLE BOLL_GEST_MERCATI_DETT ADD CONSTRAINT PK_BOLL_GEST_MERCATI_DETT PRIMARY KEY(IDCOMUNE, ID); 
ALTER TABLE BOLL_GEST_MERCATI_DETT ADD CONSTRAINT FK_BGESTMERCDETT_MERCATI_D FOREIGN KEY(IDCOMUNE, FK_IDPOSTEGGIO) REFERENCES MERCATI_D(IDCOMUNE,IDPOSTEGGIO); 
ALTER TABLE BOLL_GEST_MERCATI_DETT ADD CONSTRAINT FK_BGESTMERCDETT_MERC_USO FOREIGN KEY(IDCOMUNE, FK_MERCATO_USO) REFERENCES MERCATI_USO(IDCOMUNE,ID); 
ALTER TABLE BOLL_GEST_MERCATI_DETT ADD CONSTRAINT FK_BGESTMERCDETT_BGESTDETTAUT FOREIGN KEY(IDCOMUNE, FK_ID_GEST_AUTORIZZAZIONI) REFERENCES BOLL_GEST_DETT_AUTORIZZ(IDCOMUNE,ID);
ALTER TABLE BOLL_GEST_MERCATI_DETT ADD CONSTRAINT FK_BGESTMERCDETT_MERCATIPREST FOREIGN KEY (IDCOMUNE, FK_MERCATIPRESENZET_ID) REFERENCES MERCATIPRESENZE_T(IDCOMUNE, ID);


CREATE TABLE PAY_CONNECTOR_CONFIG_PARAMS(  
  CONFIG_PARAM VARCHAR(30) NOT NULL,
  DESCRIZIONE VARCHAR(200) NOT NULL,
  CODICE_CONNETTORE VARCHAR(20),
  PRIMARY KEY (CONFIG_PARAM)
)  ENGINE=INNODB DEFAULT CHARSET=UTF8;
ALTER TABLE PAY_CONNECTOR_CONFIG_PARAMS   ADD CONSTRAINT PAYCONNCFG_FK_CONN FOREIGN KEY (CODICE_CONNETTORE) REFERENCES PAY_CONNECTOR_CONFIG(CODICE);


CREATE TABLE PAY_CONNECTOR_CONFIG_VALUES(  
  IDCOMUNE VARCHAR(6) NOT NULL,
  ID DECIMAL(4,0) NOT NULL,
  CONFIG_PARAM VARCHAR(30) NOT NULL,
  CODICE_CONNETTORE VARCHAR(20),
  VALORE VARCHAR(500),
  PRIMARY KEY (IDCOMUNE, ID),
  CONSTRAINT PAYCONNVAL_FK_CONN FOREIGN KEY (CODICE_CONNETTORE) REFERENCES PAY_CONNECTOR_CONFIG(CODICE),
  CONSTRAINT PAYCONNVAL_FK_CONNPARAM FOREIGN KEY (CONFIG_PARAM) REFERENCES PAY_CONNECTOR_CONFIG_PARAMS(CONFIG_PARAM)
)  ENGINE=INNODB DEFAULT CHARSET=UTF8;


ALTER TABLE BOLL_CFG_TIPO ADD TITOLARITA_PAGAMENTI VARCHAR(25);

ALTER TABLE BOLL_GEST_TESTATA ADD TITOLARITA_PAGAMENTI VARCHAR(25);


ALTER TABLE BOLL_GEST_DETTAGLIO ADD IMPORTO_SENZA_IVA  NUMERIC(11,2) ;
ALTER TABLE BOLL_GEST_DETTAGLIO ADD IVA NUMERIC(2,0) NULL;
ALTER TABLE BOLL_GEST_DETTAGLIO ADD IMPORTO_TOTALE  NUMERIC(11,2) ;

UPDATE BOLL_GEST_DETTAGLIO SET IMPORTO_TOTALE=IMPORTO WHERE IMPORTO_TOTALE IS NULL;
ALTER TABLE BOLL_GEST_DETTAGLIO DROP COLUMN IMPORTO;

ALTER TABLE BOLL_GEST_DETTAGLIO MODIFY IMPORTO_TOTALE  NUMERIC(11,2) NOT NULL;
UPDATE BOLL_GEST_DETTAGLIO SET IVA=0 WHERE IVA IS NULL;

UPDATE BOLL_GEST_DETTAGLIO SET IMPORTO_SENZA_IVA=IMPORTO_TOTALE WHERE IMPORTO_SENZA_IVA IS NULL;

ALTER TABLE BOLL_GEST_DETTAGLIO MODIFY IMPORTO_SENZA_IVA  NUMERIC(11,2) NOT NULL ;

 
ALTER TABLE PAY_POSIZIONI_DEBITORIE ADD COLUMN DATA_CREAZIONE_FATTURA DATETIME NULL;
ALTER TABLE PAY_POSIZIONI_DEBITORIE ADD COLUMN DATA_INVIO_AVVISO DATETIME NULL;

ALTER TABLE STP_TIPOLOGIE_ENDO2 MODIFY DESCRIZIONE VARCHAR(250);

ALTER TABLE INVENTARIOPROCEDIMENTI MODIFY CODICEANCITEL VARCHAR(250);

ALTER TABLE STP_ENDO_TIPO1 MODIFY CODICE_ENDO_REGIONALE VARCHAR(250);


ALTER TABLE STP_ENDO_TIPO2 MODIFY CODICE_ENDO_REGIONALE VARCHAR(250);

ALTER TABLE BOLL_GEST_DETTAGLIO ADD FLAG_CONGUAGLIO NUMERIC(1,0) NOT NULL DEFAULT 0;

ALTER TABLE DECODIFICHE MODIFY RAGGRUPPAMENTO VARCHAR(200);





ALTER TABLE PAY_PROFILI_ENTI_CREDITORI MODIFY APPLICATION_CODE DECIMAL(4,0)  ;



ALTER TABLE DETT_POSIZIONE_DEBITORIA ADD IUV VARCHAR(100) ; 
ALTER TABLE DETT_POSIZIONE_DEBITORIA ADD CODICE_AVVISO VARCHAR(50) ; 
ALTER TABLE DETT_POSIZIONE_DEBITORIA ADD QRCODE VARCHAR(100) ;
ALTER TABLE DETT_POSIZIONE_DEBITORIA ADD IMPORTO_IVATO NUMERIC(10,2);
ALTER TABLE DETT_POSIZIONE_DEBITORIA ADD DATA_REGISTRAZIONE DATETIME;
ALTER TABLE DETT_POSIZIONE_DEBITORIA ADD DESCRIZIONE_CAUSALE VARCHAR(250);
ALTER TABLE DETT_POSIZIONE_DEBITORIA ADD CODICEANAGRAFE NUMERIC(6,0);

ALTER TABLE DETT_POSIZIONE_DEBITORIA ADD CONSTRAINT FK_DETTPOSDEB_ANAGRAFE FOREIGN KEY(IDCOMUNE,CODICEANAGRAFE) REFERENCES ANAGRAFE(IDCOMUNE, CODICEANAGRAFE);


CREATE TABLE MOVIMENTI_ZIP_LOGICO_TESTATA(IDCOMUNE VARCHAR(6) NOT NULL,CODICEMOVIMENTO DECIMAL(8,0) NOT NULL,GUID VARCHAR(60) NOT NULL,GUID_COLLEGATO VARCHAR(60)) ENGINE=INNODB DEFAULT CHARSET=UTF8;

ALTER TABLE MOVIMENTI_ZIP_LOGICO_TESTATA ADD CONSTRAINT MOVIMENTI_ZIP_LOGICO_TESTA_PK PRIMARY KEY (IDCOMUNE, CODICEMOVIMENTO);

ALTER TABLE MOVIMENTI_ZIP_LOGICO_TESTATA ADD CONSTRAINT MOVIMENTI_ZIP_LOGICO_TEST_FK1 FOREIGN KEY(IDCOMUNE, CODICEMOVIMENTO)REFERENCES MOVIMENTI(IDCOMUNE, CODICEMOVIMENTO);

ALTER TABLE PAY_DETTAGLIO_IMPORTI ADD COLUMN NUMERO_SOTTOACCERTAMENTO VARCHAR(35) NULL;


ALTER TABLE MERCATIPRESENZE_D DROP FOREIGN KEY  FK_PAYPOSDEB_SPUNT;
ALTER TABLE MERCATIPRESENZE_D MODIFY FK_PAY_POS_DEB NUMERIC(10,0);

ALTER TABLE BLACKLIST_SRC_P_DEB_SP DROP FOREIGN KEY  FK_BLSRCPOSDEB_POSDEB;
ALTER TABLE BLACKLIST_SRC_P_DEB_SP MODIFY FK_ID_PAYPOS_DEB NUMERIC(10,0);

ALTER TABLE BOLL_CFG_TIPO ADD cod_lett_accompagnamento  NUMERIC(10, 0);
ALTER TABLE BOLL_CFG_TIPO ADD constraint fk_bollcfgtipo_letttipo foreign key (idcomune,cod_lett_accompagnamento) references letteretipo(idcomune,codicelettera) ;


ALTER TABLE BOLL_GEST_TESTATA ADD DATA_SCADENZA DATETIME;
ALTER TABLE DETT_POSIZIONE_DEBITORIA ADD DATA_SCADENZA DATETIME;
 
ALTER TABLE LIVELLO_SERVIZIO ADD CONSTRAINT UC_LIVELLOSERVIZIO UNIQUE (IDCOMUNE,SEGNAPOSTO);

ALTER TABLE PAY_CONNECTOR_WS_ENDPOINT ADD COLUMN FLAG_SPEGNI_SCHEDULER DECIMAL(1,0) NULL COMMENT 'UTILE PER DISATTIVARE GLI SCHEDULER MANTENENDO MEMORIZZATA L''ESPRESSIONE CHE LO CONFIGURA IN QUARTZ_SCHEDULE';

ALTER TABLE CONTI ADD COLUMN NUMERO_SOTTO_ACCERTAMENTO VARCHAR(35);