ALTER TABLE ONERITIPIRATEIZZAZIONE ADD TIPOLOGIA_RATEIZZAZIONE VARCHAR(100);
ALTER TABLE TIPIMOV_STC_MAPPING MODIFY PROTOCOLLO_TIPODOCUMENTO VARCHAR(30);
ALTER TABLE ISTANZEPROCEDIMENTI ADD DESCRIZIONE_ENDOPROCEDIMENTO VARCHAR(1500);


ALTER TABLE istanzeprocure MODIFY FK_ANAG_PROC_STORICO NUMERIC(10,0);
ALTER TABLE istanzeprocure MODIFY FK_ANAG_RAPP_STORICO NUMERIC(10,0);
