package it.gruppoinit.pal.gp.core.ws.client;

/**
 * Please modify this class to meet your needs This class is not complete
 */
import it.gruppoinit.pal.gp.core.constants.WebConstants;
import it.gruppoinit.pal.gp.core.constants.WebConstants.SecurityParams;
import it.gruppoinit.pal.gp.core.dao.helper.ORMHelper;
import it.gruppoinit.pal.gp.core.exception.FunzioneBusinessRemotaException;
import it.gruppoinit.pal.gp.core.exception.InvalidConfigurationException;
import it.gruppoinit.pdfutils.schemas.messages.DatiPDFType;
import it.gruppoinit.pdfutils.schemas.messages.PDFFileType;
import it.gruppoinit.pdfutils.schemas.messages.RecuperaDatiDaPDFRequestType;
import it.gruppoinit.pdfutils.schemas.messages.RecuperaDatiDaPDFResponseType;
import it.gruppoinit.pdfutils.ws.definitions.PdfUtils;
import it.gruppoinit.pdfutils.ws.definitions.PdfUtilsService;
import it.init.sigepro.rte.types.CampoDinamicoType;
import it.init.sigepro.rte.types.CampoSchedaType;
import it.init.sigepro.rte.types.ElementoValoreCampoDinamicoType;
import it.init.sigepro.rte.types.SchedaType;
import it.init.sigepro.rte.types.ValoreCampoDinamicoType;

import java.net.URL;

import javax.activation.DataHandler;
import javax.xml.ws.soap.MTOMFeature;

import org.apache.commons.lang.StringUtils;
import org.apache.cxf.endpoint.Client;
import org.apache.cxf.frontend.ClientProxy;
import org.apache.cxf.transport.http.HTTPConduit;
import org.apache.cxf.transports.http.configuration.HTTPClientPolicy;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * This class was generated by Apache CXF 2.5.1 2014-02-17T09:13:02.524+01:00 Generated source version: 2.5.1
 * 
 */
public final class PdfUtilsWSClient extends BaseWsClient {

    // private static final QName SERVICE_NAME = new QName("http://gruppoinit.it/messages/pdfutils", "PdfUtilsService");
    private static final Logger log = LoggerFactory.getLogger(PdfUtilsWSClient.class);
    private String wsUrls = "";

    public PdfUtilsWSClient() {

	this.wsUrls = WebConstants.getSecurityParamValue(SecurityParams.WSHOSTURL_PDFUTILS);
    }

    public SchedaType leggiDatiDaPDF(String fileName, String identifier, DataHandler content) throws InvalidConfigurationException,
	    FunzioneBusinessRemotaException, Exception {

	SchedaType result = null;
	if (log.isDebugEnabled()) {
	    log.debug("leggiDatiDaPDF# recupero la porta di comunicazione");
	}
	PdfUtils port = getWsPort();
	if (port != null) {
	    if (log.isDebugEnabled()) {
		log.debug("leggiDatiDaPDF# creo la request filename:{}, id: {}", fileName, identifier);
	    }
	    RecuperaDatiDaPDFRequestType request = new RecuperaDatiDaPDFRequestType();
	    request.setToken(ORMHelper.getToken());
	    PDFFileType pdf = new PDFFileType();
	    pdf.setBinaryData(content);
	    pdf.setFileName(fileName);
	    pdf.setId(identifier);
	    request.setPdfFile(pdf);
	    if (log.isDebugEnabled()) {
		log.debug("leggiDatiDaPDF# invoco il metodo recuperaDatiDaPDF");
	    }
	    RecuperaDatiDaPDFResponseType response = port.recuperaDatiDaPDF(request);
	    if (log.isDebugEnabled()) {
		log.debug("leggiDatiDaPDF# chiamata al metodo recuperaDatiDaPDF effettuata correttamente");
	    }
	    if (response != null) {
		if (response.getDati() != null && response.getDati().size() > 0) {
		    boolean almenoUno = false;
		    result = new SchedaType();
		    for (DatiPDFType dato : response.getDati()) {
			if (StringUtils.isNotBlank(dato.getCodice())) {
			    if (!dato.getValore().isEmpty()) {
				if (log.isDebugEnabled()) {
				    log.debug("leggiDatiDaPDF# recuperato il dato codice: {}, valore: {}", dato.getCodice(), dato.getValore());
				}
				almenoUno = true;
				CampoSchedaType cs = new CampoSchedaType();
				CampoDinamicoType cd = new CampoDinamicoType();
				ValoreCampoDinamicoType vu = new ValoreCampoDinamicoType();
				vu.setNome(dato.getCodice());
				int i = 0;
				for (String valore : dato.getValore()) {
				    ElementoValoreCampoDinamicoType vp = new ElementoValoreCampoDinamicoType();
				    vp.setIndice(0);
				    vp.setIndiceMolteplicita(i);
				    vp.setCodice(valore);
				    vp.setDescrizione(valore);
				    vu.getValore().add(vp);
				    i++;
				}
				cd.setValoreUtente(vu);
				cs.setCampoDinamico(cd);
				result.getCampi().add(cs);
			    }
			}
		    }
		    if (!almenoUno) {
			return null;
		    }
		} else {
		    if (response.getErrori() != null && response.getErrori().size() > 0) {
			String errori = "";
			for (String err : response.getErrori()) {
			    errori += err;
			    if (!StringUtils.defaultIfEmpty(err, "").endsWith(".")) {
				errori += ". ";
			    }
			    errori += "\n";
			}
			throw new FunzioneBusinessRemotaException("Sono stati rilevati i seguenti errori nel recupero delle informazioni dal PDF "
				+ pdf.getFileName() + "(" + pdf.getId() + "): " + errori);
		    }
		}
	    } else {
		throw new InvalidConfigurationException("Non è stato possibile recuperare l'interfaccia a PDFUtils, getPort==nullo");
	    }
	}
	return result;
    }

    private PdfUtils getWsPort() throws InvalidConfigurationException, Exception {

	if (log.isDebugEnabled()) {
	    log.debug("getWsPort# recupero l'url {} da security", SecurityParams.WSHOSTURL_PDFUTILS);
	}
	if (log.isDebugEnabled()) {
	    log.debug("getWsPort# url recuperata: {}", this.wsUrls);
	}
	if (StringUtils.isBlank(this.wsUrls)) {
	    log.error("getWsPort# Non è stata configurata l'url {} sull'applicativo di security", SecurityParams.WSHOSTURL_PDFUTILS);
	    throw new InvalidConfigurationException("Non è stata configurata l'url " + SecurityParams.WSHOSTURL_PDFUTILS
		    + " sull'applicativo di security");
	}
	if (log.isDebugEnabled()) {
	    log.debug("getWsPort# istanzio il service");
	}
	PdfUtilsService client = new PdfUtilsService(new URL(this.wsUrls));
	MTOMFeature mtomFeature = new MTOMFeature(true, 0);
	if (log.isDebugEnabled()) {
	    log.debug("getWsPort# recupero la port");
	}
	PdfUtils port = client.getPdfUtilsPort(mtomFeature);
	Client proxy = ClientProxy.getClient(port);
	HTTPConduit conduit = (HTTPConduit) proxy.getConduit();
	HTTPClientPolicy httpClientPolicy = new HTTPClientPolicy(); // Line #1  
	httpClientPolicy.setConnectionTimeout(12000); // Line #2  
	httpClientPolicy.setReceiveTimeout(120000); // Line #3  
	conduit.setClient(httpClientPolicy);
	return port;
    }
}
