#lista degli attributi utente da recuperare nella request
fed.headers=UID,CF,NOME,COGNOME,NOMECOMPLETO,SESSO,MAIL,TEL,FAX,CELL,CITTA,REGIONE,INDIRIZZO,INDIRIZZO_NUM,CAP,NASCITA_GIORNO,NASCITA_MESE,NASCITA_ANNO,NATO_IN,NATO_PAESE,NATO_PROVINCIA,NATO_CITTA
#attributo che contiene la userid (sempre passato anche se non sovrascritto dal mapping)
fed.header.userid=UID
#prefisso da aggiungere ad ogni attributo prima di recuperarlo dalla request
fed.header.prefix=HTTP_
#se true allora il nome dell'attributo deve essere minuscolo prima di ricercarlo nella request
fed.header.lowercase=false
#attributo che assume il valore 'S' nel caso in cui l'utente abbia il ruolo di Cittadino Identificato 
authLevel=IDENTIFICATO
#lista degli attributi della request necessari per comporre la data di nascita nel formato gg/mm/aaaa
giornoNascita=NASCITA_GIORNO
meseNascita=NASCITA_MESE
annoNascita=NASCITA_ANNO
#lista degli attributi della request necessari per comporre l'indirizzo di residenza
indirizzoResidenzaVia=INDIRIZZO
indirizzoResidenzaNum=INDIRIZZO_NUM
#mapping (serve per specificare quali attributi passare e sovrascrivere il nome dell'aatributo da inviare tra quelli recuperati da fed)
#DATA_NASCITA e INDIRIZZO_RESIDENZA devono chiamarsi in questo modo anche se non presenti tra gli header fed, derivano dalla composizione.
NOME=Nome
COGNOME=Cognome
SESSO=Sesso
DATA_NASCITA=DataNascita
NATO_CITTA=ComuneNascita
CF=CodiceFiscale
MAIL=Email
INDIRIZZO_RESIDENZA=IndirizzoResidenza
CITTA=ComuneResidenza
UID=USERNAME
