#MAPPING DEI CAMPI DEL FRONTOFFICE MICROSOFT CON QUELLI DI FEDERA

#federaUserDomain
#lavoro
USERNAME=REDACTED
#lastname
#statoNascita
Sesso=sesso
Email=emailAddressPersonale
#provinciaResidenza
#statoResidenza
#DataNascita=dataNascita
Cellulare=cellulare
ComuneResidenza=comuneResidenza
CodiceFiscale=CodiceFiscale
ComuneNascita=luogoNascita
IndirizzoCorrispondenza=indirizzoDomicilio
CapCorrispondenza=capDomicilio
#provinciaNascita
Telefono=telefono
ComuneCorrispondenza=comuneDomicilio
Pec=emailAddress
CapResidenza=capResidenza
#titolo
#trustLevel
#firstname
LocalitaResidenza=cittaResidenza
Cognome=cognome
#provinciaDomicilio
#titoloStudio
IndirizzoResidenza=indirizzoResidenza
#policyLevel
Nome=nome
#statoDomicilio
CittaCorrispondenza=cittaDomicilio

url.logout=https://suape.regione.umbria.it/LoginUmbriaAG/logout
