#serviceURLPrefix=/
#samlAuthnMethod=urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport
samlAuthnMethod=urn:oasis:names:tc:SAML:2.0:ac:classes:SecureRemotePassword
#samlAuthnMethod=urn:oasis:names:tc:SAML:2.0:ac:classes:Smartcard
AdviceAttributeName=authenticationAssertion
MappingAssertionSubjectNameQualifier=https://login.regione.umbria.it/gw/metadata#mappingAssertion
MappingAttributeIssuerID=attributeIssuerID
MappingAttributeDestinationID=attributeDestinationID
MappingAttributeIssuerAttributeName=attributeNameAtIssuer
MappingAttributeDestinationAttributeName=attributeNameAtDestination
