ALTER TABLE ALBEROPROC ADD LDP_DOL_QSTRING VARCHAR2(100);
COMMENT ON COLUMN ALBEROPROC.LDP_DOL_QSTRING IS 'NELLA DOMANDA ONLINE ALLA QUERYSTRING DELLO STEP CHE REDIRIGE L''UTENTE AL SIT LDP VENGONO ACCODATI QUESTI PARAMETRI';
