<?xml version="1.0" encoding="UTF-8"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="modelloDatiDomanda" type="modelloDatiDomandaType "/>

	<xs:complexType name="modelloDatiDomandaType">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="idSemantico" type="idSemanticoType"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="idSemanticoType">
		<xs:sequence>
			<xs:element name="dato" type="datoType" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="nome" type="xs:string" use="required"/>
	</xs:complexType>

	<xs:complexType name="datoType">
		<xs:attribute name="valore" type="xs:string"/>
	</xs:complexType>

</xs:schema>
