ALTER TABLE tipimovimento ADD FLAG_SOGGETTI_MOVIMENTO NUMBER(1,0);

UPDATE verticalizzazioniparametribase SET DESCRIZIONE='(OBSOLETO vedi http://devel3.init.gruppoinit.it/vbg-docs/configurazione/area-riservata/visura/) '||DESCRIZIONE where modulo='AREA_RISERVATA' AND PARAMETRO IN ( 'VIS_FIL_CERCA_AZIENDA','VIS_FIL_CERCA_PARTITAIVA','VIS_FIL_CERCA_RICHIEDENTE','VIS_FIL_CERCA_SOGG_COLL','VIS_FIL_CERCA_TECNICO','VIS_NT_CERCA_AZIENDA','VIS_NT_CERCA_PARTITAIVA','VIS_NT_CERCA_RICHIEDENTE','VIS_NT_CERCA_SOGG_COLL','VIS_NT_CERCA_TECNICO','VIS_T_CERCA_AZIENDA','VIS_T_CERCA_PARTITAIVA','VIS_T_CERCA_RICHIEDENTE','VIS_T_CERCA_SOGG_COLL','VIS_T_CERCA_TECNICO' ) ;

ALTER TABLE pay_stato_pagamenti ADD STATO_PAGAMENTO_NATIVO VARCHAR2(50);