CREATE TABLE FO_QUESTIONARIO_GRADIMENTO (
    IDCOMUNE VARCHAR(6) NOT NULL,
    ID DECIMAL(10,0) NOT NULL,
    fk_codiceistanza DECIMAL(6,0) NOT NULL,
    valutazione DECIMAL(1,0) NOT NULL,
    note VARCHAR(4000),
    DATA DATETIME NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

ALTER TABLE FO_QUESTIONARIO_GRADIMENTO
  ADD CONSTRAINT fo_quest_pk PRIMARY KEY (
    idcomune,
    id
  );

ALTER TABLE FO_QUESTIONARIO_GRADIMENTO
  ADD CONSTRAINT fk_quest_istanze FOREIGN KEY (
    idcomune,
    fk_codiceistanza
  ) REFERENCES istanze (
    idcomune,
    codiceistanza
  );

  ALTER TABLE DOCUMENTIISTANZA MODIFY ID_BASE VARCHAR(200);