#parametri timeout delle chiamate WS
ws.timeout=300000

## parametri per comunicazione con STC
stcWsUrl=REDACTED
stcMtomEnabled=true
nlaUserId=NLA-PDD-RI
nlaPassword=REDACTED
idNodo=2100

## PARAMETRI CONFIGURAZIONE OGGETTI SERVICE WS
oggetti.ws.mtom.enabled=true
oggetti.ws.path.to.wsdl=/services/oggetti?wsdl
oggetti.ws.attach.logging.interceptors=true

## PARAMETRI CONFIGURAZIONE MOVIMENTI SERVICE WS
movimenti.ws.path.to.wsdl=/services/movimenti?wsdl

## parametri per comunicazione con Sigepro Security
ws.token.pwd=REDACTED
ws.token.url=REDACTED
ws.token.user=REDACTED

####### PORTA DELEGATA DECORATOR
####### NEL CASO DI INVOCAZIONE DELLA PORTA DELEGATA DEL FRIULI VENEZIA GIULIA (INSIEL = INSIEL_DECORATOR)
####### DEVONO ESSERE INVIATI DEGLI HEADER PER L'INSTRADAMENTO DEL MESSAGGIO
pdd.ri.ws.decorator=

########## PARAMETRI DI CONFIGURAZIONE DELLA PDD
########## ProtocolloSUAP
########## Attenzione!!! le proprietà sono sovrascrivibili per idcomunealias aggiungendo in calce al nome della property l'idcomunealias
########## ES: per personalizzare pdd.ri.ws.dettaglio.url per l'alias E256 la property va chiamata pdd.ri.ws.dettaglio.url.E256 
pdd.ri.ws.dettaglio.url=REDACTED
pdd.ri.ws.dettaglio.mtom.enabled=true
pdd.ri.ws.dettaglio.visura.pdf=true
pdd.ri.ws.dettaglio.visura.xml=false
pdd.ri.ws.dettaglio.auth.useauthentication=true
pdd.ri.ws.dettaglio.auth.username=REDACTED
pdd.ri.ws.dettaglio.auth.pwd=REDACTED
pdd.ri.ws.dettaglio.auth.tipo=BASIC_AUTHENTICATION
pdd.ri.ws.dettaglio.ws.comunicazione.std=true


########## RichiestaIscrizioneImpresaRiSPC
########## Attenzione!!! le proprietà sono sovrascrivibili per idcomunealias aggiungendo in calce al nome della property l'idcomunealias
########## ES: per personalizzare pdd.ri.ws.iscrizione.url per l'alias E256 la property va chiamata pdd.ri.ws.iscrizione.url.E256
pdd.ri.ws.iscrizione.url=REDACTED
pdd.ri.ws.iscrizione.mtom.enabled=true
pdd.ri.ws.iscrizione.auth.useauthentication=true
pdd.ri.ws.iscrizione.auth.username=REDACTED
pdd.ri.ws.iscrizione.auth.pwd=REDACTED
pdd.ri.ws.iscrizione.auth.tipo=BASIC_AUTHENTICATION

#########################################  CONFIGURAZIONE PER UN EVENTUALE COMPONENTE DI SCHEDULAZIONE QUARZ  #########################
######################################################################################################################################

## schedulazione
##false=disabilitata, true=abilitata
#scheduler.enable=false
##tipo cron, simple
#scheduler.type=cron
#espressione per tipo cron (Seconds,Minutes,Hours,Day of month,Month,Day of week,Year)
#scheduler.cron.expression=0 0 8-18 * * ?
#valori per tipo simple (millis)
#scheduler.simple.startDelay=120000
#scheduler.simple.repeatInterval=120000
