<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:sch="http://gruppoinit.it/sigepro/schemas/messages/albopretorio" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:tns="http://gruppoinit.it/sigepro/definitions/albopretorio" targetNamespace="http://gruppoinit.it/sigepro/definitions/albopretorio">
	<wsdl:types>
		<schema xmlns="http://www.w3.org/2001/XMLSchema">
			<import namespace="http://gruppoinit.it/sigepro/schemas/messages/albopretorio" schemaLocation="alboPretorio.xsd" />
		</schema>
	</wsdl:types>
	<wsdl:message name="ListaPubblicazioniFiltriResponse">
		<wsdl:part element="sch:ListaPubblicazioniFiltriResponse" name="ListaPubblicazioniFiltriResponse" />
	</wsdl:message>
	<wsdl:message name="ScaricaAllegatoPubblicazioneRequest">
		<wsdl:part element="sch:ScaricaAllegatoPubblicazioneRequest" name="ScaricaAllegatoPubblicazioneRequest" />
	</wsdl:message>
	<wsdl:message name="DettaglioPubblicazioneRequest">
		<wsdl:part element="sch:DettaglioPubblicazioneRequest" name="DettaglioPubblicazioneRequest" />
	</wsdl:message>
	<wsdl:message name="DettaglioPubblicazioneResponse">
		<wsdl:part element="sch:DettaglioPubblicazioneResponse" name="DettaglioPubblicazioneResponse" />
	</wsdl:message>
	<wsdl:message name="ListaPubblicazioniMaxRequest">
		<wsdl:part element="sch:ListaPubblicazioniMaxRequest" name="ListaPubblicazioniMaxRequest" />
	</wsdl:message>
	<wsdl:message name="PubblicazioniValideAlRequest">
		<wsdl:part element="sch:PubblicazioniValideAlRequest" name="PubblicazioniValideAlRequest" />
	</wsdl:message>
	<wsdl:message name="ListaPubblicazioniMaxResponse">
		<wsdl:part element="sch:ListaPubblicazioniMaxResponse" name="ListaPubblicazioniMaxResponse" />
	</wsdl:message>
	<wsdl:message name="PubblicazioniValideAlResponse">
		<wsdl:part element="sch:PubblicazioniValideAlResponse" name="PubblicazioniValideAlResponse" />
	</wsdl:message>
	<wsdl:message name="ListaPubblicazioniTotResponse">
		<wsdl:part element="sch:ListaPubblicazioniTotResponse" name="ListaPubblicazioniTotResponse" />
	</wsdl:message>
	<wsdl:message name="ListaPubblicazioniTotRequest">
		<wsdl:part element="sch:ListaPubblicazioniTotRequest" name="ListaPubblicazioniTotRequest" />
	</wsdl:message>
	<wsdl:message name="ScaricaAllegatoPubblicazioneResponse">
		<wsdl:part element="sch:ScaricaAllegatoPubblicazioneResponse" name="ScaricaAllegatoPubblicazioneResponse" />
	</wsdl:message>
	<wsdl:message name="ListaCategorieRequest">
		<wsdl:part element="sch:ListaCategorieRequest" name="ListaCategorieRequest" />
	</wsdl:message>
	<wsdl:message name="ListaCategorieResponse">
		<wsdl:part element="sch:ListaCategorieResponse" name="ListaCategorieResponse" />
	</wsdl:message>
	<wsdl:message name="ListaPubblicazioniFiltriRequest">
		<wsdl:part element="sch:ListaPubblicazioniFiltriRequest" name="ListaPubblicazioniFiltriRequest" />
	</wsdl:message>
	<wsdl:portType name="AlboPretorio">
		<wsdl:operation name="DettaglioPubblicazione">
			<wsdl:input message="tns:DettaglioPubblicazioneRequest" name="DettaglioPubblicazioneRequest" />
			<wsdl:output message="tns:DettaglioPubblicazioneResponse" name="DettaglioPubblicazioneResponse" />
		</wsdl:operation>
		<wsdl:operation name="ListaCategorie">
			<wsdl:input message="tns:ListaCategorieRequest" name="ListaCategorieRequest" />
			<wsdl:output message="tns:ListaCategorieResponse" name="ListaCategorieResponse" />
		</wsdl:operation>
		<wsdl:operation name="PubblicazioniValideAl">
			<wsdl:input message="tns:PubblicazioniValideAlRequest" name="PubblicazioniValideAlRequest" />
			<wsdl:output message="tns:PubblicazioniValideAlResponse" name="PubblicazioniValideAlResponse" />
		</wsdl:operation>
		<wsdl:operation name="ScaricaAllegatoPubblicazione">
			<wsdl:input message="tns:ScaricaAllegatoPubblicazioneRequest" name="ScaricaAllegatoPubblicazioneRequest" />
			<wsdl:output message="tns:ScaricaAllegatoPubblicazioneResponse" name="ScaricaAllegatoPubblicazioneResponse" />
		</wsdl:operation>
		<wsdl:operation name="ListaPubblicazioniMax">
			<wsdl:input message="tns:ListaPubblicazioniMaxRequest" name="ListaPubblicazioniMaxRequest" />
			<wsdl:output message="tns:ListaPubblicazioniMaxResponse" name="ListaPubblicazioniMaxResponse" />
		</wsdl:operation>
		<wsdl:operation name="ListaPubblicazioniFiltri">
			<wsdl:input message="tns:ListaPubblicazioniFiltriRequest" name="ListaPubblicazioniFiltriRequest" />
			<wsdl:output message="tns:ListaPubblicazioniFiltriResponse" name="ListaPubblicazioniFiltriResponse" />
		</wsdl:operation>
		<wsdl:operation name="ListaPubblicazioniTot">
			<wsdl:input message="tns:ListaPubblicazioniTotRequest" name="ListaPubblicazioniTotRequest" />
			<wsdl:output message="tns:ListaPubblicazioniTotResponse" name="ListaPubblicazioniTotResponse" />
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="AlboPretorioSoap11" type="tns:AlboPretorio">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="DettaglioPubblicazione">
			<soap:operation soapAction="dettaglioPubblicazione" />
			<wsdl:input name="DettaglioPubblicazioneRequest">
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output name="DettaglioPubblicazioneResponse">
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="ListaCategorie">
			<soap:operation soapAction="listaCategorie" />
			<wsdl:input name="ListaCategorieRequest">
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output name="ListaCategorieResponse">
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="PubblicazioniValideAl">
			<soap:operation soapAction="listaPubblicazioniValideAl" />
			<wsdl:input name="PubblicazioniValideAlRequest">
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output name="PubblicazioniValideAlResponse">
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="ScaricaAllegatoPubblicazione">
			<soap:operation soapAction="scaricaAllegatoPubblicazione" />
			<wsdl:input name="ScaricaAllegatoPubblicazioneRequest">
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output name="ScaricaAllegatoPubblicazioneResponse">
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="ListaPubblicazioniMax">
			<soap:operation soapAction="listaPubblicazioniMax" />
			<wsdl:input name="ListaPubblicazioniMaxRequest">
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output name="ListaPubblicazioniMaxResponse">
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="ListaPubblicazioniFiltri">
			<soap:operation soapAction="listaPubblicazioniFiltri" />
			<wsdl:input name="ListaPubblicazioniFiltriRequest">
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output name="ListaPubblicazioniFiltriResponse">
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="ListaPubblicazioniTot">
			<soap:operation soapAction="listaPubblicazioniTot" />
			<wsdl:input name="ListaPubblicazioniTotRequest">
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output name="ListaPubblicazioniTotResponse">
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="AlboPretorioService">
		<wsdl:port binding="tns:AlboPretorioSoap11" name="AlboPretorioSoap11">
			<soap:address location="http://devel9:8080/vbg/services/" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>