<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:sch="http://gruppoinit.it/nlapec" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://gruppoinit.it/nlapec" targetNamespace="http://gruppoinit.it/nlapec">
  <wsdl:types>
	<schema xmlns="http://www.w3.org/2001/XMLSchema">
		<import namespace="http://gruppoinit.it/nlapec" schemaLocation="WsNlaPec.xsd" />
	</schema>
   
  </wsdl:types>
  <wsdl:message name="MessaggiNonLettiResponse">
    <wsdl:part element="tns:MessaggiNonLettiResponse" name="MessaggiNonLettiResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="SetFlagLetturaMessaggioResponse">
    <wsdl:part element="tns:SetFlagLetturaMessaggioResponse" name="SetFlagLetturaMessaggioResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="MessaggiNonLettiRequest">
    <wsdl:part element="tns:MessaggiNonLettiRequest" name="MessaggiNonLettiRequest">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="ProcessaMessaggiResponse">
    <wsdl:part element="tns:ProcessaMessaggiResponse" name="ProcessaMessaggiResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="ListaMessaggiRequest">
    <wsdl:part element="tns:ListaMessaggiRequest" name="ListaMessaggiRequest">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="ScaricaMessaggioBinarioRequest">
    <wsdl:part element="tns:ScaricaMessaggioBinarioRequest" name="ScaricaMessaggioBinarioRequest">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="SetFlagLetturaMessaggioRequest">
    <wsdl:part element="tns:SetFlagLetturaMessaggioRequest" name="SetFlagLetturaMessaggioRequest">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="ScaricaMessaggioBinarioResponse">
    <wsdl:part element="tns:ScaricaMessaggioBinarioResponse" name="ScaricaMessaggioBinarioResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="ProcessaMessaggiRequest">
    <wsdl:part element="tns:ProcessaMessaggiRequest" name="ProcessaMessaggiRequest">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="ScaricaAllegatiMessaggioResponse">
    <wsdl:part element="tns:ScaricaAllegatiMessaggioResponse" name="ScaricaAllegatiMessaggioResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="ScaricaAllegatiMessaggioRequest">
    <wsdl:part element="tns:ScaricaAllegatiMessaggioRequest" name="ScaricaAllegatiMessaggioRequest">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="ListaMessaggiResponse">
    <wsdl:part element="tns:ListaMessaggiResponse" name="ListaMessaggiResponse">
    </wsdl:part>
  </wsdl:message>
  <!-- Message scarica messagio inviato binario -->
  <wsdl:message name="ScaricaMessaggioInviatoBinarioRequest">
    <wsdl:part element="tns:ScaricaMessaggioInviatoBinarioRequest" name="ScaricaMessaggioInviatoBinarioRequest">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="ScaricaMessaggioInviatoBinarioResponse">
    <wsdl:part element="tns:ScaricaMessaggioInviatoBinarioResponse" name="ScaricaMessaggioInviatoBinarioResponse">
    </wsdl:part>
  </wsdl:message>
  
  <wsdl:portType name="NlaGestioneMail">
    <wsdl:operation name="ScaricaMessaggioBinario">
      <wsdl:input message="tns:ScaricaMessaggioBinarioRequest" name="ScaricaMessaggioBinarioRequest">
    </wsdl:input>
      <wsdl:output message="tns:ScaricaMessaggioBinarioResponse" name="ScaricaMessaggioBinarioResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="ScaricaAllegatiMessaggio">
      <wsdl:input message="tns:ScaricaAllegatiMessaggioRequest" name="ScaricaAllegatiMessaggioRequest">
    </wsdl:input>
      <wsdl:output message="tns:ScaricaAllegatiMessaggioResponse" name="ScaricaAllegatiMessaggioResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="ListaMessaggi">
      <wsdl:input message="tns:ListaMessaggiRequest" name="ListaMessaggiRequest">
    </wsdl:input>
      <wsdl:output message="tns:ListaMessaggiResponse" name="ListaMessaggiResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="SetFlagLetturaMessaggio">
      <wsdl:input message="tns:SetFlagLetturaMessaggioRequest" name="SetFlagLetturaMessaggioRequest">
    </wsdl:input>
      <wsdl:output message="tns:SetFlagLetturaMessaggioResponse" name="SetFlagLetturaMessaggioResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="ProcessaMessaggi">
      <wsdl:input message="tns:ProcessaMessaggiRequest" name="ProcessaMessaggiRequest">
    </wsdl:input>
      <wsdl:output message="tns:ProcessaMessaggiResponse" name="ProcessaMessaggiResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="MessaggiNonLetti">
      <wsdl:input message="tns:MessaggiNonLettiRequest" name="MessaggiNonLettiRequest">
    </wsdl:input>
      <wsdl:output message="tns:MessaggiNonLettiResponse" name="MessaggiNonLettiResponse">
    </wsdl:output>
    </wsdl:operation>
    <!-- Operation scarica messagio inviato binario -->
    <wsdl:operation name="ScaricaMessaggioInviatoBinario">
      <wsdl:input message="tns:ScaricaMessaggioInviatoBinarioRequest" name="ScaricaMessaggioInviatoBinarioRequest">
    </wsdl:input>
      <wsdl:output message="tns:ScaricaMessaggioInviatoBinarioResponse" name="ScaricaMessaggioInviatoBinarioResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="NlaGestioneMailSoap11" type="tns:NlaGestioneMail">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="ScaricaMessaggioBinario">
      <soap:operation soapAction=""/>
      <wsdl:input name="ScaricaMessaggioBinarioRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="ScaricaMessaggioBinarioResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="ScaricaAllegatiMessaggio">
      <soap:operation soapAction=""/>
      <wsdl:input name="ScaricaAllegatiMessaggioRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="ScaricaAllegatiMessaggioResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="ListaMessaggi">
      <soap:operation soapAction=""/>
      <wsdl:input name="ListaMessaggiRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="ListaMessaggiResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="SetFlagLetturaMessaggio">
      <soap:operation soapAction=""/>
      <wsdl:input name="SetFlagLetturaMessaggioRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="SetFlagLetturaMessaggioResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="ProcessaMessaggi">
      <soap:operation soapAction=""/>
      <wsdl:input name="ProcessaMessaggiRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="ProcessaMessaggiResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="MessaggiNonLetti">
      <soap:operation soapAction=""/>
      <wsdl:input name="MessaggiNonLettiRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="MessaggiNonLettiResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <!-- Operation scarica messagio inviato binario -->
    <wsdl:operation name="ScaricaMessaggioInviatoBinario">
      <soap:operation soapAction=""/>
      <wsdl:input name="ScaricaMessaggioInviatoBinarioRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="ScaricaMessaggioInviatoBinarioResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="NlaGestioneMailService">
    <wsdl:port binding="tns:NlaGestioneMailSoap11" name="NlaGestioneMailSoap11">
      <soap:address location="http://devel9:8080/nla-pec/services"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>