ALTER TABLE responsabili ADD flag_dis_modanagrafe numeric(1,0) DEFAULT '0';
ALTER TABLE responsabili ADD CIRCOSCRIZIONE VARCHAR(50) DEFAULT NULL;

  ALTER TABLE anagrafe ADD DATA_INIZIO_ATTIVITA DATETIME DEFAULT NULL;
ALTER TABLE anagrafestorico ADD DATA_INIZIO_ATTIVITA DATETIME DEFAULT NULL;

ALTER TABLE configurazione ADD RESPONSABILE_TRATTAMENTO VARCHAR(4000) DEFAULT NULL;
ALTER TABLE configurazione ADD DATA_PROTECTION_OFFICER VARCHAR(4000) DEFAULT NULL;
ALTER TABLE configurazione ADD PROGRESSIVO_REGISTRI_AUT VARCHAR(35) DEFAULT NULL;

ALTER TABLE responsabili ADD flag_dis_modanagrafe numeric(1,0) DEFAULT '0';
ALTER TABLE responsabili ADD CIRCOSCRIZIONE VARCHAR(50) DEFAULT NULL;

ALTER TABLE configurazione ADD RESPONSABILE_TRATTAMENTO VARCHAR(4000) DEFAULT NULL;
ALTER TABLE configurazione ADD DATA_PROTECTION_OFFICER VARCHAR(4000) DEFAULT NULL;
ALTER TABLE configurazione ADD PROGRESSIVO_REGISTRI_AUT VARCHAR(35) DEFAULT NULL;

CREATE TABLE logsuap (
  ID numeric(9,0) NOT NULL,
  DATA VARCHAR(8) DEFAULT NULL,
  ORA VARCHAR(5) DEFAULT NULL,
  IP VARCHAR(15) DEFAULT NULL,
  OPERATORE VARCHAR(80) DEFAULT NULL,
  CODICERICHIESTA VARCHAR(20) DEFAULT NULL,
  CODICEERRORE VARCHAR(20) DEFAULT NULL,
  IDCOMUNE VARCHAR(6) NOT NULL,
  MESSAGGIO VARCHAR(4000) DEFAULT NULL,
  PRIMARY KEY (IDCOMUNE,ID),
  KEY IDX_LOGSUAP_001 (IDCOMUNE,CODICERICHIESTA),
  KEY IDX_LOGSUAP_002 (IDCOMUNE,DATA),
  KEY IDX_LOGSUAP_003 (IDCOMUNE,IP),
  KEY IDX_LOGSUAP_004 (IDCOMUNE,OPERATORE),
  KEY IDX_LOGSUAP_005 (IDCOMUNE,CODICEERRORE)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

ALTER TABLE SDEPROXY ADD WS_SERVIZI_CONSOLE VARCHAR(255);


