INSERT INTO MASTERKEY(TABLENAME, COLUMNNAME) VALUES ('INVENTARIOPROCEDIMENTOSOFTWARE', 'ID');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_IRIDE', 'WARNING_DA_ELIMINARE', 'Inserire in questo parametro la stringa che viene restituita dal web service in fase di protocollazione avvenuta correttamente. Iride restituisce infatti un messaggio anche in caso di protocollazione avvenuta correttamente, il messaggio viene successivamente inserito nei warning quindi va eliminata la stringa restituita in caso di protocollazione OK.');

UPDATE configurazioneutente SET valore = '100' WHERE valore='1000' AND nomeparametro ='NUMRECORDLISTE';

INSERT INTO FO_ARJ_STEPS_PARAMS_BASE (ID,CHIAVE,DESCRIZIONE,FK_FO_ARJ_STEP_BASE) VALUES (6,'OBBLIGATORIO_PF_TITOLO','Rende obbligatorio il campo titolo. Inserire il valore 1.','ANAGRAFE');
INSERT INTO FO_ARJ_STEPS_PARAMS_BASE (ID,CHIAVE,DESCRIZIONE,FK_FO_ARJ_STEP_BASE) VALUES (7,'OBBLIGATORIO_PF_CITTADINANZA','Rende obbligatorio il campo cittadinanza. Inserire il valore 1.','ANAGRAFE');
INSERT INTO FO_ARJ_STEPS_PARAMS_BASE (ID,CHIAVE,DESCRIZIONE,FK_FO_ARJ_STEP_BASE) VALUES (8,'OBBLIGATORIO_PF_RESIDENZA','Rende obbligatorio il campo residenza. Inserire il valore 1.','ANAGRAFE');
INSERT INTO FO_ARJ_STEPS_PARAMS_BASE (ID,CHIAVE,DESCRIZIONE,FK_FO_ARJ_STEP_BASE) VALUES (9,'OBBLIGATORIO_PF_EMAIL','Rende obbligatorio il campo email. Inserire il valore 1.','ANAGRAFE');
INSERT INTO FO_ARJ_STEPS_PARAMS_BASE (ID,CHIAVE,DESCRIZIONE,FK_FO_ARJ_STEP_BASE) VALUES (10,'OBBLIGATORIO_PF_PEC','Rende obbligatorio il campo pec. Inserire il valore 1.','ANAGRAFE');
INSERT INTO FO_ARJ_STEPS_PARAMS_BASE (ID,CHIAVE,DESCRIZIONE,FK_FO_ARJ_STEP_BASE) VALUES (11,'OBBLIGATORIO_PF_TEL','Rende obbligatorio il campo telefono. Inserire il valore 1.','ANAGRAFE');


INSERT INTO FO_ARJ_STEPS_PARAMS_BASE (ID,CHIAVE,DESCRIZIONE,FK_FO_ARJ_STEP_BASE) VALUES (12,'OBBLIGATORIO_PG_TEL','Rende obbligatorio il campo telefono. Inserire il valore 1.','ANAGRAFE');
INSERT INTO FO_ARJ_STEPS_PARAMS_BASE (ID,CHIAVE,DESCRIZIONE,FK_FO_ARJ_STEP_BASE) VALUES (13,'OBBLIGATORIO_PG_CCIAA','Rende obbligatorio il campo CCIAA. Inserire il valore 1.','ANAGRAFE');
INSERT INTO FO_ARJ_STEPS_PARAMS_BASE (ID,CHIAVE,DESCRIZIONE,FK_FO_ARJ_STEP_BASE) VALUES (14,'OBBLIGATORIO_PG_EMAIL','Rende obbligatorio il campo email. Inserire il valore 1.','ANAGRAFE');
INSERT INTO FO_ARJ_STEPS_PARAMS_BASE (ID,CHIAVE,DESCRIZIONE,FK_FO_ARJ_STEP_BASE) VALUES (15,'OBBLIGATORIO_PG_FAX','Rende obbligatorio il campo fax. Inserire il valore 1.','ANAGRAFE');
INSERT INTO FO_ARJ_STEPS_PARAMS_BASE (ID,CHIAVE,DESCRIZIONE,FK_FO_ARJ_STEP_BASE) VALUES (16,'OBBLIGATORIO_PG_IND_CORRISPONDENZA','Rende obbligatorio il campo indirizzo corrispondenza. Inserire il valore 1.','ANAGRAFE');
INSERT INTO FO_ARJ_STEPS_PARAMS_BASE (ID,CHIAVE,DESCRIZIONE,FK_FO_ARJ_STEP_BASE) VALUES (17,'OBBLIGATORIO_PG_NATURA_GIURIDICA','Rende obbligatorio il campo natura giuridica. Inserire il valore 1.','ANAGRAFE');
INSERT INTO FO_ARJ_STEPS_PARAMS_BASE (ID,CHIAVE,DESCRIZIONE,FK_FO_ARJ_STEP_BASE) VALUES (18,'OBBLIGATORIO_PG_PEC','Rende obbligatorio il campo pec. Inserire il valore 1.','ANAGRAFE');
INSERT INTO FO_ARJ_STEPS_PARAMS_BASE (ID,CHIAVE,DESCRIZIONE,FK_FO_ARJ_STEP_BASE) VALUES (19,'OBBLIGATORIO_PG_REA','Rende obbligatorio il campo REA. Inserire il valore 1.','ANAGRAFE');
INSERT INTO FO_ARJ_STEPS_PARAMS_BASE (ID,CHIAVE,DESCRIZIONE,FK_FO_ARJ_STEP_BASE) VALUES (20,'OBBLIGATORIO_PG_SEDE_LEGALE','Rende obbligatorio il campo sede legale. Inserire il valore 1.','ANAGRAFE');

INSERT INTO FO_ARJ_STEPS_PARAMS_BASE (ID,CHIAVE,DESCRIZIONE,FK_FO_ARJ_STEP_BASE) VALUES (21,'OBBLIGATORIO_VIA','Rende obbligatorio il campo via. Inserire il valore 1.','LOCALIZZAZIONE');
INSERT INTO FO_ARJ_STEPS_PARAMS_BASE (ID,CHIAVE,DESCRIZIONE,FK_FO_ARJ_STEP_BASE) VALUES (22,'OBBLIGATORIO_CIVICO','Rende obbligatorio il campo civico. Inserire il valore 1.','LOCALIZZAZIONE');

INSERT INTO FO_ARJ_STEPS_PARAMS_BASE (ID,CHIAVE,DESCRIZIONE,FK_FO_ARJ_STEP_BASE) VALUES (23,'OBBLIGATORIO_ESPONENTE','Rende obbligatorio il campo esponente. Inserire il valore 1.','LOCALIZZAZIONE');
INSERT INTO FO_ARJ_STEPS_PARAMS_BASE (ID,CHIAVE,DESCRIZIONE,FK_FO_ARJ_STEP_BASE) VALUES (24,'OBBLIGATORIO_SCALA','Rende obbligatorio il campo scala. Inserire il valore 1.','LOCALIZZAZIONE');
INSERT INTO FO_ARJ_STEPS_PARAMS_BASE (ID,CHIAVE,DESCRIZIONE,FK_FO_ARJ_STEP_BASE) VALUES (25,'OBBLIGATORIO_INTERNO','Rende obbligatorio il campo interno. Inserire il valore 1.','LOCALIZZAZIONE');
INSERT INTO FO_ARJ_STEPS_PARAMS_BASE (ID,CHIAVE,DESCRIZIONE,FK_FO_ARJ_STEP_BASE) VALUES (26,'OBBLIGATORIO_ESPONENTE_INTERNO','Rende obbligatorio il campo esponente interno. Inserire il valore 1.','LOCALIZZAZIONE');
INSERT INTO FO_ARJ_STEPS_PARAMS_BASE (ID,CHIAVE,DESCRIZIONE,FK_FO_ARJ_STEP_BASE) VALUES (27,'OBBLIGATORIO_PIANO','Rende obbligatorio il campo piano. Inserire il valore 1.','LOCALIZZAZIONE');
INSERT INTO FO_ARJ_STEPS_PARAMS_BASE (ID,CHIAVE,DESCRIZIONE,FK_FO_ARJ_STEP_BASE) VALUES (28,'OBBLIGATORIO_COLORE','Rende obbligatorio il campo colore. Inserire il valore 1.','LOCALIZZAZIONE');
INSERT INTO FO_ARJ_STEPS_PARAMS_BASE (ID,CHIAVE,DESCRIZIONE,FK_FO_ARJ_STEP_BASE) VALUES (29,'OBBLIGATORIO_FRAZIONE','Rende obbligatorio il campo frazione. Inserire il valore 1.','LOCALIZZAZIONE');
INSERT INTO FO_ARJ_STEPS_PARAMS_BASE (ID,CHIAVE,DESCRIZIONE,FK_FO_ARJ_STEP_BASE) VALUES (30,'OBBLIGATORIO_QUARTIERE','Rende obbligatorio il campo quartiere. Inserire il valore 1.','LOCALIZZAZIONE');
INSERT INTO FO_ARJ_STEPS_PARAMS_BASE (ID,CHIAVE,DESCRIZIONE,FK_FO_ARJ_STEP_BASE) VALUES (31,'OBBLIGATORIO_CIRCOSCRIZIONE','Rende obbligatorio il campo circoscrizione. Inserire il valore 1.','LOCALIZZAZIONE');
INSERT INTO FO_ARJ_STEPS_PARAMS_BASE (ID,CHIAVE,DESCRIZIONE,FK_FO_ARJ_STEP_BASE) VALUES (32,'OBBLIGATORIO_DATI_CATASTALI','Rende obbligatorio il campo dati catastali. Inserire il valore 1.','LOCALIZZAZIONE');

INSERT INTO FO_ARJ_STEPS_PARAMS_BASE (ID,CHIAVE,DESCRIZIONE,FK_FO_ARJ_STEP_BASE) VALUES (33,'INVIO_MAIL_A_RICHIEDENTE','Invia una mail al richiedente della pratica. Specificare il CODICE MAIL della mail tipo da utilizzare per l''invio.','INVIO');

update comuni set provincia='REGGIO CALABRIA' where codicecomune='B775';

INSERT INTO FO_ARJ_STEPS_PARAMS_BASE (ID,CHIAVE,DESCRIZIONE,FK_FO_ARJ_STEP_BASE) VALUES (34,'NASCONDI_DATI_ALBO','Nasconde la sezione relativa ai dati dell''albo dei professionisti. Inserire il valore 1.','ANAGRAFE');
INSERT INTO FO_ARJ_STEPS_PARAMS_BASE (ID,CHIAVE,DESCRIZIONE,FK_FO_ARJ_STEP_BASE) VALUES (35,'OBBLIGATORIO_PF_DATI_ALBO','Rende obbligatori i campi della sezioni DATI ALBO PROFESSIONISTI. Inserire il valore 1.','ANAGRAFE');
