#JDBC DRIVERS (composto da chiave [db.driver] + nome del provider su tabella comunisecurity [es. Oracle9i])
db.driver.Oracle=oracle.jdbc.OracleDriver
db.driver.Oracle9i=oracle.jdbc.OracleDriver
db.driver.Oracle10g=oracle.jdbc.OracleDriver
db.driver.MySql=com.mysql.jdbc.Driver
db.driver.MySqlInnoDB=com.mysql.jdbc.Driver
db.driver.MySqlMyISAM=com.mysql.jdbc.Driver
db.driver.PostgreSQL=org.postgresql.Driver
#db.driver.SQLServer=com.microsoft.jdbc.sqlserver.SQLServerDriver
#da utilizzare con i driver jdbc-2.0: sqljdbc4.jar(per JRE6) o sqljdbc.jar(per JRE5)
db.driver.SQLServer=com.microsoft.sqlserver.jdbc.SQLServerDriver
