# PARAMETRI PER COMUNICAZIONE CON STC (registrare il nodo in STC)
ws.stc.url=REDACTED
ws.stc.user=REDACTED
ws.stc.pwd=REDACTED

# PARAMETRO PER SOVRASCRIVERE L'URL DEL MAILSERVICE DA CONTATTARE
ws.mailservice.url=REDACTED

# PARAMETRI PER COMUNICAZIONE CON IBCSECURITY (registrare l'utente NLAPEC in ibcsecurity)
ws.token.url=REDACTED
ws.token.user=REDACTED
ws.token.pwd=REDACTED

###### TUTTI I PARAMETRI SEGUENTI SONO UTILIZZATI DAL PEC READER ##############

# PARAMETRI CASELLA PEC
#pec.host=mbox.cert.legalmail.it
#pec.protocol=pop3s
#pec.user=REDACTED
#pec.password=REDACTED

# PARAMETRO PER SALVATAGGIO TEMPORANEO DEGLI ALLEGATI
tmp.basePath=C:/Temp/

# IDCOMUNEALIAS PER LA PRIMA LOGIN A IBCSECURITY
ws.ibcsecurity.idcomunealias=E256

# PARAMETRI UTILIZZATI PER L'INSERIMENTO PRATICA SU STC
ws.stc.idEnteMittente=NLAPEC
ws.stc.idSportelloMittente=NLAPEC
ws.stc.idNodoMittente=800

# PARAMETRI UTILIZZATI DAL PECREADER (il PECSENDER utilizza quella della request)
ws.stc.idNodoDestinatario=400

# CONFIGURAZIONE PER IL COMPONENTE DI SCHEDULAZIONE QUARTZ
scheduler.cron.expression=0 00 01 * * ?

###### i successivi parametri per il momento non vengono utilizzati #########
ws.stc.idEnteDestinatario=
ws.stc.idSportelloDestinatario=
# CODICE COMUNE ASSOCIATO (SE IL BACKEND E' IN CONFIGURAZIONE COMUNI ASSOCIATI CORRISPONDE AL CODICECOMUNE ALTRIMENTI LASCIARE VUOTO) 
codice.comune.associato=
# PARAMETRI PER INVIO EMAIL DI RIEPILOGO
mail.host=
mail.from=
mail.to=
mail.cc=
mail.subject=
mail.text=
