#Comment out the Log4J listener in web.xml to activate Log4J.
log4j.rootLogger=WARN, logfile

log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d %p [%c] %nNLA-PEC - %m%n

log4j.appender.logfile=org.apache.log4j.RollingFileAppender
log4j.appender.logfile.File=${catalina.base}/logs/nla-pec.log
log4j.appender.logfile.MaxFileSize=4096KB
log4j.appender.logfile.MaxBackupIndex=5
log4j.appender.logfile.layout=org.apache.log4j.PatternLayout
log4j.appender.logfile.layout.ConversionPattern=%d %p [%c] - %m%n

log4j.logger.it.gruppoinit.nlapec.service.wsnlapec.GestoreCasellaMailWebService=INFO
log4j.logger.it.gruppoinit.nlapec.service=INFO
log4j.logger.it.gruppoinit.nlapec.util.RepairFI=INFO
log4j.logger.it.gruppoinit.nlapec.service.stc.StcWebServiceClient=WARN
log4j.logger.it.gruppoinit.nlapec.service.sigepro.SigeproWebServiceClient=WARN
log4j.logger.it.gruppoinit.nlapec.service.sigeprosecurity.SigeproSecurityWebServiceClient=WARN
log4j.logger.it.gruppoinit.nlapec.service.movimentimail.MovimentiMailWSClient=WARN
log4j.logger.it.gruppoinit.nlapec.service.PECReader.stcWebServiceClient=WARN
log4j.logger.it.gruppoinit.nlapec.dao.SigeproDAO=WARN
log4j.logger.org.springframework.web.servlet=WARN
log4j.logger.org.apache=WARN
log4j.logger.org.quartz=WARN
log4j.logger.org.springframework=WARN
log4j.logger.org.springframework.ws=WARN
log4j.logger.org.springframework.ws.server.endpoint.interceptor.PayloadLoggingInterceptor=ERROR
log4j.logger.org.springframework.ws.client.MessageTracing=ERROR
log4j.logger.org.springframework.ws.server.MessageTracing=ERROR
