spring.application.name=@project.name@
server.port=${ARUBA_SERVICE_PORT}
aruba.process-file-name=${ARUBA_PROCESS_FILE_NAME}
aruba.temp-path=${ARUBA_TEMP_PATH}
aruba.processati-path=${ARUBA_PROCESSATI_PATH}

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB

management.server.port=${ARUBA_MANAGEMENT_PORT}
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
