SET IMPLICIT_TRANSACTIONS ON
GO
CREATE INDEX IDX_LAYOUTTESTI_001 ON LAYOUTTESTI (IDCOMUNE, CODICETESTO)
GO
COMMIT
GO
CREATE INDEX IDX_LAYOUTTESTIBASE_001 ON LAYOUTTESTIBASE (CODICETESTO)
GO
COMMIT
GO
CREATE TABLE MASTERKEY (TableName Varchar(40) Not Null, ColumnName Varchar(40) Not Null)
GO
COMMIT
GO
Alter TABLE MASTERKEY ADD CONSTRAINT MASTERKEY_PK PRIMARY KEY (TableName ,COLUMNNAME)
GO
COMMIT
GO
Alter table LETTERETIPO alter column CODICELETTERA numeric(10)
GO
COMMIT
GO
Alter table TIPIDOCUMENTO alter column CODLETTERATIPO numeric(10)
GO
COMMIT
GO
Alter table TIPIMOVIMENTO alter column FK_LETTERETIPO numeric(10)
GO
COMMIT
GO
Alter table TIPIMOVIMENTODOCTIPO alter column CODICELETTERA numeric(10)
GO
COMMIT
GO
Alter table TIPIPROCEDURE alter column CODLETTAUORIZZATIVA numeric(10)
GO
COMMIT
GO
Alter table TIPICAUSALIONERI alter column CO_ID numeric(10)
GO
COMMIT
GO
Alter table INVENTARIOPROCEDIMENTIONERI alter column FK_COID numeric(10)
GO
COMMIT
GO
Alter table ISTANZELAVORI_D alter column FK_COID numeric(10)
GO
COMMIT
GO
Alter table LAVORITIPI_CAUSALIONERI alter column FK_COID numeric(10)
GO
COMMIT
GO
Alter table ISTANZEONERI alter column FKIDTIPOCAUSALE numeric(10)
GO
COMMIT
GO
Alter table O_CONFIGURAZIONETIPIONERE alter column FK_CO_ID numeric(10)
GO
COMMIT
GO
Alter table ALBEROPROC_ONERI alter column AO_FK_COID numeric(10)
GO
COMMIT
GO
Alter table TIPISOGGETTO alter column CODICETIPOSOGGETTO numeric(10,0)
GO
COMMIT
GO
Alter table ISTANZE alter column FKCODICESOGGETTO numeric(10,0)
GO
COMMIT
GO
Alter table ISTANZERICHIEDENTI alter column CODICETIPOSOGGETTO numeric(10,0)
GO
COMMIT
GO
Alter table TIPIMOVIMENTOONERI alter column FK_COID numeric(10)
GO
COMMIT
GO
CREATE TABLE SEGNAPOSTO
  (
    ID          NUMERIC(4,0)NOT NULL,
    TAG         VARCHAR(64) NOT NULL,
    DESCRIZIONE VARCHAR(64) NOT NULL,
    HELP        VARCHAR(4000)
  )
GO
COMMIT
GO
ALTER TABLE SEGNAPOSTO ADD CONSTRAINT SEGNAPOSTO_PK PRIMARY KEY (ID)
GO
COMMIT
GO
CREATE UNIQUE INDEX SEGNAPOSTO_IDX_001 ON SEGNAPOSTO(TAG)
GO
COMMIT
GO
ALTER TABLE DYN2_CAMPI_SCRIPT ALTER COLUMN FK_D2C_ID NUMERIC(10)
GO
COMMIT
GO
ALTER TABLE DYN2_MODELLI_SCRIPT ALTER COLUMN FK_D2MT_ID NUMERIC(10)
GO
COMMIT
GO
CREATE VIEW VW_MERCATIPRESENZETOTALI AS 
SELECT 'STORICO' AS ORIGINE, IDCOMUNE, ANNO, CODICEANAGRAFE, FK_AUTORIZZAZIONI_ID, FKCODICEMERCATO, FKIDMERCATIUSO, FK_IDPOSTEGGIO AS FKIDPOSTEGGIO, NUMEROPRESENZE FROM MERCATIPRESENZE_STORICO
UNION
SELECT 'CALENDARIO' AS ORIGINE, MERCATIPRESENZE_T.IDCOMUNE, MERCATIPRESENZE_T.ANNO, MERCATIPRESENZE_D.CODICEANAGRAFE, MERCATIPRESENZE_D.FK_AUTORIZZAZIONI_ID, MERCATIPRESENZE_T.FKCODICEMERCATO, MERCATIPRESENZE_T.FKIDMERCATIUSO, MERCATIPRESENZE_D.FKIDPOSTEGGIO, 1 AS NUMEROPRESENZE FROM MERCATIPRESENZE_D, MERCATIPRESENZE_T WHERE MERCATIPRESENZE_D.IDCOMUNE = MERCATIPRESENZE_T.IDCOMUNE AND MERCATIPRESENZE_D.FKIDTESTATA = MERCATIPRESENZE_T.ID AND MERCATIPRESENZE_D.CODICEANAGRAFE IS NOT NULL
GO
COMMIT
GO
ALTER TABLE BATCH_SCAD_ISTANZE DROP CONSTRAINT FK_BATCHSCADISTANZE_ISTANZE
GO
COMMIT
GO
ALTER TABLE MESSAGGICFGBASE ALTER COLUMN CORPO VARCHAR(4000) NULL
GO
COMMIT
GO
ALTER TABLE MESSAGGICFG ALTER COLUMN CORPO VARCHAR(4000) NULL
GO
COMMIT
GO
Alter Table Inventarioprocdyn2modellit ADD constraint FK_INV_DYN2MODT_DYN2MODELLIT FOREIGN KEY (IDCOMUNE, FK_D2MT_ID) REFERENCES DYN2_MODELLIT (IDCOMUNE, ID)
GO
COMMIT
GO
Alter Table Dyn2_Campiproprieta Add constraint Fk_Dyn2_Campiprop_Dyn2campi FOREIGN KEY (Idcomune, Fk_D2c_Id) References Dyn2_Campi (Idcomune, Id)
GO
COMMIT
GO
ALTER TABLE DYN2_CAMPI_SCRIPT ADD constraint FK_DYN2CAMPISCRIPT_DYN2CAMPI FOREIGN KEY  (IDCOMUNE, FK_D2C_ID) REFERENCES DYN2_CAMPI (IDCOMUNE, ID)
GO
COMMIT
GO
Alter Table Dyn2_Modelli_Script Add constraint Fk_Dyn2moscript_Dyn2modellit FOREIGN KEY  (Idcomune, Fk_D2mt_Id) References Dyn2_Modellit (Idcomune, Id)
GO
COMMIT
GO
ALTER TABLE TIPISOGGETTO ADD ORDINE NUMERIC(2,0)
GO
COMMIT
GO
ALTER TABLE FORMEGIURIDICHE ALTER COLUMN FORMAGIURIDICA VARCHAR(60)
GO
COMMIT
GO
ALTER TABLE F_DOMANDE ADD DM_NUM_PROT NUMERIC(7,0) 
GO
COMMIT
GO
ALTER TABLE F_DOMANDE ADD DM_DATA_PROT VARCHAR(8) 
GO
COMMIT
GO
ALTER TABLE ALBEROPROC ALTER COLUMN SC_PROTTIPODOCUMENTO VARCHAR(50)
GO
COMMIT
GO
ALTER TABLE CLMENU_JAVA ADD TIPO_FUNZIONALITA VARCHAR(1)
GO
COMMIT
GO
ALTER TABLE FO_DOMANDE ADD IDENTIFICATIVODOMANDA VARCHAR(50)
GO
COMMIT
GO
SELECT 'ATTENZIONE: Se si dovessero verificare errori durante la attivazione della chiave FK_DOMANDE_ANAGRAFE utilizzare il seguente script per bonificare i records ATTENZIONEATTENZIONE: lo script non elimina gli oggetti referenziati in fo_domande_oggetti,  eseguire questo passaggio a parte o lasciare gli oggetti nel db (potrebbero essere in uso in qualche istanza). Controllare il file WARNING1.TXT'  from NONESISTE
GO
COMMIT
GO
ALTER TABLE FO_DOMANDE ADD constraint FK_DOMANDE_ANAGRAFE FOREIGN KEY (IDCOMUNE, CODICEANAGRAFE) REFERENCES ANAGRAFE (IDCOMUNE, CODICEANAGRAFE)
GO
COMMIT
GO
SELECT 'ATTENZIONE Se si dovessero verificare errori durante la attivazione della chiave FK_DOMANDE_OGGETTI_DOMPADRE utilizzare il seguente script per bonificare i records ATTENZIONE lo script non elimina gli oggetti referenziati in fo_domande_oggetti,  eseguire questo passaggio a parte o lasciare gli oggetti nel db (potrebbero essere in uso in qualche istanza). Controllare il file WARNING2.TXT'  from NONESISTE
GO
COMMIT
GO
ALTER TABLE FO_DOMANDE_OGGETTI ADD constraint FK_DOMANDE_OGGETTI_DOMPADRE  FOREIGN KEY (IDCOMUNE, IDDOMANDA) REFERENCES FO_DOMANDE (IDCOMUNE, ID)
GO
COMMIT
GO
ALTER TABLE FO_SOTTOSCRIZIONI ADD constraint FO_SOTTOSCRIZIONI_DOMPADRE FOREIGN KEY  (IDCOMUNE, CODICEDOMANDA) REFERENCES FO_DOMANDE (IDCOMUNE, ID)
GO
COMMIT
GO
ALTER TABLE FO_MESSAGGI ADD constraint FO_MESSAGGI_DOMPADRE FOREIGN KEY (IDCOMUNE, CODICEDOMANDA) REFERENCES FO_DOMANDE (IDCOMUNE, ID)
GO
COMMIT
GO
ALTER TABLE MOVIMENTIMAIL ADD MESSAGE_ID VARCHAR(400)
GO
COMMIT
GO
ALTER TABLE MOVIMENTIMAIL ADD ID_PADRE NUMERIC(8,0)
GO
COMMIT
GO
ALTER TABLE MOVIMENTIMAIL ADD constraint FK_IDPADRE_ID FOREIGN KEY  (IDCOMUNE,ID_PADRE) REFERENCES MOVIMENTIMAIL(IDCOMUNE,ID)
GO
COMMIT
GO
ALTER TABLE MOVIMENTIMAIL ALTER COLUMN MITTENTE VARCHAR(200)
GO
COMMIT
GO
ALTER TABLE ISTANZESTRADARIO ADD constraint FK_ISTANZESTRADARIO_COLORE FOREIGN KEY (IDCOMUNE, COLORE) REFERENCES STRADARIOCOLORE (IDCOMUNE, CODICECOLORE)
GO
COMMIT
GO
ALTER TABLE ISTANZESTRADARIO ADD PIANO VARCHAR(50)
GO
COMMIT
GO
ALTER TABLE ISTANZESTRADARIO ADD QUARTIERE VARCHAR(50)
GO
COMMIT
GO
ALTER TABLE RAGGRUPPAMENTOCAUSALIONERI ALTER COLUMN  RCO_ID NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE TIPICAUSALIONERI ALTER COLUMN  FK_RCO_ID NUMERIC(10,0)
GO
COMMIT
GO
ALTER TABLE FO_DOMANDE ADD constraint FK_FO_DOMANDE_SOFTWARE FOREIGN KEY  (SOFTWARE) REFERENCES SOFTWARE (CODICE)
GO
COMMIT
GO
ALTER TABLE FO_MESSAGGI ADD constraint FK_FO_MESSAGGI_SOFTWARE  FOREIGN KEY  (SOFTWARE) REFERENCES SOFTWARE (CODICE)
GO
COMMIT
GO
alter table ISTANZEPROCEDIMENTI add TIPO_ATTO varchar(100)
GO
COMMIT
GO
alter table ISTANZEPROCEDIMENTI add RILASCIATO_DA varchar(100)
GO
COMMIT
GO
CREATE INDEX IDX_ISTANZECOLLEGATE_002 ON ISTANZECOLLEGATE (IDCOMUNE,CODICEISTANZA)
GO
COMMIT
GO
CREATE INDEX IDX_ISTANZECOLLEGATE_003 ON ISTANZECOLLEGATE (IDCOMUNE,CODICEISTANZACOLLEGATA)
GO
COMMIT
GO
DROP VIEW VW_FULL_ISTANZECOLLEGATE
GO
COMMIT
GO
CREATE VIEW VW_FULL_ISTANZECOLLEGATE (IDCOMUNE, PROGRESSIVO, CODICEISTANZA, ORDINE) AS SELECT IDCOMUNE, PROGRESSIVO, CODICEISTANZA, ORDINE FROM ISTANZECOLLEGATE GROUP BY IDCOMUNE, PROGRESSIVO, CODICEISTANZA, ORDINE UNION SELECT IDCOMUNE, PROGRESSIVO, CODICEISTANZACOLLEGATA, ORDINE FROM ISTANZECOLLEGATE GROUP BY IDCOMUNE, PROGRESSIVO, CODICEISTANZACOLLEGATA, ORDINE
GO
COMMIT
GO
ALTER TABLE ALLEGATI ADD FLAG_INSERIMENTO_AUT NUMERIC(1,0)
GO
COMMIT
GO
ALTER TABLE ALBEROPROC_DOCUMENTI ADD FLAG_INSERIMENTO_AUT NUMERIC(1,0)
GO
COMMIT
GO
CREATE INDEX IDX_DOMANDESTC_001 ON DOMANDESTC (IDCOMUNE,CODICESOFTWARE,NUMEROISTANZA)
GO
COMMIT
GO
alter table NATURAENDO ALTER COLUMN BINARIODIPENDENZE numeric(10)
GO
COMMIT
GO
DROP INDEX DYN2_MODELLIT.DYN2_MODELLIT_UK1
GO
COMMIT
GO
CREATE INDEX DYN2_MODELLIT_UK1 ON DYN2_MODELLIT (IDCOMUNE, SOFTWARE, CODICE_SCHEDA)
GO
COMMIT
GO
CREATE TABLE TIPIPROCEDURE_DYN2MODELLIT ( IDCOMUNE VARCHAR(6) NOT NULL, FK_CODICEPROCEDURA NUMERIC(10,0) NOT NULL, FK_D2MT_ID NUMERIC(10,0) NOT NULL, FLAG_PUBBLICA NUMERIC(1,0) NULL, FLAG_TIPOFIRMA NUMERIC(1,0) NULL, FLAG_FACOLTATIVA NUMERIC(1,0) NULL)
GO
COMMIT
GO
ALTER TABLE TIPIPROCEDURE_DYN2MODELLIT ADD CONSTRAINT TIPIPROCEDURE_DYN2MODELLIT_PK PRIMARY KEY ( IDCOMUNE, FK_CODICEPROCEDURA, FK_D2MT_ID )
GO
COMMIT
GO
ALTER TABLE TIPIPROCEDURE_DYN2MODELLIT ADD CONSTRAINT FK_TPD2MT_TPROC FOREIGN KEY ( IDCOMUNE, FK_CODICEPROCEDURA ) REFERENCES TIPIPROCEDURE ( IDCOMUNE, CODICEPROCEDURA )
GO
COMMIT
GO
ALTER TABLE TIPIPROCEDURE_DYN2MODELLIT ADD CONSTRAINT FK_TPD2MT_D2MT FOREIGN KEY ( IDCOMUNE, FK_D2MT_ID ) REFERENCES DYN2_MODELLIT ( IDCOMUNE, ID )
GO
COMMIT
GO
DROP VIEW VW_ISTANZECONCESSIONILISTA
GO
COMMIT
GO
CREATE VIEW VW_ISTANZECONCESSIONILISTA as SELECT 99999999 as PROGRESSIVO,AUTORIZZAZIONI.AUTORIZRESPONSABILE as CONC_AUTORIZRESPONSABILE,AUTORIZZAZIONI.IDCOMUNE,AUTORIZZAZIONI.FK_CAUSALE_ACQUISIZIONE as ICONC_CODICECAUSALE, isnull(AUTORIZZAZIONI.DATA_CESSAZIONE,CONVERT(DATETIME,'31/12/9999',103)) as DATA_STORICO, ISTANZE.SOFTWARE,ISTANZE.CODICEISTANZA as IST_CODICEISTANZA,ISTANZE.NUMEROISTANZA as IST_NUMEROISTANZA,ISTANZE.CODICERICHIEDENTE as IST_CODICERICHIEDENTE,AUTORIZZAZIONI.ID as CONC_ID,AUTORIZZAZIONI.AUTORIZNUMERO as CONC_NUMERO,AUTORIZZAZIONI.AUTORIZDATA as CONC_DATARILASCIO,AUTORIZZAZIONI.AUTORIZDATA as DATARILASCIO,AUTORIZZAZIONI.DATASCADENZA as CONC_DATASCADENZA,AUTORIZZAZIONI_CONCESSIONI.FK_TIPOCONCESSIONE as CONC_CODICETIPO,CONCESSIONITIPI.DESCRIZIONE as CONC_TIPO,AUTORIZZAZIONI_CONCESSIONI.STAGIONALEA as CONC_STAGIONALEA,AUTORIZZAZIONI_CONCESSIONI.STAGIONALEDA as CONC_STAGIONALEDA,AUTORIZZAZIONI.FLAG_ATTIVA as CONC_ATTIVA,AUTORIZZAZIONI.FK_CODICEANAGRAFE as CONC_CODICETITOLARE,''+TITOLARE.NOMINATIVO+' '+TITOLARE.NOME as CONC_TITOLARE,TITOLARE.CODICEFISCALE as CONC_TIT_CF,TITOLARE.PARTITAIVA as CONC_TIT_PIVA,TITOLARE.TIPOANAGRAFE as CONC_TIT_TIPOANAGRAFE,AUT_COLLEGATA.AUTORIZNUMERO as AUT_NUMERO,AUT_COLLEGATA.AUTORIZDATA as AUT_DATA,AUT_COLLEGATA.AUTORIZDATA,AUT_COLLEGATA.FKIDREGISTRO as AUT_CODREGISTRO,TIPOLOGIAREGISTRI.TR_DESCRIZIONE as AUT_REGISTRO,(''+IST_RICHIEDENTE.NOMINATIVO+' '+IST_RICHIEDENTE.NOME) as IST_NOMINATIVO,IST_RICHIEDENTE.TIPOANAGRAFE as IST_RIC_TIPOANAGRAFE,(''+IST_AZIENDA.NOMINATIVO+' '+IST_AZIENDA.NOME) asIST_NOMINATIVOAZIENDA,IST_AZIENDA.TIPOANAGRAFE as IST_AZI_TIPOANAGRAFE,IST_RICHIEDENTE.CODICEFISCALE as IST_CODICEFISCALE,IST_RICHIEDENTE.PARTITAIVA as IST_PARTITAIVA,CAUS_ATTUALE.DESCRIZIONE as ICONC_CAUSALE,AUTORIZZAZIONI.FK_CAUSALE_CESSAZIONE as ICONC_CODICECAUSALESTORICO,CAUS_STORICO.DESCRIZIONE as ICONC_CAUSALESTORICO,AUTORIZZAZIONI_CONCESSIONI.FK_CODICEMERCATO as CONC_IDMERCATO,MERCATI.DESCRIZIONE as CONC_MERCATO,MERCATI.ATTIVO as MERC_ATTIVO,AUTORIZZAZIONI_CONCESSIONI.FK_IDPOSTEGGIO as CONC_IDPOSTEGGIO,MERCATI_D.CODICEPOSTEGGIO as CONC_POSTEGGIO,MERCATI_D.LARGHEZZA as CONC_POS_LARGHEZZA,MERCATI_D.LUNGHEZZA as CONC_POS_LUNGHEZZA,MERCATI_D.SUPERFICIE as CONC_POS_SUPERFICIE,MERCATI_D.FKCODICETIPOSPAZIO as POST_IDTIPOSPAZIO,POSTEGGITIPOSPAZIO.TIPOSPAZIO as POST_TIPOSPAZIO,AUTORIZZAZIONI_CONCESSIONI.FK_IDMERCATIUSO as CONC_IDMERCATIUSO,MERCATI_USO.DESCRIZIONE as CONC_DESCRIZIONEUSO,MERCATI_USO.PESO as PESO_MERCATO,MERCATI_USO.FKCODICEUSO as MERC_IDUSO,MERCATI_D.FKCODICESTRADARIO as CONC_POS_CODICESTRADARIO FROM AUTORIZZAZIONI_CONCESSIONI LEFT OUTER JOIN AUTORIZZAZIONI AUT_COLLEGATA ON AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE=AUT_COLLEGATA.IDCOMUNE  AND AUTORIZZAZIONI_CONCESSIONI.FK_IDAUT_COLLEGATA=AUT_COLLEGATA.ID,AUTORIZZAZIONI LEFT OUTER JOIN TIPOLOGIAREGISTRI ON AUTORIZZAZIONI.IDCOMUNE=TIPOLOGIAREGISTRI.IDCOMUNE  AND AUTORIZZAZIONI.FKIDREGISTRO=TIPOLOGIAREGISTRI.TR_ID  LEFT OUTER JOIN CONCESSIONICAUSALI CAUS_STORICO ON AUTORIZZAZIONI.IDCOMUNE=CAUS_STORICO.IDCOMUNE  AND AUTORIZZAZIONI.FK_CAUSALE_CESSAZIONE=CAUS_STORICO.CODICECAUSALE,MERCATI_D LEFT OUTER JOIN POSTEGGITIPOSPAZIO ON MERCATI_D.IDCOMUNE=POSTEGGITIPOSPAZIO.IDCOMUNE  AND   MERCATI_D.FKCODICETIPOSPAZIO=POSTEGGITIPOSPAZIO.CODICE,ISTANZE LEFT OUTER JOIN ANAGRAFE IST_AZIENDA ON ISTANZE.IDCOMUNE=IST_AZIENDA.IDCOMUNE  AND ISTANZE.CODICETITOLARELEGALE=IST_AZIENDA.CODICEANAGRAFE,CONCESSIONITIPI,ANAGRAFE TITOLARE,CONCESSIONICAUSALI CAUS_ATTUALE,ANAGRAFE   IST_RICHIEDENTE,MERCATI,MERCATI_USO WHERE AUTORIZZAZIONI.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND AUTORIZZAZIONI.ID = AUTORIZZAZIONI_CONCESSIONI.FK_IDAUT_ATTUALE AND CONCESSIONITIPI.TIPOCONCESSIONE = AUTORIZZAZIONI_CONCESSIONI.FK_TIPOCONCESSIONE AND TITOLARE.IDCOMUNE =  AUTORIZZAZIONI.IDCOMUNE AND TITOLARE.CODICEANAGRAFE = AUTORIZZAZIONI.FK_CODICEANAGRAFE AND CAUS_ATTUALE.IDCOMUNE = AUTORIZZAZIONI.IDCOMUNE AND CAUS_ATTUALE.CODICECAUSALE = AUTORIZZAZIONI.FK_CAUSALE_ACQUISIZIONE AND ISTANZE.IDCOMUNE = AUTORIZZAZIONI.IDCOMUNE AND ISTANZE.CODICEISTANZA = AUTORIZZAZIONI.FKIDISTANZA AND IST_RICHIEDENTE.IDCOMUNE = ISTANZE.IDCOMUNE AND IST_RICHIEDENTE.CODICEANAGRAFE = ISTANZE.CODICERICHIEDENTE AND MERCATI.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND MERCATI.CODICEMERCATO = AUTORIZZAZIONI_CONCESSIONI.FK_CODICEMERCATO AND MERCATI_D.IDCOMUNE =   AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND MERCATI_D.IDPOSTEGGIO = AUTORIZZAZIONI_CONCESSIONI.FK_IDPOSTEGGIO AND MERCATI_USO.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND MERCATI_USO.ID =   AUTORIZZAZIONI_CONCESSIONI.FK_IDMERCATIUSO UNION SELECT AUTORIZZAZIONI_SUBENTRI.ID as PROGRESSIVO,AUTORIZZAZIONI_SUBENTRI.AUTORIZRESPONSABILE as CONC_AUTORIZRESPONSABILE,AUTORIZZAZIONI_SUBENTRI.IDCOMUNE,AUTORIZZAZIONI_SUBENTRI.FK_CAUSALE_ACQUISIZIONE as ICONC_CODICECAUSALE,AUTORIZZAZIONI_SUBENTRI.DATA_CESSAZIONE as DATA_STORICO,ISTANZE.SOFTWARE,ISTANZE.CODICEISTANZA as   IST_CODICEISTANZA,ISTANZE.NUMEROISTANZA as IST_NUMEROISTANZA,ISTANZE.CODICERICHIEDENTE as IST_CODICERICHIEDENTE,AUTORIZZAZIONI_SUBENTRI.FK_IDAUT_ATTUALE as CONC_ID,AUTORIZZAZIONI_SUBENTRI.AUTORIZNUMERO as CONC_NUMERO,AUTORIZZAZIONI_SUBENTRI.AUTORIZDATA as   CONC_DATARILASCIO,AUTORIZZAZIONI_SUBENTRI.AUTORIZDATA as DATARILASCIO,AUTORIZZAZIONI_SUBENTRI.DATASCADENZA as CONC_DATASCADENZA,AUTORIZZAZIONI_CONCESSIONI.FK_TIPOCONCESSIONE as CONC_CODICETIPO,CONCESSIONITIPI.DESCRIZIONE as CONC_TIPO,AUTORIZZAZIONI_CONCESSIONI.STAGIONALEA as   CONC_STAGIONALEA,AUTORIZZAZIONI_CONCESSIONI.STAGIONALEDA as CONC_STAGIONALEDA,0 as CONC_ATTIVA,AUTORIZZAZIONI_SUBENTRI.FK_CODICEANAGRAFE as CONC_CODICETITOLARE,(''+TITOLARE.NOMINATIVO+' '+TITOLARE.NOME) as   CONC_TITOLARE,TITOLARE.CODICEFISCALE as CONC_TIT_CF,TITOLARE.PARTITAIVA as CONC_TIT_PIVA,TITOLARE.TIPOANAGRAFE as CONC_TIT_TIPOANAGRAFE,AUT_COLLEGATA.AUTORIZNUMERO as AUT_NUMERO,AUT_COLLEGATA.AUTORIZDATA as AUT_DATA,AUT_COLLEGATA.AUTORIZDATA,AUT_COLLEGATA.FKIDREGISTRO as AUT_CODREGISTRO,TIPOLOGIAREGISTRI.TR_DESCRIZIONE as   AUT_REGISTRO,(''+IST_RICHIEDENTE.NOMINATIVO+' '+IST_RICHIEDENTE.NOME) as IST_NOMINATIVO,IST_RICHIEDENTE.TIPOANAGRAFE as IST_RIC_TIPOANAGRAFE,(''+IST_AZIENDA.NOMINATIVO+' '+IST_AZIENDA.NOME) as IST_NOMINATIVOAZIENDA,IST_AZIENDA.TIPOANAGRAFE as IST_AZI_TIPOANAGRAFE,IST_RICHIEDENTE.CODICEFISCALE as   IST_CODICEFISCALE,IST_RICHIEDENTE.PARTITAIVA as IST_PARTITAIVA,CAUS_ATTUALE.DESCRIZIONE as ICONC_CAUSALE,AUTORIZZAZIONI_SUBENTRI.FK_CAUSALE_CESSAZIONE as ICONC_CODICECAUSALESTORICO,CAUS_STORICO.DESCRIZIONE as   ICONC_CAUSALESTORICO,AUTORIZZAZIONI_CONCESSIONI.FK_CODICEMERCATO as CONC_IDMERCATO,MERCATI.DESCRIZIONE as CONC_MERCATO,MERCATI.ATTIVO as MERC_ATTIVO,AUTORIZZAZIONI_CONCESSIONI.FK_IDPOSTEGGIO as CONC_IDPOSTEGGIO,MERCATI_D.CODICEPOSTEGGIO as CONC_POSTEGGIO,MERCATI_D.LARGHEZZA as CONC_POS_LARGHEZZA,MERCATI_D.LUNGHEZZA as CONC_POS_LUNGHEZZA,MERCATI_D.SUPERFICIE as CONC_POS_SUPERFICIE,MERCATI_D.FKCODICETIPOSPAZIO as POST_IDTIPOSPAZIO,POSTEGGITIPOSPAZIO.TIPOSPAZIO as   POST_TIPOSPAZIO,AUTORIZZAZIONI_CONCESSIONI.FK_IDMERCATIUSO as CONC_IDMERCATIUSO,MERCATI_USO.DESCRIZIONE as CONC_DESCRIZIONEUSO,MERCATI_USO.PESO as PESO_MERCATO,MERCATI_USO.FKCODICEUSO as MERC_IDUSO,MERCATI_D.FKCODICESTRADARIO as CONC_POS_CODICESTRADARIO FROM AUTORIZZAZIONI_CONCESSIONI LEFT OUTER JOIN AUTORIZZAZIONI AUT_COLLEGATA ON   AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE=AUT_COLLEGATA.IDCOMUNE  AND AUTORIZZAZIONI_CONCESSIONI.FK_IDAUT_COLLEGATA=AUT_COLLEGATA.ID,AUTORIZZAZIONI_SUBENTRI LEFT OUTER JOIN TIPOLOGIAREGISTRI ON AUTORIZZAZIONI_SUBENTRI.IDCOMUNE=TIPOLOGIAREGISTRI.IDCOMUNE  AND AUTORIZZAZIONI_SUBENTRI.FKIDREGISTRO=TIPOLOGIAREGISTRI.TR_ID  LEFT OUTER JOIN CONCESSIONICAUSALI CAUS_STORICO ON   AUTORIZZAZIONI_SUBENTRI.IDCOMUNE=CAUS_STORICO.IDCOMUNE  AND AUTORIZZAZIONI_SUBENTRI.FK_CAUSALE_CESSAZIONE=CAUS_STORICO.CODICECAUSALE,MERCATI_D LEFT OUTER JOIN POSTEGGITIPOSPAZIO ON MERCATI_D.IDCOMUNE=POSTEGGITIPOSPAZIO.IDCOMUNE  AND   MERCATI_D.FKCODICETIPOSPAZIO=POSTEGGITIPOSPAZIO.CODICE,ISTANZE LEFT OUTER JOIN ANAGRAFE IST_AZIENDA ON ISTANZE.IDCOMUNE=IST_AZIENDA.IDCOMUNE  AND ISTANZE.CODICETITOLARELEGALE=IST_AZIENDA.CODICEANAGRAFE,CONCESSIONITIPI,ANAGRAFE TITOLARE,CONCESSIONICAUSALI CAUS_ATTUALE,ANAGRAFE   IST_RICHIEDENTE,MERCATI,MERCATI_USO WHERE AUTORIZZAZIONI_SUBENTRI.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND AUTORIZZAZIONI_SUBENTRI.FK_IDAUT_ATTUALE = AUTORIZZAZIONI_CONCESSIONI.FK_IDAUT_ATTUALE AND CONCESSIONITIPI.TIPOCONCESSIONE = AUTORIZZAZIONI_CONCESSIONI.FK_TIPOCONCESSIONE AND TITOLARE.IDCOMUNE = AUTORIZZAZIONI_SUBENTRI.IDCOMUNE AND TITOLARE.CODICEANAGRAFE = AUTORIZZAZIONI_SUBENTRI.FK_CODICEANAGRAFE AND CAUS_ATTUALE.IDCOMUNE = AUTORIZZAZIONI_SUBENTRI.IDCOMUNE AND CAUS_ATTUALE.CODICECAUSALE = AUTORIZZAZIONI_SUBENTRI.FK_CAUSALE_ACQUISIZIONE AND ISTANZE.IDCOMUNE = AUTORIZZAZIONI_SUBENTRI.IDCOMUNE AND ISTANZE.CODICEISTANZA =   AUTORIZZAZIONI_SUBENTRI.FKIDISTANZA AND IST_RICHIEDENTE.IDCOMUNE = ISTANZE.IDCOMUNE AND IST_RICHIEDENTE.CODICEANAGRAFE = ISTANZE.CODICERICHIEDENTE AND MERCATI.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND MERCATI.CODICEMERCATO = AUTORIZZAZIONI_CONCESSIONI.FK_CODICEMERCATO AND MERCATI_D.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND MERCATI_D.IDPOSTEGGIO =   AUTORIZZAZIONI_CONCESSIONI.FK_IDPOSTEGGIO AND MERCATI_USO.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND MERCATI_USO.ID =   AUTORIZZAZIONI_CONCESSIONI.FK_IDMERCATIUSO
GO
COMMIT
GO
DROP VIEW VW_CONCESSIONILISTA
GO
COMMIT
GO
CREATE VIEW VW_CONCESSIONILISTA AS SELECT IDCOMUNE, SOFTWARE, PROGRESSIVO, CONC_ID, CONC_NUMERO, CONC_DATARILASCIO, CONC_DATASCADENZA, CONC_CODICETIPO, CONC_TIPO, CONC_STAGIONALEA, CONC_STAGIONALEDA, CONC_ATTIVA, CONC_CODICETITOLARE, CONC_TITOLARE, CONC_TIT_CF, CONC_TIT_PIVA, CONC_TIT_TIPOANAGRAFE, AUT_NUMERO, AUT_DATA, AUT_CODREGISTRO, AUT_REGISTRO, IST_CODICEISTANZA, IST_NUMEROISTANZA, IST_CODICERICHIEDENTE, IST_NOMINATIVO, IST_CODICEFISCALE, IST_PARTITAIVA, IST_RIC_TIPOANAGRAFE, ICONC_CODICECAUSALE, ICONC_CAUSALE, ICONC_CODICECAUSALESTORICO, ICONC_CAUSALESTORICO, CONC_IDMERCATO, CONC_MERCATO, MERC_ATTIVO, CONC_IDPOSTEGGIO, CONC_POSTEGGIO, CONC_POS_LARGHEZZA, CONC_POS_LUNGHEZZA, CONC_POS_SUPERFICIE, POST_IDTIPOSPAZIO, POST_TIPOSPAZIO, CONC_IDMERCATIUSO, CONC_DESCRIZIONEUSO, PESO_MERCATO, MERC_IDUSO, CONC_POS_CODICESTRADARIO FROM VW_ISTANZECONCESSIONILISTA
GO
COMMIT
GO
ALTER TABLE CC_CAUSALIRIDUZIONIR DROP CONSTRAINT FK_CCCAUSRIDUR_CCCAUSRIDUT
GO
COMMIT
GO
ALTER TABLE CC_CAUSALIRIDUZIONIR ADD CONSTRAINT FK_CCCAUSRIDUR_CCCAUSRIDUT FOREIGN KEY (IDCOMUNE, FK_CCCRT_ID) REFERENCES CC_CAUSALIRIDUZIONIT (IDCOMUNE, ID)
GO
COMMIT
GO
alter table MAIL_CONFIG add IN_LOGINNAME varchar(320 )
GO
COMMIT
GO
alter table MAIL_CONFIG add IN_LOGINPASS varchar(30 )
GO
COMMIT
GO
alter table MAIL_CONFIG add IN_USEAUTHENTICATION numeric(1,0)
GO
COMMIT
GO
alter table MAIL_CONFIG add IN_MAILSERVER varchar(50 )
GO
COMMIT
GO
alter table MAIL_CONFIG add IN_PORT numeric(5,0)
GO
COMMIT
GO
alter table MAIL_CONFIG add IN_USESSL numeric(1,0)
GO
COMMIT
GO
ALTER TABLE BATCH_SCADENZARIO DROP CONSTRAINT FK_BATCHSCA_AMMINISTRAZ
GO
COMMIT
GO
ALTER TABLE BATCH_SCADENZARIO DROP CONSTRAINT FK_BATCHSCA_INVENTARIO
GO
COMMIT
GO
ALTER TABLE BATCH_SCADENZARIO DROP CONSTRAINT FK_BATCHSCA_ISTANZE
GO
COMMIT
GO
ALTER TABLE BATCH_SCADENZARIO DROP CONSTRAINT FK_BATCHSCA_MOVIMENTI
GO
COMMIT
GO
ALTER TABLE BATCH_SCADENZARIO DROP CONSTRAINT FK_BATCHSCA_TIPIMOV
GO
COMMIT
GO
CREATE INDEX IDX_DOMANDESTC_002 ON DOMANDESTC (IDCOMUNE,CODICESOFTWARE,FLAG_IMPORT)
GO
COMMIT
GO
ALTER TABLE SORTEGGIDETTAGLIO ADD CONSTRAINT SORTEGGIDETTAGLIO_UK01 UNIQUE (IDCOMUNE,SD_FK_STID,CODICEISTANZA)
GO
COMMIT
GO
ALTER TABLE ANAGRAFE ALTER COLUMN INDIRIZZO VARCHAR(100)
GO
COMMIT
GO
ALTER TABLE ANAGRAFESTORICO ALTER COLUMN INDIRIZZO VARCHAR(100)
GO
COMMIT
GO
ALTER TABLE TIPIMOV_STC_ALBEROPROC ALTER COLUMN FK_SCID NUMERIC(10, 0)
GO
COMMIT
GO
ALTER TABLE INVENTARIOPROCEDIMENTIPEOPLE ALTER COLUMN COD_PROC_PEOPLE VARCHAR(50)
GO
COMMIT
GO
CREATE INDEX IDX_DOMANDESTC_003 ON DOMANDESTC (IDCOMUNE, ID_DOMANDAMITT)
GO
COMMIT
GO
ALTER TABLE DOCUMENTIISTANZA ADD FLG_DA_MODELLO_DINAMICO NUMERIC(1,0)
GO
COMMIT
GO
ALTER TABLE ISTANZECOLLEGATE DROP CONSTRAINT FK_ISTANZE_COLL_ISTANZACOLL
GO
COMMIT
GO
ALTER TABLE ISTANZECOLLEGATE DROP CONSTRAINT FK_ISTANZE_COLL_ISTANZE
GO
COMMIT
GO
DROP INDEX ISTANZECOLLEGATE.IDX_ISTANZECOLLEGATE_001
GO
COMMIT
GO
DROP INDEX ISTANZECOLLEGATE.IDX_ISTANZECOLLEGATE_002
GO
COMMIT
GO
DROP INDEX ISTANZECOLLEGATE.IDX_ISTANZECOLLEGATE_003
GO
COMMIT
GO
SELECT * INTO ISTANZECOLLEGATE_BAK FROM ISTANZECOLLEGATE
GO
COMMIT
GO
DROP TABLE ISTANZECOLLEGATE
GO
COMMIT
GO
CREATE TABLE ISTANZECOLLEGATE (IDCOMUNE VARCHAR(6) NOT NULL, PROGRESSIVO NUMERIC(8,0) NOT NULL, CODICEISTANZA NUMERIC(6,0) NOT NULL, ORDINE NUMERIC(3,0) NOT NULL, ID NUMERIC(8,0) NOT NULL, CODICEISTANZACOLLEGATA NUMERIC(6,0))
GO
COMMIT
GO
INSERT INTO ISTANZECOLLEGATE (IDCOMUNE,ID,PROGRESSIVO,CODICEISTANZA, ORDINE, CODICEISTANZACOLLEGATA)( SELECT IDCOMUNE, ID,PROGRESSIVO,CODICEISTANZA,ORDINE,CODICEISTANZACOLLEGATA FROM ISTANZECOLLEGATE_BAK )
GO
COMMIT
GO
ALTER TABLE ISTANZECOLLEGATE ADD CONSTRAINT ISTANZECOLLEGATE_PK PRIMARY KEY (IDCOMUNE,ID)
GO
COMMIT
GO
ALTER TABLE ISTANZECOLLEGATE ADD CONSTRAINT FK_ISTANZE_COLL_ISTANZE FOREIGN KEY(IDCOMUNE,CODICEISTANZA) REFERENCES ISTANZE(IDCOMUNE,CODICEISTANZA)
GO
COMMIT
GO
ALTER TABLE ISTANZECOLLEGATE ADD CONSTRAINT FK_ISTANZE_COLL_ISTANZACOLL FOREIGN KEY(IDCOMUNE,CODICEISTANZACOLLEGATA) REFERENCES ISTANZE(IDCOMUNE,CODICEISTANZA)
GO
COMMIT
GO
CREATE INDEX IDX_ISTANZECOLLEGATE_001 ON ISTANZECOLLEGATE(IDCOMUNE,PROGRESSIVO,CODICEISTANZA,ORDINE)
GO
COMMIT
GO
CREATE INDEX IDX_ISTANZECOLLEGATE_002 ON ISTANZECOLLEGATE(IDCOMUNE,CODICEISTANZA)
GO
COMMIT
GO
CREATE INDEX IDX_ISTANZECOLLEGATE_003 ON ISTANZECOLLEGATE(IDCOMUNE,CODICEISTANZACOLLEGATA)
GO
COMMIT
GO
ALTER TABLE ANAGRAFE  ALTER COLUMN  PARTITAIVA VARCHAR(16)
GO
COMMIT
GO
ALTER TABLE ANAGRAFESTORICO  ALTER COLUMN  PARTITAIVA VARCHAR(16)
GO
COMMIT
GO
ALTER TABLE ALBEROPROC_DYN2MODELLIT ADD FLAG_FACOLTATIVA NUMERIC(1, 0)
GO
COMMIT
GO
ALTER TABLE INVENTARIOPROCDYN2MODELLIT ADD FLAG_FACOLTATIVA NUMERIC(1, 0)
GO
COMMIT
GO