//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Init.Sigepro.FrontEnd.Reserved {
    
    
    public partial class ModificaPassword {
        
        /// <summary>
        /// txtVecchiaPassword control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.TextBox txtVecchiaPassword;
        
        /// <summary>
        /// txtNuovaPassword control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.TextBox txtNuovaPassword;
        
        /// <summary>
        /// txtConfermaNuovaPassword control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.TextBox txtConfermaNuovaPassword;
        
        /// <summary>
        /// cmdConfirm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button cmdConfirm;
    }
}
