<?xml version="1.0" ?><schema elementFormDefault="qualified" targetNamespace="http://sigepro.init.it/rte" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://sigepro.init.it/rte" xmlns:types="http://sigepro.init.it/rte/types" xmlns:xmime="http://www.w3.org/2005/05/xmlmime">
	<import namespace="http://sigepro.init.it/rte/types" schemaLocation="types.xsd"></import>
	<simpleType name="XsdNlaVersion">
		<restriction base="string">
			<enumeration value="V_1_0"></enumeration>
			<enumeration value="V_1_1"></enumeration>
			<enumeration value="V_1_2"></enumeration>
			<enumeration value="V_1_3"></enumeration>
			<enumeration value="V_1_4"></enumeration>
			<enumeration value="V_1_5"></enumeration>
			<enumeration value="V_1_6"></enumeration>
			<enumeration value="V_1_7"></enumeration>
			<enumeration value="V_1_8"></enumeration>
			<enumeration value="V_1_9"></enumeration>
			<enumeration value="V_1_10"></enumeration>
			<enumeration value="V_1_11"></enumeration>
			<enumeration value="V_1_12"></enumeration>	
			<enumeration value="V_1_13"></enumeration>			
		</restriction>
	</simpleType>
	<element name="RichiestaPraticaNLARequest">
		<complexType>
			<sequence>
				<element name="token" type="string"></element>
				<element name="sportelloMittente" type="types:SportelloType"></element>
				<element name="sportelloDestinatario" type="types:SportelloType"></element>
				<element name="rifPratica" type="types:RiferimentiPraticaType"></element>
			</sequence>
		</complexType>
	</element>
	<element name="RichiestaPraticaNLAResponse">
		<complexType>
			<sequence>
				<element maxOccurs="1" minOccurs="0" name="dettaglioPratica" type="types:DettaglioPraticaVisuraType"></element>
				<element maxOccurs="unbounded" minOccurs="0" name="dettaglioErrore" type="types:ErroreType"></element>
			</sequence>
		</complexType>
	</element>
	<element name="InserimentoAttivitaNLARequest">
		<complexType>
			<sequence>
				<element name="token" type="string"></element>
				<element name="sportelloMittente" type="types:SportelloType"></element>
				<element name="sportelloDestinatario" type="types:SportelloType"></element>
				<element name="datiAttivita" type="types:DettaglioAttivitaType"></element>
				<element maxOccurs="1" minOccurs="0" name="rifPraticaMittente" type="types:RiferimentiPraticaType"></element>
			</sequence>
		</complexType>
	</element>
	<element name="InserimentoAttivitaNLAResponse">
		<complexType>
			<choice minOccurs="1">
				<element minOccurs="0" name="dettaglioAttivita" type="types:RiferimentiAttivitaType"></element>
				<element maxOccurs="unbounded" minOccurs="0" name="dettaglioErrore" type="types:ErroreType"></element>
			</choice>
		</complexType>
	</element>
	<element name="InserimentoPraticaNLARequest">
		<complexType>
			<sequence>
				<element name="token" type="string"></element>
				<element name="sportelloMittente" type="types:SportelloType"></element>
				<element name="sportelloDestinatario" type="types:SportelloType"></element>
				<element name="dettaglioPratica" type="types:DettaglioPraticaType"></element>
				<element maxOccurs="1" minOccurs="0" name="rifPraticaDestinatario" type="types:RiferimentiPraticaType"></element>
			</sequence>
		</complexType>
	</element>
	<element name="InserimentoPraticaNLAResponse">
		<complexType>
			<choice minOccurs="1">
				<element minOccurs="0" name="dettaglioPratica" type="types:RiferimentiPraticaType"></element>
				<element maxOccurs="unbounded" minOccurs="0" name="dettaglioErrore" type="types:ErroreType"></element>
			</choice>
		</complexType>
	</element>
	<element name="AllegatoBinarioNLARequest">
		<complexType>
			<sequence>
				<element name="token" type="string"></element>
				<element name="sportelloMittente" type="types:SportelloType"></element>
				<element name="sportelloDestinatario" type="types:SportelloType"></element>
				<element name="riferimentiAllegato" type="types:RiferimentiAllegatoType"></element>
			</sequence>
		</complexType>
	</element>
	<element name="AllegatoBinarioNLAResponse">
		<complexType>
			<sequence>
				<element maxOccurs="1" minOccurs="0" name="mimeType" type="string"></element>
				<element name="binaryData" type="base64Binary" xmime:expectedContentTypes="application/octet-stream"></element>
				<element name="fileName" type="string"></element>
			</sequence>
		</complexType>
	</element>
	<element name="TestNLARequest">
		<complexType>
			<sequence>
				<element name="test" type="string"></element>
			</sequence>
		</complexType>
	</element>
	<element name="TestNLAResponse">
		<complexType>
			<sequence>
				<element name="nlaXsdVersion" type="tns:XsdNlaVersion"></element>
				<element name="typesXsdVersion" type="types:XsdTypesVersion"></element>
			</sequence>
		</complexType>
	</element>
	<element name="RichiestaPraticheListaNLARequest">
		<complexType>
			<sequence>
				<element name="token" type="string"></element>
				<element name="sportelloMittente" type="types:SportelloType"></element>
				<element name="sportelloDestinatario" type="types:SportelloType"></element>
				<element maxOccurs="1" minOccurs="0" name="filtriUtenteConnesso" type="types:FiltriUtenteType"></element>
				<element maxOccurs="1" minOccurs="1" name="filtriPratica" type="types:FiltriPraticaType"></element>
			</sequence>
		</complexType>
	</element>
	<element name="RichiestaPraticheListaNLAResponse">
		<complexType>
			<sequence>
				<element maxOccurs="unbounded" minOccurs="0" name="dettaglioPratica" type="types:DettaglioPraticaBreveType"></element>
				<element maxOccurs="unbounded" minOccurs="0" name="dettaglioErrore" type="types:ErroreType"></element>
			</sequence>
		</complexType>
	</element>
	<element name="AggiungiDocumentiNLARequest">
		<complexType>
			<sequence>
				<element name="token" type="string"></element>
				<element name="sportelloMittente" type="types:SportelloType"></element>
				<element name="sportelloDestinatario" type="types:SportelloType"></element>
				<element name="idPraticaDest" type="string"></element>
				<element maxOccurs="unbounded" minOccurs="1" name="documenti" type="types:DocumentiType"></element>
			</sequence>
		</complexType>
	</element>
	<element name="AggiungiDocumentiNLAResponse">
		<complexType>
			<sequence>
				<element maxOccurs="unbounded" minOccurs="0" name="dettaglioErrore" type="types:ErroreType"></element>
			</sequence>
		</complexType>
	</element>
</schema>