ALTER TABLE VERTICALIZZAZIONI DROP PRIMARY KEY;
ALTER TABLE VERTICALIZZAZIONIPARAMETRI DROP PRIMARY KEY;

ALTER TABLE VERTICALIZZAZIONI MODIFY ID NUMERIC(6,0) NOT NULL;
ALTER TABLE VERTICALIZZAZIONIPARAMETRI MODIFY ID NUMERIC(6,0) NOT NULL;

ALTER TABLE VERTICALIZZAZIONI ADD CONSTRAINT PK_VERTICALIZZAZIONI PRIMARY KEY(IDCOMUNE,ID);
ALTER TABLE VERTICALIZZAZIONIPARAMETRI ADD CONSTRAINT PK_VERTICALIZZAZIONIPARAMETRI PRIMARY KEY(IDCOMUNE,ID);

CREATE INDEX IDX_VERTICALIZZAZIONI_001 ON VERTICALIZZAZIONI (IDCOMUNE, MODULO);
CREATE INDEX IDX_VERTICALIZZAZIONI_002 ON VERTICALIZZAZIONI (IDCOMUNE, MODULO, SOFTWARE);
CREATE INDEX IDX_VERTICALIZZAZIONI_003 ON VERTICALIZZAZIONI (IDCOMUNE, MODULO, SOFTWARE, CODICECOMUNE);

CREATE INDEX IDX_VERTPARAMETRI_001 ON VERTICALIZZAZIONIPARAMETRI (IDCOMUNE, MODULO, PARAMETRO);
CREATE INDEX IDX_VERTPARAMETRI_002 ON VERTICALIZZAZIONIPARAMETRI (IDCOMUNE, MODULO, PARAMETRO, SOFTWARE);
CREATE INDEX IDX_VERTPARAMETRI_003 ON VERTICALIZZAZIONIPARAMETRI (IDCOMUNE, MODULO, PARAMETRO, SOFTWARE, CODICECOMUNE);

UPDATE VERTICALIZZAZIONIBASE SET FLAG_GESTCOMUNE=1 WHERE MODULO='FILESYSTEM_PROTOCOLLO';
UPDATE VERTICALIZZAZIONIBASE SET FLAG_GESTCOMUNE=1 WHERE MODULO='PROTOCOLLO_AIDA';
UPDATE VERTICALIZZAZIONIBASE SET FLAG_GESTCOMUNE=1 WHERE MODULO='PROTOCOLLO_APSYSTEMS';
UPDATE VERTICALIZZAZIONIBASE SET FLAG_GESTCOMUNE=1 WHERE MODULO='PROTOCOLLO_ATTIVO';
UPDATE VERTICALIZZAZIONIBASE SET FLAG_GESTCOMUNE=1 WHERE MODULO='PROTOCOLLO_DEFAULT';
UPDATE VERTICALIZZAZIONIBASE SET FLAG_GESTCOMUNE=1 WHERE MODULO='PROTOCOLLO_DELTA';
UPDATE VERTICALIZZAZIONIBASE SET FLAG_GESTCOMUNE=1 WHERE MODULO='PROTOCOLLO_DOCAREA';
UPDATE VERTICALIZZAZIONIBASE SET FLAG_GESTCOMUNE=1 WHERE MODULO='PROTOCOLLO_DOCER';
UPDATE VERTICALIZZAZIONIBASE SET FLAG_GESTCOMUNE=1 WHERE MODULO='PROTOCOLLO_DOCPRO';
UPDATE VERTICALIZZAZIONIBASE SET FLAG_GESTCOMUNE=1 WHERE MODULO='PROTOCOLLO_DOCSPA';
UPDATE VERTICALIZZAZIONIBASE SET FLAG_GESTCOMUNE=1 WHERE MODULO='PROTOCOLLO_EGRAMMATA';
UPDATE VERTICALIZZAZIONIBASE SET FLAG_GESTCOMUNE=1 WHERE MODULO='PROTOCOLLO_EGRAMMATA2';
UPDATE VERTICALIZZAZIONIBASE SET FLAG_GESTCOMUNE=1 WHERE MODULO='PROTOCOLLO_FOLIUM';
UPDATE VERTICALIZZAZIONIBASE SET FLAG_GESTCOMUNE=1 WHERE MODULO='PROTOCOLLO_GEPROT';
UPDATE VERTICALIZZAZIONIBASE SET FLAG_GESTCOMUNE=1 WHERE MODULO='PROTOCOLLO_HALLEY';
UPDATE VERTICALIZZAZIONIBASE SET FLAG_GESTCOMUNE=1 WHERE MODULO='PROTOCOLLO_INSIEL';
UPDATE VERTICALIZZAZIONIBASE SET FLAG_GESTCOMUNE=1 WHERE MODULO='PROTOCOLLO_INSIELMERCATO';
UPDATE VERTICALIZZAZIONIBASE SET FLAG_GESTCOMUNE=1 WHERE MODULO='PROTOCOLLO_IRIDE';
UPDATE VERTICALIZZAZIONIBASE SET FLAG_GESTCOMUNE=1 WHERE MODULO='PROTOCOLLO_JPROTOCOLLO';
UPDATE VERTICALIZZAZIONIBASE SET FLAG_GESTCOMUNE=1 WHERE MODULO='PROTOCOLLO_PALEO';
UPDATE VERTICALIZZAZIONIBASE SET FLAG_GESTCOMUNE=1 WHERE MODULO='PROTOCOLLO_PINDARO';
UPDATE VERTICALIZZAZIONIBASE SET FLAG_GESTCOMUNE=1 WHERE MODULO='PROTOCOLLO_SICRAWEB';
UPDATE VERTICALIZZAZIONIBASE SET FLAG_GESTCOMUNE=1 WHERE MODULO='PROTOCOLLO_SIDOP';
UPDATE VERTICALIZZAZIONIBASE SET FLAG_GESTCOMUNE=1 WHERE MODULO='PROTOCOLLO_SIGEDO';
UPDATE VERTICALIZZAZIONIBASE SET FLAG_GESTCOMUNE=1 WHERE MODULO='PROTOCOLLO_SIGEPRO';
UPDATE VERTICALIZZAZIONIBASE SET FLAG_GESTCOMUNE=1 WHERE MODULO='PROTOCOLLO_SIPRWEB';
UPDATE VERTICALIZZAZIONIBASE SET FLAG_GESTCOMUNE=1 WHERE MODULO='PROTOCOLLO_SIPRWEBTEST';
UPDATE VERTICALIZZAZIONIBASE SET FLAG_GESTCOMUNE=1 WHERE MODULO='PROTOCOLLO_TINN';
UPDATE VERTICALIZZAZIONIBASE SET FLAG_GESTCOMUNE=0 WHERE FLAG_GESTCOMUNE IS NULL;