ALTER TABLE amministrazioni MODIFY STC_IDSPORTELLO VARCHAR2(30 CHAR);
ALTER TABLE domandestc MODIFY ID_SPORTELLOMITT VARCHAR2(30 CHAR);

alter table tipicausalioneri add mappaturanodopag varchar2(50 char);
alter table tipicausalioneri add codicetassonomia varchar2(12 char);

ALTER TABLE TIPOLOGIAREGISTRI ADD NUMERAZIONE_CUSTOM VARCHAR2(50 CHAR) NULL;

ALTER TABLE TIPOLOGIAREGISTRI MODIFY TR_FLAGDATAAUTO NUMBER(1,0) DEFAULT 0; 

update TIPOLOGIAREGISTRI set TR_FLAGDATAAUTO = 0 where TR_FLAGDATAAUTO  is null;

ALTER TABLE TIPOLOGIAREGISTRI MODIFY TR_FLAGDATAAUTO NUMBER(1,0) DEFAULT 0 not null;


alter table pay_registrazioni_contabili add codicetassonomia varchar2(12 char);

CREATE TABLE boll_gest_oneri_sequence(
idcomune VARCHAR2(6 CHAR) NOT NULL
,fk_codiceistanzeoneri NUMBER(10,0) NOT NULL 
,id_bollegest_dett NUMBER(10,0) NOT NULL 
,id_bollegest_oneri NUMBER(10,0) NOT NULL 
,guid VARCHAR2(60 CHAR) NOT NULL
) ;

CREATE INDEX idx_boll_oneri_sequence_001 ON boll_gest_oneri_sequence (idcomune,fk_codiceistanzeoneri); 
CREATE INDEX idx_boll_oneri_sequence_002 ON boll_gest_oneri_sequence (guid); 
ALTER TABLE boll_gest_oneri_sequence ADD CONSTRAINT fk_bollgestoneriseq_istoneri FOREIGN KEY (idcomune,fk_codiceistanzeoneri) REFERENCES istanzeoneri(idcomune,id);

ALTER TABLE AUTORIZZAZIONI ADD FKIDPROTOCOLLO VARCHAR2(400 CHAR);
ALTER TABLE AUTORIZZAZIONI ADD MODIFICABLOCCATA NUMBER(1,0) DEFAULT 0;
UPDATE AUTORIZZAZIONI SET MODIFICABLOCCATA = 0 WHERE MODIFICABLOCCATA IS NULL;
ALTER TABLE AUTORIZZAZIONI MODIFY MODIFICABLOCCATA NUMBER(1,0) NOT NULL;
ALTER TABLE DOCUMENTI_AUTORIZZAZIONE ADD PRINCIPALE NUMBER(1,0) DEFAULT 0;
UPDATE DOCUMENTI_AUTORIZZAZIONE SET PRINCIPALE = 0 WHERE PRINCIPALE IS NULL;
ALTER TABLE DOCUMENTI_AUTORIZZAZIONE MODIFY PRINCIPALE NUMBER(1,0) NOT NULL;
ALTER TABLE DOCUMENTI_AUTORIZZAZIONE ADD RIFERIMENTO_ESTERNO VARCHAR(50 CHAR);
CREATE TABLE AUTORIZZAZIONI_METADATI(IDCOMUNE VARCHAR2(6 CHAR) NOT NULL, FKIDAUTORIZZAZIONE NUMBER(6,0) NOT NULL, CHIAVE VARCHAR2(100 CHAR) NOT NULL, VALORE VARCHAR2(4000 CHAR) NOT NULL);
ALTER TABLE AUTORIZZAZIONI_METADATI ADD CONSTRAINT PK_AUTORIZZAZIONIMETADATI PRIMARY KEY(IDCOMUNE,FKIDAUTORIZZAZIONE,CHIAVE);
ALTER TABLE AUTORIZZAZIONI_METADATI ADD CONSTRAINT FK_AUTORIZZAZIONI FOREIGN KEY(IDCOMUNE,FKIDAUTORIZZAZIONE) REFERENCES AUTORIZZAZIONI(IDCOMUNE,ID);
