CREATE TABLE MOVIMENTI_ATTI  (
  IDCOMUNE VARCHAR(6) NOT NULL, 
  ID NUMERIC(10,0) NOT NULL,
  DATA_RICHIESTA_ATTO DATETIME NOT NULL,
  DATA_RICEZIONE_ATTO DATETIME,
  ID_DOCUMENTO NUMERIC (6,0) NOT NULL ,
  NUMERO NUMERIC (6,0) NOT NULL,
  ANNO NUMERIC (4,0) NOT NULL,
  TIPO_DOCUMENTO VARCHAR(4) NOT NULL,
  STATO NUMERIC (1,0) NOT NULL,
  FK_MOVIMENTO NUMERIC (8,0) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE UNIQUE INDEX MOVIMENTI_ATTI_PK ON MOVIMENTI_ATTI (IDCOMUNE, ID) ; 
ALTER TABLE MOVIMENTI_ATTI ADD CONSTRAINT MOVIMENTI_ATTI_PK PRIMARY KEY (IDCOMUNE, ID);
ALTER TABLE MOVIMENTI_ATTI ADD CONSTRAINT FK_MOV_ATTI FOREIGN KEY (IDCOMUNE, FK_MOVIMENTO) REFERENCES MOVIMENTI (IDCOMUNE, CODICEMOVIMENTO);

ALTER TABLE TMP_ISTANZEONERI MODIFY ENDO VARCHAR(500);

ALTER VIEW VW_LISTAPRATICHE AS 
SELECT
  ISTANZE.CODICECOMUNE          AS CODICECOMUNE,
  ISTANZE.IDCOMUNE              AS IDCOMUNE,
  ISTANZE.SOFTWARE              AS SOFTWARE,
  SOFTWARE.DESCRIZIONELUNGA     AS DESCSOFTWARE,
  ISTANZE.CODICEISTANZA         AS IDPRATICA,
  ISTANZE.NUMEROISTANZA         AS NUMEROPRATICA,
  DATE_FORMAT(ISTANZE.DATA,'%d/%m/%Y') AS DATAPRESENTAZIONE,
  DATE_FORMAT(ISTANZE.DATA,'%Y') AS ANNOPRESENTAZIONE,
  DATE_FORMAT(ISTANZE.DATA,'%m') AS MESEPRESENTAZIONE,
  ISTANZE.NUMEROPROTOCOLLO      AS NUMEROPROTOCOLLO,
  DATE_FORMAT(ISTANZE.DATAPROTOCOLLO,'%d/%m/%Y') AS DATAPROTOCOLLO,
  ISTANZE.CODICEINTERVENTOPROC  AS CODICEINTERVENTO,
  VW_ALBEROPROC.SC_DESCRIZIONE  AS DESCRIZIONEINTERVENTO,
  TIPIPROCEDURE.CODICEPROCEDURA AS CODICEPROCEDURA,
  TIPIPROCEDURE.PROCEDURA       AS PROCEDURA,
  ISTANZE.LAVORI                AS OGGETTO,
  UCASE(ISTANZE.LAVORI)         AS OGGETTOU,
  ISTANZE.CHIUSURA              AS CODSTATOPRATICA,
  STATIISTANZA.STATO            AS STATOPRATICA,
  RESPONSABILI.RESPONSABILE     AS RESPONSABILE,
  RESPONSABILI.TELEFONOLAVORO   AS RESPONSABILE_TELEFONO,
  IFNULL(STRADARIO.CODVIARIO,STRADARIO.CODICESTRADARIO) AS PR_CODVIARIO,
  CONCAT_WS('',STRADARIO.PREFISSO,' ',STRADARIO.DESCRIZIONE) AS PR_INDIRIZZO,
  ISTANZESTRADARIO.CODICECIVICO AS PR_CODCIVICO,
  ISTANZESTRADARIO.CIVICO       AS PR_CIVICO,
  ISTANZE.CODICEAREA            AS CODICEZONIZZAZIONE,
  AREE.DENOMINAZIONE            AS ZONIZZAZIONE,
  ANAGRAFE.CODICEANAGRAFE       AS CODICERICHIEDENTE,
  IFNULL(ANAGRAFE.CODICEFISCALE,'') AS CODICEFISCALE,
  IFNULL(ANAGRAFE.PARTITAIVA,'') AS PARTITAIVA,
  CONCAT_WS('',ANAGRAFE.NOMINATIVO,' ',ANAGRAFE.NOME) AS NOMINATIVO,
  ANAGRAFE.INDIRIZZO            AS INDIRIZZO,
  ANAGRAFE.CAP                  AS CAP,
  ANAGRAFE.CITTA                AS LOCALITA,
  COMUNERESIDENZA.COMUNE        AS CITTA,
  COMUNERESIDENZA.PROVINCIA     AS PROVINCIA,
  TIPISOGGETTO.TIPOSOGGETTO     AS TIPORAPPORTO,
  CATASTO.DESCRIZIONE           AS TIPOCATASTO,
  ISTANZEMAPPALI.FOGLIO         AS FOGLIO,
  ISTANZEMAPPALI.PARTICELLA     AS PARTICELLA,
  ISTANZEMAPPALI.SUB            AS SUB,
  TECNICO.CODICEANAGRAFE        AS TEC_CODICE,
  CONCAT_WS('',TECNICO.NOMINATIVO,' ',TECNICO.NOME) AS TEC_NOMINATIVO,
  IFNULL(TECNICO.CODICEFISCALE,'') AS TEC_CODICEFISCALE,
  IFNULL(TECNICO.PARTITAIVA,'') AS TEC_PARTITAIVA,
  AZIENDA.CODICEANAGRAFE        AS AZ_CODICE,
  CONCAT_WS('',AZIENDA.NOMINATIVO,' ',AZIENDA.NOME) AS AZ_NOMINATIVO,
  IFNULL(AZIENDA.CODICEFISCALE,'') AS AZ_CODICEFISCALE,
  IFNULL(AZIENDA.PARTITAIVA,'') AS AZ_PARTITAIVA,
  ISTRUTTORI.RESPONSABILE       AS ISTRUTTORE,
  ISTRUTTORI.TELEFONOLAVORO     AS ISTRUTTORE_TELEFONO,
  OPERATORI.RESPONSABILE        AS OPERATORE,
  OPERATORI.TELEFONOLAVORO      AS OPERATORE_TELEFONO,
  ISTANZE.DOMICILIO_ELETTRONICO AS DOMICILIO_ELETTRONICO,
  DOMANDESTC.ID_SPORTELLOMITT,
  DOMANDESTC.ID_DOMANDAMITT
FROM
  ISTANZE
                INNER JOIN SOFTWARE ON ISTANZE.SOFTWARE = SOFTWARE.CODICE
                INNER JOIN ANAGRAFE ON ISTANZE.IDCOMUNE = ANAGRAFE.IDCOMUNE AND ISTANZE.CODICERICHIEDENTE = ANAGRAFE.CODICEANAGRAFE
                INNER JOIN STATIISTANZA ON ISTANZE.IDCOMUNE = STATIISTANZA.IDCOMUNE AND ISTANZE.SOFTWARE = STATIISTANZA.SOFTWARE AND ISTANZE.CHIUSURA = STATIISTANZA.CODICESTATO
                INNER JOIN VW_ALBEROPROC ON ISTANZE.IDCOMUNE = VW_ALBEROPROC.IDCOMUNE AND ISTANZE.CODICEINTERVENTOPROC = VW_ALBEROPROC.SC_ID
                LEFT JOIN ANAGRAFE TECNICO ON ISTANZE.IDCOMUNE = TECNICO.IDCOMUNE AND ISTANZE.CODICEPROFESSIONISTA = TECNICO.CODICEANAGRAFE
                LEFT JOIN ANAGRAFE AZIENDA ON ISTANZE.IDCOMUNE = AZIENDA.IDCOMUNE AND ISTANZE.CODICETITOLARELEGALE = AZIENDA.CODICEANAGRAFE
                LEFT JOIN ISTANZESTRADARIO ON ISTANZE.IDCOMUNE = ISTANZESTRADARIO.IDCOMUNE AND ISTANZE.CODICEISTANZA = ISTANZESTRADARIO.CODICEISTANZA AND ISTANZESTRADARIO.PRIMARIO = 1
                LEFT JOIN STRADARIO ON ISTANZESTRADARIO.IDCOMUNE = STRADARIO.IDCOMUNE AND ISTANZESTRADARIO.CODICESTRADARIO = STRADARIO.CODICESTRADARIO
                LEFT JOIN ISTANZEMAPPALI ON ISTANZE.IDCOMUNE = ISTANZEMAPPALI.IDCOMUNE AND ISTANZE.CODICEISTANZA = ISTANZEMAPPALI.FKCODICEISTANZA AND ISTANZEMAPPALI.PRIMARIO = 1
                LEFT JOIN RESPONSABILI ON ISTANZE.IDCOMUNE = RESPONSABILI.IDCOMUNE AND ISTANZE.CODICERESPONSABILEPROC = RESPONSABILI.CODICERESPONSABILE
                LEFT JOIN COMUNI COMUNERESIDENZA ON ANAGRAFE.COMUNERESIDENZA = COMUNERESIDENZA.CODICECOMUNE
                LEFT JOIN TIPISOGGETTO ON ISTANZE.IDCOMUNE = TIPISOGGETTO.IDCOMUNE AND ISTANZE.FKCODICESOGGETTO = TIPISOGGETTO.CODICETIPOSOGGETTO
                LEFT JOIN AREE ON ISTANZE.IDCOMUNE = AREE.IDCOMUNE AND ISTANZE.CODICEAREA = AREE.CODICEAREA
                LEFT JOIN CATASTO ON ISTANZEMAPPALI.CODICECATASTO = CATASTO.CODICE
                LEFT JOIN TIPIPROCEDURE ON ISTANZE.IDCOMUNE = TIPIPROCEDURE.IDCOMUNE AND ISTANZE.CODICEPROCEDURA = TIPIPROCEDURE.CODICEPROCEDURA
                LEFT JOIN RESPONSABILI ISTRUTTORI ON ISTANZE.IDCOMUNE = ISTRUTTORI.IDCOMUNE AND ISTANZE.CODICEISTRUTTORE = ISTRUTTORI.CODICERESPONSABILE
                LEFT JOIN RESPONSABILI OPERATORI ON OPERATORI.IDCOMUNE = ISTANZE.IDCOMUNE AND OPERATORI.CODICERESPONSABILE = ISTANZE.CODICERESPONSABILE
                LEFT JOIN DOMANDESTC ON ISTANZE.IDCOMUNE = DOMANDESTC.IDCOMUNE AND ISTANZE.CODICEISTANZA = DOMANDESTC.CODICEISTANZA;
                
ALTER TABLE TIPIMOVIMENTO ADD FLAG_RIPORTA_PROT_ISTANZA NUMERIC(1,0) ;


CREATE TABLE ALBEROPROC_TIPISOG_BACK  (
  IDCOMUNE VARCHAR(6) NOT NULL, 
  ID NUMERIC(10,0) NOT NULL,
  FK_SCID NUMERIC(10,0) NOT NULL,
  FK_TIPISOGGETTO NUMERIC(10,0) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE UNIQUE INDEX ALBEROPROC_TIPISOG_BACK_PK ON ALBEROPROC_TIPISOG_BACK (IDCOMUNE, ID) ; 
ALTER TABLE ALBEROPROC_TIPISOG_BACK ADD CONSTRAINT ALBEROPROC_TIPISOG_BACK_PK PRIMARY KEY (IDCOMUNE, ID);

ALTER TABLE ALBEROPROC_TIPISOG_BACK 
ADD CONSTRAINT FK_ALB_PROC_BACK_ALBERO_PROC FOREIGN KEY (IDCOMUNE, FK_SCID)
REFERENCES ALBEROPROC (IDCOMUNE, SC_ID);


ALTER TABLE ALBEROPROC_TIPISOG_BACK 
ADD CONSTRAINT FK_ALB_PROC_BACK_TIPI_SOGG FOREIGN KEY (IDCOMUNE, FK_TIPISOGGETTO)
REFERENCES TIPISOGGETTO (IDCOMUNE, CODICETIPOSOGGETTO);

ALTER TABLE TIPIMOV_STC_MAPPING ADD (CODICE_MOV_RECUPERO_ALLEGATO VARCHAR(8) );

ALTER TABLE CLMENU_JAVA DROP COLUMN LAYOUTTESTI;
ALTER TABLE CLMENU_JAVA ADD LAYOUTTESTI VARCHAR(200);


CREATE TABLE TIPIMOVIMENTO_COMUNICAZIONI  (
  IDCOMUNE VARCHAR(6) NOT NULL, 
  ID NUMERIC(10,0) NOT NULL,
  FK_TIPOMOV VARCHAR(8) NOT NULL,
  FK_MAILTIPO NUMERIC(4,0) NOT NULL,
  FUNZIONE VARCHAR(10)  NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE UNIQUE INDEX TIPIMOVIMENTO_COMUNICAZIONI_PK ON TIPIMOVIMENTO_COMUNICAZIONI (IDCOMUNE, ID) ; 
ALTER TABLE TIPIMOVIMENTO_COMUNICAZIONI ADD CONSTRAINT TIPIMOVIMENTO_COMUNICAZIONI_PK PRIMARY KEY (IDCOMUNE, ID);

ALTER TABLE TIPIMOVIMENTO_COMUNICAZIONI 
ADD CONSTRAINT FK_TIPIMOV_COM_TIPIMOV FOREIGN KEY (IDCOMUNE, FK_TIPOMOV)
REFERENCES TIPIMOVIMENTO (IDCOMUNE, TIPOMOVIMENTO);


ALTER TABLE TIPIMOVIMENTO_COMUNICAZIONI 
ADD CONSTRAINT FK_TIPIMOV_COM_MAILTIPO FOREIGN KEY (IDCOMUNE, FK_MAILTIPO)
REFERENCES MAILTIPO (IDCOMUNE, CODICEMAIL);

ALTER TABLE RESPONSABILI ADD FLAG_EDITLABEL NUMERIC(1,0) DEFAULT 0;

alter table INVENTARIOPROCEDIMENTI add FLAG_PUBBLICA NUMERIC(1,0);
alter table TIPIENDO add FLAG_PUBBLICA NUMERIC(1,0);
alter table TIPIFAMIGLIEENDO add FLAG_PUBBLICA NUMERIC(1,0);

alter table TIPISOGGETTO add FLAG_MOSTRA_DETT_ISTANZA numeric(1,0) default 0;

CREATE OR REPLACE ALGORITHM=MERGE VIEW VW_BATCH_SCADENZARIO AS 
SELECT
  MDF.CODICEMOVIMENTO       AS ID,
  SYSDATE()                 AS DATAELABORAZIONE,
  MDF.IDCOMUNE              AS IDCOMUNE,
  ISTANZE.SOFTWARE          AS SOFTWARE,
  MDF.CODICEISTANZA         AS CODICEISTANZA,
  MF.CODICEMOVIMENTO        AS CODICEMOVIMENTO,
  IFNULL(MF.MOVIMENTO,TMF.MOVIMENTO) AS DESCRMOVIMENTO,
  MDF.TIPOMOVIMENTO         AS TIPOMOVIMENTODAFARE,
  IFNULL(MDF.MOVIMENTO,TM.MOVIMENTO) AS DESCRMOVIMENTODAFARE,
  MDF.CODICEINVENTARIO      AS CODICEINVENTARIO,
  MDF.CODICEAMMINISTRAZIONE AS CODICEAMMINISTRAZIONE,
  MDF.DATA_SCADENZA         AS DATASCADENZA
FROM 
                MOVIMENTI MDF
                               INNER JOIN ISTANZE ON ISTANZE.IDCOMUNE = MDF.IDCOMUNE AND ISTANZE.CODICEISTANZA = MDF.CODICEISTANZA
                               INNER JOIN TIPIMOVIMENTO TM ON TM.IDCOMUNE = MDF.IDCOMUNE AND TM.TIPOMOVIMENTO = MDF.TIPOMOVIMENTO
                               LEFT JOIN MOVIMENTI_CONTROMOVIMENTI MCM ON MCM.IDCOMUNE = MDF.IDCOMUNE AND MCM.CODICECONTROMOVIMENTO = MDF.CODICEMOVIMENTO
                               LEFT JOIN MOVIMENTI MF ON MF.IDCOMUNE = MCM.IDCOMUNE AND MF.CODICEMOVIMENTO = MCM.CODICEMOVIMENTO
                               LEFT JOIN TIPIMOVIMENTO TMF ON TMF.IDCOMUNE = MF.IDCOMUNE AND TMF.TIPOMOVIMENTO = MF.TIPOMOVIMENTO
WHERE 
                MDF.DATA IS NULL AND 
                (MDF.FLAG_DISABILITATO IS NULL OR MDF.FLAG_DISABILITATO = 0);

                
INSERT INTO verticalizzazioniparametribase(modulo, parametro, descrizione) VALUES (
  'SIT_LDP',
  'URL_PRESENTAZIONE_DOMANDA',
  'Url per l''inserimento dei dati nel SIT LDP (es. http://siena.ldpgis.it/presentazione_pratiche_edilizie_online/index.php?identificativo_temporaneo={idDomanda}&token_auth={token} )'
);