create index IDX_FODOMANDE_OGG_001 ON FO_DOMANDE(IDCOMUNE, CODICEOGGETTO);
create index IDX_FODOMANDE_OGG_002 ON FO_DOMANDE(IDCOMUNE, CODICEOGGETTO_CART);
create index IDX_FODOMANDEOGG_OGG_001 ON FO_DOMANDE_OGGETTI(IDCOMUNE, CODICEOGGETTO);

ALTER TABLE COMUNIASSOCIATISOFTWARE  MODIFY (SI_INTESTAZIONE1 VARCHAR2(500 CHAR) );
ALTER TABLE COMUNIASSOCIATISOFTWARE  MODIFY (SI_INTESTAZIONE2 VARCHAR2(500 CHAR) );
ALTER TABLE COMUNIASSOCIATISOFTWARE  MODIFY (SI_INTESTAZIONE3 VARCHAR2(500 CHAR) );
ALTER TABLE COMUNIASSOCIATISOFTWARE  MODIFY (SI_PDP1 VARCHAR2(500 CHAR) );
ALTER TABLE COMUNIASSOCIATISOFTWARE  MODIFY (SI_PDP2 VARCHAR2(500 CHAR) );
ALTER TABLE COMUNIASSOCIATI  MODIFY (SI_INTESTAZIONE1 VARCHAR2(500 CHAR) );
ALTER TABLE COMUNIASSOCIATI  MODIFY (SI_INTESTAZIONE2 VARCHAR2(500 CHAR) );
ALTER TABLE COMUNIASSOCIATI  MODIFY (SI_INTESTAZIONE3 VARCHAR2(500 CHAR) );
ALTER TABLE COMUNIASSOCIATI  MODIFY (SI_PDP1 VARCHAR2(500 CHAR) );
ALTER TABLE COMUNIASSOCIATI  MODIFY (SI_PDP2 VARCHAR2(500 CHAR) );

ALTER TABLE ALBEROPROC_DOCUMENTI ADD (FO_DIMENSIONE_MASSIMA NUMBER(10,0));
ALTER TABLE ALBEROPROC_DOCUMENTI ADD (FO_ESTENSIONI_AMMESSE  VARCHAR2(256));

ALTER TABLE ALLEGATI ADD (FO_DIMENSIONE_MASSIMA NUMBER(10,0));
ALTER TABLE ALLEGATI ADD (FO_ESTENSIONI_AMMESSE VARCHAR2(256));

ALTER TABLE FO_ARCONFIGURAZIONE ADD (DIMENSIONE_MASSIMA NUMBER(10,0));
ALTER TABLE FO_ARCONFIGURAZIONE ADD (ESTENSIONI_AMMESSE VARCHAR2(256));


CREATE TABLE FO_FORMATI_DOCUMENTI (
    IDCOMUNE VARCHAR2(6),
    ID NUMBER(10,0),
    SOFTWARE VARCHAR2(2),
    FORMATO VARCHAR2(50) NOT NULL,
    DIMENSIONE_MAX_PAGINA NUMBER(6,0) NOT NULL
);

ALTER TABLE FO_FORMATI_DOCUMENTI ADD CONSTRAINT PK_FO_FORMATI_DOCUMENTI PRIMARY KEY (IDCOMUNE, ID);
ALTER TABLE FO_FORMATI_DOCUMENTI ADD CONSTRAINT FK_FO_FORM_DOC_SW FOREIGN KEY (SOFTWARE) REFERENCES SOFTWARE(CODICE);

ALTER TABLE inventarioprocdyn2modellit ADD FLAG_FVG_MOSTRA_NEL_BACK NUMBER(1,0);

alter table layouttestibase modify testo varchar2(1000);
alter table layouttesti modify nuovotesto varchar2(1000);
