ALTER TABLE COMMEDILIZIE_VOTAZIONI ADD NUMEROPROTOCOLLO VARCHAR2(30 CHAR);
ALTER TABLE COMMEDILIZIE_VOTAZIONI ADD DATAPROTOCOLLO DATE;
ALTER TABLE COMMEDILIZIE_VOTAZIONI ADD FKIDPROTOCOLLO VARCHAR2(400 CHAR);


ALTER TABLE COMMEDILIZIE_APPELLO ADD PIN VARCHAR2(10 CHAR);
