//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Init.Sigepro.FrontEnd.AppLogic.WsOneri {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OnereDto", Namespace="http://schemas.datacontract.org/2004/07/Init.SIGePro.Manager.DTO.Oneri")]
    [System.SerializableAttribute()]
    public partial class OnereDto : Init.Sigepro.FrontEnd.AppLogic.WsOneri.CausaleOnereDto {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CampoDinamicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodiceInterventoOEndoOrigineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float ImportoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InterventoOEndoOrigineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrigineOnereField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CampoDinamico {
            get {
                return this.CampoDinamicoField;
            }
            set {
                if ((this.CampoDinamicoField.Equals(value) != true)) {
                    this.CampoDinamicoField = value;
                    this.RaisePropertyChanged("CampoDinamico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodiceInterventoOEndoOrigine {
            get {
                return this.CodiceInterventoOEndoOrigineField;
            }
            set {
                if ((this.CodiceInterventoOEndoOrigineField.Equals(value) != true)) {
                    this.CodiceInterventoOEndoOrigineField = value;
                    this.RaisePropertyChanged("CodiceInterventoOEndoOrigine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Importo {
            get {
                return this.ImportoField;
            }
            set {
                if ((this.ImportoField.Equals(value) != true)) {
                    this.ImportoField = value;
                    this.RaisePropertyChanged("Importo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InterventoOEndoOrigine {
            get {
                return this.InterventoOEndoOrigineField;
            }
            set {
                if ((object.ReferenceEquals(this.InterventoOEndoOrigineField, value) != true)) {
                    this.InterventoOEndoOrigineField = value;
                    this.RaisePropertyChanged("InterventoOEndoOrigine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Note {
            get {
                return this.NoteField;
            }
            set {
                if ((object.ReferenceEquals(this.NoteField, value) != true)) {
                    this.NoteField = value;
                    this.RaisePropertyChanged("Note");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrigineOnere {
            get {
                return this.OrigineOnereField;
            }
            set {
                if ((object.ReferenceEquals(this.OrigineOnereField, value) != true)) {
                    this.OrigineOnereField = value;
                    this.RaisePropertyChanged("OrigineOnere");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseDtoOfintstring", Namespace="http://schemas.datacontract.org/2004/07/Init.SIGePro.Manager.DTO")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.Sigepro.FrontEnd.AppLogic.WsOneri.CausaleOnereDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.Sigepro.FrontEnd.AppLogic.WsOneri.OnereDto))]
    public partial class BaseDtoOfintstring : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodiceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescrizioneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codice {
            get {
                return this.CodiceField;
            }
            set {
                if ((this.CodiceField.Equals(value) != true)) {
                    this.CodiceField = value;
                    this.RaisePropertyChanged("Codice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descrizione {
            get {
                return this.DescrizioneField;
            }
            set {
                if ((object.ReferenceEquals(this.DescrizioneField, value) != true)) {
                    this.DescrizioneField = value;
                    this.RaisePropertyChanged("Descrizione");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CausaleOnereDto", Namespace="http://schemas.datacontract.org/2004/07/Init.SIGePro.Manager.DTO.Oneri")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.Sigepro.FrontEnd.AppLogic.WsOneri.OnereDto))]
    public partial class CausaleOnereDto : Init.Sigepro.FrontEnd.AppLogic.WsOneri.BaseDtoOfintstring {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContoDto", Namespace="http://schemas.datacontract.org/2004/07/Init.SIGePro.Manager.DTO.Oneri")]
    [System.SerializableAttribute()]
    public partial class ContoDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodiceMappaturaNodoPagamentiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodiceSottoContoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IvaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroAccertamentoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodiceMappaturaNodoPagamenti {
            get {
                return this.CodiceMappaturaNodoPagamentiField;
            }
            set {
                if ((object.ReferenceEquals(this.CodiceMappaturaNodoPagamentiField, value) != true)) {
                    this.CodiceMappaturaNodoPagamentiField = value;
                    this.RaisePropertyChanged("CodiceMappaturaNodoPagamenti");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodiceSottoConto {
            get {
                return this.CodiceSottoContoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodiceSottoContoField, value) != true)) {
                    this.CodiceSottoContoField = value;
                    this.RaisePropertyChanged("CodiceSottoConto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Conto {
            get {
                return this.ContoField;
            }
            set {
                if ((object.ReferenceEquals(this.ContoField, value) != true)) {
                    this.ContoField = value;
                    this.RaisePropertyChanged("Conto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Iva {
            get {
                return this.IvaField;
            }
            set {
                if ((this.IvaField.Equals(value) != true)) {
                    this.IvaField = value;
                    this.RaisePropertyChanged("Iva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroAccertamento {
            get {
                return this.NumeroAccertamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroAccertamentoField, value) != true)) {
                    this.NumeroAccertamentoField = value;
                    this.RaisePropertyChanged("NumeroAccertamento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsOneri.IWsOneriService")]
    public interface IWsOneriService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsOneriService/GetListaOneriDaIdInterventoECodiciEndo", ReplyAction="http://tempuri.org/IWsOneriService/GetListaOneriDaIdInterventoECodiciEndoResponse" +
            "")]
        Init.Sigepro.FrontEnd.AppLogic.WsOneri.OnereDto[] GetListaOneriDaIdInterventoECodiciEndo(string token, int codiceIntervento, int[] listaIdEndo, string codiceComuneAssociato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsOneriService/GetContoDaIdCausaleOnere", ReplyAction="http://tempuri.org/IWsOneriService/GetContoDaIdCausaleOnereResponse")]
        Init.Sigepro.FrontEnd.AppLogic.WsOneri.ContoDto GetContoDaIdCausaleOnere(string token, string software, string codiceComune, int idCausale);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWsOneriServiceChannel : Init.Sigepro.FrontEnd.AppLogic.WsOneri.IWsOneriService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsOneriServiceClient : System.ServiceModel.ClientBase<Init.Sigepro.FrontEnd.AppLogic.WsOneri.IWsOneriService>, Init.Sigepro.FrontEnd.AppLogic.WsOneri.IWsOneriService {
        
        public WsOneriServiceClient() {
        }
        
        public WsOneriServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsOneriServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsOneriServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsOneriServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Init.Sigepro.FrontEnd.AppLogic.WsOneri.OnereDto[] GetListaOneriDaIdInterventoECodiciEndo(string token, int codiceIntervento, int[] listaIdEndo, string codiceComuneAssociato) {
            return base.Channel.GetListaOneriDaIdInterventoECodiciEndo(token, codiceIntervento, listaIdEndo, codiceComuneAssociato);
        }
        
        public Init.Sigepro.FrontEnd.AppLogic.WsOneri.ContoDto GetContoDaIdCausaleOnere(string token, string software, string codiceComune, int idCausale) {
            return base.Channel.GetContoDaIdCausaleOnere(token, software, codiceComune, idCausale);
        }
    }
}
