//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Init.Sigepro.FrontEnd.Reserved.InserimentoIstanza.ricerca_pratiche
{


    public partial class ricerca_pratiche
    {

        /// <summary>
        /// multiView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.MultiView multiView;

        /// <summary>
        /// ricercaView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.View ricercaView;

        /// <summary>
        /// txtNumeroProtocollo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.TextBox txtNumeroProtocollo;

        /// <summary>
        /// txtDataProtocollo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.DateTextBox txtDataProtocollo;

        /// <summary>
        /// cmdCercaProtocollo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button cmdCercaProtocollo;

        /// <summary>
        /// cmdIgnoraRicerca control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton cmdIgnoraRicerca;

        /// <summary>
        /// txtNumeroIstanza control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.TextBox txtNumeroIstanza;

        /// <summary>
        /// cmdCercaPratica control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button cmdCercaPratica;

        /// <summary>
        /// cmdIgnoraRicerca2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton cmdIgnoraRicerca2;

        /// <summary>
        /// dettaglioView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.View dettaglioView;

        /// <summary>
        /// ricercapratichedettaglio control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.Reserved.InserimentoIstanza.ricerca_pratiche.ricerca_pratiche_dettaglio ricercapratichedettaglio;

        /// <summary>
        /// cmdMantieniCollegamento control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button cmdMantieniCollegamento;

        /// <summary>
        /// cmdAnnullaCollegamento control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button cmdAnnullaCollegamento;

        /// <summary>
        /// cmdCopiaDati control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button cmdCopiaDati;

        /// <summary>
        /// cmdNuovaRicerca2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button cmdNuovaRicerca2;

        /// <summary>
        /// bmConfermaEliminazioneCollegamento control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Init.Sigepro.FrontEnd.WebControls.FormControls.BootstrapModal bmConfermaEliminazioneCollegamento;

        /// <summary>
        /// ltrTestoConfermaAnnullamentoCollegamento control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltrTestoConfermaAnnullamentoCollegamento;

        /// <summary>
        /// nonTrovataView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.View nonTrovataView;

        /// <summary>
        /// ltrErrorePraticaNonTrovata control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltrErrorePraticaNonTrovata;

        /// <summary>
        /// cmdNuovaRicerca control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button cmdNuovaRicerca;

        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new Init.Sigepro.FrontEnd.Reserved.InserimentoIstanza.InserimentoIstanzaMaster Master
        {
            get
            {
                return ((Init.Sigepro.FrontEnd.Reserved.InserimentoIstanza.InserimentoIstanzaMaster)(base.Master));
            }
        }
    }
}
