ALTER TABLE MOVIMENTIALLEGATI MODIFY ID_BASE VARCHAR(600);

ALTER TABLE MERCATI_FORMULE_CALCOLO ADD CONTESTO VARCHAR(20);

UPDATE MERCATI_FORMULE_CALCOLO SET CONTESTO = 'PRESENZA' WHERE CONTESTO IS NULL;

ALTER TABLE MERCATI_FORMULE_CALCOLO MODIFY CONTESTO VARCHAR(20) NOT NULL;

ALTER TABLE BOLL_GEST_DETT_AUTORIZZ ADD FK_BOLLGEST_ID DECIMAL(4,0);
ALTER TABLE BOLL_GEST_DETT_RATE ADD FK_BOLLGEST_ID DECIMAL(4,0);
ALTER TABLE BOLL_GEST_ISTANZEONERI ADD FK_BOLLGEST_ID DECIMAL(4,0);
ALTER TABLE BOLL_GEST_MERCATI_DETT ADD FK_BOLLGEST_ID DECIMAL(4,0);
ALTER TABLE BOLL_GEST_ONERI_SEQUENCE ADD FK_BOLLGEST_ID DECIMAL(4,0);

ALTER TABLE BOLL_GEST_DETT_AUTORIZZ ADD CONSTRAINT FK_DETAUT_BLLGSTTEST FOREIGN KEY (IDCOMUNE, FK_BOLLGEST_ID) REFERENCES BOLL_GEST_TESTATA(IDCOMUNE, ID);
ALTER TABLE BOLL_GEST_DETT_RATE ADD CONSTRAINT FK_DETRAT_BLLGSTTEST FOREIGN KEY (IDCOMUNE, FK_BOLLGEST_ID) REFERENCES BOLL_GEST_TESTATA(IDCOMUNE, ID);
ALTER TABLE BOLL_GEST_ISTANZEONERI ADD CONSTRAINT FK_ISTONE_BLLGSTTEST FOREIGN KEY (IDCOMUNE, FK_BOLLGEST_ID) REFERENCES BOLL_GEST_TESTATA(IDCOMUNE, ID);
ALTER TABLE BOLL_GEST_MERCATI_DETT ADD CONSTRAINT FK_MERDET_BLLGSTTEST FOREIGN KEY (IDCOMUNE, FK_BOLLGEST_ID) REFERENCES BOLL_GEST_TESTATA(IDCOMUNE, ID);
ALTER TABLE BOLL_GEST_ONERI_SEQUENCE ADD CONSTRAINT FK_ONESEQ_BLLGSTTEST FOREIGN KEY (IDCOMUNE, FK_BOLLGEST_ID) REFERENCES BOLL_GEST_TESTATA(IDCOMUNE, ID);

CREATE INDEX IDX_DETAUT_BLLGSTTEST_001 ON BOLL_GEST_DETT_AUTORIZZ(IDCOMUNE,FK_BOLLGEST_ID);
CREATE INDEX IDX_DETRAT_BLLGSTTEST_001 ON BOLL_GEST_DETT_RATE(IDCOMUNE,FK_BOLLGEST_ID);
CREATE INDEX IDX_ISTONE_BLLGSTTEST_001 ON BOLL_GEST_ISTANZEONERI(IDCOMUNE,FK_BOLLGEST_ID);
CREATE INDEX IDX_MERDET_BLLGSTTEST_001 ON BOLL_GEST_MERCATI_DETT(IDCOMUNE,FK_BOLLGEST_ID);
CREATE INDEX IDX_ONESEQ_BLLGSTTEST_001 ON BOLL_GEST_ONERI_SEQUENCE(IDCOMUNE,FK_BOLLGEST_ID);

UPDATE BOLL_GEST_DETT_AUTORIZZ INNER JOIN BOLL_GEST_DETTAGLIO ON BOLL_GEST_DETT_AUTORIZZ.IDCOMUNE = BOLL_GEST_DETTAGLIO.IDCOMUNE AND BOLL_GEST_DETT_AUTORIZZ.FK_BOLLGESTDET_ID = BOLL_GEST_DETTAGLIO.ID SET BOLL_GEST_DETT_AUTORIZZ.FK_BOLLGEST_ID = BOLL_GEST_DETTAGLIO.FK_BOLLGEST_ID WHERE BOLL_GEST_DETT_AUTORIZZ.FK_BOLLGEST_ID IS NULL;
UPDATE BOLL_GEST_DETT_RATE INNER JOIN BOLL_GEST_DETTAGLIO ON BOLL_GEST_DETT_RATE.IDCOMUNE = BOLL_GEST_DETTAGLIO.IDCOMUNE AND BOLL_GEST_DETT_RATE.FK_BOLLGESTDET_ID = BOLL_GEST_DETTAGLIO.ID SET BOLL_GEST_DETT_RATE.FK_BOLLGEST_ID = BOLL_GEST_DETTAGLIO.FK_BOLLGEST_ID WHERE BOLL_GEST_DETT_RATE.FK_BOLLGEST_ID IS NULL;
UPDATE BOLL_GEST_ISTANZEONERI INNER JOIN BOLL_GEST_DETTAGLIO ON BOLL_GEST_ISTANZEONERI.IDCOMUNE = BOLL_GEST_DETTAGLIO.IDCOMUNE AND BOLL_GEST_ISTANZEONERI.FK_BOLLGESTDET_ID = BOLL_GEST_DETTAGLIO.ID SET BOLL_GEST_ISTANZEONERI.FK_BOLLGEST_ID = BOLL_GEST_DETTAGLIO.FK_BOLLGEST_ID WHERE BOLL_GEST_ISTANZEONERI.FK_BOLLGEST_ID IS NULL;
UPDATE BOLL_GEST_MERCATI_DETT INNER JOIN BOLL_GEST_DETT_AUTORIZZ ON BOLL_GEST_MERCATI_DETT.IDCOMUNE = BOLL_GEST_DETT_AUTORIZZ.IDCOMUNE AND BOLL_GEST_MERCATI_DETT.FK_ID_GEST_AUTORIZZAZIONI = BOLL_GEST_DETT_AUTORIZZ.ID INNER JOIN BOLL_GEST_DETTAGLIO ON BOLL_GEST_DETT_AUTORIZZ.IDCOMUNE = BOLL_GEST_DETTAGLIO.IDCOMUNE AND BOLL_GEST_DETT_AUTORIZZ.FK_BOLLGESTDET_ID = BOLL_GEST_DETTAGLIO.ID SET BOLL_GEST_MERCATI_DETT.FK_BOLLGEST_ID = BOLL_GEST_DETTAGLIO.FK_BOLLGEST_ID WHERE BOLL_GEST_MERCATI_DETT.FK_BOLLGEST_ID IS NULL;
UPDATE BOLL_GEST_ONERI_SEQUENCE INNER JOIN BOLL_GEST_DETTAGLIO ON BOLL_GEST_ONERI_SEQUENCE.IDCOMUNE = BOLL_GEST_DETTAGLIO.IDCOMUNE AND BOLL_GEST_ONERI_SEQUENCE.ID_BOLLEGEST_DETT = BOLL_GEST_DETTAGLIO.ID  SET BOLL_GEST_ONERI_SEQUENCE.FK_BOLLGEST_ID = BOLL_GEST_DETTAGLIO.FK_BOLLGEST_ID WHERE BOLL_GEST_ONERI_SEQUENCE.FK_BOLLGEST_ID IS NULL;

ALTER TABLE BOLL_GEST_DETT_AUTORIZZ MODIFY FK_BOLLGEST_ID DECIMAL(4,0) NOT NULL;
ALTER TABLE BOLL_GEST_DETT_RATE MODIFY FK_BOLLGEST_ID DECIMAL(4,0) NOT NULL;
ALTER TABLE BOLL_GEST_ISTANZEONERI MODIFY FK_BOLLGEST_ID DECIMAL(4,0) NOT NULL;
ALTER TABLE BOLL_GEST_MERCATI_DETT MODIFY FK_BOLLGEST_ID DECIMAL(4,0) NOT NULL;
ALTER TABLE BOLL_GEST_ONERI_SEQUENCE MODIFY FK_BOLLGEST_ID DECIMAL(4,0) NOT NULL;

CREATE TABLE MESSAGGI_RABBIT(
IDCOMUNE VARCHAR(6) NOT NULL,
GUID VARCHAR(40) NOT NULL,
TOPIC VARCHAR(50) NOT NULL,
MESSAGGIO LONGTEXT NOT NULL,
DATA_TRASMISSIONE DATETIME
)ENGINE=INNODB DEFAULT CHARSET=UTF8;

ALTER TABLE MESSAGGI_RABBIT ADD CONSTRAINT PK_MESSAGGIRABBIT PRIMARY KEY (IDCOMUNE,GUID);


CREATE INDEX idx_messaggirabbit_001 ON MESSAGGI_RABBIT (idcomune,guid);

create TABLE TIPIMOVIMENTO_RABBIT (
IDCOMUNE VARCHAR(6) NOT NULL,
fk_tipimovimento VARCHAR(8) not null,
fk_mailtipo numeric(4,0) not null,
topic VARCHAR(50)
)ENGINE=INNODB DEFAULT CHARSET=UTF8;

ALTER TABLE TIPIMOVIMENTO_RABBIT ADD CONSTRAINT PK_TIPIMOVRABBIT  PRIMARY KEY (IDCOMUNE,fk_tipimovimento,fk_mailtipo);
ALTER TABLE TIPIMOVIMENTO_RABBIT ADD CONSTRAINT FK_TIPIMOV_TIPIMOVRABBIT FOREIGN KEY (IDCOMUNE,fk_tipimovimento) REFERENCES tipimovimento (IDCOMUNE,TIPOMOVIMENTO);
ALTER TABLE TIPIMOVIMENTO_RABBIT ADD CONSTRAINT FK_MAILTIPO_TIPIMOVRABBIT FOREIGN KEY (IDCOMUNE,fk_mailtipo) REFERENCES mailtipo(IDCOMUNE,CODICEMAIL);

CREATE TABLE BOLL_CFG_TIPO_METADATI(IDCOMUNE VARCHAR(6) NOT NULL, ID DECIMAL(10,0) NOT NULL, CODICECOMUNE VARCHAR(5) NULL, FK_BOLLCFGTIPO_ID DECIMAL(4,0) NOT NULL, CHIAVE VARCHAR(60) NOT NULL, VALORE VARCHAR(500) NOT NULL) ENGINE=INNODB DEFAULT CHARSET=utf8;
ALTER TABLE BOLL_CFG_TIPO_METADATI ADD CONSTRAINT PK_BOLLCFGTIPOMETADATI PRIMARY KEY(IDCOMUNE,ID);
ALTER TABLE BOLL_CFG_TIPO_METADATI ADD CONSTRAINT FK_BOLLCFGTIPOMETADATI_001 FOREIGN KEY(IDCOMUNE,FK_BOLLCFGTIPO_ID) REFERENCES BOLL_CFG_TIPO(IDCOMUNE,ID);
ALTER TABLE BOLL_CFG_TIPO_METADATI ADD CONSTRAINT FK_BOLLCFGTIPOMETADATI_002 FOREIGN KEY(CODICECOMUNE) REFERENCES COMUNI(CODICECOMUNE);
CREATE INDEX IDX_BOLLCFGTIPOMETADATI_001 ON BOLL_CFG_TIPO_METADATI(IDCOMUNE,FK_BOLLCFGTIPO_ID);
CREATE INDEX IDX_BOLLCFGTIPOMETADATI_002 ON BOLL_CFG_TIPO_METADATI(CODICECOMUNE);
CREATE TABLE MASSIVE_TPROT_METADATI(IDCOMUNE VARCHAR(6) NOT NULL, ID DECIMAL(10,0) NOT NULL, FK_MASSIVETPROT_ID DECIMAL(6,0) NOT NULL, FKID_TESTATA DECIMAL(6,0) NOT NULL, CODICECOMUNE VARCHAR(5) NULL, CHIAVE VARCHAR(60) NOT NULL, VALORE VARCHAR(500) NULL) ENGINE=INNODB DEFAULT CHARSET=utf8;
ALTER TABLE MASSIVE_TPROT_METADATI ADD CONSTRAINT PK_MASSIVETPROTMETADATI PRIMARY KEY(IDCOMUNE,ID,CHIAVE);
ALTER TABLE MASSIVE_TPROT_METADATI ADD CONSTRAINT FK_MASSIVETPROTMETADATI_001 FOREIGN KEY(IDCOMUNE,FK_MASSIVETPROT_ID) REFERENCES MASSIVE_T_PROTOCOLLO(IDCOMUNE,ID);
ALTER TABLE MASSIVE_TPROT_METADATI ADD CONSTRAINT FK_MASSIVETPROTMETADATI_002 FOREIGN KEY(IDCOMUNE,FKID_TESTATA) REFERENCES MASSIVE_TESTATA(IDCOMUNE,ID);
ALTER TABLE MASSIVE_TPROT_METADATI ADD CONSTRAINT FK_MASSIVETPROTMETADATI_003 FOREIGN KEY(CODICECOMUNE) REFERENCES COMUNI(CODICECOMUNE);
CREATE INDEX IDX_MASSIVETPROTMETADATI_001 ON MASSIVE_TPROT_METADATI(IDCOMUNE,FK_MASSIVETPROT_ID);
CREATE INDEX IDX_MASSIVETPROTMETADATI_002 ON MASSIVE_TPROT_METADATI(IDCOMUNE,FKID_TESTATA);


ALTER TABLE tipisoggetto ADD descrizione_estesa VARCHAR(400);
ALTER TABLE alberoproc_tipisoggetto ADD override_descrizione VARCHAR(400);
ALTER TABLE alberoproc_tipisoggetto ADD obbligatorio NUMERIC(1,0);
ALTER TABLE alberoproc_tipisoggetto ADD occorrenze_max NUMERIC(2,0);


UPDATE alberoproc_tipisoggetto INNER JOIN tipisoggetto ON alberoproc_tipisoggetto.IDCOMUNE = tipisoggetto.IDCOMUNE AND alberoproc_tipisoggetto.FK_CODICETIPOSOGGETTO = tipisoggetto.CODICETIPOSOGGETTO SET alberoproc_tipisoggetto.obbligatorio = COALESCE(tipisoggetto.FO_OBBLIGATORIO,0) WHERE alberoproc_tipisoggetto.obbligatorio IS NULL;



ALTER TABLE alberoproc_tipisoggetto MODIFY obbligatorio NUMERIC(1,0) DEFAULT 0 NOT NULL;

ALTER TABLE PROTOCOLLO MODIFY ORDINE NUMERIC(3,0);



ALTER TABLE tipimovimento_app_io_servizi ADD TEMPLATE_OGGETTO VARCHAR(120);
ALTER TABLE tipimovimento_app_io_servizi ADD TEMPLATE_MESSAGGIO LONGTEXT;



CREATE TABLE TIPIMOV_APPIOSERVIZI_INT (
  IDCOMUNE VARCHAR(6) NOT NULL,
  TIPOMOVIMENTO VARCHAR(8) NOT NULL,
  FK_ALBEROPROC_SCID NUMERIC(10,0) NOT NULL,
  IDENTIFICATIVO_SERVIZIO VARCHAR(50) NOT NULL,
  TEMPLATE_OGGETTO VARCHAR(120),
  TEMPLATE_MESSAGGIO LONGTEXT
) ENGINE=INNODB DEFAULT CHARSET=utf8;


ALTER TABLE TIPIMOV_APPIOSERVIZI_INT ADD CONSTRAINT PK_APPIOSERVINT PRIMARY KEY (IDCOMUNE,TIPOMOVIMENTO,FK_ALBEROPROC_SCID,IDENTIFICATIVO_SERVIZIO); 
ALTER TABLE TIPIMOV_APPIOSERVIZI_INT ADD CONSTRAINT FK_TIPIMOVIOSERVINT_SERV FOREIGN KEY (IDCOMUNE, IDENTIFICATIVO_SERVIZIO) REFERENCES APP_IO_SERVIZI (IDCOMUNE, IDENTIFICATIVO_SERVIZIO);
ALTER TABLE TIPIMOV_APPIOSERVIZI_INT ADD CONSTRAINT FK_TIPIMOVIOSERVINT_TMOV FOREIGN KEY (IDCOMUNE, TIPOMOVIMENTO) REFERENCES TIPIMOVIMENTO (IDCOMUNE, TIPOMOVIMENTO);
ALTER TABLE TIPIMOV_APPIOSERVIZI_INT ADD CONSTRAINT FK_TIPIMOVIOSERVINT_AP FOREIGN KEY (IDCOMUNE, FK_ALBEROPROC_SCID) REFERENCES ALBEROPROC(IDCOMUNE, SC_ID);



CREATE TABLE TIPIMOV_APPIOSERVIZI_ENDO (
  IDCOMUNE VARCHAR(6) NOT NULL,
  TIPOMOVIMENTO VARCHAR(8) NOT NULL,
  CODICEINVENTARIO NUMERIC(10,0) NOT NULL,
  IDENTIFICATIVO_SERVIZIO VARCHAR(50) NOT NULL,
  TEMPLATE_OGGETTO VARCHAR(120),
  TEMPLATE_MESSAGGIO LONGTEXT
) ENGINE=INNODB DEFAULT CHARSET=utf8;


ALTER TABLE TIPIMOV_APPIOSERVIZI_ENDO ADD CONSTRAINT PK_APPIOSERVENDO PRIMARY KEY (IDCOMUNE,TIPOMOVIMENTO,CODICEINVENTARIO,IDENTIFICATIVO_SERVIZIO); 
ALTER TABLE TIPIMOV_APPIOSERVIZI_ENDO ADD CONSTRAINT FK_TIPIMOVIOSERVENDO_SERV FOREIGN KEY (IDCOMUNE, IDENTIFICATIVO_SERVIZIO) REFERENCES APP_IO_SERVIZI (IDCOMUNE, IDENTIFICATIVO_SERVIZIO);
ALTER TABLE TIPIMOV_APPIOSERVIZI_ENDO ADD CONSTRAINT FK_TIPIMOVIOSERVENDO_TMOV FOREIGN KEY (IDCOMUNE, TIPOMOVIMENTO) REFERENCES TIPIMOVIMENTO (IDCOMUNE, TIPOMOVIMENTO);
ALTER TABLE TIPIMOV_APPIOSERVIZI_ENDO ADD CONSTRAINT FK_TIPIMOVIOSERVENDO_ENDO FOREIGN KEY (IDCOMUNE, CODICEINVENTARIO) REFERENCES INVENTARIOPROCEDIMENTI(IDCOMUNE, CODICEINVENTARIO);
