
ALTER TABLE MOVIMENTI_ZIP_LOGICO_TESTATA ADD CODICEOGGETTO_DOC_ALL numeric(10,0);
ALTER TABLE MOVIMENTI_ZIP_LOGICO_TESTATA ADD CONSTRAINT FK_MOVZIPLOGT_OGGETTI FOREIGN KEY(IDCOMUNE,CODICEOGGETTO_DOC_ALL)REFERENCES OGGETTI(IDCOMUNE,CODICEOGGETTO);


ALTER TABLE ESPORTAZIONI ADD SOFTWARE VARCHAR(2);
ALTER TABLE ESPORTAZIONI ADD CONSTRAINT FK_ESPORTAZIONI_SOFTWARE FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);


UPDATE movimenti_zip_logico
INNER JOIN movimentiallegati ON
movimentiallegati.idcomune=movimenti_zip_logico.idcomune AND movimentiallegati.id=movimenti_zip_logico.FK_IDMOVIMENTIALLEGATI
SET movimenti_zip_logico.codiceoggetto=movimentiallegati.codiceoggetto
WHERE
movimenti_zip_logico.codiceoggetto IS NULL AND movimentiallegati.codiceoggetto IS NOT NULL AND movimenti_zip_logico.FK_IDMOVIMENTIALLEGATI IS NOT NULL;

CREATE TABLE SEGNAPOSTI(SEGNAPOSTO VARCHAR(64) NOT NULL, TEMPLATEBASE VARCHAR(4000) NOT NULL, TEMPLATEBASERTF VARCHAR(4000) NOT NULL) ENGINE=INNODB DEFAULT CHARSET=UTF8;
ALTER TABLE SEGNAPOSTI ADD CONSTRAINT SEGNAPOSTI_PK PRIMARY KEY(SEGNAPOSTO);
CREATE TABLE SEGNAPOSTIPERSONALIZZATI(IDCOMUNE VARCHAR(6) NOT NULL, SEGNAPOSTO VARCHAR(64) NOT NULL, SOFTWARE VARCHAR(2) NOT NULL, TEMPLATE VARCHAR(4000) NOT NULL, TEMPLATERTF VARCHAR(4000) NOT NULL) ENGINE=INNODB DEFAULT CHARSET=UTF8;
ALTER TABLE SEGNAPOSTIPERSONALIZZATI ADD CONSTRAINT SEGNAPOSTIPERSONALIZZATI_PK PRIMARY KEY(IDCOMUNE,SEGNAPOSTO,SOFTWARE);
ALTER TABLE SEGNAPOSTIPERSONALIZZATI ADD CONSTRAINT FK_SEGNAPOSTI FOREIGN KEY(SEGNAPOSTO) REFERENCES SEGNAPOSTI(SEGNAPOSTO);
ALTER TABLE SEGNAPOSTIPERSONALIZZATI ADD CONSTRAINT FK_SEGNAPOSTI_SOFTWARE FOREIGN KEY(SOFTWARE) REFERENCES SOFTWARE(CODICE);
 




