ALTER TABLE ALBEROPROC ADD FLAG_PROG_ATT_OSSERV NUMBER(1,0);
ALTER TABLE I_ATTIVITA ADD CODICE_OSSERVATORIO NUMBER(10,0);
ALTER TABLE I_ATTIVITA_SNAPSHOT ADD CODICE_OSSERVATORIO NUMBER(10,0);

ALTER TABLE PENTAHOCFG add USERID VARCHAR2(50);
ALTER TABLE PENTAHOCFG add PASSWORD VARCHAR2(50);
