<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup Label="Globals">
		<Configurations>Debug;Release;ReleaseFramework</Configurations>
		<Platforms>AnyCPU</Platforms>
		<TargetFramework>net48</TargetFramework>
		<RootNamespace>SIGePro.Manager.Framework</RootNamespace>
		<ImplicitUsings>disable</ImplicitUsings>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="System.Text.Json" Version="10.0.10" />
	</ItemGroup>


	<ItemGroup>
		<Reference Include="System.Configuration" />
		<Reference Include="System.Core" />
		<Reference Include="System.Web" />
		<Reference Include="System.Xml.Linq" />
		<Reference Include="System.Data.DataSetExtensions" />
		<Reference Include="Microsoft.CSharp" />
		<Reference Include="System.Data" />
		<Reference Include="System.Net.Http" />
		<Reference Include="System.Xml" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\SIGePro.Data\SIGePro.Data.csproj" />
		<ProjectReference Include="..\SIGePro.DatiDinamici\SIGePro.DatiDinamici.v1.csproj" />
		<ProjectReference Include="..\SIGePro.Manager.DTO\SIGePro.Manager.DTO.csproj" />
		<ProjectReference Include="..\SIGePro.Manager\SIGePro.Manager.csproj" />
		<ProjectReference Include="..\VBG.Shared.Infrastructure\VBG.Shared.Infrastructure.csproj" />
		<ProjectReference Include="..\PersonalLib2\PersonalLib2.csproj" />
	</ItemGroup>

</Project>