ALTER TABLE INVENTARIOPROCEDIMENTISOFTWARE ADD CODICEAMMINISTRAZIONE NUMERIC(10,0);
ALTER TABLE INVENTARIOPROCEDIMENTISOFTWARE ADD CONSTRAINT FK_INVPROCSOFT_AMM FOREIGN KEY (IDCOMUNE, CODICEAMMINISTRAZIONE) REFERENCES AMMINISTRAZIONI(IDCOMUNE, CODICEAMMINISTRAZIONE);
ALTER TABLE INVENTARIOPROCEDIMENTISOFTWARE ADD ID NUMERIC(6,0);
