ALTER TABLE INVENTARIOPROCEDIMENTISOFTWARE DROP FOREIGN KEY FK_INV_PROC_SOFT_INV_PROC;
ALTER TABLE INVENTARIOPROCEDIMENTISOFTWARE DROP PRIMARY KEY;
ALTER TABLE INVENTARIOPROCEDIMENTISOFTWARE MODIFY COLUMN ID NUMERIC(6,0) NOT NULL;
ALTER TABLE INVENTARIOPROCEDIMENTISOFTWARE ADD CONSTRAINT INVENTARIOPROCEDIMENTISOFTW_PK PRIMARY KEY (IDCOMUNE, ID);
ALTER TABLE INVENTARIOPROCEDIMENTISOFTWARE ADD CONSTRAINT FK_INV_PROC_SOFT_INV_PROC FOREIGN KEY (IDCOMUNE,CODICEINVENTARIO) REFERENCES INVENTARIOPROCEDIMENTI (IDCOMUNE,CODICEINVENTARIO);