CREATE OR REPLACE ALGORITHM=MERGE VIEW VW_ISTANZE_OPE_RUOLI (IDCOMUNE, IDRUOLO, CODICERESPONSABILE, CODICEISTANZA) AS SELECT RR.IDCOMUNE,RR.IDRUOLO,RR.CODICERESPONSABILE,IR.CODICEISTANZA FROM RESPONSABILIRUOLI RR INNER JOIN ISTANZERUOLI IR ON RR.IDCOMUNE =IR.IDCOMUNE AND RR.IDRUOLO = IR.IDRUOLO INNER JOIN RUOLI R ON R.IDCOMUNE=IR.IDCOMUNE AND R.ID =IR.IDRUOLO AND (R.READONLY=0 OR (R.FLAG_GESTMOVIMENTI=1 OR R.FLAG_DISGESTMOVAMM =1));
CREATE OR REPLACE ALGORITHM=TEMPTABLE VIEW VW_ISTANZECONCESSIONILISTA as 
SELECT 99999999 as PROGRESSIVO,AUTORIZZAZIONI.AUTORIZRESPONSABILE as CONC_AUTORIZRESPONSABILE,AUTORIZZAZIONI.IDCOMUNE,AUTORIZZAZIONI.FK_CAUSALE_ACQUISIZIONE as ICONC_CODICECAUSALE,ifnull(AUTORIZZAZIONI.DATA_CESSAZIONE,STR_TO_DATE('31/12/9999','%d/%m/%Y')) as DATA_STORICO,ISTANZE.SOFTWARE,ISTANZE.CODICEISTANZA as IST_CODICEISTANZA,ISTANZE.NUMEROISTANZA as IST_NUMEROISTANZA,ISTANZE.CODICERICHIEDENTE as IST_CODICERICHIEDENTE,AUTORIZZAZIONI.ID as CONC_ID,AUTORIZZAZIONI.AUTORIZNUMERO as CONC_NUMERO,AUTORIZZAZIONI.AUTORIZDATA as CONC_DATARILASCIO,AUTORIZZAZIONI.AUTORIZDATA as DATARILASCIO,AUTORIZZAZIONI.DATASCADENZA as CONC_DATASCADENZA,AUTORIZZAZIONI_CONCESSIONI.FK_TIPOCONCESSIONE as CONC_CODICETIPO,CONCESSIONITIPI.DESCRIZIONE as CONC_TIPO,AUTORIZZAZIONI_CONCESSIONI.STAGIONALEA as CONC_STAGIONALEA,AUTORIZZAZIONI_CONCESSIONI.STAGIONALEDA as CONC_STAGIONALEDA,AUTORIZZAZIONI.FLAG_ATTIVA as CONC_ATTIVA,AUTORIZZAZIONI.FK_CODICEANAGRAFE as CONC_CODICETITOLARE,AUTORIZZAZIONI.FKIDREGISTRO as CONC_FKIDREGISTRO,CONC_REGISTRO.TR_DESCRIZIONE as CONC_REGISTRO,CONCAT_WS('',TITOLARE.NOMINATIVO,' ',TITOLARE.NOME) as CONC_TITOLARE,TITOLARE.CODICEFISCALE as CONC_TIT_CF,TITOLARE.PARTITAIVA as CONC_TIT_PIVA,TITOLARE.TIPOANAGRAFE as CONC_TIT_TIPOANAGRAFE,AUT_COLLEGATA.AUTORIZNUMERO as AUT_NUMERO,AUT_COLLEGATA.AUTORIZDATA as AUT_DATA,AUT_COLLEGATA.AUTORIZDATA,AUT_COLLEGATA.FKIDREGISTRO as AUT_CODREGISTRO,TIPOLOGIAREGISTRI.TR_DESCRIZIONE as AUT_REGISTRO,CONCAT_WS('',IST_RICHIEDENTE.NOMINATIVO,' ',IST_RICHIEDENTE.NOME) as IST_NOMINATIVO,IST_RICHIEDENTE.TIPOANAGRAFE as IST_RIC_TIPOANAGRAFE,CONCAT_WS('',IST_AZIENDA.NOMINATIVO,' ',IST_AZIENDA.NOME) as IST_NOMINATIVOAZIENDA,IST_AZIENDA.TIPOANAGRAFE as IST_AZI_TIPOANAGRAFE,IST_RICHIEDENTE.CODICEFISCALE as IST_CODICEFISCALE,IST_RICHIEDENTE.PARTITAIVA as IST_PARTITAIVA,CAUS_ATTUALE.DESCRIZIONE as ICONC_CAUSALE,AUTORIZZAZIONI.FK_CAUSALE_CESSAZIONE as ICONC_CODICECAUSALESTORICO,CAUS_STORICO.DESCRIZIONE as ICONC_CAUSALESTORICO,AUTORIZZAZIONI_CONCESSIONI.FK_CODICEMERCATO as CONC_IDMERCATO,MERCATI.DESCRIZIONE as CONC_MERCATO,MERCATI.ATTIVO as MERC_ATTIVO,AUTORIZZAZIONI_CONCESSIONI.FK_IDPOSTEGGIO as CONC_IDPOSTEGGIO,MERCATI_D.CODICEPOSTEGGIO as CONC_POSTEGGIO,MERCATI_D.LARGHEZZA as CONC_POS_LARGHEZZA,MERCATI_D.LUNGHEZZA as CONC_POS_LUNGHEZZA,MERCATI_D.SUPERFICIE as CONC_POS_SUPERFICIE,MERCATI_D.FKCODICETIPOSPAZIO as POST_IDTIPOSPAZIO,POSTEGGITIPOSPAZIO.TIPOSPAZIO as POST_TIPOSPAZIO,AUTORIZZAZIONI_CONCESSIONI.FK_IDMERCATIUSO as CONC_IDMERCATIUSO,MERCATI_USO.DESCRIZIONE as CONC_DESCRIZIONEUSO,MERCATI_USO.PESO as PESO_MERCATO,MERCATI_USO.FKCODICEUSO as MERC_IDUSO,MERCATI_D.FKCODICESTRADARIO as CONC_POS_CODICESTRADARIO,MERCATI_D.NOTE as CONC_POS_NOTE FROM AUTORIZZAZIONI_CONCESSIONI LEFT OUTER JOIN AUTORIZZAZIONI AUT_COLLEGATA LEFT OUTER JOIN TIPOLOGIAREGISTRI ON AUT_COLLEGATA.IDCOMUNE=TIPOLOGIAREGISTRI.IDCOMUNE  AND AUT_COLLEGATA.FKIDREGISTRO=TIPOLOGIAREGISTRI.TR_ID ON AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE=AUT_COLLEGATA.IDCOMUNE  AND AUTORIZZAZIONI_CONCESSIONI.FK_IDAUT_COLLEGATA=AUT_COLLEGATA.ID,AUTORIZZAZIONI LEFT OUTER JOIN CONCESSIONICAUSALI CAUS_STORICO ON AUTORIZZAZIONI.IDCOMUNE=CAUS_STORICO.IDCOMUNE  AND AUTORIZZAZIONI.FK_CAUSALE_CESSAZIONE=CAUS_STORICO.CODICECAUSALE,MERCATI_D LEFT OUTER JOIN POSTEGGITIPOSPAZIO ON MERCATI_D.IDCOMUNE=POSTEGGITIPOSPAZIO.IDCOMUNE  AND MERCATI_D.FKCODICETIPOSPAZIO=POSTEGGITIPOSPAZIO.CODICE,ISTANZE LEFT OUTER JOIN ANAGRAFE IST_AZIENDA ON ISTANZE.IDCOMUNE=IST_AZIENDA.IDCOMUNE  AND ISTANZE.CODICETITOLARELEGALE=IST_AZIENDA.CODICEANAGRAFE,CONCESSIONITIPI,TIPOLOGIAREGISTRI CONC_REGISTRO,ANAGRAFE TITOLARE,CONCESSIONICAUSALI CAUS_ATTUALE,ANAGRAFE IST_RICHIEDENTE,MERCATI,MERCATI_USO WHERE CONC_REGISTRO.IDCOMUNE = AUTORIZZAZIONI.IDCOMUNE AND CONC_REGISTRO.TR_ID = AUTORIZZAZIONI.FKIDREGISTRO AND AUTORIZZAZIONI.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND AUTORIZZAZIONI.ID = AUTORIZZAZIONI_CONCESSIONI.FK_IDAUT_ATTUALE AND CONCESSIONITIPI.TIPOCONCESSIONE = AUTORIZZAZIONI_CONCESSIONI.FK_TIPOCONCESSIONE AND TITOLARE.IDCOMUNE = AUTORIZZAZIONI.IDCOMUNE AND TITOLARE.CODICEANAGRAFE = AUTORIZZAZIONI.FK_CODICEANAGRAFE AND CAUS_ATTUALE.IDCOMUNE = AUTORIZZAZIONI.IDCOMUNE AND CAUS_ATTUALE.CODICECAUSALE = AUTORIZZAZIONI.FK_CAUSALE_ACQUISIZIONE AND ISTANZE.IDCOMUNE = AUTORIZZAZIONI.IDCOMUNE AND ISTANZE.CODICEISTANZA = AUTORIZZAZIONI.FKIDISTANZA AND IST_RICHIEDENTE.IDCOMUNE = ISTANZE.IDCOMUNE AND IST_RICHIEDENTE.CODICEANAGRAFE = ISTANZE.CODICERICHIEDENTE AND MERCATI.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND MERCATI.CODICEMERCATO = AUTORIZZAZIONI_CONCESSIONI.FK_CODICEMERCATO AND MERCATI_D.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND MERCATI_D.IDPOSTEGGIO = AUTORIZZAZIONI_CONCESSIONI.FK_IDPOSTEGGIO AND MERCATI_USO.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND MERCATI_USO.ID = AUTORIZZAZIONI_CONCESSIONI.FK_IDMERCATIUSO 
UNION
SELECT AUTORIZZAZIONI_SUBENTRI.ID as PROGRESSIVO,AUTORIZZAZIONI_SUBENTRI.AUTORIZRESPONSABILE as CONC_AUTORIZRESPONSABILE,AUTORIZZAZIONI_SUBENTRI.IDCOMUNE,AUTORIZZAZIONI_SUBENTRI.FK_CAUSALE_ACQUISIZIONE as ICONC_CODICECAUSALE,AUTORIZZAZIONI_SUBENTRI.DATA_CESSAZIONE as DATA_STORICO,ISTANZE.SOFTWARE,ISTANZE.CODICEISTANZA as IST_CODICEISTANZA,ISTANZE.NUMEROISTANZA as IST_NUMEROISTANZA,ISTANZE.CODICERICHIEDENTE as IST_CODICERICHIEDENTE,AUTORIZZAZIONI_SUBENTRI.FK_IDAUT_ATTUALE as CONC_ID,AUTORIZZAZIONI_SUBENTRI.AUTORIZNUMERO as CONC_NUMERO,AUTORIZZAZIONI_SUBENTRI.AUTORIZDATA as CONC_DATARILASCIO,AUTORIZZAZIONI_SUBENTRI.AUTORIZDATA as DATARILASCIO,AUTORIZZAZIONI_SUBENTRI.DATASCADENZA as CONC_DATASCADENZA,AUTORIZZAZIONI_CONCESSIONI.FK_TIPOCONCESSIONE as CONC_CODICETIPO,CONCESSIONITIPI.DESCRIZIONE as CONC_TIPO,AUTORIZZAZIONI_CONCESSIONI.STAGIONALEA as CONC_STAGIONALEA,AUTORIZZAZIONI_CONCESSIONI.STAGIONALEDA as CONC_STAGIONALEDA,0 as CONC_ATTIVA,AUTORIZZAZIONI_SUBENTRI.FK_CODICEANAGRAFE as CONC_CODICETITOLARE,AUTORIZZAZIONI_SUBENTRI.FKIDREGISTRO as CONC_FKIDREGISTRO,CONC_REGISTRO.TR_DESCRIZIONE as CONC_REGISTRO,CONCAT_WS('',TITOLARE.NOMINATIVO,' ',TITOLARE.NOME) as CONC_TITOLARE,TITOLARE.CODICEFISCALE as CONC_TIT_CF,TITOLARE.PARTITAIVA as CONC_TIT_PIVA,TITOLARE.TIPOANAGRAFE as CONC_TIT_TIPOANAGRAFE,AUT_COLLEGATA.AUTORIZNUMERO as AUT_NUMERO,AUT_COLLEGATA.AUTORIZDATA as AUT_DATA,AUT_COLLEGATA.AUTORIZDATA,AUT_COLLEGATA.FKIDREGISTRO as AUT_CODREGISTRO,TIPOLOGIAREGISTRI.TR_DESCRIZIONE as AUT_REGISTRO,CONCAT_WS('',IST_RICHIEDENTE.NOMINATIVO,' ',IST_RICHIEDENTE.NOME) as IST_NOMINATIVO,IST_RICHIEDENTE.TIPOANAGRAFE as IST_RIC_TIPOANAGRAFE,CONCAT_WS('',IST_AZIENDA.NOMINATIVO,' ',IST_AZIENDA.NOME) as IST_NOMINATIVOAZIENDA,IST_AZIENDA.TIPOANAGRAFE as IST_AZI_TIPOANAGRAFE,IST_RICHIEDENTE.CODICEFISCALE as IST_CODICEFISCALE,IST_RICHIEDENTE.PARTITAIVA as IST_PARTITAIVA,CAUS_ATTUALE.DESCRIZIONE as ICONC_CAUSALE,AUTORIZZAZIONI_SUBENTRI.FK_CAUSALE_CESSAZIONE as ICONC_CODICECAUSALESTORICO,CAUS_STORICO.DESCRIZIONE as ICONC_CAUSALESTORICO,AUTORIZZAZIONI_CONCESSIONI.FK_CODICEMERCATO as CONC_IDMERCATO,MERCATI.DESCRIZIONE as CONC_MERCATO,MERCATI.ATTIVO as MERC_ATTIVO,AUTORIZZAZIONI_CONCESSIONI.FK_IDPOSTEGGIO as CONC_IDPOSTEGGIO,MERCATI_D.CODICEPOSTEGGIO as CONC_POSTEGGIO,MERCATI_D.LARGHEZZA as CONC_POS_LARGHEZZA,MERCATI_D.LUNGHEZZA as CONC_POS_LUNGHEZZA,MERCATI_D.SUPERFICIE as CONC_POS_SUPERFICIE,MERCATI_D.FKCODICETIPOSPAZIO as POST_IDTIPOSPAZIO,POSTEGGITIPOSPAZIO.TIPOSPAZIO as POST_TIPOSPAZIO,AUTORIZZAZIONI_CONCESSIONI.FK_IDMERCATIUSO as CONC_IDMERCATIUSO,MERCATI_USO.DESCRIZIONE as CONC_DESCRIZIONEUSO,MERCATI_USO.PESO as PESO_MERCATO,MERCATI_USO.FKCODICEUSO as MERC_IDUSO,MERCATI_D.FKCODICESTRADARIO as CONC_POS_CODICESTRADARIO,MERCATI_D.NOTE as CONC_POS_NOTE FROM AUTORIZZAZIONI_CONCESSIONI LEFT OUTER JOIN AUTORIZZAZIONI AUT_COLLEGATA LEFT OUTER JOIN TIPOLOGIAREGISTRI ON AUT_COLLEGATA.IDCOMUNE=TIPOLOGIAREGISTRI.IDCOMUNE  AND AUT_COLLEGATA.FKIDREGISTRO=TIPOLOGIAREGISTRI.TR_ID ON AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE=AUT_COLLEGATA.IDCOMUNE  AND AUTORIZZAZIONI_CONCESSIONI.FK_IDAUT_COLLEGATA=AUT_COLLEGATA.ID,AUTORIZZAZIONI_SUBENTRI LEFT OUTER JOIN CONCESSIONICAUSALI CAUS_STORICO ON AUTORIZZAZIONI_SUBENTRI.IDCOMUNE=CAUS_STORICO.IDCOMUNE  AND AUTORIZZAZIONI_SUBENTRI.FK_CAUSALE_CESSAZIONE=CAUS_STORICO.CODICECAUSALE,MERCATI_D LEFT OUTER JOIN POSTEGGITIPOSPAZIO ON MERCATI_D.IDCOMUNE=POSTEGGITIPOSPAZIO.IDCOMUNE  AND MERCATI_D.FKCODICETIPOSPAZIO=POSTEGGITIPOSPAZIO.CODICE,ISTANZE LEFT OUTER JOIN ANAGRAFE IST_AZIENDA ON ISTANZE.IDCOMUNE=IST_AZIENDA.IDCOMUNE  AND ISTANZE.CODICETITOLARELEGALE=IST_AZIENDA.CODICEANAGRAFE,CONCESSIONITIPI,TIPOLOGIAREGISTRI CONC_REGISTRO,ANAGRAFE TITOLARE,CONCESSIONICAUSALI CAUS_ATTUALE,ANAGRAFE IST_RICHIEDENTE,MERCATI,MERCATI_USO WHERE CONC_REGISTRO.IDCOMUNE = AUTORIZZAZIONI_SUBENTRI.IDCOMUNE AND CONC_REGISTRO.TR_ID = AUTORIZZAZIONI_SUBENTRI.FKIDREGISTRO AND AUTORIZZAZIONI_SUBENTRI.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND AUTORIZZAZIONI_SUBENTRI.FK_IDAUT_ATTUALE = AUTORIZZAZIONI_CONCESSIONI.FK_IDAUT_ATTUALE AND CONCESSIONITIPI.TIPOCONCESSIONE = AUTORIZZAZIONI_CONCESSIONI.FK_TIPOCONCESSIONE AND TITOLARE.IDCOMUNE = AUTORIZZAZIONI_SUBENTRI.IDCOMUNE AND TITOLARE.CODICEANAGRAFE = AUTORIZZAZIONI_SUBENTRI.FK_CODICEANAGRAFE AND CAUS_ATTUALE.IDCOMUNE = AUTORIZZAZIONI_SUBENTRI.IDCOMUNE AND CAUS_ATTUALE.CODICECAUSALE = AUTORIZZAZIONI_SUBENTRI.FK_CAUSALE_ACQUISIZIONE AND ISTANZE.IDCOMUNE = AUTORIZZAZIONI_SUBENTRI.IDCOMUNE AND ISTANZE.CODICEISTANZA = AUTORIZZAZIONI_SUBENTRI.FKIDISTANZA AND IST_RICHIEDENTE.IDCOMUNE = ISTANZE.IDCOMUNE AND IST_RICHIEDENTE.CODICEANAGRAFE = ISTANZE.CODICERICHIEDENTE AND MERCATI.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND MERCATI.CODICEMERCATO = AUTORIZZAZIONI_CONCESSIONI.FK_CODICEMERCATO AND MERCATI_D.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND MERCATI_D.IDPOSTEGGIO = AUTORIZZAZIONI_CONCESSIONI.FK_IDPOSTEGGIO AND MERCATI_USO.IDCOMUNE = AUTORIZZAZIONI_CONCESSIONI.IDCOMUNE AND MERCATI_USO.ID = AUTORIZZAZIONI_CONCESSIONI.FK_IDMERCATIUSO;

CREATE OR REPLACE ALGORITHM=TEMPTABLE VIEW VW_CONCESSIONILISTA AS 
SELECT IDCOMUNE, SOFTWARE, PROGRESSIVO, CONC_ID, CONC_NUMERO, CONC_DATARILASCIO, CONC_DATASCADENZA, CONC_CODICETIPO, CONC_TIPO, CONC_STAGIONALEA, CONC_STAGIONALEDA, CONC_ATTIVA, CONC_CODICETITOLARE, CONC_TITOLARE, CONC_TIT_CF, CONC_TIT_PIVA, CONC_TIT_TIPOANAGRAFE, CONC_FKIDREGISTRO, CONC_REGISTRO, AUT_NUMERO, AUT_DATA, AUT_CODREGISTRO, AUT_REGISTRO, IST_CODICEISTANZA, IST_NUMEROISTANZA, IST_CODICERICHIEDENTE, IST_NOMINATIVO, IST_CODICEFISCALE, IST_PARTITAIVA, IST_RIC_TIPOANAGRAFE, ICONC_CODICECAUSALE, ICONC_CAUSALE, ICONC_CODICECAUSALESTORICO, ICONC_CAUSALESTORICO, CONC_IDMERCATO, CONC_MERCATO, MERC_ATTIVO, CONC_IDPOSTEGGIO, CONC_POSTEGGIO, CONC_POS_LARGHEZZA, CONC_POS_LUNGHEZZA, CONC_POS_SUPERFICIE, POST_IDTIPOSPAZIO, POST_TIPOSPAZIO, CONC_IDMERCATIUSO, CONC_DESCRIZIONEUSO, PESO_MERCATO, MERC_IDUSO, CONC_POS_CODICESTRADARIO, DATA_STORICO FROM VW_ISTANZECONCESSIONILISTA;

ALTER TABLE ISTANZESTRADARIO ADD ID_PUNTO_SIT VARCHAR(50);

ALTER TABLE COMUNIASSOCIATI ADD CODICE_ENTE_PAYER VARCHAR(5);

CREATE TABLE MERCATI_D2C_ASSEGNAZ 
(
  IDCOMUNE VARCHAR(6) NOT NULL,
  ID NUMERIC(10,0) NOT NULL,
  FKCODICEMERCATO NUMERIC(4, 0) NOT NULL, 
  FK_D2C_ID NUMERIC(10, 0) NOT NULL, 
  CONSTRAINT MERCATI_D2C_ASSEGNAZ_PK PRIMARY KEY 
  (
    IDCOMUNE, 
    ID 
  ) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE MERCATI_D2C_ASSEGNAZ ADD CONSTRAINT FK_MERC_D2C_ASS_MERCATI FOREIGN KEY(IDCOMUNE , FKCODICEMERCATO) REFERENCES MERCATI (IDCOMUNE, CODICEMERCATO );
ALTER TABLE MERCATI_D2C_ASSEGNAZ ADD CONSTRAINT FK_MERC_D2C_ASS_DYN2_CAMPI FOREIGN KEY (IDCOMUNE , FK_D2C_ID) REFERENCES DYN2_CAMPI (IDCOMUNE , ID);

ALTER TABLE MERCATI  ADD FK_D2CID_PREF_USO NUMERIC(10, 0);

ALTER TABLE MERCATI ADD CONSTRAINT FK_MERCATI_DYN2_CAMPI FOREIGN KEY (IDCOMUNE , FK_D2CID_PREF_USO) REFERENCES DYN2_CAMPI (IDCOMUNE , ID);

ALTER TABLE MERCATI_D  ADD PESO NUMERIC(4, 0);

CREATE TABLE MERCATI_D_CRITASS 
(
  IDCOMUNE VARCHAR(6) NOT NULL,
  ID NUMERIC(10,0) NOT NULL,
  FK_IDPOSTEGGIO NUMERIC(6, 0) NOT NULL, 
  FK_D2C_ID NUMERIC(10, 0) NOT NULL,
  VALORE VARCHAR(100) NOT NULL,
  VALOREDECODIFICATO VARCHAR(100),
  FLAG_CONSENTITO NUMERIC(1, 0), 
  CONSTRAINT MERCATI_D_CRITASS_PK PRIMARY KEY 
  (
    IDCOMUNE, 
    ID 
  )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE MERCATI_D_CRITASS ADD CONSTRAINT FK_MERC_D_CRITASS_DYN2_CAMPI FOREIGN KEY (IDCOMUNE , FK_D2C_ID) REFERENCES DYN2_CAMPI(IDCOMUNE , ID);
ALTER TABLE MERCATI_D_CRITASS ADD CONSTRAINT FK_MERC_D_CRITASS_MERCATID FOREIGN KEY (IDCOMUNE , FK_IDPOSTEGGIO) REFERENCES MERCATI_D(IDCOMUNE , IDPOSTEGGIO);


CREATE TABLE COMUNIASSOCIAZIONI (CODICEASSOCIAZIONE VARCHAR(5) NOT NULL, ASSOCIAZIONE VARCHAR(128) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE COMUNIASSOCIAZIONI ADD( CONSTRAINT PK_COMASSOCIAZIONI PRIMARY KEY (CODICEASSOCIAZIONE));
CREATE OR REPLACE ALGORITHM=TEMPTABLE VIEW VW_ENTILOCALI AS SELECT CODICECOMUNE, COMUNE FROM COMUNI UNION SELECT CODICEASSOCIAZIONE AS CODICECOMUNE, ASSOCIAZIONE AS COMUNE FROM COMUNIASSOCIAZIONI;

ALTER TABLE AUTORIZZAZIONI DROP FOREIGN KEY FK_AUTCOMUNI;
ALTER TABLE AUTORIZZAZIONI_SUBENTRI DROP FOREIGN KEY FK_AUTSUB_COMUNI;
ALTER TABLE MERCATIPRESENZE_STORICO MODIFY FKIDMERCATIUSO DECIMAL(4,0) NULL;

CREATE TABLE FO_ARJ_STEPS_BASE (
  NOME_STEP VARCHAR(50) NOT NULL,  
  LINK_FUNZIONE VARCHAR(125) NOT NULL,
  TITOLO VARCHAR(150) NOT NULL,
  DESCRIZIONE VARCHAR(4000),
  FLAG_OBBLIGATORIO NUMERIC(1,0),
  DIPENDE_DA_STEP VARCHAR(50),  
  INCOMPATIBILE_CON_STEP VARCHAR(50),
  ORDINE_DEFAULT NUMERIC(2,0),
PRIMARY KEY (NOME_STEP)
)  ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE FO_ARJ_STEPS ADD FK_NOME_STEP_BASE VARCHAR(50);
ALTER TABLE FO_ARJ_STEPS ADD CONSTRAINT FK_FASNOMESTEP_FASBNOMESTEP FOREIGN KEY (FK_NOME_STEP_BASE) REFERENCES FO_ARJ_STEPS_BASE(NOME_STEP);

CREATE TABLE FO_ARJ_STEPS_PARAMS_BASE(
  CHIAVE  VARCHAR(200),
  DESCRIZIONE VARCHAR(500),
  PRIMARY KEY(CHIAVE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE FO_ARJ_STEPS_PARAMS ADD CONSTRAINT FK_FASPCHIAVE_FASPB_CHIAVE FOREIGN KEY(CHIAVE) REFERENCES FO_ARJ_STEPS_PARAMS_BASE (CHIAVE);

ALTER TABLE FO_ARCONFIGURAZIONE ADD FK_FOARJSTEPSTEST_ID NUMERIC(6,0);

ALTER TABLE FO_ARCONFIGURAZIONE ADD CONSTRAINT FK_FOAC_FOARJST_ID FOREIGN KEY (IDCOMUNE,FK_FOARJSTEPSTEST_ID) REFERENCES FO_ARJ_STEPS_TESTATA(IDCOMUNE,ID);


CREATE TABLE I_ATTIVITA_TIPOLOGIE(
IDCOMUNE VARCHAR(6) NOT NULL
,ID NUMERIC(4,0) NOT NULL
,DESCRIZIONE VARCHAR(100)
,SOFTWARE VARCHAR(2)
, PRIMARY KEY (IDCOMUNE, ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


ALTER TABLE I_ATTIVITA ADD FK_IATIPOLOGIE_ID NUMERIC(4,0);

ALTER TABLE I_ATTIVITA ADD CONSTRAINT FK_IATT_IATIPOLOGIEID FOREIGN KEY (IDCOMUNE,FK_IATIPOLOGIE_ID ) REFERENCES I_ATTIVITA_TIPOLOGIE (IDCOMUNE,ID);
ALTER TABLE I_ATTIVITA_TIPOLOGIE ADD CONSTRAINT FK_IAT_TIPOLOGIE_SOFTWARE FOREIGN KEY (SOFTWARE) REFERENCES SOFTWARE (CODICE);


ALTER TABLE I_ATTIVITA_SNAPSHOT ADD FK_IATIPOLOGIE_ID NUMERIC(4,0);
ALTER TABLE I_ATTIVITA_SNAPSHOT ADD CONSTRAINT FK_IATTSNAP_IATIPOLOGIEID FOREIGN KEY (IDCOMUNE,FK_IATIPOLOGIE_ID ) REFERENCES I_ATTIVITA_TIPOLOGIE (IDCOMUNE,ID);

ALTER TABLE ISTANZE MODIFY LAVORI VARCHAR(2000);

CREATE TABLE FO_ARJ_DOMANDE_ONERI(
IDCOMUNE VARCHAR(6) NOT NULL
, ID NUMERIC(8,0) NOT NULL
, FK_ID_DOMANDA NUMERIC(6,0) NOT NULL
, FK_CAUSALEONERI NUMERIC(10,0) NOT NULL
, FK_CODICEINVENTARIO NUMERIC(10,0)
, IMPORTO NUMERIC(6,2)
, ID_NUM_OPERAZ_ONLINE VARCHAR(20)
, IDORDINE_SISTEMA_PAGAMENTI VARCHAR(125) 
, FLAG_STATO NUMERIC(1,0) 
, FLAG_ONLINE NUMERIC(1,0) 
, CODICEOGGETTO_XML NUMERIC(10,0) 
, CODICEOGGETTO_PDF NUMERIC(10,0)
, NOTE VARCHAR(500)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE FO_ARJ_DOMANDE_ONERI ADD CONSTRAINT PK_FO_ARJ_DOMANDE_ONERI PRIMARY KEY(IDCOMUNE, ID); 
ALTER TABLE FO_ARJ_DOMANDE_ONERI ADD CONSTRAINT FK_FADO_FADID FOREIGN KEY (IDCOMUNE, FK_ID_DOMANDA) REFERENCES FO_ARJ_DOMANDE(IDCOMUNE, ID); 
ALTER TABLE FO_ARJ_DOMANDE_ONERI ADD CONSTRAINT FK_FADO_TCASUONERICOID FOREIGN KEY (IDCOMUNE, FK_CAUSALEONERI) REFERENCES TIPICAUSALIONERI(IDCOMUNE, CO_ID); 
ALTER TABLE FO_ARJ_DOMANDE_ONERI ADD CONSTRAINT FK_FADO_INVPROCCODINV FOREIGN KEY (IDCOMUNE, FK_CODICEINVENTARIO) REFERENCES INVENTARIOPROCEDIMENTI(IDCOMUNE, CODICEINVENTARIO); 
ALTER TABLE FO_ARJ_DOMANDE_ONERI ADD CONSTRAINT FK_FADOCOXML_OGGETTICO FOREIGN KEY (IDCOMUNE, CODICEOGGETTO_XML) REFERENCES OGGETTI(IDCOMUNE, CODICEOGGETTO); 
ALTER TABLE FO_ARJ_DOMANDE_ONERI ADD CONSTRAINT FK_FADOCOPDF_OGGETTICO FOREIGN KEY (IDCOMUNE, CODICEOGGETTO_PDF) REFERENCES OGGETTI(IDCOMUNE, CODICEOGGETTO);

ALTER TABLE ALBEROPROC ADD FK_FOARJSTEPSTESTATAID NUMERIC(6,0);
ALTER TABLE ALBEROPROC ADD CONSTRAINT FK_ALBEROPROC_FOARJSTEPSTESTA FOREIGN KEY ( IDCOMUNE, FK_FOARJSTEPSTESTATAID ) REFERENCES FO_ARJ_STEPS_TESTATA ( IDCOMUNE, ID ) ;

ALTER TABLE FO_ARJ_DOMANDE ADD FK_ALBEROPROCSCID NUMERIC(10,0);
ALTER TABLE FO_ARJ_DOMANDE ADD CONSTRAINT FK_FOARJDOMANDE_ALBEROPROC FOREIGN KEY ( IDCOMUNE, FK_ALBEROPROCSCID ) REFERENCES ALBEROPROC ( IDCOMUNE, SC_ID ) ;

CREATE TABLE NLA_SERVIZI
  (
    ID          NUMERIC(6,0) NOT NULL ,
    IDCOMUNE    VARCHAR(6) NOT NULL ,
    IDNODO      NUMERIC(6,0) NOT NULL ,
    IDENTE      VARCHAR(10) NOT NULL ,
    IDSPORTELLO VARCHAR(10) NOT NULL ,
    PEC         VARCHAR(320) ,
    DESCRIZIONE VARCHAR(4000) NOT NULL
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE NLA_SERVIZI ADD CONSTRAINT NLA_SERVIZI_PK PRIMARY KEY(IDCOMUNE, ID);

CREATE TABLE FO_ARJ_SERVIZI
  (
    ID                NUMERIC(6,0) NOT NULL ,
    IDCOMUNE          VARCHAR(6) NOT NULL ,
    URL_SERVIZIO      VARCHAR(4000) NOT NULL ,
    ANONIMO           NUMERIC(1,0) ,
    FK_ALBEROPROCSCID NUMERIC(10,0) NOT NULL ,
    FK_NLASERVIZIID   NUMERIC(6,0) NOT NULL
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
  
ALTER TABLE FO_ARJ_SERVIZI ADD CONSTRAINT FO_ARJ_SERVIZI_PK PRIMARY KEY (IDCOMUNE, ID);

ALTER TABLE FO_ARJ_SERVIZI ADD CONSTRAINT FK_FOARJSERVIZI_ALBEROPROC FOREIGN KEY ( IDCOMUNE, FK_ALBEROPROCSCID ) REFERENCES ALBEROPROC ( IDCOMUNE, SC_ID );
ALTER TABLE FO_ARJ_SERVIZI ADD CONSTRAINT FK_FOARJSERVIZI_NLASERVIZI FOREIGN KEY ( IDCOMUNE, FK_NLASERVIZIID ) REFERENCES NLA_SERVIZI ( IDCOMUNE, ID );


ALTER TABLE ALBEROPROC DROP FOREIGN KEY FK_ALBERO_PROC_PROT_TIPI_DOC;

ALTER TABLE ISTANZEONERI MODIFY DOCRIFERIMENTO VARCHAR(200);
ALTER TABLE TMP_ISTANZEONERI MODIFY RIFERIMENTO VARCHAR(200);

ALTER TABLE CC_CLASSISUPERFICI ADD ALIQUOTA_CALCOLO_CC NUMERIC(5,2);

ALTER TABLE DOCUMENTIISTANZA ADD ID_BASE VARCHAR(50);
ALTER TABLE MOVIMENTIALLEGATI ADD ID_BASE VARCHAR(50);
ALTER TABLE ISTANZEALLEGATI ADD ID_BASE VARCHAR(50);