#parametri timeout delle chiamate WS
ws.timeout=300000

## PARAMETRI CONFIGURAZIONE OGGETTI SERVICE WS
oggetti.ws.mtom.enabled=true
oggetti.ws.path.to.wsdl=/services/oggetti?wsdl
oggetti.ws.attach.logging.interceptors=true

movimenti.ws.mtom.enabled=true
movimenti.ws.path.to.wsdl=/services/movimenti?wsdl
movimenti.ws.attach.logging.interceptors=true

## parametri per comunicazione con Sigepro Security
ws.token.pwd=REDACTED
ws.token.url=REDACTED
ws.token.user=REDACTED
