## SECURITY
ws.token.url=REDACTED
ws.token.user=REDACTED
ws.token.pwd=REDACTED


## STC
stc.url=REDACTED
stc.userid=	NLAINFOCAMERE
stc.password=REDACTED
stc.mtom=true
stc.timeout=480000


##Nodo mittente
stc.idNodoMittente=3200
stc.idEnteMittente=INFOCAMERE
stc.idSportelloMittente=INFOCAMERE
## Nodo destinatario
stc.idNodoDestinatario=400
## Lasciate vuoro se vogliamo ricavarlo dinamicamente dalla chiamata al NLA WS da parte del backoffice
stc.idSportelloDestinatario=

## WS OGGETTI
oggetti.ws.url=REDACTED
oggetti.ws.mtom=true
oggetti.ws.timeout=120000
oggetti.ws.attach.logging.interceptors=true
ws.eventi.mtom=true

#BACKEND
ws.backend.url=REDACTED
#INFOCAMERE



infocamere.ente.suap.ws.mtom=true
infocamere.ente.suap.ws.timeout=480000

## WS SIT
ws.sit.url=REDACTED

idcomune.alias=E256


# PARAMETRI CONESSIONE DB BACKEND SERVERFARM USATO PER LA PROCEDURA INIZIALE DI BONIFICA DATI
db.backend.jdbc_driver=com.mysql.jdbc.Driver
db.backend.db_url=REDACTED
db.backend.user=REDACTED
db.backend.user.password=REDACTED
