<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
		<OutputType>Exe</OutputType>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<Configurations>Debug;Release;ReleaseFramework</Configurations>
		<Platforms>AnyCPU</Platforms>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Moq" Version="4.20.72" />
		<PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="xunit.v3" Version="3.2.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\SIGePro.DatiDinamici\SIGePro.DatiDinamici.v1.csproj" />
		<ProjectReference Include="..\..\SIGePro.Manager.DTO\SIGePro.Manager.DTO.csproj" />
		<ProjectReference Include="..\Init.Sigepro.FrontEnd.AppLogic.ConnectedServices\Init.Sigepro.FrontEnd.AppLogic.ConnectedServices.csproj" />
		<ProjectReference Include="..\Init.Sigepro.FrontEnd.AppLogic\Init.Sigepro.FrontEnd.AppLogic.csproj" />
		<ProjectReference Include="..\Init.Sigepro.FrontEnd.GestioneMovimenti\Init.Sigepro.FrontEnd.GestioneMovimenti.csproj" />
		<ProjectReference Include="..\Init.Sigepro.FrontEnd.Infrastructure\Init.Sigepro.FrontEnd.Infrastructure.csproj" />
	</ItemGroup>
</Project>