<schema targetNamespace="http://gruppoinit.it/sigepro/schemas/messages/utilititypagopa" 
	xmlns:tns="http://gruppoinit.it/sigepro/schemas/messages/utilititypagopa"
	xmlns="http://www.w3.org/2001/XMLSchema" 
	xmlns:xmime="http://www.w3.org/2005/05/xmlmime"
	elementFormDefault="qualified">
	
	<!-- Definizioni request e response -->
	
	<element name="BollettinopagopaRequest">
		<complexType>
			<sequence>
				<element name="logoEnte" type="string" minOccurs="0" maxOccurs="1" />
	  			<element name="oggettoDelPagamento" type="string" minOccurs="0" maxOccurs="1" />
	   			<element name="oggettoDelPagamentoRata" type="string" minOccurs="0" maxOccurs="1" />
	   			<element name="oggettoDelPagamentoBollettino" type="string" minOccurs="0" maxOccurs="1" />
			    <element name="cfEnte" type="string" minOccurs="0" maxOccurs="1" />
			    <element name="cfDestinatario" type="string" minOccurs="0" maxOccurs="1" />
			    <element name="nomeCognomeDestinatario" type="string" minOccurs="0" maxOccurs="1" />
			    <element name="enteCreditore" type="string" minOccurs="0" maxOccurs="1" />
			    <element name="settoreEnte" type="string" minOccurs="0" maxOccurs="1" />
			    <element name="indirizzoDestinatario1" type="string" minOccurs="0" maxOccurs="1" />
			    <element name="indirizzoDestinatario2" type="string" minOccurs="0" maxOccurs="1" />
			    <element name="infoEnte" type="string" minOccurs="0" maxOccurs="1" />
			    <element name="delTuoEnte" type="string" minOccurs="0" maxOccurs="1" />
			    <element name="diPoste" type="string" minOccurs="0" maxOccurs="1" />
			    <element name="importo" type="string" minOccurs="0" maxOccurs="1" />
			    <element name="data" type="string" minOccurs="0" maxOccurs="1" />
			    <element name="qrCode" type="string" minOccurs="0" maxOccurs="1" />
			    <element name="cbill" type="string" minOccurs="0" maxOccurs="1" />
			    <element name="codiceAvviso" type="string" minOccurs="0" maxOccurs="1" />
			    <element name="codiceAvvisoPostale" type="string" minOccurs="0" maxOccurs="1" />
			    <element name="numeroCcPostale" type="string" minOccurs="0" maxOccurs="1" />
			    <element name="intestatarioContoCorrentePostale" type="string" minOccurs="0" maxOccurs="1" />
			    <element name="autorizzazione" type="string" minOccurs="0" maxOccurs="1" />
			    <element name="dataMatrix" type="string" minOccurs="0" maxOccurs="1" />
			</sequence>
		</complexType>	
	</element>
	
	<element name="BollettinopagopaResponse">
		<complexType>
			<sequence>
				<element name="esito" type="string" minOccurs="1" maxOccurs="1" />
				<element name="binaryData" type="base64Binary" xmime:expectedContentTypes="application/octet-stream" minOccurs="0"/>
			</sequence>
		</complexType>	
	</element>

</schema>
