UPDATE PROTOCOLLO_MEZZI SET SOFTWARE='TT' WHERE SOFTWARE IS NULL;
UPDATE PROTOCOLLO_MODALITAINVIO SET SOFTWARE='TT' WHERE SOFTWARE IS NULL;
UPDATE PROTOCOLLO_SEQUENZE SET SOFTWARE='TT' WHERE SOFTWARE IS NULL;
UPDATE PROTOCOLLO_SMISTAMENTI SET SOFTWARE='TT' WHERE SOFTWARE IS NULL;
UPDATE PROTOCOLLO_TIPIDOCUMENTO SET SOFTWARE='TT' WHERE SOFTWARE IS NULL;
UPDATE PROTOCOLLO_UFFICIREGISTRI SET SOFTWARE='TT' WHERE SOFTWARE IS NULL;
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_EGRAMMATA2', 'CODICE_CC', 'Indica il codice per conoscenza da utilizzare in fase di protocollazione. Sulla maschera di protocollazione è presente un campo a tendina denominato -Trasmesso per- legato all''anagrafica (Mittente / Destinatario), questo campo viene popolato dai valori presenti nella tabella PROTOCOLLO_MODALITAINVIO, indicando il codice in questo campo, quando l''operatore selezionerà nella tendina -Trasmesso per- il valore con lo stesso codice, l''anagrafica selezionata sarà considerata per conoscenza. Se non valorizzato il destinatario (mittente) del protocollo non sarà mai per conoscenza.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_EGRAMMATA2', 'URL_LEGGIPROTO', 'Url relativo al web service che consente leggere i protocolli. In particolare consente di recuperare una lista di protocolli a partire da determinati parametri di ricerca.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_EGRAMMATA2', 'POSTAZIONE', 'Cinquina che identifica la postazione dell’utente applicativo che si autentica al Protocollo (cinque numeri separati dal carattere ''-'' Esempio 92-25-0-0-0).');
update CLMENU_JAVA set pagina='protocollotipidocumento/list.htm?software=TT', jsp='JAVA',LINK_STANDARD='protocollotipidocumento/list.htm?software=TT',TIPO_FUNZIONALITA='S' where id=985;
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO,PARAMETRO,DESCRIZIONE) VALUES ('STC','FORZA_PROTOCOLLAZIONE','Determina in caso di pratiche o movimenti in ingresso inseriti tramite STC la chiamata al servizio di protocollazione. In questi casi anche se la direzione è la stessa la pratica - o il movimento - verranno protocollati ( sempre secondo le logiche definite nelle configurazioni). Accetta valori S o N (se vuoto allora N).');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_HALLEY', 'GENERA_SUAP_XML', 'Valori ammessi 0, 1 o null. Se valorizzato a 1 il sistema genera, in caso di Protocollazione di un''istanza in ingresso, un file xml in base alle seguenti regole:<br> - Se nell’istanza c’è l’azienda allora il file da creare deve rispettare l’xsd pubblicato su impresa in un giorno (nome: <cf_piva>-<ddmmyyyy-hh24miss>.SUAP.XML e specifiche "Definizione XSD del modello di riepilogo della pratica SUAP (SUAP.XML).xsd")<br>- Se nell’istanza non c’è l’azienda allora (nome: <cf_piva>-<ddmmyyyy-hh24miss>.SUE.xml e "Definizione SUE.xsd")<br> - Se il file già esiste non va creato<br> - Il file va allegato al protocollo e non deve essere salvato nei documenti dell’istanza.<br> Se il parametro viene impostato con valori diversi da 1 il sistema continuerà a funzionare senza generare alcun file.');
INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('PROTOCOLLO_DOCER', 'INVIA_SEGNATURA', '(Facoltativo) Se valorizzato a 1 consente, in fase di protocollazione istanza o movimento da backoffice, di inviare il file segnatura.xml che sarebbe il file che viene inviato al web service per eseguire la protocollazione; se valorizzato a 0 o non valorizzato non esegue nessuna funzionalità.');

INSERT INTO CLMENU_JAVA (ID, DESCRIZIONE,PAGINA, MENULINK, SOFTWARE, JSP, LAYOUTTESTI,LINK_STANDARD, TIPO_FUNZIONALITA) VALUES ('1018', 'Documenti da firmare','documentidafirmare/documentiDaFirmareList.htm?software=SOFTWARE','104', '*', 'JAVA', '0','documentidafirmare/documentiDaFirmareList.htm?software=SOFTWARE', 'E');
INSERT INTO CLMENU_JAVA (ID, DESCRIZIONE,PAGINA, MENULINK, SOFTWARE, JSP, LAYOUTTESTI,LINK_STANDARD, TIPO_FUNZIONALITA) VALUES ('1019', 'Documenti messi alla firma','documentidafirmare/documentiMessiAllaFirmaList.htm?software=SOFTWARE','105', '*', 'JAVA', '0','documentidafirmare/documentiDaFirmareList.htm?software=SOFTWARE', 'E');
