ALTER TABLE DOMANDESTC MODIFY RICHIEDENTE VARCHAR(250);
ALTER TABLE DYN2_CAMPI MODIFY ETICHETTA VARCHAR(200);
ALTER TABLE DYN2_MODELLIT MODIFY DESCRIZIONE VARCHAR(150);
ALTER TABLE ISTANZEONERI ADD FLAG_ONERE_RATEIZZATO NUMERIC(1,0) DEFAULT 0;
ALTER TABLE ISTANZEONERI ADD IMPORTO_INTERESSE NUMERIC(11,2)  DEFAULT 0;


ALTER TABLE ISTANZE DROP FOREIGN KEY FK_ANAGRAFESTORICO_01;
ALTER TABLE ISTANZE DROP FOREIGN KEY  FK_ANAGRAFESTORICO_02;
ALTER TABLE ISTANZE DROP FOREIGN KEY  FK_ANAGRAFESTORICO_03;
ALTER TABLE ISTANZERICHIEDENTI DROP FOREIGN KEY FK_ISTANZ_RICH_RICH_STOR;
ALTER TABLE ISTANZERICHIEDENTI DROP FOREIGN KEY FK_ISTANZ_RICH_ANAGRSTOR;
ALTER TABLE ISTANZERICHIEDENTI DROP FOREIGN KEY FK_ISTANZ_RICH_PROC_STOR;
ALTER TABLE ISTANZEPROCURE DROP FOREIGN KEY FK_ISTPROC_ANPROCST;
ALTER TABLE ISTANZEPROCURE DROP FOREIGN KEY FK_ISTPROC_ANRAPST;

ALTER TABLE ISTANZE MODIFY FK_RICHIEDENTESTORICO_ID NUMERIC(10,0);
ALTER TABLE ISTANZE MODIFY FK_TITOLARELEGALESTORICO_ID NUMERIC(10,0);
ALTER TABLE ISTANZE MODIFY FK_PROFESSIONISTASTORICO_ID NUMERIC(10,0);
ALTER TABLE ISTANZERICHIEDENTI MODIFY FK_RICHIEDENTESTORICO_ID NUMERIC(10,0);
ALTER TABLE ISTANZERICHIEDENTI MODIFY FK_ANAGRAFECOLLSTORICO_ID NUMERIC(10,0);
ALTER TABLE ISTANZERICHIEDENTI MODIFY FK_PROCURATORESTORICO_ID NUMERIC(10,0);
ALTER TABLE ISTANZEPROCURE MODIFY FK_ANAG_PROC_STORICO NUMERIC(10,0);
ALTER TABLE ISTANZEPROCURE MODIFY FK_ANAG_RAPP_STORICO NUMERIC(10,0);
ALTER TABLE ANAGRAFESTORICO MODIFY ID NUMERIC(10,0);

ALTER TABLE ISTANZE ADD CONSTRAINT FK_ANAGRAFESTORICO_01 FOREIGN KEY(IDCOMUNE,FK_RICHIEDENTESTORICO_ID) REFERENCES ANAGRAFESTORICO(IDCOMUNE,ID);
ALTER TABLE ISTANZE ADD CONSTRAINT  FK_ANAGRAFESTORICO_02 FOREIGN KEY(IDCOMUNE,FK_TITOLARELEGALESTORICO_ID) REFERENCES ANAGRAFESTORICO(IDCOMUNE,ID);
ALTER TABLE ISTANZE ADD CONSTRAINT  FK_ANAGRAFESTORICO_03 FOREIGN KEY(IDCOMUNE,FK_PROFESSIONISTASTORICO_ID) REFERENCES ANAGRAFESTORICO(IDCOMUNE,ID);
ALTER TABLE ISTANZERICHIEDENTI ADD CONSTRAINT FK_ISTANZ_RICH_RICH_STOR FOREIGN KEY(IDCOMUNE,FK_RICHIEDENTESTORICO_ID) REFERENCES ANAGRAFESTORICO(IDCOMUNE,ID);
ALTER TABLE ISTANZERICHIEDENTI ADD CONSTRAINT FK_ISTANZ_RICH_ANAGRSTOR FOREIGN KEY(IDCOMUNE,FK_ANAGRAFECOLLSTORICO_ID) REFERENCES ANAGRAFESTORICO(IDCOMUNE,ID);
ALTER TABLE ISTANZERICHIEDENTI ADD CONSTRAINT FK_ISTANZ_RICH_PROC_STOR FOREIGN KEY(IDCOMUNE,FK_PROCURATORESTORICO_ID) REFERENCES ANAGRAFESTORICO(IDCOMUNE,ID);
ALTER TABLE ISTANZEPROCURE ADD CONSTRAINT FK_ISTPROC_ANPROCST FOREIGN KEY(IDCOMUNE,FK_ANAG_PROC_STORICO) REFERENCES ANAGRAFESTORICO(IDCOMUNE,ID);
ALTER TABLE ISTANZEPROCURE ADD CONSTRAINT FK_ISTPROC_ANRAPST FOREIGN KEY(IDCOMUNE,FK_ANAG_RAPP_STORICO) REFERENCES ANAGRAFESTORICO(IDCOMUNE,ID);


ALTER TABLE COMUNIASSOCIATI ADD DISATTIVO_FO NUMERIC(1,0) DEFAULT 0;
ALTER TABLE dyn2_modellid ADD flg_spezza_tabella numeric(1,0);