INSERT INTO SOFTWARE(CODICE,DESCRIZIONE,MODULOOPZIONALE,DESCRIZIONELUNGA,ACCESSORAPIDO,ORDINE) VALUES ('XS','Scarichi',1,'Scarichi',0,54);
INSERT INTO SOFTWARE(CODICE,DESCRIZIONE,MODULOOPZIONALE,DESCRIZIONELUNGA,ACCESSORAPIDO,ORDINE) VALUES ('XE','Emissioni',1,'Emissioni',0,55);
INSERT INTO SOFTWARE(CODICE,DESCRIZIONE,MODULOOPZIONALE,DESCRIZIONELUNGA,ACCESSORAPIDO,ORDINE) VALUES ('XA','Acustica',1,'Acustica',0,56);
INSERT INTO SOFTWARE(CODICE,DESCRIZIONE,MODULOOPZIONALE,DESCRIZIONELUNGA,ACCESSORAPIDO,ORDINE) VALUES ('XR','Rifiuti',1,'Rifiuti',0,57);

DELETE FROM MASTERKEY;
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('NATURAENDO','BINARIODIPENDENZE');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('TIPIMOV_STC_MAPPING','ID');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('MAPPATURE','ID');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('TIPIMOV_STC_ALBEROPROC','ID');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('TIPIMOV_STC_ALTRIDATI','ID');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('TIPIMOV_STC_MODELLI','ID');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('ALBEROPROC_ONERI','AO_ID');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('TIPICAUSALIONERI','CO_ID');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('TIPIENDO','CODICE');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('TIPIFAMIGLIEENDO','CODICE');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('AMMINISTRAZIONI','CODICEAMMINISTRAZIONE');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('INVENTARIOPROCEDIMENTI','CODICEINVENTARIO');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('LETTERETIPO','CODICELETTERA');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('NATURAENDO','CODICENATURA');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('NORMATIVE','CODICENORMATIVA');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('TIPIPROCEDURE','CODICEPROCEDURA');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('TEMPIFICAZIONI','CODICETEMPIFICAZIONE');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('TIPICONTROMOVIMENTO','CONTATORE');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('ALBEROPROC_DOCUMENTICAT','ID');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('INVENTARIOPROCEDIMENTIINCOMP','ID');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('INVENTARIOPROC_LEGGI','ID');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('INVENTARIOPROCEDIMENTIPEOPLE','ID');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('ALLEGATI','ID');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('TESTIESTESI','ID');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('DOCUMENTI','ID');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('INVENTARIOPROCEDIMENTIONERI','ID');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('DYN2_CAMPI','ID');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('DYN2_MODELLID','ID');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('DYN2_MODELLIDTESTI','ID');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('DYN2_MODELLIT','ID');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('INVENTARIOPROC_TIPITITOLO','ID');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('ALBEROPROCPEOPLEOPER','ID');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('ALBEROPROCPEOPLEHREF','ID');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('ALBEROPROC_ARENDO','ID');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('LEGGI','LE_ID');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('LEGGITIPI','LT_ID');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('TIPIMODALITAPAGAMENTO','MP_ID');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('RAGGRUPPAMENTOCAUSALIONERI','RCO_ID');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('ALBEROPROC','SC_ID');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('ALBEROPROC_LEGGI','SL_ID');
INSERT INTO MASTERKEY (TABLENAME,COLUMNNAME) VALUES ('ALBEROPROC_DOCUMENTI','SM_ID');

INSERT
INTO CLMENU_JAVA
  (
    ID,
    DESCRIZIONE,
    PAGINA,
    MENULINK,
    SOFTWARE,
    JSP,
    LAYOUTTESTI,
    VERTICALIZZAZIONE,
    SOFTWAREESCLUSI,
    LINK_STANDARD
  )
  VALUES
  (
    1010,
    'Tipi localizzazioni',
    'tipilocalizzazioni/list.htm?software=TT',
    '005',
    'TT',
    'JAVA',
    0,
    NULL,
    'AB',
    'tipilocalizzazioni/list.htm?software=TT'
  );

update INVENTARIOPROCEDIMENTISOFTWARE set FLAG_MOV_OPZIONALE=0 where FLAG_MOV_OPZIONALE is null;
  
INSERT INTO CLMENU_JAVA(ID,DESCRIZIONE,PAGINA,MENULINK,SOFTWARE,JSP,LAYOUTTESTI,VERTICALIZZAZIONE,SOFTWAREESCLUSI,LINK_STANDARD,TIPO_FUNZIONALITA) VALUES (1011,'Pannello gestione PEC','pecinbox/inbox.htm?software=TT&resetFilter=true','11','TT','JAVA',0,NULL, 'PR,FI,AB','pecinbox/inbox.htm?software=TT&resetFilter=true','E');
  
UPDATE CLMENU_JAVA set PAGINA='pecinbox/inbox.htm?software=SOFTWARE&resetFilter=true',LINK_STANDARD='pecinbox/inbox.htm?software=SOFTWARE&resetFilter=true' WHERE ID=1009;

UPDATE MERCATIPRESENZE_D SET NUMEROPRESENZE = 1 WHERE CODICEANAGRAFE IS NOT NULL AND FK_AUTORIZZAZIONI_ID IS NOT NULL;
  
UPDATE MERCATI SET TIPOCONTEGGIO_PRESENZE=1 WHERE TIPOCONTEGGIO_PRESENZE IS NULL;
  
UPDATE PEC_INBOX BOX SET IN_LOGINNAME = (
  SELECT MAX(MCFG.IN_LOGINNAME) 
  FROM MAIL_CONFIG MCFG 
  WHERE MCFG.IDCOMUNE = BOX.IDCOMUNE
  AND MCFG.SOFTWARE = BOX.SOFTWARE
  )
WHERE BOX.IN_LOGINNAME IS NULL;


update istanzeallegati set CONTROLLOOK=null where CONTROLLOOK=0;

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE( MODULO,PARAMETRO,DESCRIZIONE) VALUES ('STC','TIPOMOV_DEFAULT_SOGG_ESTERNI','Quando un nodo NLA processa un''integrazione documentale la gestisce come notifica attività verso il backoffice questo cerca di individuare tra i movimenti della pratica quello con flag ''Front Office Richiedenti'' e se non lo trova rilancia un errore. Questo codice rappresenta il tipo movimento da utilizzare nel caso in cui il controllo precedente fallisca');

INSERT INTO VERTICALIZZAZIONIBASE (MODULO, DESCRIZIONE) VALUES ('PROTOCOLLO_SICRAWEB', 'Se abilitato permette usare le funzionalità del protocollo SICRAWEB. Questo protocollo è stato sviluppato da Maggioli ma viene fornito, oltre che da Maggioli stesso, anche da Studio K, il quale ha rilasciato proprio una versione di test del web service raggiungibile all''indirizzo http://www.studiok.it:9091/ws_sici/ProWSApi.asmx?wsdl che è pubblico');


INSERT INTO CONTENTTYPES (CT_MIMETYPE,CT_EXTENSION) VALUES ('application/vnd.openxmlformats-officedocument.presentationml.presentation',';pptx;');
INSERT INTO CONTENTTYPES (CT_MIMETYPE,CT_EXTENSION) VALUES ('application/vnd.openxmlformats-officedocument.presentationml.slide',';sldx;');
INSERT INTO CONTENTTYPES (CT_MIMETYPE,CT_EXTENSION) VALUES ('application/vnd.openxmlformats-officedocument.presentationml.slideshow',';ppsx;');
INSERT INTO CONTENTTYPES (CT_MIMETYPE,CT_EXTENSION) VALUES ('application/vnd.openxmlformats-officedocument.presentationml.template',';potx;');
INSERT INTO CONTENTTYPES (CT_MIMETYPE,CT_EXTENSION) VALUES ('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',';xlsx;');
INSERT INTO CONTENTTYPES (CT_MIMETYPE,CT_EXTENSION) VALUES ('application/vnd.openxmlformats-officedocument.spreadsheetml.template',';xltx;');
INSERT INTO CONTENTTYPES (CT_MIMETYPE,CT_EXTENSION) VALUES ('application/vnd.openxmlformats-officedocument.wordprocessingml.document',';docx;');

INSERT INTO VERTICALIZZAZIONIPARAMETRIBASE (MODULO, PARAMETRO, DESCRIZIONE) VALUES ('STC','LISTA_NODI_MITT_GET_ALLEGATI','Indicare l''elenco dei nodi mittenti per i quali recuperare gli allegati fisici invece dei riferimenti. Es. 410,420,430');