ALTER TABLE RESPONSABILI_TM_AVV MODIFY ( CODICERESPONSABILE NUMBER(8,0));

CREATE TABLE PAY_REGCAUSALI_PARAMETRI(
IDCOMUNE  VARCHAR2(6 CHAR)  NOT NULL,
ID        NUMBER(6,0)     NOT NULL,
FK_PAYREGCAUSALE_ID NUMBER(6) NOT NULL,
CHIAVE VARCHAR2(50 CHAR) NOT NULL,
VALORE VARCHAR2(4000 CHAR) NOT NULL
);

ALTER TABLE PAY_REGCAUSALI_PARAMETRI ADD CONSTRAINT PK_PAYREGCAUSALIPARAMETRI PRIMARY KEY(IDCOMUNE,ID); ALTER TABLE PAY_REGCAUSALI_PARAMETRI ADD CONSTRAINT FK_PAYREGCAUSPARAM_PAYCAUS FOREIGN KEY(IDCOMUNE,FK_PAYREGCAUSALE_ID) REFERENCES PAY_REGISTRAZIONI_CAUSALI(IDCOMUNE,ID);

CREATE INDEX IDX_PAYREGCAUSALIPARAMETRI_001 ON PAY_REGCAUSALI_PARAMETRI(IDCOMUNE,FK_PAYREGCAUSALE_ID);
CREATE INDEX IDX_PAYREGCAUSALIPARAMETRI_002 ON PAY_REGCAUSALI_PARAMETRI(IDCOMUNE,FK_PAYREGCAUSALE_ID,CHIAVE);


DROP INDEX IDX_PAYREGCAUSALIPARAMETRI_002;
CREATE UNIQUE INDEX IDX_PAYREGCAUSALIPARAMETRI_002 ON PAY_REGCAUSALI_PARAMETRI(IDCOMUNE,FK_PAYREGCAUSALE_ID,CHIAVE);

ALTER TABLE ISTANZEONERI MODIFY NR_DOCUMENTO VARCHAR2(60 CHAR);

ALTER TABLE INVENTARIOPROCEDIMENTIONERI MODIFY NOTE VARCHAR2(4000 CHAR);