ALTER TABLE INVENTARIOPROCEDIMENTI ADD FLAGTIPITITOLO numeric(1,0);
ALTER TABLE CLPERMMENU MODIFY ID NUMERIC(10,0);

CREATE TABLE FVG_TIPIVARIAZIONI (CODICE varchar(15) NOT NULL, DESCRIZIONE varchar(2000) NOT NULL, PRIMARY KEY (CODICE)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE ALBEROPROC ADD FVG_TIPOVARIAZIONE VARCHAR(15);
ALTER TABLE ALBEROPROC ADD CONSTRAINT FK_ALBERO_FVGTIPIVARIAZIONI FOREIGN KEY(FVG_TIPOVARIAZIONE) REFERENCES FVG_TIPIVARIAZIONI(CODICE);

CREATE TABLE TIPIMODELLI  (
  IDCOMUNE VARCHAR(6) NOT NULL, 
  ID NUMERIC(10,0) NOT NULL,
  DESCRIZIONE VARCHAR(200) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE TIPIMODELLI ADD CONSTRAINT TIPIMODELLI_PK PRIMARY KEY (IDCOMUNE, ID);

alter table MODELLI add FLAG_PUBBLICA numeric(1,0) default 0;
alter table MODELLI add FK_TIPIMODULO numeric(10,0);
ALTER TABLE MODELLI ADD CONSTRAINT  FK_TIPIMODULO_MODELLI FOREIGN KEY (IDCOMUNE, FK_TIPIMODULO) REFERENCES TIPIMODELLI (IDCOMUNE, ID);

alter table ALBEROPROC add PAROLE_CHIAVE varchar(1000);

alter table INVENTARIOPROCEDIMENTI add PAROLE_CHIAVE varchar(1000);

CREATE TABLE JOB_REPOSITORY_PARAM  (
  ID NUMERIC(10,0) NOT NULL,
  ETICHETTA VARCHAR(200) NOT NULL,
  DESCRIZIONE VARCHAR(2000) NOT NULL,
  VALORE VARCHAR(100) NOT NULL,
  FK_JOB_REPOSITORY NUMERIC(6,0) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE JOB_REPOSITORY_PARAM ADD CONSTRAINT JOB_REPOSITORY_PARAM_PK PRIMARY KEY (ID);

ALTER TABLE JOB_REPOSITORY_PARAM ADD CONSTRAINT FK_JOB_REP_JOB_REP_PAR FOREIGN KEY (FK_JOB_REPOSITORY) REFERENCES JOB_REPOSITORY(ID);

ALTER TABLE JOB_REPOSITORY_PARAM ADD CONSTRAINT JOB_REPOSITORY_PARAM_PK PRIMARY KEY (ID);

ALTER TABLE JOB_REPOSITORY_PARAM ADD CONSTRAINT FK_JOB_REP_JOB_REP_PAR FOREIGN KEY (FK_JOB_REPOSITORY) REFERENCES JOB_REPOSITORY(ID);
