SET IMPLICIT_TRANSACTIONS ON
GO
ALTER TABLE ISTANZEEVENTI ALTER COLUMN IDEVENTO NUMERIC(10)
GO
COMMIT
GO
ALTER TABLE ISTANZEEVENTI ADD SOFTWARE VARCHAR(2)
GO
COMMIT
GO
ALTER TABLE ISTANZEEVENTI ADD CONSTRAINT FK_IEVENTI_SOFTWARE FOREIGN KEY (SOFTWARE) REFERENCES SOFTWARE(CODICE)
GO
COMMIT
GO
CREATE INDEX IDX_ISTEVENTI_001 ON ISTANZEEVENTI (IDCOMUNE, SOFTWARE, FLAG_LETTO)
GO
COMMIT
GO
CREATE INDEX IDX_ISTEVENTI_002 ON ISTANZEEVENTI (IDCOMUNE, FKIDCATEGORIAEVENTO, SOFTWARE, FLAG_LETTO)
GO
COMMIT
GO
CREATE INDEX IDX_ISTEVENTI_003 ON ISTANZEEVENTI (IDCOMUNE, CODICEISTANZA,FLAG_LETTO)
GO
COMMIT
GO
CREATE INDEX IDX_ISTEVENTI_004 ON ISTANZEEVENTI (IDCOMUNE, CODICEMOVIMENTO, FLAG_LETTO)
GO
COMMIT
GO
ALTER TABLE ALBEROPROC_ENDO ADD FLAG_PUBBLICA NUMERIC(1, 0)
GO
COMMIT
GO
ALTER TABLE TIPISOGGETTOPEOPLE ALTER COLUMN TIPORAPPRPEOPLE VARCHAR(100)
GO
COMMIT
GO
ALTER TABLE NORMEGENERALI  ALTER COLUMN  INDIRIZZOWEB VARCHAR(512)
GO
COMMIT
GO
CREATE TABLE LINK_PREFERITI_UTENTE 
(
  IDCOMUNE VARCHAR(6) NOT NULL,
  ID NUMERIC(6,0),
  CODICERESPONSABILE NUMERIC(4, 0) NOT NULL, 
  DESCRIZIONE VARCHAR(150) NOT NULL, 
  URL VARCHAR(255) NOT NULL, 
  TARGET VARCHAR(10), 
  ORDINE NUMERIC(2, 0), 
  CONSTRAINT LINK_PREFERITI_UTENTE_PK PRIMARY KEY 
  (
    IDCOMUNE, 
    ID 
  )
)
GO
COMMIT
GO

CREATE TABLE DOCUMENTI_CONTABILITA 
(
  IDCOMUNE VARCHAR(6) NOT NULL,
  ID NUMERIC(6,0),
  CODICERESPONSABILE NUMERIC(4, 0) NOT NULL,
  CODICESOFTWARE VARCHAR(2),
  CODICEOGGETTO NUMERIC(10,0),
  NOMEDOCUMENTO VARCHAR(50) NOT NULL, 
  DOCUMENTO VARCHAR(4000),
  DATA DATE NOT NULL,
  DATAINSERIMENTO DATE NOT NULL,
  MESE VARCHAR(2), 
  ANNO VARCHAR(4),
  CONSTRAINT DOCUMENTI_CONTABILITA_PK PRIMARY KEY 
  (
    IDCOMUNE, 
    ID 
  )
) 
GO
COMMIT
GO
ALTER TABLE DOCUMENTI_CONTABILITA ADD CONSTRAINT FK_DOC_CONTAB_RESP FOREIGN KEY (IDCOMUNE , CODICERESPONSABILE) REFERENCES RESPONSABILI (IDCOMUNE , CODICERESPONSABILE )
GO
COMMIT
GO
ALTER TABLE DOCUMENTI_CONTABILITA ADD CONSTRAINT FK_DOC_CONTAB_OGGETTI FOREIGN KEY (IDCOMUNE , CODICEOGGETTO) REFERENCES OGGETTI (IDCOMUNE , CODICEOGGETTO)
GO
COMMIT
GO
CREATE TABLE PROTOCOLLO_SMISTAMENTI 
(
  IDCOMUNE VARCHAR(6) NOT NULL 
, CODICE VARCHAR(30) NOT NULL 
, DESCRIZIONE VARCHAR(300) NOT NULL 
, CONSTRAINT PROTOCOLLO_SMISTAMENTI_PK PRIMARY KEY 
  (
    IDCOMUNE 
  , CODICE 
  )
)
GO
COMMIT
GO