create table SDEPROXY (
IDENTE VARCHAR(15) NOT NULL,
ALIAS_ENTE    VARCHAR(20),
DESCRIZIONE VARCHAR(255),
CODICECATASTALECOMUNE VARCHAR(5),
WS_STRADARIO VARCHAR(255),
WS_ANAGRAFE_RESIDENTI VARCHAR(255),
WS_STATOPRATICA VARCHAR(255),
USERNAME_WS  VARCHAR(15),
PASSWORD_WS  VARCHAR(15)
)  ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE SDEPROXY ADD CONSTRAINT PK_SDEPROXY PRIMARY KEY (IDENTE);
ALTER TABLE SDEPROXY ADD CONSTRAINT FK_SDEPROXY_COMUNI FOREIGN KEY (CODICECATASTALECOMUNE) REFERENCES COMUNI (CODICECOMUNE);
CREATE TABLE SDECOMUNIASSOCIATI(
IDENTE VARCHAR(6) NOT NULL,
CODICECATASTALECOMUNE VARCHAR(5) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE SDECOMUNIASSOCIATI ADD CONSTRAINT PK_SDECOMUNIASSOCIATI PRIMARY KEY (IDENTE, CODICECATASTALECOMUNE);
ALTER TABLE SDECOMUNIASSOCIATI ADD CONSTRAINT FK_SDECOMUNIASSOCIATI_PROXY FOREIGN KEY (IDENTE) REFERENCES SDEPROXY (IDENTE);
ALTER TABLE SDECOMUNIASSOCIATI ADD CONSTRAINT FK_SDECOMUNIASSOCIATI_COMUNI FOREIGN KEY (CODICECATASTALECOMUNE) REFERENCES COMUNI (CODICECOMUNE);

CREATE TABLE DIZIONARI_CART(
ID NUMERIC(10,0) NOT NULL,
OGGETTO LONGBLOB,
NOMEFILE VARCHAR(255),
DATA_PUBBLICAZIONE DATETIME) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE DIZIONARI_CART ADD CONSTRAINT PK_DIZIONARI_CART PRIMARY KEY (ID);

CREATE INDEX IDX_DIZIONARICART_001 ON DIZIONARI_CART(DATA_PUBBLICAZIONE);
CREATE TABLE AGGIORNAMENTI_DIZIONARIO(
ID NUMERIC(10,0)NOT NULL,
IDCOMUNE VARCHAR(6) NOT NULL,
FK_DIZCART_ID NUMERIC(10,0) NOT NULL,
FLAG_ELABORATO NUMERIC(1,0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE AGGIORNAMENTI_DIZIONARIO ADD CONSTRAINT PK_AGGIORNAMENTI_DIZIONARIO PRIMARY KEY (IDCOMUNE, ID);
ALTER TABLE AGGIORNAMENTI_DIZIONARIO ADD CONSTRAINT FK_AGGDIZ_DIZCART FOREIGN KEY (FK_DIZCART_ID) REFERENCES
DIZIONARI_CART(ID);
ALTER TABLE AGGIORNAMENTI_DIZIONARIO ADD DATA_ELABORAZIONE DATETIME;

ALTER TABLE FO_DOMANDE add idente VARCHAR(15);
ALTER TABLE FO_DOMANDE add CODICECATASTALECOMUNE VARCHAR(5);

CREATE TABLE SDECOMUNIASSOCIATI(
IDENTE VARCHAR(15) NOT NULL,
CODICECATASTALECOMUNE VARCHAR(5) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE SDECOMUNIASSOCIATI ADD CONSTRAINT PK_SDECOMUNIASSOCIATI PRIMARY KEY (IDENTE, CODICECATASTALECOMUNE);
ALTER TABLE SDECOMUNIASSOCIATI ADD CONSTRAINT FK_SDECOMUNIASSOCIATI_PROXY FOREIGN KEY (IDENTE) REFERENCES SDEPROXY (IDENTE);
ALTER TABLE SDECOMUNIASSOCIATI ADD CONSTRAINT FK_SDECOMUNIASSOCIATI_COMUNI FOREIGN KEY (CODICECATASTALECOMUNE) REFERENCES COMUNI (CODICECOMUNE);

alter table fo_domande add identificativo_cart VARCHAR(600);
ALTER TABLE SDEPROXY ADD NOME_PD_PRESDOM VARCHAR(200);
ALTER TABLE FO_DOMANDE_OGGETTI ADD TIPO_FILE VARCHAR(10);
ALTER TABLE FO_DOMANDE_OGGETTI MODIFY TIPO_FILE VARCHAR(20);

CREATE TABLE CART_SERVIZI_DIZIONARIO(
  URL_DOWNLOAD_SCHEDA_TIPO1 VARCHAR(256),
  URL_DOWNLOAD_SCHEDA_TIPO2 VARCHAR(256)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

alter table CART_SERVIZI_DIZIONARIO add ID NUMERIC(4,0);

create table codifica_enti_53 (
codiceistat VARCHAR(6)
, ENTE VARCHAR(250)
, CODIFICA VARCHAR(30)
, PRIMARY KEY (CODICEISTAT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

alter table sdecomuniassociati add NOME_PD_PRESDOM VARCHAR(200);

ALTER TABLE sdeproxy add url_integration_manager VARCHAR(256);

ALTER TABLE SDEPROXY ADD IM_AUTH_USER VARCHAR(100);
ALTER TABLE SDEPROXY ADD IM_AUTH_PASSWORD VARCHAR(100);


ALTER TABLE SDEPROXY ADD ENCODE_ATT_AS_BASE64 NUMERIC(1,0);


