<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="18.7.23">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="VBG.BlazorComponentsLibrary" Version="10.0.4" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Frontoffice\Init.Sigepro.FrontEnd.AppLogic.ConnectedServices\Init.Sigepro.FrontEnd.AppLogic.ConnectedServices.csproj" />
		<ProjectReference Include="..\Frontoffice\Init.Sigepro.FrontEnd.AppLogic\Init.Sigepro.FrontEnd.AppLogic.csproj" />
	</ItemGroup>

	<ItemGroup>
		<SupportedPlatform Include="browser" />
	</ItemGroup>

</Project>
