<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://init.sigepro.it" xmlns:tns="http://init.sigepro.it"
	elementFormDefault="qualified">
	<element name="getPersonaFisica">
		<complexType>
			<sequence>
				<element minOccurs="0" maxOccurs="1" name="token" type="string" />
				<element minOccurs="0" maxOccurs="1" name="codiceFiscale" type="string" />
			</sequence>
		</complexType>
	</element>
	<element name="getPersonaFisicaResponse">
		<complexType>
			<sequence>
				<element minOccurs="0" maxOccurs="1" name="getPersonaFisicaResult" type="tns:Anagrafe" />
			</sequence>
		</complexType>
	</element>
	<complexType name="Anagrafe">
		<complexContent mixed="false">
			<extension base="tns:BaseDataClass">
				<sequence>
					<element minOccurs="0" maxOccurs="1" name="CODICEANAGRAFE" type="string" />
					<element minOccurs="0" maxOccurs="1" name="IDCOMUNE" type="string" />
					<element minOccurs="0" maxOccurs="1" name="NOMINATIVO" type="string" />
					<element minOccurs="0" maxOccurs="1" name="FORMAGIURIDICA" type="string" />
					<element minOccurs="0" maxOccurs="1" name="TIPOLOGIA" type="string" />
					<element minOccurs="0" maxOccurs="1" name="INDIRIZZO" type="string" />
					<element minOccurs="0" maxOccurs="1" name="CITTA" type="string" />
					<element minOccurs="0" maxOccurs="1" name="CAP" type="string" />
					<element minOccurs="0" maxOccurs="1" name="PROVINCIA" type="string" />
					<element minOccurs="0" maxOccurs="1" name="TELEFONO" type="string" />
					<element minOccurs="0" maxOccurs="1" name="TELEFONOCELLULARE" type="string" />
					<element minOccurs="0" maxOccurs="1" name="FAX" type="string" />
					<element minOccurs="0" maxOccurs="1" name="PARTITAIVA" type="string" />
					<element minOccurs="0" maxOccurs="1" name="CODICEFISCALE" type="string" />
					<element minOccurs="0" maxOccurs="1" name="NOTE" type="string" />
					<element minOccurs="0" maxOccurs="1" name="EMAIL" type="string" />
					<element minOccurs="0" maxOccurs="1" name="REGDITTE" type="string" />
					<element minOccurs="0" maxOccurs="1" name="REGTRIB" type="string" />
					<element minOccurs="0" maxOccurs="1" name="CODCOMREGDITTE" type="string" />
					<element minOccurs="0" maxOccurs="1" name="CODCOMREGTRIB" type="string" />
					<element minOccurs="0" maxOccurs="1" name="CODCOMNASCITA" type="string" />
					<element minOccurs="1" maxOccurs="1" name="DATANASCITA" nillable="true" type="dateTime" />
					<element minOccurs="1" maxOccurs="1" name="DATAREGDITTE" nillable="true" type="dateTime" />
					<element minOccurs="1" maxOccurs="1" name="DATAREGTRIB" nillable="true" type="dateTime" />
					<element minOccurs="0" maxOccurs="1" name="INVIOEMAIL" type="string" />
					<element minOccurs="0" maxOccurs="1" name="SESSO" type="string" />
					<element minOccurs="0" maxOccurs="1" name="NOME" type="string" />
					<element minOccurs="0" maxOccurs="1" name="TITOLO" type="string" />
					<element minOccurs="0" maxOccurs="1" name="TIPOANAGRAFE" type="string" />
					<element minOccurs="1" maxOccurs="1" name="DATANOMINATIVO" nillable="true" type="dateTime" />
					<element minOccurs="0" maxOccurs="1" name="INVIOEMAILTEC" type="string" />
					<element minOccurs="0" maxOccurs="1" name="CODICECITTADINANZA" type="string" />
					<element minOccurs="0" maxOccurs="1" name="COMUNERESIDENZA" type="string" />
					<element minOccurs="0" maxOccurs="1" name="PASSWORD" type="string" />
					<element minOccurs="0" maxOccurs="1" name="INDIRIZZOCORRISPONDENZA" type="string" />
					<element minOccurs="0" maxOccurs="1" name="CITTACORRISPONDENZA" type="string" />
					<element minOccurs="0" maxOccurs="1" name="CAPCORRISPONDENZA" type="string" />
					<element minOccurs="0" maxOccurs="1" name="PROVINCIACORRISPONDENZA" type="string" />
					<element minOccurs="0" maxOccurs="1" name="COMUNECORRISPONDENZA" type="string" />
					<element minOccurs="0" maxOccurs="1" name="PROVINCIAREA" type="string" />
					<element minOccurs="0" maxOccurs="1" name="NUMISCRREA" type="string" />
					<element minOccurs="1" maxOccurs="1" name="DATAISCRREA" nillable="true" type="dateTime" />
					<element minOccurs="0" maxOccurs="1" name="FLAG_NOPROFIT" type="string" />
					<element minOccurs="0" maxOccurs="1" name="FLAG_DISABILITATO" type="string" />
					<element minOccurs="1" maxOccurs="1" name="DATA_DISABILITATO" nillable="true" type="dateTime" />
					<element minOccurs="0" maxOccurs="1" name="Username" type="string" />
					<element minOccurs="0" maxOccurs="1" name="CODICEELENCOPRO" type="string" />
					<element minOccurs="0" maxOccurs="1" name="NUMEROELENCOPRO" type="string" />
					<element minOccurs="0" maxOccurs="1" name="PROVINCIAELENCOPRO" type="string" />
					<element minOccurs="0" maxOccurs="1" name="Pec" type="string" />
					<element minOccurs="1" maxOccurs="1" name="FoUtenteTester" nillable="true" type="int" />
					<element minOccurs="0" maxOccurs="1" name="TitoloClass" type="tns:Titoli" />
					<element minOccurs="0" maxOccurs="1" name="ElencoProfessionale" type="tns:ElenchiProfessionaliBase" />
					<element minOccurs="0" maxOccurs="1" name="FormaGiuridicaClass" type="tns:FormeGiuridiche" />
					<element minOccurs="0" maxOccurs="unbounded" name="AnagrafeDocumenti" type="tns:AnagrafeDocumenti" />
					<element minOccurs="0" maxOccurs="unbounded" name="AnagrafeDyn2ModelliT" type="tns:AnagrafeDyn2ModelliT" />
					<element minOccurs="0" maxOccurs="unbounded" name="AnagrafeDyn2Dati" type="tns:AnagrafeDyn2Dati" />
					<element minOccurs="0" maxOccurs="1" name="ComuneNascita" type="tns:Comuni" />
					<element minOccurs="0" maxOccurs="1" name="ComuneRegDitte" type="tns:Comuni" />
					<element minOccurs="0" maxOccurs="1" name="ComuneRegTrib" type="tns:Comuni" />
					<element minOccurs="0" maxOccurs="1" name="ComuneCorrispondenza" type="tns:Comuni" />
					<element minOccurs="0" maxOccurs="1" name="ComuneResidenza" type="tns:Comuni" />
					<element minOccurs="0" maxOccurs="1" name="Cittadinanza" type="tns:Cittadinanza" />
					<element minOccurs="0" maxOccurs="unbounded" name="PresenzeStoriche" type="tns:MercatiPresenzeStorico" />
					<element minOccurs="0" maxOccurs="1" name="InpsMatricola" type="string" />
					<element minOccurs="0" maxOccurs="1" name="InpsCodiceSede" type="string" />
					<element minOccurs="0" maxOccurs="1" name="InailMatricola" type="string" />
					<element minOccurs="0" maxOccurs="1" name="InailCodiceSede" type="string" />
					<element minOccurs="0" maxOccurs="1" name="SedeInps" type="tns:ElencoInpsBase" />
					<element minOccurs="0" maxOccurs="1" name="SedeInail" type="tns:ElencoInailBase" />					
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="BaseDataClass">
		<complexContent mixed="false">
			<extension base="tns:DataClass" />
		</complexContent>
	</complexType>
	<complexType name="DataClass" />
	<complexType name="ElencoInailBase">
		<complexContent mixed="false">
			<extension base="tns:BaseDataClass">
				<sequence>
					<element minOccurs="0" maxOccurs="1" name="Codice" type="string" />
					<element minOccurs="0" maxOccurs="1" name="Descrizione" type="string" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="ElencoInpsBase">
		<complexContent mixed="false">
			<extension base="tns:BaseDataClass">
				<sequence>
					<element minOccurs="0" maxOccurs="1" name="Codice" type="string" />
					<element minOccurs="0" maxOccurs="1" name="Descrizione" type="string" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>		
	<complexType name="MercatiPresenzeStorico">
		<complexContent mixed="false">
			<extension base="tns:BaseDataClass">
				<sequence>
					<element minOccurs="1" maxOccurs="1" name="Id" nillable="true" type="int" />
					<element minOccurs="0" maxOccurs="1" name="Anagrafe" type="tns:Anagrafe" />
					<element minOccurs="0" maxOccurs="1" name="Idcomune" type="string" />
					<element minOccurs="1" maxOccurs="1" name="Fkcodicemercato" nillable="true" type="int" />
					<element minOccurs="1" maxOccurs="1" name="Fkidmercatiuso" nillable="true" type="int" />
					<element minOccurs="1" maxOccurs="1" name="Codiceanagrafe" nillable="true" type="int" />
					<element minOccurs="1" maxOccurs="1" name="Anno" nillable="true" type="int" />
					<element minOccurs="1" maxOccurs="1" name="Numeropresenze" nillable="true" type="int" />
					<element minOccurs="0" maxOccurs="1" name="IdentAut" type="string" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="Cittadinanza">
		<complexContent mixed="false">
			<extension base="tns:BaseDataClass">
				<sequence>
					<element minOccurs="1" maxOccurs="1" name="Codice" nillable="true" type="int" />
					<element minOccurs="0" maxOccurs="1" name="Descrizione" type="string" />
					<element minOccurs="0" maxOccurs="1" name="Cf" type="string" />
					<element minOccurs="1" maxOccurs="1" name="Disabilitato" nillable="true" type="int" />
					<element minOccurs="1" maxOccurs="1" name="FlgPaeseComunitario" nillable="true" type="int" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="VwProvince">
		<complexContent mixed="false">
			<extension base="tns:BaseDataClass">
				<sequence>
					<element minOccurs="0" maxOccurs="1" name="SiglaProvincia" type="string" />
					<element minOccurs="0" maxOccurs="1" name="PROVINCIA" type="string" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="Comuni">
		<complexContent mixed="false">
			<extension base="tns:BaseDataClass">
				<sequence>
					<element minOccurs="0" maxOccurs="1" name="CODICECOMUNE" type="string" />
					<element minOccurs="0" maxOccurs="1" name="COMUNE" type="string" />
					<element minOccurs="0" maxOccurs="1" name="SIGLAPROVINCIA" type="string" />
					<element minOccurs="0" maxOccurs="1" name="PROVINCIA" type="string" />
					<element minOccurs="0" maxOccurs="1" name="REGIONE" type="string" />
					<element minOccurs="0" maxOccurs="1" name="CAP" type="string" />
					<element minOccurs="0" maxOccurs="1" name="CF" type="string" />
					<element minOccurs="0" maxOccurs="1" name="CODICEISTAT" type="string" />
					<element minOccurs="0" maxOccurs="1" name="CODICEISTATREGIONE" type="string" />
					<element minOccurs="0" maxOccurs="1" name="CODICESTATOESTERO" type="string" />
					<element minOccurs="0" maxOccurs="1" name="ProvinciaClass" type="tns:VwProvince" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="AnagrafeDyn2Dati">
		<complexContent mixed="false">
			<extension base="tns:BaseDataClass">
				<sequence>
					<element minOccurs="0" maxOccurs="1" name="Idcomune" type="string" />
					<element minOccurs="1" maxOccurs="1" name="Codiceanagrafe" nillable="true" type="int" />
					<element minOccurs="1" maxOccurs="1" name="FkD2cId" nillable="true" type="int" />
					<element minOccurs="1" maxOccurs="1" name="Indice" nillable="true" type="int" />
					<element minOccurs="1" maxOccurs="1" name="IndiceMolteplicita" nillable="true" type="int" />
					<element minOccurs="0" maxOccurs="1" name="Valore" type="string" />
					<element minOccurs="0" maxOccurs="1" name="Valoredecodificato" type="string" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="AnagrafeDyn2ModelliT">
		<complexContent mixed="false">
			<extension base="tns:BaseDataClass">
				<sequence>
					<element minOccurs="0" maxOccurs="1" name="Idcomune" type="string" />
					<element minOccurs="1" maxOccurs="1" name="Codiceanagrafe" nillable="true" type="int" />
					<element minOccurs="1" maxOccurs="1" name="FkD2mtId" nillable="true" type="int" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="Oggetti">
		<complexContent mixed="false">
			<extension base="tns:BaseDataClass">
				<sequence>
					<element minOccurs="0" maxOccurs="1" name="CODICEOGGETTO" type="string" />
					<element minOccurs="0" maxOccurs="1" name="IDCOMUNE" type="string" />
					<element minOccurs="0" maxOccurs="1" name="OGGETTO" type="base64Binary" />
					<element minOccurs="0" maxOccurs="1" name="NOMEFILE" type="string" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="AnagrafeDocumenti">
		<complexContent mixed="false">
			<extension base="tns:BaseDataClass">
				<sequence>
					<element minOccurs="0" maxOccurs="1" name="ID" type="string" />
					<element minOccurs="0" maxOccurs="1" name="IDCOMUNE" type="string" />
					<element minOccurs="0" maxOccurs="1" name="CODICEANAGRAFE" type="string" />
					<element minOccurs="0" maxOccurs="1" name="IDTIPODOCUMENTO" type="string" />
					<element minOccurs="1" maxOccurs="1" name="DATAREGISTRAZIONE" nillable="true" type="dateTime" />
					<element minOccurs="0" maxOccurs="1" name="CODICEISTANZA" type="string" />
					<element minOccurs="0" maxOccurs="1" name="CODICEOGGETTO" type="string" />
					<element minOccurs="1" maxOccurs="1" name="DATAINIZIOVALIDITA" nillable="true" type="dateTime" />
					<element minOccurs="0" maxOccurs="1" name="RIFDOCUMENTO" type="string" />
					<element minOccurs="1" maxOccurs="1" name="DATAFINEVALIDITA" nillable="true" type="dateTime" />
					<element minOccurs="0" maxOccurs="1" name="ANNOTAZIONI" type="string" />
					<element minOccurs="0" maxOccurs="1" name="Oggetto" type="tns:Oggetti" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="FormeGiuridiche">
		<complexContent mixed="false">
			<extension base="tns:BaseDataClass">
				<sequence>
					<element minOccurs="0" maxOccurs="1" name="CODICEFORMAGIURIDICA" type="string" />
					<element minOccurs="0" maxOccurs="1" name="IDCOMUNE" type="string" />
					<element minOccurs="0" maxOccurs="1" name="FORMAGIURIDICA" type="string" />
					<element minOccurs="0" maxOccurs="1" name="CODICECCIAA" type="string" />					
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="ElenchiProfessionaliBase">
		<complexContent mixed="false">
			<extension base="tns:BaseDataClass">
				<sequence>
					<element minOccurs="1" maxOccurs="1" name="EpId" nillable="true" type="int" />
					<element minOccurs="0" maxOccurs="1" name="EpDescrizione" type="string" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="Titoli">
		<complexContent mixed="false">
			<extension base="tns:BaseDataClass">
				<sequence>
					<element minOccurs="0" maxOccurs="1" name="CODICETITOLO" type="string" />
					<element minOccurs="0" maxOccurs="1" name="IDCOMUNE" type="string" />
					<element minOccurs="0" maxOccurs="1" name="TITOLO" type="string" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	<element name="getPersonaGiuridica">
		<complexType>
			<sequence>
				<element minOccurs="0" maxOccurs="1" name="token" type="string" />
				<element minOccurs="0" maxOccurs="1" name="cfImpresaPartitaIva" type="string" />
			</sequence>
		</complexType>
	</element>
	<element name="getPersonaGiuridicaResponse">
		<complexType>
			<sequence>
				<element minOccurs="0" maxOccurs="1" name="getPersonaGiuridicaResult" type="tns:Anagrafe" />
			</sequence>
		</complexType>
	</element>
	<element name="Anagrafe" nillable="true" type="tns:Anagrafe" />
</schema>