# PARAMETRI PER CONNESSIONE AL SERVER DI POSTA. (SE SPECIFICATI ALLORA QUELLI DEL SECURITY ED STC NON SERVONO)
mailserver.host=
#PROTOCOL: SMTP (SSL FALSE, TSL FALSE), SMTP_SSL (SSL TRUE, TSL FALSE), SSMTP_SMTPS (SSL FALSE, TSL TRUE)
mailserver.protocol=
mailserver.port=
mailserver.useAuth=
mailserver.user=REDACTED
mailserver.password=REDACTED
mailserver.emailFrom=

# PARAMETRI PER COMUNICAZIONE CON IL SECURITY (registrare l'utente MAILSERVICE in SECURITY)
ws.token.url=REDACTED
#ws.token.alias= al momento non utilizzato
ws.token.user=REDACTED
ws.token.pwd=REDACTED

# SOVRASCRIVE IL PARAMETRO WSHOSTURL_JAVA RECUPERATO DAL SECURITY
wsHostUrlJava=

# PARAMETRI PER COMUNICAZIONE CON STC
ws.stc.url=REDACTED
ws.stc.user=REDACTED
ws.stc.pwd=REDACTED

# PARAMETRI PER CONNESSIONE TRAMITE PROXY SOCKS
socks.host=
socks.port=1080
socks.username=REDACTED
socks.password=REDACTED

#504 5.5.2 : Helo command rejected: need fully-qualified hostname
#This is is usually related to an error in your name service configuration. You can work around this problem by setting the mail.smtp.localhost property to the fully qualified host name of your machine.
mail.smtp.fully-qualified-hostname=
