log4j.rootLogger=WARN, R

#CONSOLE APPENDER
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d %p [%c] %nMAIL_SERVICE - <%m>%n

#ROLLING FILE APPENDER
log4j.appender.R=org.apache.log4j.RollingFileAppender
log4j.appender.R.File=${catalina.base}/logs/mailservice.log
log4j.appender.R.MaxFileSize=2048KB
log4j.appender.R.MaxBackupIndex=10
log4j.appender.R.layout=org.apache.log4j.PatternLayout
log4j.appender.R.layout.ConversionPattern=%d %p [%c] %m %n

#LOG LEVELS
log4j.logger.org=WARN
log4j.logger.it.gruppoinit.mailservice.ws=DEBUG
