ALTER TABLE RESPONSABILI ADD PESO_CARICO_LAVORO NUMBER(3);
ALTER TABLE RESPONSABILI ADD FLAG_MOD_RESP_SORT NUMBER(1,0);
alter table istanze drop constraint IDX_UQ_ISTANZA_UIID_001;
alter table istanze add constraint IDX_UQ_ISTANZA_UIID_001 UNIQUE(idcomune,uuid);

ALTER TABLE alberoproc ADD FLAG_AR_REDIRECT NUMBER(1);

ALTER TABLE MOVIMENTI MODIFY (CODICEISTANZA NUMBER(6,0) NOT NULL);

ALTER TABLE ALBEROPROC MODIFY (SC_CODICE VARCHAR2(40));

alter table ISTANZEPROCURE add CODICEOGGETTO_DOCIDE number(10,0);
alter table ISTANZEPROCURE add constraint FK_ISTPROC_IDENT_OGGETTI FOREIGN KEY(IDCOMUNE,CODICEOGGETTO_DOCIDE) REFERENCES OGGETTI (IDCOMUNE, CODICEOGGETTO);

alter table ISTANZEPROCURE add STC_ID_DOC_DOCIDE VARCHAR2(500) ;
alter table ISTANZEPROCURE add STC_ID_ALL_DOCIDE VARCHAR2(500) ;


