
create table NATURAENDOBASE(
CODICENATURA              NUMBER(10,0) NOT NULL,         
NATURA                            VARCHAR2(50 CHAR),
BINARIODIPENDENZE                 NUMBER(10,0),         
MODALITA_APERTURA           VARCHAR2(50 CHAR), 
NATURABASE VARCHAR2(20) 
);

ALTER TABLE NATURAENDOBASE ADD CONSTRAINT PK_NATURAENDOBASE primary key(codicenatura);


Insert into NATURAENDOBASE (CODICENATURA,NATURA,BINARIODIPENDENZE,MODALITA_APERTURA,NATURABASE) values ('1','Ordinario','31','COMUNICAZIONE_NOTIFICA','ordinario');
Insert into NATURAENDOBASE (CODICENATURA,NATURA,BINARIODIPENDENZE,MODALITA_APERTURA,NATURABASE) values ('2','Autocertificabile','31','COMUNICAZIONE_NOTIFICA','scia');
Insert into NATURAENDOBASE (CODICENATURA,NATURA,BINARIODIPENDENZE,MODALITA_APERTURA,NATURABASE) values ('4','D.I.A.','31','COMUNICAZIONE_NOTIFICA','scia');
Insert into NATURAENDOBASE (CODICENATURA,NATURA,BINARIODIPENDENZE,MODALITA_APERTURA,NATURABASE) values ('8','S.C.I.A.','31','COMUNICAZIONE_NOTIFICA','scia');
Insert into NATURAENDOBASE (CODICENATURA,NATURA,BINARIODIPENDENZE,MODALITA_APERTURA,NATURABASE) values ('16','Comunicazione','31','COMUNICAZIONE_NOTIFICA','comunicazione');



ALTER TABLE INVENTARIOPROCEDIMENTI DROP CONSTRAINT FK_INV_PROC_NATURA_ENDO;
ALTER TABLE INVENTARIOPROCEDIMENTI ADD CONSTRAINT FK_INV_PROC_NATURAENDOBASE FOREIGN KEY (CODICENATURA) REFERENCES NATURAENDOBASE(CODICENATURA);

