ALTER TABLE INVENTARIOPROCEDIMENTISOFTWARE ADD CODICEAMMINISTRAZIONE NUMBER(10,0);
ALTER TABLE INVENTARIOPROCEDIMENTISOFTWARE ADD CONSTRAINT FK_INVPROCSOFT_AMM FOREIGN KEY (IDCOMUNE, CODICEAMMINISTRAZIONE) REFERENCES AMMINISTRAZIONI(IDCOMUNE, CODICEAMMINISTRAZIONE);
ALTER TABLE INVENTARIOPROCEDIMENTISOFTWARE ADD ID NUMBER(6,0);
