ALTER TABLE INVENTARIOPROCEDIMENTISOFTWARE DROP PRIMARY KEY CASCADE;
ALTER TABLE INVENTARIOPROCEDIMENTISOFTWARE MODIFY ID NUMBER(6,0) NOT NULL;
ALTER TABLE INVENTARIOPROCEDIMENTISOFTWARE ADD CONSTRAINT INVENTARIOPROCEDIMENTISOFTW_PK PRIMARY KEY (IDCOMUNE, ID);