<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:sch="http://cnshandler.gruppoinit.it/schema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:tns="http://cnshandler.gruppoinit.it/ws" targetNamespace="http://cnshandler.gruppoinit.it/ws">
	<wsdl:types>
		<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://cnshandler.gruppoinit.it/schema" attributeFormDefault="unqualified"
			elementFormDefault="qualified" targetNamespace="http://cnshandler.gruppoinit.it/schema">
			<element name="GetUserDataRequest">
				<complexType>
					<sequence>
						<element name="ticket" type="string" minOccurs="1" />
					</sequence>
				</complexType>
			</element>
			<element name="GetUserDataResponse">
				<complexType>
					<sequence>
						<element name="nome" type="string" minOccurs="1" />
						<element name="cognome" type="string" minOccurs="1" />
						<element name="dataDiNascita" type="date" minOccurs="0" />
						<element name="codiceFiscale" type="string" minOccurs="1" />
						<element name="email" type="string" minOccurs="0" />
					</sequence>
				</complexType>
			</element>
		</schema>
	</wsdl:types>
	<wsdl:message name="GetUserDataRequest">
		<wsdl:part element="sch:GetUserDataRequest" name="GetUserDataRequest" />
	</wsdl:message>
	<wsdl:message name="GetUserDataResponse">
		<wsdl:part element="sch:GetUserDataResponse" name="GetUserDataResponse" />
	</wsdl:message>
	<wsdl:portType name="cnsHandler">
		<wsdl:operation name="GetUserData">
			<wsdl:input message="tns:GetUserDataRequest" name="GetUserDataRequest" />
			<wsdl:output message="tns:GetUserDataResponse" name="GetUserDataResponse" />
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="cnsHandlerSoap11" type="tns:cnsHandler">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="GetUserData">
			<soap:operation soapAction="" />
			<wsdl:input name="GetUserDataRequest">
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output name="GetUserDataResponse">
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="cnsHandlerService">
		<wsdl:port binding="tns:cnsHandlerSoap11" name="cnsHandlerSoap11">
			<soap:address location="http://devel9:8080/cnshandler/services" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>