<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<DockerfileContext>..\..</DockerfileContext>
		<DockerfileTag>vbg.area-riservata</DockerfileTag>
		<DockerImageLabels>BUILD_DATE=$([System.DateTime]::Now.ToString("yyyy.MM.dd"))</DockerImageLabels>
		<DockerfileBuildArguments>--build-arg PAT=$(PAT)</DockerfileBuildArguments>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<RequiresAspNetWebAssets>true</RequiresAspNetWebAssets>
	</PropertyGroup>

	<ItemGroup Condition="'$(FlavorToBuild)'=='Release'">
		<PackageReference Include="BuildWebCompiler2022" Version="1.14.10" />
	</ItemGroup>

	<ItemGroup>

		<PackageReference Include="CoreWCF.Http" Version="1.9.1" />
		<PackageReference Include="CoreWCF.Primitives" Version="1.9.1" />
		<PackageReference Include="Gelf4Net.UdpAppender" Version="1.0.3.1" />
		<PackageReference Include="log4net" Version="3.3.2" />
		<PackageReference Include="Microsoft.AspNetCore.Components.QuickGrid" Version="10.0.11" />
		<!--<PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.2" />-->
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.*" />
		<PackageReference Include="Microsoft.Extensions.Logging.Log4Net.AspNetCore" Version="10.0.0" />
		<PackageReference Include="Microsoft.Extensions.ServiceDiscovery" Version="10.8.0" />
		<PackageReference Include="Microsoft.Extensions.ServiceDiscovery.Dns" Version="10.8.0" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
		<PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="18.7.23">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Ninject" Version="3.3.6" />
		<PackageReference Include="Ninject.Web.Common" Version="3.3.2" />
		<PackageReference Include="VBG.BlazorComponentsLibrary" Version="10.0.4" />
		<PackageReference Include="VBG.DatiDinamici.Agid" Version="10.1.10" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Frontoffice\Init.Sigepro.FrontEnd.GestioneMovimenti\Init.Sigepro.FrontEnd.GestioneMovimenti.csproj" />
		<ProjectReference Include="..\Frontoffice\Init.Sigepro.FrontEnd.Infrastructure\Init.Sigepro.FrontEnd.Infrastructure.csproj" />
		<ProjectReference Include="..\PersonalLib2\PersonalLib2.csproj" />
		<ProjectReference Include="..\Init.Sigepro.FrontEnd.AppLogic.Pagamenti.NodoPagamenti\Init.Sigepro.FrontEnd.AppLogic.Pagamenti.NodoPagamenti.csproj" />
		<ProjectReference Include="..\Init.Sigepro.FrontEnd.CoreServices\Init.Sigepro.FrontEnd.CoreServices.csproj" />
		<ProjectReference Include="..\VBG.AppLogic.SSU\VBG.AppLogic.SSU.csproj" />
		<ProjectReference Include="..\VBG.DatiDinamici.Agid.HtmlRendering\VBG.DatiDinamici.Agid.HtmlRendering.csproj" />
		<ProjectReference Include="..\VBG.OtherControls\VBG.AreaRiservataCore.Controls.csproj" />
		<ProjectReference Include="..\VBG.Pagamenti.NodoPagamenti\VBG.Pagamenti.NodoPagamenti.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Include="compilerconfig.json" />
		<None Include="Pages\InserimentoIstanza\Ldp\AllegatoLdp.razor" />
		<None Include="wwwroot\css\font-awesome-4.6.3\fonts\fontawesome-webfont.svg" />
		<None Include="wwwroot\css\font-awesome-4.6.3\fonts\fontawesome-webfont.woff2" />
		<None Include="wwwroot\css\ionicons-2.0.1\.gitignore" />
		<None Include="wwwroot\css\ionicons-2.0.1\fonts\ionicons.svg" />
		<None Include="wwwroot\css\ionicons-2.0.1\LICENSE" />
		<None Include="wwwroot\css\ionicons-2.0.1\readme.md" />
	</ItemGroup>

	<ItemGroup>
		<None Update="moduli-fvg\compilazione\managed-data-mappings.nocopy.xml">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>


	<ItemGroup>
		<Folder Include="PraticheInUscita\" />
	</ItemGroup>

</Project>
