package it.gruppoinit.pal.gp.core.domain;

// Generated 22-set-2015 11.46.47 by Hibernate Tools 3.4.0.CR1
import it.gruppoinit.pal.gp.core.helper.PkIdGenerator;
import it.gruppoinit.pal.gp.gestionecalendari.web.command.FiereMostreMerceologieComparator;
import it.gruppoinit.pal.gp.gestionecalendari.web.command.FiereMostrePeriodiComparator;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * FiereMostre generated by hbm2java
 */
@Entity
@Table(name = "FIERE_MOSTRE")
public class FiereMostre implements java.io.Serializable {

    private static final long serialVersionUID = -1825513021586405700L;
    private PkId id;
    private Comuni comune;
    private Comuni comuneSvolgimento;
    private String denominazione;
    private String idIstanza;
    private String numeroIstanza;
    private Date dataIstanza;
    private String numProtocolloIstanza;
    private String numAutorizzazione;
    private Date dataAutorizzazione;
    private String luogoSvolgimento;
    private String organizzatore;
    private String classificazione;
    private String qualifica;
    private Date dataInserimento;
    private String tipologia;
    private Set<FiereMostrePeriodi> fiereMostrePeriodis = new HashSet<FiereMostrePeriodi>(0);
    private Set<FiereMostreMerceologie> fiereMostreMerceologies = new HashSet<FiereMostreMerceologie>(0);
    private List<FiereMostrePeriodi> fiereMostrePeriodisTransient = new ArrayList<FiereMostrePeriodi>(0);
    private List<FiereMostreMerceologie> fiereMostreMerceologiesTransient = new ArrayList<FiereMostreMerceologie>(0);

    public FiereMostre() {

	this.id = new PkId();
	this.comune = new Comuni();
	this.comuneSvolgimento = new Comuni();
	this.dataInserimento = new Date();
    }

    @EmbeddedId
    @GenericGenerator(name = "pkGenerator", strategy = "it.gruppoinit.pal.gp.core.helper.PkIdGenerator", parameters = {
	    @Parameter(name = PkIdGenerator.CONFIG_PREFER_SEGMENT_PER_ENTITY, value = "true"),
	    @Parameter(name = PkIdGenerator.TABLE_PARAM, value = "SEQUENCETABLE"),
	    @Parameter(name = PkIdGenerator.VALUE_COLUMN_PARAM, value = "CURRVAL"),
	    @Parameter(name = PkIdGenerator.SEGMENT_COLUMN_PARAM, value = "SEQUENCENAME"),
	    @Parameter(name = PkIdGenerator.SEGMENT_VALUE_PARAM, value = "FIERE_MOSTRE.ID") })
    @GeneratedValue(generator = "pkGenerator")
    @AttributeOverrides({ @AttributeOverride(name = "idcomune", column = @Column(name = "IDCOMUNE", nullable = false, length = 6)),
	    @AttributeOverride(name = "codice", column = @Column(name = "ID", nullable = false, precision = 4, scale = 0)) })
    public PkId getId() {

	return this.id;
    }

    public void setId(PkId id) {

	this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CODICECOMUNE")
    public Comuni getComune() {

	return this.comune;
    }

    public void setComune(Comuni comune) {

	this.comune = comune;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CODICECOMUNE_SVOLGIMENTO")
    public Comuni getComuneSvolgimento() {

	return this.comuneSvolgimento;
    }

    public void setComuneSvolgimento(Comuni comuneSvolgimento) {

	this.comuneSvolgimento = comuneSvolgimento;
    }

    @Column(name = "DENOMINAZIONE", length = 1000)
    public String getDenominazione() {

	return this.denominazione;
    }

    public void setDenominazione(String denominazione) {

	this.denominazione = denominazione;
    }

    @Column(name = "ID_ISTANZA", length = 200)
    public String getIdIstanza() {

	return idIstanza;
    }

    public void setIdIstanza(String idIstanza) {

	this.idIstanza = idIstanza;
    }

    @Column(name = "NUMEROISTANZA", length = 60)
    public String getNumeroIstanza() {

	return numeroIstanza;
    }

    public void setNumeroIstanza(String numeroIstanza) {

	this.numeroIstanza = numeroIstanza;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "DATAISTANZA", length = 7)
    public Date getDataIstanza() {

	return dataIstanza;
    }

    public void setDataIstanza(Date dataIstanza) {

	this.dataIstanza = dataIstanza;
    }

    @Column(name = "NUM_PROTOCOLLOISTANZA", length = 30)
    public String getNumProtocolloIstanza() {

	return numProtocolloIstanza;
    }

    public void setNumProtocolloIstanza(String numProtocolloIstanza) {

	this.numProtocolloIstanza = numProtocolloIstanza;
    }

    @Column(name = "NUM_AUTORIZZAZIONE", length = 30)
    public String getNumAutorizzazione() {

	return numAutorizzazione;
    }

    public void setNumAutorizzazione(String numAutorizzazione) {

	this.numAutorizzazione = numAutorizzazione;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "DATA_AUTORIZZAZIONE", length = 7)
    public Date getDataAutorizzazione() {

	return dataAutorizzazione;
    }

    public void setDataAutorizzazione(Date dataAutorizzazione) {

	this.dataAutorizzazione = dataAutorizzazione;
    }

    @Column(name = "LUOGO_SVOLGIMENTO", length = 800)
    public String getLuogoSvolgimento() {

	return this.luogoSvolgimento;
    }

    public void setLuogoSvolgimento(String luogoSvolgimento) {

	this.luogoSvolgimento = luogoSvolgimento;
    }

    @Column(name = "ORGANIZZATORE", length = 400)
    public String getOrganizzatore() {

	return this.organizzatore;
    }

    public void setOrganizzatore(String organizzatore) {

	this.organizzatore = organizzatore;
    }

    @Column(name = "CLASSIFICAZIONE", length = 400)
    public String getClassificazione() {

	return this.classificazione;
    }

    public void setClassificazione(String classificazione) {

	this.classificazione = classificazione;
    }

    @Column(name = "QUALIFICA", length = 400)
    public String getQualifica() {

	return this.qualifica;
    }

    public void setQualifica(String qualifica) {

	this.qualifica = qualifica;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "DATA_INSERIMENTO", length = 7)
    public Date getDataInserimento() {

	return dataInserimento;
    }

    public void setDataInserimento(Date dataInserimento) {

	this.dataInserimento = dataInserimento;
    }

    @Column(name = "TIPOLOGIA", length = 50)
    public String getTipologia() {

	return tipologia;
    }

    public void setTipologia(String tipologia) {

	this.tipologia = tipologia;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "fiereMostre", cascade = CascadeType.REMOVE)
    public Set<FiereMostrePeriodi> getFiereMostrePeriodis() {

	return this.fiereMostrePeriodis;
    }

    public void setFiereMostrePeriodis(Set<FiereMostrePeriodi> fiereMostrePeriodis) {

	this.fiereMostrePeriodis = fiereMostrePeriodis;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "fiereMostre", cascade = CascadeType.REMOVE)
    public Set<FiereMostreMerceologie> getFiereMostreMerceologies() {

	return this.fiereMostreMerceologies;
    }

    public void setFiereMostreMerceologies(Set<FiereMostreMerceologie> fiereMostreMerceologies) {

	this.fiereMostreMerceologies = fiereMostreMerceologies;
    }

    @Transient
    public List<FiereMostrePeriodi> getFiereMostrePeriodisTransient() {

	fiereMostrePeriodisTransient.addAll(fiereMostrePeriodis);
	Collections.sort(fiereMostrePeriodisTransient, new FiereMostrePeriodiComparator());
	return fiereMostrePeriodisTransient;
    }

    @Transient
    public List<FiereMostreMerceologie> getFiereMostreMerceologiesTransient() {

	fiereMostreMerceologiesTransient.addAll(fiereMostreMerceologies);
	Collections.sort(fiereMostreMerceologiesTransient, new FiereMostreMerceologieComparator());
	return fiereMostreMerceologiesTransient;
    }
}
